ParadiseSS13/Paradise

code/controllers/subsystem/tickets/tickets.dm
Fixes mentorhelp issue with autoresolve
🆑 
fix: Fixes an issue where autoresolve was appearing in mentorhelps to mentors
/ 🆑
=> Fixes mentorhelp issue with autoreply

code/game/mecha/mecha_topic.dm
Mech ID upload panels now come with [add all] and [delete all] options
port: https://github.com/vgstation-coders/vgstation13/pull/23733
:cl:Evankhell
add: Mech ID upload panels now come with [add all] and [delete all] options
/:cl:
=> Mech id upload buttons

code/modules/clothing/gloves/color.dm, code/modules/hydroponics/grown/nettle.dm
PR now just contains a slight clean-up of shitty old format.
I also fixed some formatting in the gloves file that I noticed while there, bringing it in line with our code standards.
Just cleans up some confusing formatting, makes searching for those gloves easier
:cl:
tweak: Just slight gloves refactor, shouldn't impact anything in game.
/:cl:
=> minor glove refactor

code/game/machinery/doors/brigdoors.dm
Fixes #12349
makes doors less psychic
less bugs is good
:cl:
fix: fixed brig door timers from announcing admin names when stopped via admin powers.
/:cl:
=> less spooky doors

code/game/mecha/mecha.dm
mechs now start with a high-capacity power cell+ instead basic power cell. The initial charge is the same
:cl:
tweak: mechs now start with a high-capacity power cell+
/:cl:
=> mechs now start with a high-capacity power cell+

_maps/map_files/cyberiad/cyberiad.dmm
change all high power cells  with a 15,000 max charge with high power cell+ on the map
:cl:Evankhell
tweak: replace high power cells with high power cell+
/:cl:
=> replace high power cells with high power cell+

code/modules/mob/living/simple_animal/bot/mulebot.dm
Stops SSD people from being run over by MULEbots.
Because they usually just get an admin rejuvenation anyway, may as well cut out the need for admin intervention.
:cl:
tweak: MULEbots no longer cause any damage when running over SSDs.
/:cl:
=> Stops MULEs from running over SSDs

.github/CONTRIBUTING.md
As per title. Add instructions about bitflags and that we prefer bitshifts be used to represent them, like TG, for readability reason.
Also add that we now prefer squash merge to keep commit history clean for git blame and other purpose.
Better code maintainability
=> Add bitshift and squash merge instructions

_maps/map_files/RandomZLevels/beach.dmm, code/game/objects/structures/ladders.dm
This PR fixes #12482
Someone var-edited normal sand with the name 'rough sand', set density to 1 and tried to give it a different icon that, as far as I can tell, doesn't exist. Since there was already a dense version of the sand tile I simply replaced the rough sand with the dense sand tile. If someone knows where the actual 'rough sand' icons are that were intended for this, lemme know.
things not being bugged is good
:cl:
fix: fixed visual issues in beach gateway
/:cl:
=> Fixes beach visual bugs

code/modules/surgery/organs/augments_internal.dm
Small rewrite of reviver code to be new crit friendly and a bit cleaner
reviver implant was literally useless because you didn't go unconscious in new crit for long, now that most races are on new crit it makes more sense to tweak the reviver implant so it's useful to them
:cl:
tweak: reviver implant now heals even when you're conscious
/:cl:
=> change reviver to be new-crit friendly

code/game/world.dm
Fixes #12406
The database will now do a proper disconnect instead of having the connection forcibly closed
Stops generating false-logs for issues which arent even big issues
:cl:
fix: SQL now properly disconnects at end round
/:cl:
=> Fixes DB disconnection issue

code/game/objects/items/devices/scanners.dm, code/game/objects/items/devices/traitordevices.dm, code/modules/pda/utilities.dm
Health analyzers now use `to_chat` instead of `user.show_message`
Also PDA heatlh scanners should be more consistent with health analyzer scans instead of being their own snowflaked thing.
tweak: PDA health scans should be more in line with regular health analyzer scans
/:cl:
=> Health Analyzer Refactor

.github/CONTRIBUTING.md
This adds instructions on our preference on initialize() over new() (From TG), no implicit var in proc (original), addtimer() (Also original but seems to be not in tg's contributing.md for some reason), and one more sentence to the section on hacky code to explain how to bugfix properly instead of bandaiding.
Code quality
No CL
=> Initialize(), Implicit var/, Addtimer() and Hacky Code update to Contributing.md

code/game/objects/structures/displaycase.dm, goon/code/datums/browserOutput.dm
Changes the access requirements of the Captain's Display Case back to Captain level access from CC access 
:cl:
tweak: Captains can access their display case again
/ :cl:
=> Gives Captains access to unlock their display case again

code/modules/food_and_drinks/kitchen_machinery/monkeyrecycler.dm, code/modules/mob/living/simple_animal/slime/slime.dm, code/modules/research/xenobiology/xenobio_camera.dm
Ports my own PR from TG.
Makes Xenobio equipment and slimes GC better
tweak: performance improvements for xenobio stuff
/:cl:
=> Makes Xenobio Related Things GC Better

code/modules/telesci/telepad.dm
fixes https://github.com/ParadiseSS13/Paradise/issues/12550
fix: Fixes wrench attacking telepads
/:cl:
=> Fixes Telepad Double Attack

code/LINDA/LINDA_turf_tile.dm, code/__DEFINES/atmospherics.dm, code/controllers/subsystem/air.dm, code/datums/gas_mixture.dm
Reverts ParadiseSS13/Paradise#12566
Atmos is broken currently. Rooms getting syphoned from nothing. Rooms not refilling. Etc
=> Revert "Makes LINDA Aggressive"

code/modules/telesci/telepad.dm
fixes: https://github.com/ParadiseSS13/Paradise/issues/12585
fix: Fixes atmos pipe unwrenching
/:cl:
=> Fixes Atmos Pipe Deconstruction

code/LINDA/LINDA_turf_tile.dm
Inb4 this is the source of the problem in the previous PR.
This should fix planetary atmos not functioning properly
fix: Fixes planetary atmos not correctly happening
/:cl:
=> Fixes Planetary Atmos

code/game/turfs/simulated/floor/indestructible.dm, code/game/turfs/simulated/floor/misc_floor.dm
Fixes atmos in the Hierophant's arena being oddly hot.
fixes: https://github.com/ParadiseSS13/Paradise/issues/12597
fix: Fixes Hierophant arena atmos
/:cl:
=> Fixes Hierophant Atmos

code/game/objects/structures/window.dm, code/modules/mining/equipment/survival_pod.dm
Dunno how I feel about the buff if it's good or bad--so I'm going to revert it for now
tweak: windows are easier to break
/:cl:
=> Nerfs Glass Armor

code/game/mecha/mecha.dm
removes a duplicate definition in mecha code, those values are already defined in __defines/mecha.dm
my VScode extension doesn't complain about duplicate definitions anymore.
:cl:
del: duplicate mecha definitions
/:cl:
=> remove duplicate definition in mecha code

code/game/gamemodes/blob/blobs/blob_mobs.dm
fixes #12724
bugs are bad
:cl:
fix: blobbernaut vision blur now clears as intended.
/:cl:
=> Fixes blobbernaut vision never clearing

code/controllers/subsystem/tickets/tickets.dm
fixes #12750
The simplest way to fix this seems to be to just create the actual list when the ticket system is created. The alternative was checking for the existence of the list each time we add a new ticket.
bugs are bad
:cl:
fix: fixed a bug preventing ticket system from working under some circumstances.
/:cl:
=> fixes ticket system bug

code/game/gamemodes/autotraitor/autotraitor.dm, code/game/gamemodes/traitor/traitor.dm
Reverts some dumb changes I suggested in this PR: #12740. Which resulted in captains becoming traitors, or players getting thrown into the lobby and still becoming traitors, even though they had no body. This is what I get for not testing and just assuming.
:cl:
fix: Reverts some terrible changes that are causing some bugs with traitors
/:cl:
=> Fixes some unlisted traitor issues from a recent merge

code/modules/events/sentience.dm
Removes no-op function calls to `max()` in `code/modules/events/sentience.dm`
No change to game play, this is simple code maintenance.
N/A
:cl:
fix: Sentience no longer needs to be reassured that it's the biggest.
/:cl:
=> Clean up for changes in PR #10861

code/modules/mob/living/simple_animal/friendly/dog.dm
Very simple fix. I'm assuming this was a mistake in the corgi and dog refactor (#12206). As the way its coded right now means that they can only bark while they're incapacitated.
Woof!
:cl:
fix: Restores dog mob's ability to perform audible emotes like barking
/:cl:
=> Restores corgi's and other dog's ability to perform audible emotes like barking

goon/browserassets/js/browserOutput.js, goon/code/datums/browserOutput.dm
Port of:  https://github.com/tgstation/tgstation/pull/48524
:cl: Kyep
fix: Ported fix for excessive topic calls in goonchat.
/:cl:
=> Add a spam limiter to the goonchat topic calls

.travis.yml, code/__DEFINES/typeids.dm, code/__HELPERS/text.dm, code/game/machinery/doors/brigdoors.dm, code/game/machinery/supply_display.dm, code/game/objects/structures/musician.dm, code/modules/admin/DB ban/functions.dm, code/modules/admin/topic.dm, code/modules/admin/verbs/modifyvariables.dm, code/modules/client/preference/preferences.dm, code/modules/clothing/clothing.dm, code/modules/flufftext/TextFilters.dm, code/modules/mob/hear_say.dm, code/modules/mob/living/carbon/human/examine.dm, code/modules/mob/living/silicon/pai/pai.dm, code/modules/mob/living/silicon/robot/examine.dm, code/modules/mob/mob.dm, code/modules/mob/mob_helpers.dm, code/modules/shuttle/supply.dm
Updates Travis to use BYOND 513 when compiling on Github.
Based on: https://github.com/ParadiseSS13/Paradise/pull/9923
Replaces all lentext() with length() in the codebase to prevent compile warnings.
And: https://github.com/tgstation/tgstation/pull/47585
Alerts us if code won't work in 513.
No CL as this doesn't change anything in-game, this is purely a github thing.
=> Updates Travis to 513, Makes codebase compile on 513 without warnings

code/modules/clothing/spacesuits/plasmamen.dm
Makes the Veil ability of Slings (and others) extinguish plasmamen helmets
It is an oversight
:cl:
fix: Slings veil and such now extinguishes plasmamens helmets
/:cl:
=> Makes Veil (and other light extinguishing ways) extinguish plasmamen helmets

code/ATMOSPHERICS/atmospherics.dm, code/controllers/subsystem/idlenpcpool.dm, code/controllers/subsystem/npcpool.dm, code/game/gamemodes/blob/overmind.dm, code/game/gamemodes/changeling/powers/augmented_eyesight.dm, code/game/objects/structures/grille.dm, code/modules/flufftext/Hallucination.dm, code/modules/surgery/organs/augments_eyes.dm, code/modules/surgery/organs/eyes.dm, code/modules/surgery/organs/organ_external.dm
Fixes
Fixes simple_mobs being able to nuzzle grilles to death at hyper speed
fixes #12892
Less runtimes more good
:cl:
fix: Fixes a runtime in npcpool.dm
fix: Fixes a runtime in atmospherics.dm
fix: Fixes a runtime in overmind.dm
fix: Fixes a runtime in Hallucinations.dm
fix: Fixes a runtime in augments_eyes.dm due to cling eyes not having color
fix: Losing an arm due to overal damage now won't cause a runtime in the hand attached to the arm
fix: Nuzzling a grille now won't kill it as simple animal
fix: Hitting a grille now won't cause a runtime as simple animal
/:cl:
=> Fixes a few runtimes 

code/__HELPERS/unsorted.dm, code/game/machinery/computer/ai_core.dm, code/game/machinery/doors/airlock.dm
Title
- Fixes #12980
- Fixes #12985
:cl:
fix: AI cores can be constructed once more
fix: Things other than welders count as hot once more
fix: You can weld shielding off airlock panels again
/:cl:
=> Fixes some bugs introduced via tool refactor

code/game/objects/items/weapons/implants/implant_traitor.dm
Makes the text you get when being mindslaved bigger
Makes it easier to spot for people
New:
Old:
:cl:
tweak: The text when you get mindslaved is bigger now
/:cl:
=> Makes the mindslave message bigger

code/modules/client/preference/loadout/loadout_racial.dm
Fixes a small, inconsequential error from a previous PR I made, which showed up in dream daemon but otherwise had no effect.
Doesn't make an unused parent object anymore.
:cl:
fix: Removes an ugly error that gets thrown up on server initialization.
/:cl:
=> Racial Loadout Items Pathway Fix

code/game/machinery/doors/airlock.dm, code/game/machinery/doors/door.dm, code/game/machinery/doors/windowdoor.dm, code/game/mecha/equipment/tools/medical_tools.dm, code/game/turfs/simulated/walls.dm, code/game/turfs/simulated/walls_reinforced.dm, code/modules/reagents/chemistry/reagents/pyrotechnic.dm, code/modules/recycling/disposal.dm, code/modules/recycling/sortingmachinery.dm
Title
Just some moar bugfixing
Fixes #13035
Fixes #13023
Fixes #12997
Fixes #11960
:cl:
fix: You can set fire to thermite with a welder again
fix: Setting light to thermite on walls will no longer leave a black box behind
fix: You can disassemble delivery chutes again
fix: Disassembling disposals bins no longer turns them into chutes
fix: You can open airlocks with fireaxes again
/:cl:
=> Some bugfixes

code/controllers/subsystem/chat.dm
Turns on the chat subsystem. 
Originally ported here: #11921. However it was left with the flag `SS_NO_INIT` which mean's it never runs. TG corrected this same issue in: https://github.com/tgstation/tgstation/pull/47653.
:cl:
fix: Makes the chat subsystem actually initialize and run properly
/:cl:
=> Turns on the chat subsystem

code/modules/mob/living/carbon/human/species/plasmaman.dm
Plasma dust now has the same effect as plasma proper, healing plasmamen.
I've seen several plasmaman players complaining about plasma dust being toxic to them, despite them being literally made of plasma.
:cl: Superhats
tweak: Plasma Dust now heals Plasmamen
/:cl:
=> Plasma dust now heals plasmamen

code/modules/hydroponics/grown/tomato.dm
Adds a log for killer tomatoes being released.
Makes it easier for admins to track people releasing dangerous killer tomatoes.
:cl:
add: Adds logs for killer tomatoes being released.
/:cl:
=> Adds a log for admins

code/modules/customitems/item_defines.dm
As requested by greey's player and approved by Kyet
Will likely require a database change, not sure how that's setup
:cl:
tweak: change greey's fluff dufflebag to a backpack
/:cl:
=> Change greey's fluff dufflebag to a backpack

code/modules/reagents/chemistry/reagents/toxins.dm
=> Rename TOUCH to REAGENT_TOUCH fix

code/ATMOSPHERICS/datum_icon_manager.dm, code/__DEFINES/colors.dm, code/_globalvars/misc.dm
Fixes the issue of pipes not rendering
We should be able to see pipes
fix: Pipes render now
/:cl:
=> Fixes pipes not rendering

code/game/machinery/computer/cloning.dm
Clarifies cloning scan messages to make them more clear for new players.
Easier to understand if you should keep trying to clone someone or not.  Makes it clear why someone can't be cloned if they can't be.
:cl:
tweak: adjusted scan messages for cloning
/:cl:
=> Update cloning scan messages

code/modules/reagents/chemistry/reagents/alcohol.dm
As much as I like the idea of having alcohol addiction as a form of alcoholism, I don't think it's really worth it, in this case--especially since alcohol's combat advantage is virtually non-existent.
Even if  addiction is tweaked to ignore subtypes, I'm still not sure having alcohol cause addiction is worth it---so I'm opting to just can it, completely.
Way back in the day (2015), alcohol was addictive then, as well---it was also removed back then because it was just too annoying, most of the time. Seems it's still the case.
del: Alcohol no longer has an addiction
/:cl:
=> Removes Alcohol Addiction

code/game/turfs/simulated.dm, code/game/turfs/simulated/floor/mineral.dm, code/game/turfs/simulated/floor/misc_floor.dm, code/game/turfs/simulated/floor/plating.dm, code/game/turfs/turf.dm, code/modules/mob/living/simple_animal/hostile/floorcluwne.dm
Fixes: #12607
It's a bug
:cl:
fix: Makes floor cluwnes slippery tiles dissapear after a certain time now. As intended
/:cl:
=> Makes floor cluwnes slippery tiles not stay there till the end of times

code/modules/hydroponics/hydroponics.dm
Yes I know this is webeditor heresey. But **WE THINK** this comment is what got TG banned from github as well hippie.
https://github.com/tgstation/tgstation
Speedmerge recommended.
=> Speedpurge Bad Comments

code/modules/clothing/spacesuits/plasmamen.dm
There are multiple spelling and grammar errors in the descriptions for envirohelmets. This PR is meant to correct the errors and make the descriptions somewhat easier to read.
Proper spelling is important for immersion, and there's no such thing as an "envriohelmet" or "cheif medical officer".
:cl:
spellcheck: fix spelling & grammar errors throughout the descriptions of plasmamen's envirosuits. 
/:cl:
=> Correct spelling and grammar in envirohelmet descriptions

code/game/machinery/camera/camera.dm, code/game/objects/items/tools/welder.dm, code/game/turfs/simulated/floor/plating.dm, code/game/turfs/simulated/walls.dm, code/game/turfs/simulated/walls_misc.dm, code/game/turfs/turf.dm, code/modules/mob/living/carbon/carbon.dm
Fixes a runtime when you create a camera, when you ventcrawl but misclick or something weird and when you leave your integrated tool burning in your implant
Runtimes B GONE
Fixes:
```
[2020-03-30T18:31:01] Runtime in welder.dm,53: Cannot execute null.hotspot expose().
[2020-03-30T18:31:01]   proc name: process (/obj/item/weldingtool/process)
[2020-03-30T18:31:01]   src: the integrated welding tool (/obj/item/weldingtool/largetank/cyborg)
[2020-03-30T18:31:01]   src.loc: the integrated toolset implant (/obj/item/organ/internal/cyberimp/arm/toolset)
[2020-03-30T18:31:01]   call stack:
[2020-03-30T18:31:01]   the integrated welding tool (/obj/item/weldingtool/largetank/cyborg): process(20)
[2020-03-30T18:31:01]   Objects (/datum/controller/subsystem/processing/obj): fire(0) …
```
=> Fixes a few runtimes

code/game/gamemodes/miniantags/slaughter/bloodcrawl.dm
Knew about this a long time ago---but hardly anyone abused it.
Seeing it abused a lot now though--shame on you guys.
fix: Fixes being able to determine slaughter demon location with medical devices
/:cl:
=> Slaughter Demon Exploit Fix

code/__HELPERS/icons.dm
Adds a proc to calculate the perceived brightness of a color
getLuminance
:cl:
add:Adds getLuminance() helper proc
/ :cl:
=> Adds a helper proc to calculate luminance

code/modules/flufftext/Hallucination.dm, code/modules/mob/living/simple_animal/simple_animal.dm, code/modules/modular_computers/computers/item/laptop.dm
Fixes being able to put any item on a corgi's collar slot.
Fixes a runtime when laptops spawn
Fixes a runtime due to some hallucinations calling playsound_local to GLOBAL_PROC instead of the target.
Less runtimes more funtimes
fixes:
```
[2020-04-19T19:30:16] Runtime in simple_animal.dm,607: undefined variable /obj/item/card/id/var/tagname
proc name: add collar (/mob/living/simple_animal/proc/add_collar)
usr: NAME (CKEY) (/mob/living/carbon/human)
usr.loc: The floor (97,115,1) (/turf/simulated/floor/plasteel)
src: Sergeant Butch (/mob/living/simple_animal/pet/dog/corgi)
src.loc: the floor (98,115,1) (/turf/simulated/floor/plasteel)
call stack:
Sergeant Butch (/mob/living/simple_animal/pet/dog/corgi): add collar(Butch\'s ID Card (Civilian) (/obj/item/card/id), NAME …
```
=> Fixes the collar slot accepting everything + 2 other runtimes

code/modules/projectiles/guns/throw/crossbow.dm
Does as the title says. Also small code format touch-ups, more early returns and such
Bugs bad.
:cl:
fix: Fixes the crossbow's cell being un-removable with a screwdriver
/:cl:
=> Fixes the crossbow's cell being un-removable with a screwdriver

code/__DEFINES/role_preferences.dm, code/__HELPERS/names.dm, code/game/gamemodes/changeling/powers/hivemind.dm, code/game/gamemodes/devil/devil.dm, code/game/gamemodes/miniantags/bot_swarm/swarmer_event.dm, code/game/objects/items/stacks/sheets/mineral.dm, code/modules/awaymissions/gateway.dm, code/modules/client/preference/preferences.dm, code/modules/client/preference/preferences_mysql.dm, tools/travis/check_grep.sh
During the `GLOB`ening of #13152, I forgot to enable the travis check for this, as well as forgetting some of the vars. Dont hurt me.
GLOBs should be managed
tweak: ALL globals are now managed
/:cl:
=> Fixes part of Travis I forgot about

code/modules/clothing/suits/miscellaneous.dm
Fixes the missionary staff being unable to charge (gain faith) properly. It properly works while its in the robe wearer's hands, or anyone else's hands, as long as the staff is within 3 tiles.
Fixes: #13355
:cl:
fix: Fixes the missionary staff being unable to charge properly
/:cl:
=> Fixes the missionary staff being unable to charge properly

code/modules/mob/mob.dm
Fixes the spam that not having perms to view the panel causes.
@AffectedArc07 Aghhhhh
fix: Fixes MC status viewing spam
/:cl:
=> Fixes MC perms spam

code/modules/reagents/chemistry/reagents/medicine.dm
medicines are now properly smoke-able 
I forgot to add sate_addiction to medicines version of on_mob_life in https://github.com/ParadiseSS13/Paradise/pull/13181#issue-392258327, now medicine should sate addiction when metabolised incrementally 
:cl:
fix: medicine now properly sates addiction with incremental dosages too
/:cl:
=> Medicines now properly sate addiction when smoked.

code/modules/clothing/head/soft_caps.dm
Fixes a misspelling in the corporate hat description.
It fixes a misspelling.
:cl: 
spellcheck: fixed a type with the corporate cap descripton.
:cl:
=> Fixed description for corporate cap

code/game/objects/items/devices/flash.dm, code/modules/reagents/chemistry/holder.dm
* Fixes a grammar issue and typo issue in two files
* Code quality is good for developers
* Grammatical messages are good for players
:cl:
spellcheck: Fixed grammar in the message sent when you get flashed
/:cl:
=> Grammar and typo fixes

code/datums/diseases/advance/symptoms/sensory.dm
Fixes the duplicate "Your eyes feel great." message by changing the second one to "Your ears feel great."
Small change just to improve the virus symptom messages.
:cl:
spellcheck: Changed one of the "Your eyes feel great." to "Your ears feel great."
/:cl:
=> Your ears feel great

code/controllers/master.dm, code/game/world.dm
uhhh this not working is kinda bad.
Dunno why this caused it--it really shouldn't, but no time to diagnose/bugfix.
fix: Fixes admin logs
/:cl:
=> Fixes Admin Logs

code/controllers/subsystem/changelog.dm
Fixes a small runtime with the changelog system as well as making it so opened links now open in your real browser instead of inside the CL window
fix: Changelog system will no longer runtime on roundstart if a player disconnects
fix: Links in the changelog view will now open in your default browser instead of inside BYOND itself
/:cl:
=> CL Fixes Round 1

code/datums/mind.dm, code/game/objects/items/weapons/implants/implant_traitor.dm, code/modules/mob/living/living_defines.dm, code/modules/mob/mob_defines.dm
Backend change only, no CL.
None of these did anything, or were checked anywhere else in the codebase.
=> Removes a bunch of unused vars

code/__DEFINES/lighting.dm, code/__HELPERS/game.dm, code/modules/lighting/lighting_source.dm, code/modules/lighting/lighting_turf.dm
port of: https://github.com/tgstation/tgstation/pull/51004
Improves the performance of lighting corner updates by ~16%.
tweak: lighting. performance. It's a thing people.
/:cl:
=> Lighting Performance Improvement

config/example/dbconfig.txt
Fixes forgotten version change in dbconfig example file.
Game won't run with example files otherwise, and it's not immediately obvious this is the missing bit.
:cl:
fix: db version in dbconfig example file
/:cl:
=> Fixed db version in dbconfig example file

code/game/gamemodes/wizard/wizloadouts.dm
* Fixes the spelling of the Disintegrate spell in two locations
* Correct spelling is nice
:cl:
spellcheck: fixed the spelling of the Disintegrate spell
/:cl:
=> Fix spelling of Disintegrate

code/modules/mob/new_player/sprite_accessories/ipc/ipc_face.dm
Freaking test your PRs please--a 3 line PR has no excuse not to be tested.
Fixes HAVING A FREAKING SCREEN GLUED TO OUR FREAKING FACE AS NON-IPC.
Fix: Fixes friggin' screens glued to our gosh darned faces
/:cl:
=> Fixes Having a Frigging Monitor Glued to Your Face

code/datums/periodic_news.dm
Adds more explicit paths in the `code/datums/periodic_news.dm` file making it cleaner.
Cleaner code and also makes it easier to work with as well as find.
=> Makes explicit paths in the code/datums/periodic_news.dm file

code/controllers/subsystem/statistics.dm, code/controllers/subsystem/ticker.dm, code/defines/procs/statistics.dm, paradise.dme
This PR cleans up two awful pieces of code from the ticker. A 2 **hour** long `spawn()` and a `while(1)` infinite loop. These have been replaced with much better solutions.
Code should not be shitcode
tweak: Optimised part of the Ticker Subsystem code
/:cl:
=> Cleans up some awful code from the ticker

code/modules/karma/karma.dm
Adds current karma amount to karma menu, and also updates karma menu to show already unlocked jobs and species. This does NOT affect awarding karma, it is read-only usability changes.
The karma menu was implemented in 2013 and had not been touched up much since. It is due to be brought more in line with the usability of other UI menus.
:cl:
fix: karma menu not showing current karma
fix: karma menu not showing unlocked jobs/species
/:cl:
=> Karma menu update

code/game/mecha/combat/gygax.dm
Reworks and heavily improves the Dark Gygax exosuit - matches the updates made by TG to the mech in https://github.com/tgstation/tgstation/pull/49131 so credit for the improvements goes to them.
The Dark Gygax is currently very weak for the price paid. The carbine rifle bullets deal just 5 damage per shot, the flashbang launcher may not always be effective depending on the target and while the teleporter can be effective, it's hard to use and with the current weapon loadout there's not much damage you can really do with it. Most times I see this mech used, it dies very quickly compared to the Mauler since it cannot handle pretty much anyone with a shotgun.
This PR reworks the mech's equipment to make better use of its speed and make the mech easier to use in general, as well as give it …
=> Improves / Reworks Dark Gygax for Nuke Ops

code/game/dna/genes/disabilities.dm, code/game/dna/genes/vg_powers.dm
Fixes epilepsy having epilepsy. Who knew it was possible?
Also fixes morph having the same issue
fixes: https://github.com/ParadiseSS13/Paradise/issues/13559
fix: Fixes epilepsy having epilepsy. Who knew it was possible?
/:cl:
=> Fixes Epilepsy Having Epilepsy

code/game/gamemodes/vampire/vampire.dm
Fixes vamp vision not updating without taking off/putting on glasses.
fix: Fixes vampire vision not updating when you get the proper blood level
/:cl:
=> Fixes Vampire Vision

code/modules/clothing/shoes/colour.dm
Fixes being able to upgrade cablecuffs to regular cuffs.
fixes: https://github.com/ParadiseSS13/Paradise/issues/13567
fix: Fixes being able to upgrade cablecuffs to regular cuffs with shackled shoes
/:cl:
=> Fixes Shoe Shackle Handcuff Upgrading

code/controllers/subsystem.dm
Fixes a glaring issue we have had since the stonedMC was first implemented
We are not coderbus
del: Removed coderbus
/:cl:
=> Gamebreaking bug fix immediately

code/modules/shuttle/supply.dm
Patches an exploit that deletes ghosts allowing you to ....do things you shouldn't
fix: patches a ghost exploit
/:cl:
=> [s] Fixes Ghost Exploit

code/game/machinery/doors/brigdoors.dm
Fixes a runtime with brig timers
Bugfixes are always good
:cl:
fix: Brig timer runtime fix
/:cl:
=> Brigtimer runtime fix

code/datums/components/README.md, code/game/objects/items/toys.dm
Fixes incorrect file path for the components readme/documentation.
Also fixes a spelling issue with grumpy fox plushie.
=> Fixes a Couple of Components Things

code/game/objects/items/shooting_range.dm
Ports the way TG handles targets. I've changed some things up that didn't make much sense. I'll list them in the comments.
Also did a small refactor
Fixes #11142
Fixes #11037
Alternative to #12928
Won't crash clients now I hope
:cl:
fix: Fixes the armory crash
/:cl:
=> Ports TGs way of handling bullet_act on shooting targets. Should fix the armory crash

code/modules/food_and_drinks/kitchen_machinery/smartfridge.dm
Fixes hacking a smart fridge not doing anything
fix: Fixes being unable to disable ID scan on a smartfridge
/:cl:
=> Fixes Unhackable Smartfridges

code/modules/reagents/chemistry/reagents/alcohol.dm
Resolves a few reagent runtimes.
=> Resolves some Reagent Runtimes

code/controllers/subsystem/lighting.dm, code/game/atoms_movable.dm, code/game/turfs/turf.dm, code/modules/lighting/lighting_corner.dm, code/modules/lighting/lighting_object.dm, code/modules/lighting/lighting_source.dm, code/modules/lighting/lighting_turf.dm, code/modules/mob/camera/camera.dm, code/modules/mob/dead/dead.dm, code/modules/shuttle/on_move.dm
Ports some of TG's optimizations to lighting:
https://github.com/tgstation/tgstation/pull/45491
https://github.com/tgstation/tgstation/pull/43816
https://github.com/tgstation/tgstation/pull/51546
These are all minor optimizations--they won't do much, at all, to improve performance, but they will help a tiny bit---a bit less memory, a bit faster at handling things.
Also cleaned up some styling stuff
tweak: ported some improvements to the overall lighting system
/:cl:
=> Lighting Optimizations

code/__DEFINES/MC.dm, code/controllers/globals.dm, code/controllers/master.dm, code/controllers/subsystem.dm
ports: https://github.com/tgstation/tgstation/pull/49848 https://github.com/tgstation/tgstation/pull/49893 and https://github.com/tgstation/tgstation/pull/37126
fix: fixes some potential issues with the Master Controller
/:cl:
=> Master Controller Fixes

code/game/gamemodes/changeling/powers/mutations.dm
Replaces the [src] with [H] and fixes the logging for using a changeling tentacle on grab intent. Also simplify the message.
Simple fix on some logging issues.
:cl:
fix: fixes the logging for using the changeling tentacle on grab intent
/:cl:
=> Fixes the Changeling tentacle grab logging

code/datums/cache/crew.dm
Combines `scan` and `health_data` into one. Reducing proc overhead.
Also optimizes the proc a bit.
The real optimization can be done by removing the sortAssoc. It is the most brunt of the proc cost.
This can be done once we get TGUI. Since TGUI can sort things locally rather easily which saves server CPU time
stats (tested with 51 humans with vital scanners on):
```
Profile results (total time)
Proc Name                                                                                   Self CPU    Total CPU    Real Time     Overtime        Calls
---------------------------------------------------------------------------------------    ---------    ---------    ---------    ---------    ---------
OLD
/datum/repository/crew/proc/health_data …
```
=> Slightly improves the speed at which the crew monitor gets its data

code/datums/components/swarming.dm
Fixes the master branch being unable to compile
The game should be able to friggin compile
No CL
=> [SPEEDMERGE] Fixes master branch compiling

code/game/gamemodes/cult/cult.dm, code/game/gamemodes/cult/cult_comms.dm, code/game/gamemodes/cult/cult_items.dm, code/game/gamemodes/cult/cult_objectives.dm, code/game/gamemodes/cult/cult_structures.dm, code/game/gamemodes/cult/ritual.dm, code/game/gamemodes/cult/runes.dm, code/game/gamemodes/cult/talisman.dm, code/game/gamemodes/miniantags/slaughter/slaughter.dm
Corrects some grammar/spelling issues regarding the cult gamemode (fixes #13681)
You'd think book club members would know how to spell
:cl:
spellcheck: Correct most erroneous text in the cult gamemode
/:cl:
=> Add Rite of Spellcheck for cult

code/modules/reagents/chemistry/reagents/drugs.dm
Fixes a runtime with CBD and THC.
fixes: https://github.com/ParadiseSS13/Paradise/issues/13665
fix: Fixes CBD and THC not properly interacting
/:cl:
=> CBD Runtime Fix

code/modules/mob/living/silicon/robot/robot_damage.dm
travis compilation results being stale on old PRs is stinky
=> Fixes use of a no longer existent helper that prevented compilation

code/game/gamemodes/scoreboard.dm
1. Commented out score lines that were unimplemented and fixed at 0.
2. Changed the ranges for the crew ratings.
The current scoreboard had a lot of scores that were fixed at 0 and thus actually didn't grade anything, which is disappointing when you busted your ass all shift cooking meals. There were also numerous crew ratings that were almost never seen due to having narrow ranges or requiring absurd score totals; those have been modified so crews have a decent chance of seeing them.
:cl:
tweak: Commented out scoreboard lines that were fixed at 0 and thus don't work yet.
tweak: Changed crew rating ranges so more of them would be seen. (Some had very narrow ranges, others required absurd scores to reach.)
/:cl:
=> Scoreboard: Score and Rating Cleanup

code/modules/paperwork/ticketmachine.dm
Makes the ticket machine use soft refs, because these being hard refs is just silly.
no CL as this is backend.
=> Makes Ticket Machine Use Soft Refs

code/datums/mind.dm, code/game/objects/items/devices/megaphone.dm, code/modules/mob/living/carbon/human/say.dm
Just cleaning house, nothing special.
=> Removes some unused vars and a proc from minds

code/controllers/subsystem/events.dm, code/controllers/subsystem/vote.dm, code/defines/procs/admin.dm, code/modules/admin/admin_verbs.dm, code/modules/admin/verbs/adminsay.dm
Removes a duplicate logging helper as well as cleaning up the existing one. 
Still works
Duplicate code is bad
tweak: Cleans up some unused code
/:cl:
=> Removes duplicate helper

code/game/objects/items/devices/radio/radio.dm
Fixes a comment which made my highlights go insane
Yes
N/A
=> Fixes a comment which made my highlights go insane

code/game/objects/items/weapons/holy_weapons.dm
Fixes a runtime causing bloat in the runtime viewer
Runtimes bad
fix: Fixed a nullrod runtime
/:cl:
=> Fixes null mind runtimes with roasry nullrod

tools/github-actions/README.MD
After speaking with some people in coderbus, I have decided to add attribution to the nanomap rendering system in accordance to the license.
Attribution to original coders is important
N/A, GitHub only
=> Adds appropriate attribution to nanomap rendering

code/game/objects/items/stacks/sheets/glass.dm
This adds a short build time for fish bowls and aquariums, fixes #13809
You can't flee from sec and instantly drop dense items behind you to stop people chasing you. 
:cl:
tweak: fish bowls and aquariums now take some time to make.
/:cl:
=> Build time for aquariums

README.md
Removes now dead link to the 'krihelimeter', which was discontinued
bad links bad. Though I suppose it doesn't affect the game itself.
No changelog since it doesn't impact the game.
=> Removes dead link in repository description

code/__HELPERS/text.dm
Allows you to use standalone [logo] when writing paper, by adding invisible 0 width character before the image.
Fixes #13842 
:cl:
fix: Fixes usage of standalone logo in papers.
/:cl:
=> Fixes usage of standalone logo in papers

code/game/gamemodes/miniantags/borer/borer.dm, code/game/machinery/computer/cloning.dm, code/game/machinery/computer/depot.dm, code/game/objects/items/devices/radio/radio.dm, code/game/objects/items/weapons/RSF.dm, code/game/objects/items/weapons/cards_ids.dm, code/game/objects/items/weapons/storage/bags.dm, code/game/objects/items/weapons/storage/storage.dm, code/modules/admin/verbs/onlyone.dm, code/modules/antagonists/_common/antag_spawner.dm, code/modules/antagonists/traitor/datum_traitor.dm, code/modules/events/slaughterevent.dm, code/modules/mining/abandonedcrates.dm, code/modules/mob/new_player/poll.dm, code/modules/projectiles/guns/energy/special.dm, code/modules/reagents/chemistry/recipes/slime_extracts.dm
This PR replaces instances of `var ` with `var/`. Inconsistent code is bad and this style shouldnt be used.
Consistency good
N/A
=> Replaces all "var " with "var/"

code/modules/flufftext/Dreaming.dm, config/names/dreams.txt, config/names/nightmares.txt
Fixes this:
By changing `dreamlist` to `newlist`
Less immersion breaking, I guess?
:cl:
tweak: Capitalised the word AI in dreams.
fix: Fixed the [DREAMER] bug in dreams.
/:cl:
=> Fixes [DREAMER] message in dreams.

code/modules/client/preference/loadout/loadout_accessories.dm, code/modules/client/preference/loadout/loadout_hat.dm
Please *please* test your code first, before submitting it.
Loadouts were throwing errors from non-existent entries
fix: Fixes loadouts throwing errors
/:cl:
=> Fixes Loadout Errors

code/game/gamemodes/blob/blob_report.dm
Fixes type of new nuke code in blob gamemode. Before it was int but should be string.
Now you can actually blow up the station in blob gamemode.
:cl: azizonkg
fix: fixed type of new nuke code in blob gamemode. Now you can actually blow up the station in blob gamemode.
/:cl:
=> Fix var type of new nuke code in blob gamemode

code/game/gamemodes/vampire/vampire_powers.dm
This PR changes the description of the vampire power 'Rejuvenate', replacing potentially misleading language with more clearly understood language.
Fixes https://github.com/ParadiseSS13/Paradise/issues/13983
Not understanding what your powers can do and can't do is bad, knowing exactly what you can and can't do is good. This PR facilitates the latter.
:cl:
tweak: Tweaks the language used in the vampire rejuvenate power's description.
/:cl:
=> Changes desc of rejuvenate power

code/modules/mob/living/simple_animal/hostile/terror_spiders/princess.dm
Fixes #14051 
:cl: Kyep
fix: A dead terror princess is no longer invisible in some cases.
/:cl:
=> Fixes #14051 - invisible dead princess

_maps/map_files/generic/Lavaland.dmm
Repositions the items in the Labour Camp Maintenance a bit to make the wiring look better.
Current setup could cause eye damage.
Old:
New:
:cl:
tweak: Moved a couple of things at the Labour Camp to reduce Cable Spaghetti.
/:cl:
~~very important PR, please speedmerge~~
=> Fixed Gulag Wire Spaghetti

code/modules/mob/living/simple_animal/friendly/farm_animals.dm
This makes all cows default to female
All cows can be milked and have udders. They shouldn't have a 50% chance to be male.
:cl:
fix: cows are female now
/:cl:
=> All cows are now female

code/modules/admin/verbs/adminpm.dm
Restores mentor's ability to use:
- The "Admin PM mob" verb
- The "Admin PM key" verb
- The "Admin PM name" verb
This was accidentally removed as a result of #14024.
:cl:
fix: Restores mentor's ability to PM people
/:cl:
=> Restores mentor's ability to PM people

code/game/objects/items/toys.dm
Adds a simple description for all the figurines you can get from the arcade.
More flavor is always good, also Fixes #14055 😏 
:cl:
add: added descriptions for all the figurines obtainable from the arcade
/:cl:
=> Adds Figurine Descriptions

_maps/map_files/RandomRuins/SpaceRuins/wizardcrash.dmm, code/modules/awaymissions/mission_code/ruins/wizardcrash.dm
Fixes #14116
When I made that space ruin, I did not realize that a used charge spellbook causes an emp when used. I did not want to make a new object just to have, effectively, an inert prop. I realize now that varediting in the mapeditor is bad, especially due to situations like this.
no unintended infinite emps
:cl:
fix: used emp book in wizard crash ruin no longer causes emp's when used.
/:cl:
=> Fixes #14116

code/datums/outfits/outfit_admin.dm
Spin-off of my more ambitious other PR.
This PR just has small qol changes/tweaks to the NT Undercover Operative.
Namely, they now get yellow insulated gloves rather than combat gloves and a random uniform instead of always a black one. This should help them blend in slightly better at no mechanical disadvantage.
Undercover gotta be stealthy.
:cl:
tweak: slight adjustment to NT Undercover Operative
/:cl:
=> Minor NT undercover changes

code/defines/vox_sounds.dm, code/modules/mob/living/silicon/ai/say.dm
This changes the AI Announcement Help window to show the sounds and words separately.
Please let me know if I missed any sounds, them being so hard to find is the whole reason that I made this.
Makes it easier to find the alert nosies, since right now you have to search through the whole 1000+ words to find them.
Old:
New:
:cl:
tweak: AI Announcement sounds are now separate from words.
/:cl:
=> Separates the AI Announcement noises from the words

code/modules/admin/topic.dm
Fixes the cancel button spawning in someone naked instead of cancelling when using the re-incarnate function.
It prevents admins from spawning in someone naked when they actually want to cancel re-incarnating
:cl:
fix: Fixed the re-incarnate outfit selection menu cancel button
/:cl:
=> Makes the re-incarnate cancel button actually cancel

.travis.yml
Fixes travis CI config
We need CI to pass
N/A
=> FIxes Travis Config

code/modules/food_and_drinks/food/foods/meat.dm
Based on peoples requests, human meat, IE, meat made from gibbered / meat cleaver'ed / chainsawed people are now salty like the owner.
A more detailed flavor to the food of those that have fallen victim to the gibber, or traitorous murderers with specialized tools
:cl:
tweak: Human meat is now salty to be accurate to the dead owner
/:cl:
=> Makes human meats flavor more accurate to the feelings of the owner

code/__HELPERS/text.dm, code/game/dna/genes/disabilities.dm
This PR fixes wingdings chat messages being "" or rarely ever working.
Having features of the game work is good.
:cl:
fix: Fixes Wingdings chat messages not working.
/:cl:
=> Fixes Wingdings

code/__DEFINES/misc.dm, code/__DEFINES/stat.dm, code/controllers/subsystem/shuttles.dm
Removes and replaces some defines for the shuttle that weren't being used anywhere.
Just a small refactor, no functional changes.
=> Shuttle defines refactor

code/_onclick/hud/ghost.dm
Fixes #14228
More pAI access is good but checks should be there for bans and such.
:cl:
tweak: Can no longer become a pAI through the observer HUD button if not eligible anymore
/:cl:
=> Add eligibility checks for pAI observer button

code/modules/crafting/craft.dm
Use `key_name_admin(usr)` when alerting admins when something sensitive has been crafted. 
Allows admins to see more info about the client crafting the item (mob, admin options)
Before:
After:
:cl:
add: Add more info about the crafter in crafting messages for admins (mob, admin commands)
/:cl:
=> Adds more info about the crafter in crafting messages for admins

code/modules/research/experimentor.dm
Fixes #14152, a runtime in E.X.P.E.R.I-MENTOR
Runtimes are bad
:cl:
fix: fixed an E.X.P.E.R.I-MENTOR runtime
/:cl:
=> [Bugfix] E.X.P.E.R.I-MENTOR runtime fix

code/modules/projectiles/guns/projectile.dm
Adds a screwing sound when a Suppressor is added or removed from a gun.
Immersion or something. 🤷 
:cl:
add: Added a screwing sound when you add/remove a Universal Suppressor from a gun
/:cl:
*Should this be 'add:' or 'soundadd:'?* 🤔
=> Adds a sound when you add/remove a Suppressor from a gun

code/ATMOSPHERICS/components/unary_devices/vent_pump.dm
This PR fixes bursting vents shooting ghosts (and other non-living mobs) away by changing the type checking from `mob` to `mob/living`.
Ghosts shouldn't be affected by the real world.
:cl:
fix: Fix bursting vents shooting ghosts away
/:cl:
=> Fixes bursting vents shooting ghosts away

code/modules/reagents/chemistry/reagents/medicine.dm
The descriptions of Stimulants and Stimulative Agent were on the wrong chemical, inaccurately describing what they do. This pr fixes it.
Almost no one will put these reagents in a chem master, but it is good just in case, plus it means anyone that reads the github just for the description of reagents will not be confused by the incorrect descriptions.
:cl:
tweak: Corrects descriptions of Stimulants and Stimulative Agent in the Chemmaster 3000
/:cl:
=> Corrects the description of Stimulants and Stimulative Agent

code/game/machinery/computer/pod.dm, code/game/mecha/mecha.dm, code/game/objects/effects/portals.dm
Fix and tweak teleportation for mecha (through CentCom Mass Driver for example).
Now you can actually use CentCom Mass Driver on full power.
:cl: azizonkg
fix: now you can actually use CC Mass Driver to teleport mecha.
/:cl:
=> Fix and tweak teleportation for mecha

tools/py-midi2piano/midi2piano.py
Tool `py-midi2piano` used the old limits when converting MIDI files into usable sheets (max 200 lines, of 50 chars each). This PR changes the limits to match the ones introduced in #13865
:cl:
tweak: Adjusted limits in external tool py-midi2piano for MIDI file conversion
/:cl:
=> Match py-midi2piano music limits with new ones

code/datums/cache/air_alarm.dm
Fixes air alarms not updating on Atmospherics Consoles. They'd always show up as "Good" because of data caching that is never invalidated. That PR fixes that.
:cl:
fix: Fix Atmospheric Consoles not using up-to-date data
/:cl:
=> Fix atmospherics control UI not refreshing data correctly

code/modules/arcade/prize_datums.dm
The rubber ducky entry in the prize vendor could be worded better, this PR does this.
Clean sentence structure and wording is GOOD.
:cl:
tweak: Tweaks rubber-ducky prize description.
/:cl:
=> Alters description of rubber ducky prize

code/__HELPERS/unsorted.dm
Deletes the invertHTML function as it's not used by anything
Gets rid of useless code
=> deletes unused invertHTML function

code/modules/mob/living/simple_animal/hostile/retaliate/pet.dm
This PR properly genders Araneus in the code, as SHE is very often misgendered when referred to in game. 
As mentioned above, Araneus very often gets called a "he" rather than a "she". While this doesn't change anything game-play wise, I think it's time to finally put the discussion about which gender Araneus is to rest. To do so, I'm going to provide some proof that Araneus is actually female. It's pretty simple anatomy. Female spiders generally have larger abdomens, whereas males have smaller abdomens and longer legs. 
In the image above, we see the guard- and hunter spider variants. Araneus uses the guard spider model, which is seen to have a very large abdomen. Hunter spiders on the other hand, have a smaller abdomen and long, thin legs.
In the image below, we see an image comparing a …
=> Properly genders Araneus

code/game/objects/items/weapons/storage/boxes.dm
fixes #14382
Someone did an oopsie and typoed a typepath
bugs bad
:cl:
fix: donk boxes now contain donks again
/:cl:
=> The return of the donk

code/modules/admin/player_panel.dm
Fixed the issue where the wrong param was changed in the player panel. Now all buttons work as expected again.
Fixes issues left over from #14404
Regression bug fixed
:cl:
fix: The player panel is usuable again
/:cl:
=> Player panel fix

code/modules/mob/living/carbon/human/species/wryn.dm
Updates wryn.dm so wryn can choose their body color now.
[A quick screencap from a local server.](https://i.imgur.com/qLQkFiX.png)
:cl:
fix: Updates wryn.dm to allow for body color picking again.
/:cl:
=> Fixes wryn body color picking

tgui/.eslintrc.yml
remake of #14002
AA said I could open it.
It's very annoying, 80 characters is basically nothing once you have some indendation.
As Kyet said on the other PR, it forces less readable or understandable code.
Probably not needed?
=> Removes 80 char maximum from tgui electric bogaloo

code/modules/surgery/organs/organ.dm, code/modules/surgery/organs/organ_external.dm, code/modules/surgery/organs/organ_internal.dm
Fixes #14203 . Makes internal organs rot while outside the body. 
Also moved procs external/emp_act, internal/emp_act and internal/handle_germs to their respective files
:cl:
fix: Internal organs now rot outside the body
/:cl:
=> [Bugfix] Internal organs rot outside body

code/modules/client/client procs.dm
Makes the 'Toggle guests' admin verb work
Fixes a bug. Allows admins to toggle guests.
:cl:
fix: Fixed 'Toggle guests' admin verb
/:cl:
=> fixed the toggle guests command

code/datums/mind.dm, code/game/machinery/machinery.dm, code/game/objects/items/devices/radio/radio.dm, code/game/objects/items/devices/transfer_valve.dm, code/game/objects/objs.dm, code/modules/client/preference/preferences.dm, code/modules/instruments/objs/structures/_musician.dm
Cleans up some nanoUI remains in TGUI-ified UIs, as well as adding in some TGUI handlers that I forgot in places
Nano bad
tweak: Removes some nanoUI hooks in TGUI-ified interfaces
/:cl:
=> The beginning of the end - Minor nanoUI cleanup

code/modules/examine/descriptions/weapons.dm
Removes some examine text that was not removed with #1514
Targeting mode was removed half a decade ago, there is no reason to have examine text that teaches you about a system that was removed 5 years ago
:cl: ppi
del: Removes ranged weapon examine text regarding targeting mode
/:cl:
=> Removes Targeting Mode examine text

code/game/machinery/computer/ai_core.dm
Fixes a bug from the tool refactor that made AI Core deconstruction fail when a crowbar was used.
Bugs are bad.
:cl:
fix: Fixed the crowbar step on AI Core deconstruction.
/:cl:
=> Fixes crowbars not working on AI Core for deconstruction

.github/CONTRIBUTING.md
Makes Affected a maintainer in contribution.md
It'll not affect the game
:cl:
add: AffectedArc is now a maintainer according to the contribution document
/:cl:
=> Make Affected a Maintainer

code/modules/mob/living/silicon/silicon_defense.dm
Adds a sound for when you pet a borg, copied over from [`animal_defense.dm`](https://github.com/ParadiseSS13/Paradise/blob/master/code/modules/mob/living/simple_animal/animal_defense.dm#L15)
Immersion
:cl:
tweak: Petting a borg now makes a sound
/:cl:
=> Makes borg petting have a sound effect

code/game/machinery/doors/airlock.dm, code/game/machinery/doors/door.dm, code/game/objects/items/control_wand.dm
:cl: Flatty
add: Door remotes can now be used to change the speed of airlocks.
:cl:
=> Add door speed changes to remotes

code/modules/mining/lavaland/loot/ashdragon_loot.dm
Reverts ParadiseSS13/Paradise#14037
#13247 is fixed which fixes the actual issue behind the server killing lag
=> Revert "Disables dragon transformation because its users can freeze the whole server"

code/game/objects/items/weapons/AI_modules.dm, goon/browserassets/css/browserOutput-dark.css, goon/browserassets/css/browserOutput.css
Removes the `bnotice` span class, since it's only used in one file and is identical to `boldnotice`.
I noticed this while working on something else, so I thought I might as well make a PR to change it.
The `boldnotice` span class does exactly the same thing, and is easier to undstand.
No in-game effects.
=> Removes the 'bnotice' span class

code/datums/action.dm
Fix internals action button not showing and Boo spell button flickering
Bugs bad
:cl:
fix: Fix internals action button being invisible being internals are on
fix: Fix Boo spell button flickering and not rendering properly
/:cl:
=> Fixes internals action button not showing and Boo spell button flickering

config/example/spaceRuinBlacklist.txt
Adds the new space ruin that serves as a golem shuttle destination to the example blacklist, albeit commented out, as requested by Kyet. I also removed an incorrect line that referred to a file we don't have.
Example Config files being updated is good.
:cl:
tweak: space ruin example blacklist config updated
/:cl:
=> updated space ruin example blacklist with new space ruin

goon/code/datums/browserOutput.dm
Fixes server issues
Yes
no CL, backend change.
=> Fixes server issues

code/__DEFINES/misc.dm, code/_onclick/hud/fullscreen.dm, code/_onclick/hud/plane_master.dm, code/modules/client/preference/preferences.dm, code/modules/mob/living/update_status.dm
Reverts #14531 and #14551
New eyeblur effect is too powerful.
:cl: Kyep
tweak: reverted back to the old eye blur feature.
/:cl:
=> Revert "Blurry eyes blur eyes"

_maps/map_files/MetaStation/MetaStation.v41A.II.dmm
Multiple fix for issue #13950 , most of the problems there where fixed, all cables where changed, pipe-nets where remade and many more things where added, there's still a lot of work to do but i don't want this PR to be so big, i will keep working on the station in the future.
Examples of minor fixes in Issue #13950 
Before
After
Before
After
Before
After
---
Suit storages instead of hardsuit racks, departamental ID computers added for every head office.
---
Cargo Sec Checkpoint is now a break room.
Engineer Sec Checkpoint is now Drone Fabricator.
Medbay Checkpoint was transformed into a bigger Paramedic room and a Blood bag storage.
Science checkpoint is now a "mad scientist" area for shenanigans.
---
Useless Tcomms room in engineer is now a Clown Mime old place
---
Small but now Clown …
=> First step Metastation Fix (Issue #13950 and more)

code/modules/reagents/chemistry/reagents/medicine.dm
as title ~~hopefully~~
:cl:
tweak: haloperidol and nanocalcium to be less shit code
/:cl:
=> updates haloperidol and nanocalcium to be less shit code

code/game/objects/structures/spirit_board.dm, code/modules/mob/living/carbon/human/say.dm, code/modules/mob/living/simple_animal/hostile/megafauna/colossus.dm, code/modules/mob/new_player/new_player.dm, code/modules/paperwork/filingcabinet.dm
As per title, this replaces the inappropriate, and non-self-explanatory term `virgin` which is mostly used to denote a lack of sexual experience, with more context-appropriate terms which is: 
`used`
`modified`
`populated` 
Some coder had way too much fun over 8 years ago. I know, skip the jokes. 
No actual gameplay impact, no changelog.
So that I'm the last future coder to make a double take
:cl:
/:cl:
=> Rename all instances of "virgin" being used as a variable name

code/datums/action.dm
Fixes a few bugs with spell buttons:
- They don't flicker anymore
- An unavailable spell like hypnotise for vamps with not enough blood now won't show 100% below it while it's unavailable.
- Using a spell that fails and gets reverted now properly reverts the image
The PR also made the button text better to read. The text itself is now always fully visible. No weird alpha is being applied or such.
Fixes #14540
Bug fixes are very good
:cl:
fix: Spell buttons now don't flicker anymore
fix: Unavailable spells due to other reasons than recharging now will be blacked out without text
fix: Using a spell that fails and reverts now properly shows the button
tweak: The spell button recharge text is now better readable
/:cl:
=> Fixes spell buttons flickering and other issues. Also makes the recharge text more readable

code/modules/admin/topic.dm, code/modules/power/lighting.dm
- Cleans up the light fixture/light bulb code, and adds some documentation too.
This isn't meant to be a refactor, I was originally going to just fix a typo but I got a bit carried away.
- This also makes it so that every time a light flickers, it has a very small chance of burning out the bulb. With each flicker adding a 0.1% chance of it happening.
This may seem incredibly small *(because it is)* but each ghost spook has 5 to 10 flickers (0.5% to 1%), so it adds up over time.
And ghosts shouldn't be able to break lights consistently, since that ends up being a shadowling buff.
Documentation is good, as is *(somewhat)* more readable code!
Makes ghosts even more spooky. 👻 
:cl:
add: Ghosts spooking a light adds a very small chance of the light burning out (0.5% - 1%)
tweak: Cleaned …
=> Light fixture code cleanup & spooking

code/modules/mob/living/carbon/human/human.dm, code/modules/surgery/plastic_surgery.dm
This changes the 'Plastic Surgery' surgery to allow you to give someone a new named based on an ID card.
The choices are based off of any ID card on their body, and any ID card in the offhand of the surgeon.
(This also works for Agent IDs)
*(I can change that if it's too OP)*
If someone is revived as a Monkey (or monkey equivalent) they can now have their name back, assuming they still have their ID.
Agent ID card shenanigans.
- **The Test Subject:**
- **Normal name list:**
- **Holding an ID card in offhand: *('Held ID card' being the registered name for demo purposes)***
- **Name was changed, so...**
- **Show their old name as a choice. *(Name is based on the subjects ID card)***
---
- **Also works for any ID cards on the patients body:**
:cl:
add: Plastic Surgery now allows you to …
=> Makes 'Plastic Surgery' names include held ID Cards

code/datums/cache/air_alarm.dm, code/game/machinery/alarm.dm, code/modules/tgui/modules/atmos_control.dm
Fixes #14659 
Central atmos computers now work, and also only show station Z-level alarms
Updated UIs shouldnt break shit
fix: Central Atmos Console works again
fix: Central Atmos Console now only shows alarms on the station Z-level
/:cl:
=> Fixes a few oversights with TGUI Central Atmos

_build_dependencies.sh, code/modules/mob/typing_indicator.dm
=> Bump CI version of SpacemanDMM suite to 1.6

_maps/map_files/cyberiad/cyberiad.dmm, _maps/map_files/generic/Lavaland.dmm, code/game/machinery/computer/prisoner.dm, code/game/machinery/constructable_frame.dm, code/modules/mining/laborcamp/laborstacker.dm, code/modules/mining/machine_redemption.dm, code/modules/mining/machine_vending.dm
This PR is a complete rework and remap of the gulag, security can now use it to send both Temp and Perma prisoners there. 
The system is quite simple, if you have any prisoner with a 15+ minutes sentence, you can put a prisoner ID inside the "labor camp point manager", give them a "quota" of mining points they must achieve to be able to get out (I calculated with a couple of test runs and 150 points per minute is good enough), you then get them inside the labor camp shuttle, drop them there and they can start to work at lavaland to get those points, there is a set of mining for them to work and a personal ORM. Once they got enough points, prisoners are able to call the shuttle back, get in, swipe the ID on a console and move the shuttle back to the station, then they just need to walk …
=> Labor Camp (Gulag) Rework

.github/workflows/update_tgs_dmapi.yml
Adds manual triggering and try to fix line endings
=> DMAPI Updater Fix

.github/workflows/update_tgs_dmapi.yml
I hate github actions. Please give us a way to actually test these things locally without having to make 3 billion commits for 1 thing.
Adds a missing keyword to the conversion. God I hate actions.
=> [Hopefully] the final DMAPI updater fix

.gitignore, .travis.yml, _build_dependencies.sh, code/__DEFINES/rust_g.dm, code/__HELPERS/_logging.dm, code/game/world.dm, paradise.dme, tools/travis/install_build_deps.sh, tools/travis/install_rustg.sh
This PR is the first of a chain I plan to make for several features depending on RUSTG (Discord webhooks, Async SQL, in-code revision info, etc). This PR is updating the libraries themselves as well as the DM interface side (It already has a sizable diff as seen below). It also cleans up some log ends. 
Images of logging still functioning before the admins threaten to pitchfork me. We also still follow 8601 standards, because anything else is objectively terrible.
*windows*
*also on linux*
Up to date libraries are good, this also unlocks a lot of optimisations down the road for us.
add: Updated a backend library 
/:cl:
=> Update RustG + Minor Travis Updates

code/modules/shuttle/syndicate.dm
Fixes an issue where assault pods couldn't launch due to a bad check. My bad.
How the hell did this not get reported until now?
things working are good
:cl:
fix: syndicate assault pod now works again
/:cl:
=> assault pods now actually work

.vscode/extensions.json
See title
Colored brackets! Blame the last coder in the editor!
=> Add GitLens and Bracket Pair Colorizer to recommended extension

code/game/gamemodes/cult/cult.dm
Swaps a return for a continue, since I didn't manage to get this into #14516
Should've been in the main PR
N/A
=> Quick cult fix

code/modules/reagents/chemistry/reagents.dm, code/modules/reagents/chemistry/reagents/misc.dm, code/modules/reagents/chemistry/reagents/pyrotechnic.dm, code/modules/reagents/chemistry/recipes.dm, code/modules/reagents/chemistry/recipes/pyrotechnics.dm
Adds logging to chemicals and chemical reactions that make fire flash hotspots.
Grief is bad kids.
:cl:
tweak: Logs some chemicals better
/:cl:
=> Adds some flaming hot logging

code/modules/reagents/chemistry/reagents/misc.dm, code/modules/reagents/chemistry/reagents/pyrotechnic.dm, code/modules/reagents/chemistry/recipes/pyrotechnics.dm
Adds the PR request changes I had on #14823
One of them fixes a runtime. Others are just styling and OO stuff
No func changes
=> Adds some PR review changes from #14823. Fire flash logging

code/modules/mob/living/simple_animal/friendly/dog.dm
Fixes the `.,` in dog barking.
🐶
Old:
New:
:cl:
spellcheck: Dog barking is now grammatically correct
/:cl:
=> Makes dog barking grammatically correct

code/modules/admin/admin_verbs.dm
Fixes: #14691 
Being unable to re-admin yourself is a pretty big problem, even if it only happens with the legacy system.
:cl:
fix: Fixed a runtime when re-adminning yourself using the legacy admin system
/:cl:
=> Fixes re-admin runtime

code/modules/mining/equipment/marker_beacons.dm
Fixes a duplication exploit related to picking up placed marker beacons while incapacitated.
Dupe bad and gets you banned
:cl:
fix. Fix a duplication exploit involving marker beacons
/:cl:
=> Fix marker beacon duplication exploit

code/game/gamemodes/miniantags/abduction/gland.dm
Makes the abductor MID message admins with follow links, instead of  *just making an admin log that can only be seen through downloading logs or the admin secrets admin log panel.*
So we know why someone is delimbing the clown or trying to weld all the vox in a locker box, and can talk to the scientist if it is a bit much.
:cl:
tweak: Better logging on the abductor MID
/:cl:
=> Makes the abductor MID command mode notify admins better

goon/code/datums/browserOutput.dm
Makes the ban evader cookie more noticeable
Ban evading bad
=> [s]Admin message tweak

code/modules/economy/ATM.dm
This makes ATMs try to put money directly into your hands when withdrawing. As opposed to just dropping it on the floor next to you.
Also added some simple instructions to the ATM description, because why not.
Don't want people stealing your incredibly valuable money.
:cl:
tweak: Withdrawing money from an ATM now puts it into your hands if possible, rather than just dropping it onto the floor
tweak: Tweaked the ATM description to be a bit more user-friendly
/:cl:
=> Makes ATMs put money into your hands when withdrawing

code/_onclick/ai.dm, code/controllers/configuration.dm, code/controllers/subsystem/discord.dm, code/controllers/subsystem/http.dm, code/controllers/subsystem/ticker.dm, code/datums/discord.dm, code/modules/admin/verbs/adminhelp.dm, code/modules/client/client_procs.dm, code/modules/shuttle/emergency.dm, config/example/config.txt
Fixes and tweaks some behaviour with SShttp and SSdiscord. Exhaustive list is:
- Quotes now send over discord properly
- Support for multiple webhook endpoints for the same messages
- All admin entries are now prefixed
- Not configuring the admin role will no longer show *(Role not configured)*
- SShttp now tracks total requests in a round
- SShttp now shows processing requests and total requests in the statpanel
- Cleaned up some documentation
- Removed a message informing people the emergency shuttle has docked with the station
Improvements and fixes are good
tweak: Made some improvements to SSdiscord and SShttp
/:cl:
=> SSdiscord tweaks

code/modules/instruments/songs/_song.dm
- **Fixes instrument songs not looping even when they should**
- Fixes #15001
Bugfix
:cl:
fix: Fix instrument songs not looping properly
/:cl:
=> Fixes instruments not looping

code/modules/mining/machine_vending.dm
Fixes AIs ejecting IDs in Mining Vendors to their core. IDs that are ejected remotely will now appear at the vendor's turf.
Bugfix (there was an issue for it but I can't find it anymore)
:cl:
fix: Fix AIs being able to eject IDs inside Mining Vendors to their core
/:cl:
=> Fixes AIs ejecting IDs in Mining Vendors to their core

code/modules/mob/mob.dm
- **Makes point arrow travel smoothly to pointed object.**
- Light refactor of the Point To verb
Helps catch players' attention, giving them an easier time at locating things that are being pointed at.
*Arrow goes nyoom*
:cl:
add: Arrow now travels smoothly when pointing at things
/:cl:
=> Makes point arrow travel smoothly to pointed object

code/game/gamemodes/changeling/powers/biodegrade.dm
Makes changeling biodegrade mutation capable of dissolving legcuffs as well.
It doesn't make sense for biodegrade to dissolve handcuffs, but leave legcuffs alone, basically halting a changling's escape attempt anyways.
:cl:
tweak: Biodegrade can dissolve legcuffs
/:cl:
=> Makes biodegrade dissolve legcuffs

README.md
- Adds [Installation Guide](https://github.com/ParadiseSS13/Paradise/blob/master/.github/DOWNLOADING.md) to README.
- Reorders useful documents in a order that is logical for the end-user.
None.
=> Adds Installation Guide to README, reorders useful documents

code/game/mecha/mech_fabricator.dm
- Title. Happens on any produced atom that isn't a `/obj/item`.
Bugfix
:cl:
fix: Fix a runtime when fabricating certain things in the Exosuit Fabricator (e.g. IRC body)
/:cl:
=> Fixes Exosuit Fabricator runtime when creating non-objs (e.g. IRC body)

code/game/verbs/suicide.dm
Adds an attack log when people commit suicide
Logging
:cl:
tweak: Suicide is now logged:tm:
/:cl:
=> Adds attack log to yourself when you kill yourself

code/modules/client/client_procs.dm
Greatly increases the entropy on forum link tokens. Tokens still generate fine.
Security
tweak: Forum tokens are now a lot more randomised
/:cl:
=> Greatly increases entropy on forum link tokens

code/__DEFINES/_spacemandmm.dm
Updates the lints file used by SpacemanDMM
Lints should work
N/A
=> Updates SpacemanDMM Lints

code/modules/world_topic/_topic_base.dm
I forgot PRIVATE_PROC means it cant be overridden, not that it cant be called elsewhere.
CI should work
N/A
=> [Speedmerge] oops

_maps/map_files/cyberiad/cyberiad.dmm, code/game/objects/structures/snow.dm, paradise.dme
As requested by @FreeStylaLT , I humbly offer my Christmas-themed Cyberiad for this year. Literally only makes aesthetic changes.
EDIT: now adds "snow" as a structure that can be welded away, like alien weeds. technically a code change, but works fine and shouldn't fuck with anything else.
It's for the holiday tradition.
Cargo & Locker Room
Central Primary Command
Dorms & Bar
I don't want to give away _too_ much  of what I've added with these pictures, so I'll leave it at these - but if you want me to send you screenshots privately, or if you want to dive into the .dmm to ruin the surprises, feel free!
This is, of course, totally up to any other map editor to add whatever they like, but this is my attempt!
:cl: thatdanguy23
add: added christmas cheer
del: removed bad vibes
/:cl:
=> christmas cheer

code/modules/antagonists/traitor/contractor/datums/contractor_hub_ui.dm
Contracts didn't appear on the UI because the wrong list was being iterated on (I blame myself for using duplicate names)
Contracts should now appear on the UI
N/A
=> [Speedmerge] Fixes contracts not being sent to TGUI

code/game/gamemodes/traitor/traitor.dm
Fixes Contractors runtime on round end due to `has_antag_datum` returning `0` instead of `null` in some cases.
Bugfix
N/A
=> [Speedmerge] Fixes Contractors runtime on round end

code/game/objects/items/weapons/stunbaton.dm
Fixes stun batons not applying stutter like they should.
Bug fixes are good.
:cl:
fix: Stunbatons make people stutter again.
/:cl:
=> Makes stunbaton stutter work

_build_dependencies.sh, code/datums/mind.dm, code/modules/antagonists/traitor/contractor/datums/contractor_hub_ui.dm, code/modules/mob/living/simple_animal/hostile/floorcluwne.dm, code/modules/newscaster/obj/newscaster.dm
Fixes some instances of `?.` which the compiler didnt like Also bumps Travis to this version to make it likely to catch.
The code should compile on latest BYOND damnit
fix: Code compiles on BYOND 513.1537 now
/:cl:
=> Makes code 513.1537 compliant

_maps/map_files/cyberiad/cyberiad.dmm
Santa delivered Syndicate toys to the Cyberiad - whoops. This PR remedies this and sends a covert team of elves to smack Santa in the dick for his mistake.
Balance concerns were brought up due to a few of Security's presents containing the Syndicate or riot versions of foam force weaponry. This remedies that and gives them non-harmful toy guns.
:cl: thatdanguy23
tweak: smacks santa; changes present contents
/:cl:
=> Chrimmas 2.0

code/modules/surgery/organs/vocal_cords.dm
Corrects vocal cords for golems to use the proper language, after a PR swapped the language but not the action
Things working good.
:cl:
fix: fixes action button for golem vocal cords not working.
/:cl:
=> Fixes vocal cords

goon/browserassets/css/browserOutput-dark.css, goon/browserassets/css/browserOutput.css
Fixes Syndicate code words not being highlighted in some speech (e.g. Greys with their cybernetic translator)
Bugfix
:cl:
fix: Fix Syndicate code words not being highlighted in some speech (e.g. Greys)
/:cl:
=> Fixes Syndicate codeword highlighting on some speech

code/controllers/subsystem/tgui.dm, code/modules/tgui/external.dm
Makes the arguments for tgui procs autodoc compliant.
Easier coding or something.
=> TGUI argument documentation

code/datums/mind.dm, code/game/gamemodes/cult/cult.dm, code/modules/admin/verbs/one_click_antag.dm
Probably hopefully maybe finally fixes culting someone causing the 'Cult has ascended' CC announcement.
Should've been fixed in #14849.
:cl:
fix: Fixed 'Create Antagonist' cultists immediately ascending
/:cl:
=> Fixes 'Create Antagonist' cultists instantly ascending

code/datums/looping_sounds/weather.dm
This PR more or less cuts the volume of ash storms in half
They are annoyingly loud and annoying. I even consciously stop observing people going to lavaland because of how loud and annoying the sound is.
:cl:
tweak: ash storm volume reduced
/:cl:
=> Nerfs ashstorm sounds

code/modules/mining/lavaland/loot/ashdragon_loot.dm
Lava staff will check what z level is his user on, and if it's not mining will only spawn a few sparks.
It is good because prevents using it on the station, where it can cause too much destruction.
:cl: Nazsgull
tweak: Lava staff will check what z level is his user on, and if it's not mining will only spawn a few sparks.
/:cl:
=> Nerfs Lava Staff

code/game/objects/items/weapons/storage/secure.dm, code/game/objects/items/weapons/storage/storage.dm, code/game/objects/structures/crates_lockers/closets.dm, code/game/objects/structures/crates_lockers/crates.dm, code/modules/mob/living/carbon/carbon.dm, code/modules/recycling/disposal.dm, code/modules/research/destructive_analyzer.dm
Reverts ParadiseSS13/Paradise#14536
PR is broken.
=> Revert "Close storage UI when item becomes inaccessible"

code/modules/mob/living/carbon/alien/life.dm, code/modules/mob/living/carbon/human/life.dm, code/modules/mob/living/living_defense.dm, code/modules/mob/living/silicon/robot/life.dm, code/modules/mob/living/simple_animal/simple_animal.dm
Fixes a coding issue I left in from #15076
Gives xenos a chance atleast
:cl:
fix: Xenomorphs now don't die from nothing anymore
/:cl:
=> Fixes handle_fire for mobs. Fixes xenos burning to death from nothing

code/modules/paperwork/pen.dm
Fixes #15143
I accidentally introduced it in #14960 . I did test that the interaction still works (and it did!) but apparently i changed the code further since then until it didn't...
I'm sorry :(
Bugfix
:cl:
fix: sleepypen now works again
/:cl:
=> Fix sleepypen not working :(

code/modules/mining/lavaland/loot/hierophant_loot.dm
Nerfs Hierophant Club so it cannot use ranged attacks or blasts on station (it only spawns a few sparks)
Helps miners not getting weapons of mass destruction.
:cl:
tweak: Hierophant club will now malfunction if used onboard station
/:cl:
=> Hierophant staff nerf

code/modules/events/money_lotto.dm
Removes the `<b>` tag from newscaster story in money lottery event
HTML tags aren't rendered in TGUI. Bugfix
:cl:
fix: Removes HTML elements from the Money Lottery newscaster story
/:cl:
=> Removes <b> tag from newscaster story in money lottery event

code/game/gamemodes/miniantags/guardian/guardian.dm, code/game/gamemodes/miniantags/guardian/host_actions.dm
Fixes a small mistake with host to guardian say logging.
We should have correct logs.
:cl:
fix: Fixes a small mistake with host to guardian say logging.
/:cl:
=> Fixes a small mistake with host to guardian say logging

code/modules/clothing/clothing.dm
Reverts ParadiseSS13/Paradise#15155
This was merged before the 24 hour mark, and, furthermore, it was labeled as a controversial PR.  It was only up a total of ~10 hours and 12 minutes before being merged.
Controversial PRs require a higher amount of consensus reached before they can be merged, even post 24 hours, but an actual feature change shouldn't have been merged before 24 hours, let alone a *controversial* feature removal.
=> Revert "Removes ability to put collars on jumpsuits"

code/modules/research/research.dm
Fixes rnd logging, by making it log the level rnd becomes, instead of logging the tech level of the item deconstructed.
Feedback logging working good
:cl:
fix: fixed rnd level logging
/:cl:
=> Fixes rnd logging stuff

code/game/objects/items/weapons/dice.dm
Adds an attack log to an E20 rolling a 1, which gibs the user.
Also removed a `spawn()` and did some other cleanup.
Logging good
:cl:
tweak: E20s rolling a 1 now generates an admin log
/:cl:
=> E20 gibbing admin logs

.github/DOWNLOADING.md
Updates `.github/DOWNLOADING.md` to reflect the fact we only use 1 library now, as well as clean up some misc formatting (I wanted to please the vscode markdown lint), as well as some spelling errors. I am ashamed with the amount of mistakes I made despite typing the document sober.
Bad spelling looks unprofessional
Nothing ingame
=> Fixes many spelling errors in DOWNLOADING.md

code/modules/antagonists/traitor/contractor/datums/syndicate_contract.dm
Notifies kidnapped contractor targets that they will return to the station a few minutes after being teleported.
Hopefully clears up confusion about whether they will stay in jail for the rest of the round (they don't), sparing admins from some ahelps/prayers.
:cl:
add: Add a message to kidnapped contractor targets telling them they will return to the station after waiting a bit
/:cl:
=> Tells kidnapped contractor targets they'll return in a few minutes

code/game/objects/effects/snowcloud.dm
Adds a sound on `throw_impact()` for snowballs hitting mobs, since the normal sound never plays.
Snowballs do 10 stamina damage per hit, so audio feedback would be good.
:cl:
fix: Throwing a snowball at someone now plays a hit sound
/:cl:
=> Sound for snowballs hitting mobs

code/datums/ai_law_sets.dm, code/datums/ai_laws.dm
Adds NT Default to the lawsets that an AI can start with.
Also cleans up some 1/0 to TRUE/FALSE I saw
More variety for crew and AIs. NT Default is a workable lawset and with that name, makes perfect sense to be a possible default lawset.
:cl:
tweak: NT Default is now a possible roundstart law
/:cl:
=> Makes NT Default a possible roundstart lawset

code/game/gamemodes/shadowling/special_shadowling_abilities.dm
Changes volume of shadowlings hatching by 50%
This sound is played only by shadowlings, meta'd to hell by the crew, and is insanely loud. Lowers the volume of it a lot, so it cant be heard from as far away.
:cl:
tweak: Halves the volume of shadowlings hatching.
/:cl:
=> Lowers the volume of shadowling hatch by 50%

_maps/map_files/cyberiad/z2.dmm
Fixes this:
By removing one of the airlocks.
While the Syndicate jail *is* meant to be very secure, I'd argue that phasing two doors inside eachother is a bit much.
:cl:
fix: Fixed a double airlock at the Syndicate Contractor jail.
/:cl:
=> Fixes a double airlock at the Syndicate jail

code/_onclick/observer.dm
Allows ghosts/observers to point at things using middle click.
QOL improvement, so that you don't have to right click and do it manually.
:cl:
tweak: Ghosts can now point using middle click.
/:cl:
=> Middle Click Ghost Pointing

code/modules/mob/living/carbon/human/human.dm
Allows ghosts to click on the `More...` in the examine text for employment records to see the whole thing.
Ghosts can already see the summary, it makes sense for them to see all of it.
:cl:
tweak: Allowed ghosts to click on the 'More...' in the employment record examine text to see the full record.
/:cl:
=> Ghost employment records

code/__DEFINES/subsystems.dm, code/game/gamemodes/miniantags/morph/morph_event.dm, code/game/gamemodes/miniantags/revenant/revenant_spawn_event.dm, code/game/gamemodes/miniantags/slaughter/slaughter.dm, code/modules/awaymissions/maploader/writer.dm, code/modules/events/dust.dm, code/modules/events/slaughterevent.dm, code/modules/mob/emote.dm
Updates codebase to not error on the latest batch of vscode lints provided by the langserver extension. I will bump CI dreamchecker when a version of it comes out.
I have tested map saving, emote cooldowns and overlay compiling. Event stuff has *not* been tested but nothing should break. 
People shouldnt have false positives in the error list.
fix: Improved some code quality
/:cl:
=> Updates code to be compatible with new lints

code/modules/telesci/rcs.dm
RCS: Copy Z-levels instead of using directly (requested by @AffectedArc07)
Speedfix
:cl:
fix: Fix potential Z-level issue with emagged RCS.
/:cl:
=> RCS: Copy Z-levels instead of using directly (speedfix)

code/modules/client/client_procs.dm
Fixes the 'SSD warning acknowledged.' message being sent around 200 times, rather than just once.
This has frozen my game a couple of times, and it's clearly not meant to happen.
**Before:**
**After:**
:cl:
fix: Fixed the 'SSD warning acknowledged.' message being sent 200 times.
/:cl:
=> Fixes SSD warning spam

code/modules/mob/living/carbon/carbon.dm
Fixes #15221 by adding a check to the `do_after()`.
Also redid the `resist_buckle()` code a bit.
:cl:
fix: Fixed unbuckle progress bars not getting deleted after you've been unbuckled
/:cl:
=> Buckle resist stacking fix

_maps/map_files/Delta/delta.dmm
Removes publically-accessible kitty ears.
Upholds standard established in #13096
Look at these cute little things:
Oh no!
:cl:freestylalt
del:ears of the felines from Delta
/:cl:
=> Removes cat ears from Deltastation

code/__HELPERS/files.dm
Requested by @AffectedArc07 
- `/client/proc/browse_files()` now allows transfer of `.json` files
- Instead of checking the last 4 characters of the path, it explodes by `.` and the last substring corresponds to the path extension
None for players or general staff. Allows developers to download and view round profile logs, which end by `.json`
N/A
=> browse_files() now allows transfer of .json files

code/modules/client/preference/preferences_mysql.dm
Requested by @AffectedArc07 
Fixes:
```
MySqlError { ERROR 1048 (23000): Column 'alt_head_name' cannot be null } | Query used:
```
:cl:
fix: Fixes an issue when saving preferences while using an IPC character
/:cl:
=> Fixes an issue when saving preferences while using an IPC character

.github/PULL_REQUEST_TEMPLATE.md
Capitalised the rest of the examples in the Pull Request Changelog.
It very slightly bugs me.
**Before:**
**After:**
N/A
=> Capitalises the PR changelog examples

code/modules/events/wallrot.dm
Makes wallrot target the station zlvl instead of z1
Event works better if it hits the station.
:cl:
fix: Wallrot now rots the station instead of z1 again.
/:cl:
=> Fixes wallrot

_maps/map_files/RandomZLevels/centcomAway.dmm, _maps/map_files/RandomZLevels/moonoutpost19.dmm, _maps/map_files/shuttles/emergency_old.dmm
Fixes a few smoothing issues. I'm sure there's more, but these are the ones I know about/have found.
fixes: https://github.com/ParadiseSS13/Paradise/issues/15470
fix: fixes a few smoothing issues with shuttle walls
/:cl:
=> Fixes a few Smoothing Instances

code/modules/admin/verbs/adminjump.dm
Adds a 'Cancel' button to the 'Send Mob' admin verb.
I don't know if anyone's ever teleported someone by accident in-game, but I do it all the time in my test server. So probably important to fix.
**Before:**
**After:**
:cl:
tweak: Added a cancel button to the 'Send Mob' admin verb.
/:cl:
=> Cancel button for 'Send Mob'

code/game/objects/items/blueprints.dm
Adds a game / admin log for when someone makes or renames a room with blueprints.
Logging of renaming rooms is probably a good thing to have.
:cl:
add: (Admin) Blueprints now log when (re)naming rooms
/:cl:
=> Logs blueprint (re)naming of rooms

code/modules/admin/sql_notes.dm
Changes a spelling mistake from "The note search from X has complete." to "The note search from X has completed."
Make admin tools 1% better.
:cl:
fix: (Administration) Fixed spelling / grammar of when the note search finishes.
/:cl:
=> Completes the spelling of an administrative note search thing

code/game/machinery/suit_storage_unit.dm
This PR includes various tweaks and improvements to Suit Storage Units. 
1. SSUs now accept any suit in the suit slot and and head cover in the helmet slot, instead of just space suits. This was done primarily because we had SSUs with rad suits and explorer suits, both of which aren't space suits, so you couldn't put the suit back once you removed it.
2. Aside from tanks of any size, the storage slot now also accepts any item that's size small or smaller. This was done because the rad suit SSU started with a geiger counter and again, you couldn't put it back once you removed it. IMO it makes sense that most small items could fit in there.
3. SSUs set to dangerous UV no longer delete absolutely every item in them. Items that are lavaproof are now immune to being fried, preventing the …
=> SSU improvements

code/__HELPERS/unsorted.dm, code/game/objects/structures/tables_racks.dm
- **Fixes surgical trays passing through tables**
- Fixes #15300
- Fixes an issue with `/proc/get_atoms_of_type` where it would return an empty list if `check_shift` was false
- Cleans up, refactors and documents `/proc/get_atoms_of_type`
Bugfix
:cl:
fix: Fix being able to push surgical trays on tables
/:cl:
=> Fixes surgical trays passing through tables

code/modules/reagents/reagent_containers/pill.dm
- **General pill refactor.**
- **Fixes exploit allowing injection of reagents into pills**
- `New()` -> `Initialize()`
- Third-person message upon dissolving pill no longer displays to the user, mimicking `visible_message`
- Make all pill names improper, with the chemical capitalized
- Fixes grammar in Haloperidol pill
- **Removes `spawn(5)` before deleting the pill when dissolving it into a reagent container.**
- Touch up some of the related messages to look better in chat
- The refactor should result in a saner code and more consistent user experience, as well as fixing the injection exploit.
- Prevents potential spamming of messages when dissolving a pill. Fortunately there was no duplication exploit from this since reagents are transferred away.
:cl:
tweak: Pill dissolving message is …
=> Pill refactor and bug fixing

code/modules/mining/mint.dm
Removes the ability to collect thousands of coins in a bag. No more scrooge mcduck RP
Fixes: #15092
Bug fix bug fix
:cl:
fix: Makes the coinpress respect inventory limits
/:cl:
=> Makes the coinpress respect inventory limits

code/modules/reagents/chemistry/recipes/toxins.dm
Renames `/datum/chemical_reaction/stable_mustagen` to `/datum/chemical_reaction/stable_mutagen`.
Preeety sure that 'Stable Mustagen' isn't a thing.
N/A, since it's just the path.
=> Removes mustard from stable mutagen

.github/workflows/ci.yml, code/__DEFINES/rust_g.dm, code/modules/unit_tests/_unit_tests.dm, code/modules/unit_tests/log_format.dm, code/modules/unit_tests/rustg_version.dm, tools/ci/validate_rustg_windows.py
Adds unit tests to ensure that:
- RUSTG is the correct version for the codebase
- Logs are being written in the correct format for us (Prevents people copypasting TG's RUSTG DLL in, ours is different)
Sanity tests are good
N/A, no ingame impact
=> RustG version + log format unit tests

code/game/machinery/Sleeper.dm
Makes the text for a sleeper removing an addiction `boldnotice` rather than just `notice`.
Currently, it's really easy to miss the notification.
**Old:**
**New:**
:cl:
tweak: Made the notice for a sleeper removing an addiction bigger.
/:cl:
=> Bigger addiction removal text

code/modules/mob/living/carbon/human/human_organs.dm
Makes becoming fat actually becoming fat, and becoming slim slim actually becoming slim.....as opposed to the complete opposite of these things.
Oops.
fix: Fixes becoming fat/slim
/:cl:
=> Makes Getting Fat....getting fat

code/controllers/subsystem/ticker.dm
Removes the reverb/echo from the round end sounds.
Hearing the Time Warp with the 'Druggy' sound environment is nightmare fuel.
:cl:
fix: Fixed the round end sound effects having reverb.
/:cl:
=> Fixes the Round End sounds having reverb

code/game/atoms_movable.dm
Port of tgstation/tgstation#52517 with modifications
Adds a bit of variation to attack animations
Current attack animations are a little boring and samey
| Before | After |
| ------ | ----- |
| ![jr2lqsXPwC](https://user-images.githubusercontent.com/1496804/108560931-c017a700-72fd-11eb-9962-7380b67fe59d.gif) | ![s6LxaNzF5o](https://user-images.githubusercontent.com/1496804/108561377-73809b80-72fe-11eb-8518-a62b6456ff89.gif) |
WebM (higher FPS): https://cdn.discordapp.com/attachments/145700319819464704/812430742881566741/kLLO6ZrXIu.webm
:cl:
tweak: Improve attack animations by adding some variation and speed
/:cl:
=> Improves attack animations

code/modules/mob/living/simple_animal/parrot.dm
- Optimizes parrot AI for searching items and perches by doing the A* as late as possible
- Parrot AI can no longer swipe items from people
Bluespace parrot be gone
:cl:
del: Parrot AI can no longer swipe items from people
fix: Parrot AI no longer lags the game as much
/:cl:
=> Optimizes parrot AI for searching items and perches

code/modules/hydroponics/grown/nettle.dm
Fixes nettles burning you or stunning you.
fixes: https://github.com/ParadiseSS13/Paradise/issues/15625
fix: Fixes nettles and deathnettles burning you, even if you're wearing gloves
/:cl:
=> Nettle Pickup Fix

code/controllers/subsystem/ambience.dm, code/game/area/ss13_areas.dm
Removes ambient sounds from the `/area/start` area, primarily so that they don't overlap with the lobby music.
It sounds confusing, and is most likely an unintentional change.
:cl:
fix: Fixed ambient sounds playing on the lobby/menu screen.
/:cl:
=> Fixes ambient sounds playing in the lobby

code/game/machinery/tcomms/core.dm
Fixes apostrophes breaking telecomms user filtering by decoding the sanitised input.
It's clearly a bug, and could theoretically be used to powergame.
:cl:
fix: Fixed apostrophes in names preventing people from being muted on comms.
/:cl:
=> Fixes apostrophes breaking User Filtering on comms

code/game/objects/items/weapons/storage/storage.dm
fixes: https://github.com/ParadiseSS13/Paradise/issues/15655
fix: can no longer cheese lockbox opening
/:cl:
=> No, Mobs Are Not Lockboxes

code/datums/outfits/outfit.dm, code/modules/mob/living/carbon/human/species/_species.dm, code/modules/mob/living/carbon/human/species/diona.dm, code/modules/mob/living/carbon/human/species/machine.dm, code/modules/mob/living/carbon/human/species/nucleation.dm, code/modules/mob/living/carbon/human/species/slime.dm
Fixes some issues with certain species and the newly pathed cybernetic eyes.
fix: Fixes some issues with using cybernetic eyes with some species
/:cl:
=> Fixes Some Issues With Cybernetic Eyes

code/modules/mob/living/carbon/human/species/golem.dm, code/modules/mob/living/carbon/human/species/skeleton.dm
I forgot golems and skeletons also lacked eyes.
Oops
fix: Fixes skeletons and golems being blind
/:cl:
=> Fixes Blind Golems and Skeletons

.github/workflows/render_nanomaps.yml
***sigh***
Removes a redundant step in the nanomaps action
Can this POS work yet.
N/A
=> Fixes nanomaps action, again.

code/__HELPERS/game.dm, code/_globalvars/misc.dm, code/controllers/subsystem/ticker.dm, code/datums/diseases/advance/symptoms/shedding.dm, code/datums/helper_datums/teleport.dm, code/datums/spells/conjure.dm, code/datums/spells/knock.dm, code/game/machinery/firealarm.dm, code/game/machinery/portable_turret.dm, code/game/machinery/vending.dm, code/game/objects/items/devices/whistle.dm, code/game/objects/structures/inflatable.dm, code/modules/atmospherics/machinery/airalarm.dm, code/modules/atmospherics/machinery/components/binary_devices/dp_vent_pump.dm, code/modules/atmospherics/machinery/components/binary_devices/passive_gate.dm, code/modules/atmospherics/machinery/components/binary_devices/pump.dm, code/modules/atmospherics/machinery/components/binary_devices/volume_pump.dm, code/modules/atmospherics/machinery/components/unary_devices/outlet_injector.dm, code/modules/events/tear.dm, code/modules/mob/living/silicon/ai/ai.dm, code/modules/reagents/chemistry/machinery/chem_dispenser.dm, code/modules/reagents/chemistry/machinery/chem_heater.dm, code/modules/reagents/chemistry/machinery/chem_master.dm
Refactors code to use callbacks and/or async invokes, etc. over using `spawn()`s. Tested everything locally as best I could to be sure, didn't see any issues, but this may need a TM anyway.
Code improvement because spawn()'s are bad practice.
N/A
=> Removes a bunch of spawn()'s

strings/tips.txt
Removes the devil tips as well
Just a simple removal of the devil tips
Consistency, and not confusing people whether the mode still exists
:cl:
del: Removed devil tips
/:cl:
=> Remove Devil Tips

code/game/machinery/constructable_frame.dm
Adds disk compartmentalizer to the list of construable smartfridges
Being able to build / rebuild smartfridges is good.
:cl:
fix: Fixes disk compartmentalizers making broken circuit boards and allows them to be built.
/:cl:
=> Fixes being unable to make a disk compartmentalizer

code/game/machinery/washing_machine.dm
Prevents Krav Maga security gloves from being put in a washing machine to change their colour
Disguising steal items as other things is not good, balance wise, and the only way to tell these gloves are the real thing is to put them on. Not a good thing, not a feature we want. 
:cl:
tweak: You can no longer put krav maga gloves in the washing machine.
/:cl:
=> Prevents the look of Krav maga from being changed in a washing machine

code/game/gamemodes/wizard/spellbook.dm
This is why merging ancient PRs without a branch update it a bad idea
CODE NOT COMPILING IS VERY BAD AAAAAAAAAAAA
fix: Fixed the code not compiling 
/:cl:
=> oops I broke the repo

code/modules/mob/living/simple_animal/hostile/terror_spiders/actions.dm
- Fixes terror webs stunning under airlocks
- Root cause: the stunning mechanic was in `CanPass` and depending on the turf's `contents` order (or however it would decide to loop through it), it was considered before the airlock. This issue is fixed by moving the stunning mechanic to `Crossed` (which makes more sense anyway)
- Fixes #15691, fixes #15704
- Tidies up touched code.
Bug fix
:cl:
fix: Terror spider webs no longer stun unless actually crossed (e.g. below closed airlocks)
/:cl:
=> Fixes terror webs stunning under airlocks

code/game/mecha/working/ripley.dm
fixes a spelling mistake in the firefighter mechs description 
spelling good
:cl:
fix: spelling in the firefighters description
/:cl:
=> spelling mistake in firefighter mech

code/modules/mob/dead/observer/observer.dm
Allows ghosts to see reagents in containers, the same as wearing Science Goggles.
Better awareness about what's going on for observers.
:cl:
tweak: Added reagent vision for ghosts.
/:cl:
=> Adds reagent vision to observers

code/game/mecha/equipment/weapons/weapons.dm
demloishing ---> demolishing in the description of the mech heavy plasma cutter.
~~demloishing~~
Typos not good.
:cl:
spellcheck: Fixed a typo in the description of the mech heavy plasma cutter.
/:cl:
=> Fixes a typo in the description of the mech heavy plasma cutter

code/modules/events/apc_short.dm
- Removes `var/` from `power_restore()` def
[No implicit var/](https://github.com/ParadiseSS13/Paradise/blob/master/.github/CONTRIBUTING.md#no-implicit-var)
N/A
=> Removes var/ from power_restore() def

code/__DEFINES/rust_g.dm, code/game/machinery/computer/pod_tracking_console.dm, code/modules/mob/living/say.dm
Updates vulpkanin to give them extra language features
This uses the magic of RustG to make this extremely efficient code.
*no really someone made this shit SSE4.1 accelerated. The fact someone made a hardware-accelerated text-uwuification engine is really a mark to show the point humanity is at*
Intel's website says the 9900K supports this instruction so we should be fine.
Gotta appeal to the fandom
=> Vulpkanin Update

code/modules/martial_arts/sleeping_carp.dm
Adds admin logging to sleeping carp punches and grabs
Admins should know when you attack someone
:cl:
fix: Fixed sleeping carp's admin logs
/:cl:
=> Fixes sleeping carp logs

code/game/gamemodes/malfunction/Malf_Modules.dm, code/game/gamemodes/objective.dm
If an AI doomsdays they now greentext their hijack objective
Fixes #5773
bugs are bad
:cl:
Fix: Malf AI doomsday now greentexts their hijack objective
/:cl:
=> Fixes AI doomsday greentext

code/modules/hydroponics/grown/onion.dm
Fixes #15854 with the suggested implementation.
Things shouldn't mutate into themselves, seems like an obvious bug.
:cl:
fix: Fixed red onions being able to mutate into red onions.
/:cl:
=> Added mutatelist = list() to onion/red

code/game/turfs/simulated/minerals.dm, code/game/turfs/simulated/walls.dm, code/game/turfs/simulated/walls_mineral.dm, code/game/turfs/simulated/walls_misc.dm
Walls and grammar now love each other again
spelling good, non-existent words bad
:cl:
fix: fixes typo in wall description
/:cl:
=> Fixes turf spelling issues

code/modules/reagents/chemistry/recipes/drinks.dm
Adds Ice to Daiquiri recipe(which is often a real life ingredient to this drink)
Fixes #15900 
You will no longer have issues with Daiquiri randomly being made when you're trying to whip up a Mohito for your patrons.
:cl:
fix: Fixes Daiquiri and Mohito recipe conflict
/:cl:
=> Adds Ice to Daiquiri recipe

code/datums/spells/wizard.dm, code/game/objects/items/weapons/cards_ids.dm, code/modules/hydroponics/grown/citrus.dm, code/modules/hydroponics/grown/cocoa_vanilla.dm, code/modules/hydroponics/grown/tobacco.dm, code/modules/mob/living/silicon/ai/latejoin.dm, code/modules/mob/living/silicon/robot/drone/drone.dm, code/modules/mob/living/silicon/robot/robot.dm, code/modules/pda/cart_apps.dm, code/modules/surgery/organs/subtypes/skrell.dm
**Fixed in this PR:**
Fixes #15866
Fixes #15852
Fixes #15853
Fixes #15846
Fixes #15668
**Fixed elsewhere, but issue is still open:**
Fixes #7899
Fixes #13251
Fixes #14227
Fixes #5363
Fixes #10353
Fixes #13815
Fixes #7108
Fixes #13236
Fixes #12365
Fixes #12366
Bugfixes.
:cl:
tweak: Changed the distillation reagents of Oranges and Tobacco to Tequila Sunrise and Menthol respectively.
fix: Fixed pAIs not being able to access Security and Medical records.
fix: Fixed AIs who used the 'Wipe Core' verb losing respawnability.
fix: Fixed ghosts being repulsed by the 'Repulse' spell.
fix: Fixed Agent ID cards blocking numbers in names.
fix: Fixed maintenance drone lights showing even when they're in a vent.
fix: Fixed various runtimes caused by Skrell Headpockets.
/:cl:
=> Various bugfixes

code/modules/response_team/ert.dm, code/modules/response_team/ert_outfits.dm
Gives all ERT combat gloves by default.
ERT is supposed to deal with emergency situation, and the fact a singly shocky door is kinda silly, getting onto station and instantly running into a shocked door is honestly bullshit.
:cl: ppi
add: Gives all ERT combat gloves by default
/:cl:
=> Gives ERT Combat Gloves

code/game/objects/structures/crates_lockers/closets/secure/chaplain.dm
This PR adds a plain labcoat to the chaplain's locker.
Science/Synthetics based religions are sometimes done by chaplains and getting your hands on a plain labcoat is surprisingly annoying when it's basically just thematic. This makes doing this sort of chaplain-ing a bit less of a pain.
:cl:
add: Added a labcoat to the chaplain's locker.
/:cl:
=> Add a plain labcoat to chaplain locker

code/__HELPERS/text.dm
This PR adds the regex for [date] to paperwork, and will show the current date + 544 years.
The fact that we had [time] but not [date] was unexpected, this will be great, because nobody knows the current date and it's good for paperwork keeping it accurate, making sure this paperwork was signed when it was signed.
:cl: ppi
add: Adds [date] to paperwork
/:cl:
=> Adds [date] to paperwork

code/game/dna/dna2_domutcheck.dm, code/game/dna/mutations/_mutations.dm, code/game/dna/mutations/monkey.dm
Fixes my fuckup from #15996.
Somehow I managed to undo one for loop and I forgot to test the monkey gene (which is the most important of them all)
It works now.
Fixes genetics
:cl:
fix: Fixes genetics not properly activating genes when it should
/:cl:
=> Fixes genetics gene changes not working

code/modules/economy/ATM.dm
Fixes #16038
Fixes #13318
Bugfixes!
:cl:
fix: Fixed an infinite money exploit from ATMs.
/:cl:
=> Fixes an ATM exploit

code/game/machinery/adv_med.dm, code/game/objects/items/devices/scanners.dm, code/modules/client/preference/preferences.dm
Fixes a few operator typos which were picked up in a DM Language Client update.
N/A *(In theory)*
=> Operator typo fixes (DM Language Client compliance)

goon/code/datums/browserOutput.dm
=> Fixes a var access issue

_maps/map_files/generic/centcomm.dmm
The seat that lets you buckle down and access the ERT shuttle's various consoles has been removed at some point.. I think when we changed shuttle chairs to their own subtype? Anyway, this readds it.
Using the ERT shuttle is clunky/weird with it missing, cuz shuttle departing makes you drop on the floor.
:cl:
add: Added a seat for the pilot of the ERT shuttle to buckle down.
/:cl:
=> Add a pilot seat to the ERT shuttle

code/modules/power/port_gen.dm
Adds a log for when pacmans overheat, and who touched it last.
Explosions with no logs of what caused them is not the best.
:cl:
add: Adds logging to pacmans overheating.
/:cl:
=> Logs pacman overheating

code/game/objects/items.dm
Fixes #16019 
Partially fixes #16036 by making people unable to pickup the armblade
No more machine gun kissing.
No more people picking up cling armblades.
:cl: ppi
fix: Fixes the ability to fire infinity kisses as fast as you can click
fix: Fixes it so people can't pick up a changeling armblade if droped
/:cl:
=> Fixes #16019

code/game/objects/items/weapons/RCD.dm, code/modules/mining/lavaland/loot/colossus_loot.dm
Fixes some turf related exploits in RCDS and the Theme_Warp Crystal
No. Just no. You should not be able to do this.
:cl:
fix: Fixes some turf related exploits.
/:cl:
=> Fixes some turf related exploits

code/modules/recycling/sortingmachinery.dm
- AIs can no longer be pushed in disposal chutes
- Prevents such an exploit.
:cl:
del: AIs can no longer be pushed in disposal chutes
/:cl:
=> AIs can no longer be pushed in disposal chutes

code/game/machinery/computer/robot.dm
Fixes borgs not getting their emag items when a malf AI hacks them via the robotics console. One line fix aw yeah :sunglasses: 
Bugfix.
:cl:
fix: Fixes borgs not getting their emag items when a malf AI hacks them
/:cl:
=> Fixes borgs not getting their emag items when a malf AI hacks them

.github/PULL_REQUEST_TEMPLATE.md
Tidies some grammar issues in the PR template, adds information about deleting the CL section if the change does not affect players. (This question is asked a lot in discord)
=> Grammar issues in PR template

code/__HELPERS/_logging.dm, code/_globalvars/logging.dm, code/game/world.dm, goon/code/datums/browserOutput.dm
- Moves Goonchat chat debug logging to RUSTG
- It used direct output which sucks.
N/A
=> Moves Goonchat chat debug logging to RUSTG

code/modules/client/client_procs.dm
- Fix forum link runtime due to trying to concatenate a number to text
N/A
=> Fix forum link runtime

code/game/machinery/shieldgen.dm
Does as the title suggests. Shieldgens didn't clean up their shields. Now they do
Ensures they GC properly and don't drain server resources trying to hard del them
No functional changes
=> Makes machinery/shields GC properly

code/modules/mob/living/carbon/human/life.dm, code/modules/mob/living/carbon/human/species/_species.dm
Cold immunity now actually makes you immune to cold slowdown and damage.
Before, stuff like sling icy veins would still deal damage to people with cold immunity.
bugs are bad
:cl:
fix: cold immunity actually makes you immune to cold
/:cl:
=> Fixes cold immunity

code/modules/examine/descriptions/weapons.dm
Updates the weapon description file so captain and laser guns have the proper descriptions on them, and don't make guns that are useless that admins sometimes spawn when mistake.
Bugs are bad.
:cl:
fix: Fixes captains laser gun and AEGs from not having their correct description.
/:cl:
=> Fixes the descriptions so it doesn't make broke guns

code/game/objects/structures/loom.dm
Remove the \\the macro from loom.dm, and refer to W as `[W]` and not `[W.name]`
Add an extra . to the start weaving text, so it is a triple dot and not a double dot
Keeping code up to date with current standards is a good thing.
Triple dots usually indicate an ongoing process, where as double dots don't really mean anything.
:cl:
spellcheck: Add an extra dot to the end of the start weaving text for the loom
/:cl:
=> remove \the from loom.dm

code/game/dna/mutations/powers.dm
Captalizes the no-prints and x-ray deactivation messages
Proper grammar is good
:cl:
spellcheck: Capatilize the no-prints and x-ray deactivation messages.
/:cl:
=> capitalise the no-prints and x-ray deactivation messages

code/game/machinery/teleporter.dm
Fixes #16145
upgraded teleporters UI now shows proper calibration
bugs bad
:cl:
fix: upgraded teleporters UI now shows proper calibration
/:cl:
=> Fixes upgraded teleporters UI

code/game/atoms.dm
This PR fixes bot pathing that has been broken since #13652
Fixes #15667
Yes, I change one variable. Please don't send hatemail to mochi, we've all forgotten to change something after testing.
Bots will now behave as intended instead of getting suck on LITERALLY EVERYTHING.
:cl:
fix: Fixes bot pathing
/:cl:
=> Fixes bot pathing

code/game/mecha/mecha.dm
Adds an isai check to the exited proc of mechs, so they don't call go_out with force, which gibs the AI.
AIs exploding when you card them from a mech is not good.
:cl:
fix: Fixed AIs gibbing when being carded out of a mech.
/:cl:
=> Prevents AIS from gibbing when being carded from a mech

code/modules/clothing/suits/labcoat.dm
Labcoats can now store cyborg analyzers.
Being unable to store one of the most basic tools of your department is strange and goes against one of the tips.
:cl:
tweak: Labcoat can now store a cyborg analyzer.
/:cl:
=> Let's labcoats store cyborg analyzers.

code/modules/economy/EFTPOS.dm
The chef's EFTPOS  code parcel now spawns in the chef's backpack, instead of inside the chef. Fixes #16031
So the chef gets their EFTPOS code parcel.
:cl: Iwanabeu
fix: Chef's EFTPOS code parcel now spawns in their backpack instead of inside them.
/:cl:
=> EFTPOS code parcel now spawns in the chef's backpack.

code/modules/reagents/chemistry/machinery/reagentgrinder.dm
Fixes another instance of rogue characters in an interface
:cl:
fix: Fixed rogue characters in the grinder menu
/:cl:
=> Grinder rogue character fix

code/modules/world_topic/adminmsg.dm
Sanitizes incoming Discord PMs
Injection bad
:cl:
fix: Fix injection bug with incoming Discord PMs
/:cl:
=> Sanitizes incoming Discord PMs

code/_globalvars/lists/misc.dm
Makes the SyndicateTestLab network restricted, preventing AIs from seeing it
Closes #16310
The research base is supposed to be secret
:cl:
fix: AIs can no longer see the syndicate research base cameras
/:cl:
=> Prevent AIs from seeing the syndicate test lab, fixing #16310

code/game/objects/items/weapons/storage/belt.dm
Makes it so shotgun shells stack in bandoliers.
Quality of life change and makes bandoliers _somewhat_ worth using.
:cl:
tweak: Shotgun shells stack in bandoliers.
/:cl:
=> Bandolier shotgun shell stacking

code/modules/client/preference/loadout/loadout_general.dm
Adds a new category in the loadout menu for instruments.
Also moves the Synthesizer to this new category for obvious reasons.
You can already get a Synthesizer in the loadout which can replicate all other instruments, so this is much more of a fluff thing than anything big.
I know a few people who immediately go to the Merch Computer in cargo to get a guitar or other instrument, so this'll skip that step. It'll also help to alleviate any grinding that #15555 might introduce by having the instruments be arcade prizes.
This definitely won't invalidate getting them ingame via that or the instrument crates though, since each instrument costs 2 loadout points and, again, you can already get the Synthesizer.
:cl:
add: Added a new category in the Loadout menu for instruments!
/:cl:
=> Adds instruments to the loadout menu

code/game/mecha/equipment/tools/work_tools.dm
This PR Fixes #16249 by dusting the user and destroying the mech that tries to pick up the SM shard.
Exploit bad, dusting good.
:cl:
fix: Fixed a bug that allowed ripleys to pick up SM shards
/:cl:
=> Fixes an SM exploit with ripleys.

code/modules/admin/holder2.dm, code/modules/mob/dead/observer/observer.dm
Adds admin logging to toggling AntagHUD and DNR.
I'm honestly amazed that AntagHUD isn't logged already, considering the potential uses with metacomms. I can't help feeling that I'm missing some obvious reason here, but I guess I'll find out.
:cl:
add: Added admin logging for AntagHUD and DNR.
/:cl:
=> Logging for AntagHUD and DNR

code/__DEFINES/role_preferences.dm, code/__DEFINES/rolebans.dm, code/__HELPERS/game.dm, code/controllers/subsystem/ghost_spawns.dm, code/datums/datacore.dm, code/game/gamemodes/autotraitor/autotraitor.dm, code/game/gamemodes/blob/blob.dm, code/game/gamemodes/game_mode.dm, code/game/gamemodes/miniantags/borer/borer.dm, code/game/gamemodes/wizard/soulstone.dm, code/game/machinery/wishgranter.dm, code/game/objects/items/robot/robot_parts.dm, code/modules/admin/verbs/one_click_antag.dm, code/modules/admin/verbs/randomverbs.dm, code/modules/client/preference/preferences.dm, code/modules/mob/dead/observer/observer.dm, code/modules/mob/living/carbon/brain/robotic_brain.dm, code/modules/mob/living/silicon/pai/recruit.dm, code/modules/mob/living/simple_animal/hostile/terror_spiders/ghost.dm, code/modules/mob/transform_procs.dm
Adds a jobban category for Terror Spiders, fixed Cortical Borer jobbans being ignored, and swapped out a few `jobban_isbanned()` arguments with defines.
Tested a few of the other bannable antags and these are the only two I could find with the issue.
Fixes #16318.
If someone's been banned from a role, you'd generally expect that they won't be able to play the role anymore.
Also Terror Spiders having their own category just makes sense to me, since they're a pretty big antagonist and the only way to do it currently is a full antag ban.
*(god that UI is ugly)*
:cl:
add: Added a jobban category for Terror Spiders.
fix: Fixed some jobban categories not working.
/:cl:
=> Jobban adjustments

code/game/mecha/equipment/tools/work_tools.dm
title
exploits BAD
:cl:
fix: mechs cannot RCD indestructible walls
/:cl:
=> fixes mech RCDing indestructible walls 

README.md
Adds a link to the new Code of Conduct to the `README.md` file.
Currently `CODE_OF_CONDUCT.md` is just sitting in the main directory along with 15 other files, so there's an pretty low chance that a new contributor will actually read it, or even notice that it's there at all. I personally had to check the PR to find it since I had assumed it was in the `.github` folder.
The contents of `README.md` however shows up on Github under the main file list, so if they somehow still miss that they will have also missed the installation and contribution guides too. Still not foolproof, but a lot better than having it effectively hidden.
=> Adds a code of conduct link to the readme

code/game/machinery/teleporter.dm
I missed a pretty major case where the calibration would get reset to false
bugs are still bad
:cl:
fix: the teleporter UI no longer shows incorrect calibration
/:cl:
I am really sorry, I thought I fixed this...
=> Fixes the teleporters UI.... again

_maps/map_files/cyberiad/cyberiad.dmm
=> Revert "Re-adds engineering items to secure storage and main engineering storage (#15458)"

code/modules/mob/living/silicon/robot/robot_modules.dm, code/modules/projectiles/guns/energy.dm, code/modules/projectiles/guns/energy/stun.dm
Fixes #16398.
:cl:
fix: Fixes a bug where a Cyborg's laser gun wasn't recharging properly in cyborg rechargers
/:cl:
=> Fixes a bug where a Cyborg's laser gun wasn't recharging properly in cyborg rechargers

code/game/gamemodes/miniantags/revenant/revenant_abilities.dm
fixes revs destroying admin walls
bugs bad
:cl:
fix: revenants no longer destroy admin walls with defile 
/:cl:
=> Fixes revs destroying admin walls

code/modules/mining/machine_redemption.dm
Fixes #16414 causing the ORM to *only* accept ores, and not regular sheets/floor tiles.
Basically reverts most of that PR and does it better.
Oversight on my end, whoops.
:cl:
fix: Fixes the ORM not accepting refined sheets as an input.
/:cl:
=> ORM manual insertion fix fix

.github/CONTRIBUTING.md
This PR adds some general rules and principles that people should follow when mapping for paradise. Most of them are common sense things, and the list is not exhaustive for every small scenario. The guidelines cover the most commonly seen mapping mistakes, and setting a point for every mistake ever is not feasible.
[There has been a feedback thread on the forum for a week with no objections.](https://www.paradisestation.org/forum/topic/20824-addition-to-the-mapping-standards-section-of-contribution-guidelines/)
Consistency will be key for paradise moving forward, especially now map rotation is implemented.
Having guidelines helps PR reviewers express that suggested changes are not due to personal preference, but are due to the standards we follow.
Having some guidelines in place will also …
=> Addition to contribution guidelines, mapping section.

code/game/objects/items/weapons/AI_modules.dm
Remove the quotes from the freeform core module to have it conform to the new standard and prevent this from happening : 
I thought I got them all but messed up when deconflicting the PR. This standardises the module with all others.
Looks better, is now the same as other law boards
:cl:
fix: Fixed freeform core causing a visual bug in the AI law vendors.
/:cl:
=> Fix visual bug in AI law vendor

code/modules/research/designs/weapon_designs.dm
Adds a design for the BSG to rnd, to actually make it producible, like intended. Has heavy RND costs.
Actually being able to craft the gun in RND, like intended, is a good thing. Fixes me being dumb and not giving it a RND design.
:cl:
fix: Fixes the BSG not having a design in the protolathe.
/:cl:
=> Adds the BSG to RND designs

code/modules/mob/living/simple_animal/friendly/farm_animals.dm
Makes all goats female.
All goats can be milked and have udders. They shouldn't ever be male. Very similar PR to #14025
:cl:
fix: All goats are now female.
/:cl:
=> Makes goats female

.github/DOWNLOADING.md
Updates some documentation that I forgot when doing the TOML config
Up to date documentation is good
=> Updates some documentation

code/datums/radiation_wave.dm
I believe this broke the supermatter
=> Revert "Fixes rad contamination being 10x stronger than intended"

code/__HELPERS/traits.dm, code/modules/reagents/chemistry/reagents/admin.dm
Refactors the `ADD_TRAIT()`, `REMOVE_TRAIT()`, `REMOVE_TRAITS_NOT_IN()`, and `REMOVE_TRAITS_IN()` defines in order to make them actually readable, and adds documentation for good measure.
(Definitely recommend looking at the before/after files rather than the diff when reviewing this.)
Also fixes adminordrazine removing *all* traits, including inherent species ones.
Admittedly I've been staring at this code for six hours so it may just be me, but personally I find that this:
```dm
#define ADD_TRAIT(target, trait, source) \
do { \
LAZYINITLIST(target.status_traits); \
\
if(!target.status_traits[trait]) { \
target.status_traits[trait] = list(source); \
} else { \
target.status_traits[trait] |= list(source); \
} \
\
SEND_SIGNAL(target, SIGNAL_ADDTRAIT(trait), trait); \
} while (0)
```
is a …
=> Trait Define Refactor

code/modules/admin/player_panel.dm
QoL for admins.
:cl:
add: Adds a FLW button in the check antagonists page for blob-infected players
/:cl:
=> Adds a FLW button for blob-infected players in the check antagonists page 

code/modules/clothing/suits/armor.dm
Fixes trenchoat mispelling to trenchcoat
fixed #16446 
Less spelling mistakes is always good
:cl:
spellcheck: Fixed Trenchoat to Trenchcoat in armor.dm
/:cl:
=> Trenchoat-->trenchcoat

tools/map_conflict_fixer/README.md
Tweaks the `/tools/map_conflict_fixer/README.md` file so that the markdown styling actually works.
Just something I noticed while browsing the /tools folder.
It's a `.md` file, so clearly intended to use markdown.
**Before:**
**After:**
N/A
=> Map conflict fixer README markdown fix

code/modules/mob/living/living.dm
Adds a check to movement that prevents you pushing a person that is pulling you, however on help intent you can move through them.
Being able to push someone that is pulling you to move faster is bad, and still lets you move past them on help intent. Inspired by #12646 
:cl:
fix: You can no longer push a person pulling you, however you can move through them on help intent.
/:cl:
=> Prevents pushing a person that is pulling you

code/modules/mob/living/simple_animal/hostile/terror_spiders/actions.dm
- Re-ups terror web deletion timer to 7 seconds as the change was a regression
- Fixes #16455
- Undoes a massive grey terror nerf
:cl:
fix: Terror spider webs no longer delete instantly
/:cl:
=> Re-ups terror web deletion timer to 7 seconds

code/modules/mob/living/silicon/robot/robot.dm, code/modules/mob/living/silicon/robot/robot_modules.dm
See the CL.
:cl:
fix: The Cyborg Immolator Cannon and Cyborg Pulse Rifle will now recharge properly
fix; Spawned preset cyborgs like the "destroyer" module cyborg will no longer have a baton without a power cell.
/:cl:
=> Fixes more issues with certain cyborg rechargable items

code/game/dna/mutations/powers.dm
Adds a check for actually having eyes, to the morph power, so you don't runtime and can continue using the ability
Runtimes and bugs are bad.
:cl:
fix: Fixes morph gene not working for slimes
/:cl:
=> Fixes morph for slimes

code/game/objects/items/devices/painter/painter.dm
Fixes the weird icon of the floor painter in the autolathe.
Looks weird currently.
From:
To:
:cl:
fix: Fixed the modular painter missing an icon.
/:cl:
=> Fixes the floor painter icon state

code/game/objects/structures/girders.dm
Renames `/obj/structre/girder/detailed_examine()` to `/obj/structure/girder/detailed_examine()`.
(#16330)
English is hard okay.
N/A
=> Structre spelling fix

code/modules/admin/verbs/one_click_antag.dm
Adds the number of vampires being made by one click antag to the log
Tracking is good
:cl:
tweak: One click antag now logs the number of vampires created
/:cl:
=> Makes making multiple vampires log the number

code/modules/customitems/item_defines.dm
Changes some of the grammar of my fluff items so that it looks less awkward upon examination of Hyperion.
Grammar
:cl:LightFire53
tweak:Fluff grammar
/:cl:
=> LightFire53 Fluff Item Grammar

code/__HELPERS/lists.dm, code/_onclick/item_attack.dm, code/datums/spell.dm, code/game/gamemodes/blob/powers.dm, code/game/gamemodes/cult/runes.dm, code/game/gamemodes/miniantags/guardian/host_actions.dm, code/game/gamemodes/miniantags/slaughter/slaughter.dm, code/game/machinery/transformer.dm, code/game/objects/effects/anomalies.dm, code/game/objects/effects/spiders.dm, code/game/objects/items/weapons/implants/implant_explosive.dm, code/game/objects/items/weapons/pneumaticCannon.dm, code/game/objects/items/weapons/storage/storage.dm, code/game/objects/structures/displaycase.dm, code/game/objects/structures/inflatable.dm, code/modules/antagonists/_common/antag_datum.dm, code/modules/antagonists/_common/antag_spawner.dm, code/modules/awaymissions/mission_code/academy.dm, code/modules/events/spacevine.dm, code/modules/hydroponics/hydroitemdefines.dm, code/modules/mining/equipment/resonator.dm, code/modules/mining/lavaland/loot/tendril_loot.dm, code/modules/mob/living/simple_animal/friendly/farm_animals.dm, code/modules/mob/living/simple_animal/hostile/megafauna/bubblegum.dm, code/modules/mob/living/simple_animal/hostile/venus_human_trap.dm, code/modules/mob/mob_helpers.dm, code/modules/recycling/sortingmachinery.dm, code/modules/research/xenobiology/xenobiology.dm
Fixes #16400
Fixes #16382
Fixes #16381
Fixes #16378
Fixes #16377
Fixes #16366
Fixes #16365
Fixes #16352
Fixes #16323
Fixes #16295
Fixes macro/microbomb implants causing `to_chat()` runtimes if they were spammed.
Fixes cows mooing in lowercase.
Each fix is in a separate commit to make it (in theory) easier to review.
:cl:
tweak: Display cases now open when emagged, rather than just unlocking.
tweak: Inflatable barriers can now be burst with sharp or pointed items.
fix: Fixed a runtime caused by explosive implant detonations being queued.
fix: Fixed being unable to package wrap a filled box.
fix: Fixed venus human traps becoming invisible when ahealed.
fix: Fixed the 'Aggressive spreading' kudzu mutation damaging flower pods and venus human traps.
fix: Fixed the 'spooky lantern' not …
=> Fix bundle #3

.github/CONTRIBUTING.md
Updates the `CONTRIBUTING.md` guidelines file to improve the grammar, consistency, code examples, and overall readability throughout the whole thing.
There's quite a few minor issues with the current file, namely very inconsistent punctuation, confusing or misleading code examples, and this:
There's still a few places which could be tweaked more of course, but this pass has definitely improved the overall accessibility of the file for new contributors, even if only by a small amount.
N/A
=> Contributing guidelines readability tweaks

code/modules/antagonists/traitor/contractor/datums/objective_contract.dm
Removes the 'Central Primary Hallway' from the list of possible contract target locations.
The 'Central Primary Hallway' is actually *eight* separate areas, each shown in different colours on the image below. Having to run circles around the entire thing along with your target and half of security chasing you might be enjoyable sometimes, but it's a massive jump in difficulty compared to the rest of the locations and most likely not intentional.
There's also been a few mentorhelps about this recently which couldn't be properly answered since there's no actual way of knowing which area the game picked without VV diving.
:cl:
del: Removed the Central Primary Hallway from the list of possible contract extraction locations.
/:cl:
=> Removes the Central Hallway from the list of contract locations

code/modules/mob/dead/observer/observer.dm, code/modules/mob/new_player/new_player.dm
QoL for admins.
:cl:
tweak: Admins who ghost have their Antag HUD defaulted to On
/:cl:
=> Admins who ghost have their Antag HUD defaulted to On

code/__HELPERS/type2type.dm
Prevents a possible infinite `while()` loop in the `num2hex()` proc, caused by sending a negative number as an argument.
Fixes #16540.
While the main server likely has failsafes against this, a (not uncommon) proc being able to completely freeze everything just from a single bad argument isn't really a good thing.
N/A
=> Fixes `num2hex()` being able to freeze the server

code/game/gamemodes/changeling/changeling.dm, code/game/gamemodes/cult/cult.dm, code/game/gamemodes/shadowling/shadowling.dm, code/game/gamemodes/traitor/traitor.dm, code/game/gamemodes/vampire/traitor_vamp.dm, code/game/gamemodes/vampire/vampire.dm, code/game/jobs/access.dm, code/game/jobs/job/central.dm, code/game/machinery/tcomms/nttc.dm
This PR renames all instances of "Solar Federation Brigadier General" to "Solar Federation General"
The job takes up too much space for this crappy UI to handle, as AA pointed out above, and the title is a mouthful.
:cl:
tweak: Changed "Solar Federation Brigadier General" to "Solar Federation General"
/:cl:
=> Renames Brigadier General to just General

code/modules/antagonists/traitor/contractor/datums/contractor_hub_ui.dm, code/modules/antagonists/traitor/contractor/datums/objective_contract.dm
- Possibly fixes being unable to call contractor extraction in some cases, extended TM required.
Bugfix, but not yet nailed down
:cl:
fix: Possibly fix contractor extraction not being callable
/:cl:
=> [TM NEEDED] Possibly fix being unable to call contractor extraction

code/__DEFINES/genetics.dm, code/game/gamemodes/changeling/powers/tiny_prick.dm, code/modules/mob/living/carbon/human/species/machine.dm, code/modules/mob/living/carbon/human/species/plasmaman.dm, code/modules/mob/living/carbon/human/species/vox.dm
Removes transformation sting as a cling ability.
While a nice ability in theory, this ability is often never used in great ways. Instead of being used as a distraction to throw sec off themself, it is often used in the following ways.
Turning everyone into a fat vulp/tarajan/wingdings grey / whatever with disabilities. (breaking advanced rules)
Turning everyone into you / a known character. (breaking advanced rules)
Using transformation sting to make officers useless / stupidly easy to kill, with no way to rectify it.
When an ability has to have species blacklisted from it, you know it is an issue. Earlier, it was brought to my attention that golems in their entirety might need blacklisting, as such, I considered removing transformation sting as an option.
:cl:
del: Removes transformation …
=> Removes transformation sting

code/modules/mob/living/silicon/robot/robot.dm, code/modules/mob/living/silicon/robot/robot_modules.dm
`/mob/living/silicon/robot/Move()` is pretty bad currently. It checks if the borg has a module, then checks if that module is the janitor module. All so the borg can clean things on the tile. This PR simply extracts the cleaning code onto the janitor module and makes use of the `COMSIG_MOVABLE_MOVED` signal, so only janitor borgs trigger the cleaning code.
N/A
=> Minor cyborg Move refactor

code/game/machinery/computer/message.dm
I dont even have the energy for the template anymore
This broke as part of #16609 
:cl:
fix: Monitor decryption key works again
/:cl:
=> Fixes monitor decryption key

_build_dependencies.sh, code/_compile_options.dm, code/controllers/subsystem/metrics.dm, code/modules/client/client_procs.dm
fuck the break Im doing this before I perish to burnout
Updates the code to take advantage of 514 features and get everyone on the new client.
New version good.
N/A
=> The 514 patch

code/modules/admin/verbs/adminsay.dm
Logs messages in msay in logging view, under OOC, under the format of MSAY: (insert mentor text here)
Better logging is better. 
:cl:
tweak: MSAY is now logged under OOC in logging view.
/:cl:
=> Puts MSAY in OOC logging view

_maps/map_files/Delta/delta.dmm
This PR tackles the following delta issues:
- All deliveries went to bartender because of a hidden bent pipe
- Cargo conveyors did not align with shuttle conveyors
- Random button for mechanic that does nothing
- Punpun spawned in the kitchen (no chef, that does not mean you can legally slaughter him)
- Toxins launch shutter did not open for some reason
- Toxins burn chamber space vent had sec access
- Toxins burn chamber igniter had no button
- Barber had no atmos connection
- Pod pilot buttons opened main pod bay doors
- Engine containment SMES was feeding itself, leading to containment failures
- No cleaning stuff in medbay
- Atmos mix to filter went nowhere
- Random pipe near vault
- NTR office electrochromic windows were not properly smoothing
Note: Despite being reported as broken, …
=> Even more delta fixes

code/game/gamemodes/changeling/powers/epinephrine.dm
Fixes #16508.
Originally fixed in #16520, but reverted due to various other issues caused by that PR.
Permanent blindness isn't a good thing for an antagonist to have.
https://user-images.githubusercontent.com/57483089/132929985-8f7af65d-c188-4747-80a4-69145108ebcf.mp4
https://user-images.githubusercontent.com/57483089/132929988-a873f44e-6370-43ae-96e4-81f4d218a791.mp4
(The second took twice as long to heal because it doesn't like me)
:cl:
fix: Fixed using 'Epinephrine Overdose' as a changeling to wake up causing permanent blindness in some circumstances.
/:cl:
=> Epinephrine overdose blindness fix

code/modules/atmospherics/machinery/atmospherics.dm
This PR fixes a runtime I unwittingly introduced with transparent turf values of null turfs.
Thousands of runtimes bad, good code good.
:cl:
fix: Fixed a bug with null turfs
/:cl:
=> Fixes runtimes in null turfs

_maps/map_files/Delta/delta.dmm
The merge for #16547 didn't go well, and resulted in the entire security section missing its changes. The rest of the station wasn't affected, which had the side effect of disconnecting the dorms from the rest of the network in the process.
Pipes are set proper again, and brig phys had some tweak in its layout to accommodate for a bin. Some sort pipes also had leftover pipes under them and were removed. Bar also had its ID fixed.
Makes things go where they should.
:cl:
add: delta.dmm - Added a disposal bin in brig physician
add: delta.dmm - Added sorting junction for the Brig Physician
tweak: delta.dmm - Moved things around in Brig Physician's room
tweak: delta.dmm - Touched up the layout of the pipes
fix: delta.dmm - Fixed the sort IDs for Sec junctions and Bar junction
del: delta.dmm - …
=> DeltaStation Disposals - Fix missing security section + Quick clean up

_maps/map_files/MetaStation/MetaStation.dmm
Replaces most if not all instances of departmental clothing lockers on metastation with clothing vendors from #16489
Replaces the frankly awful lockers with a better alternative, the clothing vendors.
:cl:
tweak: Replaced all departmental clothing lockers with appropriate departmental clothing vendors on metastation/Cerebron
/:cl:
Due to the mapping queue moving, this PR will be deconflicted upon request.
=> Mapped in departmental clothing vendors to metastation/Cerebron

.github/workflows/generate_autodoc.yml
Fixes syntax in autodoc file
*sigh*
=> I am dumb and cant write yaml

.github/CONTRIBUTING.md
=> Add guideline to disallow fix bundling and excessively large PR

_maps/map_files/Delta/delta.dmm
This removes the near majority of reinforced walls sitting under grille around the station, and also cleans things up a little bit as there is too much lattice or grille otherwise. The SM still has an extra layer of protection, but is styled the same way as on BoxStation.
This makes meteor strikes matter a bit more since the whole station isn't protected by double or sometimes triple layers of reinforced walls. Likewise, players won't have their backs against said extra layers of walls.
:cl:
del: Removed almost all the reinforced walls in space
tweak: Placed or removed lattice and grilles as needed for style.
/:cl:
=> DeltaStation - Purge of the space reinforced walls

_maps/map_files/Delta/delta.dmm
Replaces most if not all instances of departmental clothing lockers on deltastation with clothing vendors from #16489
Replaces the frankly awful lockers with a better alternative, the clothing vendors.
:cl:
tweak: Replaced all departmental clothing lockers with appropriate departmental clothing vendors on deltastation/Kerberos
/:cl:
Due to the mapping queue moving, this PR will be deconflicted upon request.
=> Mapped in departmental clothing vendors to deltastation/Kerberos

code/modules/food_and_drinks/food/foods/candy.dm, code/modules/food_and_drinks/food/foods/ethnic.dm, code/modules/food_and_drinks/food/foods/junkfood.dm
Adds `antable = FALSE` to the following foods:
**4no Raisins:**
**Admiral Yamamoto Carp:**
**Bread Tube:**
**Candy:**
**Cheesie Honkers:**
**Chinese Newdles:**
**Chips:**
**Chow Mein:**
**Fried Rice:**
**Pistachios:**
**Scaredy's Private Reserve Beef Jerky:**
**Syndi-Cakes:**
(Same idea as one of the fixes in #16520, but expanded upon a bit.)
All of those foods have wrappers or containers, so it makes sense to me that ants wouldn't be able to get to them. I know I at least have been caught up in the past trying to eat some unopened 'Cheesie Honkers', only to find that ants somehow got through the packaging.
Basically, it's just less unintuitive.
:cl:
tweak: Prevented ants from getting into wrapped food from vending machines.
/:cl:
=> Prevents ants from infesting wrapped/packaged food

code/modules/events/rogue_drones.dm
Fixes a typo in the rogue drone event announcement.
`"Targetted"` > `"Targeted"`
(Originally fixed in #16520, but reverted due to various other issues caused by that PR.)
Typo
:cl:
spellcheck: Replaced "Targetted" with "Targeted" in the rogue drone event announcement.
/:cl:
=> Targetted drone announcement fix

code/datums/progressbar.dm
Makes the `do_after()` progress bar render on `ABOVE_HUD_LAYER`/`ABOVE_HUD_PLANE`, rather than `HUD_LAYER`/`HUD_PLANE`.
The normal HUD elements always take priority over the progress bar, so currently they just hide it completely.
(Originally fixed in #16520, but reverted due to various other issues caused by that PR.)
Progress bars being hidden behind the normal HUD is clearly not intentional, and this allows it to always be visible.
https://user-images.githubusercontent.com/57483089/132930411-5491c332-f35d-4623-bbc9-af027a7a7c3d.mp4
https://user-images.githubusercontent.com/57483089/132930412-f922e1e5-7614-4bf8-9bdd-2ea683ed5c1c.mp4
:cl:
tweak: Made progress bars show above regular HUD elements.
/:cl:
=> Makes progress bars render above the game HUD

code/modules/projectiles/guns/projectile/automatic.dm
fixes runtime
runtimes bad
:cl:
fix: nukie grenade launchers properly show the shell ejection message.
/:cl:
=> Runtime fix with the nukie grenade launcher

code/modules/projectiles/gun.dm
runtimes are bad, fixes one.
runtimes bad
N/A
=> Gunlight runtime fix

_maps/map_files/generic/Lavaland.dmm, _maps/map_files/generic/centcomm.dmm
This maps in dirs for all CC and lavaland consoles.
Consoles facing walls are bad, actual directions are brug.
:cl:
tweak: All CC and lavaland consoles have proper dirs
/:cl:
=> cc and lavaland directional console mapping

_maps/map_files/MetaStation/MetaStation.dmm
This maps in dirs for all metastation consoles.
Consoles facing walls are bad, actual directions are brug.
:cl:
tweak: All meta station consoles have proper dirs
/:cl:
=> Meta directional console mapping

_maps/map_files/Delta/delta.dmm
This maps in dirs for all delta station consoles.
Consoles facing walls are bad, actual directions are brug.
:cl:
tweak: All delta station consoles have proper dirs
/:cl:
=> Delta directional console mapping

_maps/map_files/Delta/delta.dmm
- Fixes delta SM APC not being wired, puts SM net on yellow wires for clarity.
- Fixes psych lobby technically being in maints.
- Fixes unconnected atmos tank ports in AI sat.
- Fixes sinks floating on walls.
- Fixes missing console for toxins burn chamber.
- Fixes missing space cleaner refiller in janitor closet.
- Fixes dodgy chemistry smartfridges
Map refinement baby, if sinks are the only issue we are doing well.
:cl:
fix: Fixed various delta station issues.
/:cl:
=> Another delta fix PR

code/modules/mob/living/simple_animal/friendly/diona.dm
Adds isrobot check to diona nymphs attack hand proc to prevent Cyborgs from picking up diona nymphs.
Bugs are bad. Fixes #16752.  Dionas shouldn't be permanently trapped inside Cyborgs.  
:cl:
fix: Cyborgs no longer trap Diona Nymphs inside their Hugging Module for all eternity.  
/:cl:
=> Prevents Robots from Consuming Diona Nymphs

code/game/verbs/webmap.dm, code/modules/client/client_procs.dm, code/modules/mapping/base_map_datum.dm, code/modules/mapping/cyberiad.dm, code/modules/mapping/delta.dm, code/modules/mapping/metastation.dm, interface/skin.dmf, paradise.dme
Adds a webmap button
Fed up of "whats this map" mhelps
add: Added a button for the current map's webmap
/:cl:
=> Adds a webmap button

_maps/map_files/Delta/delta.dmm
Changes the tag of disposals sorting junction so crates from cargo now end up in kitchen and not back in cargo.
Disposals work as intended.
:cl:
tweak: Deltastation: sending crates to kitchen by disposals from cargo works now.
/:cl:
=> Deltastation: Sending crates to kitchen by disposals works now.

code/game/objects/effects/decals/Cleanable/humans.dm
Changes the description of a drop of blood from:
desc = "It's red."
To:
desc = "A drop of blood in an ocean of mess."
Blood drips are not always red because of different species, so the old description could be hilariously wrong, with green blood being described as red. Thus, changing the description of blood drips to be something more generic is good.
:cl:
fix: Blood drips no longer say "It's red.", Even when the blood is green, or white, or blue.
/:cl:
=> Changes the description of a drop of blood

code/modules/power/treadmill.dm
Adds a Move_Resist check to make sure ghosts aren't thrown off by Treadmills when someone is running on them.  
Fixes #16757.  Bugs are mad mmkay.  
:cl:
fix: Fixes ghosts being thrown off/from Treadmills when a carbon mob is running on one.  
/:cl:
=> Fixes Treadmills throwing ghosts around when in use

_maps/map_files/Delta/delta.dmm
Adds furnishing and decoration to the lobby of science and medbay.
People complain about Delta being too open and empty. This should be an easy way to fix some of that.
:cl:
add: Added furniture and decoration to DeltaStation medbay and science lobbies.
/:cl:
=> Medbay and Science Lobby Revamp (DeltaStation)

_maps/map_files/MetaStation/MetaStation.dmm
Someone double piped meta, causing lots of runtimes.
This fixes that.
No runtimes, please and thank you.
:cl:
fix: Fixed double pipes in metastation
/:cl:
=> Fixes 2029 metastation runtimes

code/game/machinery/machinery.dm
- If you use RPED with cells - it check only rating part.
- Potato rating is 1 so every other cell is better. Even "Nanotrasen brand rechargeable AA battery" - cell/crap
- Now RPED will pick battery with better max charge. If max charge same - battery with highest current charge.
- Now botany can grow potato cells for R&D
- Now R&D willn't repace better cells with crapy one
:cl:
tweak: Now RPED replace cells according max and current charge ignoring rating
/:cl:
=> RPED replace cell according max and current charge

code/modules/food_and_drinks/kitchen_machinery/smartfridge.dm
Fixes #16828 by making items loaded into smart fridges appear as normal without the garbled string.
This issue keeps popping up all over and it is very ugly and annoying. Begone `&#39;`, we prefer your real sibling, `'`
:cl:
fix: Fixes rogue characters in smart fridges.
/:cl:
=> Fixes rogue characters on smartfridge contents

.github/CONTRIBUTING.md
Spoke to the other maintainers. This is the way forward.
**Existing PRs are not impacted.** 
And yes I know the whitespace diff is fucked up
=> Ammends mapping standards in CONTRIBUTING.md

_maps/map_files/cyberiad/cyberiad.dmm
Oops I can't map properly I left areas of maints marked as space for AA's pod removal PR. This fixes that.
:cl:
fix: Fixed some maints being space on box
/:cl:
=> Fixes space in engi maints

_maps/map_files/Delta/delta.dmm
Actually allows atmospheric technicians to use the SM shutters now on DeltaStation. Also, fixes my mishap involving airlocks by engine access and the breakroom, while using a proper freezer in atmospherics.
Testing with a CE outfit instead of a proper atmos outfit may produce incorrect results in testing. This fixes those incorrect results. And yes, I did use an atmos tech outfit and a station engineer outfit this time.
:cl:
fix: DeltaStation Engineering Airlocks now don't require both atmos tech and engineer access for engine access and breakroom
fix: DeltaStation SM shutters now work for atmos techs
fix: DeltaStation Atmospherics rogue freezer has now been put in line
/:cl:
=> Fixes DeltaStation Mishaps in Engineering

code/game/machinery/computer/arcade.dm
Adds hidden fingerprint logging to arcade machines when being emaged.
Logging is good. Note, this does not leave prints that can be detective scanned.
:cl:
tweak: Arcade machines now have hiddenfingerprints when emaged.
/:cl:
=> Adds hidden fingerprint logging to emaging arcade machines

.github/CODEOWNERS, .github/CONTRIBUTING.md, tools/github-actions/README.MD
Removes my status as a code-owner from repository files, removes my name from the maintainer list, and also cleans up something I forgot a while back.
=> The end of an era

.github/DOWNLOADING.md
Adds a special flag (`--depth 1`) that allows you to clone faster.
That happens because you only download the last commit (because of the number one).
Better docs.
=> Shows how to clone faster in the docs

code/modules/recycling/disposal.dm
Checks if the item being disposed on the disposal is abstract before continuining, preventing #17003 from happening.
Drops items with the DROPDEL flag.
Refactors a bit of the code. 
Can't lose your hand down the trash anymore.
Items with the DROPDEL flag now get properly dropped.
Fixes #17003
*Alt text: A coroner is trying its best to trash their own hand but can't because of this PR.*
:cl:
fix: Can't dispose abstract items such as a slapping hand anymore
fix: Items marked for deletion are deleted when disposed
/:cl:
Thanks to @farie82 for helping me with this.
=> Can't dispose abstract items #17003

code/game/objects/items/weapons/implants/implanter.dm
`attemping` -> `attempting`
Fixes #17026 
:cl:
fix: Fixes a spelling error when implanting others
/:cl:
=> Fixes a spelling mistake in implanter.dm

.github/CODEOWNERS
Makes @dearmochi code owner of TGUI stuff now.
She knows it in more detail than me and this makes sense for the repo, especially since I dialed duties way back.
=> Hands TGUI ownership over to mochi

.github/DOWNLOADING.md
Continues #17006.
As requested, I tested if pushing after using the `--depth 1` flag was going to pull all commit history and it didn't. Until new commits were added.
Today when I tried to pull, all the commits were being downloaded and then I realized my mistake. This updates the docs so other users don't have to deal with this.
Better docs.
=> Adds faster downloads to push too

code/modules/mob/living/living.dm
fixes an exploit allowing you to throw a person who is dragging you, making you go zoomie fast.
exploits bad
:cl:
fix: fixes an exploit involving throwing a mob dragging you.
/:cl:
=> Fixes a throwing exploit

.github/gbp.toml
Sprites & Sounds are now worth `1` not `3`. Requested by Fox.
=> Tweaks GBP values

code/game/gamemodes/miniantags/abduction/abduction_gear.dm, code/game/objects/structures/crates_lockers/crates.dm, code/game/objects/structures/crates_lockers/crittercrate.dm, code/modules/mining/lavaland/necropolis_chests.dm, code/modules/mining/mine_items.dm, code/modules/mob/living/simple_animal/hostile/mimic.dm
Fixes a bug I stupidly introduced when renaming crate files without checking them after.
They needed an _ in them
Sprites that work, please.
:cl:
fix: Fixed invisible open crate sprites
/:cl:
=> Fixes open crate sprites

code/modules/martial_arts/combos/krav_maga/leg_sweep.dm, code/modules/martial_arts/combos/krav_maga/lung_punch.dm, code/modules/martial_arts/combos/krav_maga/neck_chop.dm, code/modules/martial_arts/krav_maga.dm
Fixes krav combos/disarms not having animations
attacks should be obvious for who is attacking.
The disarms when they fail sound like hugs, and have no animation. attacks should be distinguishable from hugs.
:cl:
fix: krav now properly has animations.
/:cl:
=> Fixes krav's animations

_maps/map_files/Delta/delta.dmm
Adds a robotic storage unit to DeltaStation's Mechbay. Also moves some light switches around to not be sitting on other objects.
DeltaStation currently only has one on the AI sat, making one more accessible will make it more likely to be used by sleepy cyborgs.
:cl:
tweak: Adds a robotic storage unit to DeltaStation Mechbay
/:cl:
=> Adds Robotic Storage Unit to DeltaStation Mechbay

_maps/map_files/Delta/delta.dmm
Expands the DeltaStation Internal Affairs Office to support having two Internal Affairs Agents, giving them two desks as well as other Internal Affairs quality of life updates such as electrochromic windows, and an SOP library.
We have two IA job slots, they should both have somewhere to call home. Also moves some wiring around to make it make more sense.
Old IA Office
New IA Office
:cl:
tweak: Remaps DeltaStation IA Office to support double IAA jobslots
/:cl:
=> Adjusts DeltaStation IA Office to support two IA Agents and other QoL changes

code/modules/station_goals/dna_vault.dm
Removes Leg Muscle Stimulus from the DNA Vault
This DNA power quite literally gives you the `GOTTA_GO_FAST` trait. For those who dont know what that means, its the same trait you get for using Meth.
Speed is the strongest thing combat-wise in this game. I have no idea why it was even added in the first place. Its an RNG free with for any antag/Security/etc who get it if you have even a modicum of skill.
:cl:
del: removes Leg Muscle Stimulus from the DNA Vault
/:cl:
=> Removes Leg Muscle Stimulus from DNA Vault

code/modules/mob/living/carbon/human/update_icons.dm
- Fixes a code issue introduced in #16172 that broke hair for all machine people.
- IPCs are no longer forcibly bald.
:cl:
fix: Fixes hair not appearing on IPCs
/:cl:
=> Fixes hair for IPCs

code/modules/clothing/spacesuits/plasmamen.dm
plasmaman overlays update properly. 
fixes #17066
less confusion
bugs bad
:cl:
fix: plasmaman helmet's sprite now updates when its light is extinguished.
/:cl:
=> Sling veil now properly updates plasmamans helmet sprites.

_maps/map_files/Delta/delta.dmm
Fixes a power oversight that was initially fixed, but then unintentionally reverted. Internal Affairs will now receive power and cables won't run through walls anymore.
I borked things up, I should unbork them.
Old
New
:cl:
fix: DeltaStation IA Office now receives power
/:cl:
=> Gives IA Office Power on DeltaStation

code/game/gamemodes/miniantags/revenant/revenant.dm
Changes revenants being nullified by the chaplain to false by default.
Fixes bug #17097 introduced in #17059 preventing revenants from doing anything
:cl:
fix: Fixes revenants not able to use abilities.
/:cl:
=> Fixes revenant ability bug

code/modules/surgery/organs/organ.dm
- Fixes a runtime on organ processing in some cases.
Not user facing so no changelog.
=> Fixes a runtime on organ processing

code/game/objects/items/random_items.dm, code/game/objects/structures/crates_lockers/closets/gimmick.dm, code/game/objects/structures/crates_lockers/closets/secure/personal.dm
fix: #17060
this time on the right branch
Bugs bad
:cl:
fix: Cabinet doors will no longer turn into locker doors when opened
/:cl:
=> Fix cabinet doors 2: Electric boogaloo

code/modules/fish/fish_items.dm, code/modules/hydroponics/grown/banana.dm
As per title.
:cl:
fix: Clownfish are no longer invisible
/:cl:
=> Fix - clownfish are no longer invisible

code/game/objects/structures/table_frames.dm
- Fixes `The table frame taking damage after deletion` introduced in #17038 
Runtime fix, not user facing.
=> Fixes runtime on table frame completion

code/game/machinery/vending.dm
The EngiDrobe vendor will no longer thank you for using the SciDrobe.
Fix I suppose
:cl:
fix: The EngiDrobe no longer misidentifies itself when vending things.
/:cl:
=> The EngiDrobe vendor no longer misidentifies itself when vending things

code/datums/uplink_item.dm
Updates the description of advanced mimery in the uplink to accurately reflect the changes to it in #17075
Uplink descriptions should make it clear what an item does.
:cl:
fix: Updates the description of advanced mimery in the uplink to accurately reflect the changes to it.
/:cl:
=> Minor uplink description update advanced mimery

code/modules/mob/living/simple_animal/bot/bot.dm
Removes "has" from simple animal attack_animal text for grammatical correctness.
Old:
Gooder grammer is bestest!
:cl:
fix: Remove "has" from simple animal attacktext
/:cl:
=> Remove unnecessary "has" from attack text of simple animals towards other animals

code/modules/recycling/conveyor2.dm
Makes conveyors linked to levers GC properly
fixes #17128 
GCing propa is good
N/A
=> Makes Conveyors GC properly

_maps/map_files/Delta/delta.dmm, _maps/map_files/RandomRuins/SpaceRuins/clownmime.dmm, _maps/map_files/RandomRuins/SpaceRuins/ussp.dmm, _maps/map_files/RandomRuins/SpaceRuins/wizardcrash.dmm, _maps/map_files/RandomZLevels/beach.dmm, _maps/map_files/cyberiad/cyberiad.dmm, _maps/map_files/generic/Lavaland.dmm
Should ensure that no more invisible crates remain on any maps/ruins
fix: #17137
WATCH AS I CONJURE A CRATE OUT OF THIN AIR!
:cl:
fix: Invisible crates and lockers now visible once again.
/:cl:
=> Fixes all remaining invisible crates/lockers

code/modules/paperwork/faxmachine.dm
Cleans up UI interaction errors with the fax machine once and for all.
This _should_ be the last of the issues that my photocopier refactor PR causes
will the pain finally end?
:cl:
fix: You can use buttons on the Fax Machine Interface again
/:cl:
=> Fax Machine Hotfix

code/modules/research/server.dm
Rename Robotics and Mechanic R&D Server to Robotics R&D Server
Mechanic is purged
:cl:
fix: Renamed Robotics and Mechanic R&D Server to Robotics R&D Server.
/:cl:
=> Removes mention of mechanic in RND Robotics server

code/game/gamemodes/vampire/vampire_powers/hemomancer_powers.dm
Fixes blood tendrils not working in dark areas because `view()` fails.
~~`dview` is hacky, another way to fix this could be making the tendrils emit light, if that was wanted.~~
now uses `range()`
fixes #17134
bugs bad
:cl:
fix: blood tendrils work properly in the dark.
/:cl:
=> [GBP: no change] blood tendril fix

code/__DEFINES/math.dm, code/game/objects/items/stacks/stack.dm
Warns admins if someone tries to pull this shit.
Someone had the idea to try and lie to the admins about doing this.
They aren't coming back.
This makes it easier for admins to spot this, and then nuke said player into orbit.
N/A
=> Adds a warning message for admins for an exploit

code/game/objects/items/stacks/stack.dm
Fixes my idiocy
AAAAAAAAAAAAAAAA
=> Fixes my idiocy

_maps/map_files/cyberiad/cyberiad.dmm
Fixes https://github.com/ParadiseSS13/Paradise/issues/17022
Fixes perma arcade machine facing a wall
Fixes random floor tile in bar maints
Tweaks Ass. Line maint doors to use engi colours to telegraph their access.
Fixes https://github.com/ParadiseSS13/Paradise/issues/16332
:cl:
fix: Fixed various box station issues
/:cl:
=> Fixes some minor cyberiad issues

_maps/map_files/Delta/delta.dmm, code/game/machinery/computer/arcade.dm
Fixes https://github.com/ParadiseSS13/Paradise/issues/16979
Correctly sets delta AI sat door access so that the RD is able to get in.
Correctly sets delta AI upload so command door remote has access.
Adds missing fire alarm to delta AI sat tcomms
Fixes random arcade machines not inheriting dirs
:cl:
fix: Fixed various delta station map issues
/:cl:
=> Fixes some minor delta issues

code/game/gamemodes/miniantags/abduction/gland.dm
Makes it so that the HUD icon for abductor victims isn't floating off to the bottom for some reason, but is actually next to them.
It's just weird, and can be obscured/confusing to any abductors.
**Old**
**New**
:cl:
fix: The icon for people with abductor organs now is actually next to the person.
/:cl:
=> Abductor icon HUD fix.

code/game/machinery/vending.dm
Re-adds the Red Bandana to the SecDrobe.
Loss of functionality is bad. They used to be in the Security Wardrobe closet and now theyre gone. This fixes that. Also - drip.
:cl:
fix: readds red bandana to SecDrobe.
/:cl:
=> Re-Adds Red Bandana to Security Wardrobe

code/modules/mob/living/carbon/human/species/slime.dm
title
fixes #17213 
things should GC properly
=> Fixes slime person GCing

code/game/objects/structures/morgue.dm
Adds a check on morgue trays to prevent them from ingesting ghosts and other immovable objects (possibly AI eyes?).
Fixes #10840
Despite it being kind of funny that ghosts can get put into morgue trays, it caused some actual buggy behavior. If only a ghost stands on a morgue tray when it's closed, the light turns yellow, even if the ghost moves. One user in dchat reported it messing up their camera completely and requiring a disconnect.
The real world shouldn't be able to interact with ghosts, or anything that can't be moved under any other circumstances. 
:cl:
fix: Fixes morgue trays being able to pull in ghosts and other immovable objects.
/:cl:
=> Prevent morgue trays from sucking up the dead

code/__DEFINES/rust_g.dm
Upgrades RUSTG to add new time measurement functions. Not implemented yet.
Yes.
N/A
=> Upgrades RUSTG

code/game/mecha/equipment/weapons/weapons.dm, code/modules/research/designs/mechfabricator_designs.dm
Removes Stamina Damage from Mech Scattershot.
Removes the stamina damage from the Mech Scattershot. Adds an additional 5 brute per shot in return.
midbullet > midbullet2
:cl:
del: Removes Stamina Damage from Mech Scattershot
/:cl:
=> Removes Stamina Damage from Mech Scattershot

SpacemanDMM.toml
Tweaks our rendering config to make stuff work with new smoothing.
Yes I webedited this. No I do not have shame.
Before
After:
=> Updates render passes for new smoothing

code/game/machinery/transformer.dm
makes the description correct
descriptions should convey accurate info
:cl:
fix: Cyborg factory's description now gives accurate info.
/:cl:
=> Fixes the cyborg factory description

code/game/objects/items/weapons/tanks/watertank.dm
Makes nozzle and water tank GC properly, fixes #17244 
Hard deletes are bad.
:cl:
fix: Fixes watertank GC issues.
/:cl:
=> Fixes watertank mister GC

code/modules/admin/IsBanned.dm, goon/code/datums/browserOutput.dm
This was causing duplicate logs. Its bad.
Duplicate logs bad.
N/A
=> Fixes some busted logging

code/game/objects/items/weapons/legcuffs.dm
adds IED = I to beartraps, fixing the IEDS not exploding when attached to beartraps.
Explosions are cool. Explosions not working is not cool.
:cl:
fix: Fixes IEDS not exploding when attached to beartraps.
/:cl:
=> Fixes IEDS not working with beartraps

code/controllers/subsystem/ticker.dm
Changes [src] to the explosion, to prevent: "The blast wave from Ticker tears you atom from atom!"
Explosions kill people, not mysterious subsystems.
:cl:
fix: The ticker subsystem no longer kills people during nuclear explosions, now the explosion does.
/:cl:
=> Fixes the ticker subsystem killing people

code/modules/reagents/chemistry/reagents/medicine.dm
Fixes a typo in medicine.dm ( Fixes #17095 )
No typos.
:cl:
spellcheck: Fixed a typo (cluches->clutches)
/:cl:
=> Fix Typo cluches -> clutches

code/_onclick/hud/screen_objects.dm, code/datums/statclick.dm, code/modules/client/client_procs.dm, interface/skin.dmf
Edits the `skin.dmf` file to clean up the bloat and moves some elements around to improve colour/spacing consistency.
More visual consistency and the ability to disable the bottom-left status bar since we have screentips now.
:cl:
add: Add option to disable the status bar in the bottom left of the viewport in the menu at the top. Options > Show status bar
tweak: Clean up the game window a bit so things look and are positioned more consistently
/:cl:
=> Clean up skin.dmf, fix input darkmode, add statusbar toggle option

code/game/objects/effects/anomalies.dm
title
there is a rare bug where this happens  
hopefully this fixes that
could be exploited with the supermatter to make free cores and use them to make reactive armour farms.
:cl:
fix: fixed a bug where grav anomalies would throw their own core at people.
/:cl:
=> fixes grav & vortex anomalies throwing their own core at people

code/datums/mind.dm
Admin editing traitor objectives (and all antag datum objectives) will now properly edit the objective instead of creating a new objective.
Also:
* Adds the die a glorious death objective to the list of objectives admins can add/edit. 
* Removes the "brig" objective from the list of objectives admins can add/edit. These didn't even exist, and attempting to add one just makes a runtime.
Fixes #17290
:cl:
fix: Fixes incorrect behavior when admin editing traitor objectives
tweak: Adds die a glorious death objectives to the list of objectives admins can add/edit.
/:cl:
=> Fixes incorrect behavior when admin editing traitor objectives

config/example/config.toml
Fixes https://github.com/ParadiseSS13/Paradise/issues/17207
Makes localhost autoadmin.
Disables space ruins and gateway for faster load times.
Disables Karma system.
Most people use this config for testing, if you are making a prod server then you will be thoroughly editing it anyway.
Having it optimised for testing is ideal.
**This does not affect existing servers or the main live server, only new ones from the moment this gets merged.**
=> Touches up default config

code/game/world.dm, config/example/config.toml
This PR updates the Paradise hub entry layout to make it neater.
Adds a closing bracket to the first line so that it looks neat.
Adds a discord link.
Adds an opening bracket to the final line so that it looks neat too.
The closing square bracket not being on the same line as the opening one was very infuriating to me.
Also linking to the discord helps newer players to find our community and become a bigger part of it.
(Hosted by xx will not be on prod server, the same with the server tagline and title. This is merely a formatting update)
No in-game player facing changes for a CL.
=> Updates the paradise hub entry format

code/modules/mob/living/living_defense.dm
You can no longer grab things that you cannot pull. 
if you cannot pull something in one way, why should you be able to pull something another way?
:cl:
tweak: you cannot grab things that you cannot pull eg. megafauna, juggernaughts
/:cl:
=> Prevents grabbing things that you cannot pull

_maps/map_files/Delta/delta.dmm, _maps/map_files/MetaStation/MetaStation.dmm, _maps/map_files/cyberiad/cyberiad.dmm, code/game/objects/effects/landmarks.dm
Oh my god, I re-pathed these and didn't change the on-map objects after so they are the wrong subtype. AAAAAAAAAAA.
Late join won't work because I'm stupid
=> Fixes a critical error with the previously merged PR

code/modules/clothing/spacesuits/ert.dm
Swaps the camera inside ERT hardsuits to the portable camera subtype.
Fixes #17319 Bugs are bad.
:cl:
fix: Fixed ERT helmet cameras not updating in bags and floating in place.
/:cl:
=> Fixes ERT cameras floating in place when in a bag

code/game/gamemodes/miniantags/revenant/revenant_abilities.dm
title
fixes my own bugs
:cl:
fix: rev malfunction properly EMPs items.
/:cl:
=> [GBP: no update] Fixes Rev EMP

code/game/objects/structures/stool_bed_chair_nest/chairs.dm
- Fixes exploit involving chairs
- It just doesn't sit right with me
No
=> Fixes exploit involving chairs

code/datums/spell_targeting/alive_mobs.dm, code/datums/spell_targeting/aoe.dm, code/datums/spell_targeting/spell_targeting.dm, code/datums/spell_targeting/targeted.dm
As the title says. It seems I fixed the existing bug with it in my spell targeting refactor. But introduced another bug which made it still not function as intended. It works now!
Also made some small optimizations for certain spell_targeting types
Bug fix b gut
:cl:
fix: The "Sense Victims" spell cult slaughter demons get works now
/:cl:
=> Fixes the sense victims spell

code/game/jobs/job/central.dm
Upgrades SOO nutriment implant to a hardened EMP proof version.
SOO having a weakness (permastun, death from starvation by emping) is unacceptable.
:cl:
tweak: SOO nutriment implant has been upgraded to EMP proof version
/:cl:
=> Upgrades SOO nutriment implant to a hardened EMP proof version.

code/game/objects/structures.dm
inb4 webeditor heresy
Fixes orbiting table climbers by making sure the signal is actually fired on the climber, not the table (: 
Fixes #17349
Bugs bad, good orbiting good
:cl:
fix: Orbiters should now follow mobs scaling tables.
/:cl:
=> [GBP: NO UPDATE] Fix table-climbing with mobs

code/modules/reagents/chemistry/reagents/alcohol.dm
Removes extra capital H in the Three part of the drink
Random capitals are bad.
:cl:
fix: Fixed capital H in Three Mile Island Iced Tea
/:cl:
=> Fixes spelling of three mile island iced tea

code/modules/admin/IsBanned.dm, goon/code/datums/browserOutput.dm
=> Warning hotfix

code/game/objects/items/stacks/medical.dm
Ensures that improvised gause does not heal brute damage, in line with it's description
having the description and effects match up is better
:cl:
fix: Ensure improvised gauze does not heal brute damage, in line with its description
/:cl:
=> make sure improvised gauze doesn't actually heal brute

code/modules/client/client_procs.dm
see title
ughhhhhhhhhhh
del: My sanity
fix: Fixed a runtime in client code
/:cl:
=> Fixes a major runtime I accidently caused

config/names/first.txt, config/names/first_male.txt
Removes the ability to randomly generate the following first names: Grandpa, Gaylord, Sissy.
Grandpa and Gaylord go against our naming rules, Sissy I would also say so.
:cl:
tweak: Can no longer randomly roll with the first name Grandpa, Gaylord, or Sissy
/:cl:
=> Removes 3 names from the random name generator

code/modules/admin/sql_notes.dm
Fixes a HTML injection exploit in the admin notes feature.
Admins, if you want newlines in your notes, just press enter on your keyboard. `<br>` is not required. 
This is bad
fix: Fixed a HTML injection exploit in the admin notes system
/:cl:
=> Fixes an exploit in notes

_maps/map_files/cyberiad/cyberiad.dmm
Moves the Prisoner locker room, leaving a small break area behind, to the space that used to contain the Brig Physician's room, making more spacious and with extra lockers.
Deals with that very awkward looking space left when the Brig Physician was removed, along with giving extra prisoners locker and making it easier to move around for Security when permabrigging (or sending to the labor camp) prisoners.
<b>Before:</b>
<b>After</b>
:cl: Quantum-M
tweak: Makes the old Brig Physician space into a new Prisoner Locker room.
/:cl:
=> Makes the old Brig Physician space into a new Prisoner Lockers Room (Cyberiad)

code/game/objects/items/hand_item.dm
Slapping has been updated to now allow for it to cause damage, if you so desire.
Not used ATM, but useful for admin shenanigans.
no CL as this is mostly backend.
Also corrects grammar for the slapper.
=> Updates Slapping to Allow for Damage

code/game/jobs/whitelist.dm
Fixes players being able to play as nucleations and other restricted species.
*sigh*
N/A
=> Species selection hotfix

_maps/map_files/Delta/delta.dmm
Updates Delta Morgue to be nicer and more on par with the Cyberiad one.
Updates the Delta Station map to both be more in par with the Cyberiad morgue and making it nicer, instead of looking like some abandoned room.
Gives the Coroner a more nicer area (and tools such as the body scanner that is present in the Cyberiad but not in Delta)
:cl: Quantum-M
tweak: Updates Delta Station Morgue to be more nicer and more on par with the Cyberiad Map.
/:cl:
=> Updates Delta Morgue [Ready]

code/modules/clothing/spacesuits/miscellaneous.dm
Changes the SOO beret not to conceal mask slot and removes a line of code about it's armor since it inherits the armor from it's parent and they are the same.
Items in the mask slot will now be visible which makes sense and SOO's will look cooler now instead of having invisible cigars.
:cl:
tweak: SOO armored beret doesn't cover up the mask slot now.
/:cl:
=> Changes SOO beret not to cover mask slot

_maps/map_files/generic/centcomm.dmm
Fixes various issues on CC z-level:
- Random red floor where an invulnerable wall should be
- All docking beacons named "military no-fly zone"
- Nukie shuttle prep blast doors being emaggable
- Nukie mech charger has the ugly floor
- Nukie floor leading to the shuttle was randomly different
- Access requirements to doors being wrong on some parts of CC asset protection
- CC SpecOps secondary dock was too long after mech launches got removed
Fixes and working maps!
The following is bad:
:cl:
fix: Fixed various CC mapping issues
/:cl:
=> CC z-level fixes

_maps/map_files/RandomRuins/SpaceRuins/oldstation.dmm
It was mentioned that currently, Theta Station can't really be powered as they have the materials for a singularity generator only which has massive radiation issues (see #16349 for more details, as it's related to those PRs). As a result, changing (for now at least) ThetaStation to have energy ball capabilities.
Bugs be buggy, we removed the singularity generator from DeltaStation for the same issues.
Old:
New:
:cl:
tweak: ThetaStation ruin now has Lady Tesla instead of Lord Singulo
/:cl:
=> Replaces the Singularity with the Tesla on ThetaStation

.github/CONTRIBUTING.md
I've gone on leave a few months back and won't be back for a while
🐼 ❌ 
🐼 🔥
=> The last PR till the next T-shirt season, probably

code/game/objects/effects/portals.dm
Gives the `creation_obj_data` list a value of `list(null, null)` if there's no creation object, so that list accesses using indexes do not runtime.
Fixes #17663
:cl:
fix: Fixes portals never despawning
/:cl:
=> [GBP no update] Fixes portals never despawning

code/__HELPERS/debugger.dm
Added a proc that lets the debugger evaluate expressions.
It helps with debugging.
=> Enable the auxtools debug console

code/modules/awaymissions/maploader/writer.dm
Fixes #17700 
Corrupted map files are bad.
:cl:
fix: Fixes Build Mode Map Saver
/:cl:
=> Reverts #17636 commits to writer.dm - Fixes Build Mode Map Saver

code/modules/reagents/chemistry/reagents/medicine.dm
Sets `harmless` to FALSE for Haloperidol.
GBP No Change as per AA.
Security uses this as a tranq-dart. You really should be able to purge it via Rejuv/chems/etc.
:cl:
tweak: Tweaks Haloperidol is now counted as "harmful".
/:cl:
=> Adds `harmless = FALSE` to Haloperidol

code/modules/power/singularity/singularity.dm
This reverts commit 79fe4f7dd26104dc6cfc5ef64b8fb06a53cb1301.
Rads has been fooken busted since this was added. Begone.
Singulo should not just grind the server to a halt.
=> Revert "Fixes singularity radiation not reaching rad collectors"

_maps/map_files/cyberiad/cyberiad.dmm
The code to utilize these was removed by #17473, they're currently just hogging up space on the map and acting as mapper bait for an unfortunate mapper one day.
It's not bad. Does that count?
Nobody will see this change
=> Removes Marauder Entry landmarks from cyberiad

_maps/map_files/Delta/delta.dmm, _maps/map_files/MetaStation/MetaStation.dmm, _maps/map_files/RandomRuins/SpaceRuins/ussp.dmm, _maps/map_files/RandomZLevels/centcomAway.dmm, _maps/map_files/cyberiad/cyberiad.dmm, code/modules/power/solar.dm
Deletes unused code, reduces the line count, so on and so forth. The code hasn't used IDs in nine years. I'm honestly surprised it's lasted this long. Anyways, here we are, with that gone. Strongdmm and VSC both didn't squawk at me for this so it's probably fine I assume. But yes, there's quite literally no code involving IDs, the var just exists pointlessly on these things for no actual reason.
Blah blah nobody will see it
=> Removes unused code regarding IDs on solar panels

_maps/map_files/generic/centcomm.dmm
Removes a turret under a window in the CC shuttle control room, now that https://github.com/ParadiseSS13/Paradise/pull/17662 prevents this from working.
This often just shot people who have access anyway, so goodbye.
:cl:
del: Removed a single turret from CC
/:cl:
=> Removes a CC turret under a window

code/modules/mob/living/carbon/human/examine.dm
Fix runtime related examine code when someone isn't wearing a jumpsuit.
Runtime bad.
=> Fixes runtime in examine code for accessories.

code/modules/projectiles/guns/medbeam.dm
makes the medibeam gun use UIDs
this is BAD
=> Fixes medibeams failing to GC

code/modules/client/client_procs.dm
Fixes my own cockup on the client deletion logic
`del()` bad, `qdel()` better
N/A
=> Fixes a client deletion issue

code/controllers/subsystem/vote.dm, code/modules/admin/verbs/mapping.dm, code/modules/mapping/base_map_datum.dm, code/modules/mapping/test_tiny.dm
Fixes map votes
You shouldnt be able to vote for the test map
fix: You can no longer vote for the test map
/:cl:
=> Fixes map vote

code/modules/admin/admin_investigate.dm
Add a jump button to investigate logs in the investigate verbs
Quality of life for the admins while investigating is good.
:cl:
add: Added a jump button in investigate logs.
/:cl:
=> Add a jump button to investigate logs

code/game/mecha/mecha.dm, code/game/objects/items.dm, code/game/objects/items/weapons/dice.dm, code/game/objects/items/weapons/weaponry.dm, code/modules/admin/verbs/onlyoneteam.dm, code/modules/hydroponics/grown.dm, code/modules/mob/living/carbon/human/human_defense.dm, code/modules/mob/living/carbon/human/species/golem.dm, code/modules/mob/living/living_defense.dm, code/modules/mob/living/simple_animal/bot/ed209bot.dm, code/modules/mob/living/simple_animal/bot/honkbot.dm, code/modules/mob/living/simple_animal/bot/secbot.dm
~~Ported weak references from TG, used them to fix #17521.~~
Fixes #17521
Hard dels are CPU-expensive.
=> Fixed thrownby hard del

code/game/objects/structures/bedsheet_bin.dm
Checks if hidden is null before trying to forcemove hidden on bedsheet bins
runtimes / undestroyable structures are bad.
:cl:
fix: Fixes bedsheets bins from being undeleteable.
/:cl:
=> Stops bedsheets runtiming / being undeleteable

code/game/gamemodes/miniantags/bot_swarm/swarmer.dm
adds:
```
if(!..())
return FALSE
```
to all checks that can return true that might realistically be indestructible (stuff like robot debris are excluded, for example)
Also fixes swarmers being able to destroy objects that have a living mob in them.
Swarmers should not be able to eat indestructible machines, for example take 90% of CC.
:cl:
fix: Fixes swarmers being able to deconstruct indestructible objects / objects with a mob in them
/:cl:
=> Keeps swarmers from eating indestructible objects

code/game/machinery/doors/poddoor.dm
Fixes only /multi_tile/impassable/two_tile_hor being indestructible, all other impassable blast doors did not have this
Indestructible objects should be indestructible
:cl:
fix: Fixes some indestructible multi tile pod doors not being indestructible 
/:cl:
=> Makes /multi_tile/impassable pod doors have resistance flags.

SQL/paradise_schema.sql
SQL schema creates `karmatotals` but DM code uses `karma_totals` - not good! This fixes that
N/A
=> Fix karma totals table name in schema

code/_onclick/hud/parallax.dm
When using parallax INSANE setting, there are blue stars that get rendered in addition to everything else. These stars render infront of the random parallax feature: Asteroids. This PR makes asteroids render above the blue stars, asteroids now with 200% more light blocking powerr!!!!
It looks bad currently.
**BEFORE:**
**AFTER:**
:cl:
fix: Fixed layering issue in parallax, asteroids now opaque!
/:cl:
=> Fixes parallax layering issue

_maps/map_files/RandomRuins/SpaceRuins/dj.dmm, _maps/map_files/RandomRuins/SpaceRuins/oldstation.dmm, _maps/map_files/RandomRuins/SpaceRuins/ussp.dmm, _maps/map_files/RandomRuins/SpaceRuins/ussp_tele.dmm
Blah blah floor dirs bad. Oh and some of the areas were weird on DJstation, non-solar area around the solars, so I fixed that too. Oh and ussp had floors that were varedited to be "vacuum" at 0.01 oxygen and nitrogen. They are now the vacuum floor type.
Blah blah I dunno cleanup good.
Blah blah nobody will see it.
=> Cleans up floors on Dj station, oldstation, ussp tele, and ussp.

code/datums/weather/weather_types/solar_flare.dm
Stops maint drones from instantly exploding when stood near a window during solar flares.
Poor sods just wanna do their job, no reason for this to affect them.
:cl:
fix: Stopped solar flare from killing maint drones
/:cl:
=> [GBP no update] Excludes maint drones from solar flare damage

code/game/objects/items/weapons/grenades/atmosgrenade.dm
Sets oxygen grenades tech level to zero
illegals 4 each round off station is bad.
:cl:
fix: Fixed oxygen grenades having an origin tech.
/:cl:
=> Fixes free illegals 4 every round

code/game/gamemodes/cult/blood_magic.dm, code/game/gamemodes/cult/ritual.dm, code/game/gamemodes/cult/runes.dm
Records:
what runes get invoked, and how many cultists are active at the time
what runes get invoked with cult ghosts
what spells get prepared
what runes get drawn.
logging is good, lets us balance things better.
N/A
=> Adds more blackbox logging to cult.

code/__DEFINES/misc.dm, code/game/objects/effects/decals/Cleanable/aliens.dm, code/game/objects/effects/decals/Cleanable/tracks.dm, code/game/objects/effects/decals/cleanable.dm, code/modules/clothing/clothing.dm, code/modules/detective_work/footprints_and_rag.dm, code/modules/mob/mob.dm
Slime bloods are strangely opaque to come from a translucent being, this PR makes their blood splatters translucent.
visual consistency. opaque blood coming from translucent beings make no sense
:cl:
tweak: Slimeperson blood now translucent, like their bodies are
/:cl:
=> Transparent slime blood

code/game/gamemodes/cult/blood_magic.dm
fixes logging for cult spell preparation.
while this is true, its not exactly what I intended. 
N/A
=> GBP no change: fixes cult blackbox logging

code/game/gamemodes/cult/cult_actions.dm, code/game/gamemodes/miniantags/revenant/revenant.dm, code/modules/antagonists/vampire/vampire_powers/dantalion_powers.dm
Fixes some ghost follow links (cult commune, rev, vamp thrall) by moving the *(follow)* bit after the title but before the message, much like other messages in chat.
Consistency is good for chat messages, and this in particular tends to stick out a fair bit. 
Sorry for the mismatched screenshots, my mouse pointer is being weird
:cl:
fix: The (follow) link is now in the right place for vampires, cult, and revenant communing.
/:cl:
=> Fix some follow links

code/modules/crafting/recipes.dm
fixes: https://github.com/ParadiseSS13/Paradise/issues/17947
Recipe didnt have an amount specified, so didnt work
fixes runtime 
:cl:
fix: Fixed golden bike horn being uncraftable!
/:cl:
=> Fixes Golden Bike Horn Crafting Runtime

.vscode/extensions.json, .vscode/settings.json
* Fuck yeah, new extension.
* No player-facing changes.
=> Switches [.dmi] Editor

code/modules/surgery/organs/subtypes/moth.dm
Makes Nian eyeballs use their unique sprite instead of the human eyeball sprite.
:cl:
fix: Nian eyeballs now use the correct  sprite
/:cl:
=> Fix: Nian eyeballs now use the correct sprite

_maps/map_files/Delta/delta.dmm
Adds a liquid dispenser and a intercom that were overlooked
Hotfix
:cl:
fix: Re-adds missing intercom and liquid dispenser on DeltaStation AI Sat
/:cl:
No Good Boy Points for being a bad boy
=> Adds Missing Liquid Dispenser and Intercom on DeltaStation AI

code/game/turfs/simulated/walls_indestructible.dm
Fixes T4 working on indestructible walls
exploits bad
:cl:
fix: T4 no longer works on indestructible walls
/:cl:
=> Fixes an exploit involving T4

_maps/map_files/Delta/delta.dmm, _maps/map_files/RandomRuins/LavaRuins/lavaland_surface_envy.dmm, _maps/map_files/RandomRuins/SpaceRuins/derelict5.dmm, _maps/map_files/RandomRuins/SpaceRuins/oldstation.dmm, _maps/map_files/RandomRuins/SpaceRuins/ussp_tele.dmm, _maps/map_files/RandomZLevels/evil_santa.dmm, _maps/map_files/RandomZLevels/moonoutpost19.dmm, _maps/map_files/RandomZLevels/terrorspiders.dmm, _maps/map_files/cyberiad/cyberiad.dmm, _maps/map_files/debug/smoothing.dmm, _maps/map_files/generic/Lavaland.dmm, _maps/map_files/shuttles/admin_hospital.dmm, code/game/turfs/simulated/walls_misc.dm, tools/mapmerge2/map_scripts/rust_converter.txt, tools/mapmerge2/requirements.txt
This PR removes instances of rusty turfs, replacing them with regular ones and rust spawners.
This PR adds a new mapmerge script for doing this for any WIP maps.
This PR bumps versions for mapmerge dependencies so it actually works now
Bye deprecated rusty thingies, we won't miss you.
No user-facing changes.
=> Removes instances of rusty turfs

_maps/map_files/cyberiad/cyberiad.dmm
Replaces a normal table with the intended reinforced table in Medbay Reception. Replaces remaining variable/icon edited grilles to broken grille subtype. These were previously just normal grilles that were edited to be passable and icon_state was set to brokengrille.
Consistency with both medbay reception tables and how we deal with the rest of broken grilles.
Before: 
After:
(stuff on the tables are not changed, before image is from the actual server)
:cl: Contrabang
fix: Medbay Reception tables are now all reinforced.
/:cl:
=> Fixes a medbay reception table and removes var-edited grilles on the Cyberiad (Third times the charm)

code/game/machinery/computer/ai_core.dm
When uploading a freeform law to an under-construction AI core, the laws will now be uploaded to the law 15 and above slots, instead of directly on top of the AI's lawset.
Currently, using a freeform law board to add a freeform law during AI core construction adds it directly on top of the default law set. I.e. say you have crewsimov with the laws being in the 1, 2 and 3 slots. Adding a freeform law during AI core construction will set that law to slot 4 instead of 15 or higher. 
This makes it consistent with uploading a freeform law to the AI upload console on the bridge. You can only place those at law 15 or higher.
:cl:
fix: When uploading a freeform law to an under-construction AI core, the laws will now be uploaded to the law 15 and above slots, instead of directly on top of the AI's …
=> Freeform laws uploaded to under-construction AI cores are now "supplied" laws instead of "inherent" laws

code/modules/shuttle/supply.dm
Tracks cargo orders to the blackbox.
Seeing how often cargo crates are ordered is good.
N/A
=> Adds cargo blackbox tracking

_maps/map_files/Delta/delta.dmm
Fixes major issue with a merge conflict that got in un-noticed, meaning delta is totally broken.
Maps should compile
=> Deltastation is screwed, this fixes it

code/game/machinery/computer/aifixer.dm
I can only guess this was overlooked when screwdriver_act() became a thing. Now prevents deconstruction of the AIfixer comp while AI is inside and the machine isnt broken. Breaking the machine with AI inside delete AI still.
Fixes https://github.com/ParadiseSS13/Paradise/issues/17688
Restores intended functionality.
:cl:
fix: Fixed AIfixer being able to be deconstructed with AI inside.
/:cl:
=> Bugfix Screwdriver AIfixer

code/modules/mob/living/simple_animal/friendly/bunny.dm
Fixes: https://github.com/ParadiseSS13/Paradise/issues/17376
Dead bunnies when picked up had alive sprites, this PR fixes that.
bugs are bad.
:cl:
fix: Fixed bunnies looking alive when dead and held.
/:cl:
=> Fixes dead bunnies' icon when held

code/modules/mob/living/simple_animal/bot/secbot.dm
Makes beepsky have the attack animation when stunning people.
Otherwise beepsky just plays the stun sound effect and people go horizontal. This looks better :o)
:cl:
tweak: Beepsky's stun attack is now animated.
/:cl:
=> Beepsky Attack Animated

code/modules/mob/mob_movement.dm
Fixes being able to push off objects in space while also pushing them forwards.
Fixes: https://github.com/ParadiseSS13/Paradise/issues/17499
Bug bad.
:cl:
fix: Fixed being able to push off objects in space while also pushing them forwards.
/:cl:
=> Fixes space movement pushing jank

code/modules/mob/living/living.dm
Fixes #18031
Sadly, this is fixing shitcode with more shitcode. Please treat it as a stopgap solution (until someone rewrites the grabbing code).
bugfix.
:cl:
fix: Fixed a stack overflow when trying to move with mutual grabs
/:cl:
=> Fix stack overflow in mutual grabs

code/modules/projectiles/guns/energy/special.dm
Adds a if(charging) return check to trying to charge the plasma pistol, to prevent being able to break it
bugs are bad
:cl:
fix: Fixes being able to break plasma pistols by charging them multiple times in a row.
/:cl:
=> fixes being able to break plasma pistols (GBP NO UPDATE)

code/modules/mob/living/status_procs.dm
=> Fixes dodging admin freezes

_maps/map_files/Delta/delta.dmm, _maps/map_files/MetaStation/MetaStation.dmm, _maps/map_files/RandomRuins/SpaceRuins/abandonedzoo.dmm, _maps/map_files/cyberiad/cyberiad.dmm, code/game/objects/structures/crates_lockers/closets/secure/medical.dm
- Removes the public syringe guns from: the three station maps and the abandoned zoo ruin
- Adds a syringe gun to the CMO locker
See #17818
See #17818
:cl: Miravel, Contrabang
add: Added a syringe gun to the CMO locker.
del: Removed the syringe guns from all three station maps and the abandoned zoo ruin.
/:cl:
=> Removes public syringe guns

code/game/objects/items/devices/autopsy.dm
Fixes #18064
:cl: uc_guy
fix: Autopsy scanner no longer merges multiple autopsies into one when scanning one "Unknown" after the other.
/:cl:
=> Autopsy scanner no longer merges multiple autopsies into one when scanning one "Unknown" after the other.

code/controllers/subsystem/time_track.dm, code/modules/mob/mob.dm, paradise.dme
Added SStime_track, taking parts of it from TG.
AA wanted it and I wanted to look into how this was done.
You have more insight into time slowing down, when it does.
=> Added time dilation tracking

code/modules/clothing/gloves/color.dm
re-adds functionality for all gloves to be dyable
It was mistakenly removed in: https://github.com/ParadiseSS13/Paradise/pull/18025
:cl:
fix: All colored gloves are dyeable again.
/:cl:
=> Gloves now dyeable again

code/modules/mob/living/simple_animal/hostile/alien.dm
Fixes #17153 caused by the typo "alienq_d"
Alien Queens now have proper dead sprites. Tho I have not seen what it was without this fix myself
:cl:
fix: Fixes typo "alienq_d" to "alienq_dead", correcting the path to already existing sprite
fix: Alien Queen now has proper "dead" sprite
/:cl:
=> Alien Queen Dead Sprite Fix

code/game/objects/effects/spawners/lootdrop.dm
Replace randomly spawned shoes in maintenance from brown to black.
These brown shoes spawns date from the time that no slip shoes (which can also be found in maintenance, albeit more rarely) were brown and couldn't be changed. 
Now that noslips start as black shoes, these should also be changed ~~to bait people into happiness then disappointment~~ for consistency.
:cl:
tweak: Maintenance randomly spawned shoes are now black instead of brown.
/:cl:
=> Replace maintenance brown shoes by black shoes

code/game/objects/structures/watercloset.dm
Makes /obj/structure/toilet/Initialize(mapload) be significantly less bad.
Bad code is bad. Not bad code is less bad.
=> Code Readability - Probability of an Open Toilet

code/game/machinery/computer/HolodeckControl.dm, code/game/machinery/computer/Operating.dm, code/game/machinery/computer/ai_core.dm, code/game/machinery/computer/aifixer.dm, code/game/machinery/computer/arcade.dm, code/game/machinery/computer/atmos_control.dm, code/game/machinery/computer/camera.dm, code/game/machinery/computer/card.dm, code/game/machinery/computer/communications.dm, code/game/machinery/computer/computer.dm, code/game/machinery/computer/law.dm, code/game/machinery/computer/medical.dm, code/game/machinery/computer/prisoner.dm
Converts 0/1 to FALSE/TRUE where those #defines make the code more readable. Also converts an if statement to be more readable given that the checked value is known to a bool. Note: There are a few cases where this converts 0.0/1.0 to FALSE/TRUE - this change is consistent with how the variable are used.
=> Code Readability - Computers

code/game/machinery/doors/airlock.dm, code/game/machinery/doors/airlock_control.dm, code/game/machinery/doors/airlock_types.dm, code/game/machinery/doors/alarmlock.dm, code/game/machinery/doors/brigdoors.dm, code/game/machinery/doors/door.dm, code/game/machinery/doors/firedoor.dm, code/game/machinery/doors/poddoor.dm, code/game/machinery/doors/shutters.dm, code/game/machinery/doors/windowdoor.dm
=> Code Readability - Doors

code/controllers/configuration/sections/ruin_configuration.dm, config/example/config.toml
Updates comments around var/enable_space_ruins to be accurate, as they spawn all ruins.
Comments are outdated
No player-facing changes
=> Updates comments around enable_space_ruins in config.toml to be accurate

code/modules/reagents/chemistry/reagents/alcohol.dm
Fixes #18157 via some heresy
:cl:
fix: Fixes a bug with the Erika Surprise drink
/:cl:
=> Fixes Erika Surprise drink name

code/game/machinery/pipe/pipe_dispenser.dm
* Converts 0/1 to FALSE/TRUE where those #defines make the code more readable.
* Simplfies calls to if statements for values known to be bools
* Flips an if/else statment so that the original if can be `if(unwrenched)` rather than `if(!unwrenched)`
=> Code Readability - Pipe Dispenser

code/modules/surgery/bones.dm, code/modules/surgery/cavity_implant.dm, code/modules/surgery/dental_implant.dm, code/modules/surgery/encased.dm, code/modules/surgery/generic.dm, code/modules/surgery/helpers.dm, code/modules/surgery/implant_removal.dm, code/modules/surgery/limb_augmentation.dm, code/modules/surgery/limb_reattach.dm, code/modules/surgery/organs/augments_arms.dm, code/modules/surgery/organs/blood.dm, code/modules/surgery/organs/organ_external.dm, code/modules/surgery/organs/organ_internal.dm, code/modules/surgery/organs/subtypes/kidan.dm, code/modules/surgery/organs_internal.dm, code/modules/surgery/other.dm, code/modules/surgery/remove_embedded_object.dm, code/modules/surgery/robotics.dm, code/modules/surgery/surgery.dm, code/modules/surgery/tools.dm
Removes some dead code from surgery and refactors surgery by changing magic numbers to defines.
=> Surgery refactors

code/modules/clothing/chameleon.dm, code/modules/clothing/clothing.dm, code/modules/clothing/glasses/glasses.dm, code/modules/clothing/glasses/hud.dm, code/modules/clothing/head/misc_special.dm, code/modules/clothing/head/soft_caps.dm, code/modules/clothing/masks/gasmask.dm, code/modules/clothing/shoes/magboots.dm, code/modules/clothing/spacesuits/alien.dm, code/modules/clothing/spacesuits/chronosuit.dm, code/modules/clothing/spacesuits/hardsuit.dm, code/modules/clothing/spacesuits/miscellaneous.dm, code/modules/clothing/spacesuits/plasmamen.dm, code/modules/clothing/suits/miscellaneous.dm
* Converts 0/1 to FALSE/TRUE where those #defines make the code more readable. Note: There are a few cases where this converts 0.0/1.0 to FALSE/TRUE - this change is consistent with how the variable are used.
* Converrs -1/0/1/2 to FLASH_PROTECTION_SENSITIVE/FLASH_PROTECTION_NONE/FLASH_PROTECTION_FLASH/FLASH_PROTECTION_WELDER where those #defines make the code more readable.
* Removes some unnecessary brackets in if statements
* Removes some unnecessary == in if statements
=> Code Readability - Clothing

code/modules/mob/living/simple_animal/hostile/terror_spiders/actions.dm, code/modules/mob/living/simple_animal/hostile/terror_spiders/brown.dm, code/modules/mob/living/simple_animal/hostile/terror_spiders/gray.dm, code/modules/mob/living/simple_animal/hostile/terror_spiders/princess.dm, code/modules/mob/living/simple_animal/hostile/terror_spiders/purple.dm, code/modules/mob/living/simple_animal/hostile/terror_spiders/queen.dm, code/modules/mob/living/simple_animal/hostile/terror_spiders/reproduction.dm, code/modules/mob/living/simple_animal/hostile/terror_spiders/terror_ai.dm, code/modules/mob/living/simple_animal/hostile/terror_spiders/terror_spiders.dm, code/modules/mob/living/simple_animal/hostile/terror_spiders/white.dm
* Converts 0/1 to FALSE/TRUE where those #defines make the code more readable. 
* Adjusts if statements to use boolean values as booleans.
=> Code Readability - Terror Spiders

code/controllers/subsystem/mobs.dm
Fixes bad lengths
AAAAAAAAAAAAAAAAAAAAA
N/A
=> God damn I am dumb

code/datums/beam.dm
Makes ebeams not be effected by explosions
GC collection failing due to the ebeam effects being deleted is bad.
:cl:
fix: Fixes explosions causing ebeams to fail GC
/:cl:
=> Stops explosions causing ebeams to fail GC

code/modules/food_and_drinks/drinks/bottler/bottler.dm, code/modules/food_and_drinks/drinks/drinks/bottle.dm, code/modules/food_and_drinks/food/foods/pizza.dm, code/modules/food_and_drinks/food/snacks.dm, code/modules/food_and_drinks/kitchen_machinery/cooker.dm, code/modules/food_and_drinks/kitchen_machinery/deep_fryer.dm, code/modules/food_and_drinks/kitchen_machinery/food_grill.dm, code/modules/food_and_drinks/kitchen_machinery/gibber.dm, code/modules/food_and_drinks/kitchen_machinery/icecream_vat.dm, code/modules/food_and_drinks/kitchen_machinery/juicer.dm, code/modules/food_and_drinks/kitchen_machinery/kitchen_machine.dm, code/modules/food_and_drinks/kitchen_machinery/monkeyrecycler.dm, code/modules/food_and_drinks/kitchen_machinery/oven.dm, code/modules/food_and_drinks/kitchen_machinery/processor.dm
=> Code Readability - Food

code/modules/hydroponics/biogenerator.dm, code/modules/hydroponics/gene_modder.dm, code/modules/hydroponics/hydroitemdefines.dm, code/modules/hydroponics/hydroponics.dm, code/modules/hydroponics/seed_extractor.dm
=> Code Readability - Hydroponics

code/modules/surgery/organs/augments_internal.dm, code/modules/surgery/organs/helpers.dm, code/modules/surgery/organs/organ_external.dm, code/modules/surgery/organs/subtypes/diona.dm, code/modules/surgery/organs/subtypes/standard.dm, code/modules/surgery/remove_embedded_object.dm, code/modules/surgery/robotics.dm
* Converts 0/1 to FALSE/TRUE where those #defines make the code more readable.
* Removes the unused procs `get_leg_ignore` and `get_missing_limbs`
=> Code Readability - Surgery

code/modules/mob/hear_say.dm
This reverts commit e291a8c779c7873e1eccc4360297568fc2551bbc.
This introduced a nasty exploits I aint disclosing till this is in.
N/A
=> Revert "Quieter radio emotes (#18103)"

code/modules/mining/abandonedcrates.dm, code/modules/mining/equipment/lazarus_injector.dm, code/modules/mining/equipment/mining_tools.dm, code/modules/mining/equipment/survival_pod.dm, code/modules/mining/lavaland/loot/ashdragon_loot.dm, code/modules/mining/lavaland/loot/colossus_loot.dm, code/modules/mining/lavaland/loot/tendril_loot.dm, code/modules/mining/machine_unloading.dm, code/modules/mining/mine_items.dm, code/modules/mining/minebot.dm, code/modules/mining/mint.dm, code/modules/mining/ores_coins.dm
* Converts 0/1 to FALSE/TRUE where those #defines make the code more readable. Note: There are a few cases where this converts 0.0/1.0 to FALSE/TRUE - this change is consistent with how the variable are used.
* Where bools are in if statements, uses them as bools
=> Code Readability - Mining

code/modules/games/cards.dm
Fixes #18254
Stops a runtime error
=> Fixes Runtime Error when removing a card from your hand when both hands are full

code/game/machinery/pipe/construction.dm
Adds ability to rotate/flip pipes when AltClick or AltShiftClick on pipes.
QOL, skip the right click menu and embrace the hotkey lifestyle.
:cl:
add: Alt clicking on pipes will now rotate them, Alt+Shift clicking will flip them.
/:cl:
=> Alt Click 2 Rotate Pipes

code/modules/assembly/bomb.dm, code/modules/assembly/infrared.dm, code/modules/assembly/mousetrap.dm, code/modules/assembly/proximity.dm, code/modules/assembly/shock_kit.dm, code/modules/assembly/signaler.dm, code/modules/assembly/voice.dm
=> Code Readability - Assembly

code/game/machinery/vending.dm
Adds three damp rags to the cook's clothing vending machine. (three, becasue that's how many are in the bartender's clothing machine)
Cook currently needs to rely on janitorial to clean cooking appliances that get dirty, which can be problematic for a mid game cook when everything is already a mess. Giving an alternative but weak option (that the bartender already has) allows the cook to focus on cooking.
:cl:
add: Added 'Damp Rag' to 'ChefDrobe' vending machine
/:cl:
=> Adds Rag to Cook Clothing Vending Machine

code/game/turfs/simulated/floor.dm, code/game/turfs/simulated/floor/fancy_floor.dm, code/game/turfs/simulated/floor/mineral.dm, code/game/turfs/simulated/minerals.dm, code/game/turfs/simulated/river.dm, code/game/turfs/simulated/walls.dm, code/game/turfs/simulated/walls_mineral.dm, code/game/turfs/simulated/walls_reinforced.dm, code/game/turfs/turf.dm
Converts 0/1 to FALSE/TRUE where those #defines make the code more readable. Note: There are a few cases where this converts null to FALSE - this change is consistent with how the variables are used.
=> Code Readability - Turfs

code/game/area/areas/depot-areas.dm, code/game/area/ss13_areas.dm, code/game/dna/dna_modifier.dm, code/game/dna/mutations/disabilities.dm, code/game/dna/mutations/powers.dm, code/game/mecha/equipment/mecha_equipment.dm, code/game/mecha/equipment/tools/medical_tools.dm, code/game/mecha/equipment/tools/mining_tools.dm, code/game/mecha/equipment/tools/other_tools.dm, code/game/mecha/equipment/tools/work_tools.dm, code/game/mecha/equipment/weapons/weapons.dm, code/game/mecha/mech_bay.dm, code/game/mecha/mecha.dm, code/game/mecha/mecha_construction_paths.dm, code/game/mecha/mecha_wreckage.dm, code/game/shuttle_engines.dm
* Converts 0/1 to FALSE/TRUE where those #defines make the code more readable.
* Converts some stat_allowed = 0 to stat_allowed = CONSCIOUS
* Where bools are in if statements, uses them as bools
* For mecha equipment, converts returns that should be TRUE or FALSE to those values
* For mecha equipment with states, gets rid of magic numbers by using #defines to specify state
=> Code Readability - Game (misc)

code/modules/paperwork/faxmachine.dm, code/modules/paperwork/filingcabinet.dm, code/modules/paperwork/paper.dm, code/modules/paperwork/paperbin.dm, code/modules/paperwork/pen.dm, code/modules/paperwork/photocopier.dm, code/modules/paperwork/photography.dm
* Converts 0/1 to FALSE/TRUE where those #defines make the code more readable. Note: There are a few cases where this converts 0.0/1.0 to FALSE/TRUE - this change is consistent with how the variable are used.
* Where bools are in if statements, uses them as bools
* Adds return FALSE/TRUE where the returns are expecting bool values
=> Code Readability - Paperwork

code/modules/research/designs.dm, code/modules/research/designs/weapon_designs.dm, code/modules/research/destructive_analyzer.dm, code/modules/research/experimentor.dm, code/modules/research/rdconsole.dm, code/modules/research/rdmachines.dm, code/modules/research/server.dm, code/modules/research/xenobiology/xenobiology.dm
=> Code Readability - Research

code/__HELPERS/unsorted.dm, code/_onclick/ai.dm, code/_onclick/hud/robot.dm, code/controllers/subsystem/jobs.dm, code/controllers/subsystem/nano_mob_hunter.dm, code/datums/action.dm, code/datums/beam.dm, code/datums/diseases/advance/advance.dm, code/datums/mind.dm, code/datums/wires/alarm.dm, code/datums/wires/nuclearbomb.dm
* Converts 0/1 to FALSE/TRUE where those #defines make the code more readable.
* Where bools are in if statements, uses them as bools
=> Code Readability - Misc

code/modules/clothing/gloves/color.dm, code/modules/clothing/gloves/miscellaneous.dm
You have to be adjacent to fake insulated gloves to see if they're fake
It makes them accurate to their description, since you have to feel them. An alternative but more boring solution is to alter the description to be "They don't look like rubber."
:cl:
tweak: Buffs fake insulated gloves
/:cl:
Kind want to keep this vague, just to catch more people off guard with the fake insulated gloves, since that is their purpose.
=> Fake insuls can only be felt when adjacent

_maps/map_files/Delta/delta.dmm, _maps/map_files/MetaStation/MetaStation.dmm, _maps/map_files/RandomZLevels/terrorspiders.dmm, code/modules/atmospherics/machinery/components/binary_devices/dp_vent_pump.dm, code/modules/atmospherics/machinery/components/unary_devices/vent_pump.dm
Renames the variable 'pump_direction' to 'pump_direction_releasing ' so that it's obvious what TRUE and FALSE represent.
=> Code Readability - Atmospheric Pumps

code/datums/emote.dm
Fixes some admin logging for emotes, a slight oversight from the emote refactor.
Admin logging is generally regarded as a good thing.
:cl:
fix: Improves admin logging for emotes.
/:cl:
=> Fixes some emote logging

code/modules/mob/living/carbon/carbon.dm
You can no longer click on yourself to put out fires on yourself.
Stop drop and roll. No brushing the fire off yourself with your hands while running away at full speed.
:cl:
tweak: You can no longer click on yourself to brush fires off yourself, and must stop drop and roll or use a fire extinguisher.
/:cl:
=> You once again must stop drop and roll.

code/modules/projectiles/projectile/energy.dm
Changes BSG / BSG's explosion to a knockdown of 4 on projectile direct hit from a 2 second weaken, and changing the chance for a 2 second stun for people in it's AOE to a 4 second knockdown
Ranged stun bad, ranged knockdown better, and a little longer knockdown for more impact should be good.
:cl:
tweak: BSG now knocks down for 4 seconds instead of hard stunning for 2, on a direct hit or chance based on range from impact.
/:cl:
=> BSG now uses knockdown, slight increase in knockdown time from stun.

code/game/verbs/suicide.dm
Fixes a runtime in PAI suiciding
Runtimes are bad!
No CL as it's not a player facing change
=> PAI's no longer runtime when suiciding

code/datums/mind.dm
Fixes bad pathing of /mob/living/simple_animal/construct and some subtypes
invisible bad pathed mobs are bad
N/A
=> fixes simple_animal/construct

code/datums/components/ducttape.dm, code/game/objects/items/weapons/RSF.dm, code/game/objects/items/weapons/cigs.dm, code/game/objects/items/weapons/gift_wrappaper.dm, code/modules/food_and_drinks/kitchen_machinery/kitchen_machine.dm, code/modules/maze_generation/maze_helper_atoms.dm, code/modules/mob/living/simple_animal/friendly/farm_animals.dm, code/modules/mob/living/simple_animal/hostile/bat.dm, code/modules/mob/living/simple_animal/hostile/jungle_animals.dm, code/modules/mob/living/simple_animal/hostile/retaliate/fish.dm, code/modules/surgery/other.dm, code/modules/tgui/modules/law_manager.dm
Changes all visible instances of 'cant' to 'can't'
Removes duplicate 'the' from patting or kicking mobs [other than panther]
Changes 'the pain in your the [bodypart] is unbearable!' to 'the pain in your [bodypart] is unbearable!'
Changes 'treads on the lit the lit [cigarette/etc]' to 'treads on the lit [cigarette/etc]'
Changes 'you have no idea what you can cook with this the [food]' to 'you have no idea what you can cook with the [food]'
Grammar and readability.
:cl:
spellcheck: Fixed some grammar
/:cl:
=> Grammar fixes

code/controllers/master.dm
Ports https://github.com/tgstation/tgstation/pull/68490
=> Fix a subsystem priority sort

code/modules/food_and_drinks/food/foods/desserts.dm, code/modules/food_and_drinks/food/foods/meat.dm
Fixes the punctuation/grammar on the descriptions for meat, corgi meat, and icecream sandwiches.
Almost every object description in SS13 has punctuation, this keeps things standardized. Also, proper grammar good.
Before:
After:
:cl:
fix: Fixed punctuation/grammar on descriptions for meat, corgi meat, and icecream sandwiches
/:cl:
=> Fixes punctuation/grammar on food descriptions

code/modules/food_and_drinks/kitchen_machinery/cooker.dm
Fixes punctuation on inspected deep fried food.
Proper punctuation is good for the soul
Before:
After:
:cl:
fix: Fixed punctuation on inspected deep fried foods
/:cl:
=> Fix punctuation on deep fried food

code/modules/paperwork/photography.dm
fixes an exploit.
performance is good.
N/A
get flat icon is a sin
=> Fixes a lag exploit

code/__DEFINES/_tgs_defines.dm, code/__HELPERS/_logging.dm, code/modules/admin/admin_verbs.dm, code/modules/admin/verbs/debug_dmapi.dm, code/modules/tgs/v3210/api.dm, paradise.dme
Adds a verb to debug various DMAPI parameters and improve DMAPI logging.
I need to make the server work with TGS3 for reasons.
add: [Host] Added a verb to debug the DMAPI
/:cl:
=> DMAPI Debug Verb

code/game/objects/items/weapons/stunbaton.dm
Makes batons use the user_UID var they defined a few lines above instead of looking for it again when they add their trait to the target.
it probably doesn't matter very much but is better code I guess
Nothing player-facing.
=> Fixes batons checking user UID twice

code/game/objects/structures/stool_bed_chair_nest/chairs.dm
Planting chairs down will now set them in your direction
Its bugged at its current moment and does not make the chair face the right direction
:cl:
fix: Planting chairs down will now set them in your direction
/:cl:
=> Fixes a bug related to planting chairs

code/modules/food_and_drinks/drinks/drinks/cans.dm, code/modules/reagents/chemistry/reagents/drink_cold.dm, code/modules/reagents/chemistry/reagents/drinks.dm
Fixes the punctuation/grammar on quite a few beverage descriptions. Also adds new descriptions for vanilla/chocolate pudding, since the original description was just "Tasty".
Grammar good, punctuation good.
:cl:
spellcheck: Fixed grammar and punctuation on several beverage descriptions
/:cl:
=> Fixes grammar/punctuation on beverage descriptions

_maps/map_files/MetaStation/MetaStation.dmm
Fixes a door helper access modifier conflicting with a varedited access set
Fixes one missing area at the dorms pod and AI sat
Replaces some var edited windoors for pre-rotated ones, 3 at disposals 1 in cargo.
Mapping error fixes
Also, I think my hooks are installed now so I don't need to run map merger. Tell me if it fucked up or not.
=> More Meta Fixes

code/modules/shuttle/supply.dm
This improves the log format for readability, adds initial order logs, and adds order denial logs to the investigate logging.
It can be difficult for admins to quickly understand who is denying or spamming orders at cargo. This should make it easier to quickly check if anyone is improperly using cargo machines.
:cl:
add: Logs initial cargo crate orders
add: Logs cargo crate denials
tweak: Adjusts investigate log format for cargo
/:cl:
=> Expand Admin Investigate Logs for Cargo

code/datums/status_effects/debuffs.dm
=> Fixes an exploit with martial arts.

code/modules/mob/living/carbon/alien/alien.dm, code/modules/mob/living/carbon/alien/humanoid/caste/drone.dm, code/modules/mob/living/carbon/alien/humanoid/caste/hunter.dm, code/modules/mob/living/carbon/alien/humanoid/caste/sentinel.dm, code/modules/mob/living/carbon/alien/humanoid/empress.dm, code/modules/mob/living/carbon/alien/humanoid/queen.dm, code/modules/mob/living/carbon/alien/larva/larva.dm
`/mob/living/carbon/alien` gets converted from `/New` to `/Initialize`
Tested; works
yes
N/A
=> Xenos are Initialize

code/modules/mob/living/silicon/ai/update_status.dm, code/modules/mob/living/silicon/robot/update_status.dm
changes things
Bugs are bad, especially ones related to #18553
No player-facing changes
=> Fixes #18553

code/game/objects/items/weapons/rpd.dm
Adds the part replacer check to the RPD. Player warning and admin logs are tweaked accordingly.
Fixes #18565
N/A
=> Fix BRPD exploit

code/game/dna/mutations/powers.dm
This addresses #16239 and makes Hulk visibly update when enabled or disabled.
People can actually see when Hulk is active without requiring a secondary icon update to do it. 
:cl:
fix: Hulk visuals update when they should now
/:cl:
=> Fixes Hulk not visually updating

code/game/objects/items/crayons.dm
Fixes a spraycan runtime when spraying a xenomorph. An ishuman check is now performed before the offending code.
Runtimes bad
:cl:
fix: Fixed spraycan runtime
/:cl:
=> Fixes runtime when spraypainting xenomorphs

_maps/map_files/generic/centcomm.dmm
Makes invisible closet in wizard's den visible.
While wizard's are masters of deception this is a little ridiculous.
:cl:
fix: Made invisible closet in wizard's den visible.
/:cl:
=> Fixes invisible closet in wizard's den

code/game/mecha/combat/durand.dm, code/game/mecha/combat/gygax.dm, code/game/mecha/combat/honker.dm, code/game/mecha/combat/marauder.dm, code/game/mecha/combat/phazon.dm, code/game/mecha/combat/reticence.dm, code/game/mecha/medical/medical.dm, code/game/mecha/working/ripley.dm, code/game/mecha/working/working.dm
Move all remaining `/obj/mecha` datums to use `/Initialize()`
Simple PR. Tested; appears to be working.
Initialize good
N/A
=> Move all remaining /obj/mecha to Initialize

code/datums/uplink_item.dm, code/game/objects/items/devices/traitordevices.dm
Makes the word "warranty" spelled properly in the descriptions of the syndicate teleporter.
typo bad
:cl:
fix: Fixed a typo in the syndicate teleporter.
/:cl:
does this need a changelog?
=> Fixes a Typo in Syndicate Teleporter's Descriptions

code/game/jobs/job/job.dm, code/modules/mob/living/simple_animal/bot/bot.dm, code/modules/mob/living/simple_animal/bot/cleanbot.dm, code/modules/mob/living/simple_animal/bot/ed209bot.dm, code/modules/mob/living/simple_animal/bot/floorbot.dm, code/modules/mob/living/simple_animal/bot/griefsky.dm, code/modules/mob/living/simple_animal/bot/medbot.dm, code/modules/mob/living/simple_animal/bot/mulebot.dm, code/modules/mob/living/simple_animal/bot/secbot.dm, code/modules/mob/living/simple_animal/bot/syndicate.dm
Have `/mob/living/simple_animal/bot` use `/Initialize` rather than new.
Fixes #18421 (or, well, at least i can't repro it with the PR. However, given the scarcity of details in the issue, i'm not sure i'm fixing *the* runtime..)
yes
=> Initialize bots

code/game/mecha/mech_bay.dm
(apologies for vague title)
Fixes a runtime introduced by me in #18546
Additionally fixes mecha recharging consoles screen not working
:cl:
fix: Mecha recharge console screens are no longer permanently black
/:cl:
=> Fix mech recharger detection

code/modules/paperwork/paper.dm, strings/tips.txt
The armory inventory list now correctly lists three disablers instead of tasers.
One of the tips of the round now says you can put a seclight on a disabler as an officer, instead of taser, as you no longer have a taser.
Things being correct instead of incorrect is good.
I looked at the paper, which now said "3 Disablers", and it did not explode or something.
:cl:
fix: Replaced two obsolete mentions of tasers with disablers.
/:cl:
=> Replaces "taser" with "disabler" in two places where it's now true

code/modules/surgery/organs/organ_external.dm, code/modules/surgery/organs/subtypes/standard.dm
It adds a small quality of life examine to heads if they have been cut open.
Examining a full body without a brain will show the brain is missing, a decapitated head should be able to do the same thing.
:cl:
tweak: Examine now shows if a head has had it's organs removed
/:cl:
=> Examine now shows if a head has had it's organs removed

code/game/mecha/equipment/weapons/weapons.dm, code/game/mecha/mecha.dm
Reworks the ion weapon for mecha from firing one normal ion shots, to 4 weak ion shots, like the shotgun ion scatter shells. Heavy power cost
The mech gains a second of EMP immunity for this time.
Also adds an EMP proof variable to mechs, which does what it says on the tin. Makes the mecha EMP proof.
Current ion weapon on the mech sucks. Fires way too slow, a normal ion gun, or a heavy laser on the mech, serves you better.
As such, this reworks it to an ion shotgun, which is stronger on mechas, great for ioning a bunch of borgs, or hitting someone loaded with weapons running away.
Also gives the mech one second of EMP immunity after being fired, so it can be used point blank without dying.
Also, ion rifles are immune to EMPS, so someone can not use this to take out ion rifles from use as …
=> Reworks mech mounted ion weapon

code/modules/antagonists/changeling/powers/mutations.dm
Fixes punctuation on the armblade's description by adding a period at the end. Also slightly adjusts the description to flow better.
Proper punctuation is good.
:cl:
spellcheck: Fixed punctuation on armblade description
/:cl:
=> Fixed punctuation on armblade description

code/datums/supplypacks.dm
Removes 20/50 sheet plasteel crates from cargo ordering.
Currently the cost for these crates is significantly lower than the amount of plasma that can be extracted from the plasteel (1.5:5 point ratio on 20 plasteel crate, 1:5 point ratio on 50 plasteel crate). This means that this is effectively a money printing machine. 
This is just one of the possible solutions, other solutions include:
- Reduce price plasma sells for.
- Increase price of plasteel crates (With current plasma prices this would mean the 20 plasteel crate would need to cost at least 100 points and the 50 plasteel crate 250 points to break even, not including metal costs)
- Reduce amount of plasteel per crate
- Any combination of the above.
Should any of these be preferred please do let me know.
:cl:
del: Removed plasteel …
=> Remove plasteel supply crates from cargo ordering.

code/modules/antagonists/vampire/vampire_powers/hemomancer_powers.dm
fixes an exploit with hemomancer.
exploits bad
breakpoints baby
N/A
=> hemomancer exploit fix

code/modules/mob/living/carbon/human/life.dm
Adds the 2 brainloss say lists together, and cleans up the probabilty code. It also adds "I CAN FORCE YOU TO SAY WHATEREVE!!?!?!" to the list, a reference to how the #18279 exploit was found. It also changes some of the lines to be more "brain damagey", if they seemed too normal when said. (IE "Stat me" to "StAT ME")
Code improvement and reference this exploit
:cl:
add: adds a new brain damage message
tweak: some brain damage lines have been edited to be more "brain damagey"
/:cl:
=> Cleans up brain loss code a bit and adds a new line

code/modules/projectiles/projectile/special.dm
Prevents weak ions from calling the parent on hit effect of ions, causing weak ions to do normal ions effect as well as itself.
Weak ion shots should not... call the normal ion effect as well. This is a bug. This affects HOS gun, and ion scatter rounds / mech ion shotgun.
This does nerf them greatly, but is a bug fix. If the effects of these weapons are too weak, we can change them to normal ion rounds.
For comparison, ion scatter rounds point blank did 180 ish (rng might make it lower, going off reading code / memory rather than a test) energy damage to mechs. (not counting battery drain)
It now does 60.
HOS gun would do 45 to a mecha, it now does 15.
Spawn in.
Fire ion rifle, works as intended.
Fire hos gun, works as intended.
Fire ion scatter rounds, works as intended.
:cl:
fix: Fixes …
=> fixes weak ion shots... being stronger than normal ions

code/game/objects/items/contraband.dm, code/game/objects/items/random_items.dm, code/modules/awaymissions/mission_code/UO71-terrorspiders.dm, code/modules/fish/fish_items.dm, code/modules/food_and_drinks/drinks/drinks.dm, code/modules/food_and_drinks/drinks/drinks/mugs.dm, code/modules/food_and_drinks/food/foods/baked_goods.dm, code/modules/food_and_drinks/food/foods/candy.dm, code/modules/food_and_drinks/food/foods/desserts.dm, code/modules/food_and_drinks/food/foods/meat.dm, code/modules/food_and_drinks/food/foods/misc.dm, code/modules/food_and_drinks/food/foods/soups.dm, code/modules/food_and_drinks/food/snacks.dm, code/modules/food_and_drinks/kitchen_machinery/cooker.dm, code/modules/hydroponics/beekeeping/honeycomb.dm, code/modules/hydroponics/grown.dm, code/modules/hydroponics/hydroitemdefines.dm, code/modules/hydroponics/plant_genes.dm, code/modules/reagents/reagent_containers.dm, code/modules/reagents/reagent_containers/borghydro.dm, code/modules/reagents/reagent_containers/bottle.dm, code/modules/reagents/reagent_containers/glass_containers.dm, code/modules/reagents/reagent_containers/syringes.dm, code/modules/surgery/organs/organ_internal.dm
/obj/item/reagent_container is `/Initialize()`
Tested botany, basic chemistry and cleaning grenades. Work.
Initialize good
N/A
=> `/obj/item/reagent_container` is `Initialize`

.github/CONTRIBUTING.md, .gitignore
Makes `CONTRIBUTING.MD` follow markdown lint rules, as well as adding Sirryan2002 as a listed review team member.
I also might add a TOC to the contribution guidelines since it would be nice to jump around to stuff, and prefixing sections may help.
I also threw `dmm-tools.exe` in the gitignore because some of us like to keep that in the repo and I am fed up of my working tree being muddied. 
I dont like getting 400 lint violations when I open this file
=> Contributing cleanup + Gitignore tweak

code/game/jobs/job_exp.dm, code/modules/admin/verbs/randomverbs.dm
Fixes some stealth mode bypasses
The whole point of stealth mode is to hide, so bypasses defeat that
*Other user had +MENTOR rights*
fix: Fixed some stealth mode bypasses
/:cl:
=> Fixes some stealth mode bypasses

code/modules/hydroponics/grown/flowers.dm
Fixes a lack of a SPACE in the FLOWER POWER text.
It hurts to look at, and it triggers me.
=> Fixes sunflowers

code/game/machinery/computer/camera.dm, code/game/objects/items/devices/camera_bug.dm
This PR disables camera console sounds if you are using camera bug
Camera bug console is very cool useful item, but using it as traitor before this PR is loud. Everyone could find you in two seconds cause of loud switching camera console sounds and display activate sound. 
By my sight, it should be stealth item to make fun stealth operations, not loud shit to show everyone you are traitor.
In game i found a lot of guys using it just hearing their sounds through the walls
Compiled and tested ingame
:cl:
tweak: Disabled sounds on using camera bug
/:cl:
=> Disabling sounds on using Camera Bug

code/game/world.dm
Logs DD raw output to a file if the server is running under TGS
Its kinda important
=> DD stdout logging

code/game/machinery/doors/poddoor.dm
Makes things have a higher move resist
Bugs are bad
Spawned in.
Shot thing at thing.
Thing worked as should
:cl:
fix: Fixes something not having a high enough move resist.
/:cl:
=> fixes a bug

code/modules/paperwork/paper.dm
Fixes the holodeck disclaimer.
Typos bad.
:cl:
spellcheck: Holodeck disclaimer
/:cl:
=> Fix a misspelling on the holodeck disclaimer.

code/__HELPERS/icon_smoothing.dm
Makes these runtime, instead of throw a DD error, so people can actually know when they fail.
=> Properly log smoothing errors

code/modules/mob/living/simple_animal/hostile/mining/elites/legionnaire.dm, code/modules/mob/living/simple_animal/hostile/mining/elites/pandora.dm
Pandora no longer fires chasers at dead mobs.
Fixes legionnaire getting stuck on his skull when charging
Pandora becoming (more) of a disco inferno when it has 2 mobs in the arena is a little silly.
Spawned skrells
Killed skrells with chasers
Chaser number decreased as they died, until they were all dead
:cl:
fix: Pandora chasers no longer target dead mobs.
fix: Legionnaire no longer gets stuck on his charge.
/:cl:
=> fixes pandora chasers going after dead mobs

code/game/objects/effects/decals/cleanable.dm
When you move or are moved through blood while lying down you will become bloody. This works alongside footprints and requires blood puddles that aren't already drained.
More immersive to actually become bloody when pulled through puddles of blood. Also encourages people to clean their outfits if they choose to be a floor-dweller.
Tested with different combinations of species, outfits, and mob states. Behaved as expected.
:cl:
add: Become bloody when prone and moving through blood
/:cl:
=> Blood crawling (not the one you're thinking of)

code/__DEFINES/_tick.dm, code/controllers/configuration/sections/mc_configuration.dm, code/controllers/controller.dm, code/controllers/failsafe.dm, code/controllers/master.dm, code/controllers/subsystem.dm, code/modules/mob/mob.dm
Updates the MC to TG's latest standards, minus the init stages part because we dont care about those.
The main addition here is that of the punisher, which will force SSs that overran their tick to be delayed, which should help with the game loop in highpop, especially when atmos is starting to lose it a bit.
Upgrades people, upgrades
SSs still init, runlevels still work as intended, 0 runtimes.
I am still going to TM this on prod.
add: THE PUNISHER
experiment: Upgraded the MC
/:cl:
=> Upgrades the MC

code/game/objects/items.dm, code/game/objects/structures/crates_lockers/closets.dm, code/game/objects/structures/tables_racks.dm, code/modules/mob/inventory.dm, code/modules/mob/living/carbon/human/inventory.dm
Ported from /tg/.
Adds animations for picking items up, as well as animations for putting items onto certain things, like tables, lockers, or racks. Unlike /tg/, it won't show an animation when you pull an item out of a bag. It would be an easy fix, though, if it'd be desired.
If you're using pickpocket gloves, picking up items will look visually how it does now, with no animation.
Two big reasons. 
First of all, it looks pretty and adds some fluidity to interacting with items around you. 
Second, it makes it clear where items are coming from and/or going. If you pick up an item, poof. It teleports to your hand. Same for placing an item on a table, it magically appears there without any indication of who put it there.
Having animations should provide some visual feedback as to who picked …
=> Adds animations for picking up and placing items.

code/__DEFINES/uplinks.dm, code/datums/uplink_item.dm, code/game/objects/items/devices/uplinks.dm, code/game/objects/items/weapons/implants/implantuplink.dm, data/mode.txt, paradise.dme
Nothing to the players
Changes uplink shop to depend it on uplink type. It was dependent on game mode before so if we want to create both traitors and nuclear agents, we would fail
Also added all uplink items to admin uplink(Syndicate Officer or spawnable radio) all uplink items
More freedom to admins for making rounds more interesting and unexpectable. Nukie team after 100 mins of boring round? Go for it!
Compiled and runned on current build, spawned random uplinks, summoned items
Nothing changed to the players
=> uplink updates

code/game/objects/items/weapons/melee/misc.dm
Makes spellblade sharp again
It's a sword. Sword are sharp. Was sharp before rework.
It's a one variable change.
:cl:
fix: Spellblade is sharp again
/:cl:
=> Makes spellblade sharp again

code/modules/admin/verbs/serialization.dm
Messages admins when a json is used.
Logs what was spawned to an admin log
This stuff should be logged.
Spawn in.
Deserialize. 
Confirm it is in the admin log, and in game logs after server was restarted.
N/A, not player facing.
=> Json spawning is now logged

code/datums/emote.dm
Changes 
"You hear how [user] [emote]"
to 
"You hear how someone [emote]"
You cannot HEAR who is making sound
If we are blind, we are blind. If we cant see anyone, we cannot see who is making sound too. 
Compiled
:cl:
tweak: If someone making a sound(not talking) and you are blind, you will not see who is making it in chat
/:cl:
=> removing name from blind_message attribute

code/__HELPERS/text.dm
Adds a `[syndielogo]` pencode so nefarious individuals can make the syndie logo on papers/forms like they can with NT logo.
I don't know, roleplay? It's weird we don't have this when it can be used in a variety of situations (and pranks)
Paper tests.
:cl:
add: Added [syndielogo] pencode to allow syndicate logo on paperwork
/:cl:
=> Adds syndicate logo pencode

code/modules/mob/living/carbon/human/species/_species.dm
Fixes species armour, oversight in #18547
fixes #18853 
This should function.
Beat the shit out of myself
:cl:
fix: Species armour works properly again.
/:cl:
=> Species armour fix

code/modules/mob/living/carbon/human/species/_species.dm
=> ARMOUR FIX 2

.github/CONTRIBUTING.md
=> The headcoder shuffle

code/game/objects/items/weapons/grenades/custom_grenades.dm
Fixes some old and horrible code with a dirt grenade
Code imrprovement, code is no longer broken.
I used the grenade, it worked.
=> Fixes some broken code with a dirt grenade

code/modules/reagents/chemistry/reagents/misc.dm
This adjusts the current spraytan overdose lines into a different selection of custom ones.
The current lines for spraytan overdosing come from a fairly [terrible meme](https://knowyourmeme.com/memes/shit-was-so-cash) that really shouldn't be repeated on the server with our current ruleset. It would better to have unique lines instead of referencing said meme.
Confirmed the correct lines are said while overdosing.
:cl:
tweak: Changes spraytan overdose lines to a different selection.
/:cl:
=> Spraytan overdose update

_maps/map_files/RandomRuins/SpaceRuins/wizardcrash.dmm
Fixes invisible locker in the wizard crash space ruin.
Behold as I make this closet disappear!
Went to the wizard crash ruin.
:cl:
fix: Fixed invisible locker in the wizard crash space ruin
/:cl:
=> Fixes invisible locker in the wizard crash space ruin

_maps/map_files/RandomRuins/SpaceRuins/ussp.dmm
Fixes the last (I hope and think it is) invisible locker, which is on USSP.dmm
Long awaited trilogy to #18569 and #18948
Russians may have magic anti-capitalistic walls but they do not have the power of invisibility
Loaded up server, went to USSP ruin, locker works as intended
:cl:
fix: Fixes an invisible locker in the USSP space ruin
/:cl:
=> Fixes the last invisible locker

code/game/atoms_movable.dm, code/game/objects/buckling.dm
Makes it impossible to pull yourself forward on something you're buckled to (EG. Wheelchairs, ambulances, office chairs)
1. This mechanic is exploitable.
2. How would you PULL something you are sitting on forwards, it doesn't make any sense
Buckled myself to office chairs, vehicles and wheelchairs and tried to pull myself and various other objects while buckled.
:cl:
fix: You can no longer pull something you're buckled to.
/:cl:
=> You can no longer pull something you're buckled to.

_maps/map_files/Delta/delta.dmm
Connects the Mime and Clown offices to the main grid on DeltaStation.
Map bugs be bad, map fixes be good.
Loaded up local server
Started the round
Looked at both APC's.
:cl:
Fix: Clown and Mime offices are now connected to the main power on DeltaStation
/:cl:
=> Reconnects DeltaMime and DeltaClown to the Powernet

code/modules/economy/EFTPOS.dm
It changes the EFTPOS scanner from a Normal Sized item to a small sized item.
The EFTPOS isnt used by many people because its the size of a normal item, which takes up 1/7th of your backpack. Having it be smaller and not the same size as a fire extinguisher will be able to open up more opportunities for roleplay and economy improvements.
Tested and compiled, joined as chef, looked at the EFTPOS and it was a small-sized item.
:cl:
tweak: EFTPOS scanners are now small items.
/:cl:
=> Makes the EFTPOS a small item

code/game/objects/items/weapons/implants/implant_abductor.dm, code/game/objects/items/weapons/implants/implant_adrenalin.dm, code/game/objects/items/weapons/implants/implant_chem.dm, code/game/objects/items/weapons/implants/implant_death_alarm.dm, code/game/objects/items/weapons/implants/implant_dust.dm, code/game/objects/items/weapons/implants/implant_emp.dm, code/game/objects/items/weapons/implants/implant_exile.dm, code/game/objects/items/weapons/implants/implant_explosive.dm, code/game/objects/items/weapons/implants/implant_freedom.dm, code/game/objects/items/weapons/implants/implant_health.dm, code/game/objects/items/weapons/implants/implant_krav_maga.dm, code/game/objects/items/weapons/implants/implant_mindshield.dm, code/game/objects/items/weapons/implants/implant_sad_trombone.dm, code/game/objects/items/weapons/implants/implant_storage.dm, code/game/objects/items/weapons/implants/implant_tracking.dm, code/game/objects/items/weapons/implants/implant_traitor.dm, code/game/objects/items/weapons/implants/implant_uplink.dm, code/game/objects/items/weapons/implants/implantcase.dm, code/game/objects/items/weapons/implants/implanter.dm
Makes implant cases not have their implant be visible on first load, it also refactors them slightly to remove copied code. It also adds a few missing corresponding implanters/implant cases such as the health implants/nuclear implants
Invisible things are bad, consistency is good with having implanters/implant cases for everything
Started a server and spawned all the implants, no runtimes. I will do some testing in a bit about implanting all the implants.
:cl:
fix: Fixes implant cases holding invisible implants on first load
add: Adds a few missing implanters/implant cases where they were missing
/:cl:
=> Fixes implant cases being invisible, refactors slightly implant cases and implanters

_maps/map_files/Delta/delta.dmm
Adds the missing Chaplain Zippo to Delta, fixes #18979 
Consistency is good, especially map consistency
Start up delta, the zippo is there
:cl:
fix: Fixes the missing Chaplain Zippo on Delta
/:cl:
=> Adds the missing Chaplain Zippo to Delta

code/modules/admin/admin_verbs.dm, code/modules/client/client_procs.dm
Fixed the re-admin verb so that it works as expected with clients that were admined due to connecting from the same.
Bugs are bad
I have tested that the verb now works for the intended use-case, and nothing else.
=> Fixed localhost autoadmin for the re-admin verb

code/__HELPERS/_string_lists.dm, code/__HELPERS/files.dm, code/controllers/subsystem/mapping.dm, code/datums/helper_datums/map_template.dm, code/modules/admin/admin_investigate.dm, code/modules/admin/outfits.dm, code/modules/admin/verbs/getlogs.dm, code/modules/awaymissions/maploader/reader.dm, code/modules/awaymissions/maploader/writer.dm, code/modules/instruments/songs/play_legacy.dm, code/modules/mob/living/simple_animal/friendly/dog.dm, code/modules/tooltip/tooltip.dm, goon/code/datums/browserOutput.dm
ugh
---
Sidenote I swear I made this PR earlier, I even remember typing the same description. Must have closed the tab without submitting.
=> Fixes a ton of security issues

_maps/map_files/RandomRuins/SpaceRuins/druglab.dmm
Fixes a y-shifted cable in the space ruin drug lab
~~I spent more time testing and writing this PR than I did coding it~~
Cables not connecting visually is bad and it bothers me everytime it shows up when I try to map cables
It compiled, ran, and the cable was in its proper place
:cl:
tweak: Fixes a cable not connecting in the drug lab space ruin
/:cl:
=> Fixes a cable in the space ruin drug lab

code/game/objects/items/weapons/batons.dm, code/modules/antagonists/traitor/contractor/items/contractor_baton.dm
Adds icon_states to telescopic batons, allowing them to be seen as they appear in game when mapping.
Seeing a police baton while placing a telescopic or contractor baton is confusing
(In mapping view)
Placed the items in a map, works as intended. Server still compiles, runs, no runtimes upon creating telescopic and contractor batons
Nothing player-facing.
=> Adds icon_states to telescopic batons

code/modules/research/designs/smelting_designs.dm
Renames ORM alloys to something more new player friendly.
"Alloy_name+Alloy_name" > "MAT_Name(Alloy_name+Alloy_name)"
"Plasma+Iron" Didn't make it clear for new players (mostly from cargo) that it creates Plasteel, now it does.
:cl:
tweak: ORM: Improved alloy naming
/:cl:
=> ORM: Improved alloy naming

code/modules/arcade/crane.html
Removed line 252 wich did execute the proc win() a second time, leading to double prizes.
Fixes https://github.com/ParadiseSS13/Paradise/issues/10130.
- tested by playing (ALOT)
:cl:
fix: Claw game no longer gives double prizes
/:cl:
=> Fix issue #10130 Claw Game gives double prizes

code/modules/atmospherics/machinery/atmospherics.dm
Adds a check to see if you changed your magboot status mid-wrenching of a pipe.
Fixes #19063
Activated and deactivated magboots while wrenching a pipe
:cl:
fix: Fixes atmos magboots from not preventing you from being thrown occasionally.
/:cl:
=> Fixes magboots not preventing you from being thrown

code/modules/crafting/guncrafting.dm, code/modules/crafting/recipes.dm, code/modules/research/designs/weapon_designs.dm
Changes energy crossbow cyborg kits to require a laser gun.
Kinetic accelerators are a biiiit too easy to come across for the average antagonist, it as it has been shown many times.
They now need a laser gun
Confirmed in game a laser gun was needed.
:cl:
tweak: Energy crossbow gunkits now require a laser gun.
/:cl:
=> Energy crossbow gunkits now need a laser gun

code/datums/supplypacks.dm
Adds the barber kit supply_pack (cost = 20). 
Contains barber uniform, barber starter kit box and lipstick box.
A crewmember that job transfers to barber has currently no way to acquire a barber uniform and most of the equipment necessary for the job.
- Did order the crate, all names and contents looks good.
:cl:
add: Added barber kit crate, orderable by cargo.
/:cl:
=> Adds barber kit supply crate

code/game/machinery/computer/medical.dm, code/modules/client/preference/preferences.dm
Makes species with no blood to use "None" and Slime People to use "Slime Jelly as their blood type.
Added "None" and "Slime Jelly" as options for medical record edits.
It's good for species immersion to not have an ID/Medical Record displaying the wrong/non-existent blood type.
- Verified ID details and medical records for the relevant species
- Tested slime jelly transfusion, did work
- Verified the inclusion of the new medical record options (Because of the list size its currently "Hidden" unless you expand the window)
:cl:
add: Added "None" and "Slime Jelly" as medical record blood type options
tweak: Slime People now has "Slime Jelly" blood type
tweak: Species with no blood now has "None" blood type
/:cl:
=> "None" and "Slime Jelly" blood types added for the appropriate species

code/modules/clothing/shoes/magboots.dm, code/modules/clothing/shoes/miscellaneous.dm
If the user isn't flying, sets flying to true for the duration of the throw, once throw ends, varset callback sets falling to false.
They are made for hopping across gaps. Their action button says so. They should do it.
Now they do.
tested with a human set to flying did not lose it using boots.
Tested that people fell in chasms.
Tested that both boot types let you dash over it.
Tested that flying lost after the dash
:cl:
tweak: Jump boots / gravitational magboots leap now works over chasms and lava.
/:cl:
=> Jumpboots (and gravitational magboots) dash actually lets you cross lava / chasms.

code/modules/shuttle/emergency.dm
Makes the emergency shuttle console have resistance_flags = INDESTRUCTIBLE | LAVA_PROOF | FIRE_PROOF | ACID_PROOF, making it indestructible 
I thought it was already, to be honest. Kinda sucks if your entire hijack plan can be beat by a few laser shots.
shot console with a pulse rifle many times.
it did not break.
:cl:
tweak: Emergency shuttle console is now indestructible 
/:cl:
=> emergency shuttle console is indestructible 

code/datums/uplink_item.dm, code/game/objects/items/weapons/storage/uplink_kits.dm, code/modules/reagents/chemistry/reagents/medicine.dm, code/modules/reagents/reagent_containers/hypospray.dm
Renames / reworks nanocalcium.
It now heals organ damage and IB, in addition to bones. 60 organ damage will be healed over 30 seconds.
If the user has less than 40 hp during the organ / ib / healing section, they will heal a decient amount of all damage types.
If they are over 40 hp during this time, they will take slight brute and burn damage, as it is experimental.
Will restore up to 150 units of blood, up to 70%. Not quite a healthy number, but enough they won't keel over and die from blood loss.
Stage 2 crit will be healed during this time. Stage 1 will be healed by the healing.
To make it _slightly_ easier on bald operatives, it will purge up to 10 units of drugs during the first 40 seconds. However, if they use adrenals during stage 2 of the nanomachines, they will probably die …
=> Reworks nanocalcium injectors to be better.

code/modules/pda/cart.dm
Includes new descriptions for several cartridges making it clear wich systems they include.
Most cartridges had no custom descriptions and trying to judge by the name alone what they do can be a difficult task.
- Verified new descriptions in game.
:cl:
tweak: Added new descriptions to several cartridges.
/:cl:
=> Adds new descriptions to several cartridges

code/game/area/ss13_areas.dm
Removes ambimalf.ogg (Space Jam) from the AI chamber. Leaves it in place in all other places it would normally play (such as AI upload).
While I'm not an AI main myself, I've heard many, many people saying that this track gets incredibly grating after a while. Given the fact that ambiance is playing for a good chunk of the round, I can understand why.
Since it still plays in turret-protected regions that *aren't* the AI chamber, you can still get a taste of the sound effect if you want. It just won't torture an AI in their core all round.
Sat in the AI chamber for a little while, the sound effect didn't play.
:cl:
tweak: Removes the space jam ambiance from the AI chamber.
/:cl:
=> Remove ambimalf.ogg (space jam) from the AI chamber

code/modules/mob/living/simple_animal/parrot.dm
Fixes https://github.com/ParadiseSS13/Paradise/issues/19177
Adds a stat check to parrot speak
Ex-parrots should not speak
:cl:
fix: Fixed speaking dead parrots
/:cl:
=> Fixes speaking dead parrots

code/modules/arcade/prize_datums.dm
Adds the white/blue/red plastic ring(10 tickets), glass ring (15 tickets) and shadow ring (40 tickets) to the Prize Counter as prizes
Currently those are the only rings not being used anywhere in the game and can fit as arcade prizes.
- Cheat by spawning tickets.
- Bought all rings, all looks good.
:cl:
add: Added cool rings to the Prize Counter
/:cl:
=> Adds plastic/glass/shadow rings to Prize Counter

code/game/objects/items/weapons/melee/misc.dm
Make it so the proc will be executed to instakill bugs instead of returning.
Fixes https://github.com/ParadiseSS13/Paradise/issues/19173
- Spawned all bugs and killed them in one hit
- Tested with other mobs and just attacked them normally
:cl:
fix: Flyswatter instakills bugs again
/:cl:
=> Fix #19173 Flyswatter instakills bugs again

code/game/machinery/computer/camera.dm
Fixes grammar and punctuation on the message you get when you attempt to use a camera console as AI.
Grammar good.
:cl:
spellcheck: Fixed grammar and punctuation on "AI using camera console" message
/:cl:
=> Fixes typo when AI uses camera console

code/modules/mining/equipment/survival_pod.dm
Fixes people being able to use an item on station they shouldn't be able to
Exploits bad
Played around with it, correct behavior was shown
:cl:
fix: Fixes a certain item being able to be used on station
/:cl:
=> Fixes an exploit 

code/game/objects/items/weapons/implants/implant.dm
Merges the two destroy procs
Fixes #18990
Spawned implant, destroyed it with admin-deleting, no runtimes, no GC related
Nothing player-facing
=> Merges two implant destroy procs

goon/browserassets/css/browserOutput-dark.css
Changes asay darkchat from a shade of yellow to a pale green. To make it visually distinct from radio chatter.
Open to suggestions for other colours.
Good luck trying to pick asay messages out at a glance currently, it's been a major pain to do since https://github.com/ParadiseSS13/Paradise/pull/17903
Lorem ipsum dolor sit amet.
:cl:
tweak: Tweaked darkchat asay colour from yellow to pale green
/:cl:
=> Changes darkchat asay colour to be easier to read at a glance

code/game/objects/effects/decals/Cleanable/robots.dm, code/modules/food_and_drinks/kitchen_machinery/deep_fryer.dm, code/modules/reagents/chemistry/reagents/misc.dm
Lets you pour ice in a deepfryer. The results are about what you'd expect, with a flash of fire and a plume of hot oil being spread around the fryer.
Adds a new reagent from it, cooking oil, which is pretty much just oil that doesn't burn down to ash.
It's a funny, simple interaction. Gives you something to do if you really want to (but why would you?).
https://user-images.githubusercontent.com/89928798/192678656-f41d1201-de45-4ce3-824d-209a57ffda2e.mp4
See video.
:cl:
add: Adding ice to a deep fryer causes it to boil over with oil.
/:cl:
=> Lets you deepfry ice 

code/modules/mob/living/carbon/human/species/golem.dm, code/modules/mob/living/carbon/human/species/machine.dm, code/modules/mob/living/carbon/human/species/moth.dm, code/modules/mob/living/carbon/human/species/unathi.dm
Fixes some species having their innate actions not GC 
Things GCing is good, things not GCing bad
Compiled, ran, deleted the affected species after using their abilities, proper GCing
NPFC
=> Species now have their innate actions GC

code/modules/arcade/prize_datums.dm
Added cap revolver cylinder (30 points)
Added toy handcuffs (50 points)
Sorted the prizes by cost.
There is no way to acquire more ammo for cap revolvers wich led to a limited fun value. This PR adds a, expensive, way to buy ammo.
- Cheated by spawning tickets
- Bought all new items and tested them, looks good.
:cl:
add: Prize counter: Added cap revolver ammo and toy cuffs
/:cl:
=> Adds cap revolver ammo and toy cuffs to prize counter

code/game/objects/items/weapons/shards.dm, code/modules/fish/fish_items.dm
Makes sure the final icon_state is "teeth" instead of shards "large","medium","small".
Fixes https://github.com/ParadiseSS13/Paradise/issues/18872
- spawned the teeth and acquired it from a shark, did work both ways.
:cl:
fix: Shark teeth is no longer invisible
/:cl:
=> Fix #18872 Shark teeth is no longer invisible

code/game/objects/items/weapons/implants/implantcase.dm
Fixes implant cases in the same way that this does #19043
Fixes #19297
Print case from RND, try to remove any implant with it, no results. Spawn in an empty case, no results. Spawn in two filled implant cases, can transfer the implants to the new empty implant cases.
:cl:
fix: Implant cases will now start empty instead of having a non-existant implant
/:cl:
=> Fixes implant cases not being empty

code/game/objects/effects/decals/Cleanable/humans.dm
Fixes an exploit involving gibs
Exploits are bad
=> Fixes gib exploit
