ParadiseSS13/Paradise

- code/_onclick/item_attack.dm
- code/game/objects/items/weapons/twohanded.dm
fixes #18787
Moves the actual application of the Syndicate chainsaw buff to `afterattack()` to prevent it from triggering on attempted surgery. This prevents exploiting it to maintain indefinite buff without harming anyone.
Removes some redundant code, like playing a sound effect for unwielded chainsaw, which is played anyway.
Removes actually wrong code from `item_attack.dm`. Successful attacks return null, not TRUE. Necessary for the chainsaw to work on simple mobs properly.
This marginally nerfs the chainsaw, as the killing strike will not grant the buff. The target will die and only after that `afterattack()` will check if they're alive.
One less exploit is good.
Spawned in with a bunch of greys.
Killed a standing grey using a Syndicate chainsaw on all four intents.
Butchered the …
> Moves chainsaw buff application to afterattack()

- code/controllers/subsystem/ticker.dm
Make it so the server picks a random map, **if map voting is disabled in the config**.
The box monotony must end.
I ended a round
Nothing player facing as the config isn't enabled. If I change the config there will be a discord announcement about it.
> True map rotation

- code/__DEFINES/dcs/signals.dm
- code/game/gamemodes/wizard/artefact.dm
- code/game/objects/items/weapons/defib.dm
- code/modules/surgery/organs/heart.dm
This is a different take on #18573, which simply deleted your cursed heart on death.
As it stands currently, cursed heart users are incredibly difficult to revive. The cursed heart functions by adjusting your blood level when you pump it, bringing it down below the insta-death threshold if you don't pump it as needed. 
When you get defibrillated, you get the sleeping status applied, which prevents you from manually pumping your heart, though the pump timer keeps ticking down. This means that you will almost never have enough time to get a single pump in before you instantly die again.
When a player with a cursed heart gets defibrillated, they will be filled with enough blood to be "okay", and their heart will go into overdrive, not needing pumping for a grace period of 10 seconds. This …
> Allow cursed heart to be defibrillated up to three times

- code/modules/projectiles/projectile.dm
Makes the percentage display as the actual percentage and not raw armour value.
Accuracy.
I shot myself on my local server again.
> Fixes armour blocking combat log

- _maps/map_files/Delta/delta.dmm
- Adds a wall to prevent accidental spacewalks from the gamma armoury
- Detective's office now has a solid airlock to give them privacy with the use of their electrochromic windows
- Re-areas a rogue wall to be more appropriate
- Changes the required access for the security maintenance from `1` to `63`
- This is the access we commonly use across basic security doors
- This also now allows the Detective to use the maintenance doors
Map bugs be bad, map fixes be good
Rogue Wall is now Security Office
Newbie Officer Safety Net
Loaded up local server
Confirmed solid airlock status in Detective Office
Checked area of wall to confirm it's status as no longer being Security Equipment Storage
Parked the gamma armoury shuttle to confirm the wall lined up with the airlock.
:cl:
tweak: …
> DeltaStation Security Tweaks

- _maps/map_files/Delta/delta.dmm
- Removes firelocks from underneath the psychiatrist office windows on DeltaStation
- Removes a rogue intercom that was on the floor in the medical lobby
- Moves the paramedic office light switch so they could use the button to open the garage door
Map bugs be bad, map fixes be good
Firelock-be-gone
Light switch, switched
Loaded up local server
Pulled psychiatrist fire alarm
Confirmed the lack of intercom on the floor in the lobby
Confirmed that the light switch had been moved in the paramedic office and still operated
:cl:
fix: Paramedic can now access the garage door button on DeltaStation
fix: Removes firelocks from Psych Office windows on DeltaStation
fix: Removes the rogue intercom from the floor in the Medbay Lobby on DeltaStation
/:cl:
> DeltaStation Medical Tweaks

- code/game/objects/items/weapons/powerfist.dm
Reduces powerfist gas consumption by 5/6ths.
Adds nodrop whenever a gas tank is inserted into the fist, removes nodrop when the tank is removed.
The powerfist is a fairly terrible traitor item, having some of the worst ammo efficiency of any weapon in the game. With a stock oxygen tank, you can use the fist's maximum setting only twice before running dry.
This PR aims to make the fist a bit more competitive as a damage dealer.
Additionally, nodrop was added at the request of Qwertytoforty.
- Loaded test server
- Spawned fist
- Tested loading and unloading the fist. (works with both stock oxygen and plasma tanks)
- Beat numerous vox to death
- Fist works as intended
:cl:
tweak: Buffed the powerfist, lowering gas consumption and adding nodrop
/:cl:
> Buffs the powerfist

- code/modules/projectiles/guns/syringe_gun.dm
Adds an alert and an examine message to the syringe gun, dart pistol, and the oldRSG stating that you cannot use DNA-Injectors with them.
Adds the line "Not compatible with DNA-Injectors." to the three syringe-based syringe guns 
Adds the alert text "[Syringe gun type] is incompatible with DNA-Injectors." Upon attempting to add a DNA-Injector to these weapons. 
Fixes #18844 
Injectors do look similar to syringes, and currently gives no feedback upon denying one from use. This adds visual feedback, so the player knows that this is intended behavior. 
Compiled code and ran, attempted both interactions, text showed up when it should, attempted normal syringe interactions, correct text showed up and no behavior was altered. 
:cl:
spellcheck: Adds messages for the DNA-Injectors not being …
> Clarifies that DNA injectors cannot be used with syringe guns 

- code/datums/outfits/plasmamen.dm
- code/modules/client/preference/preferences.dm
- code/modules/mob/living/carbon/human/species/plasmaman.dm
Allows the Large Plasma Tank to be selectable as an option for Plasmamen in Character Preferences.
The Large Plasma Tank is not used at all which is shameful. This allows it to be used and gives plasmamen a small amount of customization.
I tested it in-game on a private server. The feature should work as intended.
:cl:
add: Large Plasma Tank is now selectable for Plasmamen.
/:cl:
> Large Plasma Tank

- code/modules/mob/living/carbon/give.dm
Towards the end of my give rework I changed the alerts to be `"take item"` instead of `"give item"`, and I forgot this one, causing weird invisible alerts to stay around and fuck with other alert positioning.
Fixes #18886
Got two player clients. Used the Give Item verb/hotkey to trade items back and forth. Confirmed no ghost alerts stuck around to fuck with other alert icons.
:cl:
fix: Fixed an issue where Give Item alerts were not going away properly.
/:cl:
> [GBP: No Update] Fixes problems with Give alerts

- code/modules/mob/living/carbon/give.dm
After a successful Give Item, both the giver and the receiver were being shown failure messages. This was because once the item was unequipped from the giver with `giver.unEquip(I)`, `COMSIG_ITEM_DROPPED` is fired which fires `cancel_give`, which then displays the failure messages in that proc.
No more misleading feedback.
Got two client's, used Give to hand things back and forth. Saw no failure message when the give was successful.
:cl:
fix: Fixes Give Item failure messages showing even though the give was successful
/:cl:
> [GBP: No Update] Fixes Give Item failure messages showing even though the give was successful

- code/modules/admin/admin_verbs.dm
Makes it so verbs that are meant to be used by admins are not available to admins who de-admin.
Duh.
It works
> Remove maintainer verbs from de-admined clients

- code/modules/mob/living/simple_animal/hostile/megafauna/ancient_robot.dm
- code/modules/mob/living/simple_animal/hostile/megafauna/bubblegum.dm
Bubblegum / vetus no longer bump twice, hitting for twice as much, rather than bumping once.
Ever noticed that when bubblgum / vetus bumps into something, it hits them twice?
Yeah, thats a fun issue with Bump()
This hurts extra bad with bubblegum, as it ignores armor.
This PR makes them hit once (in bubblegums case for 30 brute) rather than twice for 60 brute total.
This does make the fights easier, I was considering upping the damage to 40, but this is also ideally a fix, not balance.
Spawn bubblegum / vetus.
Get charged at.
Enjoy not getting hit twice every time instead of once.
:cl:
fix: Fix bubblegum / vetus speculator hitting mobs twice in their charge rather than once.
/:cl:
> fixes bubblegum / vetus hitting twice during charge

- code/game/objects/effects/glowshroom.dm
Fixes glowshrooms being able to be pulled
bugs bad
Compiled, made sure the glowshrooms and other variants couldn't be moved
:cl:
fix: Glowshrooms/shadowshrooms/glowcaps can no longer be pulled
/:cl:
> Fixes Glowshrooms being able to be pulled.

- code/__DEFINES/construction.dm
- code/game/machinery/defib_mount.dm
- code/game/objects/items/mountable_frames/air_alarm.dm
- code/game/objects/items/mountable_frames/apc_frame.dm
- code/game/objects/items/mountable_frames/buttons_switches.dm
- code/game/objects/items/mountable_frames/extinguisher_frame.dm
- code/game/objects/items/mountable_frames/fire_alarm.dm
- code/game/objects/items/mountable_frames/frames.dm
- code/game/objects/items/mountable_frames/intercom.dm
- code/game/objects/items/mountable_frames/lights.dm
- code/game/objects/items/mountable_frames/newscaster_frame.dm
Refactors mountable frames code to:
- be able to drop metal and glass sheets upon wrenching
- use bitmaps instead of string lists for mounting requirements
- to be up to modern standards
- all of that deleted code in the newscaster frame file is stuff that is already handled in parent procs (wtf)
**Moves newscaster frames to drop 7 metal and 4 glass instead of 2 metal to reflect autolathe costs**
Better code
Newscasters shouldn't just eat 5 metal and 4 glass if you want to wrench it back into base materials.
fixes #18705
1. Loaded up test server
2. Game Panel spawned in all mountable frames
3. Deconstructed every frame with wrench
4. Attempted to place each frame on an empty (no wall items) r-wall in a powered room
5. Attempted to place each frame on an empty r-wall in space with no floor …
> Minor Mountable Frame Code Refactor

- code/modules/paperwork/photocopier.dm
Fixes #18875
Less exploits are good
Verified that terrors can no longer be dragged on top of photocopiers.
Verified that it is still possible for humans and Ian
:cl: uc_guy
fix: Fixed exploit that allowed terror spiders and other large mobs to be dragged on top of photocopiers.
/:cl:
> Add move resist check to photocopier.

- code/game/machinery/Sleeper.dm
- code/game/machinery/adv_med.dm
fixes #18797
Makes sleepers and body scanners use all four sprites when a wrench is applied to them.
Removes a vestigial variable, `orient`, which wasn't actually doing anything.
Someone was bothered by it enough to write a bug report. More options is generally a good thing, too.
Spawned in.
Used a wrench on both machines.
Confirmed both rotate properly.
Successfully put a grey into both machines in all four positions.
:cl:
tweak: Wrenches can now make sleepers and body scanners face north and south.
/:cl:
> More positions for body scanners and sleepers when using a wrench

- code/modules/awaymissions/corpse.dm
This PR adds Nian to the "pickable species" spawner list. This means you can now select Nian as your species when playing as the syndicate researcher, beach bum, veterinarian, or bartender ghost roles.
Nian were missing from the species spawner list due to an oversight. The oversight has been fixed, and you can now be a moth.
Compiled and tested on a local debug server.
:cl:
tweak: Nian is now a selectable species for several ghost roles
/:cl:
> Adds Nian to selectable ghost role species

- code/game/gamemodes/blob/powers.dm
- code/game/gamemodes/blob/theblob.dm
Would like a TM, everything worked fine on my end, but balance / just making sure there is nothing fucky with putting the overmind var on all normal blob tiles.
Non dense mobs getting attacked by blobs experience double chemical reaction (As a finisher to someone in crit, or to punish someone who is trying to crawl to blob so they can only be attacked once)
Blobs can now attack people on blob tiles for 5 points, rather than having to destroy the tile to attack first.
Blobs will passively attack mobs ON THEIR OWN TILE when pulsed, at **most** once per second. Realistically, 2-4+ between attacks. This will not affect people beside blobs, only people inside a blob, most likely due to being in crit, or because they were crawling.
Normal blob tiles actually get their overmind variable now, so …
> Blob now punishes crawlers. [TM pls]

- code/game/objects/structures/safe.dm
Progress bar for thermal drill properly gets removed once it's done.
Thermal drill now automatically gets removed when clicked on if it's done drilling.
Thermal drill now makes a ding noise when done drilling
fixes: #18916
Previously players have been confused about when the thermal drill was done due to the progress bar not being properly removed. This PR also slightly streamlines removing the drill once it is done drilling.
What does a thermal drill have in common with a microwave?
They both go 'ping!' When their done.
Attached drill to safe.
Turned drill on
Turned drill off
Removed drill after it's done drilling
:cl:
fix: Progress bar for thermal drill properly gets removed once it's done.
/:cl:
> Improves thermal drill clarity

- code/modules/awaymissions/mission_code/ghost_role_spawners/golems.dm
Currently there is nothing stopping borgs, drones, etc from finishing golem shells and having their own golem servants. This updates it so that humanoids are required to finish the golem.
Consistency to the idea that dexterous tasks require finer human manipulation.
Stops certain roles, such as maintenance drones, from completing golems and having their own servants when this shouldn't normally be possible.
Confirmed that it worked as expected when testing humanoid mobs, silicon mobs, etc.
:cl:
tweak: Golem shells need to be finished by humanoids.
/:cl:
> Golem shells require more dexterity

- code/game/objects/structures/crates_lockers/crates.dm
- code/modules/mining/abandonedcrates.dm
- code/modules/reagents/chemistry/reagents/medicine.dm
Allows toggling of crates with alt click, also slightly changes trying to toggle the lock on a locked lootcrate so it doesnt blow you up when you accidently alt click it. It now makes you attack it with your hand, allowing you to enter the code like you would with an empty hand.
Lockers and secure crates are very similar and its annoying trying to lock them with verbs.
Blew myself up with a secure/loot crate, and changed it. Made sure that toggling the lock only works when you have the correct access.
:cl:
tweak: You can now alt-click to lock/unlock crates, similar to lockers.
tweak: Alt-clicking a locked lootcrate will pop up the code entry menu, allowing you to solve it without switching hands.
/:cl:
> Allows toggling of crate locks with Alt-Click

- code/modules/mob/living/carbon/alien/humanoid/alien_powers.dm
- code/modules/mob/living/carbon/alien/humanoid/humanoid.dm
- code/modules/projectiles/projectile/bullets.dm
- code/modules/surgery/organs/subtypes/xenos.dm
This PR adds a 5 second cooldown to the Xenomorph neurotoxin ability. Neurotoxin no longer "weaken" stuns humans, but instead applies ten seconds of knockdown and 40 stamina damage. Neurotoxin toxin damage is untouched.
Advances #18179 and #18888
Neurotoxin only costs 50 plasma to use, and Sentinels can store up to 500 plasma. Being able to fire up to 10 projectiles instantly with no cooldown is a little insane.
Paradise has largely moved away from instastuns in combat, and Xeno neurotoxin is one of the last holdouts. Removing instastuns from Xenomorphs so they respect Paradise's combat conventions is necessary if they're ever going to be readded to rotation.
Compiled and tested on a local debug server.
:cl:
tweak: Xenomorph neurotoxin now has a 5 second cooldown
tweak: Xeno neurotoxin …
> Adds cooldown to Xenomorph neurotoxin, changes stun to knockdown

- code/game/objects/items/weapons/storage/bags.dm
- code/modules/hydroponics/beekeeping/beebox.dm
- code/modules/hydroponics/beekeeping/honeycomb.dm
- code/modules/reagents/chemistry/machinery/reagentgrinder.dm
- Converts Honeycomb from apiaries from item/reagent_containers to item/reagent_containers/food/snacks.
- Adds item/reagent_containers/food/snacks/honeycomb to the list of permitted items in plant bags.
- Removes specific honeycomb entry from reagent grinder as it's already covered by the snacks entry.
Though honeycomb is not technically a plant, I believe that it's covered sufficiently by hydroponics to warrant its addition as a QoL change. Honeycomb is edible IRL and intuitively should be edible in-game; I perceive no harm in allowing it as well. 
1. Attempted to eat the honeycomb. Ate it. It was delicious.
2. Placed the honeycomb in a plant bag. It fit fine.
3. Placed multiple honeycombs in a plant bag by clicking on them on the floor. This worked fine.
4. Placed multiple honeycombs …
> Makes Honeycomb edible and allows plant bags to pick it up.

- code/game/objects/structures/window.dm
Reinforced windows now needs to be screwed to the floor before you can crowbar it into frame.
Previously you could crowbar then screwdriver the window before it was anchored the floor, breaking the construction sequence.
Tried to crowbar a window that isn't screwed to the floor
Hit it instead of putting it into the frame.
:cl:
fix: Window needs to be screwed to floor before being crowbarred in frame
/:cl:
> Window needs to be screwed to floor before being put in frame

- code/modules/hydroponics/grown/towercap.dm
Makes you unable to chop logs when you have them in your bag or holding them in your hands.
Fixes #18714 
It fixes the invisibility issue above, plus it makes no sense that you can make proper planks while they are in your purse.
1. Spawn `/obj/item/hatchet`
2. Spawn `/obj/item/grown/log`
3. Pick up log
4. Click log with hatchet, get error message
5. Put log into bag
6. Click log with hatchet, get error message
7. Drop log on the floor
8. Click log with hatchet, becomes plank
:cl:
fix: Fixed logs being choppable in hands or bags, consequently turning the new planks invisible.
/:cl:
> Fixes tower cap logs being choppable in bags

- code/datums/diseases/_MobProcs.dm
- code/datums/diseases/_disease.dm
- code/datums/diseases/advance/advance.dm
- code/modules/events/disease_outbreak.dm
- code/modules/events/event_container.dm
- code/modules/mob/new_player/new_player.dm
Splits the disease outbreak event into mundane, moderate and major versions.
Removes the level 7 biohazard announcement
Reworks the random advanced disease generation to make a disease with a severity that fits the event level.
Makes the event infect a new arrival instead of a random person on the station level. That person becomes an infectious carrier, but unaffected by the disease itself.
Fixes buggy random disease generation ( Fixes #13787 )
Removal of the level 7 biohazard announcement provides plausible deniability for antagonist virologists.
Makes mild diseases more common, making the virologists job a bit more important.
Infecting a new arrival instead of a person on the station no longer has the potential to screw up a random antags run. And it is more realistic.
Tested locally. …
> Rework disease outbreak event

- code/modules/detective_work/footprints_and_rag.dm
- code/modules/food_and_drinks/drinks/drinks.dm
- code/modules/food_and_drinks/food.dm
- code/modules/food_and_drinks/food/condiment.dm
- code/modules/hydroponics/beekeeping/honeycomb.dm
- code/modules/reagents/reagent_containers.dm
- code/modules/reagents/reagent_containers/applicator.dm
- code/modules/reagents/reagent_containers/glass_containers.dm
- code/modules/reagents/reagent_containers/hypospray.dm
- code/modules/reagents/reagent_containers/syringes.dm
1. Fixes certain reagent containers having lists of possible transfer rates that were either empty, contained only the default value, or were not even lists. All of these were intended to have fixed transfer rates, but triggered the `Alt-click to change the transfer amount.` examine message and had the `Set transfer amount` verb regardless. All of these were changed to `null` which blocks altering the transfer rate, suppresses the examine message, and removes the verb when initializing.
2. Moved the sanity checks around in `set_APTFT()` so that canceling while in a position that would normally trigger one of the warnings does not produce one (since you're choosing to do nothing anyway).
3. Added a quality-of-life feedback message when transfer rate of a container was changed successfully. …
> Small container transfer rate change improvements

- code/controllers/globals.dm
Removes an unused section of code that causes a bad index runtime (pretty sure AA asked for this to be removed). 
I like when my debugger doesn't need to ask me if I want to continue
Compiled and started, no runtime
Shot stuff and blew stuff up, no runtimes
Purposefully caused a runtime to make sure that I didn't accidentally stop runtimes from appearing 
> Removes a line of code that causes a runtime 

- code/modules/projectiles/projectile/bullets.dm
Meteor shot now knocks down for 8 seconds instead of stunning for 8 seconds.
Part of stun removal project progression.
Shot myself with some meteorshot.
Crawl around.
:cl:
tweak: Meteorshot now knocks down instead of stunning.
/:cl:
> Meteorshot now knocks down instead of stunning

- code/game/objects/items/weapons/implants/implant_mindshield.dm
- code/modules/mob/living/carbon/human/human.dm
- code/modules/surgery/organs/organ.dm
- code/modules/surgery/organs/subtypes/standard.dm
Adds implants (implanter-based ones like mindshields) to serialisation
Adds hair gradient data to serialisation
Removes organ DNA from serialisation (this was totally redundant and did not need to be saved)
Slight refactor of mindshield implant code to avoid runtime due to mindless mob
Admin QoL, characters can spawn in with implants already inserted
Tested spawning saved characters with and without implants and hair gradients, making new jsons and spawning them
:cl:
tweak: Hair gradient and implants saved on admin character json serialisation
/:cl:
> Adds implants and hair gradients to serialisation

- code/game/machinery/doors/airlock.dm
- code/game/machinery/doors/door.dm
- code/game/objects/items/devices/painter/airlock_painter.dm
Fixes stuck glass overlays in airlocks when a polarized airlock was activated within range. The caching system had to be removed as it really didn't like having color values. Performance might take a small hit, but `cut_overlays` is used so that part at least goes through the subsystem. `overlays +=` is still used due to fine timing issues.
No stuck glass.
https://user-images.githubusercontent.com/80771500/187565907-e58afa89-0895-4a34-ae1a-3a927a01f9f9.mp4
Two airlocks next to each other, one is polarized, the other isn't.
:cl:
fix: Glass airlocks do not have stuck glass when opened if there's an active electrochromic airlock nearby.
/:cl:
> [GBP: No update] Fix odd airlock interference with polarized airlocks

- _maps/map_files/Delta/delta.dmm
- _maps/map_files/MetaStation/MetaStation.dmm
- _maps/map_files/cyberiad/cyberiad.dmm
Repositions Turbine Scrubber behind Turbine so that it no longer reduces pressure in the burn room, and instead scrubs exhaust if you want to do something fancy with it (like clean it out of CO2 and put it back into the burn room).
Also adds valve between Turbine Exhaust pipe and Turbine intake pipe on other stations (already exists on Cyberiad) so you can  put the exhaust back into intake (which never 100% burns so it still have 85% of old burn mix).
Optimization will still take time and effort, but no-brain "just mix 50-50 Plasma-Oxygen and let it burn" now produces 100kW instead of 60-70, and consumes stuff slower. Also fully upgraded Turbine gives 600kW.
Before to achieve that you needed to disable or unwrench that scrubber.
Turbine is rarely used and the scrubber action is really …
> Makes that Turbine Scrubbers no longer fight against Turbine itself

- code/datums/spells/wizard.dm
Stunned / force crawling people can be hit by a fireball, by clicking on them directly, similar to how a gun works.
Fireballs no longer blow up in the wizards face
Fireball not hitting people stunned when you clicked on them was always stupid. Now you can.
Fireballed manual crawler without clicking on. Hit.
Fireballed at forced crawler by clicking over. Miss.
Fireballed at forced crawler by clicking on them. Hit.
:cl:
tweak: Fireball spell acts more like a gun, and can hit stunned / crawling mobs when clicking on them directly.
fix: Fireballs no longer blow up in the wizards face
/:cl:
> wizard can now hit forced crawlers with fireball by clicking on them

- code/controllers/configuration/sections/vote_configuration.dm
- code/modules/vote/vote_presets.dm
- config/example/config.toml
Adds a config option that, when enabled, prevents the current map from showing up in the map vote options
More flexibility to allow different map rotation styles
All i hear is the map vote noise now
:cl:
add: Added a config option to prevent the same map from being voted on twice in a row
/:cl:
> Adds config option to prevent repeating maps

- _maps/map_files/cyberiad/cyberiad.dmm
This PR adds pipenet redundancy to sci and med, since these departments had single entry-exit points that made life really sucky for ventcrawling antags.
Fixes a single missing wire in mining maints (why not) Fixes https://github.com/ParadiseSS13/Paradise/issues/18893
Fixes two turfs on one tile in departures, leading to plating that looks like a wall near the departures beach.
More options for antag movement, one removed pipe won't screw a round.
pipes
:cl:
tweak: Added atmos pipe redundancy to science and medical
fix: Missing cargo power wire added in cargo maints
fix: Fixed walls acting like plating in box departures beach bar
/:cl:
> Box station tweaks & fixes (pipe redundancy)

- code/game/machinery/tcomms/core.dm
- code/game/machinery/tcomms/presets.dm
- code/game/objects/items/devices/radio/radio.dm
When not already linked to a core, the CC tcomms relay will auto-link to any new built tcomms cores.
ERT commander, CC, DS, and nukie headsets now transmit across all Z levels when tcomms is down or out, not just the local Z.
This is not a perfect solution to the issue of unlinked tcomms cores, but it hopefully will cut down on the need for admins to manually re-link the relays when station cores are deleted and later re-made.
The headset change also makes it easier for an admin SOO/NNO/event character to communicate with an away team from CC. Previously, admins had to teleport into space somewhere to do this when tcomms is down.
Spawned a bunch of stuff, linked and unlinked, etc.
Screamed obscenities into headsets.
:cl:
tweak: CC tcomms relay auto-links to new cores when not already …
> CC tcomms QoL

- code/game/mecha/mecha.dm
- code/game/mecha/mecha_control_console.dm
1. Removes the exosuit tracking beacon's EMP act and replaces it with a movement sabotaging one
2. Makes the tracking beacon have 2 charges
3. Exosuits can no longer accept more than one tracker (of each type)
When an exosuit is pulsed, the occupant gets an audio and visual cue about their exosuit's movement being impaired. This is the same movement impair an exosuit gets when it takes too much melee damage.
The exosuit is able to move around and use everything, but its movement is randomised. To fix this, the occupant has to start a recalibration process, and the exosuit has to stand still for 10 seconds. During this timeframe, the occupant is free to leave the exosuit.
The new beacon has two charges. While the exosuit's movement is gimped, no other charges can be used. After the second …
> Reworks the exosuit tracking beacon

- code/game/area/ss13_areas.dm
- code/modules/events/anomaly.dm
- code/modules/events/event_procs.dm
1. Unifies the `findEventArea()` proc for anomalies and dimensional tears, thus fixing the dimensional tear spawning in bad areas like maintenance
2. Removes the unused `/area/ai_monitored/storage/emergency` area both from the possible spawns and its declaration
The issue: both anomalies and the dimensional tear check for an area to start in, via `findEventArea()`. However, the anomaly's `findEventArea()` is pretty much a copy-paste of the original proc with a few added paths of no-no zones that the dimensional tear doesn't have (like maintenance). The tear's area check didn't check for subtypes either.
The solution: both of these will use the same proc, thus having the same list of possible and excluded areas. This way, the dimensional tear can no longer spawn in the following areas: …
> Fixes the dimensional rift being able to spawn in maintenance

- code/game/mecha/medical/medical.dm
- code/game/mecha/working/working.dm
When a Ripley/Odysseus is made, they have a tracking beacon spawned in them (for some reason?). This PR removes this.
1. Makes no sense that any exosuit randomly has tracking beacons spawning in them
2. Robotics SOP already asks for tracking beacons to be added
3. If this is some kind of a safety net, then combat exosuits should get this, not utility mechs
1. Spawn in as an RD
2. Spawn a `/obj/mecha/medical/odysseus`
3. Look at exosuit control console
4. No beacons found
:cl:
del: Ripley and Odysseus mechs no longer start with a tracking beacon installed.
/:cl:
> Removes the pre-spawned tracking beacons from Ripleys and Odysseus

- code/modules/mob/living/simple_animal/bot/griefsky.dm
- code/modules/mob/living/simple_animal/bot/honkbot.dm
- code/modules/mob/living/simple_animal/bot/secbot.dm
Removes the weakens over tripping over simplebots, replaces them with a knockdown (4 for beepsky and griefsky, 10 for honkbot)
For note: this does not remove the stun from honk or mulebots, just the trip weaken 
"tripping" suggests you fell over, and a knockdown makes sense
also stuns bad (Pretty sure this is part of project progression) 
Compiled, ran, checked to make sure that you got a knockdown rather than a stun, made sure beepsky can still baton you
:cl:
tweak: Tripping over simplebots now deals knockdown rather than weaken 
/:cl:
> Removes weakens on tripping over simplebots

- .github/CONTRIBUTING.md
Tweaks contribution guidelines to enforce the following.
If you are adding a config change in a PR to change existing behaviour, you must have the config option default to whatever the closest behaviour is.
The reasoning behind this is largely so if things are merged, behaviour stays the same till that config option is added to production config and voted on between leadership.
I really didn't want to have to make PRs while out a on business trip but this was a pressing matter due to my own mistakes. 
Something something status quo I dont know Im just making a PR 
I webedited this.
N/A
> Tweaks guidelines to prevent my own slip ups

- code/modules/mob/living/silicon/pai/pai.dm
- code/modules/mob/living/silicon/pai/software/pai_toggles.dm
Allows pAIs to buy a diagnostic hud for 20 RAM. It also fixes a glitch in the TGUI menu showing you had multiple huds active, even if you didn't, purely a visual glitch in the menu.
pAIs can already access sec and med huds, diagnostic huds will allow them to help people away from shocked doors and be able to tell the health of IPCs. Plus it makes them a bit more fun to play since you cant buy basically all the huds, doorjack, and almost everything else.
Booted up a local server with two clients, tested a bunch with pAIs, fixed the bug with multiple huds showing in the TGUI menu but only one being active.
:cl:
add: pAIs can now buy diagnostic huds!
fix: Fixes a visual bug where it shows you have multiple huds active in a menu, when you only have one active.
/:cl:
> Adds diagnostic huds to pAIs and fixes a visual glitch with their hud menu

- code/__HELPERS/time.dm
- code/game/atoms.dm
- code/game/machinery/doors/airlock.dm
- code/modules/food_and_drinks/kitchen_machinery/gibber.dm
Added a new Timestamp proc that covers real-time and station time all at once. Makes it easier for certain logs and allows for any future additions/changes that would benefit from having both times used simultaneously.
- Changed fingerprintshidden timestamps to the new proc.
- Changed Airlock shocking timestamp to the new proc.
- Changed Gibbers victim timestamp to the new proc.
Quality of life for admins and, allows people to have an easier way to show real-time and station time simultaneously.
- [✓] Booted up a private server
- [✓] Tested fingerprintshidden
- [✓] Tested Airlock Shocking
- [✓] Tested Gibbers
- [✓] QoL increased
:cl:
tweak: Tweaked timestamps.
/:cl:
> Timestamp QoL

- code/modules/mob/living/carbon/human/human.dm
The `get_idcard()` proc in human.dm now checks for ID inside PDAs on the PDA slot.
This fixes unintended behavior with the Jestographic Sequencer where ID checks fail if the user loads their ID into their PDA.
`get_idcard()` is now more thorough in doing its job, and a traitor item works as people expect it to.
Compiled and tested locally on a private debug server.
:cl:
fix: Jestographic Sequencer now properly checks ID loaded into PDAs on the PDA slot
/:cl:
> get_idcard now checks for ID in the PDA slot

- code/modules/mining/lavaland/necropolis_chests.dm
fixes harm harm disarm katana move from making a runtime.
I did not test after moving the UnregisterSignal into the throw callback. This is on me, and I should know better.
bugs bad.
Spawned in targets, used katana move on them, ensured that it did not runtime for real this time.
:cl:
fix: Fixed cursed katana runtime
/:cl:
> fixes katana runtime GBP NO UPDATE

- code/modules/martial_arts/combos/sleeping_carp/gnashing_teeth.dm
Makes Gnashing Teeth, a Sleeping Carp harm->harm combo, deal sharp damage.
Two reasons:
1. It's silly. Karate chopping someone's head off is pure comedy. Everyone I discussed this with absolutely loved how hilarious the idea is. We want the game to be fun, right?
2. Currently, Crashing Waves Kick offers superior damage when target hits a wall while also providing minor crowd control. If there is a wall available, CWK is pretty much always the optimal choice. This PR would give GT an _edge_, something to make people consider it over CWK.
If this makes Sleeping Carp too strong, we could consider making GT respect target's armour or otherwise reduce delimb chance.
However, my tests indicate it can easily take well over a dozen hits to behead someone, at which point they're effectively dead …
> Gnashing Teeth buff - make it sharp

- _maps/map_files/Delta/delta.dmm
1. Moves the PANDEMIC machine one tile to the right, because it spawns on top of a glass table
2. Removes an extra APC because this area has two, fixes #18985 
They are bugs that need to be fixed.
Before:
After:
The other APC works properly:
1. Spawned in as a virologist
2. Checked area power
3. Checked machine location
:cl:
fix: Kerberos' virology machine no longer spawns on top of a glass table.
fix: Kerberos' virology no longer has two APCs for the same area.
/:cl:
> Fixes Kerberos virology APC and the PANDEMIC

- _maps/map_files/cyberiad/cyberiad.dmm
This tweaks rooms in Cyberiad with polarized windows to use polarized glass airlocks instead of plain opaque ones.
- Blueshield's office
- Chief Engineer's office
- Chief Medical Officer's office
- Courtroom
- Detective's office
- Head of Security's office
- Internal Affairs office
- Interrogation room
- Magistrate office
- NT Representative's office
- Operating Theatre 1 (Theatre 2 has no windows, and wasn't touched.)
- Processing room (The polarized windows are only on one side. The airlocks facing the brig are made polarized glass, the rest wasn't touched.)
- Psych's office
- Research Director's office
With the exception of processing, rooms/setups that only obscure one side aren't touched, as the affected cluster do not include airlocks (e.g. Robotics).
Consistency, now that airlocks …
> Cyberiad - Polarized airlocks

- _maps/map_files/cyberiad/cyberiad.dmm
Replaces the security newcaster in boxstation's cargo bay with a normal one.
Cargo is not sec sadly.
Spawned in, check newcaster, can no longer 1984 random articles and make fancy wanted poster things.
:cl:
fix: Fixed Cyberiad's cargo bay having a security newcaster, not a normal one.
/:cl:
_I am deeming this a fix_
> Removal of a security newcaster on boxstation's cargo bay

- code/modules/events/disease_outbreak.dm
- code/modules/events/event_container.dm
Combines the major and moderate disease outbreak into one.
Major disease outbreak was firing too often.
Even major diseases are not as catastrophic for the station as other events in the major category thus "wasting" a midround with a non-event.
Verified that the disease generation, ghost message and infection are still working as intended.
:cl: uc_guy
tweak: Combines the major and moderate disease outbreak events into one.
/:cl:
> Combines the major disease outbreak event with the moderate.

- code/game/objects/effects/spawners/lootdrop.dm
Removes the colors from lootdrop icon_states, making them actually visible and not black question marks
The color lines were last touched SEVEN years ago. How did we go this long without ever noticing this.
Being able to see what you're mapping is good
Before:
After:
Opening mapping software: I can read the maps. Game still compiles and runs.
Nothing player facing, just mapper facing.
> Mapping indictors for lootdrops are readable now

- code/modules/events/disease_outbreak.dm
Blacklists bath salts "Berserker" disease from disease outbreak event.
Non-spreadable diseases do not function in the disease outbreak event. Thus rolling that disease results in the event failing and not having any effect.
Absence of /datum/disease/berserker in the list of eligible diseases verified with a debugger.
:cl: uc_guy
fix: Non-spreadable disease berserker can no longer be rolled in the disease outbreak event.
/:cl:
> Blacklists bath salts "Berserker" disease from disease outbreak event.

- code/game/machinery/dish_drive.dm
Makes the dish drive pick up snack bowls, left behind by soups mainly.
Removes an unnecessary visible message.
This is a neat item to keep the kitchen empty, it not picking up snack bowls was an oversight.
Less spam is good.
https://user-images.githubusercontent.com/33333517/189480028-09ddba4f-c5a3-4d60-9cc4-57dcb0909118.mp4
1. Spawn an `/obj/item/coin`
2. Add it to the ChefDrobe, vend a DIY Dish Drive Kit
3. Assemble it
4. Spawn a `/obj/item/reagent_containers/food/snacks/soup/tomatosoup`
5. Eat it
6. Drop the snack bowl on the ground
:cl:
fix: The dish drive now picks up snack bowls as well.
/:cl:
> Fixes dish drive not picking up snack bowl and spamming the chat

- code/game/objects/items/dehy_carp.dm
Changes a `sleep()` in dehy_carp.dm to `addtimer()`, which avoids a runtime when hydrating dehydrated space carp. Splits `/obj/item/toy/carpplushie/dehy_carp/proc/Swell()` into two procs. No player-facing changes.
Runtimes bad.
Compiled and tested on a local debug server.
> Fixes runtime on dehydrated space carp

- code/modules/mob/living/carbon/alien/humanoid/alien_powers.dm
The Xenomorph "Secrete Resin" ability now checks if you're attempting to build on a space tile, same as weed planting. This fixes... Xenomorphs being able to generate anchored walls and resin beds in the vacuum of space, inadvertently making them masters of deep space mobility.
I can't ask the person who designed Xenomorphs if this is intended behavior because they're probably in a nursing home by now, but considering weed planting checks for space, it definitely seems like a bug that you can construct solid walls in an area that has nothing to anchor them in place. And fixing bugs is good.
:cl:
fix: Xenomorphs can no longer build resin structures on space tiles
/:cl:
> Fixes Xenomorphs being able to build resin structures in space

- code/modules/mob/living/carbon/alien/humanoid/life.dm
Xenomorphs that enter crit now take a steady trickle of brute damage over time. This damage will eventually kill them unless they're on alien weeds, in which case the weed's regeneration will outheal the DOT, and the Xeno will recover.
Fixes a very nasty bug where Xenos who enter crit are stuck in limbo until an admin intervenes to give them a merciful death. Yes, until this PR Xenos could stay in crit indefinitely.
Going into crit in a pipe and having to ahelp because you neither die nor leave crit is bad. How was this not found years ago?
:cl:
fix: Xenomorphs who enter crit will now slowly bleed out over time.
/:cl:
> Xenomorphs can now die

- code/datums/mind.dm
- code/game/gamemodes/objective.dm
- code/modules/mob/mob_helpers.dm
- code/modules/shuttle/emergency.dm
Lets antagonists be able to hack the shuttle console, starting a do after to progress the state of the hijack.
Each time this is done, it makes a VERY NOTICEABLE alert to everyone on the shuttle, and attempting it makes noise at the console. If shuttle is in transit, adds 30 seconds to the shuttle timer. 5 second delay between successful attempts.
Takes 15 seconds per stage for any antagonist. 10 seconds for a hijacker. Mindslaves, as per being antags, take 15 seconds, and can be used.
The old hijack system remains, and also passess objectives. 
Malf AI's block objective has been adjusted / clarified. Mentions that doomsday works for passing it, and they now use the **OLD** hijack system. This means that the shuttle must meet **CURRENT** hijack requirements, just hacking the console will …
> Ports the shuttle console hijack from TG. Tweaks malf AI hijack.

- code/modules/mob/living/carbon/alien/special/facehugger.dm
Advances #18179
Facehuggers no longer apply an extremely long period of paralysis to their victim. Instead, they apply knockdown and blind for the facehugger's lifespan. To compensate for the victim now being fully conscious and able to interact with their environment mid-facehug, facehuggers are now `NODROP` during the impregnation attempt. After the facehugger dies (or it recognizes that it's macking on an IPC and gets bored), `NODROP` is removed.
This PR also removes several elements of RNG in facehugger code. A `proc(20)` that gives the victim a 1/5 chance to completely ignore facehugger attaches while wearing a mask has been removed. The impregnation period, which was formerly between 100 and 150 Byond Time Units™ long, is now fixed at 12 seconds; the victim's knockdown wears off an …
> Facehuggers no longer instastun, removes some RNG

- code/game/objects/items/weapons/implants/implanter.dm
New empty implanters now are actually empty when initialized.
Fixes: #19037
Due to a bug empty implanters would be initialized with a non-functional implant in it (/obj/item/implant).
Looked in tracking implant box, empty implanter was empty.
Looked in mindshield lockbox, filled implanter was filled.
Printed a new implant at a protolathe, empty implanter was empty.
:cl:
fix: Empty implanters no longer generate with a useless implant inside of them.
/:cl:
> Makes empty implanters initialize properly.

- code/game/machinery/computer/arcade.dm
Fixes issue #18845 , orion trail trading now display the correct amount of resources the player will be receiving and you won't be able to game over by selling exactly 10 fuel/food.
Its good to have correct amounts displayed and to avoid players from getting game over by accident.
- Played the orion trail
- Got the spaceport event
- Did verify the correct amounts
- Tried to sell/buy until one of the resources reaches 0, game didn't allow such thing.
:cl:
fix: Orion Trail: Spaceport event will display the correct amount received when selling a crewmember.
fix: Orion Trail: You won't be able to game over anymore by buying crewmembers.
/:cl:
> Fix issue #18845 Orion Trail wrong value displayed and accidental game over

- code/modules/mob/living/silicon/robot/robot_defense.dm
Xenomorphs now stun borgs for 4 seconds again, vs 0.2 seconds.
Xenos should actually be able to fight cyborgs, and bugs are bad.
spawned in
disarmed borg as xeno.
4 second stun as the founding fathers intended.
:cl:
fix: Xenomorphs stun cyborgs for the proper time again.
/:cl:
> Xenomorphs can now stun borgs for practical ammounts of time.

- code/datums/emote.dm
- code/modules/mob/living/carbon/human/human_emote.dm
Fixes all visible emotes being treated as audible emotes when displayed, and vice versa. This also makes sure emotes with a sound component are treated as audible emotes, which fixes #18999, and means you can now use sound-producing emotes to trigger voice analyzers.
Also fixes a little bug where the `snaps their fingers off!` message was using the emote datum's pronouns. I got incredibly lucky while testing and noticed this, so I fixed it quickly lol
Using sound-producing emotes to trigger voice analyzers was a pretty fun feature, and it's good to have it back in the game. Beyond that, having emotes go through the right handlers means that whatever relies on those messages down the line (especially w/r/t deaf/blind folks) will have them treated correctly.
See image.
:cl:
fix: Audible …
> Fixes emotes being displayed as the wrong type

- code/modules/power/singularity/particle_accelerator/particle_emitter.dm
Fixes https://github.com/ParadiseSS13/Paradise/issues/13305 . Each EM Containment Grid part has a new name to indicate their correct placement in order to finish the construction.
Inclusion of placement in their names makes things more intuitive for players.
Managed to construct the PA by following the correct directions.
:cl:
tweak: Included correct placement in EM Containment Grid parts names.
/:cl:
> Fix #13305. PA containment firing grids names are all the same

- code/game/objects/items/stacks/sheets/sheet_types.dm
Adds Cloth footwrap to cloth recipes, with the cost of 2 cloths (same cost as the white shoes).
It's odd that the Cloth footwrap cannot be made using Cloth, confusing players and myself included a few days prior to the making of this PR.
- Managed to create cloth footwraps using cloth
:cl:
tweak: Cloth footwraps now can be made using Cloth
/:cl:
> Cloth footwraps now can be made using Cloth

- code/modules/surgery/organs/subtypes/standard.dm
Makes the head's `receive_damage` properly store the parent's return value, as its meant to return it in order to properly update its damage state.
Consistency. It's gone unnoticed for a long time due to the damage displaying properly if another part prompted an update of the body.
Oh, and fixes #19054
https://user-images.githubusercontent.com/80771500/190263526-86e1a5ac-c1d5-47b9-b7b8-df612fda32f3.mp4
Spawned a mob, and shot its head without hitting any other limb.
:cl:
fix: Head damage is displayed properly without requiring another bodypart taking a hit to show
/:cl:
> Fix head damage not displaying properly until another bodypart was updated

- code/game/objects/effects/anomalies.dm
Pyro anomalies no longer light people on fire through walls.
Bluespace still does because it's bluespace, and just a teleport.
Hot things working through walls is strange.
spawned like 10 pyro anomalies on the other side of the walls
made sure people on the other side did not catch on fire.
:cl:
fix: Pyro anomalies no longer light people on fires through walls
/:cl:
> pyro anomalies no longer light people on fires through walls

- code/modules/mob/living/carbon/alien/special/facehugger.dm
`NODROP` is now removed from latched facehuggers whenever the facehugger's impregnation proc is called, instead of only in certain checks. This fixes an issue where facehuggers can remain permanently latched onto a player's face if they happen to die mid-facehug.
A line has been added for when a facehugger relaxes its grasp (removes `NODROP`) on an IPC player, indicating that the facehugger can be removed.
Bugs bad. I'm a little embarrassed I let this one through.
:cl:
fix: Facehuggers are no longer permanently stuck to dead players
/:cl:
> Fixes facehuggers facehugging forever

- code/game/objects/effects/spiders.dm
Checks to only spawn spiderling remains if the spiderling didn't reach the growth threshold before being qdeleted.
A spiderling that grows up should not also be a green stain on the floor.
Before:
After:
Tested princess terror laying.
:cl:
fix: Grown spiderlings now no longer also spawn remains.
/:cl:
> Don't spawn spiderling remains for grown spiders.

- code/modules/reagents/chemistry/reagents/medicine.dm
Reverts ParadiseSS13/Paradise#18910<br><br>
because I have apparently commited a sin somewhere and I cant pinpoint it.
Apparently its having some issues on production, despite working on my local server. Probably best to revert it until I can get more details about whats going on.<br><br>
It might be being caused by mind code being mindcode.
It is also possible this is being caused by having more than one datum of strange reactant in the world which is... terrible? (addtimer with src and global and.... I hate it all)
It also may be that the notification is just not showing up for telling them to enter their body?
There are many other possible factors into this that can be causing it and I cant exactly pinpoint what it is right now.
I hit the undo button on github
I cant test this in …
> Revert "Changes SR to not be an instant and unavoidable revival."

- code/modules/antagonists/traitor/datum_traitor.dm
When losing the traitor status, the uplink also gets deleted.
When admins de-traitor people, they need to remove their uplink as well by pressing a second button. This should be all automated, birdbrains like me might forget to take the extra step.
The "Uplink - take" button does not clear the pda/headset's `hidden_uplink` reference either.
Delete PDA uplink:
https://user-images.githubusercontent.com/33333517/189718298-a5df3ce3-bd48-4419-abfe-b154a62d7935.mp4
Delete headset uplink:
https://user-images.githubusercontent.com/33333517/189719263-0fbd6fd9-c89b-460f-997b-8bd927c72d79.mp4
Delete implanter uplink:
https://user-images.githubusercontent.com/33333517/189719550-55fc12dc-1173-4a56-930f-6589d5fef756.mp4
By doing the videos above.
:cl:
tweak: De-traitoring someone (via admin tools) now …
> When removing traitor role, auto remove the uplink

- code/game/objects/structures/crates_lockers/closets/secure/personal.dm
Fixes #18912.
I don't 100% get overlay order/equivalency but adding lock/unlock light overlays without resetting them first results in confusing behavior.
Lockers should correctly display their lock status.
Before:
https://user-images.githubusercontent.com/59303604/190535153-5bfe26bf-0e2c-4a6b-b579-b4b3336693f6.mp4
After:
https://user-images.githubusercontent.com/59303604/190535215-3681b1e4-928c-4c24-aad4-d3866423c53b.mp4
:cl:
fix: Personnel lockers properly display their lock status.
/:cl:
> Reset personnel locker overlays when lock/unlocking.

- code/modules/reagents/chemistry/reagents/toxins.dm
Advances #18179
Beer2/Mickey Finn's Special Brew, the unique reagent that emagged service borgs can produce, no longer instantly puts people to sleep on the first cycle after ingestion.
Instead, ingesting beer2 will cause the imbiber to become drowsy, have blurred vision, and go unconscious **after the 10th cycle**, similar to ketamine. The victim will then remain unconscious for as long as the reagent remains in their system, and begin taking toxin damage after the 50th cycle as usual.
Beer2 is one of the more egregious stuns still left in Paradise; it is unique in that even _extremely_ small amounts can put players to sleep for extended periods of time. **0.2u** is enough to cuff someone twice over, but you have little reason to conserve beer2 since your emagged pal can produce infinite …
> Beer2 no longer instastuns

- code/game/objects/items/weapons/twohanded.dm
Pyro gloves action button now only shows up when in gloves slot.
no deploying gloves from pocket.
Spawn gloves
put in core.
Confirm only work in gloves slot.
(Could have sworn I already gave it this check)
:cl:
fix: Fixed pyro gloves working in your hands / pocket
/:cl:
> pyro gloves only work in glove slot [GBP NO UPDATE]

- code/game/turfs/simulated/walls_reinforced.dm
Reinforced walls won't generate 1 metal rod anymore (first deconstruction step).
Wirecutter now has to be used instead of metal rod to revert the first step of deconstruction.
Fixes https://github.com/ParadiseSS13/Paradise/issues/16297, Its good for consistency since metal rod is not used during reinforced wall construction.
- Was capable of deconstructing and constructing reinforced walls without a problem.
:cl:
tweak: Reinforced wall: wirecutter must be used to revert the first deconstruction step instead of metal rod.
fix: Reinforced wall: won't act as infinite metal rod generators anymore.
/:cl:
> Fix #16297 Reinforced walls act as infinite metal rod farms

- code/modules/awaymissions/corpse.dm
- code/modules/mob/living/simple_animal/hostile/megafauna/megafauna.dm
- Mob spawners no longer try GC stuff that dont exist
- Megafaunas now put their internal GPS in the internal GPS slot, not the internals tank slot. Dont ask.
Bugs bad
Made sure it didnt runtime
N/A
> Fix some busted logic

- code/modules/mob/living/carbon/alien/humanoid/caste/hunter.dm
- code/modules/mob/living/carbon/alien/humanoid/empress.dm
- code/modules/mob/living/carbon/alien/humanoid/humanoid.dm
- code/modules/mob/living/carbon/alien/humanoid/queen.dm
- code/modules/mob/living/carbon/human/human_defense.dm
Buffs the alien queen
Ups their disarm damage to 60 from 30
Ups their slash damage to 30 from 20 (Hal helped me with this) 
Decreases their movement delay from 3 to 1
Prevents alien queens from being pulled/pushed
(all of these changes have been mirrored to empresses as well) 
Currently, alien queen is fucking boring, everyone wants someone else to go queen so they don't need to, alien queens also suck at defending themselves. Alien queens are now a force not to be fucked with, it stamcrits you in two strikes (provided you don't have an item in hand), and deals esword level damage.
The decrease to movement speed will make basic movement less of a slog, while removing the reliance on getting a hunter to pull you
Alien queens can no longer be pushed/pulled, this prevents people from pushing …
> Buffs Alien Queens

- code/modules/clothing/suits/armor.dm
Readds guns to allowed items on captain jackets. Mantle untouched as its code was unaffected by recent drip PR
Captain should be able to hold gun in suit
Boot test server, put guns in all captain outfits
:cl:
fix: Captain jackets can now hold guns again
/:cl:
> Allows Captain jacket items to hold guns again

- code/game/gamemodes/wizard/rightandwrong.dm
Summon Guns/Magic can no longer tries to select people who are antag banned.
fixes: #19007
Previously people who would get selected for the survivalist role by the summon guns/magic spell from a wizard while antagbanned would get their body polled off to ghosts. This seems a bit harsh.
:cl:
fix: Summon Guns/Magic can no longer tries to select people who are antag banned.
/:cl:
> Summon Guns/Magic can no longer tries to select people who are antag banned.

- code/modules/mob/living/carbon/human/appearance.dm
When changing the gender of a species that has_gender it will no longer be stuck at PLURAL because of the triggered `return`
Fixes https://github.com/ParadiseSS13/Paradise/issues/17543
- Changed, using UI block 32, the gender multiple times from male, female and plural.
- It didnt get stuck in any of them
:cl:
fix: Genetics UI: properly changes gender now instead of being stuck at plural
/:cl:
> Fix #17543 Genetics UI Block 32 Doesn't Properly Change Gender

- code/game/machinery/doors/windowdoor.dm
If you bump into a windoor and stay in front of it (or at least keep a live mob in front of it), it'll stay open. This doesn't impact the behavior of clicking windoors to keep them open indefinitely.
This should hopefully do away with the obnoxious shuffle of trying to keep a windoor open for long enough to hand someone something or reach something inside if you bumped it. Think chemfridge, for instance, or HoP's desk. Because it'll still automatically close after a little bit once you move away (shorter if the window's secured), this shouldn't cause any new security issues, but might lead to some interesting gameplay of having people hold a windoor open, like how you can jam open a normal airlock. 
https://user-images.githubusercontent.com/89928798/189540259-463a84e0-d770-466e-a4d5-5ddb01 …
> Keeps bumped windoors open if someone stands in front of them

- code/__DEFINES/surgery.dm
- code/datums/components/surgery_initiator.dm
- code/modules/surgery/abstract_steps.dm
- code/modules/surgery/cavity_implant.dm
- code/modules/surgery/surgery.dm
The PR you all knew was coming: fixes up some bugs that have popped up after the refactor, and adds some behavior that I was meaning to add, but kind of wanted to make sure everything else worked first (read: I was trying to think of the best way to do this, but I forgot).
The biggest one is that you should no longer get stuck in a branching surgery step just because you started a step and canceled it. If you're in the first step of a branching surgery and you start a particular operation that isn't completed (due to moving or some other reason), you'll be able to make any other move that the branch made available. Worth noting that you'll still be stuck in a branch that's 2+ steps long once that surgery step completes successfully; you've committed to it. This should also help with other …
> Surgery Hotfixes: Part 1

- code/modules/mob/living/carbon/carbon.dm
- code/modules/mob/living/carbon/human/human.dm
- code/modules/mob/living/carbon/human/species/_species.dm
- code/modules/mob/living/living_defines.dm
- code/modules/reagents/chemistry/reagents.dm
- code/modules/reagents/chemistry/reagents/medicine.dm
Removes the var/digestion_ratio
Fixes https://github.com/ParadiseSS13/Paradise/issues/18667
Just like the linked issue says it's not being used anywhere else and serves no purpose since it's set to `= 1`.
- Nothing looks to be broken because of this
> Fix #18667 var/digestion_ratio on mob/living is a depreciated or unused variable

- _maps/map_files/cyberiad/cyberiad.dmm
Added again the button that opens all the medbay entrace doors again in BoxStation.
This PR add again the button that opens all the entrance doors in medbay. 
This can save a lot of time and it was in the old medbay, and almost everyone was using it. People can be let in quickly. 
Started dream deamon.
Local host server
Entered as CMO and clicked the button, it worked. 
:cl:
add: Added a button to open the medbay entrance doors.
/:cl:
> BoxStation: Medbay Button

- code/modules/food_and_drinks/kitchen_machinery/smartfridge.dm
Re-adds the ability for silicons to use electric smart fridges. 
Consistency is good.
Silicons can access all other electric devices, so accessing the smart fridges makes sense. 
Verified AI and Cyborgs can vend products from both normal and secure smart fridges.
Verified that it is not the case from drying racks and food cart.
Verified that Cyborgs can't load the chemist smart fridge with pill bottles.
:cl: uc_guy
add: Adds the ability for silicons to use electric smart fridges. 
/:cl:
> Allow silicons to use electric smart fridges.

- code/modules/food_and_drinks/food.dm
Ants will now longer spawn on food that is stored on racks, similar to tables.
A LOT of people forget that racks do not count to keep food safe, which is weird because they act so similarly to tables for storing items. Being able to use rack to store food would be nice, without it being infested by ants.
soup debugging. Tomato soup has no chance of spawning ants (as intented), soup on the ground may spawn ants (as intended).
:cl:
tweak: Ants will no longer spawn on food items that are on racks.
/:cl:
> Ants will no longer spawn on food that is on racks

- code/game/gamemodes/miniantags/revenant/revenant_abilities.dm
Makes revenants call emag_act correctly when using the malfunction ability thus preventing runtimes.
Side effects may include some messages about cryptographic sequencers or cards when using it.
Fixes #19027
Runtimes bad
Spawned a rev, emagged a few things through malfunction.
Got the expected messages instead of runtimes.
:cl: uc_guy
fix: Rev malfunction ability will now show the correct emagging messages instead of runtiming.
/:cl:
> Fix runtimes with Rev malfunction ability

- code/modules/assembly/assembly.dm
- code/modules/assembly/holder.dm
Making a new assembly will keep it in your hands instead of dropping it on the floor.
Dropping the items on the floor is kinda awkward. It would make more sense that they stay in your hands since you are putting them together with your hands.
https://user-images.githubusercontent.com/91113370/190971608-4e378929-6ab9-4298-bbc1-997d7329aea0.mp4
\> Be assistant
\> Smash together igniters and signallers
\> Remote bomb with welding tank
Disassembly of them works also, see attached video.
Having one hand full when disassembling works too, dropping the second item onto the floor
:cl:
tweak: Making and dissassembling assemblies will now not drop them to the floor.
/:cl:
> Making assemblies will no longer be dropped

- code/game/mecha/mech_fabricator.dm
Exosuit fabricator queue comes to a halt once the equipment power is off. Displays "Error: Insufficient power!" when that happens.
Fixes https://github.com/ParadiseSS13/Paradise/issues/18998
- Had a long queue of items to be made.
- Once power was turned off the fabricator did come to a halt after finishing his current item.
:cl:
fix: Exosuit fabricator no longer continues to print its queue after losing power.
/:cl:
> Fix #18998 Exosuit Fabricator no longer continues to process it's queue when power is out

- code/game/objects/items/mixing_bowl.dm
Changes action description to "Dispose ingredients!" to better reflect the destination of those ingredients.
Dispose action now triggers properly.
Fixes https://github.com/ParadiseSS13/Paradise/issues/18731
- Added ingredients and disposed them.
:cl:
fix: Mixing bowl now disposes properly
/:cl:
> Fix #18731 Mixing bowl now disposes properly

- code/modules/antagonists/_common/antag_spawner.dm
Gives the correct path for the 'locator' icon.
Fixes https://github.com/ParadiseSS13/Paradise/issues/19156
- Spawned as a nukie and spawned all reinforcements devices
- All of them had the locator sprite now
:cl:
fix: Nukie reinforcement teleporter is no longer invisible
/:cl:
> Fix #19156 Reinforcement caller no longer invisible

- code/modules/vote/vote_presets.dm
Check the return value for any null values before doing anything with it to avoid a runtime.
Adds an extra check to the map vote, making sure there was like...*actually* a map selected before proceeding, to fix #18699
Bumping the map vote option and ignoring it on an empty test server should no longer produce a runtime.
I loaded up a test server, ran, then ignored a few votes to make sure there were no runtimes.
> Fix empty map vote runtime

- code/modules/mob/living/carbon/human/human.dm
Resolves #19049
`get_idcard()` now only checks PDAs for ID if there's no ID present in the ID card slot. If a user has multiple ID cards (i.e. one in the ID slot and one in their PDA), only the one in the ID slot will be checked.
If a user has no ID card in their ID slot, their PDA will be checked for ID as normal.
`get_idcard()` can only return one ID, even if the user is wearing multiple. Before this PR, IDs in PDAs in the PDA slot took priority over visible ID, which was counterintuitive to some people. Talked with a head, and they agreed that visible ID should take priority so you don't get situations where an Agent ID in your PDA prevents you from using vending machines that your real, visible ID would be allowed to use.
:cl:
tweak: Visible …
> IDs now take priority over PDAs in get_idcard

- code/datums/diseases/_MobProcs.dm
- code/datums/diseases/_disease.dm
- code/datums/diseases/transformation.dm
Adds logging to the following:
- contacted disease
- cured from disease
- transformed into another mob due to disease
Helps admins with troubleshooting issues like "why did I turn into a cyborg" or finding people force-infecting other people with deadly diseases.
First image:
1. Spawn skrell
2. VV -> Add reagents -> Nanomachines
3. Wait for natural virus progression, then transform
4. Check LOGS
Second image:
1. Join as assistant
2. VV -> Add reagents -> Xenomicrobes
3. Set virus stage to 4
4. Transform on stage 5
5. Check LOGS
Third image:
1. Force Disease Outbreak event
7. Join round
8. Analyze self
9. Spawn cure, consume it
10. Cure self
:cl:
add: Adds better admin logging for virus-related events.
/:cl:
> Admin tools, adds better logging for viruses

- code/modules/mob/living/simple_animal/hostile/megafauna/blood_drunk_miner.dm
Blood drunk, if its transform ability is not on cooldown, has a 50% chance to transform its weapon after a melee attack.
The cooldown is unchanged. 5-10 seconds between transformations.
For too long miners have been able to fight blood drunk with crusher and one medipen without worrying about it transforming, since it only transforms into other modes when a user is not in melee. It would just... attack them once every 2 seconds. For 10 damage, not including armor.
Now they must actually suffer as the miner has remembered how to transform their weapon again. Maybe now it will be (slightly) harder and rushed slightly less.
Spawned in miner. 
Engaged in melee. 
Heard the sweet sweet clangs of the saw transforming as it rips me apart.
:cl:
tweak: Blood drunk miner can transform it's weapon in …
> Blood drunk will now transform its weapon during melee

- code/modules/mob/living/simple_animal/hostile/alien.dm
Removes xenomorphs from the xenobiology gold slime spawn pool. (By deleting their xenobiology subtypes.)
Xenomorphs were re-added to rotation. As they are proper biohazards, just like terror spiders or blobs, they should not be seen every second round - the crew does not take xenomorphs seriously, since "they are probably friendly". This does not occur with any other existing biohazard mob, thus this PR will make them fall in line.
...
1. Spawn a `/obj/item/reagent_containers/syringe`
2. Spawn 15-20 `/obj/item/slime_extract/gold`
3. Spawn mobs with blood
4. It works properly and doesn't spawn xenomorphs (other than the lusty xenomorph maid)
:cl:
del: Xenomorphs can no longer be spawned via xenobiology gold slimes.
/:cl:
> Removes xenomorphs from xenobiology gold slimes

- code/modules/events/anomaly.dm
Makes anomalies no longer spawning in dense turfs.
Allows anomalies to move around in a room as intended.
Anomalies spawning in walls can sometimes be hard to get to.
Spawned a lot of anomalies. None of the anomalies spawned in a wall or other dense turf.
:cl: uc_guy
fix: Anomalies can no longer spawn in walls or dense turfs.
/:cl:
> Fixes anomalies spawning in walls

- code/modules/pda/core_apps.dm
Right now you can only name the PDA once by clicking it with an ID. Different IDs just put the IDs into the PDA. Clicking "Update Info" only updates the job, not the owner name.
This PR allows you to change the PDA owner using the "Update Info" button in the PDA
The most important improvement is to allow traitors with a chameleon PDA to change their PDA names multiple times and not to be stuck with the first name they choose.
I'm open to making this a chameleon PDA only feature if it is unwanted on all PDAs.
Verified, that name change does indeed work using "Update Info"
:cl: uc_guy
tweak: PDA owner can now be updated using "Update Info"
/:cl:
> Allow changing PDA owners.

- code/__DEFINES/emotes.dm
- code/datums/emote.dm
- code/modules/mob/living/carbon/human/human_emote.dm
- code/modules/mob/living/living_emote.dm
- code/modules/mob/living/silicon/robot/robot.dm
- code/modules/mob/mob_defines.dm
- code/modules/mob/mob_helpers.dm
Adds a cooldown to audio from unintentional emotes. This means that any audible emote that is forced out of you (like screams from pain, or gasps from losebreath) will have a short cooldown before any other audible emote can be forced out of your character. This cooldown is separate from that of intentional emotes, so screaming or clapping won't suppress your sneezes.
Emotes can choose to ignore this completely, like unintentional deathgasping when you die.
This is something I hoped to do sometime soon after the emote refactor went through but kept dragging my feet about
Since the emote refactor went through, I've noticed quite a few more instances than I anticipated where emotes are consistently forced out of you very quickly, like when you're being beaten on a broken bone or assaulted …
> Add cooldown for unintentional emotes

- code/game/objects/items/devices/scanners.dm
Display of mutation_chance is now longer divided by 2, showing now the real amount when examined.
Fixes https://github.com/ParadiseSS13/Paradise/issues/18927
BEFORE
AFTER
:cl:
fix: Correct display of mutation chance on slimes
/:cl:
> Fix #18927 Incorrect display of mutation chance on slime when changing tiers

- code/__DEFINES/flags.dm
- code/modules/client/preference/link_processing.dm
- code/modules/client/preference/preferences.dm
- code/modules/mob/living/carbon/human/species/diona.dm
- code/modules/mob/living/carbon/human/species/drask.dm
- code/modules/mob/living/carbon/human/species/grey.dm
- code/modules/mob/living/carbon/human/species/kidan.dm
- code/modules/mob/living/carbon/human/species/machine.dm
- code/modules/mob/living/carbon/human/species/nucleation.dm
- code/modules/mob/living/carbon/human/species/plasmaman.dm
- code/modules/mob/living/carbon/human/species/skrell.dm
Expanded the BALD bodyflag to be included in all species that have no hair.
Created the SHAVED bodyflag and included into all species with no facial hair.
BALD and SHAVED species wont be seeing the option to change their HAIR and BEARD since they dont have it.
BALD was included and only used by nians, it should be used by all species that are bald.
SHAVED creation is good to prevent manual lists and to differentiate in the case of species that have hair but no beard.
- Looked into all species over preferences.
> Added SHAVED bodyflag and expanded BALD

- code/modules/projectiles/guns/energy/kinetic_accelerator.dm
Fixes a bug causing the PKAs to lose their chassis mod whenever fired or dropped.
Fixes #19098, and ensures that the chassis PKA mods aren't _quite_ so much of a waste of mining points anymore.
https://user-images.githubusercontent.com/46016730/191160123-a5dfa7f6-da24-4bb1-8b01-3612b74a9eaa.mp4
Installed some PKA chassis mods on a couple of PKAs, fired them, noted they remained fancy. Stuffed them in my bag and dropped them to similar results.
Uninstalled and reinstalled the mods to ensure that remained functional. Went mining to make sure they still worked otherwise, and made sure to test that the energy crossbow also worked since that was a child of the PKA.
:cl: Vi3trice
fix: Fixed a bug causing PKAs with reskin mods to lose the skin on use.
/:cl:
>  Fix #19098, update chassis mod install/uninstall procs.

- code/__DEFINES/mobs.dm
- code/game/machinery/OpTable.dm
- code/game/machinery/computer/Operating.dm
- code/game/objects/items.dm
- code/modules/hallucinations/effects/moderate.dm
- code/modules/surgery/organs/pain.dm
- code/modules/surgery/organs_internal.dm
Fixes surgery on xenos, something that was inadvertently broken as a result of the surgery refactor. You can now perform all of the standard organ manipulation steps on xenomorphs as you can on humans. Also fixes the surgery computer to work with xenomorphs as humans. 
This also adds a surgery step to xeno surgeries that seals the incision and ends the surgery. There is currently no way to end a xeno surgery without scalpel/cautery, so this formalizes it.
On the code side, this also performs some tweaks to make carbon surgery a bit cleaner in general, clearing up some inconsistencies. 
Xeno surgery is kind of important, especially w/r/t extracting their organs. *Especially* now that they're in rotation.
- Throw a xeno onto an operating table with an operating computer next to it, note how …
> [GBP: NO UPDATE] Fixes xeno surgery

- code/__DEFINES/_math.dm
- code/modules/mob/living/carbon/alien/special/alien_embryo.dm
Changes a Prob(3) check to advance a stage in facehugger incubation to a 70 second timer with 15% positive and negative deviation 
Removes stage 3 due to it being a carbon copy of stage 2
Removes a small bit of RNG that didn't function for whatever reason
This PR also adds a new def for math.dm which lets us calculate %s, made by @Vi3trice 
Part of #18888
Currently, facehuggers incubation is governed by the will of RNGjesus, and it can take 30 minutes or 30 seconds for incubation to advance. Removal of RNG is good.
The timer is 70 seconds (3 minutes on average) so that it will roughly take the same time for alien larva to fully mature before changing how this worked, and after. It's also far more understandable than "wooo magic numer"
There is a deviation of 15% so that RNG is still a …
> Reworks alien facehugger incubation 

- code/modules/mob/living/carbon/human/human_defense.dm
Fixes negative armour pen giving block chance to things that dont deserve it. 
HP rounds shouldnt be blocked by paper with a 40% success rate.
this is REALLY funny but shouldnt happen
tested shields blocked projectiles
tested a box didnt block a projectile with -100 armour pen flat
tested a projectile with 100 armour pen flat went through a shield with 100 block chance.
:cl:
fix: negative armour pen doesnt increase block chance anymore.
/:cl:
> Fixes negative armour pen and blocking

- code/modules/point/point.dm
Adds the click cooldown to the pointing verb that was missing from the pointing to inside things PR
Chat spam is pretty bad
Hopped on an instance and spammed the middle-click
:cl:
fix: Pointing to things has a cooldown
/:cl:
> [GBP no update] Adds cooldown to pointing verb

- code/modules/mob/living/carbon/human/human_defense.dm
Advances #18888
Holding an item in your active hand no longer prevents you from being knocked down or taking stamina damage from xenomorph disarm. If you don't have stun absorption (i.e. riot shield), getting disarmed by a Xenomorph will now disarm you, knock you down, and apply 30 stamina damage no matter what.
When I made #18450 a couple months ago, it was with the expectation that it would always take _four_ disarms to put a xenomorph's victim into stamcrit. Unfortunately, I was new, and didn't notice that the code I tinkered with only ran if the victim wasn't holding an item in their hands. This means that a stubborn victim can repeatedly pick up their disarmed item to prevent knockdown + stamina damage from happening, which is both unintentional and a little obnoxious. Also, an …
> Held items no longer prevent Xenomorph disarm knockdown + stamina damage

- code/datums/holocall.dm
Holopad now says "No answer received" only once.
Fixes https://github.com/ParadiseSS13/Paradise/issues/18719
- Called another holopad while standing still, 20 seconds later only received one "No answer received" warning.
:cl:
fix: Holopads will no longer repeat their lines when the call is not answered.
/:cl:
> Fix #18719 Holopads now stops talking when the call is not answered

- code/modules/clothing/head/collectable.dm
Set the correct path for the welding helmet icons for Vulps, Vox, Grey, Unathi, Tajaran.
Fixes https://github.com/ParadiseSS13/Paradise/issues/11809
- Tried wearing it with multiple species to confirm it isnt invisible
:cl:
fix: Collectable welding helmet is no longer invisible on some species
/:cl:
> Fix #11809 Collectable Welding Helmet no longer invisible on Vulpkanins and other species

- code/game/objects/items/weapons/implants/implant_storage.dm
- code/game/objects/items/weapons/implants/implant_traitor.dm
- code/game/objects/items/weapons/implants/implant_uplink.dm
- code/game/objects/items/weapons/implants/implantpad.dm
Follows up on https://github.com/ParadiseSS13/Paradise/pull/18937 by changing instances of implants to bio-chips.
I apparently missed these in merging the large volume of changes from sirryan's PR. Sorry Mr Maintainer!
Consistent naming is good, unfortunately I didn't manage to catch these in the mass of merge changes.
:cl:
fix: Fixed some bio-chips being called implants
/:cl:
> Catches all missed implants from #18937 change to bio-chip

- code/modules/surgery/organs/augments_internal.dm
Adds an adminbus-only version of the anti-drop implant. Hardened implants are exactly like the regular ones, but emp-proof.
Requested by @meow20 
Admins sometimes want emp-proof implants without varediting, especially if they intend to serialize it with json. It was requested, so I coded it.
1. Spawn skrell
2. Open VV
3. Add organ
4. Guess the path of this item because the text crops off
:cl:
add: Added a hardened version of the anti-drop implant, only accessible via adminbus.
/:cl:
> Adds a hardened version of the anti-drop implant

- code/modules/mob/holder.dm
Fixes #19097 - Issue was caused by the holders.dm for small mobs not having the same additions to examine text as the simple mob itself. Now the holder calls the examine text of the mob itself to retrieve its status.
Fixes an examine inconsistency.
Spawned in, killed mouse, examined both before and after pick up.
:cl:
fix: Small mobs now state if they dead or asleep while held in-hand.
/:cl:
> Inhand small mobs now detail if they're dead/asleep when examined

- code/game/objects/effects/spiders.dm
ACTUALLY fixes #19130.
I completely jumped the gun in #19147. It wasn't until @GDNgit pointed out the same issues with simple robots that I realized the common factor between all the GC failures wasn't any component, but the use of `/walk_to`.
After extensive testing I've come to the conclusion that when a `/walk_to(foo, ...)` call is being processed in the background by BYOND, this counts as a reference to `foo` for the purposes of qdel'ing it. Only a handful of objects use `/walk_to`. Most are simplemobs, most hostile mobs, and spiderlings, which are not a mob, but which move anyway (which is why spiderlings is happening in one PR, and the other fixes are happening later).
The fix is easy; as per the BYOND docs, "A call to a walking function aborts any previous walking function called …
> Reset spiderling walk instructions on Destroy.

- code/modules/reagents/chemistry/reagents/toxins.dm
Changes the order in wich the head object is deleted so the H.wear_mask can find it.
Fixes https://github.com/ParadiseSS13/Paradise/issues/18913
- Used fluorosulfuric acid on a clown mask and verified the chat.
:cl:
fix: Splashing acid on masks now displays the correct message.
/:cl:
> Fix #18913 splashing acid on masks no longer displays "Your [null] melts away!"

- code/modules/surgery/abstract_steps.dm
Fixes a bug that was introduced in #19108 where failing the main "next" surgery step would get you stuck in a weird limbo state. This would most often pop up at the end of organ manipulation, where failing the cautery step would leave you with an open incision and a stuck surgery step.
Fixes #19243
Thanks to meow and matt for letting me know this was an issue.
Being able to finish surgeries is good, actually.
- Dropped a vulp on an operating table
- Mashed organ manipulation steps with debug IMS until just before cautery step, then use welder to easily fail the step.
- Before PR, note that this leaves us with a proxy step tacked onto the end of the surgery, with nothing after it.
- After PR, note that this leaves us with the proxy step followed by the cautery step, letting us actually run …
> Fix failing main surgery during abstract steps getting surgeries stuck

- code/modules/mob/living/simple_animal/parrot.dm
Fixes the mistake in the logic of https://github.com/ParadiseSS13/Paradise/pull/19193
We all managed to miss that this was the wrong way around
Fixes stat check for parrots
Ex-parrots should not speak
:cl:
fix: Fixed speaking dead parrots (for real this time)
/:cl:
> [GBP no update] Actually fixes speaking dead parrots

- code/game/dna/mutations/disabilities.dm
- code/modules/mob/living/carbon/carbon.dm
- code/modules/mob/living/living.dm
- code/modules/mob/living/say.dm
- code/modules/mob/mob.dm
Facehuggers muffle (not mute!) the speech of anyone they're attached to, similar to being duct taped.
Also changes the scoping of the Swede disability's mob param to `mob/living`, since it needs to check facehugged status and ghosts can't be facehugged (or acquire disabilities).
While #19025 removed an obnoxiously long stun from facehuggers, it also introduced an issue; people with a horrific sci-fi alien violating their face can now effortlessly make callouts. From an IC perspective, this is a bit silly, and from an OOC perspective it hurts hit-and-run facehugger strategies when your victim can call out your location mid-facehug.
By having facehuggers muffle their victims' speech, the victim can alert everyone that something is obviously wrong with them _without_ breaking immersion or …
> Having a facehugger on your face muffles your speech

- code/game/objects/structures/door_assembly.dm
- code/game/objects/structures/windoor_assembly.dm
This adds an examine case for airlock assemblies to hint at the electrochromic window capability.
Windoor assemblies as a whole were lacking in examines unlike their airlock counterpart, so this adds them, adjusted for the different construction steps.
Makes the construction of windoors a bit less trial and error. The notion of electrochromic windows for those assemblies is communicated better.
Built airlocks and windoors by hand.
:cl:
add: Examining a windoor assembly will give a description of its current construction status.
tweak: Examining an airlock assembly will tell if the electrochromic windows can be toggled.
/:cl:
> Improve airlock and windoor assembly examine cases

- code/datums/mind.dm
- code/game/gamemodes/objective.dm
- code/modules/antagonists/changeling/datum_changeling.dm
Adds a missing var to admin creating the escape with identity objective (why the FUCK arent types immutable?, why does this work properly)
Fixes #19183
Before:
After:
Now failing the objective when objective is admin edited:
See above
No player facing changes, just broken admin stuff
> Fixes a missing variable on a changeling objective

- code/game/objects/structures/morgue.dm
Fixes morgue icons not updating their icons properly when the tray is clicked. Also, adds the sound effect for clicking the tray as well.
~~honestly I think morgue code could probably use a refactor too but ehh~~
It's very possible that someone could click the morgue tray, have the icon not update, and totally miss someone's revivable. This is kind of a sneaky and somewhat nasty oversight.
:cl:
fix: Clicking on the morgue tray now updates the morgue tray holder's icon.
/:cl:
> Fixes morgue icons not updating from clicking on the tray

- code/game/objects/effects/decals/Cleanable/aliens.dm
- code/game/objects/effects/decals/Cleanable/humans.dm
- code/game/objects/effects/decals/Cleanable/robots.dm
Tweaks gib icon update code to skip if needed. Robot and xeno gibs are only meant to set their color once and nothing else.
Fixes #19214
Spawned a few silicons and called gib on them
:cl:
fix: Robot debris and xeno bigs are not jet black
/:cl:
> [GBP no update] Robot and xeno gibs get their color set properly

- code/modules/paperwork/desk_bell.dm
Doesnt allow the desk bell to be picked up when its anchored.
Fixes https://github.com/ParadiseSS13/Paradise/issues/19259
- Tried to pick up a desk bell while anchored and failed
- Tested all other desk bell functions, all look good.
:cl:
tweak: Desk bell cannot be picked up when anchored
/:cl:
> Fix #19259 Desk bell cannot be picked up when anchored anymore

- code/game/objects/cleaning.dm
Fixes a bug introduced in #19001
Players near someone who is mopping will no longer erroneously receive "You finished mopping the floor" messages.
Also adds a missing visible_message argument for cleaning messages, so the mopper doesn't see "John Tider begins mopping the floor", as if he's speaking in the 3rd person.
I did not finish mopping the floor. Someone else did. Do you think this is a joke?
Compiled and tested on local debug server with an extra client. Mopper receives the relevant text, innocent bystanders do not.
:cl:
fix: Fixed bystanders getting "You finished mopping the floor" text when near someone who is mopping
/:cl:
> Fixes non-moppers getting "you mopped the floor" notifications

- code/modules/events/immovable_rod.dm
Fixes the immovable rod not deleting when it reaches the end tile.
Fixes #19153 
It was designed to despawn after reaching its end tile, it does not do it.
https://user-images.githubusercontent.com/33333517/192138977-a2ca6718-7210-457c-a8c6-3151a9888a2f.mp4
1. Event manager, set medium event to immovable rod
2. Decrease timer to 0
3. Watch immovable rod from start to end
:cl:
fix: Fixed the immovable rod not despawning after it reached its end tile.
/:cl:
> Fixes the immovable rod not despawning

- code/modules/mob/living/silicon/ai/latejoin.dm
It removes the player respawnability when wiping his core too early in the round (30 minutes)
Fixes https://github.com/ParadiseSS13/Paradise/issues/18054
- Did wipe core before and after 30 minutes, all looks good.
:cl:
fix: AI now loses respawnability when wiping its core too early in the round
/:cl:
> Fix #18054 AI now loses respawnability when wiping its core too early in the round

- code/game/objects/structures/crates_lockers/closets.dm
Removes a line that would never send because theres no usr, which caused this runtime. toggle() didnt even return true or false, so that line would always try to be sent but it would ever show up because usr.
Fixes this runtime:
```
[2022-10-04T12:48:59] Runtime in browserOutput.dm,303: DEBUG: to_chat called with invalid message/target. Message: '<span class='notice'>It won't budge!</span>'. Target: ''.
[2022-10-04T12:48:59]   proc name: to chat (/proc/to_chat)
[2022-10-04T12:48:59]   usr: *REDACTED USER*
[2022-10-04T12:48:59]   usr.loc: The plating (49,70,4) (/turf/simulated/floor/plating)
[2022-10-04T12:48:59]   src: null
[2022-10-04T12:48:59]   call stack:
[2022-10-04T12:48:59]   to chat(null, "<span class=\'notice\'>It won\...", null)
[2022-10-04T12:48:59]   the welding supplies …
```
> Fixes a runtime with telekinesis and closets

- code/modules/awaymissions/mission_code/ghost_role_spawners/golems.dm
Clarifies that free golems cannot board the station/cannot create AIs
Golems can't do this stuff rules wise, considering an announcement needed to be sent out about this it's a good idea to make this very explicit. 
Compiled, and see above
:cl:
spellcheck: Clarifies free golem spawn and ghost message. 
/:cl:
> Free Golem Spawn/Ghost Role Message Clarification

- code/modules/surgery/core_removal.dm
Fixes #19226
Slimes don't have limbs so the surgery should also reflect that.
Slimes can now be hand-harvested again for that biological slime core market
Kill a slime using `death` admin command
Throw their lifeless body on a table
Use scalpel on body to remove the core and get the menu as expected
:cl:
fix: Slimes can be hand-harvested again for their cores.
/:cl:
> No longer need to have slimes with body parts to remove their cores

- code/modules/buildmode/submodes/variable_edit.dm
Makes the Edit mode's right-click reset the selected var again
Fixes #18995
https://user-images.githubusercontent.com/80771500/193711436-169c1b54-89b9-45be-9c77-e9c7afe58b3d.mp4
Messed around in build mode
N/A
> Fix Buildmode's Edit right-click to reset vars again

- code/modules/mob/living/carbon/human/human.dm
- code/modules/mob/living/carbon/human/species/diona.dm
If dionas happen to contain nymphs and change species, those will automatically eject.
This doesn't apply to scooped up nymphs.
Fixes #18138
https://user-images.githubusercontent.com/80771500/193864860-74cc1935-343a-49d9-a3d8-13eb6ef549a7.mp4
Spawned a nymph and diona, and had them merge, then changed the species. Stuffing the nymph into storage or on top of your head won't get affected.
:cl:
fix: Geshalt nymphs automatically get ejected from dionas if they happen to transform into a different species
/:cl:
> Diona nymphs eject from dionas if a species change occur

- code/modules/food_and_drinks/kitchen_machinery/gibber.dm
Fixes #18736
The gibber feed animation was causing the grab to not be deleted when the mob was put into the gibber. Thus making it possible to quickly move away and thus teleport the mob out of the gibber again.
No more tele-gibs using the gibber
Spawn as a chef (makes grabs faster)
Spawn a willing humanoid subject
Grab them and click on the gibber
Walk away just after the `do_after` finishes.
See they don't teleport to you (before they did)
:cl:
fix: You can no longer grab teleport people out of the gibber and tele-gib them later.
/:cl:
> Ensures the gibber "feed" animation does not block the calling code

- code/modules/mob/living/simple_animal/hostile/terror_spiders/prince.dm
Prince Terror spiders now inflict 40 stamina damage per hit, in addition to the brute and knockdown they already apply. This means that the average player will enter stamcrit after being hit by a Prince Terror 3 times.
This buff was discussed during the community meeting and has the tentative approval of several members of the balance team.
The Prince Terror is meant to be the juggernaut of juggernauts, exceptionally deadly at close range; solo-kiting a Prince at melee range, confident that you'll never get owned because you have ash drake armor and a memechem cocktail, should be ill-advised behavior. No matter your armor, three hits will now put you in stamcrit, leaving you helpless.
Compiled and tested on local debug server. Getting hit 3 times puts you in stamcrit.
:cl:
tweak: Prince …
> Terror Prince attack now (also) does stamina damage

- _maps/map_files/RandomRuins/SpaceRuins/syndie_space_base.dmm
- Adds a syndicate stamp for faxes
- Fixes the soda and beer dispensers facing the wrong way
- Replaces the beer keg with a dinnerware vending machine
- Adds "syndicate" faction to the animals in the pen so syndicate killbots don't murder the entire livestock during patrol
- Replaces crates with racks
- Stamp: practicing proper paperwork
- Dispensers: simply faced the wrong direction
- Dinnerware: candy machine needs it, plus it allows for some Proper RP:tm:
- Faction: sometimes admins spawn the syndicate patrol robot `/mob/living/simple_animal/bot/ed209/syndicate` and it'd annihilate the animals, this fixes it
- Replaces crates with racks: requested by @warriorstar-orion, most of our stuff is put on racks instead of crates everywhere else in the game, rather than crates
Adds a syndicate …
> Tweaks the syndicate research base a little

- code/modules/admin/verbs/massmodvar.dm
- code/modules/admin/verbs/modifyvariables.dm
Cleans up the last part of the `initial()` removal on list indexes, which was on VV.
At the same time, adds the picked type to logging. Most of it falls into captain obvious if you look at the new var, but it doesn't hurt and Restore to Default does need to be distinct.
Tools that actually work.
VV'ing things.
N/A
> Fix VV restore to default and add additional info to logs

- code/game/objects/items/weapons/rpd.dm
Adds a check on RPD to not trigger the afterattack if it's a failed attempt at being put into storage.
Fixes #19085
Stuffed an RPD into a bag, took it out and stuffed it full with other stuff, then tried to stick it in.
:cl:
fix: Failing to put a rapid pipe dispenser into storage won't trigger the device on your feet
/:cl:
> Fix RPD making pipes on the turf when failing to be put in storage

- code/game/atoms.dm
- code/game/objects/cleaning.dm
- code/modules/hydroponics/gene_modder.dm
The Jestographic Sequencer, or cmag, (see #18933) can now be used on plant data disks.
Once cmagged, the plant disk's name, description, and icon change to that of the nuclear authentication disk, making it nigh-indistinguishable from the real thing to casual observers.
The average joe won't be able to tell the difference between a cmagged plant disk and the real NAD, but seasoned veterans can: if a Captain or Nuclear Operative closely examines the disk, they'll see right through the clown's charade!
It probably doesn't need to be said, but the cmagged plant disk does **not** inherit any of the NAD's functionality. You will not be blowing up the station with this.
This PR also adds a new proc, `uncmag()`, which handles any behavior that needs to be done after a cmagged object is cleaned. …
> Plant data disks can now be cmagged

- code/datums/mind.dm
Makes contracts added through the traitor panel properly generate rewards based on the difficulty and total amount of contracts.
This doesn't try to mess with preexisting contracts, as I feel like that's a whole different kind of ordeal. Unless a reset is intended.
Fixes #18940
https://user-images.githubusercontent.com/80771500/194184751-52a59db4-ace8-4571-b09e-4413546dc010.mp4
Bought a contractor kit, added contracts through the traitor panel.
:cl:
fix: ahelped contracts have proper rewards
/:cl:
> Admin added contracts generate rewards instead of defaulting to 0 TC

- code/modules/antagonists/vampire/vampire_powers/hemomancer_powers.dm
Removes the block chance from vampiric claws.
- booted server
- got claws
- damn claws aint got hands anymore
:cl:
tweak: Vampiric claws dont give you a 50% block chance anymore
/:cl:
> Nerfs Vampiric Claws

- code/modules/events/mass_hallucination.dm
This PR changes the "mass hallucination" announcement message to have proper punctuation and read more formally.
Proper punctuation good. Making NAS Trurl advisories read more formally is also good.
I removed the "no further damage" part because that seems like a weird judgment call for CC to make considering that most of the crew is tripping balls and acting irrationally.
Before:
After:
:cl:
spellcheck: Fixed punctuation and altered wording on mass hallucination midround event announcement
/:cl:
> Tweaks mass hallucination midround message

- code/game/objects/effects/decals/Cleanable/humans.dm
- code/game/objects/effects/decals/Cleanable/misc.dm
- code/game/objects/effects/decals/cleanable.dm
- code/game/objects/effects/decals/crayon.dm
For some cleanable floor decals like blood trails or blood splatter they have ambient occlusion effects around them, making them appear floating in the air or to have alot of volume which they shouldnt have. (It looks bad) This PR removes those efffects through plane magic.
Looks better.
_throw up and bug guts never had the weird shading effects, I realized this after making the image... dont look at those ones_
_Heres a high contrast view as well_
Tested in VSC, before and after. Spawned in and visually checked 
all `/obj/effect/decal/cleanable` objects
:cl:
tweak: Removed the shading effects for various cleanable decals where it looked bad.
/:cl:
> Fixes cleanable floor decals shading jank

- code/modules/projectiles/guns/energy.dm
- code/modules/projectiles/guns/energy/special.dm
Current overlay code for energy guns do not take into account the possibility of them being reskinned, or at least, not while creating extra overlays due to being based on `icon_state`. This adds a var so energy guns can use a shared set of overlays. It doesn't necessarily have to use it, in case someone makes a skin that uses its own unique overlays.
Fixes #19270
https://user-images.githubusercontent.com/80771500/193698379-c7218bad-984f-41e8-82c4-5720e6025c53.mp4
Spawned a few detective guns and reskinned them, checking their charge displays. Also spawned a different energy gun to see if those were working properly as well.
:cl:
fix: Charge display works properly when using a reskinned detective gun
/:cl:
> Add support for sharing overlays for energy guns

- code/modules/surgery/organs/heart.dm
Fixes #19068, where you would be stuck with the red overlay if you had your cursed heart removed while it was active.
Also tags on removing the client's signals that I forgot to do in my last cursed heart PR (oops).
Having you client be blood-red forever seems a little annoying. Also, I can see some possibly unforeseen consequences with these signals not getting properly unregistered, so it's a good thing to do so.
- Be vulp
- Use cursed heart
- let it get to red
- delete heart
- red disappears
- I die instantly from cardiac failure
:cl:
fix: The red cursed-heart overlay should now be removed with the heart.
/:cl:
> Fixes cursed heart overlay remaining active

- code/game/objects/items/candle.dm
This adds a check to see if candles do need to have their icon updated when lit. At the moment, they do so on every `process`, including even eternal candles which do not need to in the first place.
Cutting on unnecessary proc calls or updating icons.
Nothing playerfacing.
Lit various candles at different wax levels and let them burn.
N/A
> Candles do not repeatedly update their icon on every process

- code/modules/reagents/reagent_containers/pill.dm
Fixes pills not checking if target container is full before allowing the player to dissolve them inside. In the case of a container that isn't completely full and a pill with volume greater than the beaker's remaining capacity, as per current behavior however much fits is transferred and the rest destroyed.
No more bluespacing your pills by accidentally clicking on a beaker that's already full
- Spawned in a beaker
- Spawned in a bunch of pills
- Checked that a completely full beaker refuses to accept more pills, but a partially-full beaker still does not
- Checked that patches haven't been made able to dissolve in beakers in some freak accident
:cl:
fix: You can no longer waste pills by attempting to dissolve them in already-full reagent containers
/:cl:
> Adds a container capacity check before pill reagent transfer

- code/game/machinery/iv_drip.dm
Adds a check to see if there is a bag when trying to apply an IV drip to someone
Fixes this runtime:
```
[2022-10-04T14:49:06] Runtime in iv_drip.dm,49: Cannot execute null.afterattack().
[2022-10-04T14:49:06]   proc name: MouseDrop (/obj/machinery/iv_drip/MouseDrop)
[2022-10-04T14:49:06]   usr: *REDACTED USER*
[2022-10-04T14:49:06]   usr.loc: The floor (25,222,1) (/turf/simulated/floor/plasteel)
[2022-10-04T14:49:06]   src: the IV drip (/obj/machinery/iv_drip)
[2022-10-04T14:49:06]   src.loc: the floor (25,223,1) (/turf/simulated/floor/plasteel)
[2022-10-04T14:49:06]   call stack:
[2022-10-04T14:49:06]   the IV drip (/obj/machinery/iv_drip): MouseDrop(Gustavo Laborde (/mob/living/carbon/human), the floor (25,223,1) (/turf/simulated/floor/plasteel), the floor (25,222,1) …
```
> Fixes a runtime with IV drips

- code/game/machinery/doors/airlock.dm
Xenomorphs can no longer repeatedly pry open doors they're already prying open. This is how the jaws of life works, and now xeno door-prying mirrors that behavior.
https://user-images.githubusercontent.com/3611705/194777271-aa688204-b10c-44cd-9211-5c6797fa4905.mp4
:cl:
fix: Xenomorphs can no longer spam door pry dozens of times during a single attempt
/:cl:
> Xenos can no longer pry open doors they're already prying open

- code/game/machinery/camera/camera.dm
- code/game/machinery/camera/camera_assembly.dm
- code/game/machinery/computer/buildandrepair.dm
- code/game/machinery/firealarm.dm
- code/game/objects/items/devices/radio/intercom.dm
- code/modules/atmospherics/machinery/airalarm.dm
- code/modules/power/lighting.dm
- code/modules/power/singularity/particle_accelerator/particle_accelerator.dm
- code/modules/power/solar.dm
Adds a handful of construction examine-helpers (like airlock assemblies do) for the following objects:
Security Cameras, fire alarms, intercomms, air alarms, light fixtures, particle accelerators, and solar panels.
De-mystifies how to construct/deconstruct something without having to go to an external source -- also pretties up any existing examine helpers if there was one.
Booted up a server and checked each of the objects I changed.
:cl:
add: Added (de)construction hints to security cams, air/fire alarms, intercoms, light fixtures, solar panels, and particle accelerators.
/:cl:
> Adds some examine helpers

- code/modules/research/rdconsole.dm
- code/modules/research/research.dm
Technologies had an old var that was probably meant to be used for job objectives. This var was in turn being used by the admin button to maximize research, but that'd result in illegal and alien being untouched as they had a `max_level` of 0 and 1 respectively, and everything else at 7.
This makes the button set tech levels to be a set value of 8 instead, as this is the actual maximum research you can get.
Make the button actually function in full.
Went to the RD console, used the Maximize Research button.
N/A
> Admin Maximize Research applies to all tech types

- _maps/map_files/Delta/delta.dmm
- _maps/map_files/MetaStation/MetaStation.dmm
- _maps/map_files/cyberiad/cyberiad.dmm
- code/datums/supplypacks.dm
- code/game/mecha/mecha_construction_paths.dm
- code/game/mecha/mecha_parts.dm
- code/game/objects/structures/crates_lockers/closets/secure/scientist.dm
Adds mech power cores, a new item used in the creation of durands and gygaxs. They are in limited supply and can only be gotten from cargo for 250 points but the RD and robotics each start with one. Durand and gygax also no longer require capacitors to build and instead use the mech power core. Crew is now faced with a decision in the face of threats whether they want mechs or weapons and robotics is no longer capable of single handedly producing enough mechs to bring down about any threat.
Robotics's ability to churn out mechs at a ridiculous rate has long been an issue that disrupts the balance of the game especially during biohazards. Further with the addition of mech cores robotics can't go ahead and create loads of combat mechs without the RD's permission as the crate requires them …
> Adds mech cores, a component required by durands and gygaxs

- _maps/map_files/RandomRuins/LavaRuins/lavaland_surface_hermit.dmm
- _maps/map_files/RandomRuins/LavaRuins/lavaland_surface_pizzaparty.dmm
- _maps/map_files/RandomRuins/SpaceRuins/spacebar.dmm
- code/game/objects/effects/glowshroom.dm
Removes glowshrooms, glowcaps, and shadowshroom's ability to spread itself after being planted.
Glowshrooms are notorious for causing a ton of lag due to how the lighting engine works, mostly because of how many sources of light they spawn. This allows the shrooms to still be planted for when someone really wants to create natural lighting, but doesn't want to destroy the server by pressing z a few times.
Spawned in glowshrooms, shadowshrooms, and glowcaps, and went AFK
5 minutes later, none of them had spread.
:cl:
tweak: Glowshrooms and its variants no longer spread when planted
/:cl:
> Glowshrooms no longer spread when planted

- _maps/map_files/Delta/delta.dmm
1. Xenobiology was on `ACCESS_RESEARCH` (scientist + roboticist) access. Changed its doors to `ACCESS_XENOBIOLOGY`
2. Experimentor, toxins, toxins launch room were on `ACCESS_RESEARCH`, changed them to `ACCESS_TOX`
3. The airlock between scichem and the breakroom had zero access requirement, added `ACCESS_TOX`
4. Maintenance airlocks around science (not leading into the department) had zero access requirement, added `ACCESS_MAINT_TUNNELS`
The test range is intact, robotics can still access it for testing exosuit weaponry.
Robotics has almost all access in Kerberos' science, they can enter 1) experimentor 2) xenobiology 3) scichem (from the breakroom) 4) toxins mixing, but not its storage 5) toxins launch.
https://user-images.githubusercontent.com/33333517/192142114-87080bf8-f224-41e1-89f3- …
> Fixes several robotics access issues on DeltaStation/Kerberos

- code/modules/mob/living/carbon/human/human.dm
- code/modules/mob/living/carbon/human/species/machine.dm
Hallucination shocks will no longer kill IPCs
bugs are bad
shocked an IPC. Died
gave myself 523532 hallucination, walked into doors until I got shocked, did not die.
:cl:
fix: IPCs no longer die to hallucination shocks.
/:cl:
> Fixes IPCs dying to hallucinations. 

- code/game/objects/items/documents.dm
- code/game/objects/structures/bedsheet_bin.dm
- code/modules/paperwork/paper.dm
- code/modules/paperwork/paper_bundle.dm
Moves paper from layer 4 to layer 3 (Unrelated but also just removes a .0 from bedsheets for readability) 
There is no good reason to have paper on layer 4 rather than layer 3. It's an object, it should be on the object layer. People should not be able to hide under paper. 
Compiled, did stuff with paper
:cl:
tweak: Moves paper from layer 4 to layer 3
/:cl:
> Moves paper from layer 4 to layer 3

- _maps/map_files/Delta/delta.dmm
This PR addresses what I believe to be issues with Delta surfaced by the unit tests in #19204.
If these are all legit issues, then fixing them is good, and it makes it more likely that #19204 can get in alongside the tests it adds.
Execution before:
After:
**112,146** (no I don't know why these grilles are electrified)
Before:
After:
**36,147**
Before:
After:
Turbine before (with generator moved out of the way):
After:
I need someone to double check that this is fine; meta has a similar cable setup and delta is cribbing box here.
**160,100**, the medbay lobby
Before:
After:
(I don't know if windoors count for the purposes of cable-laying so this is coming from the hallway instead of up through chemistry)
Before:
After:
Before:
After:
Ran unit tests.
:cl:
fix: Small Delta fixes.
/:cl:
> Fix Delta issues caught by automated map tests.

- _maps/map_files/MetaStation/MetaStation.dmm
This PR addresses what I believe to be issues with Meta surfaced by the unit tests in https://github.com/ParadiseSS13/Paradise/pull/19204.
If these are all legit issues, then fixing them is good, and it makes it more likely that https://github.com/ParadiseSS13/Paradise/pull/19204 can get in alongside the tests it adds.
130,94
90,135
Dorms Before (clown and mime spawns hidden for clarity):
After:
84,167 and 85,167
Before:
After:
Lattice fix at 53,78
Signs that were placed in space and pixel pushed to a wall were moved directly on top of the wall in these instances:
92,160
88,176
122,183
:cl:
fix: Small Meta fixes.
/:cl:
> Fix Meta issues caught by automated map tests.

- code/datums/diseases/advance/advance.dm
- code/datums/diseases/appendicitis.dm
- code/datums/diseases/berserker.dm
- code/datums/diseases/cold.dm
- code/datums/diseases/food_poisoning.dm
- code/datums/diseases/gbs.dm
- code/datums/diseases/kuru.dm
- Fixes the Cold and Appendicitis not having proper `spread_text`, rendering as `Type: .` in-game
- Standardizes spread type text across diseases, making the terms and capitalization consistent
- Fixes some diseases having their `spread_flags` defined twice, once as `SPECIAL` and once as `NON_CONTAGIOUS`
Buggy health analyzer output bad, consistent terminology good, values being weirdly assigned twice for the same disease type bad
Fed a unathi some Cold-infected blood, as well as surgically extracted its appendix and inserted it back after VV'ing it to be inflamed; observed both conditions to now have proper spread type text when analyzed.
:cl:
fix: The Cold and Appendicitis now have proper spread type text output when analyzed.
/:cl:
> Cleans up some disease data

- code/game/objects/items/devices/radio/intercom.dm
- code/game/objects/items/devices/radio/radio.dm
Makes sure that intercomms/radios can interact with the wires instead of them being hidden behind something/not accessible in hand
Fixes #19366 
Compile and open up game, works as intended
:cl:
fix: Radios/intercomms can be accessed with wirecutters/hands again
/:cl:
> Fixes intercoms/radios not being accessible via wirecutter

- code/modules/mob/living/carbon/alien/special/facehugger.dm
Removes corgis as a target for facehuggers. Fixes #19157.
For some strange reason, facehuggers will leap at corgis despite not being able to actually plant a larva in them. As no other simplemobs can be implanted, I've elected to simply remove this entirely rather than make corgis implantable.
- Spawned group of corgis
- Spawned facehugger
- Facehugger did not attempt to couple with corgis
- Beat group of vox to death
- Success
:cl:
fix: facehuggers no longer target corgis
/:cl:
> Removes corgis as a facehugger target, fixes #19157

- .github/workflows/ci.yml
Bumps `yogstation13/DreamAnnotate@v1` to `yogstation13/DreamAnnotate@v2` 
No codebase change, this is just the CI "plugin" that makes annotations show up when you fail dreamchecker, and it puts the line markings down.
Something something old version is being deprecated and we need to keep stuff going
> Bump DreamAnnotate in CI

- code/modules/antagonists/traitor/contractor/datums/syndicate_contract.dm
Increases the punishment for being Contracted. At the moment, this includes:
- Breaking Bones
- Removing Extremities
- Maybe Nothing!
Note: I am willing to change values/add more possibilities, though I'll need to figure out some of the code for it.
**TODO**
NOTE: I'm unsure on the checks here and will need to keep taking a peek at em.
At the moment too many people simply go along with Contractors and take a "quick trip to Space Brazil" due to the WORST injury being a small amount of brute. This PR aims to make getting Contracted a REALLY BAD TIME that you should no way go along with willingly. Now you may need serious medical treatment if you get sent to the funny red portal. This should also dissuade other Antagonists from freely going along with "friends" to get them free TC.
1. Loaded …
> Contractor Post-Prison Injuries

- code/modules/mob/living/carbon/give.dm
Fixes alerts going invisible and some alert runtimes. Simply qdeling an alert causes it to remain as a null inside of a mob's `alerts` list, and we get runtimes like the one below. It needs to be properly cleared with `clear_alert()`. I should have seen this sooner.
Actually fixes #18886 this time.
```
Runtime in alert.dm,723: Cannot read null.icon_state
[2022-10-14T04:16:25]   proc name: reorganize alerts (/datum/hud/proc/reorganize_alerts)
[2022-10-14T04:16:25]   src: /datum/hud/human (/datum/hud/human)
[2022-10-14T04:16:25]   call stack:
[2022-10-14T04:16:25]   /datum/hud/human (/datum/hud/human): reorganize alerts()
[2022-10-14T04:16:25]   CHAR_NAME (/mob/living/carbon/human): clear alert("pressure", 0)
[2022-10-14T04:16:25]   CHAR_NAME (/mob/living/carbon/human): handle …
```
> [GBP: No update] Fixes screen alerts sometimes going invisible

- _maps/map_files/cyberiad/cyberiad.dmm
This PR addresses what I believe to be issues with Box surfaced by the unit tests in https://github.com/ParadiseSS13/Paradise/pull/19204.
I'm uncertain about the changes for pipes/vents in atmos/scichem so let me know if they're not great fixes.
I'm also uncertain about which parts of the turbine actually need center nodes, so I kept both.
If these are all legit issues, then fixing them is good, and it makes it more likely that https://github.com/ParadiseSS13/Paradise/pull/19204 can get in alongside the tests it adds.
Not all of these have before and afters, in the cases where the fix was rote.
171,50 maints rage cage
152,56 turbine
79-85,152 vault electrified grilles
183,154 eng maintenance 
Before (computer removed for clarity):
After:
127,89 atmos
Before (lockers removed for clarity): …
> Fix Box issues caught by automated map tests.

- code/datums/status_effects/status_effect.dm
Fixes #19239
The issue was caused by an order of execution thing. Mob gets damaged, gets deleted, and afterwards the effect gets added.
This PR basically ensures no status effect can get added on deleted mobs.
Collect me some garbage please
A hivebot, blobspore and venus_human_trap walked into the captains office. All three got shot by a laser and got deleted properly.
Any mob which gets deleted upon getting killed would work.
> Ensures status effects can't be added post qdel. Fixing GC issues with mobs caused by status effects

- code/modules/mob/living/simple_animal/bot/mulebot.dm
Corrects a small oversight made on #19024, by removing the . = ..(), it made it not able to screwdriver the mulebots. This occured because of a slight misunderstanding from me of the code during reviewing the old PR, which old me decided it was probably an accident because this is one of those procs that always tries to call . = ..()
Fixes #19346
Screwdrivered a mulebot, worked correctly.
:cl:
fix: Mulebots can be screwdrivered again
/:cl:
> Fixes mulebots not being screwable

- code/datums/helper_datums/teleport.dm
- code/game/gamemodes/cult/cult_items.dm
- code/game/objects/effects/portals.dm
- code/modules/mob/living/simple_animal/hostile/megafauna/ancient_robot.dm
- code/modules/research/experimentor.dm
- code/modules/telesci/bscrystal.dm
Makes the portals, made from wormhole projectors, only spawn effects once every 0.5 seconds
Effects can harm performance if overdone
- Make a wormhole projector
- Make two portals with it
- Walk through it fast enough
:cl:
tweak: Wormhole projector portals now only spawn effects every 0.5 seconds
/:cl:
> Makes wormhole projector portals spawn effects once every 0.5 seconds max

- _maps/map_files/Delta/delta.dmm
- _maps/map_files/MetaStation/MetaStation.dmm
- _maps/map_files/cyberiad/cyberiad.dmm
It adds convenience for the magistrate. Now, his front doors have a deskside door button and a window tint button. front doors are also glassed and tinted.
All other Heads and VIPs get this, Magistrate should too.
Box:
Delta:
Meta:
Launched every map through test server, joined as Magi, went to the office and tested the buttons.
:cl:
add: Added an office button to the magistrate's office, front doors are now glassed and tinted.
/:cl:
> Magistrate deskside office door button

- _maps/map_files/Delta/delta.dmm
- _maps/map_files/MetaStation/MetaStation.dmm
- _maps/map_files/cyberiad/cyberiad.dmm
- code/game/machinery/computer/buildandrepair.dm
- code/game/machinery/computer/camera.dm
Turns multiple monitors into proper items.
If you deconstruct one of these monitors it will have the telescreen circuit board (wich has all cameras access), it should be the respective circuit board.
- Deconstructed the monitors, it has the correct circuit board now.
:cl:
fix: Fixed monitors having the wrong circuit board when deconstructed
/:cl:
> Fixes monitors having the wrong circuit board when deconstructed

- _maps/map_files/MetaStation/MetaStation.dmm
Fixes #19308
Adds one extra camera so the bottom right slime pen can be fully reached.
Allows xenobio players to not be irritated by a minor oversight.
Load Meta.
Use the xenobio console.
Can see the previously unreachable corner.
Put a slime in said corner and took our lad back out using the console.
:cl:
fix: Fixed unreachable slime pen corner with the xenobio console in meta xenobio
/:cl:
> Add an additional camera to meta xenobio so it fully reaches every pen fully

- code/game/objects/items/weapons/RCD.dm
Fixes scuffed RCD airlock image previews and re-writes the code a bit to not use `getFlatIcon()`.
Loaded into the game. Viewed the RCD airlock image previews.
:cl:
fix: RCD airlock image previews appear normally again
/:cl:
> Fixes scuffed RCD airlock image previews

- code/datums/components/orbiter.dm
- code/modules/mining/lavaland/loot/tendril_loot.dm
Fixes the orbiter component so it actually uses the `lock_in_orbit` parameter/bitflag. It sets those up, but didn't make use of it afterwards.
Now, orbiters that use `lock_in_orbit` will not have `COMSIG_MOVABLE_MOVED` registered to them, and always stick with their atom. Ghosts can still break away as they don't use that bitflag.
Fixes #18739
https://user-images.githubusercontent.com/80771500/193825726-331a6ad2-65ab-482e-aeb7-463edb0e8103.mp4
Used a _spooky_ lantern and went back and forth with a shuttle.
:cl:
fix: Spooky lantern wisps keep orbiting the user while in shuttle transit
/:cl:
> Orbiter component now uses lock_in_orbit parameter, allowing for orbiters that always stay with an atom

- code/game/objects/items/weapons/grenades/grenade.dm
Improves the GCing on grenades
They use walk(), walk is not reset, ref is kept, the grenades will always fail to GC due to this. GCing is good.
This needs to be done for a boatload of other items as well 
compiled, grenades GCed properly. 
NPFC
> Grenade GC improvement

- code/game/objects/items/weapons/extinguisher.dm
- code/game/objects/items/weapons/tanks/watertank.dm
- code/modules/reagents/chemistry/holder.dm
- code/modules/reagents/reagent_containers.dm
Fixes #19255
- Waterpacks and the nozzles now properly GC.
- Move nozzles to Initialize
- Makes reagents not hold a reference to their atom when they get destroyed
The whole water tank stuff needs a refactor. Why are the tanks not related to each other? Refactoring it all will take a bit more time than I can spare though.
GC Gut ja
Spawned both a `/obj/item/watertank` and a `/obj/item/watertank/atmos` and deleted both after using both shortly by putting them on my back and spraying some water around.
Waited long enough for the GC to fully be done.
I've checked all subtypes of `/obj/item/reagent_containers` and `/obj/item/extinguisher` to see if any changes made there would impact the subtypes. None behave as weird as the nozzles.
I in-game tested the fire extinguisher and cleaning spray …
> Fixes waterpacks and friends not GCing. Clears atom reference from reagents

- _maps/map_files/cyberiad/cyberiad.dmm
Removes a floor turf from a tile which is only meant to be a wall.
One turf per tile is the rule.
Ran unit tests.
:cl:
fix: Fixed incorrect floor turf assignment in brig.
/:cl:
> Box: Fix tile with simultaneous floor and wall turfs in brig.

- _maps/map_files/Delta/delta.dmm
Fixes 2 minor oversights on Delta specifically a tile in arrivals with its paint facing the wrong direction and a danger tile effect in departures clipping through a wall. (see images)
Fixes small oversights to polish our beloved Delta.
**Before:**
**After:**
Load delta
Go to the 2 spots
Use eyes
Confirmed map changes worked
:cl:
fix: Fixed 2 minor tile oversights on Delta
/:cl:
> Fixes 2 minor tile oversights on Delta

- code/game/gamemodes/nuclear/nuclear_challenge.dm
Fixes an erroneous extra space in the message that's shown when a war declaration is attempted after the 10 minute grace period.
Typos bad, they make me mad
:cl:
spellcheck: Fixed typo on nuke ops war declaration failure message
/:cl:
> Fixes typo in war declaration fail message

- code/modules/reagents/chemistry/reagents/alcohol.dm
Removes the three silly lines of code that makes Beepsky Smash the best stunning Chem in the game. It no longer has any special effects and is now a normal drink.
Beepsky Smash is very available, extremely easy to make, and instantly hardstuns your target for as long as its in their system. It can be put in Smoke Powder Grenades to instantly hardstun people, even through hardsuits and regardless of internals. It can be loaded into Emagged Hypos, Syringe Guns, Dart Pistols, making it a better tranquilizer than actual tranquilizers. 
I removed the three lines of code and booted up the game to test it. I then proceeded to shamble to the bar and down as much Beepsky Smash as I could and walked around completely fine. I make Beepsky Smash Gas Grenades, I injected myself with it, and was still …
> Nerfs Beepsky Smash

- code/modules/mob/living/simple_animal/hostile/hostile.dm
- code/modules/mob/living/simple_animal/simple_animal.dm
Basically, a continuation of what #19171 is doing, extended to (now) all simplemobs. Sadly, many of these animals still fail to GC for other reasons (such as status effects and hud issues)
This fixes false positives due to walk_to not getting reset on a significant amount of mobs
GBP NO UPDATE due to warriorstar doing the majority of the actual work to find and solve these issues, not me!
GCing good, failing to GC bad
Failing to GC at a mass scale is incredibly bad
Local testing went well
Testing on the testserver went well, didn't notice any behavior differences.
Compiled, ran, screwed around with space carp and other simplemobs, more GCing than before on being deleted/killed.
:cl:
fix: Simplemobs GC more consistantly 
/:cl:
> [GBP NO UPDATE][READY FOR TM] Simplemob GC improvement 

- code/modules/mob/login.dm
Makes it so the dupe CID warning popup people get respects the CID collision list
People shouldnt be flagged just because they bought walmartputer
None but its probably fine
fix: Walmart PC users will no longer be flagged for CID collisions 
/:cl:
> Fix a CID warning not obeying the ignore list

- _maps/map_files/generic/centcomm.dmm
Adds a few QoL goodies to the admin surgery room such as a suspicious surgery duffelbag, a full toolbelt, an operating computer, a mounted defibrillator, and some anesthetics.
This is my first (real) mapping PR, so please let me know if I've broken anything/could do something better.
While the admin room is kind of a weird mix of IC and OOC, it's really nice for testing, especially when working with the tiny map. Not having to spawn in the operating computer and surgery tools each and every time would be a godsend.
The debug IMS would save a tiny bit of time too, but if it's a little too OOC to have mapped into the game anywhere, I can definitely remove it.
- Spawned in
- Everything looks right
:cl:
tweak: The admin testing room has some new surgical tools.
/:cl:
> Slightly optimizes admin surgery room

- code/modules/awaymissions/corpse.dm
Makes mob spawners generate a random name based on the species. Currently they default to human names as it is done on the mob living level, while setting species is done later on the carbon level.
Fixes #19450. Random dead bodies also get the proper names.
Used a mob spawner and set a species. Human spawners were set to have the custom option available for all for ease of testing.
:cl:
fix: Mob spawners have properly set names based on species.
/:cl:
> Carbon mobs get proper species-based names for mob spawners

- code/defines/procs/announce.dm
- code/game/jobs/job/supervisor.dm
- code/game/machinery/computer/communications.dm
- code/game/machinery/requests_console.dm
- code/modules/mob/living/silicon/ai/ai.dm
- code/modules/security_levels/security_levels.dm
Removes the state and implementation for producing newscasts from announcments.
This behavior isn't used anywhere, and it's not even exposed in any admin interfaces. We have several announcement subtypes that aren't really all that different from each other, and removing unneeded state makes it easier to refactor them.
Ran unit tests.
> Remove unused newscast ability from announcements.

- code/modules/research/experimentor.dm
When using the E.X.P.E.R.I-MENTOR, two of the random events which may occur are the teleporting of Ian or Runtime to the E.X.P.E.R.I-MENTOR itself. In order to do this, it would find those pets in LateInitialize, and hold onto those references forever. Once Ian and Runtime are killed/deleted, these references aren't cleaned up, but they are completely unnecessary in the first place.
GC failures bad.
Testing GC reference loss:
1. Enabled GC ref finder debug options in `_compile_options.dm`.
2. Spawned in, jumped to Ian and Runtime and deleted them.
3. Waited for GC logs.
Before:
```
[2022-10-18T02:44:26] Beginning search for references to a /mob/living/simple_animal/pet/cat/Runtime.
[2022-10-18T02:44:26] Finished searching globals
[2022-10-18T02:44:35] Found …
```
> Don't track Runtime or Ian in E.X.P.E.R.I-MENTOR state.

- code/game/gamemodes/blob/blob_report.dm
Logs the blob report/CC detonation request
This is
1. Rare
2. Does not alert admins that it happened
3. Has a severe impact on the round
Forced the proc looked at the logs
:cl:
tweak: Admins now see when CC automatically orders for the station to be detonated
/:cl:
> Blob report/CC detonation request is now logged

- code/modules/client/client_procs.dm
- code/modules/world_topic/adminwho.dm
- code/modules/world_topic/status.dm
- paradise.dme
*Please ignore the fact this isn't atomic. If I don't do one I'll forget the other. Do as I say not as I do.*
This PR adds a new `adminwho` topic call (requires auth, you'll see why in a minute) to better display adminwho info out of game. It will now include an actual JSON schema instead of splitting a list for keys starting with `admin` and ending with a count, and will actually consider AFK state, stealth state, etc.
The other thing this PR does is add a verb to reload your graphics. This can happen sometimes with BYOND if you have other apps open that want to use your GPU to do work (yes BYOND is actually GPU accelerated), and can result in bugged overlays. This verb disables and re-enables hardware acceleration ingame without a restart, which should fix these issues.
- Better info in …
> Adminwho topic tweak + Graphics fix verb

- code/modules/research/xenobiology/xenobiology.dm
When used more than twice in a one-minute period, Sentience Potions will violently explode, moderately injuring the user with an explosion equivalent to a PDA bomb.
Each time a sentience potion is unsuccessfully used, it "heats up" in stages (starting from 0), and explodes if you try to use it at stage 2. The potion "cools off" a stage every 60 seconds. The user receives warning notifications with every attempt, and can check the state of the sentience potion by examining it.
Xenobiology loves spamming sentience potions on mobs that dchat has zero interest in possessing, resulting in annoying spam that makes lots of people disable sentient mobs in their role preferences entirely. Now, it'll be more difficult to casually pester dchat with sentience requests.
Compiled and tested on local …
> Sentience Potions now violently explode if overused

- code/_onclick/hud/plane_master.dm
- code/_onclick/hud/plane_master_controller.dm
Fixes rotatium not rotating space.
having the  ***VOID*** show up when your screen rotates is bad.
gave myself rotatium
looked at space
:cl:
fix: rotatium now rotates space properly.
/:cl:
> rotatium now rotates space

- code/modules/mob/living/carbon/human/update_icons.dm
if the title is confusing, imagine plasmaman envirosuits, they have gloves _built_ into them.
Small followup to my oversight in https://github.com/ParadiseSS13/Paradise/pull/19058
Only jumpsuits that this will concern realistically is plasmaman envirosuits, kinda forgot that we have plasmamen as a species 💀 
Hands being ontop of some jumpsuits might be a bit too _jarring_, fixes that
Spawned as plasmaman, my purple bones weren't ontop of my envirosuit.
:cl:
fix: Fixed hands overlaying ontop of plasma envirosuits.
/:cl:
> [GBP NO UPDATE] Hands don't overlay above jumpsuits on which the hands are covered

- code/game/machinery/deployable.dm
Fixes #19475
moves a return down so the attackby always returns null instead of returning the parent function when a wooden barricade is attacked with wood. This prevents players from abusing the zero cooldown (because the attack didn't go through yet) caused by the do_after in the attackby proc.
This is an exploit, a funny and inconsequential one at that.
Loaded in game, repeated steps offered for reproduction of issue in the report in #19475
Was unable to circumvent the attack cooldown again
:cl:
fix: Players can no long circumvent the attack cooldown with Wooden Barricades
/:cl:
> Prevents Players from circumventing attack cooldown with Wooden Barricades

- code/_onclick/hud/parallax.dm
- code/_onclick/hud/plane_master.dm
- code/datums/weather/weather.dm
- code/modules/mob/dead/observer/observer.dm
- code/modules/mob/living/simple_animal/bot/bot.dm
prevents seeing parallax when you have night vision and no line of sight to a turf.
seeing space as a t-spider is disorienting 
before: 
after
walked around and changed my NV variables, saw no issues.
:cl:
fix: you wont see parallax instead of fog of war if you have night vision
/:cl:
> Fixes parallax being visible in the "fog of war"

- code/modules/events/alien_infestation.dm
- code/modules/events/blob.dm
- code/modules/events/spider_terror.dm
This makes the blob mouse, spiders and xeno larvas spawn in vents instead of directly on top of them. Except Prince. Prince is too big.
Some defines were made for spiders since that code was a mess.
Gives a chance to spawning vent crawlers. Except Prince.
https://user-images.githubusercontent.com/80771500/195956450-0558a854-59ff-4f01-bc9f-814a7ba7e63b.mp4
Spawned using the various event procs. Mouse was the first attempt.
:cl:
tweak: Blob mouse, xeno larva and spiders spawn in vents instead of on top (Except Prince)
/:cl:
> Vent crawling antagonists spawn in vents directly

- code/game/objects/structures/crates_lockers/closets/secure/security.dm
- code/modules/clothing/under/centcom.dm
Fixes https://github.com/ParadiseSS13/Paradise/issues/19419
Fixes the lack of the formal CC suit in the blueshield's locker.
Drip.
Spawned as blueshield, took a screenshot for `Images of changes`, put the uniform on, had positive drip,
:cl:
fix: The formal blueshield's uniform is back in the blueshield's locker.
/:cl:
> The (formal CC) blueshield drip is back in town

- code/datums/spells/knock.dm
- code/modules/admin/verbs/randomverbs.dm
Fixes https://github.com/ParadiseSS13/Paradise/issues/19463, which was my own dumb mistake
Changes like this shouldn't introduce new runtimes.
Tested admin verb and greater knock spell. Confirmed no runtimes.
**How do I know this fixes all remaining runtimes?** The thing these two call sites have in common is the use of the positional commas syntax in the Announce call. No other calls that I can find do this, or skip parameters without naming the following ones.
> [GBP NO UPDATE] Fix runtimes caused by proc signature change.

- code/modules/mining/lavaland/necropolis_chests.dm
Makes the cursed katana/dark shard not a valid snack organ.
Fixes #19449. Plus, who would eat that?
https://user-images.githubusercontent.com/80771500/197078396-da38ddea-cd48-48ca-92ee-ad4084c9fe74.mp4
Spawned a dark shard, and clicked on self.
:cl:
fix: You don't take a bite out of dark shards if you click on yourself while holding one.
/:cl:
> Dark shards do not get eaten by humans

- code/modules/clothing/suits/miscellaneous.dm
Lets you put guns and batons in the suit slot of the ablative trench coat
The allowed items list is copypasted from the regular armour vest
Basically, I forgot to add the allowed items list for the ablative trench coat when porting it over from TG. Oops!
Tested locally
:cl: Bmon
fix: You can now put weapons and other security items in the suit slot of the ablative trench coat
/:cl:
> Allows guns and other security stuff to be suit slotted on the ablative trench coat

- code/__DEFINES/misc.dm
- code/modules/antagonists/_common/antag_spawner.dm
- code/modules/mob/living/simple_animal/hostile/megafauna/hierophant.dm
- code/modules/mob/living/simple_animal/hostile/mining/elites/elite.dm
- code/modules/mob/living/simple_animal/hostile/mining/elites/goliath_broodmother.dm
- code/modules/mob/living/simple_animal/hostile/mining/elites/herald.dm
- code/modules/mob/living/simple_animal/hostile/mining/elites/legionnaire.dm
- code/modules/mob/living/simple_animal/hostile/mining/elites/pandora.dm
Elite tumors now kick out humans / cyborgs in the arena not summoner.
First kick out is warning, second damages them over time, worse each time they try it. (Think blue cube red cube teleportation, or hiero teleportation, or bluespace crystals.)
Elite changes
All elites have 50% armor pen in melee. Similar to megafauna, the only real fauna impacted by this is legionnaire, the only other one you melee with, bar broodmother. 
Legionare: Smoke cooldown from 3 -> 2.5 seconds.
Charge now weakens vs knockdown, multiple hits does less damage.
Broodmother:
Tenticals knockdown for 2.5 seconds in addition to stun.
Children now deal 12.5 brute instead of 5, and have 50 hp vs 40. 
Herald:
Shotgun activates after 0.5 seconds instead of 0.75
Bug fixes (Should be own pr got to it in this one sorry) …
> Elite buffs / Highlander mode for arena

- code/game/objects/items/stacks/sheets/sheet_types.dm
Moved wood floors out of the sublist.
For some reason, that i have yet to investigate even further, the max_res_amount is not working while inside a sublist, leading to the creation of an item from the main list in the same order in which the wood floor is located at.
Fixes https://github.com/ParadiseSS13/Paradise/issues/19485
- Tried to create 20 floor sheets from multiple sources, all works fine now.
:cl:
fix: Wood floor: stacked recipe now works properly
/:cl:
> [GBP NO UPDATE] Fix #19485 Wood floor: stacked recipe now works properly

- code/datums/uplink_item.dm
- code/modules/martial_arts/combos/cqc/consecutive.dm
- code/modules/martial_arts/combos/cqc/kick.dm
- code/modules/martial_arts/combos/cqc/pressure.dm
- code/modules/martial_arts/combos/cqc/restrain.dm
- code/modules/martial_arts/combos/cqc/slam.dm
- code/modules/martial_arts/cqc.dm
This PR addresses a number of community concerns/suggestions that were brought up in response to trying out the new, reworked CQC, particularly the comments about the low power level when compared to the TC cost. Here were the most common ones.
* Stamcrit in 5 hits, compared to being stamcritted by a baton in two.
* CQC is too loud for a stealthy martial art.
* The restrain combo didn't work very well, and people could just walk out of the grab.
* Legsweeping should get the user up from resting on their own.
* The description should better match what CQC does now.
<details><summary>Specific Details of Changes:</summary>
Consecutive CQC: 60 -> 70 Stamina Damage
Standing Kick: 15 -> 25 Stamina Damage, Half as loud
Horizontal Kick: Half as loud
Pressure: 1/10th as loud, nearly silent …
> CQC Balancing Tweaks/Buffs

- code/__DEFINES/is_helpers.dm
- code/game/objects/items/devices/flashlight.dm
- code/game/objects/items/weapons/storage/firstaid.dm
- code/modules/reagents/reagent_containers/glass_containers.dm
- code/modules/reagents/reagent_containers/iv_bag.dm
Adds the color blue to penlights, and makes them part of the `is_pen` check.
Penlights can already write on pill bottles, beakers and iv bags due to a specific check being made for it, what's stopping it from just being seeing as a pen all around?
This removes the listed specific checks above as well since now it's simply a pen check.
A little bit of consistency. Being only capable of writing on pill bottles, beakers and iv bags are a standout.
Spawned a pen and a penlight, and messed around with interactions as outside of the color addition, all was done was throw it into the helper check.
:cl:
tweak: Penlights are now pens all around.
/:cl:
> Penlights are universally pens

- code/datums/uplink_item.dm
- code/game/objects/items/weapons/dice.dm
- code/game/objects/items/weapons/storage/belt.dm
- code/game/objects/items/weapons/storage/uplink_kits.dm
- code/modules/projectiles/guns/projectile/sniper.dm
- code/modules/surgery/organs/autosurgeon.dm
Updates most Syndicate bundles, as well as adding 3 new ones.
I've made a forum post already with the planned changes and the design document, which can be found here:
https://www.paradisestation.org/forum/topic/23098-syndicate-bundles-rebalancing-and-new-additions/
Some changes have been made based on feedback from the thread and discord, but the design document reflects all the changes present in this PR. To summarize the changes made to bundles here as well:
- **Spy** - Removed Garrote, Camera bug and AI detector. Added Storage Implanter and Energy Dagger.
- **Hacker** - Removed Syndicate AI board. Added Blue energy sword, Agent ID and EMP Kit.
- **Bond** - Removed 10mm HP magazine. Added 10mm AP magazine and Chameleon Sec HUD.
- **Thief** - Removed No-slips.
- **Payday** - Unchanged. …
> Syndi Bundle Rework

- code/__DEFINES/layers.dm
- code/datums/weather/weather.dm
- code/game/area/areas.dm
moves weather overlays to a new plane, AREA_PLANE
this looks better than
this
looked at rad storm
:cl:
fix: weather overlays render properly
/:cl:
> Fixes weather overlays

- code/game/objects/items/random_items.dm
Removes the animalhide/random, bottle/random_chem, secure/unknownchemicals, secure/chemicals, largecrate/schrodinger, random_base_chem, secure/chemicals, and the largecrate/evil.
These items aren't used and will never be used. They fail to all GC as well. Mappers have better options
Items retained should be removed in the future honestly, but I'd rather not remove stuff that could theoretically be used in a PR that removes stuff that just won't be at all (With the exception of the pillbottle, which is actually used but probably shouldn't be)
Compiled and ran with space ruins on
NPFC
> Removes some unused (and never will be used) items

- code/datums/weather/weather_types/radiation_storm.dm
Increases the 20 raw rads the event applies to you to 400 (x20) (20 is effectively 0.44 radiation per `weather_act()`, minus armour, a pityful amount that does literally nothing)
Isn't standing out in radstorms fun? You can be a swedish clown chav!
Not anymore.
Risk a small dip, get a slap in the face. You will have about 2.4k radiation if you stand in the whole thing, enough to cause severe long-term radiation damage. Better hope medbay has strong antirads.
Got all the mutations.
:cl:
tweak: Tweaked rad storms to give you 20 times the radiation compared to previously.
/:cl:
> Buffs rad storms

- code/game/objects/items/weapons/RCD.dm
Added a check to prevent matter from being consumed if a wall has already been built.
Fixes https://github.com/ParadiseSS13/Paradise/issues/19495
- Set RCD mode to wall
- Spam click to build a wall
- Noticed that only 3 matter has been consumed
:cl:
fix: Spam clicking with an RCD to build a wall will no longer consume matter for failed attempts
/:cl:
> Fix #19495 Spam clicking with an RCD to build a wall will no longer consume matter for failed attempts

- code/game/objects/effects/landmarks.dm
Fixes https://github.com/ParadiseSS13/Paradise/issues/19432
Missing sprite suit bad :(
Spawned `/obj/effect/landmark/costume/butler`
No missing sprite.
:cl:
fix: Fixed a sprite-less suit spawning when it shouldn't.
/:cl:
> [GBP NO UPDATE] Fixes the basetype of .../under/suit spawning

- code/modules/clothing/chameleon.dm
Restricts some jumpsuits that shouldn't be used ingame... from being used ingame.
Less missing sprites(potentially).
Looked at an EMP'd jumpsuit for some time, less missing sprites.
:cl:
fix: Less broken sprites (should) now appear when using broken chameleon jumpsuits.
/:cl:
> [GBP NO UPDATE] Restricts some jumpsuits from appearing with chameleon gear

- code/modules/martial_arts/cqc.dm
Changes SetLoseBreath to AdjustLoseBreath in the cqc move.
Set and adjust does 2 different things. Set sets a value to X. Adjust adds or subtracts from a value by X.
Let us say someone had 30 seconds of lose breath, and was hit by this move. They would currently, not increase to 33 seconds of losebreath, instead, it would lower it to 3 seconds. This is bad / doesn't make sense, so will fix that up.
Confirmed it didn't subtract from the value
:cl:
fix: CQC no longer can make people choke less when choking them.
/:cl:
> makes CQC not theoretically heal losebreath

- code/modules/mob/living/simple_animal/constructs.dm
This PR removes Cult Construct Juggernaut ability to reflect lasers
In default cult round its VERY VERY easy to get juggernaut. You kill one cyborg or  one officer or any other mindshielded person and sacrifice it, then put it in shell. 
To play against it security will ALWAYS order WT auto rifles to have a chance to play against it. Without this nerf cult juggernaut has 76 fucking percent to reflect default security lasers. 
Security does NOT have any weapons to fight juggernaut and they NEED order WT rifles. 
In other side, WT rifles is kinda OVERKILL against default cultists. You can easily get cultist using disabler, rubber shotgun and other guns, same as they can easily fight you. When security get WT rifles, game balance dies. Cult need to fix fractures and IBs, cult dies very …
> Nerfs Cult Juggernaut. Removed reflection

- code/modules/tooltip/tooltip.dm
BYOND text macros are stripped from the names when they're fed to the tooltips, as it gets confused and displays a ? in a diamond when they're present.
Fixes that oddity with tooltips and macros.
Hovered over several items, spawned items with text macros in their names.
:cl:
fix: Tooltips do not occasionally show a gargabe symbol before the item name
/:cl:
> Tooltips have BYOND macros stripped from the item names

- code/modules/mob/living/simple_animal/hostile/faithless.dm
- code/modules/mob/living/simple_animal/hostile/hivebot.dm
Adds ending punctuation to the descriptions of two mobs, Faithless and Beacon. That's all.
Periods are good for the soul
Compiled and tested on local debug server. Descriptions now have periods at the end
:cl:
spellcheck: Fixed punctuation on some mob descriptions
/:cl:
> Fixes punctuation on mob descriptions

- code/modules/surgery/surgery.dm
Fixes some unintentional behavior where so long as a surgery was started on a table, it could be continued in any state. This PR ensures that surgery steps must be performed on an operable surface.
Surgery was supposed to be limited to tables (as noted by the fact that you can only start surgeries on tables); this was absolutely an oversight.
- Start surgery while someone's lying down
- Stand them up
- Click them with a scalpel and stab them instead of incising
:cl:
fix: Surgery steps can now only be completed on operable surfaces.
/:cl:
> Fix surgery steps being performable in invalid states

- code/modules/antagonists/changeling/powers/tiny_prick.dm
- code/modules/mob/living/living.dm
Adds a tweak to pathfinding for mobs specifically, allowing changeling stings to work. Feedback messaging is also added to distinguish targets that are too far away vs. not pathfinding to it.
The tweak has the side effect of causing mules to be more likely to run over people when emagged due pathfinding not rejecting paths with mobs in them.
A working, clearer cling sting. More bloody hallways from deliveries.
Spawned mobs in an open area and behind obstacles, and attempted to sting them. Looked at bots as well just to be sure. Bots with no density are unaffected.
:cl:
tweak: Mule pathfinding do not ignore possible routes if they have other living beings in the way
fix: Fixed changeling sting range
/:cl:
> Fix changeling sting pathfinding and add additional feedback messages

- code/game/gamemodes/cult/cult_items.dm
Cult spear no longer instant stuns and does 40 damage.
It now does 30 damage, and marks a person similar to cult spell. If it hits a person who was cult marked, it will trigger the stun.
Recall of the spear has been improved, and will hit threats on the way back that are lying down, or go into a knocked down cultist hand.
A 6 second instant stun is not great. A cult knockdown spell / mark trigger is much better, 
Recall is good if you miss a throw, or as a trap, but could use a bit of help. Adding undodgeable to the throw flag on recall means it will go into the hand more consistently, or can be used to trigger marks, if you want to give up the 150 blood spear.
Spawned in.
Confirmed damage was correct
Confirmed it marked on hit.
Confirmed recall worked on user if lying down.
Confirmed …
> Makes cult spear not an instant stun.

- code/modules/mob/living/carbon/human/death.dm
This PR removes the outdated gibbing animation from triggering upon the gibbing of a subject (mob/living/carbon/human).
The gibbing animation was not compatible with our many species, gibbing someone looks cleaner and is more consistent without the animation, and I encountered a rare runtime exception when punching the gibbing animation model, which could impact stability of the live server if someone were able to do so, and entirely removing it also eliminated that from happening.
https://youtu.be/xY95vOJX1hE
I removed the animation from the code that triggers upon the death via gibbing of any mob/living/carbon/human, ran the local server, gibbed a human, tajaran, and nian, did not run into any runtime exceptions, and observed no gibbing animation.
:cl:LynxSolstice
del: Removed the old …
> Removes gibbing animation

- code/modules/recycling/disposal.dm
I accidentally removed a line of code that was important to making sure disposals didn't end up looking like this
While it works fine despite the pipes, it looks jank as hell currently
welded some pipes
:cl:
fix: Fixed disposals pipes not getting the right icon when welded
/:cl:
> Fixes disposals not inheriting the proper icon state when welded

- code/datums/uplink_item.dm
It seems at some point that the Chameleon Kit, EMP bomb, Syndicate Bomb and Plasmafire grenades were removed from the nuke ops uplink. Since these items still have "nuke" variants in uplink_items.dm it seems them not showing up wasn't intentional and likely an oversight from another PR. This PR ensures they do now show up for operatives once more and at their adjusted prices.
It also removes a duplicate entry for no-slips (and their nuke variant) in the same file and moves the chameleon kit nuke variant a bit closer to the traitor one in the code.
As far as I can see, operatives should still be able to use these items and all of them would be useful to them depending on how they want to play.
Spawned myself in with a traitor and operative uplink and ensured the relevant items showed on …
> Fixes certain items being removed unintentionally from operative uplinks

- code/modules/mining/equipment/wormhole_jaunter.dm
- code/modules/mob/living/carbon/carbon.dm
If a corpse calls the vomit proc, such as being thrown through a mining jaunter, it will still vomit despite being dead. This PR implements a new check in the proc to make sure they don't starting vomiting successfully when they really shouldn't be.
If the dead don't speak they sure as hell shouldn't be throwing up.
Spawned myself in and threw a corpse through a jaunter - no more vomiting.
:cl:
fix: Corpses can no longer vomit.
/:cl:
> Fixes human mobs still being able to vomit while dead

- code/game/machinery/doors/airlock.dm
"removes" instead of "remove"
Typos are bad.
- get into the last step of airlock shielding removal
- used the crowbar to remove it
- received the message without typos
:cl:
spellcheck: Fixed typo when removing airlock shielding
/:cl:
> Fixed typo when removing airlock shielding

- code/game/turfs/simulated/walls.dm
Fixes some wall deconstruction runtimes through the attackby proc
specifically just unindents three `return TRUE`s down a level
Fixes #19586
Tbh, the way this is coded is bad and could really just use with a refactor
Runtimes are bad
Tested issue and reproduced runtimes
Unindented the three return TRUEs
Compiled and ran and tried reproduction and no runtimes were produced
no player-facing changes, no CL
> Fixes wall deconstruction runtimes with power tools

- code/game/objects/structures/safe.dm
Sets locked status to FALSE when its repaired. With this change the player will be able to close the safe instead of being stuck in a open/locked state.
- Used the drill to open the vault safe
- Spawned safe_internals and used to repair the safe (can only repair if its open)
- Managed to interact and close the safe normally
:cl:
fix: Safes can now be closed when repaired
/:cl:
> Safes can now be closed when repaired

- code/game/dna/dna_modifier.dm
> Fixes a DNA scanner stacktrace runtime

- code/modules/awaymissions/corpse.dm
- code/modules/response_team/ert.dm
- code/modules/ruins/syndicate_space_base.dm
Fixes #17891.
This PR slightly modifies how human spawners work, so that spawned humans have their appearance properly randomized.
Sets skin tone for Syndicate Base human spawners to remain albinos for that creepy sci-fi bio-engineering vibe. You know, like Dark City.
I'm not going to pretend I understand DNA code, but update_dna seems to be the wrong thing to do if you create the human first, and make appearance/head appearance changes after.
Other species don't have their properties randomized yet in spawners so this doesn't affect any other species.
The ERT issue was a slightly different one. These aren't the same kind of spawner. An unnecessary update_dna call is removed. This lines up the code with the same spawner used for nukies, which we know works because we don't have issues …
> Fix human appearance randomness in spawners.

- code/datums/uplink_item.dm
- code/game/objects/items/weapons/storage/uplink_kits.dm
- code/modules/projectiles/ammunition.dm
- code/modules/projectiles/ammunition/boxes.dm
- code/modules/projectiles/guns/projectile/revolver.dm
- code/modules/research/designs/autolathe_designs.dm
This PR removes the recipe for the .357 revolver speed loader from the hacked autolathe and instead replaces it with an ammo-box of .357 ammo for the same price. The ammo-box contains the same amount of .357 ammo (seven shots) but cannot be directly loaded into the gun or speed loader. This means you have to either individually load bullets from the ammo box to the gun or speed loader or dump all the bullets on the ground and scoop them up into the speed loader. Lastly, this ammo box is bigger than most (the speed loader remains tiny) and cannot fit into boxes, so you can't just carry a million ammo boxes and invalidate the point of this PR.
The Syndicate .357 revolver is in a really powerful position right now. It can deliver 60 damage per bullet, 7 bullets per clip, very rapidly, which …
> Removes .357 Speed Loaders from Autolathe, replaces with .357 Ammo Boxes

- code/__DEFINES/admin.dm
- code/controllers/subsystem/jobs.dm
- code/controllers/subsystem/ticker.dm
- code/game/gamemodes/game_mode.dm
- code/modules/admin/antaglog.dm
- code/modules/mob/mob_helpers.dm
- paradise.dme
Currently, antag fishing logging is kinda terrible, mainly because:
- It duplicates the message 4 times in chat
- It checks in 2 places which is redundant as hell
- It has no historical logging
This PR changes that. Players who attempt to cheese the system are now reported to admins at roundstart, complete with infraction counts
All of this data is stored as an automated note which is not only useful for readability in a convenient place, but also as a convenient datastore
Since this involves a lot of DB queries, it runs everything fully async with query batching for minimal server holdup. It also waits till 10 seconds after roundstart to avoid it being lost in the chatspam flood, as well as to let the server catch up a bit.
Logging is good. 
Tried to antag fish over 2 rounds, saving and …
> Improved antag fishing busting

- code/modules/library/library_equipment.dm
Fixes a runtime caused by passing a null value to UnregisterSignal in the barcode scanner code.
```dm
2022-11-02T12:16:10] Runtime in _component.dm,220: Cannot read null.comp_lookup 
[2022-11-02T12:16:10] proc name: UnregisterSignal (/datum/proc/UnregisterSignal) 
[2022-11-02T12:16:10] usr: *REDACTED USER* [2022-11-02T12:16:10] usr.loc: The carpet (172,137,2) (/turf/simulated/floor/carpet) 
[2022-11-02T12:16:10] src: the barcode scanner (/obj/item/barcodescanner) 
[2022-11-02T12:16:10] src.loc: Jason Ford (/mob/living/carbon/human) 
[2022-11-02T12:16:10] call stack: 
[2022-11-02T12:16:10] the barcode scanner (/obj/item/barcodescanner): UnregisterSignal(null, "parent_qdeleting") 
[2022-11-02T12:16:10] the barcode scanner (/obj/item/barcodescanner): connect(Library Computer …
```
> Fixes a Barcode Scanner Runtime

- code/controllers/subsystem/garbage.dm
The way """we""" currently do it, each time you want to walk the queue you're forced to make a copy in memory of the whole thing
There's no real reason to want this, so it seems best to just avoid it entirely. It creates a TON of usage for no reason, and also risks a lot of overtime since you can't really batch a list copy like that.
So instead let's just iterate over the length of the queue, constant rather then O(N) time.
Similarly, rather then using an associated list in the form queue[ref] = gc time, we could store queue entries in what amounts to a tuple.
This means no associated list stuff, so the operation of queuing becomes cheaper, and pulling gc time similarly goes from O(log n) to constant time
I stole this work from myself and mso, tg pr 55595. I'm pring it here because I keep …
> Changes how the garbage subsystem queue stores and processes info

- code/game/machinery/tcomms/nttc.dm
Fixes #19610
The telecomms language conversion list included "Noise", which is not technically a language and it should not be there.
Less bugs, better gameplay.
1. Go to telecomms machine
2. Select language conversion
3. It is not there
:cl:
fix: Removed "Noise" from the telecomms language conversion list as it is not a proper language (it is used for emotes).
/:cl:
> Fixes the telecommunications core having "Noise" as a listed language

- code/_onclick/click_override.dm
- code/datums/uplink_item.dm
- code/modules/clothing/gloves/color.dm
Progresses #18179 by changing the weaken on power gloves' disarm to deal 60 stamina damage, and cause jittering. Also makes the description in the uplink more descriptive.
Lowered the cooldown from 4 seconds to 3 seconds on request.
Long range, undodgeable stuns are kinda wack. Now at least there's a bit more counterplay, as you get a chance to run, or call for help before getting totally stunned.
There was also very little in-game description on HOW to use the power gloves, and not even the wiki mentions the stun on disarm function of the gloves.
Shocked a bunch of skrells, and had to shock each of them twice to stun them. Also spawned in a tot uplink to make sure it said the right thing.
:cl:
tweak: Power gloves don't instant stun, and do stamina damage instead
tweak: Power gloves …
> Power gloves deal stamina damage instead of weakening.

- code/modules/mob/living/silicon/robot/component.dm
Due to cyber implants handling critical failure on their own, I split them from the prosthetics section of the cyborg analyzer. If they're failing, they'll show as such.
Fixes #18535. They're also implants, rather than seen as prosthetics or biochips.
Spawned as an IPC, and other various customized characters. Had the implant in particular reach critical failure.
:cl:
tweak: Cyborg analyzers treat cyber implants separately, and can detect if they're critically failing.
/:cl:
> Tweak the cyborg analyzer so it handles cybernetic implants separately

- tools/ci/unticked_files.py
CC @AffectedArc07 
Adds a simple script that does a lexical search on `#include` directives and matches them to files on the filesystem, reporting any discrepancies.
Unticked files are dead code and are ticking time bombs. See #19587 and #19588. This script will solve this problem forever into the future.
No CI configuration is actually provided because it would fail instantly; the following unticked files are not part of either of the above PRs and I don't know the status of the ninja module in general, since some of the ninja files _are_ ticked, so I'm not messing with them:
```
D:\ExternalRepos\third_party\Paradise\code\modules\ninja\__ninjaDefines.dm
D:\ExternalRepos\third_party\Paradise\code\modules\ninja\admin_ninja_verbs.dm …
```
> Add CI script for verifying tickedness of files.

- .github/workflows/ci.yml
- code/controllers/subsystem/ticker.dm
- code/game/world.dm
- code/modules/unit_tests/_unit_tests.dm
- code/modules/unit_tests/map_tests.dm
- code/modules/unit_tests/test_runner.dm
- code/modules/unit_tests/unit_test.dm
- Adds test runner:
- to make it easier to track things across test types
- for example to ensure a fully specified log can be emitted
- Adds map tile test type:
- when writing a test, coders implement CheckTile, which is handed a single turf
- when the test runner runs these tests, it iterates over all turfs in the specified z-level, and runs each test's CheckTile on each turf in turn.
- Adds several sample map tile tests:
- check to see if a pipe exists on the same tile as a scrubber or vent
- check to see if a tile contains two cables, each with a center node
- check to see if a tile contains an APC bump but no center node cable
- check to see if a tile is a space turf and contains invalid objects such as airlocks
- check to see if a tile is a space turf and contains a structure but is …
> Implement map tests for catching common errors.

- .github/workflows/ci.yml
- tools/ci/unticked_files.py
Adds the script introduced in #19590 to the CI workflow.
As in previous explanations in previous PRs (#19612, #19588, #19587), unticked files in the repo are bad.
CI. I only tested on Windows so we'll see what happens.
> Add untick file check to CI.

- code/modules/atmospherics/machinery/atmospherics.dm
- code/modules/atmospherics/machinery/components/binary_devices/binary_atmos_base.dm
- code/modules/atmospherics/machinery/components/trinary_devices/trinary_base.dm
- code/modules/atmospherics/machinery/pipes/pipe.dm
- code/modules/mob/living/login.dm
Currently, every move a ventcrawler makes will cause a full update on the pipe vision. This is... less than ideal to say the least.
This PR ensures that `update_pipe_vision` is only called by `relay_move` when you actually switch pipenets. The other calls are from `forceMove`. I didn't refactor that part because it wasn't the worst offender.
pipes now always return their parent when `returnPipenet` is called. I've checked the usages, and the only other spot which could have been affected was overridden by the pipe subtype. It hardcoded parent there instead of `returnPipenet`.
I prefer to not touch too much of the atmos code. So I'll leave that as is now.
Why the new proc?
When you get on a splitting pipe, then you didn't leave the pipenet yet. You only leave the pipenet when you get onto …
> Ensures update_pipe_vision is called only when you switch pipenets. Fixes lag caused by ventcrawlers

- code/datums/uplink_item.dm
Fixes an oversight with the price of a Saboteur borg from #18996 - it's now back to 25TC in cost for nuke ops.
Shouldn't have been reduced in price from what I can see.
Spawned in and checked it's back to the normal price.
:cl:
fix: Fixed oversight with Syndi Saboteur Cyborg uplink price.
/:cl:
> Fixes Saboteur Borg Price

- code/__DEFINES/_math.dm
- code/__HELPERS/type2type.dm
- code/__HELPERS/unsorted.dm
- code/game/dna/dna2.dm
- code/game/machinery/computer/security.dm
- code/modules/reagents/chemistry/reagents/misc.dm
This PR swaps out a hand-rolled implementation of `num2hex` with a macro. Para's existing implementation used ascii2text, which used a "clever" offset trick to map values to _uppercase_ hex characters, so the macro (which uses the native `num2text` with a radix of 16) is wrapped with `uppertext`.
I guess I should mention this is a port from Goon, inasmuch as this change can be considered one. I don't know if we have a blanket acknowledgement for Goon port attribution outside of the directories mentioned in the README.
`num2hex` sits at the bottom of DNA code, and it fires a lot on init due to the creation of internal organs for various things, as well as the dent made by all players spawning, having their bodies built up, and having their DNA synced. The primary driver of this is …
> Replace /proc/num2hex with a much faster macro.

- code/game/gamemodes/steal_items.dm
Removes the Ablative Trenchcoat from the theft pool.
As of now, you cannot steal the Ablative Trenchcoat from the Armory for use as an antagonist unless you take it OFF of a dead Officer. See: [the Advanced Rules](https://www.paradisestation.org/wiki/index.php/Advanced_Rules#Rule_6:_Play_Antagonists_Responsibly). 
As such, this removal will allow antagonists to freely snag it if Security starts breaking out Immolators/Pulse Slugs instead of catching a bwoink. This will also mean a smaller pool of theft objectives, meaning more antagonists may have to fight one another, creating inter-antagonistic conflict, something we truly have very little of in my experience.
Another option that could be taken is to add two Ablative Armor sets to the Brig's loadout to bring to total energy weapon …
> Removes the Ablative from the Theft Pool

- code/modules/projectiles/ammunition/energy.dm
Reduces the disabler rate of fire by 0.6 seconds.
From full charge to depletion, 20 shots.
8.5 seconds to 13.4 seconds.
Disablers are a bit cracked right now, fire rate is too good and easy to spam with its giant capacity. This should make missing shots more punishing as well as giving people time to close the gap.
Made a server and stopwatched, time is an interesting thing... speaking of time... did you know-
:cl: OctusGit
tweak: Added disabler delay and reduced its fire rate
/:cl:
> Reduces the Disabler's Fire Rate

- code/modules/martial_arts/combos/sleeping_carp/keelhaul.dm
Increases the stamina damage of keelhaul from 40 to 60. This makes keelhaul stamcrit in 2 combos (4 hits), from 3 (6 hits).
A carp user's only method of debiliating their opponent outside of already having a baton at hand is to perform three successive keelhauls. The fact that this takes six consecutive hits makes it vastly inferior to just using a baton instead. With crawling, this also means that you can be batonned at any point during this process by a user who can put their baton away in between each keelhaul (since it drops items in hand when performed on a horizontal target). 
This change doesn't majorly increase the viability of the 13tc martial art, but it does improve one of its weakest tools in the face of the suicidal nature of engaging in melee with baton-armed security. …
> Buff sleeping carp keelhaul stamina damage

- code/__HELPERS/traits.dm
- code/game/machinery/cloning.dm
The Jestographic Sequencer (cmag) can now be used on the cloning pod. Doing so taints the pod's synthmeat storage chamber, causing all people who emerge from the cloning pod to have the comic and clumsy disabilities.
As with cmagged doors, it's plainly obvious upon examination that the cloning pod has been tampered with, and the pod can be returned to normal functionality by scrubbing it down with soap or a mop.
The genetic disabilities brought on by bananium exposure are quite persistent, and can't be cured with mutadone alone. You'll have to get a Clean S.E. from Genetics to remove your disabilities... or otherwise accept your new life as a honking abomination.
A traitorous clown can now make the crew see the world from his perspective *and* inconvenience security, all without ever …
> Cloning pods can now be cmagged

- code/modules/mob/living/carbon/alien/alien.dm
This PR makes Xenomorph night vision default to "on" for all Xenomorph variants. The "toggle night vision" verb is still present.
Typically, Xenomorphs have night vision enabled far more often than not. With the default set to "off", you have to turn it on when you spawn in as a larva, then turn it on _again_ when you evolve, and if you're a drone evolving into a queen, you have to reenable it a **third** time. This PR will save you the fuss and enable it by default, like Terror Spiders.
Compiled and tested on local debug server. Larva start with NV enabled and the setting persists as you evolve
:cl:
tweak: Xenomorphs now start with night vision enabled
/:cl:
> Xenomorph night vision now defaults to on

- code/modules/antagonists/changeling/powers/mimic_voice.dm
Removes the chemical regeneration slowdown from the changeling's mimic voice ability.
One of the biggest issues changelings have are they the good abilities are very good, and the bad ones are very bad. Mimic voice is good for doing gimmicks and tricking people over comms, but not a ton else. Part of the reason why it's underused otherwise is because it halves your resource production when its on. If you forget/don't want to turn it off, it can seriously mess with combat situations.
Made myself cling, changed my voice to "Wah" and then regenned chemicals as normal.
:cl:
tweak: Changelings don't slow chemical production down when using mimic voice
/:cl:
> Changeling voice mimic doesn't slow chemical production

- code/datums/mind.dm
- code/modules/antagonists/traitor/datum_traitor.dm
**Fix 1:** 
`owner.current.client.chatOutput?.clear_syndicate_codes()` was runtiming because it's possible for client to be null if either the user disconnects too quickly or if they're ghosting out of a cryo pod. So I added a null check on client.
**Fix 2:**
Since it's possible for the `antag_datums` list to become null during `/datum/antagonist/Destroy`, I've changed the use of `QDEL_LIST(antag_datums)` over to manually looping through entries and deleting them/cutting the list etc. This was causing runtimes and potential GC issues due to the `L.Cut()`.
Spawned as a mob, gave myself traitor, vampire and changeling antag datums, then either deleted my mob or ghosted via the cryopod (deletes you as well).
No player-facing changes.
> Fixes runtimes and GC issues with antag datums / the traitor datum

- code/game/machinery/tcomms/_base.dm
- code/game/machinery/tcomms/nttc.dm
- code/game/objects/items/devices/radio/radio.dm
Alternate implementation of #19615, using AffectedArc's advice.
NTTC now checks rank as well as job title on the ID in regards to message formatting.
Rank is decided by the preset list of jobs on the HoP's ID computer, whereas using the "Custom" option only changes the Job Title displayed on the ID.
This allows Acting Heads to have the amplified "bold" font, as well as their departmental colors on their name and job title.
This also allows custom job titles to keep their departmental colors as well.
Note that only the job title is ever shown on the telecomm messages, never the rank.
The rank is only ever used for formatting.
Acting Heads are currently shown on the comms as default-green, and are not emboldened when they speak, making them indistinguishable at a quick glance from your …
> NTTC now uses rank for formatting if the job title is non-standard

- code/game/gamemodes/miniantags/revenant/revenant_abilities.dm
Fix #19520 If the target of a revenant harvest is alive but SSD, it sends a warning and returns, otherwise they Harvest(target)
I've copied the code from OnClick() that triggers the SSD alert and adapted it to the local code. Enclosed Harvest() inside an else.
SSD people being harvested by revenants is bad for the game.
Posessed a revenant with a guest account and tried to Harvest() an SSD corpse left by my actual account. The SSD warning message takes a while to show up after the player has gone SSD, but when it does it s consistent.
> Fix #19520 Adds a check for SSD players so they don't get harvested by revenants

- code/modules/power/supermatter/supermatter.dm
- code/modules/surgery/organs/eyes.dm
This PR makes the meson eyes implant prevent supermatter hallucinations. 
Currently both meson goggles and engineering goggles will prevent hallucinations; it only makes sense that the robot eyes with the same function function the same.
Tested on a local server. Shoved some swanky new eyeballs into my head and stared into the Magic Dorito(tm) for several minutes. Didn't get attacked by phantom abductors.
:cl:
tweak: Meson eyes now prevent supermatter hallucinations
/:cl:
> Meson eyes prevent supermatter hallucinations

- code/modules/clothing/masks/boxing.dm
Adds missing can_toggle = TRUE to balaclava, without it the item was stuck at the initial icon state and the head version of it would be invisible.
Fixes something that used to work before, the toggle for balaclavas.
- spawn balaclava, toggle it and wear to see if its correct.
:cl:
fix: Balaclava toggle now works again.
/:cl:
> A thieves best friend: Balaclava fix

- code/game/gamemodes/miniantags/revenant/revenant_abilities.dm
Fixes some oversights and weaknesses in the rev buff PR.
Notably:
- If no valid targets existed for the haunted objects, they just runtimed.
- No feedback to rev if haunting failed due to no objects, so it is now refunded and prints in chat.
- The range for checking for valid targets was 5 instead of the desired 7.
- No feedback was available to victims regarding dangerous-ness of the haunted items, so the filter size now scales with throwforce.
- Items that have no targets to throw at just sit there uselessly, so they now gain 5 throwforce for every idle cycle (up to the 15 cap).
- Items were attacking too slowly after server lag was being taken into account.
- Damage values were not being properly applied to haunted objects
- `Dodgeable = false` lead to the items hitting each other more …
> Rev buff day 1 patch

- code/modules/food_and_drinks/kitchen_machinery/kitchen_machine.dm
Fixes a bug where kitchen machines would fail to preserve all of the ingredient reagents when making additional servings, due to the code using a portion of a _constantly updating_ total reagent volume for its transfers, rather than caching the total first.
In other words, for an example of 2 servings, the code would first transfer 50% of the full 100% total ingredient reagents into the 1st serving, then 50% of the *new* total (reduced to 50%, so only 25% transferred) into the 2nd serving, then delete the remaining 25% of ingredient reagents.
Food vanishing in weird ways is bad. As much as kitchen machines eating up some of the food is funny and kinda realistic, it could be implemented in a better, more controlled and sane way (instead of via buggy code).
1. Spawned in a …
> Fixes kitchen appliances partially sucking up ingredients when upgraded

- goon/browserassets/css/browserOutput-dark.css
- goon/browserassets/css/browserOutput.css
Fixes security announcements to have properly-sized headers. Font sizes specified as percentages are relative to the inherited font size, not the element's default font size. In other words, if a normal sized h1 is 200%, a slightly smaller one is 180%; it is not 80% of the header's original font size.
Fixes #19687.
Visual regression fix.
Launched game, toggled alerts.
:cl:
fix: Security announcements have properly sized titles.
/:cl:
> Fix security announcement title size.

- code/modules/mob/living/living_emote.dm
This makes it so that if one is muffled, the deathgasp sound effect does not play.
Instead, it simply shows the normal message that comes with deathgasping.
Upon actual death, the message AND sound play.
It does not really make sense how one can audibly deathgasp while being muffled if normal gasping is muted.
Also prevents deathgasp being used to game being muffled to still audibly alert nearby players when in reality you should be muffled!
1. spawn in
2. deathgasp
3. see message and hear sound
4. apply tape to mouth
5. deathgasp
6. see message but hear no sound
7. commit die while muffled
8. see message still pop up and hear the deathgasp sound
:cl:
fix: Fixed deathgasp sound playing despite being muffled
/:cl:
> Removes the deathgasp sound if one is muffled

- code/game/objects/structures/watercloset.dm
This PR gives the puddle (the pool of water in the oasis enclosure at boxstation departures) a unique description. Before this PR, it inherited the sink's description, which didn't make any sense.
Flavor text that makes sense is good.
Compiled and tested on local debug server. The puddle has appropriate flavor text
:cl:
fix: Water puddle flavor text is now unique, instead of mirroring the sink's flavor text.
/:cl:
> Gives puddle a unique description

- code/modules/mob/living/carbon/give.dm
I've been looking at Kibana, and still seeing the occasional GC failure for `/obj/screen/alert/take_item` on some days, which appears to directly correlate with the `null.icon_state` runtimes described in #19385.
* This PR follows the logic of 19385. Alerts should not be directly qdel'd and instead need to be deleted with `clear_alert`. So, `COMSIG_PARENT_QDELETING` calls `cancel_give` now instead of qdeling the alert.
* Additionally converts some signal procs to use `PROC_REF` in this file while I'm here.
Less GC failures and runtimes.
No player-facing changes.
> Give item GC/runtime fixes

- code/game/machinery/portable_turret.dm
Revives https://github.com/ParadiseSS13/Paradise/pull/17440
Prevents cheesing syndicate turrets by standing on them.
Normal turrets are dense when deployed, syndie turrets are always deployed so they are never dense. This fixes that.
:cl:
fix: You can no longer stand on a syndicate turret to avoid it killing you.
/:cl:
> Fixes cheesing syndicate turrets by standing on them

- code/datums/weather/weather_types/solar_flare.dm
Makes the arrival shuttle completely protected from solar flares
People loading into the game while a solar flare is happening should get some breathing room, and not instantly have their vision flashed and start taking damage.
Fixes #19206
Loaded into test server at the arrival shuttle, and fired the solar flare event. Stood in the arrival shuttle and stared at space, took no damage. Walked out into the initial arrival hallway, stared at space, took reduced damage.
:cl:
tweak: Players in the arrival shuttle no longer take any damage from solar flares
/:cl:
> Makes the arrival shuttle completely protected from solar flares

- code/__DEFINES/flags.dm
- code/game/machinery/doors/airlock.dm
- code/game/machinery/doors/door.dm
- code/modules/mob/living/silicon/robot/drone/drone_abilities.dm
- code/modules/mob/living/simple_animal/friendly/mouse.dm
- code/modules/mob/living/simple_animal/powers.dm
- code/modules/mob/living/simple_animal/simple_animal.dm
Allows drones and mice to pass doors when hidden, using a new PASS DOOR flag. It does not allow them to pass doors when they are bolted. They have to use their hide verb first, which is to stop them from appearing on top of the door. Design port of yogstation13/Yogstation/pull/2209 and partial port of yogstation13/Yogstation/pull/7838
Allows drones easier time to follow their laws, without having to worry about letting someone into a room. It also allows mice to get to more places, hopefully allowing for more fun for mouse players but also so there is less "BLOB TURBINE".
Yep, mice and drones can pass under doors when hidden, but not when the doors are bolted.
:cl:
add: Mice and drones can now crawl under unbolted doors when hidden.
/:cl:
> Allows drones and mice to go under doors when hidden

- code/datums/spells/mime.dm
Reduces the uptime of Mime invisible wall spell from 30 seconds to 20 seconds. Cooldown is unchanged. All time values in the modified file have been converted from deciseconds to seconds.
Honestly, the Mime should not have had a 30 second unbreakable wall with a 30 second cooldown as part of its default kit. It's rarely used for RP value and is honestly just for shittery. Leaving it at 20 seconds keeps it as a powerful ability, but you will still have some downtime now for people to get their angry hands on you.
Spawned in as Mime, changed name to Mimeroni, created force wall, counted in sesames (very poorly), confirmed when the wall went away that the ability was not fully recharged. Everything else seemed to function fine with the conversion from deciseconds to seconds.
:cl:
tweak: …
> Shortens the Mime's invisible wall duration

- code/game/objects/items/devices/radio/radio.dm
- code/modules/mob/mob_helpers.dm
Gives another spin to #19241
Headsets with syndicate encryption key are protected from jammer effects.
Jammer replace_rate has been increased (50 --> 70)
The current scramble rate isnt enough to prevent the location or traitor name from being exposed to the public (even worse if the target is wounded), this buff should be enough to make most messages not that readable anymore.
- tested while using syndie keys, was not affected.
- tested jammer with common keys, see images of changes.
:cl:
tweak: Headsets with syndiekeys are protected from jammers
tweak: Buffed jammer scramble rate
/:cl:
> Another buff to radio jammers

- code/game/objects/items/weapons/storage/garment.dm
- code/game/objects/structures/crates_lockers/closets/secure/security.dm
Adds garment bags for dignitaries (NT Rep, Magistrate, Blueshield)
Moves all current clothing items (barring the shoulder holster) into the garment bag in all respective lockers
Will be useful for a later PR in which I plan to add clothing items to some of the lockers without cluttering them
Less locker clutter
Booted test server
Spawn as captain
Check all lockers and make sure all bags have what they are supposed to
Gib self
:cl:
add: Garment bags added for NT Rep, Magistrate and Blueshield
tweak: All respective clothing items moved into garment bags (excluding holster for BS)
/:cl:
> Garment bags for dignitaries

- code/modules/reagents/chemistry/recipes/pyrotechnics.dm
Makes blackpowder explosions work again.
Fixes #19548
The `my_atom` variable is null now due to the `holder` being deleted when the grenade gets deleted. Besides that the callback was done wrong which I've refactored to not be a global proc to begin with.
Fixes a bug
Created a grenade with heated blackpowder of about 470 K each beaker. Activated it and threw it into medbay. It blew up
Splashed blackpowder on the floor and heated it up with a welder
:cl:
fix: Blackpowder explosions work again
/:cl:
> Makes blackpowder explode again

- code/modules/mob/living/simple_animal/hostile/carp.dm
Makes space carp shockproof, so they can actually be a threat to things behind electrified windows.
Currently, if carp spot someone behind a shocked external window, they chomp at it until they die. This stops that and lets them potentially cause more havoc.
:cl:
tweak: Space carp do not take electrocution/shock damage
/:cl:
> Makes carp shockproof

- code/datums/helper_datums/map_template.dm
Adds an additional exception handler to map loading to ensure runtimes don't permanently freeze Z level inits.
This has happened a few times recently, as a result of either random bugs, admins using a proc call that ends up runtiming, or the shuttle manipulator being a buggy useless machine.
Tried to advance proc call a map template, init freeze lifted after runtime.
:cl:
fix: Fixed a bug that could break the game entirely if a map did not load properly
/:cl:
> Adds additional safeties to map template loading

- code/game/machinery/doors/airlock.dm
- code/game/machinery/doors/door.dm
- code/game/machinery/doors/windowdoor.dm
- code/game/objects/cleaning.dm
- code/modules/hydroponics/gene_modder.dm
All cmaggable objects now use the `CLOWN_EMAG` define for their ADD_TRAIT source, instead of being manually defined as `"clown_emag"`. No player-facing changes
Code consistency is good
Compiled and tested on local debug server. Everything works as expected
> Cmagged objects now use the same define on ADD_TRAIT

- code/modules/mob/living/living_defense.dm
Refactors `run_armor_check` so that it actually works with negative armour_penetration_flat. I asked Hal and armour_penetration_percentage should never be negative, only flat.
It allows hollowpoint bullets to actually work properly, along with any future melee weapons that have negative armor penetration
Tested armor against riot, and normal security armor, with negative and positive armor penetration items, works as intended.
:cl:
fix: Hollowpoint bullets now properly interact with armor
/:cl:
> Fixes negative armor penetration not working as intended

- CODE_OF_CONDUCT.md
Our code of conduct surrounding PR procedure is a bit outdated and unclear about how to work with the new design and balance teams. This PR updates it to be in line with what we expect of our contributors.
- Major changes or major impact should be relatively common sense as to why this should be discussed with the teams.
- We've seen over the years that species changes, however minor, are usually a very sensitive topic. To avoid unneeded issues here we want to ensure that a PR is checked with the corresponding teams before it gets made. This should avoid big discussions.
- Any other controversial change is relatively vague, but you should be able to use common sense here if you play the actual game.
This should make it more clear to contributors what we expect them to do when they plan on …
> Changes the code of conduct to include that you have to discuss major changes with the proper teams

- code/modules/projectiles/guns/energy/stun.dm
Prevents users from bypassing recently added disabler cooldowns by using two disablers and rapidly switching between them while firing on help intent.
Akimbo firing on harm intent is unimpeded.
This cooldown was added for a reason guys, people being sweaty to get around it is not what anyone had in mind when adding the cooldown.
Fired guns, modded cooldowns to be much longer and tried firing both.
:cl:
fix: Fixed being able to bypass disabler cooldowns by rapidly switching between two of them.
/:cl:
> Prevents bypassing disabler cooldowns by using two.

- code/modules/mining/machine_redemption.dm
ORM unfasten time increase (2 -> 6 seconds), same required time as vending machines.
The ORM is an important and supposedly heavy machine that is always at risk of being stolen (cargo one). 
It doesnt make much sense that it only required 2 seconds to move while vendors and other machines have bigger times.
- Tried to steal cargo ORM, took 6 seconds to complete.
:cl:
tweak: ORM unfasten time has been increased (6 seconds)
/:cl:
> ORM unfasten time increase (2 -> 6 seconds)

- code/modules/atmospherics/machinery/portable/canister.dm
Adds a logging entry for opening plasma/N2O canisters to the players logs (player panel -> LOGS). One could already access these via another menu but this one makes it easier to check.
No player-facing changes so I just deleted the changelog if that is ok.
Easier to find and yeet griefers.
1. Spawn a plasma and an N2O canister
2. Open them
3. Right-click character, player panel
4. Click on LOGS
> Adds more accessible logging for opening harmful canisters

- code/game/gamemodes/miniantags/guardian/types/bomb.dm
- code/game/gamemodes/miniantags/guardian/types/charger.dm
- code/game/gamemodes/miniantags/guardian/types/fire.dm
Tweaked the playstyle_string to include a few useful informations (chaos, charger and explosive).
Buffed Chaos by removing the need to be un-manifested to toggle his mode.
The hallucinate mode makes your target see all carbons as if they are a guardian (15 SECONDS), this isnt that useful since he knows the real one did punch him last, but if combined by teleporting him soon after it could be the chaos that makes for the guardian name.
I think the hallucination mode isnt strong enough to deserve this restriction, if someone had to choose they would always keep the teleportation mode on as it is useful in a greater amount of situations than hallucination.
- Verified new messages and tried to toggle Chaos mode while manifested.
:cl:
tweak: Chaos guardian can now toggle modes while manifested …
> Chaos guardian buff and tweak to some descriptions

- code/game/turfs/simulated/walls_indestructible.dm
Fixes the CC fakeglass windows by making them use the proper new window edging.
Moves CC from the weird overbusy indestructable walls to useing indestructable rwalls.
Consistent windows+walls, plus making CC look like a normal station, are good things.
Looked at CC
:cl:
fix: Fixed CC walls and windows being broken and incompatable
/:cl:
> Fixes CC windows and walls

- _maps/map_files/MetaStation/MetaStation.dmm
Fixes a few bugs/nitpicks I have with Meta
opacity on the plastic flaps in medbay has been set to 1
a rogue air vent in the SM room has been removed
very minor fixes to the warning stripes around SM to make it consistent
a few wall mounted signs around brig have had their x/y pixel push fixed
cameras are no longer area'd in space
map upkeep
Ran it locally to check the changes
:cl: Bmon
fix: Fixed a few minor mapping errors with Meta
/:cl:
> Bug fixes for Meta

- _maps/map_files/Delta/delta.dmm
- code/game/area/ss13_areas.dm
Changes the area from `library` area to `apmaints `area, so it responds correctly to radiation storms.
Fix #19489 by changing the type of area at the aft library zone (Delta) from library to apmaints (the surrounding maintenance area).
Having a maintenance area unshielded breaks the cohesion of "Maintenance is shielded from radiation".
Before
After
Launched a local server
:cl:
tweak: Delta maintenance library is now shielded from radiation
/:cl:
> Fix #19489, Changes aft maintenance library to aft maint area

- code/__HELPERS/traits.dm
- code/game/objects/effects/spiders.dm
- code/modules/mob/living/simple_animal/friendly/butterfly.dm
- code/modules/mob/living/simple_animal/friendly/cockroach.dm
- code/modules/mob/living/simple_animal/friendly/lizard.dm
Adds "lose tail" and the ability for NPC lizards to eat bugs
Player controlled lizards can now use the "lose tail" verb to escape a grab once every 5 minutes, after this is used, the person who grabbed them is knocked down for 3 seconds (as they tripped due to the lizard slipping out of their grasp) 
NPC lizards can now eat spiderlings, Butterflys, and cockroaches. This instantly kills all the types, but spiderlings have a 9/10 chance to slip out of the NPC's lizards grasp
These are some minor things to make lizards more distinct from mice
Compiled and ran 
:cl:
add: NPC lizards now eat bugs
add: Player controlled lizards now can use the "lose tail" verb
/:cl:
> Adds shed tail and eating bugs to simplemob lizards

- code/modules/clothing/masks/gasmask.dm
This PR changes the "use" effect of the Clown Mask from opening a window with options of other masks to change to, to opening a radial menu with other masks to change to. It also changes how the clown mask shifts (previously it simply changed icon state while keeping the old name, which was weird) and as a result properly adds the joker and rainbow clown masks to the game, which seemed to have previously only existed as icon state changes on the original clown mask.
Radial Menus are preferable over popup selection boxes, and this gives users a preview of what the mask will change into.
And a clearer image without the jokes,
Joined as Clown, took off mask, confirmed radial menu worked, confirmed it shifts between mask types properly, confirmed closing the radial menu plays nicely, made …
> Converts clown mask selection to a radial menu

- .github/CONTRIBUTING.md
Somehow we forgot to update the file when @S34NW got promoted. Well here is the official promotion according to the document!
May your reviews be fair and just!
Yes
We threw S34N into a map with lots of double disposal pipes and broken atmos piping and the only way out was to correct them all.
> Adds S34N to the review team. Long overdue this change

- code/modules/mob/living/carbon/human/examine.dm
- code/modules/mob/living/carbon/human/species/tajaran.dm
- code/modules/mob/living/carbon/human/species/unathi.dm
- code/modules/mob/living/carbon/human/species/vulpkanin.dm
- code/modules/mob/mob_grab.dm
Includes bees into allowed_consumed_mobs for tajaran, unathi and vulps. Will be stinged by it if eaten.
https://www.paradisestation.org/forum/topic/20908-make-tajaransunathivulps-able-to-eat-bees/
It makes sense that those species should be able to eat bees.
Being able to punish those stupid enough to eat living bees is worth it.
- Ate lots of bees while wearing a bee suit.
:cl:
add: Tajaran, Unathi and Vulpkanin can now eat bees
/:cl:
> Tajaran, Unathi and Vulpkanin can now eat bees!

- code/datums/components/largeobjecttransparency.dm
Tweaks the large object transparency component to remember the atom's mouse opacity, instead of setting a fixed value.
Fixes objects that use the component suddenly having their entire bounding box be mouse clickable when they shouldn't.
https://user-images.githubusercontent.com/80771500/203431247-f71bdb64-425e-476a-ac2b-6c5971d14243.mp4
Spawned a tree, walked behind it and then away from it, hovered the mouse near it.
:cl:
fix: Trees don't become suddenly clickable in a box around them when someone has walked behind one and away afterwards.
/:cl:
> Large object transparency component uses the proper mouse opacity value

- code/modules/antagonists/changeling/powers/headslug.dm
Adds two quick lines of text given to the user upon headslugging themselves as a Cling, instructing them as to how headslugs work. This is already done in the evolution menu but you can't view the evolution menu as a headslug, so this gives a little extra reminder for people, and was requested. Resolves https://github.com/ParadiseSS13/Paradise/issues/19703, at least the main part of it. Doesn't make it so headslugs work on monkeys, go out and find a person to bite >:)
More clarity to users about how their ability works is always good, especially in case they didn't properly read it on the evolution menu.
See above.
:cl:
add: Added a few lines of text upon using Last Resort to explain how headslugs work
/:cl:
> Gives some info about how headslugs work upon using Last Resort

- code/datums/spells/mime.dm
- code/datums/spells/wizard.dm
- code/game/gamemodes/wizard/spellbook.dm
- code/game/gamemodes/wizard/wizloadouts.dm
- code/modules/mob/living/simple_animal/hostile/hellhound.dm
Was discussed over at [#19266 ](https://github.com/ParadiseSS13/Paradise/discussions/19266) - the basic forcewall is very situational to use and often considered noobbait since newbie wizards might not realise the greater one exists. This PR merges them into a single forcewall spell to fix these issues. This does also means that healer apprentices, magical morphs and anyone that acquires a forcewall spell book will also now cast a 3 tile wide version.
Better for newbie wizards so they don't take the 1-tile wide version of the spell by accident and get themselves killed thinking it's the better version of the spell.
Spawned in and tested that the forcewall spell now deploys a 3 tile wide wall, and that other sources of the spell are working as intended (invisible greater wall etc.).
:cl: …
> Merges Forcewall and Greater Forcewall into a single spell

- code/game/objects/items/weapons/soap.dm
- Drasks now receive 5 nutrition per bite of soap, up from 2.
- Soap is now a finite source of food: After **30** bites, it disappears. The amount of bites remaining can be roughly tracked by examining the soap.
- Splits all soap-eating behavior into its own proc.
Prior to this PR, Drasks could use a single bar of soap as a source of infinite nutrition; the hunger system should not be something that standard players can opt out of with roundstart items. To encourage departmental cooperation, Drasks will now have to periodically consult with the janitor to acquire more food.
Compiled and tested on local debug server. The drask had a soap but he eated it
:cl:
tweak: Drask can no longer infinitely eat a single bar of soap. Savor the flavor while it lasts.
tweak: Soap now provides slightly …
> Drask can no longer eat soap for infinite nutrition

- code/modules/mob/language.dm
- code/modules/mob/living/carbon/alien/alien.dm
- code/modules/mob/living/carbon/alien/humanoid/empress.dm
- code/modules/mob/living/carbon/alien/humanoid/queen.dm
Gives the Alien Queen bold text in Alien Hivemind so Aliens can hear them better. Also gives this feature to Empress, even if that one's admin-spawn only.
The Queen should be able to be heard by her brood if she needs to speak, and this should hopefully give her more of a sense of authority. This same effect is had by Terror Spiders.
See above.
:cl:
tweak: Alien Queens and Empresses now have bold text in Alien Hivemind speech.
/:cl:
> Gives Alien Queen (and Empress) bold text in Alien Hivemind

- code/modules/supply/supply_packs/pack_engineering.dm
- code/modules/supply/supply_packs/pack_medical.dm
- code/modules/supply/supply_packs/pack_miscellaneous.dm
- code/modules/supply/supply_packs/pack_organic.dm
- code/modules/supply/supply_packs/pack_science.dm
- code/modules/supply/supply_packs/pack_security.dm
Fixes a few crates typos.
**Removes the following crates:** 
Conveyor assembly
Wizard costume
hygiene station
IV drip crate
Bottler crate
**Tweaked the following crates:** 
Blood pack crate (added iv drip)
Corporate posters crate (5 --> 8 posters, 5 is too little)
Lavatory crate (added hygiene station contents)
Costume crate (added wizard crate contents to it)
Suggestions are welcome.
Supply packs are currently bloated, removing unnecessary crates will help with that.
Conveyor crate: Cargo already prints it using the autolathe, theres no reason to order this crate.
Wizard costume: It's contents can be found inside the costume vendor, it would be better to order a vendor refill for multiple wizard costumes than ordering an expensive crate.
Bottler crate will become unnecessary if PR #19755 …
> Supply packs tweaks

- code/game/objects/items/weapons/storage/belt.dm
Checks that a sprite actually exists first before trying to create and apply an overlay for a non-existent image. Overlays for them will now work and not break if theres an item with no belt_icon
Fixes #18638, Fixes #19336, Fixes #18706
See above, also fixes toolbelts and pocket extinguishers. Tested the advanced toolbelt and t-ray described as in the other issues, also fixed.
:cl:
fix: Things on belts will now show correctly, even if one of the items doesn't have a sprite
/:cl:
> Fixes belt's overlays being weird when an item doesnt have a belt sprite

- code/_compile_options.dm
- code/datums/keybindings/emote.dm
- code/modules/unit_tests/emotes.dm
Player-facing, adds new emotes for some keybinds like *crack and *sign. On the backend, adds unit tests to ensure newly added emotes get keyninds.
Emotes like this should be optionally bound to keys, I just forgot to do so in my original PR. Unit tests make sure that we don't have to make more PRs like this in the future.
- Loaded in
- Bound key
- Cracked knuckles
:cl:
tweak: *crack can now be bound to a key.
/:cl:
> Adds new emote keybinds, and emote keybind unit tests

- code/modules/power/apc.dm
Allows APCs that have no cover to be destroyed, and fixes some weird duplicated messages. I think this method of not having it be under obj_deconstruction is good because it means people cant just welder down APCs when they're destroyed and will require full deconstruction. These explosions and tesla zaps are the exception.
Fixes partially #18334, fixes #13873 and fixes this 
into this
This used to be an APC
Dropped some bombs, released some teslas, APCs got destroyed
:cl:
fix: APCs can be destroyed by explosions and teslas now
/:cl:
> Fixes APCs being immune from explosion and tesla destruction

- code/__DEFINES/misc.dm
- code/__DEFINES/status_effects.dm
- code/datums/status_effects/blob_burst.dm
- code/game/gamemodes/blob/blob.dm
- code/game/gamemodes/game_mode.dm
- code/modules/mob/living/simple_animal/friendly/mouse.dm
- paradise.dme
Adds a status effect to blob-infected humans and mice. This effect has a timer on it like how the spell cooldown system does it.
Blob mice now don't get the spamming in the chat anymore of how long they still have. The messages humans get are still there.
The current icon works just fine with the better font. In a later rework :tm: this could be changed
The human blob infected don't have a good way to see when they are going to burst. This sometimes causes new players to burst in the middle of hallways which is not fun for anybody.
The mouse's current implementation is also quite bad. Spamming the chat with how long you still have ain't the best solution.
- Spawned a mouse and assumed direct control. And waited for it to burst
- Set the gamemode to blob and spawned as one. Then waited for …
> Adds Blob burst status effect to both blob mice and humans

- code/game/mecha/equipment/weapons/weapons.dm
- code/modules/projectiles/projectile/bullets.dm
The Reticence's gun once again deals stamina damage rather than brute damage
All other traits are untouched
40 brute -> 40 stamina 
The silly little mime mech shouldn't be murdering people left and right, especially if the pilot doesn't know that the silly little mime mech is very, very lethal.
The whole gimmick of it draining the charge of the honk mech is kind of null if it just kills them.
I've been told this is also unintended, and that fox didn't mean for this to deal brute. Makes sense as it turns a fun item that a mime can use into something that isn't going to ever end well for them.
You can still easily kill people with this as a tot, it has combat mecha punches, but a nonantag mime isn't gonna get a nasty surprise. 
skrell murder :>
:cl:
tweak: Mime mech's primary weapon now …
> Reticence now deals stamina damage

- _maps/map_files/shuttles/emergency_jungle.dmm
Sets timid to 1 on the jungle shuttle docking
Not breaking the game is very cool!
Shuttles should be shuttles, and shouldn't break species/tgui/huds
We really, /really/, should have this written down somewhere more obvious
NPFC - Should fix admins accidentally breaking the game with it for real now
> Fixes the jungle shuttle causing issues

- code/modules/atmospherics/machinery/airalarm.dm
Improves the code of air alarms, adds a construction examination helper to them, and fixes some missing icons during construction for them. Changes the drop placement during deconstruction to be the location of the item, instead of at the user's feet, which is awkward to pick up the parts. Changes their name to "Air Alarm", and adds a description. Partial revival of #18697
Not having to open the wiki to find out how to do something (you can just examine it instead) is good and makes the game more accessible to new players. Fixing bugs is good.
Built air alarms, took apart air alarms, worked as planned. See above.
:cl:
fix: Air Alarms now show their construction sprites.
/:cl:
> Changes air alarm name and description, fixes missing icons during construction

- code/modules/mob/living/simple_animal/friendly/mouse.dm
Fixes a case where blob mice would burst twice
Fixes a nasty bug
Spawned 3 blob mice. Killed one by suicide, another by calling `gib` and the last one by calling `death`.
:cl:
fix: Blob mice now don't burst twice in certain cases
/:cl:
> Avoid double bursting for blob mice

- code/modules/response_team/ert_outfits.dm
Gives the Gamma Medical ERT a toxins medkit, as stated in the title. This is to bring it in-line with other ERTs, which have toxins treatment options (Red has a toxins medkit, Amber has a bottle of pills containing salicylic and charcoal). I'm open to changing this to a charcoal pillbottle if that's preferred.
Gamma ERT should be a step up from Red ERT. It should have the same or better options available. Presently, if Gamma Med wants to treat toxins damage on itself, it needs to use combat stims. I know it can use the medigun to heal other people but it really should have the option of using charcoal the good old fashioned way.
Spawned in, confirmed it loaded, confirmed Gamma Med had charcoal, wept tears of joy.
:cl:
tweak: Added a Toxins Medkit to Gamma ERT equipment
/:cl:
> Gives the Gamma Med ERT a toxins medkit

- code/game/turfs/simulated/floor/light_floor.dm
Light tiles turn off without apcs having lighting power enable, and can not be turned on without power.
Uses 100 W per tile. A lightbulb with light range of 4 uses 80 w, and this has a range of 5.
Light tiles must be manually turned on if turned off by power outage, do not self turn on, can be changed.
They also use the extinguish message when turned off via power as it is spookier.
Light tiles producing light in maints without requiring area power is not great for upcoming shadow demons. Or placed in space. Shadow demons can not tentacle the tiles either, meaning they can not deal with them.
This PR means that while still very effective vs shadow demons, they still require the apc to be powered. If the APC is depowered or destroyed, the demon will have much more freedom once again. …
> Light tiles now require apcs to provide light power

- code/modules/mob/living/simple_animal/friendly/mouse.dm
Brings back the old `bursted` var that I removed (on accident). Dying doesn't set the `stat` var instantly. This is why you can get multiple `death` calls in this case due to the `gib` call in the `burst` proc.
Fixes a bug
Let the timer run out on a mouse blob
:cl:
fix: Actually fixes mouse blobs from bursting twice
/:cl:
> Adds var back which fixes double mouseblob bursting

- code/modules/shuttle/shuttle_manipulator.dm
Adds a 2 second cooldown to preview and load on the shuttle manipulator 
Prevents maploading errors because the first shuttle wasn't done being spawned yet, gives it just enough time to do so. 
Compiled and ran 
NPFC but admins can be a little less careful around it
> Adds a cooldown to shuttle manipulator 

- code/game/machinery/vendors/vending.dm
Adds an access check for vendors. They already got `req_access_txt` and `req_one_access_txt` mapped in, so it wasn't originally a free for all.
This could get TMed just in case, I already tried with drones and they retain the same behavior as before.
There's already mapped in access for vendors, they shouldn't be ignored and likewise the greytide just shouldn't empty the medbay's supplies just like that.
Spawned as a non-med and tried buying from med vendors, also tried as a drone. Tried `0` access vendors as well and that works fine too.
:cl:
tweak: Vendors now check for ID access if they have a minimum requirement set.
/:cl:
> [TM] Access check for vendors

- code/__DEFINES/dcs/signals.dm
- code/game/gamemodes/objective.dm
- code/modules/antagonists/changeling/datum_changeling.dm
If a changeling has an assassinate and escape with identity objective, the target cryos, and a new one is found, the assassinate objective is updated, but the escape with identity objective still registers as having the old target. 
Now the escape with identity target will know when it's linked assassinate objective finds a new target and update its own accordingly.
The escape with identity objective and it's linked assassinate objective should not have a mismatched target after their previous target goes to cryo. Less work on admins having to re-sync targets.
Loaded up a few different accounts and used a changeling with an assassinate and escape with identity objective, and had the target go to cryo.
:cl:
fix: Fix steal identity objectives not syncing to their linked assassinate …
> Fix escape with identity objectives not syncing to their linked assassinate objectives after the target cryos

- code/game/objects/structures/lattice.dm
- code/game/turfs/turf.dm
Adds special reinforced catwalk for use in the mining outpost, this catwalk cannot be destroyed by wire cutters. 
Tweaks lattice removal on turf change to exclude invulnerable lattice, as currently mapped in lattice is destroyed on mapload.
(Regular catwalk is due to changes in https://github.com/ParadiseSS13/Paradise/pull/12345) 
This catwalk is not constructable by players. It is not the same as TG's heatproof support lattice.
(Ironically I added this the same way as TG did, without even realising they had the same thing)
Allows us to place catwalks on lavaland in the map editor
(previously this just deleted the catwalk that was here and it was regular volcanic floor)
> Adds special reinforced catwalk

- code/modules/food_and_drinks/drinks/drinks/cans.dm
Shake can is now activated by CtrlClick.
Fixes https://github.com/ParadiseSS13/Paradise/issues/18918
- Could shake it using Ctrl and open transfer menu with Alt.
- ## Changelog
:cl:
fix: Soda can is now shaked by clicking Ctrl
/:cl:
> Fix #18918 Soda can alt click shakes are now activated by ctrl clicks

- code/game/objects/effects/anomalies.dm
- code/modules/mob/living/simple_animal/hostile/megafauna/ancient_robot.dm
- code/modules/power/supermatter/supermatter.dm
Vetus spawned grav and flux anomalies now knockdown, instead of hard stun. 
Vetus no longer dies slowly in space, legs were taking cold damage.
Vetus no longer gets thrown around by grav anomalies, messing up it's charge greatly.
Vetus legs are a bit easier to disable turrets on.
Grav anomalies if spawned via event (or by admins), can spawn with up to 3 shards of glass / rods, so even if it spawns in a hallwy, it is a threat. Vetus and SM uneffected.
With the benefit of hindsight, *maybe* hard stuns in a megafauna boss fight suck to play against.
Grav anomalies were extra special with vetus, making it's charge very silly, so this makes it immune to the pull and throw of it. You and the ore on the ground however, are still not.
Bluespace still works, as it already is mass teleporting, and …
> Vetus balance tweaks, also with a grav anomaly tweak

- code/game/gamemodes/miniantags/guardian/guardian.dm
- code/game/gamemodes/miniantags/guardian/types/assassin.dm
Assassin guardian now deploys stealthed, instead of having to deploy to go invisible.
Assassin guardian does not make an effect when deploying or recalling, or **visibly** make the host bleed when attacked. The host is still injured by their guardian being attacked, but it is much less noticeable.
Assassin guardian now deals 20 brute in melee when not stealthed, and now has 40% damage resist, making it actually have damage resist like other melee guardians. Before it had no armor.
Stealth timer lowered to 10 seconds.
Assassin does not show on huds, so it no longer gets outed by a doctor with a medhud.
Claws effect vs punching because it looks cooler. and fits an assassin more. Most assassins don't punch people to death.
Assassin sucks. You have to deploy to stealth, which is hilariously …
> Buffs assassin guardian

- code/game/objects/items/weapons/storage/backpack.dm
- code/game/objects/items/weapons/storage/storage.dm
Adds a method to zip/unzip duffelbags.
Zipped duffelbags have no slowdown, but cannot be accessed.
Unzipped duffelbags cause slowdown, but can be accessed.
Zipping/unzipping takes 0.7 seconds.
Syndicate duffles do not have a slowdown or zip/unzip delay, in the same way they currently do not have a slowdown.
Duffel bags are in a bit of a sad state, and this is my first step towards a few item rebalances. (This was the simplest to code.)
Essentially, dufflebags are totally unviable currently due to the slowdown. There is no way in hell anyone is using them, and it is sad. This will hopefully mean they will see more use by non-combat focused players (while remaining a not-so-great choice for antags and sec).
https://user-images.githubusercontent.com/12197162/203178123-a6785c1d-425a-433e-8acb- …
> Dufflebag rebalancing

- code/modules/projectiles/guns/projectile/automatic.dm
The WT-550 now cannot fit into normal backpacks as it has been made bulky. ~~It also needs two hands to fire.~~
This weapon is nuts. You can carry multiple in your backpack, ~~dual wield them for double fire output at **40 SHOTS** before needing to reload~~, and can carry multiple mags for quick reloading. Its a very common thing for security or antags to carry more than one WT because they have no limits on storage due to being normal sized. This change's goal is to make ballistics have some cons compared to lasers and also try to balance the gun, as its genuinely superior to lazers in most situations which I feel is a case of pretty bad powercreep.
booted server, checked size and tried to fire with two wt's. testing passed
:cl: OctusGit
tweak: The WT is now bulky
/:cl:
> Nerfs the WT-550's size.

- code/game/objects/items/weapons/implants/implant_traitor.dm
Fixes a runtime that happens when mindslave implanting a non-viable target, such as ones with mindshield a implant. 
Issue is that since the parent call of `implant()` happened so soon, `removed()` needed to be called, but that resulted in the runtime below, due to `mindslave_UID` not being set yet. However the parent call does not need to happen immediately so I've moved it to the end of the proc.
Fixes:
```
[2022-11-28T03:28:45] Runtime in implant_traitor.dm,48: Cannot execute null.remove antag datum().
proc name: removed (/obj/item/implant/traitor/removed)
usr: Lorde Buttersworth (CKEY) (/mob/living/carbon/human)
usr.loc: The floor (121,131,2) (/turf/simulated/floor/wood)
src: Mindslave Bio-chip (/obj/item/implant/traitor)
src.loc: null
call stack:
Mindslave Bio-chip …
```
> Fixes a runtime when using a mindslave implant

- code/modules/mob/living/stat_states.dm
You cant hear SFX when you asleep
realism. makes little sense to hear sound effects but not people talking
knocked myself out, blew myself up, no sounds. could hear sounds when I woke up.
:cl:
fix: you can no longer hear sounds when you are asleep.
/:cl:
> You are now deaf when unconscious

- code/modules/projectiles/projectile/special.dm
Plasma cutters and advanced plasma cutters will no longer delimb when in a pressurized area, but when they are in low pressure such as lavaland or space they will still be able to delimb
Plasma cutters are a great mining tool and a nice reference to the dead space series with their ability to cut off limbs like, unfortunately this means people could use them to delimb and even decapitate people extremely quickly, a single 357 shot followed up with a plasma cutter shot will most of the time instantly delimb. Seeing as it is mainly intended for lavaland by making it only work in low pressures like lavaland we get to keep the neat reference without harming the balance. It also means it can be used in space to decapitate otherwise nearly impossible to catch changelings.
Booted up private …
> Plasma cutter only delimbs in low pressure

- code/modules/clothing/suits/miscellaneous.dm
Adds guns, combat knife and contractor baton to the list of items which jacket can hold in the storage slot.
It would make sense to be able to hold thise things, especially considering it can be purchased for one tc. Its heavily weaker than basic security jacket anyway.
Started the game, put the items in the slot.
:cl:
tweak: Adds guns, contractor baton and combat knife to the list of the items syndicate jacket can hold.
/:cl:
> Suspicious jacket suit storage slot 

- code/modules/events/event_container.dm
It removes the space dust event from the game. Much of the code is still left in because Meaty ores event relies on it. For that reason this PR only removes it from rotation
The space dust event didn't work to begin with and I only learned that it existed because I saw the event trigger in the debug log. While I could instead try to fix it I think we don't need more variants of meteors considering we already have major and moderate ones as well as meaty ores. By removing space dust it means that it will no longer take up event rolls and do nothing, meaning actual events can trigger instead.
Wasn't really able to test it, if there are any tests you would like me to put it through I will gladly. It did however compile fine
:cl:
del:  Space dust event from rotation
/:cl:
> Removes space dust from event table

- _maps/map_files/cyberiad/cyberiad.dmm
Changed the near space area on top of the SM waste injector to engineering area.
Changed the space area on top the ai sat waste injector to ai sat area.
This makes it so that they properly work at round start.
This went unreported for quite a while. This caused the gas in the sm loop to slowly clog probably leading to a few delamns. This was likely a map edit oversight.
Now its back to how it used to be and engineering can rest a bit easy knowing that they have one less issue to worry about.
Load ol cyberiad and see if the reported injectors work.
They do not.
Try editing some vars.
Did not work.
Try changing the area.
Now it works!
Huzzah
:cl:
fix: Fixed the sm and ai sat waste injector not working at round start
/:cl:
> Fixes the sm and ai sat injector not working at round start on box

- code/game/gamemodes/cult/cult_items.dm
Fixes #19823
Makes cult bola throwing check if you're a cultist before throwing, and ensnare you, instead of being able to hit someone next to you before getting you for being non-cult.
Non cultist being able to use cult bolas, very bad.
Being able to break bola code and bola 2 people with one bola, even worst
Tested on master branch, bug happens.
Tested on private w/ fixes, bug doesn't happen. Cultists can still throw bolas just fine.
:cl:
fix: Fixes cult bola-throwing by non-cultists ensnaring others alongside themselves.
/:cl:
> Fixes cult-bola throwing by non-cultists

- code/modules/surgery/robotics.dm
This PR adds a new surgery option for IPCs and IRCs called "Reconfigure Identity" which allows them to have their names changed, similar to how it's done for organics. The only difference is that this operation allows the surgeon/roboticist to input a fully custom name, which I justify by the fact that they don't have the complexities of organic faces.
The surgery follows the standard steps, and uses a multitool for the renaming step, similar to Cybernetic Appearance Customization. If for whatever reason the player inputs an invalid name, it will tell them and force them to redo the step. Once a name has been chosen, the player then selects a gender which completes the surgery step.
I've played a lot of roboticist and this has always been one of the glaring holes in the functionality of …
> Adds IPC plastic surgery

- code/game/gamemodes/cult/cult_items.dm
- code/game/objects/structures/window.dm
Title
Fixes #19700
Ugly sprites of windows after being moved is bad
And window being force pushed to another tile but being anchored makes little to no sense
Above image, made drake, walked at walls, worked
Also tried to move windows normally with a human, debuilt/unanchor just to be sure I didn't bork anything, didn't break anything.
Looked very hard at changed files, this time this doesn't either do my last fix commit (again) nor deletes the entire cult items file (That was a newbie oopsie)
:cl:
fix:  Fixes pushed-window sprites not updating/staying anchored
/:cl:
> Fixes Window-Pushing not updating sprites / staying anchored (doesn't delete cult this time)

- code/game/machinery/computer/robot.dm
If the round is over, the borg console no longer responds to commands, preventing all borgs being blown at round end because RD / AI / Captain felt like it.
People should (mostly) enjoy round end, all of one job being blown to a brain sucks just because someone felt like it. (also looking at you monkey all button.
Confirmed button did not work after round ended
:cl:
tweak: You can no longer blow up all borgs when shuttle docks at cc.
/:cl:
> Borgs can no longer be locked / blown at round end

- code/game/objects/items/decorations.dm
Fixes #19843
Makes the craftable large decoration statues such as the metal angel statue anchorable in place.
A very minor QoL feature that prevents other players from pushing around your display pieces.
Spawn in statues.
Pull them around.
Wrench em in place.
Can't pull them around anymore.
Unwrench em.
Pull them around some more.
:cl:
tweak: Tweaked the large decor statues so that they can be anchored in place with a wrench
/:cl:
> Anchorable Large Decor Statues

- code/datums/mind.dm
Gives admin-granted traitors their objectives and uplink automatically. Closes #19847
Less tedium for admins. Consistency with other antags like vampires and clings who get their objectives automatically. I thought the same should be done for the uplink as well since I don't see a reason to make a traitor without an uplink.
:cl:
tweak: Gives admin-granted traitors their objectives and uplink automatically
/:cl:
> Gives admin-granted traitors their objectives and uplink automatically

- code/modules/shuttle/shuttle.dm
Turns shuttle gibbing on to deal with those pesky clings in an emergency.
Alternative to https://github.com/ParadiseSS13/Paradise/pull/19878
Re-enables shuttle gibbing, if I remember correctly shuttle gibbing was disabled a very long time ago and was one of those changes that I just never agreed with. There are plenty of valid reasons why you'd need to gib someone and your only option is a shuttle as risky as it is to gib someone with a shuttle.
I think this is a better alternative than making the cremator indestructible.
Speaking from a more logical standpoint I think having a shuttle bluespace warp onto you is grounds for immediately exploding into a fine mist of blood.
[Unknown 2022.12.08-07.45 1-1.webm](https://user-images.githubusercontent.com/92271472/206450645-9c450f97-d4f2-495d-bbc …
> Re-enables shuttle gibbing

- code/modules/power/solar.dm
Puts the matrix transform on the overlay instead of the object itself.
Fixes #19893
Set up solars. Did both partial and fully to see the differences.
:cl:
fix: Solar panels rotate independently from their base.
/:cl:
> Solar panel rotation applies to the panel only and not the base itself

- code/__DEFINES/mobs.dm
- code/modules/mob/living/carbon/update_icons.dm
Fixes the code handling laying offset which was erroneously doubling itself from the base offset of -6 to -12. This is because TG uses a `base_pixel_y ` whereas on Paradise we don't and math just didn't work as it was.
The block of code in question on TG would normally have `pixel_y = base_pixel_y` and then add
`final_pixel_y(= pixel_y)  = base_pixel_y + PIXEL_Y_OFFSET_LYING(defined as -6)`  to add up to -6.
On Paradise this was `pixel_y = pixel_y` and then add `final_pixel_y(= pixel_y) = pixel_y + PIXEL_Y_OFFSET_LYING(defined as -6)` meaning it was duplicating itself and adding the same number twice leaving us with -12 where it should be -6.
This is my understanding of this bug, I kind of have a shakey knowledge of DM in the first place but everything seems to be working now.
It's a bug …
> Resting offset fix

- code/__DEFINES/icon_smoothing.dm
- code/__HELPERS/icon_smoothing.dm
- code/game/atoms.dm
Fixes the constant debug messages we keep getting about things trying to smooth in nullspace.
```
[2022-12-10T21:43:47] Runtime in stacktrace.dm,14: /obj/structure/window/full/reinforced called smooth_icon() without being on a z-level
[2022-12-10T21:43:47]   proc name: stack trace (/datum/proc/stack_trace)
[2022-12-10T21:43:47]   src: the reinforced window (/obj/structure/window/full/reinforced)
[2022-12-10T21:43:47]   src.loc: null
[2022-12-10T21:43:47]   call stack:
[2022-12-10T21:43:47]   the reinforced window (/obj/structure/window/full/reinforced): stack trace("/obj/structure/window/full/rei...")
[2022-12-10T21:43:47]   the reinforced window (/obj/structure/window/full/reinforced): smooth icon()
[2022-12-10T21:43:47]   the reinforced window (/obj/structure/window/full/reinforced): …
```
> Fixes a "problem" with smoothing

- code/controllers/subsystem/jobs.dm
Adds in a null check for jobs in the `CreateMoneyAccount` proc. to prevent a runtime 
Fixes #19801 
Built without errors, shouldn't have to test this since it won't effect logic
no player facing changes, no CL
> Fixes a runtime with ERTs and Money Accounts

- code/game/turfs/simulated/floor/plating.dm
Exactly as on the tin. If you're on harm intent you will neither attempt to unfasten plating or repair it. Works fine on other intents.
Sometimes, you want to use the welder to absolutely weld the shit out of something, but there's damaged plating in the area and suddenly you have no eyes left because clicking is difficult. This change lets people use welders as weapons in areas that have damaged plating without subjecting themselves to sudden-onset blindness and bright white flashes.
Blew a hole in the station, tried to aggressively weld the damaged plating, nothing happened. Tried to gently weld the damaged plating, success.
:cl:
tweak: You will no longer weld plating if you are on harm intent
/:cl:
> Makes it so you no longer weld plating if you're on harm intent

- code/game/objects/items/stacks/sheets/glass.dm
- code/game/objects/items/stacks/sheets/mineral.dm
- code/game/objects/items/stacks/sheets/sheet_types.dm
Adds full 50 sized stacks of the following materials to the admin spawn menu and to mappers:
- Reinforced glass
- Sandstone
- Uranium
- Gold
- Silver
- Adamantine
- Plasteel
- Plasmaglass
- Reinforced plasmaglass
- Titanium glass
- Plastitanium glass
- Plastitanium
Removes enruranium sheets, since they don't have sprites and aren't used anywhere.
Being able to spawn stacks of fifty instead of having to varedit or click 50 times is nice.
Spawned stacks of 50 for every material, looked at them.
This doesn't affect players.
> Creates full stacks of all sheets and minerals

- code/modules/antagonists/changeling/datum_changeling.dm
title + clings start with 75 chems instead of 20.
50 seconds to refill your chem tank vs 150 is a major buff to how quickly changelings can get back up on their feet. cuts down on the time a player needs to stand around in a locker in order to actually play the game. 
the starting at 75 chems doesn't really change balance but it does make debugging and testing changes to cling abilities. 
I VVed it on prod
:cl:
tweak: changelings chem regen has been tripled. they now start with 75 chems instead of 20.
/:cl:
> triples changeling chemical regen

- code/game/objects/structures/mineral_doors.dm
Removes the last_bumped check from mineral doors, meaning you can now open them even if you bumped into another, unrelated door within the last 3 seconds.
Previously this would check whether last_bumped was over 3 seconds. On the user. Which keeps track of when you last ran into a door. Any door. Meaning you couldn't open/close a mineral door like a wooden door for 3 seconds after you opened any other door.
This seemed unnecessary.
Run into an airlock.
Run into a wooden door within 3 seconds of running into an airlock.
The wooden door opens.
:cl:
fix: Opening/closing mineral doors is now more consistent.
/:cl:
> Makes opening/closing mineral doors more consistent.

- code/game/machinery/cryopod.dm
Fixes the "Drop all items" button on the cryogenic oversight console
Buttons should work
:cl:
fix: Fixed the "Drop all items" button on the cryogenic oversight console
/:cl:
> Cryogenic oversight console "Drop all items" fix

- code/modules/clothing/masks/miscellaneous.dm
Changes the time it takes to resist out of a tape gag from 15 to 30 seconds
Also refactors all masks to use seconds instead of deciseconds for resist time.
Having to move people every 10 seconds whilst feeding on them as a vampire is extremely tedious, and actively hinders roleplay. Now vampires can try making the situation a little more interesting by making small talk to their victim instead of having to constantly worry about scream spam. 
Also helps other antagonists and security get some peace and quiet, if they desire it. 
Note that this only helps people who take the time and planning effort acquire tape. Other kidnapping victims can continue to scream away.
Performed and timed various types of self bondage.
:cl:
tweak: Tape gags now take longer to resist out of
/:cl:
> Tape gags take longer to resist out of

- code/__HELPERS/icons.dm
Reverts ParadiseSS13/Paradise#13190
If we are removing useless procs this can go. It aint used anywhere, plus its not even right. It reads RGG instead of RGB, plus we have `rgb2hsl`.
> Revert "Adds a helper proc to calculate luminance"

- code/game/objects/items/weapons/storage/backpack.dm
Fixes https://github.com/ParadiseSS13/Paradise/issues/19983
Bluespace zipping bad
Tried to do the thing using a camera
:cl:
fix: Fixed being able to zip/unzip duffels remotely using camera console
/:cl:
> Fixes remotely zipping/unzipping duffelbags with camera consoles

- code/game/gamemodes/nuclear/nuclearbomb.dm
- code/modules/admin/verbs/deathsquad.dm
Deathsquad will now spawn properly, with the first one chosen actually being the NAD carrier. Players will now actually get to choose organic or cyborg deathsquad (I broke that too...). Unrestricted NADs have been refactored so admins can delete them without the NAD respawning as a normal NAD. 
Unrestricted NADs will now be deleted instead of transforming into a normal NAD. Better not lose it...
Fixes #19866
Spawned deathsquad with 2 accounts, the NAD holder will now always be the first chosen, and other players can now choose to play cyborgs. Unrestricted NADs will now be deleted instead
Nothing player facing, only admin facing.
> Fixes some issues with Deathsquad spawning

- code/modules/mob/living/carbon/carbon.dm
Fixes #19908. Before, resisting multiple times whilst tape gagged would cause the chat message and sound to be played multiple times as well. Now, it only does it once.
Chat and your ears being spammed with tape gags being ripped off bad.
Tested resisting out of tape gags normally, whilst cuffed, whilst bucklecuffed.
fix: Tape gags no longer get ripped off multiple times
/:cl:
> Fixes #19908 - Tape gags no longer get ripped off repeatedly

- code/datums/spells/rathens.dm
- code/game/gamemodes/wizard/spellbook.dm
Readds the spell Rathen's Secret to the spellbook, a 1-cost spell with a 50 second cooldown that forcibly removes the appendixes of anyone near you. If they have no appendix (presumably because you've already used this spell on them), they suffer increased damage from the spell and a longer stun. It also seems to come with a semi-infrequent chance to remove limbs, what fun.
The spell was initially cut from the Wizard's spellbook in https://github.com/ParadiseSS13/Paradise/pull/10364, but from what I can tell in this PR Rathen's was intended to be reworked to just not be so malodorous instead of being removed from the Wizard's spellbook simultaneously. Thus, let's just re-add it so Wizards can have their funny appendicectomy spell.
Eight skrells lost their appendixes (it IS appendixes when …
> Re-adds Rathen's Secret to the Spellbook

- code/modules/food_and_drinks/food/foods/bread.dm
- code/modules/food_and_drinks/food/foods/ingredients.dm
- code/modules/food_and_drinks/food/foods/side_dishes.dm
Fixes two descriptions in the bread file (also moves one thing around and removes an extra blank line)
descriptions should exist
Compiled, ran, really shouldn't have compiled because these aren't valid icon states
:cl:
spellcheck: bread and tofu bread now have a description as intended
/:cl:
> Fixes descriptions on two food items

- code/game/gamemodes/blob/blobs/core.dm
Reduces the blob core "split" spawn time to 10 seconds (initial spawns from mice and such aren't affected)
Long wait times are all well and good provided you're not in active combat, blobs will almost always be in active combat, so the extra wait time comes up /a lot/
A 10 second wait time is more than enough time to sign up and play, 30 seconds just screws over the blob
Compiled ran, things worked fine
:cl:
tweak: blob split cores now only take 10 seconds to accept a candidate 
/:cl:
> Reduces blobs "split" spawn time 

- code/game/turfs/simulated/floor/plating.dm
When you click on plating with your smuggler satchel in active hand, you place the satchel on the plating ready to be covered up.
I had a frustrating round last shift that lead to me mhelping about how to put a smuggler satchel down. I was unaware you had to drop it on the tile then cover it up.
That seemed counterintuitive, so this change hopefully makes it behave in a way that makes more sense for users.
Placed satchels.
:cl:
tweak: When you click on plating with a smuggler satchel, you now place it there
/:cl:
> When you click on plating with a smuggler satchel, you place it there

- code/modules/mob/living/carbon/brain/MMI.dm
- code/modules/mob/living/carbon/brain/robotic_brain.dm
The MMI radio actions were calling `ApplyIcon` directly instead of `UpdateButtonIcon`, which would cause runtimes as they weren't otherwise passing the button. This brings it in line with other actions.
`ApplyIcon` is tweaked slightly so it only passes the object's icon and icon state, and lets the parent handle the rest.
Fixes #19933. Nothing playerfacing otherwise.
Debrained someone, stuffed them into an MMI, installed a radio. Did the reverse where the radio was installed first then the brain.
N/A
> Clean up MMI radio actions to call the right procs

- code/game/machinery/rechargestation.dm
Cyborg recharge station no longer continues to work after its broken/without power.
Cyborg recharge station now updates its icon properly and makes use of occupied/without power icon (borgcharger2).
Fixes https://github.com/ParadiseSS13/Paradise/issues/19964
- Tested the recharge station while inside, outside, with and without power.
:cl:
fix: Cyborg recharge station icons have been fixed
fix: Cyborg recharge station no longer works while unpowered
/:cl:
> Cyborg recharge station no longer works while unpowered

- code/game/mecha/equipment/tools/medical_tools.dm
fixes the below runtime
```
Runtime in medical_tools.dm,216: Cannot execute null.has charge().
proc name: process (/obj/item/mecha_parts/mecha_equipment/medical/sleeper/process)
src: the mounted sleeper (/obj/item/mecha_parts/mecha_equipment/medical/sleeper)
src.loc: the floor (111,95,2) (/turf/simulated/floor/plasteel)
call stack:
the mounted sleeper (/obj/item/mecha_parts/mecha_equipment/medical/sleeper): process(20)
Objects (/datum/controller/subsystem/processing/obj): fire(0)
Objects (/datum/controller/subsystem/processing/obj): ignite(0)
Master (/datum/controller/master): RunQueue()
Master (/datum/controller/master): Loop()
Master (/datum/controller/master): StartProcessing(0)
```
runtimes bad
-1 OXY and checking SSobj debug
NPFC
> Fixes a mecha sleeper runtime

- code/game/objects/items/stacks/sheets/mineral.dm
build time has been increased (0 seconds - > 2 seconds) for all mineral doors.
Big doors shouldnt be instantaneous to build and wood variation already has a build time of 2 SECONDS.
- Made a bunch of mineral doors with sheets
:cl:
tweak: Mineral doors now takes 2 seconds to build
/:cl:
> Mineral doors now takes 2 seconds to build

- code/__DEFINES/MC.dm
- code/__DEFINES/_globals.dm
- code/__DEFINES/_protection.dm
- code/__DEFINES/cult.dm
- code/__DEFINES/dcs/signals.dm
- code/__DEFINES/js.dm
- code/__DEFINES/misc.dm
- code/__DEFINES/qdel.dm
- code/__DEFINES/subsystems.dm
- code/__HELPERS/game.dm
- code/__HELPERS/icons.dm
- code/__HELPERS/matrices.dm
- code/__HELPERS/text.dm
- code/__HELPERS/time.dm
- code/__HELPERS/unsorted.dm
- code/_globalvars/lists/reagents.dm
- code/_globalvars/misc.dm
- code/_onclick/ai.dm
- code/_onclick/hud/alert.dm
- code/_onclick/hud/parallax.dm
This PR fixes a subset of leading whitespace issues surfaced by the CI checks added in #19875.
The directories affected by this PR are:
- `code/__DEFINES/...`
- `code/_globalvars/...`
- `code/_onclick/...`
There should be _no changes in this PR other than the following_:
1. The removal of leading spaces, or the replacement of leading spaces with tabs.
2. The addition of an asterix prefix for lines of comments which previously had leading whitespace.
Even if other cleanups were possible, or comment alignment/etc could be fixed, these actions were not taken, in order to keep the PR as small and as straightforward to review as possible.
> Whitespace cleanup part 1.

- code/datums/action.dm
- code/game/turfs/simulated/walls.dm
- code/modules/mob/living/silicon/robot/drone/drone_items.dm
- code/modules/mob/living/silicon/robot/inventory.dm
- code/modules/mob/living/silicon/robot/robot.dm
- code/modules/mob/living/silicon/robot/robot_modules.dm
- code/modules/surgery/surgery.dm
Minorly refactors the "gripper" cyborg item 
moves the "drop gripped item" from the drone tab to an action button
mediborgs no longer get the above verb
only thing the drone tab is used for, used with things that aren't drones so it's silly
mediborgs shouldn't get a verb they can't use'
buttons good verbs bad
compiled and did things
:cl:
tweak: "drop gripped item" is now an action button
fix: Mediborgs no longer have an unusable verb
/:cl:
> Minorly refactors the "gripper" cyborg item and moves the "drop gripped item" to an action button

- code/__DEFINES/is_helpers.dm
- code/game/objects/structures/table_frames.dm
adds a `isstack` define for easily checking if an obj is a stack or not
fixes all items being passed on to the entire proc rather than just stacks
runtimes bad
NPFC
> Fixes a table runtime

- code/game/objects/structures/misc.dm
Allows people with event permissions to set outfits on ghost clone respawners, which will be equipped when the person spawns.
This allows for admins to equip a large amount of people for stuff like fun events, or general shenanigans with ghosts.
Changed the outfit, spawned in as ghost. Tried spawning as naked and it spawned me as naked.
Just admin-side stuff
> Allows the Long-Distance Cloning Machine to use Outfits

- code/modules/clothing/spacesuits/plasmamen.dm
Tweaks the armor values for Security Envirohelms so that they're up to snuff with the armor that all other species are able to gain from their Security gear.     
Plasmamen cannot wear armored headgear without combustion and death, so they're limited to only their Envirohelmet.  However the Helmets that Plasmamen were wearing are much weaker than the standard Beret and Helmet non-Plasmaman Officers can wear at all times.  Kind of bad for someone who is going to be dealing with Station-Wide Threats, even more so for the Warden and Head of Security roles given they're a more valuable target for many Antagonists.  Turns out that even the basic Plasmaman Sec. Envirohelm had only 5% melee armor compared to a regular Redman's 25% from a basic helmet.  
I whack Plasmeme on the head, he take a …
> Matches Sec. Plasmaman Helmets to Standard Sec. Headgear

- _maps/map_files/Delta/delta.dmm
- _maps/map_files/MetaStation/MetaStation.dmm
Fixes #19815
Adds the missing pda server monitor key note to the RD office for both delta and meta.
The RD is supposed to have access to this.
The key being missing likely was an oversight.
**DELTA:**
**META:**
Check if the key is indeed missing.
It is.
Add it to both delta and meta RD office.
Check both maps if its there.
Now it is! (see images)
:cl:
fix: Fixed the lack of pda server keys in the RD office on delta and meta
/:cl:
> Adds the missing pda server key to the rd office in delta and meta

- code/modules/antagonists/vampire/vamp_datum.dm
Vampires will no longer suffer any ill effects if they are in the chapel area as long as they didn't obtain any usable blood.
Getting attention from security before you obtained any usable blood will result in a time sentence (or it's lack, depending what did you do to get security attention in the first place) instead of round ending permabrig while you are still locked to only having two abilities (and helps if security is mass testing people in the chapel because another vampire tipped them off about their presence on the station)
Checked what happens to vampires at specific stages when exposed to chapel and space: vampire with no blood drained, vampire with some blood drained, vampire with specialization, full power vampire and all burned up in space, while only vampire with some …
> Prevents vampires who didn't drain anyone from being tested in the chapel

- code/modules/economy/economy_machinery/atm.dm
Fixes this runtime
```
Runtime in _component.dm,220: Cannot read null.comp_lookup
proc name: UnregisterSignal (/datum/proc/UnregisterSignal)
usr: *REDACTED USER*
usr.loc: The floor (143,130,2) (/turf/simulated/floor/plasteel)
src: Nanotrasen automatic teller ma... (/obj/machinery/economy/atm)
```
It was passing a null value onto clear_account if you just ejected your ID without logging in.
added a sanity check to prevent this
runtimes bad
let the GC debugger smash it's head into the wall for 15 minutes and used an excessive amount of breakpoints
NPFC
> Fixes an ATM runtime 

- code/modules/client/preference/preferences.dm
Speeds up opening the keybinds tab of the prefs menu, taking it from ~270ms to ~20ms, purely by moving the string concat operations to a list join. 
---
One person's prefs menu using the full time allotment of over 5 ticks is disgusting.
Opened the prefs menu.
add: Sped up the prefs menu
/:cl:
> Speeds up the preferences menu by 10x. No that is not hyperbole.

- code/modules/recycling/disposal.dm
- code/modules/recycling/sortingmachinery.dm
Disposal chutes are no longer capitalized, an extra period has been removed from the "rim shot" line
Disposals chutes no longer try to transfer Qdeleted items
Runtimes bad
Improper grammar bad
Threw items like snowballs and wine bottles into disposals 
:cl:
spellcheck: disposal chutes are no longer capitalized 
/:cl:
> Fixes a disposals runtime and cleans up a touch of disposals grammar 

- code/game/objects/items/weapons/storage/backpack.dm
fixes #20015 
they know
It worked
None of us are safe
:cl:
fix: observers can now view the contents of zipped dufflebags
/:cl:
> observers can now view the contents of zipped duffles

- code/modules/surgery/organs/augments_arms.dm
Attacks the loc of hitby if it is an item, since that is the person with the item, vs trying to hit the item directly
Thrown items should not longer duplicate on embed from vortex arm reflection, as its throwspeed was lowered to a reasonable value, as well as slightly increased callback to ensure no issues happen.
Bugs are bad. Sorry for not catching in testing earlier.
Tested to ensure that humans would get hit by vortex arm on perfect parry
Tested to ensure thrown items no longer duplicate on embed from the arm
:cl:
fix: Vortex arm now melee hits humans on parry, and no longer freaks out when parrying items that embed on target.
/:cl:
> Fixes some vortex arm bugs that were not caught

- code/modules/antagonists/changeling/powers/shriek.dm
Increases the range of cling emp, from 2, 4, to 3, 5
I had pictures to go with this, but I fell asleep before posting the pr a month ago and forgot about it.
It makes the EMP actually viable at being able to lower the charge at guns, rather than having to be beside the person to fully drain it, now you can be 2 tiles away, with a 50/50 for 3, to fully drain a gun.
Confirmed numbers are right.
:cl:
tweak: Increased changeling emp size from 2, 4 to 3, 5
/:cl:
> Buffs cling emp from 2, 4 to 3, 5

- code/game/objects/structures/tables_racks.dm
Allows you to place off welders on reinforced tables, but still keeps the message about it needing to be on to weld the table.
Its weird needing to toss them onto or over tables while theyre off.
Tested on local server, could place it on the table and still deconstruct it if the welder is on
:cl:
fix: Disabled welders can be put on reinforced tables
/:cl:
> Allows you to place off welders on reinforced tables

- code/game/objects/structures/tables_racks.dm
Uses the correct path for the custom reinforced glass table behaviour.
Makes the shoved behaviour work like regular tables, not glass ones.
Glass tables should be deconstructable, and should cause shove stun
:cl:
fix: Fixed not being able to deconstruct reinforced glass tables
/:cl:
> Fixes epic fail with reinforced glass tables

- code/game/gamemodes/blob/powers.dm
- code/game/gamemodes/blob/theblob.dm
Blobs can expand diagonally for 10 points.
If a blob is northeast, it try to spread horizontally or vertically for 5 points as normal. If this fails, only 5 points is spent.
If it succeeds, it consumes another 5 points, and now spreads to that originally diagonal tile.
This will not reliably work in space, and naturally bodies in the way will block spreading (but will be attacked)
Being able to attack blob but blob not being able to attack is silly. It makes no sense realistically, only makes "sense" in a land of squares.
This PR lets blob attack diagonally IF the path is not blocked linearly, so no attacks that don't make sense, and without lettting blob cover area diagonally for only 5 points, which would be rapid spreading
Lots of testing to make sure diagonal spread works as intended, …
> Blob can now expand diagonally by moving twice linearly in one move for 10 points.

- code/game/objects/items/stacks/sheets/leather.dm
- code/modules/mob/living/silicon/robot/robot.dm
- code/modules/mob/living/silicon/robot/robot_modules.dm
- code/modules/mob/living/silicon/silicon.dm
- code/modules/mob/living/silicon/silicon_defense.dm
Silicons now have armor.
By default, it is zero across the board.
Mining borgs now have 20% melee armor and nothing else.
This maxes at 60% armor after 4 plates.
This armor is lost on module reset.
Considering we are on lavaland, and mining borgs kinda don't have armor when everything hits like a truck, and while miners get meds and legion cores, and all mining cyborgs get is the worlds slowest self repair system, maybe they should have melee armor.
So this pr does it.
Yes, this makes mining cyborgs *slightly* more robust for melee attacks for say, malf AI.
However, they usually die by lasers or flash into baton, which is perma stun, so this will not be an issue.
Theoretically one could now give gamma borgs armor equivlent to ERT armor, but that is out of this prs scope, and honestly …
> Mining borgs now have melee armor.

- code/game/turfs/turf.dm
- code/modules/fish/fishtank.dm
Cleans up some remnant AStar procs that weren't removed in the JPS PR. `AdjacentTurfs` is reworked into a more general proc that returns a list of turfs.
Outside of cleaning up old procs, having a proc that returns either all adjacent turfs, cardinal or all dirs, with or without density is useful.
Messed around with a fishtank. Also did some test with possible future PR prospects.
N/A
> Clean up of AStar procs, rework one into an independant adjacent turf proc

- code/game/jobs/job/support.dm
Gives the bartender an EFTPOS scanner to have the option of charging for drinks.
Payed drinks > Free drinks, MAKE THAT MONEY PLAYAH
*In all seriousness, it helps people use the economy more and its part of SoP. Seems nobody ever gave them the one tool that makes charging people a fucking breeze.*
booted server, charged myself 0 credits, that stonks baby
:cl:
tweak: Bartenders spawn with an EFTPOS on roundstart now
/:cl:
> Bartenders Spawn with an EFTPOS

- code/modules/mining/fulton.dm
fixes #20020 
Hell is not a great place to be.
Playing the game is generally preferred over not playing the game
Got acquainted with the Brazilian wildlife, chat message properly showed up and I got set down in the correct location
:cl:
fix: fixes fultons sending you into an immobile state if the beacon selected was removed
/:cl:
> Fixes fultons being able to send you into a nullspace like state

- code/game/objects/items/stacks/sheets/glass.dm
- code/game/objects/items/stacks/sheets/mineral.dm
- code/game/objects/items/stacks/sheets/sheet_types.dm
- code/modules/research/designs/smelting_designs.dm
Plasmaglass and plasmarglass now returns the correct amount of materials when placed into the ORM.
Standardizes all sheets to use MINERAL_MATERIAL_AMOUNT.
Fixes https://github.com/ParadiseSS13/Paradise/issues/20076
- Spawned plasmaglass and place it into the ORM, it gave the correct amount.
:cl:
fix: Plasmaglass and plasmarglass now returns the correct amount of materials when placed into the ORM
/:cl:
> Fix #20076 Plasmaglass and plasmarglass now returns the correct amount of materials

- _maps/map_files/generic/centcomm.dmm
Adds Engineering Storage to the Special Operations area of Central Command, locked behind admin access blast doors.
Engineering Storage contains the following equipment:
- 12 stacks of metal
- 12 stacks of glass
- 6 stacks of plasteel
- 6 Combat RCDs, along with 30 spare cartridges
- 6 Bluespace rapid pipe dispensers
- 6 full advanced toolbelts
- 6 bluespace power cells
- 12 metal foam grenades
- 3 upgraded S.U.P.E.R.P.A.C.M.A.N.-type Portable Generators
- 60 uranium sheets to power them with
- 2 floodlights
- 1 Engi-Vend
- 1 box of construction permits
This replaces the Diplomatic Office, as it was practically never used, and a functionally identical Administrative Office is located 20 tiles to the south. It also cuts off one of the entrances to the Gamma armory, but that door was also …
> Adds Engineering Storage to Special Operations

- code/modules/research/rdconsole.dm
The upgrade coefficient now multiplies the reagent amount properly when checking if the protolathe has enough reagents.
Fixes https://github.com/ParadiseSS13/Paradise/issues/20049
- Inserted all materials necessary for the Vortex arm implant
- Upgrade the protolathe (4 rating)
- Could start the printing with 20 blood instead of 50
:cl:
fix: Upgraded protolathe no longer has issues with reagent costs
/:cl:
> Fix #20049 Upgraded protolathe no longer has issues with reagent costs

- code/datums/spells/wizard.dm
base cooldown of forcewall up to 15 seconds from 10
Greater forcewall, which is now normal force wall, offers a bit too much protection for its cooldown. One could have 3 groups of 3 forcewalls up at once. Effectively being able to permamently 2 or even 3 doors to one room fully sealed, or an area of maints. Practically untouchable, for 1 point.
Now, one can only have 2 groups of 3 forcewalls at base price. Still strong, but a noticable reduction to control.
N/A, just tweaking the numbers
:cl:
tweak: Wizard forcewall now has a 15 second cooldown vs 10 second cooldown
/:cl:
> Wizard forcewall now has a 15 second cooldown vs 10 second

- _maps/map_files/MetaStation/MetaStation.dmm
- _maps/map_files/RandomRuins/SpaceRuins/intactemptyship.dmm
- _maps/map_files/RandomRuins/SpaceRuins/ussp.dmm
- _maps/map_files/RandomZLevels/example.dmm
- _maps/map_files/cyberiad/cyberiad.dmm
- _maps/map_files/generic/Lavaland.dmm
- code/game/machinery/vendors/generic_vendors.dm
Gives a cost to Artvend cable coils.
Tweaks Vendomat amounts slightly (new standard is 4, increased wirecutter amount to 2) and paid version has been given to the ones located in public areas.
Theres no reason to acquire cables from the tools vendor or cargo since Artvend has big amounts of it for free and in close proximity.
It makes sense that Vendomat should cost money in public areas just like how it is with Tool Vendors.
- Compiled and looked into the new prices and amounts.
:cl:
tweak: Artvend cable coil now has a price
tweak: Vendomat now has a paid version and amounts have been tweaked
/:cl:
> Tweaks to Vendomat and Artvend

- code/modules/admin/verbs/one_click_antag.dm
Fixes the thunderdome adminsecret
Sets people spawned via the thunderdome to an offstation role
Thunderdome no longer uses an alert, uses a ghostpoll now 
Working code is a good thing, the thunderdome is pretty cool
Compiled and ran with two clients 
:cl:
fix: [ADMIN] The thunderdome secret now functions 
/:cl:
> Fixes the Thunderdome

- code/game/objects/items/weapons/implants/implant_explosive.dm
- code/modules/mob/living/carbon/human/death.dm
Re-upload of #19626 which GitHub can't tell is open or closed.
This PR unequips human types on gib, tossing their equipment around randomly in the same way that their organs are. This adds to the list of equipment that may possibly survive an explosion, and ensures indestructible items are not wiped out of reality on gib.
This has several consequences and, depending on how you look at it, balance implications.
1. When a human type is gibbed, their internal and external organs are removed, and 'thrown' about in the area of the gib. This process does not consider certain things. The primary issue here is that objects, even indestructible ones, are simply deleted on gib when the human entity itself is deleted. Their damage resistance is completely ignored. This is a problem.
2. Typically, …
> Unequip gib victims earlier in the process.

- code/modules/client/client_procs.dm
- goon/browserassets/css/browserOutput-dark.css
Updates darkmodes theming to match Bays which is overall a better version of darkmode
Darker bits are a little darker especially up in the status panel, themes better with the chatbox now.
All chat colours have remained unchanged except for the default chat colour which includes say and the announcement colour. Basically, if it was bright ass #FFFFFF white before it's gone and now replaced with a white blue, kind of like the same colour you have here on Github darkmode but a little bluer to compensate for it being on a darker background.
These changes are from Baystation.
Please for the love of all that is good in this codebase my eyes bleed every time I switch on darkmode and am flashbanged by a half white half dark chatbox. I want a darkmode, not an inverted colours mode.
:cl: Bmon, …
> Updates darkmodes theming to more closely match Bay

- code/modules/power/gravitygenerator.dm
The gravity generator irradiates itself a bit more, and irradiates allmobs in it's view (won't go through walls, or xray on a vampire that can see it), when turning off or on. Does not irradiate when just on normally.
It's supposed to be radioactive, it has signs and rad suit lockers for god sake. I don't want it SM level as people will cheese it, nor should it create work for the server for being radioactive passively. So we cheat and place radiation on people that can see it.
It probably should be more radiation, it's not really contaminating the person that much, but hey, it's a start.
Confirmed people actually get irradiated by the gravity generator now
:cl:
tweak: Gravity generator now irradiates people more reliably.
/:cl:
> Gravity generator is now more radioactive to people when turning on or off

- code/game/objects/items/weapons/mop.dm
- code/game/objects/structures/mop_bucket.dm
(might just refactor this whole thing but I'm too tired right now)
fixes #19466 
mops now can be placed in mopbuckets
I hate runtimes
:cl:
fix: mops can now be placed in mopbuckets
/:cl:
> fixes the mopbucket not accepting mops

- code/game/objects/items/weapons/storage/bags.dm
The portable seed extractor is now activated with an alt-shift-click instead of a verb/right-click. I've also added some additional feedback to make it easier to work with and feel better to use.
The portable seed extractor isn't always the best tool available, but when it is (such as for lavaland spawns) it's often crucial to be able to use it properly.
Doing a modified click (which is told on examine) is a lot easier than having to know there's a verb for it. It's also good to do away with another verb in general if we can.
Loaded in, tried using it with and without seeds
:cl:
tweak: The portable seed extractor is now activated with an alt-shift-click.
/:cl:
> Changes portable seed extractor to be alt-shift-clickable

- code/modules/client/preference/character.dm
A cane will be spawned in the right hand if you are lacking one foot on arrival.
Crewmembers without both legs do get a wheelchair upon arrival, those without one foot should get the same treatment, saving them the time and money from buying a cane at the vendor.
- Joined the round with characters without one of both their feets.
:cl:
tweak: Crewmembers missing one of their foot now spawns with a cane
/:cl:
> Crewmembers missing one of their foot now spawns with a cane

- code/game/machinery/doors/airlock_types.dm
Cult doors will no longer hard stun you, instead knocking you down as punishment for touching the door (as a non cultist).
Hardstuns are something Paradise has been moving away from in terms of design. Doors hardstunning you is a bit too punishing and while I do agree there should be some sort of consequence, I think a simple knockdown suffices. Not as painful, but still noticeable and not a position you wanna be in.
spawned door, ran in, knockdowned
:cl: Octus
tweak: Cult Doors no longer weaken, instead they simply knock you down.
/:cl:
> Tweaks the Hardstun (Weaken) from Cult Doors to a Knockdown

- code/modules/power/apc.dm
In pr #16192 I made it so malf AI did not lose points when it's apc was destroyed.
However, I was dumb, and presumably only tested it by deleting the APC. If I looked in the file more, or tested by attacking the apc, I would find out that when the apc is damaged to breaking (set_broken() gets called), Malf AI also loses points there.
As such, this pr removes the second check that should have been caught 
A: Finishing something a merged pr should have done:
B: The text from the last pr: 
After discussing with a maintainer, it was decided that malf AI should be tweaked to prevent a malf AI from gaining all its points from space built APCs. We are aware however, with the limited APCs on station and off station, so with this PR it is tweaked that if crew deconstructs APCs the malf AI has …
> Removes the part of apc losing malf points on apc deconstruction I missed

- code/game/jobs/departments.dm
- code/game/objects/items/weapons/cash.dm
- code/modules/supply/supply_console.dm
Fixes 
Partially Resolves. #19779 Adds alt roundstart job titles to department datums
Fixes #20093 Properly updates icons in money stack code
Fixes #19921 AI no longer runtimes when denying crates
Bugs bad
Compiled and ran on test server
- Alt-click transferred space cash and it updated properly
- Tried out a couple alt job role names on my ID and it showed correct dept accounts
- Denied a crate as the AI
:cl:
fix: Alt job titles can now properly access dept account on supply console
fix: Alt-click'ing money now properly updates the new stacks icon
fix: AI's can now properly deny cargo crates
/:cl:
> Fixes 3 Economy Bugs

- code/modules/surgery/organs/organ_external.dm
Sharp burn weapons have the same chance to disember as burn weapons, accounting for burn instead of brute, in the form of DROPLIMB_BURN
If a DROPLIMB_BURN is used on head, it changes to DROPLIMB_SHARP, as otherwise it would instantly delete the brain.
Sharp weapons that are burn being cutting edge is cool. Who doesn't want to turn someones arm into ash. Sharp does not have much of a point without being able to delimb, so burn weapons that are sharp (which are rare) could use this.
Confirmed burn weapons that were sharp delimbed
Confirm limbs got turned to ash, and heads got cut off.
:cl:
add: Burn weapons that are sharp can now delimb people.
/:cl:
> Sharp burn weapons can now disember

- _maps/map_files/RandomRuins/LavaRuins/lavaland_biodome_clown_planet.dmm
- _maps/map_files/cyberiad/cyberiad.dmm
- code/modules/mob/living/silicon/robot/robot.dm
- code/modules/recycling/disposal.dm
- code/modules/recycling/sortingmachinery.dm
Since disposals work off a list that starts off at 1, this adds some fail-safes for weird mapping issues and removes hacky tag handling.
Disposals is now mutually exclusive from the rest. Removing all destinations on a junction automatically sets it to Disposals, and adding another destination will remove it from the list.
The sort junction on the clown planet ruin is replaced with a regular junction as you can't tag yourself.
Fixes #20098
Mapped in odd sorting junctions, and checked their vars after init. Sent stuff through disposals from different devices (`flush()` handled tags differently between devices)
:cl:
tweak: Disposals is a mutually exclusive destination for sorting pipes
fix: Fixed disposals looping if a sorting pipe isn't set up properly
/:cl:
> Add fail-safes to disposal sort junctions, fix looping

- code/game/gamemodes/cult/cult.dm
Adds a check to see if the convertee is a simplemob, if they are they cannot be turned into a Cultist.  
Just like how Golems were added to the list of non-convertables, simplemobs like Slimes were on it too.  I do not know what happened to break it or disable that, but this should fix it.  
It's considered not intended by many Admins and often will end up with the mobs being deleted, and while I'd say you haven't truly lived until you've seen a Xenobiologist push out 20+ cult slimes with other random simplemobs of murderbone death -- it's preferable to avoid simplemob murderbone armies in the future under the same reasons Golems were not allowed to be churned out for conversion.  (Sorry for all of those who were murdered by 3+ slimes to never be converted *chuckle)
I was unable to …
> Makes Simple Mobs unable to be Converted

- code/modules/events/event_container.dm
Mundane event scaling halfed from 50 weight per doctor to 25.
Medium event scaling reduced by 4/5 from **150** to 30, with a base weight of 50 instead of 0
The viral medium event and mundane event was happening basically every round, becoming a bit overused at that point. The mundane version will still probably happen most  rounds, but is more likely to be later in the round.
As for the medium event, it had one of the highest scalings in the game, increasing in weight by 150 for each doctor. With 6 doctors, we had 950 weight. This puts it more likely than all the anomaly events combined, as likely as communication blackouts on most rounds. This scaling is now tuned down, to be 30 per doctor. This means the weight with 6 doctors is 230, more comparable to other events.
Number changes, …
> GREATLY lowers the chances of viral events

- code/datums/components/surgery_initiator.dm
Fixes #19394, an issue introduced in the surgery refactor. Turns out that mobtypes were being checked a bit too late in the surgery chain, which caused trouble with some surgeries that made certain assumptions in their `can_start` procs (I'm looking at you, Alien Organ Manipulation).
Big thanks to @GDNgit for helping work through this issue and trying to fix it earlier.
This isn't a huge runtime, but it's a good (and annoying) one to knock off.
Loaded in, performed the action that used to runtime, and saw that it now does not.
NPFC
> Fixes a surgery runtime 

- code/game/objects/items/weapons/storage/belt.dm
Increases the bandolier capacity from 8 > 16.
Shotgun shells now stack into a single slot for ease of storage management.
That's it.
This belt item is trash, completely outclassed by having your shells in box's inside your backpack. This buff gives it a better niche of being easier to manage your shells, having them all in one place, and also more storage then keeping it in a box. An actual improvement to its entire gimmick overall.
boot server, used new belt, epic
:cl: Octus
tweak: Bandoliers are more useful, their storage capacity has been doubled and storage management is much more convenient to use and manage.
/:cl:
> Bandolier Buff because its existance is pathetic and im tired of every individual shell being its own seperate slot oh my god

- code/__HELPERS/mobs.dm
hide_attacklogs set the log priority to ALL rather than ALMOST_ALL
(removes just a wee bit of else spam too)
admins that don't wanna see logs shouldn't need to see logs
compiled, ran, beat a skrell to death
:cl:
tweak: [ADMIN] hidden attack log areas actually hide their logs now
/:cl:
> hide_attacklogs areas actually hide attack logs

- code/game/gamemodes/traitor/traitor.dm
Adds Changelings to the check that prevents Vampires from also rolling Traitor, making it impossible to roll both Changeling and Traitor at the same time.
This has been quite some time coming, especially with the buffs Changeling has seen recently - Changelings are now antagonists that can stand on their own without needing 20TC of traitor gear, and Clingtots were honestly kinda a pain for balancing either Changeling or Traitor. Besides, the concept of dual-antagonists seems to be flawed from the start - the player was given double the powers/equipment of a normal antagonist and double the amount of objectives, which didn't really make it harder so much as it gave them an excuse to cause even more chaos with their augmented abilities.
It built, which is about all I can test on my own. May …
> Removes Clingtot

- code/__DEFINES/dcs/signals.dm
- code/game/gamemodes/objective.dm
Continues #19809
If a changeling has an escape with identity objective and an assassinate objective, and their assassinate objective target cryos, it will no longer re-roll invalid targets (such as IPCs).
In the previous PR, I didn't account for that fact that the escape objective had no way to prevent it's linked assassinate objective from choosing a `GENELESS` target.
* Adds a `COMSIG_OBJECTIVE_CHECK_VALID_TARGET` and accompanying return flags to allow for objectives to influence the target selection of other objectives using signals.
* Also fixes the `datum/objective/escape/escape_with_identity/New()` arg order, since I didn't account for the `team_to_join` arg. This was also creating a bunch of buggy behavior with escape with identity objectives.
Bug fix.
:cl:
fix: If a changeling has …
> Escape with Identity objective fixes

- code/game/objects/items/devices/autopsy.dm
- code/game/objects/items/devices/scanners.dm
Scanners are now SMALL weight and can fit into SLOT_BELT (doesnt include detective and librarian scanner).
Judging by the icons it doesnt make sense for some of the scanners to be classified as TINY.
Giving SLOT_BELT for the autopsy/analyzer and slime scanners is good for consistency.
- Compiled, spawned some scanners and did wear them
:cl:
tweak: Standardized most scanners to have SMALL weight and to fit into the BELT SLOT
/:cl:
> Standardizes weight and slots for most handheld scanners

- code/game/machinery/vendors/departmental_vendors.dm
Adds 5 peppersprayers to each sectech
SecTechs have all the supplies of a full secbelt except a baton and pepperspray. Currently, the only way to get peppersprayer is to order a new officer kit, or raid some poor officer's sec belt, or have them be mapped in like on cyberiad.
Peppersprayers was in the vendor
:cl:
add: SecTech vendors now contain 5 peppersprayers
/:cl:
> Adds pepperspray to the SecTech vendor

- code/game/machinery/Sleeper.dm
- code/game/machinery/adv_med.dm
- code/modules/mining/satchel_ore_boxdm.dm
Adds a desc to both the body scanner and the sleeper
Removes some wrong information from the detailed examine on the body scanner
Replaces the "empty box" verb with an alt-shift-click keybind
Replaces the "eject" verb with an alt-click keybind
The fact you'd rather just go into the UI for these and hit the button rather than using what should be an easier and quicker method ain't great. The future is now, old verbs
Compiled and ran 
:cl:
tweak: "empty box" verb is now an alt-shift-click keybind
tweak: "eject" verb is now an alt-click keybind
spellcheck: The sleeper and body scanner now have proper descriptions 
spellcheck: Removed mention of a previously removed verb
/:cl:
> Replaces some ore box, sleeper, and body scanner verbs with click combinations 

- code/__DEFINES/dcs/signals.dm
- code/modules/martial_arts/sleeping_carp.dm
- code/modules/mob/living/carbon/carbon.dm
- code/modules/mob/living/carbon/carbon_defense.dm
If the user has a martial art with ranged deflection and catches an item, throw mode is no longer turned off.
Throwing items at people to turn off carp is disgusting, especially non bola items like handcuffs or rods. 
Confirmed catching worked without carp, and with carp.
:cl:
tweak: Throwing items at someone no longer turns off sleeping carp deflection
/:cl:
> Throwing items at someone no longer turns off sleeping carp deflection

- code/game/machinery/vendors/generic_vendors.dm
- code/modules/antagonists/changeling/powers/epinephrine.dm
- code/modules/reagents/chemistry/reagents/medicine.dm
The Stimulative Agent given to clings upon popping their Epi OD ability has been changed to a subtype (Stimulative Cling) which has all the same effects without the speedboost. On health scanners it is identical to Stimulative Agent so you can't automatically know it's a Changeling using the ability.
Giving Changelings Stimulative Agent when Synaptizine got reworked from anti-stun to anti-confusion was a good way to give them a decent buff at the time, as they were still in a very weak state and this was an ability they could only reasonable use once in quite a while - it got them up and out of danger rapidly, but strained muscles still had a role in being longer term speed boosts. However, with the 3x to chemical regen rate, this ability is now much more spammable and as such has taken …
> Removes the Speed-boost from Cling Epi OD

- code/game/objects/items/weapons/storage/backpack.dm
- code/game/objects/items/weapons/storage/belt.dm
Alternate to #20115. Bag of holding max item size has been decreased from huge (5) to bulky (4), the max weight has also been changed from 35 (7 huge items) to 28 (7 bulky items). 
BOH is a bit overpowered, but I dont think it needs a full on anomaly core for it to nerfed.
Game compiles, changes work.
:cl:
tweak: Bag of holding can only hold bulky items instead of huge sized items now (no chainsaws, shotguns, etc.)
tweak: Bag of holding has a max weight of 28 instead of 35.
/:cl:
> Alternate to Bag of holding changes

- code/game/objects/items/blueprints.dm
Adds the SHOW_WIRE_INFO trait to the CE's blueprints and /only/ the CEs blueprints 
(also probably should mention this was an idea from charlie I just randomly remembered)
The CE's blueprints right now are kind of a weird traitor item. Taking a photo of it can also be done for a steal objective which is really cool, but you're not really given a reason not to do so as the utility of the item just is not applicable to an antagonist. The ability to see wires, while small, presents a choice on how you're going to steal the item.
This is also useful for CE players who aren't too keen on playing the wire minigame startshift, or just might want a reminder.
:cl:
tweak: CE's blueprints now can view wire info while in hand
/:cl:
> CE's blueprints can now see wires

- code/game/gamemodes/nuclear/nuclearbomb.dm
Adds an additional variable to Syndie nukes which prevents the first step of tool-based unanchoring from being done until the NAD is used to unbolt the nuke. Once the nuke is unbolted, this variable is set to false which means it can be un-anchored by tools so crew can still try to unanchor it and space it if it's actually planted on station.
The nukies game-mode is intended to be crew vs nukies, actually fighting for defense of the station. Instead, some players have figured out that they can entirely circumvent the gamemode by easily breaking into the nukie shuttle (it's poorly defended), and it's genuinely unfair to say that one of the players picked for nukie should have to sit behind on the shuttle and not enjoy the fun of the round just because some people want to cheese the …
> Prevents Syndie Nukes from being moved without the NAD

- code/game/objects/effects/spawners/lootdrop.dm
- code/game/objects/structures/spirit_board.dm
Added pie cannon (service gear) and spirit board (largeitem) to Sol Trader items.
Spirit board now can be fastened and the redundant examine text has been removed.
The pie cannon is only available to the honk squad currently and it could fit into the sol traders service gear.
The spirit board is fun and chaotic. With the various requirements to use it, combined with the fact that Sol Traders arrival is only approved during green alert, could allow for a fun usage by the crew without the worry of ghosts reporting antags (and its not that better at it than simply using camera obscura + cranyon letters).
- Compiled and tried to fasten it with a wrench
:cl:
add: Added pie cannon and spirit board to Sol Traders items
tweak: Spirit board now can be fastened
spellcheck: Spirit board redundant …
> Added pie cannon and spirit board to Sol Trader items

- code/game/gamemodes/miniantags/morph/morph.dm
Morph actions are now updated when food is eaten
Bugfix, plus people not knowing when they can use their spell is bad
Compiled, ran, proc'd the proc, and unwelded some vents
:cl:
fix: Morph actions now update when that morph gains/loses food
/:cl:
> fixes morph button icons not getting updated

- code/game/objects/cleaning.dm
Mop no longer fails to clean when used with 1 unit remaining.
It currently only wets the floor on last use, not cleaning the decals. Its not intended behaviour.
- Used the mop with 1u of water remaining to see if it did clean the blood.
:cl:
fix: Mop no longer fails to clean when used with 1 unit remaining
/:cl:
> Mop no longer fails to clean when used with 1 unit remaining

- code/game/gamemodes/nuclear/nuclearbomb.dm
- code/game/objects/items/tools/multitool.dm
- code/game/objects/items/weapons/storage/toolbox.dm
The syndicate screwdriver now spawns in suspicious toolboxes, basically a way for traitors to buy another ultra thin tip screwdriver if they lost their original one. For everyone else, it's just a faster screwdriver kind of like the suspicious multitool.
Speaking of the suspicious multitool, I have removed the capitalization from its name. This is improper for an item.
The syndicate screwdriver no longer interacts with the syndie nuke. This is to prevent easy disarms without the NAD. There was no way to get one on a nukeop round before so this isn't really a big deal.
As described above. Just adds more of a benefit to buying or finding a suspicious toolbox. Could have sworn this was already a thing though unless I am once again crossing my TG knowledge with Paradise.
This is going to …
> Syndie tool tweaks

- _maps/map_files/generic/Lavaland.dmm
- code/controllers/subsystem/shuttles.dm
- code/modules/shuttle/shuttle.dm
Adds 2 new variables to mobile docking ports.
uses_lockdown and lockeddown
Only the mining shuttle and labour shuttle have this.
When a shuttle with this variable uses_lockdown an order from a shuttle console, it locks down the shuttle for 15 seconds, in that no more orders can be recived. This is enough time for the shuttle to reach the destination, and unseated people to get off the shuttle before it is called again.
Ends the pain that is shuttle wars, where a person on the shuttle, is fighting to have the shuttle go to / from lavaland, while the ai / officer / antag is spamming the shuttle console like no tomorow to keep it from going somewhere. This can go on for minutes as people click, which is fun for no one, can also be used to just call it the moment it docks at lavaland / base, …
> You can no longer redirect the mining / labour shuttle when it is moving

- code/game/gamemodes/vampire/traitor_vamp.dm
Fixes a bug preventing you from being a traitor chaplain on traitor+vampire rounds
Fixes #20145
Tested on a local server with a config allowing single player non-extended rounds, it wouldnt let me roll vamp chaplain, but it would let me roll traitor chaplain
:cl:
fix: Chaplains can be traitors on traitor+vampire rounds
/:cl:
> Allows chaplain to be a traitor on vamptot rounds

- code/game/gamemodes/nuclear/nuclearbomb.dm
Adds a proc respawn checking on the nuke disc. Should the picked spawn be in a wall due to player intervention, it'll check for open turfs in all directions. If it somehow fails to find one (Space is valid as some spawns are mapped in space), it will pick from the list of other spawns and try again.
Failing to find an open space will cause it to fail like if it couldn't find a spawn. All spawns being dense is a possible very rare edge case, so it could be tweaked to spawn regardless and notify the hitch specifically.
The disc respawning in a wall occured on Cere and was originally assumed to be a mapping mistake, but it was a player-made wall. It's more consistent to have it slightly nudge the spawn to be in the open as none of the mapped respawns are in walls specifically. …
> Nuke disc respawn checks its surroundings for an open space if someone winds up building a wall over it

- code/modules/admin/topic.dm
Removes an unneeded and not functional thunderdome warning
fixes #20177 (TY for the report ryan)
Admins don't need to know the thunderdome has been started... twice. one message is enough and the old one doesn't properly work
Compiled, ran, started a match
:cl:
fix: [ADMIN] The thunderdome no longer sends an extra alert it has been started
/:cl:
> Removes a defunct thunderdome warning

- code/modules/power/singularity/narsie.dm
Fixes #18341 
The cause was due to the playerlist being able to contain null values, not leaving the z level
Runtimes bad
Compiled, ran, went postal
NPFC
> Fixes a narsie runtime

- code/datums/components/parry.dm
Requested by @hal9000PR. **(Implementation pending)**
Parry-capable shields/weapons will list which attack types they're able to parry when examined (melee, projectile, unarmed, etc.)
Spawned parry-capable objects and examined them.
:cl:
tweak: Parry-capable shields/weapons list which attack types they're able to parry when examined (melee, projectile, unarmed, etc.)
/:cl:
> Parry-capable shields/weapons list which attack types they're able to parry when examined

- code/game/objects/structures/aliens.dm
Fixes #19327
Alien weed nodes now have their references in other weeds removed on destroy
I like gcing
will make part of #20154 work more consistently 
compiled and ran with gc tests enabled
NPFC
> Fixes alien weed nodes not GCing

- code/modules/mob/living/simple_animal/bot/griefsky.dm
Revives #19970
fixes #19151
Runtimes bad, not getting the right sword is bad
Copied code from #19970
:cl: Exavere 
fix: Fixed a griefsky runtime, you get some of your swords back.
/:cl:
> Fixes bad del on griefsky (made by exavere) 

- code/game/objects/items/weapons/storage/wallets.dm
Wallets can no longer hold the hand drill.
fixes: #20075
What is this, some kind of bluespace wallet?
Try and put a screwdriver in a wallet
It goes in
Try and put a hand drill in a wallet
It does not go in
:cl:
fix: Wallets can no longer hold the hand drill
/:cl:
> Wallets can no longer hold the hand drill

- code/game/objects/items/tools/screwdriver.dm
The hand drill's screwdriver form no longer has a weight class of 1, it now has a weight class of 2 like the jaws of life and the hand drill wrench mode
Attaching a bit to the end of if shouldn't halve its weight 
:cl:
tweak: The hand drill screwdriver mode now has a weight class of small
/:cl:
> Hand drill's screwdriver form no longer as a weight class of 1

- code/modules/surgery/organs/augments_arms.dm
Makes it impossible to deploy an arm implant while wielding a twohanded item.
fixes: #20142
Previously the implant item appeared in your offhand while your primary hand still has the wielded item with its full effect. This for example would allow someone to use a vortex feedback inversion arm while using a chainsaw.
Install a vortex feedback arm
Wield a proto-kinetic crushes in both hands
Attempt to deploy the vortex feedback arm and fail.
:cl:
fix: It is no longer possible to deploy an arm implant while wielding a twohanded item.
/:cl:
> Makes it impossible to deploy an arm implant while wielding a twohanded item.

- code/modules/mob/say.dm
Adds two new possible say_dead_direct options, the thing that pops up before you speak as a ghost like "salts" and "whines". Now, ghosts are additionally able of coping and seething.
As per Qwerty's request, ghosts will additionally mald.
These dchat say options have always been great, let's bring in some modern ones.
See above
:cl:
add: Added additional say-prefixes to DChat. Cope, seethe, and mald, ghosts.
/:cl:
> Cope and seethe, ghosts

- code/game/objects/items/devices/chameleonproj.dm
- code/modules/mob/living/silicon/robot/robot_modules.dm
The cyborg chameleon projector can now transform into every (crew) cyborg type, rather than just the landmate cyborg
All things you would expect to change (Desc and icon) change upon use.
While already cloaking, it takes no time to change a disguise again
Instead of using the cloaker again to change back to normal, you hit the Cancel button
(The examine text for the saboborg has also been renamed to "saboteur module" but that's minor and it was only like that in the first place because you could only turn into an engineering borg)
The current iteration of this item sucks, like wholesale just not useful
You're locked into one module sprite, so you're 100% getting metachecked via a shove or a disabler beam
There's still signs that someone is a saboborg, such as "why is that mediborg holding …
> The cyborg chameleon projector can now transform into every (crew) cyborg type

- code/game/machinery/airlock_control/airlock_button.dm
Currently some external airlock buttons are mapped to space. This is a problem because they dont work due to never having power. I had 2 options
1. Map the station areas out to the buttons
2. Make the buttons feed off the controller power
This PR does the second
Bugs bad
fix: Fixed some external airlock buttons not working
/:cl:
> Fixes external airlock buttons

- code/datums/keybindings/mob.dm
The drop hotkey is now consistent with the drop verb
Two very similar ways to drop an item should function off of the same rules. Prevents some weird interactions like dropping objects in objects.
:cl:
tweak: The drop hotkey now functions the same as the drop verb
/:cl:
> The drop hotkey is now consistent with the drop verb

- code/modules/surgery/organs/subtypes/tajaran.dm
- code/modules/surgery/organs/subtypes/vulpkanin.dm
Reduces the dark sight Tajs and Vulps get from 8 tiles(Full view range) to 3 tiles(One more than humans).
Primal forms dark sight also reduced for both 
Both species essentially have free night vision with a very minor drawback. This PR keeps their dark sight while reducing it so that it is not on the same level as night vision.
Left new, right old. Both images were taken in full darkness.
In game.
:cl: Bmon
tweak: Tajarans and Vulpkanins have had their dark sight reduced from 8 tiles to 3.
/:cl:
> Reduces Taj and Vulp dark sight from 8 tiles to 3

- _maps/map_files/RandomRuins/SpaceRuins/spacebar.dmm
- code/game/area/areas/ruins/space.dm
Removes varedited area on Space Bar.
Part of #20018, fixes for which I'm splitting into separate PRs because I'm not going to attempt to manage one PR that touches five different maps if I don't absolutely have to.
Started server, joined, observed, flew to Space Bar. Ensured bar was powered, and VVed object locs. Checked no runtimes were logged.
> Fix varedited areas on space bar.

- _maps/map_files/RandomRuins/SpaceRuins/ussp.dmm
Removes varedited area on USSP. Replaces custom "Annex" area with a pre-existing `/area/ruin/space/derelict/hallway/primary`. Sure it's not _all_ hallway but let's be real no one is going to notice (Derelict Botany! Derelict Science! Derelict Engineering! No thanks I'm good).
Part of #20018, fixes for which I'm splitting into separate PRs because I'm not going to attempt to manage one PR that touches five different maps if I don't absolutely have to.
Started server, joined, observed, flew to Space Bar. Ensured bar was powered, and VVed object locs. Checked no runtimes were logged.
> Fix varedited areas on USSP.

- code/game/machinery/quantum_pad.dm
Fixes observers being sent to nullspace by clicking on the wrong quantum pad. This would happen when there was a quantum pad still deleted but still linked. However, the ghost teleport didnt check if this quantumpad was deleted and then sends the ghost to nullspace. This was a funny find.
No one should go there, even if they can get out easily
Not able to nullspace myself anymore
:cl:
fix: Observers can no longer nullspace themselves with quantum pads
/:cl:
> Fixes observers nullspacing themselves via quantum pads

- code/game/objects/structures/janicart.dm
- code/game/objects/structures/mop_bucket.dm
Increased janicart and mop bucket maximum volume (100u -> 150u).
You will no longer attack the mop bucket while transfering reagents to it.
Mop bucket: redundant examine text (reagent amount being displayed twice) has been removed.
It makes no sense that a mobile reagent container like the bucket (120u) has more volume than heavy, specialized equipment for cleaning (100u).
- Spawned a mop bucket and janicart.
- I filled it with a bucket to its new maximum capacity.
- Examined the Mop bucket.
:cl:
tweak: Increased janicart and mop bucket maximum volume (100u -> 150u)
fix: You will no longer attack the mop bucket while transfering reagents to it
spellcheck: Mop bucket: redundant examine text has been removed
/:cl:
> Janicart and Mop bucket tweaks

- code/__DEFINES/dcs/signals.dm
- code/datums/components/parry.dm
- code/datums/keybindings/human.dm
Parrying is no longer tied to resist and now has its own hotkey. The key is unbinded and can be changed to any key. (For best results bind it to F)
Parrying sharing resist is bad design, has some very annoying misinput moments, and really needed its own key because hitting B in a fight is awkward.
i love ultrakill
booted test server, binded parry, parried, damn
:cl: OctusGit SabreML
tweak: Parrying no longer uses resist as a signal, it now has its own designated hotkey and signal for the action.
/:cl:
> Parrying Hotkey

- code/__DEFINES/is_helpers.dm
- code/game/data_huds.dm
- code/game/jobs/access.dm
- code/game/machinery/machinery.dm
- code/game/objects/items.dm
- code/game/objects/items/weapons/storage/wallets.dm
- code/modules/mob/inventory.dm
- code/modules/mob/living/carbon/human/human.dm
- code/modules/pda/PDA.dm
Wallets and PDAs now correctly display the job of the ID they have for both comms and sechud. Wallets with multiple IDs will display the first ID. 
PDAs without an ID inserted, will show their cached job (Owner: Blah-name name, **Head of Security** ). This cached job on PDAs is how it has worked for a long time, if this should be removed, I can do so.
This also eliminates the unused procs GetJobRealName and FindNameFromID, because they are terrible code.
It also moves GetIdCard to a carbon/human proc
Wallets not showing IDs is confusing for security, and showing the wrong ID on comms is also confusing.
No ID - shows no id on sechud, "No id" on comms
Wallet, HOS ID first - HOS sechud, HOS on comms
Wallet, Captain ID first - Captain sechud, Captain on comms
HOS PDA, no ID - HOS sechud, HOS …
> Wallets now show proper jobs on Sechuds and Comms

- code/game/verbs/switch_server.dm
Qdel's a db query for the server switching var when its no longer needed
a query should be deleted after its no longer being used
no player facing changes
I compiled without runtimes
> Clears an undeleted DB query on switch_server()

- code/game/objects/items/weapons/cards_ids.dm
Gives the Prisoner IDs `LIBRARY_ACCESS` so that they can use the book computer in Perma (mapping is scary and I didnt want to make a new Library Computer variant to clog map queue).
Allowing the Prisoners to read is good for morale. Library access is also not something that would be "useful" for a prisoner so far from the Library to begin with. In terms of an ID getting stolen and used by a Temp Prisoner from the cells, theyre simply asking for a free Theft + Trespass charge.
I went and READ a BOOK!
:cl:
add: Added Library access to the Perma Prisoner ID so they can print books.
/:cl:
> Allows Prisoners to Use the Perma Library Computer

- code/modules/antagonists/_common/antag_datum.dm
Cleans up `/datum/antagonist/proc/add_objective`. Fixes code so that receiving two steal objectives no longer makes the second one a Free Objective. This should heavily cut down on/eliminate occurrences of free objectives for the most part.
This whole time, I was checking `if("[S.steal_target]" in assigned_targets)`, but what I failed to notice is that `steal_target` is just a datum, so what was actually happening here is `if("/datum/theft_objective" in assigned_targets)`. As you can see, by the time the 2nd steal objective is added, it automatically detects it as a "duplicate". The fix is to instead check `"[S.steal_target.name]"` so we have something unique to compare.
Spawned in and gave myself traitor. `add_objective` was able to give me two steal objectives properly. Other objectives …
> Receiving two steal objectives no longer makes the second one a Free Objective

- code/modules/countdown/countdown.dm
When an atom with a countdown (like an SM shard) moves, the countdown moves with it.
Unfortunately, when the crates holding stuff like this, they wont update in real time. This is because the move signal isnt sent. So they will revert to their old fashion of lagging slightly behind.
It looks better
From this...
to this
See gif above, also tested inside crates which used the fallback instead
:cl:
fix: Countdowns over bombs and the SM integrity counter will now stay on top of the object when moved.
/:cl:
> Fixes countdowns being out of movement sync with their atom

- code/modules/mob/living/silicon/ai/ai.dm
Fixes what is almost certainly a logic error in Topic lookup for AI alarm alerts.
I am almost 100% certain this `in` clause is meant to select a reference from the list of available cameras. In its current position it has no effect since it is at the top-level expression of the statement, and its result is just thrown away. In point of fact it is a syntax error to attempt to assign this value:
```
var/x = switchCamera(locate(href_list["switchcamera"])) in GLOB.cameranet.cameras
// leads to
code\modules\mob\living\silicon\ai\ai.dm:688:error: GLOB.cameranet.cameras: unexpected 'in' expression
```
This is technically a minor performance improvement, as the locate call is now no longer using `world` as its search scope, which is the default if no `in` clause is specified, in the (relatively) …
> Fix AI alarm camera selection locate scope.

- code/game/objects/structures/janicart.dm
- code/game/objects/structures/mop_bucket.dm
Fixed janicart and mop bucket overlays for mop, trashbag and light replacer not updating properly when inserted.
Overlays not updating when they should is bad
https://user-images.githubusercontent.com/77684085/213077200-a8055594-3be4-4245-abc4-9f49aee2f4af.mp4
- See video above
:cl:
fix: Fixed janicart and mop bucket overlays not updating properly
/:cl:
> Fixes janicart and mop bucket overlays not updating properly

- code/modules/clothing/spacesuits/hardsuit.dm
The syndicate hardsuit updates it's on/ off flag when the helmet is toggled, meaning it *actually updates it's icon*
Fixing ancient bugs is good.
Icons updating as intended is good.
Having the 2 hardsuit modes show is good
(making spriters hate me is bad but hey)
https://cdn.discordapp.com/attachments/145700319819464704/1065120706997801041/Paradise_Station_13_2023-01-17_23-08-48.mp4
See above video
##Todo: Get spriters to make the other hardsuit mode for EACH OTHER NON HUMAN SPECIES FAAAAK
:cl:
fix: Fixed syndicate hardsuits not updating their body icon when helmet transform
/:cl:
> fixes body syndicate hardsuit sprites not updating properly

- code/game/objects/items/bodybag.dm
- code/game/objects/structures/crates_lockers/closets.dm
- code/game/objects/structures/crates_lockers/closets/secure/secure_closets.dm
- code/game/objects/structures/crates_lockers/crates.dm
Lets you shove people into lockers. If you shove them against an (openable) locker, it'll open. If you shove them against an open locker, it'll close on them. You can finally live out your high school dreams in space station 13.
Idea from https://github.com/tgstation/tgstation/pull/60000.
Another aspect for environmental combat. This one is more funny than impactful, though might slow you down for a bit. It's also funny!
https://user-images.githubusercontent.com/89928798/212011932-04e9ca56-9934-4cfb-a9da-e42b104badbe.mp4
Shoved some nerds (vulps) into lockers. Verified that things which are technically lockers but not really (body bags, crates) didn't work.
:cl:
add: You can now shove people inside of open lockers.
/:cl:
> Shoving nerds into lockers

- code/modules/projectiles/guns/energy/special.dm
Plasma pistol no longer requires the user to stand still while charging.
Plasma pistol is a niche weapon, being able to hit hard and break shields, but having to stand still for 2.5 seconds reduces the practicality of it greatly.
This now only just puts a charge wait of 2.5 seconds between shots, while still keeping the penalties of switching off it. I might make the penalties apply if the gun is dropped / holstered while charging, will see what people think.
Honestly it might still be too large of a charge time.
Confirm charging worked, and that it failed if dropped / holstered.
:cl:
tweak: Plasma pistol no longer requires the user stand still while overloading it
/:cl:
> Plasma pistol no longer requires the user stand still while overloading it

- code/datums/uplink_item.dm
- code/modules/projectiles/guns/energy/telegun.dm
- code/modules/projectiles/projectile/special.dm
Makes it so that the Telegun only teleports to beacons that are on its z-level. This can be extended to any beacon if you emag the target beacon. If you manage to walk off z-level and back on to set the beacon to space it will instead teleport you somewhere within 15 tiles as it would if you didnt have a beacon set.
Also reduces the Telegun's cost by two to make up for the change.
One-click permakilling Security/targets is cringe. This allows you to do silly things without perma-ending someone.
Sent many vox on a wild space adventure.
:cl:
tweak: Tweaked the Telegun's targeting to only choose beacons on your current z-level unless theyre emagged.
tweak: Telegun cost reduced to 10TC
/:cl:
> Limits Telegun to Current Z-Level (Unless a Beacon is Emagged)

- code/modules/assembly/igniter.dm
Assemblies containing an igniter do not prime grenade when used in hand
This was unintended behaviour introduced in a previous PR. Bombs should not explode in your hand while you're trying to set a timer for it or change the frequency on a signaller.
Build a timer-igniter assembly, use it in hand, bomb does not explode, set timer, bomb explodes upon timer elapsing.
Build a signaller-igniter assembly, use it in hand, bomb does not explode, signal bomb frequency and bomb explodes.
:cl:
fix: Assemblies containing an igniter do not prime grenade when used in hand
/:cl:
> Assemblies containing an igniter do not prime grenade when used in hand

- code/modules/reagents/reagent_containers/applicator.dm
Removes the small injection by automenders before the timer begins.
We have lots of different ways for applying healing reagents, but the automender takes the cake for the most braindead default choice applicator. This leads to a lack of diversity in non-medbay reagent application.
This PR makes it so that the automender isn't the default best at everything, with healing on the move being handled better by pills or patches.
Prevously fox has argued for retaining this (https://github.com/ParadiseSS13/Paradise/pull/14704), i quote: 
> The instantaneous application is so inconsequential as to be not worth mentioning; it's not really going to save your life or make much of a difference in the times it matters. In the long drawn out circumstances that I'm sure some hypothesize regarding this, …
> Removes automender smallhealth

- code/modules/mob/living/simple_animal/hostile/mining/goldgrub.dm
Goldgrubs can not block projectiles with 100% armor penetration
Certain shots should not be blocked for certain reasons.
Confirmed such shots were not blocked
:cl:
tweak: Goldgrubs can not block projectiles with 100% armor penetration
/:cl:
> Goldgrubs can not block projectiles with 100% armor penetration

- _maps/map_files/RandomRuins/LavaRuins/lavaland_biodome_clown_planet.dmm
Tweaks the disposals in the clown ruin so taking the wrong chute has a 50/50 chance of either sending them into lava, or right at the start to try again.
Due to quirks of the disposal system, before or even after the switch to destination lists, the clown ruins would never send people into lava for their failure. This is disappointing to the Honkmother, so now people will burn. Half the time. The Mother knows mercy.
https://user-images.githubusercontent.com/80771500/211218331-c66743b3-1cbe-4019-a6b2-3d1e79a32b1e.mp4
_go down chutes, put clown.ogg on repeat_
:cl:
tweak: THE TRIAL OF HONKITUDE is funnier
/:cl:
> Wrong chute in clown ruin now has a 50% chance of sending failures in lava instead of safety

- code/game/gamemodes/cult/blood_magic.dm
As it states on the tin, if you are on the ground for any reason and you try to cast the cult teleport spell, you will be unable to.
Discussing cult balance is a bit of a joke in the community, but I think most will agree that cult at the moment is an exceptionally safe antag for a number of reasons - they can be fully rejuvenated if they die using a revive rune, they can be recalled to a recall rune by their fellow cultists, and at any point they feel like they can use the teleport spell to escape any ill situation. With this change at least, if you baton a cultist they cannot immediately cast this spell to get out risk-free from any combat.
Made sure it worked for both stuns, knockdowns, and intentional resting, has a message to the cultist that it doesn't work while prone and doesn't …
> Prevents cult teleport while prone

- code/game/dna/mutations/powers.dm
- code/modules/mob/language.dm
Grey (the species) mimes will no longer be able to talk through telepathic messages or their species hivemind. This also affects the genetic power to speak into peoples heads.
Greys shouldnt be except from the mime's vow of silence
Spawned as a grey mime.
Tried speaking out loud, failed.
Tried the telepathy spell, failed.
Tried the grey hivemind, failed.
Broke vow of silence
Spoke out loud
Telepathied a skrell
Spoke on grey hivemind
:cl:
fix: Grey Mimes are now bound by their vow of silence for their hivemind and telepathy
/:cl:
> Prevents Grey Mimes from talking via telepathy

- code/datums/action.dm
- code/game/objects/items/robot/robot_upgrades.dm
- code/modules/mob/living/silicon/robot/robot.dm
- code/modules/mob/living/silicon/robot/robot_modules.dm
- code/modules/research/designs/mechfabricator_designs.dm
Alternative version of #15864
Janiborgs no longer starts with a floor buffer, its now an upgrade module.
Floor buffer now can be toggled on/off and the movement speed is decreased while active.
Janiborgs are too good at cleaning, most of the time leaving poor organic janitors to stare while they just cleans the room by simply existing.
Janiborgs advanced mop wont be ignored as much with floor buffers no longer being something they start with.
By decreasing their speed while the buffer is active we would be mainly nerfing their combo with vtec, that did turn them into cleaning monsters before.
WITHOUT VTEC
https://user-images.githubusercontent.com/77684085/211211566-fe9a7245-ba02-478b-857f-fb9f7463ece8.mp4
WITH VTEC
https://user-images.githubusercontent.com/77684085/211211549-b751fe96-e0ea- …
> Janiborg no longer starts with floor buffer and now can be toggled

- code/defines/procs/announce.dm
Sets the announcement config for request consoles to be logged.
This ensures that all proper logs are logged. Log.
Launched server, spawned in, made bridge announcement, checked the output of `game.log`. Ensured ckey, character name, announcement type, and full text of the announcement were logged.
> Re-enable logging for request consoles.

- code/modules/projectiles/guns/throw/crossbow.dm
the powered crossbow + it's cell now properly GC
you no longer runtime upon adding a bolt to the crossbow
things working 👍 
:cl:
fix: Powered crossbow now properly displays ammocount upon examine and adding a bolt
/:cl:
> powered crossbow fixes

- _maps/map_files/generic/Lavaland.dmm
- code/game/area/areas/mining.dm
- code/game/area/ss13_areas.dm
Removes varedited areas on Lavaland.
Also removes duplicate area defs for some labor camp areas.
Part of #20018, fixes for which I'm splitting into separate PRs because I'm not going to attempt to manage one PR that touches five different maps if I don't absolutely have to.
Started server, joined, observed, flew to Lavaland and VVed object locs. Checked no runtimes were logged.
> Fix varedited areas on Lavaland.

- code/__HELPERS/unsorted.dm
- code/game/gamemodes/cult/cult.dm
- code/game/gamemodes/nuclear/nuclear.dm
This PR attempts to fix two parts of the game, 1) cultist halo not appearing when 30% of the crew is culted 2) nukies getting more telecrystals than they should.
In both cases, the calculation is based on the connected players who are not sitting in lobby (living or observers). This means that animals, off-station roles, etc. are all counted, not to mention dead people. For this reason, cult halo almost never occurs, as you can have 10 living people with 20 ghosts - if 5 of those 10 are cultists, the halo still does not appear (despite 50% of the crew being culted), because the game counts observers too (`ascend_number = round(0.3 * (players_list - cultists))` which is `7.5` - as it is higher than 5, the halo doesn't happen.)
This PR attempts to make a calculation based on "whichever …
> Attempts to fix cult halo/nukie telecrystal number

- code/modules/mob/living/carbon/alien/humanoid/inventory.dm
- code/modules/mob/living/carbon/carbon.dm
- code/modules/mob/living/carbon/human/update_icons.dm
Aliens can now be properly bola'd 
Aliens can be bola'd but they won't get set to walk intent current, or have an alert show up.
Both of these above things happening is good. 
Compiled, ran, tossed a bola
:cl:
tweak: Aliens are now set to walk intent after being bola'd
/:cl:
> aliens can be properly bola'd

- code/game/objects/structures/crates_lockers/closets/fireaxe.dm
- code/game/objects/structures/crates_lockers/closets/statue.dm
- code/game/objects/structures/crates_lockers/crates.dm
- code/game/objects/structures/crates_lockers/crittercrate.dm
You can no longer push people into fireaxe cabinets.
This is very funny but unintentional.
Tried to push someone into a fireaxe cabinet, didn't work
:cl:
fix: You can no longer push people into fireaxe cabinets.
/:cl:
> You can no longer push people into fireaxe cabinets.

- code/game/machinery/teleporter.dm
fixes a runtime on the station teleporter
Feedback good, runtimes bad
:cl:
tweak: permeant teleporter boards when interacting with a station teleporter will now tell if you the station teleporter is linked to no console
/:cl:
> fixes a teleporter runtime

- code/game/turfs/simulated/floor.dm
adds a missing RETURN TRUE to the try_replace_floortile proc
Runtimes bad, incorrect proc calls are bad
NPFC
> fixes a floor tile runtime

- code/game/objects/items/weapons/storage/wallets.dm
- code/modules/mob/living/carbon/human/human.dm
Allows you to see the front ID on a wallet when examining someone. Also minorly refactors colored wallets. Idea comes from TG wallets. It also fixes people showing as Unknowns when having a wallet equipped but a mask on. It also refactors the can_track proc to use getID instead, which will make it consistent with wallets.
Makes it easier to understand what ID card someone is wearing without using a security HUD, and makes stuff more consistent.
Has an ID
No ID
See above. Using arcade wallets, they appear exactly as before but also have the new functionality.
:cl:
tweak: You can now see a Wallet's front ID when examining someone.
tweak: ID cards are now considered when showing someone (As Unknown)
tweak: Anti-tracking ID cards can be used inside wallets now.
/:cl:
> Wallets and ID card tweaks

- code/modules/mob/living/carbon/human/human.dm
Currently, beepsky will think you dont have an ID if youre wearing a wallet with an ID in it. Beepsky now considers any IDs when considering weapon arrests/No ID arrests. It also fixes a runtime with people not wearing an ID causing a large runtime log.
Walking into the armory with a wallet on but a valid ID in it current gets you walloped by Armsky
Weapons mode on:
no ID, with a gun - arrested
HOS ID with a gun - not arrested
HOS ID in a wallet with a gun - not arrested
empty wallet with a gun - arrested
No ID arrest mode on:
No ID - arrested
HOS ID - not arrested
HOS ID in wallet - not arrested
empty wallet - arrested
:cl:
tweak: Security bots now consider wallets when performing arrests
/:cl:
> Security bots now consider wallets when arresting people

- code/modules/mob/living/simple_animal/hostile/terror_spiders/mother.dm
Puts a check after the do_after. As well as converts the `do_after` to a `do_after_once`.
Shouldn't be able to get more jelly than you can buy
Spawned myself a MOT. Set the regen variable to 100. Started the process, stopped it by doing it again. Started it again and set my regen stat to 10 so it would fail once the do_after was done.
:cl:
fix: Mother of terrors can't produce jelly they can't afford
/:cl:
> Stops the mother of terror from shitting out too much jelly

- code/datums/status_effects/buffs.dm
- code/modules/mining/equipment/kinetic_crusher.dm
Adds the Parry Component to the Kinetic Crusher for melee attacks only.
Also reduces BDM Trophy Damage Reduction to 75% to offset the additional defense.
Skill Expression and more ways to fight on Lavaland without needing to speedrun to the BDM for its trophy. Half the times I want to go and use the KC I need to fight some sweatlord to the spawn.
Had a drake beat the hell out of me.
:cl:
add: added Parrying to the Kinetic Crusher
tweak: Blood Drunk Miner's Trophy now has a 75% damage reduction (down from 90%)
/:cl:
> Allows the Kinetic Crusher to Parry Melee Attacks + BDM Trophy Tweaks

- code/datums/status_effects/debuffs.dm
- code/game/gamemodes/cult/runes.dm
If a cult ghost goes too far from the summoner (3 screens) they take 7.5 brute damage per second.
Means you can not send an army to meme on security without them dying in approximently 25 seconds after they teleport, being pain slowed 6 seconds after teleporting.
For rune use, summoning people, or base defence, still quite useful.
Confirmed that I started dying once I went too far from the summoner.
:cl:
tweak: Cult ghosts begin to die if they go more than 3 screens from their summoner.
/:cl:
> Cult ghosts begin to die if they go too far from the summoner

- code/datums/status_effects/buffs.dm
Fixes BDM trophy resetting your damage to the initial value it would have instead of the updated value (as it now reduces damage to 1/4th instead of 1/10th).
I dunno, miners exploding upon being hit with a light breeze is very entertaining but this is a bug, so...
Fixes https://github.com/ParadiseSS13/Paradise/issues/20335.
Beat up some goliaths with it on, seemed to be taking correct damage before and after, and during the resistance activation.
:cl:
fix: Fixed BDM trophy causing you to take absurd damage after it deactivates
/:cl:
> Fixes BDM trophy causing you to take absurd damage

- code/datums/uplink_item.dm
Carp scroll can no longer be refunded
This was added because clingtot and vamptot were antagonists and couldn't use certain items, those antagonists no longer exist. Elimination of surplus based cheese brings a smile to my face, you got 40-120 tc worth of items, you can figure it out!
Holoparasite remains refundable due to it requiring a ghost. I thought about making it refundable only after attempting to use it once but I dunno seems overly complicated. 
probably didn't need to this is a var change
:cl:
del: Scrolls of the carpfu can no longer be refunded. 
/:cl:
> carp scroll can no longer be refunded

- _maps/map_files/cyberiad/cyberiad.dmm
- code/game/area/ss13_areas.dm
Removes varedited areas on Box. Mostly AI sat issues, although there was a varedited /area/toxins/storage as well. I can't think of any reason why the name used in the varedit shouldn't be the default name of the area so I moved that up.
Part of #20018, fixes for which I'm splitting into separate PRs because I'm not going to attempt to manage one PR that touches five different maps if I don't absolutely have to.
Started server on Box, joined, observed, flew to affected areas and VVed object locs (I wish areas showed up on the right-click menu for admins). Checked no runtimes were logged.
Nothing worth noting here except that separating AI areas out leads to the base `/area/aisat` only being used on two tiles, the external cams. Not sure if this is desirable.
> Fix varedited areas on Box.

- _maps/map_files/cerestation/cerestation.dmm
Removes varedited areas on Cerestation.
Part of #20018, fixes for which I'm splitting into separate PRs because I'm not going to attempt to manage one PR that touches ~~five~~ six different maps if I don't absolutely have to.
- Switched some overridden unknown mining areas to the appropriate Cere per-department mining areas. There was a tiny bit of unexplored mining with an override name of "Medical Asteroid" that were surrounded by "Civilian Asteroid" and not located directly on the med asteroid, so I moved those over to Civilian Asteroid.
- For some reason /area/security/execution had a custom label of "Prisoner Transfer Lounge", which I guess is technically true but probably not the intended name, so it was removed
- Garden was marked as construction area.
Started …
> Fixed varedited areas on Cere.

- code/_globalvars/lists/objects.dm
- code/game/turfs/simulated/walls_indestructible.dm
- code/modules/mob/living/simple_animal/hostile/megafauna/hierophant.dm
hierophant arena walls now decay after the hierophant dies, slowly turning to arena turf over time.
If it is better to collapse them all at once I can do that. Probably is, but thought a slow collapse would be cooler.
Hierophant will follow colossus bolts to the source if hit by one in their arena.
Looks cool. Arena collapsing, hierophant is dead, nothing really keeping it up. 
Thematics. 
Nothing else.
Confirmed the walls started slowly collapsing. 
:cl:
tweak: The walls in the hierophants arena collapse over time after hierophant is killed.
/:cl:
> hierophant arena walls now decay after the hierophant dies

- code/game/objects/items/weapons/cards_ids.dm
IDs with alternative titles (Most notably acting heads) will now be able to select account associated with their department regardless of the title.
Fixes: #19779
Acting heads should probably have access to their department's funds.
Create research director ID, rename the ID to Acting Research Director, attempt to order a crate on the science account.
:cl:
fix: IDs with alternative titles are now able to select account associated with their department.
/:cl:
> IDs with alternative titles now be able to select account associated with their department

- code/modules/projectiles/ammunition/ammo_casings.dm
- code/modules/projectiles/firing.dm
- code/modules/projectiles/guns/projectile/shotgun.dm
- code/modules/projectiles/guns/projectile/toy.dm
fixes foam dart gc issues
things not being in nullspace good, non-existent entities in turf contents bad 
gcing good
having "spent" but fully fired rounds in your chamber is just stupid
compiled, ran, GC debugged 
:cl:
fix: Toy shotguns/subtypes no longer say they have a spent round without actually having a spent round
/:cl:
> fixes foam dart gc issues

- code/__HELPERS/unsorted.dm
Tweaks the `is_blocked_turf` proc a little bit so it doesn't iterate over the entire contents of a turf unless it has to. So in this case, returning immediately if it finds an AI instead of happening to come across one at some point in the loop. The double negative with `||` was also hurting my head, and it made sense to simply check for living mobs first if `exclude_mobs` isn't true. The likelyhood of living mobs dogpiling in a turf are low, so it'd be in the single digits to check before actually iterating over objects.
To be honest, I was doing other optimizations until I came across this proc and got confused. So I decided to fix it first.
I tried jaunting or placing holosigns among other things.
N/A
> Minor is_blocked_turf optimization

- code/game/gamemodes/miniantags/demons/slaughter demon/slaughter.dm
The demon fluff objective was finding a crew target and then when that target cryo'd, it would give the demon the "Time for plan B" message. This shouldn't be happening.
Spawned in as a slaughter demon, VV'd through my demon objectives. Everything worked.
:cl:
fix: Demon fluff objectives will no longer be assigned targets or attempt to re-roll targets who have cryo'd.
/:cl:
> Cleans up and fixes an issue with demon fluff objectives

- code/game/objects/items/weapons/storage/belt.dm
Changes the beanbag shells to rubbershot for roundstart bartenders.
Rubbershot works better at handling people who jump the counter or tide inside the bar. Its a more close range ammo type and most of your time in the bar will be dealing with people getting in your face.
Beanbags also are a bit awkward and you need three while rubbershot needs two to stamcrit. Makes sense with a gun that can fire only two barrels.
booted test server, spawned as bartender wow
:cl: Octus
tweak: Bartender bandoliers now start with rubbershot instead of beanbag shells.
/:cl:
> Bartender bandolier now starts with rubbershot instead of beanbag

- code/modules/recycling/disposal.dm
Adds a shove interaction for disposals units. It drops you inside the unit, though doesn't automatically flush you, meaning you're free to crawl out, though it could be comboed for some pretty fun BM.
I can see this being useful for getting annoying people out of places they aren't supposed to. You aren't open to a free attack after this like you might be after tabling or walling, so it's a nice "get out of here" interaction.
It's a nice shortcut to click-dragging, and it'll be good at getting people out of areas if used effectively. You still need to manually flush.
https://user-images.githubusercontent.com/89928798/212252476-3e34a85a-30a1-4e8f-a3c5-758200fdd164.mp4
See video
:cl:
add: Adds shove interactions to disposals units.
/:cl:
> Shoving nerds into disposals

- code/modules/point/point.dm
Removes duplicate code that broke pointing inside carried containers, and moved the cooldown to the initial verb, so that people can't just queue spam.
Fixes pointing into things. The cooldown was something I noticed and decided to fix there instead of risking it.
Spawned and pointed at something inside a container on self.
:cl:
fix: You can point in carried containers
/:cl:
> Fix pointing into containers and cooldown

- code/game/machinery/machinery.dm
- code/modules/atmospherics/machinery/components/unary_devices/thermomachine.dm
Fixes issues with APCs having negative power consumption on certain channels
power needs to come from somewhere, not just exist infinitely
Ran on test server in, checked to make sure heaters adjusted their power consumption properly.
:cl:
fix: Fixes Negative Power Consumption on Toxin APCs
/:cl:
> Fixes Negative Power Consumption Caused by Thermo Machines

- code/game/machinery/portable_turret.dm
Turrets no longer take damage from a projectile, then call the parent, to take damage from a projectile again.
Turrets no longer take half damage from a melee attack, then call the parent, to take damage again.
Turrets now use their armor when hit by an attack.
Mob attacks on turrets now respect armor / act like any other structure being hit.
When object damage was brought over, some remenants of  turrets taking damage from attacks were not fully removed, causing them to take damage twice from some sources.
Turrets are supposed to have 80 hp, 50 melee armor, and 30 bullet / energy. They are supposed to die in 6 laser shots. Currently they die in 2. This is bad.
(Admittedly turrets still should be harder to fight and less cheeseable, but that is not a fix.)
shot / toolboxed / …
> Attacks on turrets no longer do 2x-> 1.5x damage, and now respect armor

- code/__DEFINES/gamemode.dm
- code/game/gamemodes/objective.dm
Changelings no longer have to debrain changelings, since well, debraining them isn't their real mind, nor does it kill them.
Impossible to complete objectives make no sense. It is good to have changelings be targeted by traitors / changelings, but it's also good to not give people impossible objectives.
In an ideal world, this would stay a debrain objective, then update to assassinate once the changeling revives / uses some offensive cling power on a person. Hard to code well, so this is the better solution for now
Confirmed that the game would not roll the changeling as a target.
:cl:
fix: Changelings no longer have to debrain changelings, as the objective is impossible
/:cl:
> Changelings no longer have to debrain changelings

- code/game/gamemodes/nuclear/nuclearbomb.dm
The nuclear fission explosive no longer needs power to be armed
bugfix
set the var to false and killed some APCs
:cl:
fix: nuclear bomb no longer needs to be powered to be used
/:cl:
> nuke no longer needs power to be armed

- code/datums/diseases/advance/symptoms/skin.dm
- code/modules/mob/living/carbon/human/appearance.dm
Fixes [Re]Vitiligo not updating the mob's sprite properly
Non-functional virus symptoms bad
Took a funky monkey, made it less funky by humanizing it via Mutadone, gave it a virus with Vitiligo
Repeat with Revitiligo
:cl:
fix: Fixed Vitiligo and Revitiligo not working properly
/:cl:
> Fixes [Re]Vitiligo

- code/modules/admin/admin_verbs.dm
- code/modules/error_handler/error_handler.dm
Tweaks runtime logging to not include proc arguments in the call stack
Before:
After:
**Note the change in the `call stack:` section, how procs no longer include their args**
I was recently made aware that lines like this exist in the runtime logs
`[2023-02-11T19:58:28]   HTTP (/datum/controller/subsystem/http): create async request("post", "https://discordapp.com/api/web...", "{\"content\":\"**\[paradise_ma...", /list (/list), null)` 
As we can see, theres half a webhook link here, meaning runtime logs are a potential for having secrets leaked. I dont like that. After this PR is merged, all existing secrets will be rotated.
**Note for concerned players** - There is no evidence in runtime logs to show that the database credentials have ever been logged, and even if they had been, the game …
> Fixes a security issue on runtime logging

- code/game/machinery/computer/brigcells.dm
- code/game/objects/items/weapons/batons.dm
This PR fixes two whitespace issues that snuck in between the last manual whitespace cleanup (#20226). With the submission of this PR all existing whitespace issues should be fixed and #19875 will be ready for review, making further whitespace checks part of CI.
There should be _no changes in this PR other than the following_:
1. The removal of leading spaces, or the replacement of leading spaces with tabs.
2. The addition of an asterix prefix for lines of comments which previously had leading whitespace.
3. Strings with leading spaces having their spaces moved to the previous line.
> Whitespace fixes, final part (hopefully)

- code/modules/admin/admin.dm
- code/modules/admin/admin_verbs.dm
- code/modules/admin/verbs/randomverbs.dm
- code/modules/supply/supply_order.dm
- code/modules/supply/supply_pack.dm
Allows admins to use the new "Create Crate" command, allowing them to summon any cargo crate at their current location. Its based heavily on the spawn_atom command.
This is different than spawning crates from the game panel, these crates will be copies of those you can order from cargo, which will be full of goodies.
Admins shouldnt need to manually put together crates like these if they want to send them
Spawned different types of crates. Unlocked, locked, critter crates, water tank crates, mule crates. All worked as expected. Buying crates from cargo worked as intended also, including manifests.
:cl:
add: [ADMIN] The "Create-Crate" tool will now let you spawn supply crates
/:cl:
> Adds a cargo crate spawning tool for admins

- code/game/gamemodes/steal_items.dm
- code/modules/reagents/reagent_containers/hypospray.dm
Renamed the CMO hypospray from "hypospray" to "advanced hypospray"
I had doubts in the past about which hypospray was the objective one, new antag players could be confused by it too.
"hypospray" makes it look like a common item, following the example of "advanced compact defibs" and "advanced magboots" could help to clear any confusion that may arise.
- Compiled and looked at the adv hypo inside the CMO locker
:cl:
tweak: CMO hypospray has been renamed to "advanced hypospray"
/:cl:
> Renames the CMO hypospray

- code/modules/recycling/disposal.dm
Allows humanoids (Borgs are unable to) to Alt-click on disposal bins to manually eject their contents after 5 seconds, even when depowered.
Currently when a disposals bin is depowered, the only way to get the contents out is by destroying the bin or powering it. This PR should offer a viable alternative to this.
Put something in a disposals bin, alt-click it, 5 seconds later the contents are ejected.
:cl:
tweak: Alt-clicking on a disposal bin as a human now manually ejects its contents.
/:cl:
> Alt-click on disposal bins to manually eject their contents

- code/controllers/subsystem/air.dm
Adds the SSair Recover override.
Seems like peeps found a way to make Atmos go tits up, and since it can't recover, that's bad.
Let the ai sat die, checked the offline SSair and it still had the original's pipenets and turfs.
N/A
> Add SSair Recover

- code/modules/mapping/cerestation.dm
Moves the cere webmap link to a real webmap not the scuffed non-updating ones
Its a real map now, it should have a real webmap
None. Its a webedit.
add: The webmap link for CereStation / NSS Farragus is now a proper webmap
/:cl:
> Real cere webmap link

- _maps/map_files/cyberiad/cyberiad.dmm
Add indestructable toxins test site camera to the toxins network on Boxstation so that it may be viewed via the camera monitor in the toxins launch room.
Previously this camera was not on the toxins camera network, despite being in the toxins test site. This camera is rather useful if you want to watch your toxins bomb go off. Now you can actually do so.
Go to toxins launch room
Look at the camera console
Middle camera is there
:cl:
fix: Indestructable toxins test site camera is now viewable from the camera monitor in the toxins launch room on Boxstation.
/:cl:
> Indestructable toxins test site camera is now viewable from the camera monitor in the toxins launch room on Box.

- code/_globalvars/lists/flavor_misc.dm
- code/game/gamemodes/miniantags/abduction/abduction_gear.dm
- code/game/objects/items/weapons/stunbaton.dm
- code/modules/clothing/under/color.dm
- code/modules/martial_arts/brawling.dm
- code/modules/martial_arts/martial.dm
- code/modules/mob/living/carbon/human/human_defense.dm
- code/modules/mob/living/carbon/human/human_say.dm
- code/modules/mob/living/carbon/human/species/_species.dm
deletes the forcesay() proc, this is NOT the admin forcesay command and this proc didn't work
Checked with coolrune, this will
Fixes #17458 
This will fix tyder the grey wizards from getting 2 shotted, turns out if you go through a proc 6 times, that proc will happen an extra 6 times causing you to fucking die. 
Does not work in game, and if I smacked someone with a sword and they just constantly started going ACK ACK ACK I'd have an aneurism
compiled, ran, didn't die instantly 
:cl:
fix: You no longer get hit 6 extra times by projectiles if you have an ancient jumpsuit equiped  
/:cl:
> deletes the forcesay() proc fixing tyder wizards getting murderized 

- _maps/map_files/generic/centcomm.dmm
- code/game/objects/effects/spawners/lootdrop.dm
- code/game/objects/items/weapons/grenades/clusterbuster.dm
- code/game/objects/items/weapons/grenades/custom_grenades.dm
Removes any cluster grenade that contained smoke grenades of any kind, the only one of these that was actually obtainable was the regular smoke cluster grenade and the tear gas smoke cluster grenade that were available from traders. There were a few others in the code that existed but were impossible to obtain outside of an admin spawning them, they have been removed as well. Because the cluster smoke grenade was remove it had to be removed from the ninja room in the admin room area so there is a slight mapping change. I've also gone ahead and removed the hellwater cluster grenade since it didn't work anyways.
These smoke grenades are incredibly performance intensive, in a recent round when a tear gas cluster grenade was set off time dilation reached 152% causing massive lag that made the …
> Removes smoke cluster grenades

- code/game/machinery/computer/HolodeckControl.dm
See title
Holocarp really should be the only kind being deleted, not *every* carp
compiled, fibsh
:cl:
tweak: The holodeck no longer deletes any carp upon changing the chosen holodeck map, only holocarp
/:cl:
> regular space carp are no longer deleted when changing holodeck, only holocarp

- code/game/objects/items/robot/robot_upgrades.dm
- code/modules/research/designs/mechfabricator_designs.dm
Lowers the alien level requirement for abductor surgery tool upgrade for the medborg from 4 to 3, and lowers the deconstruction reward from 3 to 2. 
Always struck me as slightly strange that despite getting alien medical tools before, medborgs have to wait for the abductor event to roll to get faster tools.
I made sure i somehow didn't mess up changing two numbers by deconstructing a single abductor upgrade, verified it was not in the mechfab, did a second, verified it was now there.
This was talked about a bit ago with qwerty, and they said they were up for this change, and did verify they are still willing for this to be made. 
:cl:
tweak: lowers the tech level requirement, and reward, for the abductor upgrade by one level. 
/:cl:
> more medborg love: surgery tool edition.

- code/datums/keybindings/human_keybinds.dm
- code/datums/keybindings/mob.dm
Title
Parrying is pretty important and it ought to be an automatically set keybind
Another big reason why this is very nice is because of how annoying parrying is without an automatic keybind while testing, you need to go into prefs `every time` and rebind it when you're testing something, just infuriating really.  
Compiled, hit space
:cl:
tweak: Parry is now automatically binded to space
/:cl:
> parry is now automatically binded to space

- code/modules/atmospherics/machinery/components/unary_devices/cryo.dm
fixes `Runtime in atmospherics.dm,242: Cannot read null.transparent_floor`
runtime fix
> fixes a cryocell runtime

- code/game/objects/items/candle.dm
- code/game/objects/structures/stool_bed_chair_nest/bed.dm
Shoving someone onto a bed while they're both wearing PJs and the bed has a bedsheet will put them right to sleep. Depending on some other comfort factors, they may sleep for a bit longer.
It's another fun shove interaction. It takes a bit of setup, so it might be a bit hard to pull off if you're not trying to.
https://user-images.githubusercontent.com/89928798/219446278-e2325665-05a0-4175-9bdb-302049f6c99d.mp4
Put some people to bed. 
:cl:
add: Being pushed into a made bed while wearing PJs will put you to sleep.
/:cl:
> Putting nerds to bed

- code/modules/mob/mob_login_base.dm
- code/modules/mob/new_player/new_player_login.dm
Fixes a runtime caused by re-admin verbs being assigned to the mob, not the client. Meaning re-adminning runtimes after a de-adminned client disconnects and reconnects.
Runtimes bad and admins coming back good.
A bit hard to test, but seems to be working.
:cl:
fix: Fixed re-adminning after closing and opening the client.
/:cl:
> Fixes re-admin runtime

- _maps/map_files/cyberiad/cyberiad.dmm
This PR implements the same changes as #19993, which I accidentally closed while resolving a merge conflict.
This PR makes some minor map changes to turbine on the Cyberiad, first, all the pumps and valves that lead to the AI sat distro from atmos have been closed/turned off, and second, the turbine room has been rewired so that the turbine SMES' input and output wiring is no longer connected.
With the current pipe setup if you send any gas from atmos to turbine without closing any pumps or valves in the turbine room then that gas will end up being sent to the AI sat's distro, this PR fixes that as its not great to accidentally send burn mix to AI sat's distro.
Turbine's SMES currently has its input and output connections connected to the same grid, while this doesn't cause any major …
> Turbine Wiring and Pipe Safety Tweaks Deconflicted

- code/datums/uplink_item.dm
- code/game/objects/items/weapons/storage/uplink_kits.dm
- code/modules/clothing/clothing.dm
- code/modules/clothing/gloves/color.dm
- code/modules/paperwork/paper.dm
- code/modules/paperwork/pen.dm
Reworks the poison pen to have unlimited uses, different poisons based on the selected color ink, and it goes through normal gloves now. Increases the TC cost as a drawback, while allowing coroners and psychiatrists to purchase them from uplinks. Also comes with a special pair of gloves that prevent you from poisoning yourself.
**Able to apply 20 units of these poisons, by selecting these colors**
- Black Ink: Nothing
- Red Ink: Amanitin
- Green Ink: Polonium
- Blue Ink: Teslium
- Yellow Ink: Pancuronium
Poison pen is an interesting concept, with a lackluster execution. It is a 3 use item with a very niche activation mechanic, that is not even guaranteed to put the target into crit. Even if it always did max damage, so many people on the station wear gloves, which completely blocks it …
> Reworks the poison pen

- code/game/objects/items/weapons/holosign_projector.dm
Janitorial holosign projector capacity has been increased (10 ->18).
Janitorial holosign projector now starts with the wet evaporation timer activated.
Having the W.E.T system on as the standard mode is good for newer janitors that will very likely forget to delete their signs.
10 holosigns might feel like not enough for some janitors, 18 would be enough to cover 3 locations (considering someone that covers the wet floor with 3 signs on each side on a hallway)
- Changed modes and used the projector until max amount of holosigns
:cl:
tweak: Janitorial holosign projector capacity has been increased (10 ->18)
tweak: Janitorial holosign projector now starts with the wet evaporation timer activated
/:cl:
> Janitorial holosign projector tweaks

- code/modules/vehicle/janicart.dm
You can now add trash directly to a trashbag attached to the pimpin' ride.
You can no longer waste multiple bags and upgrades by inserting lots of them.
Having to remove the trashbag from the vehicle to use it is too clunky, it should work like the janicart.
- Tried to insert more than one trashbag, received failure message
- Deposited lots of trash while riding the pimpin' ride
:cl:
tweak: You can now add trash directly to a trashbag attached to the pimpin' ride
fix: Pimpin' ride: You can no longer waste multiple bags and upgrades by inserting lots of them
/:cl:
> janicart (pimpin' ride) tweaks

- code/__DEFINES/status_effects.dm
- code/datums/emote.dm
- code/datums/status_effects/debuffs.dm
- code/game/objects/items/weapons/garrote.dm
- code/modules/mob/living/living_status_procs.dm
Fiber Garrote now applies new status effect, Absolute Silence
It means all emotes will be with disabled sound, no more gasping for a minute while you're trying to stealth
This PR makes new effect status to silence all emotes. Currently this status effect applies only by fiber garrote, but can be used in future
We have fiber garrote in game, its 6 TC. It supposed to make target silenced and supposed to be able to kill someone without a sound
But instead the only thing it silence is talk. All gasps, all cry all other emotes will emit sound. 
Great silence item *clap
This PR changes that, if you are silenced by fiber garrote, all your emotes wont emit sound.
compiled, garroted, killed
:cl:
tweak: fiber garrote now mutes all emote sounds on use
/:cl:
> Fiber Garrote now mutes all emotes when garroting target

- code/modules/antagonists/changeling/powers/mutations.dm
Replaces the old removal method of chitinous armor (using a saw on a prone target over 15 seconds) with an armor durability system. It functions as follows:
Every time the armor is deployed, it sets its durability to 600. Damage done to the Changeling is also done to the armor, with modifications dependent on damage type and certain weapons.
Charged Plasma Pistol shots do 200 flat damage to the armor. The Plasma Pistol is designed to be a niche weapon that destroys shields and armor, so giving it some targeted functionality here seems like a good idea. 
Plasma Cutters do 4x damage to armor, so regular does 20, advanced does 28, and the mech one does 40.
Circular saws do 25 flat damage to the armor. This is because previously, circular saws were the only tools that could remove the armor …
> Gives chitinous armor durability

- code/modules/crafting/guncrafting.dm
- code/modules/crafting/recipes.dm
- code/modules/projectiles/guns/energy/laser.dm
- code/modules/research/designs/weapon_designs.dm
Re-adds the LWAP sniper rifle to the game, with a rework to its functionality to better suit the current state of the game.
The LWAP sniper rifle functions similarly to the accelerator sniper rifle, starting with higher damage but increasing more slowly. Its benefits lie in its scope and ability to knock people down if the damage is above a certain threshold (40), with the knockdown scaling with the damage dealt.  It is limited by a severely bad firerate and gives you poor situational awareness while scoped. 
The LWAP used to appear in the Gamma Armory, but things that got the Gamma Armory caused were rarely something that would require the LWAP - so it is instead integrated into the RnD weapons kit system, requiring a LWAP kit and an Accelerator Laser (because it functions as a …
> Re-adds the LWAP, reworked

- code/game/objects/items/devices/handheld_defib.dm
- code/game/objects/items/weapons/implants/implant_freedom.dm
- code/modules/clothing/gloves/misc_gloves.dm
- code/modules/hallucinations/effects/moderate.dm
- code/modules/mob/living/simple_animal/bot/ed209bot.dm
- code/modules/mob/living/simple_animal/bot/secbot.dm
Fixes a pathing issue with the shock sound that seems to have been caused by Byond deciding it'd suddenly be case sensitive about audio paths. This should fix the shock sounds for handheld defibs, shock gloves, and beepsky/ED stuns.
Hand defibrillators are borderline unusable without the sound effect, it's good to have it back.
Loaded in, gave a vulp 600 oxyloss, shocked with a handheld defib.
:cl:
fix: Fixes some shock sound effects
/:cl:
> Fix shock sounds

- code/game/machinery/machinery.dm
- code/modules/reagents/chemistry/machinery/reagentgrinder.dm
title
how the fuck this was not reported for 3 years is "byond" me, but this fixes the issue
working code GOOD
:cl:
fix: You can once again deconstruct reagent grinders
/:cl:
> fixes being unable to deconstruct reagent grinders

- code/game/gamemodes/miniantags/revenant/revenant_abilities.dm
only carbons can hallucinate!
:cl:
fix: Revenant's hallucination no longer shows non carbon mobs being targeted, this is only visual, they weren't actually affected by the hallucination spell
/:cl:
> fixes improper scoping on revenant hallucination

- code/modules/mining/lavaland/loot/colossus_loot.dm
fixes a possible qdel loop and this runtime: `Runtime in observer_base.dm,234: Cannot modify null.timeofdeath`
aghosting no longer deletes your body as a lightgeist
bugfix, and honestly aghosting shouldn't delete your body lol
:cl:
tweak: [ADMIN] Aghosting will no longer delete your body as a lightgeist
/:cl:
> fixes a lightgeist runtime + possible qdel loop

- code/modules/projectiles/guns/energy/special_eguns.dm
Prevents the large E-bows produced via science guncrafting from being holstered in a shoulder holster.
Most large guns were prevented from holster a while ago, this one may have been left out. Either way, it makes sense it wouldn't fit in the holster like the mini version would, and having replicable e-bows in holsters is... very strong.
See above
:cl:
tweak: Large E-bows can no longer be holstered
/:cl:
> Prevents large E-bows from being holstered

- code/game/objects/items/robot/robot_upgrades.dm
- code/modules/mob/living/silicon/robot/robot_modules.dm
- code/modules/research/designs/mechfabricator_designs.dm
More or less the title. removes the RCD from engineering borgs base kit, and adds a new upgrade module that gives it back, with the level&matts requirements as follows: 
materials 6, engineering 5, and power storage 5.
matts: 30000 metal, and 15000 glass. 
Also adds a new var for _adding_ items rather than replacing for borgs.
The rcd is a extremely powerful tool, even more so for cyborgs, since they can deconstruct Rwalls with it, and being able to rapidly space, or un-space a room. on top of all of that, it is a rather lazy, and boring way to fix station damages. while it is fast, and sometimes the only option for somethings, like a SM delam, or something of similar destructive results, ideally RnD would have the required stuff to upgrade a borg to have the rcd. 
i ensured the engi borg …
> Removes the RCD from engi borgs base kit, and replaces it with a module upgrade

- code/modules/mob/living/simple_animal/friendly/cat.dm
- code/modules/mob/living/simple_animal/friendly/dog.dm
Fixes the last reference to Ian and Runtime before they are deleted.
...or so I hope, persistent data is an @AffectedArc07 thing, I'm sorry if this is dumb
Things should be GCing and I should only close issues when they are fully fixed (#19152)
1. Enabled GC ref finder options in `_compile_options.dm`
2. Spawned in Ian and Runtime
3. Deleted them
4. Waited 5-10 minutes
5. Checked gc_debug.log
6. No logs about them failing to GC
> Fixes Ian and Runtime not GCing

- code/modules/mob/living/carbon/human/species/drask.dm
Buffs Drasks by reducing their heat modifier from 300% to 200%.
Drasks are currently probably one of the weakest species. With a 300% heat modifier, they take a total of 450% additional damage from fire (due to the 150% burn damage modifier). This PR scales the damage down without buffing Drasks too much.
At the same time, the 200% heat modifier in the wiki is now correct.
Compiled and ran it.
:cl:
tweak: Reduced heat damage of Drasks from 300% to 200%.
/:cl:
> Reduces heat damage for Drasks from 300% to 200%.

- code/game/objects/items/mixing_bowl.dm
Makes `OPENCONTAINER` a proper container flag rather than the base atom flag.
Fixes #20512. `OPENCONTAINER` was the equivalent of `NOBLUDGEON`, `AIRTIGHT`, and `HANDSLOW`, which made things... weird.
Added salt to a bowl
:cl:
fix: Adding condiments and probably other ingredient types works on mixing bowls
fix: Fix odd interations from mixing bowls
/:cl:
> Fixes wrongly set var on mixing bowls

- code/modules/awaymissions/corpse.dm
Mob spawners like ash walkers or syndie researchers now respect ROLE_SYNDICATE bans the same as they do ROLE_GHOST bans. This is the case for like 99% of other antag related jobbans, as ROLE_SYNDICATE is the catch-all antag ban it seems.
Tourte will stop demanding I do it. Also, apparently this is intended to be banned alongside full antag bans (if not, go yell at Tourte).
Actually unable to test on my own, as I lack a database. However, this SHOULD entirely work, but it may need a TM to confirm nothing breaks horribly.
:cl:
fix: Fixed mob spawners not respecting antag jobbans
/:cl:
> Fixes mob spawners not respecting antag jobbans

- code/game/machinery/vendors/vendor_crits.dm
fixes #20551
Machine should be used here, not the datum
:cl:
fix: Lucky vendor tipping no longer references a datum
/:cl:
> fixes a vendor alert bug

- code/datums/uplink_item.dm
- code/game/objects/items/weapons/storage/firstaid.dm
- code/modules/reagents/reagent_containers/hypospray.dm
Syndicate medikit now costs 4 TC, no longer has combat defib in it, contains 2 emergency epipens and a sacid pill bottle as well now (10 units each)
Syndicate medikit bundle now costs 16 TC from 20
Combat defib is it's own item in the uplink now, costs 12 TC 
The combat defib stands out as one of the strongest nuclear available weapons, the ability to instantly 1-tap anyone resulting in them being stunned and soon dead is frankly amazing, and right now it is far too cheap for it's power level.
The Syndicate medikit, a healing tool, is pretty much only bought explicitly for the combat defib to it's sheer power level. At 7 TC nothing can really remotely compete with it, and it makes the "healing kit" not really used for healing.
at 12 TC the combat defib can still certainly hold it's own …
> combat defib tweaks, moved out of the medikit

- code/datums/spells/mime.dm
- code/game/objects/effects/forcefields.dm
the mime's (normal, traitor version is not affected) invisible wall can now be destroyed and has integrity. 
currently has 80 integrity (can probably be pushed up into the 100 range)
Mime's forcewall is pretty often used as a griefing tool as a nonantag more than anything else. Mimes slapping this down wherever whenever for really no reason is a pretty common sight, and a 20 second forcewall gets pretty annoying rather quickly. This gives it some integrity so that if this is used for complete shittery it can be broken down and delt with. 
Mime tot variant is kept as is because it's a tot item. 
compiled and ran, tried to pass atmos conditions but couldn't 
:cl:
tweak: The mime's basic invisible wall now has 80 integrity and can be broken
/:cl:
> the mime's force wall is now destructible

- code/modules/power/apc/apc.dm
see title
runtime this fixes: `Runtime in apc.dm,499: Cannot read null.connected_robots`
bugfixes
:cl:
fix: AIs can no longer control APCs that have the AI control wire cut
/:cl:
> fixes ais being able to control apcs with ai control off and borgs runtiming when attempting to do so

- code/game/turfs/simulated/walls_indestructible.dm
Fixes CC indestructible windows not smoothing with each other properly, they shouldn't have other overlays so doing this is fine I think.
Admin spawned stuff should look right
Fixes this (kudos for dsdiy for pointing it out):
Spawned windows
:cl:
fix: Fixed improper smoothing on indestructible windows
/:cl:
> Fixes indestructible window smoothing

- code/__DEFINES/misc_defines.dm
- code/game/atoms.dm
- code/modules/paperwork/handlabeler.dm
Adds three links (FLW, VV, JMP) and coords to labeller logs in the Investigate-Round-Objects menu. This allows admins to jump to the location of the labelling/renaming and to quickly undo things should the labels be rule-breaking.
Adds logging to `rename_interactive()`.
You only need one player to serial-label a bunch of items with the n-word to see why we need shortcuts for these.
Old:
New:
1. Spawn in as an assistant
2. Spawn a `/obj/item/hand_labeler`
3. Label a bunch of items
4. Take pen out of PDA, rename guns and containers
5. Admin -> Investigate Round Objects
:cl:
tweak: Admin logging for renaming objects was improved.
/:cl:
> Adds more robust labeller/rename logging

- code/_onclick/hud/alert.dm
Fixes a bug where ghosts who are orbiting something when clicking certain ghost notifications will get teleported back to their original orbit location. You've probably noticed this issue the most with manifest runes and the chaplain's salt shaker, among other things.
Changing loc directly, instead of using forceMove, doesn't fire the signals that orbit code uses to remove your orbit, so it tries to pull you back to whatever you're orbiting. 
Getting repeatedly pulled back when you meant to orbit on one tile is kind of annoying, and another late side-effect from my orbiting refactor (oops lmao).
:cl:
fix: Clicking some ghost alerts will no longer cause you to teleport back
/:cl:
> Forcemoves, instead of setting loc, for ghost notifications.

- code/modules/mob/living/simple_animal/constructs.dm
Harvester damage increased to 25-20 from 5-1
Harvester health decreased from 60 to 40
Outside of smoke and removing atmos from every single area on and off station, harvesters don't really do anything. Got internals? Harvesters are fucked, and that makes playing harvester kinda a drag, especially for what should be an end of round high point. An increase in melee damage will just let them actually do things, and the decrease in health will let crew fight them and let them make real progress until the shuttle leaves.
compiled and ran.  
:cl:
tweak: Harvesters now deal 25 melee damage
tweak: Harvesters now only have 40 health 
/:cl:
> harvesters are now glass cannons

- code/game/dna/dna2.dm
Fixes #20372
Fixes #12254
Same thing happens to everything else that uses this proc so clings get a very niche tell removed and cluwnes lose a way out
oh you know, bugs bad
:cl:
fix: Default blocks are still treated as default blocks after cloning
fix: You're stuck as a cluwne forever
/:cl:
> fixes default blocks not being carried over through Clone()

- code/modules/reagents/chemistry/reagents/water.dm
Adds the synthetic flag to the space cleaner reagent.
All space cleaner does is clean. You can't get addicted to it nor does it have an effect on mob life, so it doesn't make sense for it to not work on IPCs, resulting in janitors being stuck with soap and giving them a rub.
https://user-images.githubusercontent.com/80771500/221379427-e5319eb5-639e-4311-8b30-b03db245d894.mp4
Made a mess, had an IPC roll on it, and spray some space cleaner on it.
:cl:
tweak: Space cleaner works on machine people
/:cl:
> Space cleaner works on IPCs

- code/modules/mob/mob.dm
When a mob would be deleted it wouldn't clear the storage var if they didn't stop viewing the actual storage item, leading to GC fails.
things should GC properly
> improves storage GCing

- code/_onclick/hud/_defines.dm
- code/_onclick/hud/ghost_hud.dm
- code/modules/mob/dead/observer/observer_base.dm
See title, this does NOT delete the admin input() version, just the seldom used ghost version
Closes #19294
This thing barely works anymore and has some seriously bad performance impact. If opened EVEN ONCE during a round it keeps a hard reference to every single mob currently in that round and causes them to GC fail and hard delete with 100ms+ deletion times. This is really bad and it's not worth saving.
:cl:
del: Removed the "Jump to mob" verb from ghosts
/:cl:
> Deletes the "Jump to mob" verb from ghosts

- code/game/machinery/dish_drive.dm
Fixed the dish drive beam not having an icon.
Added feedback when there are no disposable items inside the dish drive.
Lack of feedback made me think for a few minutes that the dish drive was broken.
Beam with no beam icon is no beam, and must BEam fixed.
https://user-images.githubusercontent.com/77684085/222927525-93b4b250-5280-47ac-9317-e096584ddcad.mp4
- See video above
:cl:
tweak: Added feedback when there are no disposable items inside the dish drive
fix: Fixed the dish drive beam not having an icon
/:cl:
> Fixes dish drive beam

- code/game/machinery/machinery.dm
- code/modules/atmospherics/machinery/components/unary_devices/thermomachine.dm
unfucks the maths on thermo machines
Fixes #20461
Now power consumption for using heaters/coolers has minimum power consumption and scaled with the temperature differential + the magnitude of the current temperature.
A single heater can no longer out consume the entire station by a magnitude of 3
Ran a test server and tried out different settings
:cl:
fix: thermo machines no longer consume power at the same rate as a medium-sized metropolitan city
/:cl:
> Fixes Thermo-Machine Power Consumption

- code/datums/uplink_item.dm
Limits combat defib to nuclear operative uplinks, making it impossible for regular traitors to buy them.
This was an unintended change from moving the combat defib from the nukie medkit to a seperate item. And I _really_ don't think we should give traitors the one-tap weapon.
Become a traitor
Open uplink
There is no combat defib
:cl:
tweak: Limits combat defib to nuclear operative uplinks.
/:cl:
> Limits combat defib to nuclear operative uplinks.

- SQL/paradise_schema.sql
- SQL/updates/45-46.sql
- code/__DEFINES/misc_defines.dm
- code/modules/admin/verbs/playsound.dm
- code/modules/client/client_procs.dm
- code/modules/client/login_processing/10-load_preferences.dm
- code/modules/client/preference/preferences.dm
- code/modules/client/preference/preferences_mysql.dm
- code/modules/client/preference/preferences_toggles.dm
- config/example/config.toml
Allows players to see which admin played a soundfile, as well as the option to mute sounds from that specific admin without disabling the entire system.
I wont beat about the bush, there are some admins who only play shitposts with the playsound feature. This lets players ignore sounds from said people while not having to disable the entire system.
- Played a soundfile with no mute (heard it)
- Played a soundfile with a mute (did not hear it)
- Saving and loading the preference worked
- Removing admins from the mutelist works
add: Added the ability to silence admin soundfiles from specific admins without disabling the entire system
/:cl:
---
Stop calling them admin MIDIs. 99% of plays arent even MIDIs, MIDIs dont even make sound on their own, its just a way of storing …
> Allows you to mute soundfiles from specific admins

- code/modules/power/apc/apc.dm
Fixes borgs not being able to use APCs
I dunno, maybe borgs should be able to wield the power they have. Be it shocking or not, this area of code was malfunctioning and would cause runtimes. 
:cl:
fix: Borgs can interact with APCs
/:cl:
> fixes borgs not being able to use APCs

- code/modules/response_team/ert_outfits.dm
Adds soap to the backpack of both the Medical ERT Amber and Medical ERT Red
This brings ERT closer inline to the SOP of medbay personel, as the role for both Amber and Red Medical ERT is to help support the operation of the medbay itself, when applicable. 
Medical ERT Description:
"As an Amber ERT medic you are slightly better equipped than the station Medical Doctors. Use your heavy set of medications to quickly stabilized patients. You should primarily focus on support medbay and acting as additional medical personnel. Only if medbay is well staffed should you consider moving with the rest of your team. "
"As an Red ERT medic you are much better equipped than the station Medical Doctors and your amber counterparts. Use your heavy set of medications to quickly stabilized patients. You …
> Adds soap for medical ERT

- code/modules/mining/lavaland/loot/colossus_loot.dm
See title, becomes a POI when activated by someone (spawns you in as a lightgeist on click)
ghosts should actually know that it exists
:cl:
tweak: Helper crystal is now a point of interest
/:cl:
> Helper crystal is now a point of interest

- code/modules/mob/mob.dm
Friendly mobs which can be chosen to respawn as, now only show on-station and centcomm level mobs. Centcomm/admin levels 
Prevents players as spawning as mobs on the syndicate space base and needing to ghost out and lose their respawning privileges.
Could spawn as on-station pets normally and Syndicat and Syndifox on nuclear gamemode. Could not spawn as mobs in space (i.e. syndicate station cow)
:cl:
tweak: Players can no longer spawn as mobs off-station
/:cl:
> Prevents spawning of off-station mobs

- code/game/objects/items.dm
Ashes no longer tell you what they used to be on examine.
Frankly I was surprised this was even a thing, what's the point of burning something if you can still identify what it was.
Burned a named piece of paper
Examine the ashes
Ashes to ashes, dust to dust.
:cl:
tweak: Ashes no longer tell you what they used to be.
/:cl:
> Ashes no longer tell you what they used to be on examine.

- code/modules/mob/living/simple_animal/hostile/floorcluwne.dm
Floor cluwne now drops the false cluwne mask
The floor cluwne, which is currently only used as an smiting option, shouldnt reward players that manage to kill him and save the smited person with a mask that can end their round permanently, causing with it consequences that are not part of the original intent of the admin.
- Compiled
:cl:
tweak: Floor cluwne now drops the false cluwne mask
/:cl:
> Floor cluwne now drops the false cluwne mask

- code/game/gamemodes/wizard/spellbook.dm
Summon magic and summon guns now gives you 2 Wizpoints when purchasing them
So these two rituals are total dogwater. When they were first added they both gave you a wizpoint, however you would proceed to die due to the fact crew got like, pulse guns. Eventually it was changed to add survivalists into the mix and I really shouldn't need to tell you how reliable those are with their very vague objectives and a effective target on the wizard. These spells need something and a little extra wizpoints should allow people to make funnier builds of wizard while the crew is gunning for their ass. 
:cl:
tweak: Summon guns and summon magic now give you 2 wizpoints on use
/:cl:
> Buffs summon magic and summon guns

- code/game/gamemodes/wizard/rightandwrong.dm
- code/modules/mob/living/living.dm
TRIGGER_GUARD_NONE was a trigger_guard var applied to energy gun turrets that was meant to make it so no one could fire them and they were only usable inside a turret. However it was not fully implemented so while the var existed, it didn't do anything. This PR makes it so guns with the TRIGGER_GUARD_NONE var cannot be fired by mobs. In practice this means the Hybrid turret gun you could get from destroyed turrets will not be able to be fired, so no more tasers for crew.
Bugs are bad. Also tasers were removed for a reason, people should not be able to get them again by destroying turrets.
-Started private server
-Attempted to fire a normal gun as a human, it worked
-Attempted to fire a normal gun as a monkey, it worked
-Attempted to fire a normal gun as an abductor, it did not work …
> Fixes a bug that allowed turret guns to be fired by mobs.

- code/modules/paperwork/paper.dm
Port from https://github.com/ss220-space/Paradise/pull/934
You can now click a small button located next to the text editing to automaticaly fill it with the following information: Current name, job, signature, account number, PIN, station name, date, time, gender, species.
This will hopefully make filling paperwork more easier for those that are not accustomed to it.
https://user-images.githubusercontent.com/77684085/220946072-9eed4bf8-bbdf-4d63-a6a8-28b929524eea.mp4
- See video above
:cl: Henri215, PhantornRU
add: You can now use the new autocomplete feature when writing on a paper (the small "A" located next to "write")
/:cl:
> Ports SS220 AutoComplete for Documents

- code/modules/mob/living/silicon/robot/robot_laws.dm
fixes this runtime
```
[2023-02-25T14:52:08] Runtime in robot_laws.dm,69: Cannot read null.syndiemmi
[2023-02-25T14:52:08]   proc name: set zeroth law (/mob/living/silicon/robot/set_zeroth_law)
[2023-02-25T14:52:08]   usr: *REDACTED USER*
[2023-02-25T14:52:08]   usr.loc: The floor (206,117,2) (/turf/simulated/floor/plasteel)
[2023-02-25T14:52:08]   src: the maintenance drone (130) (/mob/living/silicon/robot/drone)
[2023-02-25T14:52:08]   src.loc: the floor (206,118,2) (/turf/simulated/floor/plasteel)
[2023-02-25T14:52:08]   call stack:
[2023-02-25T14:52:08]   the maintenance drone (130) (/mob/living/silicon/robot/drone): set_zeroth_law
[2023-02-25T14:52:08]   the maintenance drone (130) (/mob/living/silicon/robot/drone): emag_act
[2023-02-25T14:52:08]   the cryptographic sequencer …
```
> malf drones get zeroth law alerts again

- code/modules/mining/equipment/kinetic_crusher.dm
- code/modules/projectiles/guns/energy/kinetic_accelerator.dm
Fixes KPAs and Crusher upgrades not GCing if they are destroyed while in the crusher, fixes ghost values which lead to neither item properly working
Working code good
:cl:
fix: a crusher/kpa mod destroyed in their respective item will no longer stop the item from functioning
/:cl:
> makes crusher+accelerator upgrades gc and fixes a ghost upgrade issue

- code/modules/error_handler/error_handler.dm
fixes #20452
I would like to see runtimes thank you
it does
:cl:
fix: [Coder] Runtimes with less than 2 proc arguments are properly logged again
/:cl:
> Fixes runtimes with less than 2 proc arguments runtiming

- code/modules/projectiles/projectile/force.dm
fixes this runtime:
```
[2023-02-25T22:20:10] Runtime in force.dm,16: undefined proc or verb /turf/simulated/wall/indestructible/syndicate/throw at(). 
proc name: on hit (/obj/item/projectile/forcebolt/on_hit)
src: the force bolt (/obj/item/projectile/forcebolt)
src.loc: the floor (225,139,1) (/turf/simulated/floor/plasteel)
call stack:
the force bolt (/obj/item/projectile/forcebolt): on_hit
the wall (225,140,1) (/turf/simulated/wall/indestructible/syndicate): bullet_act
the wall (225,140,1) (/turf/simulated/wall/indestructible/syndicate): bullet_act
the wall (225,140,1) (/turf/simulated/wall/indestructible/syndicate): bullet_act
the force bolt (/obj/item/projectile/forcebolt): Bump
the wall (225,140,1) (/turf/simulated/wall/indestructible/syndicate): Enter
the force bolt …
```
> fixes a forcebolt runtime

- code/modules/antagonists/changeling/powers/mutations.dm
Fixes a runtime, because fists don't have a set damage or damage type. Woopsies.
Fists do 1 damage to Chitinous Armor, by the way. It's a feature, reason below:
https://www.youtube.com/watch?v=WHujzgKlPqM&ab_channel=Hemotoksin
Runtimes bad, and anyone who decides to beat the shit out of an armored cling can have one armor_durability damage. As a treat.
See above.
:cl:
fix: Fixed a runtime with Cling Chitinous Armor being punched
/:cl:
> Fixes runtime with Chitinous Armor being punched

- code/modules/reagents/chemistry/recipes/slime_extracts.dm
Adds the missing snack base types to the list of blocked foods in the slimebork reaction.
Fixes #18634.
Did some silver core reactions, but really, I simply spawned all snack subtypes and checked their names so I could add to the list.
:cl:
fix: Silver slime core reaction doesn't spawn placeholder food.
/:cl:
> Silver slime cores don't spawn placeholder snacks

- code/modules/food_and_drinks/kitchen_machinery/smartfridge.dm
The Food Cart when it was reworked over a year ago was coded to not use power, or at-least that was what was intended. As it turns out it DOES need power in order to function as I found out quite recently.
I'm not quite sure what the above line does however it doesn't work as intended. If you wrench down the cart and turn off the APC the cart will cease to function trapping all the food inside. With the changes in this PR it now truly uses no power, at all, ever.
It's a cart not an actual vendor despite its subtype and food shouldn't be trapped inside if the power goes out in the area that it's wrenched down in. It was also intended that it wouldn't consume power from the beginning, just incorrectly/improperly done. This PR fixes that.
1. I codeded it.
2. Booted test server.
3. Wrenched …
> Food Cart now correctly no longer uses power.

- code/modules/mob/living/simple_animal/hostile/venus_human_trap.dm
Adds a cooldown to the venus human trap, so you can't just infinitely click people with it.
Currently, the venus human trap does 25 brute as fast as you click. That's probably not a good thing.
Spawned in, and clicked a vulp
:cl:
fix: Venus fly trap no longer has the gloves of the north star, and attacks at a reasonable rate.
/:cl:
> Fixes venus human trap cooldown

- code/modules/hydroponics/hydroponics_tray.dm
This adjusts the weedinvasion proc to more accurately display the type of tray or soil it is affecting when the soil or hydroponics tray is void of plants and is overtaken by weeds. 
This makes the visible message more accurate.
Before:
After:
Used weedinvasion proc on empty hydroponics tray and soil
:cl:
tweak: Tweaked the visibile message to show the proper name of the empty tray
/:cl:
> adjusts the visible message for weedinvasion proc

- code/modules/mob/living/carbon/human/human_defense.dm
Fixes this runtime by making sure the potential rev has a mind first.
```
[2023-03-05T18:09:28] Runtime in revolution.dm,254: Cannot read null.current
[2023-03-05T18:09:28]   proc name: remove revolutionary (/datum/game_mode/proc/remove_revolutionary)
[2023-03-05T18:09:28]   usr: *REDACTED USER*
[2023-03-05T18:09:28]   usr.loc: The floor (60,160,6) (/turf/simulated/floor/plasteel)
[2023-03-05T18:09:28]   src: Trifecta (/datum/game_mode/trifecta)
[2023-03-05T18:09:28]   call stack:
[2023-03-05T18:09:28]   Trifecta (/datum/game_mode/trifecta): remove_revolutionary
[2023-03-05T18:09:28]   the monkey (299) (/mob/living/carbon/human): attacked_by
[2023-03-05T18:09:28]   the stechkin pistol (/obj/item/gun/projectile/automatic/pistol): attack
[2023-03-05T18:09:28]   the stechkin pistol …
```
> Fixes a runtime with mindless revolutionaries

- code/modules/surgery/limb_reattach.dm
- code/modules/surgery/organs/organ.dm
- code/modules/surgery/organs/organ_external.dm
- code/modules/surgery/surgery.dm
Fixes #19661, where organs being dropped mid-surgery would sometimes cause surgeries to become stuck, necessitating an aheal.
Another surgery bug patched is always a good thing. More IPC surgery love.
Logged in, started surgery on an IPC and dropped the limb I started surgery on, it canceled the surgery.
:cl:
fix: Losing a limb that a surgical operation is being performed on will now cancel said surgery.
/:cl:
> Fixes organ removal mid-surgery causing stuck surgeries

- code/game/machinery/vendors/vendor_crits.dm
Uses the correct gib spawners when someone gets their head squished by a vending machine, with IPCs exploding into a shower of robot parts. Fixes #20571.
Even if you squish them under a vending machine, IPCs should not explode into a shower of gore.
splat
:cl:
fix: Squished IPC heads under vending machines no longer conjure mystery human gibs, but instead create robo gibs.
/:cl:
> Vendor head squishes now use more consistent gib colors

- code/game/objects/structures/mineral_doors.dm
Fixes transparent mineral doors. Previously they would start out transparent and be transparent whenever opening or closing actively, but the moment that they opened the first time their opacity would be set to opaque and thus whenever closed OR open they would be opaque. This was because opacity was simply inverted at the END of closing the door and transparent doors were set specifically to be transparent while opening, leading to a confusing result. To fix this, they're just always transparent now, as I assume was intended by the fact that they're called transparent 👍.
Fixes diamond and plasma doors from being very very weird.
Above image.
:cl:
fix: Fixed transparent mineral doors from becoming opaque whenever opened or closed
/:cl:
> Makes transparent mineral doors work

- code/__DEFINES/status_effects.dm
- code/datums/keybindings/emote.dm
- code/datums/status_effects/neutral.dm
- code/game/objects/items/hand_item.dm
- code/modules/mob/living/carbon/human/human_emote.dm
- code/modules/point/point.dm
Title. Pops a little image showing your interests in high fiving (*highfive or using a slapper in-hand), daps (*dap), or shaking hands (*handshake). Use the same activation method yourself while standing next to someone readying one of these emotes to return the gesture!
I just think it's fun.
https://user-images.githubusercontent.com/89928798/220552798-0cf6624b-5388-4c66-a2d4-5e61d2d2136d.mp4
:cl:
add: High-fives and other emotes now pop up a little thought bubble to show your interest.
add: Using a slapper (put in your hand by emoting *slap) in-hand will set you up for a high-five.
/:cl:
> Pops up a little bubble when you're requesting a high-five, along with some other emotes

- code/datums/status_effects/buffs.dm
- code/modules/antagonists/changeling/powers/fleshmend.dm
If a Changeling's body temperature is 50 below their species' normal body temperature, their fleshmend will be significantly weakened on activation. This is indicated in the activation message, and stacks on top of the existing debuff for frequent activation. The regeneration is weakened enough that it will not out-regenerate space damage once you start building tolerance.
Changelings have an ability called organic space suit. Didn't you know?
Except they have NO reason at all to use it because, you can spam fleshmend super quickly in space to out-regenerate all taken damage with basically no penalties or reason to use the space suit. That is, fleshmend, which is already a significantly powerful ability on its own, also basically negates the purpose of another ability entirely. Thus, …
> Gives fleshmend a weakness to cold

- code/game/machinery/vendors/vending.dm
As advertised by the title.
Less people confused about why they can't interact with things that seem to be turned on but actually aren't.
Compiled, smacked an APC with a captain ID and turned equipment off, observed the fading light signaling multiple vendors' last final moments of life until they are fed power noms again
:cl:
fix: Vendors now again visually turn off when they lose power
/:cl:
> Fixes vendors not updating icons when depowered

- code/modules/response_team/ert_outfits.dm
This PR adds a death alarm for the ERT Red Janitor.
This brings the ERT Red Janitor in line with all other Red Team members, who all currently have death alarms. ERT members should be valued the same, regardless of their assigned role on the team. This allows for other team members to know quickly, if a member is lost, in what is probably an already chaotic situation. 
Created an ERT Red Janitor and tested to see if their death alarm sounded when they died.
:cl:
add: added a death alarm to the ert red jani
/:cl:
> Adds a death alarm for ERT Jani Red

- code/modules/crafting/recipes.dm
Fixes an oversight where a category was left off of /datum/crafting_recipe/donk_box allowing for the crafting of empty Donk Pocket boxes in the crafting menu.
It fixes crafting for an item as it was intended to be.
Opened the crafting menu, confirmed that Donk Pocket box showed up in the proper category.
:cl:
tweak: Tweaked code allowing Donk Pocket boxes to appear in the crafting menu under MISC
/:cl:
> adds empty donk box to crafting menu

- code/modules/mob/mob.dm
Mice that try to respawn but fail, no longer lose their respawnability. Also does some minor refactoring. It also includes making mice not spawn in 1x1 holes with no escape (aka airlock vents). It also makes them similar to other vent-spawning mobs, and spawns them inside the vent, ventcrawling.
Losing your respawnability because you didnt wait exactly five minutes to try playing as a mouse again sucks. Fixes #18669.
See above
:cl:
fix: You can no longer lose respawnability when trying to respawn as a mouse
fix: Player mice will no longer spawn in areas with a single vent and being trapped because of it.
tweak: Player mice will spawn inside the vents now, like other vent-crawlers.
/:cl:
> Refactors becoming a mouse

- code/game/machinery/computer/communications.dm
Adds a 1 minute cooldown for changing the alert level at a comms console.
Players can currently change the alert level really really fast and it's really really annoying, borderline deafening and spamming chat.
Tried to change the alert level, got cooled down.
:cl:
tweak: The communications console now has a 1m delay between changes of alert level.
/:cl:
> Adds a cooldown for setting alert level through comms console

- code/modules/mob/living/simple_animal/friendly/farm_animals.dm
- code/modules/mob/living/simple_animal/hostile/mining/gutlunch.dm
Fixes gutlunch udders not properly GCing
Having two reagent datums exist in the same obj causes issues and some minor memory leakage (One was set on init, then overwritten on new), this is bad because:
```
[2023-03-22T20:26:13] Path: /obj/item/udder/gutlunch
[2023-03-22T20:26:13] 	Failures: 28
[2023-03-22T20:26:13] 	qdel() Count: 28
[2023-03-22T20:26:13] 	Destroy() Cost: 3.084ms
[2023-03-22T20:26:13] 	Total Hard Deletes 27
[2023-03-22T20:26:13] 	Time Spent Hard Deleting: 527.125ms
```
This PR repaths the cow udder and prevents the gutlunch from making "fake" reagent datums that don't really exist
Compiled, ran, milked some simple animals
> fixes gutlunch udders not properly GCing

- code/game/objects/items/devices/radio/headset.dm
Adds a qdel null to headsets on the syndikey ref
fixes #19324 
GCing is good.
> fixes syndikey gc issues

- code/modules/food_and_drinks/food/foods/baked_goods.dm
Adds a new TK interaction with pancakes
Takes four seconds of standing still, must be done purposefully by swapping hands and grabbing again, causes a low yield explosion and destroys the targeted pancakes. 
https://www.youtube.com/watch?v=XBlJmWfsgOM
More silly interactions are good and small and stupid details make SS13 endlessly replayable. I hope to god someone actually uses this in a traitor run because that would be so fucking funny and possibly effective. 
https://user-images.githubusercontent.com/96800819/224503069-e85cd20e-bab1-4c96-b87b-48e7a2395aa3.mp4
:cl:
add: You can now blow up pancakes with your mind
/:cl:
> blows up pancakes with mind

- code/modules/mob/living/simple_animal/slime/slime_life.dm
closes #20589 (not a bug, just poorly communicated)
the fact you're about to die due to becoming a slime popsicle probably should be communicated to the player
:cl:
tweak: Slimes get a message when they can no longer move due to temp changes
/:cl:
> adds a message notice that you can no longer move as a slime 

- code/modules/pda/PDA.dm
- code/modules/pda/app.dm
Address PDA sprites not updating correctly when removing ID after hot swapping with an additional ID. Fixes #20590
Refactors how PDA overlays are handled.  
It is nice when the sprites update correctly. 
Tested to see if the PDA sprite updated correctly after hot swapping and removing IDs. Checked to see if the PDA sprite updated correctly when receiving a notification. 
:cl:
fix: Fixes PDA ID sprites not updating after hot swapping and removing IDs
/:cl:
Special thanks to @Contrabang for guidance with this one!
> PDA ID fix

- code/modules/crafting/recipes.dm
Makes the list be properly assoc, so crafting doesn't runtime.
It specifically looks up indexes and requires a number, even if it's just 1.
Crafting should not runtime.
Eyeballs.
:cl:
fix: Fixed a runtime preventing the crafting of donk pocket boxes
/:cl:
> Fixed a runtime preventing the crafting of donk pocket boxes

- code/datums/keybindings/emote.dm
This fixes #18415, a small oversight where binding shake would cause two different emote outputs to occur. 
It makes it so the correct emote for the intended key bind is displayed.
Bound several of the emotes to different keys and tested for the correct outputs. 
:cl:
tweak: Tweaked the name of a key bind
/:cl:
> Fixes an oversight with head shake/shake keybind

- code/modules/food_and_drinks/kitchen_machinery/cooker.dm
Fixes a bug where the emagged deepfryer would try to deepfry a grab instead of the face of the person you are grabbing.
fix: #20677
Bug bad
Emag deepfryer
Grab Skrell
Deepfry Skrell's face, not the abstract grab
Smells like burnt fish.
:cl:
fix: Trying to deepfry someone's face no longer causes you to deepfry the grab instead.
/:cl:
> Emagged deepfryer no longer tries to deepfry grabs

- code/modules/supply/supply_pack.dm
This PR Fixes #20676, where certain stacked items were not appearing inside of cargo shuttle crates correctly.  
It fixes a bug, allowing for stacked items that are contained within cargo shuttle crates to spawn within the crates correctly. 
Tested two ways:
Ordered multiple crates at cargo that contained children of /obj/item/stack and tested to see if those items contained the correct amount and functioned properly.
Used the create crate verb to create crates that contained children of /obj/item/stack and tested if the items were functioning properly.
:cl:
fix: fixed a line of code allowing items to appear within the crates in the right amount
/:cl:
Credit goes to @Contrabang for providing a solution to this issue.
> Supply crate item stack fix

- code/game/gamemodes/cult/cult_mode.dm
- code/modules/mob/living/simple_animal/constructs.dm
- code/modules/mob/living/simple_animal/shade.dm
fixes this runtime `Runtime in cult_mode.dm,181: Cannot read null.faction`
Why the hell are we so reliant on current for stuff that really doesn't need to use current GNARG 
Common oldcoder L
Looked for runtime, no runtime
:cl:
fix: Dead constructs no longer count for total cult amount 
/:cl:
> fixes a cult construct death runtime

- code/game/gamemodes/cult/runes.dm
Makes revive runes not kick out the person being revived in rare cases
A revivable person shouldn't get kicked outta the round because they ghosted too fast
The more and more cult code I read the more and more I'm convinced this was more of a straight point compared to anything really adjusted to para. 
Compiled
:cl:
fix: Cult revive runes should no longer kick you out of your body if you're holding a movement key
/:cl:
> makes revive runes not kick out the dead in some cases

- code/game/machinery/rechargestation.dm
This PR changes the borg charger's maximum nutrition value to `NUTRITION_LEVEL_FULL` (550) as opposed to the hardcoded value 450. The decrement by one is because the maximum nutrition value is considered "fat", when presumably it is only meant to be "fat" when _above_ full (in other words, the hud icon would temporarily change to "fat" before changing back to full). This would be a change to the range logic in `/mob/living/carbon/human/proc/handle_nutrition_alerts` but I clamped the range in the charger code to keep the change as isolated as possible.
When IPCs leave a borg charger, their hunger immediately immediately changes, despite the HUD alert logic intended to remain in the 'full' state until the mob's nutrition value is in the "fed" to "well_fed" range. For forever I thought this …
> Properly charge IPC/IRCs in borg charger to full.

- code/game/objects/structures/mirror.dm
removes kidan and slime people from syndicate magic mirror
When I added the magic mirror for nukies, karma species were avoided for sanity, and for balance.
Most karma species (now karma is gone) are fine, vox and plasmamen currently are not in this list, and would be fine, but would need vox / plasmamen tanks there.
However, slime people and kidan, which are in the list before this pr, have to go. Slime people nukies would grant access of no bones for nukies, which would be incredibly strong. Kidan nukies get 20% less brute damage, which is why I was suggested to remove that.
Confirmed species did not show up
:cl:
tweak: Kidan and slime people are no longer valid nuclear agent species (again)
fix: Wizards can be vox / plasmamen again.
/:cl:
> Removes slime people and kidan from the syndicate M.A.G.I.C mirror

- _maps/map_files/generic/centcomm.dmm
- code/game/machinery/portable_turret.dm
Adds 4 turrets to the inside of the nukie ship. These turrets are weakened versions that only shoot bullets that deal 20 damage instead of 60, albeit a slight health buff from 80 to 100. I'm kind of split on whether to include the back 2 turrets, but I feel like the front 2 are good, feedback is appreciated. 
Its a bit silly having explorers break in every nuclear round and mess with the bomb in someway, even now that its tamper proof (please stop finding exploits). If we want to stop them from messing with it, we should go all the way.
Two turrets near the cockpit, 2 turrets near the nuke storage
Top turret range reaches down to about here
Turrets worked inside the ship, didnt target nukies, did target nanotrasen employees.
:cl:
add: The nuclear operative's ship now has 4 weak internal …
> Adds internal turrets to the nuclear operative ship

- code/_onclick/hud/constructs.dm
title
See reasoning in #20624 
:cl:
tweak: Constructs now have an intent hud
/:cl:
> gives constructs an intent swapping hud

- code/_onclick/observer_onclick.dm
- code/modules/mob/dead/observer/observer_base.dm
Ghost's follow link on their pointing now works. It also fixes ghosts being moved when they pointed to much. Middle clicking to point as a ghost will no longer be interpretted as a double click and move you around.
The link was broken and the middle click was janky.
Booted up 2 clients on a local server, made sure that both ghosts were able to click on eachother's pointing links.
:cl:
fix: Ghosts pointing messages in chat will now have working follow buttons
fix: Ghosts rapidly middle clicking will no longer be moved around and will only point
/:cl:
> Fixes some issues with ghosts pointing

- code/game/objects/effects/spawners/lootdrop.dm
- code/game/objects/items/weapons/bee_briefcase.dm
- code/modules/hydroponics/hydroponics_tray.dm
- code/modules/reagents/chemistry/reagents/medicine.dm
- code/modules/reagents/chemistry/recipes/medicine.dm
- code/modules/reagents/chemistry/recipes/others.dm
- code/modules/reagents/chemistry/recipes/pyrotechnics.dm
- code/modules/reagents/reagent_containers/bottle.dm
Progress towards #20532 
This PR renames strange reagent to lazarus reagent, both in the code and in name. It also makes the description a little more unique, though I'm not sure if anyone reads those.
"Strange Reagent" is a bad name for a chemical. It doesn't give any hint at what it actually does or reference anything. Take cryoxadone; while it's not a real medicine, its name - specifically, the prefix "cryo-" hints towards what it does. Capulettum is another example; it references Romeo and Juliet while still sounding like a real medicine. Styptic Powder is another good example of a name - it's literally a real medicine that does the same thing as it does in game.
However, "Strange Reagent" doesn't give any hints at all towards what it does. If you're playing for the first time as a …
> Renames Strange Reagent to Lazarus Reagent

- code/modules/reagents/reagent_dispenser.dm
most reagent dispensers are no longer automatically anchored. This applies to stuff like the fuel tanks and water tanks in maintenance. This does not apply to wall dispensers or the beer keg (because it's funny). 
So this was changed in a previous PR that allowed these to be anchored. Honestly I don't think this needs to be the case anymore, people putting all the tanks in one fuckoff area was still an issue after the PR went through and only stopped being an issue later down the line, and environmental combat is cool. Slip stuns are thankfully no longer a thing so water is infinitely less annoying now as well. 
I don't think this will affect balance much except give people more options (like a perma escapee running from sec) in niche situations. 
:cl:
tweak: most reagent …
> most reagent dispensers are no longer automatically anchored

- code/game/objects/items/robot/robot_upgrades.dm
Previously janiborgs could install the floorbuffer then VTEC to gain a speed boost equivalent to adrenals permanently.
Bug bad.
Install floor buffer
Install VTEC
Regular speed movement.
:cl:
fix: Janiborgs can no longer use floor buffer for massive speedboost.
/:cl:
> Janiborgs can no longer use floor buffer for massive speedboost

- code/modules/mob/living/simple_animal/hostile/syndicate_mobs.dm
Removes the point from the syndie depot NPC AI routine.
The verb queue system isn't meant for NPCs, and will throw a stack trace. Also, they're rude.
Got killed by depot NPCs.
:cl:
tweak: Syndie depot NPCs do not point at targets
/:cl:
> Syndie depot NPCs do not point at their fallen targets

- code/game/machinery/vendors/vending.dm
Adds better logging for vending machine crushes, noting who crushed who.
Admins would generally like to know who was responsible for someone else getting turned into a pancake.
splat
:cl:
fix: Vending machines now provide admins with logs of who shoved who into them.
/:cl:
> Improves logging on vending machine crushes

- code/modules/surgery/cavity_implant.dm
- code/modules/surgery/implant_removal.dm
Fixes #20578.
Bio-chip removal now uses **wirecutters** to remove implants, instead of a hemostat or crowbar.
Sealing up a cavity implant now uses a welder as the primary tool, with a cautery still working as a ghetto tool.
Surgeries should be consistent and not buggy, especially for robotics.
Tested surgeries on a created IPC, worked properly.
:cl:
tweak: IPC bio-chip removal now uses wirecutters on the removal step.
fix: Sealing an IPC's cavity implant now properly uses a welder as the primary tool, with cautery working as a ghetto tool.
/:cl:
> Fixes some tool interactions for IPC surgeries

- code/game/turfs/simulated/floor/chasm.dm
Fixes #19760.
Chasms will no longer be modified by explosions, as they are supposed to be... empty space.
Considering the existance of gibonite, it is not uncommon for explosions to happen next to chasms. Before they used to visually change into lattice/lava, which was dangerous as it was simply a (reportedly) visual change. You would still fall to your death if walking over the modfied tiles, giving you a false sense of security.
- Go down to lavaland, find and kill a tendril.
- Gibonite gaming.
- Drop down a couple of big explosions just to be sure.
- All chasm tiles remain the same.
:cl: GoR
fix: Chasms no longer show lattice/lava when blown up.
/:cl:
> Fixes chasms showing lattice or lava when affected by an explosion

- code/game/machinery/cloning.dm
- code/game/machinery/cryopod.dm
- code/game/objects/items/collar.dm
- code/game/objects/items/devices/radio/radio_objects.dm
- code/modules/mining/laborcamp/laborshuttle.dm
- code/modules/mob/living/silicon/ai/latejoin.dm
- code/modules/mob/new_player/new_player.dm
- code/modules/power/supermatter/supermatter.dm
- code/modules/projectiles/guns/energy/special_eguns.dm
- code/modules/security_levels/keycard_authentication.dm
Sets the follow target of the SM crystal's internal headset (yes, that is how indeed it works) to the crystal itself, andalso updates this for some similar implementations.
Should make clicking "follow" on the SM announcements do what you'd expect it to
set off a delam, followed it
:cl:
fix: The follow link on SM crystal (and some other) announcements should work more consistently. 
/:cl:
> Fix SM (and some other) follow links

- code/game/turfs/simulated/minerals.dm
Adds a blob act to ancient turfs
So these are used like walls on cerestation but a blob can't break them. Doesn't just seem unintentional but gives the blob a massive advantage on cerestation, an already huge map that blob loves
SMACK THE WALLS
:cl:
fix: ancient rocks on cerestation can now be destroyed by blob tiles
/:cl:
> adds a blob act to mineral/ancient turfs

- code/game/objects/items/robot/robot_upgrades.dm
- code/modules/reagents/reagent_containers/borghydro.dm
Buffs abductor cyborg medical module to affect the medihypo. Reduces Recharge time from 10->6 seconds, Recharge energy cost from 50->40, adds Corazone to the list of ingredients it can inject, and allows the hypo to pierce armor. 
Allows Corazone to be made and used when heart surgeries will be needed as abductors are around. Also allows for medical cyborgs to spend less time waiting for their chemicals to regen. Also allows for the cyborg hypospray to penetrate armor as a experimental change.
Spawned as a mediborg, injected people and saw the usual 10 second time and 50 energy cost. Applied the module, observed a new 6 second time, 40 energy cost, and corazone added to the list of chemicals. 
:cl:
add: Buffs abductor cyborg medical module to affect the medihypo.
/:cl:
> Buffs Mediborg abductor module to affect medihypo

- _maps/map_files/Delta/delta.dmm
- _maps/map_files/MetaStation/MetaStation.dmm
- _maps/map_files/cerestation/cerestation.dmm
- _maps/map_files/cyberiad/cyberiad.dmm
- code/datums/spells/knock.dm
- code/game/machinery/doors/airlock_types.dm
- code/game/machinery/doors/poddoor.dm
- code/modules/admin/misc_admin_procs.dm
Changes gamma armoury hatches from weird airlock subtypes to impassable blast doors, operated solely when the shuttle is moved.
Makes impassable blast doors unable to be pried when power is off. (why was this a thing?)
Being able to bypass armoury rwalls by tinkering with a single door is a no-no. This finally fixes it.
Tried prying blast doors
:cl:
tweak: Tweaked gamma armoury hatch to be a blast door
/:cl:
> Fixes gamma armoury hatch cheese

- code/__DEFINES/mob_defines.dm
- code/datums/components/spooky.dm
- code/datums/spells/lichdom.dm
- code/game/gamemodes/wizard/artefact.dm
- code/modules/awaymissions/corpse.dm
- code/modules/mob/living/carbon/human/human_mob.dm
- code/modules/mob/living/carbon/human/species/skeleton_species.dm
- code/modules/mob/living/simple_animal/hostile/mining/hivelord.dm
Companion and partial alternative to https://github.com/ParadiseSS13/Paradise/pull/20528
Adds brittle skeletons, a less powerful version that is more common.
Brittle skeletons heal 0.66 brute and burn per tick with milk (same as salglu when taken on average), as opposed to 4. They have no chance of healing a fracture, down from 5%. They do not have inherent low pressure or cold resistance, making spacewalks more difficult.
Adds lich skeleton, a subtype now used in wizard stuff to make it easier for balance tweaks in future.
Renames OG skeleton species to "Ancient Skeleton" to make it clearer that these things are stronk
Lavaland ashen skeleton corpses are now the brittle variant.
Roundstart dead skeleton spawners are now the brittle variant.
Getting an envy's knife or being a changeling …
> Balances skeletons by adding a subtype

- _maps/map_files/RandomRuins/SpaceRuins/abandonedzoo.dmm
- _maps/map_files/RandomRuins/SpaceRuins/deepstorage.dmm
- _maps/map_files/RandomRuins/SpaceRuins/derelict2.dmm
- _maps/map_files/RandomRuins/SpaceRuins/dj.dmm
- _maps/map_files/RandomRuins/SpaceRuins/moonoutpost19.dmm
- _maps/map_files/RandomRuins/SpaceRuins/onehalf.dmm
- _maps/map_files/RandomRuins/SpaceRuins/spacebar.dmm
- _maps/map_files/RandomRuins/SpaceRuins/syndie_space_base.dmm
- _maps/map_files/RandomRuins/SpaceRuins/ussp.dmm
- _maps/map_files/RandomRuins/SpaceRuins/wizardcrash.dmm
- _maps/map_files/RandomZLevels/evil_santa.dmm
This PR swaps out grill/window stacks with the appropriate window spawner for all space ruins (and `evil_santa.dmm`).
Part of map conformance changes needed to push #19875 along.
Added maps to space ruin config, spawned in and gave a pass over several ruins to ensure no weirdness.
Tech debt stuff, no changelog.
> Update all space ruins with window spawners.

- _maps/map_files/Delta/delta.dmm
- _maps/map_files/MetaStation/MetaStation.dmm
- _maps/map_files/cyberiad/cyberiad.dmm
Fixes SOP bookcases not spawning with books inside by using the correct /obj/structure/bookcase/sop path.
Books should be inside BOOKcases.
BEFORE
AFTER
- Compiled and verified a few sop bookcases, they all loaded with the books inside.
:cl:
fix: Fixed SOP bookcases not spawning with books inside
/:cl:
> Fixes SOP bookcases not spawning with books inside

- code/game/gamemodes/cult/cult_structures.dm
Cult structures now have a cooldown before being able to produce items upon creation. So making a flask of unholy water or blade takes time and isnt instant.
A rather exploited mechanic were I've seen players carry around 50 runed metal to make instant production factories mid fight. Using said factories to instantly restock on all their spent viel shifters, unholy water, shielded robes, and then proceeded to run back in and do it over and over. Not only is this pretty unhealthy, its also poorly balanced. This slows down cult in their arms production as well as giving a window before the cult war begins.
tested it in server
:cl: Octus SabrelML GDNgit
tweak: Cult production structures now have a delay upon creation before producing anything
/:cl:
> Functional cult structures have a cooldown upon creation

- code/game/machinery/Sleeper.dm
- code/modules/atmospherics/machinery/components/unary_devices/cryo.dm
- code/modules/reagents/chemistry/machinery/chem_dispenser.dm
- code/modules/reagents/chemistry/machinery/chem_heater.dm
- code/modules/reagents/chemistry/machinery/chem_master.dm
- code/modules/reagents/chemistry/machinery/pandemic.dm
- code/modules/reagents/chemistry/machinery/reagentgrinder.dm
When you interact with a chem or medical machines with harm intent and a container in your hand, you only spill the contents of the container over the machine. Previously you spilled the contents and placed the container in the machine.
Following machines are fixed:
- Sleepers
- Cryo Cells
- Chem Dispensers
- Chem Heater
- Chem Master
- Pandemic
- Reagent grinder
Fixes Issue #18562 and fixes a bug.
Compiled and run.
:cl: 
fix: You now only splash reagents over chem and medical machines with harm intent.
/:cl:
> Fixes a bug with chemistry and medical machines.

- code/game/gamemodes/game_mode.dm
- code/game/gamemodes/revolution/revolution.dm
- code/modules/mob/living/living.dm
Reverts part of #20327
Revolution is broken due to this, transit_z is called upon roundstart spawning in
This is a partial revert
:cl:
fix: Revolution not instantly end
/:cl:
> fixes revolution not working

- code/modules/atmospherics/machinery/components/unary_devices/cryo.dm
This is a change to the text a user inside a cryopod gets when injecting from inside.
It was changed from 2 minutes to 1 minutes in #523, but the text was never updated.
Displays correct information
1. Start cryo cell.
2. Disable Auto-eject healthy occupants.
3. Smite self.
4. Enter cryo cell.
5. Upon going unconcious, eject occupant via right click.
6. Read that the release sequence will take one minute.
:cl: ppi
fix: Updates the cryo pods release sequence to display the correct time.
/:cl:
> Updates the cryo pods release sequence to display the correct time

- code/modules/assembly/voice.dm
Fixes that when a clown sets a message for a voice analyzer the voice analyzer only activates when the clown says the message, no one else, and they said it EXACTLY the same as the set message
Fixes others not being able to interact with voice analyzers set by a clown and having to say it exactly the same is infruiating
Recorded message as clown -> said something containing the recorded message as a clown -> it works
Recorded message as clown -> said something containing the recorded message as a non-clown -> it works
and vice versa
:cl:
fix: Fixed others not being able to activate voice analyzers set by a clown
fix: Fixed having to say a voice analyzers prerecorded message exactly the same in order for it to activate
/:cl:
> fixes voice analyzer issues with clown´s different font speech

- code/modules/projectiles/guns/projectile_gun.dm
makes ammo not forcemove a qdeleted object 
Makes ammo without a casing not play a sound effect of the casing being dropped
This is bad
```
[2023-03-26T21:24:45] QDEL: Path: /obj/item/ammo_casing/caseless/laser
[2023-03-26T21:24:45] 	Failures: 2543
[2023-03-26T21:24:45] 	qdel() Count: 3189
[2023-03-26T21:24:45] 	Destroy() Cost: 240.508ms
[2023-03-26T21:24:45] 	Total Hard Deletes 2543
[2023-03-26T21:24:45] 	Time Spent Hard Deleting: 7235.51ms
```
it worked
:cl:
fix: Caseless ammo no longer plays the drop ammo sound effect on being fired
/:cl:
> makes caseless ammo GC

- code/modules/mob/living/silicon/robot/robot_mob.dm
title
Yall ever actually played as a xenoborg? Shit sucks. I'm working on a rework right now but I feel actual pain for anyone that has had "viagra spray" as the main form of entertainment 
yes
:cl:
tweak: Xenoborgs can also be any standard borg module as well as hunter
/:cl:
> xenoborgs can now select any normal borg module as well as the hunter module

- code/game/objects/items/collar.dm
Lets petcollars better support ERP (Extremely Rotated Pigs).
Setting a petcollar's name to `dinnerbone` and putting it onto a mob will rotate the mob 180 degrees.
(Also, setting a collar's name to `jeb_` will cause the mob to cycle rainbow colors)
Silly
https://user-images.githubusercontent.com/89928798/229177287-0b63b6ab-1409-4e60-b5f4-816a918817cd.mp4
> Improves ERP with petcollars

- code/modules/mob/dead/dead.dm
- code/modules/mob/dead/observer/observer_base.dm
When testing I noticed that ghosts call `Moved` twice while moving. This might lead to some odd behaviour. I've not yet noticed any changes by removing the second moved call though.
You only moved once when moving :)
Moved around as a ghost for a while. Checking parallax etc.
Didn't notice a functional change
> Ghosts now don't call moved twice

- code/modules/reagents/chemistry/reagents/medicine.dm
Changelings are no longer gibbed by sr. 
~~SR now revives changelings regardless of damage taken and has different effects when used below a gibbing health threshold:~~
~~The changeling will first start to jitter like it's going to gib, then revive. This is a full aheal so limbs and organs will be replaced, after that the changeling will take 0-10 burn and brute damage, 20 clone damage, and 50 stamina damage, and gain 40 chemicals to use. Then the changelings external organs all have a 20% chance to become necrotic, which basically forces them to revive at some later point due to the effects of necrosis letting SR still have some impact.~~
I've gotten back into sec and a couple of things about changelings have become abundantly clear
1. Clings are only good at combat, literally fails at …
> Changelings are no longer gibbed by SR

- code/game/objects/items/robot/robot_upgrades.dm
- code/game/objects/items/weapons/storage/bags.dm
- code/modules/research/designs/mechfabricator_designs.dm
Adds the trash bag of holding upgrade for janiborgs, printed at the mechfab for the same material/research costs as the original trash bag of holding.
Its odd that this upgrade is available for janitors but not janiborgs.
It being available to them would be another cool thing to ask robotics for and shouldnt have much of an impact on balance.
- Maximized all research levels to maximum
- Inserted the materials into the mechfab and made the trash bag upgrade
- Inserted it into the janitor cyborg and picked up A LOT of trash
:cl:
add: Added the trash bag of holding upgrade for janiborgs
/:cl:
> Adds the trash bag of holding upgrade for janiborgs

- code/game/objects/items/weapons/twohanded.dm
fixes #20754
Wielded items should require being wielded to gain those effects
Also fixes a runtime
:cl:
fix: You can no longer one-handed use push brooms
/:cl:
> fixes #20754

- code/controllers/subsystem/air.dm
Makes atmos overlays ignore the turf's set color.
Fixes #20688
Used cerulean prints, opened a canister.
:cl:
fix: Visible gasses do not inherit the tile's color they occupy
/:cl:
> Gas overlays ignore the turf's color

- code/__DEFINES/layers.dm
- code/game/objects/effects/decals/Cleanable/fuel.dm
- code/game/objects/items/devices/scanners.dm
- code/game/objects/structures/aliens.dm
- code/game/turfs/simulated/floor/plating.dm
- code/game/turfs/simulated/floor/transparent.dm
- code/game/turfs/simulated/minerals.dm
- code/game/turfs/turf.dm
- code/modules/atmospherics/machinery/atmospherics.dm
- code/modules/atmospherics/machinery/pipes/pipe.dm
Fixes issues introduced by [PR#20503](https://github.com/ParadiseSS13/Paradise/pull/20503), the t-ray scanner now functions properly and you can once again see pipes and wires in StrongDMM. Fixes #20722. Fixes #20738. Fixes #20760. This PR is an alternative to [PR#20721](https://github.com/ParadiseSS13/Paradise/pull/20721), do not merge both of them.
Fixes. It's better than [PR#20721](https://github.com/ParadiseSS13/Paradise/pull/20721) because it maintains functionality that I require for [Pulse Demon](https://github.com/ParadiseSS13/Paradise/pull/20577), where the other does not.
Tested the t-ray scanner (and goggles) and StrongDMM.
:cl:
fix: t-ray scanner works again
/:cl:
> Fixes t-ray scanners and map editing

- code/game/objects/items/weapons/garrote.dm
- code/game/objects/items/weapons/handcuffs.dm
Halves the volume and range in which you can hear the sounds of zipties/cuffing.
Also reduces the volume of garroting someone and makes it inaudible through walls.
You should not be able to hear cuffing from SEVENTEEN TILES AWAY through METAL WALLS. This should honestly apply to screamspam and such as well but I dont want to refactor the entirety of sound because hell no.
Stealth should be a factor in SS13. The sound system we have GREATLY hampers it.
Cuffed a lot of skrell.
:cl:
tweak: Tweaked the volume and sound range of cuffing, reducing both by half.
tweak: Tweaks the sound range of garroting someone as well as making it respect walls.
/:cl:
> Halves Cuffing + Garrote Sound Range and Volume

- code/modules/reagents/chemistry/reagents/drinks_reagents.dm
- code/modules/reagents/chemistry/reagents/food_reagents.dm
Merges the defintion of Hot Chocolate reagent from `food_reagents.dm` into the one in `drinks_reagents.dm` (as well as the associated `on_mob_life()` proc definition).
Bar drinks using Hot Chocolate actually gain the proper sprite/name/description.
Less crimes against coders.
Grabbed a hot chocolate drink from the drinks vendor, extracted only the Hot Chocolate reagent, put in a bar glass - noted the correct drink sprite and name.
Fed the glass to a vulpkanin - noted it still raises their body temperature and poisons them.
:cl:
fix: Hot Chocolate bar drinks now have the correct sprite/name/description.
/:cl:
> Removes a duplicate definition of Hot Chocolate

- code/modules/admin/verbs/freeze.dm
- code/modules/power/supermatter/supermatter.dm
Allows the admin freeze verb to also affect Supermatter Crystals, both the primary engine and shards, which prevents it from processing (and thus decreasing in integrity). Additionally, if frozen while in the 30-seconds before delamination, it returns the crystal to a single damage point before the explosion point is reached, so that the timer fully restarts after being unfrozen. Nothing changes to the integrity upon being unfrozen, so admins can change it back up while frozen if they determine the SM was sabotaged by a griefer or whatnot. 
It also gives a message over engineering comms (where the SM normally announces) indicating that an unknown force has frozen the SM, and overlays the crystal itself with an adminfreeze overlay. Hopefully this is sufficient to indicate to players that …
> Allows admins to freeze the SM

- code/game/objects/items/weapons/garrote.dm
Fixes [#20674](https://github.com/ParadiseSS13/Paradise/pull/20674) Garrote tweaks.
It now has less range/doesnt go through walls, like it was intended.
Only the suicide playsound() was changed by the author, not the one played during attack.
- Did garrote a few skrells
:cl:
fix: Garrote sound now works like it was intended
/:cl:
> Garrote sound now works like it was intended

- code/modules/clothing/shoes/misc_shoes.dm
This does the following to the clown traitor item slip shoes:
- **Performing a tactical slip no longer drops held items:** This was a dumb oversight I had when I added this, it is very crippling and makes the item annoying to use.
- **The shoes start with their waddle-dampeners active (no slowdown and waddling), you can still de-activate them with ctrl-click:** Some people do not know you can turn off the slowdown with ctrl-click and instead opt to not use the item. Is it baby-proofing? yeah. But I imagine that 9/10 you wont want slowdown anyway.
- **Removes the visible message "X slips forward!" when performing a slip:** There was really no reason for this message, regular slips don't have a chat message, this one shouldn't either.
- **Slips can now pass through tables:** Adding this as …
> Tweaks and Fixes to Slip Shoes

- code/modules/reagents/reagent_containers/borghydro.dm
Total chemicals in the base borg hydro brought down to 50 from 100, chem restoration reduced
Total chemicals in the syndicate borg brought down to 30 from 60, chem restoration reduced
So uh, I was expecting that PR to be tmed rather than full merged, it wasn't so I gotta do this here. Right now the borg hydro is broken out the ass, you recharge chemicals faster than you can actually use them in most cases and even if you are, you can wait under a minute to get all your chemicals back. Everyone in your general area getting healing + complete pain slowdown immunity is absolutely crazy and there needs to be some restriction to it. 
Compiled and filled a skrell with chemicals
:cl:
tweak: Cyborg hypospray's total chemicals have been halfed, restoration rate for those chemicals reduced 
/:cl:
> Balances the borghydro

- code/game/objects/items/stacks/stack.dm
The `item_state` (on-mob inhands) for stacks are just the `icon_state`, this is not what we want for dynamic `icon_state` as we just want the base single item sprite. We don't have the dynamics for on-mob inhands so they were vanishing.
Materials vanishing with more than one
Spawned, held stacks with 50 things in and looked at them.
:cl:
fix: Fixed stacks with dynamic icons states vanishing in-hand when the amount was more than one
/:cl:
> Fixes stacks with dynamic icon states vanishing in-hand when amount > 1

- code/modules/reagents/reagent_containers/syringes.dm
Stepping over syringes without protection injects the chemicals in the syringe in you.
!!!doesn't apply to genetics dna injectors!!!
!!!you wont get injected if you have shoes/fly/float/are buckled/are an IPC/are wearing something that covers your feet like a hardsuit/are pierce immune!!!
Kinda funny.
Promotes managing your waste disposal well.
https://user-images.githubusercontent.com/48032385/232134126-50767118-c958-40c5-9b61-cc1a60794740.mp4
1. Waited for code to compile.
2. Stepped over a bunch of syringes.
3. Code finished compiling, tried it in-game.
4. Tested with golems, xenos, IPCs, humans, humans with shoes, humans with hardsuits, humans crawling.
:cl:
tweak: Stepping over syringes without protection injects you their chemicals.
/:cl:
> Walking over syringes without protection injects

- _maps/map_files/RandomRuins/SpaceRuins/syndie_space_base.dmm
Adds two sets of doors to the TEG room, and where you spawn on the syndicate research base.
I have seen quite a few times people flooding the entire syndicate base with plasma, from a single small slip up, these new doors, should at least help in the 'entire' part. 
compiled, ran, checked the doors out, there were doors. 
:cl:
add: Adds two sets of doors in the syndicate research base to assist in containing plasma floods.
/:cl:
> Adds some doors to syndi research base

- code/_onclick/click_override.dm
- code/modules/antagonists/changeling/powers/tiny_prick.dm
- code/modules/mob/living/living.dm
Fixes clingstings not GCing, fixes clingstings runtiming in destroy
This is a mob var why the hell are we clearing this on a action datum delete... Also current is actually nulled now so
Guess who found out that mobs with antag datums aren't properly GCing as well! But yes this works
> makes clingstings GC

- code/_onclick/click.dm
- code/_onclick/click_override.dm
Middle click overrides no longer also override alt click if the middle click action fails to resolve
When you're using one of the few middle click overrides in the game (Adminstuff, Cling stings, power gloves), you probably expect this just to be middle click, right? Well it also covers alt-click which causes a whole bunch of issues with alt-click keybinds like looking in your bag or crawling into vents, this sucks so if it fails let's just have it do alt-click things. 
~~If you do not have a mouse 3 option for any reason, good time to speak up as well. ~~
Forgot trackpad users
:cl:
tweak: Middle click override actions with Alt-click no longer trigger if the actual ability fails to resolve (you can now ventcrawl with a sting out)
/:cl:
> middle click overrides no longer also override alt-click if the middle click action fails to resolve

- code/modules/mob/living/silicon/robot/robot_mob.dm
- code/modules/response_team/ert.dm
This PR makes it so robot/ert/red spawned by the game panel spawn with the ability to choose the Security module, without changing how cyborgs spawned as an ERT work - their ability to select a module is tied to whether the admin spawning the ERT enabled the security module. This is done by inversing the way the security module being allowed is done, making it so the subtype has the module by default but removing it if the security module is not selected.
Admins spawning in red ERT borgs have to do some real fanangling to get them to select the security module as the way the code implements it is by force changing the available modules as the team spawns. This way now, if an admin spawns a red ERT they will by default have the Security module as an option. If an admin wants to spawn borgs …
> Allows Red ERT Borgs spawned through the game panel to select the Security Module

- code/game/objects/structures/kitchen_spike.dm
Enabled an alternative method of moving mobs onto meat-spikes. You can now click-and-drag in addition to the old method. (The old method was use grab intent to grab, then click the meat-spike similar to "tabling")
I also added a message in chat when you initiate the action, so that a potential victim can see the message and react.
This is more in line with other similar actions such as: buckling someone to a chair or bed, stuffing someone in disposals, or putting someone in a gibber.
This is especially important as chef is a role intended for beginners, so making chef-related actions more intuitive will help beginners learn quickly and not get frustrated.
- Should I add a message to admins when a player slams someone onto a meat spike? This is what the gibber does, for example.
- Should I …
> Allows click-dragging onto meat spikes

- code/game/machinery/floodlight.dm
- code/modules/supply/supply_packs/pack_emergency.dm
Refactors the tool interaction code as well as some power drain code.
Adds sounds to tool interactions.
Lowers Light range from 20, to 10(about one and a half screens)
Increases the power draw from 5, to 30(around 11 minutes of use for high capacity cell)  
Adds detailed inspections to show that you can remove the cells from the floodlight, and if it lacks a cell, or is out of power.
And lets you buy more floodlights from cargo, 250 credits, for a single one. 
As of right now, floodlights are absurdly old, powerful, and not very intuitive, this PR (hopefully) lowers how stupidly strong they are against two antag sub types they directly counter, and makes them more usable for power outages, as well as makes it a little more easy to figure out how to replace the cells. 
Booted up local …
> Freshens up floodlights to not be 10 years old

- code/game/mecha/combat/gygax.dm
- code/game/mecha/combat/marauder.dm
- code/game/mecha/equipment/tools/other_tools.dm
- code/game/mecha/mecha.dm
- code/game/mecha/mecha_actions.dm
- code/modules/research/designs/mechfabricator_designs.dm
adds the mecha ion thruster, a new exofab made mecha upgrade 
made with 15k metal, 3000 plasma, and 6 engineering and two other level 5s
Takes 20 units of charge per processing cycle to use (roughly 2 seconds) + the movement per tile power (This means that if you're going fast you're gonna get DRAINED)
~SPACE MECHS!~
Gives people a new way to ball with space combat, sucks currently so giving people more options will lead to ~less space clings~ more options in combat
Also pods were cool concept wise and this is just cooler pods imo
It works
:cl:
add: Ion thrusters for mechs are now available at RND
tweak: all previous mechs with a natural ion jetpack now start with one as equipment
/:cl:
> adds the mecha ion thruster

- code/modules/atmospherics/machinery/airalarm.dm
- code/modules/power/apc/apc.dm
This adds the ability for crewmembers with access to alt-click to unlock or lock an APC or Air Alarm.
It also adds an examine text that tells you the state of the APC or Air Alarms lock.
This functionality has existed for secure lockers, so why not at it to APC and Air Alarm, and not having to swipe your ID to unlock things.
https://user-images.githubusercontent.com/21987702/228848508-e168480c-52d0-4bb5-a279-503f22820f20.mp4
See Images of changes
:cl: ppi
add: Allows crewmembers with access to Alt + Click to unlock APC and Air Alarms.
add: Crewmembers can now examine APC or Air Alarms to see their lock status.
/:cl:
> Allows human mobs to alt+click to unlock APC and Air Alarms

- code/game/objects/items/weapons/cigs.dm
- code/game/objects/items/weapons/storage/fancy.dm
Fixes [#20734](https://github.com/ParadiseSS13/Paradise/issues/20734)
Custom rollies made with items from the drying rack will no longer magically have 40u of nicotine in them.
Not all of us want to be addicted to nicotine when we smoke our AppleCigs(tm)
Rolled a dried apple, got obesity instead of addiction.
Spawned rollies (like those from Midori packets or maints) still have nicotine.
:cl:
fix: Custom rollies no longer contain magic nicotine.
/:cl:
> Fixes custom rollies having nicotine by default

- code/modules/admin/misc_admin_procs.dm
Admin announcements now more obviously alert players, a window flash and a bwoink sound effect are now added
Believe it or not, these are easy to miss and have been missed by many. When an admin sends out an alert it's almost always for time sensitive stuff, like "Don't worry about this guy they got an aheal" or "please stop griefing the shuttle", people should 100% be aware an admin sent this out and a window flash + sound effect should do the trick.
:cl:
tweak: A window notice and sound are sent out when an admin uses the announcement command 
/:cl:
> admin announcements now more obviously alert players
