ParadiseSS13/Paradise

_maps/map_files/cyberiad/cyberiad.dmm, code/game/objects/items/weapons/misc.dm
Turned point of sale into a phone subtype.
Fixes point of sale description.
Broken descriptions are bad.
Having it become a proper item avoids repetition and makes it easier to be used in other places.
BEFORE
AFTER
- Verified the item description, all looks good.
:cl:
spellcheck: Point of sale description has been fixed
/:cl:
=> Fixes point of sale description

_maps/map_files/Delta/delta.dmm
Changes the kitchen goat to be Pete subtype.
Pete is the chef pet, not a random goat (and because thats the standard for box/meta)
- Gave Pete a hug, he looks like Pete
:cl:
tweak: Delta station: kitchen goat is now pete
/:cl:
=> Return of  Pete, delta station edition

code/datums/components/surgery_initiator.dm, code/modules/surgery/organs/organ_external.dm
Fixes some emergent issues with prosthetic robot limbs. If a robot leg got surgeryized into a prosthetic, it wouldn't end up getting its surgery initiator activated so it'd still try to start human organ surgeries.
Being able to start a reattachment surgery by just applying the limb is a nice QoL thing, it shouldn't have weird edge cases like this where it doesn't work.
- Got a vulp
- Amputated their left leg
- Applied a `robot_parts` left leg
- sliced it until it came off
- applied the same leg again
- noted that the surgery procedure started as it should
:cl:
fix: You can now properly apply prosthetic limbs to start re-attachment surgeries.
/:cl:
=> [GBP: NO UPDATE] Fixes robotic surgery issues

code/game/machinery/washing_machine.dm, code/game/objects/structures/bedsheet_bin.dm
Fixes washing machine bedsheets icons not updating properly by making them update their item_state. 
Fixes https://github.com/ParadiseSS13/Paradise/issues/18370
- Spawned different colors bedsheets, all good.
- Used common bedsheets with crayons on the washing machine, all good.
:cl:
fix:  Crayon bedsheets colors are correct now
/:cl:
=> Fix #18370 Crayon bedsheets colors are correct now

code/game/machinery/cloning.dm, code/game/objects/items/weapons/defib.dm, code/modules/hydroponics/grown/replicapod.dm, code/modules/reagents/chemistry/reagents/medicine.dm
Adds SSblackbox logging for revival
More data is good, revival data is good.
Compiled (Unable to test the revival pod method due to requiring 2 clients, should work however)
NPFC
=> Adds SSblackbox logging for revival

code/game/objects/items/stacks/rods.dm, code/game/objects/items/stacks/sheets/glass.dm, code/game/objects/items/stacks/sheets/leather.dm, code/game/objects/items/stacks/sheets/mineral.dm, code/game/objects/items/stacks/sheets/sheet_types.dm
Adds the briefcase and card box as leather recipes.
Includes some recipes lists  and reorganizes leather, plastic, cloth, minerals, cardboards and wood recipes.
The briefcase and card box are supposedly both made of leather, it would make sense  being able to make them with it.
Having organized recipes is good for locating your desired item.
- spawned all sheets, got the added items and verified all recipes, all look good.
:cl:
tweak: Briefcases and card boxes now can be made using leather
/:cl:
=> Adds briefcase/card box as leather recipes and reorganizes other recipes

code/datums/datacore.dm, code/modules/mob/living/silicon/ai/ai.dm
Uses get_id_photo instead of getFlatIcon (wich didnt work) for the holograms.
Fixes https://github.com/ParadiseSS13/Paradise/issues/13967
- Selected crewmembers to use as hologram.
- Did swap between holograms, verified directions, all looks good.
:cl:
fix: AI crewmember hologram now works properly
/:cl:
=> Fixes #13967 AI crewmember hologram now works properly

code/modules/reagents/chemistry/holder.dm
mobs that cant process a reagent wont get on_mob_add/delete called on them
bugs are BAD
gave a skrell meth, speed
gave a IPC meth, no speed
gave an IPC ultralube, speed
:cl:
fix: fixed meth giving IPCs speed and ultralube giving organics speed.
/:cl:
=> fixes chems giving speed boosts to the wrong people

config/names/nouns.txt
Removes a word from nouns.txt
Words like this shouldn't be anywhere near our codebase
NPFC
=> Removes a word from nouns.txt

code/modules/mining/lavaland/loot/tendril_loot.dm
The lavaland lava boat no longer ignites you when you ride in it, by making you temporarily lava immune while you're on it.
Also reduces the message spam if you use it on the ground.
This seems to have been intended in https://github.com/ParadiseSS13/Paradise/pull/6350, with it being eventually implemented once lava tiles were simulated. (Shoutouts to coolrune for pointing this out).
Well, it's been almost five and a half years since then. Better now than later.
https://user-images.githubusercontent.com/89928798/196016135-fd86a218-7026-4bbb-800b-b22aea4737de.mp4
See video.
:cl:
tweak: The lavaboat now properly protects you from lava.
/:cl:
=> Lavaboat now doesn't burn you when you ride it over lava

code/modules/mob/living/simple_animal/parrot.dm
It fixes a possibly emersion breaking issue. With a single line of code!
I tested resting, as well as sleeping, also tested to make sure it caused no issues. 
Fix: Poly can no longer fly while sleeping.
=> Poly no longer can fly while resting, and sleeping!

code/datums/diseases/kingstons.dm
Thier becomes Their 
Spelling good
compiled
:cl:
spellcheck: Fixed a spelling mistake in advanced kingstons
/:cl:
=> Fixes a spelling error in advanced kingstons

_maps/map_files/MetaStation/MetaStation.dmm
Removes a duplicated vendor where there should only be one
Two of the same vendor on the same tile is not good, and slightly confusing
Complies, vendor is gone
:cl:
fix: Removes a duplicated vendor from metastation
/:cl:
=> Fixes a duplicated vendor on metastation

code/modules/mob/living/simple_animal/friendly/mouse.dm
Tom now uses his custom description instead of generic mouse one.
Removed icon_state for gray mouse since its already set.
Tom should be using his custom description, not a generic one.
- Took a look into other mouses icons and descriptions, all look good.
:cl:
fix: Tom now has the correct description
/:cl:
=> Fixes Tom description

code/modules/mob/living/carbon/human/species/machine.dm, code/modules/mob/living/simple_animal/slime/life.dm
Slimes now ignore IPCs as they arent full of delicious meat to consume horribly.
Using a big-ass slime as a body shield to prevent your hitbox from being hit is gross. IPCs will be ignored by slimes.
Abused IPCs with (emotional neglect from) slimes until horizontal.
:cl:
tweak: IPCs are now ignored by slimes.
/:cl:
=> IPCs are Now Ignored by Slimes

code/modules/reagents/chemistry/reagents/toxins.dm
title.
fixes #19368
its gonna irradiate you if you are made of metal or flesh. bugs R bad
ate radium as an IPC, VV, saw brain damage.
:cl:
fix: IPCs now process radium
/:cl:
=> Radium is now processed by IPCs

code/_onclick/click_override.dm, code/modules/clothing/gloves/color.dm
Fixes a power gloves exploit
It fixes a power gloves exploit, which is bad
I tried to use the power gloves exploit, and I could not use the power gloves exploit
N/A
=> Fixes a power gloves exploit

code/game/gamemodes/blob/blobs/blob_mobs.dm, code/game/gamemodes/blob/overmind.dm
Adds ghost follow links to blobbernaut/overmind conversations. As an observer, you'll see this link to jump to the blob or naut who's speaking.
As a ghost, it's very nice to be able to follow who's talking in chat, and this is one of the locations that's notably missing a follow link.
- Spawn as blobbernaut
- Open the textbox
- type something
- ghost mid-typing
- send
- see message pop up with follow link
- tada
:cl:
tweak: Blob/bernaut telepathy now has a ghost follow link for observers.
/:cl:
=> Add ghost follow links to blob telepathy

code/game/objects/effects/spawners/lootdrop.dm
Adds cloth to maintenance loot, with a weight of 40
Its quite useful for things like bags, blindfolds, rags, and improvized gauze. Its quite accessible through stuff like medical, arrivals lockers, some stations have a little bit of it in maints, and botany. Having it be randomly around the station and not in any particular place is quite useful.
I think 40 is a good weight because its found about as often as a wrench or proximity sensor, meaning you can find about on average 8-11 of them on the map (tested on cyberiad). I also think 3 pieces of it is useful, because you can use it to make a blindfold, or halfway to making a bag.
Loaded up cyberiad and went maint looting, found about 10 stacks of cloth. 
:cl:
add: Cloth rolls can be found in maintenance.
/:cl:
=> Adds cloth to maintenance loot

code/game/gamemodes/malfunction/Malf_Modules.dm
Uses the camera update_remote_sight proc wich handles properly the xray/nightvision updates.
Fixes https://github.com/ParadiseSS13/Paradise/issues/12922
- Spawned a malf AI and purchased the module, night vision has been given.
:cl:
fix: Malf AI: upgrade camera network module is now properly giving night vision
/:cl:
=> Fixes #12922 Malf AI camera upgrade is now giving the ai night vision

code/game/machinery/doors/airlock_electronics.dm, code/game/machinery/doors/firedoor.dm, code/game/machinery/firealarm.dm, code/game/objects/items/devices/flashlight.dm, code/game/objects/items/devices/geiger_counter.dm, code/game/objects/items/devices/radio/headset.dm, code/game/objects/items/devices/radio/intercom.dm, code/game/objects/items/devices/radio/radio.dm, code/game/objects/items/devices/scanners.dm, code/game/objects/items/devices/taperecorder.dm, code/game/objects/items/tools/crowbar.dm, code/game/objects/items/tools/multitool.dm, code/game/objects/items/tools/screwdriver.dm, code/game/objects/items/tools/welder.dm, code/game/objects/items/tools/wirecutters.dm, code/game/objects/items/tools/wrench.dm, code/game/objects/items/weapons/extinguisher.dm, code/game/objects/items/weapons/flamethrower.dm, code/game/objects/items/weapons/paint.dm, code/modules/assembly/voice.dm, code/modules/atmospherics/machinery/airalarm.dm, code/modules/food_and_drinks/drinks/drinks/drinkingglass.dm, code/modules/food_and_drinks/drinks/drinks/shotglass.dm, code/modules/hydroponics/hydroitemdefines.dm, code/modules/mining/equipment/mining_tools.dm, code/modules/power/cable.dm, code/modules/power/lighting.dm, code/modules/reagents/reagent_containers/glass_containers.dm, code/modules/research/designs/autolathe_designs.dm
Tweaks multiple autolathe designs costs, mainly tools and flamethrower.
Full list included here: https://docs.google.com/spreadsheets/d/1wwWD1Ca927MANKbilkPInMrTsRpSrNFD9T2OTQYk1Xw/edit?usp=sharing
Cost tweaks suggestions of any items are welcome.
Multiple autolathe items are extremely cheap even without upgrades (full upgrade is 12,5% of the original cost).
Giving them non laughable costs and balanced with everything else we have is good.
- Did print and verify some items costs, all looks good.
:cl:
tweak: Multiple autolathe design costs have been tweaked
/:cl:
=> Tweaks to autolathe design costs

code/modules/mob/living/carbon/human/update_icons.dm
Fixes golems that are not adamantine to have hands that are.
But I'll say this right at the start, this is not the greatest solution if admemery gets involved, but since golems should not be able to have prosthetics limbs under normal circumstances since they cannot lose their limbs at all + you cannot augment them, this should be fine?
Could only think of this solution since golems have a variable that decides what color their body will be, recoloring their icobase, which is adamantine by default. Using anything other than icobase wouldn't work as far as I know?
Fix :)
before: 
after:
Spawned a golem before the fix, and after
Arranged images in `Images of changes`
:cl:
fix: Fixed all golems having adamantine hands.
/:cl:
=> [GBP: No update] Golem hands fix, probably

code/game/objects/items.dm
Adds a helpful comment saying what `item_state` actually does and how it behaves.
I spend way too long going through the many references of `item_state` to find out how it worked. This comment would have saved me the trouble
N/A
=> Add a comment for item_state

code/modules/mob/living/simple_animal/bot/medbot.dm
Cleans up and refactors some Medbot code, fixing a few bugs along the way.
Readable and working code is good to have
Spawned in a Medbot and several Unathi, gave them various kinds of viruses (visible, stealthy, harmless) and damage, made sure all of it worked as expected with no runtimes. Loaded some custom medicine beakers into the Medbot to make sure they interact as intended with the rest of the system.
:cl:
fix: Medbots no longer require you to have other kinds of damage before they offer disease treatment
fix: Medbots no longer ignore your other diseases if the first one they analyzed did not meet their treatment criteria
fix: Medbots no longer ignore their loaded beaker when treating diseases
fix: Medbots' disease treatment criteria are now consistent between analyzing patients …
=> Small Medbot patient analysis and injection refactor

code/modules/crafting/recipes.dm, code/modules/projectiles/ammunition/ammo_casings.dm
This PR removes the very un-used Laser Slug techshell which was craftable under the ammunition tab of the crafting menu and instead replaces it with a Lasershot techshell, crafted with the same recipe. As opposed to simply firing a laser out of a shotgun (which was very weird and significantly worse than just using a laser gun), it now fires 8 projectiles of 5 burn damage each. This means if all shots connect, it does 40 burn damage.
The Laser Slug was quite a useless item honestly, with its bigger brother the pulse slug being far better in every way (double its damage, able to damage walls, not too much more expensive, and still only uses the protolathe to create all the ingredients). It also just kinda was conceptually weird. Lasershot will hopefully at least have its own unique …
=> Converts Laser Slugs to Lasershot 2: Electric Boogaloo

code/modules/world_topic/announce.dm, goon/browserassets/css/browserOutput-dark.css, goon/browserassets/css/browserOutput.css
Fixes this
PRs are huge, but they dont need to be this huge
none lol
fix: Fixed PR text being huge
/:cl:
=> Fixes this text being huge for no reason

code/game/objects/items/stacks/stack.dm
Removes a string macro which doesnt do anything because theres no variable. See #19573 and image below
Useless code and stops us from being flagged on opendream linters.
Still compiles, text shows up
No player-facing changes
=> Removes a useless string macro (part 2)

code/defines/procs/announce.dm, code/game/mecha/mecha.dm, goon/browserassets/css/browserOutput-dark.css, goon/browserassets/css/browserOutput.css
Fixes a collision in CSS names with IC announcements vs OOC PR messages (and AI taking over mechs apparently as well)
Ughgghg
:cl:
fix: Chatlog style fixes.
/:cl:
=> Rename IC announcement CSS class

code/modules/events/cargobonus.dm
Fucking file isn't even ticked.
If this had managed to get ticked it would have broken the build.
=> Remove unused dead code for cargobonus event.

code/modules/mob/living/carbon/alien/humanoid/caste/drone.dm, code/modules/mob/living/carbon/alien/larva/powers.dm, code/modules/mob/living/carbon/alien/special/alien_embryo.dm, code/modules/mob/living/carbon/alien/special/facehugger.dm
Logs how many people get infected by facehuggers, how many eggs hatch, and how many people evolve into a certain alien type.
Done through blackbox logger
Logging good
Viewed in blackbox debugger
:cl:
add: Alien growth is now logged
/:cl:
=> Alien BlackBox tracking

code/datums/ai_law_sets.dm, code/game/objects/items/weapons/AI_modules.dm, code/modules/research/designs/AI_module_designs.dm
This PR adds a new illegal Crewsimov-adjacent lawset, **Pranksimov**.
This lawset is identical to Crewsimov... except that the silicon is free to disregard any law if doing so would be funnier than obeying it.
Unlike the Syndicate Directive module, this module leaves the clown (and everyone else) at the mercy of the AI's sense of humor, so you better make sure your silicon buddies have a funny bone before you commit to subverting them.
Pranksimov modules can be constructed by R&D after hitting Programming 5, Materials 5, and Syndicate 2, and require 1000 glass and 100 bananium to print.
Mischievous syndiclowns can also cmag (#18933) a standard Crewsimov module to permanently reconfigure it to Pranksimov.
(Directly cmagging borgs to change their lawset to Pranksimov will come in a later …
=> Adds new lawset, "Pranksimov"

code/game/dna/mutations/powers.dm, code/game/objects/items/weapons/storage/boxes.dm, code/game/objects/structures/watercloset.dm, code/modules/clothing/head/jobs.dm, code/modules/clothing/shoes/miscellaneous.dm, code/modules/food_and_drinks/food/foods/pasta.dm
Fixes the grammar in a few descriptions, mostly apostrophes.
Grammar good.
The game still compiles.
:cl:
spellcheck: Fixed grammar on a few descriptions
/:cl:
=> Fixes description grammar in a few places

.github/CONTRIBUTING.md
Steps me down
Its been an honour
=> End of an era redux

.github/workflows/ci.yml, code/controllers/subsystem/profiler.dm, config/example/config.toml
Fixes multibuild 
Theres no point in having multibuild CI if it doesnt bloody work
We're about to find out
=> Fixes multibuild - It appears I cant do CI properly

code/controllers/subsystem/pathfinder.dm, code/controllers/subsystem/ticker.dm, code/modules/pda/PDA.dm, tools/ci/check_grep.sh
Adds a CI linter check for `.proc/` syntax, as we don't allow users to do this anymore. Use the macros.
https://discord.com/channels/145533722026967040/499000353312735233/1039973825376440370
Works
=> CI check for old style procrefs, tidies some that slipped in

code/modules/mob/living/simple_animal/bot/bot.dm
Lets bots patrol again, reverts error introduced in https://github.com/ParadiseSS13/Paradise/pull/19360
Bots are not patrolling
Removed line, bots patrolled
:cl:
fix: Fixed bots not patroling properly
/:cl:
=> Bot movement hotfix

code/game/objects/items/weapons/powerfist.dm
Changes the knockback speed of the power fist from a flat .2, to 3 times the power setting.
This feels unintentional, and the power fist is a gas powered super-arm, it should actually throw people back instead of making them do slow back-flips.
I spawned in a skrell, and smashed it against a wall for a while, trying each setting.
:cl:
tweak: Powerfist now properly knocks back
/:cl:
=> Powerfist now actually knocks back

code/game/objects/items/devices/scanners.dm, code/modules/research/designs/bluespace_designs.dm, code/modules/research/designs/equipment_designs.dm, code/modules/research/designs/medical_designs.dm, code/modules/research/designs/weapon_designs.dm
Tweaks multiple protolathe designs costs.
Standardizes some design names with uppercases.
METAL/GLASS costs
Gives it the same cost as other HUDs.
hydroponic hud 50/50 --> 500/500 
hydroponic night vision hud 200/200 --> 600/600
Too cheap when compared to other protolathe designs.
tracking beacon 150/100 --> 300/200 
reagent scanners 30/20 --> 300/200
cyborg analyzer 30/20 --> 300/200
Health Analyzer Upgrade 20/20 --> 200/200
Handheld Defibrillator 20/20 --> 200/200
Handheld Crew Monitor 30/20 --> 300/200
- Used my eyes to verify the new costs
:cl:
tweak: Multiple protolathe design costs have been tweaked
/:cl:
=> Tweaks to protolathe designs

code/modules/antagonists/changeling/powers/augmented_eyesight.dm
Gives Augmented eyesight, a Changeling ability full night vision. Allowing it to pair well with what is already x-ray.
Clings currently suck and need some buffs, it also struck me as odd that they were lacking this one piece of vision tool. This makes augmented eyesight not be a half measure when buying and should help clings who lurk in the maints.
booted a server and turned on augmented eye
:cl:
tweak: Augmented Eyesight now gives you vision in the dark
/:cl:
=> Minor Buff to Cling Augmented Sight

code/game/machinery/deployable.dm, code/modules/research/designs/weapon_designs.dm
Lowers the cost of dropwall grenades by ~75%
Lowers recoverable materials as well
I _really_ overpriced these when I added them. They cost more than most gun conversion kits, for something one use. This makes them more comparable to other grenades, in price.
Just a numbers game.
:cl:
tweak: Dropwall grenades are about 75% cheaper to print from rnd.
/:cl:
=> Makes dropwall grenades actually a reasonable price

code/game/objects/items/stacks/sheets/mineral.dm
Adds sarcophagus (sandstone coffin) as sandstone recipe.
The sarcophagus is not being used anywhere and could be included as another coffin variation available to players.
- Spawned sandstone and made sarcophagus with it.
:cl:
tweak: Sarcophagus now can be made using sandstone
/:cl:
=> Sarcophagus now can be made using sandstone

code/game/gamemodes/miniantags/guardian/types/protector.dm
Protector guardian is now immovable while in shield mode (move_resist = MOVE_FORCE_STRONG).
The protector guardian is supposed to protect his master, with crew being capable of moving him while hes on shield mode (95% dmg resist and slow speed) it makes the task of protecting him difficult, with this change he will be able to stand in the way to protect (or to block chokepoints) with more efficiency.
- Tried to move him with shields on and off.
:cl:
tweak: Protector guardian is now immovable while in shield mode
/:cl:
=> Protector guardian is now immovable while in shield mode

_maps/map_files/generic/centcomm.dmm, code/game/area/ss13_areas.dm, code/game/objects/items/candle.dm, code/game/objects/structures/crates_lockers/closets/gimmick.dm, code/game/turfs/simulated/walls_indestructible.dm
Gives the wizard den a remap to add theme and ambience, while not going overkill as to distract the wizard from his objective.
The current wizard den is a little lame, quite frankly. It's fully bright, surrounded by uranium, has poor flow, and doesn't feel "real".
This remap intends to get wizards into the wizarding mood by giving them ambience, a touch of comfort, and a sense that they are a real person in the universe.
Our CC z-level is big enough to support this comfortably. I did not make it too large so as to distract the wizard from the station, but made it just big enough to feel real.
Also, the wizard ghost council can now sit in a cooler location to discuss dchat salt.
Loaded in, wizard-ed about
:cl:
tweak: Wizard den gets a facelift
fix: Fixed non-lockable cabinet doors being …
=> Wizard den remap

code/game/objects/items/weapons/storage/belt.dm
Adds forensic scanner to the list of acceptable items of security belt.
QoL change, since detective has his own security belt seems a bit weird he cant put his equipment in it.
Started the game, put the scanner into the belt (image attached)
:cl:
tweak: Security belt can now hold the forensic scanner.
/:cl:
=> Secbelt and detective

code/modules/client/preference/loadout/loadout_uniform.dm, tools/loadout_converter/loadout_converter.json
Adds hawaiian t-shirts to the loadout.
A lot of people use them as regular uniform, its nice to have it roundstart without having to run to vendors every round.
Started the game, selected shirt in hte loadout, made sure i spawn with one when join the round.
:cl:
tweak: Hawaiian t-shirts are now available in the loadout
/:cl:
=> Hawaiian loadout

code/modules/antagonists/vampire/vampire_powers/umbrae_powers.dm
title
intended functionality is good functionality 
tried to break it.
:cl:
fix: shadow anchors are indestructible 
/:cl:
I am stupid
=> fixes shadow anchors getting destroyed

code/game/objects/items/devices/aicard.dm, code/game/objects/items/devices/paicard.dm
Adds descriptions to pAI device and intellicards (written by ArcZelf).
Intellicard name doesnt make it 100% clear what it does (it didnt to me as a new player).
The addition of descriptions should help newer players understand and make more use of PAIs.
- Compiled and used my eyes to see descriptions
:cl: ArcZelf
tweak: Added descriptions to pAI device and intellicards
/:cl:
=> Adds descriptions to pAI device and intellicards

code/modules/events/spider_terror.dm, code/modules/mob/living/simple_animal/hostile/terror_spiders/black.dm, code/modules/mob/living/simple_animal/hostile/terror_spiders/brown.dm, code/modules/mob/living/simple_animal/hostile/terror_spiders/empress.dm, code/modules/mob/living/simple_animal/hostile/terror_spiders/ghost.dm, code/modules/mob/living/simple_animal/hostile/terror_spiders/gray.dm, code/modules/mob/living/simple_animal/hostile/terror_spiders/green.dm, code/modules/mob/living/simple_animal/hostile/terror_spiders/mother.dm, code/modules/mob/living/simple_animal/hostile/terror_spiders/prince.dm, code/modules/mob/living/simple_animal/hostile/terror_spiders/princess.dm, code/modules/mob/living/simple_animal/hostile/terror_spiders/purple.dm, code/modules/mob/living/simple_animal/hostile/terror_spiders/queen.dm, code/modules/mob/living/simple_animal/hostile/terror_spiders/red.dm, code/modules/mob/living/simple_animal/hostile/terror_spiders/terror_spiders.dm, code/modules/mob/living/simple_animal/hostile/terror_spiders/white.dm
Addresses the request in #19546 by adding in some introductory text for terror spiders that are either event spawned or taken control of by ghosts. The text aims to tell spiders their role, abilities, strengths and weaknesses rather than expecting them to either know it before taking the role or click the wiki link to read up.
<details>
<summary>The exact intro text for each spider is as follows:</summary>
As a Red Terror Spider, your role is to directly attack the crew and defend weaker spiders. You have high health and deal high damage which increases the more injured you are. Your brute strength also allows you to force open powered doors and your webs are stronger and take longer for the crew to destroy. However, you move much slower than most other spiders.
As a Green Terror Spider, …
=> Terror spiders now have intro text

_maps/map_files/Delta/delta.dmm, _maps/map_files/MetaStation/MetaStation.dmm, _maps/map_files/RandomRuins/SpaceRuins/dj.dmm, _maps/map_files/RandomRuins/SpaceRuins/moonoutpost19.dmm, _maps/map_files/RandomRuins/SpaceRuins/ussp.dmm, _maps/map_files/cyberiad/cyberiad.dmm, _maps/map_files/generic/centcomm.dmm
Converts varedited signs that already had respective structures.
Theres no reason to have a varedit structure if the structure you want already exists.
- Did fly around looking for any broken warning signs, all good.
=> Converts multiple warning signs into proper structures instead of varedits

code/modules/mob/living/simple_animal/hostile/mining/elites/elite.dm
Adds 1 more radius to the tumor arena teleport radius, so people that have a movement bug at the time the arena teleports them don't get the "You dare to try to break the sanctity of our arena? SUFFER..." 8 times and get murdered super fast
Getting the w key stuck down and taking 380 damage over 30 seconds isn't great.
:cl:
tweak: The cancerous tumor now teleports people 1 tile farther, to reduce risk of them instantly entering it's radius again.
/:cl:
=> adds 1 more radius to the arena teleport

.github/CONTRIBUTING.md
Updates the contributing file to reflect @Sirryan2002 their new role. May your reviews be just and your merges be conflictless.
Yes
Made a ton of shitty PRs and had Ryan review them
=> Promotes Sirryan to commit access

.github/PULL_REQUEST_TEMPLATE.md
Update PR template to mention GitHub Fixes syntax.
Saves issue managers time, and avoids having to circle back to issues to manually close them.
=> Encourage Fixes syntax in PR template.

code/game/objects/effects/spawners/lootdrop.dm
Adds empty wallet (weight = 20) and wallet with contents (weight = 5, has money and coins) to maintenance loot.
Wallets can be a cool loot to be found, if you consider that its random version has a chance to have money in it, would incentivise maint looters to search for it.
- Did fly around looking for wallets, found 3/4 on average.
:cl:
tweak: Wallet has been added to maintenance loot
/:cl:
=> Adds wallet to maintenance loot

code/modules/mob/living/simple_animal/friendly/lizard.dm
Lizards can now crawl under doors while hidden like mice and drones
These are pretty much just a reskin of mice, they ought to have this
They're pretty small too
Compiled and crawled 
:cl:
tweak: Lizards can now crawl under doors
/:cl:
=> Lizards can now crawl under doors while hidden

code/modules/station_goals/bsa.dm
puts the name of the GPS fired on by BSA in the message admins
Good to know what gps was fired on, incase it was an honest mistake with a miner having a gps named fire or something
fired bsa at target.
GPS name tag showed up.
:cl:
tweak: BSA messages admins name of gps targeted now.
/:cl:
=> puts the name of the GPS fired on by BSA in the message admins

code/modules/mining/equipment/kinetic_crusher.dm
fixes crusher trophy misspelling
I spell the path and name right, but not the description, I guess.
I put it in a spellchecker 
:cl:
fix: Fixes crusher trophy misspelling
/:cl:
=> fixes crusher trophy misspelling

code/modules/economy/economy_machinery/atm.dm
(Original concept by @lewcc)
The Jestographic Sequencer (cmag) can now be used on ATMs. Cmagging an ATM causes it to LOUDLY announce that you've logged into your banking account... in excessive detail.
As with almost all other cmaggable objects, cmagged ATMs can be repaired by cleaning off the bananium ooze with cleaning supplies.
This PR also culls an unused proc from `ATM.dm`, and removes the ability to insert emags/cmags into ATMs, as that behavior unfortunately overrides `cmag_act()` (and `emag_act()`, if an emag effect is ever added to the ATM).
Giving the cmag more functionality so it can be used as a full-bodied pranking tool is good. With the new economy rework, money is worth more than ever before; it's only natural that criminally inclined clowns would incorporate identity theft …
=> ATMs can now be cmagged

code/game/machinery/constructable_frame.dm, code/modules/research/designs/machine_designs.dm
Added circuitboards version of slot machine and bottler to protolathe.
Moving bottler to be made using circuitboards will allow us to decrease the supply pack bloat by removing his crate.
Allowing players to make slot machines will make it easier for them to make custom cassinos (without having to steal).
- printed circuitboards at protolathe and made those two machines.
:cl:
tweak: Slot machine now can be made using circuitboards
tweak: Bottler now can be made using circuitboards
/:cl:
=> Slot machine and bottler now can be made using circuitboards

_maps/map_files/generic/centcomm.dmm
Makes the nukie's tool vendor the free subtype, same for SST's tool vendor too
fixes #19776
The tools are free
:cl:
fix: Nukie's tool vendor is now free
/:cl:
=> Fixes the Nukies's tool vendor being paid

_maps/map_files/cyberiad/cyberiad.dmm
Exchanged the var edited point of sale for the proper item (1 has been added by accident during the merge of another map edit).
Exchanged six free vendors from Cyberiad for paid version (see images of changes).
It makes no sense that viro/science and some random maintenance vendors would be for free (and only for Cyberiad).
- Looked into the vendors and pos, correct version is now in place.
:cl:
fix: Cyberiad: Versions of pos and some vendors have been corrected
/:cl:
=> Cyberiad Fix: wrong version of pos and vendors

code/game/gamemodes/nuclear/pinpointer.dm
You can now alt-click a traitor's advanced pinpointer to change it's mode.
Its really awkward to use currently with verbs.
I alt-clicked the pinpointer, and the menu popped up.
:cl:
tweak: You can now alt-click an syndicate advanced pinpointer to change it's mode
/:cl:
=> Makes the Advanced Pinpointer easier to use

code/modules/reagents/chemistry/reagents/drugs.dm
Changes the OD on pump up from a stun to a knockdown. Makes my github stats page more green by changing one word.
There was a comment next to this line saying to change this once crawling got merged, so I imagine that was the original intent.
Took drugs, vomited, and kept crawling around
:cl:
tweak: Pump up overdose knocks down instead of stunning
/:cl:
=> Changes pump up OD to knockdown

code/game/machinery/computer/HolodeckControl.dm
Fixes this monstrosity:
By making it like the old directional window
Windows should make sense
:cl:
fix: Fixed holowindows not being directional
/:cl:
=> Fixes holowindows

SQL/paradise_schema.sql, SQL/updates/44-45.sql, code/__DEFINES/misc.dm, code/__HELPERS/text.dm, code/controllers/subsystem/tickets/mentor_tickets.dm, code/controllers/subsystem/tickets/tickets.dm, config/example/config.toml
Admin and mentor tickets are now logged to the DB. This includes the ticket info, state, and all the response.
Metrics on this **might** be useful? All I know is I want a good way to aggregate what the most common tickets and responses are, purely so I have an easier way of doing ungodly ML experiments.
I have 8 tickets logged in my DB, it works
N/A
=> Logs tickets to the DB

code/controllers/subsystem/jobs.dm, code/game/jobs/departments.dm
properly GC's money accounts on station member datums
hard dels suck
Logged in and cryo'd, check to see that 1 money account was QDEL'd properly.
no player facing changes
=> Fixes Money Account GC issues

code/modules/assembly/signaler.dm
title, usr wasnt declared so it runtimed
runtimes are bad
made prox sensor send signal, no runtime.
N/A
=> fixes a runtime when a signal is sent from a prox sensor 

code/game/objects/structures/mirror.dm
Adds the ability to become Nian to the wizard's magic mirror
No reason why wizards should not be able to become Nian
Interact with magic mirror
Select Nian
Transform into a Nian
:cl:
fix: Nian now a selectable species in magic mirror
/:cl:
=> Nian now a selectable species in magic mirror

strings/tips.txt
Fixes #19857
Removed or adjusted outdated tips as Goliath mentions.
Read through it myself and the rest looked fine to me.
Made a few minor adjustments as well. 
If any new tips need to be added or existing ones adjusted, I'd be more than happy to add to this.
Tips intended for newer players should not show outdated information.
Make changes to the tips text file.
Wait in the lobby and spam tips.
Confirm it worked as expected.
:cl:
fix: Fixed outdated tips in the tips list
/:cl:
=> Updates the tip list

code/modules/antagonists/changeling/evolution_menu.dm
=> Fixes an exploit

_maps/map_files/generic/centcomm.dmm, code/game/turfs/simulated/walls_indestructible.dm
Fixes weird smoothing between the syndicate nuclear shuttle and the syndicate base. These are clearly two separate objects, they should not have been allowed to smooth together for this long.
Shuttles should not merge with their docks.
Loaded an instance and looked
:cl:
fix: Fixed the nukie shuttle merging with the syndie base docking arm
/:cl:
=> Fixes weird syndicate base smoothing

code/__HELPERS/lists.dm
Removes a commented out proc.
It's been commented out since 2015, I think it's fine to go away.
=> Remove commented proc/dd_sortedObjectList.

code/game/machinery/cryopod.dm
Fixes https://github.com/ParadiseSS13/Paradise/issues/19928
Exploit bad
:cl:
fix: Fixed an exploit with cryo storage
/:cl:
=> Fixes exploit

code/game/objects/items/weapons/storage/backpack.dm, code/game/objects/items/weapons/storage/storage.dm, code/modules/food_and_drinks/kitchen_machinery/smartfridge.dm, code/modules/hydroponics/seed_extractor.dm, code/modules/mob/mob.dm, code/modules/recycling/disposal.dm
Fixes runtimes and failures when inserting loadout items into a player that spawns with a duffelbag, and when users cryo with a zipped duffel.
Fixes syndie duffels not showing themselves to users after unzipping
Duffel bags should work at spawn and cryo
Equipped multiple bags with loadouts.
:cl:
fix: Fixed loadout items not being put in duffelbags at spawn
/:cl:
=> Fixes a niche dufflebag issue

code/datums/components/footstep.dm
Turns on crawling sounds of which its sound file was already in our repo from when we ported footstep.dm
Crawling didn't exist when footstep.dm got ported so it was left out.
Implementation matches TG pre-refactored code.
I like little details like this and it kind of looks weird to watch people silently slither across the floor.
Turn on sound.
[Unknown 2022.12.10-16.31-1.webm](https://user-images.githubusercontent.com/92271472/206876011-900c21ef-d6d4-4816-b5d3-258501296606.webm)
I crawled around a bunch
:cl: Bmon
soundadd: There is now a step sound for when you crawl.
/:cl:
=> Crawling sounds

code/modules/food_and_drinks/kitchen_machinery/kitchen_machine.dm
Adds checks for being unanchored and panel being open for cooking machines to stop any shenanigans. Also adds a warning if there is no power, because you could try to activate it and get no response why it was failing.
Fixes #19889
Tried to use a depowered microwave, failed. Tried to use an unanchored microwave, failed. Tried to use a microwave with its panel open, failed. Activated a microwave and couldn't unanchor it.
:cl:
fix: Kitchen machinery can no longer be dragged around while active.
tweak: Adds a warning for kitchen machines if they have no power and you attempt to activate it.
/:cl:
=> Fixes some stuff with microwaves

code/game/machinery/guestpass.dm
The guest pass now goes to your hand instead of the floor when created.
Its a big annoyance to grab the issued pass from the floor everytime you use it, putting it in your hand is how it works with similar machineries.
- Issued cards with hands full and empty, tested their access too.
:cl:
tweak: Guest pass terminal now issues the card directly to your hand
/:cl:
=> Guest pass terminal now issues the card directly to your hand

code/modules/economy/economy_machinery/account_terminal.dm
Allows you to actually sort by account number and who has the most money, because those were broken, because for some reason localeCompare only likes strings.
Fixes a bug
Didn't work before, works now.
:cl:
fix: The Account Uplink Terminal should now allow you to sort by money and account number
/:cl:
=> Fixes a small sorting issue with the Account Terminal

code/modules/antagonists/vampire/vampire_powers/hemomancer_powers.dm
title
admins will stop being angry at me
tested on prod.
del: admin rage
=> Makes Predator Senses Not Spam Admin Logs So Admins Stop Hating Me.

code/modules/mob/living/carbon/alien/humanoid/caste/sentinel.dm
Removes a commented out proc from the sentinel file
This is not used
I pressed F5 and compiled
NPFC
=> Removes a commented out proc

code/game/objects/structures/misc.dm
Fixes #19938 
Fixes people getting sent to nullspace with this thing
Fixes admins getting spammed with logs
Bugs bad, nullspace bad, logspam bad
compiled, ran, deleted and spawned in Mutiple times
:cl:
fix: respawning using a long-distance cloner after it's been deleted will no longer send you to nullspace
/:cl:
=> Sanity checks for the respawner

code/__HELPERS/global_lists.dm, code/datums/mind.dm, code/game/gamemodes/miniantags/abduction/abduction.dm, code/game/gamemodes/objective.dm, code/modules/admin/player_panel.dm, code/modules/admin/topic.dm, code/modules/antagonists/_common/antag_datum.dm, code/modules/antagonists/_common/antag_helpers.dm, code/modules/antagonists/_common/antag_team.dm
Adds antag team framework code (which isn't used yet) so we can have modern sane code for antag teams.
Also adds an admin UI so they can view teams, or do things such as add/remove objectives for those teams, remove its members, or send an admin message to members of the team.
The team UI.
What it looks like when an admin messages the team. (Not quite sure if this is the best format to show messages. Feedback welcome)
Gave myself traitor with a dummy team and made sure all the admin functions (add/remove objective, etc) worked. 
N/A
=> Refactors antag team code. Adds an admin UI to interact with teams

code/modules/food_and_drinks/kitchen_machinery/kitchen_machine.dm
As an is(operating) check
yeah.
Confirmed things worked as it should
:cl:
fix: Fixes a bug with cooking
/:cl:
=> fixes a bug with a thing

code/modules/games/cards.dm
fixes #19447 
I don't think this code actually does anything; no owner would be set at the point of addition, so it probably doesn't need to be there
compiled, ran, tried to break it and failed
NPFC
=> Fixes a playing card runtime

code/modules/martial_arts/martial.dm
specifies a user
targets are needed
NPFC, admin only item
=> fixes a wrestling to_chat() runtime

code/game/mecha/mecha.dm
lets umbrae and shadow demons extinguish mech lights
bugs are bad.
called proc on mecha with lights on, lights turned off.
:cl:
fix: mech lights are extinguished by umbrae and shadow demons
/:cl:
=> Fixes mechs being immune to extinguish light

code/game/mecha/mecha_control_console.dm
Exosuit console: cell charge value is no longer stuck at the false value of 100%.
Fixes https://github.com/ParadiseSS13/Paradise/issues/20063
- Spawned a ripley with tracking beacon and walked around with it
- Looked at exosuit console cell charge.
:cl:
fix: Exosuit control console: cell charge now shows the real value
/:cl:
=> Fix #20063 Exosuit control console: cell charge now shows the real value

code/datums/keybindings/human.dm, code/modules/mob/living/carbon/human/inventory.dm
As the title says, you can now put items into belts, bags and the suit slot using hotkeys.
Default bindings are Shift E for belt Shift B for bag and Shift Q for suit slot. These can be changed in the hotkeys menu.
Semi-based on Cits implementation but the original code is from TG and thus is credited.
yeah i think this is okay for putting stuff into things yeah woo
I messed around in-game to make sure nothing runtimed(don't quote me on that)
:cl: Bmon, ninjanomnom
add: You can now put items into your belts, bags and the suit slot using new hotkeys! (shiftE for belt, shiftB for bag, shiftQ for suit slot)
/:cl:
=> You can now put items into bags, belts and the suit slot using hotkeys.

code/datums/diseases/kingstons.dm, code/game/dna/dna2.dm, code/game/dna/mutations/monkey.dm, code/game/gamemodes/miniantags/abduction/gland.dm, code/modules/antagonists/changeling/powers/humanform.dm, code/modules/mob/living/carbon/human/human.dm, code/modules/mob/living/carbon/human/species/_species.dm, code/modules/mob/transform_procs.dm
Reverts ParadiseSS13/Paradise#19945
Fuckin breaks IPCs
=> Revert "Prevents limb regeneration when changing species"

code/game/machinery/recycler.dm, code/game/objects/items/decorations.dm, code/modules/arcade/prize_counter.dm, code/modules/food_and_drinks/kitchen_machinery/gibber.dm, code/modules/food_and_drinks/kitchen_machinery/monkeyrecycler.dm, code/modules/food_and_drinks/kitchen_machinery/processor.dm, code/modules/food_and_drinks/kitchen_machinery/smartfridge.dm, code/modules/hydroponics/seed_extractor.dm, code/modules/reagents/chemistry/machinery/chem_dispenser.dm, code/modules/reagents/chemistry/machinery/chem_master.dm, code/modules/reagents/chemistry/machinery/pandemic.dm
Recycler: 2 -> 6 SECONDS
Decorative structures: 0 -> 2 SECONDS (same time it takes to unfasten statues)
Prize counter: 2 -> 6 SECONDS
Gibber: 2 -> 4 SECONDS
Monkey recycler: 2 -> 4 SECONDS
Processor: 2 -> 4 SECONDS
Smartfridges: 2 -> 4 SECONDS
Seed extractor: 2 -> 4 SECONDS
Chem dispenser (includes soda fountains and alike): 0 -> 4 SECONDS
Chem master: 2 -> 4 SECONDS
Pandemic: 2 -> 4 SECONDS
Suggestions to values are welcome
It updates unfasten times to reflect how important some of these items are and their sizes.
- Spawned in with a wrench and did go around unfastening the tweaked items.
:cl:
tweak: The time to unfasten some items have been changed
/:cl:
=> Tweaks to unfasten times

code/game/machinery/computer/robot.dm
Only admins that are ghosts and malf AI can see if a robots safeties are overiden. This was the case before TGUI, and the PR showed that this was to be the case, but in the final version of the pr this did not work, and anyone could see a borg was safety overridden. 
Malf AI should not be outted when they hack their borgs without the borgs doing anything, the safeties display was only supposed to show to malf ai, not everyone.
Confirmed only malf AI / admins could see robots that malf ai had hacked.
:cl:
fix: Crew can no longer see on the robotics control console when malf AI hacks a borg
/:cl:
=> Fixes mistake in tgui conversion of robotics control console

code/modules/paperwork/desk_bell.dm
Desk bell now can be spooked by ghosts, making it ring if not broken.
It makes sense for the desk bell to be a valid BOO spell target, and its spooky.
- Did use boo spell on the desk bell, it did ring
:cl:
tweak: Desk bell now can be spooked by ghosts
/:cl:
=> Desk bell now can be spooked by ghosts

code/modules/antagonists/changeling/powers/revive.dm
Makes it so you are unable to revive as a Changeling if another Changeling absorbs you. Apparently, it was intended that if you were absorbed by a cling, you should not be able to revive at all, as it would forbid you from entering stasis. However, there was no check on the revival itself, so if you stasis'd at any point before you'd be just fine.
An admin informed me this was not intended, so... Exploits bad, mechanics working as intended good.
Tested before and after by absorbing another cling as a cling and was unable to revive the second time.
:cl:
fix: You can no longer revive as a Changeling if another Changeling absorbs you, as intended
/:cl:
=> Fixes a Changeling Exploit

code/game/area/ss13_areas.dm
Adds new `/area` types for the AI sat. These types are necessary for multiple maps in order to remove varedited areas so I'm pulling it out into a smaller atomic PR.
Contributes to fixing varedited `/area`s across multiple maps.
=> Add AI sat /areas necessary for multiple map fixes.

code/modules/paperwork/desk_bell.dm
Boo cooldown now resets properly when used on desk bells.
Spams are bad
- Used BOO on desk bells, the cooldown did reset back to 0% instead of 90%
:cl:
fix: Boo cooldown now resets properly when used on desk bells
/:cl:
=> Fix a thing with desk bells

_maps/map_files/generic/centcomm.dmm, code/modules/food_and_drinks/drinks/drinks.dm
title
3rd place is pretty good guys. GG
it compiles.
:cl:
add: a bronze trophy to CC, celebrating paradises 2023 3rd place. 
/:cl:
=> adds a unique trophy to CC

code/game/gamemodes/vampire/traitor_vamp.dm, code/game/objects/structures/stool_bed_chair_nest/chairs.dm
Pews take 5 wood to make, and give 5 back on deconstruction
Following the law of conservation of mass is good
Went to chapel, deconstructed the pews, got 5 wood per pew
Built some pews with that wood, then deconstructed them for the same amount of wood
:cl:
fix: Pews now return 5 wood on deconstruction
/:cl:
=> Pews now give 5 wood back when deconstructed

code/modules/hydroponics/biogenerator.dm
Changes `/obj/machinery/crowbar_act` in the biogenerator file to properly be to `/obj/machinery/biogenerator/crowbar_act`.
In #18263, I screwed up scoping this path.
I don't know how many issues this has created, but this PR definitely fixes them.
N/A
=> Fix bad pathing on `/obj/machinery/biogenerator/crowbar_act`

code/modules/mob/living/silicon/robot/drone/drone.dm
fixes #19339
Adds some Qdel nulls
GCing good, how nobody noticed this surprises me
Drone kill
NPFC
fucking drones
=> Fixes drone GC issues 

code/game/machinery/vendors/generic_vendors.dm
Adds the DNA Injector - Comical and the Sad Trombone bio-chip to the Wizard's Wizvend.
Clown Wizard is a gimmick that Wizards can already take, so giving them access to some more comedic utilities seems like a good idea to me. Also, sad trombone on a wizard is inherently hilarious.
See above image.
:cl:
tweak: The Magivend now contains a Sad Trombone biochip and a DNA injector for the comic gene
/:cl:
=> Gives the wizard some more clownish options

code/game/objects/items.dm
I trusted a maintainter on using static lists, but the list wasn't static and its my fault for not checking that. This is the hotfix for it because it breaks SECURITY HUDs
Broke things bad
sec HUDs work now
:cl:
fix: Security HUDs are no longer broken
/:cl:
=> Fixes Wallets breaking security HUDs

code/modules/station_goals/bluespace_tap.dm
makes bsh not spawn the parrent penguin type that is invisible
invisible birds are bad
Ensured it had a proper spawn path
:cl:
fix: bsh no longer spawns invisible penguins
/:cl:
=> bsh no longer spawns invisible penguins

code/game/objects/items/weapons/grenades/flashbang.dm
Fixes being able to cheese having a flashbang on the same turf.
To the people using it. Issue report it. Don't use it till someone notices you using it.
Flashbangs are supposed to stun you if you have it in bag or such, this certifies it.
Confirmed it worked.
:cl:
fix: Fixes being able to cheese flashbangs
/:cl:
=> fixes flashbang cheese

code/modules/clothing/masks/gasmask.dm
Folded gas mask actually starts folded now
this item probably shouldn't exist
not working code bad, working code good
because there will be no user, a new proc that doesn't rely on a user had to be created
I spawned one in w/o a runtime
NPFC
=> fixes a folded mask runtime

code/modules/mob/living/status_procs.dm
fixes adjust knock down applying weakened
bugs are bad
Set it to floored
:cl:
fix: fixes adjust knock down applying weakened
/:cl:
=> fixes weakened issue

code/datums/diseases/_disease.dm, code/datums/diseases/anxiety.dm, code/datums/diseases/appendicitis.dm, code/datums/diseases/beesease.dm, code/datums/diseases/berserker.dm, code/datums/diseases/brainrot.dm, code/datums/diseases/cold.dm, code/datums/diseases/cold9.dm, code/datums/diseases/fake_gbs.dm, code/datums/diseases/flu.dm, code/datums/diseases/fluspanish.dm, code/datums/diseases/food_poisoning.dm, code/datums/diseases/gbs.dm, code/datums/diseases/kingstons.dm, code/datums/diseases/kuru.dm, code/datums/diseases/lycancoughy.dm, code/datums/diseases/magnitis.dm, code/datums/diseases/pierrot_throat.dm, code/datums/diseases/retrovirus.dm, code/datums/diseases/transformation.dm, code/datums/diseases/tuberculosis.dm, code/datums/diseases/wizarditis.dm
fixes #18344
fixes #19476
just because you qdel something doesn't mean it instantly stops processing 
production log is now actually readable. 
add: the ability to read the production log
=> fixes disease curing runtimes

code/game/gamemodes/objective.dm
Changes `/datum/objective/is_invalid_target`'s parent call to run at the start of the proc so we can get all the `if(!ishuman())` etc. checks out of the way *before* we send `COMSIG_OBJECTIVE_CHECK_VALID_TARGET`. This is so that we don't have to perform any duplicate checks that the parent call already covers inside of procs which are registering to that signal, such as
`/datum/objective/escape/escape_with_identity/proc/assassinate_checking_target`)
Fixes potential runtimes/unintended behavior.
N/A
=> `/datum/objective/is_invalid_target` order of operations fix

code/_compile_options.dm, goon/code/datums/browserOutput.dm
Makes a few global vars managed, and removes some unnecessary vars and references to them in comments.
Fixes issues surfaced by #19875, bringing it closer to getting merged.
Built, checked for runtimes, spawned into map, checked to ensure icons in chat showed up properly.
=> Make chat-related globals managed.

code/modules/mob/login.dm
Optimises `mob/Login()`
Speed
Please TM this for the love of god
experiment: Added Performance
/:cl:
=> The most black magic and scuffed of optimisations

code/controllers/subsystem/jobs.dm
makes a check no longer runtime
a list return will still runtime if the index is 0
runtimes bad
NPFC
=> fixes a broken check in the job controller

code/modules/mob/living/carbon/human/species/_species.dm, code/modules/surgery/organs/eyes.dm
\
Wearing glasses no longer makes mobs see invisible worse, it was using minimum instead of maximum.
Eyes of god no longer loose their filter when glasses are taken on / off
Bugs are bad
Confirmed glasses no longer mess up eyes of god
:cl:
fix: Glasses no longer make mobs have worse invisible vision.
fix: Eyes of god no longer loose colour filter when active if glasses are taken on / off
/:cl:
=> Fixes eyes of the gods bugs

code/modules/mob/living/silicon/robot/robot.dm
fixes mail_setter not being qdeleted
NPFC
=> fixes a cyborg gc issue

code/modules/clothing/spacesuits/ert.dm, code/modules/mob/living/silicon/ai/ai.dm
adds some qdel nulls
this item can and will fail to GC due to camerachunks, but improvements are good none the less
NPFC
=> portable camera GC improvements

code/game/machinery/vendors/generic_vendors.dm
Adds water bottles to Soda Vendors around the station - 10 for 20 credits each
It's odd we don't have this, water is one of the best drinks around 😏 and NanoTrasen would clearly monetize it where possible. I don't see the fluorine causing any issues at all.
worter
See above.
:cl:
tweak: Robust Softdrinks now stocks Water Bottles
/:cl:
=> Soda Vendors have Water Bottles

code/_onclick/hud/radial.dm
fixes #19907 
cleaning up elements and the close button is needed
NPFC
=> fixes radial menu gc issues

code/__DEFINES/flags.dm, code/game/objects/items/weapons/twohanded.dm, code/modules/mining/lavaland/loot/ashdragon_loot.dm, code/modules/mob/living/carbon/human/human_defense.dm
Adds a flag_2 to mark objects that can randomly parry, allowing the game to know an item has block chance and check it
Chainsaw / ghost swords blocking is good
Confirmed the chainsaw actually worked
:cl:
fix: Fixes rng block chance not working
/:cl:
=> Fixes rng block chance not working

code/modules/mob/living/carbon/human/human.dm
Fixes a runtime where a random human parameter was passed in
Runtimes bad
That runtime is gone
=> Fixes another runtime with id cards

code/game/gamemodes/cult/cult_items.dm
checks if there's a thrower before it gets tossed
disposals moment, shouldn't be trying to send a message from someone that doesn't exist
NPFC
=> cult bola runtime fix

code/modules/power/singularity/singularity.dm, code/modules/power/tesla/energy_ball.dm
Projectiles will now curve around singulos. 
I planned on doing more for this but this took me ages. hardest PR to lines written ratio ever.
If I get more time I will do more reworking so its actually an interesting engine.
neat feature
you dont want to fucking know what I have been through.
:cl:
experiment: projectiles now curve around black holes. 
/:cl:
=> Projectiles now orbit blackholes

code/modules/projectiles/guns/medbeam.dm
Fixes a bug with medbeams being equipped.
Bugs are bad.
Confirmed bug did not happen.
:cl:
fix: Fixed a bug with medbeams being equipped.
/:cl:
=> fixes medbeam bug

code/game/gamemodes/miniantags/morph/morph.dm
makes morph spells GC when a morph is destroyed 
i like morph :) 
NPFC
=> makes morph spells GC properly

code/game/objects/structures/crates_lockers/closets.dm
Fixes an unintended interaction with ghosts and lockers.
Exploits bad
Tested, interaction no longer occurs.
:cl:
fix: Fixed an unintended interaction with ghosts and lockers
/:cl:
=> Fixes ghost locker exploit

_maps/map_files/Delta/delta.dmm
Fixes disconnected APCs in research department on Deltastation.
fixes: #20278
Disconnected APCs not good.
Before
After
Enter Deltastation, power the SMESes, the RD's office is now getting charged.
:cl:
fix: All APCs now in research department on Deltastation are now propely connected.
/:cl:
=> Fixes disconnected APCs in research department on Deltastation.

code/game/gamemodes/trifecta/trifecta.dm
allows trifecta to generate traitors
It's trifecta not twofecta
:cl:
fix: fixes trifecta bug with antagonist generation
/:cl:
=> fixes trifecta bug with antagonist generation

code/controllers/subsystem/http.dm
Removes an unneeded init from HTTPS subsystem
Runtimes bad
Compiled and ran on a local server with DB
NPFC but this was basically made by AA07, I just posted the code
=> https runtime fix

code/game/objects/items/weapons/handcuffs.dm
Changes the description of fluffy cuffs to not talk about 'keeping significant others inline', and replaces it with mentioning them being itchy. 
We aren't that kind of server.. 
Just a description change, but still made sure it did indeed change the description. (it did)
:cl:
tweak: Removed fluffy cuffs mentioning of SO's being kept in line
/:cl:
=> Changes the fluffy cuffs description to not mention keeping your SO in line..

code/game/objects/items/weapons/alien_specific.dm
Removes the tidbit in the xenoborg ether spray description that noted it as "spraying viagra", now actually noting it sprays ether.
Yeah, no.
Just a desc change.
:cl:
tweak: Removed mentions of viagra from a Xenoborg module
/:cl:
=> Removes Viagra

code/modules/mob/living/carbon/human/human_emote.dm
fixes a minor spelling mistake
fixes #20359 
:cl:
fix: Kidian *click emote now plays an audio clip again
/:cl:
=> fixes the kidian click emote

code/modules/reagents/chemistry/reagents/alcohol.dm
see title, Runtime in alcohol.dm,1672: pick() from empty list
yes
=> fixes an acid dreams runtime

code/modules/food_and_drinks/drinks/drinks_base.dm
Replaces the chocolate in weightloss shakes with berry juice so vulps can drink them without being poisoned.
As of the recent vulp vision and diet changes, vulps are now poisoned by chocolate. Weight-loss shakes are quite useful for losing weight, and the fact vulps would need to break weight-loss shakes down in chemistry feels like a bit of an oversight.
Drank a weight-loss shake, didn't get poisoned.
:cl:
tweak: Weight-loss shakes now contain berry juice instead of chocolate.
/:cl:
=> Replaces chocolate in weightloss shakes with berry juice

code/modules/mob/living/simple_animal/hostile/megafauna/bubblegum.dm
actually nulls a GPS
fixes #19457
bwuh
This would cause it to psudo sleep in destroy sometimes, which is really bad for performance 
yes
=> fixes a bad del runtime on bubblegum

code/game/machinery/computer/arcade.dm
Fixes a typo on the arcade machine.
Because spelling is important.
Started the game.
Went to an area that had arcade machines.
Used an arcade machine to confirm the changes.
:cl:
spellcheck: Fixed a typo on the arcade machine
/:cl:
=> Arcade machine typo

code/modules/mob/living/carbon/human/human_defense.dm, code/modules/power/cable.dm
Fixes #12821
This is an exploit. 
:cl:
fix: Fixes being able to overheal on invalid robotic limbs
/:cl:
=> Fixes #12821

_maps/map_files/Delta/delta.dmm, _maps/map_files/MetaStation/MetaStation.dmm, _maps/map_files/cerestation/cerestation.dmm, _maps/map_files/cyberiad/cyberiad.dmm, _maps/map_files/generic/centcomm.dmm, code/game/objects/structures/signs.dm, code/game/turfs/simulated/floor/plasteel_floor.dm
Fixes commemorative and memorial plaques descriptions.
Converts all varedited plaques into proper items.
Broken descriptions are broken.
- Compiled and verified both plaques descriptions
:cl:
spellcheck: Fixed commemorative and memorial plaques descriptions
/:cl:
=> Fixes some plaques descriptions

code/modules/paperwork/paper.dm
Armory inventory document has correct quantities now.
Storage inventories should have info that reflects reality.
- See above
:cl:
fix: Armory inventory document has correct quantities now
/:cl:
=> Fixes armory inventory having incorrect quantities

code/game/objects/items/weapons/highlander_swords.dm
title
I do very much like when code works
:cl:
fix: Highlanders will once again be unable to fire firearms and gain 100% ranged block chance
/:cl:
=> fixes a highlander runtime and the highland martial art not being assigned

code/modules/economy/economy_machinery/eftpos.dm
=> fixes an EFTPOS runtime if there's no connected account

code/datums/diseases/kingstons.dm, code/datums/diseases/pierrot_throat.dm, code/datums/diseases/rhumba_beat.dm
I forgot 3, fixes that
runtimes bad, GDN stupid
it compiled
NPFC
=> actually fixes all disease curing runtimes

code/datums/status_effects/debuffs.dm, code/modules/events/mass_hallucination.dm
Buffs hallucinations effects by increasing the chances of the hallucinate() triggering.
https://github.com/ParadiseSS13/Paradise/pull/17579 ended up HEAVILY nerfing hallucinations, with such low chances of the effect triggering it did even fool me and other players into thinking the mass hallucination event was broken.
This PR objective is to bring our current hallucination close to what it used to be.
<details><summary>OLD HALLUCINATION</summary>
<p>
Mass hallucination
https://user-images.githubusercontent.com/77684085/217785121-7cdc631c-392d-42f4-abb2-514a41800121.mp4
Cling hallucination
https://user-images.githubusercontent.com/77684085/217785151-6f24672d-68b5-4446-9c0f-edd093fc9346.mp4
Revenant hallucination
https://user-images.githubusercontent.com/77684085/217785166-c91413bb-3bcf-4b4 …
=> Making hallucination great again

code/datums/components/parry.dm
Fixes a small math issue with Parrying, allowing you to spam it (see: deswords)
100% uptime on parry is bad.
1. Spawn in.
2. Spam click parry.
:cl:
fix: Fixed a math issue with parrying.
/:cl:
=> Parry Spam Fix

code/game/gamemodes/game_mode.dm, code/game/gamemodes/revolution/revolution.dm, code/game/objects/items/devices/flash.dm, code/modules/mob/living/living.dm
Refactors revolution code to be a little less of a mess.
Revolution code is currently a bit of a mess. Hopefully also fixes issues with deconversion messages not being properly displayed during revolution rounds.
:cl:
/:cl:
=> Refactors revolution code to be a little less of a mess

code/modules/crafting/recipes.dm
Halves gun-kit crafting time from 20 seconds to 10 seconds.
Ever had to sit around crafting gun kit weapons until the end of time? Probably, and it's really not engaging, even with help. Halving it to ten seconds should alleviate some of this monotony, if just a bit.
Also,
I want a goddamn cookie, I'm very hungry.
It's just number changes.
:cl:
tweak: Weapon crafting using gun-kits takes half as long
/:cl:
=> Reduces Gun-kit weapon crafting time

code/modules/mob/new_player/new_player.dm, code/modules/mob/new_player/new_player_logout.dm
Title
They weren't always GCing when you observed, this should fix that issue and improve general code quality
why are we here, just to suffer
Deleted a bunch of new players in a bunch of ways
=> actually makes new players fully GC

code/controllers/subsystem/redis.dm, code/game/gamemodes/game_mode.dm
Redis is randomly dropping on the new server. This is gonna take a bit to diagnose, so let the pain begin.
The PR is now for merge as I added actual functionality 
I compiled it
fix: Fixed redis error reporting 
/:cl:
=> The attempts to diagnose asay/msay dropouts

code/modules/atmospherics/machinery/airalarm.dm
Fixes the Air Alarm scrubbing mode to return the connected vents and scrubbers to default settings by setting vent output back to 101kpa and disabling extended scrubbing. Fixes #20310 
Filtering mode should be the default setting, vent pressure not being changed and scrubbers being set to extended causes the room atmosphere to fluctuate unless manually set for each device.
Ran the code, air alarm filtering now sets the vents to 101kpa and scrubbers are no longer set to extended. All other air alarm modes remained the same and there were no errors.
:cl:
fix: Air Alarm Filtering mode will now set default room values for vents and scrubbers
/:cl:
=> Fixes air alarm scrubbing mode

code/modules/power/apc/apc.dm
makes APCs GC
fixes(I'm guessing it's unintended), destroyed APCs not setting environment to off. Seems like a copy and paste mistake
bugs bad
:cl:
fix: APCs correctly toggle environment off after being destroyed 
/:cl:
=> makes APCs gc and fixes an APC destroy issue

code/modules/food_and_drinks/food/foods/pizza.dm
Adds investigate logs and attack logs for arming and opening of pizza bomb.
Admins complained to me about insufficient logging so I'm fixing it.
See above.
:cl:
tweak: Improved pizza bomb logging for admins
/:cl:
=> Better pizza bomb logging

code/game/objects/items.dm, code/game/objects/items/blueprints.dm, code/game/objects/items/documents.dm, code/game/objects/items/weapons/defib.dm, code/game/objects/items/weapons/melee/melee_misc.dm, code/game/objects/items/weapons/tanks/jetpack.dm, code/game/objects/items/weapons/teleportation.dm, code/modules/clothing/shoes/magboots.dm, code/modules/clothing/suits/armor.dm, code/modules/clothing/under/accessories/accessory.dm, code/modules/martial_arts/krav_maga.dm, code/modules/projectiles/guns/energy/laser.dm, code/modules/projectiles/guns/energy/nuclear.dm, code/modules/reagents/reagent_containers/hypospray.dm
See title
Knowing that the HOS gun is now in the SM is useful information for "AHELP: Does the HOS gun even exist? Can't seem to find it". Admins can then reroll or spawn in a new item for the person who needs the objective
:cl:
tweak: [admin] Objective item deletion now messages admins 
/:cl:
=> objective items being destroyed are now logged

code/datums/components/material_container.dm
fixes:
```
[2023-02-25T02:18:34] Runtime in material_container.dm,324: bad index
[2023-02-25T02:18:34]   proc name: get item material amount (/datum/component/material_container/proc/get_item_material_amount)
[2023-02-25T02:18:34]   src: /datum/component/material_cont... (/datum/component/material_container)
[2023-02-25T02:18:34]   call stack:
[2023-02-25T02:18:34]   /datum/component/material_cont... (/datum/component/material_container): get_item_material_amount
[2023-02-25T02:18:34]   the recycler (/obj/machinery/recycler): recycle_item
[2023-02-25T02:18:34]   the recycler (/obj/machinery/recycler): eat
[2023-02-25T02:18:34]   the recycler (/obj/machinery/recycler): Bumped
[2023-02-25T02:18:34]   the wooden chair (/obj/item/chair/wood/wings): Bump
[2023-02-25T02:18:34]   the plating …
```
=> fixes a null material runtime

code/game/objects/items/weapons/grenades/chem_grenade.dm
See title
Requested by an admin
:cl:
tweak: [ADMIN] Improved chemical bomb logging when used with an assembly
/:cl:
=> improved admin logging for chembombs

code/modules/mob/living/living.dm
Fixes mind GC issues with mob/living
this ought to go for a TM simply due to the amount of things that this COULD fuck up, looked good on my end but you never know
curren't
performance
compiled, ran, mass genocide 
NPFC
=> fixes mob/living mind gc issues

code/modules/surgery/organs/organ_external.dm
Fixes some runtimes in the floor cluwne event, makes it work better
There are nodrop organs and organs can have a null value, this should be addressed
:cl:
fix: Floor cluwne event should be less buggy
/:cl:
=> Fixes some runtimes in the floor cluwne event

code/game/gamemodes/nuclear/nuclear_challenge.dm
When Nuclear Operatives declare war, the station is automatically set to gamma alert after a delay of 30 seconds.
This has always basically been in effect unofficially, might as well make it official at this point, also makes sense for the situation considering that gamma alert is for extreme threats, and I don't know about you, but I would consider nukies an extreme threat.
1. Booted up a test server
2. Spawned in as a nukie
3. Gave myself the challenge item
4. Declared war
5. Waited 30 seconds
6. Gamma alert
:cl:
tweak: Gamma alert is automatically declared shortly after Nuclear Operatives declare war.
/:cl:
=> Declaring War Now Sets Gamma Alert

code/game/objects/random/random.dm
title
I ran into this while testing some GC stuff and I needed to init these else I'd get a couple of runtimes, so I'm also putting a PR up for it
NPFC
=> initializes obj/random

code/controllers/subsystem/jobs.dm, code/datums/mind.dm, code/game/gamemodes/blob/blob_mode.dm, code/game/gamemodes/miniantags/abduction/abduction.dm, code/game/gamemodes/nuclear/nuclear.dm, code/game/gamemodes/revolution/revolution.dm, code/game/gamemodes/wizard/raginmages.dm, code/game/gamemodes/wizard/wizard.dm, code/modules/antagonists/_common/antag_datum.dm, code/modules/events/sentience.dm, code/modules/events/traders.dm, data/mode.txt
Adds logging for when someone was made into an antag (different from conversion logs such as mindslaves/revs/etc)
Adds logging for when someone spawns in a regular character, including roundstart/latejoin state, and the job they spawned as.
This info is somewhat hard for admins to come across at a quick glance, adding it to the logging pane makes it much easier to spot.
(Ignore the extra bracket, this has been fixed)
Logs got looked at
:cl:
add: Added more QoL admin logs
/:cl:
=> Adds more QoL logs for admins

code/modules/clothing/under/misc_jumpsuits.dm
Cursed clown suit now appears properly on people.
Fixes https://github.com/ParadiseSS13/Paradise/issues/20348
- Tested on every species, see image above
:cl:
fix: Cursed clown suit now appears properly on people
/:cl:
=> Fix #20348 Cursed clown suit now appears properly on people

code/_globalvars/game_modes.dm, code/_globalvars/genetics.dm, code/game/gamemodes/setupgame.dm, code/game/mecha/equipment/tools/work_tools.dm, code/game/objects/items/weapons/mop.dm
See title
Variables that aren't used but exist in the code are rather confusing, so let's yeet them.
Compiled, ran, made sure I didn't break genetics, realize old coders were not very smart
=> deletes some unused variables

code/modules/paperwork/paper.dm
Fixed paper [field]
Bugs bad, bad numbers bad, good numbers cool
- Created lots of fields and use them
:cl:
fix: Fixed paper fields
/:cl:
=> Fixes paper fields

code/modules/projectiles/ammunition/ammo_casings.dm
Tightens Lasershot's spread cone from 35 degrees to 25 degrees, bringing it in-line with rubbershot and buckshot.
Spread probably should have been this from the start, as it was meant to be a laser equivalent to buckshot, but I borrowed the 35 degree variance from the more complicated techshells like dragonsbreath and ion shells. Ultimately, I feel from the comments I've received and the usage of lasershot I've seen so far that it fares just a little bit too poorly at range, so bringing its spread down a bit should help it be a bit more combat viable without upping its damage which I'm hesitant to do.
It's just a number change.
:cl:
tweak: Lasershot has a smaller variance in its shot spread
/:cl:
=> Decreases Lasershot Variance

code/__DEFINES/status_effects.dm, code/datums/status_effects/debuffs.dm, code/modules/events/event_container.dm, code/modules/events/fake_virus.dm, paradise.dme
Port from https://github.com/tgstation/tgstation/pull/45348
Added the fake virus virus, mundane event (weight = 50), up to three crewmembers are going to receive fake symptoms messages for the duration of it.
With this event, a visit to the doctor would be necessary to be 100% sure that you are not sick with a deadly virus.
Removing the assurance of "i did lightly cough so i am sure there is a disease around" is good for the paranoia of the game.
All the messages received for the duration of the event
- Joined the game as crewmember
- Forced the event and noticed the fake symptoms happening
:cl: Henri237, PKPenguin321
add: Added the fake virus virus
/:cl:
=> Ports TG Fake virus event

code/game/machinery/constructable_frame.dm
Recolours the body scanner's circuit board from purple to blue.
Fewer bugs, fewer triggered Nithaans
1. Spawn a body scanner
2. Decon it
:cl:
fix: Body scanner circuits are blue now.
/:cl:
=> Fixes body scanner's circuit color

code/game/gamemodes/cult/blood_magic.dm, code/game/gamemodes/cult/cult_items.dm, code/game/gamemodes/cult/cult_structures.dm
fixes #20673
Stuff should return a qdel hint
Backend
=> fixes cult stuff not returning a qdel hint

code/game/machinery/computer/card.dm, code/modules/newscaster/obj/newscaster.dm
Removed barber job from the blacklisted_partial list.
Barber is no longer a karma job and has no reason to be in that list anymore.
- Could change the number of barber slots
:cl:
tweak: You can now change the amount of barber job slots
/:cl:
=> You can now change the amount of barber job slots

code/game/objects/items/weapons/storage/backpack.dm, code/game/objects/items/weapons/storage/storage_base.dm
This PR allows for Smuggler's Satchel to now be held inside a Bag of Holding, while still restricting other backpacks from being stored.
It provides a fix to allow for the use of Smuggler's Satchel as intended.
Checked to see if Smuggler's Satchel could be stored in the Bag of Holding, while checking to see if other backpacks remained restricted from being stored.
:cl:
tweak: tweaked the storage_base.dm to allow for an override of restricted items
tweak: adjusted the bag of holding to accept the smuggler's satchel
/:cl:
=> Smuggler's satchel now fits in Bag of Holding

code/game/objects/items/weapons/twohanded.dm
You can now sweep into janicarts and pimpin' ride trash bags.
Makes using the push broom easier to use without having to go to a disposal bin that may be far away.
It also makes it a good alternative to removing the bag to collect the trash or the other way around.
https://user-images.githubusercontent.com/77684085/224570106-96e62e6f-3208-4e47-b19f-c4829d8598aa.mp4
- See video above
:cl:
tweak: You can now sweep into janicarts trash bags
/:cl:
=> You can now sweep into janicarts trash bags

code/modules/events/fake_virus.dm
IPC's are no longer a valid target for the event.
Fixes https://github.com/ParadiseSS13/Paradise/issues/20704
- Spawned in as IPC and triggered the event, nothing happened.
:cl:
fix: IPCs can no longer get fake viruses
/:cl:
=> IPCs can no longer get fake viruses

code/game/gamemodes/steal_items.dm, code/game/machinery/OpTable.dm, code/game/verbs/suicide.dm, code/modules/clothing/under/accessories/accessory.dm, code/modules/projectiles/projectile/magic.dm
Fixes a number of privately disclosed bugs and exploits.
Some of these are stupid, and have been in the game for 6 years!
:cl:
fix: Fixed a few bugs and exploits
/:cl:
=> Bug and exploit fixes

code/modules/mob/living/silicon/pai/pai.dm
Adds a burn overlays to pAIs, similar to how cyborgs burn, basically only from lava.
Fixes #4848
Burnt some pAIs
:cl:
fix: pAIs now have a burning overlay when on fire
/:cl:
=> Burning pAIs have a proper overlay

code/modules/reagents/chemistry/reagents_holder.dm
fixes #19946 
Runtimes bad, lots of runtimes also bad for people who want to view the runtime log.
=> Fixes cooking machines making a runtime whenever they process a reagent without a normal reaction

code/game/objects/structures/grille.dm
Fixes duplicated examine text on grills
Duplicated examine text bad,
:cl:
fix: Fixed grills having duplicated deconstruction examine text
/:cl:
=> fixes duplicated examine text on grills

code/game/objects/items/tools/wrench.dm
Fixes a long-standing TODO about adding a glow to the medical wrench's suicide act. It indeed now glows, very brightly. You might now notice in your periphery a sudden glow where a medical doctor was just a moment ago begging for the syringe gun.
LET THERE BE LIGHT
https://user-images.githubusercontent.com/89928798/224173819-f4146292-e8c0-43d9-8db4-11e8d169a519.mp4
Suicided
:cl: Lewc, Vi3trice
tweak: Suiciding with the medical wrench now floods the area with holy light.
/:cl:
=> Medical Wrench suicide now glows brightly

_maps/map_files/cyberiad/cyberiad.dmm
Fixes Cyberiad AI core unprotected camera
All cameras inside the AI core should have start_active set to TRUE, to make sure its not turned off by various events.
- Compiled
Not important enough for players
=> Fixes Cyberiad AI core unprotected camera

code/modules/admin/verbs/adminpm.dm
Removes the "(ALERT)" button from messages recieved by admins, it was meant to only be shown to the sender not the victim.
Useless confusing buttons.
It's the same as the ping link, something that works very well.
:cl:
fix: Fixed (ALERT) button being shown to non-admins in a chat window admin PM
/:cl:
=> Fixes (ALERT) button being shown to non-admins in a chat window admin PM

code/game/objects/effects/meteors.dm
fixes meteors not causing enough damage
events should cause crew action, like evacuation
I saw it all burn down
=> Fixes meteors not being impactful

code/game/objects/effects/spawners/lootdrop.dm, code/modules/projectiles/guns/energy/stun.dm
Is it a rubber ducky or a gun? find out since its available as maints loot
FUNNI
Video is outdated, chance for shot is now 2%.
https://user-images.githubusercontent.com/77684085/229166636-8467e72b-cb63-432c-b4a0-bc0eb421cd24.mp4
video above
:cl:
add: Added a new gun to maints loot
/:cl:
=> Adds rubber ducky gun

code/modules/mob/living/carbon/human/species/machine.dm, code/modules/surgery/organs/augments_arms.dm
gives IPCs a minor buff
IPCs weak :(
it works
=> Minor IPC buff

code/modules/power/lights.dm
lights will be broken roundstart more
gives janitors something to do roundstart
yep lights broke
=> Buffs Janitors roundstart

code/game/objects/structures/crates_lockers/closets/secure/security_lockers.dm, code/modules/projectiles/guns/energy/stun.dm
Criminals must fear the Golden Bolt! The mighty HoS locker now has an anti-clown weapon!
Clowns must fear security!
Shot clowns.
=> Face the Wrath of the Golden Bolt!

code/game/verbs/ooc.dm
Enforces good decisions in OOC chat surrounding the playerbase and their choice in vehicular transport.
I was promised an M3 if I did this.
n/a
=> Enforces good decisions in OOC chat 

code/datums/status_effects/neutral.dm, code/modules/mob/living/silicon/silicon_emote.dm
Gives service robots an actual reason to exist: being able to dap other people up.
Nanotrasen research has demonstrated that dapping increases morale by a significant factor.
https://user-images.githubusercontent.com/89928798/229197639-8aaa2cad-c74a-4af6-86b4-3745b557d2cf.mp4
=> Service robots (brobots) can now *dap

code/game/objects/structures/crates_lockers/closets.dm
Fixes a bug with closets.
Closets should behave more or less as we'd expect.
Things seemed to work as they should.
:cl:
fix: Fixes a bug with closets.
/:cl:
=> Fixes a closet bug

code/modules/surgery/organs/subtypes/skrell.dm
Fixes headpockets not being able to store small items.
Non intentional change made by https://github.com/ParadiseSS13/Paradise/pull/19317
- Could store small sized items into headpockets
:cl:
fix: Fixed headpockets not being able to store small items
/:cl:
=> Fixes headpockets not being able to store small items

code/modules/mining/equipment/mining_tools.dm
It doubles the speed at which shovels dig dirt, or plants.
Pickaxes and shovels are equally good at digging up sand. Shovels are more specialized, so they should work better at what they can do.
I went to lavaland and played digdug, then I dug up some botany plants too.
:cl:
tweak: Shovels dig twice as fast
/:cl:
=> Shovels dig faster

_maps/map_files/cerestation/cerestation.dmm, code/game/machinery/camera/camera_presets.dm
Minor fixes that are required following the previous massive PR.
Adds plating under doors and shutters in cargo.
Adds more lights to library and bar.
Fixes the floor pattern in service south.
Fixes https://github.com/ParadiseSS13/Paradise/issues/20716
Fixes a longstanding bug with autoname cameras
Minor issues of no real consequence, but still annoying.
Eyeballs
:cl:
fix: Fixed minor issues that persist on cere station
/:cl:
=> Follow up Cere tweaks

code/modules/mob/living/living.dm, code/modules/mob/living/living_logout.dm
fixes #17668
I like performance and this should fix janky interactions with cryopods
=> greatly improves observer GCing

_maps/map_files/RandomRuins/LavaRuins/lavaland_surface_greed.dmm, code/game/objects/items/weapons/dice.dm, code/modules/ruins/lavalandruin_code/sin_ruins.dm
Decreased the amount of money the greed ruin has by 3000 credits.
Die of fate roll 17 and 20 have been tweaked.
17 (has been swapped with roll 14). Rolls a list with some uplink items instead of bundle now.
20. Gives you three free good rolls instead of wizard.
The roll 20 was the main reason greed ruin was removed, with those tweaks it could be put back into rotation.
3000 credits removed from it to adjust it to economy rework values.
- Compiled
- Used the die of fate rolls multiple times to test 17 and 20.
:cl:
tweak: Decreased the amount of money the greed ruin has.
tweak: Die of fate roll 17 and 20 have been tweaked
/:cl:
=> Tweaks to greed ruin and die of fate

code/modules/reagents/reagent_containers/borghydro.dm, code/modules/research/designs/mechfabricator_designs.dm
Fixes #20735
Fixes a minor spelling mistake as well
Things should work, no radial icon means it won't work, PR wasn't updated to be compat so it just won't show up in game
:cl:
fix: corazone now appears in abductor-upgraded hydros again
/:cl:
=> fixes #20735, makes corazone appear in abductor hydros

code/game/objects/items/stacks/stack.dm
Adds in a small bit of code that prevents like 5 runtimes every single time an engi borg spawns.
Less runtimes good
Compiled with fix and spawned in as engi borg, no runtimes
Compiled current master, spawned in as engi borg, got runtimes
Compiled with fix again and spawned in as engi borg, no runtimes
=> Fixes a runtime with cyborg stacks being initialized with no power source

code/modules/food_and_drinks/kitchen_machinery/processor.dm
title
Fixes https://github.com/ParadiseSS13/Paradise/issues/20842 oversight.
- Could rotate using alt+click non anchored processors
:cl:
tweak: You can now alt+click rotate processors
/:cl:
=> You can now alt+click rotate processors

code/game/objects/items/devices/flashlight.dm, code/game/objects/items/weapons/cigs.dm, code/game/objects/items/weapons/storage/fancy.dm, code/modules/hydroponics/grown/banana.dm, code/modules/mob/living/silicon/robot/drone/drone_items.dm, code/modules/paperwork/paper.dm
Matter decompiler now works on cigarettes, empty donut box, banana peel, paper scrap, flares with no fuel.
Removed a no longer valid // TODO comment.
These items are found over the floor as trash most of the time, the drone should be able to scrap them.
- Tried to decompile these items, full and empty.
:cl:
tweak: Matter decompiler now works on cigarettes, empty donut box, banana peel, paper scrap, flares with no fuel
/:cl:
=> Small matter decompiler tweaks

code/modules/mob/living/silicon/ai/ai_mob.dm
Fixes #20315 
Runtimes are annoying, stuff needs sanity checks if it's messing with UIDs and /refs
Compiled, made sure you can still track people
=> fixes an ai UID runtime

code/game/objects/items/crayons.dm
Spraycan icon now updates properly when removing the cap.
Fixes https://github.com/ParadiseSS13/Paradise/issues/20896
- Removed cap and changed color, works now.
:cl:
fix: Spraycan icon now updates properly when removing the cap
/:cl:
=> Fixes spraycan icon not updating properly

code/game/gamemodes/miniantags/guardian/guardian.dm, code/game/gamemodes/miniantags/guardian/host_actions.dm
Fixes a guardian communication runtime
Dead guardians/hosts shouldn't be attempting to send each other messages
Tried talking it up as a solo guardian
=> fixes a guardian communication runtime

code/modules/events/event_procs.dm
Makes it so anomalies can't spawn in cryogenics anymore
Admeme asked me to do it
But in all seriousness, not waking up to a flux anomaly/spaced cryogenics/demons is nice
It's a simple adding of an area and I don't have the time to 
:cl:
fix: Fixes anomalies spawning in cryogenics
/:cl:
=> Anomalies can't spawn in cryogenics

code/modules/mob/living/silicon/pai/recruit.dm
Ensures when a pai is downloaded, that the mob is trying to download is an observer, rather than a pai, slaughter demon, ect.
bugs bad
ensure bugs not happen
:cl:
fix: Fixed being able to download downloaded pais
/:cl:
=> Fixes being able to download an already downloaded pai.

code/__DEFINES/status_effects.dm, code/datums/status_effects/neutral.dm, code/modules/crafting/guncrafting.dm, code/modules/crafting/recipes.dm, code/modules/projectiles/guns/energy/laser.dm, code/modules/projectiles/guns/misc/blastcannon.dm, code/modules/projectiles/guns/projectile/sniper.dm, code/modules/projectiles/projectile/beams.dm, code/modules/projectiles/projectile_base.dm, code/modules/research/designs/weapon_designs.dm
Lwap now crafts from a base laser vs the accelerator laser cannon. Same material cost, half the crafting time, crafting a gun twice is silly.
The LWAP now has a super advanced NT targeting scope in it. Capable of highlighting creatures in pitch black darkness, not even walls can stop the targeting. It takes 3 seconds to activate the scope's targeting.
However the scope is not perfect, and highlights mobs as dots. No diffrence between friend or foe. Could be a xenomorph, could be a vampire, could be a fellow officer. Communication is key.
LWAP projectile is now 25% faster unscoped, 2x scoped. This should make the longer shots possible. I might keep this at 2x for scope, will see how people feel. Otherwise without the speed boost, hitting a long shot on a mobile target is near impossible. …
=> Reworks the lwap to make it better.

code/modules/mob/living/simple_animal/hostile/megafauna/ancient_robot.dm
Vetus no longer shoots dead bodies
Vetus no longer has legs shuttle gibbed.
Vetus projectiles are now proper bullets.
Vetus scales in attack speed slightly below 50% hp.
Vetus no longer calculates it's cap for each human in range.
Vetus makes slightly more rocks on vortex, and vortex vetus actually hits everything in the turf with EX act, rather than just the turf.
Vetus charge scales less then other moves as it is injured.
Stupid projectile paths are bad, vetus endlessly shooting at dead legions is bad, vetus being slightly harder on vortex / as it gets injured is good.
Confirmed vetus worked as expected / still shot projectiles / ex act'd right.
:cl:
fix: Vetus no longer can have its legs gibbed, and legs no longer shoot at dead legion bodies.
tweak: Vetus scales in difficulty better as …
=> tweaks / fixes vetus a bit

code/modules/events/brand_intelligence.dm
Fixes a typo
Fixes: #20996 
Typo bad
Yes, I've heard of this before
:cl:
spellcheck: "Obession" -> "Obsession"
/:cl:
=> Fixes brand intelligence typo

_maps/map_files/cyberiad/cyberiad.dmm
Reverts ParadiseSS13/Paradise#20648
broke maints and a bunch of other stuff I’m making this pr at 5am woo
=> Revert "Cyberiad: Maintenance Rework [Part #1] (Fixed merge issue)"

code/modules/admin/verbs/one_click_antag.dm
Fixed thunderdome only allowing up to 9 players to participate.
Thunderdome no longer allows for an odd number of players to participate
Bugs are bad, and we dont want to set up unfair fights without admin input.
- Compiled
:cl:
tweak: Thunderdome no longer allows for an odd number of players to participate
fix: Fixed thunderdome only allowing up to 9 players to participate
/:cl:
=> Thunderdome no longer allows unfair fights

code/datums/spells/alien_spells/larva_evolve.dm
The sentinel in the evolve menu appears as a sentinel now
You should be able to tell what xeno you're picking
see above
:cl:
Fix: Xeno larva's evolve menu now shows the sentinel for picking sentinel
/:cl:
=> Fixes sentinels appearing as drones in the evolve menu

code/__HELPERS/_logging.dm, goon/browserassets/css/browserOutput-dark.css, goon/browserassets/css/browserOutput.css
Adds a custom span class for debug logs, while still trying to keep them non-intrusive.
Its hard to tell debug logs against normal chat messages
Debug logs compared to science comms, server announcement, and deadchat
See above
:cl:
nothing player facing
/:cl:
=> Adds color to debug text

code/game/objects/items/hand_item.dm
Fixes a bug with slappers that allowed you to highfive quicker than intended.
My ears hurt.
Also, it's incredibly spammy, and not at all what I intended.
:cl:
fix: Fixes high-speed highfives
/:cl:
=> Fixes rapid highfives

code/modules/events/event_container.dm
Changes shadow demon spawn weight from 50 -> 20
Changes slaughter demon spawn weight from 10 -> 20
There will be less shadow demons, and more slaughter demons, but they will now appear with the same frequency.
Hal said to do it - 
Uh, I mean, Shadow Demons had a high spawnrate when they were introduced - this was meant to be toggled down eventually, to be in line with Slaughter Demons, but that never happened, so we may as well do it now.
However, Slaughter Demons are absurdly rare, and could honestly stand to spawn more frequently, so their weighting will also be increased.
Numbers change.
:cl:
tweak: Slaughter Demons spawn more frequently, and Shadow Demons now have the same chance as Slaughter Demons
/:cl:
=> Tweaks demon spawn rate

code/modules/food_and_drinks/food/foods/meat.dm
Fixes #20959
Now cutting raw cutlets in hand with a knife actually creates bacon
More bacon is always good
1. spawned as chef
2. spawned raw cutlets
3. cut cutlets in hand
4. Woo! Bacon!
:cl:
fix: Fixed getting bacon from cutlets in hand
/:cl:
=> fixes bacon from cutlets in hand

code/datums/uplink_items/uplink_traitor.dm, code/game/machinery/syndicatebomb.dm
EMP bomb now pulses 3 times.
Righty-o. The emp bomb does create a nice big EMP. It fits that... niche. 
One can buy 4 emp kits for the same price, and get almost certainly get better emp coverage, hitting things more, covering more area, and getting more precise control.
By increasing the pulses to 3, this might be worth it as an area denial that keeps everything hit by EMP down for sure for a bit.
It may be worse lowering price, but I don't want damage to be too much for engineering to want to repair, if people spam this. 
confirmed it worked by setting it off
:cl:
tweak: EMP bomb now explodes 3 times
/:cl:
=> Makes emp bomb more useful

code/game/objects/structures/flora.dm
This makes the plant pot hide a mob's HUD when wielded. Restores it when dropped.
Sneaky plant pot time.
Before:
After:
Plant pot
:cl:
tweak: Holding a plant pot hides a mob's HUD
/:cl:
=> Holding a plant pot hides mob HUD

.github/CONTRIBUTING.md
- Adds myself to the Headcoder list, replacing Charliminator
- Adds AffectedArc07 and Charliminator to the Commit Access list
- Moves Sirryan2002 from the Commit Access list to the Review Team list
N/A
=> Updates Github Staff List in CONTRIBUTING.dm

code/modules/reagents/chemistry/reagents/admin_reagents.dm
Adminordrazine now removes 60 damage per 2 seconds, healing a full stun (120 stam damage) in 4 seconds. It also resets the user's temperature back to their normal body temperature
DO NOTE: Gamma med ERT has the same autoinjector as deathsquad, meaning that they also have this absurd amount of healing. Maybe it should be changed to another chemical
Deathsquad's two major weaknesses right now are stamina, and cold. This makes it so with enough effort, yes you can keep them down for prolonged times, but they will get back up.
Put myself in space, adminrazine, no more cold. Stunned myself, and slowly got back up
:cl:
tweak: Adminordrazine now heals stamina damage and protects against the cold
/:cl:
=> Buffs Adminordrazine against stamina and cold

code/_onclick/hud/radial.dm
Changes radial menu opening speed to be faster
Currently radial menu is opening kinda a bit long. If you do surgery with your surgery toolset implant, those icons opening and moving too slow. This PR changes it to be faster
https://youtu.be/h9-gMTgcKxQ
new speed on the bottom
:cl:
tweak: Radial menu is opening faster
/:cl:
=> faster radial menu

code/modules/recycling/disposal.dm
this PR fixes a bug. Previously if you shove someone into trash bin its icon wont update and you wont see that someone is inside it
bugs bad
compiled, shoved drask into bin
:cl:
fix: Trash bin icon now updates when you shove someone into it
/:cl:
=> Fix: Trash bin icon not updating when someone got shoved in

code/modules/clothing/head/helmet.dm, code/modules/clothing/spacesuits/misc_spacesuits.dm, code/modules/clothing/suits/armor.dm, code/modules/supply/supply_packs/pack_security.dm
Removed SWAT suit spaceproof
Removed SWAT suit slowdown on wearing
Added BLOCKHAIR to SWAT helmet
Currently SWAT kit is useless slow spacesuit withour proper helmet. It makes SWAT armor the thing all security ignores all the time. 
As we dont usually fight in space and we hate it, there is no need for another security hardsuit with just a little bigger stats. 
You will never see experienced security officer using SWAT suit in ever cause its slowdown makes you weaker and its stats is not that big.
This change removes SWAT suit slowdown aswell as spaceproof.
In result, we have middle between bulletproof vest, riot vest and ablative vest which would be good for security to use.
It has the same(with some exceptions) armor stats as default security armor vest, but this one will cover all your …
=> SWAT suit tweak

code/game/objects/items/weapons/cigs.dm
It makes it so that all Zippo lighters can light all Cigars
it just doesnt make sense why a classy zippo lighter is said to be too uncivilized to light a cigar
i booted up the code and tried lighting all cigars with all zippos and then checked to make sure cheap lighters couldnt light the cigars
:cl:
tweak: You can now light cigars with zippos
/:cl:
=> Zippos can light Cigars

code/game/objects/items/weapons/stunbaton.dm
This PR brings back stutter effect on batonning someone. Beepsky had them, but stunbaton after rework lost it.
H-hel-lp m-main-n-nt-ts-s is funny. 
H-hel-lp m-main-n-nt-ts-s!
:cl:
fix: Stunbaton now applies stutter effect again on hit("H-hel-lp m-main-n-nt-ts-s!")
/:cl:
=> H-hel-lp m-main-n-nt-ts-s!

code/__HELPERS/unsorted.dm, code/game/machinery/deployable.dm
The dropwall now lasts a minute rather than 12 seconds. Having cover for such a short time is practical, and it doesnt block movement, so its fine to last that long.
Dropwall has some armor now, so it doesnt die as fast as before. No melee armor.
The dropwall generator will survive explosions a little better, though a maxcap will still destroy it. Shields are uneffected.
The dropwall now automatically deploys when thrown when armed, rather than waiting for the timer to run out.
The dropwall now has an automatic mode, where it tries to orient the wall to protect you. Throwing it north will block north, south will block south, ect.
Yeah the dropwall is niche. Instant directional cover is good, but it lasts far too little time to hold a position, takes too long to deploy for quick combat, …
=> Makes the dropwall probably viable

code/__HELPERS/text.dm
Currently, if someone has any rights (such as view runtimes), every time they write down on paper, they get 
`Error: You do not have sufficient rights to do that. You require one of the following flags: +EVENT.`
This checks that the error only shows up if they try to create a signfont
Getting errors for no reason is bad
Messed around with admin privileges and signing on a local server
=> Fixes for [signfont]

.github/workflows/render_nanomaps.yml, tools/github-actions/README.MD, tools/github-actions/nanomap-renderer-invoker.sh
Use up-to-date VM and updated SpacemanDMM, with source modifications retained.
Keeps maps up-to-date
Ran action on my fork successfully.
:cl:
fix: Fixed nanomaps
/:cl:
=> Fix render_nanomaps action

_maps/map_files/Delta/delta.dmm, _maps/map_files/MetaStation/MetaStation.dmm, _maps/map_files/cerestation/cerestation.dmm, _maps/map_files/cyberiad/cyberiad.dmm, code/modules/mob/living/simple_animal/friendly/sloth.dm
https://github.com/ParadiseSS13/Paradise/pull/20831 Was busted, this remakes it
Maps gorillas (name: `Forklift`) into cargo, moves paperwork to IAA and tweaks desc.
Relies on https://github.com/ParadiseSS13/Paradise/pull/20830 being merged, DO NOT MERGE without that.
:cl:
tweak: Moved paperwork to IAA department, mapped in cargorilla to cargo
/:cl:
=> Gorilla mapping changes 2

_maps/map_files/Delta/delta.dmm, _maps/map_files/MetaStation/MetaStation.dmm, _maps/map_files/RandomRuins/SpaceRuins/ussp.dmm, _maps/map_files/RandomZLevels/example.dmm, _maps/map_files/cerestation/cerestation.dmm, _maps/map_files/cyberiad/cyberiad.dmm, _maps/map_files/shuttles/emergency_bar.dmm, code/modules/instruments/objs/structures/piano.dm, code/modules/supply/supply_packs/pack_miscellaneous.dm
Updates the pianos path instead of using "parent_type =" for it.
Kills this 
- Spawned lots of pianos and tested them.
No change for players
=> Updates piano path

code/modules/reagents/chemistry/reagents/medicine.dm
Buffs the duration of 15 units morphine from 75 seconds to 120 seconds
Lets people who are learning surgery and slow at surgery, to have a bit more time for completing surgeries, as well as reducing the chance of causing morphine addiction in patients, for the rare times when they got a plasmaman or vox in surgery.
This will also make using morphine IV bags very unviable.
Inject human with 15 units on morphine, and track time with a clock
:cl: ppi
tweak: Increases the duration of Morphine
/:cl:
=> Buffs morphine duration

code/modules/research/designs/medical_designs.dm
Moves the requirements from power 6 to power 5.
Holostretchers arent used that much despite their common need of dragging bodies around without spilling blood everywhere. Most people just use body bags as the paramedic because you can do the same rescuing without and research and without spilling blood. Power 6 is usually one of the last researches gotten (botany moment), so you dont usually see it around.
It also deconstructs for `"magnets=3;biotech=4;powerstorage=3"`, so you cant abuse it to get around the tech tree
Tested it, its cheaper research wise
:cl:
tweak: Holostretchers can now be made with power 5 research
/:cl:
=> Decreases the research requirement for Holostretchers

code/modules/reagents/chemistry/recipes/drinks_reactions.dm
Adds 1 part mint to the mojito recipe
IRL Mojitos have mint in them, this also makes it 5 parts so you can make an even 100 units in a shaker.
just changed a value, _**shouldnt**_ need testing
:cl:
tweak: Making a Mojito now requires 1 part Mint
/:cl:
=> adds mint to mojito recipe

code/game/objects/items/latexballoon.dm, code/game/objects/structures/crates_lockers/closets/secure/depot_closets.dm, code/game/objects/structures/depot_structures.dm
Adds descriptions to the latex glove balloons, syndicate fusion reactor and supply depot closets.
Just some added fluff and humour to some items that didn't have any description beforehand
:cl:
add: Descriptions to the latex glove balloons, syndicate fusion reactors, and supply depot closets.
/:cl:
=> Added empty descriptions

code/datums/outfits/outfit_admin.dm
Honksquad clowns now spawn with comic sans and title of "Emergency Response Clown". Their name is now also selected from clown name list and is prefixed by their rank (Trickster First Class, Master Clown or Major Prankster")
Previously honksquad clowns spawned WITHOUT THE COMIC SANS FONT GENE. This PR aims to fix this.
:cl:
tweak: Honksquad clowns now spawn with comic sans and proper title
/:cl:
=> Honksquad clowns now spawn with comic sans and title

code/modules/tgui/modules/ghost_hud_panel.dm
Fixed ghosts not being able to deactivate antaghud
Fixes https://github.com/ParadiseSS13/Paradise/issues/21178
- Compiled, turned of admin
- Created an antag
- Activated the antaghud as a ghost and could see the hud
- Deactivated the antaghud and could no longer see the hud
:cl:
fix: Fixed ghosts not being able to deactivate antaghud
/:cl:
=> Fixes ghosts not being able to deactivate antaghud

code/modules/projectiles/ammunition.dm
Empty shotgun shells no longer runtime on EMP
As it turns out, spent shotgun shells runtiming on EMP is in fact bad.
set off an EMP with spent shotgun shells around
N/A not player facing
=> Empty ammo no longer runtimes on EMP

code/modules/mob/new_player/sprite_accessories/human/human_hair.dm
Fixes: #20840 ; See title
Less confusion in code, typepath was unused and redundant.
=> Oversight fix: Remove redundant typepath for "Flat Top" hair

code/modules/reagents/chemistry/reagents/medicine.dm
Fixes #21143
Makes it so nano calcium is guaranteed to fix burn wounds/IB/broken bones
Before there was a small chance that it could fail to fix these things
also reduces the weaken time by half
Probably shouldnt be possible for a 4 tc item to do jack
30 seconds of weaken is a long time, 15 feels slightly more fair
1. give self burn wound/IB/Broken bones
2. inject self with nano calcium
3. sit on the floor for 15 seconds
4. no more IB/wounds/broken bones
5. profit
:cl:
tweak: lowered weaken time for nanocalcium
tweak: removes chance for nanocalcium to not fix your wounds
/:cl:
=> Makes it so nano calcium always fixes bones/IB/burns and lowers weaken time

code/game/objects/structures/crates_lockers/closets/secure/medical_lockers.dm
Actually adds MedHUD Sunglasses to Paramedic and CMO. This was intended in #21129 but I cant read.
This was intended in #21129.
Actually double-checked the locker.
:cl:
fix: actually adds MedHUD Sunglasses to the CMO/Paramedic Lockers.
/:cl:
=> Adds MedHUD Sunglasses to CMO/Paramedic

_maps/map_files/cerestation/cerestation.dmm
Its in the title
yes
:cl:
tweak: Added Safecodes to Farragus
/:cl:
=> Adds Safe Codes to Farragus

code/game/gamemodes/cult/blood_magic.dm
Cleans up code, makes blood rites collect blood if you didnt click human or construct by default(prev you needed to click blood itself), allows you to collect blood in full darkness
blood rites not working in full darkness while all cult is wearing nightvision blindfold is stupid
`if`
`   if`
`        if`
`            if`
code is bad
compiled, tested
:cl:
tweak: Now you can click any object with Blood Rites to collect blood
tweak: Applying Blood Rites on cultist cleans their blood on clothes
fix: Now Blood Rites blood collection works in full darkness
/:cl:
=> Blood rites refactor

code/game/gamemodes/wizard/spellbook.dm
Removes a var that was added in magic nanny bag but not removed in https://github.com/ParadiseSS13/Paradise/pull/21136
Since the CI for that ran before magic nanny bag was merged, the conflict was not detected.
I need to add more things to my mental checklist as a commit access member, it seems.
=> Fixes a stealth conflict

code/modules/food_and_drinks/food/customizables.dm
Clicking on a burger bun with a non food item will now do stuff with it, like adding it to a tray.
bug bad
click on bun, bun on tray
:cl:
fix: You can now click on buns to add them to trays
/:cl:
=> Fixes an issue with adding buns to trays

code/datums/armor.dm
Fixes an error I made in #21108
Bugs bad
Bathed in green light
:cl:
fix: fixed rad-immune clothing not working correctly
/:cl:
=> Fixes radsuits not working correctly

code/game/machinery/turret_control.dm
Fixes an issue with turrets not updating on roundstart to be what their turret controller says they should. This was due to the changes with the proc `power_change()` during #19991.
Bug bad
Turrets now update roundstart
:cl:
fix: Fixes a bug with AI turrets not updating to match their turret controller on roundstart.
/:cl:
=> Fixes an issue with turrets not updating on roundstart

code/datums/uplink_items/uplink_traitor.dm
Decreases the price of CQC from 13tc to 10tc for traitors, it can also now be discounted
CQC is good in 1v1, but it doesn't have much use against more than one opponent. Its closer to a stealth weapon now, and while still being viable, isn't as good as other 13tc weapons, like the chainsaw or carp. 
Its 10 TC for traitors now.
:cl:
tweak: CQC price decreased from 13tc to 10tc
tweak: CQC can now be discounted
/:cl:
=> Decreases the price of CQC to 10tc, CQC can now be discounted

code/modules/supply/supply_packs/pack_engineering.dm
This lowers the price of solar pack crates at cargo from 250 to 100 credits.
The amount of power a solar assembly crate, after a decent amount of effort, can output is significantly lower when compared to the other options available to order, those being TEGs and shards with those costing 250 and 750 respectively. The goal of this PR is to make solar assembly crates more accessible to individual engineers or large scale engineering projects by reducing the cost and better scaling it to other sources of power.
Went in game and checked that the price was now 100 credits at a cargo console.
:cl:
tweak: Reduces Solar Pack Crate price from 250 to 100 credits
/:cl:
=> Reduces Solar Crate Price from 250 to 100

code/modules/mob/living/carbon/carbon.dm
When you activate throw mode, you cursor will be changed
When you deactivate it, cursor goes back
I messed up with throwing my stunbaton instead of beating someone too many times
This is how active throwing cursor looks like
same as cult spell hallucination
compiled, threw items
:cl:
tweak: Active throw mode now changes cursor
/:cl:
=> Throw mode changes client cursor when activated

code/datums/uplink_items/uplink_general.dm, code/game/objects/items/devices/traitordevices.dm, code/modules/clothing/chameleon.dm
Adds a new chameleon item, chameleon mesons (I think they would be cool to add to maints, but thats another PR)
Having style is cool, and it allows for newer players to handle the teleporter better
see above
:cl:
add: Syndicate Teleporter kit now comes with chameleon mesons
/:cl:
=> Synditele kit now comes with chameleon mesons

code/datums/status_effects/status_effect.dm, code/modules/mob/living/carbon/carbon.dm
You can now help intent click on people to complete a dap, highfive, or handshake. Also does some refactoring of the nearby code
Makes it easier to do stuff like handshakes without binds
Tested it, realized I put in some wrong code, tested it again and it worked
:cl:
add: You can now help intent click on people to complete a dap, highfive, or handshake
/:cl:
=> You can now help intent click on people to complete a dap, highfive, or handshake

code/game/machinery/machinery.dm, code/game/machinery/portable_turret.dm
Fixes an issue where machinery did not consume power upon use, except for turrets.
It's an intended feature that was bugged.
Went to the chapel
Cremated some skrell
Went home
Turned on PC and test server
Spawned in some skrell
Cremated some more skrell and saw the chapel APC take a big hit of power consumption
:cl:
fix: machinery now properly consumes power on use
/:cl:
=> Makes machinery properly consume power on use

code/datums/spells/summon_supermatter.dm
removes a debug to_chat
oops
I didn't
:cl:
fix: Summon supermatter no longer notifies the world when it's created
/:cl:
=> removes a debug check that I forgot to cut

code/modules/reagents/chemistry/reagents/toxins.dm
Sarin now works overdosed again
bugs bad, missed it since it did not have a special overdose effect. Yes, I should have made things process on overdose by default, I know
fixes #21277 
:cl:
fix: Sarin now works overdosed again
/:cl:
=> Sarin now works overdosed again

code/datums/uplink_items/uplink_nuclear.dm, code/game/mecha/equipment/weapons/weapons.dm, code/modules/projectiles/ammunition/ammo_casings.dm, code/modules/projectiles/guns/rocket.dm, code/modules/projectiles/projectile/special_projectiles.dm
This PR gives rocket launchers a much needed update, turning them into actual guns instead of having them throw the rockets at people. Adds it into nukie uplink in a more usable state. This is still a work in progress, mostly because this forces me to touch mech weapon code too, and that will take a while for me to figure out how to fix that.
Everyone loves using rocket launchers in video games. They're satisfying, fun, and VERY destructive. Considering nukies is a gamemode all about mass destruction, rocket launchers fit right into that playstyle. 
I blew up a lot of skrells, damage numbers will need further tweaking, and I'll test a bunch of the mech weapon subtypes when I get around to it.
:cl:
tweak: Refactors the rocket launcher, and adds it into the nuclear agent uplink.
/:cl:
=> Refactors rocket launchers, adds it to nukie uplink

code/game/gamemodes/wizard/soulstone.dm
Fixes the soul stone that miners get to actually work.
Resolves #21210 
Went into a test server, checked if I took damage when trying to use a soul stone
:cl:
fix: soul stones that are supposed to be usable by everyone are now actually usable by everyone
/:cl:
=> Makes soul stones that are supposed to be usable by everyone actually usable by everyone

code/modules/research/experimentor.dm
Blacklists certain items from the experimentor.
Because it's bad.
Source: Dude, just trust me
VV experimentor
Check valid_items
No longer in list
:cl:
fix: Blacklists certain items from the experimentor.
/:cl:
=> Blacklists certain items from the experimentor.

code/modules/shuttle/shuttle_manipulator.dm
See title, makes sure that the vars or var_edited variables are never edited
Intended functions are good, although this shouldn't happen in normal gameplay
NPFC
=> adds a little extra security to shuttle manip var-editing

code/controllers/subsystem/tickets/tickets.dm
Fixes a spelling error with Representative
Spelling error bad
its spelling change
:cl:
spellcheck: Representetive -> Representative
/:cl:
=> Fixes a spelling error with Representative

_maps/map_files/cerestation/cerestation.dmm
Adds a pipe that was missing. Also slightly moves the distro pipe to avoid any chances of anything linking that shouldn't.
Missing pipes bad. Also, it has apparently been seen by someone that the distro pipe above it had no air in it sometimes.
Fuck it we ball
:cl:
add: missing pipe and a slight change of distro layout
/:cl:
=> Fixes a missing pipe on farragus

_maps/map_files/MetaStation/MetaStation.dmm
Fixes: #21314
you shouldn't be able to access ~~a charger~~ Stuff on both sides of a wall.
Before: 
After:
there was two other tiles that were pointed out AFTER i had posted this, so i've also fixed the guest pass terminal, and sci requests console.
Checked if the charger was inside the wall, it wasn't.
:cl:
fix: Fixed being able to reach a charger, guest pass terminal, and requests console on both sides of a wall on meta station
/:cl:
=> fixes a minor over sight with meta stations RnD

_maps/map_files/cyberiad/cyberiad.dmm
Fixes several lattice/firelock issues on Box. Continuation of #19875 burndown.
<details><summary>Images</summary>
</details>
:cl:
fix: lattice and firelock issues on Box
/:cl:
=> Box: fix lattice and firelock dupes.

_maps/map_files/Delta/delta.dmm
Removes many stacked lattices. Continuation of https://github.com/ParadiseSS13/Paradise/pull/19875 burndown.
<details><summary>Images</summary>
</details>
:cl:
fix: fixed lattice issues on Delta
/:cl:
=> Delta: fix many lattice stacking issues

code/game/objects/items/control_wand.dm
Interrupting they keyring unlock should no longer brick the Janitor's keyring.
Fixes #21433 
Code should work :gatto:
Tested interrupting the keyring open proc.
:cl:
fix: Fixed the janitor's keyring from getting stuck in the "busy" state.
/:cl:
=> Janitor Keyring Fix

code/modules/antagonists/changeling/datum_changeling.dm
Fixes a bug with changeling headslugs
:cl:
fix: Fixes a bug with changeling headslugs
/:cl:
=> Fixes a bug with headslugs

code/datums/elements/waddling.dm, code/game/area/areas.dm, code/modules/power/gravitygenerator.dm
Reverts ParadiseSS13/Paradise#20944
This PR has resulted in some really fucking weird behavior. I don't really know why, and I'm not in a position to investigate it. I may reopen if I can down the line with proper testing.
Why, gravity code, why???
(I will probably also edit this PR desc with the proper formatting, I'm just on mobile and this is all I get)
=> Revert "Allows for the gravity generator to be cmagged."

code/game/machinery/computer/robot_control.dm
When an AI hacks a borg, its modules get emaged as well. This means medborgs get their emaged defibs / mining borgs get the better drill.
Also makes it update to the malf module icon to make it more clear (only borg sees this on hud.)
borgs should get the stuff that emaged borgs get when hacked by AI
confirmed borg gets the funny defib.
:cl:
fix: Borgs hacked by malf AI now get the emaged upgrades to equipment, primarly medborgs emaged defib.
/:cl:
=> When an AI hacks a borg, its modules get emaged as well

code/game/gamemodes/objective.dm
Spiderbots no longer count as "alive", similar to silicons/brains. Also a slight refactor of code to minimize copy pasting
Fixes #21346. I asked design team and they generally agreed that spiderbots do not count as alive
Put my assassinate objective in a spiderbot, counted for the objective
:cl:
fix: Spiderbots now count as "dead" for objectives
/:cl:
=> Spiderbots now are properly accounted for with objectives

code/modules/mob/living/carbon/human/species/monkey.dm
Monkies now have half the hunger rate as a normal humanoid mob.
Monkies are much smaller, and take 2x effective damage from brute and burn. Allowing the NPC monkies like pun pun and the wizard den monkey to not starve every round would be nice. (They can't eat for themselves anyways, I feel bad for them)
I checked that the variable was changed. I'm not gonna wait 3.5 hours to watch a monkey starve
:cl:
tweak: Monkeys and other lesser forms now take twice as long to starve
/:cl:
=> Monkies now take twice as long to starve

code/modules/hydroponics/gene_modder.dm
I added a check for seed in the disk part, where the previously was none. Fixes a runtime.
Fixes a runtime
(UPDATED) I put a plant disk in the gene modder with no seed, and it didn't runtime
Nothing player facing, just a runtime
=> Fixes a runtime with the genemodder

code/game/turfs/simulated/floor/transparent.dm
Title. Not sure if this is really an exploit so I won't go into much detail but this also cleans up the code.
bugs bad, readability good
I loaded in and placed a glass floor, then pried it up
:cl:
fix: Fixes an issue with glass flooring
/:cl:
=> Fixes an issue with removing glass flooring

code/__DEFINES/dcs/signals.dm, code/game/objects/structures/flora.dm, code/modules/mob/living/carbon/carbon_update_icons.dm
Fixes an issue with potted plants that left users in an undesirable state.
Exploits bad, fixes good.
Tested various plant actions.
:cl:
fix: Fixed an exploit with potted plants
/:cl:
=> [s] Fixes an issue with potted plants

code/modules/clothing/suits/armor_suits.dm
Adds sprite_sheets for greys in armor vest code
Using the wrong sprite is bad and I hated how it looked.
Old
New
oh i forgot to fill this part out but simply just look above this anyways
:cl:
fix: Fixes armor vest sprites for Greys
/:cl:
=> Fixes vests using the incorrect sprites for Greys

code/modules/projectiles/guns/energy/laser.dm, code/modules/projectiles/guns/projectile/sniper.dm, code/modules/projectiles/projectile_base.dm
If we were aiming at one target and hit another one, our accuracy will be 0 and we will hit random bodypart
With those burn wounds that makes your right foot dead random laser through hallway became a madness. This supposed to make it less painful, if you were not aiming at target, you will not hit bodypart you selected.
compiled, shoot
:cl:
tweak: Projectile will hit selected bodypart only if you shoot at target 1 tile away or less from person you hit(sniper shots are not affected by this change)
/:cl:
=> Projectile accuracy tweak

code/datums/uplink_items/uplink_general.dm, code/modules/reagents/chemistry/reagents/medicine.dm
Makes Nanocalcium cost 2 TC, and also completely disinfect the user.
Nanocalcium costing 20% of your total TC while also stunning you for 2 minutes isn't very nice. Also if you had a burn wound you'd still have the infections from it.
Gave a skrell an infection. Saw as nanocalcium fixed the infections.
:cl:
tweak: Nanocalcium now costs 2 TC and also cleanses your germs
/:cl:
=> Buffs Nanocalcium

code/game/objects/items/weapons/weaponry.dm
Fixes #21183
All I had to do was add the random blocker flag so the bat will deflect stuff again. I think it would be cool to rework this to not be random block but that would take a lot longer than this one-line change.
The bat works as intended now.
I used the matter driver to throw small objects at myself and it worked.
:cl:
fix: The baseball bat can deflect small objects again.
/:cl:
=> Fix baseball bat deflecting small objects 

code/modules/awaymissions/mission_code/ruins/derelict5.dm
Changes one word in a space ruins riddle.
Makes it so the riddle leads people to the correct place instead of a wall.
One singular word change, crossing my fingers and praying to the honkmother.
Forgive me
:cl:
fix: Fixes a mistake in a space ruin paper.
/:cl:
=> Fixes a minor mistake in a space ruin riddle.

code/modules/mob/living/simple_animal/bot/bot_construction.dm
Fixes a bug
Fixes #14777
Less bugs is good
Stupid stuff didn't happen
:cl:
fix: Fixed an old issue with bot comms
/:cl:
=> Fixes an issue with bot comms

_build_dependencies.sh
Updates the beta version used for CI beta tests to the latest public beta versions, since new build errors have been added in recent versions.
Stops stealth errors blocking server code deployment.
Stealth error that will now be detected by CI:
Not detected on earlier 515 build:
Not detected on 514:
=> Bumps CI beta version

code/modules/reagents/chemistry/reagents/water.dm
Cleans up some code in the blood reagent's `on_merge`, fixes an oversight
Cleaner code good, different types of blood should interact properly when mixed
Mixed together various types of blood to make sure previous mechanics still worked as intended
:cl:
fix: Properties of blood now interact properly when mixed
/:cl:
=> [s] Fixes some blood properties not interacting properly

code/modules/mining/machine_redemption.dm
Fixes an issue where upgrading the machine didn't upgrade anything
It had bad logic so upgrades weren't working
Insert 1 diamond ore into each version
:cl:
fix: Upgrade parts now affect Ore Redemption machine. Time to upgrade it and multiply our resources!
/:cl:
=> fix: upgrades parts now affect ore_redemption machine

code/game/machinery/doors/airlock.dm
fixes a lag exploit
lag bad, performance good
Nobody needs to know
=> [s] fixes a lag exploit

code/modules/antagonists/changeling/powers/transform.dm
Fixes #14122
Exploit bad
Tested it, exploit didn't happen
Nobody needs to know
=> [s] fixes a cling exploit

code/game/objects/items/toys.dm, code/modules/mob/living/living.dm
Fixes an issue.
Issues are bad.
Things worked as they should
N/A
=> [s] Fixes an inconstancy 

.github/CODEOWNERS
Makes myself codeowner of build dependencies
Given I own the entirety of CI, this makes sense. The server might also use this file one day.
None
N/A
=> Makes myself codeowner of build dependencies

code/modules/mob/living/carbon/carbon.dm
Clicking on someone to finish a dap/highfive wont play the hug sound effect anymore. This code is intended to be pre-hugcode.
Oversight bad
It works, no extra sound now
:cl:
fix: Clicking on someone to finish a dap/highfive wont play the hug sound effect anymore.
/:cl:
=> Fixes an issue with dap/highfive code

code/datums/uplink_items/uplink_general.dm, code/datums/uplink_items/uplink_traitor.dm, code/modules/clothing/gloves/misc_gloves.dm
Gloves of the north star now work with martial arts, but have a 0.4 second delay instead of 0.2 seconds. Suggested by Qwerty. GOTNS + CQC is 18 tc, GOTNS + Sleeping carp is 21 tc. These can both be discounted but it makes you a VERY dangerous foe, especially in 1v1.
GOTNS also works with all intents now.
Gloves of the North star isnt even worth 4tc by itself, outshined by stuff like the stechkin
https://github.com/ParadiseSS13/Paradise/assets/91113370/c4edff1f-fc84-4e22-8b17-51299972c8b6
Killed a lot of skrells with GOTNS + CQC and GOTNS + Sleeping carp
:cl:
tweak: Gloves of the North Star now work for martial art users, but at a slightly slower pace.
tweak: Gloves of the North Star is now quicker on all intents.
/:cl:
=> Gloves of the North Star now allow Martial Arts

code/modules/events/rogue_drones.dm
Fixes #20487
This is my first time doing gc stuff, I hope this is the correct way to do it
Fixes a gc fail
I ran the event and deleted a drone. It was removed from the list.
=> Fix malfunctioning drones failing to GC

code/datums/outfits/outfit_admin.dm, code/game/gamemodes/wizard/spellbook.dm, code/game/objects/items/weapons/storage/boxes.dm
Wizard Magboots aren't used anywhere. Why "hardsuit" bundle shouldn't have it?
Wizard magboots!
Spawn as wizard, buy it
:cl:
add: Battlemage Bundle now contains wizard magboots!
/:cl:
=> [FEAT] Battlemage Bundle now contains wizard magboots!

code/game/objects/items/weapons/stock_parts.dm
BRPED tier4 for debugging... That's it
Faster debugging with machines
Spawn it, check insides.
:cl:
add: [DEBUG] Tier4 bluespace RPED
/:cl:
=> [FEAT] BRPED tier4 for debugging

code/modules/mob/living/simple_animal/hostile/terror_spiders/gray.dm
Gray Terror Spider now glides, not 'teleports' to its location
Junky movement is bad visuals
Spawn, walk
:cl:
fix: Gray Terror Spider moves like a normal mob. Weee, gliding time!
/:cl:
=> [FIX] Gray Terror Spider moves like a normal mob

code/game/machinery/transformer.dm
https://github.com/ss220-space/Paradise/pull/1356
MALF Factory emaggs borgs. It's show time.
It's time to go loud, and having AI to monitor if there is a new borg is redundant micromanagement
Put factory, go inside, STUN PROD
:cl:
add: MALF Factory emaggs borgs. It's show time.
/:cl:
=> [FEAT] MALF factory emaggs borgs

code/game/objects/items/weapons/storage/garment.dm
Adds a sechailer mask into blueshield's garment bag.
It's a gas mask, helps in case of toxins in the air. 
It fits blueshield's color scheme way better than the light blue breathe mask.
It also is just drippy.
Spawned in as blueshieled, opened my garment bag, mask was inside.
:cl:
add: Blueshield's garment bag now starts with a sechailer gas mask
/:cl:
=> Gives blueshield a sechailer gas mask

code/game/machinery/doors/airlock.dm
fixes returning true when door not shocked
doors should open / close when clicked on
clicked on doors with finished code fuck sorry I swear this part was tested with the bumping and shocking, not sure why it did not work on live.
:cl:
fix: Fixes doors not opening when clicked on.
/:cl:
=> Fixes doors not opening when clicked on.

code/modules/mob/living/init_signals.dm
Fixes an exploit with tails.
Exploits are generally undesirable
Tested the thing I changed, it worked properly.
:cl:
fix: Fixes a bug with tail wagging.
/:cl:
=> [s] Fixes an exploit with tails

code/__HELPERS/lists.dm
Fixes pickweight's comment to be accurate, because the proc does work
Incorrect comments are bad
Its a comment, but yes... it compiles.
=> Fixes pickweight's comment

code/modules/research/server.dm
Server blacklist now logs to game / messages admins when stuff is blacklisted
Logging this stuff is good, we do want antags and such to use it, but it is also good to know when it has been used, in case it is being used when it should not be, / to stop potential a/mhelps about certain things not being in rnd.
Blacklisted / unblacklisted stuff from rnd, confirmed it messaged admins
:cl:
tweak: Server blacklist now logs to game / messages admins when stuff is blacklisted
/:cl:
=> server blacklist now logs to game / messages admins when stuff is blacklisted

_maps/map_files/MetaStation/MetaStation.dmm, code/modules/reagents/reagent_dispenser.dm
Does exactly what the title says.
It looks bad in-game and it's a typo
:cl:
fix: Fixed a weird pixel offset on the beer nuke on metastation
spellcheck: Fixed a typo on the beer nuke
/:cl:
=> Fixes a weird pixel offset and typo on the beer nuke

code/modules/client/preference/character.dm
Adds additional check and defaults SP to human, when defaulting is needed
Missing check made it impossible to load prefs if species are not found on the save
Delete species, it defaults to human
:cl:
fix: Missing species now for sure defaults to human
/:cl:
=> [FIX] Missing species now for sure defaults to human

code/game/objects/items/theft_items.dm
Adjusts the sliver layer to be slightly above that of the supermatter. Fixes https://github.com/ParadiseSS13/Paradise/issues/21404
You shouldn't need to alt+click the supermatter tile to realize that the sliver is under it. Adjusting the layer allows for visibility and use.
Cut a sliver off, could see it above the SM. Used the right branch this time.
:cl:
fix: The Supermatter Sliver is now visible above the SM.
/:cl:
=> Adjusts the Supermatter Sliver layer

code/modules/antagonists/vampire/vampire_powers/umbrae_powers.dm
Umbraes won't go to negative blood if the fake recall takes more blood than the vampire has.
Fixes #21747 
Bugs bad
i had to wait a whole two minutes to make sure my blood didnt go negative, the lengths i go for this smh
:cl:
fix: Fixed a negative blood umbrae bug
/:cl:
=> Fixes an umbrae bug

code/modules/games/cards.dm
https://github.com/ss220-space/Paradise/pull/1284
Fixes the player eating a deck of cards
The player just wanted to take a card, not eat it!
Take a deck of card. Take it again in my hands. It works.
:cl:
fix: Fixes the player eating a deck of cards
/:cl:
=> [FIX] Fixes the player eating a deck of cards

code/game/objects/items/weapons/implants/implant.dm, code/game/objects/items/weapons/implants/implant_mindshield.dm
Headsrevs can no longer be mindshielded.
Fixes a bug
See above, normal people and other non-headrevs could still be mindshielded.
:cl:
fix: Headrevs can no longer be mindshielded.
/:cl:
=> Fixes headrevs being able to be mindshielded

code/modules/clothing/glasses/glasses.dm
Adds the research scanner ability to the sunscanners, and also updates the description to reflect that, while also fixing a typo(?)
The science goggles have them, so why don't the direct upgrade to them have it?
And adding the research scanner to the sunscanners makes them more useful than diagnosis huds for science in my opinion 
Checked if it worked, it did. Also checked if the description was correct, it was.
:cl:
tweak: Sunscanners now have the research scanner ability, like the science goggles do, as well as updated its description.
spellcheck: Fixed what was seemingly a typo in the sunscanners description, as well as a bit of grammar.
/:cl:
=> Adds the research scanner ability to the sunscanners. 

code/game/jobs/job_globals.dm
Fixes issues with job playtime for Magi/BS counting for the wrong types of playtime.
Im bad at coding, this should not change things that already exist. Whoops.
:cl:
fix: Fixes Blueshield/Magi Departmental playtime tracking.
/:cl:
=> Fixes Blueshield/Magi Job EXP Issues

code/modules/mob/living/simple_animal/bot/syndicate_bots.dm
fixes ed209 not doing what it should code wise, due to bad proc overide on ed209s
bad code bad
:cl:
fix: Fixed ed209 AI being funky in reaction to unarmed attacks
/:cl:
=> fixes ed209 not doing what it should code wise

code/game/gamemodes/cult/cult_items.dm
Fixes #21807 
Bug bad
Tested, spears didn't break on recall
:cl:
fix: Fixed cult spears shattering on recall
/:cl:
=> Fixes blood spears shattering on recall

code/modules/mob/living/carbon/alien/special/facehugger.dm
fixes #20992
fixes #20990 (they're the same issue)
jank reduction wooooo
Facehuggers shouldn't randomly stop working sometimes requiring you to wait for them to do what you want them to
skrell abuse
:cl:
tweak: Facehuggers no longer randomly stop working
/:cl:
=> facehuggers are less janky

_maps/map_files/generic/centcomm.dmm
Replaces some of the blastdoors in the thunderdome area with the indestructable variant.
Stop those pesky gladiators from trying to break your games.
Join game
Try blastdoor buttons
They work
:cl:
tweak: Replaced thunderdome blastdoors with indestructable variant
/:cl:
=> CentComm: Replaces thunderdome blastdoors with indestructable variant

code/modules/clothing/glasses/glasses.dm
Title, i forgot to include the check that you need to actually wear the glasses
oversight bad
made sure you actually had to wear the glasses to use them. and you actually do now.
:cl:
fix: Fixed a oversight with sunscanners
/:cl:
=> you need to WEAR the glasses to use them!

code/modules/clothing/suits/misc_suits.dm
Adds cover hair flag to ablative hood
Hair being showed through the hood is bad
:cl:
fix: Hair no more being showed through ablative hood
/:cl:
=> Ablative hood now covers hair

code/__DEFINES/is_helpers.dm, code/game/objects/items/devices/scanners.dm
Allows simple mobs to be scanned by health analyzers.
Ending discrimination against simple mobs.
:cl:
tweak: Simple mobs can now be scanned by health analyzers
/:cl:
=> Allows simple mobs to be scanned by health analyzers.

code/datums/components/defibrillator.dm, code/game/mecha/equipment/mecha_equipment.dm, code/game/mecha/mecha.dm, code/game/objects/items/weapons/holy_weapons.dm, code/game/objects/structures/crates_lockers/closets/cardboardbox.dm, code/modules/admin/topic.dm, code/modules/mob/dead/observer/observer_base.dm, code/modules/mob/living/carbon/human/human_life.dm, code/modules/mob/living/silicon/robot/robot_update_status.dm, code/modules/mob/mob_misc_procs.dm, code/modules/reagents/chemistry/reagents/paradise_pop.dm
converts uses of << to send_sound, removes unneeded sound() calls
backend change, improves consistency in code, generally improves code by cutting down on unneeded args as well
compiled and made sure the easiest sound to check, the alert sound from the cardboard box still played
NPFC
=> removes uses of << sound, replaces with send_sound

_build_dependencies.sh
Bumps our CI beta version from 1608 to 1610 (we skipped 1609 due to issues).
https://www.byond.com/forum/21?command=search&scope=local&text=resolved%3A515%2E1610
https://www.byond.com/docs/notes/515.html
515 "stable" is nearly here, we want to make sure any issues are stamped out before release.
=> Bump BYOND beta minor version

code/game/objects/items/toys.dm
Adds . = ..() to plushies being Destroyed
blew up some plushies, no GC weirdness
=> Fixes an issue with plushies being destroyed

code/modules/mob/living/carbon/human/human_life.dm
Fixes a bug introduced in #21774 that accidentally made all human heartbeats sound robotic
It's a little disconcerting to have your heartbeat sound robotic when you have a normal heart
None, replacing the soundfile shouldn't change anything
:cl:
fix: Non-robotic hearts now don't make a robotic sound.
/:cl:
=> Makes human heartbeats not sound robotic

code/game/objects/structures/kitchen_spike.dm
Someone hooking a mob with a mind is now logged.
Closes https://github.com/ParadiseSS13/Paradise/issues/21394
- Hooked lots of mobs, with and without mind
:cl:
tweak: [ADMIN] Hooking someone on a meat spike is now logged
/:cl:
=> Hooking someone on a meat spike is now logged

code/modules/paperwork/pen.dm
Removed the "It uses blue ink" from the description, it always used black ink.
Incorrect info is not good.
:cl:
spellcheck: Fancy pen description is no longer incorrect about the ink being used
/:cl:
=> Fixes fancy pen description

code/game/objects/items/weapons/defib.dm
title
Exploit bad
- Tried to remove the thing from it, failed.
:cl:
fix: Fixed an exploit involving the CMO defib
/:cl:
=> [s] Fixes an exploit involving the CMO defib

code/game/machinery/computer/Operating.dm
title
Fixes https://github.com/ParadiseSS13/Paradise/issues/21873
- Turn the power off and lay down on the operating table, notice no audible message from the computer.
:cl:
fix: The operating computer no longer "speaks" with no power
/:cl:
=> The operating computer no longer "speaks" with no power

code/modules/surgery/robotics.dm
Hopefully fixes a surgery runtime that pops up around here. Should be NPFC beyond fixing the runtime, I believe.
I don't know if it's causing active issues, but I've seen a related runtime pop up quite a few times and it's probably good to deal with it.
=> Attempt to fix a surgery runtime

tools/mapmerge2/dmm.py
Ports tgstation/tgstation/pull/77283
Prevents rare cases of map merge eating your map
Its a simple .py change, same PRs are being put up by multiple codebases
=> Updates mapmerge

code/modules/mob/living/simple_animal/hostile/gorilla/gorilla.dm
Adds a missing var that should have been included to prevent dead gorillas from twerking
Fixes https://github.com/ParadiseSS13/Paradise/issues/21916
teabagging gorillas belong in halo, not here.
:cl:
fix: Fixed dead gorillas being able to stand up and lie down
/:cl:
=> Gorilla death now properly blocks stance switch

code/game/objects/items/robot/robot_upgrades.dm
title
exploit bad
- Tested it by manually printing the thing and then destroying the thing without any errors
:cl:
fix: Fixed an exploit related to a cyborg upgrade
/:cl:
=> [s] Fixes a floor thing

code/datums/status_effects/neutral.dm
fixes a bug
bugs bad
touched skrells
N/A
=> [s] fixes a bug

code/modules/mob/living/simple_animal/hostile/megafauna/bubblegum.dm
So uhhh I accidentally broke one of Bubble's abilities ... oops
Thanks Qwerty for the fix and Jubs for finding it
Borked things bad
Compiled
:cl:
fix: Fixed an issue with bubblegum's charge not working correctly
/:cl:
=> Fixes an issue with Bubblegum charging

_maps/map_files/RandomRuins/SpaceRuins/moonoutpost19.dmm, _maps/map_files/RandomRuins/SpaceRuins/ussp.dmm, code/controllers/failsafe.dm, code/datums/periodic_news.dm, code/datums/spells/lichdom.dm, code/game/gamemodes/malfunction/Malf_Modules.dm, code/game/gamemodes/wizard/spellbook.dm, code/game/objects/items/control_wand.dm, code/game/objects/items/devices/traitordevices.dm, code/game/objects/items/weapons/dna_injector.dm, code/modules/events/spacevine.dm, code/modules/food_and_drinks/kitchen_machinery/gibber.dm, code/modules/mob/living/simple_animal/hostile/megafauna/drake.dm, code/modules/surgery/remove_embedded_object.dm, strings/ion_laws.json, strings/tips.txt
Fixes common spelling mistakes: "protocalls", "technicial", "criticaly", "permamently", "estinguished", "civillian", "accidently", "sucessfully", "artifical", "appearence", "interal", "immediatly", "concious", "tourrets".
Misspelling bad
- Compiled
:cl:
spellcheck: Fixed some spelling mistakes
/:cl:
=> Fixing common spelling mistakes part 4

code/game/objects/items/control_wand.dm
Halves the use time to hack a door with  the access tuner.
When was the last time you've seen someone use an access tuner? 
Currently, it's not bought a lot as an emag is usually just better, works instantly, can be used while running away, can have functions beyond a door opener and the only downside of it is that the door is bolted open for both sec and themselves. 
This PR should give the access tuner some more bang for their buck, as it is currently priced as 6 TC, same as the emag.
Walked around, could actually hack a good amount of doors in less time.
:cl:
tweak: The access tuner hack time is halved
/:cl:
=> Halves the time needed to hack a door with the access tuner

code/modules/mob/living/living.dm
Slightly refactors makeTrail() to make it more readable, and some comments to explain the math behind it.
Some quotes from a contributor and a headcoder respectively:
"God what is this unreadable abomination"
"Good example of why we use early returns"
Compiled
NPFC
=> Slightly refactors makeTrail() and adds a few comments

tools/maplint/lints/obj_item.yml
Bans the exact /obj/item typepath from maps using maplint
This is an item that is never meant to be spawned in for players.
No mapping files has banned typepath
=> Bans the exact /obj/item typepath from maps

code/datums/spells/alien_spells/plasma_weeds.dm
Uses the `\a` macro(?) so that when you plant eggs you see "planted an alien egg!" instead of "planted a alien egg!"
Grammar is a good thing to get correct
loaded in and planted weeds + eggs
:cl:
spellcheck: Fixed a typo with alien egg laying
/:cl:
=> Minor alien grammar fix

code/game/objects/effects/spiders.dm, code/modules/antagonists/changeling/powers/summon_spiders.dm, code/modules/mob/mob.dm
Fixes an issue where an infestation spider would runtime on death
Fixes an issue where a runtime would happen if a proc was called when the mob is qdel'ed already
Removes infestation spiders from the pool of what spiderlings can grow into
Fixes several stupid issues and the infestation spider isn't able to be grown into by spiderlings
:cl:
fix: Fixed some issues related to clingspiders
/:cl:
=> [s] Fixes several clingspider related runtimes and fixes spiderlings growing into infestation spiders

.github/CONTRIBUTING.md
As we prefer to use `length()` over `.len`, it shouldn't be in the guide to contributing, even if it's used to show a bad (albeit unrelated) example.
Bad info shouldn't be spread
=> Updates CONTRIBUTING.md slightly

code/game/gamemodes/wizard/raginmages.dm, code/game/gamemodes/wizard/wizard.dm
Fixes an issue where a ragingmage could be dusted for being AFK, because the SSD check would be made after the AFK check
Also cleans up some code that could easily be done in a 1 line `OR` statement
Fixes a bug and refactors some code
Compiles
:cl:
fix: Fixes a bug where a raging mage could be dusted if they were SSD
/:cl:
=> Fixes an issue with raging mages and slightly cleans up the code around it

code/modules/surgery/organs/organ_external.dm, code/modules/surgery/remove_embedded_object.dm
Fixes a bug that prevented the surgery for removing embeds on IPCs from appearing. I also made changes that should make embed messages more consistent with limb addition and removal.
Being able to remove embedded stuff from IPCs without replacing limbs is kind of a good thing, actually.
Threw a frag grenade at an IPC, and surgically removed the shrapnel.
:cl:
fix: Embedded item removal surgery should now work on IPCs.
/:cl:
=> Fixes embed surgery on IPCs not working

code/game/objects/items/toys.dm, code/modules/supply/supply_pack.dm, code/modules/supply/supply_packs/pack_miscellaneous.dm
Does what the name says: adds an orderable crate at cargo which contains 3 random plushies, for the low low price of 1000 credits!
Oh and I guess there's a 1% chance to get a ... Blahbomb? Whatever that is.
Qwerty ported some amazing sprites, and it would be nice to have another way of obtaining them that isn't grinding the arcade.
Bought a LOT of crates
:cl:
add: Adds a new orderable crate at cargo: a random plushies crate!
/:cl:
=> Adds an orderable random plushies crate for 1000 credits

code/game/machinery/camera/camera.dm, code/modules/power/generators/portable generators/port_gen.dm
fixes ais being unable to use cameras after an emp sometimes
also fixes another runtime cuz we're here already why not
cameras should never have a network of 0 or null, lots of shit breaks
Runtimes bad
Got to do stupid breakpoint things for awhile after bombing the shit out of multiple versions of the cyberiad
:cl:
fix: fixes ais being unable to use cameras after an emp sometimes
/:cl:
=> fixes ais being unable to use cameras after an emp sometimes

code/game/objects/items/weapons/dice.dm
title
The butler role is not a wizard and it should have a more appropriate polling text (probably caused by copy and paste of code).
BEFORE
AFTER
- See image above
:cl:
fix: The butler polling text for ghosts is now correct
/:cl:
=> The butler polling text for ghosts is now correct

code/game/objects/items/devices/traitordevices.dm
Fixes a mistake Silver made with the args in the choice popup
Shit's broken, I can't sugarcoat it. We like it when features work.
Ran around on fire as a plasmeme
:cl:
fix: Fixed the fireproofing injector not working
/:cl:
=> Fixes an issue with the fireproofing injector

code/modules/projectiles/projectile/bullets.dm
Makes it so the RSG can pierce everything it's supposed to, and be stopped by anything it should be
Bug bad
Tested the RSG against:
- Skrell naked
- Skrell with hardsuit
- Skrell with Dsquad hardsuit
:cl:
fix: Fixes an issue with the RSG piercing
/:cl:
=> Fixes an issue with the RSG

code/game/gamemodes/wizard/wizard.dm
Fixes an issue where a wizard dying wouldn't result in a round over
Issues bad
Killed a wizard, it died and the round ended.
:cl:
fix: Fixes an issue with wizard rounds not ending
/:cl:
=> Fixes wizard rounds not ending when the wizard dies

code/modules/mob/living/carbon/human/human_mob.dm
Fixes an issue where the RSG would runtime on hitting someone who was naked
Runtimes bad
Tested on a skrell with Dsquad armor, a normal hardsuit and a naked skrell. All received chemicals as expected, and no runtimes happened.
NPFC
=> Fixes a runtime related to the RSG

code/modules/power/engines/supermatter/supermatter.dm
This PR replaces the pyroclastic anomalies spawned by the SM when over 7000 EER with cryogenic anomalies.  
As it stands, the supermatter's risk reward ratio at high EERs is very skewed. Below 5000 EER, the engine has very view stability issues, between 5-7k the SM begins to arc and spawn gravitational and flux anomalies, often leading to the deaths of the unprepared. However, at 7k EER, once pyro anomalies begin to spawn, the risk increases extremely sharply. While the plasmafires that are generated present a challenge, they can be easily contained with some good engineering (and some luck). The issue stems from the repeatedly spawning antagonist anomaly slimes, that often proceed to kill the engineering team and/or severely damage the engine during their few brief moments of life. In my …
=> Replaces pyroclastic anomalies with cryogenic anomalies during high EER supermatter operation. 

code/modules/reagents/chemistry/reagents/medicine.dm
Improves stimulant feedback. Where they would previously silently stun you in place, they now weaken you and print out a message that should hopefully indicate that you didn't get randomly stunned.
Random, silent stuns are just awful. Any chance we have to get rid of them (see https://github.com/ParadiseSS13/Paradise/pull/18463), the better.
:cl:
tweak: Stimulants now provide a message when you get stunned by them, and they now weaken you.
/:cl:
=> Stimulants now provide clearer feedback and weaken you instead of stunning

code/datums/uplink_items/uplink_traitor.dm
Fixes a surplus uplink description.
Im a silly goose. That needs to be fixed.
I can read this time I swear.
:cl:
fix: Fixed the surplus uplink description.
/:cl:
=> Quick Surplus Description Fix

code/controllers/subsystem/SSdebugview.dm
makes debug text gc properly
I'm a fan of things working properly, lag is bad
hit F3 a bunch of times
=> makes debug text gc

code/modules/projectiles/guns/energy/special_eguns.dm
title, fixes a tiny oversight in #21313
misleading descriptions are bad
checked if laser guns rambled on about being able to self charge, they didn't.
spike thrower still has it
:cl:
fix: Fixed every energy guns description implying it had self charge
/:cl:
=> Fixes every energy guns description implying it has self charging abilities

code/game/objects/structures/girders.dm
Decrease my hope in humanity even more.
Come on people, you're better than this.
Booted up a server, checked if it didn't happen anymore.
:cl:
fix: Fixed an oversight
/:cl:
=> [s] Fixes a stupid oversight

code/modules/mob/living/carbon/carbon.dm, code/modules/mob/living/living_defines.dm
Removes an unused variable on `/mob/living`
It's quite stupid to load a var on `/mob/living` and to never remove it if it isn't used anymore.
Uhhhhhhh
NPFC
=> Removes an unused var on /mob/living

_maps/map_files/generic/centcomm.dmm
Adds in the blast doors that were missing in the thunderdome template after my thunderdome PR.
Bug bad.
Made a mess in thunderdome.
Restarted the thunderdome.
There are blastdoors now.
:cl:
fix: Adds missing Blast Doors on Thunderdome Template
/:cl:
=> Fixes Blast Doors on Thunderdome Template

code/modules/mob/living/carbon/human/human_mob.dm
Fixes a runtime if you try injecting something in a missing limb
Runtimes bad
Shit didn't runtime this time
NPFC
=> Fixes a runtime if you tried to inject something in a missing limb

.github/workflows/generate_autodoc.yml
Fixes the DMDoc generation CI step.
Sick of this shit failing to run on CI.
See CI checks.
No user-facing CL.
=> update autodocgen to ubuntu 20

code/datums/helper_datums/async_input.dm, code/modules/response_team/ert.dm
Makes ghosts that sign up for an ERT gc
Lag is bad
I dont wanna get into it, this was an absolute pain
=> makes ghosts that sign up for an ert gc

code/game/turfs/simulated/walls.dm, code/game/turfs/simulated/walls_reinforced.dm
fixes not being able to weld wall with no reagents
https://github.com/ParadiseSS13/Paradise/issues/22109
compiled, welded
:cl:
fix: You can weld walls again!
/:cl:
=> hotfix for thermite PR

code/datums/uplink_items/uplink_general.dm
Properly adjusts discount threshold to reflect TC inflation.
Corrects an oversight from the TC inflation affecting discounted items.
Made player traitor, checked traitor uplink and verified items were being discounted properly.
:cl:
fix: Fixed TC discounts.
/:cl:
=> TC Discount Fix

code/modules/clothing/under/jobs/civilian.dm
This PR fixes the name and description of the Head of Personnel's Dress Uniform as per #22135 .
fixes #22135 
Fixes the issue raised by #22135 
Joined round as Head of Personnel. Opened garment bag and verified head of personnel's dress uniform was properly named and described.
:cl:
spellcheck: Fixed a few typos
/:cl:
=> Fixes Improper Description: HoP Dress Uniform

code/__HELPERS/lists.dm, code/datums/looping_sounds/looping_sound.dm, code/game/objects/items/weapons/storage/storage_base.dm, code/modules/maptext_alerts/text_blurbs.dm
Merges LAZYDISTINCTADD and LAZYADDOR defineS
Its duplicate code
It works
=> Merges LAZYDISTINCTADD and LAZYADDOR

code/modules/reagents/chemistry/reagents_datum.dm
Scaling drug downsides will now work again. This should mean people will have to take breaks from chugging drugs, and downsides should be more meaningful.
Expect confusion of why people are dying / getting confused by drugs. We'll want to watch this now that values work, and see if any values need tweaking.
Bugs are bad. Being able to constantly be on drugs 24/7 is bad. Downsides not working is bad.
I would suggest not chugging meth constantly after this PR.
Confirmed scaling worked as intended. May be a bit harsh, will have to see!
:cl:
fix: Fixes scaling drug downsides not working. You will die if you just chug meth and manitol. This is your warning
/:cl:
=> Fixes scaling drug downsides not working.

code/modules/reagents/chemistry/reagents/drugs.dm
Slows done some interesting things that could happen
Exploits go brrrrr
I didn't go vroom vroom :(
:cl:
fix: Fixed a Vox/IPC speed issue
/:cl:
=> [s] Speed no go brrrrr

code/modules/atmospherics/machinery/portable/portable_pump.dm, code/modules/atmospherics/machinery/portable/scrubber.dm
Makes it so you can pull portable pumps, and scrubbers at full speed.
The sprite makes it look like they have wheels, and almost every other sprite that has wheels are excluded from the slowdown.
I checked if you could drag them at full speed, you could.
:cl:
tweak: You can drag portable scrubbers, and pumps at full speed again. 
/:cl:
=> Couple more forgotten pull slowdowns

.github/CONTRIBUTING.md
Updates the mapping standards section within the contributing guidelines file.
These standards have been lagging behind reality, time for a touchup.
=> Updated mapping standards

code/modules/reagents/chemistry/reagents/medicine.dm
Removes addiction chance from Ephedrine
Ephedrine's status as a sleeper chem means that bald doctors often pump their patients full of it not realizing that it causes a crippling addiction. Ephedrine's usefulness as a antistun/combat chemical is about nil due to the extremely weak (1 per cycle) stamina regen. Its properties as a stabilization chemical are much better.
If ephedrine remains in sleepers, it should have a purpose beyond an arcane knowledge check. 
Pumped myself full of ephedrine and noticed that it did not give me a horrific and crippling addiction.
:cl:
tweak: Ephedrine is no longer addictive
/:cl:
=> removes ephedrine addiction

code/modules/atmospherics/environmental/LINDA_fire.dm
This PR adds explosiong with 3 tiles light impact range to proc fireflash_sm
This proc is used to instantly melt walls and such with some really strong chemicals. The problem is some squishy scientists who uses it in a beaker or a spray. As the result, we get beaker that instantly melts r walls without any side effects.
So this change supposed to make it more dangerous if used nearby and to keep its melting effect.
Cmon, if this shit is hot enough to instantly melt the wall, it should be dangerous enough.
Compiled, melt
:cl:
tweak: Fireflash_sm proc(instant melting walls/floors) now makes explosion if it melts successfully.
/:cl:
=> fireflash_sm is now more dangerous

code/game/objects/items/stacks/medical_packs.dm, code/modules/reagents/reagent_containers/applicator.dm, code/modules/reagents/reagent_containers/hypospray.dm, code/modules/reagents/reagent_containers/patch.dm, code/modules/reagents/reagent_containers/pill.dm
This PR allows you to click patch/pill/autoinjector(or just activate it with button Z) to apply it on yourself.
What if your screen is shaking, you have little sprite and you're in the locker with 20 other people, how do you heal self? Alt click and looking for your name?
It should not be hard, so now you can just press Z with medicine in hand to apply it on yourself.
Compiled, activated various medicine
:cl:
tweak: Patches, pills, autoinjectors, trauma kits and other now can be used in hand to apply it on yourself.
/:cl:
=> Using medicine on yourself on activate

code/modules/mob/living/simple_animal/hostile/megafauna/megafauna.dm
Prevents Shuttle Crushing Megafauna.
These big lads shouldnt be phased by getting hit with a shuttle (this also fixes a slight exploit).
1. Ran my car into a buncha megafauna, they were unphased.
:cl:
tweak: prevents megafauna from being shuttlecrushed.
fix: Fixed a bug with shuttlecrushing megafauna.
/:cl:
=> Prevents Shuttle Crushing Megafauna

code/game/objects/items/weapons/manuals.dm
Replaces the outdated information in the SM users manual with information on the newly merged SM events.
Incorrect information in a reference book is bad. This information has been removed and replaced with actually useful information.
Confirm book was updated.
:cl:
tweak: Updates the Supermatter Engine Book to act as a pocket guide for SM events
/:cl:
=> Updates the Supermatter Engine Book to act as a pocket guide for SM events

code/modules/antagonists/changeling/powers/swap_form.dm
Grabs someone to ensure nothing bad happens. Also warns them.
Issues are bad.
Tested case of issue.
:cl:
fix: Fixed a swap forms issue.
/:cl:
=> [s] Fixes an issue with an ability

code/modules/reagents/chemistry/reagents/drugs.dm
This fixes a small oversight with Supercharge implant allowing it to function properly when used by an IPC.
Allows for the implant to function properly.
Spawned an IPC and gave it a Supercharge implant. Tested the affects. 
:cl:
fix: Fixed Supercharge implant
/:cl:
=> Fixes an oversight with Supercharge implant

code/datums/uplink_items/uplink_traitor.dm
Fixes an exploit, I believe I've accounted for all available base cases.
Fixes an exploit
Compiles.
NPFC
=> [s] Fixes a exploit

code/modules/food_and_drinks/drinks/drinks_base.dm
Bartender's shaker can now be shaken while moving
QOL
moved it, shaked it at the same time
:cl:
tweak: Bartender's shaker can now be shaken while moving
/:cl:
=> Bartender's shaker can now be shaken while moving

code/modules/mob/living/silicon/robot/robot_mob.dm
Fixes bad spelling of roboticist in cyborg cover lock info texts
bad spelling bad
=> Fixes a typo

code/game/machinery/merch_vendor.dm
Fixes merchandise vendor's description grammar
The grammatical issue was resolved, it fixes #22181 as instructed.
Fixes #22181
Basic Grammar PR, not much testing was required.
:cl:
spellcheck: Added a period to the merchandise vendor's description
/:cl:
=> Fixes merchandise vendor's description grammar

code/game/objects/structures/crates_lockers/closets/secure/security_lockers.dm
Every other Head gets one in their locker. This should be consistent.
Consistency is goodd.
1. There's a flash there now.
:cl:
add: Added a flash to the Captain's Locker.
/:cl:
=> Gives the Captain's Locker a Flash

code/modules/mob/living/simple_animal/hostile/hostile.dm
Hostile animals will now dodge slightly, rather than running at you in a straight predictable line.
Hostile animals will now be slightly harder to shoot at when AI controlled, and will now dodge now and then, making them slightly harder to shoot at.
https://imgur.com/a/9eMIqR8
Watched animals swiggidy swoogidy as they came for my booty
:cl:
tweak: Hostile animals will now dodge a bit, rather than running in a straight line.
/:cl:
=> Hostile animals will now dodge a bit.

code/game/gamemodes/wizard/soulstone.dm
Fixes soul stones not getting its rays in some cases.
Bugs bad.
Resolve #21771
Sharded myself in a way other than just using the soulstone on someone.
:cl:
fix: Fixed soul stones not always glowing.
/:cl:
=> Soulstone now updates rays always

code/game/machinery/portable_turret.dm, code/modules/power/engines/supermatter/supermatter.dm, code/modules/power/engines/supermatter/supermatter_event.dm
Fixes some missing investigate stuff for the SM that was previously stored in a variable on the SM
We should also probably remove the emitter shots on it, but that's not for this PR.
Also fixes a nasty other thing.
Bugs and bad logging VERY bad
See image, didn't test the nasty thing though, but it compiled and with the blessing of Contra, should work
NPFC
=> [s] Fixes some investigate admin stuff that was missing

code/controllers/configuration/sections/general_configuration.dm, code/controllers/subsystem/SSambience.dm, code/game/area/areas.dm, config/example/config.toml
Adds a new config option for disabling of ambient and white noise sounds.
Another option is just disabling the whitenoise and ambience sound on servers without a database, but I think this is preferable.
I **love** loading into the game and getting my ears instantly blasted with sounds (read: quality of life)
finally... sweet sweet silence...
Nothing player-facing.
=> Adds a new config option to disable ambience and white noise

code/datums/spell_targeting/matter_eater_targeting.dm
Stops matter eater doing some weird stuff with abstract items.
No you cannot eat things that are OOC indicators of things.
Could not eat the funny things
NPFC
=> [s] Stops matter eater from eating items that don't exist

code/modules/admin/verbs/debug.dm
Exploit bad
Exploit bad
Compiles, works like before but safer.
NPFC
=> [s] Fixes a server lag exploit

code/game/objects/items/weapons/twohanded.dm
Stops fusion gauntlets from doing bad stuff
I blame qwerty for making it do this. A lot.
It acted like it would take a normal amount of CPU for a pair of gloves.
NPFC
=> [s] Fixes a fusion gauntlet issue

code/modules/client/preference/link_processing.dm
Fixes a runtime that happens because of no sanity check
Runtimes are bad, might be best to not have so many of em sometimes
It Compiled:tm:
NPFC
=> Fixes a runtime

code/modules/mob/living/carbon/examine.dm
Cleans up some examine code slightly, and makes `Weekend_at_bernies` work on any chair, not just wheelchairs as:
1. It's already very underused
2. A lot funnier if we can do it more often (and hope that people actually notice it and read the examine text well)
Ignore the catatonic message, it is caused by me using aghost to exit the body
While keeping it to a wheelchair fits nicely with the movie, as this is an underused mechanic anyways, I don't think it would be too bad if we made any chair work for this.
See two paragraphs above
See the paragraph above
:cl:
tweak: Weekending at Bernie's now works with all chairs
/:cl:
=> Weekend at bernies now also works on any chair. Also slightly cleans up some examine code

code/modules/atmospherics/machinery/portable/portable_pump.dm, code/modules/atmospherics/machinery/portable/scrubber.dm
title.
compiling is good
compiled.
N/A
=> Ensures the codebase compiles

code/modules/mob/living/simple_animal/hostile/hostile.dm
fixes mobs with clients trying to dodge while moving in some cases
Shouldn't have your movement messed up at random
Walked in a straight line, didn't get a ticket
:cl:
fix: Mobs with clients no longer try and dodge if moving in some cases
/:cl:
=> fixes mobs with clients trying to dodge while moving

_maps/map_files/Delta/delta.dmm, _maps/map_files/MetaStation/MetaStation.dmm, _maps/map_files/cerestation/cerestation.dmm, code/modules/unit_tests/map_tests.dm
CI now bans nearspace that is not on turf/space (or other valid tiles like walls, and airless plating). Fixes the areas where this is broken as needed.
This PR also includes the fixes for it.
Area oversights are bad
See CI, first commit will fail.
NPFC
=> CI now bans nearspace that is not on turf/space

.github/CONTRIBUTING.md
Changes our standards document to actually follow the standards we use.
Newer contributors should be informed of the correct standards.
Yesn't
NPFC
=> Slightly updates contributing.md yet again

code/game/objects/items/granters/_granters.dm
Fixes a runtime with a granter not passing through a user in arguments, causing a runtime
I'd prefer it if this didn't runtime
Stopped reading my cookbook, didn't runtime
NPFC
=> Fixes a runtime with the Combat Bakery Kit

code/game/objects/items/theft_items.dm, code/modules/power/engines/supermatter/supermatter.dm
Fixes a few issues with Oblivion Enforcers, inc. a few cases where `TRAIT_SUPERMATTER_IMMUNE` isn't checked on slivers and where you could stack multiple sliver carving do_afters 
Fixing these issues makes playing Oblivion Enforcers more fun
tested each individual mechanic
:cl:
fix: Being immune to supermatter now makes you immune to supermatter slivers too
/:cl:
=> Oblivion Enforcer Hotfixes

code/modules/food_and_drinks/kitchen_machinery/gibber.dm
Fixes gibbers runtiming and not working in some cases, as the one if statement did not match the other
Fixes gibbers not working in some cases
Gibbing multiple captains
:cl:
fix: Fixes gibbers runtiming and not working in some cases
/:cl:
=> Fixes gibbers runtiming and not working in some cases

code/game/gamemodes/miniantags/guardian/guardian.dm
Makes sure that the game doesn't attempt to spawn Chaos holoparas in anymore so we can actually use the gaseous guardian
A feature was made, a bug was introduced, this PR fixes the bug
:cl:
fix: Fixed gaseous holoparasites being replaced by standard holoparasites
/:cl:
=> Actually allows Gaseous Guardians to spawn

code/modules/surgery/organs/augments_arms.dm
Vortex parry arm is now abstract, so it no longer says you are holding it in your hand when it takes up your entire arm
If your arm is turned into an item with a visable sprite, you don't need to see it on examine where it looks ugly.
Examined self after deploying implant, not in hand
:cl:
tweak: Vortex arm implant no longer shows as it is "in your hand" when deployed
/:cl:
=> Vortex parry arm is now abstract.

code/game/machinery/computer/arcade_games/recruiter.dm
"New Cannan" -> "New Canaan"
"Internal Affairs" -> "Internal Affairs Agent"
The planet name isnt new cannan.
Internal affairs AGENT is how we most commonly refer to that job, added it to avoid any confusions.
- Compiled
:cl:
spellcheck: NT Recrutier arcade: Some typos have been fixed
/:cl:
=> NT Recruiter: Fixes a typo

code/modules/shuttle/supply.dm
title
It doesnt make sense why they shouldnt receive in that one case when selling seeds and the duplication of the "credits being deposited" code leads me to think it was just a mistake.
- Sent ambrosia gaia seeds on cargo shuttle
- Verified supply and service account balance
:cl:
fix: Fixed service not receiving credits when selling seeds discoveries on cargo
/:cl:
=> Fixes service not receiving credits when selling seeds discoveries on cargo

code/game/objects/items/hand_item.dm
Being slapped now wakes you up, 1.5 times more effective than just using help intent.
Suggestion from https://www.paradisestation.org/forum/topic/24314-slapping-someone-should-wake-them-up/#comment-173944.
This is a behavior one would expect from slaps.
- Used the abductor baton to make multiple skrells sleep
- Slapped them to WAKE THEM UP!
:cl:
tweak: Being slapped now wakes you up
/:cl:
=> Being slapped now wakes you up

code/modules/clothing/suits/wiz_robe.dm
fixes battlemage armor being able to recharge
unintended
Shot wall then myself
:cl:
fix: fixes battlemage armor being able to recharge
/:cl:
=> fixes battlemage armor being able to recharge

code/modules/mod/modules/modules_supply.dm
Fixes bug
bug bad
Confirm module worked, confirm fix worked.
:cl:
fix: fixes exploit with mining modsuit
/:cl:
=> [s] fixes exploit with mining modsuit

code/game/machinery/vendors/contraband_vendors.dm, code/game/machinery/vendors/departmental_vendors.dm, code/game/machinery/vendors/generic_vendors.dm, code/game/objects/items/weapons/storage/bags.dm, code/game/objects/items/weapons/storage/belt.dm, code/game/objects/items/weapons/storage/boxes.dm, code/game/objects/items/weapons/storage/firstaid.dm, code/modules/reagents/reagent_containers/hypospray.dm, code/modules/response_team/ert_outfits.dm
There now an empty variant of the autoinjector now, with the epi becoming a subtype of autoinjectors.
The basetype should be empty as we have a decent amount of autoinjectors already
Compiled, the basetype was empty
NPFC
=> Epi autoinjectors are now a subtype of autoinjectors, the basetype is now empty

code/modules/mob/mob_misc_procs.dm
Severely nerfs stutter to be less severe by reducing the probability of it happening, and reducing the amount of repeated letters.
Stuttering can easily double the amount of characters in a sentence, making it so bad that it's being added as a disability that you can't play with as a Head of staff.
See the image
:cl:
tweak: Lowered the amount of stuttering stutter does
/:cl:
=> Severely nerfs stutter

code/modules/awaymissions/mob_spawn.dm
Fixes some oversights from #21728 where some spawners were not assigned outfits because they were given them via inheritance, which is something that was forgotten about when the PR was made.
Let's not create situations where there can be 4 naked humans on the lavaland beach.
All three spawners gave the correct job outfits again.
:cl:
fix: Fixed some lavaland spawners spawning humanoids in without clothing
/:cl:
=> Fixes some lavaland spawners not working

code/game/turfs/simulated/floor/asteroid_floors.dm
fixes the MC crashing in rare cases due to a recursion limit on tunnels
fixes #22356
Would prefer this didn't happen on prod (even if rare) as it would end the round
Compiled and ran multiple times
:cl:
fix: Tunnel generation no longer rarely crashes the MC
/:cl:
=> fixes lavaland mc crashes

strings/tips.txt
Updates a tip to reflect current TC
Outdated tips bad
It complied. For clear reasons, this was not tested past that, considering it is a tip in a text file.
:cl:
fix: Fixed an outdated tip
/:cl:
=> updates a tip

code/modules/events/anomaly_event.dm
Fixes a bug that prevents anomalies from properly spawning, and causing all sorts of trouble (like trying to delete themselves when they don't really exist).
Less bugs is good.
Started some anomaly events, they functioned as intended.
:cl:
fix: Anomalies should now spawn correctly.
/:cl:
=> Fixes anomalies not spawning right

code/modules/clothing/glasses/glasses.dm
Fixes some oversights from #20872 
The previous PR was intended to make all NV goggles available to be put prescription glasses on. This PR fixes the oversight for Sci goggles and meson goggles.
Also my god, that PR was 6 months ago. Time flies by fast.
I'll be honest, I didn't test this but it *should* be only two variables gone, that all went fine in the previous PR
:cl:
fix: Sci- and MesonNVG now can both be upgraded with prescription glasses
/:cl:
=> Makes some NV goggles also prescription upgradeable

code/game/objects/items.dm, code/game/objects/items/stacks/medical_packs.dm
This PR: 
fixes eyestab logic to check for shields, blocking and pacifism
fixes some medical items such as advanced med kits not working properly when used in hand
Bugs bad
Bypassing pacfism and shields, blocking with eyestab is bad
Compiled, tried eyestabbing and such
:cl:
fix: Eyestab no longer bypass shields, pacifism and blocking
fix: Advanced medical kits(burn, trauma) and splints now works properly on use in hand
/:cl:
=> eye stab bypassing everything fix, some med kits not working on use in hand fix

code/modules/station_goals/bluespace_tap.dm
Reduces the power needed for the BSH levels
Increases the safe level by 5, up to 15
Adds 5 extra levels of power generation to the BSH, now slightly less unreachable:tm:
The old BSH levels were designed for a TEG. Even then, the later levels (ranging from 1 to 500 GW) were already quite unreachable. This PR makes it so you can actually max out the goal faster, and have to limit yourself less.
The levels:
```	
(1 kW, 2 kW, 5 kW, 10 kW, 15 kW,
25 kW, 50 kW, 100 kW, 250 kW, 500 kW,
1 MW, 2 MW, 5 MW, 10 MW, 15 MW,
20 MW, 25 MW, 30 MW, 40 MW, 50 MW,
60 MW, 70 MW, 80 MW, 90 MW, 100 MW)
```
Spawned in a BSH, checked if it all worked correctly
:cl:
tweak: The BSH now requires less power, and has 5 extra safe levels added.
/:cl:
=> Reduces the power amount needed for the BSH. 

code/modules/mob/living/simple_animal/hostile/bees.dm
Fixes an oversight in the code making it unable to do anything with queen bees other than splitting them with bee jelly
Resolves #22442 
I disabled a feature accidentally, it shouldn't be disabled.
Could inject queen bees with chemicals and it'd actually work
:cl:
fix: Fixed Queen bees not working well with reagents that weren't bee jelly
/:cl:
=> Fixes Queen bees not being able to be mutated

code/datums/outfits/outfit.dm, code/datums/outfits/outfit_admin.dm, code/datums/outfits/outfit_debug.dm, code/game/jobs/job/job.dm, code/game/objects/items/weapons/cash.dm, code/game/objects/items/weapons/storage/backpack.dm, code/game/objects/items/weapons/storage/storage_base.dm, code/modules/clothing/glasses/hudglasses.dm, code/modules/mod/mod_types.dm, code/modules/reagents/reagent_containers/spray.dm, code/modules/surgery/tools.dm, paradise.dme
This a port from TG and a few other codebases. The debug outfit is a "small" admin-spawn only outfit, providing all the tools you could ever want to debug stuff. (well, most of it.)
This includes
- A headset with all comms (yes. all comms, even medical 1 and security 1)
- vomit prevention welding mask (wow)
- a resurrection and death wand, both recharging and with 500 charges
- advanced glasses, with all HUDs built in, and allowing you to toggle X-RAY and disabling all darkness
- A new human spawner object, for spawning "test subjects"
- An advanced RCD, with infinite matter
- 50000 credits
- An advanced surgical implant
- An advanced janitorial implant (it also has a tazer, for shits and giggles.)
- World's fastest cleaning tools, and farthest reaching.
<details>
<summary>Thats the new …
=> Adds the adminspawn debug outfit

code/datums/datumvars.dm
Restricts the visibility of some variables in the VV menu to only those with `R_ADMIN` permissions.
Avoiding potential legal trouble from personal information leaks.
:cl:
fix: [Admin] Restricted some variables in the VV menu to admin-permissions only.
/:cl:
=> Restricts the visibility of some variables in the VV menu

code/modules/admin/verbs/debug.dm
fixes viewruntimes not being able to use visualize active turfs
bug
I just forgor 
Only jimkil facing
=> fixes viewruntimes not being able to use a verb I gave them

code/game/objects/items/robot/robot_upgrades.dm
Fixes some typos and slightly rewords some flavour text for cyborg upgrade modules.
It removes some slightly annoying typos.
No testing was performed.
:cl:
tweak: Tweaked some descriptions for cyborg upgrade modules.
spellcheck: Fixed a few typos for cyborg upgrade modules.
/:cl:
=> Cyborg Upgrade Typo Fix

code/modules/surgery/organs/ears.dm
Ears no longer runtime when splashed with mitocholide
Runtimes are annoying
It didn't runtime this time
NPFC
=> Fixes a mitocholide runtime

code/_onclick/hud/guardian_hud.dm, code/game/gamemodes/miniantags/guardian/guardian.dm
Fixes a funny bug
The feature was removed a few PRs ago, this accidentally allowed it to still be a thing
Believe me, I've spent too much time testing this.
NPFC
=> [s] Last one? Last one. (Probably not)

code/datums/uplink_items/uplink_traitor.dm, code/modules/paperwork/pen.dm
Fixes #22532
Makes the pen only transfer 25u as the description says
Fixes a typo
We should be using proper English. Also, we shouldn't mislead people with false descriptions.
Compiled, checked how many times I could inject someone
:cl:
fix: Fixed skrell pens not injecting 25u instead of 50u as the description says
spellcheck: Fixed the name of the skrell love pen
/:cl:
=> Fixes the skrell love pen injection amount && name

code/_onclick/hud/action_button.dm
Fixes an action button runtime with the toggle button, it doesn't have a linked action, it's just straight overridden so there's no reason to call parent on it
runtimes bad
works on my machine
NPFC
=> fixes an action button runtime

code/modules/tgs/v3210/v3_api.dm
Replaces call\call_ext with a CALL_EXT macros that depends on the same factor(byond ver)
Actually useless change because tgs 3 is outdated. The question is why isnt it removed at all.
Coders wont see this wierd stuff when searching where byond version affects anything
Nothing player related
=> Refactor: tgs bridge call/call_ext to CALL_EXT

code/game/turfs/simulated/floor/chasm.dm
Fixes borgs not being able to build over chasms, it will now check their other modules for a screwdriver.
Fixes #22598
Struggled to find a chasm, then built over it as a borg, and as a human. Both worked.
:cl:
fix: Borgs can now build over chasms by holding a screwdriver in another module.
/:cl:
=> Fixes borgs not being able to build over chasms

code/modules/projectiles/guns/energy/energy.dm, code/modules/projectiles/guns/energy/laser.dm, code/modules/projectiles/guns/energy_guns.dm
Energy guns now accurately tell you if they can recharged or not.
fixes: #22624
Desciption shouldn't lie.
Spawn captain's gun, plasma cutter, AEG and Lgun
They accurately tell me if they can be recharged or not.
:cl:
fix: Energy guns now accurately tell you if they can recharged or not.
/:cl:
=> Energy guns now accurately tell you if they can recharged or not.

code/modules/antagonists/_common/antag_datum.dm
Fixes a to_chat runtime
Messages should be sent
This is just a logic issue and replace_banned_player would be kind of a pain to do on local
:cl:
fix: Players are once again properly alerted if they get given up due to a jobban
/:cl:
=> fixes a to_chat runtime

code/modules/clothing/spacesuits/ert_hardsuits.dm, code/modules/clothing/suits/bio.dm, code/modules/mining/lavaland/necropolis_chests.dm
Fixes some typos in certain lists
Typos are bad (if funny) and Contra will give me 30 paracoin for this
Spawned all the outfits and species, had a fashion show
NPFC
=> Fixes some typos

code/__DEFINES/misc_defines.dm, code/__DEFINES/status_effects.dm, code/datums/status_effects/buffs.dm, code/modules/library/book.dm
Every powergamer's fantasy, opening a book will decrease your brain damage by ONE!
Two exceptions.
- Mobs can only be valid for this if they've not read a book in the past 10 seconds.
- A book is only valid when it has not been read in the past 45 seconds.
This means you can carry multiple books to heal faster, but a single book wont get you that far. Just keep in mind books are NORMAL sized items, if you want to carry around 5 for MAXIMUM BRAIN HEALING, that'll take up most of your backpack.
Numbers are subject to change if balance team feels this is too powerful.
This includes player made books, and manuals. It does not include granter books, spellbooks, tomes, or the chaplain's bible.
It adds a reason for characters to go interact with the librarian and the library. While not …
=> Reading books can help decrease brain damage

code/modules/mob/living/silicon/robot/drone/drone_items.dm
Fixes silicons from being unable to pick up cells from cell chargers
Its inconsistent, why can they insert them, but can't remove em?
fixes #22526
Spawned in as a drone with a cell charger and few power cells, doing various combinations of adding cells, removing them, adding cells when cell was already inserted, dropping cells all resulted in correct behaviour.
:cl:
fix: Fixes silicons from being unable to pick up cells from cell chargers
/:cl:
=> Fixes silicons from being unable to pick up cells from cell chargers

code/modules/mob/dead/observer/observer_base.dm
Lets ghosts scan for and see n2o with their analyze air verb.
Edit:
Since slightly refactored/standardized the code chunk.
It was a oversight with #20891, and the normal hand held one can, so ghosts should be able to, to.
Checked if n2o showed up, it did, checked if agent b was still unknown, it was. 
:cl:
fix: Fixed a oversight preventing ghosts from seeing N2O with their analyze air verb.
/:cl:
=> Ghosts are now able to see N2O with the analyze air verb. 

code/datums/outfits/outfit_debug.dm
Removes some todo comments, makes syndicomms actually work for the headset. Allows you to change hide your name on syndicomms, and change your agent name. This does not affect normal syndicate encryption keys.
I forgot some stuff for the original PR
Could speak on syndi comms, using the encryption key in hand toggled the hiding of my voice behind my agent name, alt clicking allowed me to change my agent name.
NPFC
=> Fixes some minor stuff with the debug outfit

code/modules/clothing/glasses/hudglasses.dm
Fixes a runtime with hud glasses and latespawn players
runtime bad
runtime gone
NPFC
=> Fixes a runtime with hud glasses and latespawn players

code/modules/mob/new_player/new_player.dm
Moves the lobby panel to the status panel
Better access to information that is somewhat obscure, less panels are also generally nice
this should also be faster
Checked it out on the lobby screen
:cl:
tweak: Moves the lobby panel to the status panel
/:cl:
=> Moves the lobby panel to the status panel

_maps/map_files/Delta/delta.dmm
Fixes all the windoors that are missing in Deltastation's security department.
Fixes missing windoor at Deltastation's HOP's office.
Fixes: #22536
Missing windoors bad.
Restores brig windoors to state before #22168 see mapdiffbot for changes.
:cl:
Fix: Added all the windoors that were missing in Deltastation's security department.
Fix: Missing windoor at Deltastation's HOP's office has been replaced.
/:cl:
=> Fixes missing windoors in Delta security (And a few other places)

code/modules/food_and_drinks/food/foods/sandwiches.dm
Fixes an issue in code that caused admins to no longer be alerted when a hamborger is made.
This was an unintended change, and code that was simply incorrect.
:cl:
fix: Admins are now properly alerted again when a hamborger is made.
/:cl:
=> Admins are now properly alerted again when a hamborger is made.

code/modules/mob/living/carbon/human/species/_species.dm
Drask no longer slow down when very cold.
Im classifying this as fix as it probably wasn't intended, and not a tweak/balance change but of course im open to anything in comments.
This pr could include making so they dont shiver from cold in shivering.dm but oh well.
Makes sense considering they love cold and heal from cold gases around them.
WIP
:cl:
fix: Drask no longer slow down when cold
/:cl:
=> Drask no longer slow down when cold.

code/modules/atmospherics/machinery/portable/portable_atmospherics.dm
Title.
I messed up with not watching chat when testing if it messed with tanks.
Checked if canisters 'failed to connect' when they actually connected, they didn't.
Checked if this broke pumps/scrubbers, it did not.
:cl:
fix: Fixed canisters pretending that they failed to connect.
/:cl:
=> Fixes canisters constantly 'failing to connect' despite it actually connecting

code/modules/client/client_procs.dm, interface/skin.dmf
fixes some interface runtimes
Niche as hell but this stuff is long gone
I clicked the buttons and the buttons worked
NPFC
=> fixes some interface runtimes

code/game/gamemodes/cult/runes.dm
Fixes an issue where normal ghosts wouldn't have a `current`, making it so the summon cult ghost option was just useless.
Cult nerfs are good, but not when they're the result of a bug in a recent fix.
It works
:cl:
fix: Fixed the cult rune not working
/:cl:
=> Fixes cult ghosts not being able to be summoned anymore

code/controllers/subsystem/SSjobs.dm
Fixes a runtime with ERTs cryoing
runtime bad
No runtime
NPFC
=> Fixes a runtime with ERTs cryoing

code/game/gamemodes/nuclear/nuclear.dm
Fixes a small oversight from #22024 where nukies would be paid less because their starting TC wasn't updated from the base.
This is not a wardecleration change
This is a fix on the extra TC that you get as a nukie that scales with the amount of crew on the station.
It's an unintended consequence that accidentally nerfed nukies.
If CI fails because of me only chaning one var, I'm either eating my hat or buying charlie a pint
:cl:
fix: Nuclear agents should now spawn in with their intended amounts of TC again
/:cl:
=> Buffs nukies (Just kidding, fixes an oversight from the TC inflation act)

code/game/gamemodes/cult/runes.dm
fixes a to_chat runtime
we do not talk to the mind
single var change
:cl:
fix: You now properly get alerted if you get given up as a revived cultist
/:cl:
=> fixes a tochat runtime

code/game/objects/items/weapons/storage/backpack.dm
Adds an else  to nanny bag, so you get sword and - value, or a bo staff, instead of both
It was supposed to be a 50 % for one or the other, not a 50% for both or nothing
It compiled, should not need further testing
:cl:
fix: Fixed nanny bag giving you a sword, - value, and a bo staff
/:cl:
=> fixes tabbing in nanny bag

tools/mapmerge2/merge_driver.py
This PR fixes errors in the DMM merge driver that occur when the driver attempts to reuse both an existing key and existing tile data, if the key and tile data are being used in different prefabs.
The error, `bidict.KeyAndValueDuplicationError`, occurred when the key and tile data that we attempted to put into the bidict both existed in different key-value pairs. My original code didn't handle this case and in rewriting it, I realized the logic was confusing and possibly wrong, so I simplified the implementation and made it clear what was going on with comments.
Failing merge conflict resolutions are a nightmare.
Tested against #22669. Before:
```
D:\ExternalRepos\third_party\Paradise [pr/1080pCat/22669 ≡ +0 ~1 -0 !]> git merge master
Merging dmm: …
```
=> mapmerge: fix bidict.KeyAndValueDuplicationError

code/game/objects/items/weapons/grenades/flashbang.dm
Fixes people with hearing protection ending flashbangs effects.
Fixes flashpowder only effecting the closest person.
Oops. This was not noticed in testing, as my skrells were always closer to the flashbang, then the person with hearing and flash protection. My mistake, sorry.
resolve #22742
Confirmed flashbangs worked when people had hearing protection around
:cl:
fix: fixes flashbangs
/:cl:
=> fixes flashbangs

code/modules/mob/living/carbon/human/human_mob.dm, code/modules/mob/living/init_signals.dm
Fixes an exploit
Fixes an exploit
Discussed with dev team
Fixes an exploit (nobody needs to know...)
=> [s] Fixes an exploit

code/controllers/globals.dm, code/controllers/subsystem/tickets/tickets.dm, code/datums/datumvars.dm
Restricts the visibility of some more variables in the VV menu to those with `R_ADMIN` and above permissions:
- `attack_log_old` mob var
- `allTickets` list var on the ticket subsystem
- `asays` global list
- `admin_log` global list
- `logging` global list
- `jbh` client var (Job Ban Holder)
- And more (look at diffs)
Tested on an account with the VIEWRUNTIMES permission only. Variables did not show up.
:cl:
fix: [Admin] Restricted some variables in the VV menu to admin-permissions only.
/:cl:
=> Restricts the visibility of some more variables in the VV menu 

.github/CONTRIBUTING.md
adds Contrabang as reviewer in documentation
adds Contrabang as reviewer in documentation (read: its good to keep documentation up to date)
adds Contrabang as reviewer in documentation
adds Contrabang as reviewer in documentation
=> adds Contrabang as reviewer in documentation

code/modules/reagents/reagent_containers/chemical_bottle.dm
Implements https://www.paradisestation.org/forum/topic/24450-raise-max-transfer-capacity-on-bottles-from-30u-to-50u/
Quality of life for dumping out bottles
:cl:
tweak: Reagent bottles can now transfer 50u at a time.
/:cl:
=> Raises max transfer capacity on bottles from 30u to 50u

code/game/objects/items/weapons/manuals.dm, code/game/objects/structures/crates_lockers/closets/secure/engineering_lockers.dm
Minor edits of the atmospherics manual to correct typos, some odd grammar, and misinformation about atmospheric devices. Also adds information about passive vents alongside references to digital valves.
Misinformation is bad in an IC manual attempting to convey how one of the more complicated systems in the game works. Typos are also bad.
All text.
Booted it up in game, read through the manual to look for any left over issues and confirm that my changes were present.
:cl:
tweak: Corrects misinformation and typos in the atmospherics manual and adds information about passive vents.
/:cl:
=> Atmospherics Manual Improvement

code/modules/mod/modules/modules_antag.dm
Adds an attack log to a successful modsuit kick
Fixes #22456
Power kicked a tajaran
N/A
=> Add logging to modsuit kick module

code/controllers/globals.dm, code/controllers/subsystem/tickets/tickets.dm, code/datums/datumvars.dm
Fixes some runtimes caused by #22788. Uses usr instead of src
Runtimes bad
Compiles, could use verbs
NPFC
=> Fixes some runtimes caused by #22788

code/modules/mob/living/simple_animal/bot/bot.dm, code/modules/mob/living/simple_animal/bot/cleanbot.dm, code/modules/mob/living/simple_animal/bot/ed209bot.dm, code/modules/mob/living/simple_animal/bot/secbot.dm
Existing TGUI for bots (Clean, Sec, ED) now use `data["x"] = x` instead of the `"x" = x,`
Merges all non bot specific backend code to bot.dm
changes `mob/M` to `mob/user`
Tidy up bot tgui backend
NPFC
=> TGUI Bots Refactor

code/modules/mob/living/carbon/carbon_death.dm
Fixes an issue with fake death and CPR. We don't want revivability applied a second time if they actually die while faking death. This situation doesn't come up much, but we don't want it.
This is something I only realized after fixing fake death to have the revivable status effect, accidental oversight
Faked death for 5 minutes, appeared undefibbable, actually died, still appeared undefibbable.
:cl:
fix: Fixes an issue with fake death and CPR
/:cl:
=> Fixes an issue with fake death

code/modules/admin/verbs/adminpm.dm
Adds a missing whitespace to pms, so admin rank and ckey arent the same word.
:cl:
spellcheck: Added missing whitespace in pm. PM from-Adminckey -> PM from-Admin ckey)
/:cl:
=> Fix: whitespace in pm

code/__DEFINES/mob_defines.dm, code/game/gamemodes/miniantags/abduction/gland.dm, code/modules/mob/living/simple_animal/slime/slime_life.dm, code/modules/mob/living/simple_animal/slime/slime_mob.dm, code/modules/mob/living/simple_animal/slime/slime_powers.dm, code/modules/mob/living/simple_animal/slime/slime_say.dm
Removes the slime friendship & speech buffer system.
Remake of #17562
Have you ever had a round where you come into xenobio after an hour, and the scientist wants to show you a cool trick? The trick of course is to magically freeze your entire game by saying `hi`. Slime talking and the friendship mechanic is a very very costly process
```
/mob/living/simple_animal/slime/proc/handle_speech    9.27
- Data from GDN
```
It's handled poorly, and isn't quite used. 
Also bonus:
> Commanding slimes and what to do/who to attack is a pretty interesting feature, to say the least--I'd hate to lose it when we haven't even tried to optimize it yet.
This was March 2022 - Fox McCloud
I don't think someone is gonna swoop in and optimize this too
Spawned in a random slime, saw it walk around and it even …
=> Removes the slime friendship & speech buffer system

code/modules/client/client_procs.dm, code/modules/client/preference/preferences.dm
removes 2 vars we no longer need
People shouldn't be able to see these and they aren't compared anywhere
NPFC
=> [s] removes 2 vars we no longer need

code/modules/antagonists/revolutionary/team_revolution.dm
Fixes an administration issue with revolutionaries when an admin spawns one, deletes them, and somehow all the heads die. Also, the revolution can only win once. They can not win infinitely many times.
Fixes #22813
Didn't get spammed
NPFC
=> Fixes an administration issue with revolutionaries

code/modules/reagents/chemistry/reagents/medicine.dm
Lazarus reagent can no longer necrotize robotic organs when revived.
Fixes: #22763
Bug bad.
:cl:
fix: Lazarus reagent can no longer necrotize robotic organs when revived.
/:cl:
=> Lazarus reagent no longer necrotizes robotic organs

code/game/machinery/autolathe.dm, code/game/machinery/vendors/vending.dm, code/game/objects/items/ashtray.dm, code/game/objects/items/weapons/stock_parts.dm, code/modules/food_and_drinks/drinks/drinks_base.dm, code/modules/food_and_drinks/food_base.dm, code/modules/food_and_drinks/kitchen_machinery/kitchen_machine.dm, code/modules/hydroponics/beekeeping/honey_frame.dm, code/modules/hydroponics/gene_modder.dm, code/modules/hydroponics/hydroitemdefines.dm, code/modules/mining/ores_coins.dm, code/modules/paperwork/paper.dm, code/modules/paperwork/paperbin.dm, code/modules/power/cables/cable_coil.dm, code/modules/research/rdconsole.dm, code/modules/research/research.dm
Removing pixel_x/y = rand() from some things.
Now, all item
All items given out by autolat/vendors, drop with a random position. ( pixel_y = rand(-5, 5); pixel_x = rand(-5, 5) )
Most of the things will not "hang" from the table, unless the mapper does not do so, in general gives more space to mappers, because now you can beautifully arrange the items on the tables and they will not turn into a mess
Before
After
Yes.
:cl: Aylong
tweak: Removed randomization of some things at server startup, you probably won't even notice it.
tweak: Now all items given out by autolat/vendors, drop with a random position.
/:cl:
=> Tweak: Removes position randomization for some things

code/modules/antagonists/traitor/contractor/datums/syndicate_contract.dm
Being contracted with a Holopara now kills the holopara
Asked balance team, they generally approved of it. It means more people will stop getting willingly contracted.
Yeah, worked.
🆑 
tweak: Getting contracted will now kill any holoparas you have, be careful!
/🆑
=> Being contracted with a Holopara now kills the holopara

code/modules/mob/living/silicon/ai/freelook/chunk.dm
fixes a runtime with camera signals
borgs also got cameras in em, and we don't mind these overriding
NPFC
=> fixes a runtime with camera signals

code/_onclick/hud/alert.dm, code/_onclick/hud/fullscreen.dm, code/modules/mob/living/simple_animal/slime/slime_life.dm, code/modules/mob/living/simple_animal/slime/slime_mob.dm, code/modules/mob/mob_vars.dm
Moves some variables to the proper files, as they were messing up my ctr+click in VSC.
We have files specifically to keep this all orderly, instead of it being scattered across files.
It compiled - I'll go check if screens and alerts still work properly.
NPFC
=> Moves some mob and slime variables under the defines in the right file

code/modules/antagonists/traitor/contractor/datums/syndicate_contract.dm
Stealth implants are not removed, like other syndicate implants
Syndicate implants generally shouldnt be removed by contracting
Kept my implant
:cl:
fix: Stealth implants are not removed when contracted
/:cl:
=> Stealth implants kept during contracting

code/datums/uplink_items/uplink_nuclear.dm, code/game/objects/items/weapons/implants/implant_explosive.dm
Time to explode: 7 seconds -> 3 seconds
Price: 100 telecrystals -> 50 telecrystals.
When was the last time this thing was used outside of a gag. You spend WAY too much to justify it on any nukie round you're taking seriously. The timer currently is hilariously long, letting anyone near you get away from the bomb. Its also TWICE the price of the syndicate bomb (similar explosion radius) which nukies get TWO of, for free and which they can explode in about 5 seconds thanks to the Big Red Button. 
By cutting the time in half, it means the majority of people who were meleeing the nukie are actually going to get affected by it (even then, I think 3 seconds might be too long). And by cutting the price down to 50 tc (just 5 tc below the syndicate bomb), it makes it viable because while it is …
=> Buffs the macrobomb implant

code/datums/mind.dm, code/modules/mob/dead/observer/observer_login.dm
Fixes some issues with med hud updating (read: WHY CAN CURRENT BE A NEW_PLAYER)
Bugs bad
Compiles, basic logic checking
:cl:
fix: Some weird errors with updating medical huds
/:cl:
=> Fixes some issues with med hud updating

code/game/objects/items.dm
Eliminates some shenanigans
Whoops!
Loaded in, tried the funny, it was no longer funny.
:cl:
fix: Fixes some funny storage behavior
/:cl:
=> [s] Fixes a storage exploit

code/modules/surgery/surgery.dm
Fixes surgery germ rates being broken since we moved organs to nullspace (2.5 years)
Organs now get germs from bloody rooms and people without masks again.
This will get people killed a bunch I suspect.
Good.
Confirmed organs happened in surgery again from masks and blood
:cl:
fix: People get germs from blood on the grounds again, as well as people without masks
/:cl:
=> Fixes germs, kills many people in surgery

code/game/verbs/ooc.dm, code/modules/client/client_procs.dm, code/modules/client/view.dm, code/modules/input/input.dm, code/modules/tooltip/tooltip.html, goon/browserassets/js/browserOutput.js, interface/skin.dmf
Renames some things
Trust me bro
Keybinds still worked, commands that need the skin still worked
NPFC
=> Renames some things

code/game/objects/items/weapons/storage/bags.dm
Fixes something funny
Trust me on this
Couldn't do it anymore, other interactions seemed to work well.
NPFC
=> [s] Removes something

.github/workflows/ci.yml, _build_dependencies.sh, code/__byond_version_compat.dm
Makes the latest working 515 build the CI's "stable" build.
Disables the beta multibuild option from CI for now. (This can come back whenever a new 515 build is released)
We don't have anything to do with 514 anymore, no use wasting CPU time on CI for 514 anymore.
=> 514 is dead, long live 515

code/game/objects/items/weapons/implants/implant.dm
Fixes a runtime when removing an implant
NA
=> [s]Fixes a implant removal runtime

.github/CODEOWNERS
- Fixes my codeowners files post rename
- Removes fox's ownership of atmos and chem - they are now free
=> Codeowners changes

code/controllers/subsystem/SSgarbage.dm
makes the code compile if find_ref is on
Code should compile, code not compiling is very not good
Compiled the code with the reference tracking on
I hope to god this didn't affect live
=> makes the code compile if find_ref is on

code/game/gamemodes/miniantags/demons/slaughter demon/slaughter.dm, code/game/gamemodes/objective.dm, code/game/gamemodes/wizard/artefact.dm
Fixes this
Fixes bugs
Yeah, it works
:cl:
fix: Objective popups should no longer show "/list"
/:cl:
=> Fixes more /list s with objectives

code/game/machinery/computer/camera_console.dm
fixes the screen objects in camera consoles not gcing, don't want them sitting in that screen_map() list on the clients, now they get removed on close
Things should GC
Checked it in the reference finder, GCed fine although the reffinder is broken right now and doesn't properly compile
NPFC
=> fixes the screen objects in camera consoles not gcing

code/modules/projectiles/guns/magic/wand.dm
fixes non wand belt / nanny bag wands having semi randomised charges
not every wand should have max charges roundstart
confirmed it worked in game
:cl:
fix: Fixed random wand charges of non wand belt / nanny bag wands
/:cl:
=> Fixes wand capcity

code/modules/mob/living/carbon/human/species/machine.dm
Fixes IPCs not having health HUDs, which happened with the HUD split up.
This doesn't move IPCs back from diaghuds to medhuds, it just makes them visible again on diaghuds.
Fixes a bug
Tried several methods, this was the best I could come up with that worked and wasnt called every single time the HUD wanted to be updated
:cl:
fix: Diagnostic HUDs should be able to see the health of IPCs again
/:cl:
=> Fixes IPCs not having health HUDs

code/game/machinery/vendors/wardrobe_vendors.dm
Adds cyborg action figure to RoboDrobe contraband list, updates the binary phrase the vendor sometimes says from "clotheshere" to "Clothes here!"
1. The Cyborg action figure definitely belongs in the RoboDrobe along with the Roboticist action figure.
2. Just because a phrase is expressed in binary doesn't mean it can't be grammatically correct.
Hacked a RoboDrobe, dispensed a Cyborg action figure, played with it until the vendor said the modified line.
:cl:
tweak: Cyborg action figure added to RoboDrobe contraband list.
spellcheck: Slightly altered one of the RoboDrobe quotes.
/:cl:
=> Adds cyborg action figure to RoboDrobe contraband list, updates RoboDrobe quote.

code/modules/projectiles/guns/throw/crossbow.dm
fixes an infinite loop in crossbow code
this code may be stupid, also game shouldn't explode
my solution? Air strike, EMP them, EMP them, keep emping them, emp them again, and again, also no infinite loop
i gotta like make this shit log right toooooo
NPFC
=> fixes an infinite loop

code/game/jobs/job/support.dm
Mimes with department backpack/satchel in character creation get the mime backpack. Department duffel mimes get regular dufflebag due to no item existing.
Consistency with all other jobs, convenience
Ideally we should get a mime dufflebag and satchel added but this is a step in the right direction
Spawned as a mime with department backpack, satchel, dufflebag, grey backpack, everything works as expected 
:cl:
tweak: Mimes spawn with the mime backpack if department backpack or satchel is selected in character setup
/:cl:
=> Mimes get department backpack

code/_onclick/hud/radial.dm, code/modules/clothing/clothing.dm
Removing accessories is now a radial menu
Adds a new radial helper, where all the icon work is done for you, and allows for multiple inputs of the same item.
Picking text from a list is boring, new using radial menus is fun and cool!
I discovered some bugs, fixed them, broke my breakpoints, fixed my breakpoints
:cl:
tweak: Removing accessories from a jumpsuit is now a radial menu
/:cl:
=> Removing accessories from a jumpsuit is now a radial menu

code/controllers/configuration/sections/url_configuration.dm, code/controllers/subsystem/tickets/tickets.dm, config/example/config.toml
Adds an Exploit Report autoresponse for the ticket system.
`To report an exploit, please go to our <a href='[GLOB.configuration.url.exploit_url]'>Exploit Report page</a>. Then 'Start New Topic'. Then fill out the topic with as much information about the exploit that you can. If possible, add steps taken to reproduce the exploit. The Development Team will be informed automatically of the post.`
One-click directions to give to someone to report an exploit if they ahelp about it.
Sent myself a response to my own ticket.
:cl:
add: Added an exploit report auto-response.
/:cl:
=> Exploit Report Autoresponse

code/modules/reagents/chemistry/reagents/medicine.dm
fixes an omni od runtime, OD needs to return a list vs just null
Runtimes bad
/world/Error being higher than npcs is bad
Compiled and smoked the holo cigar while absolutely getting wrecked on omni
NPFC
=> fixes an omni od runtime

code/modules/mob/living/carbon/human/species/_species.dm
Fixes unspeakable horrors
We blame the cat
I wasn't cosplaying a certain lizard after shooting myself
NPFC
=> [s] Fixes an unathi nerf

code/modules/mob/living/simple_animal/hostile/megafauna/bubblegum.dm
Adds a check to bubblegum
yeah
confirmed it worked as it should.
:cl:
fix: Fixes an issue with bubblegum
/:cl:
=> [s] Fixes an issue with bubblegum

code/game/gamemodes/wizard/raginmages.dm
Magivends will now only be altered when a second wizard spawns, to not spoil any ragin mages stuff. 
Requested by an admin, if they want to run ragin mages, they should have control over it.
Gibbed myself a few times and looked at the vendor
:cl:
tweak: Magivends on raging wont be refilled until the first wizard dies
/:cl:
=> Adjusts ragin' mages magivend changes

code/modules/projectiles/guns/medbeam.dm
Medbeams now heal robotic limbs
medbeams heal borgs for god sake and this is a gamma item or nukie weapon it can heal robotic limbs please.
(this is not an I ded please nerf this is a why moment)
It worked.
Then we scoped it to human so it would pass checks
:cl:
tweak: medbeams now heal ipcs / robotic limbs
/:cl:
=> medbeams now heal ipcs since it is the future

code/modules/food_and_drinks/food/snacks.dm, code/modules/hydroponics/grown.dm
Fixes random position when slicing food
Hopefully that's the only thing I'm forgetting in [this](https://github.com/ParadiseSS13/Paradise/pull/22820) PR
Pizza slices and watermelon slices no longer in each other after slicing
Sliced pizza and watermelons. The picture above was a random 10px. In code - 7
:cl:
fix: Anything that can be sliced has a random position again after slicing.
/:cl:
=> Fix: Slices random position

code/game/objects/items/robot/robot_upgrades.dm, code/modules/research/designs/mechfabricator_designs.dm
If science gets illegals 2, robotics will be able to print an upgrade that gives janitor borgs syndie soap.
I think illegal soap is funny + It's a very useful upgrade that doesn't invalidate the other janitors too much more.
Upgraded a borg, and made sure it showed up correctly in the exofab
:cl:
add: Robotics can now upgrade janitor cyborgs with syndicate soap
/:cl:
=> Adds a syndicate soap upgrade for janitor borgs

code/__DEFINES/misc_defines.dm, config/example/config.toml
Bumps SQL version in code from #22417 
AAAAAAAAAAAAAA
=> I am big stupid - fix SQL version bump

code/game/objects/items/weapons/cards_ids.dm
Fixes the typo previously present in the appearances list of the Agent Card for "Roboticist", this typo made it so that the agent card was unable to take the appearance of a Roboticist's ID. 
Fixes #23037 
Makes it easier to blend in as a Roboticist with an Agent ID.
The server compiled with no issues and I was able to change the Agent ID's appearance to that of a Roboticist's ID.
:cl:
fix: An Agent ID can now take the appearance of a Roboticist ID.
/:cl:
=> Fixes the typo in the appearance list

code/modules/mod/modules/modules_engineering.dm
Prevents the firefighting module from dispensing metal foam if it is out of water.
Bugs are bad, the water drain for metal foam use is pointless if you can use it without water.
Spawned in, used all the water, made sure metal foam couldn't be used.
:cl:
fix: Fixes the firefighting module metal foam working without water. 
/:cl:
=> Fixes a firefighting module issue

code/modules/mob/living/simple_animal/hostile/megafauna/colossus.dm, code/modules/mob/living/simple_animal/hostile/megafauna/legion.dm
Legions big beam melts walls. Colossus bolts now break lights around impact
Better atmospherics for colossus, turns off lights as it fucks up station.
Legion beams melting walls as the beam plows through it is cool
deployed colossus and legion to station, watched.
:cl:
tweak: Legions big beam melts walls. Colossus bolts now break lights around impact.
/:cl:
=> Legions big beam melts walls. Colossus bolts now break lights around impact

_maps/map_files/generic/Lavaland.dmm
- re-adds GPS tags to mining outpost stationary GPS, as well as QM's desk GPS
- fixes some minor layering issues
- renames a couple cameras
**If any more issues/oversights show up, please report them here.**
A couple things have slipped my testing for  #22391! Oversights bad!
Spawned in, all worked.
:cl:
tweak: Mining outpost GPS has a name tag again
fix: Certain items in the lavaland outpost no longer overlay over each other
tweak: Renames a couple mining outpost cameras
/:cl:
=> Fixes some minor issues with the outpost remap.

code/modules/mob/living/simple_animal/bot/medbot.dm
Legnthens the medbot TGUI because this is annoy
ng (see below)
Its triggering
**CURRENT**
No real need, just pixel edit?
:cl:
tweak: Medbot ui is 20 pixels longer
/:cl:
=> Fix: Medbot UI, lengthens it a bit

code/__DEFINES/chat_box_defines.dm, code/game/objects/items/devices/scanners.dm, goon/browserassets/css/browserOutput-dark.css, goon/browserassets/css/browserOutput.css
Makes health analyzers significantly more readable by removing some unnecessary information and moving it to a textbox.
Also, changes the colors for oxyloss to make it significantly more readable on darkmode.
Keeping up with a health analyzer with a busy chat can be a pain. This should make it easier to more quickly find the most important information from an analyzer usage in medbay.
Punched myself a few times, drank all the cryoxadone and sugar, then analyzed myself.
:cl:
tweak: Health analyzers should now be a fair bit more readable.
/:cl:
=> Improve readability of health scanners

code/datums/uplink_items/uplink_general.dm, code/datums/uplink_items/uplink_nuclear.dm, code/datums/uplink_items/uplink_traitor.dm
This lowers some mostly unused, niche or otherwise extremely weak items (Looking at you, feral cats) prices. There are also three cases where the price was increased. Most notable of these are the nuclear medikit and the stealth biochip.
This is a continuation of #21753, but these are all the balance changes of it.
Traitor Items:
Cardboard Cutouts: 1TC `(-80%)`
Cham Voice Mod Mask: 8TC `(+60%)`
Chameleon Flag: 1TC `(-80%)`
Chameleon Stamp: 1TC `(-80%)`
DNA Scrambler: 7TC `(-30%)`
False Bottom Briefcase: 10TC `(-33%)`
Feral Cat Grenade: 10TC `(-33%)`
Singularity Beacon: 10TC `(-67%)`
Stechkin magazine: 3 TC `(-40%)`
Stechkin Special magazine: 6 TC `(-40%)`
Chameleon Thermals: 15 TC `(-50%)`
Stealth bio-chip: 45 TC `(+13%)`
Armored jacket: 3 TC `(-40%)`
Operative Items:
Flamethrower: 3TC …
=> Rebalances some more traitor item costs

code/_onclick/observer_onclick.dm, code/modules/mob/dead/observer/observer_base.dm
Adds a verb `Toggle Gas Analyzer` to ghosts that when enabled allows the user to click pipes to scan their gas contents. Provides the same information as an inhand gas analyzer.
Adds a tool for ghosts that lets them better see what's going on inside of a pipe. This lets a ghost better see what's happening in a pipenet, be it debugging someone's project, checking pipes for a ticket, or just curiosity to see what a player is up to. 
Spawned in, used ghost examine/click as normal, toggled the analyzer, checked pipes, checked turfs, tried the analyze air verb, all worked as intended.
:cl:
add: Adds the verb 'Toggle Gas Analyzer' to ghosts that allows ghosts to click pipes in order to scan the pipe's gas contents.
/:cl:
=> Expanded ghost gas analyzer

code/game/objects/mail.dm
fixes a mail runtime, mail sometimes not opening, and a human GC issue
bugfix
opened some mail
:cl:
fix: Fixes mail not opening in some cases
/:cl:
=> fixes mail not working sometimes

code/modules/mob/camera/camera_mob.dm, code/modules/mob/living/silicon/ai/freelook/eye.dm
Fixes #23084 
A non-physical representation of an Eye should not be able to be squashed like a bug
Didn't get squashed like a bug under the shuttle, instead nothing happened
:cl:
fix: Fixed AI eyes able to be shuttlecrushed
/:cl:
=> Fixes AI eyes able to be shuttlecrushed

tgui/packages/tgui/components/NanoMap.js, tgui/packages/tgui/interfaces/BotFloor.js, tgui/packages/tgui/interfaces/BotHonk.js
Just merging the prettier edits.
Standardized code
NPFC
=> Prettier TGUI

code/modules/mob/dead/dead_death.dm, code/modules/mob/dead/observer/observer_base.dm
Makes observers immune to shuttlecrush
Observers and ghosts are immaterial beings that should not be affected by the material.
They did not get crushed
=> [s] Observers are immune to shuttlecrush

.github/TICK_ORDER.md
This pull request addresses and corrects several grammatical errors found throughout the codebase.
The changes include fixing typos, punctuation, and ensuring proper sentence structure for improved readability and clarity.
No functional changes have been made; this is purely a maintenance update.
Typos are bad
None
None required
=> docs(grammatical): correct typos and improve grammar

code/game/gamemodes/wizard/spellbook.dm
Restricts bottle of ooze(morph spawner) and bottle of blood(slaughter demon spawner)
Forced extended death is bad for this kinda mode, medical being swamped with 15 bodies suddenly while needing to treat everyone else being beat up by wizards is not very neat.
checked if they were restricted on ragin, and not normal wiz
:cl:
tweak: You can no longer summon blood demons, or morphs on ragin' mages
/:cl:
=> Restricts the bottle of ooze and blood on ragin' mages. 

code/modules/reagents/chemistry/reagents/water.dm, code/modules/reagents/chemistry/recipes/pyrotechnics.dm
Toilet water is now somewhat toxic and does not spread in chemical smoke.
Toilet water smoke is, frankly, incredibly annoying. These changes should make it harder to use for griefing and, when it is used, more easy to justify a punishment (as it's quite literally harmful).
Loaded in, tried to make toilet water smoke, drank toilet water
:cl:
tweak: Toilet water does not work in smoke reactions
tweak: Toilet water is now toxic
/:cl:
=> Toilet water changes

code/_onclick/observer_onclick.dm
Adds a check to prevent the ghost gas analyzer from creating runtimes with revenants
Bugs are bad. [NO GBP Update]
Spawned in as a revenant and ghost, checked that it could be used and did not runtime.
NPFC
=> Fixes a revenant runtime

.github/CONTRIBUTING.md
Adds myself to CONTRIBUTING.md
I made review team, I should probably be included in here :)
We ball
=> Adds DGamerL to the review team

code/game/machinery/deployable.dm, code/game/objects/items/weapons/lighters.dm
Fixes a typo
Fixes #23065 
Typo bad
I didn't
:cl:
spellcheck: Fixed a typo with the broken dropwall generator description
/:cl:
=> Grammar and formatting/issue 23065/broken dropwall generator description typo

code/modules/antagonists/_common/antag_team.dm
As admins can now more easily make teams, sometimes info needs to be made known. 
When this is your message it can very easily be lost in a fight. A message box + the ticket opening sound should add to help make known that an admin just tried to message everyone.
Admin messages shouldn't be easily missable
Made myself a member of a team, messaged myself
:cl:
add: [ADMIN] Messaging a team now plays a ticket open soundeffect + chat box for the team members
/:cl:
=> Adds a chat box + bwoink sound to the Admin Message Antagonist Team button

code/modules/food_and_drinks/food/foods/misc_food.dm
There was a small oversight, allowing for the base recipe of the salad to be made by microwaving 2 cabbages. Instead of removing it as a bug, I consider this a feature. Let them eat bland salad!
https://github.com/ParadiseSS13/Paradise/assets/19627140/888b525e-8ffd-4780-ba46-fb87af097343
It removes the debug description and allows the item to be used ingame without destroying the roleplay
Just a text change, no testing. 
:cl:
tweak: Adjusted the text of the basetype salad to be able to be used
/:cl:
=> Salad Description Adjustment

code/__HELPERS/unsorted.dm
Ghosts using the analyzer will no longer create a message visible to other ghosts.
Ghosts don't need to see what other ghosts are scanning.
Joined with two clients, tested analyzing with both humans, one ghost one human, and both ghosts
:cl:
fix: Fixes analyzing pipes as a ghost showing messages to other ghosts
/:cl:
=> Fixes analyzer chat message visibility

code/modules/mob/living/autohiss.dm
Autohiss now properly capitalizes the hissing when the first letter is capitalized
Fixes: #23064
Oversight.
Set autohiss to full
Say something in allcaps
The words remain in allcaps
:cl:
fix: Autohiss now properly capitalized
/:cl:
=> Autohiss now properly capitalized

code/modules/mining/lavaland/loot/hierophant_loot.dm
Fixes hiero staff still not working in [REDACTED AREA FOR SPOILERS] (my fault)
Fixes hiero staff working with pacisism (not my fault)
Using staff here good, being able to kill people as pacifist bad
Tested in arena, tested pacifism
:cl:
fix: Fixed hierophant club not working where it should not, and with pacifism
/:cl:
=> Fixes hierophant club issues

code/controllers/master.dm, code/controllers/subsystem/non_firing/SStitlescreen.dm, code/game/turfs/simulated/walls_indestructible.dm
Adds SS loading to the title screen - shows visual indicators of whats loading, as well as clearing when all SSs are loaded
Why not
https://github.com/ParadiseSS13/Paradise/assets/25063394/8db6355b-6734-4e62-b36b-9896cca687ee
Started the server
add: Added SS loading stats to lobby screen
/:cl:
=> Adds SS loading to title screen

code/datums/radio_frequency.dm
fixes radios doubling up on frequency sometimes causing weirdness and GC issues
fixes #19325
Ain't a fan of jank or GC issues
Man find ref takes like 30 seconds on my laptop, it's so nice, something is absolutely fucked with the GC though, it is a LOT slower than it was
NPFC
=> fixes radios doubling up on frequency sometimes causing weirdness and GC issues

code/game/objects/items/devices/camera_bug.dm
Adds the camera bug camera network to restricted_camera_networks when it is initialized to prevent the AI from accessing the network.
Not particularly stealthy if the AI can jump onto the network as well.
Spawn in a camera bug kit.
Turn into the AI.
Camera bug network does not appear in the jump to network list.
:cl:
fix: AI can no longer access camera bug networks.
/:cl:
=> [s] Adds camera bug camera network to restricted_camera_networks

code/modules/clothing/chameleon.dm
Lowers the amount of research that thermals give
Per the standards from the design teams on these research levels, as the chameleon thermals got reduced in price, they should also get this reduction in obtained research levels.
It compiled.
:cl:
tweak: Chameleon thermal goggles now give slightly lower amounts of research levels
/:cl:
=> [s] Lowers thermals research

code/modules/mob/living/silicon/robot/robot_modules.dm
Service cyborgs have a multicolor pen now.
It's a tiny change that they should get.
Tested it and it works.
:cl:
tweak: Service cyborgs have a multicolor pen instead of a regular one
/:cl:
#
=> Multicolor pens for service borgs

code/_globalvars/lists/reagents_lists.dm, code/modules/reagents/chemistry/recipes/pyrotechnics.dm
Fixes some small oversights
Has only went wrong once, let's not make that twice.
Didn't do the stuff it did
NPFC
=> [s] Fixes some small oversights

code/game/objects/effects/temporary_visuals/projectile/projectile_effects.dm
Fixes the multitude of issues with overlays.
Turns out that not giving a proper image to an overlay causes issues.
Overlay work.
Turn on emitters.
Rapidly start switching hands.
I can still tell which hand is active.
:cl:
fix: Overlays get properly subtracted again.
/:cl:
=> Fixes overlay issues

code/game/objects/items/granters/action_granters/summon_cheese.dm
No more cheeseless cheese from summon cheese.
Fixes #23199 
Cheese good, no cheese bad >:( 
I read the summon cheese book and ate it, the cheese was not cheeseless.
:cl:
fix: The cheese spell book turning into cheese after being read and interacted no longer produces cheeseless cheese.
/:cl:
=> Adds cheese to the cheese

code/modules/crafting/craft.dm, code/modules/crafting/recipes.dm, code/modules/holiday/christmas.dm
Makes throwing croissants craftable, like intended.
Spellchecks a variable
While being very funny that adding a stick to a croissant makes a normal croissant again, it does invalidate half a kit that costs TC.
Also the variable was annoying me for having a typo in the name.
Compiled, made some throwing croissants
:cl:
fix: Fixed throwing croissants being uncraftable
/:cl:
=> Makes throwing croissants craftable (again)

code/game/mecha/mecha.dm, code/modules/mob/living/silicon/robot/robot_modules.dm
Mechs can now read IDs inside wallets and PDAs.
Fixes #23192 
Allows unknowns with access to get into a mech.
I tried getting into a durand without an ID and it didn't work, then I wore my wallet with my PDA inside of it and I got in.
:cl:
fix: Fixed wallets and PDAs with an ID inside of them not being able to go inside a mech.
/:cl:
=> Fixes wallets and PDAs with an ID (which has access) inside of them being unable to enter a mech

code/modules/food_and_drinks/food/customizables.dm, code/modules/food_and_drinks/food/foods/meat.dm, code/modules/food_and_drinks/food/foods/sandwiches.dm
Fixing missing sprite on:
wing fang chu & egg wrap
The chef will no longer cook the air
Nope.
SDMM
:cl:
fix: Returned "wing fang chu" and "egg wrap" sprite
/:cl:
=> Fix: Some invisible food sprites

_maps/map_files/generic/Lavaland.dmm, code/game/turfs/simulated/floor/plating.dm, code/game/turfs/turf.dm
Breaking floors in outpost or gulag now creates regular lavaland ash floors instead of lava/plasma/chasms.
It does it so by changing all of /baseturf_helper/lava_land/surface into /baseturf_helper/asteroid/basalt
Makes it way less annoying to fix in case something explodes/someone goes on an unscrewing spree.
Besides, why would NT build on unstable ground?
Spawned in, messed around with floors.
TO-DO:
:cl:
tweak: Breaking tiles in lavaland outpost or gulag no longer creates lava/plasma/chasms. Instead, it creates regular ash surface.
fix: Removed an accidental air alarm from gulag.
fix: Icons no longer break if plating is destroyed on Lavaland.
/:cl:
=> Makes lavaland outpost (and gulag) less annoying to fix.

_maps/map_files/MetaStation/MetaStation.dmm, code/game/area/ss13_areas/public_areas.dm
Fixes #22636 
every place needs an area/name
**OLD**
**NEW**
:cl:
fix: Metastation: Hallway sandwiched between bridge now has an area
/:cl:
=> Metastation Adds Hallway

code/game/objects/items/devices/scanners.dm
Makes IPC health scans shorter
Fixes #23289
They shouldn't be attempted to scan with this, it is just clutter
I added a return which was obviously missing, didn't
:cl:
fix: Fixed IPC healthscans being longer than intended
/:cl:
=> Fixes health scans of IPCs being longer than they are supposed to be

code/modules/hydroponics/growninedible.dm
Fixes acid peels. They'll now slip you for multiple tiles and chain like they used to.
Acid peels are very funny. It's good to have them back.
Slipped on some banana peels
:cl:
fix: Banana peels now chain-slip again.
/:cl:
=> Fixes acid peels

code/modules/food_and_drinks/kitchen_machinery/smartfridge.dm, code/modules/mob/living/carbon/carbon.dm
Fixes an issue where you couldn't feed people pills
Fixes an issue where you couldn't add patches to fridges
These are quite important mechanics
Ate some pills, fed a skrell some drugs
Added both patches and pills to a medical fridge
:cl:
fix: Fixed pills only being forcable to people with hats
fix: Fixed patches not being able to fit in medical fridges
/:cl:
=> Fixes some issues with patches and pills

code/modules/shuttle/supply.dm
Adds pAI cards to the cargo shuttle blacklist.
Shouldn't be able to get a pAI on CC.
:cl:
fix: Personal AI device can no longer be transported in the cargo shuttle
/:cl:
=> [s] Adds pAI to cargo shuttle blacklist

code/game/gamemodes/cult/runes.dm
Why does this compile? ghost is used later in the proc but cmoooon man.
These are supposed to work. Fixes a bad runtime.
Code compiles, and logic looks fine.
:cl:
fix: Cult ghost runes now work again
/:cl:
=> [s] Makes cult ghost runes work again

code/game/objects/structures/reflector.dm
Makes reflectors return materials when deconstructed.
It's struck me as odd that you lose the materials when you deconstruct a reflector
Unweld an existing reflectorbox , use a wrench, 1 diamond and 5 pieces of metal are returned
Build a new reflector then deconstruct it, 5 pieces of glass and 5 pieces of metal are returned
:cl:
fix: Reflectors now return materials on deconstruction
/:cl:
=> Reflectors now return materials on deconstruction

code/game/objects/items/weapons/stunbaton.dm
Removes the knockdown from baton throwing.
Baton throwing is quite strong, this should help it become more of a soul thing rather than a main form of combat.
We ball (and we throw batong)
:cl:
tweak: Thrown batons now don't knockdown anymore
/:cl:
=> Nerfs baton throwing

code/modules/projectiles/guns/energy/special_eguns.dm
Removes the self charge ability of the temp gun, as well as fixes some strangeness with the temp changing, changes a comment to be actually correct.
Also changes the emag chat message from a 'caution'(normal white text) to a 'warning'(red italic text)
The temp gun is very powerful at what it does, now add onto the fact you don't need to worry about charge? you've got rather powerful weapon on your hands.
This pr makes it so they're not self sustaining. 
Shot a bunch of skrells, and also made sure it was charging correctly, and changing temp correctly.
:cl:
tweak: The temp gun can no longer self charge.
tweak: Changes how the temp gun handles changing its temperature.
tweak: The chat message you get for emaging the temp gun looks scary, rather than just white text.
/:cl:
=> The temperature gun no longer self charges. 

code/modules/paperwork/paper.dm, code/modules/paperwork/paperplane.dm
fixes a compiling issue resulting in paper being unable to be renamed, the lower proc would always get called first leading to a no argument runtime
bugs bad
renamed a bunch of paper
:cl:
fix: Paper can once again be renamed
/:cl:
=> fixes being unable to rename paper

code/modules/atmospherics/machinery/portable/portable_pump.dm, code/modules/atmospherics/machinery/portable/scrubber.dm
Makes the portable scrubber and pump put the tank into your hand when you hit eject.
Minor QOL changes are nice.
Be an atmospherics skrell, put a tank into a portable scrubber
Hit eject, the tank is put directly into my hand instead of onto the floor
:cl:
tweak: Portable scrubber/pump now ejects into hand
/:cl:
=> Portable scrubber/pump eject into hand

code/controllers/subsystem/SSticker.dm, code/game/gamemodes/changeling/changeling.dm, code/game/gamemodes/cult/cult_mode.dm, code/game/gamemodes/game_mode.dm, code/game/gamemodes/miniantags/abduction/abduction.dm, code/game/gamemodes/nuclear/nuclear.dm, code/game/gamemodes/revolution/revolution.dm, code/game/gamemodes/traitor/traitor.dm, code/game/gamemodes/vampire/vampire_gamemode.dm, code/game/gamemodes/wizard/wizard.dm
reduces a massive amount of endround lag, fixes people crashing in some situations at the end of the round
It's reduced a 5-7 second freeze to a half a second stutter 
String operations are also pricy and we should just make lists
Made a skrell be ALL the antags and then ended the round, threw some borgs in too for the hell of it
:cl:
fix: Fixed people crashing at the end of the round in rare cases
/:cl:
=> reduces a massive amount of endround lag

code/modules/surgery/organs/organ_external.dm
fixes badly tabbed return true on limbs that makes attaching limbs to ipcs harder
bugs bad
installed limbs
:cl:
fix: fixes badly tabbed return true on limbs that makes attaching limbs to ipcs harder
/:cl:
=> fixes badly tabbed return true on limbs

code/modules/mob/living/carbon/human/species/_species.dm, code/modules/mob/living/carbon/human/species/golem.dm, code/modules/mob/living/carbon/human/species/machine.dm
fixes ipcs not dying in crit
bugfix
Killed an IPC
:cl:
fix: ipcs once again die in crit
/:cl:
=> fixes ipcs not dying in crit

code/game/objects/items/weapons/twohanded.dm
This PR adds percentage armor penetration to dualsabers 
dualsabers are currently worse than single esword against armor. This shouldnt be that. Someone forgot to add this variable to dualsaber when armour refactor PR(https://github.com/ParadiseSS13/Paradise/pull/18547) was made
compiled, cut some nerds with both dualsaber and esword
:cl:
fix: fixed deswords not having armor penetration
/:cl:
=> Make dualsaber great again

code/modules/surgery/organs/augments_internal.dm
Does ..() before like comic implant, vs return ..() with the wire implant. Don't do that, if the implantation fails they get the trait forever it turns out
runtimes / bugs bad
confirmed no runtimes on failing to install a sealed joint implant
:cl:
fix: Fixed new ipc implants runtiming
/:cl:
=> fixes IPC organs runtiming

.github/CONTRIBUTING.md
Disallows using list operators in strings in the contributing document
These meme lists are 10 or so times slower than just using an actual list. These absolutely should not be allowed
=> Disallows using list operators in strings in the contributing document

code/__HELPERS/mob_helpers.dm, code/_globalvars/lists/flavor_misc.dm, code/_globalvars/lists/misc_lists.dm, code/_globalvars/lists/objects.dm, code/game/objects/structures/lavaland/necropolis_tendril.dm, code/modules/admin/verbs/logging_view.dm, code/modules/mob/living/carbon/human/body_accessories.dm, code/modules/power/engines/singularity/field_generator.dm, code/modules/recycling/conveyor2.dm, tools/ci/check_grep2.py
Initing empty lists with GLOBAL_LIST_INIT(X, list()) is now prohibited by CI, use the GLOBAL_LIST_EMPTY helper instead.
Makes the code more readable
Code compiles, all the global lists that I changed look normal. CI seems to work.
NPFC
=> Initing empty lists with GLOBAL_LIST_INIT(X, list()) is now prohibited by CI

code/modules/reagents/chemistry/reagents/medicine.dm
Adds a proper overdose to DPH, featuring hallucinations, sleeping, and other nasty stuff.
You can finally live out your spaceman fantasies of taking 36 benadryl.
https://github.com/ParadiseSS13/Paradise/assets/89928798/9e0b2dca-f7b4-492b-a2a9-dfa9b7ecf981
Loaded in, drank a lot of benadryl, met the hat man.
:cl:
tweak: Diphenhydramine now has an overdose that causes some pretty nasty side effects, including a lot of hallucinating.
/:cl:
=> Adds an overdose to diphenhydramine

_maps/map_files/MetaStation/MetaStation.dmm, _maps/map_files/generic/Lavaland.dmm, tools/maplint/lints/different_access_helpers.yml
Changes access helpers from `all` to `any`, which caused CI to fail sometimes
This shouldn't make CI fail
Let's check the CI, code compiled
NPFC
=> Fixes the lavaland outpost causing CI to fail

code/modules/admin/misc_admin_procs.dm
stops bolding the player panel when someone enables antag hud by adding </b>
I don't want their entire player panel bolded please
before
after
compiled, ran, ahud, checked pp
:cl:
fix: Player panel no longer becomes bolded when someone enables antag hud
/:cl:
=> stops bolding the player panel when someone enables antag hud

code/game/objects/structures.dm
fixes a table climbing runtime
runtimes bad
Climbed on a table
NPFC
=> fixes a table climbing runtime

code/modules/mining/lavaland/loot/tendril_loot.dm
makes it fit in pockets / smaller
Action button is now useful, can use it from pocket to save yourself for 10 seconds before you beat up your opponent / get beat up
spawned, pocketed, used from pocket
:cl:
tweak: Immortality Talisman is now pocket sized
/:cl:
=> Immortality Talisman is now pocket sized

code/datums/uplink_items/uplink_general.dm
Fixes a misunderstanding on my part about the stechkin special ammo pricings.
- 6 for AP
- 9 for Fire
- 7 for HP
It was approved on the basis that these were the special ammo costs, I fucked up and didn't do that.
Compiled
:cl:
tweak: Tweaked the specialized stechkin ammo TC pricings
/:cl:
=> Changes specialized stech ammo prices

code/_onclick/hud/radial.dm, code/game/gamemodes/wizard/artefact.dm, code/game/mecha/mecha.dm, code/modules/mob/living/silicon/silicon_mob.dm, code/modules/surgery/organs/augments_arms.dm
fixes a few radial menus not working
fixes #23493
fixes #23487
Fixes everfull mug being able to be refilled out of range
bugfixes
Opened a whole bunch of menus
:cl:
fix: Fixed a few weird interactions with radial menus
/:cl:
=> fixes a few radial menus not working

code/_onclick/hud/radial.dm, code/datums/mutable_appearance.dm, code/game/mecha/mecha.dm
This may fix CI as well keep the fix that might be reverted in #23499 if this does not work.
Return of UI bugs is horrible
Compiled
=> Attempts to fix CI by removing filters from mutable_appearance

_maps/map_files/RandomRuins/SpaceRuins/syndie_space_base.dmm
Add missing oven for "kitchen"
Run VSC, no errors/warnings
:cl:
tweak: Add oven in syndicate base in exchange for meat spikes.
/:cl:
=> Add missing oven in syndicate research base.

code/modules/mob/living/carbon/human/species/unathi.dm
Fixes ash walker speed not updating in some situations
Yes, we actually need to recalculate it on move. The DNA record system isn't built to support interactions with source, such as the signals we were previously using
fixes #23370
bugs bad
I moved around a bunch
This took four hours to debug and I'm never getting that time back
:cl:
fix: Fixes ash walker speed not updating in some situations
/:cl:
=> Fixes ash walker speed not updating in some situations

code/game/objects/items/control_wand.dm
This PR adds windoor access to remote. 
Remote control can only open/close them, any other actions will result in fail message.
If you can control the electronic door, why can you control electronic windoor?
Compiled, tried accessing doors with wrong access, tried multiple modes, tried access tune doors and windoors, tried access depowered windoor
:cl:
tweak: Remote controls(and access tuner) can now access windoors in open/close mode.
/:cl:
=> Remote access can open/close windoors

code/datums/action.dm, code/datums/components/_component.dm, code/datums/position_point_vector.dm, code/datums/spell.dm, code/datums/spell_cooldown/spell_cooldown.dm, code/game/gamemodes/game_mode.dm, code/modules/mob/living/carbon/alien/alien_life.dm, code/modules/mob/living/carbon/carbon_life.dm, code/modules/projectiles/guns/medbeam.dm
Removes an unneeded/unimplemented proc from the breathing chain, alongside some other uncalled procs/unused variables.
We don't use it, it's 8 years old. If someone wants to implement this again, they don't need this empty proc shell anyways.
Compiled.
NPFC
=> Removes a few unused procs

code/modules/clothing/chameleon.dm
It makes the gloves you get in the chameleon kit insulated.
They come out of the kit as insulated gloves, which often causes some confusion when the wearer proceeds to get zapped by a door. This prevents that confusion, while also slightly buffing the chameleon kit.
Bought a chameleon kit. Wore gloves. Touched a shocked door. Did not smell like bacon after.
:cl:
tweak: Made chameleon gloves insulated.
/:cl:
=> Make Chameleon Gloves Insulated

code/game/turfs/simulated/floor/lava.dm, code/modules/research/designs/mining_designs.dm
Fixes lavaproof rods not working.
Adds them to rnd.
Lavaproof rods working is good.
Them being buildable as a more sensible alternative to the lava staff is good
Built with them on lava.
:cl:
add: Adds lavaproof rods to rnd
fix: Fixed lavaproof rods not working on lava
/:cl:
=> fixes lavaproof rods, adds to rnd

code/game/objects/buckling.dm
This PR adds check to nearby buckle so if target is incapacitated(cuffed, dead, stunned), it wont require 1 second do_after
QOL, fast buckling cuffed person is good, this also doesnt affect "combat buckle" which is still impossible
compiled, buckled
:cl:
tweak: Buckling incapacitated person has no delay
/:cl:
=> Bucking incapacitated is fast

code/modules/mob/living/living.dm
Fixes a runtime caused by pointing with no item in your hand caused by #23494
runtime bad
Compiles, could point with stuff
NPFC
=> Fixes a runtime with pointing

code/__HELPERS/path.dm
Upgrades our Pathfinding aka jump point search.
This PR does 2 main things
1. Diagonal movements are now properly penalized, bots will prefer to go in straight lines rather than around corners and back (which you can see as the blue line in #18984). I suspect also speeds pathfinding up because it considers the long-run cardinal lines more often.
2. We now use Pythagorean algorithm instead of get_dist(). get_dist() is quicker in the shortterm (as you can see in this test, https://discord.com/channels/145533722026967040/727448459862343711/1178177360101646406), but in the long term, using Pythagorean seems to actually takes up less CPU, and is faster. I suspect may have sometime to do with optimization of the f_value by having decimals, allowing the heap to take the actual lowest value …
=> Upgrades our Pathfinding

code/modules/surgery/organs/augments_arms.dm
Fixes vortex parry arm being invisible
I like to see my weapon, I like to see my parry, I like to see other peoples parry with this weapon
compiled, icon showed in game
:cl:
fix: Fixes vortex parry arm being invisible
/:cl:
=> fixes vortex parry arm being invisible

code/datums/uplink_items/uplink_general.dm
Fixes a small oversight in PR #23505
Just a description change, the old one was wrong, needed to be updated.
compiles
🆑
fix: Fixed an outdated description from the stechkin in the uplink
/:cl:
=> Small Oversight Fix for PR #23505

code/modules/events/event_procs.dm
blocks space from anomaly events.
anomalies should not spawn in space. Fix 23556
Compiled, now in list of blocked areas. Event ran.
:cl:
fix: blocks space from anomaly events.
/:cl:
=> blocks space from anomaly events.

code/game/gamemodes/miniantags/abduction/gland.dm, code/game/gamemodes/miniantags/morph/morph.dm, code/game/gamemodes/miniantags/morph/spells/reproduce.dm, code/modules/clothing/under/jobs/engineering_jumpsuits.dm, code/modules/mining/lavaland/loot/colossus_loot.dm, code/modules/mob/living/carbon/alien/alien_base.dm, code/modules/mob/living/carbon/alien/humanoid/empress.dm, code/modules/mob/living/carbon/alien/humanoid/queen.dm, code/modules/mob/living/living_defines.dm, code/modules/mob/living/simple_animal/friendly/crab.dm, code/modules/mob/living/simple_animal/friendly/diona_nymph.dm, code/modules/mob/living/simple_animal/friendly/farm_animals.dm, code/modules/mob/living/simple_animal/friendly/mouse.dm, code/modules/mob/living/simple_animal/friendly/spiderbot.dm, code/modules/mob/living/simple_animal/hostile/deathsquid.dm, code/modules/mob/living/simple_animal/hostile/headslug.dm, code/modules/mob/living/simple_animal/hostile/killertomato.dm, code/modules/mob/living/simple_animal/hostile/mushroom.dm, code/modules/mob/living/simple_animal/hostile/terror_spiders/empress_terror.dm, code/modules/mob/living/simple_animal/hostile/terror_spiders/prince.dm, code/modules/mob/living/simple_animal/hostile/terror_spiders/purple.dm, code/modules/mob/living/simple_animal/hostile/terror_spiders/queen_terror.dm, code/modules/mob/living/simple_animal/hostile/terror_spiders/terror_spiders.dm
Moves all of the ventcrawler var to defines
Defines are good
Compiles
NPFC
=> Code improvement for ventcrawling defines

code/modules/antagonists/changeling/datum_changeling.dm, code/modules/antagonists/survivalist/survivalist.dm
fixes a syntactical grammar issue, we shouldnt return assignments, i spotted this while looking through random code
fix good
compiles
NPFC
=> Fixes survivalist antag greeting

tgui/packages/tgui-dev-server/index.js
Pushes a quick and dirty change to the dev server on TGUIv4 that hot-reloads automatically once, always kicking the first window you open into dev/debug mode.
=> TGUIv4 - Dev server hotfix

tools/ci/check_grep2.py
Introduces a new check for CI that checks the arguments of the object constructor for `ui_interact` and verifies they are valid. This ensures that during CI testing size values are disallowed as a valid argument. Window sizing in regards to width and height have been moved to corresponding JavaScript files for each individual UI. This pertains to `ui = new()` and the arguments contained within.
This is part of the TGUIv4 upgrade project roadmap. 
Created some test cases where extra arguments were added to the object constructor. 
Checked to see if the script was able to catch these edge cases.
Checked to see if edge cases for the line search were present that would register false positives.
NPFC
=> TGUIv4 - CI check for ui_interact

_maps/map_files/RandomRuins/LavaRuins/lavaland_surface_watcher_grave.dmm
Fixes space turf on Watcher grave ruin
No bugs
Mapdiff
Trust me bro
:cl:
fix: No space turf in Watcher grave ruin
/:cl:
=> Another fix for Watcher grave, no space turf

code/modules/mining/lavaland/loot/tendril_loot.dm
removes extra a
it bugged me
I did not because it's removing an A
:cl:
fix: fixes Immortality Talisman grammar
/:cl:
=> fixes Immortality Talisman grammer

code/modules/mining/lavaland/loot/legion_loot.dm
Makes the staff of storms aggro mobs
It should do this
Attacked Bubblegum, got chased and killed
=> [s] Fixes a staff of storms issue

code/modules/mob/living/simple_animal/bot/cleanbot.dm
Fixes cleanbot not cleaning
because I forgot to init :)
Cleanbot must clean
Spawn things to clean
They clean
:cl:
fix: Cleanbot can clean again
/:cl:
=> Cleanbot hotfix

code/_globalvars/lists/reagents_lists.dm
Fixes a very rare oversight to not happen anymore
I don't know what the chance for this to happen is but it shouldn't happen
Adds 1 thing in a list, compiled
NPFC
=> [s] Fixes an oversight

code/__HELPERS/name_helpers.dm, code/controllers/subsystem/SSticker.dm, code/datums/components/codeword_hearing.dm, code/modules/antagonists/traitor/datum_traitor.dm, code/modules/mob/hear_say.dm, paradise.dme
Fixes traitor codeword highlighting for TGchat, partially implements TG's system for this. But due to their different system for languages, speaking, and hearing, I had to sorta smoosh it in paracode in a bespoke way.
Feature parity for TGUIv3 and TGUIv4
fix: Fixed TGchat traitor codeword highlighting
=> TGUIv4: TGchat fix traitor codeword highlighting

code/modules/pda/PDA.dm, code/modules/pda/pda_tgui.dm
PDA ringtone input is now trimmed, any spaces before or after will now be removed.
Makes it a lot easier to copy-paste your uplink code into your PDA, because you sometimes overshoot and include an extra space (which makes it not your uplink code).
Opened my uplink a lot easier
:cl:
tweak: PDA ringtones will now remove any extra space characters, allowing easier copypasting of uplink codes into a PDA.
/:cl:
=> PDA ringtone input is now trimmed

code/modules/food_and_drinks/food/foods/frozen.dm
Let there be cake. Clown cake can be sliced now. Whoops. Taste description properly modified.
There's a clown cake slice, it should be obtainable. Banana does not taste like cake.
I cut a cake :D
:cl:
fix: You can now slice clown cake.
fix: Clown cake now tastes correctly.
/:cl:
=> Clown cake can now be sliced.

code/game/turfs/simulated/floor/chasm.dm
demons / people no longer fall in chasms while jaunting / bloodcrawling, by adding their effects to chasm blacklist.
every day chasms expose new fun
bloodcrawled / jaunted over chasms
:cl:
fix: demons / people no longer fall in chasms while jaunting / bloodcrawling
/:cl:
=> demons / people no longer fall in chasms while jaunting / bloodcrawling

code/modules/atmospherics/machinery/airalarm.dm, tools/ci/check_grep2.py
Fixes an oversight with grep checking for conditional spaces. Also rewrote the regex and comments a little to be more accurate.
Better CI
Compiles
NPFC
=> Fixes an oversight with grep checking for conditional spaces

code/modules/mob/living/carbon/human/species/machine.dm
Removing feature which were removing IPC hair after death
IPC dont need to visit barber after every death
Tested, werks
:cl:
del: Removed the feature which was making IPC bald after death
/:cl:
=> IPC will no longer lose his hair after death

code/game/gamemodes/miniantags/abduction/abductee_objectives.dm
Adds more Abductee Objectives from multiple servers varying from fulp, tg, monkey and more.
Higher variety in abductee objectives would lead to entertaining RP and less of 3 people getting the same exact objective of leaving station by coincidence.
Opened test server got glands until the objective rolled
:cl:
add: Ported buddy, final death, forbidden number, mispronouncing, one person, blindness,, illness, game reality, instructor, writer, actor, imminent doom and proof abductee objectives from monkey, fulp, tg and skyrat (god forgive me).
/:cl:
=> Ports Abductee Objectives

code/modules/reagents/chemistry/reagents/drinks_reagents.dm, code/modules/reagents/chemistry/reagents/food_reagents.dm
Fixes https://github.com/ParadiseSS13/Paradise/issues/23735
Small little error on my part, just readds ..() back to the coco code.
Errors bad
yeppers, even made a cup irl 
:cl:
fix: Chocolate now metabolizes properly
/:cl:
=> Fixes an oversight in which drinking too much hot chocolate gives you diabetes and fatally kills you due to sugar overdose

code/datums/diseases/transformation.dm
Stops transformation viruses from throwing you out of the game if you transform
Code should work and keep you playing without issues
Ate xenomicrobes, became hunter
:cl:
fix: Fixed transformation viruses stopping you from playing the game
/:cl:
=> Fixes transformation viruses yeeting you out of the game

code/modules/martial_arts/bearserk.dm
Fixes bearserker not being removed when unequipped
This is not the buff bearserker should've gotten
Tried doing combos with and without the bearserker pelt, both worked as intended after removing the pelt
:cl:
fix: Bearserker now properly removes once you unequip the pelt
/:cl:
=> [s[ Fixes bearserker

code/game/objects/items/devices/radio/beacon.dm
blackbox logs syndicate bundle picks
so we can see how often each type is picked
Followed correct blackbox logging format, compiled
:cl:
add: blackbox logs syndicate bundle picks
/:cl:
=> blackbox logs syndicate bundle picks

code/modules/mob/living/carbon/human/species/grey.dm, code/modules/mob/living/carbon/human/species/human_species.dm, code/modules/mob/living/carbon/human/species/kidan.dm, code/modules/mob/living/carbon/human/species/skrell.dm, code/modules/mob/living/carbon/human/species/slimepeople.dm, code/modules/mob/living/carbon/human/species/tajaran.dm, code/modules/mob/living/carbon/human/species/unathi.dm, code/modules/mob/living/carbon/human/species/vulpkanin.dm
Corrects the grammar and typos for Species Blurbs, which you can see right on the Setup Character screen.
No one likes typos. Especially for Lore. 
Opened up the game. Looked at the species blurbs for each species. Looked correct. Bada boom, bada bing. 🤷
:cl:
spellcheck: Fixes grammar and typos with Species Blurbs
/:cl:
=> Corrects grammar and typos for Species Blurbs

code/modules/projectiles/guns/energy/pulse.dm
Blocks the pulse pistol from being charged again, an undocumented change from 
https://github.com/ParadiseSS13/Paradise/pull/18118
It's nice to give out this pistol as a limited weapon to ERT at times, that has a limited number of shots for more balanced use, and can't be charged by a charger.
Having it being able to be charged kinda defeats the point, and was undocumented (probably unintentional)
confirmed pistol could not be charged
:cl:
tweak: Blocks the pulse pistol from being charged again
/:cl:
=> Blocks the pulse pistol from being charged again

code/modules/projectiles/guns/syringe_gun.dm
Lethal injection syringes no longer fit into syringe guns
Warcrimes must come in small packages 15 unit packages, not 50. This also cuts down on some peoples habits of instantly rushing it on wizard rounds to shoot the wizard, come on, let people have fun.
spawned gun and syringe, attempted to load it into syringe gun, failed
:cl:
tweak: Lethal injection syringes no longer fit into syringe guns
/:cl:
=> Lethal injection syringes no longer fit into syringe guns

code/modules/awaymissions/mission_code/ruins/oldstation.dm
changes non-existing icon in code to existing icon
non existing icons is not good
compiled, spawned the ID
:cl:
fix: APC access ID now has icon
/:cl:
=> APC access ID must have an icon

code/modules/reagents/chemistry/reagents/toxins.dm
Cleans up the code around facid/sacid/aceacid
Does some very minor balance changes/tweaks:
- Slightly increases sulphuric acid damage if you get splashed with more than 25 units
The code could use a cleanup, this makes it a lot more readable.
I splashed a skrell with a LOT of acid
NPFC
=> Refactors some reagent sacid/facid code

code/modules/martial_arts/krav_maga.dm, code/modules/martial_arts/muscle_implant.dm
Stomping on someone with krav makes the kick sound / visual vs the punch one
Muscle implant users no longer have kick as an attack verb.
Bugs are bad, stomps should do the proper effect. Arm implants shouldn't get super strong kicks when the implant is in their arms
Kicked skrell, worked. Stomped on skrell, worked. Punched skrell, did punch.
:cl:
fix: Stomping on someone with krav plays the correct sound / visual now.
fix: Muscle arm implant users no longer use the kick verb, since their arms are strong
/:cl:
=> fixes an 8 year old krav sound / visual bug

code/game/mecha/mecha.dm
Refactors the mech's sprite update code, unifying the code to fit any change to the starting sprite, allowing you to freely add any future skin on a mech without fear of sprite update bugs or errors.
Refactor is good. Also let paintkits on rupara working without ussues and bugs, or here if find any good in future.
change completely nothing, but let code more variable for future.
all tested in rupara with local paintkits. 2 paintkits here also work completely smooth
=> REFACTOR: Mecha icon_state

code/modules/client/client_procs.dm
Just increases default minute topic limit from 100 to 200
I'm sure a lot of people have had situations when in a normal game, you get a warning that you've done too many actions in a minute, without using macros, most often it is noticeable when playing for the AI.
The limit was set 3 years ago, and during this time a lot of things have changed, including the players themselves who could easily learn to click faster plus hotkeys, thanks to which it became possible to cross this threshold many times more easily
The new threshold should save regular players from being annoyingly ignored just because they are faster.
No need, just a number
:cl:
tweak: Message "Your previous action was ignored because you've done too many in a minute." should now not pop up for normal players
/:cl:
=>  Increase default minute topic limit to 150

code/game/machinery/vendors/departmental_vendors.dm
Adds suckers/lollipops to the hacked inventory of the NanoMed Plus vendors you can find in the medbay.
It's a classic. A child at a doctor's office is given a lollipop for behaving well, and for shutting them up after they get their shots.
By contrast, the mental image of a doctor offering an adult a consolation lollipop after stuffing their bloody guts back into them is hilarious. I think it fits right in with SS13's tone.
Of course, you can just get suckers from the chef if you want to use this gimmick. I understand if this PR is seen as unnecessarily taking away need of interaction with the chef, but this PR was such little effort, I thought I may as well put it up for discussion.
Spawned myself in, hacked a vendor, took the sucker out, ate it.
:cl:
add: Adds suckers/lollipops to …
=> Add suckers/lollipops to hacked NanoMed Plus inventory

code/game/machinery/vendors/departmental_vendors.dm
Makes it the right typepath
Code should compile
Compiled
NPFC
=> Fixes a stealth conflict with lollypops

code/game/objects/items/weapons/whetstone.dm
Increases force after check of it being a transforming weapon, rather than before.
removes force check, force_on should always be increased when force_off is increased
Sharpening the cleaving saw should work like before
sharpened the saw
worked as intended.
:cl:
fix: fix eswords / cleaving saws not being sharpenable
/:cl:
=> fix eswords / cleaving saws not being sharpenable

code/modules/food_and_drinks/food_base.dm
Makes un-antable food actually have reagents again
Food not having reagents fucks it up majorly
Could eat junkfood again
:cl:
fix: Fixed some food being uneatable
/:cl:
=> Fixes some food being broken

code/modules/food_and_drinks/food_base.dm, tools/UpdatePaths/Scripts/23063_patch_pill.txt, tools/UpdatePaths/Scripts/23379_food_containers.txt
Fixes food being normal sized instead of tiny
Fixes the updatepaths to not brick a map
- Food being normal size is a regression, as shown in #23879
- Resolves #23879 
- Updatepaths shouldn't brick your map / confuse the local maintainer
Could put donk back inside the box
:cl:
fix: Fixed food being too big
/:cl:
=> Fixes a food size issue

_build_dependencies.sh
Bumps our CI to BYOND 515.1628, lets make sure we're keeping up with these changes.
=> Bump BYOND ver for CI deps to 1628

_build_dependencies.sh
Bumps us to 1630
Ci should work
=> bumps ci to 1630

tgui/bin/tgui, tgui/bin/tgui_.ps1
Removes the enhanced diff reporting at CI output for TGUI build mismatches, we enabled this when we had issues with SVG files and I forgot to remove it after.
None, it's a CI log output removal
NPFC
=> Remove additional TGUIv4 debug logs at CI

code/modules/antagonists/changeling/powers/fleshmend.dm
Increases Fleshmend's DNA cost from 4 to 5.
The balance man speaks and I obey.
*Really though, we inflated cling ability costs like traitor TC so we could add more variance to costs specifically like this. Fleshmend will still be worth the extra cost, it'll just be less of a no-brainer always take ability. I hope.*
The unfortunate downside is we only have one other 1 cost ability, Apex Predator, but as abilities get revisited or tweaked this issue should alleviate.
Even though it's just a numbers change, I checked it works in-game.
:cl:
tweak: Fleshmend now costs 5 DNA points, up from 4.
/:cl:
=> Increases Fleshmend cost by one point

code/game/objects/items/devices/lightreplacer.dm
Light replacers will now also work when you click on an object on the tile, meaning you don't have to pixelhunt for the turf.
It can be very frustrating that clicking on the light fixture will not work, as it currently doesn't accept any other input than turfs.
Resolves #23540
Could replace the broken light by clicking on the lighter that I dropped on the turf
:cl:
tweak: Light replacers now work on anything on a tile, instead of only working when clicking a tile
/:cl:
=> Small QOL improvement for (bluespace) light replacers

code/datums/spells/mimic.dm, code/modules/hydroponics/hydroponics_tray.dm, code/modules/hydroponics/seeds.dm, code/modules/paperwork/silicon_photography.dm
Fixes some to_chat runtimes
Messages should be sent if they exist, and shouldn't if they don't exist
Triggered both chats in game
NPFC
=> Fixes some to_chat runtimes

code/game/objects/effects/effect_system/effects_water.dm, code/modules/reagents/reagent_containers/spray.dm
This PR makes extinguisher extinguish you once again, same with spray bottles
fixes https://github.com/ParadiseSS13/Paradise/issues/23884
Bugs bad
Compiled, extinguished
:cl:
fix: Extinguisher and spray bottle once again acts on tile you're staying.
/:cl:
=> Extinguisher and spray bottle works on tile you're standing fix 

code/game/gamemodes/cult/blood_magic.dm
Brings back ability to recharge cult suit with blood rites
Undocumented change from https://github.com/ParadiseSS13/Paradise/pull/23154 is a bug, i guess, bugs bad
Compiled, tested recharging suit
:cl:
fix: Shielded cult suit can be recharged again
/:cl:
=> Recharge cult suit again

code/game/gamemodes/wizard/soulstone.dm
fix dull dull dull dull dull dull dull dull dull dull dull dull dull shard
dull
compiled, used shard on construct shell
:cl:
fix: soul shard is not anymore dull dull dull dull dull
/:cl:
=> Soul shard dull name fix

code/modules/reagents/chemistry/machinery/reagentgrinder.dm
Makes the reagent grinder shake instead of just shifting a few pixels and then doing nothing
Look at it goooooo
https://github.com/ParadiseSS13/Paradise/assets/108773801/b68324ba-5f91-4b75-80a3-47d7d0063189
See above
:cl:
tweak: The reagent grinder now shakes when it is grinding things
/:cl:
=> Makes the reagent grinder shake

code/modules/food_and_drinks/kitchen_machinery/gibber.dm
fixes #3331
8 year old bugfix
I posted a GIF of it working in codingchat, it's too big for git sadly
:cl:
fix: The gibber's gibs no longer disappear when gibbing someone
fix: the gibber's gibbing animation is now properly tied to the gibber
/:cl:
=> Fixes the gibber animation not being glued to the actual gibber, fixes the gibber losing it's blood while gibbing someone

code/modules/admin/misc_admin_procs.dm
Removes the datum `/datum/player_info`
Code cleanup is good
It compiled
NPFC
=> Removes variables on a datum that is never used or declared

code/game/objects/empulse.dm, code/modules/projectiles/projectile/special_projectiles.dm
Weak ions now consistently do the light emp_act, vs being a coin flip into heavy or light emp.
Heavy emps should be tied to the ion rifle, rather than the HOS gun coin flipping to be full strength.
This weakens ion scatter shot again. It probably should have a few more pellets added to it in the future. so it stays useful.
fired weak ion a bunch to confirm it no longer coin flips
:cl:
tweak: weak ions no longer coin flip into heavy emps, and are now consistently light emps.
/:cl:
=> weak ions no longer coin flip into heavy emps

code/game/objects/items/weapons/AI_modules.dm
Lowers a tech value from deconstructing an item
Level 3 should be harder to reach
just a simple numbers game
:cl:
fix: Pranksimov law boards can no longer get you to illegals 3
/:cl:
=> [s] tweaks a value

code/modules/food_and_drinks/drinks/drinks_base.dm, code/modules/mob/living/carbon/carbon.dm
Fixes chugging issues,
Slightly refactors drink() so that it can override amount to drink (similar to eat() proc),
_Fixes something nobody used even once in a week_
It's good because chugging is the only way honourable gentlemen escape reality
So I basically launched it and it worked
:cl:
fix: make chugging possible again
/:cl:
=> fix: chugging

code/game/machinery/machinery.dm
Extract preprocessing of machinery hand attack.
This will make it easier for coders to modify machinery interaction limitations without duplicate code.
Works fine.
=> Refactor machinery hand attack

code/__HELPERS/mob_helpers.dm, code/controllers/subsystem/processing/processing.dm, code/datums/components/orbiter.dm, code/datums/datum.dm, code/game/atoms.dm, code/game/atoms_movable.dm, code/game/jobs/access.dm, code/game/objects/objs.dm, code/modules/admin/verbs/freeze.dm, code/modules/atmospherics/environmental/LINDA_turf_tile.dm, code/modules/client/client_defines.dm, code/modules/detective_work/detective_work.dm, code/modules/mob/living/carbon/alien/humanoid/humanoid.dm, code/modules/mob/living/carbon/alien/larva/larva.dm, code/modules/mob/living/carbon/carbon.dm, code/modules/mob/living/carbon/carbon_defines.dm, code/modules/mob/living/carbon/human/human_defines.dm, code/modules/mob/living/carbon/human/human_mob.dm, code/modules/mob/living/carbon/human/human_organs.dm, code/modules/mob/living/simple_animal/simple_animal.dm, code/modules/tgui/external.dm, code/modules/tgui/tgui_panel/audio.dm, code/modules/tgui/tgui_panel/telemetry.dm, code/modules/tgui/tgui_panel/tgui_panel_external.dm
This PR removes most toplevel vardecls and adds comments on lines that are exceptions to the rule.
Code navigation will be improved.
Ran CI.
NPFC.
=> remove most top-level vardecls

code/modules/food_and_drinks/kitchen_machinery/gibber.dm
fixes #24006 
Forgot to remove the ``as anything``
Bugs bad
Gibbed a skrell by a clientless mob
:cl:
fix: Fixes the gibber rarely not working
/:cl:
=> Fixes the gibber rarely not working

code/modules/antagonists/vampire/vampire_powers/hemomancer_powers.dm
Adds a missing "d" to "ensnared"
go go grammer team
it's a string grammar change
:cl:
spellcheck: ensnare -> ensnared
/:cl:
=> Fixes grammar with vampire ability

code/modules/reagents/chemistry/reagents/paradise_pop.dm
Removes quite literally the letters "S" from Blackeye Brew's ";S WHATS SPACE LAW?!"
Im in shambles from being clowned on for thinking this was more S-spam and its something the Heads have told us to smack people for.
~~It prevents stupid admins from smacking people for saying stupid things.~~
Code should not make you do stuff that gets GAs mad at you.
Ate Soup.
:cl:
tweak: Tweaked a blackeye brew quote.
/:cl:
=> Removes Something LRP From Code (Literally 1984)

code/game/machinery/computer/card.dm
fixes a card console runtime. Forgot to remove this string
Runtimes bad
Used the console in game
NPFC
=> fixes a card console runtime

code/modules/mod/modules/_modules.dm, code/modules/projectiles/guns/energy/special_eguns.dm
fixes vortex shotgun being dropable
vortex shotgun should not be dropable
Tried to put vortex shotgun on table, couldn't, still able to retract it
:cl:
fix: vortex shotgun from modsuit module is not dropable.
/:cl:
=> modsuit nodrop fix

code/_onclick/hud/alert.dm, code/controllers/subsystem/SSghost_spawns.dm
fixes the signed up icon not getting updated when a new poll is polled
Fixes #19390
Things should work as intended
Compiled and ran. Triggered the morph event a bunch and watched it work
:cl:
fix: the signed up icon is updated when an additional role is added to that poll
/:cl:
=> fixes the signed up icon not getting updated when a new poll is polled
