ParadiseSS13/Paradise

code/modules/vehicle/janicart.dm
Reopening https://github.com/ParadiseSS13/Paradise/pull/20382 since it now got one approval.
Pimpin' ride floor buffer now can be toggled on/off and the movement speed is decreased while active.
Pimpin' ride floor buffer no longer works if theres no one driving it.
1. Pimpin' rides are supposed to be made of dead janitor cyborgs, it makes sense for their floor buffers to work the same way.
2. Being able to toggle your buffer is useful is there is something on the way you dont want to clean by accident.
3. The current cleaning speed of the pimpin' ride (with floor buffer + vtec) is too much if you compare it after the recent tweaks made to janitors/janiborgs.
Pulling an entire vehicle to bypass his speed limitations so you can use his buffer at faster speed doesnt look to be intended. …
=> Pimpin' ride floor buffer now can be toggled on/off v2

code/game/machinery/OpTable.dm
Allows you to properly buckle folks to operating tables, notably locking them in if they're handcuffed as you'd expect with a chair.
(also updates some messages while I'm here).
This is behavior that you'd really expect to be the default, but currently isn't. At least in my own experience, I've run up against this a *ton*, with prisoners or research subjects crawling off even if they're handcuffed. This should make operating tables a bit more secure and workable.
Buckled a monke to an optable, waited a bit.
:cl:
fix: You can now actually buckle people to operating tables.
/:cl:
=> [serious] Fixes buckling to operating tables

code/modules/power/singularity/singularity.dm, code/modules/power/supermatter/supermatter.dm, code/modules/power/tesla/energy_ball.dm
Adds a interaction, and message if you try to use tele on a singulo, as well as updates the tesla interaction a little.
~~Singulo message: As you mentally focus on the endless void you feel your very consciousness and soul sucked into the void. That was a infinitely dense idea.~~
New message: As you mentally focus on the singularity, you feel your knowlage of the universe grow. So much raw information is there for the taking, and you won't waste a speck of it. Within fractions of a millisecond you absorb as much information as possible, more than even an AI would have access to, you feel like a god. Suddenly, the gravity of this situation dawns on you. As you feel your skull begining to collapse, you think to yourself. That was a really dense idea, wasn't it?
Teslo message: As you …
=> Adds a funny little message if you focus too hard on a singulo/teslo

code/modules/events/event_container.dm
Adds false alarm event (triggers the announcement of a random event) back into rotation (MODERATE, weight = 200).
Now that the event has been fixed it can be put back into the events pool.
- Forced the event.
:cl:
add: False alarm event has been added to the events pool
/:cl:
Please suggest good weight number and tier for it :)
=> Adds false alarm event to the events pool

code/modules/power/singularity/narsie.dm, code/modules/power/singularity/singularity.dm
Pings ghosts when the singularity reaches stage four, at which point it's very likely not going to return to containment.
Inspired by /tg/.
Gives ghosts who aren't paying as much attention something to follow, and in the off-chance we do see a singulo, it's always fun to have a bit more flavor.
:cl:
add: New ghost alert appears when a singularity reaches stage 4.
/:cl:
=> Adds ghost notification when the singularity is (likely) loose.

code/game/gamemodes/cult/runes.dm
fixes #20832 
fixes #20806
Fixes a logic error that would cause people revived from a cult revive rune always getting their body given up
Bugs are bad
:cl:
fix: You will no longer be given up to ghosts while in a valid revivable state by a revive rune
/:cl:
=> Fixes cult revive runes always giving up a persons body

code/modules/arcade/arcade_base.dm, code/modules/economy/economy_machinery/economy_machinery.dm
Fixes #20408 
Arcade machines now show the proper amount of space cash when cash is inserted.
Players should not panic thinking they sacrificed their life savings to THE CLAAAAWWWW.
Insert cash into claw machine. VV edit claw machine to change token cost. Confirm cash inserted value is changed. 
:cl:
Fix: When inserting cash to arcade machines, the amount inserted is now properly shown.
/:cl:
=> Corrects cash input text for arcade machines

code/modules/reagents/chemistry/reagents/medicine.dm
Buffs Potassium Iodide, no longer has a 20% chance to not heal radiation, heals 25 radiation rather than 10 radiation. 
Potassium Iodide is rather awful in it's current state. The majority of people who come in with radiation to medbay will have a minimum of 2k+ radiation, which takes around 7 to 9 minutes to just fix the radiation with Potassium Iodide. Even though this is much quicker to produce in bulk then penetic, it's never used just due to the slow speed of it. This should let it actually do something instead of being a joke chemical you give someone while you scream at chem for Pentetic.
Watched the rads go down
:cl:
tweak: Potassium Iodide no longer has a 20% chance not to heal radiation. Heals 25 radiation per cycle from 10
/:cl:
=> buffs Potassium Iodide

code/modules/client/preference/character.dm, code/modules/mob/living/silicon/ai/ai_mob.dm
Adds some crash reports to character loading, because currently loading characters who can runtime
```
[2023-04-09T05:06:00] Runtime in character.dm,479: Cannot read null.has_gender
[2023-04-09T05:06:00]   proc name: load (/datum/character_save/proc/load)
[2023-04-09T05:06:00]   src: /datum/character_save (/datum/character_save)
[2023-04-09T05:06:00]   call stack:
[2023-04-09T05:06:00]   /datum/character_save (/datum/character_save): load
[2023-04-09T05:06:00]   /datum/client_login_processor/... (/datum/client_login_processor/load_characters): process_result
[2023-04-09T05:06:00]   *ADMIN* (/client): New
```
Unfortunately, the admins never know either what characters are runtiming because theres basically no data here. This adds some more that will hopefully help diagnose the problem. …
=> Adds some crash reports to character loading

code/modules/world_topic/status.dm
Adds performance metrics to the `world/Topic?status` export so we can get metrics outside of the game easier. These are queried via the world/Topic API and will allow me to put the info into `/status` on ALICE.
Formatted:
Allows me to put perf metrics into ALICE.
See above
See above
NPFC
=> Adds TD info to world/Topic?status

code/game/gamemodes/cult/blood_magic.dm
Reduces the range of the Conceal Rune cult spell.
Conceal is now a 4 tile range sound, down from 17.
Reveal is now a 7 tile range sound, down from 17.
(These numbers are spitballs, leaning more toward stealth. Im willing to change these.)
As per most of my sound PRs, you should not be able to echolocate a rune from nine years away. Conceal is less a range than reveal because HIDING should be stealthier than REVEALING.
1. Made a buncha blood runes.
:cl:
tweak: Tweaked sound range of Conceal Runes cult spell.
/:cl:
=> Reduce Sound Range of Conceal Rune Cult Spell

code/modules/mob/language.dm, code/modules/mob/mob_say_base.dm
Adds a following link for psionic communication, visible to ghosts.
This feels like something that should have been added, I have to wonder why it wasn't (beyond possibly an oversight).
:cl:
tweak: Grey psionic communication now has a follow link
/:cl:
=> Add follow link to grey psionic communication

code/game/objects/items/weapons/soap.dm
Fixes #20661
This is a bug, you should be able to clean stuff regardless of your target
Cleaned some stuff
:cl:
fix: Soap will still clean objects while targeting the mouth 
/:cl:
=> fixes being unable to clean stuff with soap while targeting the mouth

code/modules/supply/supply_console.dm
Significantly reduces the character limit on order reasons.
Prevents crates from having extremely long names or order reasons going off the TGUI menu
Ran test server
Put in 1000 character reason and it was properly clamped.
:cl:
fix: Order TGUI will no longer overflow off screen
/:cl:
=> Fixes Cargo Order Console reasons overflowing off screen

code/modules/atmospherics/machinery/portable/canister.dm
This PR corrects an oversight made with commit 8c24a36 where removing tank from a canister, it would not automatically close the canister, instead of flooding the room with plasma, or draining the oxygen canister. But the examine text was never updated to reflect these changes. As well as the changes brought on by #11377, as well as cutting down on the repetitive language
Examine text should show correct information as well as being easy to read, describing the mechanics of today, and not how they worked 9 years ago, changes since then, such as the ability to alt-click and hot-swap tanks.
Before:
After:
I made the changes, ran the server, found a plasma canister to examine, examined the plasma canister and took a screenshot of the updated text.
:cl: PPI
fix: Corrects the examine text of …
=> Corrects the examine text of portable canisters to be correct to current mechanics

code/game/machinery/vendors/vending.dm, code/modules/events/brand_intelligence.dm, code/modules/mob/living/simple_animal/hostile/mimic.dm
Adds a new degree of danger to the relatively lowkey brand intelligence event.
As the event currently works, machines will gradually become infected by an "origin machine", and if the origin machine isn't dealt with in time, they will eventually all become mimics. It isn't really that dangerous, just a bit annoying.
*Now, however, the vendors are a bit more...angry.*
Whenever a machine becomes infected, it will still shoot items out at you, but will *also* be watching the spaces around it for any new ~~victims~~customers. If you walk too close, it'll topple over onto you with a significant chance for a crit.
If you decide not to deal with the issue and wait until all machines are infected, they'll become mimics as before, with one notable change: The vendor mimics can now *tilt over onto …
=> Makes the Brand Intelligence event a bit more dangerous

code/modules/mob/living/carbon/human/human_damage.dm, code/modules/reagents/chemistry/reagents/medicine.dm
Cleans up code around `adjustCloneLoss()` and adds a missing human `setCloneLoss()` proc override, fixing a couple bugs along the way.
Reaching a cloneloss of 0 through either proc will now unmutate all external organs, and `setCloneLoss()` now respects species cloneloss damage mod.
Less bugs and more sane code good
1. Spawned in a Kidan and a decloner
2. Shot the poor sod several times
3. Swapped into the Kidan, confirmed it has multiple mutated limbs
4. Healed all the cellular damage away via Rezadone (`setCloneLoss(0)`) and VV-adjusting cloneloss to negative of current value
5. Confirmed that all limbs have been unmutated
6. Repeated several times for good measure
​
7. VV'd some toxin damage into the Kidan to confirm species damage mods still work
:cl:
fix: Lowering cellular damage to …
=> Slightly refactors `adjustCloneLoss()` and `setCloneLoss()`

code/game/machinery/teleporter.dm
Teleporters portal sections (be it the normal teleporter, or the permanent teleporter), now use crossed over bumped. This means thrown items no longer clang when you hit them, and will keep momentum going through the teleporter, similar to a portal. This also means that projectiles shot into a teleporter that is active acts like a portal, and will travel through them.
Teleporters are no longer dense.
Stuff banging on a teleporter / losing momentum through teleporters is bad.
Teleporters and portals acting more similar is good.
Being able to make funny deathtraps with teleporters and emitters is good.
Ensured teleporters still work.
Ensured they worked as expected.
Ensured teleporters no longer being dense was fine.
:cl:
tweak: Teleporters are no longer dense.
tweak: Teleporters are more …
=> Teleporters now use crossed over bump

code/datums/components/surgery_initiator.dm
Fixes a bug with early finishing surgeries (with a cautery or crowbar/screwdriver) where failing the surgery step would put you into a weird step. Now, as you'd expect, failing the step lets you try again immediately afterwards.
Better consistency across surgeries is always a net positive.
Loaded in, threw a vulp onto a table, tried to fail surgeries, noted that I was able to retry the closing step after failing it.
:cl:
fix: Failing to interrupt a surgery should let you try again afterwards.
/:cl:
=> Fixes a bug with early-finishing surgeries

code/game/objects/items/weapons/tanks/watertank.dm
Increases the water cap of the atmos firefighting backpack from 200 to 500, to be more in line with the janitor cleaning backpack
Currently, nobody uses the backpack for anything other than metal foam, as the water capacity is simply too little for any effective firefighting, or nanofrost usage.
Went into testing, had 500 water at roundstart.
:cl:
tweak: Increased atmos firefighting backpack capacity
/:cl:
=> Slightly buffs the atmos firefighting backpack

code/game/gamemodes/nuclear/nuclearbomb.dm
Fixes #20889
fixes a minor graphical glitch
took out the nuke core, re-instered it with no hit animation, then reassembled the nuke and blew up the station.
:cl:
fix: Fixed nuke core insert animation error
/:cl:
=> Fixes attack animation when inserting nuke core

code/game/objects/items/devices/flash.dm
Do note, that this returns the functionality back to flashes going off when EMP'd, even if theyre on cooldown, as that is how the logic *should* have worked without the runtime I believe. Currently, they do not go off if theyre on cooldown.
Fixes this runtime
```
[2023-04-22T13:15:15] Runtime in browserOutput.dm,299: DEBUG: to_chat called with invalid message/target. Message: '<span class='warning'>Your flash is still too hot to use again!</span>'. Target: ''.
[2023-04-22T13:15:15]   proc name: to chat (/proc/to_chat)
[2023-04-22T13:15:15]   usr: *REDACTED USER*
[2023-04-22T13:15:15]   usr.loc: The floor (75,57,2) (/turf/simulated/floor/plasteel)
[2023-04-22T13:15:15]   src: null
[2023-04-22T13:15:15]   call stack:
[2023-04-22T13:15:15]   to chat(null, "<span class=\'warning\'>Your f...", …
```
=> Fixes an emp flash runtime

code/game/machinery/vendors/vending.dm
Tweaks the changes recently introduced in #20904.
Makes the Brand Intelligence event a little less of a massacre by tweaking the random vending machine tilts.
- Aggressive vendors now only have a 25% chance to tilt over if someone walks by them.
- Aggressive vendors will only very rarely inflict crits. Mimics, on the other hand, still will, but they should be a bit easier to deal with (hopefully).
- You can now tell on examine if a vendor is aggressive or not, as they'll get a little extra flavor text.
- Aggressive vendors will have a much higher chance to speak, trying to draw you in closer to purchase so they can ruin your day.
The revamped brand intelligence was up for one round.
Loaded in, ran through a whole event, seemed to work.
:cl:
tweak: Better tunes brand intelligence to make …
=> Tones down Brand Intelligence a bit

code/modules/paperwork/pen.dm
increases e-dagger throw speed to 4 from 3 to allow embeds
Fixes #20078
By increasing the throw speed of the e-dagger it now embeds when thrown at someone.
As mentioned in the above issue the e-dagger already had an embed chance of 100 but because its throw speed was too slow  it could not actually embed.
It seems to have been the intent from the beginning that the e-dagger embeds, so this makes that reality. 
Threw e-dagger at things, embeds.
:cl:
fix: Fixed e-dagger ability to embed
/:cl:
=> Allows e-dagger to embed when thrown

code/game/gamemodes/nuclear/nuclearbomb.dm
Improves the nuclear disk GCing, parent should always be called when properly Qdeleting something. It's got emissives and stuff 
Lag is bad, little less lag is nice. Things not calling parent on destroy is not good.
=> makes the nuclear disk GC better

code/game/objects/items/stacks/medical_packs.dm, code/game/objects/items/stacks/stack.dm
Fixes #18173.
Prevents the upgrading of gauze and ointment into advanced trauma and burn kits through abuse of parent/child status in code. 
Adds the parent_stack flag to obj/item/stack allowing items flagged TRUE to be handled separately when stacks are merged.
Allows for parent items to not be merged with daughter items when picked up.
Try to pick up advanced kits with gauze, and then gauze with advanced trauma kits
Repeat with ointment and burn kits.
:cl:
Fix: Prevents stacking gauze/ointment into advanced kits
/:cl:
=> Medical stacks

code/game/gamemodes/trifecta/trifecta.dm
Trifecta now pays for the guaranteed vampire traitor and changeling it had, before it did not pay for it, leading to 25 players worth of extra antags.
Now requires 25 players (not that that will ever really matter)
25 extra antags in a gamemode is not great:tm:
Just number configuration, compiled.
:cl:
fix: Trifecta no longer has an extra 25 players worth of antags
/:cl:
=> trifecta no longer has an extra 25 players worth of antags

code/game/area/ss13_areas.dm
Fixes Cryogenic being misspelled as cyrogenic
Spelling issues are bad
:cl:
spellcheck: Corrects Cyrogenic to Cryogenic on area names
/:cl:
=> cryogenic area spelling fix

code/datums/spells/alien_spells/basetype_alien_spell.dm
Fixes xenos getting negative plasma, I forgot to set a limit on the negative stuff
Bugs are bad, and min/max is better than > checks
Did hunter things
:cl:
fix: Aliens have a negative plasma cap again
/:cl:
=> fixes negative plasma on xenos

code/modules/mob/mob_say_base.dm
Removes an `#undef` that I accidentally left in after moving stuff around during #17544. The define isn't even in the same file anymore, so this undef is kind of spurious. I noticed this while working on another PR, but wanted to keep the changes atomic.
Non-player-facing.
This isn't currently causing problems, but it seems like something that could cause some really sneaky bugs down the line.
It still compiles, I think this is a pretty safe PR.
=> Removes an accidental undef

_maps/map_files/cyberiad/cyberiad.dmm
Removes roundstart proximity mine janitorial signs and replaces them with normal signs.
Roundstart S class is bad. Janitors accidently blowing up medbay is also bad. 
Join as janitor, confirm map properly loaded, confirm signs no longer explode you.
:cl:
tweak: Medical secondary storage wet floor signs are no longer the explosive varient.
/:cl:
=> Removes roundstart janitoral mines

code/modules/mob/living/simple_animal/bot/secbot.dm
Fixes #20943
By adding a check to see if a sec bot is on when cuffing this PR prevents sec bots from cuffing if turned off while doing so.
prevents matttheficus from being ded
It seems to make more sense that a bot shouldnt be able to complete an action after being turned off.
1. Made unknown humans, 
2. set beepsky on them, 
3. turned beepsky off while cuffing,
4.  human was not cuffed
:cl:
fix: Fixed sec bots being able to cuff when turned off
/:cl:
=> Prevents sec bots from cuffing when turned off

code/modules/reagents/chemistry/machinery/chem_heater.dm
fixes: #20274
Fixed the chem heater sprite not properly displaying the beaker when the maintenance panel is opened then closed
fixes a minor graphical glitch with the heater
unscrewed and re-screwed chem heater without a beaker
unscrewed and re-screwed chem heater with a beaker
:cl:
fix: fixed chem heater sprite update
/:cl:
=> Chem heater now shows beakers when screwed closed

code/modules/mob/living/simple_animal/hostile/giant_spider.dm
Replaces a bunch of spawn() with do_after_once
Moves verbs to action buttons
Usability good, cleaner code good
Being able to use action buttons rather than verbs will more easily let players know they can actually use those said abilities. 
:cl:
tweak: Giant spider verbs now use action buttons
/:cl:
=> cleans up some giant spider code, moves verbs to action buttons

_maps/map_files/RandomRuins/SpaceRuins/syndie_space_base.dmm
gah
Replaces the regular reinforced windows at the Syndicate spacebase with plastitanium ones, also replaces the viro ones with spawners
Consistency good, syndicate aesthetic good
Untested - this is a very simple map change and will HOPEFULLY not blow up in my face
:cl:
tweak: The Syndicate has found room in the budget to give their space-based research outposts proper windows.
/:cl:
=> Gives the Syndicate Space Base plastitanium windows

code/modules/mining/equipment/survival_pod.dm
Fixes this runtime
```[2023-04-24T23:34:49] Runtime in ,: bad arg name 'time'
[2023-04-24T23:34:49]   proc name: default unfasten wrench (/obj/machinery/smartfridge/survival_pod/default_unfasten_wrench)
[2023-04-24T23:34:49]   usr: *REDACTED USER*
[2023-04-24T23:34:49]   usr.loc: The pod floor (52,221,6) (/turf/simulated/floor/pod)
[2023-04-24T23:34:49]   src: the survival pod storage (/obj/machinery/smartfridge/survival_pod)
[2023-04-24T23:34:49]   src.loc: the pod floor (52,222,6) (/turf/simulated/floor/pod)
[2023-04-24T23:34:49]   call stack:
[2023-04-24T23:34:49]   the survival pod storage (/obj/machinery/smartfridge/survival_pod): default_unfasten_wrench
[2023-04-24T23:34:49]   the survival pod storage (/obj/machinery/smartfridge/survival_pod): wrench_act
[2023-04-24T23:34:49]   the …
```
=> Fixes a survival pod runtime

code/game/objects/items/weapons/melee/melee_misc.dm
Spellblade with the lightning enchantment grants the user immunity to shocks. A: Makes sense, but more importantly B: Keeps the user from being stuned from the shock when they stab the person they are dragging with spellblade.
Spellblade actually zaps people with the name of "lightning", so it no longer says someone was shocked by the !
Spellblade stunning / knockdowning  the user with the lightning enchantment is silly. Making the person immune to shocks fixes the issue, and makes sense like the fire spellblade.
Bugs are bad.
fixes #16986
fixes #18330
Electrified fish with lightning.
Compiled and ran code, attacked dragged skrell with lightning spellblade. Worked as expected.
:cl:
tweak: Lightning spellblade grants the user shock immunity.
fix: Spellblade user no longer gets shocked from …
=> gives spellblade with lightning grant the user shock immunity

code/modules/projectiles/ammunition/energy_lens.dm, code/modules/projectiles/guns/energy/special_eguns.dm
With the blessings of Qwertytoforty, the BSG has now been buffed as to make it less of a meme weapon for something that needs an anomaly core. Reduces firerate by 6 seconds, making it the same as normal energy weapons, and removes the random chance for a bluespace crystal to be destroyed.
The BSG was never used, and is not on par with other items that require anomaly cores. This makes it so the anomaly core is a choice between the reactive armor and a BSG.
Yes
:cl:
tweak: BSG firerate is now 4 seconds, random chance to crack bluespace crystals is gone
/:cl:
=> Rebalancing the BSG

code/game/machinery/firealarm.dm
Fixes #20919
Turns off the fire alarm sound if it becomes unpowered
At least one person might be happy to stop hearing fire alarm sounds in the unlikely event the fire alarm is pulled and then an admin deletes the APC
1. pulled fire alarm
2. turned off power
3. alarm sounds stopped
:cl:
fix: Fire alarm sounds no longer continue without power
/:cl:
=> turns off fire alarm sounds when power is off

code/modules/mob/living/carbon/human/human_organs.dm, code/modules/surgery/organs/organ_external.dm
Modifies `has_organic_damage()` proc (used by the autoejection mechanic) to exclude `perma_injury` on limbs.
Also fixes a minor oversight where burn wounds did not call a health update (doesn't change much on live since only time burn wounds are inflicted is on damage taken, which eventually calls a health update later).
Cryocells shouldn't keep patients stuck inside for no good reason.
- Spawned in a lighter
- Toggled it off/on enough to cause some serious damage, checking for an eventual burn wound as well
- Hopped into a cryocell, waited a while
- Rejoiced when the cryocell spat me out when all the burn damage was healed
:cl:
fix: Cryo cells no longer eternally imprison occupants with burn wounds.
/:cl:
=> Fix cryo cells not autoejecting patients with burn wounds

code/game/objects/structures/crates_lockers/crates.dm
Plastic crates no longer drop metal, drop 4 plastic instead
Didn't know the station crew figured out alchemy, these are plastic crates, not metal crates! Just a bit weird right now.
Shot a plastic crate
:cl:
tweak: Plastic crates no longer drop metal, drop 4 plastic instead
/:cl:
=> plastic crates no longer drop metal

code/modules/reagents/chemistry/reagents/misc_reagents.dm
fixes #19583
Fixes jestosterone removing clown waddling when it leaves the system. Also added in some extra safegaurds due to some runtimes when clown drinks it, causing attempted overrides to the waddling.
station needs to properly HONK!
drank jest as a clown, had a fun time and still clowned after
drank jest as a normal crew
drank jest as a mime and had a horrible time
:cl:
fix: Fixed jestosterone removing clown waddles
/:cl:
=> Fixed Jestosterone removing clown waddles

code/modules/surgery/organs/blood.dm
Fixes #20298
Ensures that when slimes vomit blood, either via holy water or viruses, that the blood splatter is properly made and colored correctly.
Bugfixing
gave holy water to a slime vampire to vomit jelly blood
gave slime a virus to vomit blood
cut self with a meat cleaver to bleed jelly blood
added alien organ to splatter jelly blood over the walls
:cl:
fix: Fixed slimes properly vomiting blood
/:cl:
=> Slime Jelly Vomit Fix

code/game/objects/structures/crates_lockers/closets.dm
fixes #20982
mobs that don't really exist shouldn't fit in lockers, weird jank things are bad for the game
:cl:
fix: Camera mobs(AI and blob overminds) no longer fit in lockers
/:cl:
=> Prevents /camera/ mobs from being put in lockers

code/modules/events/bureaucratic_error.dm
Bureaucractic error event now logs properly instead of runtiming
runtime bad, go away.
- Forced event to happen, did see image above
:cl:
fix: Bureaucractic error event now logs properly
/:cl:
=> Fixes bureaucratic error event runtime

code/modules/reagents/chemistry/reagents_holder.dm
Changes the minimum reagent amount threshold from 0.1 to 0.09 to account for computers not being great at storing decimal values, and converts the magic number into a define.
Fixes 0.1u pills being unreliable (sometimes you'd get the ChemMaster yelling at you that there wasn't enough reagents, and sometimes it'd just straight up print empty pills), fixes some chemicals' metabolism rates/specific injection amounts of chemicals not always giving them an extra cycle when they should.
1. Put 1u of Water in a beaker
2. Made 10 pills out of it in a ChemMaster
3. Rejoiced when the machine did not yell at me, all 10 pills were properly created, and all of them when shoved back into the beaker combined into the full 1u
1. Put 2u of Chlorine and 18u of Iodine (chemical that does nothing) into an IV …
=> Fix 0.1u reagent amounts behaving inconsistently

code/game/mecha/working/ripley.dm
Fixes ripleys having a capped movespeed while using thrusters
Not supposed to happen and the returns are diminishing anyways, they can go a little faster if they want to. 
God I fucking hate mechcode
became speed via a ripley, watched my power cell drain in a minute
:cl:
fix: Speed cap removed on ripleys with exosuit ion thrusters
/:cl:
=> fixes ripleys having their movespeed capped while using thrusters

code/game/gamemodes/scoreboard.dm
Fixes #20641
This PR takes a persons account balance into consideration when determining the richest escapee at the end of the round. Before the richest escapee was determined purely based on the cash carried on their person.
Accurate end of the round statistic is accurate
1. spawn as captain
2. spawn in 1000 credits
3. put 500 into ATM account and 500 into bag
4. account balance = 1100
5. end round
6. richest escapee has 1600 credits
:cl:
fix: Fixed the richest escapee check to be accurate
/:cl:
=> calculates richest escapee by including account balance along with cash

code/modules/mob/living/carbon/human/human_damage.dm, code/modules/mob/living/carbon/human/human_death.dm
Fixes #20584 
Adds a check to make sure Machine people aren't husked. Was unlikely but weirdly possible before.
bugs bad?
1. Spawn dozens of IPCs in lava
2. No IPCs get the husk trait
:cl:
fix: Prevents Machine people from being husked
/:cl:
=> Prevents IPC husking

code/modules/atmospherics/machinery/components/unary_devices/cryo.dm
Reworks how the bobbing mob is displayed for the cryo cell. This involves making an effect and some layering, but that is more reliable overall than having a separate thread that's constantly adding and removing overlays.
Fixes #20875. Doesn't rely on spawns.
https://user-images.githubusercontent.com/80771500/235948908-4cc47b39-30cd-440d-a0cf-5b212337adac.mp4
Stuffed a mob in the cryo cell and turned it on and off.
:cl:
fix: Fixed ghost image of cryo cell being stuck
/:cl:
=> Rework the cryo cell's handling of the occupant icon

code/modules/mob/living/carbon/alien/alien_base.dm, code/modules/mob/living/carbon/alien/humanoid/queen.dm
Sends a message to all living xenomorphs when a xenomorph is killed, with an even bigger one being sent when a queen is killed. Inspired by tgmc.
If you have better suggestions for the messages, feel free to make suggestions.
If xenomorphs aren't communicating or run out and die, it can be pretty easy to lose track of just how the fight is going. It's especially important to know if the queen dies, and this should help xenomorphs stay better coordinated.
Killed a bunch of benos.
:cl:
add: Xenomorphs are now notified when their sisters die.
/:cl:
=> Xenomorph Deathrattle

code/game/machinery/computer/card.dm
Adds security officers to the light blacklist. Crew can still priorities sec officers, but the number of slots are locked. Admins can still increase numbers.
So, of late we have had issues with traitor hop lowering security slots without anyone noticing, or command raising security slots greatly when it is not needed, leading to the situation of 5 vampires to 14 security members excluding warden. 
As such, I am proposing applying security officer jobs to the minor blacklist. This means command can prioritize the job, but not raise or lower it. We can still manually raise it as admins, and it will not stop mainfest hires in situations that need it. It will purely stop sec from being taken out before they exist from an HOP, and stop command from raising security to over needed levels, and …
=> Officer slots can no longer be opened or closed

code/modules/mob/living/carbon/carbon.dm, code/modules/mob/living/carbon/carbon_life.dm, code/modules/mob/living/carbon/human/human_life.dm, code/modules/mob/living/carbon/human/human_mob.dm, code/modules/reagents/chemistry/reagents/medicine.dm
Chemicals that reduce pain (salic acid, morphine, and hydrocodone) will add "health" to the health bar equal to the shock resist.
In short, this generally means that the user when on these chemicals, will not be able to tell how injured / the stamina damage they are from the health bar. 
Health bar is impacted by a fraction (20%) of this value.
The red filter applied to edges of your screen is also impacted and reduced by this
A few reasons why this is good / interesting.
It allows an antagonist to use a toxic chemical in someone that does toxic damage, without them instantly running to medbay, when combined with a pain killer. When someone eats food, and that heal bar goes off 100%, people scream they are poisioned instantly and rush to medbay. This buys some time for the poision to …
=> Chemicals that reduce pain make the users personal health bar less accurate

code/modules/mob/living/carbon/human/human_mob.dm
Security bot will check if your ID is in your hand, when id_check is enabled
New warden being batonned by Armsky cause he tried to disable them or modify settings? 
The entire security department crying to AI and admins to disable Armsky cause it owns them? 
Roboticist calling security cause ED209 is shooting him while he's trying to set settings?
No more, if you have your ID in your hand, id check will work fine and wont make bot attacking you
compiled, runned, moved ID to hand slot
:cl:
fix: Security bots no longer ignore ID in your hand when checks for criminals around
/:cl:
=> Security bot now checks if your ID is in your hand

code/game/gamemodes/vampire/vampire_gamemode.dm
Splits vampire objective & success feedback data from traitor, this was probably an oversight when copy pasting. The code could probably do with refactoring at some point.
Makes vampire and traitor data from gamemodes with both antags useful.
Tested if it logs correctly by making some antags on my local server and seeing if they log at the end of the round.
=> Splits traitor & vampire feedback data

code/datums/uplink_items/uplink_traitor.dm, code/game/objects/items/weapons/caution.dm
Changes the mind requirement to arm and disarm proximity mine floor signs from the janitor role to the traitor special role.
Additionally, allows proximity mines to be found in surplus boxes
This item is very rarely used, so a buff to its usability as a surplus item could be interesting. Could be very useful as a way to remove the knees of any security officers poking around near a traitors hideout. 
Spawn a proximity sign, confirm it fails to arm or disarm. Traitor yourself, and confirm it arms and disams. un-traitor self and confirm you cannot disarm it. Explode. Repeat with mindslaves.
:cl:
tweak: Changes mind requirement for proximity mine signs from "janitor" to "traitor" and/or "mindslave"
Tweak: Proximity mine janitorial signs can now be found in surplus crates
/:cl:
=> Allows proximity mine signs to be used by all traitors

code/modules/mob/living/carbon/human/human_say.dm
Translator implants no longer allow you to bypass mute effects
This was thought to be an exploit for quite awhile, but turns out it's actually intended. For a feature that's not a good sign.
Vampires suddenly needing to figure out how they hell they're gonna deal with a grey (in a way that doesn't involve just killing them) is frustrating, and being able to ignore muting effects is quite weird if you say, chose mute as a roundstart disability. 
Compiled and ran, mutes remained muted
:cl:
tweak: Translators no longer bypass mutes
/:cl:
=> Translator implants no longer bypass muting effects

code/datums/keybindings/carbon.dm, code/datums/keybindings/living.dm, code/datums/keybindings/mob.dm
Changed the default keybindings slightly. Give and Whisper now default to G and U respectively. 
I had to remove the default binding for Next Intent and Prev Intent. However, both can still receive custom bindings in the Game Prefs menu if desired.
Now that we removed the right click option for Give, you either need a hotkey or you need to click the Give verb in the IC tab. Clicking verbs in the IC tab is super annoying. Cycle intent hotkey is not that important, since you already have 1,2,3,4.
:cl: GnomeDePlume
add: Set default keybind for Give to G
add: Set default keybind for Whisper to U
del: Removed default keybind F (Previous Intent) and G (Next Intent). They can still be rebound in the Hotkeys menu.
/:cl:
=> Add default key binding for Give and Whisper, remove default binding for Cycle Intents

code/modules/crafting/craft.dm, code/modules/crafting/recipes.dm
Fixes #20871
Molotov cocktails are now blacklisted from being used to craft molotov cocktails.
Now blacklisted items can not be used to craft. For instance you can no longer use molotov cocktails to craft molotov cocktails. Before blacklisted items only prevented selecting the craft option for a given item but could still be used in the crafting if a valid crafting item was in the players reach.
Prevents wasting materials and not getting what you intended to craft.  Things working as intended is good.
1. spawn as bartender
2. spawn in 5 damp rags
3. grab 5 bottles of whiskey
4. craft 5 molotov cocktails
5. Profit
:cl:
fix: Fixed being able to use molotov cocktails to craft molotov cocktails
/:cl:
=> Fixes molotov cocktails being used to craft molotov cocktails

code/modules/antagonists/changeling/powers/tiny_prick.dm
Makes it so if the distance between the changeling and the target is 0 (Directly on top, or grabbing), it doesn't go through the pathfinding and keeps going as a valid target.
Allows changelings to sting someone who's on the same turf as them.
Held someone in a close grip, and stung them.
:cl:
fix: Changelings can sting targets they're grabbing or standing directly on top of.
/:cl:
=> Changelings can sting targets on the same tile as them

code/modules/projectiles/guns/energy/laser.dm
Lwap scope no longer freaks out if you move before scoping, it only does the process check when fully scoped, as the do_after checks for movement after starting to scope
scope being angry when you are standing still after moving bad
confirmed I got yelled at less by the scope
:cl:
tweak: The lwap will no longer complain as much if you move before scoping in
/:cl:
=> Makes lwap scope not freak out if move before scoping

code/datums/components/material_container.dm, code/modules/awaymissions/mission_code/ghost_role_spawners/golems.dm, code/modules/telesci/bscrystal.dm
Removes bluespace polycrystals (aka bluespace sheets). There only purpose was to be broken down... back into poly crystals. We can sepeate minerals into stack with alt click, there is no real need to have this, especially when we want to inherent the ability to crush crystals, and ore acts just like the stack when put into the ORM / protolathe again. We have 3 types of bluespace ore, we don't need a sheet on top of that.
Raw bluespace ore now is embeded in rock, which used to be what sheets looked like, despite being refined.
Refined bluspace crystals and artifical bluespace crystals now stack visually, were missing the dynamic icon state flag.
Golems are now crafted by refined bluespace crystals rather than sheets. Functionally the same, as you broke sheets into refined crystals. …
=> Removes bluespace crystal sheets, makes crystals look as expected

code/modules/food_and_drinks/recipes/recipes_oven.dm
Closes #21015
Makes it so that birthday cake requires mutated botany plants (10u vanilla), 3 candles, raised the amount of sugar to 15u to be in line with other cakes. Removed the need for using the cake hat for its recipe so it can be made on other stations, and can be made more than once (realistically).
New cake recipe overview:
- 3 doughs
- 3 candles
- 15u sugar
- 10u vanilla
- 5u milk
Needing a hat for cooking both limits where and how many can be made, but needing a hat is just silly. 
made some beautiful cakes
:cl:
tweak: tweaked the birthday cake recipe
/:cl:
=> Removes need for the cake hat when making Birthday Cake

code/modules/surgery/organs/lungs.dm
Fixes an inconsistency where lungs were the only vox organ that wasn't sterile and accumulated infections.
Every other vox organ is sterile, wiki mentions *all* vox organs being unaffected by infections - might as well remove the inconsistency and make it actually correct.
Considering vox lungs are oddly not in the same file as the other vox organs, it also feels like a simple oversight.
Forcefully dragged a vox into an OR and ripped their lungs out, VV'd them to make sure they don't amass infections anymore. Did the same with a vulpkanin to make sure other types of lungs weren't somehow affected by the change.
:cl:
fix: Vox lungs are no longer affected by infections.
/:cl:
=> Fixes vox lungs being affected by infections

code/_onclick/hud/guardian.dm
Guardians can not manifest when user is in atmos machinery. This does include cryopods, though I do not think anyone was using cryopods for that.
Crew can't really fight a holopara when the user is in the pipes. Too mobile, and if the user is a plastic golem, they even take less damage.
This PR blocks holopara useage in pipes, without blocking somone using a locker (people can see where it pops out of / can check a locker), cham projector (TC / still pop out over an item, have to stealth the item out of the room once pulling the trick), or in a mech (Hard to get / have to leave mech for healing / people will guess that the durand has the guardian.)
Confirmed the guardian could not manifest in pipes.
:cl:
tweak: Guardians can not manifest when user is in atmos machinery such as pipes. …
=> Guardians can not manifest when user is in atmos machinery

code/modules/research/designs/medical_designs.dm, code/modules/surgery/organs/augments_arms.dm
Removes the hacking implant from the game. Adds an upgraded toolset implant with abductor tools.
The hacking implant was just, not used. This adds the ability to make an abductor toolset implant instead, which contains all of the abductor tools. This adds an extra lategame upgrade to engineering and anyone who uses tools, which in turn will add extra things for medbay to do.
The research required is one level higher than the lone tools, except for alien. The cost is about 60% of if you were to make them all individually.
Went into testserver, checked if resource costs were correct, and if it was unlocked by the right level of technologies. Also checked if the tools worked.
:cl:
add: Abductor toolset implant
del: Hacking implant
/:cl:
=> Changes the hacking implant to the abductor toolset implant

code/game/machinery/computer/communications.dm
Comms consoles can now only change alert level on red or lower alert
Being able to change alert from gamma/delta/epsilon to green alert, isn't intended I believe
Set alert to epsilon, wasnt able to set it to green
:cl:
fix: Comms consoles can only change alert on red or lower
/:cl:
=> Comms consoles can now only change alert level on red or lower alert

code/game/gamemodes/miniantags/guardian/types/protector.dm
Yeah this one is an I'm dead pls nerf, to be 100% honest. I did wish for someone else to make it, but they needed to pack for a flight. So I'll take the hit for a needed PR.
Protector guardians now block mob movement through them in protector mode. 
Negating a 12 investments point of being a wall by crawling is bad. This was never an issue before, as we did not have crawling before. With crawling, people can now just crawl under them and bypass their entire mechanic of being a wall that people can not go through, without dealing a whole bunch of damage, or going around the guardian through another path.
Tried to crawl through protector in defense, failed. Tried to crawl through protector in offense, succeeded. Try to crawl through a person with protector in defense inside them, succeeded. …
=> You can no longer crawl under protector guardians.

code/datums/components/defibrillator.dm
Removes a unneeded notify_ghosts() that make every observer's taskbar icon flash unnecessarily
The taskbar icon should only flash when something important is happening
Defibbed someone with 3 clients, it only flashed the person's being defibbed task bar
:cl:
fix: Defibrillating someone no longer flashes all ghost's screens
/:cl:
=> Defibrillating someone no longer flashes all ghost's screens

code/modules/antagonists/vampire/vampire_powers/umbrae_powers.dm
This PR adds flash ability to destroy shadow snares(vampire umbrae powers)
Shadow Snare is half invisible trap hiding in shadows, its hard to detect without nightvision or something else, but once you find it, its hard to remove it too. You need to keep light for about to 5 seconds near it to destroy. Using flash at it would do nothing, same as anything else, just light. So adding ability to fastly remove it looks nice to me and this flash utilization supposed to be there.
Compiled, flashed.
:cl:
tweak: Shadow Snare could be instantly destroyed by using flash on it
/:cl:
=> flash ability to destroy shadow snare

code/game/machinery/quantum_pad.dm
This change adds handling for AI eye interactions with quantum pads.
* When an AI eye user clicks on the quantum pad, the eye will center on the pad if it is not already, mimicking holopad behavior.
* If the AI eye is already centered on the pad when it is clicked, the pad will be tested for usability in the same manner it is for users, which logic has been moved to its own proc. 
* If the pad is usable, the turf of the linked pad will be checked for visibility. 
* If the turf of the linked pad is visible, `setLoc` is called on the AI eye, allowing visibility chunks to be updated. 
* If it is not usable, the AI will receive a warning notification similar to the one used when unable to track a mob via cameranet.
Usability tests for quantum pads have been moved from …
=> Quantum pads now check AI cam visibility (#21074)

code/modules/reagents/chemistry/reagents/medicine.dm
Title.
- Makes it show up as `OVERDOSING` on the health analyzer, less confusion.
- Not strictly intentional, but it lifts the actual range in which you get the overdose to *above* 4u (metabolism code is jank, can't really control it without making the threshold an ugly float), though I figure it's fine to give the players a tiny bit more leeway.
- Drank 5u of Perfluorodecalin, suffered as advertised by the health analyzer.
- Drank 4u of Perfluorodecalin, did not suffer.
:cl:
tweak: Perfluorodecalin overdose now shows up as such on health analyzers
/:cl:
=> Converts Perfluorodecalin's side-effect into an actual overdose

code/game/objects/effects/spawners/lootdrop.dm
Adds advanced burn kits to the maintenance loot spawner with the same weight as advanced trauma kits.
Consistency, I'm not entirely sure why trauma kits could spawn but burn kits can't.
Loaded in, observed, saw a few burn kits.
:cl:
tweak: Burn kits now spawn in maintenance
/:cl:
=> Adds advanced burn kits to maintenance

code/datums/uplink_items/uplink_general.dm, code/datums/uplink_items/uplink_traitor.dm
Moves the traitor posion bottle to the main uplink from job specific
Some people have asked me to do this in the past, and I agree.
The jobs that can buy the bottle, do often feed people reagents. However, these people can already make reagents to poison with, there is no reason to keep the poison to them.
We allow anyone to buy the sleepy pen / RSG / dart pistol kit, so we might as well let them gamble on toxins to reload it with.
Confirmed uplink had it.
:cl:
tweak: Any traitor can now buy the traitor poison bottles.
/:cl:
=> Moves the traitor posion bottle to the main uplink from job specific

code/modules/research/designs/autolathe_designs.dm
Title. This was probably just missed during the tool size change.
Clicking a button that says "pocket crowbar" and not getting a crowbar that fits in your pocket is bad
crowbar
Loaded in and took the screenshot just above
:cl:
spellcheck: The autolathe no longer lies about the size of its crowbars
/:cl:
=> Changes "Pocket Crowbar" to "Crowbar" in the autolathe menu

code/modules/mob/living/silicon/robot/robot_mob.dm
Title - while reset modules remove the _effects_ of upgrades, they don't remove the upgrades themselves. This fixes that.
Bugs are bad
Loaded in and applied upgrades to myself, then proc called reset_module and saw that it worked
:cl:
fix: The reset module upgrade now properly deletes other upgrades on use
/:cl:
=> Fixes reset modules not properly clearing upgrades

code/modules/hydroponics/seeds.dm
Tweaks a weird hack in code that creates harvest products from botany plants to make more sense mathematically. More precisely, it converts a `1 + <sane volume calculation>` - which I can only assume was meant to ensure you always get at least a tiny bit of the chemicals - into a `max(<sane volume calculation>, 1)`.
- Makes the mechanic consistent with the wiki guide. While this is extremely minor in practice, people who *do* want to do some botany math shouldn't have to adjust for what feels like an off-by-one bug (which this kinda is).
- Nerfs botany extremely slightly 👍
Before and after:
- Grab a pack of Poppy seeds from the botany vendor
- Plant the lil guy nice and firm
- Make sure to get him some Robust Harvest to avoid mutations on harvest which could alter the test results
- Wait …
=> Fix plant reagent genes producing slightly more chemicals than expected

code/modules/mob/living/simple_animal/hostile/megafauna/ancient_robot.dm
Fixes an ever so small but ever so important spelling mistake in vetus since it was added:
/mob/living/simple_animal/hostile/megafauna/anicent_robot/ex_act(severity, target) to:
/mob/living/simple_animal/hostile/megafauna/ancient_robot/ex_act(severity, target), which keeps vortex vetus from offing itself.
Also removes some extra spaces / uneeded extra line.
Vortex vetus doing ~ 1500 damage to itself in a 3 charge burst is not good.
https://tenor.com/view/minor-spelling-mistake-gif-21179057
Spawned in vetus, confirmed it no longer took damage charging.
Missed before as I had vetus charge at me as vortex with the tweak merged 2 weeks ago, so I did not see the health change, despawning it after I was sure it was ripping me apart with the charge from explosions.
:cl:
fix: Vortex vetus no …
=> Vortex vetus no longer bloody dies when it charges at you more than once.

code/__DEFINES/dcs/signals.dm, code/__DEFINES/status_effects.dm, code/datums/status_effects/debuffs.dm, code/datums/status_effects/neutral.dm, code/game/objects/items/weapons/implants/implant_adrenalin.dm, code/game/objects/items/weapons/stunbaton.dm, code/modules/antagonists/changeling/powers/epinephrine.dm, code/modules/antagonists/vampire/vampire_powers/vampire_powers.dm, code/modules/mob/living/living.dm, code/modules/mob/living/simple_animal/bot/ed209bot.dm, code/modules/mob/living/simple_animal/bot/secbot.dm
This PR moves stunbaton delayed knockdown into status effect
Adds removing this status effect to adrenal bio-chip, changeling adrenals, vampire rejuvenate and to admin rejuvenate
So now if you got batonned and you pressed adrenals to run away you will not fall down in two meters if you didnt get hit after you used it
Thats what adrenals, rejuvenate and other supposed to do. They supposed to reduce or remove all bad effects like stamina damage and other but stunbaton delayed knockdown was ignoring that all, so when you see adrenals guy you can just spam your stunbaton at them and there is high chance that they will not run away
This PR makes them all(adrenals, changeling adrenals, rejuvenate) act like intended. You are great vampire, you just healed tons of damage and all stamina, you …
=> Stunbaton delayed knockdown now respects antistuns

code/game/objects/effects/effects.dm
This PR adds check for decals attackby
If nothing happends on our click on decal(we didnt try to collect fungus with beaker if we are brown terror escaping five thousand ERT shooters), it starts action on its location, which must be simulated turf(walls are)
Have you even been scared by this fella?
When you want to make falsewall or fastly touch the wall under it, you need to hit little pixel on the top right of it or you get your action declined and message like "You heat the space fungus with the integrated welding tool."
This PR allows you to just hit this fella instead, you will hit the wall, no actions will be declined.
This wont affect your default actions with those, if you want to collect them, you will do that and not hit the wall with beaker
It only affects if default action did …
=> Decals now do not decline your action

code/modules/antagonists/changeling/powers/headslug.dm, code/modules/mob/living/simple_animal/hostile/headslug.dm
Reworks last resort
Last resort no longer stuns for 2 seconds, knocks down now for 4
Headslugs now move much faster, a 1 speed delay to a .3 speed delay, still slower than a human 
Planting your eggs is now done with alt-click
Eggs can now be planted in living mobs, takes 5 seconds of them staying still to do so, hatches slower, and gives them notices that they are infected
Eggs can now be planted in small mobs
Headslugs now die after 25 seconds post egging, instead of 10
Headslugs can now hide and pass under doors while hidden
I've been running a poll on changeling balance stuff, and this is considered to be the weakest changeling ability only tied by organic shield. I must agree this ability fucking sucks
This ability requires you to have
1. A body basically set up in advanced (semi …
=> Reworks changeling's last resort

code/modules/reagents/chemistry/reagents/medicine.dm
morphine now processes on OD
Morphine is supposed to sleep them when it is in their system for a while. This is the downside of morphine as a painkiller, and the upside if using it to sleep people. However, because I am an idiot and missed morphine as it had no personal overdose process, since morphine does not process when overdosed, overdosing on morphine lets you ignore the downside of morphine.
I probably should have made it true by default then false for the problematic reagents in the overdose pr, that is on me.
confirmed people go to sleepy zone
:cl:
fix: Overdosing on morphine once again will still have you be asleep.
/:cl:
=> morphine now processes on OD

code/modules/response_team/ert_outfits.dm, code/modules/surgery/organs/augments_internal.dm
Adds the hardened wire interface implant.
Replaces the wire implant on ERT with the hardened one.
It's really funny watching ERT get hard stunned for 10 seconds from an EMP
It's less great balance wise however, and all other ERT implants that stun are hardened, so...
confirmed engi ERT had the emp proof implant.
:cl:
add: Adds the hardened wire interface implant, now with less wires.
tweak: Engineering ERT now get the hardened implant, rather than the normal one.
/:cl:
=> Engi ERT now get hardened wireless interface implants

code/game/objects/items/weapons/storage/secure.dm
Fixes #20238
By adding a check to make sure that resetting a secure safe it will only close your inventory if the safe is your active inventory, we get no more stacked inventories
bug bad
1. spawn as captain
2. open backpack
3. go to secure safe(wall safe) and press "R"
4. Enter passcode and open safe
5. safe inventory replaces backpack inventory
6. Profit!
:cl:
fix: Fixed issue where safe inventory appeared over other inventories
/:cl:
=> Fixes secure safe inventory breaking

code/modules/hydroponics/seeds.dm
Title; also refactors the `harvest` proc to be cleaner and no longer do a roundabout ceiling operation, instead applying it explicitly in `getYield`.
Less confusion about whether that extra harvested plant you can see in your plant bag is an actual full product or maybe half-empty somehow, when using Robust Harvest's decimal yield boost.
Before & after:
- Plant a pack of poppy seeds
- Give them some Robust Harvest
- Look at him go
- Harvest when ready, check that the harvest feedback message perfectly mirrors the number of produce
:cl:
spellcheck: Harvesting plants grown with Robust Harvest no longer reports a decimal number of products
/:cl:
=> Fix harvest message reporting decimal item amount when using Robust Harvest

code/game/jobs/job/medical_jobs.dm, code/game/objects/structures/crates_lockers/closets/secure/medical_lockers.dm, code/modules/clothing/spacesuits/misc_spacesuits.dm
- The Paramedic now has `EVA_ACCESS`.
- The Paramedic Locker now starts with its current contents plus a Defib, Medical Belt, Advanced Medkit, emergency toolbox, and a pair of MedHUD Sunglasses.
- To match literally every other Head, the CMO has ALSO been given MedHUD sunglasses.
- The Paramedic's EVA Suit is now storable in a bag and has a 0.25 slowdown (down from 1).
- Medical Storage lockers are now `ACCESS_MEDICAL` instead of `ACCESS_SURGERY`.
Paramedic is in a weird spot. Their EVA Suit is mega trash compared to the Medical Hardsuit (which quite literally have less slow down at 0.5) so it has been made into a proper "one of a kind useful" suit. They also now have EVA Access so they can actually get O2 tanks refilled.
Their access was lacking as well - you were unable to restock with …
=> Paramedic Tweaks (and Tiny CMO Tweak)

code/modules/mob/living/carbon/give.dm
Makes it so that you can only use the give verb to give items to other humanoids (`/mob/living/carbon/human`). This is more of a fix. Xenos should not be holding anything besides facehuggers really.
Fixes #21137
:cl:
fix: You can no longer use the give verb to give items to xenos.
/:cl:
=> You can no longer give items to xenos

code/modules/surgery/organs/blood.dm
Raises your blood regeneration a tiny bit if you're well fed.
Adds a small boost to being well fed, also makes it so the perpetuating myth (that made it into the wiki somehow) is actually correct.
Also cookie
Shot some skrell with haemorrhage rounds and saw which one regenerated faster
:cl:
tweak: Being well fed now buffs your blood regeneration
/:cl:
=> Being well fed increases your blood regeneration 

code/modules/mob/mob_helpers.dm
Fixes some weird behavior with ghost notifications on icons larger than 32x blowing up the viewport.
Before: 
After:
also: proof it still works with regular-sized icons
Large icons in these notifications can *really* mess with the viewport. While this won't fix every instance where something similar happens, it should fix the most noticeable, especially when a large atom is just Passed In as source
Loaded in, granted deadchat control over a bunch of large and small things. Offered direct mob control to ghosts as well, to ensure smaller things with overlays still work.
:cl:
fix: Large icons in ghost notifications should no longer mess up the viewport.
/:cl:
=> Improves how notify_ghosts works with larger icons

code/modules/response_team/ert_outfits.dm
Removes duplicate code from the ERT Red Medics in regards to their cybernetic implants.
Cleans the code and ensures the right implants are being used.
Spawned and inspected an ERT Red medic to see that they had the intended cybernetic implants. 
:cl:
tweak: tweaked implant list for ERT Red medics
/:cl:
=> Removes duplicate cybernetic implants from ERT Red Medic

code/modules/surgery/limb_augmentation.dm
Fixes: #21111 - an oversight that allows augmentation surgery to occur when limbs are damaged. 
Forces players to fix damaged body parts before performing augmentation surgery. Prevents possible jank from happening due to damage. 
Tested to see if the surgery was available when limb was splinted or salved. Checked to see if the surgery was not available while broken/necrotic/burned/dead/IB. 
:cl:
tweak: Tweaked the augment limbs surgery eligibility check
/:cl:
=> Oversight fix: Augment Surgery Limb Status Fix

code/game/machinery/adv_med.dm
Fixes the body scanners so they display blood level percentage properly when using the printout option. 
Allows for equipment to function as intended.
**Before:**
**After:**
Checked blood percentages on both the stationary and handheld body scanner.
:cl:
fix: Fixed body scanner printout and blood percentages
/:cl:
=> Fixes body scanner printout not properly displaying blood level 

code/game/machinery/cryopod.dm
The Captain's ID used to be the only ID kept in cryostorage, as it was a subtype of the spare ID. As I imagine this was not intended due to reasons bellow, now it follows the logic of all other personal IDs and gets deleted when the holder goes to cryo.
Spare not being deleted makes sense, as it is a necesary item that should always be kept on the station, as it is the only way to modify access without Captain/HoP. However, a normal Captain's ID being stored makes it so anyone with access to the console  (Head ID or Armory access) can get AA very easily, and on an unintutive way - as you would expect personal belongings to be removed on cryo. If you are antag Head and see the Captain cryos, you know you are getting All Access with no effort.
- Spawn as captain
- "Didn't roll antag, better …
=> Prevents Captain's ID from being kept in the cryostorage console

code/modules/antagonists/changeling/powers/biodegrade.dm
This PR removed delay of removing cuffs, legcuffs, grabs when using biodegrade changeling ability
This PR adds acid hand as lesser version of xeno corrosive acid. It cant be used to attack someone(xeno corrosive is GREAT assault weapon), but still can melt walls and other objects.
Biodegrade costs 2 evolution points and 30 chemicals on use and thats the only way for changeling to remove handcuffs without statis. rn it has delay on removing cuffs which allows sec to just baton you and you're losing escape chance again.
By my sight it should work like basic freedom implant, meaning removing cuffs and other instantly, allows you to action.
Also using this acid to melt other objects looks fine. It wont overpower cling(cause its melting is TOO LONG to be OP and cant melt a LOT of objects) but …
=> Biodegrade buff

code/game/machinery/doors/airlock.dm, code/game/machinery/doors/door.dm, code/game/machinery/requests_console.dm, code/game/machinery/status_display.dm, code/game/machinery/vendors/vending.dm, code/modules/mapping/mapping_helpers.dm
Adds `update_icon` calls in various Inits, or helper payload. The unres proc for airlocks is slightly rewritten.
Vendors, airlocks, request consoles, status displays, and the unrestricted access helper are affected.
A lot of overlays or lightmasks weren't being set properly until some other action would prompt an object to update itself, which wasn't good for ambience.
Loaded into Boxstation, and killed all the lights.
:cl:
fix: Vendors, airlocks, request consoles, and status displays set their icons properly on round start.
/:cl:
=> Make various machinery properly update their icons on init

code/modules/reagents/chemistry/reagents/misc_reagents.dm
- Most importantly - title. Makes burning oil not create flash fires if you use >=30u. Previously you *always* had a flash fire regardless of volume (though it only explodes nearby oil tanks if the amount burned is actually *>=40u*).
- Improves the feedback slightly, giving you a slightly different message depending on whether the reaction explodes in a flash of fire or not, as well as introducing a minor detail in the form of making the resulting smoke non-cough-inducing for the safe burned volume range.
- Adds some sound to the reaction to indicate boiling and sizzling oil; previously it was silent aside from the coughing.
Yet another case of wiki misinformation that became a widespread myth (or maybe the other way around?). Figured it's better to adjust the game rather than the wiki, …
=> Make burning Oil into Ash *actually* not cause fires at 30u or below

code/datums/components/deadchat_control.dm, code/game/atoms_movable.dm, code/modules/mob/living/carbon/carbon_emote.dm, code/modules/mob/living/carbon/human/human_mob.dm
Makes some small tweaks to deadchat controlled humans:
- Attack now properly makes use of the attack chain (or unarmed attacks if nothing's in their hands), though still won't behave exactly like clicking their target.
- Humans now have a "resist" command, to attempt to escape restraints.
- Humans also have a "help" command, which attempts to click the target with help intent. If used on a mob with an empty hand, it'll give them a hug. "attack" now uses harm intent.
- Fixes a runtime with *clap failing if called by a mindless mob, and another with a qdel loop when removing the component from things with cardinal movement.
- Ghosts orbiting something with deadchat control added to it will be added to the controller list automatically without needing to refollow.
- Adds a message for people …
=> Minor deadchat control improvements

code/datums/mind.dm, code/modules/martial_arts/adminfu.dm, code/modules/martial_arts/brawling.dm, code/modules/martial_arts/cqc.dm, code/modules/martial_arts/grav_stomp.dm, code/modules/martial_arts/krav_maga.dm, code/modules/martial_arts/martial.dm, code/modules/martial_arts/mimejutsu.dm, code/modules/martial_arts/plasma_fist.dm, code/modules/martial_arts/sleeping_carp.dm, code/modules/martial_arts/wrestling.dm
This PR changes how martial arts are stored, and gives each one a weight for determining which ones should be overridden by others.
Right now, getting new martial arts does not properly remove the old one, resulting in a weird mess of having multiple instances of CQC or carp. Not only does this fix some runtimes, but current martial arts are automatically overriden by any new ones you get. This means that getting drunk, or putting on boxing gloves will temporarily disable any other martial arts someone might have. This system makes it so they learn the new martial art, but if it's a lower weight value than their current one, it won't be as the active martial art.
Fixes #13501
Spawned in, gave myself many duplicate martial arts, gave myself many different martial arts and made sure they …
=> Martial arts now use a weight system to determine which one is active

code/modules/clothing/glasses/hudglasses.dm
Adds the ability to put prescription glasses onto NV HUDglasses.
Currently, people who have chosen to be shortsighted cannot effectively use NV HUDglasses.
Booted up a testserver, tried adding prescription glasses to the NV HUDglasses, stared at a screen for a bit for bad eyesight, then checked if the glasses worked to negate it.
:cl:
add: the ability to add prescription glasses to all 4 night HUDglasses
/:cl:
=> Prescription glasses for all!

_maps/map_files/Delta/delta.dmm, _maps/map_files/cyberiad/cyberiad.dmm
Fixes #20193
Sort of... Court room access doesn't seem to actually do anything so getting it is pointless on all stations. It should probably just be removed but at least now all court  rooms require the same access
This PR changes access in the following areas
Delta Equip room: now you need more then front door access to the brig to get access to the open armoury
Delta Court room: now anyone with front door brig access can get into the courtroom and not just IAAs, this is done to make it inline with the Cyberiad
Cyberiad Prisoner Observation: You now need perma access in order to enter this room because otherwise the control for opening the perma doors has no access requirements and thus a CMO could release prisoners and access tear gas grenades
No walking into the armoury for the RD, no …
=> Fixes access' around the brig and courtroom

_maps/map_files/MetaStation/MetaStation.dmm, _maps/map_files/cyberiad/cyberiad.dmm
Adds a teleporter shutter for public usage of the teleporter if the heads wishes to open it.
Now that the gateway is going away its a good moment to include public teleporter shutters, that other maps already have, to send your crew to any place you desire, without the risk of someone sabotaging it.
- Used the shutter both on box and meta.
:cl:
tweak: Added public teleporter shutters to Cyberiad and Cerebron
/:cl:
=> Adds public teleporter shutters to box and meta stations

code/game/objects/structures/holosigns.dm
Closes #21046
See title
The fact it's restricted to carbons seems more like an oversight if anything considering these are mob vars. Silicons and simplemobs really should be able to use these because they'll just destroy them otherwise. It's weird, unintuitive, and doesn't really add anything. 
Compiled and ran 
Walked into some barriers
:cl:
tweak: All mobs can now walk through security barriers, rather than just carbons
/:cl:
=> All living mobs can now go through security holobarrier signs

code/modules/clothing/clothing.dm
Balaclavas will now move directly to your head/mask slot when adjusted if possible, instead of going to the hands and having to put it on again.
In another way Fixes: #16149
Convenience, intuitive behavior.
https://github.com/ParadiseSS13/Paradise/assets/16618648/7015c812-3741-4d56-94ba-e1e289b0defc
*See video*
:cl:
tweak: Balaclavas, when adjusted, will move to head/mask if possible instead of always to hands.
/:cl:
=> Balaclava QOL

code/modules/reagents/reagent_dispenser.dm
Adds some logic for reagent container structures to have overlays, and gives the beer keg nuke the real nuke's bolted wheels overlay when it's wrenched in place.
The model nuke should demonstrate the real nuke's capability to be anchored in place! Also, if people want to sprite similar overlays for water or fuel tanks in the future, they can add that pretty easily now by basically copying what I did for the beer keg nuke.
Loaded in, wrenched and unwrenched the beer keg nuke a few times.
:cl:
tweak: The beer keg nuke now has anchoring bolts just like the real nuke
/:cl:
=> Makes the beer keg nuke more realistic

code/game/machinery/vendors/vending.dm
Adds instruction to the description of a tipped over vending machine about the need to alt+click to right it
New players will get less frustrated trying to figure out how to fix the vending machines
:cl:
tweak: Description of tipped vending machine now tells you how to put it up again (alt+click)
/:cl:
=> Instruction for how to right a vending machine

code/game/machinery/doors/brigdoors.dm
Makes it so that the icons of the lockers in brig cells update when they are automatically unlocked after the timer runs out/the prisoner is released.
Bug bad.
Go to brig
Close and lock locker
Start timer
Timer runs out
Locker unlocks, visibly
:cl:
fix: Brig cell lockers now update their icon on release.
/:cl:
=> Fixes brig cell lockers not updating their icon when a prisoner is released.

code/datums/action.dm, code/datums/spell_cooldown/spell_charges.dm, code/datums/spell_cooldown/spell_cooldown.dm
This PR improves spell with charges icon when its recharging. Now it shows you amount of charges and progress on recharging new one.
Currently its only vampire glare and you want to know when you have two glares or when it will be avaiable
compiled, glared
:cl:
tweak: Spells with charges(vampire glare) will now show current charge level and recharging process
tweak: Using spell charge while recharging no more reset recharge timer
/:cl:
=> Improved cooldown visualisation on spells with charges

code/game/objects/items/tools/welder.dm
See title, welders now use 0.5 fuel on attack on any object/mob, this will get you one blob tile per one fuel for reference. 
Welders are more and more becoming a multi tool for combat, mass printed, and used for everything. this PR aims to not make them a 15 burn damage powerhouse for every bio hazard, and _any_ task that requires damage at zero fuel cost, hopefully getting people to use other means of damage/be more conservative with their fuel.
Booted up a test server, THWACKED a few things to make sure fuel was being spent correctly, and it was.
:cl:
tweak: Welders now use 0.5 fuel on hit on any mob/tile
/:cl:
As this is quite the tweak, I'll request a TM to see if the fuel would need to be upped/lowered at all. Or if there's some bizarre glitch i didn't think of.
Also, apologies if i …
=> Welders now use 0.5 fuel on attack. 

code/modules/research/rdconsole.dm, code/modules/research/research.dm, code/modules/research/server.dm
Research datums have 2 new lists. The blacklisted list, and the unblacklisted list.
Instead of deleting a design (which currently does nothing RND wise, since once the servers link, the tech levels restore the design), RD can blacklist designs with the R&D server controller. This prevents a design from being printed from linked protolathes / circuit imprinters. A new rnd setup could still build said design.
The console can also unblacklist a design, allowing rnd to have it once again once the rnd console syncs again.
The delete functioning being changed to something that works is useful. It allows silent sabatoge by an antagonistic traitor or AI, who can delete a certain design from rnd, to prevent the crew from making it. Shame that the illegals tech doesnt let security get a silencer. …
=> Lets the rnd server controller actually have use in blacklisting

code/datums/looping_sounds/looping_sound.dm
This PR fixes a bug when some object that should emit looping sounds was added twice to list, makes object emitting sounds infinitely. Currently its happening when you EMP fire alarm with APC, magic happends and TADAA, loud fire alarm looped sound is here forever until you destroy it.
Bugs bad
Compiled, blew up big EMP bomb, enjoyed silence after disabling fire alarms
:cl:
fix: EMPd fire alarm(object) now will not emit fire alarm sounds forever
/:cl:
=> Fixing infinite fire alarm sounds

.github/workflows/ci.yml
Fixes CI error on mariadb container setup
https://github.com/MariaDB/mariadb-docker/issues/512
https://github.com/tgstation/tgstation-server/pull/1532
https://mariadb.com/kb/en/mariadb-11-0-1-release-notes/#docker-official-images
:cl: azizonkg
fix: CI error on mariadb container setup
/:cl:
=> Fix(CI): mysqladmin symlink is gone in latest mariadb docker container

code/modules/antagonists/changeling/powers/become_headslug.dm, code/modules/mob/living/simple_animal/hostile/headslug.dm, code/modules/surgery/organs/organ.dm
See title
Adds a aheal at the end of the monkey spawn just to make sure that they're properly revived.
also improves clarification on how to lay your eggs
This is a fix, right now you can get necrotic organs if you wait too long to reproduce as a headslug (It's only a few minutes too, it's gonna happen). A cling with a dead brain is a soon to be dead cling.
checked germ level in var panel
:cl:
fix: Last resort clings no longer have their organs necrotize if they don't reproduce quickly 
spellcheck: improves clarification on how to lay your eggs as a headslug
/:cl:
=> organs no longer gain germs while in a changeling egg/headslug

code/modules/surgery/limb_reattach.dm
It is currently possible to add a head with a brain to a body with a roboticized chest containing an MMI, causing there to be two brains in one body. This PR fixes this.
You really, really do not want two brains in one body.
Remove a skrell's brain.
Put the brain in an MMI.
Augement another skrell's chest (Henceforth referred to a skrell 2.)
Decapitate skrell 2.
Put MMI in skrell 2's chest.
Attempt to put skrell 2's head back.
Not possible.
:cl:
fix: You can no longer add a head with a brain to a body that already contains a brain.
/:cl:
=> Prevents adding a head with a second brain to a body

code/game/machinery/quantum_pad.dm
Makes cyborgs capable of using quantum pads again.
fixes: #21252
Walking all the way from one end of Farragus to the other as a cyborg is not fun.
Also bug bad.
Join as AI.
Use quantum pad.
Camera view jumps to other pad.
Join as borg.
Use quantum pad.
Teleport.
:cl:
fix: Cyborgs can use quantum pads again
/:cl:
=> Fix: Cyborgs can use quantum pads again

code/game/objects/items/weapons/powerfist.dm
power fist no longer works when user is pacified
It's not an I ded pls nerf if you aren't the one that died to it right?
In all seriousness though, it should not work when pacified. It only worked as it overrides attack.
Tried to punch while pacified.
Failed.
Tried to punch when not.
Succeded.
:cl:
fix: Power fist no longer works when user is pacified
/:cl:
=> power fist no longer works when user is pacified

code/game/objects/items/devices/geiger_counter.dm
Adds units (rads) to the chat results of the geiger counter.
Quantifying numbers with units is good
Disable grav gen, confirm units are present. Confirm emag functionality is untouched.
:cl:
tweak: Adds units (rads) to geiger counter readout
/:cl:
=> Adds units (rads) to geiger counter readout

code/_onclick/hud/parallax.dm
Fixes parallax not continuously rolling when inside a moving shuttle. (before it would move through one loop and stop)
Visual bug executed.
**BEFORE:**
https://github.com/ParadiseSS13/Paradise/assets/16618648/b7419fdb-91ac-4955-a7cb-9d81cbace96b
**AFTER:**
https://github.com/ParadiseSS13/Paradise/assets/16618648/6600eb3e-1d2f-4653-8212-4f9eba02484c
:cl:
fix: Fixed parallax not looping during shuttle transits.
/:cl:
=> Fixes Shuttle Parallax 

code/modules/mob/living/silicon/ai/ai_life.dm, code/modules/tgui/states.dm
For quite a long while now, the AI has had a power restore sequence when the APC in their room is disabled. It also has been broken for a long while.
This PR fixes this power restoration routine. This means that if the APC in the AI's room is disabled for any reason, after the specified time (I believe it's currently roughly 20 seconds?) the AI gets access to their APC control panel, which would allow them to turn it back on (Assuming the APC doesn't have cut wires or the likes)
fixes: #19440
Bug bad. 
Become the AI.
Disable my own APC.
Wait for the APC screen to pop up.
Turn my APC back on.
:cl:
fix: AI Restore Power Routine finally works again
/:cl:
=> Fixes AI Restore Power Routine

code/game/machinery/transformer.dm
Decreases the cooldown for the malf AI borgifier to 30 seconds from 1 minute.
While I do understand the need for a longer cooldown on this device, the length of the cooldown often results in long ques for people to be borged. Ive seen this end in one of two ways: an orderly line to get chopped to robo-bits, or a free for all that results in borgs just killing people since the wait is too long. Ive only seen the first one once in my over 2k hours on paradise. The goal of this PR is to reduce the latter of the above outcomes and allow more people to get in on the chaos. 
Once I understood the weakness of the skrell's flesh, it disgusted me. The omnissiah was fed every 30 seconds for two minutes.
:cl:
tweak: reduces malf AI borg factory cooldown from 1 minute to 30 seconds
/:cl:
=> Buffs Cyborgificaiton machine for malf AI

code/game/objects/items/weapons/storage/garment.dm, code/game/objects/structures/crates_lockers/closets/secure/medical_lockers.dm
Gives psychologist a garment bag with following contents:
- Psychiatrist Jumpsuit
- Psychologist Turtleneck
- Medical Doctor Jumpsuit (job title "therapist" starts with it)
- Medical Doctor Jumpskirt (for good measure)
- Psychologist Labcoat
- Laceup Shoes
- Medical HUD (they steal one every round anyways - access to records on the fly)
- Skills HUD (they start with one in their office on Cyberiad and it's an INCREDIBELY useful tool for RP - doing background checks in patient's employment records)
- Blue Tie
If anyone has further ideas for drip psych could use - feel free to leave them below!
Psych drip is a strange case, where most of it (mainly jumpsuits) are, simply, unaccessible to you if you have the wrong JOB TITLE of all things.
In addition, his locker is absolutely filled with …
=> Gives psychologist a garment bag

code/modules/client/preference/loadout/loadout_racial.dm
Sleek veil, the Tajaran sec hud racial loadout item is unable to be used as detective. This is probably an oversight from when detective didn't spawn with sec huds. 
detective drip is required to function 
successfully spawned with sleek veil as detective
:cl:
add: detective job to sleek veil whitelist
/:cl:
=> adds detective to sleek veil whitelist

code/modules/events/blob/overmind.dm
This turns the blob overmind icon into a tilsized clickable object, for easy follow, and allows admins to use the right-click options on blob overmind. Fixes #20987
Lets it be clickable as an observer or admin.
Boot up server, spawned a blob mouse, waited for it to pop, aghosted and confirmed that I could both click and right click it.
:cl: ppi
fix: Makes the Blob Overmind clickable
/:cl:
=> Lets you click the blob overmind

code/modules/events/bureaucratic_error.dm
See title, they get a dsay message about it
Why wouldn't ghosts have this info?
Saw it in game
:cl:
tweak: dchat now gets an alert on what jobs have changed in Bureaucratic error
/:cl:
=> dchat now gets an alert on what jobs have changed in Bureaucratic error

code/modules/mob/living/silicon/ai/ai_mob.dm
malf ai apc hack sounds no longer play on the AIs turf, rather they're sent to the actual AI
I don't think it's good to have everyone in the room know you just hacked an APC
Hacked some APCs
:cl:
tweak: You can no longer hear a malf AI hack an apc
/:cl:
=> players no longer hear a malf ai hack an apc

code/modules/supply/supply_packs/pack_organic.dm
Adds the Ingredient Crate to cargo, containing 25 random plants. The crate includes wheat, tomatos, potatos, carrots, pumpkins, chilis, cocoa pods, corn, eggplants, apples, bananas, and cherries. The crate can be bought for 300 credits, it was originally 500 but Marm talked me down. 25 plants wont be able to fuel the kitchen for the entire round, they'll either need to buy multiple crates or still rely on botany.
Sometimes chefs want to cook with more variety, and botany can't provide (or simply fails to provide, looking at you 17 million pound marijuana brick).
Heres an example of what you can get in a crate
Used the create crate command, plants were in it correctly.
Bought some crates via cargo, all the plants were in there. I then turned all those plants into seeds, and tried to sell …
=> Adds the "Ingredient Crate"

code/modules/research/designs/autolathe_designs.dm
Moves the RCD, RPD, RCL, and industrial welder out of the lathe hack requirement.
Also shifts around where they physically are in the code, to reflect changes.
Currently, hacking lathes is just a must for engineering, despite it actually being against SOP, for basic engineering tools. Not to mention that the hack mostly gave illegal/lethal items, then just.. also engineering equipment? Sort of odd imo, so this PR aims to change it.
Compiled ran, checked if the stuff was there, it was.
:cl:
tweak: RPD, RCD, RCL, and industrial welder no longer need the lathe to be hacked to print.
/:cl:
=> the lathe hack wire now really only gives illegal stuff

code/__DEFINES/mob_defines.dm, code/datums/datumvars.dm, code/game/objects/structures/crates_lockers/closets.dm, code/modules/martial_arts/martial.dm
See title
You keep martial arts even as different mob because it's stored in the mind, so if you get revived again as a human you keep said arts. It's not good to encourage people to file github reports over things that aren't issues because the author of an older PR didn't consider an edge case. 
Tried it in game
:cl:
spellcheck: improved clarification on having martial arts as a non carbon
/:cl:
=> improves clarification on having martial arts as a non carbon

code/modules/mob/living/carbon/human/species/_species.dm
If you have slowdown that is not a multiple of 0.5 BEFORE PAIN SLOWDOWN, your slowdown from items is reduced DOWN to the nearest multiple. 0.3 becomes 0, 0.9 becomes 0.5. Our speed system really only takes 0.5 multiples well.
If you have slowdown that is not a multiple of 0.5, that leftover value is saved, and used to adjust when the threshold of pain slowdown is.
If you have 0.25 leftover slowdown, your slowdown is set to 0, but pain slowdown begins at 20 for you, instead of 40. 
If you have 0.625 total slowdown, it is rounded to 0.5, and then you get pain slowdown begining at 30.
Pain slowdown will ONLY provide 0.5 slowdown to you below 40 damage. This means, having a 0.25 slowdown item, acts like a zero slowdown item till you hit 20 damage, then it would act more like a 0.5 slowdown …
=> Fractional slowdown under 0.5 no longer slows you, reduces damage neded to slow instead

code/__DEFINES/sight.dm, code/modules/antagonists/changeling/powers/digitalcamo.dm, code/modules/mob/living/silicon/ai/ai_mob.dm
Digital Camouflage now makes you fully invisible to the AI, as well as untrackable
Complete meme ability rn, not useful in the slightest. Congrats on your worse agent ID that marks you off as being KOS if the AI realizes what's up. It's bad, so let's make it better.
Peak shot me this idea over discord and I thought it was pretty good, having counterplay against the AI as an antag is nice, but not too powerful if sec is doing well (especially in an antag like cling that's so melee focused). This will force up sec and the AI to change up tactics a bit, and it should be fun for both parties. Won't help you too much in an ai steal situation though, you can't hide thermite and tool sounds. 
"oh no where did mr cling go :("
:cl:
tweak: Digital Camouflage now makes you fully invisible to the AI …
=> Digital Camouflage now makes you fully invisible to the AI

code/modules/surgery/limb_reattach.dm
Limbs can be attached to bodies again
Previous PR worked a BIT too well and prevented all limbs from being attached to bodies
Two clients did the thing
:cl:
fix: limbs can be attached to bodies again
/:cl:
=> limbs can be attached to bodies again

code/modules/reagents/chemistry/recipes/slime_extracts.dm
Blacklists the dragons breath and drop of immortality bottle from slime reactions
In my defense I did block the stimulating steak before in the pr.
Pie is left, it's purely healing, those pills can be got from space, and its not much diffrent from botany plant memes.
confirmed they were blocked
:cl:
tweak: Blacklists some problimatic bottles from silver slimes
/:cl:
=> Blacklists some other bottles from silver slimes

code/datums/uplink_items/uplink_general.dm, code/game/objects/items/weapons/storage/uplink_kits.dm
Stechkins now come with 2 spare mags when purchased from the Uplink.
Stechkins are outclassed by literally every other uplink lethal. Having more chances to reload is good. Maybe people will now use the "standard syndicate firearm" a bit more.
1. Used my god given rights with the 2nd amendment to buy me some guns.
2. Got some extra ammo with it.
:cl:
tweak: gave the uplink stechkin purchase two extra magazines
/:cl:
=> Uplink Stechkins Now Come with Two Spare Mags

code/game/objects/items/robot/robot_items.dm
Technically fixes #18895
This PR prevents medical borgos from picking up mice or diona nymphs. Now they pet them instead. This used to put them into the borg and they could not be dropped.
No more undroppable mice
1. Spawn as med borg
2. pet mouse
3. pet nymph
4. profit!
:cl:
fix: Fixed being able to pick up mice as medical borg
/:cl:
=> allows med borgs to pet nymphs and mice

code/game/machinery/adv_med.dm
This PR cleans up the printouts from the body scanners used in medical and by ERT teams with handheld scanners. Changes include reorganizing and moving elements around, eliminating unnecessary readings, splitting organs into two tables and cleaning up the information listed.
It makes the reports easier to read, which aids medical personnel in examining the reports for critical information. 
Tested against various damage types and conditions to test for appearance and functionality. 
:cl: Burza and CinnamonSnowball
del: Removed some printout information to reduce clutter
tweak: Divided organ table into two tables for internal/external and fixed their format
tweak: Reorganized various elements and tweaked the format of the report
/:cl:
=> Improved body scanner printouts

_maps/map_files/RandomRuins/SpaceRuins/mechtransport.dmm
Completely remakes the old mechtransport.dmm space ruin.
This new updated version notably features:
>Mech modules such as a diamond drill, repair droid, honk voice module, mech sleeper.
>Buttons that must be pressed in order to open the bunker doors underneath the airlocks with the loot inside.
>Sheets of materials, to be specific - 5 Diamond, 15 Silver, 10 Titanium, 15 Uranium, 20 Metal, 20 Glass.
>A mech power core
>Tiny fluff sheet of paper that gives some information on the background of the ship.
>Oxygen wall lockers to grab any emergency spares
It also removes the GPS that was previously on the ship. This is because the ship now notably contains a mech power core which can prove quite useful back on station. I did not want people to spawn as an Explorer roundstart and then …
=> Remakes the Mech Transport space ruin

code/datums/spells/shapeshift.dm
fixes #21330 
forcemove should always be used over direct location checks, or weird shit (such as seen in the issue) can and will happen
Saw buckled was properly being unset
:cl:
fix: Fixes some weird teleporting with lesser drake shapeshift
/:cl:
=> fixes some lesser drake weirdness

code/modules/atmospherics/machinery/components/unary_devices/thermomachine.dm
Changes the `New` proc to `Initialize` for thermomachines.
Fixes #21328. No, really.
Took apart a thermomachine. Also used it to see if its functionality was unchanged.
:cl:
fix: Thermomachines give the proper amount of wire when disassembled.
/:cl:
=> Switch thermomachines to Initialize

code/game/objects/structures/aliens.dm
Makes resin doors only try to open on bump rather than on crossed as well
This causes janky situations where the door will instantly close when you try an open it, as well as weird closing delays
This also called parent as well, which is extremely funny
Ensured this game was 1% less russian
:cl:
fix: Resin doors no longer "lock up" in weird situations 
/:cl:
=> makes resin doors a tad less jank

code/_globalvars/misc_globals.dm, code/game/gamemodes/objective.dm, code/game/gamemodes/steal_items.dm, code/modules/power/engines/supermatter/supermatter.dm
You can no longer get the supermatter sliver objective if the station does not have a supermatter.
This mostly just means if the station doesn't have one roundstart (IE sheppard TM), you will not get the objective.
It also means if the supermatter has decontaminated, one will get the objective.
While the option to order a shard in order to get a sliver is perfectly valid, and a good way to get around engineering being nerds and doing an ~~overcomplicated~~ awesome 7000 EER setup that they will kill you if you dare try to touch, an antagonist should not be *forced* to order a sliver, especially since the crystal is going to delam after the sliver is cut, less it is put in a setup. One should also not get the objective if the shard doesn't exist at all in the first place.
:cl:
tweak: You …
=> You can no longer get the supermatter sliver objective if the station does not have a supermatter

code/game/machinery/doors/airlock.dm
This PR changes logic when you attack airlock with opened panel(screwdriver). Instead of displaying UI it will act as you touched it with closed panel, means you will try to open it(or close).
When you're playing with airlocks in fight you really do not want those pop up advertises with cable lists on half of your screen.
Also this will allow you to close/open airlocks with opened panel with your hand instead of bumping them with your body.
Compiled
:cl:
tweak: Airlock's opened panel no more forces you to see cables when you touch it with your hand/other object
tweak: Examining airlock with exposed wires now will open wires panel if you're staying next to it
/:cl:
=> Airlock wires panel no more pop ups when you're trying to open it

code/modules/clothing/suits/armor_suits.dm, code/modules/mob/living/simple_animal/hostile/illusion.dm
Illusions now copy sec huds, tracking implants, chemical implants, and mindshields, so it actually fools anyone that has a security hud.
Stealth armor illusions now have 20 hp.
Stealth armor no longer can trigger while the user is invisible.
Illusion creating abilities are fun, but people rarely fall for them as the security hud quickly gives away that the illusion is a fake. Now, security should have a harder time telling illusions, though there are still tells.
Reactive stealth armor was a bit too good, and has been nerfed. Illusions now have only 20 hp, so a single laser will take it out., but a punch or 1 baton will not.
Reactive stealth armor no longer can trigger when the user is invisible from it, to reduce the tankiness already created by the illusions.
Shot myself off a titanium …
=> Improves illusions, nerfs stealth armor

code/game/mecha/mecha.dm
Fixes an issue where the "Connect to port" alert would be thrown and not cleared (when exiting the mech while standing on the port). Also gives the user the "Disconnect from port" alert when they exit and re-enter the mech, as previously this could cause the mech to get stuck because you cannot disconnect from the port without the alert.
fixes: #21344
Bug bad.
Enter a ripley (As a skrell)
Stand on top of a connector port, alert shows up
Exit mech, alert disappears
:cl:
fix: Alert for mech connecting to an atmos connector is now properly cleared/thrown
/:cl:
=> Alert for mech connecting to an atmos connector is now properly cleared/thrown on exit/enter.

code/game/gamemodes/cult/cult_items.dm, code/game/machinery/OpTable.dm
PR prevents pulling anchored items along while veil shifting. This could occur if you are pulling something, then anchor it down, so the pulling state does not get updated until you move. Examples include, but are no limited to pulling a vendor and wrenching it down, and screwdriving a window from the floor and back again.
fixes: #21364
Bug bad.
Be a skrell cultist.
Drag a vendor and attempt a veil shift, it works.
Wrench the vendor down and attempt to veil shift, no dice.
:cl:
fix: You can no longer pull anchored objects along while veil shifting.
/:cl:
=> Prevents pulling anchored objects along while veil shifting

code/game/machinery/OpTable.dm
Fixes a bug where you cannot unbuckle a mob that's buckled to a operating table when it is depowered. 
fixes: #21281
Bug bad.
Buckle a skrell to an operating table
Unbuckle a skrell from an operating table
:cl:
fix: Mobs can now be unbuckled from an operating table normally even when it is depowered.
/:cl:
=> Allows unbuckling mobs from an operating table even if it is depowered.

code/game/objects/structures/tables_racks.dm
When tables are flipped, their items will go flying in the right direction, instead of at the user. Unflipping a table will actually make the table look like its supposed to.
Fixes #21362, Fixes #12312
https://github.com/ParadiseSS13/Paradise/assets/91113370/94f83cda-ea4f-4ea1-8668-78539aedc9c0
See above
:cl:
fix: Flipping a table will send the items on it flying in the right direction
fix: Unflipping a table will now make the table look correct
/:cl:
=> Fixes a few issues with flipping tables

code/game/gamemodes/objective.dm
Changes the debrain objective to not require you to be not dead for it to be a success. I found this while doing other objective changes, and it seemed weird, so this PR is up to change it. This does not make the debrain objective glorious death compatible.
All other steal and assassinate objectives don't require the user to be alive, they usually have survive objective anyways if they want the full greentext. No where in the debrain objective does it state that you have to be alive.
Stole a brain and died, greentexted
:cl:
tweak: Being dead and having your debrain objective complete will now count as a success
/:cl:
=> Debrain objective no longer requires being not dead

code/modules/library/library_equipment.dm
Similar to lockers, but they pick up only books roundstart
Maps have this stuff mapped in, but it doesnt actually work
Tested on a map, unfortunately I was not able to test the random books because of lack of an SQL database, so I went with what lockers used.
Only a mapping feature, nothing player related
=> Bookcases now pickup books on roundstart

_maps/map_files/RandomRuins/SpaceRuins/moonoutpost19.dmm, _maps/map_files/RandomRuins/SpaceRuins/onehalf.dmm, _maps/map_files/RandomRuins/SpaceRuins/spacebar.dmm
Fix wall bump nudges on several space ruins. Continuation of #19875 burndown.
:cl:
fix: APCs are correctly positioned on space ruins.
/:cl:
=> Ruins: fix APC bumps on moonoutpost19, onehalf, spacebar.

_maps/map_files/RandomRuins/SpaceRuins/debris1.dmm, _maps/map_files/RandomRuins/SpaceRuins/derelict3.dmm, _maps/map_files/RandomRuins/SpaceRuins/dj.dmm
Removes stacked lattices for several space ruins. Continuation of https://github.com/ParadiseSS13/Paradise/pull/19875 burndown.
<details><summary>Images</summary>
</details>
:cl:
fix: Remove stacked lattices on several space ruins.
/:cl:
=> Fix stacked lattices on debris1, derelict3, and dj ruins.

code/game/gamemodes/wizard/raginmages.dm
wizards now dust instead of gib on raging. This means that when a wizard dies with the wand belt for the 800th time, crew doesnt polymorph the rest of the wizards. In the past gibbing blocked belt and similar items, but with modern gibbing it does not.
Updates the dust threshold to new crit, so sleepy time wizards don't gib when they sleep for half a second with no crew in sight while healing.
See above.
(yes I posted it after a raging round, no, I did not die to wand belt, yes, this happens each raging round I admin. wizards that were wand of deathed also didn't gib so it was extra funny and bad.)
:cl:
tweak: Wizards have learned of nt's dust implants, and now have imitated it into a spell form for raging wizards.
tweak: Wizards now dust at deep crit, vs sleeping at under 0 dusting
/:cl:
=> wizard dusts now on raging, now that gib no longer deletes items as constistantly

_maps/map_files/RandomRuins/SpaceRuins/blowntcommsat.dmm
Removes many stacked lattices and fix APC pixel shift. Continuation of #19875 burndown.
<details><summary>Images</summary>
</details>
:cl:
fix: Fixed lattice and wall bump positions on tcommsat space ruin.
/:cl:
=> Ruin: fix lattices and APC nudge for blowntcommsat.

code/game/objects/structures/false_walls.dm
Fixes false wall smoothing, false walls near each other will look like real walls now. Similar PR to #21369
This is a very old bug, and an annoying one.
https://github.com/ParadiseSS13/Paradise/assets/91113370/663f2e41-045c-460e-9eb2-a66b0dcf3369
See above
:cl:
fix: False walls near each other will smooth properly
/:cl:
=> Fixes false wall smoothing

_maps/map_files/MetaStation/MetaStation.dmm, _maps/map_files/cerestation/cerestation.dmm, _maps/map_files/cyberiad/cyberiad.dmm
Atmospherics access has now been added to the two SM chamber doors on Meta, Cere, and Box. Delta SM chamber doors already had both atmospherics and engineering access. Door placement and all other features remain the same, only the door access should have changed. 
The SM is heavily based in atmospherics while the air alarm that controls the chamber devices and access to the chamber is locked to atmos techs, preventing them from fully setting the engine up or correcting issues in a pinch without hacking through one or two doors. This standardizes the chamber access across all of the maps to align with delta.
Access change, maps are unchanged visually
:cl:
tweak: Tweaked the SM chamber doors to now include atmospherics access
/:cl:
=> Adds Atmos Access to SM chamber doors

_maps/map_files/generic/centcomm.dmm
Removes two spawners on top of indestructible windows. Continuation of #19875 burndown.
:cl:
fix: Removed unnecessary window spawners on Centcomm
/:cl:
=> Centcomm: remove stacked windows/spawners.

_maps/map_files/cerestation/cerestation.dmm
Title - just puts the zippo on their desk with the holy water.
Consistency with the other maps & a cool lighter.
Loaded in, observed, saw it on the table
:cl:
add: The chaplain now has a zippo lighter on the NSS Farragus (CereStation)
/:cl:
=> Gives the chaplain a black zippo lighter on CereStation

_maps/map_files/Delta/delta.dmm, _maps/map_files/MetaStation/MetaStation.dmm, _maps/map_files/cerestation/cerestation.dmm, _maps/map_files/cyberiad/cyberiad.dmm
This is my first mapping PR if everything goes wrong when it comes to conflicting this I'm sorry
- Adds the janidrobe to all custodial closets, and the lawdrobe to all IAA offices. Items in janitor closets shuffled around to make room, and the lawdrobes have replaced hot drinks machines where available (meta office lacked one and the others all have a hot drinks vendor 1-3 tiles away from the door in the hallway so they weren't needed.)
New drip, once added, available at shift start rather than having to build a vendor to get it
Cyberiad: 
Custodial closet
Internal Affairs
Cerebron:
Custodial closet
Internal Affairs
Kerberos:
Custodial closet
Internal Affairs
Farragus:
Custodial closet
Internal Affairs
Boot server, go to area and check
:cl:
add: Janidrobe and Lawdrobe now mapped in to all …
=> Maps the janidrobe and lawdrobe in to all stations

_maps/map_files/cyberiad/cyberiad.dmm
Engineering Space tile Fix
Fixes a problem that occured after merging https://github.com/ParadiseSS13/Paradise/pull/21071
Space is bad
:cl:
fix: Fixed engineering having a space tile.
/:cl:
=> Engineering Space tile Fix

code/datums/spells/alien_spells/plasma_weeds.dm
Xenomorphs can no longer make resin in pipes
No. You should not be able to place resin anywhere in pipes.
Confirm it worked
:cl:
fix: Xenomorphs can no longer make resin in pipes
/:cl:
=> Xenomorphs can no longer make resin in pipes

code/_onclick/drag_drop.dm, code/_onclick/hud/action_button.dm, code/_onclick/hud/screen_objects.dm, code/game/alternate_appearance.dm, code/game/dna/dna_modifier.dm, code/game/gamemodes/miniantags/abduction/machinery/experiment.dm, code/game/machinery/OpTable.dm, code/game/machinery/Sleeper.dm, code/game/machinery/adv_med.dm, code/game/machinery/cryopod.dm, code/game/machinery/suit_storage_unit.dm, code/game/mecha/mecha.dm, code/game/objects/items.dm, code/game/objects/items/bodybag.dm, code/game/objects/structures.dm, code/game/objects/structures/crates_lockers/closets.dm, code/game/objects/structures/kitchen_spike.dm, code/game/objects/structures/morgue.dm, code/game/objects/structures/stool_bed_chair_nest/bed.dm, code/game/objects/structures/stool_bed_chair_nest/chairs.dm, code/game/objects/structures/tables_racks.dm, code/modules/atmospherics/machinery/components/unary_devices/cryo.dm, code/modules/food_and_drinks/kitchen_machinery/gibber.dm, code/modules/food_and_drinks/kitchen_machinery/smartfridge.dm, code/modules/mob/living/simple_animal/bot/mulebot.dm, code/modules/mob/living/simple_animal/slime/slime_mob.dm, code/modules/mob/mob.dm, code/modules/paperwork/photocopier.dm, code/modules/recycling/disposal.dm, code/modules/tooltip/tooltip.dm
This PR addes drag effects for every atom in the game. Usually if you drag something, it would activate it's Click method.
Have you ever seen your interface not reacting to your clicks? You press RMB to shoot that vampire, but instead nothing happends? You press three times on your stechkin in suit slot to pull it out? Your ability just ignores your mouse pressing? 
I thought i am the only one with that problem before due to my ping/packetloss/whatever, but im not
So, whats happening then? For some reason sometimes game registeres your clicks as DragNDrop
You can see it there https://youtu.be/jUhmdNjufwA
There is few items/objects that can be interacted with drag and drop, others just do NOTHING. That is what happening most of the time. You press your mouse, possibly move it on one pixel …
=> Laggy DragNDrop fix

code/modules/reagents/chemistry/reagents_holder.dm
Removes an inexplicable `- 30` from the proc call that gradually shifts the temperature of carbon mobs' internal reagent holder towards their body temperature.
In practice, fixes water freezing into ice *inside your stomach* shortly after drinking (as well as Cider freezing into Applejack and one other alcoholic drink reaction).
As someone who occasionally drinks water from the water coolers around the station for the miniscule RP value, it's.. kind of silly to eventually hear the magic fizz and get notified that the water has now frozen into ice *inside my body*, which should be fairly hot and definitely not at the freezing point of water.
I've done some research to make sure this wouldn't break something important, and discovered that basically only carbon mobs actually metabolize …
=> Makes reagents adjust their temperature towards your actual body temperature

_maps/map_files/cerestation/cerestation.dmm
Adds an extra tile of length to Farragus Medchem. Also pushes maints down one tile.
Currently, medchem on Farragus is very tiny and you have a 1 length path that you can walk through. Making medchem not tiny is a simple but effective QOL change for chemists.
Note: The crate has been moved two tiles up, but this screenshot was made before that
Went into DreamMaker, compiled maps and checked if my changes went through.
VSC had a compiling issue and didn't show half the map.
:cl:
tweak: Farragus Medchem is now slightly bigger.
/:cl:
=> Makes Farragus MedChem slightly bigger

_maps/map_files/Delta/delta.dmm
Adds cargo technician lockers to cargo.
All other stations have these lockers. Besides being a place to put personal items they also include the cargo headset.
No testing, YOLO
:cl:
add: Kerberos Cargo now has CT lockers.
/:cl:
=> Delta: Add cargo technician lockers.

_maps/map_files/MetaStation/MetaStation.dmm
Changes the 4 Exile lockers into Personal Lockers in the Expedition Room
Exile lockers were unintentional
Loaded up metastation (the greatest station available on paradise) and saw that all the lockers were personal and not exile lockers
:cl:
fix: Metastations expedition room lockers are now personal lockers and not exile lockers.
/:cl:
=> Fixes Metastations Expedition Room lockers

_maps/map_files/MetaStation/MetaStation.dmm
Resets security duffels on Meta to not have custom names and descriptions or attempt to fill them with surgical tools (?)
This stuff shouldn't be in these and I assume `newlist` is a terrible idea anyway.
Started rounds on Meta before and after, 
:cl:
fix: Meta: removed improperly customized security duffels
/:cl:
=> Meta: Remove security dufflebag varedits.

_maps/map_files/Delta/delta.dmm, _maps/map_files/MetaStation/MetaStation.dmm, _maps/map_files/RandomRuins/LavaRuins/lavaland_surface_ash_walker1.dmm
replaces basetype belts with toolbelts on some maps
these are useless, and this seems to just be a minor pathing mistake
compiled 
:cl:
fix: replaces basetype belts with toolbelts on some maps
/:cl:
=> replaces basetype belts with toolbelts on some maps

_maps/map_files/generic/Lavaland.dmm
Removes a 1px nudge from labor camp APC.
Map conformance. Continuation of #19875 (technically now #21390) burndown.
:cl:
tweak: Labor camp APC positioning was off
/:cl:
=> Fix an unnecessary pixel offset on gulag APC.

_maps/map_files/shuttles/emergency_narnar.dmm
Fix window/wall stacking on cult emergency shuttle.
Map conformance. Continuation of https://github.com/ParadiseSS13/Paradise/pull/19875 (technically now https://github.com/ParadiseSS13/Paradise/pull/21390) burndown.
:cl:
tweak: Fix stacked walls on cult emergency shuttle.
/:cl:
=> Fix wall/window stacking on Nar'sie shuttle.

code/datums/elements/waddling.dm, code/game/area/areas.dm, code/modules/power/gravitygenerator.dm
Adds a new cmag interaction to the gravity generator.
When someone uses a cmag on a gravity generator, after about ten seconds or so, the gravitational dampeners will activate in a way that...isn't quite right.
Everyone in range of the generator will slip on first activation, and then begin to waddle, with no other downsides.
Like all cmag interactions, this is incredibly easy to fix, just requiring soap or some other cleaning implement to be applied to the gravity generator.
Once a gravity generator has been cmagged, there's a five minute delay before the generator can be cmagged again, to prevent spamming.
I think it's good for a few reasons:
- It's a pretty harmless prank, as waddling just animates your walk animation. There isn't even squeaking.
- It applies equally to everyone; …
=> Allows for the gravity generator to be cmagged.

code/modules/mob/living/carbon/carbon.dm
Refactors the proc to be more readable, removes some weird behavior that frankly doesn't make sense
Yes
Made sure it works according to logic and sense
:cl:
del: Muzzles and facehuggers don't block vomiting anymore
/:cl:
=> Tweaks the `vomit()` proc

code/game/machinery/vendors/departmental_vendors.dm
Donuts now cost 40 credits to buy, or 200 credits for a box of 6, so a discount in bulk. This is cheaper than bread tubes, to reduce complaints about the pr for now.
Food from vendors should cost money. Security has 24 donuts roundstart, 48 if you hack the vendors.
On cyberiad, at least, there are also *3* free donut boxes on the table of the security meeting room, but I'm not going to make a map edit over donut boxes, I'm not that drastic.
Security, like any other department, should have to pay for food, or rely on finding more limited supplies such as maints, or the generosity of hydro / the chef giving out free food, or surgery for a nutriment pump. Donuts with frosting also heal security, making it extra fun. Double so when security is one of the bigger cargo spenders, on guns and …
=> Donut tax. Security now must pay for donuts from the security vendor.

code/modules/mob/living/carbon/human/human_movement.dm
This PR changes a BIT new pulling slowdown feature. Now slowdown will be applied only if pulled object has gravity.
This looks better for people using magboots in space. Magboots are designed to be used in space but currently they force you to have gravity and have slowdown. After the change you will move as fast as before in space, if you're pulling object also in space.
compiled
:cl:
tweak: Pulling slowdown now applied only if pulled object has gravity
/:cl:
=> Pull slowdown tweak

code/modules/reagents/chemistry/reagents/medicine.dm
Alternative to https://github.com/ParadiseSS13/Paradise/pull/21319
If we dont want meth debuffed, lets bring stimulative_agent which is in adrenal implant and changeling adrenaline ability to meth level stamina regeneration
0 TC infinite meth should not be better than 8 TC 3 uses adrenal implant
:cl:
tweak: Stimulative agent(adrenals bio-chip and changeling adrenaline ability) now heals 40 stamina per cycle(was 20)
/:cl:
=> Buffs stimulative agent

code/game/machinery/OpTable.dm
Previously after getting put onto a surgery table you'd be in a resting state even after unbuckling. This PR makes it so that the surgery table behaves like a bed, so after you unbuckle you will stand up (Unless you were resting previously).
A decent amount of people have been complaining about how annoying it is that you remain resting even after you unbuckle from the surgery table, this PR aims to make it a little less tedious.
Be a skrell and lie down on the surgery table.
Unbuckle, and I automatically get up.
Buckle another skrell to the surgery table.
Attempt to start a surgery and succeed.
:cl:
tweak: Operating table no longer forces you to rest after unbuckling
/:cl:
=> Operating table no longer forces you to rest after unbuckling

code/game/objects/items/devices/chameleon_counter.dm
chameleon counterfeiter no longer gives illegals 3, gives illegals 1 instead.
Too cheap. We did this with the chameleon flag back in the day.
When tech webs come out, and we divide all illegals stuff into levels, it should probably be standardized to illegals 2 items 1-3 tc, illegals 3 items 4-9 TC, and illegals 5 items (ebow) 10+ TC items.
I tweaked numbers.
:cl:
tweak: chameleon counterfeiter no longer gives illegals 3
/:cl:
=> chameleon counterfeiter no longer gives illegals 3

code/modules/shuttle/emergency.dm
Golems no longer cause hijacks to fail
If you are using golems for hijacking and you're not intent on hacking (or you're the ai) you'll need to get all your golems to walk out an airlock, which is obviously not good.
If you're not a hijacker you can just spam a bunch of golems at a hijacker, which is less problematic but also not great as they are a ghost role, and are pretty much have no value
It compiled
:cl:
tweak: Golems no longer cause hijacks to fail
/:cl:
=> golems no longer cause hijacks to fail

code/modules/research/xenobiology/xenobiology.dm
Makes the Slime Blueprint's colortint slightly lighter.
Current version makes areas an eyesore, and actually impossible to differentiate between ironwalls/plating in maintenance.
Before
After
Bear in mind this is in fully illuminated rooms, imagine doing this in maintenance. Please imagine it because I did not get a picture for that case and I do not wanna test again for the sake of making you not imagine how it looks like.
:cl:
tweak: Slime Blueprints apply a lighter color filter on rooms.
/:cl:
=> Slime Blueprints have a nicer colortint

code/modules/projectiles/ammunition/energy_lens.dm
Buffs cyborg emitters, now only requires 350 energy per shot and has a 1 second delay between shots, rather than 2
This ability is bad
I don't really need to elaborate much. This 50 point ability gives only engineering cyborgs a ranged option, this ranged option has a whopping 15 dps and the most obvious sound attached to it and you're still probably taking it because malf AI has three abilities that actually do something.
Well, maybe this ability will actually do something sometime, you're still probably going to want to use stun arm in every situation, but it's an ok flyswatter for unathi trying to screw up your core.
I probably didn't need to test this but I did, it's 2 value changes
:cl:
tweak: Cyborg emitters fire twice as fast and take less energy per shot
/:cl:
=> buffs cyborg emmitters

code/game/objects/structures/crates_lockers/largecrate.dm, code/modules/supply/supply_packs/pack_engineering.dm
Adds the ability to order gas canisters with cargo, in all the normally accessible flavours! Plasma, CO2 and N2O are all  very high in demand by traitors and crew alike, so the prices of those are of course raised.
This also adds a destroy() to large crates.
In case of someone destroying the counter and all of the atmos air production gets nuked, this allows for small restocks so the station won't die a slow choking death.
Went to cargo, ordered some canisters of Oxygen and Plasma. 
Used my god-given right of the second amendement to open the crates up.
Watched the world burn.
:cl:
add: adds the ability to buy gas canisters from cargo
tweak: large crates drop their contents when they are destroyed
/:cl:
=> You can now order gas canisters from cargo

code/modules/reagents/chemistry/recipes/pyrotechnics.dm
Limits the size of water-potassium explosions to "30 TNT". Previously, it had no cap. See "Images of changes" for the difference this makes.
We have a whole host of cool chemicals to blow shit up like black powder, nitroglycerine, but none of it matters if the chemicals you can pour out of a chemical dispenser straight can still make explosions nearly as large or just as large simply by using larger beakers. Making massive explosions should take either actually using chemistry to make the cooler explosion chems or toxins to make toxin bombs (which have their own downsides). Water + Potassium grenades will still not be _terrible_ for causing significant damage, but if you want to run around with a bunch of pocket maxcaps you'll have to make the more complicated chemicals.
Before: (300 …
=> Puts a cap on the size of Water-Potassium explosions

code/game/objects/structures/safe.dm
The safe now calls the proper proc 2 minutes after granting the visual effects to ghosts, rather than calling the same proc again every 2 minutes.
While security is always assaulting the crew, thats usual. We don't need to tell ghosts about security after the vault raid is done.
Triggered the event, waited 2 minutes for the effect to go away, waited 2 more minute for it to come back.
Think I messed this up when I renamed the procs in the past PR? Not sure.
:cl:
fix: The thermal drill no longer grants the visual effect to deadchat every 2 minutes
/:cl:
=> the thermal drill no longer grants the visual effect to deadchat every 2 minutes

code/game/machinery/doors/windowdoor.dm, code/game/objects/structures/grille.dm, code/game/objects/structures/railings.dm, code/game/objects/structures/tables_racks.dm, code/game/objects/structures/window.dm
Fixes an oversight with https://github.com/ParadiseSS13/Paradise/pull/21209 that lets all simplemobs do extreme damage to windows when they could not previously.
Fixes an issue where smashing happens regardless of intent.
mice shouldn't be able to do 75 damage to windows.
:cl:
fix: Fixed an issue that let simplemobs do extreme damage to windows
fix: Fixed help intent animals smashing things accidentally
/:cl:
=> Fixes oversight in simplemob smashing code

code/game/objects/structures/door_assembly.dm
Stops the duplication of airlocks.
Also makes polarized airlocks not freak out when built with reinforced glass
Bug bad. Item duplication worse.
Fixes #21452 
Fixes #21479
Shot an airlock, repaired airlock to full afterwards. No duplicate airlocks.
Constructed an airlock from scratch with reinforced glass, polarized it, checked if anything weird was going on.
:cl:
fix: Fixed airlocks duplicating themselves
fix: Fixed polarized airlocks not freaking out when built
/:cl:
=> Fixes duplicate airlocks spawning

code/modules/antagonists/traitor/datum_traitor.dm
Fixes the logic behind glorious death, now properly removes the escape alive objective 20% of the time when your objectives are martyr compatible.
People not getting an escape alive objective a lot of the time isn't what was intended.
Didn't test for a single !
:cl:
tweak: people now properly get no escape objective assigned
/:cl:
=> Fixes a problem with logic for glorious death

code/modules/mob/living/carbon/carbon.dm
Fixes a bug, when you go ghost with throw mode on or get mob deleted, your mouse pointer no more stays in throw mode
Bugs bad
Fixes https://github.com/ParadiseSS13/Paradise/issues/21418
:cl:
fix: Throw mode cursor doesnt follow you in ghost world anymore
/:cl:
=> Wenting ghost or getting mob deleted with throw mode on now making mouse pointer default

code/modules/antagonists/traitor/datum_traitor.dm
Fixes people not getting escape objectives when they should
This is unintended, whoops (Also makes the code easier to follow)
Had my ears blown out by the traitor greeting 
:cl:
fix: You should always get an escape objective when you previously should have
/:cl:
=> Fixes people not getting escape objectives when they should

code/game/objects/structures/railings.dm
`body_position` is a `/mob/living` variable. We need to make sure the mob is living before running `IS_HORIZONTAL(M)`.
Runtime fix:
```
[2023-06-29T16:13:59] Runtime in code/game/objects/structures/railings.dm,84: undefined variable /mob/camera/aiEye/var/body_position
proc name: CanPass (/obj/structure/railing/CanPass)
src: the railing (/obj/structure/railing)
src.loc: space (64,32,2) (/turf/space)
call stack:
the railing (/obj/structure/railing): CanPass
B.R.A.D (AI Eye) (/mob/camera/aiEye): get_spacemove_backup
B.R.A.D (AI Eye) (/mob/camera/aiEye): Process_Spacemove
B.R.A.D (AI Eye) (/mob/camera/aiEye): newtonian_move
B.R.A.D (AI Eye) (/mob/camera/aiEye): Moved
B.R.A.D (AI Eye) (/mob/camera/aiEye): setLoc
B.R.A.D (AI Eye) (/mob/camera/aiEye): setLoc
[CKEY] (/client): AIMove
[CKEY] …
```
=> Fixes a runtime with railings

code/modules/events/event_container.dm
Event manager now adds events to GLOB.event_last_fired.
Without doing this, it just checked how long ago the start of the round was for duplicate events, and thus had no impact, when events start rolling at say, 30 minutes, then 50 minutes, at 50 minutes this would remove... 150 points, rather than 200 as expected, and this only gets worse as the round goes on.
Event manager now uses a percentage system, over a flat point deduction system. This means events with a higher rate get deducted a higher value, and smaller events that are not one shot don't get basically treated as a one shot, just become rare.
The way the duplicate event weight is calculated is 
which translates to 60 minutes as 36000. This means a duplicate event after 30 minutes has a 50% weight, a duplicate event at 45 …
=> Makes duplicate events have less weight work / work based on percentage now.

code/game/gamemodes/cult/cult_mode.dm
Security getting free reign to spam IKs and WTs at the 2 remaining cultists is never fun. This makes it so if the cult falls below half of the rise number (5% on highpop, 10% on lowpop), the cult will revert to the "risen" state and a special announcement will be played disincentivizing the murder by random crew and lethals by security. Any advice on specific wording in the announcement is appreciated, along with potential changes to the numbers that the cult reverts at.<br><br>
The percentages mean there is a 15% on highpop and 20% on lowpop difference between rising and falling, so these announcements can't be easily spammed (unless some metaclique is deconverting themselves and converting themselves, but that's an admin problem).<br>
Specific wording for any of the stuff in this PR is …
=> Cults can now "fall" when their numbers are too low.

code/datums/components/ducttape.dm, code/game/machinery/computer/ai_core.dm, code/game/objects/items.dm, code/game/objects/items/devices/aicard.dm, code/modules/mob/living/silicon/ai/ai_mob.dm
This PR makes it so when applying tape to a Carded AI, the built in camera no longer functions until that tape is removed OR its placed back into its Core.
On request by Qwerty, the carded AI can remove the tape after a 2 minute resist. If the card is moved in any way during this, it stops the removal of the tape. There is a notice for the AI that it is being removed and an audible tape removal sound effect for everyone nearby.
Currently, the AI steal objective for any antag is the worst objective to get as an antag. Not only do you have to worry about borgs being told locations through binary chat from the AI but also anyone at a camera console can just sit down and callout the location of the holder, refreshing it without delay. This issue in turn makes it so most antags either wipe the …
=> Tape removes AI inbuilt Camera while Carded

code/game/gamemodes/miniantags/abduction/abduction_gear.dm, code/modules/antagonists/changeling/powers/epinephrine.dm, code/modules/antagonists/vampire/vampire_powers/vampire_powers.dm
Vampire's rejuvenate, Changeling's epinephrine overdose and Abductor agent's combat mode ability all now will instantly make you stand up when stunned, instead of making you eat a do_after while crawling to stand up again.
This was the case before crawling:tm:, the use of these abilities makes them severely limited when you're getting spammed with a stunbaton due to the slowdown of crawling.
1. Spawned myself as all three
2. Looked at the code to find out that you switch vest mode in the abductor computer???? okay.
3. Batonged myself and used the ability afterwards, stood up.
:cl:
tweak: Vampire rejuvenate, Changeling epinephrine overdose and Abductor Agent combat mode ability will make you stand up instantly rather than having to crawl for a bit first.
/:cl:
=> Vampire/Changeling/Abductor anti-stuns remove all stuns instantly

code/modules/mob/living/carbon/human/human_defense.dm
See title, you just couldn't reflect projectiles while horizontal
Carp isn't very good, and this kinda feels like rubbing salt into the wound by making them even worse to batons, this should hopefully make carp a little less terrible
Emitter go BRRRT
:cl:
tweak: Carp now reflects projectiles while horizontal
/:cl:
=> carp now reflects projectiles while horizontal

code/game/objects/items/weapons/melee/energy_melee_weapons.dm, code/game/objects/items/weapons/twohanded.dm, code/modules/mob/living/carbon/carbon.dm
A thrown body at a dsword user will no longer disarm it. The thrown body will now be brutally stabbed and left for dead on the floor.
Dswords will now return an attack on parry. While this means someone still needs to chose over offense or defense, it should make it clear that batoning the esword user may not be a good idea. Thrown items can also be reflected (might take this off actually. Will have to make it not runtime, will do tomorow
Eswords reflect energy projectiles on PARRY. They do not passively do it, they must block to do it.
Esword and dsword have fell off. A gun is cheaper and hurts much more. As well, while active block is more engaging, for a weapon trying to attack people, it has issues. Trying to dsword someone? Disarms will push you back, often into a wall. Baton? Better …
=> Dswords now return melee attack on parry.  Eswords reflect lasers on parry. Throwing bodies at a dsword user may not work well

code/datums/uplink_items/uplink_general.dm
Increases to cost of the Powerfist from `8TC > 10TC`
The Powerfist is a LITTLE bit strong for an 8TC item. This should smooth out its value a tiny bit.
:cl:
tweak: increased the powerfist's TC cost from 8TC to 10TC.
/:cl:
=> Powerfist Now Costs 10TC

code/modules/supply/supply_packs/pack_security.dm
Allows you to buy two box's of tranquilizer shells for 400 credits in cargo.
A very niche, but none replenishable shell for the shotgun. Meth is very common and a majority of answers to it is lethals. While I think lethals are still viable and good to handling threats like these, the shotgun's whole niche is being a specialist weapon that can be used to solve problems with its shell types. Tranq shot is a hard counter to meth/stimulants and should be more utilized in game.
yes
:cl:
tweak: You can now order tranquilizer shells from cargo in the security tab
/:cl:
=> Tranquilizer Shells can be ordered from Cargo

code/datums/weather/weather_datum.dm, code/datums/weather/weather_types/solar_flare.dm
Solar flare now only affects station level instead of all players that can see space (Including those on CentComm). This does mean solar flares no longer affect other space Z-levels.
Fixes: #21282
Bug bad
Spawned a skrell in CentComm.
Spawned a skrell on station.
Spawned a skrell on a space ruin.
Skrell on station gets burnt, others do not.
Smells like napalm, tastes like chicken.
:cl:
fix: Solar flare now only affects station level
/:cl:
=> Solar flare now only affects station level

code/game/objects/items/devices/megaphone.dm
Objects on the same tile as a megaphone user can now hear them. This means if you use a megaphone and you're recording yourself with a tape recorder, or using an intercom it can hear you now on the same tile.
Fixes two bugs in one
Megaphone worked in both cases
:cl:
fix: Megaphones now work properly with intercoms or tape recorders on the same time as the megaphone
/:cl:
=> Objects on the same tile as a megaphone user can now hear them

code/game/dna/dna_modifier.dm
This fixes the labels on disks that are copied from the DNA modifying console. 
Makes sure that disks are labeled properly as intended.
Copied SE of subject and labeled a disk.
Exported disk and examined the label.
:cl: Burza and Contrabang
fix: Fixed disk labeling
/:cl:
=> Fixes labeling disks when using DNA Modifier 

code/modules/mob/living/carbon/carbon.dm
Fixes missing preposition in vomiting on an empty stomach message
Good English is good
N/A
:cl:
spellcheck: Fixed missing preposition
/:cl:
=> Minor SPaG fix in vomiting section

code/game/machinery/iv_drip.dm, code/game/objects/structures/crates_lockers/crates.dm, code/game/objects/structures/stool_bed_chair_nest/wheelchair.dm
Removes pull slowdown from IV drip stands, wheelchairs, and trash cart crates
Most other common objects with wheels were excluded, why shouldn't these
Spawned thingy in, pulled thingy around
:cl:
fix: Fixed some objects with wheels still having pull slowdown
/:cl:
=> Adds some overlooked objects to pull slowdown exclusion

code/controllers/subsystem/tickets/tickets.dm
Makes the tickets table actually capture the `awho` column properly
This is good
```json
[{"ckey":"affectedarc07","rank":"Host & Maintainer","afk":26.5},{"ckey":"cornmycob","rank":"Game Admin","afk":0.5}]
```
This is bad
```json
[{"ckey":"warriorstar","rank":"Runtimes Access","afk":46},{"ckey":"warriorstar","rank":"Runtimes Access","afk":46},{"ckey":"warriorstar","rank":"Runtimes Access","afk":46},{"ckey":"warriorstar","rank":"Runtimes Access","afk":46},{"ckey":"warriorstar","rank":"Runtimes Access","afk":46},{"ckey":"warriorstar","rank":"Runtimes Access","afk":46},{"ckey":"warriorstar","rank":"Runtimes Access","afk":46}]
```
A moment of silence please for the **7 months** of scuffed data.
Made ahelp with 2 people on test server, logged properly.
=> Fixes tickets not logging awho properly

code/modules/assembly/voice.dm
Removes an extra "is" from the voice analyzer's description.
It's it's good to not have double words.
I think this is a fair case of "it compiles"
:cl:
spellcheck: Removes a spurious "is" from the voice analyzer description
/:cl:
=> Fix typo with voice analyzer

code/game/objects/structures/false_walls.dm
Fixes the examine text of false walls to match that of regular walls (Fixes #21286).  Also makes false walls instantly smashable by simplemobs that have the ability.  Since false walls are weak, even mobs that can't normally smash through walls (like blobbernauts) will be able to smash through them (Fixes #21503).
Created some walls, examined some walls, smashed some walls.
:cl:
tweak: False walls are now instantly smashable by simplemobs that can smash through structures
fix: Examine text of false walls to match regular walls
/:cl:
=> Fixes false wall examine text and makes them instantly smashable by simplemobs

code/game/objects/structures/crates_lockers/closets/secure/cargo_lockers.dm, code/modules/clothing/under/accessories/accessory.dm
Adds a "stable supply medal" to Quartermaster's locker.
Name and description are possibly subject to change.
Itt's odd Quartermaster never had one! While not being a head, he still is in charge of a (sub)department. And while yes, supply _technically_ is part of service, HoP is not around there nearly enough to have opinions strong enough to give out any medals. 
Spawned in as QM, opened my locker, played around with the medal a bit, took above screenshots
:cl:
add: QM's locker now starts with a supply medal.
/:cl:
=> Adds Supply Medal

code/modules/antagonists/changeling/powers/mutations.dm
Reduces the amount of perf organic space suit injects 0.4 -> 0.2
Right now you get double the perf added per processing tick than you can metabolize, leading to changelings being unable to speak after using this ability for extended periods, not being able to talk as an antagonist that theoretically focused on RP and disguises isn't a great place to be.
Proper way to do this is probably with a status effect but this does work
Chilled out with the suit, watched my oxy not drop and still had the ability to speak
:cl:
tweak: Reduces the amount of perf organic space suit injects 0.4 -> 0.2, You no longer get excess perf by using organic space suit
/:cl:
=> Reduces the amount of perf organic space suit injects

code/game/objects/items/weapons/RCD.dm
This PR allows players to click on the compressed matter cart with an RCD, instead of needing to pick up each individual cart and add it to the RCD. Also changes logic to allow players to reload an RCD when the extra ammo would go over the maximum capacity.
Loading RCDs is tedious, and this has annoyed me ever since I found out you can install pKA mods by clicking on them.
Loaded and used an RCD a lot, made sure borgs couldn't also reload their RCDs.
:cl:
tweak: RCDs can be reloaded by clicking on a cartridge with it.
/:cl:
=> Clicking on RCD carts with an RCD loads it.

code/modules/mob/living/living_defense.dm
Being splashed or rised by water now wakes you up. Spiritual port of yogstation13/Yogstation/pull/19476. It will not wake you up from sleeping gas. It removes sleep at 20 seconds per 100 units
There are no real clear ways of clearing out someone being sleepy besides just spam hugging them. This is a nice alternative
Tested sleeping in sleeping gas and in a shower, didnt wake up.
Slept in a shower without sleeping gas, woke up real quick.
:cl:
tweak: Being splashed by water will help wake someone up
/:cl:
=> Being splashed with water now wakes you up

code/game/machinery/vendors/generic_vendors.dm
**Cigarette vendor changes:**
- Moves cigars and robust golds out of contraband - it sucks that you need to hack a vendor to have access to perfectly valid flavor items. They are NOT contraband. They are not money-efficient either. They are just cool. If design team decides they are too accessible like that, I can rack up their price, altrough I don't think it's necessary.
- Moves zippos out of contraband, halves their amount and gives them a price (80 credits) - pretty much same reasons as above, having to hack the vendor for fluff gear sucks.
- Moves rolling papers into contraband - now those ARE fit for contraband. They are for rolling weed and, more rarely, your own cigarettes. Average joe won't use them - only drug dealers and botanists will.
- Adds Carp Classics, halves Robusts …
=> Cigarette vendor tweaks

code/__HELPERS/mob_helpers.dm, code/game/machinery/doors/airlock.dm, code/modules/antagonists/changeling/powers/contort_body.dm, code/modules/mob/living/living_status_procs.dm
Ups the chemical cost from 5 to 25 chemicals (People were swapping this mid combat, which seemed to not be super great)
Takes 2 seconds of staying still to go under an airlock now, windoors can still be gone under easily, both because I can't find a good way to apply a timer there and because most windoor locations are a lot less favorable for break in vs an airlock
Clings with contort form are on a high layer now, so they don't fit under stuff like conveyer belts which can spammed nonstop
Bit overtuned, mostly fine but people using it in active combat has been a little much
I hate semidense objects
:cl:
tweak: Contort form costs 25 chems to use compared to 5
tweak: Contort form takes an extra 2 seconds to go under doors now
tweak: Contort form costs can no longer fit under conveyers and …
=> Contort body day 1 changes

code/__HELPERS/trait_helpers.dm, code/modules/mob/living/carbon/carbon.dm
Changes how fire rolling works, it no longer weakens and stuns you, now you can roll and crawl while also being able to use things.
Hard stun bad, 7 year mechanic that nobody bothered to update bad, less restrictive movement good, more fun and not one sided status effects good.
set self on fire, rolled while on fire and moved, amazing
:cl: Octus SabreML
tweak: Putting yourself out via rolling while on fire no longer stuns you, its now just a knockdown
/:cl:
=> Fire rolling no longer hardstuns you because its not 2016 and is current year

code/game/objects/items/control_wand.dm, code/game/objects/items/weapons/storage/belt.dm
Adds Cargo Office Access to JaniKeyring.
Makes it so the JaniKeyring fits in the Janitor's belt.
This was intended in the original PR.
Oversights are bad.
:cl:
fix: Fixed the access oversight with the JaniKeyring in Cargo.
fix: JaniKeyring now also fits in the Janitor Belt.
/:cl:
=> Adds Cargo Office Access to JaniKeyring + Fits in JaniBelt

code/modules/clothing/spacesuits/hardsuit.dm
see title
Origin tech of engineering 6 and syndicate 4
Lots of new explorer players now, one of the loot items they can get are blood red hardsuits, they can't legally have these on station so it's sad they can't use it for syndicate tech to help out RND, or engineering tech (it has a jetpack) to get rnd to engineering 7 if cargo are being useless.
Deconstructed one
:cl:
tweak: Syndicate hardsuits now have an origin tech of engineering 6 and syndicate 4
/:cl:
=> Gives the syndicate hardsuits some origin tech

code/modules/antagonists/changeling/powers/tiny_prick.dm
deletes hallucination sting
Yeah so this has been a longtime coming.
This ability isn't remotely useful, you instead use this to sting everyone in a hallway because it's 10 chemicals and then basically just grief with it. I've tried reworking this but lemme be honest, it ain't worth it at all. I cannot thing of a good thing to say about this ability so into the sun with it.
the actual utility from this ability is to sit around and watch someone get randomly hardstunned followed by a good armblading, you may have noticed this sucks.
It compiled
:cl:
del: Hallucination sting
/:cl:
=> removes hallucination sting

code/__DEFINES/status_effects.dm, code/datums/diseases/advance/symptoms/deafness.dm, code/datums/elements/earhealing.dm, code/datums/status_effects/debuffs.dm, code/game/mecha/equipment/weapons/weapons.dm, code/game/objects/items/weapons/grenades/flashbang.dm, code/modules/antagonists/changeling/powers/shriek.dm, code/modules/mob/living/carbon/alien/humanoid/humanoid.dm, code/modules/mob/living/carbon/alien/larva/larva.dm, code/modules/mob/living/carbon/human/human_mob.dm, code/modules/mob/living/living.dm, code/modules/mob/living/living_status_procs.dm, code/modules/mob/living/simple_animal/bot/honkbot.dm, code/modules/mob/mob_status_procs_base.dm, code/modules/reagents/chemistry/reagents/medicine.dm, code/modules/surgery/organs/ears.dm, code/modules/surgery/organs/organ_internal.dm
This PR brings ears in line with how other organs deal, and heal from damage. They can now die like any other organ, and won't work until healed via surgery if they do die.
Additionally, temporary deafness has been changed to be a status effect.
Consistency in how organs work is good, and being able to actually see how damaged ears are when scanning is also good. 
The justification for removing natural healing is that even though ears do take (invisible) damage, you would never notice because by the time you get un-deafened most of the damage you'd already taken has healed up.
Made sure things that dealt ear damage still did, killed the ears of a few skrells, then fixed them back to make sure they worked again. Also made sure I didn't accidentally make everyone deaf permanently.
After the …
=> Ear Organ Refactor + Deafness is a status effect

code/game/objects/items/weapons/holy_weapons.dm
fixes #21332 
Stuff that gets dropped should be able to be picked up again, especially if it was able to be picked up in the first place
I cut off my arm and then put it back on
:cl:
fix: You can pick up a dropped mining dark blessing
/:cl:
=> fixes mining armblades being unable to be picked up after being dropped

code/game/machinery/OpTable.dm
Refactors and cleans up a bunch of operating table code, fixing some bugs as well as removing doubled-up feedback introduced during the switch to buckling, an unnecessary inventory closing, and the old and bugged methods (grab-clicking, verb) of putting people on operating tables.
Also removes the `attack_hulk()` proc override, which removes another case of doubled feedback and makes operating tables take a whopping ***2*** hits to destroy by hulks instead of just 1.
Outdated code bad, bugs even worse
Tested all of the fixes
Made sure you still can't put non-carbons or multiple carbons at once on operating tables, that abductor tables still inject chemicals properly, that you can't buckle people while incapacitated, etc.
:cl:
fix: Fixed being unable to buckle someone to an operating table …
=> Cleans up and fixes some bugs in operating table code

code/game/turfs/simulated/floor/misc_floor.dm
Fixes a copy paste for a proc override on floor catwalks. You're not supposed to be able to place wires right through catwalks,
Fixes an oversight.
Tried placing wires on catwalk floor. Attempted before the fix too just to see what the current behavior was.
:cl:
fix: Wires can't be placed through floor catwalks
/:cl:
=> Block wires from placed under floor catwalks

code/game/gamemodes/malfunction/Malf_Modules.dm
Gives a new ability to malf ais, repair cyborgs, costs 20 CPU, two uses per purchase
Clicking on a cyborg that's got broken armor will resurrect it and fix it's components, but will not heal it to full HP, if it's HP is very low, it will fail to resurrect. 
If the cyborg has armor, this functions as an aheal and will fully revive the cyborg.
Takes 10 seconds on use, if the cyborg is moved during this time, the ability will fail and the use will still be deducted. You can only fix one cyborg at a time. This ability is obvious to anyone in the room when used.
blah blah blah malf ai is the bargain bin of antags, not good in the slightist.
A lot of the frustration that comes from malf ai is that they really only have like, the one way to effectively fix borgs, being nanopaste from a mediborg, …
=> gives malf ais the ability to repair their cyborgs

code/game/objects/items/weapons/twohanded.dm, code/modules/mob/living/carbon/carbon.dm
People holding toy dswords are no longer immue to people being thrown at them / no longer do 100 damage to the person thrown at them.
Clowns no longer die using a toy dsword.
Toys should not kill people very fast when people are thrown into them.
Clowns should not kill themselfs with a toy. I know this was controversial in the past, but frankly it's funnier when clowns can actually do their pranks, vs dying when they try to prank someone with a dsword.
Threw people at the clown with a toy dsword, slashed people with a toy dsword.
:cl:
fix: Toy Dswords no longer kill people thrown at people holding one.
fix: Clowns no longer die using a toy dsword.
/:cl:
=> Toy dualswords no longer fucking kill the crew when thrown into, clowns no longer die to toy dsword.

code/modules/surgery/organs/organ_external.dm
Fixes two oversights involving sharp weapon delimb chance.
How it works right now is that the chance of delimbing per attack with a sharp weapon is half of the damage that the attack deals to the limb itself. This is a problem because when you reach the limb's damage cap, half or more of your attack's damage is then distributed to other limbs. An esword attacking a head that is at its damage cap of 75 health will not have a 15% chance of delimbing, but rather a 7.5% chance or lower depending on what organs the damage is split between. 
The second oversight is that there was a 5% chance to deal internal organ damage when attacking with a brute weapon. This had the effect of halving the damage of the hit and dealing negligible damage to a random internal organ. It now deals half the damage …
=> Droplimb Chance Tweak

code/modules/reagents/chemistry/reagents/drugs.dm, code/modules/reagents/chemistry/recipes/drugs_reactions.dm
Crank heals more stamina and gives less confusion. 25 to 40, with confusion halfed.
Pump up will get you out of stam crit each cycle, but uh, still not great.
Meth now heals 30 stamina per cycle instead of 40.
Bath salts is now craftable realistically with reworked economy, requiring salt instead of mugwort.
Arsnep now gives50% stamina resist instead of 30%. This may make it see use. Maybe.
Surge gets a buff as lets be real, ipcs need it.
None of the other drugs are used.
Crank doesnt heal enough stamina, and confusion is hard to work with.
Pump up already decays fast enough.
Arsnep needs to be combined with other drugs, and could be done better with just meth + crank + hydro for more managable downsides.
Bath salts are perfect.
But require mugwort so you more or less needed to buy money …
=> Buffs most stamina drugs. Nerfs meth stamina ***SLIGHTLY***

code/__DEFINES/dcs/signals.dm, code/__DEFINES/misc_defines.dm, code/datums/components/defibrillator.dm, code/game/objects/items/weapons/defib.dm, code/modules/mob/living/carbon/human/human_life.dm
- Fixes like three different bugs with the way defibrillators inflicted brain damage (previously not only did it completely overwrite old brain damage even if new value was *lower*, it also scaled *backwards*, and was even subject to a macro expansion bug that made the actual value go fuck knows where)
- Fixes a runtime that happened when you tried to defib a heart-removed slimeperson due to some some presumably pre-newcrit code where slimeperson cores (brains) used to double as hearts
- Reorganizes code slightly so it's more readable
Less runtimes is nice, defibs also should not be *reducing* brain damage
Put a skrell into crit so it got some brain damage; defibbed it very quickly to see it didn't gain any brain damage as expected, but also didn't lose any; killed the skrell again and …
=> Fix some defib bugs

code/modules/antagonists/changeling/changeling_power.dm, code/modules/antagonists/changeling/datum_changeling.dm
Currently the changeling UI element for chemical storage updates before they generate chemicals causing it to be one step outside of what it should be (this can be easily observed by comparing it with the status panel, which does not suffer from this error).  This PR fixes this issue and also makes it so the UI element updates whenever a power takes it's cost, making it immediately accurate.
More accurate UI
Grew and ungrew lots of armblades and used my eyeballs.
:cl:
tweak: Changeling storage now immediately updates when powers take chemicals
fix: Issue where the changeling chemical storage UI element would display incorrectly
/:cl:
=> Fixes inaccuracy in changeling chemical storage UI element.

code/datums/components/defibrillator.dm, code/game/machinery/computer/aifixer.dm, code/game/objects/structures/morgue.dm, code/game/verbs/suicide.dm, code/modules/mob/living/carbon/brain/brain_update_status.dm, code/modules/mob/living/carbon/human/human_update_status.dm, code/modules/mob/living/silicon/robot/robot_update_status.dm, code/modules/mob/living/stat_states.dm
Adds some missing checks on some revivals to prevent the revival of people (silicons included) who have used the IC/OOC "I'm done playing my character" button, but didn't choose to ghost and leave their live body behind.
Also adds a check to entirely prevent changelings from committing suicide. With their weird sort of existence in and out of death (as well as the weird sort of IC thing that suiciding is), it feels like giving them the unique ability among antagonists to commit suicide without catching a jobban is a little strange, and would probably have security ahelping about them every time. Easier to just put a hard stop there.
Suicide, as stated before, is by design a mechanic that is supposed to remove you, the player, from re-entering the game as your character permanently. While …
=> Adds some missing checks for suicides on revivals, prevents clings from suiciding

code/game/machinery/vendors/wardrobe_vendors.dm
Removes the price for galoshes, belts, gloves, and hats in the janidrobe.
Fixes https://github.com/ParadiseSS13/Paradise/issues/21587
The Janidrobe was added with the intent of charging for extra spares for an item.
However the free roundstart items were removed in a follow-up PR as the locker was refusing to close due to too many items. This PR makes the essential items free in the janidrobe.
New uniforms still cost as expected.
Looked at vendor prices
:cl:
fix: Fixed janitors having to pay for galoshes, belts, gloves, and hats
/:cl:
=> Fixes janidrobe charging for essential equipment

code/modules/reagents/chemistry/reagents/water.dm
Fixes a variable shadowing bug where adding a vaccine reagent to a container with a different vaccine reagent would merge the incoming vaccine's data onto itself, doing nothing in practice.
Extremely minor annoyance begone
Gave meself a cold and a flu, cured both, synthesized their respective vaccines, poured both into a single container, infected a monke with the same diseases, gave the monke a sip of the good juice, confirmed that both diseases vanish (rather than only the first added).
:cl:
fix: Merging vaccine samples into a single multivaccine now works properly.
/:cl:
=> Fixes vaccines not merging properly

code/datums/looping_sounds/looping_sound.dm, code/modules/client/preference/preferences.dm, code/modules/client/preference/preferences_volume_mixer.dm
Adds the delta alarm to the sound mixer. The alarm itself was added in https://github.com/ParadiseSS13/Paradise/pull/21174. 
Also, fixes some weirdness that would sometimes occur while changing a slider with a decreasing sound added in the aforementioned PR.
If we're concerned about sound mixer bloat, I can also convert this to a pref toggle.
I've heard a few people complaining about how shrill the sound effect is, particularly after listening to it for a long time. It's cool and atmospheric, and it does indeed get quieter on its own, but it'd be really nice if it could be quieted a bit more (or silenced outright, for people who want that).
Also, the channel was still coded in, it was just never added. I think that might have been an oversight?
:cl:
tweak: The delta alarm now has a slider …
=> Adds delta alarm to mixer

code/game/objects/effects/landmarks.dm
- Fixes random costume landmark spawners sometimes spawning nothing due to unnecessary subtyping resulting in an accidental subtype that had nothing defined on it
- Removes the random extra egg that spawned with the chicken costume, resulting in eggs showing up in some undesirable locations
More costumes good, less non-costumes bundled with costumes spawning in places that cause issues also good
It compiles, chicken suit no longer spawns with an egg, no more empty `/landmark/costume` subtypes should exist
:cl:
fix: Fixed random costume spawners sometimes spawning nothing
del: Chicken costume spawner no longer spawns an additional egg
/:cl:
=> Fixes a couple issues with random costume spawners

code/game/objects/items/weapons/implants/implant_stealth.dm
Stealth implant boxes no longer drop cardboard when destroyed.
Fixes #21705
Activated stealth implant to summon the box. Shot the box and destroyed it. Box did not drop cardboard.
:cl:
fix: Stealth implant boxes no longer drop cardboard when destroyed
/:cl:
=> [Fix] Stealth implant boxes no longer drop cardboard when destroyed

code/game/objects/effects/meteors.dm, code/modules/events/event_container.dm, code/modules/events/meteors_event.dm
Meteor events now use severity *2 + rand(0, severity) waves, leading to more meteors on average than before.
Meteor waves are now severity +rand(1, severity) meteors, leading to more meteors on average now.
The major meteor pool now contains meaty ores and xenomorph ores rarely. These have human organs in them, or xeno organs.
We already have traders with xenomicrobes (much less space ruins), so this will not be an issue
The weight overall of major meteors has been rebalanced, with the big meteor weight GREATLY lowered.
Due to the above, major meteors now has a weight of ZERO, scaling at 10 per engineer. This means a shift with no engineers will not be subjected to this, and a 6 engineer crew now having a weight of 60, same as a 6 engineer crew now.
Also radioactive meteors have a much …
=> Makes meteor events more consistant, with major meteors being more deadly.

code/game/objects/items/toys.dm
The syndicate balloon now has a special suicide act, which makes you float into the air. The sound is the same one the ash drake uses when it launches. It drops everything except balloon, and the balloon is vaporized. Balloon thieves are now 100x more dangerous.
Adds more fun to the game
(slightly outdated, clothes and stuff are left on the ground now). 
https://github.com/ParadiseSS13/Paradise/assets/91113370/3bb90189-98bc-49f6-9b15-9b744dc1179a
See above, also tested with contractor balloon
:cl:
add: Syndicate balloons now have a special suicide action
/:cl:
=> The syndicate balloon now has a special suicide action

code/__HELPERS/text.dm, code/modules/mob/living/carbon/human/human_examine.dm, code/modules/mob/living/carbon/human/species/_species.dm, code/modules/mob/living/carbon/human/species/unathi.dm
Makes articles on examine more consistent, fixing (for example) `a ash walker`, while making one less snowflake check for unathi (did you know they're pronounced "you-nah-thee"? I didn't until 20 minutes ago).
Better grammar, especially in examine bodies, is good. This change means we won't have to worry about special-casing any other species down the line in this check.
:cl:
fix: Ash walkers will now use the proper article in their examine text.
/:cl:
=> Adds article override to make examine text more consistent

code/modules/mob/new_player/new_player.dm
Puts an option to set region right on the main menu.
People have had 20ms ping reductions using these. We should be encouraging it.
I clicked it
add: Added a main menu option for selecting a server region.
/:cl:
=> Makes the existence of regions a little more obvious

code/modules/mob/living/carbon/human/species/_species.dm, code/modules/mob/living/carbon/human/species/diona_species.dm, code/modules/mob/living/carbon/human/species/machine.dm
Fixes that weird bug where you'd sometimes get "He is missing his ." when you examine someone. 
Bugs are bad and being able to tell what's missing is good.
Took the above screenshot.
:cl:
fix: Fixed "He is missing his ." showing up on examining someone with missing limbs
/:cl:
=> Fixes an issue with examining

code/modules/clothing/glasses/engine_goggles.dm, code/modules/clothing/glasses/glasses.dm, code/modules/clothing/head/helmet.dm, code/modules/power/engines/singularity/singularity.dm, code/modules/power/engines/supermatter/supermatter.dm
Meson helmets, meson goggles, and the other goggles with meson modes now use traits instead! Also removes unnecessary vision_flags and invis_view from the goggles since those are applied via the trait also.
Getting rid of istypes() when we have a trait for it is good!
Meson helmets protect from the SM now. Meson glasses still protect from the SM. 
engineering scanner goggles now only protect on their meson mode, as expected.
Atmos t-ray scanners do not protect from the SM anymore, as expected.
Meson Eyes protect you from the SM.
Looking through walls still works as expected with the meson_vision
:cl:
fix: The meson vision helmet now works properly again.
fix: Engineering scanner goggles now only protect from the SM on their meson mode.
fix: Atmos t-ray scanners do not protect from the SM …
=> Migrates meson stuff FULLY to traits

code/controllers/subsystem/SStimer.dm
Throws an error along with whatever proc a timer was trying to call if there's no object attached to it
ok so we've been getting an absolute mass of runtimes like this: ``Runtime in SStimer.dm,550: Cannot read null.type``
it's attached to a subsystem so this pretty much gives us zero help in figuring out what exactly is causing the issue. If the object is null now, we'll get the proc it was trying to call and then will be able to work backwards from there 
We don't know what's causing the issue, so I can't really think of a way to test this
NPFC
=> Attempts to allow for timers attached to no objects to be diagnosed

code/modules/mob/living/simple_animal/parrot.dm
This PR stops headsets from spawning with parrots. Note that Poly's implementation retains the eng headset. Fixes https://github.com/ParadiseSS13/Paradise/issues/21632.
Crew should not be able to obtain departmental headsets, especially sec's, just by using flaptonium or slime extract.
Relatively small change, no testing other than CI.
:cl:
del: Non-Poly Parrots no longer spawn with a random departmental headset.
/:cl:
=> Do not spawn parrots with headsets.

code/datums/outfits/plasmamen_outfits.dm
See title
I chalk this up to likely being an error. There's no reason to restrict detective plasmamen from spawning with a bowman headset. 
Compiled, ran, joined as a detective plasmaman
:cl:
fix: Detective plasmamen now spawn with a bowman headset
/:cl:
=> plasmamen detectives now spawn with bowman headsets

code/game/mecha/mecha_parts.dm
Removes the unused type `/obj/item/circuitboard/mecha/pod`, since it appears to be a remnant from space pods, and is not used anywhere.
Removing dead code or unnecessary object types is good for code quality.
Successful compilation after removal. Double-checked to ensure path wasn't present in non-station maps.
Dead code removal, no changelog.
=> Remove obsolete pod mainboard.

code/modules/mob/typing_indicator.dm
Mutes can now show that they are emoting
Mutes can still Emote, so, they shouldn't be blocked from Emote Typing Indicator
Be mute, try to say, try to me
:cl:
fix: Mute people can show Emote Typing Indicator
/:cl:
=> [FIX] Mute people can show Emote Typing Indicator

code/modules/events/brand_intelligence.dm
https://github.com/ss220-space/Paradise/pull/1343
Brand Intelligence leader now cares if it can be disassembled.
Fighting the virus is disassembling, not destroying vendors.
I HOPE IT WORKS HERE TOO
:cl:
fix: Brand Intelligence leader now cares if it can be disassembled.
/:cl:
=> [FIX] Brand Intelligence will live in refillable vendor

_maps/map_files/RandomRuins/LavaRuins/lavaland_surface_ufo_crash.dmm, code/game/gamemodes/miniantags/abduction/machinery/experiment.dm
Remove Jokerge trap, where you can enter the experimentor, but can't leave it. At all. Forever.
If it doesn't work, it shouldn't open and close doors on you.
Spawn it, stat 1, can't enter
:cl:
fix: UFO crash site chamber no more enterable. Jokerge trap is no more
/:cl:
=> [FIX] UFO crash site chamber no more enterable

code/game/dna/mutations/mutation_powers.dm
Fixes #21465. 
This change adds a `mutation#deactivate` override for `mutation/grant_spell/remoteview` that nulls any active remoteview target and resets the camera view for `mob/living/carbon/human`s.
Per #21465, previously, deactivation of the remoteview gene while its effects were active (thus shifting the camera to center on another mob) would result in the camera remaining stuck on its centered mob, without any way to reset the view. With this fix, the camera view is reset upon gene deactivation of remoteview.
From commit b3880e5,
1. I loaded a local copy of the server and joined as a geneticist.
2. I gave myself two mutadone pills with `spawn mutadone`.
3. I created a subject with `spawn human/monkey`, choosing the base type.
4. I fed the subject monkey one of the mutadone pills, …
=> Reset camera upon remoteview gene deactivation (#21465)

code/game/machinery/doors/airlock.dm
Fixes a bug where one could open shocked doors without being immune to shocks.
Shocked doors now can shock someone twice as often, however it's unlikely this will come into play unless someone puts a belt in front of the door.
A bug that happened when we changed electricity stuns, is that there was ways to open a shocked door without shock immunity, by performing certain inputs on a door.
Now, if you try to open a shocked door on the "don't kill people too fast cooldown" it will refuse, unless one has insulated gloves.
If a door is shocked, you should need to depower it or get gloves.
Ran into / clicked on doors fast with and without gloves.
:cl:
fix: Fixes being able to open doors while they are shocked without gloves.
/:cl:
=> You can no longer cheese open shocked doors

code/datums/log_record.dm, code/modules/projectiles/projectile_base.dm
Logs stamina damage in the log viewer
Stamina damage is pretty important now, good to know if someone is in stamcrit or not
(The cyan is stamina damage)
~~Found out that stamina damage isn't properly logged for the first strike because of sequencing in the projectile code (In practice this will only really affect the detectives revolver and beanbags, as every other weapon that deals straight damage + stamina is going to put you far into stamina crit, still gotta find a solution though)~~
ok should fully work now
Joy
:cl:
tweak: Stamina damage now appears in admin logs
/:cl:
=> stamina damage logging

code/modules/antagonists/vampire/vampire_powers/umbrae_powers.dm
Umbrae's burn mode is reduced to 1.1 when cloaking. Burn wounds / IK are common, along with immolators generally means they don't need this mod to be as strong.
Shadow anchor fake recalls after 2 minutes, making the user invisible for 4 seconds, and makes an illusion for 10 seconds at the anchor. Allows for fake outs / makes this not insanely risky to use without being full power.
If / when modsuits are merged, I'll add middle click functionality to this ability and shadow step, to fake do the shadow step or anchor, for mind games.
Eternal darkness has been buffed greatly, to synergise with shadow boxing a little better, and feel a bit more worthy of being a final ability (see BBR) without being a press to win button.
The darkness is stronger, and has 2 tiles more range. The colour of the …
=> Buffs 3 Umbra powers. 

code/modules/mob/living/living.dm
Direct port of https://github.com/tgstation/tgstation/pull/68493.
When on walk movement intent, you won't bump into people, help-intent shuffle, or shove people around. 
As noted in the original PR, beyond not slipping, there isn't really much other use for walking, so this adds some reason to slow down, particularly in crowded spaces like medbay or the trader line.
Spawned in, held in my walk key, and tried to push against another mob, with nothing happening.
:cl: Guillaume Prata, Lewcc
tweak: Moving around with walk intent will now not cause you to bump or shuffle others around.
/:cl:
=> Be polite! While on walk intent, you will no longer bump into/shuffle around people.

_maps/map_files/cerestation/cerestation.dmm
Removes a handful of duplicate lattices and a window spawner over a wall in the NTR office. Continuation of #19875 burndown.
:cl:
fix: lattice and window spawner issues on Cere
/:cl:
=> Cere: fix lattice dupes and spawner over wall in NTR office.

_maps/map_files/MetaStation/MetaStation.dmm
Removes stacked wall/lattice tiles on Meta. 
Map conformance. Continuation of #19875 (technically now #21390) burndown. Note that while it looks like a tile with a transit tube has been removed, it's just now a repeat of a tile definition of the transit tube below it.
<details><summary>Changed Tiles</summary>
</details>
:cl:
fix: Fix wall/lattice stacking on Cerebron.
/:cl:
=> Meta: fix wall/lattice stacking.

code/modules/mob/living/carbon/human/species/slimepeople.dm
makes hearts be placed in slime people before brain like every other species, fixes them spawning with the crit hud
crit hud bug bad exposes clings
spawned slime with new code, no crit
:cl:
fix: people transformed into slimes / newly made slimes no longer spawn in crit
/:cl:
=> people transformed into slimes / newly made slimes no longer spawn in crit

_maps/map_files/cerestation/cerestation.dmm
Removes null varedits for `req_*_access_txt` varedits.
Map conformance. Only one of these are allowed by default, and their default value should be the string `"0"`, not null.
Ensured map and code compilation, loaded map and verified door spawns, checked logs for unexpected errors.
=> cere: remove null req_access varedits

_maps/map_files/generic/Lavaland.dmm
Removes null varedits for `req_*_access_txt` varedits.
Map conformance. Only one of these are allowed by default, and their default value should be the string `"0"`, not null. Note that this does not change the access of these airlocks. Despite being on gulag, these airlocks (the external facing ones and the prisoner-side shuttle entrance) did not (and presumably are not meant to) have any access restrictions.
Ensured map and code compilation, loaded map and verified door spawns, checked logs for unexpected errors, checked access.
=> lavaland: remove null req_access varedits

_maps/map_files/cyberiad/cyberiad.dmm
Removes null varedits for `req_*_access_txt` varedits.
Map conformance. Only one of these are allowed by default, and their default value should be the string `"0"`, not null.
Ensured map and code compilation, loaded map and verified door spawns, checked logs for unexpected errors.
=> box: remove null req_access varedits

_maps/map_files/RandomRuins/SpaceRuins/spacebar.dmm
Fix plushie carp path
it create issues, issues bad
open map editor and placed plushie back
:cl:
fix: Fix gold carp plushie path for spacebar space ruin.
/:cl:
=> Fix Plushie Path in spacebar, it cause other PR's to fail map check.

SQL/paradise_schema.sql
Adds missed migration (42-43) to the main schema file
Now you wont get sql errors on death on your local server
:cl:
fix: If you are running a local server with sql enabled: now default sql schema works correctly on player's deaths
/:cl:
=> Fix: paradise_schema missed migration

code/game/gamemodes/nuclear/pinpointer.dm
Advanced pinpointers will now point to the nearest of their selected items (for example, 2 hand teles, will point to the nearest one when recalibrated). It retains its original ability to track stuff even off z-level, but now stuff on the current z-level is prioritized. (for example, 1 hand tele on station, 1 at mining outpost. If you're on station, it will track the on station hand tele, if you're on mining, it will track the one at the mining base. If you're out in space, on not of the same z-levels, it will pick one of them randomly, saying that the backup is off-sector.)
Nukie borg pinpointers will now actually point at the nearest alive human operative, instead of that dead operatve brain on the floor.
This also makes it so advanced pinpointers won't toggle themselves off when …
=> Fixes some issues with the advanced and operative pinpointers

code/modules/mining/machine_vending.dm
Mining Vendor now spits ID on power_off
My card, no! Also someone broke the check, it used to dupe it, but I fixed it too
Put card inside, turn off power
:cl:
fix: Mining Vendor now spits ID on power_off
/:cl:
=> [FIX] Mining Vendor now spits ID on power_off

code/game/objects/items/weapons/storage/storage_base.dm
Now almost every manipulation with storage makes sound. Why should it be silent if you mousedrop it?
More consistency and less metagame-y 'features'
Shuffle shuffle shuffle
:cl:
fix: Storage shuffling sound now works for mousedrops
/:cl:
=> [FIX] Storage shuffling sound now works for mousedrops

code/modules/mob/mob_movement.dm
Now when you move, whoever had a pull on you - they lose it. Removes janky movements when the party is agressive to each other but can't break more than 1 tile away.
Moving means you want to move by yourself.
Pull, move, not more pulled
:cl:
fix: Moving breaks being pulled
/:cl:
=> [FIX] Moving breaks being pulled

code/modules/security_levels/keycard_authentication.dm
Keycard Authenticator now has 20 seconds to swipe, but requires 2 different people. Also refactors a ton of the old code, along with fixing a bug where admins would not be notified if an ERT request wasn't responded to in 5 minutes. It checks by mob, so clings cant cause any shenanigans with it.
These things are kind of frustrating, sometimes you just miss your chance to swipe and you gotta redo it all over again. To trade this off to prevent abuse, you can no longer swipe at 2 different keycard auths to get red/ert/whatever. You shouldn't be able to do it anyways, but sometimes mistakes are made in mapping.
This is what happens if you try to run over and swipe at another one.
Did a ton of swiping, running around, and waiting 5 minutes for the admin reminder
:cl:
tweak: Keycard …
=> Keycard Authenticator now has 20 seconds to swipe, but requires 2 different people.

code/game/atoms.dm, code/game/machinery/doors/door.dm, code/game/objects/structures/aliens.dm, code/game/objects/structures/inflatable.dm
Kills off a var on all atoms, last bumped
Reduces jank on xeno doors even further (i ded plz optimize memory)
I had a stroke earlier when I realized that none of the xeno doors I were clicking were opening, I then remembered it was because I slightly grazed an airlock earlier.
Last bumped is the silliest of vars, preventing you from using doors if you open an airlock by bumping on it, fuck this so much. it exists to fix a problem that shouldn't have been there in the first place AND DID NOT FIX THAT PROBLEM (this is related to the exploit I fixed earlier)
the only issue with this right now is that you can cheese open airlocks by bumping into them rather than just clicking on them, qwerty should have fixed that in a pr of his so I do not really care.
Bumped into airlocks, things (mostly) …
=> kills off last_bumped, jank reduction

code/game/machinery/recycler.dm, code/modules/recycling/disposal.dm, code/modules/recycling/sortingmachinery.dm
Adds a short cooldown on the recycler when it consumes items, as well as disposals machinery processing items in general, preventing them from playing a ton of overlapping sounds at once.
It also fixes some checks that were already there but inverted (read: broken).
When stuff has piled up in cargo disposals and someone finally pulls the lever, any poor sap close to the recycler will have their ears destroyed. This isn't really great, [as funny as it can be](https://cdn.discordapp.com/attachments/145700319819464704/1129853880008724550/2023-07-15_21-15-27.mp4) (VOLUME WARNING)
Spawned 100 pieces of paper, put them through disposals, my ears felt fine afterwards.
:cl:
tweak: Recyclers and disposals are now a lot quieter when processing a ton of items at once.
/:cl:
=> Significantly reduce volume of disposals machinery when processing a ton of items

code/datums/uplink_items/uplink_general.dm
Changes the price of the Chameleon Projector from 7 TC to 5 TC.
Honestly? The Cham Proj shouldn't be taking over a third of your TC budget. It's not a bad item, but considering where the Stealth Implant is sitting at 8 TC (which is generally superior to the Cham Proj), this item simply is not worth 7 TC when you could just spend a single more TC on the Stealth Implant. Lowering it to 5 TC should help this item maybe be occasionally relevant, as I think the only time it's really used currently is when it appears in bundles and surpluses.
It's a numbers change, but it builds.
:cl:
tweak: The Chameleon Projector now costs 5 TC instead of 7
/:cl:
=> Makes the chameleon projector cheaper

code/game/machinery/floodlight.dm
Floodlights can now only be turned on if they are anchored to the ground.
Running around with a lit floodlight in maints is silly, also it can really steamroll an unprepared shadow demon. There's some more here that I really can't remember off of the top of my head right now.
Tried to turn an unanchored floodlight on, could do it when I wrenched it down
:cl:
tweak: you can now only turn on a floodlight if it's wrenched down
/:cl:
=> Floodlights can now only be turned on if they are anchored

code/modules/surgery/surgery.dm, strings/tips.txt
Fixes a typo/oversight which let borgs keep their perfect surgery success rate after #18325 claimed they wouldn't.
False advertisement bad, I assume this change was consciously approved along with the rest of the PR, so I'm fixing the lack of it.
- Spawned in as a Cyborg
- Applied roller bed rack module to floor
- Applied Skrell to rolled bed
- Repeatedly applied laser scalpel to Skrell in a surgery procedure, starting it and canceling it after a few steps
- Noticed the occasional surgery step failure as intended
- Kept going until Skrell dead
- Declared success
:cl:
fix: Cyborgs are no longer perfect surgeons by default
/:cl:
=> Fixes cyborgs being perfect surgeons

code/game/objects/items/theft_items.dm
Fixes: #21316 where modules were deleted from drones and cyborgs who interacted with Supermatter Slivers instead of dusting them.
Cyborgs and Drones that interact with Supermatter Slivers should be dusted while interacting with a sliver with one of their modules.
Spawned in Supermatter Slivers. 
Tested multiple modules on both Drones and Cyborgs.
Checked for dusting.
Tested with regular mobs using tools.
Checked to make sure they didn't dust.
:cl:
fix: Cyborgs and Drones dusting when using modules
/:cl:
=> Cyborgs and Drones dust when interacting with Supermatter Slivers

code/game/objects/effects/anomalies.dm
Gravitational anomalies no longer throw items at people inside them as much, meaning they will be more deadly when someone is dead in the middle of it.
Gravitational anomalies from events will short out the gravity generator if not defused, meaning engineering will have to repair it. Fun for the whole family!
Flux anomalies (not from supermatter / vetus) are MUCH deadlier. You will require insulated gloves to defuse this safely. If you have a flux anomaly and you do not have gloves, my advice is to get out of there. It *will* kill you if you don't get away from it.
Bluespace anomalies will now teleport unanchored structures / machines, rather than just items passively, and increases the range of selecting things to teleport by one tile.
Pyro anomalies produced a near meaningless ammount …
=> Makes anomalies deadlier. Again.

code/modules/mob/living/carbon/human/human_mob.dm
Allows dchat-controlled mobs to fire guns.
Also adds handling for nodrop/abstract items, so admins can equip their victims with whatever they see fit.
I got a request for this, and it provides one more little thing for dchat-controllable mobs.
https://github.com/ParadiseSS13/Paradise/assets/89928798/692b1894-4862-496a-acd3-8c489900fa47
See video.
:cl:
tweak: A new option, "shoot", is available when deadchat controlling a human to fire a gun it might be holding.
/:cl:
=> Lets dchat-controlled mobs fire guns

code/game/gamemodes/miniantags/guardian/types/explosive_guardian.dm
Detonate now happens on every time of action with an object, not just touching. Pushing a bomb is not a good idea.
Detonating only by touching by HAND, and not by pulling/pushing is not good?
Place bomb, touch it, ouchie
:cl:
add: Guardian Bomb now detonate almost on every interaction with it
tweak: Gurdian Bomb can't be placed to piloted mechs and disposals due to bugs with it
/:cl:
=> [FIX/FEAT]: Bomb Guardian fixes and more DETONATE options

code/modules/surgery/organs/augments_internal.dm
Revivers heal to 10 hp rather than stopping at 0 hp.
Reviver cooldown reduced on brute, burn, or toxin healing, and healing of brute / burn doubled to 2
Let us discuss what the reviver is, and what it does.
The reviver is supposed to _try_ to heal you out of critical condition. It is something you must undergo sugery for, and take the risks and time of surgery. It should not heal you out of crit, or save you from being beaten to death, or save you in a hostile enviroment like plasma / space / fire. You also take the risk of EMP certifying your death unless someone has a handheld defib near you. It's not supposed to save you from having to go to medbay after
Now, what does it do in practice:
Fuck all, really.
It leaves you on the end of crit, struggling to heal shock if the person has any …
=> Buffs revivers, Again.

code/__DEFINES/dcs/signals.dm, code/datums/components/slippery.dm, code/datums/mind.dm, code/game/jobs/job/support.dm, code/modules/mob/living/carbon/human/human_mob.dm
The clown is now slippery, 8 second slip when they're horizontal and someone tries to walk over them
Mime now has no footsteps
Both these things work with the gimmick of the job. Mimes being silent and clowns being a little slippery (with their PDA and... well everything else). This gives a little more sillyness to the antagging side of both these roles as well, now you can do silent takedowns effectively as a mime.
Walked around, heard nothing, slipped on a damn clown!
:cl:
tweak: The clown can now slip you while lying down, 8 second slip
tweak: The mime has no footstep sound
/:cl:
=> Clown is slippery and the mime has no footsteps

code/modules/reagents/chemistry/machinery/chem_dispenser.dm
Chem dispensers now need to be anchored in order to be used.
Requiring the dispenser to be anchored prevents on the fly chem mixing and low prep smoke bombs that previously required little effort for the user
Tried to use an anchored chem dispenser: Worked
Tried to use an unanchored chem dispenser: Did not work
:cl:
tweak: Chem dispensers must be anchored to use
/:cl:
=> Chem Dispensers no longer work while unanchored

code/game/objects/items/weapons/implants/implant_stealth.dm
The stealth implant's box cooldown now begins when the box is dismissed or destroyed.
Cooldown is 10 seconds (unchanged).
The current cooldown is very inconsequential, as it starts when you SUMMON the box (press the action button). Which means you can summon the box, run into combat 10 seconds later, get shot and immediately summon another one, and run off. This will add a bit more counter-play to the stealth implant.
* Summoned the stealth implant box, then dismissed it with the action button. It went on cooldown.
* Summoned the stealth implant box, was shot and had the box destroyed. It also went on cooldown.
:cl:
balance: The stealth implant's box cooldown now begins when the box is dismissed or destroyed, instead of starting when it was summoned.
/:cl:
=> The stealth implant's box cooldown now begins when the box is dismissed or destroyed

code/__DEFINES/dcs/signals.dm, code/__DEFINES/status_effects.dm, code/datums/status_effects/buffs.dm, code/game/gamemodes/revolution/revolution.dm, code/modules/mob/living/carbon/human/human_defense.dm, code/modules/mob/living/carbon/human/human_mob.dm, code/modules/mob/living/carbon/human/species/_species.dm
When a non-head rev is deconverted by beating in the head, the message will be much bigger. They will also be granted a 10 second grace period from being attacked from someone on disarm/harm intent. You can still use help and grab intent on them. I settled on 10 seconds because when revs are deconverted, they are paralyzed for 10 seconds (paralyze is basically sleeping them, they can't see or move, and are forced to the ground.) The one exception to this is revolutionaries, they can still harm their ex-comrades. Idea from Qwerty.<br><br>
I particularly chose disarm and harm intent, and left help and grab intent because disarm and harm are the COMBAT intents, which people use when fighting. The others are left so if you still want to stab them, you can kind of, or automender them. 
Revs is …
=> Revolutionaries now have a grace periods from attacks after beating deconversion

code/game/objects/items/devices/radio/encryptionkey.dm
Gives the blueshield access security comms.
I've started a topic on the forums here: https://www.paradisestation.org/forum/topic/24207-balance-blueshield-and-security-comms/ and feedback was rather positive.
tl;dr, it would GREATLY help blueshield do their job, as believe me or not, command does a poor job at communicating threats to you.
If blueshields use them to validhunt, I advise pressing "F1" and choosing "adminhelp". It's a player issue, not a code issue.
Spawned in, used my comms, seemed to work.
:cl:
add: Blueshield now spawns with security comms.
/:cl:
=> Gives the blueshield security comms roundstart.

code/modules/projectiles/guns/projectile/revolver.dm
This PR fixes #21562. The Cursed Russian Revolver now shards the user instead of turning them into a cult ghost and deleting.
Broken items are bad
Spawned in, spawned a revolver/russian/soul, used on self, became a shard and the body inside immediately died.
:cl:
fix: The Cursed Russian Revolver now properly shards the user.
/:cl:
=> Fixes the Cursed Russian Revolver

code/datums/uplink_items/uplink_general.dm, code/game/objects/items/weapons/storage/uplink_kits.dm
Adds Fragmentation Grenades and a 5-Pack-Combo-Deal of Frags to the Uplink. 
Singular = `2TC`
5-Pack = `8TC`
Anti-personnel grenades are good. They dont breach the floor and cause minimal structural damage. This gives antagonists a nice way to cause Medbay/Bridge Hobo chaos if they need to get a target from a crowded room.
1. Bombed some skrell.
2. Loaded test server.
3. Bombed more skrell from the uplink.
:cl:
add: Added frags to the uplink.
/:cl:
=> Adds Fragmentation Grenades to the Uplink

code/modules/mob/living/simple_animal/hostile/megafauna/bubblegum.dm
Adds a check for bubblegum to not follow someone if they use a jaunter, or similar, to go back to the station
;BUBBLEGUM MEDBAY is not something I want to hear when there is no hijacker around
I really didn't have a good way to test this, but this uses the exact same logic as bloodcrawl for bubble, so it should work.
:cl:
fix: Fixed bubblegum being able to follow you back to the station
/:cl:
=> Bubblegum now can't follow people on the station

code/game/turfs/simulated/floor/plating.dm
Multiplies the amount of N2O that atmos starts with by 10.
(Sorry for the amount of files and lines edited)
Alright, let's crunch some numbers:
CO2:
9 x 50.000 = 450.000 moles of CO2
Plasma:
9 x 70.000 = 630.000 moles of Plasma
O2 & N2:
9 x 100.000 = 900.000 moles of N2 & O2
N2O:
9 x 6000 = 54.000 moles of N2O
Slight discrepancy here. N2O is very interesting because it has a high heat capacity, and is able to keep the EER down very well, with the downside of dissolving into N2 and O2 at 1400 Kelvin.
This PR makes the atmos storage start with 540.000 moles of N2O, slightly more than CO2, but still less than every other gas tank.
It's literally adding a single "0"
:cl:
tweak: The roundstart amount of N2O of atmos has been increased by tenfold
/:cl:
=> Increases the amount of N2O that atmos starts with

code/game/gamemodes/wizard/artefact.dm
Gives night vision to the scrying orb in addition to xray vision.
The wizard scrying orb now grants nightvision when held or kept in inventory, in addition to xray vision.
While xray without nightvision isn't useless, it's very difficult to see things through walls in maintenance with only the xray vision. Given that this isn't a very commonly used item in the first place, I don't see the harm in giving it some quality of life/added utility.
before
after
Two-line change, spawned in an orb, it works as-intended
:cl:
tweak: Scrying orb grants nightvision.
/:cl:
=> Scrying Orb gains Nightvision

code/game/machinery/cryopod.dm, code/game/objects/effects/portals.dm
Adds a var to check whether or not the portal should cause sparks.
A mechanic intended to remove SSD players from the round should not be sparking and potentially causing fires or other related issues.
Checked both cryo portals and normal portals, cryo no longer sparks, normal ones do.
:cl:
tweak: Tweaks the cryo storage portal to no longer spark when used. 
/:cl:
=> The automatic Cryo storage Portal will no longer spark on use

code/datums/spells/wizard_spells.dm, code/game/gamemodes/wizard/spellbook.dm, code/modules/mob/living/carbon/human/human_defense.dm, code/modules/projectiles/projectile/homing_projectiles.dm, code/modules/surgery/organs/organ_external.dm, paradise.dme
adds support for future homing projectiles, projectiles that redirect themselves towards their target as they fly.
adds a new wizard spell, homing toolbox. fires out a toolbox similar to the fireball spell. the projectile does 30 damage, ignores armour and embeds a toolbox in the target on hit. costs 1 spellpoint. honestly might be better as a staff/wand rather than a spell itself. up for change there.
fun wizard spell, adds future support for new features.
[dreamseeker_cxIUkxOdmf.webm](https://github.com/ParadiseSS13/Paradise/assets/69320440/110785f8-89b6-4aab-861c-f4ab39813bff)
compiled, made the video and image above, and checked it was in the spellbook.
:cl:
add: new wizard spell, homing toolbox
/:cl:
=> adds homing projectiles and a new wizard spell, homing toolbox

code/modules/client/preference/loadout/loadout_uniform.dm
Took three whole hours, I'm finally a coder. time to do coder things and.. I dunno, cry in a corner
this PR takes the Assistant's Formal Uniform, usually only found in the maintance tunnels, and adds it to the Loadout menu for people to start with from round start
its a fun little piece of clothing that I feel goes unappreciated a lot of the time
-Booted up private server
-Looked through Loadout menu
-Found Assistant's Formal Uniform
-Equipped it and joined the round
-Assistant's formal uniform appeared on my character
-Tears of joy
:cl:
add: Added Assistant's Formal Uniform to the Loadout menu
/:cl:
=> Adds the Assistant's formal uniform to the loadout Menu

code/datums/uplink_items/uplink_general.dm, code/game/objects/items/weapons/implants/implant_freedom.dm, code/game/objects/items/weapons/implants/implantfluff.dm
Adds a cheap one-use Freedoms implant for Traitors/Operatives.
Cost: `2TC`
Freedoms get you lethal'd. Its kinda in Space Law to allow Security to BLAST you for freedoms. But sometimes, you want ONE try to get away before getting blasted. `5TC` is a fairly steep price to pay for getting blasted with red beams afterwards.
This makes it so it hits less hard to your wallets without being insanely OP.
1. I can break these cuffs.
2. You cant break those cu-
3. You can, but only once.
:cl:
add: Adds the one-use prototype freedom implant.
/:cl:
=> Adds the Prototype Freedom Implant

code/game/objects/items/hand_item.dm
Adds a short blind + deafen to CQC slap along with a ringing sound.
Blind: `2s`
Deaf: `4s`
Judo Eye Poke and Discombobulate have enlightened me. A Security Tool shouldnt have more CC utility than a TC item.
This adds to the sheer chaos of being in melee range with a CQC user.
https://github.com/ParadiseSS13/Paradise/assets/57759731/4f292f48-751f-4e83-9560-e47bace64717
1. First, discombobulate.
2. Dazed, discombobulate.
3. Distract target, discombobulate.
4. Block his blind jab, discombobulate.
5. Ill attempt wild haymaker, discombobulate.
6. In summary, discombobulate.
:cl:
add: Adds a short blind and deafen to CQC Slap.
/:cl:
=> Adds More Discombobulation to CQC Slap

code/game/machinery/cryopod.dm
Fixes an oversight in named args from PR https://github.com/ParadiseSS13/Paradise/pull/21739
SSD portals shouldn't runtime anymore.
:cl:
fix: Fixed SSD portals failing
/:cl:
=> Fix ssd runtimes on cryo portal generation

_maps/map_files/RandomRuins/SpaceRuins/syndiecakesfactory.dmm
Removes grilles from window spawner tiles and replaces their floors with plating.
Verified map in-game.
:cl:
fix: Fixed window spawners on syndie cakes space ruin.
/:cl:
=> syndiecakes: remove grilles from window spawners.

code/datums/components/sticky.dm
Fixes an oversight where taking a camera bug off something then moving it, would make it runtime. It didnt have any effect on the game, but holy SHIT, did it spam runtime logs.
BUGS VERY BAD
Loaded in, put a camera bug on myself, took the camera bug off, moved around. Switched to a new body, pulled by old body around. No runtimes!
:cl:
fix: Fixes a bug causing moving anything that had a camera bug removed it to runtime constantly
/:cl:
=> Fixes 9000+ runtimes with the camera bug because I'm an idiot

code/game/turfs/turf.dm
Removes a bullet act from walls, that caused pulse lasers to ex_act it _before the pulse laser hit it_. This caused the wall to turn into plating often, causing the pulse laser to hit the floor instead, leading to the tile being spaced.
Ever wondered why pulse lasers turned the floor to space? So did I. I wanted to make the shotgun ammo not do that. But as I went to adjust the pulse lasers, I noticed: Walls shouldn't be spaced by pulse lasers to begin with, they *should* break, but not space.
Queue some breakpoints later, I found bullet_act on walls, called ex_act(2) on itself if it got hit by a pulse laser. Amazing. I presume this was from pre-object damage.
I'll call this a tweak, and if people *really* want, I'll only make it apply to shotgun pulse lasers, though a double call like …
=> pulse lasers no longer have shenaigins that cause the floor to breach

code/game/objects/structures/morgue.dm
Fixes morgue and cremator trays moving while in 0g
Fixes #20014 
Bug bad
PR kills bug
PR good
Before:
After:
See images
:cl:
fix: Morgue and crematorium trays now really can't move while in no grav
/:cl:
=> Morgue trays now can't move while in no gravity

code/modules/surgery/organs/augments_internal.dm
Changes Nutriment item description and typo in name
- Reworded description
- Changed nutrient to nutriment
Fixes #21569
Changed slightly confusing description wording and fixed a typo that led to the item not being properly searchable in certain menu's
Loaded test server, spawned all versions of nutriment pumps and viewed their names and description with no issues.
:cl:
fix: Fixed nutriment pump typos
/:cl:
=> NutrimentPump

code/__DEFINES/MC.dm, code/controllers/subsystem/SStimer.dm, code/modules/admin/admin_verbs.dm, code/modules/admin/verbs/debug.dm
Adds a new debug verb and timer loggin.
There is a new verb, `Debug GC Queue`, which does what it says on the tin.
You are presented with a list of the GC queues
You can then see exactly whats in the queue, and how many of that there are
Again, does what it says on the tin. Writes a `.json` file after each round with all the timers made that round.
Means I can work on solving this
And this
See above
See above
NPFC
=> A healthy addition of debug verbs

code/game/objects/items/weapons/dice.dm
Fixes #21791 (Caused by #21634)
Do not swallow dice, they are not pills and will not fix your brain damage
https://github.com/ParadiseSS13/Paradise/assets/55188452/9a1a48c2-9b0b-41ab-a220-31cda20051a6
Spawned a dice bag
Alt clicked it
Correct sound plays
Rejoiced and basked in the glory
:cl:
fix: Dice bags no longer sound like pill bottles
/:cl:
=> Dice bags no longer sound like pill bottles

code/modules/admin/admin_verbs.dm
Adds `/client/proc/show_gc_queues` to the global `admin_verbs_debug` list so that it's available to those with the +DEBUG permission. Requested by AA.
:cl:
fix: The View GC queue verb is now available to those with the +DEBUG permission
/:cl:
=> The View GC queue verb is now available to those with the +DEBUG permission

code/datums/components/sticky.dm
Updates /datum/component/sticky's code to better fit our component standards, along with adding a destroy to help clean up. Adds several more errors too if somehow something goes wrong. Adds stuff for removing the item if the sticky component is deleted, or the parent is deleted. This shouldn't be happening often, but good code is safe code. It also means
Requested by Steelslayer to move signals to RegisterWithParent, I fixed some other stuff too along the way
put a bunch of camera bugs on stuff, no runtimes. Crushed myself with a recycler, camera bug stayed, crushed myself with an emagged recycler, camera bug was destroyed along with the rest of my clothes
:cl:
fix: Camera bug hidden cameras will be properly destroyed when a person wearing one is sent into an emagged recycler
/:cl:
=> Improves /datum/component/sticky code

_maps/map_files/Delta/delta.dmm, _maps/map_files/MetaStation/MetaStation.dmm, _maps/map_files/cerestation/cerestation.dmm, _maps/map_files/cyberiad/cyberiad.dmm
fixes #21879
Brig cell doors now use the proper path so they close/open when a cell timer ends/starts
Cell doors should close/open when a timer starts/expires
You won't see anything playerfacing mapping wise
Found out cerestation just straight up doesn't have a cell 5
:cl:
fix: Cell doors once again close when they should when using a cell timer
/:cl:
=> fixes cell doors not closing when they should

code/modules/mob/living/carbon/human/species/_species.dm, code/modules/projectiles/ammunition/energy_lens.dm, code/modules/projectiles/guns/energy/stun.dm
Tweaks the equation for slowdown to be less harsh at the 40 damage threshold and onward.
Reduces the amount of shots in the disabler from `20 > 16`
The disaber is a . . . weapon. It is VERY good at downing people at range. Currently, you have 20 shots per full charge disabler and it takes 2 shots to get to put you in slowdown.
With the current equation (`health_deficiency / 25`), 60 stamina gives a slowdown of `2.4`, rounding to `2.5`
With the new equation (`(health_deficiency / 25) - 1.1`), 60 stamina gives a slowdown of `1.3`, rounding to `1.5`
This should make the disabler a BIT less oppressive and allow for a slightly easier escape if you manage to dodge/counter the shots somehow. This also affects damage-damage, so this should make getting tagged by a shot or two on BOTH sides a bit …
=> Disabler Nerf: Slowdown Tweaks + Shot Reduction

code/modules/antagonists/vampire/vampire_powers/umbrae_powers.dm
Fixes an unnoticed bug with recastable vamp spells
Minor exploits are still bad
The spell worked fine now
:cl:
fix: A vamp exploit has been fixed
/:cl:
=> [s] Fixes an umbruh exploit

code/modules/food_and_drinks/food/foods/sandwiches.dm
Adds location logging to roburgers upon creation.
In short: faster+better grief prevention
In long: Roburgers are like chainsaws, it is statistically more likely they are made for griefing than for legit reasons. Even though this specific logging has no user attached to it, we still have the tools to see who did it based on this location.
Added an extra article before the name
1. Spawn these: `/obj/machinery/kitchen_machine/microwave`, `/obj/item/reagent_containers/food/snacks/bun`, `/obj/item/robot_parts/head`
2. Add the robot head and bun to microwave
3. Start cooking
=> Adds more admin logging to roburgers

code/modules/power/engines/supermatter/supermatter.dm
removes the duplicate `SSair.atmos_machinery += src` from SM init. this is called on the parent now that the SM is atmos machinery so it is redundant.
bugs are bad
looked at SM console, only 1 SM.
:cl:
fix: SM monitoring console will no longer show up duplicates
/:cl:
=> Fixes the SM showing up twice on the monitor console 

code/game/gamemodes/nuclear/nuclear_challenge.dm
Fixes the description incorrect information, currently you have 10 minutes (after round has started) to make that decision, not 5.
The time to make that decision was increased from 5 to 10 minutes in the past since it did take into consideration the time spent in the lobby, this is no longer the case because of the PR https://github.com/ParadiseSS13/Paradise/pull/9112 resulting now in 10 minutes total.
The wiki page is correct about this information
- See image above
:cl:
fix: Declaration of war item description is no longer incorrect about the time available for it to be used
/:cl:
=> Declaration of war item description is no longer incorrect about the time available for it to be used

code/__DEFINES/atmospherics_defines.dm, code/modules/reagents/chemistry/reagents/medicine.dm
Cryoxadone has been tweaked. Partially reverting https://github.com/ParadiseSS13/Paradise/pull/14440
Cryoxadone now once again works off internal tempatures, though a colder tempature, making it harder to use as a combat chemical, both for rapid on the spot healing, and so someone can't keep people stunned effectively with say, syringe guns.
It also will give messages to people  that are awake and weakened by it, so it won't hit people in cryotubes, but it will to those wondering why they can not move.
And naturally, as hinted at above, cryoxadone weakens the user for 4 seconds when healing. This does not add up, it just means they get the weaken removed 4 seconds after it is removed from their system.
I mean to be frank this is for people that just walk into space without a suit. This is …
=> Nerfs suitless spacewalking: Cryoxodone now stuns while healing.

code/modules/reagents/chemistry/machinery/chem_master.dm
This fixes a bug that allows players to insert pills into patch packs using the ChemMaster 3000.
Patch packs should not be able to hold pills.
Tested to see if pills could not be put into patch packs.
Tested to see if patches could not be put into pill bottles.
Tested to see if patches and pills could still be put in their intended containers.
:cl: Burza and CinnamonSnowball
fix: Fixed item checking for pills and patches when inserting into containers with ChemMaster
/:cl:
=> Fixes pills being put into patch packs via the ChemMaster

code/game/gamemodes/miniantags/guardian/guardian.dm, code/modules/mob/mob.dm
Stops guardian spirits from being buckled, which caused jank sometimes
Resolves #16563 
Also changes some `return 0` and `return 1` to the appropriate defines
Fixes a bug and reduces jank
Also, being able to buckle a swarm of nanomachines that can dissolve at will/a literal spirit seems not very realistic
See image
:cl:
tweak: Guardian spirits now can't be buckled
fix: Fixed a bug with buckled guardian spirits
/:cl:
=> Stops guardian spirits from being buckled

code/game/objects/items/theft_items.dm
Makes it so the sprite actually updates after dusting someone(and yourself) with the tongs holding a sliver.
They don't hold the sliver after dusting, so the sprite should reflect that.
dusted myself and a poor skrell a few times with the same tongs. 
:cl:
fix: Fixed the supermatter tongs sprite not correctly updating after dust
/:cl:
=> The SM tong sprite now correctly reflects if its holding a sliver after dusting. 

code/game/gamemodes/miniantags/morph/spells/pass_airlock.dm
fixes #21936 
Morphs shouldn't get sent to nullspace
passed a deleted airlock, did not get sent to nullspace
:cl:
fix: You no longer get nullspaced if you try and pass through a deleted airlock as a morph
/:cl:
=> morphs no longer get sent to nullspace

code/modules/reagents/chemistry/machinery/reagentgrinder.dm
Fixes #20841 where juicing a blumpkin produces pumpkin juice instead of blumpkin juice.
Juicing one type of fruit/vegetable should not produce juice from another fruit/vegetable.
Juiced a blumpkin and checked the contents of the container.
:cl:
fix: blumpkins now produce the right juice when juiced in a grinder
/:cl:
=> Fixes blumpkin juicing

code/modules/projectiles/ammunition/ammo_casings.dm, code/modules/projectiles/projectile/bullets.dm
Lasershot, rubbershot, and weak buckshot have their spread increased by 10 degrees to 35, from  25.
Actual buckshot, which is gamma or nukie only, is uneffected.
Beanbags now throw people back a tile. This can wall knockdown / do damage / vendor crush. Good for keeping people you do not like away from you, rather than an ammo you want to be close for, like buckshot.
Also good for making people drop what they drag.
Beanbag is not used often. Disablers / eguns are easier to get, and rubbershot is insanely good. 
This makes beanbags a weapon about positioning, or keeping people away from you. Could be useful!
As for lasershot / rubbershot, this makes the ammo miss partially when the victim is 3 tiles away from the shotgunner. This should help make it less painful at range while still being …
=> Beanbag shot now throws a tile. Increases the spread on rubbershot / lasershot / weakbuckshot

code/game/objects/structures/crates_lockers/closets/secure/medical_lockers.dm
Adds 5 mannitol pills to the psychiatrist's pill bottle.
It's kind of weird that the psychiatrist doesn't have pills to treat brain injuries.  While the psychiatrist could easily walk into medical for this at roundstart, there's no reason why they wouldn't have their own stash.  This also gives the psychiatrist more of a practical role on the station.
Pills are in bottle.
:cl:
add: 5 mannitol pills to the psychiatrist's pill bottle
/:cl:
=> Adds 5 mannitol pills to the psychiatrist's pill bottle

code/controllers/subsystem/SSjobs.dm, code/modules/mob/living/simple_animal/hostile/retaliate/clown.dm, config/example/config.toml
Fixes a typo in an emote string but more importantly fixes two job map names in the TOML config.
If these names in the TOML config aren't as specified they won't be properly applied to the job datums. Roboticist for obvious reasons and Atmospheric Technician because alt job titles don't work here.
=> Fix two typos.

code/__DEFINES/dcs/signals.dm, code/_onclick/item_attack.dm, code/datums/components/material_container.dm, code/game/machinery/autolathe.dm, code/game/objects/items/tools/screwdriver.dm
Fixes #20599, Holding a screwdriver on harm intent and clicking on the autolathe will recycle it.
Okay, this is more complicated than I thought, at least to not make it hacky. This PR adds a signal to intercept the tool attack and cancel the tool act. This is generally useful, but it is needed here to insert the screwdriver into the material container since the logic to insert items into the container relies on the AttackBy signal. Another necessary change is the if statement in the material container code that allows all tools to be inserted on harm intent. Otherwise, inserting any items with harm intent is impossible. I did all this to avoid using GetComponent and keep all the material container logic within the component.
Suppose you wanted to use GetComponent from within AutoLathe.dm, …
=> Screwdrivers can now be recycled in autolathes

code/modules/reagents/chemistry/reagents/misc_reagents.dm
Title, lowers from 1000 seconds to 100
Honestly 1000 seems like a typo, there's no reason a purely client side effect that honestly really only gives motion sickness irl should last for 16 entire minutes, not even counting the extra 20 every 2 seconds. 
Single number changed, still tested, appears to be correct as i didn't get a stupidly high number.
however im not 100% sure how strength works.
:cl:
tweak: jestosterone no longer applies 16 minutes of dizy
/:cl:
=> Lowers the ammount of dizy jestosterone applies. 

code/modules/events/false_alarm.dm
fixes #21502
adds an extra arg so it properly plays the sirens
these are fully false alarms, not kinda false alarms 
i had to trigger the event like 30 times to test this thing
:cl:
fix: Sirens are triggered on false alarm events
/:cl:
=> false alarm now sounds the sirens

code/modules/mob/language.dm
This PR does several things to shorten the visual length of scrambled phrases spoken in trinary. It truncates the available syllables to the digits 0, 1, and 2; removes the word-joiner that may appear when scrambling text, removes the chance for spaces to be inserted, and reduces the input text by 75% before passing it to `/datum/language/proc/scramble`. A side-effect of all this is that punctuation should also not be inserted in the scrambled text based on the input, unless there's punctuation within the first 25% of the text.
Trinary is described as utilizing "machine-level" "sound encoding". This suggests that the speech is converted digitally, and digital encoding of data is--compared to human speech--very efficient. Based on some very quick research, a 60 minute audio cassette with a …
=> feat: truncate the length of scrambled trinary speech

code/game/objects/structures/signs.dm
Allows clients to click on a wall map to prompt for opening the station's webmap. I'm not sure if this should go in attack_hand or attackby but this seems straightforward.
A diegetic action like interacting with a map is much more natural and intuitive than clicking on the Map button in the UI. It also allows for an IC explanation for players instead of trying to explain where the UI's "Map" button is in LOOC.
Tested interacting with map on Box. Interaction doesn't work as a ghost but that's prooooooobably fine?
:cl:
add: interacting with station wall maps prompts players to open the webmap.
/:cl:
=> feat: clicking on wallmaps prompts to open webmap

code/datums/outfits/outfit_admin.dm
Adds a bare-bones outfit for spawning people in on the Live server OR for testing when needed. Can simply click "o" to jump down to "Observer" and pick the appropriate outfit!
Having an easy-to-get-to outfit for Admins to spawn people in as for the Admin Zone/testing stuff on Live is nice. This outfit has no ID and no headset, so you can just let dchat peeps go about and do whatever testing/stupidity you want.
Also comes with a dust implanter so that when you die/if you want to go back to dchat, you can.
Comes in Human Standard, Vox, and Plasmaman flavor!
1. Spawned in a human, dressed em.
2. Spawned in a vox, dressed em.
3. Spawned in a plasmeme, dressed em.
:cl:
add: Added basic observer outfits for admin use.
/:cl:
=> Adds Basic Observer Outfits for Admin/Testing Use

code/game/objects/effects/anomalies.dm, code/modules/mob/living/simple_animal/hostile/megafauna/ancient_robot.dm
Cryo vetus ice trails last much less time.
Cryo anomalies from vetus no longer apply perma frost (aka meaning no slips / magboots wont help you), and the ice trails last less time.
The ammount of slipping cryo vetus did was a little much. This should make the terrain less hellish, as well as making no slips work as intended (bringing jump boots is still highly suggested)
confirmed vetus worked as I wanted
:cl:
fix: Cryo vetus is less hellish with ice duration, and no longer does permafrost ice, so no slips / magboots will work.
/:cl:
=> cryo vetus slip nerf

code/datums/action.dm
Item action usability now checks for handblocked over being horizontal (This probably removes some jank, not entirely sure what)
To be entirely honest not being able to do this post crawling feels incredibly weird. I would like to be able to turn on my internals while lying down, thank you very much. There might be some weirdness with like the jump boots that i'll look at tomorrow but this probably should be alright and have minimal impact outside of QOL.
Turned on my internals while on the ground
:cl:
tweak: item actions can be used while horizontal
/:cl:
=> item actions can be used while horizontal

code/game/machinery/camera/camera.dm, code/game/machinery/doors/airlock.dm, code/game/objects/items/devices/flash.dm
Only malf AI can hack doors with cut AI control wires. Otherwise, an AI can no longer interface with a door that has its ai control wires cut, period. Malf AI however can now hack these doors faster, taking only 30 seconds.
Flashes can be used to to now emp cameras, either weakly emping camers around the user when flash is used in hand, or a strong emp when used directly on a camera. Naturally, emp proof cameras are immune to it.
Weaker emps last 45 seconds on disabling cameras, as a bit of counter balance.
AI is strong, and while I do not agree with the door bolt / shock delay PR, I do think there should be more options against ais.
If someone goes through the effort of cutting ai control wires, they should have to be fixed. AI should not be able to hack the airlock and be able to access …
=> Only malf AI can hack doors with cut ai wires, flash emps cameras 

code/_onclick/hud/screen_objects.dm, code/modules/mob/living/carbon/carbon.dm, code/modules/mob/living/carbon/carbon_update_icons.dm, code/modules/surgery/organs/subtypes/standard_organs.dm
There is now a visual indicator if you can't use your hand. Also refactors some code so that we use a consistent update proc. Idea is from TG, code wasn't a clean port so I made it work with our system.
Tried using just normal calls with delimbs, and didnt work. Neither did async. So I had to do a 0 tick callback (fun)
Giving the player knowledge about their body is good
Handcuffs still work, swapping active hands still works.
:cl:
add: Your hands now have a "blocked" symbol if you can't use them (i.e. no hand, dead hand)
/:cl:
=> There is now a visual indicator if you can't use your hand

code/game/gamemodes/malfunction/Malf_Modules.dm
Reworks reactivate cameras
No longer a one purchase ability
Fixes up to 10 cameras now (instead of 30), works in the area the AI eye is centered on
Actually fixes the wires in the camera (jank reduction)
we all know malf AI is bad, but giving them an ability that's one use and basically rng relient is a bit of a sin against nature. Like, malf AIs NEED cameras and this ability is a total newb trap because it just isn't sure to work. 
This removes that RNG by giving them control over what cameras are repaired, and the frankly odd one purchase part of the ability. Are we scared that malf AI might be able to expend APC points to uh, repair cameras that can be cut again right after? 
Found out the camera list on areas didn't work because the UIDs would change after fully initing
joy
:cl: …
=> reworks reactivate cameras for malf ai

code/modules/projectiles/guns/magic.dm
Makes staffs actually have the number of max charges they're supposed to
This makes the value of `max_charges` on a `/gun/magic` item more accurate. Before, `max_charges = 1` would actually mean two charges, because you'd accumulate infinite increases to `charge_tick` that would then immediately refill the charge when lost.
Spawned and fired a bunch of staffs
:cl:
fix: Magic staffs now have the correct number of max charges in practice
/:cl:
=> Fix: stop magic staff recharging while already at max charge

code/__DEFINES/status_effects.dm, code/datums/status_effects/debuffs.dm, code/game/objects/items/devices/traitordevices.dm
Confusion buffed from 30 seconds to 45 seconds
batterer now recharges a use every 20 seconds
batterer no longer works on mobs with no clients
Alright now that the batters in, it's clear this item is not very good. This was stuff I wanted to do in the original pr that I held off on so it would get merged. I would really prefer to not give it knockdown if someone is (pretty likely) thinking to suggest that.
But yeah, more consistent confused and recharge is really what this item needs to be somewhat viable
also I don't think NPCs/ssd people should get brain damaged you know. seems a little fucked up to me
battered a skrell a bunch
:cl:
fix: mind batterer no longer affects clientless mobs
tweak: mind batterer confuse lasts longer
tweak: mind batterer recharges over time
/:cl:
=> buffs the mind batterer

code/modules/reagents/chemistry/reagents/toxins.dm, code/modules/reagents/chemistry/reagents/water.dm, code/modules/reagents/chemistry/reagents_datum.dm
If you're a vampire, you now no longer get toxins from drinking the wrong blood type. Also makes vampires able to drink slime jelly to regain hunger.
As a side effect, vampires can also use slime jelly to restore their own blood, regardless of being a slime.
TODO:
Fixes #19798
Fixes #21614
It's intended that drinking blood from blood bags and such will restore your hunger, it is however quite stupid and annoying if you instead get 100 u of toxin because you grabbed the wrong bloodbag.
Drank blood, didn't die a vomiting death
:cl:
fix: Vampires can now drink all types of blood without dying of blood incompatability
tweak: Vampires can now drink slime jelly to restore hunger and blood level
/:cl:
=> Vampires now don't get toxin damage from drinking a wrong blood type

code/modules/mob/living/living.dm
Fixes nonhumans having white blood instead of red, caused by an accidental tab in the code by https://github.com/ParadiseSS13/Paradise/pull/21863
Fiixes https://github.com/ParadiseSS13/Paradise/issues/21976
BEFORE
AFTER
- Beat Ian multiple times until he bleeds
- Drag him around and notice the trail color
:cl:
fix: Nonhumans now have red blood again
/:cl:
=> Fixes #21976 Nonhumans now have red blood again

code/game/gamemodes/wizard/soulstone.dm, code/modules/mob/living/living.dm, code/modules/power/engines/singularity/narsie.dm
Jobbanned can spam smoke with Nar'Sie, when it should spawn only on harverster spawn. It fixes this.
Jobbanned shouldn't be able to make server lag
Nope, just hoping for the best...
:cl:
fix: Jobbanned can't spam NarSie harvester smoke anymore
/:cl:
=> [FIX] Jobbaned can't spam-spawn as cult harvesters

code/modules/power/engines/supermatter/supermatter.dm
Makes things dust when a supermatter crystal runs into them as well. While this probably won't be the case with the main engine supermatter, it could come into play if a supermatter crystal starts moving around...
Also, provides some examine text to show that the crystal can be wrenched down, since it isn't really clear and not something you're generally going to experiment with.
Really, a supermatter crystal running into you and you being fine is just a weird interaction that doesn't feel quite right. This is more where it's at. Note that if an SM (in particular, a shard) runs into a window, it will destroy it, which should encourage you to anchor your shards before they start bouncing all over the place.
https://github.com/ParadiseSS13/Paradise/assets/89928798/5bd0f82c-c44d-4454-ad6a-eb7 …
=> Makes things dust when the SM bumps them as well

code/game/machinery/tcomms/tcomms_core.dm, code/game/objects/items/devices/radio/radio_objects.dm
Prevents radios from working in certain admin areas.
Admins can always vv the radios to work if they want to (or just move elsewhere), so it hopefully shouldn't matter too much.
Players using the radio in admin testing or the thunderdome (or just having death implants triggered) sometimes causes some bleed-over into the station, prompting weird reactions. This isn't really ideal and creates some ick-ock situations. This should hopefully fix that.
:cl:
tweak: Radios now no longer work in certain admin areas.
/:cl:
=> Prevents radios from working in certain admin areas

code/modules/mob/living/carbon/brain/carbon_brain.dm
fixes #18595
MMI brainmobs were always returning they were incapacitated; this caused all their clicks to fizzle before they got to the mecha actions. This pr makes it so that mmi brainmobs don't fail incapacitated checks, this probably also causes like a mild change with some niche but I'm not that concerned considering that it would succeed with robobrains so it's more consistency than anything. 
Bugs bad, let the poor brains go mine or something.
Slammed my head into a wall for an hour trying to get stuff to work, eventually found out it was failing even earlier than the mech actions and worked backwards
:cl:
fix: MMIs can use mech actions again
/:cl:
=> Fixes mmis being unable to use mech actions

code/game/area/areas.dm
Basically ports tgstation/tgstation/pull/48910. This decreases init times by 0.05 seconds on average from my testing on JUST cyberiad (what an insane increase, I know). It is likely way more factoring in lavaland and space ruins.
Performance is good
Testing on cyberiad (no lavaland, no space z levels or ruins)
Old
New
Testing on a prod-like environment
Old
New
See above
nothing player facing
=> Refactors some old area initialization code to improve performance

code/game/objects/items/stacks/sheets/sheet_types.dm, code/game/objects/items/stacks/stack.dm
Now stacks change icon_state every third of amount.
If we have max amount = 50 in stack. We got:
1: 1-16
2: 17-33
3: 34-50
No more 1-2-3.
Stacks displaying a more accurate amount
Only code
Placed almost all stacks
:cl:
tweak: Stacks now work on the principle of 1/3
/:cl:
=> tweak: Better stacks

_maps/map_files/RandomRuins/SpaceRuins/wreckedcargoship.dmm, code/datums/ruins/space_ruins.dm, code/game/area/areas/ruins/space_areas.dm, config/example/config.toml
Adds a space ruin with slightly spicy to questionable loot. Current loot is a subject to change.
As gateway content was removed exploring is in dire need of some attention. New content is good, bonus points if it has a story to tell.
no issues with map files as far as i can tell though my word shouldn't be taken as i am completely new
:cl:
add: Added a new space ruin: wrecked cargoship
/:cl:
=> Adds a new space ruin: Wrecked Cargoship

code/game/machinery/camera/camera_presets.dm
ports BeeStation/BeeStation-Hornet/pull/9540. Refactors the cameras' init for ***the micro-optimizations***
Better init times
Cerestation (the station with the most auto-named cameras), all autonamed cameras were named correctly. Spawned some autoname cameras manually, turned out like before.
=> Better autonamed camera init performance

code/game/objects/items/weapons/storage/bags.dm
While empty, trashbags can fit into backpacks. However while holding items, they cannot.
Currently trashbags have a weight class of bulky, while being.. trashbags, something that (while empty) really isn't all that large, meaning janitors need to carry around empty trashbags in their hands constantly, or need to use the jani car/t, or a bluespace bag, both having frustrating downsides, mainly being the need to constantly drag/drive something around, thats really prone to being stolen, or needing a high tech level from rnd. 
Not to mention if you're a janitor ert, you often do not have time/the ability to obtain such items.
I tried to put the trashbags(bluespace and non) in various storage compartments while full of cigar butts and empty, making sure that it acted how i expected. 
And it …
=> Empty trashbags can now fit inside backpacks.

code/modules/mob/living/simple_animal/bot/bot_construction.dm
Fixes #21841 - all robot names must now be at least 1 character long. Also fixed a bug that made the rename dialog pop up twice for floorbots.
Things not having names bad.
Tried giving empty names to the most popular robots, tried giving a normal name to a robot.
:cl:
fix: Robot names can no longer be 0 characters long
/:cl:
=> Robot Names Can No Longer Be 0 Characters Long

code/modules/pda/app.dm
Fixes #21893 - PDA Icons flash again after receiving messages.
Bug bad, flashing PDA good.
Sent PDA a message, observed flashing, observed flashing stopping when looking at messages.
:cl:
fix: PDAs flash when receiving messages again.
/:cl:
=> PDAs Change Icon With Unread Messages Again

code/modules/mining/lavaland/necropolis_chests.dm, code/modules/ruins/lavalandruin_code/puzzle.dm
lavaland sliding puzzles now spawn normal mining chests instead of a whisp lanter or soulstone
Right now this is the chest you get if you complete the sliding puzzle
```
/obj/structure/closet/crate/necropolis/puzzle/populate_contents()
var/loot = rand(1,2)
switch(loot)
if(1)
new /obj/item/soulstone/anybody(src)
if(2)
new /obj/item/wisp_lantern(src)
```
50/50 chance between literal thermals and a soulstone, a rather useless item for a miner. Just give them a varied pool rather than this
I'm not doing a sliding puzzle, it compiled 
:cl:
tweak: lavaland sliding puzzles now spawn normal mining chests instead of a whisp lanter or soulstone
/:cl:
=> lavaland sliding puzzles now spawn normal mining chests

code/modules/admin/verbs/SDQL2/SDQL_2.dm, code/modules/admin/verbs/debug.dm
Fixes proccall wraper that didnt work as intended in dm ref. Before this fix trying to call a global proc would give "bad proc" runtime.
Alt description: You dont need to write /proc/ before proc names when calling a global proc anymore.
Shitspawning intensifies
I called a global proc and got no runtimes.
:cl:
fix: Now advanced proccalling a global proc works properly 
/:cl:
=> Fix: global proc procall

code/game/objects/items/devices/radio/radio_objects.dm
This fixes the radio jammer and stops it from being able to jam across z-levels.
This makes the jammer work as intended.
Created an active jammer at the x,y coordinates of the bridge on a different z-level.
Tested radio on the bridge to see if comms were still jammed.
:cl:
fix: Fixed jammer's ability to jam comms across z-levels
/:cl:
=> Radio Jammer can no longer jam across z-levels

code/game/objects/items/devices/chameleonproj.dm
Fixes #12006 (it responds to both lava, fire, and acid now). Also fixes orbiters failing to follow someone in a chameleon projector when they activate it. (this was an issue with direct loc editing, instead of moving). 
Bugs are bad, the acid part wasn't explicitly stated in the issue, but I found it also by looking at the resistance flags, since effects are by default, lava, acid, and fire resistant.
Activated the chame projector, ghosts could follow me. The chame projector could be disrupted by lava, fire, and acid.
:cl:
fix: Orbiting a chameleon projector user as a ghost should be much more consistent.
fix: Chameleon projectors respond properly to lava, acid, and fire.
/:cl:
=> Fixes some issues with lava, acid, orbiters, and chameleon projectors

code/modules/power/engines/supermatter/supermatter.dm
The singulo delamination, (when the supermatter has too many moles), now darkens as it heads to 50% integrity, rather than getting brighter as it delaminates. 
Below 50% integrity, the singulo slowly begins to darken the area, similarly to how light can not escape a black hole.
Does this accurately reflect physics? No, but it is cool.
Making an area bright and an eery glow as engineering makes either high power (over 5000 EER), or fucks up (too many moles) is cool.
But darkness, from the supermatter shard collapsing, is much cooler.
The darkness becomes stronger as the SM delams, blacking out the area  slowly over time, especially from cameras. For people actually working on the SM with mesons, pipes are generally viewable in a reasonable radius up until about 10% remaining integrity. …
=> supermatter gets darker as it delams, rather than brighter, below 50% it darkens the area

code/_onclick/ai_onclick.dm
Gives AI/Borgs/etc a `do_after` when shortcut-clicking to bolt or shock. You can queue up multiple of these AND move while doing so.
Bolting: `3 SECONDS`
Shocking: `3 SECONDS` + Audio Cue (short spark sound) for when a door near you is shocked.
This ONLY effects the shortcut and does not effect opening the menu to do so.
Currently AIs are VERY VERY VERY strong against antagonists. An AI can kinda just shaft any antagonist at will. Youre meant to be a moral-less cyborg who's only kept in check by your Laws. The fact that so many AI then choose to act like RoboCop (while not even ON the Lawset) is beyond absurd.
This change makes it so if you want to ignore the funny menuing to lock a door down, you have a slight delay to do so. This will ONLY effect non-antagonist AI - so malf/emagged …
=> Gives Bolting/Shocking a `do_after` Unless Antagonist

code/game/machinery/airlock_control/airlock_controllers.dm, code/game/objects/items/weapons/dna_injector.dm, code/game/objects/items/weapons/handcuffs.dm
This adds in some user warning messages when a check is performed on handcuffs, DNA injectors, and airlock controls, if the mob can not use it due to not being an advanced tool user. 
This will alert the players if they can not complete a certain action or use an item due to not being eligible, mostly likely because they are a mob like a monkey. This brings these specific items up to speed with other items that perform the same check and display the same message. 
Spawned in and took control of a monkey. 
Tested DNA Injectors, Airlock Controls, and Handcuffs and checked to see if the appropriate error message was displayed.
:cl:
add: Added some warning messages when ineligible to use certain items.
/:cl:
=> Alert messages for AdvancedToolUser checks

SQL/paradise_schema.sql, SQL/updates/49-50.sql, code/__DEFINES/misc_defines.dm, code/modules/admin/admin_verbs.dm, code/modules/admin/topic.dm, code/modules/admin/verbs/serialization.dm, config/example/config.toml
This PR is an admin-only tool. Feel free to ignore.
---
Adds a system to allow saving of JSON datums to a database table with slot names. This means that you can now save your JSON character saves to the DB and load them as slots. Yes, this means no more text files littered all over your documents.
TODO - Make the server automatically strip JSON of broken stuff that shouldnt save like scuffed implants or similar.
As for the implementation, when asking to serialise an object you are now given this menu
`PC` will dump the JSON to chat as it does now.
`Server` will bring up this menu.
Selecting an existing slot will update that slot. Selecting `--NEW--` will allow you to type a name for a new one.
You can then spawn future ones and delete them from the `Spawn Saved JSON Datum` verb.
Not …
=> [ADMIN] Allows saving of JSON datums server side

code/modules/recycling/disposal.dm
Disposals now instantly shoot you out rather than having a delay
Adds a 1 second immobilize to reduce further cheese after being shot out by a disposal outlet
This is weird and frankly pretty janky, it's gotten to the point where a good amount of maps have quarter tile windows around the recycler so you can't cheese emmaged recycler stuff as easy, you can still cheese past it so here's a better solution. Adds a 1 second immobilize to reduce further cheese
Also it's just weird to get thrown AFTER you're out of the tile with the disposal outlet
oh no emmaged recycler
:cl:
tweak: Disposal outlets shoot you out instantly, Adds a 1 second immobilize after being shot out by a disposals outlet
/:cl:
=> Disposals now instantly shoot you out rather than having a delay

code/datums/uplink_items/uplink_traitor.dm, code/game/objects/items/weapons/grenades/syndieminibomb.dm, code/game/objects/items/weapons/storage/uplink_kits.dm, code/modules/projectiles/guns/projectile/revolver.dm
This PR
1: Moves trick revolver from subtype of russian revolver to subtype of actual 357 revolver. Now it acts the same as default revolver whatever you do with it, but if you try shoot, you will die.
2: Makes trick revolver bring recognisable with clumsy trait. If you examine it with clumsy, you will see "Its mechanism looks like it shots backwards."
3: Adds Trick minibomb. That is minibomb as actual one, but once you activate it, it will gain NODROP flag makes it impossible to throw at target. If you examine it with clumsy gene, you will see text "There is small glue ejectors all over the bomb."
After activating the bomb, you will see text "As you activate the bomb, it emits super glue and sticks to your hand." and "Uh oh."
Trick revolver supposed to looks like real one, but its nature …
=> Fixed Trick Revolver, Added Trick minibomb

code/game/objects/effects/decals/Cleanable/misc_cleanables.dm, code/game/objects/effects/effects.dm, code/modules/events/event_container.dm, code/modules/events/wallrot.dm
Adds a new mundane event, Fungus Growth, which causes fungus tiles to grow on maintenance tiles. 
Fungus is also now re-harvestable after some time (between 5-10 minutes).
Spacecillin is now more useful than ever with germs and infections becoming more prevalent (hello, burn wounds), but most chemists won't be producing it since fungus is pretty uncommon. This adds a little bit of life to maintenance (maybe there's some new fungus popping up), while also making it a bit more consistent to get -- assuming, of course, the event rolls. It also allows you to farm the fungus that does currently exist, though you'll have to know the spots where it spawns on maps to do so effectively.
Of course, if it pops up in unsightly spots, it can be cleaned off with soap or other common cleaning tools. …
=> Adds a new Fungal Growth event, makes fungus re-harvestable

code/datums/uplink_items/uplink_traitor.dm
adjusts surplus crates for inflation
fixes #22057
bugs are bad
checked the numbers on my 90 pound calculator
:cl:
fix: surplus crates give the proper amount of items
/:cl:
=> fixes surplus crates

code/_onclick/ai_onclick.dm, code/modules/mob/living/silicon/robot/robot_mob.dm, code/modules/mob/living/silicon/silicon_mob.dm
Ensures emagged borgs, both malf and emaggedd, can instantly bolt/shock doors.
This was intended in the original PR #21491:
`This change makes it so if you want to ignore the funny menuing to lock a door down, you have a slight delay to do so. This will ONLY effect non-antagonist AI - so malf/emagged borgs/etc do not have to deal with this change.`
1. Emagged myself as a cyborg.
:cl:
fix: Fixed emagged cyborgs not being able to instantly bolt/shock.
/:cl:
=> Fixes Emagged Borgs Not Having Instant Bolt/Shock

code/game/objects/items/weapons/rpd.dm
RPDs can runtime if they broke an object with their attack, causing the turf to be null and thus runtiming.
Runtimes bad
Broke bushes with my RPD, shit didn't runtime
NPFC
=> Fixes a RPD runtime

code/modules/hydroponics/grown/flowers.dm
Fixes #22029 
Two random flowers missing periods in their descriptions made the game literally unplayable for at least 60% of the playerbase. I'm sure many will be happy to see this change.
Loaded in. Spawned flowers. They have periods in their descriptions now.
:cl:
spellcheck: Adds periods to two flower descriptions. Fixes #22029 
/:cl:
=> Adds a period to two flower descriptions. Fixes #22029

code/datums/keybindings/emote_keybinds.dm, code/modules/mob/living/carbon/human/human_emote.dm
Fix #22014, ensuring that the checks that had previously been applied to slimepeople *squish were also applied for the new emotes.
Humans shouldn't be able to *bubble, unless they have rabies that is.
:cl:
fix: Fixes non-slimes being able to *bubble and *pop
/:cl:
=> ensure only slimes can bubble and pop

code/modules/power/engines/supermatter/supermatter.dm, code/modules/power/engines/supermatter/supermatter_event.dm
This PR fixes 2 runtime errors that occured when SM events were called. This PR also changes class A-2 events to simply reset the air alarm, as opposed to the previously attempted custom settings. Finally, this PR fixes a several year old issue in which admins were not notified and a flag was not set if an engine was not powered with emitters.
Runtimes bad. Things acting wrong is bad. Oversights are also bad.
Ensure events starts on emitter based and gas based SM designs.
:cl:
fix: Fixes 2 runtimes and some unintended behavior in SM events
/:cl:
=> HOTFIX: 2 SM event runtimes, 2 instances of unintended behavior

code/modules/reagents/chemistry/machinery/chem_master.dm
Fixes single pill/patch creation buttons doing absolutely nothing due to early-returning thanks to an arguments list property that is never set for those buttons
I broke this on accident in #21904 because the way the code did it previously was undocumented and baked into a one-liner; still, probably should've caught it in more rigorous testing, totally my b
(also, Chem Master UI code is horrible)
Bugs be gone
Tried to make a singular pill, confirmed success
Tried to make 1 pill in a multi number prompt, confirmed result was the same as above
Tried to make 0 pills in a multi number prompt, confirmed machine aborts successfully
:cl:
fix: Fixed Chem Masters' singular pill/patch creation buttons not working
/:cl:
=> Fixes single pill/patch creation in Chem Masters

code/game/gamemodes/nuclear/nuclear_challenge.dm
nukies no longer get tc from non players
this is a bugfix
I dunno how i would test this on local reasonably 
:cl:
fix: Nukies get telecrystals based on the number of crew, rather than any mob with a client
/:cl:
=> nukeops no longer get tc from ghosts and related

code/game/objects/structures/aliens.dm, code/modules/mob/living/simple_animal/hostile/venus_human_trap.dm
Fixes #21200
Removes the weird alien resin spawned due to inheritance bullshit
Also slightly refactors the surrounding code because it bothered me
Runtimes bad, random alien resin bad
Spawned in resin doors and walls, they didn't runtime
Spawned flowering pod, it didn't runtime and it flowered nicely
NPFC
=> Fixes a flowering kudzu runtime

code/modules/surgery/organs/subtypes/standard_organs.dm
fixes a null.hudused runtime from detaching a hand
source will be null if you input null into a timer send
```
/mob/living/carbon/proc/update_hands_hud()
if(!hud_used)
return
var/obj/screen/inventory/R = hud_used.inv_slots[slot_r_hand]
R?.update_icon()
var/obj/screen/inventory/L = hud_used.inv_slots[slot_l_hand]
L?.update_icon()
```
remember to sanity check your timer sends
runtimes bad
=> fixes a runtime if your hand gets cut off

code/modules/security_levels/keycard_authentication.dm
Fixes #22055. ERT without admins online will also be properly tallied on the blackbox.
Nasty bug
2 Clients on a server, called ERT while both were de-admined, could only call 1 instead of spamming it. Changed alert to red alert without any problems with the async.
:cl:
fix: ERT calling when no admins are online is more consistent with normal ERTs.
/:cl:
=> Fixes some issues with keycard authenticators

code/modules/food_and_drinks/kitchen_machinery/kitchen_machine.dm
This fixes https://github.com/ParadiseSS13/Paradise/issues/19486, a bug that causes items inserted into kitchen machines to not pluralize properly. 
Prevents a spelling error from occurring.
Put multiples of the same item into a kitchen machine and checked the behavior.
:cl:
spellcheck: Fixed kitchen machine plurals
/:cl:
=> Fixes item plurals for kitchen equipment 

code/datums/status_effects/debuffs.dm
Fixed a fake virus runtime related to empty emote lists.
The "FAKE_RETRO_VIRUS" had no ```var/list/fake_emote```  [1], [2], [3] lists applied to it since they had no emote symptoms, this caused a runtime when checking for ```!length(fake_emote[1])```
Runtimes that are not cats are bad
- Made the retro virus the only fake virus available and forced the event to trigger
- No runtime happened because of lacking emote list
:cl:
fix: Fixed a fake virus runtime related to empty emote lists
/:cl:
=> Fixes a fake virus runtime

code/modules/projectiles/gun.dm
Checks if the gun fired actually has bullets that can influence the muzzle flash.
This runtimed on a cling tentacle because those things are guns too, but have no chambered ammo or muzzle flash.
Runtimes bad
Fired the clingtacle a bunch at a dummy, nothing runtimed and the tentacle behaved as expected
NPFC
=> Fixes a rare runtime with the clingtacle

code/modules/martial_arts/martial.dm
fixes this runtime
```
[2023-08-19T22:46:34] Runtime in code/modules/martial_arts/martial.dm,81: Cannot read null.combo_display
proc name: reset combos (/datum/martial_art/proc/reset_combos)
```
sanity check your uids, they don't have any knowledge of what they point to, could be deleting, could be not even your thing
Skrell and delete after CQCing it
=> fixes some martial art runtimes

code/game/objects/structures/signs.dm, code/modules/customitems/item_defines.dm
Fix: Typos with a crowbar and a sign
Fixes #22033
=> Fix: Typos with a crowbar and a sign Fixes #22033

code/modules/mob/living/carbon/human/human_mob.dm
If you have no ears, for example by being a slimeperson, and are bombed with heavy or light explosions, the code tries to damage your ears that you don't have, causing runtimes.
Runtimes bad
Bombed a slime with light explosions, didn't get the runtime that live had
NPFC
=> Fixes a runtime with having no ears and explosions

code/modules/admin/misc_admin_procs.dm
If you press enter while giving no string to look for to spawn, the game would give you a list of every single atom. This can easily freeze your game for 30+ seconds, giving you some good time to think about what you just did.
Also adds logging to the verb.
TODO:
Edit: it already logged things, but these logs didn't appear in my chat for some reason?
`	log_admin("[key_name(usr)] spawned [chosen] at ([usr.x],[usr.y],[usr.z])")`
I don't want to sit in the time-out of shame
Tried giving no spawn path, didn't break on me
NPFC
=> Debug spawn now returns when you don't give a string to spawn, instead of freezing your game

code/datums/spells/conjure.dm, code/datums/spells/wizard_spells.dm
Fixes the Timestop spell. It now works every time you cast it, including when stamcritted.
Much credit to QwertyToForty for basically holding my hand through the process.
The Timestop spell is wacky. It randomly refuses to fire and straight up won't work if you're in stamcrit. This should fix that.
Loaded in, became wiz, used spell, it works. Shot beepsky, it works even as he beats my ass.
:cl:
fix: Fixed timestop. It now works every time, including when stamina critted.
/:cl:
=> Fixes the Timestop spell

code/game/turfs/simulated.dm, code/game/turfs/simulated/walls.dm, code/game/turfs/simulated/walls_reinforced.dm, code/modules/reagents/chemistry/reagents/pyrotechnic.dm
This PR changes thermite melting logic. Now melting time and melting progress is on thermite volume. Now it uses 100 units to melt r wall and 20 units to melt default wall. Melting r wall is 20 seconds, melting basic wall is 4 seconds.
When you start melting, it doesnt remove the wall, instead it is damaging it every second, making welder sound.
This does not affect T4, it still melts wall in 3 seconds(or whatever its time is)
I really dont like the idea of 3chem reagent being able to melt everything in one drop. This PR forces you to at least get MORE thermite to melt r walls, making raiding shit like AI sat harder. 
Compiled, thermitted
:cl:
tweak: Thermite now requires volume to melt walls. 20 units to basic metal wall, 100 units to reinforced wall. Its melting time now is also based …
=> Thermite tweak

tools/ci/check_grep2.py
This fixes check_grep2 to properly handle errors for files missing trailing newlines. `lines` here is actually an `io.TextIOWrapper`, which has an `__iter__` but no `__len__`, so we have to be kind of clumsy here for the sake of satisfying the same API as the other error checks and returning a line number in the error message.
CI should now fail properly for files that contain no trailing newline.
Tested on the same commit that failed at https://github.com/ParadiseSS13/Paradise/actions/runs/5959649385.
NPFC
=> Fix error in check_grep trailing newline test.

code/datums/status_effects/buffs.dm, code/game/gamemodes/changeling/changeling.dm, code/modules/antagonists/changeling/datum_changeling.dm, code/modules/antagonists/changeling/powers/lesserform.dm, code/modules/antagonists/changeling/powers/strained_muscles.dm
This PR removes unnecessary code which has no functionality nor use anymore.
Removes code mentioning genetic_damage from 5 files.
Removes the mention of genetic damage from the description of the ability Strained Muscles.
Removes unrequired lines of code, likely removing the possbility of errors within in the code.
Old:
New:
Tested via Testserver, everything is functional.
:cl:
del: Removed genetic_damage from the changeling code as it is not used anymore.
/:cl:
=> Removes old lines of code mentioning genetic_damage, fixes text misleading to receiving "genetic_damage".

code/modules/ruins/lavalandruin_code/puzzle.dm
fixes #22115
Put in the wrong typepath by mistake, not entirely sure it isn't just the default anyways, you don't call parent on populate contents 
still not doing a sliding puzzle
:cl:
fix: sliding puzzle chests have an item in them again
/:cl:
=> sliding puzzle chests have an item in them again

code/game/objects/structures/aliens.dm
/obj/structure/alien/egg/grown now has a prox timer
Fixes #21594 
Bugfix good
spawned /obj/structure/alien/egg/grown, walked near it, owch!
:cl:
fix: alien eggs that are created as grown on creation will facehug people who walk near them again
/:cl:
=> /obj/structure/alien/egg/grown has a prox timer now

code/modules/mob/living/simple_animal/hostile/megafauna/hierophant.dm
Adds a check to make sure the hierophant doesn't stray too far from its dance floor
Same as #21778, megafauna coming to station via non hijacker shenanigans is bad.
Fought the hierophant in a dance battle just long enough to get it to enter its triple teleport phase, once in it, jaunted back to station upon its first teleport, and the hierophant assumed it was victorious in the dance battle and didn't chase me upto the station. 
Jokes aside, this wasn't the easiest thing to test, but after doing it a couple of times, i feel pretty okay with saying that it can't do it anymore. 
:cl:
fix: Fixed the hierophant being able to chase you upto the station 
/:cl:
=> The hierophant now can't teleport to you if you're on the station. 

code/datums/uplink_items/uplink_general.dm
Fixes an oversight in the uplink discounts caused by the TC inflation
No I do not want a fucking half off plastic bag
I did not test this PR further than compilation.
:cl:
fix: The uplink will no longer give you the equivalent of pre-inflation 1 TC items discounts
/:cl:
=> Fixes an oversight in uplink discounts

code/modules/power/engines/supermatter/supermatter.dm
makes sm events not chain together in rare cases, sm event timer only starts ticking after the sm is set up
Events chaining together because nobody set up the SM is generally bad, getting an event right after you set it up is bad
Compiled, took a look at the SM to make sure the events functioned
:cl:
tweak: makes sm events not chain together in rare cases, sm event timer only starts ticking after the sm is set up
/:cl:
=> makes sm events not chain together in rare cases

code/modules/power/engines/supermatter/supermatter_event.dm
Changes Event b3 to be a EER spike of 3000, as opposed to detonation of a small nuclear warhead inside the Sm chamber.
Sm nuking on a B 3 class event is not intended. Fixes a rather severe issue
Setup Co2 SM, confirm engine does not detonate while under 5k EER.
:cl:
fix: Event B3 now functions as intended
/:cl:
=> HOTFIX: event B3 no longer nukes the SM

code/modules/mob/living/simple_animal/hostile/terror_spiders/white.dm
Grants white terror spiders the ability to force open powered doors.
White terrors are a tad weak. After the intial blitzkrieg they basically lose a lot of relevance as every door is shut and every vent is welded. This should slightly alleviate this problem.
Also definitely not because of a recent round where I was stuck in one room for ten minutes because all the doors were closed and all the reds were dead.
Created white terror, became white terror, forced door open, bit things.
:cl:
tweak: Gives White Terrors the ability to open doors.
/:cl:
=> Allows White Terrors to force open powered doors.

code/datums/statclick.dm
view_runtime right holders no longer need to right click on debug stats and vv them to access globals/controllers
we can already do it this is just easier
don't wanna set up a db but it's handled the same somewhere else so it should work just fine
=> allows view_runtimes to access the mc stuff easier

code/modules/mob/living/carbon/human/human_mob.dm
IDs in your PDA can no longer affect the color of your radio chatter when your PDA is in your PDA slot. I really should have done this sooner, but its taken me so long to track down.
Unintended consequence and bug of #20251. I've seen players abuse this to figure out who someone is when they're using a voice changing mask, but their ID is in their PDA
See above
:cl:
fix: IDs in your PDA no longer affect the color your radio chatter when your PDA is in your PDA slot
/:cl:
=> IDs in your PDA no longer affect the color your radio chatter

code/game/machinery/tcomms/nttc.dm, code/game/machinery/tcomms/tcomms_base.dm, code/modules/mob/dead/observer/observer_say.dm, code/modules/mob/hear_say.dm, code/modules/mob/living/simple_animal/parrot.dm
Ghosts will now not see duplicate names if the user's real name matches with their shown name.
Fixes a bug that was caused by NTTC configurations
(The bottom line used to say [Common] Zack Woodworth (Zack Woodworth (No id)) (follow) says, "Test")
Works with any type of voice changer
See above, and tested with a variety of voice changers
:cl:
fix: Observers should no longer see duplicated names in radio chat when someone has the correct name
/:cl:
=> Fixes an oversight with observers and ghosts

code/modules/mob/living/carbon/human/human_emote.dm
This fixes a runtime that occurs when a non-human uses the gasp emote.
Prevents a runtime error from occurring.
Spawned is a cyborg and emoted, checked for runtime.
Spawned in a a human species and emoted, checked for proper function and runtime.
NPFC
=> Fixes a runtime with gasp emote

code/modules/mob/living/simple_animal/hostile/terror_spiders/terror_spiders.dm
terror spiders can now pull non dense objects at normal speed
it's not a problem if a spider drags a gun away, it is a problem if they are pulling a locker, rather than hurting everything let's be more selective 
pulled a locker, pulled a welder
:cl:
tweak: terror spiders can now pull non dense objects at normal speed
/:cl:
=> terror spiders can now pull non dense objects at normal speed

code/game/gamemodes/wizard/wizloadouts.dm
Adds homing toolbox to the Greytider Wizard loadout
It's a greytider wizard, they like toolboxes so they get this cool spell Charlie made
Spawned in as a wizard, shit worked
:cl:
tweak: The wizard greytider loadout now has Homing Toolbox
/:cl:
=> Adds homing toolbox to the Greytider Wizard loadout

code/game/gamemodes/wizard/spellbook.dm, code/modules/clothing/suits/wiz_robe.dm
Greatly improves Battlemage Armor, giving it Syndicate Hardsuit grade armor with a recharging shield, along with spaceproofing. 
EDIT: At the behest of the voices in my head and on the balance team, the shields no longer recharge and return to 15 charges. Armor and spaceproofing remain.
Also buffs Archmage Armor with an extremely rapid recharging shield for admeme use.
Removes the armor charges since they're still worthless and will never return or be loved.
Battlemage armor sucks. You get exactly 15 hits before your armor is now utterly worthless as its base armor values are terrible.
The charges to replenish this are also a complete scam and not worth it in the slightest. The suit not even being spaceproof is insult to injury.
Now, it should be a proper set of wizard power armor that …
=> Buffs the Battlemage Armor, deletes Battlemage Armor charges

code/modules/surgery/organs/organ_external.dm
Partially reverts #21295
Decap chance now uses the original incoming damage values, to avoid spreading strangeness, and can no longer decap on the hit that maxes out the limb damage, similar to bones, to avoid things like the syndicate chainsaw decaping 20% of the time on the second hit.
Doubled decap chance was bad. There was no 50% spread like the author indicated, said 50% spread *only* happens on the hit that maxes out a limb, when the damage left over is equal to half the weapons force. The 3rd esword hit meets that exact threshold, which is why the author was confused, I believe. 
Since we fix the strangeness involving this by checking values earlier, we make it like broken bones, in which the limb must be fully damaged before decaps can happen, to avoid things like having a 20% …
=> fixes decap chance, makes it more like bone breaks

code/datums/diseases/advance/symptoms/vomit.dm, code/datums/status_effects/debuffs.dm, code/modules/mob/living/carbon/carbon.dm, code/modules/mob/living/carbon/human/human_life.dm, code/modules/reagents/chemistry/reagents/drugs.dm, code/modules/reagents/chemistry/reagents/medicine.dm
This PR removes stun from vomit proc, instead it confuses and slowdowns you, if its blood vomit(IB), it knockouts you.
Random stuns while two IBs, random stuns while toxin damage is bad.
Having no random stuns is good for me so i think this PR should be fine.
Compiled, got damage
:cl:
tweak: Vomit no longer stuns, instead it makes you Confused and Knockouts you if its vomit from IB.
/:cl:
=> Vomit no longer stuns

code/datums/components/defibrillator.dm
Title. There was no signal sent so the modsuits didn't subtract charge, same went for normal defibs that have charge.
Kinda buggy/exploity, the entire idea of the modsuit defib is that it has a drawback alongside it being able to be wielded in 1 hand.
Combat defibbed a few times, almost got locked out of my suit.
:cl:
fix: Fixed combat defib modules not subtracting charge
/:cl:
=> [s] Fixes Nukie modsuit combat defibs not subtracting charge on harm mode

code/game/objects/structures/crates_lockers/closets/secure/personal.dm
This fixes https://github.com/ParadiseSS13/Paradise/issues/11001, an oversight that allows for the use of guest passes on personal lockers. 
It fixes a labeled oversight. It prevents personal lockers from being accessed so easily, through faking a name or from cloning access. 
Created a guest pass.
Tested on a personal locker while wearing a regular ID and without an ID.
:cl:
tweak: Tweaked personal locker access to disallow the use of guest passes
/:cl:
=> Guest pass can not be used on personal lockers. 

code/modules/events/event_container.dm
Decreases the weight of blob from 30 to 20. Weight added per officer decreased from 5 to 4.
Decreases the weight of xenos from 20 to 15. Weight added per officer decreased from 4 to 3.
Decreases the weight of terrors from 20 to 15. Weight added per officer decreased from 4 to 3.
On a high pop round, there is an approx. 31.6% chance per major event roll that a destructive event(Biohazard or meteors) will roll. This PR lowers that value to approx 21%. In my opinion, and in the opinion of a few members of the community, biohazards have been rolling too often. This is unsurprising, given that there are on average 2 major rolls per round, that gives us an average chance of a destructive midround of about ~47%. In my opinion, this is far too high.
:cl:
tweak: decreases the odds of biohazards …
=> Decreases biohazard weights by roughly 25%

code/modules/mob/living/silicon/ai/ai_mob.dm
Increases the CPU time gained from hacking APCs to 15 from 10.
Considering the time expenditure and risk of being caught, APC hacking is a bit sad in its reward. This should hopefully remedy the issue.
- Spawned in
- Became AI
- Malf'd
- APCs give 15 points now
- August 28 Plasmafire Incident
:cl:
tweak: Buffed Malf AI, hacking APCs gives 15 points now
/:cl:
=> Buffs Malf AIs

code/modules/surgery/organs/organ_external.dm
Splints now no longer hardstun you when it pops off, as long as the limb it is on doesn't have a bone fracture.
Splints also now Weaken you when it pops off a limb with bone fractures.
Currently, if you use a splint on a healthy limb, or have your damaged limb fixed after you splint it but forget to remove the splint, it will pop off after a while and then hardstun you for four seconds.
While it makes sense for this to happen to limbs with bone fractures, making splints still punish you with a debilitating stun when you have either spent TC on a prototype nanite injector or went to Medbay to get your fractures fixed is... not ideal. That really seems like an oversight and this PR aims to fix that. The splint still pops off, but you won't get stunned for four seconds.
The change from …
=> Tweaks how splints work on healthy limbs

.github/CONTRIBUTING.md, .github/PULL_REQUEST_TEMPLATE.md
Adds some public-facing info about the "Allow edits and access to secrets by maintainers" checkbox.
By leaving this box ticked maintainers can make changes to your branch.
We currently have no contributor-facing information about this, and no real policy on when we should and should not use it.
This PR will give some info to contributors about the use of this permission, and dev policy will follow for control over when we should use it, if this PR is passed.
=> Makes it clear that maintainers can edit a branch if you allow them

code/modules/food_and_drinks/food/foods/sandwiches.dm, code/modules/food_and_drinks/recipes/recipes_microwave.dm
Changes Roburger name to Hamborger
Adds a new description for the item
Hamborger seems like a more natural sounding name than roburger and I feel the name more accurately alludes to what it does. It is a "borger". The description gives a better hint at what this burger does.
The name and description are changed
:cl: RatNut
tweak: Renames roburger into hamborger
tweak: New examine description
/:cl:
=> Roburger renamed to Hamborger and new description for clarity

code/game/objects/items/stacks/tiles/tile_types.dm, code/modules/mob/living/silicon/robot/robot_modules.dm
Adds cat walk tiles for robots to use. 
Aesthetically catwalks in maintenance is neat, so drones and cyborgs being able to fill the maintenance tunnels up with catwalks should be cool. 
Checked if both had the catwalks, they both did. Also checked if the energy correctly discharged/recharged via recharges and picking up existing catwalks. 
:cl:
add: Cyborgs and maints drones can now place catwalk tiles
/:cl:
=> Cyborgs and drones now get catwalk tiles

code/modules/antagonists/vampire/vamp_datum.dm, code/modules/antagonists/vampire/vampire_powers/umbrae_powers.dm, code/modules/antagonists/vampire/vampire_powers/vampire_powers.dm, code/modules/antagonists/vampire/vampire_subclasses.dm, code/modules/mob/living/carbon/human/species/_species.dm
Extends Vampire Night Vision from `3` to `7` tiles once they reach 500 blood.
For a creature that attacks from the darkness, you have absolute PISS poor night vision until you reach Full Power.
This gives Vampires a slight bonus when they reach 500 blood.
1. Ran around in the dark at various blood levels.
:cl:
add: Adds Advanced Vampire Night Vision at 500 Blood as a passive.
/:cl:
=> Gives Vampires Stronger Night Vision at 500 Blood

code/modules/reagents/chemistry/machinery/chem_dispenser.dm, tools/ci/check_grep.sh, tools/ci/check_grep2.py
fixes a to_chat runtime
adds a check to check_grep.py to make sure that to_chat procs have a target argument 
fixes the .proc/ checker not working
this stuff happens and is bad, to_chat procs should have a target and it happens enough where the author should know something is wrong if they forgot to add one.
it works, wish there was an documented way for new contributors to know how to run these on local
:cl:
fix: you are now notified that you cannot use chemical dispensers while they're unanchored 
/:cl:
=> fixes a to_chat runtime, lints now throw an error if a to_chat proc lacks a target argument

code/_onclick/hud/guardian_hud.dm
Prevents Holoparas from being able to Manifest while their user in a Stealth Implant
We removed Contortionist + Holopara for a reason.
This is the same issue.
Tested manifesting while in the Stealth Implant Box
(god this was the first time I had to multikey for testing, pain pain pain)
:cl:
tweak: prevents Holoparasites from Manifesting inside Stealth Boxes.
/:cl:
=> [s] Holoparasite Can No Longer Manifest in Stealth Boxes

code/modules/mob/language.dm
This PR does two things:
1. Adds a bunch (35) of names, a bunch of (14) jobs, and a couple (6) clans to the generator.
2. Makes random name generator support all three naming schemes kidans have.
1. Kidan names are EXTREMELY repetetive. You can randomize twice and there is a good chance SOMETHING will repeat.
2. Most people aren't even aware of this, but kidans actually have three different naming schemes, I will show off with an example:
- Krek, Worker Of Clan Orlan (is the "classical" scheme)
- Krek Orlan (is a modern scheme, adapted by kidans who are working with other species, for simplicity)
- Krek (is a scheme for lower social classes)
Enforcing all three code-wise makes them (hopefully) more common, even with limited kidan player numbers. I've never seen a Kidan using the second …
=> Kidan random name generator updates.

code/game/objects/items/weapons/storage/storage_base.dm, code/game/objects/structures/tables_racks.dm
This PR:
1: Changes putting items on the table logic. Now you will only put item on the table if your intent is HELP.
2: Changes putting items in storage items(such as backpacks). If its location is something living(like you), it will work like it works right now, any intent. If its location is something else(like floor), you will only put items in it on HELP intent. 
This logic already works with closets and its fine. There is a reason why your intent is not harm and you still not want to put your weapon on the table.
This logic already works with lockers and crates and i see no reason for other storage items and objects not work like that.
There is a lot of reasons you want to keep not harm intent and still not put item on the table / in the backpack
Compiled, tried putting items in …
=> No more accidental put baton on table/in backpack

code/game/objects/structures/crates_lockers/closets/secure/security_lockers.dm
- NTR's, Blue's and Magi's lockers now start with their PDA cartridges (Easy-Record DELUXE for NTR and Magi, R.O.B.U.S.T. DELUXE for Blue)
- Blue's and NTR's lockers now start with spare headsets, magi had one already apparently
- Blue's locker now starts with his duffel, his backpack and his satchel
- Cartridges and headsets - in case you loose your PDA/headset, you should be able to get them back. Currently, you either need to bother another head (HoS for blueshield-level comms and R.O.B.U.S.T. cartridge, captain for NTR-level comms), or can't get a replacement at all (easy-record cartridge)
- Gives blueshield bags, so you can swap between them, for drip.
Spawned in, checked every locker, stuff was there.
:cl:
tweak: Blueshield, NT Representative and Magistrate now have spare PDA …
=> VIP lockers now get more spare gear.

code/game/objects/buckling.dm, code/game/objects/structures/bedsheet_bin.dm, code/game/objects/structures/stool_bed_chair_nest/bed.dm, code/game/objects/structures/stool_bed_chair_nest/chairs.dm, code/modules/mob/mob_movement.dm
Clicking on a bed/bedsheet/chair when pulling something, will pull the person onto the tile. This is similar to clicking turfs around you to move something. If you're not pulling something, it acts normally. Buckling someone down, will also stop anyone currently pulling them, this minimizes "scuffed-ness" when clicking multiple times on a chair. (This doesn't already have any balance implications, since you already can't start pulling or continue pulling someone that is buckled.)
Makes it easier to click on stuff for quality of life, clicking on tiny pixels around chairs is annoying
Spawned a skrell, clicked on a chair, bed, and bedsheet, the skrell moved on top. I buckled them, and I was no longer pulling them.
:cl:
tweak: Beds, bedsheets, and chairs can now be clicked on to move the …
=> Allows for easier pulling onto beds and chairs, buckling someone stops anyone currently pulling them.

code/datums/status_effects/buffs.dm
-​ Makes Rod of Asclepius Hippocratic Oath buff no longer waste heal points on completely healthy targets
-​ Allows the Oath to heal robotic limbs (it could already heal silicons)
-​ Makes the Oath's heal particles more accurate
-​ Refactors and cleans up the Oath's code a bit
The current state of the Rod is pathetic. Only a few seconds after activating it, you've already wasted all of your points trying to heal yourself, remove IBs/fractures/burn wounds from your already perfect condition limbs, and other healthy people nearby. This results in the rod only ever really healing you, *very rarely* leaving enough points for healing anybody else.
The change to allow it to heal robotic limbs is just logical consistency with it healing silicons; don't see a reason why it shouldn't.
Spawned in …
=> Buffs Rod of Asclepius

code/modules/events/bureaucratic_error.dm, code/modules/events/event_container.dm
**Tweaks**
Decreased the event weight from 80 to 40.
Number of jobs affected is now 2 (6 -> 2).
Number of job slots affected has been increased by one (+-1 -> +-2).
Added a "Contact your local HoP to solve this issue" line to the event announcement.
Gave some line breaks to the message ghosts receive.
**Fixes**
The number of jobs being affected is now correct (caused by giving the var/error the value of 0 without making the necessary adjustments during the initial PR reviews, thus increasing the limit of affected jobs by one)
Cyborg job has been included into the event blacklist.
The event weight i initially gave  was too much from what i intended (which is for an event that a player would see once in a while). With this new weight, the chances for it to trigger during the round will be …
=> Bureaucratic error event tweaks

code/game/objects/effects/anomalies.dm
Title. Cryogenic anomalies now shoot at people who are close to them directly in addition to shooting at random angles around them. Their projectiles now also stun you for half a second, making you drop what's in your hand and freeze in place for a moment.
Cryogenic anomalies are pretty weak if you wear internals. This'll add at least a little threat to approaching one without appropriate cold protection.
Loaded in and got frozen by an anomaly
:cl:
tweak: Cryogenic anomalies are now more dangerous
/:cl:
=> Buffs cryogenic anomalies

code/__DEFINES/vending_defines.dm, code/game/machinery/vendors/contraband_vendors.dm, code/game/machinery/vendors/departmental_vendors.dm, code/game/machinery/vendors/generic_vendors.dm, code/game/machinery/vendors/vending.dm, code/game/machinery/vendors/wardrobe_vendors.dm, code/modules/events/brand_intelligence.dm, paradise.dme
Makes brand intelligence less specific about the type of the leader machine in its initial announcement. It'll now list off something like "supplies vendor", "food vendor", or "departmental vendor". Some names might be easier to work out than others.
Also adds some extra debug logs to brand intelligence.
When you hear that the infected machine was a virodrobe, it's pretty easy to go straight there and dismantle it, ending the event. This should make it a bit harder to determine which exact kind of vendor was infected, while still pointing the crew towards the actual culprit.
Loaded in, ran the event, things worked.
:cl:
tweak: Brand intelligence is now a bit less specific about the type of vendor first converted.
/:cl:
=> Makes brand intelligence less specific

code/game/gamemodes/miniantags/guardian/guardian.dm
Title. Also makes every call of `lay_down` and `stand_up` to instantly upright the holopara, in case of adminbus
It's a not very noticable thing if a holoparasite rests, and it can cause confusion and makes people think the holopara is rooted for some reason
Resolves #21086
Resolves #9794
Tried to rest as a holopara, but nothing happened
:cl:
tweak: holoparasites now can't rest anymore
/:cl:
=> Stops holoparasites from resting

code/datums/spells/ethereal_jaunt.dm
This PR tweaks relaymove proc of blood pool(hemomancer spell). Previously if you try to move diagonally and turf to the diagonal direction is blocked, you would not move at all and you will get message "Something is blocking the way!".
After this PR if diagonal move is blocked, you will try to move in cardinal directions which are parts of diagonal movement like it works with default walk. (you try to move diagonally into the wall, you move in parallel with wall instead)
Unexpected behaviour of blood pool move is not cool, blood pooling into a door before this PR was really hard, you need to stand accurate at the door and only then move into, now you can just bumb it as default walk.
Compiled, tried blood pooling
:cl:
tweak: Blood pool movement now tries to move in cardinal directions if …
=> Blood pool now tries cardinal move if diagonal is blocked

code/modules/clothing/glasses/engine_goggles.dm, code/modules/power/engines/singularity/singularity.dm, code/modules/power/engines/supermatter/supermatter.dm
Allows Radiation Mode to protect against SM Hallucinations and the Singularity.
Why the mode that allows you to carefully avoid radiation doesnt also protect you against the most radioactive things on Station is a bit wild.
1. Stared at code till I went crazy.
2. Stared at an SM till I didnt go crazy, cause the code works.
:cl:
tweak: Radiation Goggle Mode now prevents SM Hallucinations and Singulo Staring.
/:cl:
=> Engineer Scanner Goggles on Radiation Mode Prevent SM Hallucinations/Singulo Staring

code/modules/mob/living/silicon/robot/robot_modules.dm, code/modules/projectiles/ammunition/energy_lens.dm, code/modules/projectiles/guns/energy/laser.dm
Removes Stun Arm from the Safety Override for EngiBorgs.
Adds the Proto Emitter Gun to the Safety Override for EngiBorgs.
There is no reason for the Crew to be able to make pseudo-SecBorgs. We dont need more insta-stuns for Antags to deal with. This was discussed with GAs/HAs before being made, as we see this as an issue.
Given that some Antag Roboticists used this for evil, I gave them a ranged emitter that's slightly weaker than the Malf AI one.
Tested the Safety Override on myself, it works.
:cl:
add: Added Proto Cyborg Emitter to the EngiBorg Safety Override.
del: Removed Stun Arm from the EngiBorg Safety Override.
/:cl:
=> Removes Stun Arm from Safety Override, Adds Proto Emitter

code/datums/uplink_items/uplink_traitor.dm, code/modules/paperwork/pen.dm
The plasmaman fireproof injector and the IPC supercharge implant can no longer be found in surplus crates.
The Skrell love injecting pen has had its sprite and appearance changed to that of the fancy pen, to make it appear different then the sleepy pen.
Randomly getting items you cannot use due to species locks is bad game design. The love pen is now visually distinct, preventing people from thinking they just overdosed a target on ketamine, when in fact they made them feel all warm and cuddly. 
Spawn surplus crates, confirm no overcharge implants or fireproofing injectors were given.
Confirm pen sprite and appearance was properly updated.
:cl:
fix: You can no longer get species exclusive traitor items from surplus crates.
/:cl:
=> Tweaks species specific traitor items

code/modules/martial_arts/cqc.dm
If a chef learns CQC from the traitor item, he can use it outside of the kitchen. Multiple uses of CQC now doesn't add multiple defence stance actions
Fixes #21995 
Chef should be able to use CQC outside of kitchen when they purchase a CQC manual, multiple defensive stance icons unnecessary 
Spawned in as chef, robusted things in the kitchen, made sure couldn't robust outside. Gave chef CQC, could robust where he pleases. Used multiple CQC manuals, didn't get multiple defensive stance icons, CQC still worked, multiple defence stance icons is not good
:cl:
fix: Using CQC manual as chef now allows you to use CQC outside of the kitchen
fix: Multiple uses of CQC manual don't give you multiple defensive stance actions
/:cl:
=> Traitor chef can use traitor CQC, no multiple defensive stance actions

code/game/machinery/constructable_frame.dm
Adds a check to determine if circuit boards have components required.
Adds a single cable coil to the components required to make the Nanotrasen Merchandise Vendor.
Returns a description of "Does not require any more components." if a circuit board has no components required.
Changes the variable "name" to "board_name" of /obj/item/circuitboard/merch.
Fixes #22141 
Fixes a runtime error.
Future proofs for boards that may not have components.
Spawned in, constructed Nanotrasen Merchandise Vendor with cable coil.
Tested with board that did not require components, and confirmed no runtime occurred.
Tested with Soda Fountain at the same time to confirm full functionality
:cl:
tweak: Changed required component for the Merchandise Computer Circuit Board to require one cable coil and one matter …
=> Adds Check for Circuit Boards Having Components

code/modules/food_and_drinks/food/condiment.dm
Removes the ability to feed simplemobs chemicals or drinks with condiment bottles (It does jack shit anyways)
It's a bug
Fixes #18915 
Also cleans up some surrounding code
Tried to feed a guardian salt, to prepare it for when it's master would die, it failed :(
:cl:
fix: You can no longer feed simplemobs with condiment bottles
/:cl:
=> You can't feed simplemobs with condiment bottles anymore

code/modules/mob/living/carbon/human/human_mob.dm
Fixes a runtime that happens when the crew monitor tracks a crew member with sensors but without an ID.
Prevents a a few hundred runtime errors from being generated during a round.
Used crew monitor to check to see if a runtime error occurred.
Tested ID behavior if in ID slot and PDA.
NPFC
=> Fixes a runtime when a crew monitor is used

code/game/objects/buckling.dm
Hotfix for a runtime that occurs when buckling players
Prevents a runtime error from occurring. 
Pulled and buckled mob and checked for runtime.
NPFC
=> Hotfix for buckling runtime

code/game/turfs/simulated/floor/lava.dm
Mapping lava turfs now have the proper atmos on them, and use late initialize to change the turfs after atmos is setup
14000 roundstart active turfs on lavaland is bad. Performance is good.
Confirmed all 3 lava types worked as expected.
:cl:
fix: Fixed lava / liquid plasma / chasms having no air roundstart on lavaland
/:cl:
=> fixes about 14000 roundstart active turfs due to funny init issues.

code/game/machinery/doors/airlock.dm
This commit adds a check for non-closed airlocks during the repair logic, and returns the user a warning message that airlocks must be closed for repairs to work. This avoids the animation cycle of an interrupted repair attempt, and clarifies that repairs cannot be attempted in this state.
Fixes #13724, clarifying to a user why an airlock repair is not possible in this state.
* Damage an airlock to the point it needs repairs
* Attempt repairs whilst airlock is **not** closed, and observe no animation cycle and a warning message
* Attempt repairs whilst airlock is closed, and repairs work as normal
:cl:
fix: Non-closed airlocks no longer animate a failed repair cycle, and warn the user of their inability to be repaired.
/:cl:
=> Warn user during open airlock repair attempts

code/modules/mod/mod_actions.dm
This PR adds some missing `UpdateButtonIcon()` calls from https://github.com/tgstation/tgstation/pull/63836
Fixes #22161, updating UI buttons on interactions where required.
* Wear a modsuit
* Interact with the "Activate MODsuit" button, and have the button react to interactions.
:cl:
fix: MODsuit button UI interactions now update the icon if required.
/:cl:
=> Add missing UpdateButtonIcon() calls for Modsuits

code/modules/surgery/organs/mmi_holder.dm
Fixes being able to bypass a curse via irc
Escaping curses is bad.
Confirmed: 
- You can not escape a curse
- You can however irc someone without cursing them randomly.
:cl:
fix: Fixed being able to avoid magical curses via a metal body.
/:cl:
=> [s] You can't escape a curse.

code/game/objects/items/weapons/RCD.dm
Allows you to refill combat RCDs past 100 units of matter.
fixes: #22179
Bug bad
Be a skrell
Use 30 matter from combat RCD
Refill combat RCD
Matter is now at 490 units.
:cl:
fix: Combat RCDs can be refilled past 100 units of matter.
/:cl:
=> Fixes combat RCD refilling

code/game/objects/items/devices/camera_bug.dm
Fixes #20999 and Fixes #22146
Items should work
1. Gave myself a camera bug from the uplink
4. Used it while the original room had/didnt have power
3. Spawned the ruin that has a camera bug
4. Used it while the original room had/didnt have power
:cl:
fix: Camera bugs will no longer occasionally not work.
/:cl:
=> Fixes Camera Bugs not working

code/game/objects/effects/anomalies.dm
Fixes a runtime where a gravitational anomaly would try to pick a gravity generator on the Z-level even if there aren't any gravity generators on the Z-level.
fixes: #22054
Runtime bad.
Spawn a gravitational anomaly
It detonates, disabling the gravity generator, no runtimes are generated
Spawn a second gravitational anomaly
It detonates and nothing happens, no runtimes are generated
=> Fixes runtime grav anomaly disabling gravity generator

code/modules/surgery/limb_augmentation.dm
Fixes a bug where you were able to start the augmenting step of augment limb with non-limb parts that are subtypes of robot_parts (Eg. armour plating, binary communication device)
Fixes: #11635
Unintended behaviour.
Be a skrell
Start augment limb surgery on left arm
Perform first 3 steps
Attempt to augment using armour plating, does not work
Attempt to augment using robotic right arm, does not work
Attempt to augment using robotic left arm, works
Robot fish
:cl:
fix: You can no longer augment limbs with non-limb robot parts.
/:cl:
=> Prevents augmenting with non-limb robot_parts

code/game/turfs/simulated/floor/asteroid_floors.dm
Hostile asteroid mobs will no longer spawn if something important is in a 12 tile range again
Lavaland generation code working as intended is good.
Confirmed that the code was updated to account for the fact spawners are used rather than mobs spawning directly, and that it was returning due to this factor.
:cl:
fix: Fixed lavaland mobs clumping too close to megafauna or tendrils occasionally.
/:cl:
=> Fixes lavaland mob spawning mechanics

code/datums/uplink_items/uplink_traitor.dm, code/modules/antagonists/traitor/contractor/items/contractor_kit.dm, code/modules/clothing/clothing.dm, code/modules/clothing/under/syndicate_jumpsuits.dm, code/modules/mob/living/carbon/human/human_mob.dm
Adds the "Big Brother" Obfuscation Suit to the Uplink for Agents for `20TC`.
This suit prevents all tracking from AI cameras as well as makes the user invisible to the AI (just like Changeling Cham Skin).
It is unable to be purchased by Nuclear Operatives. It has been added to the Contractor Starter Bundle's possible rolls.
This is a reversal of the Radio Jammer. Instead of hiding everyone ELSE talking, this hides the user.
1. Ensured Traits added/removed properly.
2. Ensured the AI could not track the user of the suit when the suit was being worn.
3. Ensured the AI could not see the user of the suit when the suit was being worn.
:cl:
add: Added the Syndicate "Big Brother" Obfuscation Suit to the Traitor Uplink.
/:cl:
=> Adds the Syndicate "Big Brother" Obfuscation Suit

code/modules/assembly/signaler.dm
You can now send a signal with ALT+CLICK.
You can now transfer the code/frequency by using a signaler on another (based on https://github.com/tgstation/tgstation/pull/23340).
I judge it to be good quality of life additions to the game, allowing for you to set multiple signallers more easily.
- Tested by using the signal with the new shortcut
- Did transfer the settings multiple times and tested it with an airlock
:cl:
tweak: Remote signaler: you can now send a signal with ALT+CLICK
tweak: Remote signaler: You can now transfer the code/frequency by using a signaler on another
/:cl:
=> Remote signaler tweaks

code/game/objects/effects/decals/Cleanable/humans.dm
Prevents blood from attempting to dry if the blood tile no longer exists
We don't need to waste a timer slot on something that doesn't exist
I'm not entirely sure how to reproduce this, but src will only be null in this case if it is being qdeleted, therefore it is most likely being qdeleted
Hopefully not playerfacing
=> Prevents blood from attempting to dry if said blood no longer exists

code/modules/mob/mob_movement.dm
fixes people not being unbuckled from stuff if they're being pulled (eg a chair)
Bugfix, kind of an issue if you're an antag or sec
Compiled, ran, and tied down a skrell
:cl:
fix: Pulled people can be unbuckled from objects
/:cl:
=> fixes people not being unbuckled from stuff if they're being pulled

code/modules/antagonists/vampire/vamp_datum.dm
Fixes a runtime where a MMI had no DNA, thus causing the `make a vampire` procs to runtime
Runtimes bad
Put a vampire brain inside a MMI, shit didn't runtime 
NPFC
=> Fixes a runtime that happens when you put a vampire brain inside a MMI

code/modules/mob/living/silicon/robot/robot_mob.dm
Makes it so that cyborgs can no longer instantly bolt doors, unless emagged or malfunctioning, as intended in #22084
fixes: #22278
It'll work completely, for sure this time, I swear.
Be a cyborg
Try and bolt a door, it takes 3 seconds
Add the "syndicate" faction to my faction list
Bolting is now instant
:cl:
fix: Cyborgs can no longer instantly bolt doors unless emagged or malfunctioning.
/:cl:
=> Fixes cyborg bolting so it is no longer instant. Again.

code/modules/antagonists/changeling/powers/humanform.dm, code/modules/antagonists/changeling/powers/lesserform.dm
Fixes an oversight with transformation code that allowed some annoying things to happen
We really shouldn't have this in the game.
Also my god transformation code has so many oversights it's unreal
Hit myself a few times with an armblade, did some black magic and checked  the damage values before and afterwards
:cl:
fix: Fixed an issue pertaining to monkeys and changelings
/:cl:
=> [s] Fixes a monkey issue with changelings

code/__DEFINES/dcs/signals.dm, code/modules/mob/living/carbon/human/human_mob.dm
Adds some missing to_chats in the new CPR code which cause it to consistently runtime.
~~I thought we had a CI check for this~~
Fewer runtimes better, and I'm also concerned that this might cause some issues with people not being able to repeatedly perform cpr.
Compiled
:cl:
fix: Fixes some errors in CPR code which might cause it to stop suddenly
/:cl:
=> CPR hotfix

code/game/gamemodes/revolution/revolution.dm, code/game/objects/items/weapons/implants/implant_mindshield.dm, code/modules/antagonists/revolutionary/team_revolution.dm
Fixes some stylistic code choices with revs, including comments.
This also fixes an issue where only one headrev would spawn at the beginning of a rev round. Woops.
Style is good, requested by S34N.
Compiles, all changes work the same logically.
Headrevs can now spawn more than 1 at a time at roundstart.
:cl:
fix: Revolutions should no longer only start with one headrev.
/:cl:
=> Fixes some issues with revs

code/modules/mob/living/simple_animal/bot/bot.dm
Fixes some weird behaviour that mostly appeared in cleanbots.
What would happen is, upon being built, there was a decent chance that instead of cleaning the mess next to it, the cleanbot would travel more than half the screen to find a random speck of blood. This PR fixes that and makes it check the closest tiles first.
Simple robots should be behaving as expected.
Made a big mess, had a cleanbot clean it all up.
:cl:
fix: Fixed cleanbots not cleaning the closest-by mess
/:cl:
=> Fixes (clean)bots behaving erratically

code/modules/surgery/organs/pain.dm
Fixes what seems like an indentation error + an operator error, causing custom_pain messages to have no cooldown at all.
There is one downside to this, and that is in the case of multiple burn wounds/bone breaks. When you have more than two, the messages will only cycle between two set limbs (probably decided in how the `bodyparts` list is set up), and you will not get any messages for the rest of the pain. Below is how it looks after walking for around ~10 seconds with 2 burn wounds:
If it is preferred that there is indeed a message for each limb, I'll gladly take the step to refactor the custom pain message for burn wounds/broken bones to be handled on the limbs themselves, so the cooldowns can be handled separately.
Having multiple burn wounds/broken bones absolutely spams your chat if …
=> Fixes custom_pain spamming your chat if you have multiple burn wounds/broken bones

code/game/gamemodes/miniantags/abduction/machinery/dispenser.dm
Fixes https://github.com/ParadiseSS13/Paradise/issues/22289, an oversight created when gland dispensers were moved to TGUI.
We don't need players grabbing organs from the dispenser that could spawn on Lavaland.
Tested dispenser access as non-abductor.
Tested dispenser access as abductor.
:cl:
fix: Fixed gland dispenser access
/:cl:
=> Fixes gland dispenser access

code/modules/food_and_drinks/food/foods/pizza.dm
You can now alt+click a pizza bomb box like any other pizza box and it will still allow you to set the time/explode.
Fixes: #22299
Bug bad
Be a pizza addicted skrell
Open pizza bomb box by alt+clicking.
Set the timer to 1.
Open pizza bomb box again by alt+clicking
There's now skrell all over the walls.
:cl:
fix: Pizza bomb now behaves as expected again when alt+clicked.
/:cl:
=> Pizza bomb now behaves as expected when alt+clicked

code/modules/recycling/disposal.dm
Fixes a runtime that popped up in https://github.com/ParadiseSS13/Paradise/pull/22062 which causes runtimes when things without throwers end up landing in disposals.
Runtimes bad, also this could be causing weird things with disposals, particularly on farragus.
Loaded in, set up a system that should have caused the same behavior, didn't runtime
:cl:
fix: Things being thrown into disposals by other machines should now no longer runtime.
/:cl:
=> Fixes a runtime when things are thrown into disposals by non-mobs

.github/CONTRIBUTING.md
Adds @lewcc as a commit access member in documentation
Should be properly noted
=> Adds lewcc as commit access in documentation

code/datums/uplink_items/uplink_general.dm, code/game/objects/items/weapons/AI_modules.dm
Drops the price of the syndicate ai module from 60 tc to 15 tc (also the syndi tech cuz you know whyyyyy)
so, I'm just assuming people do not actually know what this item does.
Although in admin logs it suggests this is a zeroth law, this is an ion law, ion laws can be cleared using a reset board, this item is not good. it is not 12 tc legacy good, it is still probably not good for 3 tc considering you can just use a freeform module. it is somewhat easier to use, but not 60 tc easier to use.
To explain how fucking awful this item is, the hacker kit, the bundle themed around hacking, does not have this item in it because it literally just does nothing. 
also this is the most sane change i've made in the past 72 hours and my brain no longer hurts
My map cut off first time testing this …
=> drops the price of the syndicate ai module significantly

code/modules/mod/mod_types.dm
Engineering modsuits now start start with tether module
This module doesn't see too much use, since people either go jetpack or bust, even with high tech levels.
This makes some IC sense, at least *some* emergency equipment for engineering, as well as a way to give them some basic space mobility to make up for no jetpacks from the EVA room.
spawned as engineer
checked suit storage
has tether module
tested in space for fun why not.
:cl:
tweak: Engineering modsuits now start start with a tether module
/:cl:
=> Engineering modsuits now start start with tether module

code/modules/surgery/organs/subtypes/unathi_organs.dm
Title. The precise amount is ~30% of the amount of oxygen available to them on lavaland, so they should still be able to breathe very comfortably.
The problem lies in two points:
- While in crit, you start taking respiratory damage (as well as from other sources, like a certain species of lavaland mushrooms). This normally isn't a big problem, because most species that can take respiratory damage also breathe, which with enough of the required gas, provides resp. damage healing.
- Ash walkers don't breathe any gases to heal from.
This makes any respiratory damage they take basically permanent, which I hardly buy is an intended side-effect of letting ash walkers exist safe from lavaland's low pressure. Making ash walkers need a small bit of oxygen should also nerf their resistance to space …
=> Makes ash walkers breathe a small bit of oxygen

code/modules/assembly/signaler.dm
Tracks all signalers in the Investigate Round Objects verb.
Funnily enough, this isnt tracked in bombs, so we'll track it in its own area. This makes finding out who blew up things easier.
Only having the last 10 signalers to check is very wacky - I for one would rather see all signalers.
Clicked a buncha signalers.
:cl:
add: Added logging for signalers to the investigate verb.
/:cl:
=> Adds Signalers to the Investigate Round Objects Verb

code/controllers/subsystem/non_firing/SSmapping.dm
makes the lavaland theme log sound more rational
Before:
``"We feel like /turf/simulated/floor/plating/lava/smooth/lava_land_surface/plasma today..."``
After:
``"We're in the mood for liquid plasma today..."``
Same vibe, significantly less fucked up execution 
Crazy? I was crazy once. They locked me in a turf, a uninitialized turf, an uninitialized turf with string typepaths, and uninitialized turfs with string typepaths make me crazy
Looked at the thing in game
:cl:
tweak: Lavaland theme log now displays name vs typepath
/:cl:
=> makes the lavaland theme log sound more rational

code/game/turfs/simulated/floor/chasm.dm
As it says on the tin. To build over a chasm you now need a screwdriver in the offhand for the rod stage.
Presently, if Lavaland rolls chasms, the labor camp is completely useless as prisoners can just... build out willy nilly. This makes it so you need the most basic of tools to build across chasms - screwdrivers fit in boxes so miners shouldn't have issues with using them and they can still build over to labor camp if they feel so inclined.
See above. Almost made a silly mistake and made it consume the rod even if it failed.
:cl:
tweak: Building across chasms now takes a screwdriver in the off-hand.
/:cl:
=> Makes building on chasms take a screwdriver

code/modules/mob/living/silicon/robot/drone/drone_items.dm
Allows cyborg magnetic grippers to be able to pick up igniters.
There are 3 things that this actually allows borgs to do, and that is repair the cremator if it is destroyed.
Anything you can do otherwise with the igniter, like making sparks, is already something a borg can do just fine. If they wanted to make bomb assemblies with these, they would still need actual humanoid hands to do so. 
Also they can build ORMs now
Oh, and malf borgs can construct stunprods, at the cost of their ziptie module
This is just some QOL for borgs, so they don't need a humanoid to put in the igniter for them.
Became an engiborg, picked up an igniter.
:cl:
tweak: Engiborgs can now pick up igniters
/:cl:
=> Allows engiborgs to pick up igniters

code/game/jobs/job/syndicate_jobs.dm
This gives the Syndicate Officer a Hardened Nutriment Pump Implant Plus.
Syndicate officers should not need to experience starvation. 
Joined as Syndicate Officer and checked for appropriate implant. 
:cl:
add: Added hardened nutriment pump plus implant to Syndicate Officer
/:cl:
=> Adds a hardened plus nutriment implant for Syndicate Officer

code/game/gamemodes/nuclear/nuclearbomb.dm, code/game/machinery/iv_drip.dm, code/game/machinery/machinery.dm, code/game/objects/objs.dm, code/game/objects/structures.dm, code/game/objects/structures/crates_lockers/closets.dm, code/game/objects/structures/crates_lockers/crates.dm, code/game/objects/structures/engicart.dm, code/game/objects/structures/janicart.dm, code/game/objects/structures/stool_bed_chair_nest/bed.dm, code/game/objects/structures/stool_bed_chair_nest/chairs.dm, code/game/objects/structures/stool_bed_chair_nest/wheelchair.dm, code/game/objects/structures/tables_racks.dm, code/modules/mob/living/carbon/human/human_movement.dm, code/modules/reagents/reagent_dispenser.dm, code/modules/vehicle/ambulance.dm
Reverts PR #21056
You no longer have slowdown while pulling structures
To quote the PR that added this change
``There is gamer move in current build, you pull crate or something behind you and your chaser can not shoot you nor reach you which is kinda stupid. This PR makes person trying to defend yourself by pulling crate reachable. Doesnt affect pulling humans or enything else.``
That PR did not accomplish this goal. Structure pulling was still extremely effective when done in close quarters hallways (1 by 1s on maps like shepard, where even before this change locker pulling was at it's most viable) and the most common in those hallways. The most frustrating form of this tactic is when it was used with meth/any speed chemical, and even then you can still use it and you'll have a speed …
=> Reverts Slowdown on pulling #21056

code/game/machinery/suit_storage_unit.dm
SSUs actually drop contents on destruction now.
Stuff should not disappear into the aether.
Broke the shit out of an SSU.
:cl:
fix: SSUs drop contents on destroy now.
/:cl:
=> SSU `Destroy()` Fix

code/modules/power/engines/singularity/collector.dm
Adds a check to prevent multiple rad collectors from being anchored on the same turf.
Stacking collectors provided a cheesy way to maximize power gain without the limitations of space and dealing with the drop off of rad strength that a similar unstacked number of collectors would suffer from as they are added further and further from the source.
Spawned in 2 collectors on top of each other, spawned in one alone nearby
Unanchored and anchored the rad collector with no others on the turf: worked as intended
Anchored one rad collector of the two stacked, attempted to anchor the second: could not anchor the second
Unanchored the first rad collector, anchored the second rad collector: worked as intended
:cl:
tweak: Multiple radiation collectors can no longer be stacked and anchored on the …
=> You can no longer stack Rad Collectors on the same turf

code/game/gamemodes/cult/runes.dm
This PR allows you to activate Revive rune on living cultist if there is at least two invokers to regenerate their body.
Activating rune on living starts 10 seconds do_after and revives only after that.
Did you know you actually can heal IBs, burn wounds and such as cult by just using its magic? All you need is cut your cult buddy to death and then use the Revive rune. Honestly, i did not know that until someone told me that in code chat and we decided that making Revive rune actually abailable to use on living would be cool. Thats why we are here.
Compiled, draw rune, clicked it with multiple options.
:cl:
tweak: Revive rune now can be used on living cultist to heal their wounds, it requires cultist to stand still for 10 seconds and at least two cultists to start process.
/:cl:
=> Cult Revive rune can be used on living

code/modules/mob/living/simple_animal/hostile/mining/hivelord.dm
Title says it all, the Legion mob doesn't drop Syndies anymore.
Free combat hardsuit that is S-Class Contraband, has significant TC value, and is easily farmable from the weakest mob on Lavaland, all from rng chance? Yeah thats pretty funny and bad.
compiles 
:cl:
tweak: Legion mobs no longer drop Syndicate Operatives on death
/:cl:
=> Legion no longer drop dead Syndicate Operatives

code/game/objects/items/weapons/grenades/flashbang.dm
Flashbangs bang is now affected by pressure. Less pressure = quieter = shorter status effect. If you or the flashbang is in space and you are not on / beside it, you will be unable to hear it, and unaffected. Flash of the flashbang is unaffected.
Flashbangs now deafen people for a shorter amount of time if on the same tile when they have hearing protection.
Re-orders flashbang code so bang related stuff is ran only if bang is called.
Realism is good, if you can't hear a flashbang, you should not be affected by it. Also makes lower pressure environments interesting, with the bangs being weaker.
Also makes sense that if a flashbang knocks you down on the same tile, it should deafen you for a bit too.
Lots of flashbanging in various pressures.
:cl:
tweak: Flashbangs bang is now affected by …
=> Flashbangs are now affected by pressure like sound.

code/game/objects/items/weapons/explosives.dm
Simplifies attaching an assembly to C4. You can now directly attach an assembly (Eg. Mousetrap, remote signalling device) to C4 instead of having to create an assemblyholder (Eg. Remote signalling device attached to an igniter.) Also fixes a bug where C4 would not explode when an assembly was attached to it.
Fixes: #22129
Be a skrell with C4.
Have a remote signalling device and attach it to a piece of C4.
Attach the C4 to an airlock and signal the frequency.
It detonates.
Attach an armed mousetrap to a C4.
Step on it.
Smells like gunpowder tastes like fish.
:cl:
tweak: Assemblies like the remote signalling device or mousetrap can now directly be attached to C4.
fix: C4 now explode when the attached assembly is activated.
/:cl:
=> C4 now properly explodes when an assembly is attached.

code/modules/martial_arts/martial.dm
This PR fixes help/harm on judo, help on CQC and other not working propertly
Bugs bad, infinite loops in code bad, lack of testing bad
fixed https://github.com/ParadiseSS13/Paradise/issues/22392
Compiled, hugged people while having judo belt, tried to CQC someone and i hope i dont need to test all remaining martial arts on all intents
:cl:
fix: Non combo intents works again while having martial arts
/:cl:
=> Fix: You can once again help people while having martial arts

code/datums/status_effects/neutral.dm
Fixes medhuds not showing the flatline icon on death due to changes in https://github.com/ParadiseSS13/Paradise/pull/21754.
It currently may look like someone is unrevivable for a moment when they die, which might not be great for them getting treatment. If things don't update right, it might not update at all.
Killed a vulp, they fell over with the flatline icon.
:cl:
fix: medhud icons should now show properly on death.
/:cl:
=> Fix medHUD not updating properly on death

code/game/machinery/Sleeper.dm, code/modules/reagents/reagent_containers/iv_bag.dm
Fixes sleepers runtiming when doing dialysis
Does the same thing for IV bags
This is something I should've noticed and I think something went wrong when I worked on this PR from my remote branch not carrying things over or some dumb stuff.
Dialysis did not runtime on me and actually worked as intended
:cl:
fix: Fixed dialysis not working on IV bags and sleepers
/:cl:
=> Stops sleepers from runtiming when attempting to dialysis

code/datums/emote.dm, code/modules/mob/mob_emote.dm
Fixes a runtime where emotes with the get_sound datum overridden would runtime when mobs that can't even run the emote tried to run it (Eg. Cat calling the *bark emote)
Fixes: #18023
Runtime bad
Be a gorilla
Attempt to use the *sneeze emote, no runtime occurs
Attempt to use the *ooga emote, ooga loudly with no runtimes
Return to monke
No player facing changes.
=> Fixes runtime with sound emotes

code/modules/recycling/disposal.dm
Adds a little message to people when they get stuck in pipes due to being fat.
Marking this a fix since it looks like there was supposed to be code that did this, it just...never did.
Fun fact: there's a 2% chance of getting trapped in a pipe if you're fat. Another fun fact: there's no way of knowing why it happened, since it looks like the code was incomplete. Certified disposals code moment.
:cl:
fix: Disposals now let you know why you got stuck if you're fat
/:cl:
=> Gives you a notice when you get stuck in a pipe for being fat

code/game/objects/items/devices/traitordevices.dm
This fixes a missing name for the fireproofing injector, a species specific traitor item. 
It allows the item to be identifiable.
Purchased a fireproofing injector from an uplink and checked the name.
:cl:
fix: Fixed missing name from fireproofing injector 
/:cl:
=> Fixes missing name for fireproofing injector

code/datums/uplink_items/uplink_traitor.dm
Updates the uplink implant description to refer to the correct amount of available implant TC. Fixes #22231.
Inaccurate syndie item descriptions are bad.
:cl:
fix: The description for uplink implants now state the correct amount of uploaded TC.
/:cl:
=> Update uplink implant description amount.

code/game/machinery/computer/card.dm
Prevents ID consoles from raising Quartermaster slots.
QM PR oversight.
Tried to raise QM slots as HOP, couldn't.
:cl:
fix: QM slots can no longer be raised.
/:cl:
=> Prevents Quartermaster job slots from being raised.

code/_onclick/hud/screen_objects.dm
This fixes https://github.com/ParadiseSS13/Paradise/issues/22163, where alien mobs hands are blocked in the HUD as they have no hands, technically.
Hand HUD will now function properly for alien mobs.
Spawned in as multiple different aliens and checked the HUD.
:cl:
fix: Fixed block on alien hand HUD
/:cl:
=> Fixes blocked alien hand HUD

code/modules/atmospherics/environmental/LINDA_fire.dm
Reverts ParadiseSS13/Paradise#21951
This has caused a number of problems due to a poor testing depth, including:
- Explosions being way out of scope for what is expected
- Smoke causing mass damage to surroundings
What was meant to be a way to make wall-melting dangerous has turned into an easy way to cause big explosions, making the problem worse if anything.
See: https://discord.com/channels/145533722026967040/984761070159818753/1151823517885673472
=> Revert "fireflash_sm is now more dangerous"

code/modules/recycling/disposal.dm
When an unconnected disposals pipe tries to expel someone, it first checks for dense objects on the tile in front of it: If there is a dense objects on the tile in front of it, it will instead expel you on the tile with the pipe.
Fixes: #13249
Currently you are able to bypass any door/window/non-turf dense object by placing an unconnected disposals trunk/pipe in front of it and getting into a chute, this PR aims to fix that.
Be a skrell with and RPD and tools
Point a disposals trunk into an airlock and add a chute to enter the trunk.
Enter the trunk.
Get thrown out of the trunk on the side of the airlock I started on, and not behind it.
:cl:
fix: Disposals now checks for density before expelling
/:cl:
=> [s] Disposals now checks for density before expelling

code/modules/research/designs/mechfabricator_designs.dm
Requires Illegals 4 for the Safety Override Cyborg Module.
Im very very very tired of seeing (the same) cyborgs get an emitter cannon every Shift and use it on antags.
This makes it doable still, but requires some investment or EXTREME Maints Loot luck.
Youre circumventing NT Safety standards, this should not be something you can do willy-nilly every Shift.
:cl:
tweak: Safety Override now requires Illegals 4.
/:cl:
=> Makes Safety Override Module Require Illegals 4

code/datums/elements/waddling.dm, code/datums/spells/cluwne.dm
Fixes a runtime when a clown is cluwned. Clowns waddle after cluwned as god intended. 
Fixes #18946
Runtime bad, cluwned clowns should waddle
Spawned as clown, cluwned self via proc call and by equipping cursed mask. Maintained waddle
:cl:
fix: Cluwned clowns now no longer runtime, cluwned clowns waddle like god intended.
/:cl:
=> Fixes runtime, cluwned clowns waddle after being cluwned

code/__DEFINES/mob_defines.dm, code/modules/clothing/clothing.dm, code/modules/mob/living/carbon/examine.dm, code/modules/mob/living/carbon/human/human_examine.dm
This PR fixes examining wounds logic
Previously
1. It did not use its own proc args, they just were not transfered when we called the proc
2. It did check just for existing jumpsuit, not for it `body_parts_covered` flags
3. same for gloves, feets; mask had even weirder logic
4. rolling up and down jumpsuit did not change any of `body_parts_covered` flags
Bugs bad, being able to see crit burn through ERT hardsuit and not being able to see crit burn through rolled down jumpsuit is bad
Compiled, did critical burn, examined myself multiple times
:cl:
tweak: Rolling down and up jumpsuit now affects if you can see chest, lower body, arms on examine
fix: Examining injured now checks if you cant see body parts
fix: Examining now will show robotic limbs only if you can see them(jumpsuit + gloves …
=> Fixing examining logic

code/game/objects/structures/depot_structures.dm
Fix https://github.com/ParadiseSS13/Paradise/issues/22448, which was brought about by https://github.com/ParadiseSS13/Paradise/pull/22313. 
Objects not having invisible sprites is generally better than the alternative.
:cl:
fix: The Syndicate have rolled back their invisible fusion reactor experiment after a series of Space OSHA reports
/:cl:
=> Fix invisible depot fusion reactor

code/modules/mob/living/simple_animal/hostile/megafauna/megafauna.dm
Placeholder fix to #22220 regarding megafauna
Disables random dodging for all megafauna.
Currently megafauna have a small issue where they _teleport wildly toward you when moving._
This disables that until someone can look into it and miners dont die to bullshit.
Regular mobs arent affected as we didnt notice this behavior in them for some reason.
https://github.com/ParadiseSS13/Paradise/assets/57759731/e7bb4c7d-3b52-4ae7-9fbd-441fadcfeadc
Ran about smacking megafauna on live.
:cl:
tweak: disables hostile mob dodging for megafauna.
/:cl:
=> Disables Mob Dodging for Megafauna

code/game/gamemodes/steal_items.dm
Fixes a small issue with objectives about the core/vault docs
Misinformation for new players, oversight on the QM PR
yea, works for both objectives
:cl:
fix: The Quartermaster is no longer in sole possession of the plutonium nuclear core/vault docs
/:cl:
=> The Quartermaster is no longer in sole possession of the plutonium nuclear core

code/modules/surgery/abstract_steps.dm, code/modules/surgery/other.dm
reopening this https://github.com/ParadiseSS13/Paradise/pull/21801
Makes curing burn wounds its own separate surgery requiring an advanced trauma kit or ointment.
As discussed in discord, this brings burn wound surgery in line with the speed and ease of curing IB and broken bones. Debridement surgery is untouched and still cures burn wounds.
compiled, did surgery
:cl:
add: Adds burn wounds surgery to fix critical burns, similar to internal bleeding surgery. Scalpel -> Hemostat -> Retractor -> Advanced burn kit -> Cautery.
/:cl:
=> Burn wound surgery

code/game/objects/effects/landmarks.dm, code/game/turfs/simulated/floor/asteroid_floors.dm
Gutlunches (and more rarely gubbucks) can now spawn on lavaland.
They are a non-hostile fauna, previously found in ash walker den.
Spawn chance is currently at four, I'd prefer to see it in game first to (possibly) adjust it.
There is also 5% (more than regular "rare" mobs) chance for it to become a gubbuck - they effectively are the same, just smaller and colorful.
More diversity for Lavaland fauna - having something that only _HOPES_ you die is pretty sweet after going through hordes of stuff that _ACTUALLY_ kills you!
This also makes sense lore wise on many levels!
1. We now know how did ashies get theirs.
2. It makes sense for scavenger fauna to develop on a murder planet.
3. It makes sense for non-violent fauna to develop on any planet.
okay that was only three... anyways!
observed, …
=> Gutlunches now spawn on lavaland.

code/datums/diseases/_MobProcs.dm, code/modules/mob/living/carbon/alien/alien_base.dm, code/modules/mob/living/carbon/alien/humanoid/humanoid.dm
Makes Xenomorphs virus immune. 
Resolves #11668 
This was discussed by the teams and was decided to be fixed, as an issue report for it was made.
Put some aliens around a skrell who I blessed with the flu, none got sick
:cl:
fix: Xenomorphs now can't get sick anymore 
/:cl:
=> Xenos can no longer get viruses

code/modules/admin/verbs/pray.dm, code/modules/security_levels/keycard_authentication.dm, code/modules/tgui/modules/ert_manager.dm
ERTs are now properly silenced, reviewing ERT requests will also not have a bunch of garbled text in them now if the user used an html-viable character, and instead they will be turned into spaces.
Unintended things bad
Proper looking safe text rendering, by removing the text instead of just encoding it
See above, silencing worked properly between toggles. Tested the safety of the sanitize input using exploits, all worked as intended.
:cl:
fix: ERTs are no longer always silent if an admin clicks a button
/:cl:
=> Fixes some issues with the ERT manager

code/modules/mob/mob_emote.dm
Fixes a bug where unintentionally fired emotes (like screams from pain) could still be fired while dead.
Corpses screaming and drooling aren't really ideal?
Filled an IV with two bottles of floor pills and injected it into myself, saw that I wasn't continuously screaming and drooling.
:cl:
fix: Mobs can no longer unintentionally emote while dead.
/:cl:
=> Prevents mobs from emoting while dead

code/_onclick/ai_onclick.dm
See title
Fixes: #22441
Robot should be able to do things while bolting or shocking an airlock.
Be a cyborg.
Start bolting an airlock.
Switch my module from welding tool to wrench.
The door airlock still bolts successfully.
:cl:
fix: Silicons can now switch modules without cancelling bolting/shocking
/:cl:
=> Allows silicons to switch modules without cancelling bolting/shocking

code/modules/surgery/organs/subtypes/standard_organs.dm
Makes it so that when you lose a hand, whatever you are holding in your _other_ hand is not dropped as well.
Fixes: #21975
Bug bad.
Give a skrell a thing to hold in both hands.
Cut off one hand.
One item drops, the other stays in the hand that is still attached.
:cl:
fix: No longer drop items in other hand when one hand is lost
/:cl:
=> No longer drop items in other hand when one hand is lost

code/modules/mob/living/carbon/human/species/moth.dm, code/modules/tgui/modules/appearance_changer.dm
This removes the appearance fields for certain species from the mirror that they cannot change. An example of this would be removing the Hair option when a Grey uses the mirror.
This cleans up the UI and reflects the appearance options that a specie has correctly.
Spawned in as each species and checked what appearance options were available to them in the mirror.
:cl:
tweak: Tweaked the visible appearance options on the mirror based on species
/:cl:
=> Removes appearance options not available to species from mirror

code/datums/wires/nuclearbomb_wires.dm
Fixes a grammatical error in the nuke core wiring.
Good grammar is pleasing to read.
Before
After
Loaded the game, opened nuclear device wiring, checked grammar was correct.
:cl:
spellcheck: Fixed a grammatical error in the nuke core wiring.
/:cl:
=> Fixes grammatical error in nuke wiring

code/game/gamemodes/wizard/wizloadouts.dm
Nerfs the oblivion enforcer loadout from wizard by removing the jaunt spell from it.
The loadout already provides plenty of mobility though the supermatter halberd/pushing a SM shard, the jaunt makes them too survivable.
:cl:
tweak: Removed ethereal jaunt from oblivion enforcer loadout.
/:cl:
=> Remove ethereal jaunt from oblivion enforcer loadout.

code/modules/mob/living/silicon/robot/robot_mob.dm
Currently, if a borg is emagged then blown up through the robotics control console, it qdels the MMI within. This removes that.
Being round-ended after being emagged feels bad. While blowing up borg is usually the last resort to dealing with them, the explosion itself should be more than enough punishment. No need to remove them from the round too.
Couldn't due to multi-client weirdness with MMIs and cyborgs, but it compiles.
:cl:
tweak: Emagged borgs don't have their brains deleted when blown up through the robotics console.
/:cl:
=> Robotics console no longer deletes borg brains

code/datums/spells/alien_spells/corrosive_acid_spit.dm, code/game/objects/obj_defense.dm, code/modules/mob/living/carbon/human/human_defense.dm
Title. Xenomorph acid now does less damage to living mobs.
In return, any acid on the chest (As far as I know, only xenomorphs and probably acid foam/acid smoke can actually touch this) has doubled strength and is applied twice. This means that the maximum acid damage is doubled, and it will reach the maximum damage faster.
Naked humans take 120 burn damage and 60 brute damage from this acid.
Humans with no headgear take 40 burn damage and 20 brute damage.
Fixes #12901 
Fixes a bug and makes coming into the melee range of xenos slightly more interesting and fair. 
Some other testing:
- Skrell in security officer outfit: jumpsuit & protective vest melted in about 25 seconds, helmet and others in about 30 seconds
- Skrell in HOS outfit: same numbers for the helmet and others, armored jacket …
=> [s] Lowers xenomorph acid damage on living mobs

code/game/objects/items/devices/traitordevices.dm
Syndicate teleporter no longer drops items manually, as the gib proc does that now. Fixes internal modsuit bag being dropped
No internal bags on the outside.
Gibbed self, no more loot on outside
:cl:
fix: syndicate teleporter no longer makes the modsuit internal bag get thrown outside the mod.
/:cl:
=> syndicate teleporter no longer makes the funny modsuit internal bag get thrown out

code/modules/atmospherics/machinery/portable/portable_atmospherics.dm, code/modules/atmospherics/machinery/portable/portable_pump.dm, code/modules/atmospherics/machinery/portable/scrubber.dm
You're unable to turn on portable pumps, and scrubbers, if they're connected to a connector, and they turn off if you connect them while on.
This does NOT affect canisters.
The fact you're able to turn the pump/scrubber on while they're wrenched, is silly. as you're covering the intake/outlet to remove/add the gasses, so how are you also pumping/scrubbing in/out gas from room?
Wrenched portable scrubbers, canisters, and pumps down and tried to turn them on.
Turned all three types on, then wrenched them down.
All worked as expected.
:cl:
tweak: You can no longer turn portable pumps/scrubbers on if they're wrenched to a connector.
tweak: Wrenching a portable pump/scrubber to a connector now turns them off.
/:cl:
=> You can no longer turn on portable scrubbers/pumps if they're connected to a connector.

code/controllers/subsystem/SSjobs.dm, code/modules/clothing/glasses/glasses.dm
Makes all loadout glasses options prescription upgradable (cheap sunglasses, monocle, eyepatch, Tajaran veils). Current behaviour is that they just get set to `prescription = TRUE`, with this fix, they will call `upgrade_prescription()` properly, introduced in #22227. A side-effect is that these items can be now upgraded during the round as well.
Fixes #22351 
Consistency, fixes an oversight regarding my refactor
1. Set character's disability to Nearsighted
2. Select a glasses option in loadout
3. Spawn in
4. Use screwdriver on the glasses
5. Try to put the prescription lenses back into the glasses
:cl:
fix: You can now properly remove prescription glasses from roundstart prescription glasses.
tweak: Eyepatches, cheap sunglasses, monocles, and Tajaran veils can be now upgraded with …
=> Fixes oversight about loadout prescription glasses

code/game/machinery/vendors/contraband_vendors.dm, code/game/machinery/vendors/departmental_vendors.dm, code/game/machinery/vendors/generic_vendors.dm, code/game/machinery/vendors/wardrobe_vendors.dm
Pretty much just the title, standardizes the following files slogans, ads, prices, contraband, and products lists:
Contraband_vendors.dm,
Departmental_vendors.dm,
Generic_vendors.dm,
Annnd wardrobe_vendors.dm.
As well as removes some spaces from the critter care vendor ad list, that didn't look to be correct. 
" Heat lamps for Unathi!" to "Heat lamps for Unathi!" 
" Vox-y want a cracker?" to "Vox-y want a cracker?"
Since changed non-capitalized armor types as per Henri215's request.
Im honestly not too sure what the ads_list is used for, but it was a typo, so.
As for the standardization, i wouldn't say its good for the game per say, but it is very nice for the coding nerds to not have every list be different, and sometimes the same list change partway through. Looking at you dinnerware …
=> Standardize(s?) vendors.dm lists. Also fixes a typo(?)

code/game/gamemodes/nuclear/nuclear.dm
Nuclear operatives now spawn with the backpack of their choice as set in their preferences.
Fixes: #6665
You should spawn with your backpack of choice
Join game (As skrell) with backpack preference set to departmental duffelbag
Go to traitor panel, make myself nuclear operative, press the equip button
I am equipped with a grey duffelbag rather than a backpack.
:cl:
fix: Nukeops now spawn with backpack preference.
/:cl:
=> Nukeops now spawn with backpack preference

.gitattributes
This PR enables the custom DMI file merge driver by default.
DMI merge conflict is a special hell
Made two branches, merged them.
NPFC
=> add dmi mergedriver to gitattributes

code/game/jobs/job/support.dm, code/game/objects/items/stacks/sheets/sheet_types.dm, code/game/objects/items/weapons/storage/bags.dm, code/game/objects/structures/crates_lockers/closets/secure/cargo_lockers.dm, code/modules/clothing/suits/misc_suits.dm, code/modules/mod/mod_theme.dm
see changelog. I messed up.
This absolutely should have been in the mail PR, I just didn't notice.
Logged on, checked..
:cl:
tweak:  Mail bags can now be crafted with cloth.
tweak: Both the Quartermaster and Cargo Techs now start with mail bags in their lockers.
tweak: Quartermaster roundstart loadout changed to include a mail scanner.
tweak: Cargo Winter Coats can now accept more cargo themed items.
tweak: Mail bags can now fit mail scanners.
/:cl:
=> Cargo QOL + Mail Bag Fix

.github/workflows/ci.yml, tools/ci/check_icon_conflicts.py
This PR adds a CI check to parse DMI files looking for states with the `!CONFLICT!` token added by the DMI merge driver. It does the whole codebase in 4 seconds which is fine performance-wise. Note that the invocation in the CI file is `python -m tools.ci.check_icon_conflicts` versus `python tools/ci/check_icon_conflicts.py` so that it can reach into the parent module to find the icon file parser.
Currently nothing stops someone from just accepting the conflicted file as is.
Tested with a conflicted DMI file, ran CI.
NPFC
=> add CI check for DMI conflict markers

code/modules/events/disease_outbreak.dm
This adjusts the overall probability for the Disease Outbreak event to pull from the predetermined list of viruses, adjusting it from 25% to 50%. 
This will make it an even chance to pull from a list of known diseases versus a disease that is randomly generated when the event is initiated, making some of the more interesting known viruses more common. 
Used event manager to cause disease outbreak to occur and viewed the results.
:cl:
tweak: Tweaked the probability of known viruses to be selected during Disease Outbreak
/:cl:
=> Adjusts the virus selection probability for Disease Outbreak event.

code/game/machinery/computer/arcade.dm
Changed the way score is calculated for Orion and battle arcade:
* Battle arcade: HP + MP + 5 -> 35 tickets
* Orion arcade: crew + food/2 + fuel/5 + engine + hull + electronics - clings ->
10 * (crew - clings) + 5 * (engine+hull+electronics)
Feel free to suggest different numbers
Battle arcade: With the way this game is built i find it unlikely to find a way which will prevent the spam that players can do to accumulate scores. Turning into a random amount would be better, making the players play the game multiple times for tickets instead of just spamming "recharge power" until their stats are high enough.
Orion arcade: This will result in better amounts of tickets for this arcade and will incentivise players to keep their crew alive for more tickets (which is what makes sense for the …
=> Tweaks to Orion and Battle arcades ticket amounts

code/game/turfs/simulated/floor/fancy_floor.dm
Removes sand being dropped when you shovel a grass tile.
How do miners end up with 2000 sheets of glass in the ORM you ask? They just do this:
1. Place a grass tile
2. Shovel it
3. It returns 2 sand and 1 grass tile
4. Place the grass tile again
5. Repeat infinitely
1. Spawn a grass tile
2. Shovel it
3. Tile is returned, no sand
:cl:
del: You can no longer get infinite sand with constantly shoveling grass tiles and placing them back.
/:cl:
=> [s] Fixes an infinite sand/ORM exploit with grass tiles and shovels

code/game/objects/effects/landmarks.dm
Moves the icon states to be on the basetype of mob spawners, instead of being added to literally every subtype of mob spawners
Very slight code improvement, useful nontheless
Compiles + checked in SDMM2
NPFC
=> Moves some vars on mob spawners to the basetype

code/game/objects/mail.dm
This PR adds two feedback stats for mail: successful scans and successful deliveries.
These are stats worth having for this feature for posterity, especially fun stuff like year end stats reports.
Performed actions in round, confirmed rows were added to DB.
NPFC
=> add blackbox stats for mail scans/deliveries

code/modules/response_team/ert_outfits.dm
This PR adds a full Chief Engineer's belt and Shield eyes to the Amber Response Team Engineer.
This is a reopening of https://github.com/ParadiseSS13/Paradise/pull/21872 with the addition of the welding protection.
As an emergency response team member, the player should have the equipment necessary to be able to handle emergencies on station for which they were requested for.
Spawned an Amber RT Engineer.
Checked to see if a full utility belt with power tools was present.
Checked to see if shield eyes were present.
:cl:
add: Added shield eyes to Amber Engineer 
tweak: Tweaked belt type that is given to Amber Engineer
/:cl:
=> Gives Amber RT Engineers CE Belt and Welding Protection

code/game/gamemodes/nuclear/pinpointer.dm, code/modules/mob/living/silicon/robot/robot_modules.dm, code/modules/mob/living/silicon/robot/syndicate_robot.dm, code/modules/projectiles/ammunition/magazines.dm, code/modules/projectiles/guns/projectile/launchers.dm
Buffs:
All nuclear cyborgs to:
- Have a bluespace cell (30k charge to 40k charge)
- A pinpointer that can both point towards nuclear operatives and the NAD
Assault cyborg:
- Increases the magazine of their grenade launcher from 6 to 15 shots.
- Gives them nanopaste
Sabotage cyborg:
- Gives them nanopaste
Let's be honest. Out of the three cyborgs, only the medical cyborg is only useful. The assault cyborg can barely hold it's own ground, and the saboteur cyborg is almost always called out roundstart because of the AI telling which cyborgs are connected to it.
The pinpointer change should give every cyborg the ability to help navigate the station + if they somehow have to work alone and need to find the NAD. 
The extra charge is a QOL upgrade, mostly for mediborgs and assault borgs.
The …
=> Buffs Nuclear Operative Cyborgs

code/game/turfs/simulated/floor/asteroid_floors.dm
Fixes deadly deeprock generation
Resolve #22546
#21858 broke oasis generation, #22283 did not fully fix it as I missed a change of view to range. Now fixed.
Confirmed cave rooms / oasises spawned properly
:cl:
fix: Fixes deeprock room generation
/:cl:
=> Fixes deeprock room generation

code/modules/clothing/suits/armor_suits.dm
As the title suggests, it lets the Crusader Armor carry the Bible in the exosuit slot.
It has struck me as odd that the Holy Person's Armor couldn't carry the Holy Person's Holy Book, and that the only thing it could carry is the Nullrod in Claymore form. Gives Chaplains that use the armor slightly more options.
Put on the armor as Chaplain, equipped The Bible
:cl:
tweak: Chaplain's Crusader Armor can now carry their Bible
/:cl:
=> Makes the Templar Armor able to carry the Bible

code/modules/surgery/organs/eyes.dm
Eyes of the Gods has passive night vision. Good for miners on lavaland if science doesn't have NV mesons. as well as nice on station.
Eyes of the Gods has had its damage lowered on use, to allow it to be used longer. I made it's use time a bit too short in practice. This also makes it much more viable for near permanent use on lavaland, which is good.
The eyes notify you a bit better that you are overusing them, with slightly more messages, and your head lightly burning.
I was a bit harsh with the use time on the Eyes of the Gods, this should make it a bit more worth implanting, and perform much better on lavaland.
Did a bunch of testing on / off station, confirming it felt better.
:cl:
tweak: Eyes of the Gods have better passive night vision.
tweak: Eyes of the Gods gain damage slower. …
=> Makes Eyes of the Gods more worth it.

code/game/objects/items/weapons/misc_items.dm
You can now hide tiny items inside crutches by screwing their tips.
Considering that crutches are BULKY one could justify the inclusion of this obscure mechanic, allowing people to hide their illegals by pretending to be crippled.
- Did screw and unscrew the crutches multiple time
- Tried to insert items with different sizes
- Deleted it to make sure its dropping the hidden item
:cl:
tweak: You can now hide tiny items inside crutches by screwing their tips
/:cl:
=> Adds a new crutch mechanic

code/game/gamemodes/cult/runes.dm
Cultists that have gone into ghost form via the spirit realm rune can no longer be summoned as a cult ghost via the spirit realm rune, which would otherwise cause them to be locked out of their body.
Fix: #22522
Bug bad.
Two cultist client.
Use ascend option on spirit realm rune.
Hover over second spirit realm rune and use summon cult ghost, says no ghosts available.
:cl:
fix: Cultists that have gone into ghost form via the spirit realm rune can no longer be summoned as a cult ghost.
/:cl:
=> Ascended spirit no longer can be summoned as a cult ghost.

code/game/objects/items/toys.dm, code/game/objects/items/weapons/handcuffs.dm
"Unsecure" cuffs are logged differently to attack logs.
I cant tell if an Officer is an idiot or not when they scream "FREEDOMS" and lethal some poor nerd.
Checked the logs.
add: [ADMIN] toy cuffs/twimsts are logged differently from regular cuffs
=> Logs Toy Cuffs/Twimsts Differently from Standard Cuffs

code/game/objects/items/weapons/batons.dm
Normal stunbatons have a respect of 3.5 Seconds between two actual hits of a stunbaton. Telescopic batons do not have this, and can be used to quickly stun someone with a telescopic baton and a stunbaton. Telescopic batons only make this a cooldown of 2 seconds, to respect them being generally weaker.
You can use a stunbaton in quick conjuction with a telescopic baton to instantly stun someone, something which was explicitly something you couldn't do with stunbatons.
I couldn't stunbaton someone who I recently batonged with a telescopic batong, and vice versa.
:cl:
tweak: Telescopic batons now respect the global cooldown on baton stunning.
/:cl:
=> Adds telescopic batons to the baton cooldown timer

code/modules/projectiles/gun.dm
Allows you to one-hand fire some of the larger guns available when using the Holo Cigar.
- Shotguns
- LWAP
- BSG
- L6 SAW (if you somehow got one)
- Sniper Rifle (if you somehow got one)
Opens up more weapon choices with the Holo Cigar.
Does **NOT** allow you to double-fire these weapons. Only use them one-handed.
Nuclear Operatives CANNOT obtain a Holo Cigar, so not worried about it affecting Nuke Ops balance.
Shot some skrell in the face.
:cl:
tweak: Holo Cigars allow you to one-hand large weapons.
/:cl:
=> Holo Cigar Allows One-Hand Large Gun Firing

SQL/paradise_schema.sql, SQL/updates/51-52.sql, code/__DEFINES/misc_defines.dm, code/controllers/subsystem/SSjobs.dm, config/example/config.toml
Logs data in the `playtime_history` table for all departments, not just `living` and `ghost`.
Realistically we should:
- Make this one table with exp_type and a value as another column, but that can wait
- Track this on a per-job basis for stupid detail on stats
But this will do. 
More stats are always good.
Loaded up the server and selected RD
=> Logs playtime history for ALL departments

code/game/objects/structures/aliens.dm
Prevents alien resin from growing over chasms/lava
Fixes #20885
You can safely navigate around resin covered area without a worry there is 50 tiles of lava, plasmalava and chasms hidden by resin.
I checked how the resin behaves around all 3 obstacles that appear on lavaland.
:cl:
fix: Alien resin no longer grows over lava/chasms
/:cl:
=> Prevents alien resin from growing over chasms/lava

code/modules/antagonists/vampire/vampire_powers/gargantua_powers.dm, code/modules/mob/living/simple_animal/hostile/mining/elites/elite.dm
Fixes an oversight I made in the original PR, I assume that the walls were automatically blocking projectiles
Oversights bad, I meant for it to be a melee duel, not a cage for the garg to be executed by firing squad.
:cl:
fix: Fixed projectiles passing through the Desecrated Duel arena
/:cl:
=> Fixes projectiles passing through the Desecrated Duel arena

code/modules/mob/living/carbon/human/human_damage.dm
Fixes the spam of "X goes limp, their facial expression utterly blank." message caused by excessive brain damage. Could happen with any species, but IPCs specifically take brain damage on electrocution regardless of stat
https://github.com/ParadiseSS13/Paradise/blob/5b4796d3f05766e2f03acc62d3befc8d60022a46/code/modules/mob/living/carbon/human/species/machine.dm#L166-L170
Less message spam
Before
After
Spawn pulse demon and IPC, control pulse demon, cross the IPC multiple times
NPFC
=> Fix death by brain damage spamming message

code/game/objects/structures/coathanger.dm
Fixes runtime when clicking an empty coathanger with empty hand.
Runtimes bad, spamming admin logs too.
fixes #22561
I tested all functionalities of the coat hanger a few times and there were no runtimes, and the hanger still works. (before coding chat recommendations that is...)
:cl:
fix: Fixed a runtime when clicking empty coat hanger.
/:cl:
=> Fixes runtime when clicking an empty coat hanger with empty hand.

code/game/machinery/clonepod.dm
Updates the name of cloning data disks to genetic data disks. The box name has also been updated from Diskette Box to Genetics Diskette box.
These disks no longer have anything to do with cloning.
See above, and verified that 7 disks were in the box.
:cl:
tweak: Cloning Data Disks are now called Genetics Data Disks. The box they come in has also been updated to reflect this.
/:cl:
=> Updates the name of cloning data disks

code/modules/power/engines/supermatter/supermatter.dm
Fixes #22345 where bumping a supermatter into another supermatter triggered the special interaction for supermatter collisions on both crystals and resulted in both supermatters being deleted, instead of the crystal that was not moved persisting.
Fixes an oversight with supermatter collisions.
Shoved supermatters into objects, shoved supermatters into supermatters, all worked as intended.
:cl:
fix: Fixes collisions between two supermatter crystals to prevent both from being deleted.
/:cl:
=> Fixes collisions between two supermatters

code/modules/vehicle/motorcycle.dm
Fixes the motorcycle overlay not being applied properly.
Broken overlay is bad.
**BROKEN**
**FIXED**
- Did ride the motorcycle until i ran out of gas
:cl:
fix: Motorcycle sprite overlays have been fixed
/:cl:
=> Fixes the motorcycle overlay

code/__DEFINES/mob_defines.dm, code/game/machinery/Sleeper.dm, code/game/machinery/adv_med.dm, code/game/machinery/computer/Operating.dm, code/game/objects/items/devices/scanners.dm, code/modules/mob/living/carbon/carbon.dm, code/modules/mob/living/carbon/human/human_mob.dm
You know that check pulse verb that's been in the right click menu for however long? You know, the one that's visible even if you're a ghost?
This removes that.
It's almost something worse than useless? It gets in the way and clogs up the right click menu on every mob.
Good riddance.
:cl:
del: Removes "Check Pulse" from the right-click menu
/:cl:
=> Kills Check Pulse

code/controllers/subsystem/SSshuttles.dm
Fixes an oversight where mail crates could spawn inside the shuttle 
Resolves #22507
I forcibly removed all non-dense turfs from the list, then checked if the new proc works as intended, and it does indeed work as intended.
:cl:
fix: Fixed mail crates sometimes spawning inside the Supply Shuttle thrusters
/:cl:
=> Fixes mail crates sometimes spawning inside the Supply shuttle engines

code/modules/projectiles/ammunition/ammo_casings.dm
Marks cap gun ammo as harmless, meaning it can be fired by pacifists.
People in the ghost bar can't shoot cap guns, which is a little sad.
Shot myself in the foot a few times. Then hopped onto my dev server in and tried with a capgun.
:cl:
tweak: Pacifists can now fire cap guns.
/:cl:
=> Allows pacifists to fire cap guns

code/datums/status_effects/debuffs.dm, code/modules/events/fake_virus.dm
Fake virus now simulates brainrot too.
Number of victims is no longer a fixed amount (5% for status effect victims and roughly 10% for one-message ones)
one-message victims: Added "yawn" to  emotes and increased the random time it can take for it to trigger.
Allowing it to scale is good to avoid it affecting too few people during highpop rounds.
- Spawned lots of skrells and triggered the event multiple times to verify the changes
:cl:
tweak: Fake virus: Added a new virus that it can fake
tweak: Fake virus: Number of victims now scales with total amount of valid targets
/:cl:
=> Some fake virus tweaks

code/_onclick/item_attack.dm
Does what it says on the tin. Adds a progress bar to heating up any reagent container.
The formula for the timer is `((reagent_temp / 10) / (is_hot(src) / 1000))`
`is_hot()` is a function that gives us an estimate of how hot the thing is that we're trying to heat something up with.
As an example: at 0 degrees C, it'll take a lighter about 2,7 seconds to heat the beaker up.
So, the hotter the reagents in the beaker, the slower the timer
The better the tool, the faster the timer.
Oh, and you can only queue up one progressbar.
Lighter:
293 K - 2,93 seconds
500 K - 5 seconds
800 K - 8 seconds
Welder:
293 K - 0,83 seconds
500 K - 1,42 seconds
800 K - 2,28 seconds
Heating up chemical mixes with lighters/welders/zippos etc was always a major gripe. It made the chemical heater so unused that …
=> Adds a progressbar to heating up reagent containers.

code/modules/pda/cart_apps.dm
Syndicate bot is no longer visible on bot control pda menu.
fixes #20865
If you make me use "faction_check_mob" and it won't work it ain't my fault cuz it didn't work for me.
Kinda immersion breaking to see syndicate bots (Z levels away too) as a security member of nanotrasen space station.
I tested basic functionality of the existing, NT friendly bots and they do work and follow commands, syndie bots  are not visible there and there were no runtimes.
:cl:
fix: Syndicate bots no longer show up on security bot control PDA menu
/:cl:
=> Syndicate bots no longer show up on security bot control PDA menu

code/datums/ruins/bridges/bridges.dm
Hopefully fixes a rare issue that has happened on test servers. Suggested by s34n
Rare painful to replicate issues are bad
Like, the spawners worked. The issue is a pain to replicate (I have been unable to a week ago after compiling and running for an hour), so no way to tell if this fixes it or not without a lot of compiling and running
:cl:
N/A
/:cl:
=> changes qdel method on bridge spawners

code/game/machinery/tcomms/tcomms_base.dm
Makes it so that certain headsets no longer need telecomms to be on to communicate with each other (Eg. Nukeops, deathsquad, CentComm, ERT Commander), this was an intended feature (See variable "requires_tcomms" on headsets), but was not working.
Certain roles should have access to telecomms even when telecomms are down for various reasons.
Attempted to speak over common comms while comms were up, functions normally.
Attempted to speak over syndicate comms while comms were up, functions normally.
Attempted to speak over common comms with a normal headset while comms were down, no messsage sent.
Attempted to speak over syndicate comms with a syndicate headset while comms were down, messsage is sent.
Note that I have yet to test this with a second player, will do so later.
:cl:
fix: Certain …
=> Certain headsets now no longer need telecomms to work (Nukeops, Deathsquad, ERT Commander)

code/modules/mod/mod_control.dm, code/modules/mod/modules/modules_general.dm
Ensures that modsuit lights are properly extinguished by external sources (e.g. shadow demon grasps).
Modsuits are currently a hard counter to shadow demons because their lights aren't extinguished properly, which is kind of an oversight. This fixes that.
Loaded in a vulp with an engi modsuit and flashlight enabled, shadow demon grasped said vulp, switched over to them, wasn't able to turn on my modsuit's flashlight until the cooldown expired.
:cl:
fix: Shadow demons and other sources can now properly extinguish modsuit flashlights.
/:cl:
=> Modsuit flashlights are now properly extinguished

code/modules/mob/mob_logout_base.dm
Changes the order of logout rights check. Previously if an admin had R_MENTOR their logout didnt trigger admin logout message, but mentor one instead. Now its fixed.
:cl:
tweak: Admin: now if an admin has both R_MENTOR and R_BAN their logout message will apear in-game and in discord
/:cl:
=> Fix/Tweak: Now admin logout messages are more important than mentor ones

code/modules/martial_arts/brawling.dm, code/modules/martial_arts/judo.dm, code/modules/martial_arts/krav_maga.dm, code/modules/martial_arts/martial.dm, code/modules/mob/living/living_defense.dm
Stops people from being able to grab other people while they're on the ground. Does not apply to anyone with a martial art, except for: Judo, Krav and Drunken Brawling.
Nah but more seriously, you can already not reinforce your grab if you're prone. This just stops you from also stopping the cuffed prisoner that you're dragging behind you.
:cl:
tweak: You can now not grab someone if you're lying on the ground, unless you know a Martial Art
/:cl:
=> Stops you from grabbing someone if you are horizontal

code/game/objects/items/weapons/misc_items.dm
Makes it so crutch item hiding works fully as intended again!
Resolves #22658
While teleporting is cool, some people would use this to teleport bread for three days straight.
Shit went into the crutches as expected, and removed itself from my hand!
:cl:
fix: Fixed Crutch item hiding not working as intended
/:cl:
=> Fixes Crutches not working properly

code/datums/mind.dm, code/game/objects/items/weapons/highlander_swords.dm, code/modules/clothing/shoes/magboots.dm, code/modules/martial_arts/judo.dm, code/modules/martial_arts/krav_maga.dm, code/modules/martial_arts/martial.dm, code/modules/surgery/organs/augments_arms.dm
Martial arts that are granted by equipped items (Eg. Krav Maga, wrestling belt, judo belt) no longer persist through cloning when someone is cloned wearing them.
Fixes: #22655
Also fixes a bug where the combo counter would disappear after being cloned
Fixes: #22429
This is easily exploitable and should be fixed.
Also bug bad
Equip Krav Maga gloves, wrestling belt and use the CQC manual
Die and get cloned.
Krav Maga and wrestling martial arts are gone from my mind, CQC remains.
Clone myself while I have CQC.
Combo counter still appears when I hit a monkey
:cl:
fix: Martial arts granted by equipped items no longer persist through cloning.
fix: Martial arts combo counter no longer disappear after getting cloned.
/:cl:
=> [s] Martial arts granted by equipped items no longer persist through cloning.

code/__DEFINES/language_defines.dm, code/game/jobs/job/support.dm, code/modules/mob/language.dm
Essentially gives the Librarian a free built in limited Book of Babel.
Its no shock that the librarian is absolutely one of the worst service roles in the game, it completely is dogshit. Not only is the library one of the most worthless and niche places to visit on station, the job of a librarian is also flawed. People either build bars in the library in desperate attempts to attract people, or they go off and act as shitters from complete boredom.
I think its in need of something that makes it unique or interesting, giving it book of babel knowledge is a *small* remedy to a bigger problem that helps it somewhat, not completely, but it does help.
Firstly, Librarians having extensive knowledge of many languages is not out of the scope of that job, their intelligent. 
Secondly, the ability …
=> Makes the Librarian a little less shit, now they know most languages.

code/modules/mining/machine_vending.dm
Adds the jaunter kit to mining voucher options. Provides a jaunter and brute trauma kit to the purchaser.
An option for those who want a quick evacuation from lavaland, or who want safety on their belt if chasms generate.
Confirmed option was there and worked
:cl:
add: Adds jaunter kit to mining voucher options
/:cl:
=> Adds jaunter kit to mining voucher options

code/__DEFINES/flags.dm, code/datums/uplink_items/uplink_nuclear.dm, code/game/objects/structures/girders.dm, code/modules/projectiles/guns/projectile/sniper.dm, code/modules/surgery/organs/organ_external.dm
converts passflags.
Adds PASSGIRDERS, for passing girders.
Sniper bullets are now faster and pass through weak blockages like glass, grills, and girders, due to their high caliber. Walls still stops them, or other objects. This should allow for longer range shooting to be more viable.
Pen rounds are slightly faster but not as fast, due to penetration. They also still break glass and such.
Antimatter rounds are now inaccurate unless zoomed in, and will drop organs when gibbing a limb.
Permakill sniper rounds are not as fun, makes a bit more work to one shot someone, but better at longer ranges, and glass barricades will not make the weapon useless.
Shot a bunch of skrell with antimatter, shot other weapons.
:cl:
tweak: Sniper bullets are faster and pass through weak barricades such as …
=> Antimatter now innacurate without zooming. Sniper projectiles are faster / pass through weak stuff.

code/modules/mob/living/silicon/ai/ai_mob.dm
Adds a delay of 5 seconds when carding living AIs. It's no longer an instantaneous click, unless they're dead.
Downloading an AI to a card is kind of a big deal. It's one click to end a malf AI's round, and means that AIs can't really make any form of escape.
Put another way, this should make fighting an AI, especially one who's in a mobile core or has friends, a bit more dynamic.
Carded an AI, waited five seconds before it was transferred to the card. Clicked the core again to instantly put it back.
:cl:
tweak: Carding a living AI now takes five seconds.
/:cl:
=> Carding AIs now takes time.

code/modules/response_team/ert_outfits.dm
This cleans up ert_outfits.dm file and makes the code more uniform. In theory, this will allow the code to be read easier and will make maintaining it simpler as well.
It is good for the code base. It makes the code look a bit cleaner and easier to navigate. This brings it up to a more acceptable and uniform standard that we want for our code base.
Made sure that ERT outfits still functioned properly.
NPFC
=> File cleanup for ert_outfits.dm

code/game/objects/items/weapons/cards_ids.dm
Adds the supply department to the agent ID occupation options so you can pretend to be part of that department again, and cleans up some duplicative code along the way.
You should be able to pretend to be a shaft miner without having to use the custom job option on the agent ID.
Be a traitor, buy an agent ID
Use the agent ID and select the supply department
Select shaft miner, job title on ID has now updated to shaft miner.
:cl:
fix: The supply department can now be selected on agent IDs.
/:cl:
=> Adds supply department to agent ID options and cleans code a little

code/modules/antagonists/changeling/powers/shriek.dm
Stops changelings from using their shrieks while ventcrawling. Resonant Shriek already had failsaves in place for doing it while in lesser form, but I added it in case they get their hands on some other form of ventcrawling.
Some people enjoy ventcrawling as changelings, spamming their EMP shriek, either to annoy security or to just keep killing their IPC target, which is in both cases very uninteractive for both sides.
I went on a little ventcrawling adventure, looked at the fancy button animations doing nothing as I couldn't Shriek anymore.
:cl:
tweak: Changelings now cannot use both Shrieks while ventcrawling.
/:cl:
=> Changelings now cannot use their shrieks while they are ventcrawling

code/modules/mob/new_player/new_player.dm, code/modules/mob/new_player/new_player_login.dm
fixes new players not always being able to use their keybinds
I wanna look at the debug menu without needing to hit the funny rebind button first
yippie 80k gc queue
:cl:
fix: New players should now always be able to use their keybinds
/:cl:
=> fixes new players not always being able to use their keybinds

code/game/objects/items/crayons.dm
This PR fixes two runtimes that might occur when 1) setting a crayon message to the empty string and 2) using a crayon with an  empty string as a message. In these cases the crayon will just be reset to print "A".
If there's a better helper for checking the empty string here let me know but since the regex takes out everything that isn't one of the printable characters, and spaces aren't printable, the string shouldn't have to be trimmed of whitespace.
These runtimes are bad. Luckily they don't break the UI.
Spawned in, set crayon messages, checked runtime logs.
:cl:
fix: Crayons will no longer runtime when set to an empty message.
/:cl:
=> fix runtimes setting empty crayon message

code/game/gamemodes/malfunction/Malf_Modules.dm, code/modules/mob/living/silicon/robot/robot_inventory.dm
Fixes some runtimes with the AI malf module
Most of the runtimes were just visual, but they still runtime and should be displayed. I also found another runtime that I fixed along the way.
I rejuv'ed a borg, and didn't notice any runtimes
:cl:
fix: Rejuv Borg will now actually send a message to the AI about how many uses it has left
/:cl:
=> Fixes some runtimes with the Rejuv Borgs Malf AI upgrade

code/modules/mob/living/carbon/brain/MMI.dm
You are no longer able to attack posibrains and MMIs with items, this includes things like food, handcuffs and other bits and bops that would cause runtimes. 
Fixes: #8441
Attacking posibrains and MMIs in this way doesn't actually damage the brain, meaning it is literally useless, besides being a headache for coders.
:cl:
fix: You can no longer attack MMIs and posibrains with items.
/:cl:
=> You can no longer attack MMIs and posibrains with items.

code/datums/mind.dm
Your job gets transferred to the new body when you get cloned, this is mostly used for healing from certain reagents, suchs as security officers getting healed by sprinkles.
Fixes: #10829
Bug bad.
Be a security officer
Get cloned
Job is still security officer
:cl:
fix: Your job now gets transferred to the new body when cloned.
/:cl:
=> Your job gets transferred to new body when cloned.

code/modules/mining/equipment/survival_pod.dm
Sets the ambience for the shelter areas to be mining, as the default one is for the station. That'll make station shelters sound like mining, but that's a tradeoff and most of the time the shelters will be on lavaland anyways.
Fixes #22611
https://github.com/ParadiseSS13/Paradise/assets/80771500/3e97efc7-e51a-4f69-ae92-5f3e04c16520
Deployed a shelter and waited a bit inside to trigger the ambience sounds.
:cl:
fix: Shelters do not use station ambience noises
/:cl:
=> Shelter areas use mining ambience instead of station ones

code/game/objects/items/weapons/implants/implant_chem.dm
This adds logging for the activation of the chem bio-chip implant. It will now show target, reagent type, and amount injected within the log. 
This allows admins to identify when a chem bio-chip implant was activated, who activated it and what it contained, making it easier to track misuse of the implant when dealing with potential rules violations. 
Implanted chem bio-chip into a Skrell.
Observed log results.
NPFC
=> Adds logging for chem bio-chip implant

tools/requirements.txt
Reverts ParadiseSS13/Paradise#22712
Need to upgrade Python before we can do this.
=> Revert "Bump pillow from 9.3.0 to 10.0.1 in /tools"

_build_dependencies.sh, tools/bootstrap/python311._pth, tools/bootstrap/python_.ps1, tools/requirements.txt
Fixes the issues that will be introduced by https://github.com/ParadiseSS13/Paradise/pull/22728 preventing users with merge hooks from making commits.
Moves us from an end-of-life python release used in mapmerge, dmi merge (icon conflict fixer), etc.
Bumps beautifulsoup4, pygit2, bidict, and pillow to latest stable versions.
Users with merge hooks should be allowed to make commits.
I made some commits, they worked?
=> Bumps merge driver deps

code/modules/atmospherics/machinery/portable/portable_pump.dm, code/modules/atmospherics/machinery/portable/scrubber.dm
Updates the title, and inspect description of portable pumps, and scrubbers, to be better, and actually reflect what they do better.
The current inspect description is flat out copy pasted, and mostly incorrect/out dated in the scrubbers case. this fixes it.
see above.
:cl:
tweak: Changed the inspect message of both portable scrubbers, and pumps, to be more reflective of what they actually do.
tweak: Changed how the title of the portable scrubber, and pump is capitalized.
/:cl:
=> Updates the title, and inspect message of portable pumps, and scrubbers.

tools/mapmerge2/dmm.py, tools/mapmerge2/merge_driver.py
Last PR for this I swear, and not urgent. This PR brings diff size back in line with before #22737. When testing against the Meta cryodorms/restroom swap I realized that more keys were being generated than I expected, and the diff ended up being a lot noisier. This is a better version of my original implementation.
Maps using the DMM merge driver will continue to have more straightforward diffs.
~4,000 lines of the left versus ~400 lines on the right for the same map.
NPFC
=> mapmerge: one last fix for diff size

code/game/objects/items/devices/traitordevices.dm
Syndicate teleporter now breaks grabs when teleporting someone.
Unlike the veil shifter, syndicate teleporter should not be able to kidnap people. It now breaks grabs apon teleporting, to prevent the niche situation where one can grab someone, then teleport to teleport them with you
I teleported with a skrell in a neck lock and all I got was this hacktober fest shirt. Wait a minute.
:cl:
fix: You can no longer kidnap people with the syndicate teleporter.
/:cl:
=> you can no longer kidnap people with the syndicate teleporter

code/datums/outfits/outfit_admin.dm, code/modules/admin/verbs/infiltratorteam_syndicate.dm
This fixes the TC amount in hidden uplink when a Syndicate Infiltrator is created via the Select Equipment menu.
This accounts for the TC Inflation Adjustment. 
Spawned a mob.
Used Select Equipment and selected Syndicate Infiltrator.
Checked the starting balance on hidden uplink.
:cl:
tweak: Tweaked the default TC value for admin spawned syndicate infiltrators
/:cl:
=> Fixes TC amount for admin spawned Syndicate Infiltrator

.github/CONTRIBUTING.md
Adds Burza as a member of the Review Team in the documentation.
Updates documentation to reflect team addition accurately. 
Examined file for appropriate information.
**@Burzah**
=> Adds Burzah to the Review Team in Documentation

_maps/map_files/cyberiad/cyberiad.dmm
Perma no longer has a pipe missing a vent.
Custodial office no longer has a duplicate pimpin'ride key.
Maintenance old television type is now correct.
Fixes https://github.com/ParadiseSS13/Paradise/issues/21768
Fixes https://github.com/ParadiseSS13/Paradise/issues/21113
Fixes the maintenance television being of the wrong path, causing its screen to change to the entertainment monitor one once a video camera was activated.
- compiled and verified the changes as one can see over images of changes
:cl:
fix: Cyberiad: perma no longer has a pipe missing a vent
fix: Cyberiad: custodial office no longer has a duplicate pimpin'ride key
fix: Cyberiad: maintenance old television type is now correct, no longer having issues with its screen
/:cl:
=> Cyberiad: Fixes some minor issues (No conflicts version)

code/game/gamemodes/miniantags/guardian/types/protector.dm
Fixes some weird behavior with the protector guardian, you can't project your shields in your host or project your shields on your host anymore
You can no longer move through a guardian wall as the summoner, and the speed of a projecting holopara is decreased to 2 from 1
bugfixes are good and this is rather overtuned right now. You can put the holo on the same tile you're on and you can't really hurt em. Making people play more carefully instead of using it like forcewall where you can just walk through it
dd is pain
:cl:
tweak: Protector guardian now has more reduced speed while moving, summoner cannot move through guardian walls, and you cannot project your shields while you're on the same tile as your host
fix: You can no longer project guardian shields in your host
/:cl:
=> Tweaks the protector guardian

code/modules/projectiles/guns/energy/laser.dm
LWAP now uses on_mob_move instead of checking if the mob has moved every process. You can still turn / shoot without breaking the zoom, just not move off the tile
More accurate movement tracking is good.
Not having the lwap process and check every 2 seconds is also good.
Confirmed lwap descoped as expected.
:cl:
tweak: LWAP now descopes more accurately to movement, instead of every 2 seconds
/:cl:
=> LWAP now descopes more accurately to movement, instead of on process

code/game/objects/items/weapons/shields.dm
Adds combat knives alongside batons to the items that can bash riot shields for the text and sound effect. 
Adds a fun bit of noise and interaction if you have a riot shield and a combat knife.
1. Spawned in a riot shield, baton, combat knife
2. Checked that both items could bash the riot shield properly
:cl:
tweak: You can now bash riot shields with a combat knife to make a sound.
/:cl:
=> Adds Riot Shield Bashing with Combat Knives

code/modules/mob/dead/observer/observer_base.dm
You can now type out the verb in the command box in the bottom right, instead of always needing a popup. Functions exactly the same otherwise.
Quality of Life
See above.
0 saves properly, making everything light. 255 and above saves everything to 255, making all darkness appear.
:cl:
tweak: Pick-Darkness verb now supports input from the command box
/:cl:
=> Pick-Darkness verb now supports command box input

code/modules/mod/mod_control.dm, code/modules/mod/modules/modules_general.dm
This adds some basic support for modsuit serialization, specifically for modules. I tried doing the core as well, but ran into issues when it comes to standard cores and their cell, so I'm limiting the scope to just installed mods.
Fixes #22483
Serialized a character, and a modsuit on its own with objects stored. Deserialized both, making sure there wasn't duplicated modules, or left overs from copying over new objects.
N/A
=> Add serialization support to Modsuit modules

code/game/machinery/vendors/departmental_vendors.dm, code/game/objects/structures/crates_lockers/closets/secure/engineering_lockers.dm
This replaces the t-ray scanners in atmospheric lockers with full engineering goggles. T-ray scanners only have the t-ray mode while engineering goggles have meson alongside several other modes, which provides protection from the SM induced hallucinations.
Added 4 tray scanner goggles to the engi-vend to compensate as they have a higher scanning range than the base goggles.
When mesons were refactored, the hallucination protection was changed from just the goggles to the meson specific mode. This meant that atmos techs no longer had protection from hallucinations and have to hack or steal engineering goggles in order to be protected from the SM hallucinations. As the role that interacts with the supermatter engine as much, or even more than station engineers, they shouldn't need to steal …
=> Swaps Atmos Tray scanners with engineering goggles

code/modules/martial_arts/combos/cqc/kick.dm
Remembering the Basics of CQC will now inform the player that Combo Harm'ing people while they're down with CQC inflicts brain damage.
As it stands, it's proper noob bait for chefs that do not have code knowledge that Head Kicking does brain damage. It's not informed anywhere but the Martial Arts page on the wiki. Players, especially new players, shouldn't have to read an out of the way wiki page to know this. Will hopefully lead to less cases of Chef players getting into admin trouble from not knowing that repeatedly kicking a dude isn't just dealing large amounts of stamina like it originally claimed.
Information good.
I compiled it and verified I edited the right text line in game.
:cl:
tweak: CQC Kick now properly informs the player that it does minor brain damage to prone targets. …
=> Properly informs CQC Headkick does Brain Damage

code/modules/mining/fulton.dm
Makes fulton packs use the proper unbuckling proc instead of doing `buckled = 0` like a madman.
Fixes #22372, possibly other buckled cases as well.
https://github.com/ParadiseSS13/Paradise/assets/80771500/bb6df1c4-f047-4bb2-be92-87281b3cfe1a
Spawned an extraction point and a pack in Lavaland, strapped a tajaran on a wheelchair, and watched them fly. Then pushed around the wheelchair and the mob.
:cl:
fix: Mobs do not rubberband back when fulton extracted while buckled to something
/:cl:
=> Fulton extraction properly unbuckles mobs

code/modules/atmospherics/machinery/components/binary_devices/passive_gate.dm
This adds a requirement to passive gates that requires the input pressure to be above the target(pressure set in the UI) pressure in order for the gas to move. This adds functionality as a pressure control device for different pipe systems.
As it stands, passive gates are pretty boring and aren't much different than pressure pumps. Besides passive gates not requiring power, both devices can be applied in almost the exact same instances with very minimal differences. Adding this requirement would allow for passive gates to be used as pressure control or overfill control on pipe networks if setup properly, allowing for a distinction between pressure pumps and passive gates. Pressure control can already be achieved using passive vents and some creative piping, but this would build the same …
=> Expanded Passive Gate Functionality

code/modules/atmospherics/environmental/LINDA_turf_tile.dm, code/modules/mob/living/carbon/carbon.dm
This PR makes sure that objects that are on a human that are about to be qdel'd, aren't already qdel'd. Now you may think this may be a "roundabout" fix, but the real problem here is the objects about to be qdel'd have already been gotten from get_all_slots(). I've also made it so that qdel'd objects are not affected by atmos pressure differentials, this means if something like this happens again, we wont get infinite dusting because of SM atmos.
Fixes #22698
Dusted myself a lot.
:cl:
fix: Wearing a modsuit while being dusted on the SM will no longer cause the items to be infinitely stuck in a loop of dusting
/:cl:
=> Fixes dusting part 2

code/_onclick/click.dm, code/_onclick/hud/alert.dm, code/_onclick/hud/blob_overmind.dm, code/_onclick/hud/screen_objects.dm, code/game/atoms.dm, code/game/atoms_movable.dm, code/game/objects/items.dm, code/game/turfs/simulated/floor.dm, code/game/turfs/simulated/walls.dm, code/game/turfs/space/space_turf.dm
Optimizes mouseenter
Mouseenter no longer has nullchecks because if this breaks we should know about it
We really don't need to be calling this on turfs or areas
Also ``atom/MouseEntered 50.818 50.864`` this is bad
tried to do weird shit and failed
NPFC
=> optimizes MouseEnter

code/game/turfs/simulated/floor/chasm.dm, code/modules/mob/living/simple_animal/hostile/megafauna/ancient_robot.dm, code/modules/mob/living/simple_animal/hostile/megafauna/bubblegum.dm, code/modules/mob/living/simple_animal/hostile/megafauna/megafauna.dm
Megafauna now path across chasms to murder people that are on the other side.
Megafauna will also fuck up structures around them more often.
Being able to cheese megafauna with chasms bad.
Megafauna causing more destruction good?
Taught megafauna to not fear the abyss, confirmed could path across
:cl:
fix: Megafauna are no longer chronically afraid of chasms
/:cl:
=> Megafauna are no longer chronically afraid of chasms

code/modules/response_team/ert_outfits.dm
Gives all engineering ERTs (amber, red, and gamma) an RPD in their bag. 
Engineering ERTs should be able to fix up the atmos pipes alongside their other work without shelling out for the ridiculously expensive autolathe cost for an RPD. This will let them fully do their job without robbing the station of materials or the atmos lockers and avoid the pain of hunting down scattered pipes. 
Spawned in all three engineering ERTs and checked their bags for RPDs
:cl:
tweak: All levels of Engineering ERTs now spawn with an RPD.
/:cl:
=> Gives Engineering ERTs Rapid Pipe Dispensers

_maps/map_files/Delta/delta.dmm, _maps/map_files/MetaStation/MetaStation.dmm, _maps/map_files/cerestation/cerestation.dmm, _maps/map_files/cyberiad/cyberiad.dmm
This PR removes directional varedits from floor tiles where either the direction is invalid (such as 0 or 7 (?!)) or the icon state does not have a direction which matches it. This PR applies only to station maps; a followup PR may contain other DMMs. Note that this also results in the removal of many redundant tile definitions.
This improves map correctness.
If done correctly there should be no visual changes, since these tiles should have defaulted to the south icon state if they were missing in the first place. That also means there should be no visual diffs of the map in MDB.
Tested compile, tested map override for each station map loaded cleanly on roundstart.
NPFC
=> Remove invalid icon dirs from station floors.

code/__HELPERS/time.dm, code/modules/admin/player_panel.dm
While there's a proc to convert seconds to a minutes:seconds format, it strips off hours if it exceeds 60 minutes. I'm adding a new proc, `seconds_to_full_clock`, which is basically how round time is calculated, but with seconds as the argument. There's other procs that return that kind of format, but take timestamps or world.time instead.
The shuttle timer for the Check Antagonists panel uses it now.
Fixes #21688.
Opened the Check Antagonists panel, called in the shuttle, set a custom time that exceeded one hour.
N/A
=> Add seconds to hh:mm:ss proc for Check Antagonists panel

code/modules/reagents/reagent_containers/syringes.dm
This PR creates a new attack log when a player injects reagents into food items using a syringe. 
Allows admins to combat kitchen grief by tracking who is injecting food and what reagent they are injecting.
Spawned cheeseburger.
Injected chemicals into burger.
NPFC
=> Adds logging for injecting food via syringe

code/datums/spells/summonitem.dm
The summon item spell still had some odd interactions and feedback, in order:
Cavities would not get cleared properly, it now does so.
Headpockets would just cause the spell to runtime due to being in nullspace, and gets its own check now.
Storage implants just got deleted by the spell, and now it just pulls the item out, leaving the implant in place.
Feedback for the disappearing item now has a check to see if it's intended to be seen. It doesn't make sense for people who can't even see the item to be told that X suddenly disappeared. The storage implant in particular gives no feedback unless its content are being viewed while the item is recalled.
Fixes #22400. More sensible feedback based on what happens is better as well.
Used summon item on an object that was stored in a headpocket, …
=> Add edge cases to summon item spell, and tweak to feedback if object is hidden

code/game/objects/items/weapons/storage/bags.dm
Title. You can fit trash bags into empty belts now. Also removes a useless flag
You couldn't fit them into empty belts, but you could if the belt had anything in it, was kinda funny.
Checked what it could, and couldn't fit into.
:cl:
fix: Fixed not being able to fit empty trashbags into empty belts. 
/:cl:
=> Fixes empty (bluespace)trashbag not being able to fit into empty belts.

code/game/objects/items.dm
Makes you able to remove powercells by attacking a modsuit with an empty hand when the panel is open.
Fixes: #22704
Draft for now so I can take some time to properly test it, so I don't create runtimes like my previous 2 fixes.
Bug is bad, and the signal not being sent might also be an issue for other items using the same `COMSIG_ATOM_ATTACK_HAND` signal.
https://github.com/ParadiseSS13/Paradise/assets/19361017/df7378ff-508c-4f6e-a71b-c2ccdc165a63
Open modsuit panel
Pick up modsuit
Click on modsuit with empty hand, cell is removed
Click on modsuit with cell, cell is put into the modsuit.
:cl:
fix: Modsuit powercell can no we be removed by opening the panel and clicking on it with an empty hand.
/:cl:
=> Fixes modsuit cell removal

code/modules/surgery/organs/augments_internal.dm
Fixes a bug where if an anti-drop user lost the item they were holding (Eg. it got amputated), picks it up with the other hand, then tried to relax the hand, causing the item to stay nodrop permanently.
Fixes: #22651
Bug bad.
Hold an item, use antidrop, I can't drop the item, turn antidrop off, I can drop the item again.
Hold an item, use antidrop, cut off the hand holding the item, pick the item up with my other hand, turn antidrop off, I can still drop the item, turn antidrop on, I can no longer drop the item.
:cl:
fix: Anti-drop can no longer cause permanent nodrop items for its user.
/:cl:
=> Fix: Anti-drop causing permanent nodrop items when dropped item picked up by user.

code/modules/client/preference/character.dm, code/modules/clothing/clothing.dm, code/modules/mob/living/carbon/human/human_update_icons.dm, code/modules/mob/living/carbon/human/species/_species.dm, code/modules/mob/living/carbon/human/species/unathi.dm, code/modules/mod/mod_control.dm, code/modules/mod/modules/_modules.dm
Right now, ashwalkers use HUMAN clothing sprites, making with some weird interactions with masks/helmets/hardsuits/modsuits if they can get their hands on one.
Essentially, this makes icon code for clothing check by the species `sprite_sheet_name`, which by default is their normal species name. Ash walkers have a `sprite_sheet_name` value of "Unathi", allowing them to use unathi sprites. I originally considered this being a proc on species, but then I realized the massive amount of proc overhead that would happen.
This system could eventually be used for golems if we ever wanted them to have specific clothes looking differently for them.
Fixes some ugly visuals with ash walkers and clothing
I went through and manually checked all the cases of `species.name`. There are some cases where it …
=> Ashwalkers now use unathi clothing sprites

code/modules/mob/mob_misc_procs.dm
The resting/getting up message is sent before the do_mob for lying and laying down. And slightly rewords it.
Imo, its weird how the message appears only after the 1 second do_after. Sometimes when I accidently mash the button in a fight, I struggle to realize when intent im trying to go to crawling, or walking)
See above
:cl:
tweak: Lying down will tell you what you're trying to do before you do it (get up/lay down)
/:cl:
=> The resting/getting up message is sent before the do_mob

code/__HELPERS/trait_helpers.dm, code/modules/assembly/health.dm, code/modules/mob/dead/observer/observer_base.dm, code/modules/mob/living/carbon/alien/alien_base.dm, code/modules/mob/living/carbon/brain/carbon_brain.dm, code/modules/mob/living/carbon/human/human_mob.dm, code/modules/mob/living/silicon/pai/pai.dm, code/modules/mob/living/simple_animal/parrot.dm, code/modules/mob/mob.dm, code/modules/mob/new_player/new_player.dm, code/modules/telesci/gps.dm
I am going to scream I'm actually just angry that we've had it like this for so long
Stops /Stat from processing panels that you don't have focused
stops calling stat's parent value because it doesn't exist and just adds overhead
Before:
``/mob/Stat                                                                                   0.016        0.057        0.059        0.000          459``
After:
``/mob/Stat                                                                                   0.006        0.008        0.009        0.000          567``
this was more expensive than fucking **SSmachines**
``/mob/living/carbon/human/Stat 74.076``
this is bad to see throughout a round
it just works my bros
:cl:
fix: Removed a lot of status panel related lag
tweak: GPSes and health assemblies only …
=> Makes the /Stat proc about five times faster

code/modules/research/rdconsole.dm
Usually after deconstructing in Destructive Analyzer you return to the console's Main Menu.
This PR makes it so you stay in the menu of Destructive Analyzer.
Usually in R&D at the start of the round you make and deconstruct a lot of items in bulk,
but it is annoying to deconstruct in bulk because console keep going back to Main Menu after each deconstruction.
there is no benefits in automatically quitting to main menu, and I think it would be a good QOL tweak.
Joined as Research, did basic R&D routine, tried screwing with consoles and analyzer in the middle of deconstructing.
:cl:
tweak: R&D console no longer returns to main menu after deconstructing an item.
/:cl:
=> Makes destructive analyzer stay in the same menu after deconstruction

_maps/map_files/RandomRuins/SpaceRuins/syndie_space_base.dmm, code/game/machinery/vendors/contraband_vendors.dm
This PR makes it so the donksoft vendor located in the syndie research base can no longer be disassembled or unbolted from the floor. Using these tools will smack the vendor, leaving the user at risk of the vendor falling on them.
Crew should not have access to a vendor full of automatic riot dart firing weapons. Its fully problematic from a balance perspective, and should be removed. Explorers who dare to enter the research base will still be able to access the vendor, so acquiring them is still possible, but highly risky. 
Spawn a donksoft vendor, attempt to disassemble it and un-wrench it, lose my head trying.
:cl:
tweak: Donksoft vendor can no longer be unwrenched/disassembled. 
/:cl:
=> Removes the ability to disassemble and unwrench the donksoft vendor in the syndie research base.

code/modules/reagents/chemistry/reagents/toxins.dm
- Kidan now get half the toxin damage from pest spray if they are wearing a mask.
- Every other humanoid gets 1 or 2, depending on if they are wearing a mask too, toxin damage from pest spray, because my god that can't be healthy.
While Diona got an update with their plant killer to have it be reduced by other factors, while Kidan never got that. That is why even when wearing a lot of protection as kidan, you can still get 30 toxin damage if you get hit by pest spray, because of their 70% increased toxin damage - which, if the balance team gives a green light, I'd be happy to knock down like 10-20% - Now, if they *are* wearing a mask, the damage is halved to about 17.
Sprayed a kidan with and without a mask, they took different amounts of damage
:cl:
tweak: Kidan now take less toxin …
=> Makes Kidan take less damage from pest spray if they have a mask, everyone else takes a very minor amount too

code/modules/awaymissions/zlevel_helpers.dm
This adds an associated feedback of ruin filename -> placement coordinates to the feedback DB.
I want to get a better look at some aspects of ruin spawning, namely the practical rarity, duplication, and density of ruins in-game. If we record placement in this way we can also answer more interesting questions like "how many ruins with teleporters spawn on average in a given sector?" or "how many tiles on a space z-level are not ruins on average?"
Ruins and placement are logged in log_world but not in an easily consumable format and not accessible via parastats.
It also makes it easy for developers to sanity check if certain ruins are spawning or not.
Affected can make post-round maps of z-levels with this information, because we're not using enough storage on pictures of maps.
Ran rounds, …
=> blackbox: record ruin placements

code/modules/projectiles/guns/projectile_gun.dm
The sounds of shells dropping now has a lower sound range, and can't be heard through walls
Small guns are reloaded silently, normal sized guns can still be heard through walls unless silenced.
Silenced weapons are nice!
The fact that you could hear the ammo dropping from a pistol, from farther away and through walls when the gun is silenced, is  less so.
Same with reloading.
Now you can no longer hear shells drop through walls.
Reloading on small weapons is now quiet. Reloading larger weapons are still louder, unless silenced
Confirm it sounded right.
Confirmed normal weapons worked right.
:cl:
tweak: The sound of shells dropping from a gun is now quiet / unhearable through walls.
tweak: Reloading can not be heard through walls on small or silenced guns.
/:cl:
=> The sound of shells dropping from a gun is no longer louder than the gunitself. Reloading modified

code/datums/uplink_items/uplink_general.dm, code/datums/uplink_items/uplink_traitor.dm
Removes the following items from being able to be rolled by surplus crates.
The list is as follows.
- Ambrosia Cruciatus Seeds
- Boozey Shotgun Shells
- Meat Cleaver
- Chef Excellence's Special Sauce
- Kinetic Accelerator Pressure Mod
- Guide to Advanced Mimery Series
- Safe-cracking Kit
- Poison Bottle
- .357 Revolver - Speedloader
- Stechkin - 10mm Hollow Point Magazine
- Stechkin - 10mm Incendiary Magazine
- Stechkin - 10mm Armour Piercing Magazine
- Stechkin - 10mm Magazine
- Chainsaw
- Missionary Starter Kit
- The E20
- Holoparasites
- Amplifying Thermal Safe Drill
For a good while, surplus crates have been a bit two-fold. Rather they are utterly trash, useless and barely usable by whichever traitor or team or traitors that have bought them, or they are the least balanaced, most …
=> Removes a number of items from being able to be rolled by surplus crates.

code/modules/reagents/chemistry/reagents/drugs.dm
Surge now matches crank in confusion, being equal drugs, one just ipc.
Confusion / heat on surge and crank scale 5x slower
Surge and crank should be identical.
For context:
Surge before this pr would confuse people for 20 seconds and add 300 to body tempature after 10 units. After 20 units, 40 seconds and 600 tempature with a prob 20. It was insane, and needed drastic tuning down.
Confirmed drugs felt good.
And by good I mean downsides being reasonable
:cl:
fix: Surge and cranks downside mirrors each other again.
tweak: Crank / surge now scale heat and confusion more reasonably
/:cl:
=> make surge better / surge and crank no longer boil people and perma confuse

code/modules/mob/living/carbon/carbon.dm
Changes dsword from checking if the mob is wielded to if the dsword is wielded.
Bugs are bad.
Threw blue and black vulp into a dsword user :^)
:cl:
fix: Fixes dsword throw impact not working.
/:cl:
=> Fixes dsword throw impact not working.

code/modules/surgery/limb_reattach.dm
You can no longer reattach limbs when the required parent limb is not there, eg. you cannot attach a left hand when the left arm isn't there.
Fixes: #22817
Bug bad.
Goodbye Rayman.
Remove a skrell's hand, then arm.
Try to reattach just the hand, doesn't work.
Try to reattach the arm, then the hand, works.
Remove a IPC's hand, then arm.
Try to reattach just the hand, doesn't work.
Try to reattach the arm, then the hand, works.
:cl:
fix: You can no longer reattach limbs when the required parent limb is not there.
/:cl:
=> You can no longer reattach limbs when the required parent limb is not there.

code/game/gamemodes/nuclear/nuclearbomb.dm, code/modules/tgui/states/viewer_state.dm, paradise.dme
While there's an `observer_state`, it specifically grants full interaction to observers and admins. So in comes `viewer_state`, which only grants observational interaction, regardless of anything. A variant of `always_state`, basically.
Fixes #21475. There are use cases for just being able to see/keep track of the UI while not an admin.
https://github.com/ParadiseSS13/Paradise/assets/80771500/2d337755-52e2-432f-84c5-d9cd6a9a7cb5
Spawned a nuke, clicked on it as a ghost, and moved rather far away.
:cl:
fix: Observers can keep the nuclear bomb interaction window open regardless of distance
/:cl:
=> Add viewer_state for TGUI, an observational state

_maps/map_files/cyberiad/cyberiad.dmm
**What Does This PR Do**: Removes a varedited "plaque" tile and replaces it with the proper subtype. Note this is an exact replacement:  
https://github.com/ParadiseSS13/Paradise/blob/859a38cde20d9d2fbd0637b138627715d59d405c/code/game/turfs/simulated/floor/plasteel_floor.dm#L27-L30
**Why It's Good For The Game**: Varedits bad, duplicate object state bad.
**Testing**: Built and ran.
**Changelog**: NPFC
=> box: remove redundant varedited plaque

code/modules/reagents/chemistry/machinery/chem_heater.dm, code/modules/reagents/chemistry/reagents_holder.dm
Following up on my previous PR to nerf heating reagent holders with lighters and such, this is buffing the chemical heater to be a lot better than it was.
Before, the chem heater would heat for a portion of the difference in chemical temperature, and the target temperature (with a cap), which would mean that you'd just set the heater to `1000`, which was the best way to make it fast.
With these changes, the chemical heater will now heat the chemicals a certain amount, regardless of the current temperature difference. It will heat in increments of 40 degrees, with every upgrade tier adding 20 degrees on this.
While heating beakers and such with lighters was not very good for the state of chemistry, it did point out one thing: Chemical heaters suck. People don't like using them as they are …
=> Buffs the chem heater

code/controllers/subsystem/non_firing/SSmapping.dm, code/datums/chatmessage.dm
Removes some uneeded warnings
RA doesn't need to know if an admin deleted a client, I don't want my ears to get blasted by lavaland if I'm debugging something
today I found out that chemical crafting is still broken, but this is also just deleting some independent checks
NPFC
=> removes some unneeded error warnings

code/game/gamemodes/wizard/rightandwrong.dm
prevents people with offstation role from becoming a survivalist
bugfix
use the secrets panel to trigger the event multiple times
:cl:
fix: people with offstation role cannot become a survivalist
/:cl:
=> prevents people with offstation role from becoming a survivalist

code/modules/food_and_drinks/kitchen_machinery/smartfridge.dm
'disk compartmentalizer' does not accept unloading discs from boxes, it adds the ability to unload discs from boxes in addition to bags
Helps botanists unload disks from 'plant data disks box' into 'disk compartmentalizer'
Checked the unloading of boxes and bags with various items
🆑
tweak:  You can now unload botanical discs from boxes into disk compartmentalizer
/🆑
=> Adding unloading of botanical discs from boxes

code/modules/mob/living/silicon/robot/robot_mob.dm
Allows deathsquad borgs to turn their thermals on/off
Fixes: #22835
Fix good.
Spawn in a deathsquad borg, control them, I can see through walls.
Can't hear through walls though. Deaf squid.
:cl:
fix: Deathsquad borgs can now turn their thermals on/off.
fix: Deathsquad gets languages like other borgs now.
/:cl:
=> Deathsquad borgs can now turn their thermals on

code/modules/mob/dead/observer/observer_logout.dm
Fixes a possible runtime with observers logging out
This is less critical than the other PR, but this should probably be changed for consistency.
I can logout as an observer without any runtimes
NPFC
=> Fixes a possible runtime with observers logging out

_maps/map_files/RandomRuins/LavaRuins/lavaland_surface_althland_excavation.dmm, code/game/area/areas/ruins/lavaland_areas.dm
Made new path for the area, that doesnt use default /area/ruin/unpowered, now uses /area/ruin/unpowered/althland_excavation to avoid the core problem. Also slaps no lava helpers on places were lava shouldnt spawn
fixing oversights is good
works
:cl:
fix: Adds new area for Althland Excavation Ruin to give its unique zone
fix: Adds more lavahelpers onto Althland Excavation Ruin
/:cl:
=> Hot Fix for Althland Excavation Ruin

code/game/objects/structures/janicart.dm
title
Radial menus make it easier to grab something from the janicart without having to open a whole new window.
- Inserted and removed all possible items from it
:cl:
tweak: Janicart now uses a radial menu
/:cl:
=> Gives janicart a radial menu

code/modules/atmospherics/machinery/pipes/cap.dm, code/modules/projectiles/guns/projectile/shotgun.dm, code/modules/ruins/lavalandruin_code/dead_ratvar.dm
fixes some objects not being able to be proper examined
fixes https://github.com/ParadiseSS13/Paradise/issues/19955
I like being able to read stuff
examined all 3 objects
:cl:
fix: Fixes a couple of objects not being able to be properly examined
/:cl:
=> fixes some examine issues

code/modules/food_and_drinks/food/condiment.dm, code/modules/supply/supply_packs/pack_organic.dm
Adds a crate for 300 credits that includes a bottle of every condiment.
Perfect for rounds when botany is slacking, non-existent, or you're wanting more condiments than a newbie botany team can reasonably manage and you want to have plenty of different condiments for your food. I do have concerns with frost oil being orderable as it's cold sauce...but it shouldn't be that horrible, really, probably. It can be removed from the crate if it's deemed an issue.
Price can also, of course, be raised or lowered if needed.
1. Loaded game.
2. Ordered and Spawned a crate.
3. Confirmed contents of both.
4. Ate the mayonnaise.
:cl:
add: You can now purchase a crate of condiments from cargo for 300 credits.
/:cl:
=> Adds a Condiment Crate, Orderable from Cargo.

code/modules/antagonists/changeling/powers/fakedeath.dm
Ensures faking your death checks your status after the user input
Gotta fake your death properly
Faked my death. Don't tell the tax people
:cl:
fix: Faking your death as a cling checks the status properly now
/:cl:
=> [s]Ensure the fake death power checks the status again after input

code/modules/hydroponics/seed_extractor.dm
Removes an unnecessary to_chat in the seed extractor that happened to be targeting world.
I don't think we need to inform the entire server that this seed isn't a variant.
I don't think the entire server needs to know there are no variants.
Put a seed into the seed extractor
Take a seed out of the seed extractor
The entire server remains uninformed about my dastardly deed.
:cl:
fix: Seed extractor no longer broadscasts to the world when a seed is taken out.
/:cl:
=> [s] Seed extractor no longer broadscasts to the world when a seed is taken out.

code/modules/research/server.dm
This PR makes it so that the RND server will take damage in the environment its its warmer then 343.15 kelvin, instead of only between 293.15 to 343,15 kelvin.
Now the RND server will take damage from not only 40 degrees celcius to 70 degree celcius, but all the way up to 1e+31 kelvin/celcius
Compiled, run, upgraded the freezer and swapped it to heater at max temperature and checked if the RND Core server health went down, as well as turning it down to 2 kelvin, to check that it does indeed automatically heal back up
:cl: ppi
tweak: Update RND server to take damage at temperatures above 70 degrees.
/:cl:
=> RND Server will now take damage when its warmer then 70 degrees celcius

code/modules/mob/living/carbon/human/human_life.dm
Fixes the logic of hardcrit to have a set percent chance to kill you per tick, based on overall health, brain damage, and oxyloss.
The logic for determining if someone should die in hardcrit is currently broken. The variable deathchance is almost always negative, so it'll never kill you. If you've died to crit in the past 3 years, it's been from softcrit. Fixing this makes it so hardcrit is significantly more lethal, as I imagine the intent of the original author was.
[Here](https://www.desmos.com/calculator/w63wbsfhwk) is a tool that will let you check the chance of death per tick in hardcrit, with the formula in this PR.
The variable w represents brain damage.
The variable q represents health.
The variable z represents oxyloss.
Finally, y represents the chance to die on a given tick. …
=> Newer Crit (Hardcrit is fixed to be more lethal)

code/modules/mob/transform_procs.dm
Fixes #22868. Modsuit bags are actually moved inside you when you wear the modsuit, so we want to equip everything thats in our SLOTS, not every one of our contents.
Fixes #22868
See above. Also made sure that gorillas don't get stuff like adrenalin implants when they transfer.
:cl:
Fix: Becoming a gorilla while wearing a modsuit should no longer make the internal modsuit bag appear.
/:cl:
=> Fixes an issue with gorillas and modsuit storages

code/game/gamemodes/miniantags/abduction/machinery/experiment.dm, code/modules/antagonists/_common/antag_team.dm
Ensures that `prepare_announce_objectives()` is not wrapped in a list. I caught one of these in the review of the PR, but not the other ones. This fixes all the remaining ones.
Fixes #22873
It compiles, and it works.
:cl:
fix: Fixes an issue with abductor objectives not showing up
/:cl:
=> Fixes some chatbox errors

code/modules/martial_arts/martial.dm, code/modules/martial_arts/wrestling.dm
Fixes the explanation text for wrestling by bringing it more in line with other martial arts.
The current code refers to a tab that doesn't work, and suggests using a verb that doesn't work. While the martial arts tab still isn't great, it's the best we've got.
Loaded in, was able to learn how to suplex a vulp.
:cl:
fix: You can now properly get an explanation in-game for how to use the wrestling belt's moves.
/:cl:
=> Fix wrestling explanation

code/modules/mod/modules/modules_supply.dm, code/modules/telesci/gps.dm
Removes NODROP from the MOD hydraulic clamp module, it was intended for the GPS device.
Fixes #22885, oops
Spawned a MOD hydraulic clamp module, picked it up, and dropped it.
:cl:
fix: MOD hydraulic clamp module can be dropped and installed properly
fix: Deployed MOD GPS device can't be dropped after retracting it once
/:cl:
=> MOD hydraulic clamp module isn't NODROP anymore, flag transfered to MOD GPS device

code/modules/projectiles/guns/projectile/revolver.dm
Fixes #22893
Gives sawn-off improvised shotguns their sprite back.
Bug fixes are good fixes.
Loaded game, spawned improvised shotguns, sawed off one
:cl:
fix: Sawn off shotguns have their sprites back
/:cl:
=> Whaddya mean I can't saw off my boomstick - Fixes #22893
