ParadiseSS13/Paradise

code/game/objects/items/weapons/holy_weapons.dm

Fixes spellblade and sentient sword inhand sprites. Fixes #22912 
Weapons should be visible and bugs are bad.
Spawned in all scythe subtypes to check they have inhands for good measure, they did.
:cl:
fix: Sentient swords and spell blades are visible inhand once more.
/:cl:

Fixes spellblade and sentient sword inhands

---

code/__DEFINES/flags.dm
code/game/gamemodes/cult/blood_magic.dm
code/game/gamemodes/wizard/godhand.dm
code/game/objects/items.dm
code/game/objects/items/weapons/holy_weapons.dm
code/game/objects/items/weapons/twohanded.dm
code/modules/antagonists/changeling/powers/mutations.dm
code/modules/antagonists/vampire/vampire_powers/hemomancer_powers.dm
code/modules/mob/living/carbon/examine.dm
code/modules/surgery/organs/augments_arms.dm

This PR adds customised_abstract_text() proc for /obj/item which is only called in examine proc when item is abstract. 
It allows us to show that there is something instead of not showing anything when they have an armblade.
Do you see this huge bloody arm blade this changeling made of their arm? Uh, you dont? well ummm.. now you do. 
Items that have physical form like armblade should be shown on examine
Compiled, looked at changeling
:cl:
tweak: Abstract weapons(armblade, vampire claws, tentackle) that have physical form are now shown on examine with unuqie text
/:cl:

Abstract items can be shown

---

code/modules/projectiles/gun.dm
code/modules/projectiles/guns/energy/energy.dm
code/modules/projectiles/guns/energy/laser.dm
code/modules/projectiles/guns/energy/pulse.dm
code/modules/projectiles/guns/energy/special_eguns.dm
code/modules/projectiles/guns/energy/stun.dm
code/modules/projectiles/guns/magic/magic_staff.dm
code/modules/projectiles/guns/magic/wand.dm
code/modules/projectiles/guns/projectile/automatic.dm
code/modules/projectiles/guns/projectile/pistol.dm
code/modules/projectiles/guns/projectile/revolver.dm
code/modules/projectiles/guns/projectile/shotgun.dm
code/modules/projectiles/guns/projectile/sniper.dm

Makes weapon executions dramatically faster.
It also now depends on the kind of weapon:
`/gun/` Base Value: `6 SECONDS`
Pulse/Admin Weapons: `2 SECONDS`
Pistols: `4 SECONDS` _(includes u-ION, Mini E-Gun, and Blueshield/PDW)_
Laser/Disabler Weapons: `5 SECONDS`
Standard Rifles: `6 SECONDS`
Shotguns: `7 SECONDS`
Combat Weapons: `5 SECONDS` _(Combat Shotguns/ERT IK-60/Bulldogs)_
Snipers/LWAP/ALC: `8 SECONDS`
Wands/Magic Shit: `3 SECONDS`
12 seconds to execute someone is kinda insane. You could do so much more damage by just spam-clicking someone to death or simply grabbing a toolbox and beating them to death.
Also, Rule of Cool.
Shot a buncha skrell in the head.
:cl:
tweak: Tweaked headshot execution speed to be set at the weapon level. Reduced drastically across the board.
/:cl:

Drastically Reduces Execution Time for Handguns + Makes it Weapon-Dependent

---

code/modules/admin/verbs/adminpm.dm

Add ability to cancel out of the client selection prompt for Admin PM verbs
I got tired of misclicking it
See screenshot
:cl:
tweak: Added a cancel button to admin PM
/:cl:

Add cancel button to Admin PM verbs

---

code/modules/antagonists/changeling/datum_changeling.dm
code/modules/antagonists/changeling/powers/augmented_eyesight.dm
code/modules/antagonists/changeling/powers/become_headslug.dm
code/modules/antagonists/changeling/powers/biodegrade.dm
code/modules/antagonists/changeling/powers/chameleon_skin.dm
code/modules/antagonists/changeling/powers/contort_body.dm
code/modules/antagonists/changeling/powers/digitalcamo.dm
code/modules/antagonists/changeling/powers/epinephrine.dm
code/modules/antagonists/changeling/powers/fleshmend.dm
code/modules/antagonists/changeling/powers/hivemind.dm
code/modules/antagonists/changeling/powers/lesserform.dm
code/modules/antagonists/changeling/powers/mimic_voice.dm
code/modules/antagonists/changeling/powers/mutations.dm
code/modules/antagonists/changeling/powers/panacea.dm
code/modules/antagonists/changeling/powers/shriek.dm
code/modules/antagonists/changeling/powers/strained_muscles.dm
code/modules/antagonists/changeling/powers/summon_spiders.dm
code/modules/antagonists/changeling/powers/swap_form.dm
code/modules/antagonists/changeling/powers/tiny_prick.dm

Upscales changeling DNA from 10 to 20. Multiplies the cost of changeling abilities to compensate.
Have we considered that trying to balance changeling abilities around them costing rather 1 or 2 may be a poor idea? I feel this would open up the door for actual balance discussion regarding the cost of abilities.
Loaded the game. Checked costs. They were as planned. Bought things. Things worked fine.
:cl:
tweak: Changelings now have 20 DNA points to spend instead of 10. Ability cost have been changed to compensate.
/:cl:

Upscales Changeling DNA Costs

---

code/modules/reagents/reagent_containers/hypospray.dm

As title. New chemicals have been added into the hypospray allowed list, while some chemicals have been removed. This DOES NOT affect the CMO's Hypospray, as well as emagged hyposprays as they already accept all chemicals.
**Added:** 
- Iron
- Sanguine Reagent
- Sugar
- Sodium Chloride
- Mutadone
- Ephedrine
- Heparin
- Corazone
- Bicaridine
- Kelotane
- Diluted Omnizine (Godblood)
- Lavaland Extract
**Retained:** 
- Charcoal
- Cryoxadone
- Mannitol
- Salbutamol
- Saline Glucose Solution
- Menthol
- Omnizine
- Salicylic Acid
- Antihol
- Epinephrine
- Hydrocodone
- Insulin
- Mitocholide
- Oculine
- Potassium Iodide
- Rezadone
- Spaceacillin
- Synaptizine
- Teporone
**Removed:**
- Stimulants
- Blood
Right. Hyposprays have always had a list of acceptable chemicals that really doesn't adhere …

Changes what reagents are allowed within normal Hyposprays

---

code/modules/mob/living/silicon/robot/drone/drone_items.dm

fixes magnetic grippers sucking up light-tubes
fixes #22930 
Bugfix
Why does this work off afterattack, makes lightbulbs have a random chance to break
:cl:
fix: Engineering borgs can properly replace lights
/:cl:

fixes magnetic grippers sucking up light-tubes

---

code/modules/shuttle/shuttle.dm

This fixes #22934 by adding a check to the variable in charge of pushing to also check if they are a mob or not, thus preventing multiple gibbings of the same creature.
I call it soul removal, but hey, someone made an issue, and it is technically an issue, irrelevant of soul removal
https://github.com/ParadiseSS13/Paradise/assets/21987702/56506cde-1fbb-4d96-b452-ce4241a63755
:cl: ppi
fix: Fixes shuttle gibbing to not gib multiple times.
/:cl:

Fixes #22934

---

_maps/map_files/RandomRuins/SpaceRuins/oldstation.dmm
code/game/objects/structures/transit_tubes/transit_tube_pod.dm

Because it wouldn't be a big lewcc pr without a hotfix to follow
Fixes the transit tubes on the oldstation ruin, since I completely forgot to update them to the new pipes we use.
Fixes some issues with getting stuck in the kinds of transit tube stations used on oldstation.
This currently kinda breaks a ruin, sorry about that.
Loaded in, spawned the ruin, was able to take the transit tubes
:cl:
fix: Fixes the transit tubes on the oldstation ruin.
fix: You're now much less likely to get stuck in a transit tube at certain station types.
/:cl:

Transit tube hotfixes

---

code/game/gamemodes/cult/runes.dm
code/modules/mob/living/silicon/ai/ai_login.dm

Makes Runes actually invisible to AIs, you no longer get screentips from the runes
fixes #16604
The original coder here had a very clever workaround, that workaround also didn't work and searches world contents. Another day another weird oldcode laced with illicit substances slain. 
I can see a skrell but I'm afraid I can't see that rune in front of it, can't see the skrell either if I change it's invis
:cl:
fix: You can't see the screentips on runes now as the AI
/:cl:

Makes Runes actually invisible to AIs

---

code/modules/research/experimentor.dm

Resolves #18778
Ian and Runtime are now always unbuckled when teleported through the experimentor.
Invisible dog beds bad
- Buckled Ian to his bed
- Changed the code so "Destroy" would always summon Ian
- Experimented on literally 20 objects before I finally found one that would work with the verb I chose
- Noticed that the summoned Ian could be moved
:cl:
fix: Fixed Ian and Runtime having the potential to be buckled to invisible things when summoned by the Experimentor
/:cl:

Fixes summoned mobs from the experimentor being able to be buckled to nothing

---

code/modules/mob/living/simple_animal/hostile/headslug.dm

This give changeling eggs the xenomorph treatment, so that instead of gibbing, they will burst outta their chest!
Gibbing is bad, you now have a more valid reason to hide in the comfy darkness that is maint, and get to keep your body!
https://github.com/ParadiseSS13/Paradise/assets/21987702/d3951c8c-5dfe-49c2-93c3-3d673194538c
:cl: ppi
tweak: Changeling eggs now chestburst instead of gibbing.
/:cl:

Changeling eggs now chestburst instead of gibbing

---

code/modules/response_team/ert_outfits.dm

Paranormal ERT get a bible for cult soulstones and holy water tank blessing
hhggggg cult rounds where ert buy no prayer beads.
In all serious, important for them to have to bless water as backup and for soulstones.
confirmed all 3 ert had em
:cl:
tweak: Paranormal ERT get a bible for cult soulstones and holy water tank blessing
/:cl:

Gives ERT bibles

---

code/game/gamemodes/objective.dm
code/modules/mob/living/silicon/ai/latejoin.dm

Makes it so that the destroy AI objective is automatically rerolled into an assassination objective when the AI wipes their core.
Fixes: #21948
There's no longer a chance traitors end up with a moot objective when the AI cryos.
Two traitor skrells with the destroy AI objective and an AI are on station.
AI cryos.
The traitor skrells have their destroy AI objective replaced with an assassination objective for the other skrell.
:cl:
fix: The destroy AI objective is automatically rerolled into an assassination objective if the AI wipes their core.
/:cl:

Reroll destroy AI objective when the AI goes to cryo

---

code/__DEFINES/sound_defines.dm
code/game/gamemodes/cult/blood_magic.dm
code/game/gamemodes/cult/runes.dm

Changes a large amount of sound ranges for Cult Spells/Runes.
Summon Dagger: `17` -> `4`
Conceal Runes: `1` Before Rise/Ascend, `4` after. (was `4` constant)
Twist Materials: `17` -> `4`
Twist Airlock: `17` -> `7`
Recharge Item/Heal/Blood Magic: `17` -> `7`
Cult Cuffing: `15` -> `7` (this is in line with all other forms of cuffing)
Sacrifice: `17` -> `10`
Summon Ghost: `17` -> `10`
Right, before you all go and try to crucify me for buffing Cult.
There is nothing fun about getting meta-echolocated as Cult. Security will immediately get lethals and its now the arms race that Cult usually is. People should be rewarded for well-planned stealth operations.
Investigation should find the Cult. Not meta-echolocation from some random Doctor/Engi/etc.
Made a buncha spooky sounds in the darkness. …

Cult Sound Tweaks

---

code/__DEFINES/is_helpers.dm
code/game/objects/effects/meteors.dm

Makes it so meteors don't take damage from hitting railings.
Also makes it so empty asteroid turfs will not take away hits of the meteor.
Farragus starts out with a ghetto meteorshield, this PR will avoid that.
Spawned in some railings and meteors, they didn't go boom from the railings.
:cl:
tweak: Meteors don't take damage from railings anymore
/:cl:

Makes meteors not take damage from railings

---

code/game/objects/items/devices/megaphone.dm

Adds some additional logging when a player uses a megaphone.
This allows easier access to megaphone messages via the in-game log viewer. 
Used a megaphone.
Viewed in-game logs.
NPFC

Adds additional logging for megaphone

---

code/modules/shuttle/shuttle.dm

Makes shuttles take into account all turf color types and lights for transit. Light tiles would runtime as it'd try to copy over layered `atom_colours`, but not hard set `color`. Lights are copied over as well since as it wasn't taken into account originally.
Fixes #21679
https://github.com/ParadiseSS13/Paradise/assets/80771500/63845b79-81c8-491b-ae74-75de8001dd34
Placed a light tile in the mining shuttle, changed its color, and had the shuttle transit.
:cl:
fix: Light tiles in shuttles keep their color and light when in transit
/:cl:

Shuttles transit copies color and lights from turfs properly

---

code/modules/mob/living/simple_animal/bot/floorbot.dm

Fixes #22472
Fixes #22478 
Fixes floorbot eating up tiles nonstop.
Removes bridge mode from floorbot
Floorbot usage is rare, and discussed with people randomly and seems like, floorbot in on itself is not used much, but bridge mode function isnt even known in general. Removes this old and ancient mode/option
Flame Thrower an area, remove some tiles and space some. Watch the bot suffer
:cl:
fix: No longer gets stuck and eats up tiles, actually does place a tile
del: Removed Bridge Mode option
/:cl:

Floorbot bug fix + Bridgemode Removal

---

code/modules/reagents/chemistry/machinery/chem_dispenser.dm
code/modules/reagents/chemistry/machinery/chem_master.dm

Clicking on full Chem-Dispenser or Chem-Master with a beaker will now swap beakers instead of giving a warning.
I saw it on other SS13 servers and I think it would be a good QoL feature to add.
https://github.com/ParadiseSS13/Paradise/assets/20885860/6f967e3e-9dbf-4647-ab20-822858ffc704
Joined as chemist, upgraded chem-master buffer, made some Saline while constantly swapping beakers.
:cl:
add: You can now swap beakers inside chemistry machines with beaker in hand.
/:cl:

Allows chemistry beaker swapping

---

code/game/objects/items/weapons/RCD.dm

Makes RCDs not require grilles on a window to be deconned.
Still deletes the grille under a window if there is one present.
Fixes #22974
With the degrilling, this weird issue has been found. It works completely counterintuitive, and is a very weird design choice.
Could decon windows with and without grilles without any issues
:cl:
fix: Fixed RCDs not being able to decon windows without grilles
/:cl:

Fixes RCDs requiring grilles under windows for deconning

---

code/game/machinery/doors/airlock_types.dm
code/game/objects/items/stacks/sheets/sheet_types.dm

Does precisely what it says on the tin. Doubles cult door damage reflection from 10 to 20. Ups the runed metal cost to 3.
Cult doors are honestly weak. The fact that over 100 objects in the game, including a stunbaton and even just chucking a piece of metal at it, can quickly and easily break them is kind of bad. 
My hope is that it will help encourage on-station cult bases more if they have better means of defending said bases.
EDIT: After a brief discussion on Discord I have decided to go with upping damage reflection to 20 and tripling the cost to compensate. Cult doors must now be shot, speared, or axed down. After the discussion I thought it over and realized that they could still be pretty easily destroyed and could honestly stand to be a bit better.
1. Upped value
2. Tried to bonk …

Buffs Cult Door Damage Reflection to 20. Ups Runed Metal cost to 3

---

code/game/machinery/firealarm.dm

Fixes the following issues:
fixes #22836 
Fire alarm being constructed at builders location
Fire alarm assembly appearing to be completely built
Fire alarms works as intended, now exploit free!
Compiled and ran, deconstructed a fire alarm, rebuilt it, checked that the fire alarm was added to that area, and it updates properly during every alert level.
:cl: ppi
fix: Fire alarms can now be properly built
/:cl:

Fixes firealarms

---

code/datums/helper_datums/teleport.dm
code/game/objects/effects/anomalies.dm

Bluespace vetus doesn't spark from it's anomalies, by adding an argument to teleportation procs
6% tidi on hardmode bluespace vetus with 4 people is not good. 
Should make it sound better.
Would make it part of hardmode tweaks but would like it approved sooner
confirmed sparks happened with normal teleports not no core bluespace anomalies
:cl:
fix: Bluespace vetus doesn't spark from it's anomalies, no more tidi of 6%
/:cl:

Bluespace vetus doesn't spark from it's anomalies

---

code/game/atoms.dm
code/game/objects/items.dm
code/modules/clothing/clothing.dm
code/modules/mob/living/carbon/human/human_defines.dm

Moves a variable to a higher hierarchy, making it not be put on every atom.
Makes VV a bit easier to read, while still working correctly
Tried to leave fibers on a door, checked that it still worked with a forensic scanner.
NPFC

Moves the `can_leave_fibers` var to `/obj/item/clothing` instead of being on `/atom`

---

code/game/objects/items/weapons/storage/garment.dm
code/game/objects/structures/crates_lockers/closets/secure/scientist.dm

Moves superior welding goggles from RD locker into garment bag, adds science goggles and diagnostic sunglasses.
RD has the most poor garment bag of all roles, even more poor than psychologist.
Welding goggles should be in garment bag just like CE garment bag.
Diagnostic sunglasses are only obtainable through obscure crafting menu recipe and are otherwise never used, this should continue trend of Heads getting their own sunHUDs.
Beret was added because most other heads have berets.
Joined as RD, checked garment bag, questioned why science berets do not exist.
:cl:
add: Added more cloth to RD garment bag.
/:cl:

Added extra items to RD garment bag

---

code/game/machinery/computer/aifixer.dm

Fixes #23002 
The AI fixer no longer has an overlay when powered off.
Bugs are bad, yaya?
Spawned an AI fixer. Cut the power.
:cl:
fix: Fixed AI integrity Restorer Overlay's displaying when powered off
/:cl:

Fixed the AI Fixer's Power Problem

---

code/game/objects/items/weapons/storage/fancy.dm
code/game/objects/items/weapons/storage/lockbox.dm

This lets you alt+click to lock and unlock lockboxes
Apcs', air alarms, secure lockers, secure crates can already be locked and unlocked via altclick, this is just bringing lockboxes in line with that.
https://github.com/ParadiseSS13/Paradise/assets/21987702/45229320-9256-4509-8d49-729320c55b84
See Above
:cl: ppi
add: Added the ability to lock and unlock lockboxes with altclick.
/:cl:

You can now altclick lockboxes to open them

---

code/modules/power/engines/tesla/energy_ball.dm

*Everything except grounding rods and tesla coils
Makes every zap follow normal targeting before the Tesla rework PR, with the slight change that APCs are preferred over all other machinery. This way, things like flux anomalies will actually target mobs again, instead of just going to that APC 3 rooms next.
I accidentally heavily nerfed flux anomalies for 3 months, this will help them get back into it again.
Flux anomalies actually were dangerous again
:cl:
fix: Fixed zaps targeting APCs over anything else
/:cl:

Fixes zaps focusing APCs over everything*

---

code/modules/projectiles/guns/projectile/automatic.dm

Changes the ARG rifle's description to reflect who actually uses it.
THE LORE, JIM, THE LORE.
NT doesn't use this rifle, the TSF does. We don't spread misinformation on the internet in this household.
- Loaded in
- Spawned ARG
- Description is updated
:cl:
tweak: Updated the ARG's description
/:cl:

Updates the ARG's description

---

code/modules/food_and_drinks/recipes/recipes_microwave.dm

It fixes my 2 AM coding error. Philly Cheesesteak uses Onion instead of Cabbage.
Who the hell eats Cabbage on a Philly?
1. I used an onion.
:cl:
fix: Philly Cheesesteak now correctly uses onions instead of cabbages.
/:cl:

Philly Cheeseteak now correctly uses Onion

---

code/game/objects/structures/false_walls.dm

Changes the false wall layer to the turf layer. 
The current false wall layer means it shows above wall mount objects, making it stand out if a false wall is made on an APC wall or others.
Before:
After:
Spawned in, made a lot of false walls with various objects above and below, tried to see what might break, it worked fine.
:cl:
tweak: Wall mounted objects will now show above false walls instead of inside.
/:cl:

Adjusts false wall layer so wallmounts are above

---

code/modules/mob/living/simple_animal/bot/syndicate_bots.dm

title
It is a sentry bot not an ed209
BEFORE
AFTER
- Destroyed it multiple times to verify its remains
:cl:
fix: Sentry bot no longer drops ed209 loot when destroyed
/:cl:

Sentry bot no longer drops ed209 loot when destroyed

---

code/game/objects/items/weapons/storage/belt.dm
code/modules/clothing/shoes/misc_shoes.dm
code/modules/mod/mod_types.dm
code/modules/mod/modules/modules_general.dm
code/modules/mod/modules/modules_service.dm
code/modules/response_team/ert_outfits.dm
code/modules/surgery/organs/augments_arms.dm

Adds a new janitorial toolset implant, that is mostly the same, but with a bluespace light replacer, the big space cleaner spray bottle and deluxe soap, the implant is also EMP proof.
Removes the bluespace light replacer, and a spray bottle form their bags/belt, as they're in the implant now and dont need two, and moves the bluespace trash bag to the belt.
Adds a new MODsuit module, "boot heating" to dry floors as you walk, much like the dry galoshes, for GAMMA jani ert.
Gives amber ert dry galoshes, adds and gives red ert lightweight dry galoshes, as they have heavy armor already, they don't need double slowdown.
Replaces the Red ert mini egun with a normal one, and replaces the Gamma ert egun with a advanced energy gun, for fighting those pesky mice and man eater kudzu, and for self …

Janitorial ERT rekit/buff and a few additions for the jani ert squad.

---

code/__HELPERS/unsorted.dm

This adds a volume scan to the gas analyzer when used on full or empty pipes. This does not add volume information when scanning the environment.
This information can already be found by applying the ideal gas law, but you are left guessing at what measurement to use. This makes the information more accessible to the player and allows them to find the volume of empty pipenets, which can't be done without just counting your pipes and adding them up. Its a fairly minimal change to anything atmos related as volume isn't terribly important in its current state, but it does effect gas systems in niche applications and adds a bit more flavor to scanning pipes.
spawned in, scanned a bunch of pipes, volume showed up correctly.
:cl:
tweak: Gas analyzers now show the volume of scanned pipes.
/:cl:

Adds volume to gas analyzer info

---

code/game/machinery/computer/cloning.dm

Changes some cloner error messages to be clearer to new players by suggesting other ways to continue, as well as replacing most instances of 'scanning' with 'cloning' in cloner error messages. Also adds a new error message if a burn husk victim is placed inside the cloner, differentiating from changeling absorb husks.
I have been told that some of the cloner error messages are not very initutive. This change should help with newer players identifying cloning issues.
Xenomorphs:
Slimepeople:
Vox:
IPCs:
Burn husks:
Changeling Absorb Husks:
:cl:
tweak: Changed cloning messages to be more user friendly to new players
/:cl:

Updates some cloner error messages to be clearer

---

code/modules/mob/living/carbon/carbon_emote.dm

Changes up *twirl a bit.
- You will always twirl the item in your active hand (you can still twirl things in your offhand).
- You can no longer *twirl abstract items, except grabs.
- If you *twirl a grab, you twirl around the person you're grabbing.
Adds a fun interaction and makes *twirl more intuitive. (Also, twirling abstract items isn't great - how do you even twirl an armblade or a slapper?)
Recorded the above gif and twirled a couple other items in my bag. Also, failed to *twirl a slapper and an armblade
:cl:
add: You can now *twirl people!
tweak: You can no longer twirl abstract items
tweak: *twirl now prioritizes your active hand
/:cl:

Tweaks *twirl

---

code/game/objects/items/granters/action_granters/summon_cheese.dm
code/modules/food_and_drinks/food/foods/ingredients.dm

Fixes a bug with summon cheese by adding a subtype of cheese wedge that has the cheese reagents pre-installed.
I will never forget the moment I discovered this bug. I was walking down the hallways of the NSS cyberiad, and heard whispers of an explorer whom found magical treasures beyond belief. Lo and behold, a man dressed in a wizard costume appeared before me. I gasped, expected to be met with a swift end at the hands of an EI NATH!, but no such fate befell me. Instead, he simply spoke a short invocation. To my delight, he was quickly surrounded by cheese! In my delighted fervor, I very quickly picked up the wedge, only to find out that my beloved cheese slice contained no cheese at all, and simply vanished before my eyes! For a moment, I was stunned. "There's nothing left of the cheese …

Summon cheese no longer summons cheeseless cheese

---

code/modules/mob/living/carbon/human/human_examine.dm

Title
There's no good reason to exclude slime people from this system (and, most likely, it was not intentional for them to be excluded)
Loaded in, examined myself, CMA'd into a slime, examined myself again
:cl:
fix: You can now see slime people's physiques
/:cl:

Fixes slime people physique not showing

---

code/__HELPERS/AnimationLibrary.dm
code/game/objects/items/weapons/holy_weapons.dm

Fixes #23039 and makes the item actually function somewhat properly.
If you just enable it, then the clown will be greyscaled forever. While funny, this is a bit too much I'd say.
One issue I found was that moving around as the clown would instantly zap you to greyscale or back. Don't have much time to look more into it sadly.
Fixes bugs
Spawn as a clown and spawn prayer breads and hold it.
Equip it afterwards in my pockets or so and watch the clown turn normal again.
Drop it for the same effect
Delete it as well
:cl:
fix: Makes prayer breads actually work
/:cl:

Fix prayer breads making it actually smite clowns

---

_maps/map_files/RandomRuins/SpaceRuins/abandonedtele.dmm

Adds a pump between the pressure tank and connector on the abandoned tele ruin. 
As it stands, you can only get 12,000 or so of the total 20,000 moles of gas out of the pressure tank before refilling becomes horrendously tedious as it will only fill the attached canister until the tank and the canister's pressure equalize. If there's 20,000 moles availible, you should have access to all 20,000 moles, a pump let's you empty it. 
Spawned in, found the ruin, made sure it existed and changes were present
:cl:
tweak: Adds a volume pump to the abandoned teleporter ruin.
/:cl:

Tweaks the Abandoned tele ruin pipes

---

code/game/objects/structures/transit_tubes/station.dm

This PR applies some checks to dispenser stations in Bumped that were missing and passes in a mob instead of an atom to prevent inanimate passengers. I didn't generalize this because there's only two types involved and the checks. I also split the logic into two conditionals to make it easier to read/reason about.
These checks belong here and cause all kinds of problems if not. For example bumping into the dispenser tube while riding a janicart sends the cart off while leaving the player buckled to nothing.
Tested dispenser tubes while buckled to an object, attempted to throw non-mobs into the dispenser.
NPFC (these dispensers aren't mapped in anywhere right now)

Apply living checks to dispenser stations.

---

code/modules/client/preference/preferences.dm

lets people open their character creator before SSatoms is set up, fixes a bunch of runtimes from this too
It's a lot nicer to be able to change your character and prefs than not
Looked at my choices multiple times, before and after SSatoms got set up
:cl:
fix: You can now open your character creator before SSatoms is set up
/:cl:

lets people open their character creator before SSatoms is set up

---

code/_onclick/hud/alert.dm
code/modules/mob/living/simple_animal/friendly/diona_nymph.dm

Lets diona gestalts drop diona nymphs that they've picked up
It's kind of weird to be able to pick something up, but not drop it. Also, if a gestalt picks up a dead sentient nymph, there's no easy way to remove it.
Picked up and dropped 1-2 nymphs in various orders
:cl:
add: Dionae can now drop nymphs they've absorbed
/:cl:

Dionae can now drop nymphs they've picked up

---

code/modules/food_and_drinks/food/foods/ethnic.dm

I didn't realize that the sweet and sour meatballs was a vendor food or coded to have an icon of it showing in the Chang vendor. This makes it show a proper icon instead of a broken sprite sheet.
Fixes #23100 
Broken spritesheet bad.
I loaded the game and clicked the vendor.
:cl:
fix: Mr. Chang now correctly displays an icon for Sweet and Sour Chickenballs
/:cl:

Fixes Sweet and Sour Chickenballs icon

---

code/game/objects/items/devices/traitordevices.dm

Fixes handheld mirrors so you can now alter body accessory and other body marking options, bringing it in line with the mirrors placed around the station. I am assuming body customization options should have been included given this from the PR that added the mirror. ``allowing all the same customization options as the ones scattered across the station in a pocket item.``
Fixes #22966 
Bugs are bad, and the handheld mirror should be useful to species without hair to change.
Spawned in as nian, unathi, and human. Checked that they all had the option to alter body markings and accessories. 
:cl:
fix: Handheld mirrors now properly allow you to alter body appearance.
/:cl:

Fixes lack of body customization options for the handheld mirror

---

code/game/gamemodes/miniantags/demons/shadow_demon/shadow_demon.dm
code/game/gamemodes/miniantags/demons/slaughter demon/slaughter.dm
code/game/gamemodes/miniantags/pulsedemon/cross_shock_component.dm
code/game/gamemodes/miniantags/pulsedemon/pulsedemon.dm
code/modules/surgery/organs/organ_internal.dm
paradise.dme

adds a pulse demon demon heart, the perpetual pacemaker
Functions as a very powerful light source if you refuse to eat it, but if you do you gain the following stats:
1. A nerfed version of the pulse demons shock
2. A slow recharge on cells within your person
3. Shock immunity
4. A permanent glow around yourself 
This, like the other hearts is just recolored using the color var
We do this for all the other demons, why not pulse? Gives wizards for example more to do and a crew member can put this to good use if they get access to it. It's also easy to miss a pulsedemon death so this fixes that
millions of skrells were turned into fried seafood today
:cl:
tweak: adds a pulse demon demon heart, the perpetual pacemaker 
fix: fixes demon hearts being nulled when removed
/:cl:

adds a pulse demon demon heart

---

code/modules/reagents/chemistry/reagents/misc_reagents.dm
code/modules/reagents/chemistry/recipes/medicine_reactions.dm

Slightly ups the produced volume of Ash from Oil's temperature reaction.
Tweaks Oil's temperature reaction to only boil and cause a fire if the beaker doesn't have enough empty space remaining (requiring as much empty volume as the oil's), as opposed to every time if the volume is >30u.
Tweaks the Charcoal reaction to require more Salt, effectively lowering the amount of Ash needed.
While burning paper is fine and dandy, it's a bit ridiculous that the self-reliant method requires you to make a dozen batches of Ash 15u at a time to even get anywhere. The sheer amount of Ash you need to make a decent amount of Charcoal is also quite silly.
These changes allow you to make more Ash per batch (depending on the size of your beaker) and tones down how much of it you blow through while making a …

Tones down the demand for Ash

---

code/modules/mob/living/carbon/human/human_mob.dm

There are two sets of positive and negative flavor messages you can occasionally get while giving CPR, depending on how effective the CPR is - except due to a bug only the negative set would ever show up. This PR fixes this so the proper message shows up during effective CPR.
Fixes: #23004
Immersion restored.
- Kill someone
- Start doing CPR with chest compressions and rescue breaths
- Observe the positive flavor messages
:cl:
fix: CPR effectiveness messages now properly reflect effectiveness
/:cl:

CPR effectiveness messages now properly reflect effectiveness

---

code/game/objects/items/weapons/holy_weapons.dm

Makes it so that dark blessing has a visible in-hand sprite again.
Fixes: #23055
Invisible armblade bad.
Be a skrell.
Pick up a dark blessing.
It's now actually visible.
:cl:
fix: Dark blessing now has an in-hand sprite again.
/:cl:

Fixes dark blessing not having an in-hand sprite

---

code/__DEFINES/directions.dm

Makes it so that FLIP_DIR no longer works unreliably when the dir does not contain east/west or north/south.
Fixes: #22331
Define should work reliably.
NPFC.

Fixes FLIP_DIR_HORIZONTALLY/VERTICALLY

---

code/modules/admin/verbs/infiltratorteam_syndicate.dm

Gives Syndicate infiltrators ACCESS_CONSTRUCTION instead of ACCESS_ENGINE.
This PR aims to give syndicate infiltrators basic engineering access. To be quite honest, our access defines are quite fucked and misused. ACCESS_CONSTRUCTION is the define used for basic engineering access, which was the intentended to be given to infiltrators with ACCESS_ENGINE. 
Be a syndicate infiltrator
I am able to walk into engineering
:cl:
fix: Syndicate infiltrators now have basic engineering access.
/:cl:

Gives syndicate infiltrators basic engineering access

---

code/__DEFINES/dcs/signals.dm
code/game/objects/structures/morgue.dm
code/modules/mob/dead/observer/observer_base.dm
code/modules/mob/living/living.dm

Morgue tray now updates properly when you re-enter/exit your body.
Fixes: #22876
Currently a draft PR so I can fix some remaining issues
Morgue trays should accurately represent whether the corpse inside is currently revivable, or could viably be revived in the future.
Enter a morgue tray and die.
Morgue tray light is now green.
Exit my corpse.
Morgue tray light is now purple.
:cl:
fix: Morgue tray now updates properly
/:cl:

Morgue tray now updates properly

---

code/modules/projectiles/guns/energy/laser.dm

The LWAP will only pierce one rwall now
updates code comments for lwap projectile
Lwap now peirces resin structures like normal walls.
Piercing more walls was good for lwap, but let us not have it work on multiple layers of reinforced walls, so things like the AI don't get 2 tapped in 5 seconds. Xray at least is less common, and takes more than one clip to kill and much more time.
Xeno resin structures now get pierced like normal walls
Shot a lot of combinations of objects, walls, rwalls, etc
:cl:
tweak: Lwap can now only pierce one reinforced wall, and pierces resin better
/:cl:

makes the lwap not pierce infinite r_walls, pierces resin like walls

---

code/modules/admin/admin_verbs.dm
code/modules/admin/verbs/debug.dm
code/modules/mob/dead/observer/observer_base.dm

This PR moves the "Jump to Ruin" action from admin-restricted to available as a ghost. It also removes some behavior from the proc to make it more appropriate for ghost use (changing the use of `admin_forcemove`, doesn't message admins). The ruin names and descriptions are also not printed to chat; some of these are not well-written/lore-accurate.
There's currently no good way as a ghost to find ruins on the planet/in space -- they don't (necessarily) have unique areas and so can't easily be listed in the existing Teleport menu. Since ghosts can already teleport and travel the whole world space having this available to them doesn't seem unreasonable.
Logged in, ghosted, made sure verb was available, used verb.
:cl:
add: "Jump to Ruin" now available as a ghost action for ashland/space …

move 'Jump to Ruin' from an admin to a ghost verb

---

code/modules/surgery/organs/eyes.dm

Adds an EMP weakness to welding shield eyes.
Every other cybernetic eye has a form of weakness to EMPs, except welding shield eyes which grant you flash protection for free with no downside. For consistency sake, and giving the implant a downside, I think filling out 'EMP weakness' on Paradise station balance bingo would be adequate.
EMPed myself a few timeswith numerous combinations of cybernetic eyes. Confirmed welding shield eyes both made a flashing effect, and took cybernetic eye damage while retaining their flash protection.
:cl:
tweak: Welding shield eyes now have a weakness to both weak and strong EMPs!
/:cl:

Adds EMP weakness to welding shield eyes

---

code/game/objects/items/weapons/vending_items.dm

Changes the vendor units code so that the description isn't set as full in every case, sealed tight when there's more than 30 items (arbitrary number), lists the number of items when there's less than 30 and more than zero and finally when there's 0 items it has the empty description.
Fixes #22899 
Removes a misleading description
Compiled with no errors and I tested it on a nanomed vendor in medbay, worked as expected.
:cl:
fix: Fixes the vendor restock unit description always being full
/:cl:

Bugfix/issue 22899/vendor restocking unit's description is misleading

---

code/modules/pda/PDA.dm

fixes pdas not being able to have their ids removed/added while on the ground, you can now insert/remove the ID inside of them while they're on the ground
fixes #22641 
less annoying to drag around a bunch of PDAs and IDs, also a bug
I did it
:cl:
fix: PDAs can once again have their IDs removed/added while on the ground
/:cl:

fixes pdas not being able to have their ids removed/added while on the ground

---

code/game/objects/items/weapons/powerfist.dm

Changes the powerfist to drain a set amount of pressure per hit instead of moles from the attached air tank. This means cooling down tanks will no longer provide additional hits. Pressure drain is kept the same.
Level 1: 58 hits
Level 2: 29 hits
Level 3: 19 hits
Powerfist balance is dubiously based around a gas drain that is supposed to limit the amount of hits per level. This system works off of the moles inside of the tank instead of pressure, which would realistically be what generates the force. Draining moles means that if you cool down the air to increase the moles inside, a tank of the same pressure would provide a drastic increase in hits, effectively nullifying any cost per use and allowing the user to set it to the highest level all the time. At level 3, a tank at room temp(273 …

Changes the powerfist to work off pressure

---

code/__DEFINES/flags.dm
code/game/objects/items.dm
code/game/objects/items/toys.dm
code/game/objects/items/weapons/defib.dm
code/game/objects/items/weapons/storage/belt.dm
code/game/objects/items/weapons/stunbaton.dm
code/game/objects/items/weapons/tanks/tank_types.dm
code/game/objects/items/weapons/weaponry.dm
code/modules/martial_arts/judo.dm
code/modules/mob/living/carbon/human/human_inventory.dm
code/modules/mob/living/carbon/human/human_update_icons.dm
code/modules/mob/living/carbon/human/species/_species.dm

All belts and some belt slot items now could be worn if you do not have a jumpsuit, and they also do not get unequipped when a jumpsuit is unequipped.
Full list of items:
- All belts, including the Judo Belt and Belt Defibs
- All emergency tanks (Oxygen, Nitrogen, Plasma) and specialised belt tanks (Plasma and Nitrogen)
- Katanas and Toy Katanas (NOT energy katanas)
- Stunprods
- And of course, inflatable ducks (How could I forget?)
Also comments out redundant code in regards to unequipping items in `human_update_icons.dm`.
It always makes me unsure why you can't wear a toolbelt while you don't have a jumpsuit, considering that you can do that easily IRL, so this PR aims to change that behaviour.
This also has the added benefit of making it so vox and plasmamen don't lose their tanks that …

Belts and some select belt slot items no longer require a jumpsuit to wear

---

tools/mapmerge2/merge_driver.py

This PR fixes merge conflict marker creation. I was being too clever with default arguments and this would result in types like `>>>/obj_conflict_marker` which is not a valid typepath. I also renamed `type` to `typ` because `type` is a reserved word in Python and I want to avoid any bullshit lexical scoping problems.
Mapmerge failing is bad.
Looked very carefully at the code with my eyes
NPFC

fix conflict marker creation

---

code/game/turfs/simulated/floor/chasm.dm
code/modules/mining/equipment/wormhole_jaunter.dm
code/modules/mining/machine_vending.dm

Chasms now store mobs in a storage object, persists across turf changes.
Clings can crawl out via revival
A chasm recovery grenade can be used on the chasm to teleport *all* mobs in *that* chasm tile to random beacons on station.
Chasm recovery grenade can be used outside of chasms to make a shit load of wormholes to station beacons.
1500 points from mining vendor.
Getting permakilled to chasms via lag sucks, this adds a recovery function, as well as a funny grenade for more evil uses.
slightly outdated videos:
https://imgur.com/a/pEsrz3M
https://imgur.com/a/mi1Qtrf
Chasmed, revived, grenaded stuff
:cl:
tweak: Clings can climb out of chasms
tweak: Chasms no longer delete mobs but hold them inside
tweak: Adds the NT drunk dialer, a jaunter grenade that can make a bunch of wormholes, or …

Adds the NT drunk dialer, chasm recovery grenade

---

code/controllers/subsystem/SSticker.dm

makes ssticker fire twice as fast
It makes ssticker time based statistics more consistent, such as time before the round
``/datum/controller/subsystem/ticker/fire | 0.027 | 3.477`` ssticker is pretty inexpensive, so this should be fine
Started, delayed, then ended the round
:cl:
tweak: Most ticker related time tracking is now more consistent
/:cl:

makes ssticker fire faster

---

code/modules/antagonists/vampire/vampire_powers/hemomancer_powers.dm

Fixes an oversight with hemo claws being used when clicking tiles, resulting is shorter and more awkward amounts of slices.
Clicking a tile shouldn't waste your important vampire ability. No more having paper blood daggers for hands that break after a single slap against someone. Also consistency is nice.
yes
:cl: DGamerL Octus
fix: Fixed hemo claw charges being used from clicking tiles
/:cl:

Fixes a bug with Hemo Claws being spent on tile clicks

---

code/modules/crafting/craft.dm
code/modules/crafting/recipes.dm
code/modules/food_and_drinks/kitchen_machinery/smartfridge.dm

Title. Improvised gauze (from cloth) can be treated with medicine and made into normal gauze (which heals damages on application), and ointment can be crafted with plastic and some reagents.
- 6 Improvised Gauze
- 30u Styptic Powder
- 10u Sterilizine
... makes 6 normal gauze
- 2 Plastic Sheets
- 10u Water
- 30u Silver Sulfadiazine
- 10u Sterilizine
... makes 6 ointment
The PR also refactors crafting code to properly work with multiple reagents and allows `/obj/item/stack/medical` to be put in medical smartfridges.
Giving medchem more to make than patches and pills is good, and gauze/ointment are useful alternatives to straight styptic powder/silver sulfadiazine patches. Sterilizine is also a chemical that doesn't see much use, and this application makes sense for it (to sterilize the …

Makes gauze/ointment craftable; refactors a bit of crafting code

---

code/game/gamemodes/changeling/changeling.dm

Regenerative Stasis will now take **50** seconds up from 40 seconds.
Ignore any time I said "one minute" or "sixty seconds" below, balance team requested it changed to 50 seconds and I'm too lazy to edit every instance of the time mention.
As stated in my pitch to Mr. Balance Man, "Cling has gotten a lot of love and attention over the last year, significant power increase, and we cut out the most common ways to kill it - now there's only usually static places to kill it. Combine this with the fact we've been introducing larger maps like Farragus, Clings now enjoy a massive degree of safety armblading security so long as they just do it somewhere away from a gibber/cremator or by destroying these first." The 40 second revive existed before we cut down on the options available to kill …

Increases the duration of Regenerative Stasis to 50 seconds

---

code/modules/clothing/suits/armor_suits.dm

fixes reactive frost armor shooting at ghosts
bugfix
:cl:
fix: Reactive frost armor no longer shoots at ghosts
/:cl:

fixes reactive frost armor shooting at ghosts

---

code/game/objects/items/weapons/storage/fancy.dm
code/game/objects/items/weapons/storage/lockbox.dm

Emagged lockboxes responds correctly, and gives you feedback on altclick that the box is broken, as it would when you hit it with your id.
Getting Access denied on an emagged lockbox sends the wrong information
compiled, tested locking, unlocking with access, and with emag to confirm that it now provides the player with correct information.
:cl: ppi
fix: Fixes emagged Lockboxes saying Access denied  when altclicked.
/:cl:

Fixes an oversight when altclicking emagged lockboxes

---

code/modules/awaymissions/mission_code/beach.dm

Ports fix of drip proc from [this commit](https://github.com/ss220-space/Paradise/commit/6f91f3c215ff1b1d046cf5353638bbcac4318dee)
This is bad
This is good
Spawn waterfalls, checked them in game
:cl:
fix: Change waterfall drip recursive timer to loop one
/:cl:

Fixes waterfall drip recursive timer to loop one

---

_maps/map_files/RandomRuins/SpaceRuins/syndie_space_base.dmm
code/_globalvars/lists/misc_lists.dm

Fix syndicate outpost camera network and change pipes/cables placement to be more convinient, on top of that i added some "warning stripes" under sinks to make them more "visible" and added light replacer with boxes to replace lights.
Add some QoL stuff and reduce some shanenigans.
Compiled and it works.
:cl: Venuska1117
tweak: Fix Syndicate Outpost camera network, moves pipes away from glass floor in "service" section and remove dual pipe in one tile.
/:cl:

[s] Fix Syndicate Outpost and Cameras

---

code/modules/mob/living/carbon/human/human_mob.dm
code/modules/mob/living/carbon/human/human_organs.dm
code/modules/surgery/bones.dm
code/modules/surgery/cavity_implant.dm
code/modules/surgery/encased.dm
code/modules/surgery/generic.dm
code/modules/surgery/implant_removal.dm
code/modules/surgery/organs/organ.dm
code/modules/surgery/organs/organ_external.dm
code/modules/surgery/organs/pain.dm
code/modules/surgery/organs_internal.dm
code/modules/surgery/other.dm
code/modules/surgery/robotics.dm

Rescopes `custom_pain` to be a proc on `/obj/item/organ` instead of mobs.
This will prevent custom pain messages to be clouded up if there are multiple burn wounds/broken bones/damaged organs on a person.
- Won't only give chat messages for 2 of your total burn wounds/broken bones/damaged organs
- Still won't spam your chat as much as it used to
Gave myself a burn wound, broken bone and a pierced lung. All messages showed up in my chat.
NPFC

Refactors custom_pain to work on organs instead of on mobs

---

code/controllers/subsystem/SSjobs.dm
code/game/jobs/job/job.dm
code/game/jobs/job/silicon_jobs.dm

Makes sure that Cyborgs and AIs don't get a bank account assigned on roundstart.
Alright so, let's first take a look why this even happened.
First, everyone gets created as a human/whatever race, and then they get equipped for their job. The equip for Cyborgs is that they get Roboticized, meaning that the borg is created. The issue is that right before this, they get assigned a bank account which is thus linked to the human mob.
Then why is this good?
AIs and Cyborgs don't get paid by Nanotrasen. There is no reason for them to have a bank account that just siphons funds for no reason.
And for those arguing Corporate is a reason for this:
The **station** should be making money on this lawset. Revenue for Nanotrasen =/= revenue for the sillicons.
Resolves #22364
Spawned in as a roundstart …

Cyborgs and AIs now don't get a bank account assigned.

---

code/modules/mob/living/carbon/human/species/machine.dm
code/modules/surgery/organs/organ_external.dm

Removes damage mod from ipcs.
Prevents IPCS from using limb damage mods. The only thing that uses this is robo limbs, which ipcs will never not have.
IPCs still have a damage mod. For lasers / punches, it balances out.
Anything that does adjust brute loss or adjust burn loss however, does about 37% more damage than it should.
Chemicals, atmos, fire, magic, special attacks from mobs, a whole bunch of other mechanics do this
As such, we fix this by removing the damage mods ipcs have internally to counter their resist by robo limbs, and prevent them from getting the damage mod from robo limbs. We don't make limbs more protected, ipcs will never get less protected limbs (organic limbs), so we will not have to worry about it.
The only way this would be funny is if an admin var edited the limbs …

Removes the IPC damage mod. For real this time.

---

code/game/machinery/vendors/vending.dm
code/game/objects/items/weapons/vending_items.dm

Fixes vendor refills not working correctly due to a recent bugfix.
Also cleans up some code because my god this needed it
Refills should work aaaa
First is one that was just used to refill something, second is a fresh one from cargo/admin spawning
After restocking most of the vendor
See above
:cl:
fix: Fixed vendor refills not working
/:cl:

Fixes vendor refills not working

---

code/game/objects/structures/crates_lockers/closets/secure/medical_lockers.dm
code/modules/mining/machine_vending.dm
code/modules/projectiles/ammunition/energy_lens.dm

- triples the charge required to fire one shot with the BASIC (read: **NOT ADVANCED**) plasma cutter. This means you now only get 13 shots (and 2% left) from a full mag. 
- removes a bonus shelter capsule from the plasma cutter kit (also renames it to just "plasma cutter")
- gives paramed a drill instead of a cutter
Remember #22153? I have SEVERELY underestimated basic cutter's power. I have, accidently, created a new meta and I'm not sure whether I like it.
I thought a while about how to make it more balanced - my idea was messing with it's charge.
The more a shot costs, the more you have to recharge. The more you have to recharge, the more plasma you waste. The more plasma you waste, the less points you get from ORM.
I don't want to fully kill the option - I just want to make it have …

Nerfs the basic plasma cutter. Yep.

---

code/modules/unit_tests/areas_apcs.dm

CI now shows the type of the area instead of the name. If the area has multiple APCs, it now lists the locations of the APCs.
Makes it easier for people to fix their CI.
Yeah, it runs
NPFC

Makes some alterations to the APC CI

---

code/modules/mob/living/carbon/human/human_update_icons.dm

Fixes PDAs and such not being dropped when being stripped of your jumpsuit.
Fixes #23244
Nobody except IPCs for some reason should get a free PDA slot that's unstrippable.
Stripped someone of their jumpsuit, PDA dropped.
:cl:
fix: Fixed PDAs not dropping when being stripped
/:cl:

Fixes PDAs not dropping when being stripped

---

code/modules/hydroponics/plant_genes.dm

Resolves #23155
All potato batteries now have a minimum max charge of 1.
It's a simple solution to potato batteries being able to runtime when having 0 max charge.
Varedited a potato to have 0 potency, made a battery out of it that had a charge of 1.
:cl:
tweak: Potato batteries now have a minimum max charge of 1
/:cl:

Potato batteries now have a minimum max charge of 1

---

code/datums/mind.dm
code/game/gamemodes/objective.dm

Fixes https://github.com/ParadiseSS13/Paradise/issues/23174#issue-1978366201
the objective properly functions when it's given to player via admin.
spawned two mobs and gave them minds, gave one traitor and a assassinateonce objective, killed the second mob, revived them, added a second assassinate once for comparison and ended the round.
:cl:
fix: Admin given "assassinateonce" works properly now.
/:cl:

fixes admin given assassinateonce objective.

---

code/game/gamemodes/cult/cult_items.dm
code/game/objects/items/devices/flashlight.dm

Fixes item states
No visual bugs
Tested in game
:cl:
fix: Sprite "on" item states on flashlights & cult mirror shield in hands
/:cl:

Fix item state of flashlights & cult mirror shield

---

code/controllers/subsystem/SSghost_spawns.dm
code/modules/research/xenobiology/xenobiology.dm

Added reason text pop-up when you try to give animal sentience. Now ghosts would know you wanna some new friends or do little silly massacre. 
I guess no one want to see x99 attempt to give some bees sentience without any explains. This PR make easier to find friend to chat, or arise sentience army, leting ghost know your intentions without "LOOC: STOP PLEASE A DONT WANNA BE FLYING HORN POTATO". Much easier to invite ghost for gimmicks. via "I want to turn diamond golem into Senator Armstrong for lulz", not just ordinary boring serve.
Activating hidden imba creature..
.. and creature realize: HIS TIME HAS COME!
Launch 2 player local, give dogo potion with pop-up text reason, ghosts see reason why dude wanna arise dogo ultramind.
:cl:
add: Added reason text pop-up for sentience potion …

Reason text for sentience potion

---

code/modules/mob/living/carbon/examine.dm
code/modules/mob/living/carbon/human/human_mob.dm
code/modules/mob/living/silicon/robot/robot_examine.dm
code/modules/mob/living/silicon/silicon_mob.dm

Simple PR, removes the 'is' from the set pose command.
Allows a wider degree of expression with the command, rather than being restricted to whatever grammatically correct statements you can make with 'he/she/it is...'. Baycode has already done this to good effect.
Private server.
:cl:
tweak: the set pose command is better to use now
/:cl:

removes the 'is' from the set-pose command

---

code/__HELPERS/trait_helpers.dm
code/modules/antagonists/vampire/vampire_powers/vampire_powers.dm

This fixes a runtime in `HAS_MIND_TRAITS` by adding a nullcheck, as well as setting the correct argument for checking of mind traits in vampire powers.
Being holy makes you resistant to most vampire powers, currently you are not resistant, and it throws out runtimes a plenty
Tested shadow snare on many chaplains and skrells, as well as a couple of hemo powers have varying degrees of immunity, power depending.
:cl: ppi
fix: Chaplains are once again immune or resistant to some vampire powers.
/:cl:

Fixes a runtime in mind traits and makes IS_HOLY work versus vampires

---

code/game/machinery/cell_charger.dm
code/game/machinery/computer/ai_core.dm
code/game/machinery/computer/buildandrepair.dm
code/game/machinery/doppler_array.dm
code/game/machinery/machinery.dm
code/game/machinery/recharger.dm
code/game/machinery/snow_machine.dm
code/modules/atmospherics/machinery/datum_pipeline.dm
code/modules/atmospherics/machinery/portable/scrubber.dm
code/modules/food_and_drinks/drinks/bottler/bottler.dm
code/modules/food_and_drinks/kitchen_machinery/deep_fryer.dm
code/modules/food_and_drinks/kitchen_machinery/icecream_vat.dm
code/modules/food_and_drinks/kitchen_machinery/kitchen_machine.dm
code/modules/food_and_drinks/kitchen_machinery/smartfridge.dm
code/modules/hydroponics/hydroponics_tray.dm
code/modules/power/generators/thermo_electric_generator.dm
code/modules/reagents/chemistry/machinery/chem_dispenser.dm
code/modules/reagents/chemistry/machinery/chem_master.dm

Updates the machine powernet to the powernet of the area it is in when it is unwrenched/wrenched, meaning that machines that have been moved use the power of the area they are currently in, rather than the powernet of the area they came from.
Note that this means that machines that can be used while unwrenched will still use the powernet of the area they were originally built in until they are wrenched down again. This will still need fixing in the future.
Having machines draw power from an area they aren't even in is weird and potentially exploitable, and having machines randomly stop working because an area on the other side of the station has become unpowered is annoying.
Be in scichem, use the chem dispenser, it works.
Depower scichem, use the chem dispenser, doesn't work.
Move the …

Fixes machine using power from the area it was created in, rather than using the area it is in

---

code/modules/mob/living/simple_animal/hostile/mining/goliath.dm

makes ancient goliaths only make tendrils if they have a target
The timers made from just one of these mobs is like 10% of the timers we make in a round, this is just silly
If nobody is around to see it, we shouldn't be making timers
Killed an ancient goliath
:cl:
tweak: ancient goliaths only make tendrils if they have a target
/:cl:

makes ancient goliaths only make tendrils if they have a target

---

code/game/verbs/suicide.dm
code/modules/mob/living/silicon/robot/drone/maint_drone.dm

Gives drones respawnability, gets removed if the drone gets emmaged
Drones shut off when suiciding
Drones are already an observer like role so I don't really see a reason they shouldn't be able to join as a ghost role if one ends up happening, not like they can share any information on what's going on with them.
Drones now shut off when suiciding, generally more consistent than oxyloss
Suicided as a drone, still thinking if I really need to make an override for some drone dusting stuff
:cl:
tweak: Drones can respawn while in round
/:cl:

Gives drones respawnability, improves killing yourself as a drone

---

code/modules/paperwork/paper_bundle.dm

makes paper stack burning more consistent, uses ishot (any hot object) instead of checking for only lighters
You now always burn the entire stack
also fixes a bunch of runtimes
fixes https://github.com/ParadiseSS13/Paradise/issues/16218
This is just better, more consistent with other stuff and less jank to use
Compiled, ran, burned some books
:cl:
tweak: paper stack burning is more consistent and no longer requires just a lighter
/:cl:

makes paper stack burning more consistent

---

code/datums/ai_laws_datums.dm
code/modules/tgui/modules/law_manager.dm

This adds an argument that defaults to TRUE to override zeroth laws in the lawset `sync` proc. Overall that means loading lawsets remains the same... Unless you're a simple emagged-non-admin borg. Lawsets will load properly, but will ignore the zeroth law.
Admins are also now warned when changing whole lawsets, and get to choose if the silicon's zeroth law is retained, or overwritten.
Lawset boards and AI syncs will still affect the zeroth law as usual.
Fixes #21577
https://github.com/ParadiseSS13/Paradise/assets/80771500/a7e9fde8-1968-4e58-8cf0-221c34d5885d
Spawned a borg, added a zeroth law, emagged it, then de-admin'd self to use the Load Laws option. As an admin, messed with a borg's laws using both options to either leave or load the preset zeroth, if any.
:cl:
fix: Emagged borgs …

Tweaks Load Lawset to differentiate between admins and normal players, admins can choose to not change zeroth laws

---

_maps/map_files/cyberiad/cyberiad.dmm

Fix research delivery windoor on cyberiad, it was rotated in wrong direction
oversight bad.
[i am lazy, look at code]
Rotated, VSC compiled, done.
:cl: Venuska1117
tweak: Rotate Cyberiad research delivery windoor to correct position.
/:cl:

[s] Fix cyberiad research windoor.

---

code/game/objects/items/weapons/defib.dm

fixes some issues with defibs not working with some actions
action buttons should work and bugs are bad
clicked on defib buttons and on the paddles, did you know only the advanced defib can have it's paddles removed by attacking the defib with it?
:cl:
fix: Reverted some accidental regression with defibs
/:cl:

fixes some issues with defibs

---

code/datums/components/defibrillator.dm
code/modules/mob/living/carbon/human/human_defines.dm
code/modules/mob/living/carbon/human/human_mob.dm

Title. If you're giving CPR to someone who gets shocked by a defibrillator, you'll get a pretty nasty zap!
It's a fun little detail and encourages people in medbay to call out "CLEAR!"
https://github.com/ParadiseSS13/Paradise/assets/89928798/6e3220df-232b-447e-abd3-19e07065245f
See video. Shocked someone receiving CPR, watched as they twitched.
:cl:
tweak: Giving CPR to someone who's actively being defibrillated might leave you with a nasty shock! Careful!
/:cl:

Defibs now shock people giving CPR

---

code/game/machinery/doors/airlock.dm

Makes contort body check if the user has not stood up since lying down to crawl underneath an airlock. Also checks if the airlock hasn't been bolted since starting to crawl underneath.
Contort body is only supposed to allow you to crawl underneath airlocks while lying down and while the airlock is unbolted.
Be a skrell changeling, try to crawl underneath an airlock but stand up before crawling under, it fails.
Be a skrell changeling, try to crawl underneath an airlock but bolt it before crawling under, it fails.
:cl:
fix: Fixes changeling with contort body being able to pass airlock while upright
fix: Fixes changeling with contort body being able to pass through an airlock when it is bolted
/:cl:

Fixes changeling with contort body being able to pass airlock while upright

---

code/modules/mod/mod_theme.dm
code/modules/mod/mod_types.dm
code/modules/response_team/ert_outfits.dm

Give all engineer erts double emergency tanks(should last roughly 30-45 minutes if my math is right), gives gamma and red ert bluespace pipe replacers, and gives gamma ert the fire fighter module on their modsuit.
All ert modsuits now have 20 max complexity, mainly for the engineer that was very strapped for space, all ert modsuits also have bluespace cells now.
ERT engineers should be given some better gear since they're for emergencies and all, the bluespace pipe replacer, doesn't requite *too* high/hard to get of levels from rnd to be printed, needing toxins level 6, (the BSRPD doesn't decon into toxins levels), and the storage room on central command has a handful of them laying there.
As for the suit changes, the complexity is mainly due to the fact i wanted to give the engineer …

Engineer ERT buff, and a small gamma ert buff

---

code/game/gamemodes/cult/blood_magic.dm
code/game/gamemodes/wizard/godhand.dm
code/game/objects/items.dm
code/game/objects/items/weapons/holy_weapons.dm
code/game/objects/items/weapons/twohanded.dm
code/modules/antagonists/changeling/powers/mutations.dm
code/modules/antagonists/vampire/vampire_powers/hemomancer_powers.dm
code/modules/mob/living/carbon/examine.dm
code/modules/surgery/organs/augments_arms.dm

Cleaning code, nothing else
removed all 
```
if(!ishuman(loc))
return
```
in procs `customised_abstract_text()` 
It is not needed because this proc is only called when we examine `/mob/living/carbon`, there is no chance it is called in other conditions
moved all 
`var/mob/living/carbon/human/owner = loc` into proc argument
less checks faster game
compiled, run
NPFC

customised_abstract_text - removed useless check, changed var

---

code/game/objects/items/weapons/tanks/watertank.dm

fixes water backpacks not being able to have their miser be toggled by clicking on it while it's on your back
bugs are bad, manually calling ui-interact is stupid
clicked on it
:cl:
fix: fixes water backpacks not being able to have their miser be toggled by clicking on it while it's on your back
/:cl:

fixes water backpacks not being able to have their miser be toggled by clicking on it while it's on your back

---

code/game/objects/items/stacks/sheets/sheet_types.dm
code/modules/client/preference/loadout/loadout_shoes.dm

Title self-explanatory
I see no particular reason not to add all the colors of shoes to the loadout, especially considering our current options are somewhat limited color-wise; let people express themselves better!
Satchels are practically just a reskin of backpacks, so if backpacks can be crafted with cloth, I imagine satchels also should be.
Loaded in with some snazzy sneakers and spawned a bit of cloth to craft meself a satchel
:cl:
add: Colored shoes are now available as Loadout options
add: You can now craft satchels using cloth
/:cl:

Adds colored shoes to loadout, makes satchels craftable

---

code/modules/power/generators/thermo_electric_generator.dm

Fixes https://github.com/ParadiseSS13/Paradise/issues/23311, where the TEG could not be properly anchored or unanchored due to some vestigial logic.
Requiring admin intervention every time a teg is wrenched is less than ideal.
Loaded in, wrenched and unwrenched the TEG.
:cl:
fix: The teg can be properly wrenched and unwrenched again.
/:cl:

Fixes teg anchoring

---

code/modules/mob/living/simple_animal/hostile/headslug.dm
code/modules/surgery/organs/organ.dm

fixes #23316 
Intended behavior is good, runtimes are bad
Egged a skrell and an xeno
:cl:
fix: xenos can be properly headslug'd again
/:cl:

fixes xeno headslugging not working

---

code/controllers/subsystem/SSticker.dm
code/modules/mapping/base_map_datum.dm
code/modules/mapping/cerestation.dm

- Adds `min_players_random` variable (default `0`) to `/datum/map`. Used to filter out potential map picks during random map selection (that is, random map day) if the player count at the time of selection does not exceed it
- Sets the above variable to `60` for CereStation. I picked that number kind of randomly, so I'm open to adjusting it
On random map days, any map can currently be picked which is fine for normal pop. The problem is when CereStation (a large map) is picked during off hours where departments are rarely filled. At the time of writing, I just saw it get picked and the round started with 12 players in-game. That's a ridiculously low number
This doesn't solve the voting issue, but it should alleviate some of the frustration of having to deal with that map with hardly anyone …

Make CereStation eligible for random map selection on 60+ players only

---

code/game/gamemodes/nuclear/nuclearbomb.dm

Makes sure that the user is adjacent to it, because for some reason AI calls attack_hand on nuclear bombs. Its not really that game breaking, just funny.
Fixes an oversight
I could no longer use my remote-AI hands to touch the nuclear bomb
:cl:
fix: AIs can no longer remove the nuclear core from the nuclear bomb
/:cl:

[s] Fixes an issue with nuke cores and AIs 

---

code/_onclick/hud/radial.dm
code/datums/mutable_appearance.dm
code/game/mecha/mecha.dm

Changes mutable_appearance var in mecha.dm and radial.dm to use mutable_appearance() instead of new()
Now UI, hydroponics trays and beakers overlays will break less often
Before (not your build, but your code anyway):
Localhosted the game
:cl: Romains
fix: UI, hydroponics trays and beakers overlays will break less often
/:cl:

Fixes mutable_appearance where it causes UI bugs

---

code/game/objects/items/weapons/holy_weapons.dm

Fixes sord inhand sprite
Fixes: #23371
A weapon so terrible it can't even display its own sprite.
:cl:
fix: Sord has an inhand sprite again.
/:cl:

Fixes sord inhand sprite

---

code/datums/status_effects/buffs.dm
code/game/objects/items/weapons/twohanded.dm

Spellblade now has it's buff last one more second on protection mode and be refreshable. This means the weapon no longer has a period of downside when you are actively attacking someone. This makes it more viable (read: not great) for a wizard  to run spellblade without instant summons or mutate for stun immunity / recovery, which is the point of shielded spellblade (It's still finicky as hell. If balance wants I can make it refresh the status effect on each hit vs every 4 seconds.)
Fixes the shielded spellblade having an alert that shows nothing.
The singularity hammer now does it's vortex in range vs oragne from the person that you hit. This means you are no longer punished for... hitting a person with your melee weapon and it not stunning them. It's not exactly intuitive that every 4 …

makes 2 wizard weapons less of a pain to use.

---

code/modules/arcade/prize_datums.dm

Fixes chat messages meant just for the user going to everyone within view.
Generally makes more sense, not everyone needs to see that you're too arcade poor to afford the water balloon
Fired up the server with 2 clients, made sure only the machine user could see it when the purchase went through and when it didn't
:cl:
fix: Arcade reward machine no longer broadcasts your lack of tickets to the world
/:cl:

Fixes some chat messages with the arcade prize machine

---

code/datums/uplink_items/uplink_general.dm

See title.
feesh. 
Dehydrated carp isn't a very often picked item, and while this probably isn't going to turn it into a must-pick, it will hopefully see some more use. 
Additionally, if you're going for a full carp build you can now buy 25 carp instead of 20. That's five more than twenty.
- Loaded in
- Became tot
- Purchased 25 dried instant carp
:cl:
tweak: Syndiefeesh now cost 4tc
/:cl:

Reduces Dehydrated Carp's price to 4tc

---

code/modules/surgery/organs/organ_external.dm

Checks for an owner before checking droplimb from max damage on limbs since limbs don't droplimb with no owner and it causes null check
bugs bad
Compiled, now has checks protected via the owner check
:cl:
fix: Limbs no longer runtime when taking damage with no owner
/:cl:

No more runtimes when a limb takes damage with no owner

---

code/game/verbs/suicide.dm

admins no longer get a notification when a ghost bar occupant suicides
they don't need this notification
suicided while in the ghost bar
:cl:
tweak: admins no longer get a notification when a ghost bar occupant suicides
/:cl:

admins no longer get a notification when a ghost bar occupant suicides

---

code/modules/projectiles/guns/projectile/revolver.dm

fixes shotguns not being able to be reskined
bug
reskined a double barrel shotgun
:cl:
fix: Shotguns can be reskined again
/:cl:

fixes shotguns not being able to be reskined

---

code/modules/antagonists/changeling/powers/become_headslug.dm
code/modules/mob/living/simple_animal/hostile/headslug.dm

Marginally buffs the health of headslugs, and makes them deal stamina damage on bite.
- 50>60 HP.
- Last resort can now be used when incapacitated or dead.
- 30-35 stamina damage per bite.
Time for incubation has been lowered to 60 seconds for dead bodies, and 120 seconds for living people.
In later stages of incubation, victims will now actually go into crit and start taking heavy stamina damage.
We're gradually moving away from changelings dying and reviving constantly in combat and death warring security, its best we give changelings a more interactive 'out', previous headslug buffs have made them viable but they're still quite squishy and struggle to live past popping out of the vent.
I'm sick and tired of using headslug, I've had to tweak numbers so much.
:cl:
tweak: Buffs headslugs, …

Changeling Headslug Buff + Incubation Changes

---

code/datums/uplink_items/uplink_traitor.dm

Actually removes e20s from surplus crates like intended in https://github.com/ParadiseSS13/Paradise/pull/22772
My reasons have been pointed out in https://github.com/ParadiseSS13/Paradise/pull/22772. This item should not be able to be rolled in surplus crates as per the PR approving them no longer being rolled in surplus crates.
e20 does not roll in surplus crates. How the fuck did I miss this?
:cl:
tweak: E20s can no longer be rolled in surplus crates.
/:cl:

Removes the e20 from surplus crates (for real this time)

---

.github/workflows/ci.yml
code/controllers/configuration/sections/redis_configuration.dm
code/game/world.dm

Disables redis in CI
CI is spuriously failing because of issues with new BYOND and redis. I'll fix it at some point.
NPFC

Temporarily disables redis in CI

---

_maps/map_files/RandomRuins/SpaceRuins/moonoutpost19.dmm
code/game/objects/items/weapons/storage/lockbox.dm

Removes the fluff item from moonbase.
Moves the anomaly core into the safe, as that is more valuable than the research paper.
Paper moved outside the vault.
Added the experimental item lockbox to the safe. This one requires head or sec door access, so an explorer will have to bribe a head or officer to keep the contents.
Note: The ruin has no way to open a safe. You need to bring a stethoscope from somewhere else.
Contents 10% of the time are a facehugger, which will leap out and infect the person without a proper helmet.
This is unlikely to cause a breakout, as the person will need to not be taken to medbay during this time, and not have a mask on. Combined with sec access or head access needed, rare. As you can not look inside, not going to exactly be easy to prepare a monkey as bait …

removes the fluff item from moonbase, modifies loot

---

code/modules/client/preference/character.dm
code/modules/client/preference/preferences.dm
code/modules/mob/living/carbon/human/species/diona_species.dm
code/modules/mob/living/carbon/human/species/drask.dm
code/modules/mob/living/carbon/human/species/grey.dm
code/modules/mob/living/carbon/human/species/human_species.dm
code/modules/mob/living/carbon/human/species/kidan.dm
code/modules/mob/living/carbon/human/species/machine.dm
code/modules/mob/living/carbon/human/species/moth.dm
code/modules/mob/living/carbon/human/species/plasmaman.dm
code/modules/mob/living/carbon/human/species/skrell.dm
code/modules/mob/living/carbon/human/species/slimepeople.dm
code/modules/mob/living/carbon/human/species/tajaran.dm
code/modules/mob/living/carbon/human/species/unathi.dm
code/modules/mob/living/carbon/human/species/vox.dm
code/modules/mob/living/carbon/human/species/vulpkanin.dm

Connects blurbs from species.dm to be read onto the character menu. Allowing for general information about said species.
The biggest issue I've found with paradise is its lack of innovation to teach lore towards new or old players, without the use of third party extensions like the wiki. This allows us to help new players who are making characters easily be given a summary of the species they choose, as well as helping bridge the interest of lore, and game together without disrupting the established order. Species lore is the most important part for alot of people, so it deserves some support.
Works, but WIP
:cl: Octus GDNgit
add: Added species lore blurbs in the character menu
/:cl:

Adds Species Blurbs in the Character Preference Menu

---

code/modules/client/preference/loadout/loadout_general.dm
code/modules/client/preference/loadout/loadout_glasses.dm

Makes goggles not take up multiple loadout points like some other items already do https://github.com/ParadiseSS13/Paradise/pull/13827.
Moves goggles and Classic SecHUD to glasses section of loadout.
it had been requested as a feature 
fixes https://github.com/ParadiseSS13/Paradise/issues/23201?
Opened game, picked all goggles, join as Captain.
Only one loadout slot was taken, I spawned with only one goggles.
Questioned why roundstart HUDs weren't merged and why this is the first instance of roundstart HUDs.
:cl:
tweak: Made job specific goggles not take up extra loadout points.
tweak: Moves goggles and classic SecHUD to glasses tab.
/:cl:

Makes goggles no longer take up multiple loadout points

---

code/datums/uplink_items/uplink_traitor.dm

Removes Syndicate Super Surplus (200 TC) from the uplink. This does **NOT** remove the normal 100 TC surplus. 
Just gonna repost what I said in discord, to here, quote
"Mega surplus is a pretty obvious choice with zero risk aside from the gambling part. 
People will blurt out code words and do surplus because it always results in something either party can use, or an extremely broken combo that has been gained by breaking the job restrictions. 
Given that 95% of the time antags don't actually backstab each other when doing it means there isn't any sort of risk, so it's not something that is ever taken into account when making the choice.
The main issue is it complete breaks the TC economy for a round. 100 tc per antag is stable, and there are two exclusions, the first being contractor, …

Removes Syndicate MEGA Surplus Crate

---

code/game/gamemodes/cult/cult_mode.dm

With the addition of #21429, the amount of cultists actually alive matters a lot more. This PR makes it so dead cultists no longer count towards the rise/ascend/fall of cults, and fixes the amount of cultists on the study screen to not include the dead ones.
This PR makes it so that this count is also checked whenever a cultist's stat is changed, this includes both death and revival.
Security can kill all the cult they please, and then not deconvert any of them, so that the 2 remaining cultists will still have their halos. Having the cult count be more accurate is a good thing.
Spawned in a bunch of skrells, made them into cultists, killed em with a pulse rifle and revived them.
:cl:
fix: dead cultists no longer count towards the rise/fall number
fix: cultist's study objectives should now …

Dead cultists no longer count towards the amount of cultists & cult-size is checked on stat change

---

code/modules/mob/living/carbon/alien/alien_base.dm
code/modules/mob/living/carbon/carbon.dm
code/modules/reagents/chemistry/machinery/reagentgrinder.dm

Fixes patches and pills not being grindable
Fixes xenos not being able to have patches and pills forced on them - This takes 5 seconds instead of the 3 for humans
These are things that should absolutely work.
Grinded patches and pills, forced a xeno queen to get patched and eat pills
Didn't get the Perf OD from applying a 30u perf patch
:cl:
fix: Fixed pills and patches not being grindable
fix: Xenos can now be forced patches again
fix: Fixes some issues with reagent amounts
/:cl:

Fixes patches and pills not being grindable, and fixes a runtime with xenos

---

code/game/objects/items/weapons/pneumaticCannon.dm
code/modules/crafting/recipes.dm

This updates pneumaticCannon.dm to more modern standards and buffs the cannon itself to knockdown the user when fired at max power, instead of weakening them.
It makes life easier if we want to add new pneumatic cannon subtypes (foreshadowing) later down the line, and is hopefully much easier to read and understand.
I also imagine the weaken not being changed was an oversight from when crawling was added, though I am fine with removing that part if it's too much of a balance change.
Shot some skrells, learned a bit about how thrown items work, and made sure the tools had their act procs set properly.
:cl:
tweak: Max power pneumatic cannons now knock you down, instead of weakening you.
/:cl:

Pneumatic Cannon Refactor

---

code/modules/surgery/organs/heart.dm

Removes the `emp_act()` override of upgraded cybernetic hearts. Instead of going _necrotic_ on an EMP, being a basically unavoidable death, it now simply stops beating just like the regular cybernetic heart (which still very likely means death).
The upgraded variant already has an additional malus from taking electric shocks, ranging from brute/burn damage, instant Cardiac Failure, to stopping or even rarely necrotizing. Even besides that, the self-restarting quirk of the organ only lets you survive 10% of EMPs, which can simply be chained if something wants to mathematically guarantee your demise. In other words, necrotizing on EMPs as a downside on top of everything else is severely overkill.
The more notable effect of this buff and frankly the ignition point of this change is that …

Tone down upgraded cybernetic heart EMP necrosis

---

code/modules/mob/living/carbon/examine.dm

fixes species hiding when wearing something like a modsuit by passing arguments
Makes a modsuit or hardsuit once again make it harder to see what species you are, especially with similar species like plasmaman, human, kidan, and IPC. A closer glance may be needed to tell based on clothing shape, or may be impossible!
before
after, fixed
see above
:cl:
fix: Fixed species / height / physique not being hidden by clothing like modsuits or space suits
/:cl:

fixes species / physique hiding when wearing something like a modsuit

---

code/modules/tgui/modules/appearance_changer.dm

This adjusts checks on appearance changer options and fixes the CMA admin ability, that was preventing admins from properly changing appearance of players while ghosted.
Fixes an oversight with the original PR that hid appearance options from species that were not applicable. (PR #22359)
Fixes #23409 
Spawned in mobs of varying species.
Used CMA admin to change appearance and species.
Checked for odd behavior and runtime issues. 
NPFC

Adjusts checks on appearance changer, fixes CMA admin

---

code/game/objects/items/weapons/storage/belt.dm

Makes tools fit in all versions of the military belt
Right now, military belts are just plastic bags with the added bonus of getting you arrested by security for c class. This makes them an actual upgrade, and also means that nukies can put the crowbar they start with into their belt.
Put a bunch of tools in a bunch of belts
:cl:
tweak: Military belts can now hold tools
/:cl:

Tools now fit in all versions of the military belt

---

code/game/objects/items/weapons/garrote.dm
code/modules/mob/living/carbon/human/species/_species.dm
code/modules/mob/living/living.dm
code/modules/mob/mob_movement.dm

Improvised Garrote is no longer unescapable.
Instead, it stuns for 1 second, then constantly grants them 3 seconds of immobilization. As such, their method of escape must be slaming them into something via disarm, batoning them, shooting them, ETC, but not just holding move or space.
You can no longer resist grabs when immobilized.
Grabs can no longer be dropped by disarm, so it isn't 2 disarms by people being grabbed to break it. Enviroment will matter. Disarming the person being grabbed still breaks it.
**Fiber wire is unchanged**
Improvised Garrote can not be escaped right now. Considering it is an instant craftable hard stun, this is not great.
This means that while still very good, and still *hard to escape from*, it is not impossible unless you do not have the weapons to fight back, …

Improvised Garrote nerf, tweaks to grab resisting.

---

_maps/map_files/RandomRuins/SpaceRuins/moonoutpost19.dmm
code/game/area/areas/ruins/space_areas.dm

fixes moon base 19 powering all other ruins, makes it it's own ruin area
Ruin being it's own area is good.
god this place is power hungry, 30 sheets doesn't last long, hope you brought plasma or better stock parts
see above
:cl:
fix: Fixed moonbase 19 using the base unpowered area, now uses it's own area.
/:cl:

fixes moon base 19 powering all other ruins, makes it it's own ruin area

---

code/datums/uplink_items/uplink_general.dm
code/game/objects/items/weapons/storage/uplink_kits.dm

Reverts
- https://github.com/ParadiseSS13/Paradise/pull/21300
Removes the two free spare mags from the Stechkin. Back to its old one gun, on clip purchase. Spoken with another member in the balance team.
Gonna be honest, I don't understand why the Stechkin needed 16 extra shots of magazines despite its previous position before the buff being in a well established place. The points I read were, it was outclassed, needed more chances to reload, and promote its viability. But all of these were never issues to begin with.
The Stechkin is a 20 TC weapon (out of 100), for that price you get a pretty strong firearm that deals 30 brute damage on unarmored targets, and can be silenced, concealed easily, and use specialized ammo. I don't understand how it feels outclassed to other weapons when the …

Reverts Stechkin Buff, No Extra Mags

---

.github/workflows/ci.yml

More CI fix testing, after a short period of it working it broke again due to package conflicts. This tests a fix by stripping back the required packages to what TG's rust-g repo recommends.
``` 
The following packages have unmet dependencies:
binutils : Conflicts: binutils:i386 but 2.38-4ubuntu2.4 is to be installed
binutils:i386 : Conflicts: binutils but 2.38-4ubuntu2.3 is to be installed
binutils-common : Breaks: binutils-common:i386 (!= 2.38-4ubuntu2.3) but 2.38-4ubuntu2.4 is to be installed
binutils-common:i386 : Breaks: binutils-common (!= 2.38-4ubuntu2.4) but 2.38-4ubuntu2.3 is to be installed
libbinutils : Breaks: libbinutils:i386 (!= 2.38-4ubuntu2.3) but 2.38-4ubuntu2.4 is to be installed
libbinutils:i386 : Breaks: libbinutils (!= 2.38-4ubuntu2.4) but 2.38-4ubuntu2.3 is to be …
```

Test further CI fixes

---

code/__HELPERS/unsorted.dm
code/game/machinery/computer/HolodeckControl.dm

- Replaces the janky "spawn in nullspace then directly overwrite `loc`" solution in `/area/proc/copy_contents_to()` with a parameter the proc already had, `atom/newloc`. This means the loc is set earlier in the duplication code, and lets `.update_icon()` run on an actual turf rather than nullspace.
For tables specifically, this means they won't be invisible in the holodeck anymore, as they can finally smooth properly.
- Removes the explicit `perfect_copy = FALSE` argument pass in holodeck code, which means the copied stools and chairs will inherit the facing direction properly.
- Cleans up a bunch of obvious shitcode throughout the code file. Didn't touch the more complicated parts as I was less sure it'd break something.
Invisible objects bad, chairs facing the correct way good
:cl:
fix: …

Fix holodeck tables being invisible and chairs facing the wrong way

---

code/datums/uplink_items/uplink_general.dm
code/game/machinery/deployable.dm
code/game/machinery/portable_turret.dm

adds a new tot item, the syndicate pop-up turret. 20 TC
has 50 HP, shoots anyone who didn't deploy it, bullets deal 20 damage
deployed using a grenade similar to the barrier grenade
Gives tots some minor area control for a low TC value. let's them turn 1 on 1s into 2 on 1s, pretty good for getting some backup in the middle of like, a long objective such as vault docs.
Skrells got shot but I didn't. Weird we don't have a simpler path for this but man I'm not doing a map edit
:cl:
add: Added a new 20 tc tot item, the syndicate pop up turret
/:cl:

adds a new tot item, the syndicate pop-up turret

---

code/modules/mob/language.dm

If a cyborg gets a message from the AI they're linked to in binary comms, the text will be larger. 
Sometimes messages get lost in chat, which is a problem for AIs who rely on being able to communicate with their linked borgs. This change makes it harder for an important message to slip by.
Made sure binary comms formatting wasn't messed up for ghosts, drones, or other AIs
:cl:
tweak: AI messages in binary comms will be display in a larger font to their linked cyborgs.
/:cl:

AIs a cyborg is linked to will have larger text in binary comms

---

code/modules/antagonists/changeling/powers/apex_predator.dm

Fix error in code. Replaces `menu_location` to `category` for changeling ability. Also, rename some 1 char vars
The game will compile, it's good.
All in code
Compiled
Not player facing (actually is, but not really)

fix: replace `menu_location` with `category` in `/datum/action/changeling/apex_predator`. Rename 1 char vars

---

code/modules/mob/living/living.dm

fixes resist not unbuckling by returning false instead of true, turns out the proc is called in an if statement
Resist should unbuckle you.
Confirmed  grab resisting worked as expected, confirm could unbuckle via resist
:cl:
fix: Fixes resist not unbuckling
/:cl:

fixes resist not unbuckling

---

code/datums/spells/lichdom.dm

- Fixes most cases where wizard rounds wouldn't end when lich can no longer revive
- Fixes lich action button not updating after making phylactery
- Refactors lich code for readability
Rounds sometimes do not end when a lich is properly eliminated which turns the round into extended but with magic ™️ . No one wants this so now wizard rounds actually end when the lich dies and cannot revive due to destruction of body or phylactery, or if the lich and phylactery are in different z-levels at time of death
Tested cases with qdeling self or phylactery, moving self or phylactery to another z-level etc
:cl:
fix: Fixed some cases where destroying a lich's body or phylactery would not end a wizard round
/:cl:

Fixes Lichdom preventing proper wizard round end

---

code/game/turfs/simulated/floor/plating.dm

In this PR - https://github.com/ParadiseSS13/Paradise/pull/21437
For some unknown reason, there was a reset of the saved icon at the pryed floor, this PR fixes that.
Pryed floor does not lose icon_state
https://github.com/ParadiseSS13/Paradise/assets/69762909/4e58f563-78a5-4985-8a7e-4f46734ca038
Above
:cl:
fix: Pryed floor no longer lose paint
/:cl:

Fix: Missing icon_state after removing the floor

---

code/game/objects/effects/decals/cleanable.dm

It now removes the jani HUD when the cleanable is destroyed.
It lags the server if not GC properly.
- Spawned a cleanbot over a dirty maints and observed for any issues
:cl:
fix: Cleanable decals no longer lags the servers when destroyed
/:cl:

Fixes cleanables not garbage collecting properly

---

code/datums/datacore.dm

For custom work, we remember the last position so that we know where to display the role in the manifest.
This is only used in manifest_modify and in the role manager console.
This will help against custom roles issued by HOP. Now if you want to write "Temporary Deputy Captain", it will appear where it should be.
This problem has been annoying the HOS and everyone who looks at the manifest for several years now, especially with the influx of players and the actively working HOP, who likes to assign interesting roles to assistants.
Screenshot above. It's worked.
:cl:
fix: correct custom rank manifest modify
/:cl:

FIX: correct custom rank manifest modify

---

code/__DEFINES/preferences_defines.dm
code/modules/client/preference/link_processing.dm
code/modules/client/preference/preferences.dm
code/modules/client/preference/preferences_toggles.dm
code/modules/tgui/modules/tgui_input_list.dm

Allows you to switch off TGUI Input Lists if you don't like them for any reason
The setting is available both in Game Preferences (Input Lists) and in the Preferences tab (Toggle TGUI Input Lists)
Choice is always a good thing
https://github.com/ParadiseSS13/Paradise/assets/69762909/5f9c2489-bc42-4a94-9184-9c0b884f5dc0
Yep
:cl:
tweak: You can turn-off TGUI Input Lists if you don't like it, in Game Preferences (Input Lists) and in the Preferences tab (Toggle TGUI Input Lists)
/:cl:

TGUI Input List Toggle

---

code/modules/antagonists/_common/antag_datum.dm

Owner is not mandatory in `/datum/antagonist`, but when it's destroyed - `owner` is not properly checked for nullability, where it is required
Less runtimes - better.
Nothing to show.
Compiled, added antag datums and removed antag datums.

fix: remove `owner` requiring dependencies from `/datum/antagonist` only if `owner` is present

---

code/modules/mob/living/carbon/human/human_defense.dm

Fixes an argument mismatch in arguments called here
```
Runtime in code/modules/food_and_drinks/food/foods/meat.dm,328: type mismatch: cannot compare Seth Knapp (/mob/living/carbon/human) to 1
proc name: water act (/obj/item/reagent_containers/food/snacks/monkeycube/water_act)
src: the wolpin cube (/obj/item/reagent_containers/food/snacks/monkeycube/wolpincube)
src.loc: HUMAN (/mob/living/carbon/human)
call stack:
the wolpin cube (/obj/item/reagent_containers/food/snacks/monkeycube/wolpincube): water_act
HUMAN (/mob/living/carbon/human): water_act
the shower (/obj/machinery/shower): wash
the shower (/obj/machinery/shower): Crossed
```
Runtime bad
Compiles
:cl:
fix: Things on your body will now be properly affected by water when walking under a shower
/:cl:

Fixes a runtime with human's water_act

---

code/game/objects/effects/decals/cleanable.dm

Having two cleanables be spawned on the same tile would make them runtime, since the extra cleanable gets merged, the /Destroy() (that has remove_from_hud) is called without going through prepare_huds(), making it have no janihud to be removed.
Runtimes are bad
- Did face bubblegum and realized i am not robust enough for that.
- Went to the station and spawned two cleanables on the same tile, it didnt runtime on merge.
:cl:
fix: A runtime related to janihud has been fixed
/:cl:

Another jani HUD runtime fix

---

code/modules/clothing/clothing.dm
code/modules/clothing/shoes/magboots.dm
code/modules/mob/living/carbon/human/human_movement.dm

Moves the `mob_has_gravity` check to check for the magpulse trait instead of checking if the shoes have the noslip flag.
This doesn't have any mechanical implementations.
It cleans up the code and removes a proc that does nothing for 99% of all items.
Compiled, and chameleon shoes didn't protect me against the gravity being down.
NPFC

Refactors `mob_has_gravity` to use `TRAIT_MAGPULSE` instead of a noslip flag

---

code/controllers/configuration/sections/general_configuration.dm
code/modules/mob/new_player/new_player.dm
config/example/config.toml

This extends the #23009 PR to allow people observing the game within 5 minutes of roundstart (not just before the game has actually started) to antaghud without losing respawnability. 
Sometimes players leave their computers between rounds, and when they come back the round has already started. If they want to observe in this case, I think they should have a chance to have the same benefits as of just before the round.
Observed 2 minutes after the game started, was a roundstart observer
set the config to 0 minutes
observed 2 minutes after the game started, was not a roundstart observer
restarted, observed before the game started, was a roundstart observer
:cl:
tweak: Observing before 5 minutes into a round, lets you toggle AntagHUD without losing respawnability.
/:cl:

Observer antaghud use is extended to 5 minutes after roundstart

---

code/datums/mind.dm
code/game/gamemodes/objective.dm

Updates mind.dm and objective.dm to move redundant explanation text off of mind.dm and consolidates into a new proc called update_explanation_text in objectives to handle the explanation text instead of find_target and add_objective preforming those functions. doesn't affect custom objectives.
Capture and download have not existed for a very long time so removed their options from add/edit_objective
Fixes: https://github.com/ParadiseSS13/Paradise/issues/23207
Fixes: https://github.com/ParadiseSS13/Paradise/issues/23525
Outside of find target, objective logic shouldn't be replicated in mind.
spawned in multiple test subjects, commited some unethical mind control and gave them all jobs and assigned the objectives to one traitor.

Cleans up and update of mind and objective.

---

code/__HELPERS/name_helpers.dm
code/game/machinery/teleporter.dm
code/game/objects/items/flag.dm
code/modules/food_and_drinks/food/foods/baked_goods.dm
code/modules/mob/language.dm
code/modules/mob/living/simple_animal/hostile/retaliate/clown.dm
code/modules/projectiles/guns/energy/special_eguns.dm
strings/ion_laws.json

Removes most references to clown planet within the code and rewrites the accompanying text to accomodate this.
Ruins are unaffected currently but will be purged properly in the future.
By order of the Lore Team, this content has been marked for immediate destruction. 
Clown planet is an ancient meme that has no reason for existing beyond lolrandom funni clown world. The world will be better off for its passing.
- Loaded in
- Spawned items
- Descriptions are updated
:cl:
del: Removed clown planet references
tweak: Rewrote several item and mob descriptions
/:cl:

Purges most clown planet references

---

code/modules/mob/living/living.dm

Adds a dialog for trying to say your last words when you succumb from crit. 
Also allows you to succumb when you're below -100 HP, which might not have actually been possible before?
If you're in losebreath, this won't do much for you, so I'm hoping that https://github.com/ParadiseSS13/Paradise/pull/23425 goes in before this one.
It adds a bit of fun flavor to death, and lets you choose how you'd like to go out. You can summon just enough energy to break out of unconsciousness for one last phrase...and then you're done.
https://github.com/ParadiseSS13/Paradise/assets/89928798/18c8631d-88ae-477a-9922-f41b231d4be8
Punched myself to death, then tried the succumb verb.
:cl:
add: You can now utter some last words when you succumb to death from crit.
/:cl:

"You'll find all my treasure in one place..." -- Adds optional last words whispered when succumbing

---

code/modules/arcade/prize_datums.dm

Lowers the cost of the bike from the arcade to 7000 tickets, making it actually possible to get within a round. Cost is still up for negotiation, of course.
After a few arcade tweaks it's now incredibly difficult to get the bike; say the average arcade go-er gets 60 tickets a minute on average while trying to go fast, it would take them 167 minutes (2h 47min) to get the bike. Considering that rounds never take this long, lowering it to 7000 will make it a tad more achievable. It would now take said player around 117 minutes (just under 2 hours), which while still very difficult isn't impossible.
Opened the game, checked the price was lower.
:cl:
tweak: Changed the price of the bike in the arcade to 7000 tickets.
/:cl:

Lowers cost of the bike from the arcade.

---

code/modules/antagonists/changeling/changeling_power.dm

Ensure that changeling internals are retained after transformation to prevent them from being disabled, Therefore Fixes #23432 
Bug fixes are always good
Spawned as an human took the DNA of a random skrell and transformed into them with my tank on, they stayed on.
:cl:
fix: Fixes issue with changeling internals not persisting after transformation
/:cl:

Fix issue with changeling internals not persisting after transformation

---

code/modules/reagents/reagent_containers/patch.dm
code/modules/reagents/reagent_containers/pill.dm

Fixes pills and patches displaying their nonexistent transfer rate in examine text;
Also cleans up a couple redundant, same-as-parent property reassignments from pills.
Oversights bad, pills/patches shouldn't have a visible transfer rate
Made some pills and patches, examined them
:cl:
spellcheck: Fixed pills/patches advertising a nonexistent transfer rate in their examine text
/:cl:

Fixes pills and patches displaying a fake transfer rate

---

code/modules/mob/living/living_defense.dm
code/modules/mod/modules/modules_antag.dm

Mobs now put out ATOM_BULLET_ACT
Stealth module now goes on cooldown when deactivated by being hit.
Stealth module now responds to bullet act due to above fix.
Stealth module cooldown increased to 10 seconds.
Signals working is good.
Stealth module deactivating when being shot is good.
Stealth module going on cooldown is good.
A longer cooldown makes getting hit more meaningful.
Shot shit, got hit, cooldown activated, as did stealth going away.
:cl:
fix: Stealth module deactivates when being shot now.
tweak: Stealth module goes on cooldown when  being deactivated forcefully.
tweak: Stealth module cooldown is now 10 seconds.
/:cl:

Fixes human bullet act, fixes cooldown of stealth module, ups it

---

_maps/map_files/RandomRuins/LavaRuins/lavaland_surface_watcher_grave.dmm

Fixes a map failure with the new watcher ruin and lava
CI needs to pass
CI works
NPFC

Fixes a map failure with the new watcher ruin and lava

---

code/modules/client/preference/link_processing.dm

Removes the ability to directly assign `null` to a character's language and/or species.
`[2023-12-17T22:44:15] MySqlError { ERROR 1048 (23000): Column 'language' cannot be null } | Query used: UPDATE characters`
Null safeties need to actually work properly please.
:cl:
fix: Fixed a bug allowing you to null your character's language and species.
/:cl:

Fix null character languages due to an oversight

---

code/game/machinery/snow_machine.dm

Fixes #23620 : snowmachine were let loose even if you tried to anchor them, while they can only be turned on when wrenched in the floor.
Bug fix gud
Spawned as the CE, wrenched the snow machines. Turned the machine on. Steve got snow, Steve is happy.
:cl:
fix: Snow machines are no longer anchored and then set loose - allowing the player to use them
/:cl:

Fix snow machines

---

code/modules/antagonists/changeling/powers/mutations.dm

reworks the changeling shield
No longer has it's uses scale with the amount of DNA you have, has 6 uses in total. You always would have 5 DNA so it just didn't matter
Auto parries instead of requiring you to parry. 
No longer drains charges if the parry fails
This ability sucks is much worse than a riot shield. With these changes it has the use of being focused on blocking stray shots for a more mobile playstyle.
I am very sad I can't make this disarm someone if they do it in melee
Shot at myself from a shuttle wall
:cl:
tweak: Changeling shield has been reworked. Autoparries and has less total charges
/:cl:

reworks the changeling shield

---

code/game/objects/items/robot/robot_upgrades.dm

Fixes an issue
The thingy turned off
NPFC

[s] Nothing happened here

---

code/modules/paperwork/pen.dm
code/modules/projectiles/projectile/bullets.dm
code/modules/reagents/reagent_containers/hypospray.dm

Fixes an oversight in hyposprays/darts/sleepy pens where if you'd inject a mix of reagents containing `????`, it'd stop doing the reaction after encountering it in the list.
It should do all reactions except the `????` reaction.
Compiled
Injected skrell with mixed, saw that it all reacted properly.
:cl:
fix: Fixed a rare bug that could occur when injecting chemical mixes with `????`
/:cl:

Fixes a small oversight if you inject `????` with other reagents in a hypospray or other devices

---

code/modules/response_team/ert.dm

Kidan, drask, and greys can be ERT now
Slime not included at this time due to bones, vox / plasmaman due to internals. May work on that in a diffrent PR down the line.
More random eye colour options for the game to pick from for ERT
Karma is dead, let us have a bit more variety in ERT. None of these species are balance breaking, so should be fine!
queued for ert, chose drask
queued for ert, chose kidan
queued for ert, chose grey
:cl:
tweak: Kidan, drask, and greys can be ERT now
/:cl:

Kidan, drask, and greys can be ERT now

---

code/modules/supply/supply_packs/pack_miscellaneous.dm

Add the janicart (and its key) as a misc supply.
Sometimes the HoP hires multiple janitors - and only one of us can get the janicart, it fix this situation and allow multiple player to have the janicart...in exchange for the hefty sum of 500 credits each, which i think is only fair.
Just compiled and ran the game to be sure that i could actually purcharse it. 
:cl:
add: Janicart and Janikey added as purchasable miscellanous supply.
/:cl:

Added the Janicart to the available list of supply pack

---

code/game/gamemodes/objective.dm
code/game/gamemodes/objective_holder.dm
code/modules/antagonists/traitor/datum_mindslave.dm

* Fixes GC issues with `datum/objective_holder` Which was causing mindslaves and thralls to fail GC and have their owners to have a null entry in their `mind.antag_datums` list.
This was leading to runtimes in the orbit menu:
```dm
[2023-12-09T05:04:10] Runtime in code/modules/mob/dead/observer/orbit.dm,102: Cannot read null.name
proc name: ui static data (/datum/orbit_menu/ui_static_data)
usr: Kar-Ski (ckey) (/mob/dead/observer)
usr.loc: The catwalk (107,144,2) (/turf/simulated/floor/catwalk)
src: /datum/orbit_menu (/datum/orbit_menu)
call stack:
/datum/orbit_menu (/datum/orbit_menu): ui_static_data
/datum/tgui (/datum/tgui): open
/datum/orbit_menu (/datum/orbit_menu): ui_interact
Kar-Ski (/mob/dead/observer): Orbit
Orbit (/obj/screen/ghost/orbit): Click
```
* Also fixes a runtime where …

Runtime and GC fixes related to orbit UI bluescreens

---

code/game/gamemodes/miniantags/guardian/types/ranged.dm

Ranged guardian snares are now not visable on alt / right click
invisible things that say "You shouldn't be seeing this!" should be invisible.
:cl:
fix: Fixed guardian snare trap being visable
/:cl:

fixes a 6 year old ranged guardian bug

---

code/game/objects/items/devices/radio/beacon.dm

Fixes a small whoopsie oversight in tot bundle code that allowed the input to stay valid for too long
You only get one.
Made myself a tot, logged into the uplink, bought a bundle, used it in hand several times.
:cl:
fix: Syndicate Bundle beacon's UI no longer allows you to get multiple bundles.
/:cl:

[s] Fix a Syndicate Bundle oversight

---

code/game/objects/structures/crates_lockers/closets.dm
code/game/objects/structures/morgue.dm

Player-controlled simplemobs (and xenos) can now open lockers and morgue trays. They need to be human size or bigger to do this, and will still slash at lockers/morgues if they're on harm intent or if the locker is locked/welded.
Note that this does not change behavior for non-intelligent simplemobs - they'll still chew away at lockers as before.
You also need to be human sized or bigger to open stuff - no mice slamming lockers closed.
Interacting with lockers has always been really awkward as an intelligent simplemob. Lockers being something humans can pass trough and flick closed with ease whilst the xeno (with perfectly functional hand-like appendages) right behind them needs to spend 5 seconds slashing at it in order to get it open is a bit silly.
Also fixes annoying scenarios like …

Player-controlled simplemobs can now open lockers and morgue trays

---

code/controllers/subsystem/SSticker.dm
code/defines/procs/announcer_datum.dm

Makes it so anyone can post news stories in Public Station Announcements channel using newscaster, Before only admins could use it.
Adds new Station Announcements Log channel that tried to implement how old Public Station Announcements worked, it silently publishes every announcement as a news story.
I was told that Public Station Announcements was used to save command announcements in news form, but it was at some point broken or removed.
It is currently only usable by admins, and admins do not use it because they can make Central Command announcements.
I think having an auto-generated channel news channel may encourage crew to share one of their small stories without any complications of making another news channel.
I have been requested to re-add old feature of having announcements …

Re-adds newscaster announcement logging + Makes Public Station Announcements news channel Public

---

code/modules/mob/new_player/new_player.dm

Make everyone random now works without randomizing the players *currently saved character in preferences that will fuck them if they save it*
the button being usable is good
fix #20168
confirmed it scrambled, and that the save was not changed
:cl:
fix: make everyone random will no longer fuck up peoples saved characters so it can be used.
/:cl:

makes make everyone random not the worst button of all time

---

code/game/mecha/mecha.dm

It prevent the player from putting two trackers (ai beacon+ the standard one) within a mech.
It return the old tracker on the player hand when you put a new one in the mech.
Before it was possible to put both an ai beacon and a tracker one within a mech, making the same mech appear twice in the robotic control console.
This isn't the end of the world type of "issues" as i was even unable to find any players reporting it on the github, but it's good to have it fixed.
There was also another (rare) issue that came with it:
From my own experiences, since it was also impossible to remove an ai beacon when it was put on a mech by a mistake, the RD usually order the mech to be destroyed to not tempt luck in the worst case scenario of a malf AI.
I made a mech and the trackers spawns to test it …

Fix duplicate tracking beacon issue

---

code/modules/clothing/suits/armor_suits.dm

Ensure that Reactive Repulse Armor does not affect spectators by adding a check for ghost entities during repulsion action. 
Fixes #23574
Bug fix is good
Got the reactive armor on in a NPC, ghosted, spawned some megacarp and wasn't pushed away
:cl:
fix: Fix reactive repulse armor no longer affecting ghosts
/:cl:

Fix Reactive Repulse Armor no longer yetting spectators

---

code/datums/weather/weather_types/ash_storm.dm
code/modules/mob/living/simple_animal/posessed_object.dm
code/modules/mob/living/simple_animal/shade.dm

Fixes #23110 by adding immunity to ash storm for both possessed objects (admin ghost controlled object) and possessed sword (miner loot), addressing the oversight.
Oversight fix gud.
Spawned as a possessed sword during an ashtorm took no damages.
:cl:
tweak: Add immunity to ash storm for possessed objects
/:cl:

Add immunity to ash storm for possessed objects and swords

---

code/game/objects/items/robot/robot_parts.dm

Makes it harder to assemble borgs on the fly by plopping down a finished borg shell with an active brain. An arguably rare occurrence, but even still. Main point of this is it makes no sense for an endoskeleton as big as a person to be able to fit into your backpack. 
It just doesn't make sense to me and does fix an, albeit rare, balance concern I have about being able to carry completed borg shells and plop down armies/multiple borgs on the fly for crew and antag alike.
1. Spawned endoskeleton.
2. Attempted to bag it.
3. Could not bag it.
:cl:
tweak: Endoskeletons are bulky and no longer fit in backpacks.
/:cl:

Makes Endoskeleton Bulky

---

code/datums/spells/summonitem.dm

Instant summons no longer works on the NAD, and gives a message.
Instant summons will eject nad from contents when summoning something with the NAD inside it
Similar to implantation, certain NAD related things should be disabled, under the fact that "maybe this isn't fun for nukies when abused"
Instant summons plus NAD is a recipe for nukies having a horrible time, especially if used right. Let us give them some mercy.
Attempted to bind spell to NAD, failed.
:cl:
tweak: Instant summons no longer works on the NAD.
tweak: Instant summons will eject the nad from contents when recalling something.
/:cl:

Instant summons no longer works on the NAD.

---

code/modules/supply/supply_packs/pack_miscellaneous.dm

Adds two new soap crates:
Assorted Soap Crate: 3 regular soap, one NT soap. 250 credits
Suspicious Soap Crate: 2 Syndiesoaps. Requires emagged supply console. 250 credits.
Soap is surprisingly difficult to get. You either grab the few in the station's bathrooms, are lucky enough to get one from the janitor, or you bribe mining.
With the mixed reactions to the semi-recent space cleaner nerf, I figured it should be a bit easier for people to help clean the station, without needing to buy an entire crate of janitorial equipment. 
- Loaded in
- Bought soap
- Soap was delivered
- Hacked supply console
- Bought sus soap
- Soap was delivered
:cl:
add: Added two new soap crates
/:cl:

Adds Two Soap Crates

---

code/modules/reagents/chemistry/recipes/slime_extracts.dm

Xenobio can no longer make watcher eggs, the ones that give you the orbiter
Supposed to only be one of these, don't need a bunch of scientists getting 3 of these  each orbiting them shooting at every terror / xenomorph
it was in the list
:cl:
tweak: Xenobio can no longer make baby watcher eggs
/:cl:

Xenobio can no longer make baby watcher eggs

---

code/game/machinery/computer/cloning.dm

Added a check for non-clonable species DNA (body) before checking for brain existence to prevent cloning of non-clonable species. Hence Fixes #22675
Another player ploy to get free KFV while harvesting innocents Vox and you thought I would not patch it? Foolish thought surely...
Also oversight fix gud
Spawned as a doc, tried to clone a vox with human brain (forgive me), couldn't.
:cl:
fix: Non-clonable species can no longer be cloned
/:cl:

Non-clonable species can no longer be cloned

---

code/game/machinery/Sleeper.dm

This PR removes "crisis" var from sleeper code and removes health checks for chemicals so you can inject any available chemicals on any health if person is not dead.
Removes variable related to it and actual emergency_chems list
This part of sleeper logic was incomprehensible and not needed at all. Sometimes when you use sleeper its buttons becomes grey and you cant inject any chemicals but one(ephedrine or epinephrine). Even with syndicate sleeper. You wonder why? Because it had list of "emergency" chemicals and if occupant's health becomes less than -25(upgradable), sleeper wont allow you to inject "non emergency" chemicals. Without saying it. There is a message in code but with current TGUI it will never be displayed.
So lets say you have a person with 130 toxin damage, you will be …

Removing sleepers chemicals type limit on injured occupants

---

code/modules/mob/living/simple_animal/hostile/megafauna/ancient_robot.dm

blocks vetus' charge and potential teleport if someone changes zlvls
best to not let this happen (again)
:cl:
fix: bluespace vetus can no longer rarely teleport on station when a miner jaunts
/:cl:

bluespace vetus can no longer rarely teleport on station when a miner jaunts

---

code/modules/clothing/suits/job_suits.dm

Adds allowed items to HoP coat - Currently uses the same list as the HoS mantle (HoP mantle inherits this, so it's consistent with other HoP items)
Drip should not come at the cost of specific item storage
It works :)
:cl:
tweak: The HoP coat can now hold items such as batons and guns
/:cl:

Adds allowed items to HoP coat

---

code/modules/reagents/chemistry/reagents/drinks_reagents.dm
code/modules/reagents/chemistry/reagents/food_reagents.dm

Removes the negative effects of Vulp chocolate digestion.
If you need to add a niche weakness that pretty much is never recognized to balance things out, then it probably isn't worth making said consequence to begin with. Also we should avoid making our species be animals on legs, and more alien in nature, bit on the nose to have something like this. Lastly, this is technically a buff, so yeah, Vulp buff hooray woohoo.
editors note: I forgot Taj existed, this affects them, same argument applies lmao
compiles
:cl: Octus
tweak: Removed Vulp weakness to chocolate
/:cl:

Removes Vulp/Taj Chocolate Debuff

---

code/game/gamemodes/objective.dm

Fixes an issue with the destroy ai objective not updating + adds a stack_trace for when a update_explanation_text is called without being overwritten.
Bad code is bad
code compiles
:cl:
fix: Destroy AI objective will no longer appear as "Nothing."
/:cl:

Fixes an issue with the destroy ai objective not updating + adds a stack_trace

---

code/_onclick/ai_onclick.dm
code/game/gamemodes/miniantags/pulsedemon/pulsedemon_interactions.dm

Makes pulse demons return true on instant bolting / shocking
Runtimes bad, pulse should be able to bolt / shock instantly when in an apc they control
bolted / shocked / opened door as pulse
:cl:
fix: pulse demons can now ai click doors without runtiming
/:cl:

pulse demons can now ai click doors without runtiming

---

code/modules/mob/living/silicon/robot/robot_mob.dm
code/modules/mob/living/silicon/silicon_mob.dm
code/modules/mob/living/simple_animal/bot/bot.dm
code/modules/mob/mob_misc_procs.dm

Silicon mind names are now updated properly when they rename themselves. Also refactors some ugly code.
Its weird that it shows your default name when you spawn in as AI, even though you changed your name. This fixes it so its not the default name forever.
Blew myself up as AI, kept my chosen name as a ghost. Did surgery to turn myself into an AI part of the way through the round, still kept my old AI name.
:cl:
tweak: Deadchat names should be more accurate for roundstart AIs and cyborgs
/:cl:

Silicon mind names are now updated properly

---

code/modules/mob/living/living.dm

Adds another intent check to movement//
If you move someone you are pulling with a mouse click in front of you, then he pushes you and can help you move faster. This PR fix it. Now the person will not push you. If you both have help intents, you will switch places as you are now.
fixed this:
https://github.com/ParadiseSS13/Paradise/assets/120549107/0f6451b5-ac04-4ac6-8165-37b938f774ab
Moving in this way makes you move faster is bad.
Start local server, all working.
:cl:
fix: you can no longer push the person who pulls you when he moves you with a click.
/:cl:

Prevents pushing from the person you are pulling

---

code/modules/mob/living/carbon/human/human_inventory.dm

Add modsuit storage keybinding (through shift+b) to works.
Updated the quick_equip_item method to handle MODsuits and allow items to be inserted into MODsuit storage using key bindings. Therefore Fixes #23152.
Oversight fix gud 
Spawned with a modsuit with storage item, could put item on item with shift+b. Joy.
:cl:
add:  Allow MODsuit storage Bag (ShiftB) keybinding
/:cl:

Allow MODsuit storage Bag (ShiftB) keybinding

---

code/datums/diseases/transformation.dm

Fixes #23616 : Oversight where cyborgs created with Roborgers/Nanomachines were not prompted to change their name.
**If** it is an oversight then it is good to have it fixed.
Spawned as an assistant got some tasty hamborger, was proposed to change my name.
:cl:
tweak: Add a prompt for cyborg created with Roborgers/Nanomachines
/:cl:

Add a prompt for cyborg created with Roborgers/Nanomachines

---

code/modules/mob/living/silicon/robot/robot_laws.dm

Fix https://github.com/ParadiseSS13/Paradise/issues/23581 and fix https://github.com/ParadiseSS13/Paradise/issues/17855
Turns out lawset code doesnt like to_chat inserted into the procs I had em in. Removing the to_chat fixes the issue. I've also removed the syndie_override calls as they are not actually needed, the proc is already called on installing the syndicate MMI.
Bugs bad
Tested syndi MMI with two accounts, checking that everything still works fine, without message spam
Tested purging the syndi MMI cyborg's laws, working as expected (All laws purged besides zeroth law)
:cl:
fix: Fixed syndicate MMI spamming the subverted cyborg with messages when opening law manager
/:cl:

Fix syndicate MMI message spam

---

code/modules/security_levels/security_level_datums.dm

Changes the gamma alert announcement from 
`Central Command has ordered the Gamma security level on the station. Security is to have weapons equipped at all times, and all civilians are to immediately seek their nearest head for transportation to a secure location.`
to
`Central Command has ordered the Gamma security level on the station. Security is to have weapons equipped at all times, and all civilians are to immediately seek out command staff for instructions.`
About half the time, the instructions it gives to civilians are contrary to what command would want them to do (nukies/blob). Nobody follows it anyways during these cases, but it would be nice for the announcement to line up with reality to avoid confusion for newer players.
Since this also involves slight SOP changes, I also …

Changes the gamma alert announcement wording

---

code/modules/reagents/chemistry/reagents/misc_reagents.dm
code/modules/reagents/chemistry/reagents_holder.dm

Fixes IPC not losing component "squeak", waddling and comic sans trait when drinking jestosterone
Fixes runtime error when applying jestosterone to mob without a player
Right now IPC receives all effects from on_new() proc of reagent disregarding ability to metabolize it. Fixes this bug.
Locally
:cl:
fix: Fixes IPC not losing squeakyness, waddling and comic sans trait when drinking jestosterone
/:cl:

Fixes IPC drinking jestosterone

---

_maps/map_files/Delta/delta.dmm

Fix mapping errors and add a monkey box to CMO office.
Fix ares: Wires missing in psych office, added a monkey cube box to CMO office, deletes a flying cam and a status display in surgery storage, deletes a firealarm in a window in surgery observation
Because 2 cams and a flying display status is not cool. And CMO needs a monkey box. Adds a missing wire to psych office as well.
Local Host
:cl:
fix: Fixed missing cable in pych office and flying status display board and cam.
add: added monkey cube box in CMO office.
/:cl:

Delta - Fix some issues in Medbay Delta

---

code/__DEFINES/atmospherics_defines.dm
code/modules/mob/living/autohiss.dm
code/modules/mob/living/carbon/human/human_life.dm
code/modules/mob/living/carbon/human/species/_species.dm

Makes it so Humans will more easily go towards their desired bodytemperature. This'll make humans have an average temperature of 33 degrees, instead of 20.
Body heat creation and  cooling down is bufffed between +-50 degrees of your desired body temperature.
This makes Drask live at ~3 degrees C.
Gives the game a touch of realism, making everyone live at seemingly normal (albeit still low) temperatures.
Ran around as a naked human, was nice and cozy at ~33 degrees
Ran around as a naked Drask, was nice and cozy at ~3 degrees
I went out to space as both, it took only about one extra cycle to reach space temperatures with this change.
:cl:
tweak: Humanoids will now live at a bodytemperature closer to their ideal bodytemperature
/:cl:

Nudges bodytemperature to your desired temperature

---

code/modules/antagonists/changeling/powers/mutations.dm

Chitinous armor headgear cover both mouth and eyes. Therefore protect from pepper spray. Fixes #23500
Misdesign requested fix gud.
Spawned as a ling, pepper spray did nothing.
:cl:
tweak: Chitinous armor headgear cover both mouth and eyes
/:cl:

Chitinous armor headgear cover both mouth and eyes

---

code/modules/hydroponics/grown/olive.dm

Makes Olives no longer mutate into anything, especially apples. My fault for copy pasting code and not noticing at all. Fixes #23665 
Olives shouldn't magically break biological and botanical barriers.
1. Olive no mutate.
:cl:
fix: Olives no longer mutate into apples.
/:cl:

Removes Apple mutation from Olives

---

_maps/map_files/shuttles/admin_armory.dmm

removes a sneaky space tile under an armory shuttle window that spaces it
I like my shuttle being non spaced.
Loaded it through shuttle console.
Wasn't spaced
:cl:
fix: Admin shuttle no longer spaces itself.
/:cl:

fixes armory shuttle spacing itself every time we send it

---

code/game/mecha/equipment/tools/other_tools.dm

Part of topic https://discord.com/channels/145533722026967040/1188998198635806750/1188998198635806750
Buffs resource generators by a factor of 5, and tesla generator by a factor of three. This will allow generators to compete with the slime battery and say "I'm not taking up a slot in the mech for nothing!". Consumption, as well as generation of energy is increased by 5 times, without changing the coefficient of total energy, only speeds up the "metabolism".
The Tesla generator, on the other hand, has a different problem. It is so weak that it does not even cover the cost of walking. Increasing the delta by three times will increase the load on the APC, but will at least allow you to walk without discharging the battery. Regen will still be critically lacking for high-end weapons like …

BALANCE: Buff generator for mecha

---

code/modules/antagonists/traitor/contractor/items/contractor_kit.dm

**Chameleon kit changes**:
The chameleon suit has long not been enough to hide your disguise as a contractor, which is why they will get a suit and helmet to change their disguise while on the run.
Removes: 
**Energy dagger:** Contractors are not supposed to have lethal gear as their package. You can buy it from the uplink instead.
**X4 charges:** This is a highly lethal weapon that can gib people outside of the door. Potentially round-ending the person on the other side. Not to mention that the noise is heard throughout the entire station. The direct opposite of a stealth weapon.
**Binary translator key:** Useless AI comms that do nothing for the contractor. It's generally only used to add laws and talk with the AI privately.
Adds: 
**A box of 5 C4 charges:** Swapped with the X4 charges, …

Contractor item changes

---

code/_onclick/hud/action_button.dm

Adds altclick proc to click proc for hide_toggle action button. This returns the ability to reset the positions of the action buttons that you moved.
This matches the description of the hide button, I think it was deleted by accident.
Started local server, moved action buttons, alt-click on the hide button, all buttons reset positions
:cl:
fix: you can alt-click on the hide button again to reset buttons positions
/:cl:

you can reset actions button's positions again

---

code/modules/surgery/organs/organ_external.dm

Checks for owner before checking if the owner has a trait
runtimes bad
dropped an ipc in a chasm and it did not runtime.
:cl:
fix: fixes external limbs runtiming when no owner at times
/:cl:

fixes external limbs runtiming when no owner at times

---

code/modules/crafting/recipes.dm
code/modules/projectiles/ammunition/ammo_casings.dm
code/modules/projectiles/ammunition/magazines.dm
code/modules/projectiles/projectile/bullets.dm

Purges improvised shotgun ammo and overloaded improvised shotgun ammo. The improvised shotgun remains.
We moved past buckshot long ago for a reason. It's time to kill off improvised shotgun, which was nearly as strong point blank or a few tiles away. Lasershot gets to stay as it's damage is burn, and 20 less than buckshot. While not the most effective on armored targets, it's high base damage still made it pack a punch, especially vs terrors.
Improvised overloaded has been removed,  due to it being easier (arguably) to make than frag 12, and more destructive. Yes, it can back fire, but more often than not, the person you are trying to kill will go down with you. A lot of people would trade a kill on a vampire / nuclear operative / agent with their own life, and this ammo made it a bit too …

Purges improvised and overloaded improvised shotgun ammo

---

code/modules/ruins/ghost_bar.dm

Make it so the character selector on ghost bar use index and you know which character slot you are picking.
Meaning, no more bug with same character names.
Gotta follow ACID properties and make sure unique ID (and not names) are used as identifiers.
Therefore Fixes #23608
Bug fix gud
Spawned in ghost bar with two different characters having the same name, had no issues.
:cl:
fix: Fix ghost bar character selection - using ID now
/:cl:

Fix ghost bar character selector breaking when multiple characters share the same name

---

code/game/gamemodes/objective.dm

Steal object special kits are now given to random objective owner (multiple owners possible when objective is assigned to team). 
Previously the SAME item was given to each one in team, which effectively resulted in item being given to the last owner.
More predictable special equipment giving strategy.
All in code.
Spawned, given objective.
:cl:
tweak: Steal object special kits are now given to random objective owner. Previously the SAME item was given to each one in team, which effectively resulted in item being given to the last owner.
/:cl:

tweak: randomly choose special kit receiver

---

code/game/objects/items/devices/taperecorder.dm

Recorders no longer say `"Skipping X seconds of silence."` when playing them back.
Recorders already come with built-in time stamps for when something was said, having it announce that it `Skipped 2 seconds of silence` mostly clutters up chat with information you can already see right next to messages.
It makes people not want to use payback feature because printing transcript is usually easier.
Said stuff to recorder with different delays in-between, played recordings back.
:cl:
tweak: Universal Recorder no longer announces the fact it skipped silence.
/:cl:

Recorder no longer says "Skipping Silence"

---

code/modules/atmospherics/machinery/components/binary_devices/passive_gate.dm

Adds functionality to quickly turn off and on passive gates, which seems to be forgotten in the original PR
Makes them easier to use
Could ctr+click to turn on passive gates, didn't get any messages about the gate being pulled
:cl:
tweak: You can now ctr+click passive gates to turn them on or off
/:cl:

You can now ctr+click to turn on/off passive gates

---

code/modules/power/lights.dm

Allows players to use Spraycans to color lights, similar to the functionality of the Floor Lights.
Allows for nice, pretty colored lighting without the ugly as sin Light Floor sprites. Adds further functionality to Spray Cans that aren't just lol graffiti or antag item
Built, no errors. Loaded up in game. Took Spray can. Hit light tube. Changed color. Worked. Removed Light Tube. Put it back. Color came back. Good! Activated Fire Alarms, lights turned red, turned them off, lights went back to the colored states. Great. Tested crayon, didn't work, that is good.
:cl:
add: Added Light Coloring! Spray a light tube with a spraycan to use it!
/:cl:

Adds Light Tube Coloring - Colored Lighting! No more light floors needed!

---

code/modules/projectiles/guns/projectile/shotgun.dm

**Please merge this PR, after or with** https://github.com/ParadiseSS13/Paradise/pull/23739
Read title
Combat shotty is pretty mid currently due to its weight being very limiting in storage. So this slaps it down a size to make it more viable against other security weapons in terms of choices.
yep, looks bulky to me
:cl: Octus
tweak: Combat shotty is now bulky instead of huge
/:cl:

Makes the Combat Shotgun Bulky instead of Huge

---

code/modules/research/designs/equipment_designs.dm

This PR removes several NVG's from the RnD console. The normal NVG and NVG Mesons are still available. Removed NVG's can still be spawned via admin. These include;
- NVG Sec Hud
- NVG Med Hud
- NVG Jani Hud
- NVG Sci Hud
- NVG Diagnostic Hud
- NVG Hydroponics Hud
So big issue with night vision is the powercreep state its in. There are several variants of NVG Huds that have made the item bloated as a blob, and its made the glasses a somewhat no brainer for all players to grab. With an NVG variant in almost all departments, its common to see people grabbing them to replace previous eyewear. Resulting in a majority of the station wearing NVG's because sci hands them out with no issue.
This also leads to another issue, and that is *fog of war*. Essentially, darkness is a common veil of …

RnD Nerf, Purges most NVG variants from the lathe

---

code/game/objects/items/devices/flashlight.dm

Gives flares the same attack sound and attack verbs as lighters.
Currently flares use the generic hit sound and generic "attacked" verb in it's attack message. Flares only do damage when they're turned on and do burn damage, so it would make sense for them to use the same sound and verbs as lighters.
Hit things with flares.
:cl:
tweak: Flares now use the same attack sound and attack verbs as lighters
/:cl:

Gives flares the same attack sound and attack verbs as lighters.

---

code/game/objects/items/weapons/kitchen.dm
code/modules/mining/ores_coins.dm

Fixes ghetto surgery tools for the first step of IPC surgeries not being able to actually initiate the surgery
On other species you can initiate surgeries with ghetto tools used in the first step of those surgeries, so consistency in that is good and plus IC wise it doesnt make sense to be able to physically make the first step of a surgery but not being able to think about starting the surgery, initiating a surgery being hovering a scalpel over the limb and such
Initiated a surgery on a IPC with a knife and a coin and then completed the surgery to make sure everything worked (the knife and coin being ghetto surgery tools for the first step of IPC surgeries)
:cl:
fix: Fixed not being able to start IPC surgeries with ghetto surgery tools
/:cl:

Fixes IPC ghetto surgery tools not being able to actually initiate the surgery

---

code/modules/ruins/ghost_bar.dm

#23610 became actually broken during discussion, what made it impossible to spawn with saved character due to null value. This PR fixes this. Fixes #23848
Players can spawn at ghost bar with their characters now.
Works fine now.
:cl: Maxiemar
fix: Fixed spawn at ghost bar
/:cl:

Fix spawn at ghost bar

---

code/modules/mob/living/carbon/human/human_update_status.dm
code/modules/surgery/organs/organ_helpers.dm

Currently, if an IPC dies from a damaged microbattery and they attempt to re-enter their corpse they'll pop right back up until the heart takes damage again and realizes it's not supposed to work. This fixes that by adding a proc for checking if all vital organs are working.
People should die when they are killed
Starved to death then tried to re-enter corpse, also made sure the check for brain damage didn't break either
:cl:
fix: IPCs that die from a damaged battery have to get it repaired before living
/:cl:

[s] The PR I just made about fixing an IPC revival exploit but this time I'm on the right branch

---

code/modules/surgery/organs/organ_external.dm

Fixes IPCS taking much more (60 from light, 99 from heavy) damage from emp when intended.
Brings them back to 40 and 65 as before
resolve #23862 
When https://github.com/ParadiseSS13/Paradise/pull/23178 was merged, it turns out that the limb damage mod (rather than the species damage mod) affected emp damage.
So when we removed the limb resist and extra damage from species, ipcs were taking extra damage from emp.
This brings them back to 40 and 65 as before
Light and heavy emp'd machines to confirm intended values.
:cl:
fix: IPCs once again get 65 damage from a heavy EMP, and 40 from a light.
/:cl:

IPCs once again get 65 damage from a heavy EMP, and 40 from a light.

---

code/__DEFINES/access_defines.dm
code/game/area/shuttle_areas.dm
code/game/jobs/access.dm
code/game/objects/items/weapons/cards_ids.dm

This PR removes an unused ID card type, the "salvage captain". This was nominally meant to be used for some kind of ship that could access other space ruins: https://github.com/ParadiseSS13/Paradise/commit/544c39f7c2aeab497eaae61032cdf80c15b92e2e but I can't find any use of it in any map throughout git history. It also removes the unused `/area/shuttle/salvage/...` subtypes. While these have the same name as existing ruins, they are _not_ the areas for those ruins. Those are `/area/ruin/...`.
Dead code bad.
NPFC

Remove unused 'salvage captain' ID and related areas

---

code/game/objects/items/weapons/storage/boxes.dm

Fixes the metal foam box sprite being invisible because of an incorrect naming.
Fixes https://github.com/ParadiseSS13/Paradise/issues/23789
- Spawned and used my eyes to see if it was no longer invisible
:cl:
fix: Metal foam box sprite is no longer invisible
/:cl:

Fixes the metal foam box sprite being invisible

---

code/modules/projectiles/projectile/magic_projectiles.dm

Makes the staff of animation properly set the factions of the created mimics
Fixes #23654
A wizard should not be eaten by the cheese he raiseth himselve
See above
:cl:
fix: Fixes the staff of animation not working correctly
/:cl:

Fixes the staff of animation not working properly

---

html/create_object.html

This PR adds a handler to the Admin spawn windows to allow for doubleclicking on the desired items to spawn them. It works as expected for multiple selections as well.
I've lost years of my life moving my mouse cursor to the Spawn button.
https://github.com/ParadiseSS13/Paradise/assets/59303604/5e370541-c16f-4508-ab5f-eff0edf3f9d4
See above. Since the create object page is reused for all types, this works for e.g. the Spawn Mob page as well.
NPFC

allow quick spawn with doubleclick

---

code/game/data_huds.dm

The janihud highlight low image alpha combined with the slime jelly, that too has a small alpha value, resulted in not so visible sprites.
This PR fixes this by making it reset the image alpha and its color too to prevent cleanables from changing its colors.
Fixes https://github.com/ParadiseSS13/Paradise/issues/23892
- Made both human and slime people to bleed
- Noticed that the slime jelly highlight has the same alpha as common blood
:cl:
fix: Janihud highlight is now more visible on certain kinds of bloods
/:cl:

Fixes janihud highlight not being very visible sometimes

---

code/modules/power/engines/supermatter/supermatter.dm

Up to this point, it was possible for more than one S-class anomaly to appear in SM crystal. This PR makes SM behavior match the original idea of S-class uniqueness.
There is no mismatch with the documentation now.
Works fine now.
:cl: Maxiemar
fix: Fixed multiple s-class SM anomalies appearing per round.
/:cl:

Fix multiple S-class SM anomalies appearing per round

---

code/datums/station_traits/neutral_traits.dm

See title.
Also edits the tranquilite crate trait to make it lore-compliant.
Lore team already agreed Clown Planet was to be deleted, so here we are again.
N/A, just text changes
:cl:
tweak: Edited trait descriptions for Bananium and Tranquilite crate station traits.
/:cl:

Purges clown planet references from station traits

---

code/datums/weather/weather_types/radiation_storm.dm

This PR adds the syndie depot interior to areas excluded from radstorms. Fixes #23895.
All other space ruins are protected from radstorms, this one should be too.
Spawned in, caused radstorm, checked inside and outside of depot.
:cl:
fix: The interior of the Syndicate depot is now protected from radstorms.
/:cl:

protect syndie depot interior from radstorms

---

code/game/gamemodes/miniantags/revenant/revenant.dm
code/game/objects/items/weapons/dice.dm
code/modules/admin/topic.dm
code/modules/admin/verbs/deathsquad.dm
code/modules/admin/verbs/gimmick_team.dm
code/modules/admin/verbs/one_click_antag.dm
code/modules/events/spider_terror.dm
code/modules/mob/mob_misc_procs.dm
code/modules/response_team/ert.dm

Reverts ParadiseSS13/Paradise#23847
This has likely broken ghost polling for most roles that you can be banned from, such as ERT and antags.
Fixing these issues requires a larger refactor than is currently ready.

Revert "[FIX] Jobbaned Roles at poll_candidates"

---

code/modules/mining/machine_redemption.dm
code/modules/mob/living/simple_animal/hostile/mining/hivelord.dm

- Fixes dupe of hivelord cores with lazarus injector
- Fixes dupe of resources with ore redemption
_I take fixes from here:_
https://github.com/ss220-space/Paradise/pull/2482
https://github.com/ss220-space/Paradise/pull/3796
No exploits
:cl:
fix: Fix dupe of resources with ore redemption & hivelord core with lazarus
/:cl:

[S] Fix hivelord core exploits & dupe with ore redemption

---

code/modules/power/lights.dm

Fixes people being able to create lights with negative light
Ideally the station shouldn't be this fucking dark
Sprayed the lights on the arrival shuttle
:cl:
fix: Fixed being able to give lights no luminosity 
/:cl:

Fixes reverse lighting

---

code/game/machinery/lightswitch.dm

This PR fixes emissive underlays for light switches. Also increases the light power amount to make them stand out a bit more.
These should have been showing up, more glowing things are better.
Spawned in, toggled light switch, turned off power at APC to make sure it didn't show up with no power.
:cl:
fix: Light switches now properly glow.
/:cl:

fix lightswitch emissives

---

code/game/gamemodes/cult/cult_mode.dm

This fixes weird behaviour with getting spells as roundstart cultist aswell as getting double cult talk and cult objective check
fixes https://github.com/ParadiseSS13/Paradise/issues/23750
bugs bad
compiled, culted
:cl:
fix: Roundstart cultists no longer have weird spell behaviour and double cult actions
/:cl:

Roundstart cultists spells fix

---

code/__DEFINES/language_defines.dm

This PR removes several unused `#defines` used in earlier versions of language code.
Deadcode bad.
Searched the codebase, prayed for successful CI.
NPFC

remove unused language defines

---

_maps/map_files/generic/Lavaland.dmm

Change necropolis walls back to be undestructable.
Fix issue where legion would break its own walls.
Run VSC, no errors occured.
:cl:
fix: changed destructable necropolis wall, back to undestructable.
/:cl:

Fix lavaland necropolis walls.

---

code/game/objects/items/weapons/storage/surgical_tray.dm

Surgical tray no longer fits in bags
oversight / unintended behaviour
Surgical tray can hold all the medical tools, so it being inside a bag is carrying an entire surgery room with you without using your backpack space
:cl:
tweak: surgical tray no longer fits in bags
/:cl:

Surgical tray and bags

---

code/game/machinery/requests_console.dm
code/modules/research/message_server.dm

- Added a sender(instead of leaving it blank) to the radio notification for a new message
- Changed the radio notification for a new message to better align with above changes
- Merges the code for sending messages to requests consoles present in messaging server into request consoles' `createMessage` proc
- Added a reminder for unread messages which triggers every 5 minutes
- Changes request consoles so that they no longer process messages(unless forced) when they are inoperable. Affected machinery include but are not limited to, ore redemption machines, mail crate shuttles, and MULE bots
Note: I am aware that ORMs send messages which may not necessarily be considered important enough to have a reminder. I've decided to keep that out for now and fix it in a separate PR because adding a …

Request Console Unread Messages Reminder

---

code/controllers/subsystem/SSthrowing.dm
code/game/atoms_movable.dm
code/modules/mob/living/living.dm
code/modules/mob/mob_movement.dm
code/modules/mod/modules/modules_engineering.dm

This PR blocks moving if you're currently being thrown. 
If you're being thrown, being able to stop throw by any movement button is... weird. 
Xeno hunter stopping jump in the middle of leap? Shadow demon being able to not move after using grapple hand on non living target? Gargantua failing charge spell because you pressed W in fight? not like this. 
Being thrown is not easy and being able to just press button to make it much lesser than it supposed to be  or to completely kill spell based on throwing is weird.
Compiled, tested various throwing
:cl:
tweak: You cant move while being thrown
/:cl:

Thrown mobs cant move until the throw ends

---

_maps/map_files/MetaStation/MetaStation.dmm

Fixes the access to the windoor so no Assistants don't got access to the checkpoint, 
fixes #22434
People shouldn't be able to easily break into sec like this
https://github.com/ParadiseSS13/Paradise/assets/98861947/94d5198c-9155-44c6-9fe4-bf93550663f9
I spawned myself as a Assistant and checked if you they access and they don't, But security officers do
:cl:
fix: Fixed the door access in arrivals sec checkpoint on NSS Cerebron
/:cl:

Fix Windoor at NSS Cerebron Arrivals Security Checkpoint public access

---

_maps/map_files/MetaStation/MetaStation.dmm

Title.
Also shocks the two inner windows.
Prisoners could just walk off freely, granted into space, but im 99% sure this was a oversight. 
Checked if the stuff existed. yea
:cl:
tweak: Execution room on METASTATION is grilled again, and makes the two windows in execution shocked.
/:cl:

Adds grills back to the execution chamber on meta. 

---

_maps/map_files/Delta/delta.dmm

Fixed the departures airlock access and moved a few things around
Fixes #22861 
Makes the paramedic have faster response in Departures In case someone dies in spess
Before
After
Spawned as a paramedic and tested that I got access and I did
:cl:
Add: added a airlock helper for the airlock
Tweak: made the room a bit bigger
/:cl:

Fixed the paramedic not having access on NSS Kerberos Departures cycled airlock

---

code/datums/uplink_items/uplink_traitor.dm
code/modules/pda/messenger_plugins.dm

Removes the random chance that a PDA bomb will backfire on you.
The original idea I assume is to make it slightly harder to bomb the heads of staff, but considering that you pay **30 TC** for the cartridge (On par with a MODsuit, the contortionist jumpsuit and pickpocket gloves for example), it doesn't seem like something you'd restrict, especially as it removes your PDA and uplink, costing you up to 100 TC in total.
It compiled, I'm in the process of blowing many skrell up
:cl:
tweak: The PDA bomb cartridge can now no longer backfire
/:cl:

Removes the random chance that a detomatix cartridge will backfire

---

_maps/map_files/RandomRuins/SpaceRuins/ussp.dmm

pretty much what the title says
Makes it easy to access instead of being one way of accessing in and out
spawned as a USSP and checked if the airlocks worked
:cl:
Add: added airlock helpers since it was needed on USSP
/:cl:

Adds airlock helpers to USSP station

---

code/game/machinery/computer/card.dm

Demotion/Termination - with the exception of a command role - will clear their job slot.
Hence Fixes #22731.
Bug fix gud
Tested both demotion and termination on detective and command members. Worked as excepted.
Even upon entering cryo no new job slot was created.
:cl:
tweak: Demotion/Termination - with the exception of a command role - will clear their job slot.
/:cl:

Terminating/Demoting IDs now clear jobs slots

---

code/controllers/subsystem/SSair.dm
code/controllers/subsystem/non_firing/SSmapping.dm
code/datums/datacore.dm
code/game/dna/dna2.dm
code/game/jobs/job_exp.dm
code/game/objects/items/devices/painter/floor_painter.dm
code/modules/client/preference/character.dm
code/modules/mob/living/carbon/human/appearance.dm
code/modules/mob/living/carbon/human/human_mob.dm

Optimises some init things, specifically:
- Makes SSair sleep between initialising atmos machines (splits 300ms over multiple ticks)
- Makes ruin spawning check tick (each zlevel takes 330ms to add, and cant be slept, but for multiple Zs we can sleep between)
- Optimises creating DNA strings (moves it to a list that joins instead of += on a string 52 times for SE, and 48 for UI)
- Makes mobs not update icons constantly on ticker init (saves a ton of icon blend calls)
- Makes datacore use the existing ID photo if possible instead of regenerating each time (saves 50ms **per player**)
Also optimises some runtime things:
- EXP verb
- The floor painter UI
Performance good
Spawned in - my character was still correct
add: Added performance
/:cl:

[TM prolly] Some init optimisationss

---

code/game/objects/structures.dm
code/game/objects/structures/railings.dm

Checked if it worked
:cl:
fix: Fixed railings mentioning tables in the tip of click-dragging
/:cl:

Fixes railings mentioning tables on inspect.

---

code/__DEFINES/dcs/signals.dm
code/modules/mob/living/carbon/carbon_life.dm
code/modules/mob/living/carbon/carbon_status_procs.dm
code/modules/mob/living/carbon/carbon_update_status.dm
code/modules/mob/living/damage_procs.dm
code/modules/mob/living/living_defines.dm
code/modules/surgery/organs/augments_internal.dm

The CNS rebooter no longer runs a life based reduction of stamina every 2 seconds.
Instead, when a person enters stamina crit with the CNS rebooter, it will lower their stamina regen time to 4 seconds. 
This does **not** impact stamina regeneration out of stamina crit. If you take 90 stamina damage, you will take 10 seconds to regenerate your stamina.
EMPing the implant stuns as before. However, it will be disabled for 30 seconds or a minute, depending on EMP severity.
Current CNS rebooter is... niche. It can save your ass. It will take 3 batons to down you, over 2. If you eat a bunch of buckshot rapidly, it can recover a bunch of stamina.
If you are disabled however, it probably won't help you much.
The issue is the implant checks every 2 seconds off life. As such, depending on on when …

Reboots the CNS implant

---

code/game/gamemodes/cult/blood_magic.dm

This PR adds charges meter similar to other spells to cult spells
Being able to see your spell charges instead of looking into chat or counting how many times you used your shadow shackles is good
Compiled, used various cult spells
:cl:
add: Cult spells with charges will now show their charges on their action panel
/:cl:

Cult spells shows charges now

---

code/__DEFINES/preferences_defines.dm
code/modules/client/preference/preferences.dm
html/browser/common.css

Antag preferences now in separate tab
The Yes/No button is also painted
There are only getting more customisations, so I thought it would be a good idea to move the antagonists to a separate tab
It's also logical.
https://github.com/ParadiseSS13/Paradise/assets/69762909/be6264b3-f04b-4b07-a728-ff79709a4c7e
Screenshots
:cl:
tweak: Antagonists preferences now at the separate tab
tweak: Be [Special Role] yes/no button now have green/red colors
/:cl:

Separate `Antags` from `Game Settings`

---

code/__DEFINES/combat_defines.dm
code/modules/mob/living/carbon/carbon_life.dm
code/modules/mob/living/carbon/carbon_update_status.dm

This PR adds an in-between phase for species that use oldcrit, where from 0 to -50 HP, they'll be in a forced knockdown state instead of immediately going unconscious. This affects IPCs, Abductors, Golems, Skeletons, and Shadows.
Oldcrit has not been touched since crawling was added, and I feel like it is a worthwhile change. The game is much more forgiving than it used to be, so I think this change lines up with these new game design decisions.
The major pushback that I can see is that that this is a major buff to IPCs and abductors. Abductors are currently getting nerfed, but they're still in a very strong position. IPCs are already quite weak, and they cannot repair themselves without nanopaste if they are floored. 
With these numbers, it would take a maximum of 102 seconds to go from …

Species with oldcrit no longer go unconcious at 0 HP

---

_maps/map_files/MetaStation/MetaStation.dmm

Changes an oil and pink slime core out for normal and unusable slime cores.
You shouldn't have an oil slime core in maints roundstart.
Compiled, checked in-game, no more slime cores
:cl:
tweak: Switched out some slime cores in Metastation maintenance
/:cl:

[s] Changes two slime cores out on Metastation

---

code/modules/mod/mod_core.dm

This PR notifies modsuit users with plasma cores when they can't be charged anymore.
Without this, you can just keep clicking the plasma on the modsuit and not get the correct textual feedback.
Wore modsuit, charged with plasma.
:cl:
fix: Modsuits with plasma mod cores now properly notify you when they're fully charged.
/:cl:

fix: stop charging plasma mod core when full

---

code/datums/station_traits/neutral_traits.dm

The typepath of the station trait `Tranquilite Shipment` will be changed because it was the same as that of the `Bananium Shipment`.
Because of this, there was no bananium trait. I don't think it was done on purpose. I would like to become a clown with bananium.
I started local server. Both traits were on the `Modify station traits`
:cl:
fix: Bananium Shipment trait available now
/:cl:

fix Tranquilite Shipment station trait typepath

---

code/modules/research/rdconsole.dm

Optimizes CallMaterialName which is called a lot
BEFORE:
0.00007270315 per call (Roughly 0.21 cycles of overtime when trigger too, that's bad!)
AFTER:
0.00000403225 (No overtime)
18 times more efficient!
lag stupid and bad
I profiled it so that should be enough. Just went in game and after putting mats and chems in the machine I viewed the machine after 
NPFC

fixes extra lag from the RND console

---

tools/UpdatePaths/Scripts/23379_food_containers.txt

This PR adds an extra modifier to the reagent UpdatePaths script to mutate condiment paths separately.
Without this, map-related PRs might break unexpectedly when merging to master.
Checkout out master so I had the migrated paths from #23379, checked out all the maps to the PR immediately before #23379, ran the new UpdatePaths script and compiled.
NPFC

add condiments to reagent updatepaths script

---

code/controllers/subsystem/SStimer.dm

This PR reduces time taken by bucketJoin approximately by 4 times.
Moved name-making of timer into a proc, which can be used on demand by warnings and stack traces. Otherwise, that info is useless except for debugging purposes 
Less lags, i guess
Before: MTPC for bucketJoin without optimization
After: MTPC for bucketJoin with optimization
Did a compile, ran Tracy tests twice to verify that time for bucketJoin has reduced.
No player facing changes aside lag reduction

Optimized SSTimers' bucketJoin to be less laggy

---

code/datums/weather/weather_types/ash_storm.dm

This PR excludes the golem ship from the ash storm weather ambience. `is_shuttle_docked` calls into `SSshuttle.getShuttle` which has a `WARNING` call if the shuttle ID can't be found, but we always spawn ghost roles now, so this shouldn't increase the amount of log spam.
Hearing the ash storm in space isn't correct.
Went into space with golem shuttle, triggered ash storm in Admin secrets.
:cl:
fix: The golem ship will no longer hear ash storms when in space.
/:cl:

fix: golem ship no longer hears ash storm in space

---

code/modules/surgery/organs/brain.dm
code/modules/surgery/organs/subtypes/standard_organs.dm

Fixes #23942. Previously, butchering or gibbing a monkey would yield a head and brain with a random human name, determined from its DNA. This change makes all monkeys drop heads and brains with their displayed name instead - that is, "monkey (488)" will, upon gibbing, yield "monkey (488)'s head".
As noted in #23942, it's confusing and not immersive to see a random human's name labeled on a brain when butchering a monkey.
1. Loaded local copy of the server, joined as Captain.
2. Gave myself a monkey cube, a kitchen sink, and a kitchen knife using the `spawn` verb.
3. Wet the cube
4. Killed and butchered the monkey
5. Observed that among the exploded parts were "monkey (716)'s head" and "monkey (716)'s brain"
6. `spawn`ed a wolpin
7. Killed and butchered the wolpin
8. Observed that among …

Remove names from monkey brains and heads (#23942)

---

code/game/objects/items/robot/robot_upgrades.dm

Makes VTEC give the slowdown more sanely, ensuring that we don't have to hotfix any speed altering modules the day after merge.
It's unmaintainable if we keep having to add more checks for modules here, this does the same speed-up while also doing it sanely.
Gave a mediborg VTEC, checked that it sped up properly
Gave an engiborg VTEC with no module on, it sped up properly
Gave an engiborg VTEC with magboot module on, it sped up properly and didn't give more speedboost after turning it off
NPFC

Makes the VTEC subtract 1 speed instead of setting it to -1 [NPFC]

---

_maps/map_files/RandomRuins/SpaceRuins/wizardcrash.dmm

Walls of the shuttle are insulated against non magical fire, so crew can not welder a wall to pick up the loot avoiding the two monsters inside.
The windows inside the shuttle are now plasma reinforced however, so the crate doesn't instantly break the windows surrounding the singularities, destroying the loot before you pick it up if you don't cheese it.
Slightly more effort for your magic item.
Loot getting destroyed because you didn't cheese it is bad.
went to ruin, tried to weld it, had crate agro me and not instantly smash the windows
:cl:
tweak: Crashed wizard shuttle is no longer weldable.
tweak: Crashed wizard shuttle now has plasma reinforced windows surrounding the singularity.
/:cl:

Wizard crash shuttle walls are now not weldable, crate no longer destroys the loot.

---

code/game/machinery/tcomms/nttc.dm

Removes the double space after comms messages when job announcements are turned on.
Fixes: #23885
It annoys me.
Before:
After:
:cl:
fix: There are no longer two spaces when a comms message is sent with job announcements on.
/:cl:

Removes superfluous spacing from comms messages with job announcements

---

code/modules/atmospherics/machinery/components/unary_devices/cryo.dm

fixes xenos bricking cryopods
fixes #24086
bugfix
put a xeno in a cryopod and dragged them out
:cl:
fix: Xenos no longer render the cryopod unusable when they're removed from it
/:cl:

fixes xenos bricking cryopods

---

_maps/map_files/RandomRuins/SpaceRuins/moonoutpost19.dmm

Swaps the infinite cell for a void core on moonoutpost19
They're functionally the exact same aside from having 20kw more than the infinite cell, its just makes more sense icly for it to be abductor tech rather than 'teehee im infinite' 
compiled, checked if the cell was swapped, yeah
:cl:
tweak: Swapped the infinite cell on moonbase19 to a void core.
/:cl:

Swaps the infinite cell on moonoutpost19 for a void core

---

code/game/gamemodes/malfunction/Malf_Modules.dm

Adds two uses to the Machine Overload Malfunction ability, bringing the total to four, comparable with Machine Override.
Increases the explosion's size to roughly that of several frag grenades duct-taped together.
Apparently, Machine Override also has four uses, thus making it more economical to use despite being objectively better than Overload.
This should make the decision over which ability to use slightly more of a thinker. 
Additionally, the explosion size has been buffed per request from Qwerty.
Became AI, violently exploded R&D, Cargo, Command, and several Vulps.
It works very well.
:cl:
tweak: Increased Machine Overload uses to four. Increases blast size.
/:cl:

Buffs Machine Overload

---

code/modules/projectiles/ammunition/energy_lens.dm

Returns portable emitters (such as those used by malf upgraded/combat upgraded cyborgs) to projectiles. Stationary emitters unaffected, remain hitscan.
Technically a partial revert of https://github.com/ParadiseSS13/Paradise/pull/22754.
I did consult at least one of the balance nerds who approved this PR first.
Hitscan weapons can be very cool - when rare. Death wand? Super limited uses, dramatic effect. Pulse weapons? Admins or DSquad, and both can use the oomph. Stationary Emitters? Very cool, and limited by being difficult to move and set up quickly. Turrets? Again stationary, even moreso than emitters. Cyborgs? Easily mass-produced by a malf AI with a borging factory, as all of them tend to go Engi for the stun arm, and very just generally unfun to fight. I believe these were probably …

Reverts Portable Emitter Hitscan

---

code/game/objects/items/weapons/cards_ids.dm

Fixes being unable to edit the agent ID by using the proper TGUI input panel instead of regular input.
Fixes: #24176
Traitor items should probably work shouldn't they.
Buy an agent ID.
Try to edit it.
Input panel actually opens.
:cl:
fix: Agent ID can now be edited again
/:cl:

Fixes agent ID being uneditable

---

code/_onclick/item_attack.dm
code/game/objects/items.dm

Makes it so `afterattack()` isn't defined twice on `/obj/item`
Luckily we got it right with compile order but this could've broken more
Discovered that taping items to a wall is a thing and checked that it was still a thing
NPFC

Fixes a duplicate definition of a proc

---

code/modules/surgery/organs/heart.dm
code/modules/surgery/organs/organ_internal.dm

You now get an option to bind the cursed heart action to a keybind when you insert it.
Cursed heart now has a 10 second grace period upon being inserted to start pumping
People should be able to easily bind an action button to a keybind if they want to
Pumped my blood in game
:cl:
tweak: You now get an option to bind the cursed heart action to a keybind when you insert it
tweak: Cursed heart now has a 10 second grace period upon being inserted to start pumping
/:cl:

Cursed heart tweaks

---

code/modules/reagents/chemistry/machinery/reagentgrinder.dm

Refactors and cleans up some Reagent Grinder code.
Fixes food with special grinding reagents not transfering other reagents.
Fixes plants halting grinder juicing if they don't have a special juicing reagent.
There's still a minor issue with special grinding/juicing reagents overpowering reagents already present in the ground items, but it's a significantly more complex problem that is probably better left for a future PR.
Disappearing reagents bad.
Injected a branch of wheat with some Unstable Mutagen and ground it to receive Flour + Unstable Mutagen.
Placed a few non-juicables and a tomato to check if the tomato can be juiced successfully ignoring the non-juicables.
Stuffed a grinder full of various grindables to make sure it still stops early if beaker gets filled up during grinding. …

Reagent Grinder refactor'n'fixes

---

tools/ci/check_grep2.py

This PR adds a CI check for toplevel vardecls. This is only the check, it will fail CI until the burndown list is complete.
As GDN said, navigation to types is possible and simple, there's no reason to scatter these around their related functionality.
Ran CI.
NPFC.

add ci check for toplevel vardecls

---

code/modules/events/vent_clog.dm

Scrubber backpressure surge no longer causes gas to spew through welded scrubbers.
Fixes: #23955
It doesn't make much sense for gas to escape via a welded scrubber.
Weld a bunch of scrubbers.
Start the backpressure surge event.
No gas.
:cl:
fix: Scrubber backpressure surge can no longer spew gas through welded scrubbers.
/:cl:

Backpressure surge now checks if a scrubber is welded

---

code/modules/mob/living/silicon/robot/robot_damage.dm

Fixes an issue where a cyborg damage would not update until damage was updated from another source (e.g. repairs or taking damage again)
Fixes: #23600
When you take damage you should take damage, rather than receiving delayed damage out of nowhere later.
Unwrench a high pressure pipe, integrity is immediately updated, rather than being at 100% until it is updated from another source.
Walk into a chasm. I die, instead of being alive at the bottom of the chasm.
:cl:
fix: Cyborgs no longer receive delayed damage when damage goes over a certain threshold.
/:cl:

Cyborg now always updates damage when taking damage

---

code/game/gamemodes/miniantags/pulsedemon/cross_shock_component.dm

Perpetual Pacemaker properly shows source of electrocution rather than /datum/component/cross_shock
Fixes: #23815
My immersion
Expose some wires underneath a Skrell.
Crawl underneath them, shocking them.
I shocked them, not some weird component
Smells like baked fish.
:cl:
fix: Perpetual Pacemaker properly reports source of electrocution
/:cl:

Perpetual Pacemaker properly reports source of electrocution

---

code/modules/detective_work/evidence.dm

Evidence bag now respects nodrop (And any other reason you would not be able to unequip an item)
Fixes: #24147
Ghost items are bad.
Equip some knuckledusters, hold on to them.
Try to put them in an evidence bag, fail.
:cl:
fix: Evidence bag now respects nodrop items.
/:cl:

Evidence bag now respects nodrop

---

code/modules/mining/lavaland/necropolis_chests.dm

Called when someone cryos with the the rod of asclepius activated. Just make sure its not qdel'd before trying.
```
[2024-02-13T04:51:46] Runtime in code/__HELPERS/stacktrace.dm,11: addtimer called with a callback assigned to a qdeleted object. In the future such timers will not be supported and may refuse to run or run with a 0 wait
proc name: stack trace (/proc/stack_trace)
src: null
call stack:
stack trace("addtimer called with a callbac...")
addtimer(/datum/callback (/datum/callback), 0, 0)
the Rod of Asclepius (/obj/item/rod_of_asclepius): addtimer
the Rod of Asclepius (/obj/item/rod_of_asclepius): dropped
...
```
hate runtimes, simple as
It compiled and worked
NPFC

Fixes a runtime with the rod of asclepius

---

code/modules/food_and_drinks/food/snacks.dm

Attacking someone on harm intent with a food item that has a force value attacks with the item rather than force eating. Effectively fixes the combat baguette. 
Fixes #23763 
Separate issue with the throwing croissants, double clicking when throwing causes croissant to damage self on return, moving while boomerang is active makes catching unreliable, might have something to do with walls, throwing to X location from Y position will 100% fail
Combat Baguette should bonk
Spawned in, fed and bonked with baguette, tested other food items still functioned correctly
:cl:
fix: Combat Baguette bonks correctly
/:cl:

Combat Baguette now bonks correctly

---

code/game/objects/items/weapons/storage/bags.dm
code/modules/hydroponics/seeds.dm

This PR lowers plant bag capacity from 100 to 40.
This PR also lowers the upper limit of the amount of plants botany can gain per tray per harvest to make it a little less ridiculous. The upper clamp that handles maximum plant yield has been lowered from 10 to 5, making it so Botany will at most be harvesting plants per yield in the 10s, rather than in the 20s.
The sheer amount of instantdeath plants botany can carry on their person is a little silly at times. Combining this with general plantspam from both war crime instantdeath plants, but also the amount of plants that can be grown, left on the floor to create alt+click piles of instant lag.
Basically, its a bit much and a bit silly. This PR should hopefully make the numbers just that little more reasonable.
Grew a lot of tobacco, just …

Nerfs Botany Maximum Yield + Plant Bags

---

code/game/machinery/requests_console.dm

Fixes runtime introduced by #23897
```
[2024-01-29T01:52:10] Runtime in code/controllers/subsystem/SStimer.dm,701: Tried to delete a null timerid. Use TIMER_STOPPABLE flag
proc name: deltimer (/proc/deltimer)
src: null
call stack:
deltimer(-1)
Cargo Bay Requests Console (/obj/machinery/requests_console): remind_unread_messages
/datum/callback (/datum/callback): InvokeAsync
Timer (/datum/controller/subsystem/timer): fire
Timer (/datum/controller/subsystem/timer): ignite
Master (/datum/controller/master): RunQueue
Master (/datum/controller/master): Loop
Master (/datum/controller/master): StartProcessing
```
Less runtimes
Messaged several departments from Captain's Desk then went to each department to mark messages as read. Monitored the logs to make sure there's no runtimes

Fix runtime

---

code/game/objects/items/devices/taperecorder.dm

Fixes #24216.
Bug bad. Accurately knowing remaining capacity on a recycled tape good.
Became detective, recorded some words, erased the words, saw that the tape correctly had 10 minutes remaining capacity listed.
:cl:
fix: Universal Recorder tapes now show correct remaining time after erasing them.
/:cl:

Tapes correctly display capacity after erasing them.dm

---

code/modules/power/cables/cable_coil.dm

This fixes the weird and *tricky* change in the color of a cable when splitting the stack.
Splitting a cable stack looks good now. Please use crayons to change cable color.
Yes.
:cl: Maxiemar
fix: Fixed changing the color of a cable when splitting the stack.
/:cl:

Don't pick the color of `cable_coil/random` when splitting a stack

---

code/game/machinery/camera/camera.dm

`drop_item()` is a check that is usually followed by `forceMove()` or something else, but it is not about upgrading a camera. This is why we have a stack of plasma being dropped, even if a camera is already upgraded. This PR fixes it.
I change this for a proximity sensor too to keep checks same and clear.
A little more convenient camera upgrading.
Pretty simple, works.
:cl: Maxiemar
fix: Solid plasma no longer falls out of hand when upgrading a camera.
/:cl:

Fix item dropping when upgrading camera

---

code/game/turfs/simulated/floor/light_floor.dm

Prevents floor-lights (like the light tiles) from being toggled in any intent that isn't help.
It's nice to have the option to choose if you want to toggle the lights or not.
Compiled, clicked some lights.
:cl:
tweak: You can now only toggle floor light tiles in help intent.
/:cl:

Makes floorlights only toggleable in help intent

---

code/game/objects/items/mountable_frames/mountables.dm

This PR allows mountable items like light frames, light switches, and APCs to be built on asteroid walls such as the ones on Cerestation.
Cere has a lot of rock walls. It'd be nice to be able to build on them without replacing them with walls.
Spawned on Cere, added a bunch of stuff to the wall.
:cl:
add: Wall-mounted items like light frames can now be installed on asteroid walls.
/:cl:

allow mountable machines on asteroid walls

---

code/__HELPERS/mob_helpers.dm
code/modules/surgery/organs/organ.dm
code/modules/surgery/organs/organ_external.dm
code/modules/surgery/organs/organ_internal.dm

This PR makes all organ damage numbers fixed to 2 symbols after the period
Receiving 0.2359 damage because funny armor blocked some part of it is not really better than receiving just 0.24 damage
0.2359 damage makes all health texts unpredictable while that accuracy is not neccesary
This just makes people's life better, dunno what to say else
Compiled, received some damage, healed
:cl:
tweak: All external and internal organs damage is now limited to 2 symbols after the period
/:cl:

Rounds all organ health damage to the second decimal

---

code/modules/hydroponics/plant_genes.dm

Adds 2u of teslium if you eat and recharge something with a plant that has the electrical activity gene
Currently you can easily just grab 10 of these that you can use as a one click recharge for your guns, this PR punishes you a little bit if you eat only one, and punishes you a lot more if you eat many in a short time period.
Ate a glowcap to recharge my gun, I got unlucky and got shocked
:cl:
tweak: The plant gene "Electrical activity" now gives you teslium when you charge a gun with it
/:cl:

Electrical activity plant gene adds a bit of teslium when you recharge your items

---

code/modules/atmospherics/machinery/atmospherics.dm
code/modules/mob/living/carbon/carbon.dm

Refactors `handle_ventcrawl`
Fixes #24205
You shouldn't be able to climb into vents that are welded shut before you get in it
I tested the refactor by ventcrawling as various mobs, I didnt have the reaction speed to test the bugfix.
The logic however is (in my opinion) sound, a check after the `do_after` if you can crawl into the machine. The fix is on line 505 to 507
:cl:
fix: Fixed ventcrawlers being able to go into welded vents if they were already climbing inside it before the welding was finished
/:cl:

Refactors one ventcrawl proc and fixes a bug

---

code/modules/hallucinations/effects/moderate.dm
code/modules/hallucinations/hallucinations.dm

Adds a check if the target is qdeleted, and uses the `block()` proc over `range()`, as it is faster
Performance + less runtimes is good
Gave myself hallucinations, heard and saw various hallucinations, including but not limited to the gunshot hallucination, which is one of the ones that sometimes runtimed
NPFC

(Hopefully) Fixes the runtime where a hallucination tries to pick from an empty list

---

code/controllers/subsystem/non_firing/SSchangelog.dm
code/datums/outfits/outfit_debug.dm
code/game/gamemodes/malfunction/Malf_Modules.dm
code/game/gamemodes/miniantags/guardian/guardian.dm
code/game/gamemodes/miniantags/guardian/host_actions.dm
code/game/gamemodes/nuclear/nuclear_challenge.dm
code/game/gamemodes/wizard/spellbook.dm
code/game/machinery/computer/atmos_controllers.dm
code/game/machinery/computer/buildandrepair.dm
code/game/objects/items/devices/traitordevices.dm
code/game/objects/structures/crates_lockers/crates.dm
code/game/objects/structures/misc_structures.dm
code/modules/awaymissions/mob_spawn.dm
code/modules/client/preference/link_processing.dm
code/modules/games/cards.dm
code/modules/library/library_equipment.dm
code/modules/mining/lavaland/loot/colossus_loot.dm
code/modules/mob/living/simple_animal/hostile/mining/elites/elite.dm
code/modules/mob/living/simple_animal/hostile/terror_spiders/terror_ghost_interaction.dm
code/modules/pda/PDA.dm
code/modules/research/rdconsole.dm
code/modules/research/xenobiology/xenobiology.dm
code/modules/ruins/ghost_bar.dm
code/modules/ruins/objects_and_mobs/necropolis_gate.dm
code/modules/tgui/modules/ghost_hud_panel.dm
code/modules/tgui/tgui_input/text_input.dm
interface/interface.dm

Fixes #24274 
Added html_decode() to default message into Text Input. I'm sure it's not the best solution, but I haven't found a better one, it almost completely removes the problem with `&#39;` while not affecting the standard inputs.
Flavor text and Employment Records limit is raised 3 times what it used to be
I just hope I didn't make it worse...
P.S. I Hate text Inputs
You can set 3k symbols employment record and edit it freely, without `&#39;`
And you ain't be punished if just close alert window (Probably)
https://github.com/ParadiseSS13/Paradise/assets/69762909/bf351083-c4ff-49e1-8ead-84f2a81ce62f
Images of changes
:cl:
fix: Flavor text and Character Records now have 3072 symbols limit. And doesn't show you `&#39;` instead of '
fix: TGUI Alerts no longer do things if you bad guy and …

Fixes some issues with TGUI Alerts, and Text Input

---

code/game/objects/structures/stool_bed_chair_nest/alien_nests.dm

Removes outdated line about them turning humans into eggs.
No longer hurts humans in it, since that is pointless and did not work on huggered people.
Heals humans with hivenodes, will not revive them.
Non hivenoded can not get in it or unbuckle people.
Descriptions being accurate is good.
Hivenoded being able to use xeno structures is good, but we don't need humans reviving from death with it.
No point in a damaging function when it only works on unhugged crew, or dead crew. You want to hugger crew before killing them, and there is no point in damaging a dead body.
Buckled / unbuckled hivenoded alien
Buckled a human with hivenode.
Unbuckled alien with hivenode
unbuckled human with hivenode, etc
:cl:
tweak: Revival nest no longer mentions it being able to turn people into eggs.
tweak: …

Revival nests description updated, heals hivenoded humans

---

code/game/objects/items/weapons/knuckledusters.dm

Knuckledusters lose their abstract flag on dropped now.
Fixes #24329
bug bad
Code compiles, I can more thoroughly test in a few hours.
:cl:
fix: Knuckledusters can be re-picked up if removed via surgery.
/:cl:

Knuckledusters lose their abstract flag on dropped now.

---

code/modules/mining/equipment/wormhole_jaunter.dm

Mining wormhole jaunters now knockdown for 12 seconds, instead of weakening.
Mining antags are already very strong, and jaunters give a free way to guarantee a stun if someone follows you through them. As long as the miner jaunts first, they'll be actionable before anyone who follows 100% of the time. It creates an annoying catch-22 where if an officer doesn't follow, then the antag gets away for 750 mining points. If they do follow, they'll have a small period of time where they're hardstunned, and the person they followed isn't. This changes it so while there's still an advantage for the miner, it doesn't guarantee the free stun.
It's also a nice QOL for miners who use jaunter.
I've Fallen And I Can Get Up (after being able to crawl around for 12 seconds)
:cl:
tweak: Going through a …

Wormhole jaunters knockdown

---

code/modules/client/preference/link_processing.dm

Slightly changes the input checks when editing records, flavors and OOC notes.
Brings back convenient records deletion.
Yes.
:cl: Maxiemar
fix: Fixed the impossibility to delete records, flavor text and OOC notes.
/:cl:

Allow an empty string when editing records, flavors, OOC notes

---

_maps/map_files/cerestation/cerestation.dmm

This PR adds a missing pipe in the waste belt room.
Map fix.
Spawned in, double checked. verified airlock properly depressurized as well.
:cl:
fix: Farragus: fixed missing piping in SE waste belt airlock.
/:cl:

cere: fix missing pipe in SE waste belt room

---

code/modules/clothing/clothing.dm

Galoshes no longer cause a runtime trying to get an item slot from a user that doesn't exist.
Fixes: #24163
Runtime bad.
Dispense galoshes from a janitor vendor with my hands full
No runtime baby.
NPFC

Galoshes no longer runtime when dispensed from a vendor.

---

code/game/objects/structures/fluff.dm

makes fluff structures able to be deconstructed
bugfix and runtime fix
deconstructed a fluff structure
:cl:
fix: fluff structures are once again able to be deconstructed
/:cl:

makes fluff structures able to be deconstructed

---

code/modules/mob/living/carbon/carbon_defense.dm
code/modules/mob/living/carbon/human/human_defense.dm

- Makes reflected bullets reflect in a 60 degree arc (subject to change) in front of the user
- Makes thrown items be reflected in a random arc in a direction
Carpfu is in a weird spot of being very expensive (65 TC) while also being not really worth it. You can easily disable the ranged immunity by throwing any item. This prevents that from happening while also buffing the offensive potential a bit.
https://github.com/ParadiseSS13/Paradise/assets/108773801/f4649dd8-2fd8-413c-a37f-e2cbea7b6364
See above
:cl:
tweak: Carpfu now reflects bullets and projectiles in a 60 degree arc in front of the user
tweak: Carpfu now reflects thrown items
/:cl:

Buffs Carpfu

---

code/modules/mob/living/living.dm

fixes #24313
Someone fatfingered the wrong var so this works again
grab jank BEGONE
Screwed around with a skrell, grabed and passed through em, then twirled them around for the hell of it
:cl:
fix: Grabs no longer fail when you run into the person you grabbed
/:cl:

fixes #24313

---

code/modules/mob/mob_grab.dm

Fixes #24198 
Makes reinforcing a grab only check whether or not a mob is restrained, not immobilized. This allows mobs to reinforce above yellow grab if they're buckled in a chair or otherwise do not have the MOBILITY_MOVE flag.
Not being able to reinforce grabs while you're sitting in a chair is kind of silly, and the reinforcement failing silently is just confusing and unintuitive. If you can yellow grab while in a chair, you should be able to go all the way.
Tested all of the edge cases that I thought could cause issues, like anything that adds TRAIT_IMMOBILIZED with the intention to stun or otherwise debilitate the user. I'm pretty sure that any potential grabbing-after-stun issues are resolved by the grab dropping before the user can reinforce it.
:cl: Chuga
fix: Grabs can now be …

Fixes #24198

---

code/modules/admin/verbs/adminpm.dm

Moves the chat section of the `PM to-...` message from unsorted to `Admin PM`
It's very cluttered and keeping all admin PM stuff in one tab is a lot better for organizing and checking what you sent to someone without having to open the PM window
See image above
:cl:
tweak: The `PM to-...` message has been moved from the unsorted category to the admin PM category
/:cl:

Moves the `PM to ...` to the admin PM section

---

code/datums/diseases/advance/symptoms/hair.dm
paradise.dme

Adds a "Cranial Hypertrichosis" symptom which behaves like hairgrownium in stage 1-3, and like super hairgrownium in stage 4-5. This symptom complements the symptom "Facial Hypertrichosis"
Completes the hair symptom trio: Alopecia, Facial Hypertrichosis, and Cranial Hypertrichosis.
Infected the player with a virus containing Cranial Hypertrichosis and checked that the behavior is consistent with Hairgrownium
:cl: cdui
add: Cranial Hypertrichosis symptom for advanced microbes which behaves similarly to Hairgrownium
/:cl:

Add Cranial Hypertrichosis (Hair Grow Symptom)

---

code/modules/projectiles/projectile/magic_projectiles.dm

re-writes and clarifies the Weeping Angel message when converted by a wizard using the flesh to stone + animate wand.
The old message is simply a boldened red text. its EASILY lost in most high-chaos scenarios. I personally experienced a wizard who was routinely attacked by their own statues because the players did not notice the text saying to not bother the wizard. The message now is extremely obvious, and also added in the fact that you're expected to hunt down other players as a weeping angel. 
**Before**
**After**
Spawned in. Had friend turn flesh to stone, then animate. Got message and de-statued as anticipated after.
:cl:
tweak: Clarified Weeping Angel Message
/:cl:

Makes Weeping Angel Conversion Clearer

---

code/modules/mob/living/carbon/alien/special/alien_embryo.dm

fixes xenos being nullspaced in rare situations
Do not send xenos directly to FALSE (This is not a joke)
This is just a change to get_turf(), I didn't
:cl:
fix: Xenos will no longer be sent to null in some odd situations
/:cl:

fixes xenos being nullspaced in rare situations

---

code/modules/projectiles/ammunition/ammo_boxes.dm
code/modules/projectiles/ammunition/ammo_casings.dm
code/modules/projectiles/guns/projectile/saw.dm
code/modules/projectiles/guns/projectile/sniper.dm

See title.
Currently, every single bullet in the game has the exact same name and near-identical descriptions, which doesn't make much sense.
Secondly, I am aware many of our players and staff do not come from the Land of the Free, and thus may need help identifying what a bullet does, and to what gun it goes.
This should hopefully rectify both issues.
- Loaded in
- Spawned many bullets and ammo boxes
- Names and descriptions have changed
:cl:
tweak: Added names and descriptions to many bullets and ammo boxes
/:cl:

Adds names and descriptions to most bullets and ammo boxes

---

code/game/objects/items/tools/welder.dm

Allows welding tools to light another person's cigarette by targeting the mouth whilst there is an unlit cigarette perched between their lips.
When someone asks you if you have a light, you can nod with confidence as you pull out your trusty welder like a true badass.
A number of skrell were given cigarettes. They then lit each other's cigarettes with a welding tool that was also provided.
No skrell were harmed in the making of this PR.
:cl:
add: Unlit cigarettes in the mouth slot can be lit by another person using a lit welder when targeting the mouth.
/:cl:

Welding tools can be used to light other people's cigarettes

---

code/modules/mining/lavaland/loot/ashdragon_loot.dm
code/modules/mining/lavaland/loot/tendril_loot.dm
code/modules/mob/dead/observer/observer_base.dm

Tweaks the spectral blade to show small orbs to represent the ghosts orbiting it, rather than the ghosts themselves. This means no concerns about ghosts being stuck visible, or ghosts pointing. The only thing the living will see are the little orbs.
The orbs will still have the colors of the ghosts, meaning they will still have a bit of character, but they will not have any of the same levels of identifiability as the original characters.
The spectral blade is one of the few places in the game where the dead can be manifested by the living. Ghost invisibility has been kind of a problem with ghosts getting stuck visible due to weird interactions with the spectral blade, which leads to ghosts travelling everywhere across the station. Pointing also leads to some pretty troublesome …

Spectral blade now shows orbs, not ghosts

---

code/modules/antagonists/changeling/powers/become_headslug.dm

makes last resort work
bugfix
Used it in game
:cl:
fix: Last resort now works again
/:cl:

makes last resort work

---

code/modules/paperwork/pen.dm

Makes sleepy pens trigger reactions correctly.  The existing code doesn't work because the reagents are empty by the time it tries to react.  This updates the call to match a syringe.
Fixes #24158 (the unintended part, at least)
Things that inject should trigger injection reactions.
Made advanced mutation toxin, put it in a sleepy pen, injected a monkey, waited.  Am now being glomped by a slime.
:cl:
fix: Sleepy pens will trigger reactions properly.
/:cl:

Made sleepy pens awake enough to react.

---

code/modules/economy/economy_machinery/eftpos.dm

Removes the account login from the EFTPOS.
This was actually supposed to be removed by PR #20095, but the merge in commit e4510f576 undid it by accident.  With the current state of the code, it checks to make sure the account info is valid... but then doesn't actually link to that account.  It uses the one you selected in the dropdown instead.
Spawned as chef, set EFTPOS to deposit into my own account without a prompt, paid, checked ATM, $20 successfully paid to myself, instead of the default service account.
:cl:
fix: EFTPOS will no longer ask you for account ID and password.  They didn't use them anyway.
/:cl:

Remove account login from EFTPOS

---

code/modules/mapping/mapping_helpers.dm

This PR sets the layer of `/obj/effect/mapping_helpers/no_lava` to `ON_EDGED_TURF_LAYER`, which is just above `/turf/simulated/mineral`'s layer of `EDGED_TURF_LAYER`.
This makes the mapping helper show up above the rock walls so that it's visible in map editors. Not being able to see this on e.g. ruin maps is confusing and frustrating.
Checked map editor output before and after change.
NPFC

make no_lava mapping helper visible above rock walls

---

code/game/gamemodes/cult/blood_magic.dm
code/game/gamemodes/wizard/godhand.dm
code/game/machinery/computer/atmos_controllers.dm
code/game/mecha/paintkits.dm
code/game/objects/items/devices/camera_bug.dm
code/game/objects/items/devices/radio/intercom.dm
code/game/objects/structures/signs.dm
code/game/turfs/simulated/floor/light_floor.dm
code/modules/clothing/masks/gasmask.dm
code/modules/clothing/suits/misc_suits.dm
code/modules/crafting/guncrafting.dm
code/modules/mob/living/simple_animal/bot/honkbot.dm
code/modules/mob/living/simple_animal/friendly/dog.dm
code/modules/mob/living/simple_animal/friendly/farm_animals.dm
code/modules/mob/living/simple_animal/hostile/bat.dm
code/modules/mob/living/simple_animal/hostile/jungle_animals.dm
code/modules/mob/living/simple_animal/hostile/retaliate/fish.dm
code/modules/paperwork/stamps.dm
code/modules/power/engines/singularity/collector.dm
code/modules/projectiles/guns/projectile/revolver.dm
code/modules/research/anomaly/anomaly.dm

\improper makes a capitalized word not omit "the", e.g. "You pick up CPU." (without) vs "You pick up the CPU." (with).
This makes no sense to use if the next letter isn't capitalized.  So we shouldn't.
Consistency is good.  Using BYOND features incorrectly is not.
Compiled, spawned a random object from the list of previously-\improper objects.
`You put the pyroclastic anomaly core into the backpack.`
NPFC

Removed improper \improper

---

code/_onclick/hud/other_mobs_hud.dm

Simplemobs have a see_through_darkness variable that has been going unused because they didn't enable the overlay that makes it work.  This enables that overlay.
In effect, this grants most simplemobs a very slight amount of vision in darkness.  It's darker than a small light fixture, but you can barely see stuff now, with a larger range based on your see_through_darkness.
Humanoids already have this (most at level 2), and simplemobs have values set for it, they just seem to have forgotten to turn it on.
Mouse (6):
Headslug (2):
See images.
:cl:
fix: Simplemobs were supposed to have slight vision in pitch black areas, like humans do, but with species-specific values. The overlay responsible for this was not activated until now.
/:cl:

Fix simplemobs' see_through_darkness

---

code/modules/mob/living/simple_animal/friendly/farm_animals.dm

Fixes #23778 
you can make funny names for chicks and NOT expect them to dissapear when they grow into chickens now!
I spawned a chick, gave it a custom name and watched it grow into a chicken!
:cl:
fix: chicks are now keep their names when growing up into chickens
/:cl:

fixes the error where chicks lose their custom name when growing into chickens

---

code/game/objects/items/stacks/sheets/glass.dm

Makes glass and plasma glass shards craftable via the in-hand menu for glass, reinforced glass, plasma, and reinforced plasma sheets.
Adds QOL for acquiring shards. Having to place down a bunch of windows is pretty tedious when you want a lot of them.
Spawned and crafted shards using a sheet of each type.
:cl: Chuga
add: Shards can now be crafted using glass and plasmaglass sheets
/:cl:

Makes glass shards craftable using sheets

---

tools/maplint/lints/apc_pixel_shifts.yml
tools/maplint/lints/directional_apcs.yml

This PR updates the maplint for APC pixel offsets. It now explicitly bans any subtype that's not a specific directional helper, and it bans any pixel offset varediting for any subtype.
Without this, people could still map in the non-directional mapping helpers. This prevents that, and prevents people from using a directional helper but modifying the pixel offset anyway.
Ran CI.
NPFC

ci: update maplint for APC mapping helpers

---

code/modules/mob/mob_misc_procs.dm

Fixes bug where AI would still see the HUD on mobs using the big brother jumpsuit or digital camouflage cling power.
Fixes: #23578
These items are a bit useless if you can still see users on HUD.
Be AI, medical HUD on.
Spawn skrell, call proc set_invisible(25) on them.
The skrell and their HUD are no longer visible.
Something smells fishy in here but I can't see what it is.
:cl:
fix: Big brother obfuscation suit and digital camouflage cling power now properly hide user's HUD from silicons.
/:cl:

Fixes AI still seeing HUD on mobs invisible for silicons.

---

code/game/gamemodes/cult/cult_mode.dm
code/modules/mob/living/simple_animal/constructs.dm
code/modules/mob/living/simple_animal/shade.dm

fixes deleted cultists still being considered cultists, this will also fix some cult gc issues
bugs bad
Deleted some cultists
:cl:
fix: Cultists will now stop being cultists when deleted
/:cl:

fixes deleted cultists still being considered cultists

---

code/datums/emote.dm

Fixes #23835
Adds a check in can_run_emote() to verify that a mob's species is allowed to use an emote even if their original mob type can't. 
Bugs are bad 
Successfully screamed in agony
:cl: Chuga
fix: Humanized monkey brain transplants can now scream again
/:cl:

Fixes #23835: Emotes properly check for mob species

---

code/modules/mob/living/silicon/robot/robot_mob.dm

Fixes a runtime that prevents borgs without a client from being reset
Runtimes bad.
Spawned as borg.  Picked a module.  Left module tray open.
Moved to roboticist, reset borg.
Moved back to borg, module tray was not open.
:cl:
fix: Fixed a runtime when resetting a borg without a connected client.
/:cl:

Borgs without a client can be reset now

---

code/modules/events/ion_storm.dm
code/modules/mob/living/simple_animal/bot/bot.dm

Now we check the bots for the ion storm in GLOB.bots_list and not in GLOB.machines
Beepsky no longer considers himself a machine. I think its bugfix...
I started local server, trigger ion storm event, some bots are emagged
:cl:
fix: bots emag during an ion storm, as they should
/:cl:

replacing with correct bots list for emag in ion storm

---

code/modules/tgui/tgui_panel/tgui_panel_external.dm

Adds alert when you try to Refresh TGUI.
And fixes blank windows if you do it.
TGchat and TGsay will refresh only after first refresh.
No blank windows
https://github.com/ParadiseSS13/Paradise/assets/69762909/c930b4ce-8ba7-4169-8c92-49e58a7b2350
Above
:cl:
fix: There should no longer be a blank windows if you do Refresh TGUI
/:cl:

Refresh TGUI blank window fix

---

code/game/objects/items/stacks/stack.dm
code/game/objects/items/stacks/stack_recipe.dm

Creates two new procs on /datum/stack_recipe/ - try_build() and do_build().
try_build() is a series of checks to prevent impossible constructions while do_build() handles the actual construction.  This code is not new and is just relocated from /obj/item/stack into a better and more sensible place.
This PR also makes it so stack-crafted items will go into the player's off-hand if it's free - this was always intended behavior but it wasn't functional in most situations.
Allows recipes to have custom construction checks and behavior.
Things still craft correctly.
:cl:
fix: Items crafted by using stacks in-hand will now be properly placed in your off-hand if it's free.
/:cl:

Puts some of the stack crafting code onto the stack recipe datum.

---

code/game/gamemodes/cult/runes.dm

This PR makes shards put in invoker's hand instead of dropping on the floor
When there is many security fallen on the offer rune, its cluttered with tons of items and bringing shards out of it becomes a real problem. Imagine being a shard in newbie's cult hands, being dropped on the floor and forgot forever.
This supposed to be QoL change for any cultists
Compiled, logged in, sharded security.
:cl:
tweak: Cult offering someone by sharding(mindshields, cyborgs) will put shard in invoker's hand instead of dropping it on the floor.
/:cl:

Cult offer puts shard in hands instead of dropping on the floor

---

code/game/objects/items/tools/crowbar.dm
code/modules/mob/living/silicon/robot/robot_modules.dm

Replaces the crowbars of all borgs except engi and saboteur with a red emergency crowbar with identical stats (change is cosmetic only) and a different description.
Non construction borgs were given crowbars to allow them to pry open doors in the event of power failure. They're *emergency* tools that are not expected to be used during normal operation. Thus, they have been been given a slightly different version that reflects this fact.
Spawned, became various borgs. Saw that they had the different crowbar.
:cl:
tweak: All borgs except engi and sabotage have red crowbars now.
/:cl:

Makes the crowbars of non-construction borgs red

---

code/modules/clothing/suits/armor_suits.dm

Dishonourably demotes the blueshield from the rank of lieutenant for failing to ensure all the child locks are enabled on the station maint tunnels, allowing the captain to wander into the tunnels where he proceeded to get lost for more than 6 hours until a passing engineer found him curled up in the foetal position crying for help.
Fixes an oversight in #12701.
The blueshield is not worthy of holding the rank of lieutenant.
Became a blueshield. Saw my armour. Was sad that I was no longer an officer of the Nanotrasen Navy.
:cl:
tweak: Blueshield's security armour no longer refers to the blueshield as a lieutenant.
/:cl:

Blueshield armour no longer refers to the blueshield as a lieutenant

---

code/controllers/subsystem/non_firing/SSchangelog.dm

Make the Changelog button change color when unread, again.
This seems to have been accidentally removed by #23726.
It's good to know when things change.
It compiled and ran OK. My test setup doesn't have a working changelog, so I can't really test that the color changes when there's a new change.
:cl:
fix: Changelog button will change color when unread again. But you saw that already, right?
/:cl:

Make the Changelog button change color when unread.

---

code/datums/emote.dm

#24361 added a check to let an emote pass if their species was able to use it even if their mob type was in the blacklist typecache. This had the unintended side effect of letting both /living/scream and /living/carbon/human/scream pass at the same time for humans and subspecies, and caused both double screaming and blocked species specific noises like moth buzzing.
Bugs are bad, but adding even more bugs is worse.
It theoretically compiles

Revert #24361, fixes double screaming

---

code/datums/station_traits/postive_traits.dm

Replaces the following implants with the following implants on the marked jobs
Atmos: Upgraded lungs. swapped from breathing tube
Hydro: Botanical toolset implant. Lost feeding implant
CE: Wire interface implant. Lost mesons
Hos: CNS rebooter. Lost telebaton implant
Janitor: Jani hud implant. Lost jani toolset implant
Miner: Meson eyes. Lost breathing tube
Engineer: Welding shielded eyes. Lost wire interface implant
Viro: medhud implant. Lost breathing tube
Bluesheild: Flash arm implant. Lost upgraded heart.
Some of the choices were very strange, ce getting objectively worse stuff than engineers, some of the heads getting upgraded hearts over.. useful things? and hydro feeding implant makes no sense the botany toolset existed i guess it was forgotten about.
hopefully these changes are …

Changes some of the cyber implants that you get from the cybernetic revolution trait 

---

code/modules/surgery/organs/augments_arms.dm

Title
botanists only get use out of the wire cutters, that're easily accessible, they'll objectively get far more use out of pest and weed spray 
compiled, pssst psssssted
:cl:
tweak: The botany toolset implant has pest and weed spray apposed to a wrench and wire cutters
/:cl:

Swaps the wrench and wire snippers for weed and pest spray on the botany implant

---

code/modules/clothing/clothing.dm

You no longer need to take off glasses to tweak if they show above/below a mask.
Quality of life, because its SO clunky otherwise, especially when you usually just want to see if it looks good above the mask or not
~~Probably compiles~~
:cl:
tweak: Glasses are no longer removed when you toggle if they show above or below a mask.
/:cl:

Buffs all glasses

---

code/modules/mob/mob.dm

A chat message is sent to the user when they use Respawn as NPC to become a mouse.
Old text: You are now a mouse. Try to avoid interaction with players, and do not give hints away that you are more than a simple rodent.
New text: You are now a mouse, a small and fragile creature capable of scurrying through vents and under doors. Be careful who you reveal yourself to, for that will decide whether you receive cheese or death.
This is a really old message, going back at least as far as when respawning as mice was added, in commit 632cad10.  And even that mentions it's re-adding the feature , so the message might be even older..
The message doesn't reflect the reality of mouse spawns anymore.  We've got a variety of sentient animals, and this is the only one that gets warned to not give away …

Update the Respawn as NPC -> Mouse intro text

---

code/modules/mob/living/simple_animal/hostile/angel_statue.dm

Slightly refactors the blindness spell and adds a check for other weeping angels. 
Being able to blind other angels during a wizard round that contains multiple angels is not very fun or intuitive.
It selects the correct targets and blinds them.
:cl: Chuga
tweak: Weeping angels no longer blind other weeping angels
/:cl:

Makes weeping angel blindness not affect other angels

---

code/modules/projectiles/ammunition/magazines.dm
code/modules/research/designs/autolathe_designs.dm

Reduces cost of E-Revolver Chargepacks to 20000 metal and 6000 glass from 30000 metal and 6000 glass.
To me it doesn't make much sense why the chargepacks are more expensive than .357 ammo, and it tends to force the detective to ask for a disabler when cargo doesn't have much in terms of materials.
Printed more ammo than usual.
:cl:
tweak: E-Revolver Chargepacks are now less costly to print from autolathes.
/:cl:

Reduces Autolathe cost of E-Revolver Chargepacks

---

code/modules/food_and_drinks/food/condiment.dm

When suiciding with the salt shaker, if it has any room left, it will be filled with salt.
Adds a silly detail to an already-silly suicide action.
Emptied 5u out of salt shaker.  Suicided.  Salt shaker was full again.
:cl:
tweak: The salt shaker suicide will now refill the salt shaker. Salt from dead crew indeed.
/:cl:

Salt shaker suicide refills its salt

---

code/modules/food_and_drinks/food/foods/ingredients.dm

Mice can now pull cheese wedges under doors
Minor QOL for the humblest of station pets.
Spawned as mouse. Spawned cheese wedge. Pulled it under a door.
Spawned a grille. Could not pull it under the grille.
Spawned a skrell with PASSDOOR. Could not pull cheese wedge under a door or a grille.
:cl:
add: The station's mice have learned how to sneak cheese wedges under a door.
/:cl:

Mice pull cheese wedges under doors

---

code/game/objects/items/crayons.dm
code/game/objects/items/toys.dm
code/game/objects/items/weapons/courtroom.dm
code/game/objects/items/weapons/defib.dm
code/game/objects/items/weapons/garrote.dm
code/game/objects/items/weapons/kitchen.dm
code/game/objects/items/weapons/legcuffs.dm
code/game/objects/items/weapons/melee/energy_melee_weapons.dm
code/game/objects/items/weapons/melee/melee_misc.dm
code/game/objects/items/weapons/shards.dm
code/game/objects/items/weapons/stunbaton.dm
code/game/objects/items/weapons/weaponry.dm
code/game/verbs/suicide.dm
code/modules/antagonists/changeling/powers/mutations.dm
code/modules/fish/fish_items.dm
code/modules/food_and_drinks/food/condiment.dm
code/modules/hydroponics/grown/banana.dm
code/modules/hydroponics/grown/kudzu.dm
code/modules/hydroponics/grown/nettle.dm
code/modules/hydroponics/hydroitemdefines.dm
code/modules/paperwork/pen.dm
code/modules/power/cables/cable_coil.dm
code/modules/power/cell.dm
code/modules/projectiles/guns/energy_guns.dm
code/modules/projectiles/guns/magic.dm
code/modules/projectiles/guns/projectile_gun.dm
code/modules/surgery/tools.dm

s/trying to commit suicide\\./trying to commit suicide!/
(plus a few manual ones that use a word other than 'suicide')
Consistency is good.
It compiled.
:cl:
spellcheck: All suicide actions now put an exclamation point on "trying to commit suicide!"
/:cl:

Standardize on exclaiming about committing suicide.

---

code/game/objects/structures/crates_lockers/largecrate.dm
code/modules/supply/supply_packs/pack_security.dm

Adds a secway crate to cargo, requiring head approval and 800 credits. (To avoid random tiders buying them. They should STEAL them.)
In general I feel there's a lack of things to order from cargo each round, and if Security want to go around larping as mall cops I think that's their god given right as the founding harmbatoners intended.
I ordered one and opened one, confirmed the right money had been taken out.
:cl:
add: Secways can now be ordered from cargo.
/:cl:

Adds Secway Crate to Cargo orderables.

---

code/game/machinery/vendors/vending.dm

Title.
They should do this.
It works.
:cl:
tweak: Vendors now unanchor when tipping over.
/:cl:

Makes vendors unanchor themselves when tipping over.

---

code/modules/mob/living/carbon/carbon_life.dm
code/modules/reagents/chemistry/reagents/toxins.dm
strings/chemistry_tools.json

Lexorin is now one of the poisons that can spawn when you buy a poison bottle from the Syndicate uplink.
Lexorin was broken before, all it did was make you completely ignore breathing code (you could smoke a Lexorin enigma cigarette and walk through N2O, Plasma, or an area with no breathable atmos for your species and be completely unaffected). It now does breathloss like all other chems that stop you breathing. It now also does 5 oxygen damage per cycle (you can't breathe, dummy!). This also means that smoking the aforementioned cigarettes will now absolutely screw you up (just as god intended).
Lexorin is an underappreciated chem, it adds a dedicated oxyloss chem to the uplink, we don't really have a chem that primarily works via oxyloss. It doesn't leave much permanent damage aside …

Adds Lexorin to the Uplink Poison Bottle Bool. Also, Fixes Lexorin.

---

code/game/objects/items/robot/robot_parts.dm

The panel from using a multitool on an unfinished borg chassis was supposed to let you disable the borg connecting to an AI when built.  That button works now.
Apparently this panel exists? Well, it should work correctly, even if people don't know it's there.
Built two borg chassis. Disabled AI Connection Port on one. Finished borgs. The one with a closed port didn't link to the AI, and the other did.
:cl:
fix: The panel from using a multitool on an unfinished borg chassis was supposed to let you disable the borg connecting to an AI when built.  That button works now.
/:cl:

Made the AI Connection Port setting actually work.

---

code/modules/power/engines/supermatter/supermatter.dm

Adds a check for containment field so SM won't delete them. Fixes #24423
This was an oversight, SM shouldn't be able to qdel those.
Compiled, pushed a crystal into containment field, it worked
:cl:
fix: SM crystals no longer delete containment fields.
/:cl:

fixes SM crystals being able to delete containment fields

---

.vscode/tasks.json
code/modules/shuttle/shuttle.dm
tools/ci/check_grep2.py

This PR adds a new task to the VSC tasks listing which runs check_grep2, and makes it a dependency on the build task so that the compiler won't run unless check_grep2 is happy. It also ensures the errors actually show up in the editor.
It is technically feasible to run these on save, but that would require a 'watch task', essentially something that sits in the background and waits on file changes to run. Custom tasks can't be run on save. I'd link to the GitHub issue describing this but I already closed the tab.
Rather than try and get all our linters working at once, I'm starting with just one to make sure it works for other users and to refine them if I have to, later.
If someone isn't comfortable with the command line, the only way to get CI results is to push a PR and run CI. Even if …

vsc: run check_grep2 before build

---

code/modules/atmospherics/machinery/components/unary_devices/cryo.dm

Mapped in cryo cells now gives the correct amount of cables when deconstructed (1 cable instead of 30)
Initialize is already being used by /unary and is prefered.
It giving 30 cables (which is the initial amount the stack has) instead of 1 when deconstructed is a bug.
**BEFORE**
**AFTER**
- Healed skrells after beating em up using the cryo cell
- Deconstructed cryo cells from medbay and verified cable amounts
:cl:
fix: Mapped in cryo cells now gives the correct amount of cables when deconstructed
/:cl:

Mapped in cryo cells now gives the correct amount of cables when deconstructed

---

code/__HELPERS/unsorted.dm
code/game/objects/items/weapons/dice.dm

Updates get_edge_target_turf to TG's version. This gives us PROPER diagonal support for it.
See changelog for basically everything affected.
Also fixes an issue with the die of fate not being passed a proper direction.
We have diagonal movement, and I hate that this code says it works with diagonals, but it LIES.
Code compiles, I threw some people around. I tested the fix.
:cl:
tweak: Powerfist, Sleeping Carp's Crashing Kick, Wizard's repulse spell, Energized Fireaxe, Traitor's pushbroom, Vampire's Seismic Stomp, RD's repulse armor, and Cursed Katana all work better with diagonals now.
tweak: Unwrenching pipes with unsafe pressure now considers diagonals
tweak: Gibbing humans will now explode with their organs and items flying more accurately on diagonals.
tweak: Gorillas, kangaroos can …

Updates get_edge_target_turf to work better with diagonals

---

code/game/objects/items/weapons/storage/storage_base.dm
code/modules/clothing/suits/suit_storage.dm

Suit storage items (labcoats and similar) can now be opened with alt-click.
Adds an extra check to make sure items can't be put into distant inventories.
Closes suit storage item inventories when thrown away (Fixes #3588)
Making storage items more consistent is good.
Bug fixing is good.
Alt-clicked a labcoat.  Got UI.
Threw it away.  Lost UI.
:cl:
tweak: Suit storage items (labcoats and similar) can now be opened with alt-click.
fix: Throwing suit storage items no longer leaves their UI open.
/:cl:

Improved storage UX of labcoats and similar.

---

code/game/gamemodes/nuclear/nuclearbomb.dm
code/game/machinery/machinery.dm
code/game/machinery/portable_turret.dm
code/game/objects/items/devices/camera_bug.dm
code/modules/food_and_drinks/kitchen_machinery/smartfridge.dm

I think that `interact_offline` can be used instead of `requires_power` in all cases, so let's just remove the last one.
This brings a little refactoring.
Also fixes #24517.
Bugs bad, less memory cool.
Launched locally, tried several machines, turned the power off. Works like expected.
:cl: Maxiemar
fix: Tint control button can be toggled in advanced admin interaction mode
/:cl:

Remove excess variable from machinery

---

code/modules/mod/modules/modules_general.dm

Fixes the jetpack stabilizer setting on on the modsuit jetpack modules.
Fixes: #23998
Settings should actually work.
Put on a modsuit with a jetpack module.
Turn on the stabilizer module.
I no longer float away.
Turn off the stabilizer module.
:cl:
fix: Jetpack module stabilizer setting button now works.
/:cl:

[FIX] Jetpack module stabilizer setting button now works.

---

code/game/machinery/deployable.dm

Adds a deconstruction act, to wooden barricades. 
Takes six seconds, you need a crowbar, returns the 5 planks it takes to craft them
Before this we've needed to wack the planks 15 times, this changes that to be better.
see images of changes
:cl:
tweak: You can now deconstruct wooden barricades with a crowbar.
/:cl:

Finally adds a decontruction act to wooden barricades!

---

code/controllers/subsystem/SSstatpanel.dm

Fixes a statpanel runtime:
```
[2024-03-08T01:00:23] Runtime in code/controllers/subsystem/SSstatpanel.dm,114: Cannot modify null.atoms_to_show.
proc name: set turf examine tab (/datum/controller/subsystem/statpanels/proc/set_turf_examine_tab)
src: Stat Panels (/datum/controller/subsystem/statpanels)
call stack:
Stat Panels (/datum/controller/subsystem/statpanels): set_turf_examine_tab
Stat Panels (/datum/controller/subsystem/statpanels): fire
Stat Panels (/datum/controller/subsystem/statpanels): ignite
Master (/datum/controller/master): RunQueue
Master (/datum/controller/master): Loop
Master (/datum/controller/master): StartProcessing
```
I'm not really sure how this runtime is happening, but there we go.
Loaded up the game and checked functionality

Fix for null "atoms_to_show" runtimes

---

code/modules/food_and_drinks/food/customizables.dm

Food can now be named.
Creative chefs can rejoice.
This is a haiku.
Fixes #24028
There's been a tip that says this is possible for years, but I'm not clear that it was ever actually possible.  Now the tip and the reality will match.
Spawned French onion soup and a slice of bread.  Put the soup on the bread.  Pulled out a pen.
```
You declare this to be Bread Bowl of French Onion Soup. Delicious!
You declare this to be a mistake. Delicious!
You declare this to be an iconic dish. Delicious!
```
(the name updated, too)
:cl:
add: Custom food can now be renamed.  Yes, there's been a tip claiming this was possible for years.  No, it wasn't until now.
/:cl:

Custom food can now be renamed, as the tip indicates.

---

code/modules/research/server.dm

After more that 100 years, NT has finally changed the password on their research servers.  Or maybe they cheapened out on antennas, IDK.
Regardless, non-admin R&D server controllers can no longer control R&D servers on the different Z-levels, nor can they modify the upload protocols of R&D consoles on different Z-levels. This means that the station, Theta, and the free golems can no longer steal tech from each other.  However, if any of them wish to, they can grant the others download access for the data on their own server (if any).
Stealing tech from the station is problematic both lore-wise and gameplay-wise.  On the lore end, NT really should be protecting their cutting-edge research from trivial cyber attacks.  On the gameplay end, part of the point of ghost spawns is that you're …

Lock down research servers

---

code/game/objects/items/tools/wirecutters.dm
code/game/objects/items/tools/wrench.dm

Wrench and powered wirecutters suicides now remove the head, and do not kill if the head isn't vital.
Normal wirecutters now have a fitting message for machines.
More amusing this way.
Spawned as a human.
Tried to suicide with powered wirecutters, but moved. The SHAME.
Suicided with all three tools.
C.M.A. to machine.
Failed to suicide with wrench and powered wirecutters, but head still came off. The SHAME.
Suicided with normal wirecutters.
Failed to suicide with wrench and wirecutters with no head. The SHAME.
:cl:
tweak: Suicide effects for wrench, wirecutters, and powered wirecutters have been adjusted.
/:cl:

Change wrench, wirecutters, and powered wirecutters suicides.

---

code/game/turfs/simulated/floor/misc_floor.dm
code/game/turfs/simulated/floor/plating.dm
code/game/turfs/simulated/walls_misc.dm

Majorly buffs clockwork tiles to be 134% cooler
Does the same for cult tiles
Gives cult walls an on-hit effect
Restore a small part of the glory of Ratvar
https://github.com/ParadiseSS13/Paradise/assets/108773801/8648606e-7250-4cb4-a725-d8063a0e542c
https://github.com/ParadiseSS13/Paradise/assets/108773801/245b6e90-ab5a-43d0-b485-3a5229f93307
:cl:
add: Clockwork/Cult tiles now give a glow effect when you walk over them
add: Cult walls now show an effect when they are hit by a bullet
/:cl:

Buffs clockwork and cult floortiles

---

code/game/gamemodes/miniantags/abduction/abduction_surgery.dm

Fixes #24512
Adds a mirror surgery that skips the sawing steps of experimental dissection if the target doesn't have any bones. 
Consistency in surgery steps is good!
Sawed through a skrell, could not saw through a slime.
:cl: Chuga
fix: Abductor Experimental Dissection surgery steps now respect the (non)existence of bones.
/:cl:

Fixes #24512: Adds Abductor Experimental Dissection surgery for boneless people

---

code/modules/mob/living/silicon/!silicon_mob.dm
code/modules/mob/living/silicon/robot/!robot_mob.dm
code/modules/mob/living/silicon/silicon_defense.dm
code/modules/mob/mob_emote.dm

Fixes some issues with borg hats.
- When a robot drops their hat from flipping it tells you that the robot dropped the hat, not "/datum/emote/flip"
- It is now possible to remove hats from drones an AIs by using an empty hand on them with grab intent.
Also cleaned up some code by moving emote behaviour to the proper file.
Bugs bad
Be a drone, have a hat on, have a hat remove. Flip with a hat on. People can see I dropped the hat, not some emote.
:cl:
fix: It is now possible to remove hats from drones an AIs by using an empty hand on them with grab intent.
fix: When a robot with a hat does a flip it now properly displays the name of the robot that dropped the hat instead of a path.
/:cl:

[FIX] Borg hat fixes

---

code/datums/outfits/outfit_debug.dm
code/game/objects/items/weapons/storage/storage_base.dm
code/game/objects/structures/snow.dm
code/modules/mod/mod_control.dm

storage items no longer bring up the turf panel on alt-click
surprise clientside lag is something I'm not for. This is also done for every other alt click interaction
you BET I alt clicked a storage item
:cl:
tweak: storage items no longer bring up the turf panel on alt-click
/:cl:

storage items no longer bring up the turf panel on alt-click

---

_maps/map_files/RandomRuins/LavaRuins/lavaland_surface_althland_excavation.dmm
_maps/map_files/RandomRuins/LavaRuins/lavaland_surface_althland_facility.dmm

Adds missing baseturf helpers to areas on:
- `_maps/map_files/RandomRuins/LavaRuins/lavaland_surface_althland_facility.dmm`
Removes unconnected one-tile areas with no baseturf helpers in:
- `_maps/map_files/RandomRuins/LavaRuins/lavaland_surface_althland_facility.dmm`
- `_maps/map_files/RandomRuins/LavaRuins/lavaland_surface_althland_excavation.dmm`
Space on lavaland is really bad for the CPU
:cl:
fix: Fixed being able to make space on lavaland
/:cl:

Fixes issues with althland ruins causing space on lavaland

---

code/game/verbs/suicide.dm
code/modules/mob/living/brain/MMI.dm

At some point in the past, MMI brains could commit suicide, as evidenced by #12845.  This has been re-added, without that bug.  So, uh, fixes #12845, I guess?
Being in an MMI should not prevent players from becoming an observer.
Spawned as robiticist.
Huffed my air tank.
Spawned a new humanoid.
Inserted roboticist brain in MMI.
Took direct control of brain mob.
Committed suicide.
Switched back to the newbie, dumped the brain, put it back.
Took direct control of brain mob again.
Committed suicide again.
:cl:
add: Brains in MMIs can now commit suicide.
/:cl:

Let MMI brains commit suicide.

---

.vscode/tasks.json
tools/ci/check_grep2.py

Reverts ParadiseSS13/Paradise#24538. If someone has a non-DM file open and focused when they try to build, the linter will break trying to lint the non-DM file.

Revert "vsc: run check_grep2 before build"

---

code/game/atoms_movable.dm
code/game/objects/structures/window.dm

Fixes #22396 
The reason this fix is needed is that the first part of the diagonal movement isn't completed before the second part is checked, so if you were moving northwest, `get_dir` will report that you're moving directly north (or west) for the first half of the move, but northwest for the second half of the move.
Also contains a minor refactor to `/atom/movable/Move` because I was digging through it for the fix.  It's impossible for `moving_diagonally` to have any value other than `FIRST_DIAG_STEP` here, so the checks are pointless.
Windows should be solid objects.
Built hallways out of directional windows and windoors. Hivebots couldn't dodge out of them.
Built apiary in hydroponics. Planted. Waited outside. No bees came.
Var-edited a bee to target me. It hit the windoor and went …

Make directional windows and windoors solid

---

code/controllers/subsystem/tickets/mentor_tickets.dm
code/controllers/subsystem/tickets/tickets.dm

One of the mentors complained the other day, "you know what, maybe it is a good rule of thumb to check if client is still connected before taking a ticket". And I thought, "Huh, it'd be nice if the ticket view showed that they're DC'd." Well, it was supposed to.
It turns out we've been caching the initial message, with all its details and links, and regurgitating it back every time the admin/mentor ticket view was opened. So you couldn't see if they mindswapped to a different mob, became a ghost, respawned as something else, or disconnected.
This has been fixed.
Also added some hardening against null mobs/clients, since that's a bigger concern now.
Stale info is bad. Current info is good.
Disconnected user:
Deleted mob:
Filed a mentor and admin ticket. Opened the views. Changed to a …

Make admin and mentor tickets actually update their info in the table view

---

_maps/map_files/RandomRuins/SpaceRuins/syndie_space_base.dmm

Removes the sentry bot from the syndicate research facility
- It will bug out because it can't pathfind, making extra unnecessary debug logs
- The shutters are admin access only, which if they want to protect the base they can already either spawn a sentry bot in, or do other ways, like summoning syndicate reinforcements/borgs.
This also means that the researchers can't use it as a helper if they quickly need support, because it requires admin intervention
I made it a rock wall, inspired by the hallway to the right of it
It compiled, it looked correct in the Syndie space base
:cl:
del: The sentry bot and shutters on the Syndicate research facility have been removed
/:cl:

Removes the mech from the syndie space base

---

code/game/objects/structures/crates_lockers/closets.dm

Crates and lockers could "steal" objects that were supposed to go somewhere else when dropped. That doesn't happen anymore.
Fixed #24575
Bugs bad.
Tried to put a janitor's water nozzle into the crate. It went back to the tank instead.
:cl:
fix: Stopped crates and lockers from taking stuff they shouldn't.
/:cl:

[s] Stop crates and lockers from taking stuff they shouldn't.

---

code/game/objects/items/weapons/storage/belt.dm

Allows the detective holobarrier to be put inside security belts.
This fixes an oversight in my original holobarrier PR.
Took projector, put in belt.
:cl:
fix: The Detective holobarrier projector now fits in security belts.
/:cl:

Fixes detective holobarriers not fitting inside security belts.

---

code/game/jobs/job/supervisor.dm

This PR updates IAA access to include cargo office. It also removes a deadcode comment from the IAA type.
When I made supply access more fine-grained in #23819 I neglected to update IAA. This fixes that oversight.
Spawned in as IAA on all stations, ensured could enter cargo office.
:cl:
fix: IAA has cargo office access again.
/:cl:

fix: IAA has access to cargo again

---

_maps/map_files/cerestation/cerestation.dmm

Fixes a supply pipe with a T-mainfold and adds back a disposals chute
Fixes #24590 
People won't suffocating and die due to the lack of air anymore
Spawned as a engineer and checked if the supply pipe and a disposal chute was there and it was
:cl:
fix: Fixed a wrong supply pipe and added back a disposal chute that was also missing at arrivals asteroid on NSS Farragus
/:cl:

Fixes a wrong pipe on Farragus cuts off arrivals asteroid from the air supply and disposals

---

code/game/objects/items/weapons/cards_ids.dm
code/modules/pda/nanobank.dm

When you are entering a PIN code through the nanobank PDA app it uses a tgui input window which as the default allows at max 10000 while pin codes can be at max 99999. This PR sets the max value of the nanobank pin code input window 99999, making all pin codes fit
This PR fixes this same issue but with setting a money account on a agent ID
bugs bad
increased account security in nanobank and then decreased it with a pin code which was above 10000
:cl:
fix: Fixed nanobank not being able to accept pin codes above 10000
/:cl:

Fixes the nanobank tgui input window not being able to accept pin codes above 10000

---

code/modules/mob/living/carbon/human/human_defense.dm

APPARENTLY, there has been a probability equivalent to the targeted limb's armor that your sharp attack becomes blunt this entire time. This heavily contributes to the current difficulty of decapitating people, and does not need to happen if the target is dead.
fixes https://github.com/ParadiseSS13/Paradise/issues/24455
Makes it a little bit easier to decapitate dead bodies with armor on them. This shouldn't have been a thing for dead people in the first place to be honest.
Confirmed that the check only happens if the target is not dead.
:cl: Chuga
tweak: It is now easier to whack off an armored limb with a sharp weapon if the target is dead.
/:cl:

Sharp attacks no longer get randomly blunted when the target is dead

---

code/modules/mod/mod_theme.dm

This bumps the radiation armor of both the normal blood red hardsuit, and the elite modsuit up to infinity, making the wearer fully immune.
You would think that suits given to nuclear strike teams would have better protection against radiation. It also gives people a way to use telecrystals to avoid finding radiation protection gear. I'll admit that buffing elite suit feels bad given how strong it already is, but I think the main impact this change will have will be making radiation-based hijacks more viable. The suit will otherwise remain as strong as it is now.
Irradiated myself so hard I became green on discord, blood red modsuit protected me
:cl:
tweak: Syndicate modsuits fully protect from radiation
/:cl:

Syndicate MODsuits fully protect from radiation.

---

code/modules/mob/mob_movement.dm

Probably needs TM
Ports https://github.com/tgstation/tgstation/pull/63332, explanation included in PR
Thanks to this https://github.com/ss220-space/Paradise/pull/4628 PR for pointing at that (also for comparsion showcase)
Better smooth when moving
Included in attached PR's above
Tested locally
:cl: LemonInTheDark, dj-34
fix: Fixed hitting a move input inside a small grace period in move code leading to teleportation. It's a side effect of when movement used to be verbs, and holding a button down meant constantly sending the server move commands
/:cl:

Reduce the move delay buffer to 1 tick

---

code/modules/supply/supply_console.dm

Removes `can_launch` from the supply console's UI data.
Don't send data if you're not going to use it!
Compiled, ran, opened shuttle console.  LGTM
NPFC

Removed an unused bit of UI data from the supply console.

---

code/modules/clothing/under/color.dm

Adds the hypernobilium weave jumpsuit to the random colored jumpsuit's exclude list
assistants spawning with something that looks like wizard gear is bad
it compiled
:cl:
fix: Fixed assistants spawning with a fake hypernobilium weave jumpsuit sometimes
/🆑

Fixes assistants spawning with fake wizard gear

---

code/__HELPERS/trait_helpers.dm
code/_globalvars/traits.dm
code/datums/helper_datums/teleport.dm
code/game/objects/items/devices/chameleonproj.dm
code/modules/mining/fulton.dm
code/modules/mining/lavaland/loot/tendril_loot.dm

Refactors the list of effects that can teleport into a trait.
Fixes #24636
Hardcoded lists bad.
Fultoned a corpse into a teleporter, received a corpse.
:cl:
fix: Fulton recovery beacons can no longer delete corpses that they send into a teleporter.
/:cl:

[s] Made effect teleporting into a trait.

---

code/modules/projectiles/guns/energy/special_eguns.dm

Makes it so that the plasma cutter does not require a weapon permit to be carried around.
The plasma cutter is a tool first and foremost, not a weapon, and having Beepsky beat random miners for seemingly no good reason is annoying.
Beepsky is leaving me alone, finally.
:cl:
fix: Beepsky no longer considers plasma cutters weapons.
/:cl:

[FIX] Security bots will no longer attempt to arrest people with plasmacutters.

---

code/controllers/configuration/sections/gamemode_configuration.dm
code/controllers/subsystem/processing/SSstation.dm
config/example/config.toml

Added a setting that gates random station traits on round start.
The setting is on by default, but disabled in the example config, to help test servers be more predictable.
I'm testing something with the NAD now, so I'll spawn as the Captain... and I'm drunk in AI upload. Great.
Started the game. Spawned as Captain at roundstart. Was in my office.
Edited the code to force hangover to be added "randomly" (by setting `force = TRUE`). Started the game again. Spawned as Captain at roundstart. Was in my office.
NPFC

Added a setting that gates random station traits on round start.

---

code/controllers/subsystem/SSdbcore.dm

Adds a check to prevent the database subsystem from attempting (and loudly failing) to run queries when the database isn't enabled.
A SQL error occurred during this operation, please inform an admin or a coder. xLOTS
ADMIN LOG: An SQL error has occurred. Please check the server logs, with the following timestamp ID: [2024-03-13T02:11:25] xLOTS
Toggled hearing instruments.
```
You will no longer hear musical instruments.
You will now hear people playing musical instruments.
```
No whining about SQL.
NPFC

Don't try to run queries when the database isn't enabled.

---

code/modules/paperwork/photography.dm

Fixes #24656. Adds opening span that I neglected to catch in #24257.
Fixes a bug.
Made sure the message did not have a big fat warning in front of it.
:cl: Chuga
fix: Burning photos no longer has a bugged message
/:cl:

Fixes #24656: corrects bad <span> when burning photos

---

code/game/objects/items/robot/robot_parts.dm
code/modules/mob/living/silicon/robot/!robot_mob.dm

If roboticists set locomotion to false on a cyborg frame, it partially set them to locked, which was really weird. This sets them to fully locked down.
bug bad
Code compiles
:cl:
fix: Disabling locomotion on a cyborg exoskeleton will now properly lock them down.
/:cl:

Fixes a problem with lockdown on borg exoskeletons

---

code/modules/surgery/organs/brain.dm
code/modules/surgery/organs/lungs.dm
code/modules/surgery/organs/organ_datums/lung_datum.dm
code/modules/surgery/organs/subtypes/tajaran_organs.dm
code/modules/surgery/organs/subtypes/unathi_organs.dm

Adds Heat and Cold tolerances to species lungs who are missing it. (Tajaran, Unathi, Drask, Ashwalker and Slime People)
Lowers Heat Tolerance Level 3 from 1000 to 460 to align with body tolerances.
Gives Drask Lungs a name instead of just being called lungs which no other species apart from Human have.
It's never really made sense to me why these species can't breathe what they can withstand or are just fine in these ranges where they wouldn't be able to.
Allowing species to breathe their suitable temperatures and take damage in areas that aren't adds more depth and helps to separate them from the rest of the playable species, it can be used in creative ways or even malicious ways to either add a bit to rounds or even change the course of them with enough imagination.
Meticulously checked …

Adjusts Species Lung Temperature Tolerances

---

code/modules/mob/living/simple_animal/hostile/headslug.dm

Makes the mob size of changeling headslugs small rather than normal. In practice, this has three effects.
- They can no longer open morgue trays and the like.
- They can only pull items of normal size or smaller.
- They can only pull mobs that are also small or smaller (So they can no longer pull humans.
- They can no longer strip mobs of their items.
Fixes: #24617
(I have more general issues with simple mobs being able to open morgue trays at all but that is out of the scope for this PR.)
As a headslug you are a slug; You should be fairly limited in what you can do since you are a small slug with no hands. This should making getting a new body at least slightly less trivial than just crawling into the morgue and opening a morgue tray.
Be a headslug.
Attempt to open a morgue tray, I …

[TWEAK] Makes headslug mob_size MOB_SIZE_SMALL

---

code/modules/mob/mob_misc_procs.dm

Fixes #12161.
This will also make bank accounts update properly when admins rename a player.
Consistency good.
Spawned as a clown, named myself Not A Clown.
Opened ATM.
"Welcome, Not A Clown"
:cl:
fix: Nanotrasen's accounting department has finally ruled that the clown and mime's chosen names can appear on their bank accounts.
/:cl:

Fix mime/clown picked names not being on their bank account.

---

code/modules/mob/living/silicon/pai/pai_death.dm
code/modules/mob/living/silicon/pai/pai_life.dm

Make pAIs show correctly in diagnostic HUDs
Fixes #5260
Bugs bad. Especially that terror spider..
Spawned a pAI, put it in mobile form.
Spawned a terror spider, gave it diagnostic HUD, used it to bite the pAI to death.
:cl:
fix: pAIs now show their health and status correctly in diagnostic HUDs.
/:cl:

Make pAIs show correctly in diagnostic HUDs

---

code/__DEFINES/mob_defines.dm
code/modules/mining/equipment/lazarus_injector.dm

Retaliate mobs no longer break stuff after revived with a laz injector.
Fixes #4152
Bugs bad. Except Araneus, she's nice.
Upset Araneus. She broke windows.
Revived her with a Lazarus Injector. She no longer broke windows.
:cl:
fix: Mobs that retaliate when attacked will no longer continue breaking terrain after being revived with a Lazarus Injector.
/:cl:

Retaliate mobs no longer break stuff after revived with a laz injector.

---

code/__DEFINES/is_helpers.dm
code/_onclick/adjacent.dm

Makes `/obj/item/Adjacent` handle if the item's `loc` is a structure or vehicle. This is to fix not being able to put items into trashbags if they're mounted on the `janitorialcart` or `janicart` (Fixes #24608). Examples of cases:
| Situation | Current behavior | With this PR |
|--------|--------|--------|
| Putting a pill into a pill box, inside a box | ✅ `Adjacent` for items inside items works | ✅ same behavior |
| Putting trash into trashbag, when mounted on `janitorialcart` | ❌ `Adjacent` for items inside structure doesn't work | ✅ now works |
| Putting trash into trashbag, when mounted on `janicart` | ❌ `Adjacent` for items inside vehicles doesn't work | ✅ now works | 
Makes the trashbag/janicart more intuitive to use, no longer needing to remove it from cart to discard trash.
Played …

Fix janicarts with trashbags mounted now accepting trash

---

code/modules/power/gravitygenerator.dm

Gravity generator for some reason has `interact_offline = TRUE` that makes it operational even without power after #24518. This PR brings the usual behavior back.
The generator works just like it has to.
Locally, fine.
:cl: Maxiemar
fix: Gravity generator is power-dependent again.
/:cl:

Make gravity generator power-dependent again

---

code/modules/mob/living/simple_animal/friendly/cat.dm

* Fixes #24365
* Fixes #24366
* Punishes anyone cruel enough to eat the last bite of Keeki with 5u of Teslium.
Bug fixes are good.
It's bad enough to kill Keeki, but you ate him completely?  You monster.
* Bit Keeki on harm intent, got reagents.
* Bit Keeki on disarm intent, got reagents.
* Almost ate up Keeki's corpse, revived him, killed him again, and took a few more bites without finishing him.
* Ate the last bit of Keeki.  Waited.   Bzaaaap.
:cl:
fix: Eating Keeki on disarm intent actually feeds you.
tweak: Eating a dead Keeki now gives nutrition, but there's only so much.
add: An unpleasant surprise awaits anyone who dares to eat the last bite of Keeki.
/:cl:

Made eating Keeki a bit smarter.

---

tools/ci/check_grep2.py

This PR makes all check_grep failures in a file be reported at the same time. It's also a bit smarter about running checks, running all the checks on a line at once rather than starting again at the beginning of a file for each check (although this hilariously doesn't seem to impact performance whatsoever).
Previously, check_grep2 would run each check on all the lines of a file, and if a failure was found, cut short and return that one failure. That meant playing whack-a-mole fixing one error, running check_grep2 again to find the next error, etc. Now it returns all failures, at once.
Here you can see the same type of failure is returned multiple times in a file:
Made several breaking changes, ensured check_grep2 found them.
NPFC

ci: check_grep now exhaustive

---

code/modules/mob/living/simple_animal/parrot.dm

Adds a check to parrots' Life to ensure their held item is still inside them. If not, un-holds it.
Fixes #7040
No, Poly, you can't keep holding the pAI card that unfolded and walked away.
Spawned parrot and pAI.
Parrot picked up pAI.
Unfolded pAI.
Parrot no longer holding pAI.
Also checked the supposed-duplicate #7053, but it seems to have been fixed independently.
:cl:
fix: Parrots can no longer violate the laws of time and space by holding an item they don't have.
/:cl:

Parrots no longer hold items they don't have.

---

code/game/objects/items/weapons/cigs.dm

* Cigars and pipes no longer REFUSE to be lit by stuff that can't light anything.
* Pipes will no longer REFUSE to be lit while simultaneously becoming lit.
* Renamed `can_light` to the more accurate `try_light`.
Fixed #6385, except for the FR to allow dried plants to be added.
Your cigar shouldn't refuse to be lit by a package wrapper, since the package wrapper probably wasn't trying to light it in the first place.
Got a pipe. Could not light it with a cheap lighter. Did nothing to it with my ID card. Lit it with a zippo.
:cl:
fix: Cigars and pipes no longer REFUSE to be lit by stuff that can't light anything.
fix: Pipes will no longer REFUSE to be lit while simultaneously becoming lit.
/:cl:

Cigar/pipe cleanup.

---

code/modules/food_and_drinks/food/foods/meat.dm
code/modules/surgery/organs/brain.dm
code/modules/surgery/organs/subtypes/standard_organs.dm

Refactors how monkey cube monkeys assign their name so that we no longer need specific overrides for monkey brain/head names.
Special cases are suboptimal.
Got a monkey and a stok from cubes.
EI NATH! EI NATH!
Got monkey and stock brains.
NPFC

Refactored how monkeys name their brains.

---

code/modules/admin/topic.dm

The admins' interface for updating the shuttle timer now takes input in units of minutes, not seconds.
Minutes are a more useful unit here, and math is scary.
Spawned as captain, opened comms console.
Admin-set the shuttle timer to 55 minutes.  To 6.5 minutes.  To -2 minutes (clamped to 0).
All changes reflected as expected.
:cl:
tweak: Admin controls now update the shuttle timer in units of minutes, not seconds.
/:cl:

Admin controls now update the shuttle timer in units of minutes, not seconds.

---

code/modules/mob/living/carbon/carbon_procs.dm

Checking yourself for injuries now uses the examine chat box. Also embedded items are now tabbed in, making it easier to differentiate them from the rest of the text.
Makes it easier to read it
See above
:cl:
tweak: Checking yourself for injuries is now in chatbox
tweak: Finding shrapnel in yourself when checking yourself for injuries will show it tabbed over
/:cl:

Checking yourself for injuries is now boxed

---

code/modules/economy/economy_machinery/account_terminal.dm

We used to print out a wrapped sheet of paper with account details when creating a new account, but it got lost in the economy rework. Re-added.
Fixed #22200.
You should have PIN access to a newly-created account.
Became HoP. Made definitely-not-illegal new account. Got nice printout. Was able to update PIN with the provided one.
:cl:
add: Re-added the account info printout on creating a new account at the Accounts Uplink Terminal.
/:cl:

Re-added the account info paper on creating a new account.

---

code/modules/mob/living/simple_animal/hostile/mining/gutlunch.dm

Changes the list of things gutlunches eat so they do not eat brains or implants by specifying exactly what organs they can eat.
Miners getting their brain eaten by gutlunches if gibbed by ashwalkers feels unnecessarily cruel given the gibbing alone tends to be a round removal. If a miner seeks to go out and recover their friend from an ashwalker, then damn let them have that cool story. Its a bit anticlimactic to see a weird lava planet spider ate your friends' brain after you go through all that effort to rescue them.
Tried to eat brains and implants, could only eat what I set to eat.
:cl:
tweak: Gutlunches will no longer eat brains and implants.
/:cl:

Gutlunches will no longer eat brains.

---

code/modules/projectiles/projectile/magic_projectiles.dm

This PR puts the text alerting people when they are transformed into either a xenomorph or a terror spider in a box.
This is important text, it's good to make it as noticeable as possible to avoid accidental bwoinks.
I turned myself into a spider and was astounded by the magic of rectangles.
:cl:
tweak: Transforming into a xenomorph or terror spider now has boxed text.
/:cl:

Adds a red box to some of the polymorph staff's transformation texts.

---

.github/workflows/merge_upstream_master.yml

Adds some level of security against people spamming our action workflows by skipping the run if not part of the repo org or the PR author.
The internet is full of horrible people, I was too innocent.

Restrict !merge_upstream workflow to dev team and PR author

---

code/game/verbs/ooc.dm

Fit Viewport now changes size of map window according to icon size thus removing black borders on the sides
More chat space. Also perfectionists should be happy
https://youtu.be/s-ZfJystP8A
Localhost
:cl:
tweak: Tweaked "Fit Viewport" to scale without black borders on the sides with different icon size
/:cl:

No more black borders on the sides with different size

---

.github/workflows/merge_upstream_master.yml

Fixes logic which prevents the PR's author from using `!merge_upstream`.
More convenient for PR authors.

Allow PR Authors to use !merge_upstream

---

code/modules/mod/mod_control.dm
code/modules/reagents/chemistry/reagents/drugs.dm

Brightenss the filter from mephedrone
Reduces the blur
Makes it more useable, less of a mess to see with
https://imgur.com/a/WaaItpY
See above, shrimple number change
:cl:
fix: Mephedrone has had it's blur and darkgreen changed to be less harsh
/:cl:

defogs mephedrone

---

code/game/objects/structures/window.dm

reinforced plasma windows (Stronger than fulltile non reinforced plasma windows) now require enviroment smash of breaking walls to instantly break.
This should make the loot in the crashed wizard ship reasonably getable
Reinforced plasma windows should be hard to break, especially when they are harder than plasma fulltile windows.
Clearing a ruing (Wizard ship) the intended way should not break loot
changed the value
:cl:
fix: reinforced plasma windows now have smash protection equal to walls
/:cl:

reinforced plasma windows now have smash protection

---

_maps/map_files/RandomRuins/SpaceRuins/whiteship.dmm
code/datums/ruins/space_ruins.dm
code/modules/shuttle/shuttle.dm

This PR remaps the "white ship", outfitting it for explorers redux. It provides lockers for storing salvage, an ersatz medbay, a properly functioning airlock, a handful of tools useful for space exploration -- station-bounced radios, flares, and glowsticks -- and most importantly, a recreation room for explorers to relax in between salvage runs.
This isn't meant to be a self-sufficient base for explorers, just a jumping off point for their work and a way to incentivize moving and working together through space.
The white ship is a relic of oldmapping. It's far too big for no reason. Its rooms only vaguely hint at their purpose, if they have any at all. Its airlock entrance is awful and is one of those places where atmos keeps pushes you out as you try to enter. It lacks personality.
This …

remap: white ship to explorer ship

---

_maps/map_files/generic/centcomm.dmm
code/game/gamemodes/game_mode.dm
code/game/objects/items/devices/uplinks.dm
code/game/objects/items/weapons/bio_chips/bio_chip_uplink.dm

Replaces the meeting room on the admin room with some wizard and syndicate equipment, as well as debug tools.
Replaces the no access requirement airlock on the admin shuttle with a window and a bit of fluff.
Makes the windows of the BSA room indestructible.
Makes uplinks placed down before gamemode is set not cause a runtime.
Players could theoretically get to the admin room on any round in which ERT was spawned. Admins can still teleport trough windows from the right click menu.
Players could either spacewalk to the airlock or abuse z level wrapping to get into the admin room. This fixes both cases, and replaces the very seldom used meeting room with a more practical testing area. 
BSA room windows are indestructible for consistency.
Players can still theoretically float about if they …

Improves the admin room

---

_maps/map_files/RandomRuins/SpaceRuins/mechtransport.dmm
code/datums/ruins/space_ruins.dm
code/game/area/areas/ruins/space_areas.dm

This PR remaps the "mech transport" space ruin, turning it into a more in-depth ruin with a bit more interactivity and exploration involved. The basic loot (the mech parts and secure crates) are unchanged.
**How it works:** There are two sets of blast doors: the lockdown blast doors, which seal off the factory floor and manager's office, and the secure storage blast door, which seals off all the loot east of the factory floor. All the blastdoors are impassible, so unless you want to deconstruct the walls, you'll have to replace the APC's cell with a charged one. Next to the APC is the switch for the lockdown doors. Once the power is online and lockdown is lifted, the player can enter the manager's office to open the blast door to the secure storage.
The lockers are empty but count as …

remap: mechtransport is now the Cybersun Exosuit Factory crashsite

---

_maps/map_files/Delta/delta.dmm
_maps/map_files/MetaStation/MetaStation.dmm
_maps/map_files/cerestation/cerestation.dmm
_maps/map_files/cyberiad/cyberiad.dmm
_maps/map_files/generic/centcomm.dmm
_maps/map_files/shuttles/emergency_raven.dmm

Fixes non raven shuttles not docking at CC
shuttles should worked
punched myself in the balls for 2 hours while looking at shuttle code.
looked for cramped shuttle for example of how a diffrent size worked.
cried as it cramped shuttle is WRONG and is horrible and not how it should be done
eventually realise that in order to make a *smaller* shuttle dock we need... for the docking port to be bigger.
:cl:
fix: Fixes non raven shuttles not docking at CC
/:cl:

Fixes non raven shuttles not docking at CC

---

code/__DEFINES/mob_defines.dm
code/game/dna/mutations/mutation_powers.dm
code/game/machinery/clonepod.dm
code/modules/mob/living/carbon/human/human_damage.dm
code/modules/mob/living/carbon/human/human_defense.dm
code/modules/mob/living/carbon/human/species/_species.dm
code/modules/surgery/organs/organ_helpers.dm
code/modules/surgery/surgery.dm

Changes the `isorgan()` define to `is_external_organ()`
Changes the `is_int_organ()` proc to a define `is_internal_organ()`
Adds 1 new define: `is_organ()`
I just spend 10 minutes debugging why `isorgan()` wouldn't say a fleshy mass was an organ, it's not an intuitive name.
It compiled, and I checked the diff twice
NPFC

Makes the `isorgan()` define more sane

---

code/_onclick/hud/map_popups.dm
code/_onclick/hud/plane_master.dm
code/modules/mob/mob.dm

fixes smoke not being partially see through with thermals / xray due to bad path
removes last trace of /obj/screen
bugs bad
code cleanup good
resolve: #24773 
see above
:cl:
fix: fixes smoke with xray or thermal vision
/:cl:

fixes smoke with xray or thermal vision

---

.github/workflows/merge_upstream_master.yml

- Changed curl call in "PR Data" step to send the response to a variable instead of to the file system(pr.json does not appear to be used elsewhere.)
- Added code to check whether the PR has "Allow edits and access to secrets by maintainers" checked. If not, then the action will comment `GitHub Actions can not push to the repository without "Allow edits and access to secrets by maintainers" checked.`. Demonstration https://github.com/ActionsProxy2/Paradise/pull/1#issuecomment-2016374088
- Optimized checkout to only fetch the commits needed.
- Fixed the avatar shown in the commit.
- Changed commit email from `github-actions@github.com` to `41898282+github-actions[bot]@users.noreply.github.com`. The latter email was extracted from a commit made by actions in the distant past. The ID does …

Subminute Upstream Merge & Add Comment for Access Denied

---

code/modules/supply/supply_console.dm

Fixes the Snappop shuttle always being available
bug bad
Looked at cargo, no snappop shuttle, cmagged the console, boom snappop shuttle
`Giggles says, "AI!! CALL SHUTTLE!!"`
:cl:
fix: Snappop shuttle is now properly locked behind cmag access. Mimes rejoice.
/:cl:

Fixes the Snappop shuttle always being available

---

code/game/dna/dna_modifier.dm
code/game/machinery/constructable_frame.dm
code/modules/research/designs/machine_designs.dm

Adds the DNA Modifier circuit board, allowing the DNA Modifier  to be rebuilt and to have new copies of it built.
Also removes some now deprecated code that interacted with cloning
It's weird that DNA modifiers have a cloner scanner board inside of it, especially because it doesn't allow it to be rebuilt now
Deconstructed a DNA Modifier, rebuilt it with what came out of the DNA Modifier
:cl:
add: Adds the DNA Modifier circuit board, printable at the same levels as a Cloning scanner (Programming 4 and Biotech 3)
fix: Fixed the DNA Modifier not being rebuildable after deconstructing it
/:cl:

Adds a DNA Modifier circuit board

---

code/game/machinery/vendors/departmental_vendors.dm

All of the seeds in the seed vendor now have a stock of 3, with the sole exception of strange seeds, which remain at 2.
Long, long ago, before Fox ported TG's botany in #6236, the seeds in the vendor were divided into two categories. The non-contraband seeds all had a stock of 3, and the contraband seeds all had a stock of 2. The port added two contraband seeds with a stock of 3, and much later, #22891 moved glowshrooms to the non-contraband section, while keeping their stock of 2.
You could argue several ways on what the "correct" number of seeds should be for each category, but I'm standardizing at the higher value of 3 for the simple fact that getting more seeds isn't hard, it's just a bit slow.
The only one I've left at 2 is strange seeds, because each of those is unique, so it would …

The seed vendor now has 3 of all seeds/mycelium except strange seeds.

---

code/_globalvars/lists/mob_lists.dm
code/modules/mob/dead/observer/observer_base.dm

Puts admins having antag HUD enabled round start into global list.
Shows 'poll candidates' alerts for admins even if they have enabled antag HUD.
Admins re-enabling their antag HUD makes it impossible for them to see and participate in candidate polls. I don't see any reason for this.
Having admins with antag HUD enabled in `GLOB.antag_hud_users` is just for consistency and some messages.
Tested locally.
:cl: Maxiemar
fix: Admins should see candidate polls in all circumstances from now.
/:cl:

Show poll alert for admins anyway

---

code/modules/mob/living/silicon/robot/robot_mob.dm

Fixed the cyborg skins from https://github.com/ParadiseSS13/Paradise/pull/24287 having wrong hat offsets
It is an oversight, caused by not adjusting the PR in time after the borg hats was merged.
- See image above
:cl:
fix: Fixed some cyborg skins having wrong hat offsets
/:cl:

Adjusts some borg hat offsets

---

code/modules/client/client_procs.dm

Fixes a math oversight that would subtract someone who wasn't counted as an online mentor/admin from the total of online mentors/admins, leading to a situation where we could report having -1 of either online.
Accuracy is good.
It compiled. I don't have a setup that would let me test it better.
NPFC

There can no longer be -1 admins/mentors online.

---

code/datums/status_effects/buffs.dm

Fixes a weird edge case with revs not being paralyzed while being protected by the de-rev'd status effect
Bug bad
See above
:cl:
fix: Fixes a weird edge case with revolutionaries when being de-rev'd
/:cl:

Fixes an issue with revs being de-rev'd

---

code/controllers/subsystem/SSeconomy.dm
code/modules/awaymissions/mission_code/ruins/oldstation.dm

The ancient space station's crew awakening alert now uses the correct game year and date.
Consistency is good.
Spawned as an observer, read paper.
:cl:
tweak: The ancient space station's crew awakening alert now uses the correct game year and date.
/:cl:

Updated the ancient space station awakening text

---

code/modules/power/cables/cable.dm
code/modules/power/cables/cable_coil.dm

White cables no longer spontaneously change color.
Fixed #7104
White is nice.
Spawned white cable. Placed wires. Got white wires.
Colored cable white with the mime's crayon. Same result.
:cl:
fix: White cables no longer spontaneously change color. When asked why he didn't tell us about this bug, the mime made a rude gesture.
/:cl:

White cables no longer spontaneously change color

---

code/modules/mob/living/simple_animal/hostile/megafauna/legion.dm
code/modules/ruins/objects_and_mobs/necropolis_gate.dm

It partially "carries over" [this](https://github.com/ss220club/Paradise-SS220/pull/872) PR from our downstream to fix an issue where miners use the Hirepohant club to kill Legion without any difficulties, because Legion couldn't leave Necropolis as the gates remained closed.
No abuse from miners with Hiero club
Tested in-game
:cl:
fix: Necropolis gate is now opens when Legion takes damage
/:cl:

Fix: Necropolis gate is now opens when Legion takes damage

---

code/modules/mod/mod_control.dm

Makes the modsuit control unit update it's icon state properly
Modsuit control unit should update when deploying
Deployed modsuit, also did testing with the cham module to make sure it still works
:cl:
fix: Fixes mod control icon being fucky when deploying
/:cl:

fixes mod control icon being fucky

---

code/__DEFINES/mappers.dm

This PR removes the custom names for directional mapping helpers.
This isn't really necessary since the type name now specifies the direction, and so we don't need to rename wallbumps after the fact.
Checked in-game, and in map editor, for any weird naming problems, saw none.
:cl:
fix: ATMs are now named correctly.
/:cl:

don't give directional mappers custom names

---

_maps/map_files/Delta/delta.dmm

This PR fixes Delta's whiteship docking port. I have no idea how long this has been broken but it hasn't been using the correct docking port subtype.
The whiteship should at the very least be able to dock near the station.
Spawned in, moved whiteship.
:cl:
fix: The whiteship can now properly dock near the NSS Kerberos.
/:cl:

delta: fix whiteship docking port

---

code/modules/reagents/reagent_dispenser.dm

Using the NAD on the beer keg nuke will cause it to explode in a shower of beer.
It's funny.
Used other objects, attacked normally.
Used NAD, got drunk.
:cl:
add: Some hooligan added a self destruct device to that beer keg we dressed up like the nuke. Fortunately, it can only be set off by the real nuclear authentication disk, and nobody would do that, right?
/:cl:

Make the nuclear beer keg react to the NAD.

---

_maps/map_files/cyberiad/cyberiad.dmm

This removes a duplicate prefab left over from when SOMEONE hand edited boxstation without properly letting git hooks run.
If I don't do this it'll show up in some other unrelated PR and confuse people.
No testing, YOLO
NPFC

box: fix duplicate prefab in janitorial

---

_maps/map_files/cerestation/cerestation.dmm

This PR fixes the northmost supply computer on Cere's bridge to be the proper permissions.
I should point out there already is one of these supply computers here:
but I guess I'm keeping both of them for the symmetry.
A public supply computer on the bridge is pretty useless since it can't approve requests.
Confirmed that a Command member could approve orders on the new console.
:cl:
fix: Farragus: The supply console on the bridge correctly allows Command order approval.
/:cl:

cere: bridge has correct supply computer

---

code/modules/tgui/modules/crew_monitor.dm

Fixes a UI state issue that seems to have been preventing non-admins from using the orbit button on the crew monitor.
Also, fixes the z-level dropdown to now properly show and switch between z-levels.
Fixing bugs on a recent PR, good to have this work in the way that it should.
Loaded in, tried the orbit stuff
:cl:
fix: Switching between z-levels on the observer and CC crew monitors should now work properly.
fix: Observers should now be able to properly use the orbit button on the observer crew monitor.
/:cl:

Fix bugs with observer crew monitor

---

code/game/objects/items/weapons/weaponry.dm

Returns sord item icon
No invisible items
Hi Henri
:cl:
fix: Fixed missing SORD sprite
/:cl:

Sord missing icon fix

---

code/datums/uplink_items/uplink_general.dm
code/game/objects/items/weapons/bio_chips/bio_chip_adrenalin.dm
code/game/objects/items/weapons/bio_chips/bio_chip_fluff.dm

Adds the Proto-Adrenaline Bio-chip. 18 Tc. Acts like adrenals in unstuning you and healing stamina, and grants 1 unit of changeling antistun chemical, same as the changeling overdose. No speed. No healing. Only a few short precious seconds of antistun. Enough to get you out of a stun and survive one extra baton hit, but nothing more. 1 use.
The adrenals tax is real. Freedoms are nice, but you are not always going to be cuffed, or waiting to be cuffed will make the situation much worse.
This implant ensures to you a stamina crit will not be the end, but will not require you to be lethaled, nor will it let you dunk an entire security team. It will allow you to get one extra time, or to start running away again, activate an item, or something else.
It will also hopefully add some nice …

Adds the Proto-Adrenaline Bio-chip

---

code/modules/food_and_drinks/kitchen_machinery/kitchen_machine.dm

Makes the damp rag able to clean dirty kitchen machines.
The chef doesn't get screwed over from random people breaking into the kitchen and making the machines unusable and undisassembleable or through their own error.
The fact that the chef doesn't have equipment to clean their cooking machines is pretty weird considering that no real kitchen would be without these things.
Became chef, made tons of burned mess, cleaned my microwave with rag.
:cl:
tweak: The damp rag can clean dirt from kitchen machines.
/:cl:

Damp rags can clean dirty kitchen equipment (just like they do it in real life)

---

code/modules/error_handler/error_handler.dm
code/modules/error_handler/error_viewer.dm

`DEBUG: Runtime in code/modules/error_handler/error_handler.dm,154: Division by zero`
is now
`DEBUG: Runtime in code/modules/error_handler/error_handler.dm:154: Division by zero`
Paraphrased from AA: "Kibana only touches the full runtime.log", so all of the runtime logging locations except for writing to that one have been changed. It will stay this way unless "unless Denghi can edit the pipeline beforehand to allow file,line as well as file:line"
By changing the comma to a colon between the filename and line number, it makes it much easier to copy paste the error into VSCode to search for the line on which the error occured.
NPFC

Slightly modifies the logging of runtimes

---

code/game/jobs/job_globals.dm
code/game/objects/items/weapons/cards_ids.dm
code/modules/admin/db_ban/functions.dm
code/modules/admin/topic.dm
code/modules/client/client_procs.dm
code/modules/unit_tests/_unit_tests.dm
code/modules/unit_tests/jobs/test_job_globals.dm

Fixes #24774: Removes duplicate **Head of Personnel** value from `GLOB.service_positions` (HOP showed up twice on ID computer), adds sanitizing for `job_globals` values via unit-test.
Fixes minor oversight, hopefully prevents it from happening again in the future.
HOP no longer listed twice in ID computer:
Added unit-tests for sanitizing `job_globals` values, checked ID Computer again and verified it was fixed.
:cl: Zantox
fix: HoP job no longer listed twice in Identification Computer
/:cl:

Add job_globals sanitization, fix duplicate value

---

code/modules/tgui/tgui_input/alert_input.dm
code/modules/tgui/tgui_input/list_input.dm

fixes tgui alerts taking WAY longer than they should to delete
Before: Around ~25MS to delete
```
[2024-03-28T19:14:18] Path: /datum/tgui_list_input
[2024-03-28T19:14:18] 	qdel() Count: 164
[2024-03-28T19:14:18] 	Destroy() Cost: 4057.33ms
```
After:
GC GO VROOM
This is the highest qdel cost atm
see above for a screenshot
NPFC

fixes tgui alerts taking WAY longer than they should to delete

---

code/modules/mob/living/simple_animal/hostile/mining/elites/elite.dm

Fixes an issue with elites that emerged after https://github.com/ParadiseSS13/Paradise/pull/24482 which borked elite's action buttons.
Elites are pretty messed up right now, let's fix that.
Loaded in as an elite, things worked again.
:cl:
fix: Fixes a bug that made elites nearly unplayable.
/:cl:

Fixes elite action buttons breaking entirely

---

code/game/objects/items/stacks/medical_packs.dm
code/modules/surgery/generic.dm
code/modules/surgery/organs/blood.dm

Gauze will not work if any limb is open
Bleed suppression removed on surgery start
Gauze doesn't work on open limbs and should not stop open limbs from bleeding.
As per above, if one gets their limbs opened, gauze should no longer prevent open limbs from bleeding
cut skrells, with gauze before / after
:cl:
fix: Gauze will not work if any limb is open
fix: Bleed suppression removed on surgery start
/:cl:

[s] Tis just a flesh wound

---

.github/workflows/label_stale.yml
.github/workflows/merge_upstream_master.yml
.github/workflows/render_nanomaps.yml

Current stale labels are applied if and when a maintainer realises any given PR or issue is stale, this makes the process fairer for all by automating it based on certain rules.
PRs are marked as stale after 14 days of no activity (comments or commits) unless they have the labels `"Stale Exempt", "-Status: Awaiting approval"`. They are then closed after a further 7 days of no activity.
Issues with the labels `"Need Verification", "Cannot Reproduce", "Not A Bug", "(99% Sure) Not A Bug"` are marked as stale after 60 days of inactivity, and close after a further 14 days of inactivity.
Comments are left by the bot at all stages to keep users informed.
I also tidy up existing workflows to better manage how we sort github tokens.
The `!merge_upstream` workflow also has:
Likes the requesting …

Adds workflow for automatic handling of stale PRs and issues, tidies other workflows and adds better logging

---

code/datums/mind.dm

Fixes a call that was supposed to include a mind to include the mind.
Runtimes suck, doubly so when they spoil the gamemode to admins.
It compiled.
NPFC

Don't runtime when creating nukies.

---

code/game/objects/structures/grey_autocloner.dm

Made the gery autocloner work properly on greys.
In delicious irony, #24038 made everyone using the grey autocloner become greys, except greys, who became human.
Fixed #24862.
While this is also funny, the grey autocloner should probably, you know, work correctly on greys.
Spawned as grey.
Made autcloner.
Implanted self.
Died.
Revived as grey.
Became human.
Implanted self.
Died.
Revived as grey.
:cl:
fix: The greys' infiltration project has completed, so they no longer become semi-human when using their advanced cloning system. This was definitely intended, and in no way a flaw in their advanced technology.
/:cl:

The grey autocloner now works properly on greys

---

code/game/area/areas.dm

This PR removes an unused variable from `/area`.
Unused variables bad.
Searched codebase, found no instances of use. Built project, saw no errors.
NPFC

refactor: remove unused var /area/no_air

---

code/modules/clothing/shoes/misc_shoes.dm

Clown shoes can be washed with a crayon to disguise them as normal shoes.
This was most likely originally a bug, but got documented on the wiki as a feature back in 2017. At some point in the intervening years, the bug was unintentionally fixed, and the "feature" went away.
This intentionally reinstates the prior behavior, which was kinda funny.
Washed clown shoes with an orange crayon. Got ordinary-looking orange shoes that squeak.
Washed all the clown shoe subtypes that could be placed in the washing machine with a red crayon. No change to any of them.
:cl:
add: Clown shoes can be washed with a crayon to disguise them as normal shoes.
/:cl:

Disguised clown shoes.

---

code/modules/reagents/reagent_containers.dm

Cyborgs with reagent container modules (currently service and medical) can now set transfer amounts on them.
Fixes #23824
The examine text said you could, and it really didn't make sense that a cyborg couldn't control their own modules.
Became human. Set transfer amount on a bucket.
Walked away. Could not set transfer amount.
Handcuffed myself. Could not set transfer amount.
Became corgi. Could not set transfer amount.
Became human again. Tried to set transfer amount, walked away before finishing. Failed to set.
Tried to set transfer amount, handcuffed self before finishing. Failed to set.
Tried to set transfer amount, became corgi before finishing. Window closed, couldn't even try to set.
Became mediborg. Was able to set transfer amount on beaker and dropper while in hotbar.
Became …

Allowed cyborgs to set transfer amounts on their modules.

---

code/game/gamemodes/game_mode.dm
code/modules/mob/living/living.dm

An S-GBS Outbreak has been detected at this Nanotrasen Station!
(Gives everyone a modfified version of the gib-self verb).
Captain also gets an alert of the S-GBS outbreak
yes
yes
:cl:
experiment: An S-GBS outbreak has been detected on station. Ask your captain for more details!
/:cl:

[AFD] WARNING: S-GBS OUTBREAK DETECTED

---

code/__DEFINES/tickets_defines.dm
code/controllers/subsystem/tickets/mentor_tickets.dm
code/controllers/subsystem/tickets/tickets.dm
code/modules/admin/topic.dm
paradise.dme

Adds an autoresponse system to mentorhelp, directly equivalent to the adminhelp version, but with a different set of messages.  It uses the existing (AUTO) button.
Autoresponses are useful for mentors, too!
Filed a mentor ticket.  Gave a couple autoresponses.
Filed an admin ticket.  Gave a couple autoresponses. 
:cl:
add: Mentors now have some canned responses for common mentorhelp situations.
/:cl:

Added an autoresponse system for mentorhelp, using the existing button.

---

_maps/map_files/RandomRuins/SpaceRuins/whiteship.dmm
_maps/map_files/shuttles/emergency_raven.dmm
code/game/shuttle_engines.dm
code/modules/awaymissions/mission_code/ruins/oldstation.dm
code/modules/shuttle/shuttle.dm
code/modules/shuttle/shuttle_rotate.dm

Fixes multitile doors and multitile engines on shuttles. Also pods if they existed still.
Grants the NTSS Raven it's large engines it was intended to have, but I removed when porting due to the bug that this fixes.
Fixes #24610
Bugs are bad.
More creative shuttles with huge engines good.
Raven having big boy engines is good.
example on discord
:cl:
tweak: Gives NTSS Raven it's big engines back, gives whiteship multi tile cockpit per request
fix: Fixes multitile doors and multitile engines on shuttles.
/:cl:

Fixes multitile doors and multitile engines on shuttles. Gives raven it's big engines back

---

code/game/objects/structures/window.dm
code/game/turfs/turf.dm
code/modules/atmospherics/environmental/LINDA_system.dm
code/modules/atmospherics/environmental/LINDA_turf_tile.dm

Adds superconductivity blocking to fulltile plasma windows.
Corrects a related typo.
The SM should not leak heat. Fulltile plasma windows shouldn't be worse than their directional versions.
Varedited a suncan. Surrounded it with fulltile basic and reinforced plasma windows. Opened it. Successful containment.
:cl:
fix: Fulltile plasma windows will no longer leak heat.
/:cl:

Adds superconductivity blocking to fulltile plasma windows.

---

code/_onclick/hud/action_group.dm
code/datums/action.dm
code/game/objects/items.dm

Removes some code treating actions as a lazy list, and instead just treats it as a normal list. This fixes some runtimes that have sprung up due to how actions get deleted.
This is a micro-optimization that honestly feels like it causes more trouble than it's worth. Let's just do this and leave it as-is.
Fewer runtimes good, especially if they cause particularly nasty effects.
Compiled, verified that actions were still added and removed.
:cl:
fix: Action buttons are less likely to cause issues when being removed from you.
/:cl:

Removes code treating actions as a lazy list

---

_maps/map_files/generic/centcomm.dmm

This PR removes cables from mech charging stations on Gamma armory shuttle and in admin areas. These are `/obj/machinery` subtypes which means they already enjoy the advantage of being in areas with `requires_power` set to `FALSE`. In removing these cables, we're removing 5 redundant regional powernets.
Unnecessary powernets being processed is bad.
Spawned in, removed cell charge from mechs in bay, watched cells recharge.
NPFC

centcom/admin: remove unnecessary powercables/powernets

---

code/modules/events/spacevine.dm

Kudzu no longer mutates at 0 potency, despite not mutating at 1 potency.
Fixed #15985
0 shouldn't be magically *more* mutating than 1.
Planted kudzu with 0 potency. 0 mutativeness.
Planted kudzu with 1 potency. 0 mutativeness.
Planted kudzu with 10 potency. 1 mutativeness.
:cl:
fix: Kudzu no longer mutates at 0 potency, despite not mutating at 1 potency.
/:cl:

Fixed kudzu mutativeness at 0 potency.

---

code/modules/reagents/chemistry/reagents/toxins.dm

This PR removes the faulty math that makes beer2 metabolize at 0.04 units per life(). Fixes #17462
Apparently this was a bug the whole time, it was intended to have the same metabolism rate as cyanide. 1 sip still knocks out, and 2 sips still easily kills.
Forced a skrell to drink beer2 and watched their health/reagents tick down correctly.
:cl:
fix: Beer2's metabolism rate is up to .1u
/:cl:

Fixes beer2's extra-low metabolism rate

---

code/datums/status_effects/debuffs.dm

pepperspray confusion no longer infinitely stacks. now stacks to a cap of 20 seconds.
Not capping it leads to situations where someone ends up with an ungodly amount of confusion that frankly sucks. This also makes pepperspray less of a crapshoot to use by proxy. 
peppersprayed the fuck out of a skrell
:cl:
tweak: pepperspray confusion no longer infinitely stacks. Stacks to 20 seconds now
/:cl:

pepperspray confusion no longer infinitely stacks

---

code/controllers/subsystem/SSticker.dm
code/modules/admin/misc_admin_procs.dm

Pressing Delay before setup finishes will no longer cause the round to start instantly when it finishes loading.
If the round start is delayed, Start Now will prompt the admin to undo that first.
Fixes #24788.
Admin verbs should do what they sound like they do, not nothing, and definitely not the exact opposite.
Started server.
Delayed round start before init finished.
Init finished.
Round was delayed.
Tried to start the round while it was delayed.
Was told not to be silly.
Un-delayed the round start.
Game didn't start yet.
Force-started.
Game started.
LGTM
:cl:
fix: The admins' Delay verb now works correctly before server startup finishes.
fix: Admins' Start Now verb will no longer silently fail while the round start is delayed.
/:cl:

Make Delay saner.

---

code/modules/food_and_drinks/recipes/recipes_grill.dm

Removed the requirement for 1 metal rod from BBQ ribs.
The metal rods are silly. They do not get consumed in the recipe, and eating the ribs does not return a rod with which to hit yourself when you scarf it down too fast (unlike skewers).
Cooked rodless BBQ ribs.
:cl:
tweak: BBQ ribs no longer require a metal rod to cook.
/:cl:

BBQ ribs no longer require rods

---

code/modules/mob/living/living_status_procs.dm

Transient status effects now have a default upper bound of 5 minutes
we have adjust druggy and other kind of status effects just kind of sitting around the codebase with no upper limit. this prevents situations where you literally can't get rid of it.
Made sure Afreeze worked fine with these changes
:cl:
tweak: Transient status effects now have a default upper bound of 5 minutes
/:cl:

Transient status effects now have a default upper bound of 5 minutes

---

code/modules/admin/verbs/adminsay.dm

Corrected over-escaping that lead to HTML gibberish in #msay and, presumably, its admin equivalent..
`People shouldn&#39;t have to interpret &#34;useful&#34; HTML codes.`
It compiled, but I don't have a setup that lets me test it.
NPFC

Removed #msay (+#asay?) gibberish

---

code/modules/mob/living/brain/robotic_brain.dm

title
Non-sapient is the correct word choice here, as non-sentient implies robobrains are physically incapable of thinking about their actions.
- got in game
- looked at brain
:cl:
tweak: Updated robobrain description
/:cl:

Updates robobrain description

---

code/modules/mob/living/carbon/human/human_defense.dm

Adds a check to pick a random existing bodypart from the victim if the targeted limb is missing (i.e. whacked off). This should make melee combat against IPCs a little bit less clunky.
Knocking somebody's head off should probably not make the rest of your attacks in the area enter the void, given how clunky it is to hotswap body zone targeting.
Disassembled several skrell. I can't think of any specific edge cases of attackby that could be affected by this, but please let me know if there is one.
:cl: Chuga
fix: Attacking a missing limb now chooses a random body part instead of not working.
/:cl:

Attacking a missing limb instead chooses a random body part

---

code/__HELPERS/pronouns.dm
code/__HELPERS/unsorted.dm
code/game/objects/explosion.dm
code/game/objects/items/weapons/grenades/frag.dm
code/game/objects/items/weapons/tanks/tanks.dm
code/modules/mob/living/carbon/human/human_defense.dm
code/modules/mob/living/carbon/human/human_examine.dm

If you've ever played CM, you've may have realized how boring the rest of SS13's explosions are, wheres all the PIZAZZ?
This PR implements CM-style fragmentation explosions, which throw shrapnel everywhere, and will embed in any targets that it hits within 5 tiles. These are given to the frag grenades, which contain 20 shrapnel projectiles.
Leaping and laying on top of a source of shrapnel will cause you to take all of the shrapnel (maybe you'll save a bystander?). Standing over a grenade will also have 50% of all the shrapnel hit you.
This PR also makes shrapnel read as "some shrapnel" instead of "the shrapnel"
Previous frag grenade code literally just found everyone within 5 tiles, and put shrapnel in them, thats BORING, lets add some SKILL (if you can move fast enough to dodge the …

Frag grenades now explode into proper projectiles

---

code/modules/antagonists/changeling/datum_changeling.dm
code/modules/antagonists/changeling/powers/shriek.dm

Revives #24391
Increases Dissonant Shriek by 2.5x on Cyber Revo rounds.
All other EMP items cost more - this should be no different.
With the Cyberrev trait
Without the Cyberrev trait
See above
:cl:
tweak: Dissonant Shriek costs 2.5x more on Cybernetic Revolution Rounds.
/:cl:

Increases EMP Shriek Price on Cybernetic Revolution Rounds

---

code/modules/clothing/head/misc_special.dm

Title. Stops cardborg helmets from protecting against facehuggers
They're easy to mass produce. They shouldn't protect against facehuggers.
Checked if they protected against facehuggers
:cl:
tweak: Cardborg helmets now no longer protect against facehuggers
/:cl:

[s] Makes cardborg helmets not protect against facehuggers

---

code/__HELPERS/text.dm
code/game/gamemodes/miniantags/pulsedemon/pulsedemon.dm
code/game/machinery/computer/communications.dm
code/game/objects/items/devices/radio/radio_objects.dm
code/game/objects/items/devices/voice_changer.dm
code/modules/admin/topic.dm
code/modules/admin/verbs/pray.dm
code/modules/events/blob/overmind.dm
code/modules/hydroponics/seeds.dm
code/modules/mob/dead/observer/observer_base.dm
code/modules/mob/living/carbon/carbon_procs.dm
code/modules/mob/living/carbon/human/human_say.dm
code/modules/mob/living/living_say.dm
code/modules/mob/living/simple_animal/friendly/dog.dm
code/modules/mob/living/simple_animal/parrot.dm
code/modules/mob/living/simple_animal/simple_animal.dm
code/modules/mob/mob.dm
code/modules/mob/mob_say_base.dm
code/modules/mob/mob_vars.dm
code/modules/ruins/ghost_bar.dm
code/modules/station_goals/station_goal.dm

1. Corrects a bunch of over-escaping that led to HTML code appearing in various places.
2. Permits ghosts and ghost bar occupants to use symbols banned from IC speech (e.g. >), with proper escaping.
3. Permits emotes to use symbols banned from IC speech (e.g. >), with proper escaping.
The only place that actually removed escaping entirely was the admin-only fax creation interface, because it had falsely claimed to allow HTML in its message. Happy to change the message instead if we're not comfortable with that.
Known limitation: The right click menu and alt-click view still show HTML escapes.
Fixed #23360
Fixed #23759
The over-escaping just looks ugly and makes it harder to read stuff.
Ghosts aren't IC and shouldn't be bound by IC rules.
Emotes aren't spoken, so there are reasonable uses …

Corrected a bunch of over-escaping.

---

code/datums/keybindings/movement_keybinds.dm

makes direction lock no longer a default bind
so this is bound to ctrl, a very commonly used keybind for pulling things. most people end up unbinding this instantly so they don't get locked in place when they're trying to pull something. either way having an "unbind instantly" keybind ain't great.
:cl:
tweak: Direction lock is no longer binded to ctrl by default
/:cl:

makes direction lock no longer a default bind

---

code/modules/reagents/reagent_containers/hypospray.dm

Adds the ability to rename a hypospray with a pen. It'll mark it as "hypospray - label"
Keeping track of hyposprays is a pain in the ass. While you can use a hand labeler, those aren't always super readily available. This should help you keep tabs on which is which without a reagent scanner.
Loaded in, tried to rename the hypospray, was able to.
:cl:
add: You can now rename hyposprays with pens and other writing utensils.
/:cl:

Lets you rename a hypospray with a pen.

---

code/modules/surgery/organs/organ_external.dm

Fixes #24563 by adding a missing return.
Bugs are bad
Chopped an IPC's arm off and I was able to reattach with no screwdriver
:cl:
fix: Reattaching IPC limbs no longer requires a screwdriver
/:cl:

Fixes attaching robotic limbs requiring a screwdriver to start the surgery

---

_maps/map_files/stations/metastation.dmm

This PR removes CT access from the mining dock on Meta. Fixes #24976.
Access fix.
Spawned in as CT, checked I couldn't enter mining dock.
:cl:
fix: Cerebron: Cargo Techs no longer have access to the mining dock.
/:cl:

meta: remove CT access from mining dock

---

code/game/machinery/spaceheater.dm
code/game/objects/structures/noticeboard.dm

This PR removes some Russian text from the Noticeboard and Space heater GUI titles. These were just "panel" and "notices" translated.
English
Forgive me if I assume this just works
:cl:
fix: Some Russian text has been removed from the Noticeboard and Space Heater GUIs.
/:cl:

remove russian from some GUI titles

---

_maps/map_files/RandomRuins/LavaRuins/lavaland_surface_hermit.dmm

This PR adds no-lava helpers around the entrance to the hermit shelter and shuttle. It also adds some rock around the square border of the ruin to make it a bit more organic-looking when being placed.
**Note that the lava under the shuttle and shelter corners is an icon-smoothing problem, _not_ a procgen problem.**
The hermit should be able to exit their shelter. While it is possible for them to mine around it, this sucks the atmosphere out of their cavern which would be a bad idea IC. Also, they must have been able to walk to these areas to create the shelter in the first place. This is still a pretty precarious setup since there's only a few thin tiles between the shelter and the external rock.
<details><summary>SDMM screenshots</summary>
</details>
<details><summary>In-game …

add no-lava helpers to hermit ruin

---

.gitignore
.vscode/launch.json

Adds launch.json to vscode folder.
That's allow you to start debugging (F5) in any file, not only into dm/dmi/dmm
Dev comfy
https://github.com/ParadiseSS13/Paradise/assets/69762909/af0a070e-590b-4613-97d0-cc274ea085ac
Above
NPFC

Debug on F5 regardless of file extension

---

code/game/turfs/simulated/floor/asteroid_floors.dm

This PR does a few more checks in Lavaland cave generation for ruin areas.
Ruin areas should be basically guaranteed not to be overwritten by procgen.
Using the hermit ruin as an example
Not a bad spawn in sight
See above
:cl:
fix: Lavaland tunnels are now less likely to overwrite ruins.
/:cl:

fix: do more ruin checks for lavaland procgen

---

code/_onclick/hud/action_button.dm

fixes https://github.com/ParadiseSS13/Paradise/issues/24895
Fixing bugs good
MODsuit checked
:cl:
fix: MMB-ing action buttons now is different again from LMB-ing them
/:cl:

Clicking Action-Buttons now checks if it's left-click

---

code/modules/clothing/under/accessories/accessory.dm

Fixes a runtime if you don't have an organ with a heart datum attached to it
Less runtimes is good, also this proc was a literal sin against our standards
See above
NPFC

Fixes a runtime with the stethoscope and missing hearts

---

code/modules/admin/topic.dm
code/modules/admin/verbs/adminpm.dm
code/modules/station_goals/secondary/secondary_goal.dm
code/modules/station_goals/station_goal.dm

Corrects a couple places in Modify Station Goals where "or null" was being specified wrong for `input()`, leading to a missing cancel button.
Added admin logging to all Modify Station Goals actions.
Better admin tooling is good.
Added, modified, and removed some goals.
:cl:
tweak: Modify Station Goals now has more cancel buttons and admin logging.
/:cl:

Added cancel buttons and logging to Modify Station Goals

---

tgui/packages/tgui-dev-server/reloader.js

- Added a try-catch around the code which reloads BYOND clients so that when one disconnects during the reload, the dev server doesn't crash
Reduces time wasted having to wait for dev server to restart because it failed a fetch request
1. Opened DreamSeeker
2. Opened tgui-dev-server
3. Disconnected DreamSeeker
4. Immediately hit save on a random tgui interface file
5. tgui-dev-server should print error but not crash

Fix tgui-dev-server crashing when reloading clients shortly after one disconnects

---

code/modules/lighting/lighting_source.dm

if a lighting object has no attached target we throw a stack trace now
We need to figure out why this error has been happening
I can't, we don't know what causes it

throw a stack trace if a light has no source atom

---

code/game/machinery/machinery.dm
code/game/objects/items/weapons/stock_parts.dm

Adds beaker support to RPEDs.
Deletes an unused RPED-related proc.
The three main-line beakers are functionally stock parts, just not type-wise. This makes them act that way with the RPED.
Spawned a preloaded bluespace RPED. Upgraded ChemMaster and Autolathe.
Spawned a normal bluespace RPED. Picked up a stack of all beaker subtypes, only got normal, large, and bluespace. Upgraded another ChemMaster and Autolathe.
Added all the other T4 parts to the bRPED. Upgrade another ChemMaster and Autolathe.
Emptied bRPED. Added all T4 parts to the bRPED. Added all three mainline beakers in opposite order. Upgrade another ChemMaster and Autolathe.
Tried picking up an empty and filled beaker in a few combinations. Sometimes didn't get either, but never got the filled one.
:cl:
add: RPEDs can now pick …

Added beaker support to RPEDs.

---

code/game/machinery/clonepod.dm

Makes the switch statement in the `process()` of the cloner decimal proof
Resolves #25072
The cloner shouldn't be stuck because some scientist loaded in a rating 4 and rating 3 manipulator in the cloner
Cloned myself, set progress to 10,5 , it happily went to 11,5.
Set progress to 150, still completed
:cl:
fix: Fixed the cloner randomly stopping sometimes
/:cl:

Makes the cloner not stop at 10,5 %

---

code/_onclick/adjacent.dm
code/_onclick/click.dm

Adds some safety to prevent a runtime when clicking an item that just got deleted.
Runtimes bad.
Spammed a hatchet on a bamboo log, no runtime.
NPFC

Fix runtime when clicking an item that just got deleted.

---

code/__HELPERS/unsorted.dm
code/game/area/areas.dm

Baseturf helpers are completely broken, I daresay the all_areas list turns out to be empty, during the initialization of the helper
Soo... i steal TG solution
Closes #25085 <details><summary>(yeah, selfclosed)</summary> ![image](https://github.com/ParadiseSS13/Paradise/assets/69762909/927532eb-8b8e-4e4b-b06e-b5f93f999ab7) </details>
No space holes on lavaland
Can i just remove this section, Henri?
:cl:
fix: Space should no longer appear on lavaland, for now
/:cl:

Baseturf helpers fix

---

_maps/map_files/generic/centcomm.dmm
code/game/machinery/door_control.dm
code/game/objects/structures/crates_lockers/closets/secure/guncabinet.dm

The button allowing access to the CC armory from the OUTSIDE has been changed to prevent cyborg usage. The gun cabinets in the armory now require NNO/SOO access to open. Additionally, the CC engineering bay, and CC bridge now require an NNO/SOO to open, and cannot be opened by cyborgs.
Admins should not need to stand by with a taser when they spawn an ERT with a cyborg to prevent the ERT from equipping themselves with gamer gear. This PR secures that button, as well as secures the cabinets in the armory if the blast door is somehow opened.
Confirmed button was gone. Confirmed station AA could not open cabinets/shutters. Confirmed borgs can not open shutters via buttons. Confirmed ERT cannot open cabinets/shutters. Confirmed SOO/NNO CAN open the cabinets/shutters. 
:cl:
tweak: Increased …

Increases security of CC armory

---

code/__DEFINES/chat_box_defines.dm
code/controllers/subsystem/tickets/mentor_tickets.dm
code/controllers/subsystem/tickets/tickets.dm
code/modules/admin/misc_admin_procs.dm
code/modules/admin/verbs/adminhelp.dm
code/modules/admin/verbs/adminpm.dm

Consistently textboxes ahelps (red) and mhelps (blue).
Consistently includes links for mentors/admins, including a link to the ticket (replacing the equivalent but less-useful window link).
Makes mhelps use a less jarring sound effect; no more scaring the people we teach.
QOL changes are good. Scaring mentees is bad.
Sent a bunch of ahelp and mhelp messages to myself.
:cl:
tweak: Admin helps and mentor helps are now consistently put in a text box.
tweak: Mentors and admins now consistently get links on ahelp and mhelp messages, including a link to the ticket (replacing the equivalent but less-useful window link).
soundadd: Mentor helps now use a less jarring sound effect. The bwoink is dead, long live the bedodoop.
/:cl:

Ahelp and Mhelp QOL 2

---

code/modules/awaymissions/mission_code/ghost_role_spawners/golems.dm
code/modules/mob/living/brain/robotic_brain.dm

Robobrains now do the standard alert popup when activated instead of using a chat hyperlink
Robobrains are first come first serve like most other spammable ghost roles. (same method as golems/terrors for example)
We do this for everything else but PAIs let's just let them get in the round in a normal way
Polled then spawned in as a robobrain
:cl:
tweak: Robobrains now do the standard alert popup when activated instead of using a chat hyperlink
tweak: Robobrains are first come first serve
/:cl:

improves robobrain spawning

---

code/modules/atmospherics/machinery/components/unary_devices/thermomachine.dm

Thermomachines can no longer work backwards, heating while cooling, or cooling while heating.
Fixed #24419
Don't do the opposite of what you say.
Heated a pipe,  lowered heating temp, pipe didn't cool.
Repeated the other way around.
:cl:
fix: Thermomachines can no longer work backwards, heating while cooling, or cooling while heating. You can actually turn them on in the SM setup without making things actively worse!
/:cl:

Thermomachines can no longer work backwards.

---

code/modules/mob/living/simple_animal/friendly/bunny.dm

Allows the bunny mob to ventcrawl, fixes #24174
Fixing issues good, allowing to player to roll as a sentient mob but not letting them escape the room they are in is bad
https://github.com/ParadiseSS13/Paradise/assets/13879982/021d914f-8bdb-4958-b1ec-853a93f0ef71
Loaded game, became bunny, scurried into the vent.
:cl:
tweak: Bunny can now ventcrawl
fix: Fixed Spaghetti not being able to escape atmos when rolled as a sentient mob on Farragus
/:cl:

Bunny can now ventcrawl

---

code/modules/antagonists/vampire/vampire_powers/vampire_powers.dm

Changes vampire glare to apply the full stun to a person who is on the same tile as you, instead of a partial stun.
It's kind of lame that currently, the best strategy for avoiding the second glare is to just crawl under the vampire, as the vamp has to then move away, face the right direction, and press the glare button.. at which point the person has had time to crawl under them again. Having your only stun get potentially avoided in such a counterintuitive manner doesn't seem great.
Also discussed this with the balance team before making this PR, and they seemed on board with it.
Glared a fool.
:cl:
tweak: Vampire glare now fully affects people on the same tile as the vampire
/:cl:

Vampire glare now fully affects people on the same tile as the vampire

---

code/modules/projectiles/guns/syringe_gun.dm

Makes the blowgun only do stamina and oxy damage if there's actually something in it
Haha spamclick into instant death goes brrrr
Tried to spamclick, only heard clicks and no deathgasps
:cl:
fix: Fixed the blowgun dealing oxy damage when you tried to fire an empty one
/:cl:

Fixes the blowgun being an excellent suicide method

---

code/datums/elements/strippable.dm
code/datums/uplink_items/uplink_traitor.dm
code/modules/mob/living/carbon/carbon_stripping.dm
code/modules/mob/living/carbon/human/human_stripping.dm

Fixes stripping of non-pocket items while having pickpocket gloves not being silent. Also, pickpocketing will put it items in your hands again.
Fixes #25073.
Oversight bad
Stripped someone without pickpocket gloves, got messages and it got dropped to the ground
Stripped someone while wearing pickpocket gloves, it was silent and I picked up their stuff
:cl:
fix: Fixes pickpocket gloves not being silent when stealing from non-pockets
fix: Fixes pickpocket gloves not picking up items when stealing from non-pockets
/:cl:

Fixes pickpocket gloves

---

code/game/dna/mutations/mutation_powers.dm

Refactors the scan mind spell to use names that are unambiguous about who's doing what to whom.
In the process, this fixes at least one bug: that scan mind was delivering the prompt to the wrong user when clicked.
Unreadable code bad. Resulting bugs worse.
It compiled, but I haven't managed to get ~~victims~~volunteers to help me verify that it works.
:cl:
fix: Scan Mind now offers its prompt to the correct person.
/:cl:

Make Scan Mind offer the prompt to the correct person.

---

code/game/machinery/clonescanner.dm
code/game/machinery/computer/cloning.dm

Adds the 5 second delay back to the cloning scanner to give ghosts some time to get back in their body
Also fixes some issues where these actions would wipe your current cloning data:
- Scanning a patient who already has a scan
- Clicking the `scan` button while the machine is on cooldown
Also changes the feedback text of those actions to green ... which is the fix. Yeah.
You can't expect ghosts to always be stuck in their boring dead bodies, also it's unintended
Got the proper cooldown, UI data didn't get wiped when I did the actions above
:cl:
fix: Added the 5 second delay back to scanning a person's body in the cloning scanner
fix: Fixed a few actions in the cloning scanner that could remove your patient UI data
/:cl:

Adds the delay back to the cloning scanner

---

code/modules/projectiles/gun.dm

Badass people are now allowed to execute people again.
Resolves #24525
Execution is back in style this summer! All the other badass people are doing it, why not you??
See above
:cl:
fix: Badass people are now allowed to execute people again
/:cl:

Badass people can now execute again

---

code/modules/mob/living/silicon/ai/ai_mob.dm

ais are no longer sent to null on destroy
bugfix
destroyed an ai
:cl:
fix: ais are no longer sent to null on destroy
/:cl:

ais are no longer sent to null on destroy

---

code/modules/mob/living/simple_animal/bot/medbot.dm

Removes an attempted `<span>` from a medbot line.
It looked like this:
Yolo. (it compiles)
:cl:
fix: A rare medbot line no longer attempts to speak the forbidden tongue of HTML.
/:cl:

Removes an attempted <span> from a medbot line.

---

_maps/map_files/stations/metastation.dmm

Fixes the tint button in Prisoner Processing on Meta.
If it ain't broke, don't fix it!
Wait, this *was* broke...
Glass goes on. Glass goes off.
:cl:
fix: [Meta] Fixes the tint button in Prisoner Processing.
/:cl:

[Meta] Fixes the tint button in Prisoner Processing.

---

code/modules/mob/living/simple_animal/hostile/mining/elites/elite.dm

- Removed double spaces in `elite.dm` chat messages
- Fixed missing chat message when the activator is defeated
> As the life in the activator's eyes fade, the forcefield around you dies out and you feel your power subside. Despite this inferno being your home, you feel as if you aren't welcome here anymore. Without any guidance, your purpose is now for you to decide.
Grammar
| Current | Fixed |
|-|-|
| ![Current](https://github.com/ParadiseSS13/Paradise/assets/41360489/b484d22e-c305-4929-b9e9-e83502496ef4) | ![Fixed](https://github.com/ParadiseSS13/Paradise/assets/41360489/c54f1967-c946-4ba8-936f-331ee36fcb56) |
Spawned in as an elite then defeated the activator and checked that the message was there.
:cl: cdui
fix: The message about a triumphant sentient Lavaland elite's fate is now …

Lavaland Tumor Grammar Fixes

---

code/game/machinery/cryopod.dm

Add every forgot high risk items on the list of items stored on cryo storage.
Also add up items such as stamps.
For once as a Ntr i don't need to ahelp the admins to get a new stamp back to be allowed to fax them in the first place.
Spawned went into storage with my stamp, stamp was on the list, all gucci.
:cl:
tweak: Stamps, knuckleduster and captain rapier can be recovered from cryo storage
del: Delete RCD and RPD from cryo storage
/:cl:

Update items stored on cryo storage

---

code/datums/keybindings/movement_keybinds.dm

Reverts https://github.com/ParadiseSS13/Paradise/pull/24974. Default bind restored.
A: This has disabled it for people who were still actively using the bind willingly, while doing nothing for people who had voluntarily disabled it.
B: If the fact that we've received quite a few ahelps/mhelps/looc questions about why this is no longer working is any indicator, this feature was still in use by enough people to justify it not being disabled by default.
C: Better to leave this bound by default so new players can see it existing, they have full capacity to unbind it if they do not like it. It's used in roleplay and convenience, after all.
It's a revert, which worked previously and nothing else has changed here, so it should work.
Regardless, it still builds, and I confirmed the default …

Reverts "makes direction lock no longer a default bind"

---

code/game/objects/items/devices/voice_changer.dm

Allows you to select a voice to imitate again with the voice changer.
Fixes: #25054
Voice changer should allow you to change your voice.
Get a chameleon mask.
Change the voice.
My voice is changed.
:cl:
fix: Voice changer voice can now be selected again.
/:cl:

Fixes the voice changer

---

code/modules/shuttle/supply.dm

Manifests have to be stamped before sending them back to CC.
Everyone thought this was true already.
Sent back an unstamped manifes.
Sent back a manifest only stamped with irrelevant stamps.
Sent back a manifest stamped GRANTED and with an irrelevant stamp.
Sent back a manifest stamped both GRANTED and DENIED.
:cl:
add: Manifests must now be stamped GRANTED before returning them to CC. Yes, this is a new feature.
/:cl:

Require stamping manifests.

---

code/__HELPERS/text.dm

Pencode now supports [s] for strikethrough text.
More formatting is good.
See above.
:cl:
add: Strikethrough text is now available in paperwork with [s][/s].
/:cl:

Add [s] to pencode.

---

code/game/objects/items/crayons.dm

Spraycan now warns you when you try to spray stuff while the cap is on.
You can no longer use spraycans as a source of nourishment (whyyyyyyy!?)
Knowing why ye cannot spray ye flaske is good.
Being able to casually print nutrition is silly. When that nutrition is literally spraypaint that doesn't even have any negative side effects, it is even more silly. IT DOESN'T EVEN USE A SPRAY SOUND AGGHHH!
Tried to spray stuff with cap on. Got told to remove cap.
Tried to eat the spraycan. Could not.
:cl:
tweak: Spraycans now warn you if you try to use them without removing the cap. You can no longer fill your nutrition bar with solvent abuse.
/:cl:

Updates the spraycan

---

code/modules/mining/lavaland/loot/hierophant_loot.dm

Stops the Hierophant Club from turning to ash.
So when an ash drake desides to sneeze in your general direction the club doesn't turn to ash. The club is basically the body of the dead boss,(I know that the old sprite was the boss holding the club, but with the current sprite, the club itself is the boss) so it doesn't make much sense for the club to be turned to ash so easily, even more so that the boss literally lives on lavaland.
(My VSCode is borked. Funnyman let me test it on his local)
Spawned Lava turf and the hierophant club.
Threw the club into lava, watched it not burn.
Spawned an ash drake and pulled the hierophant club behind me.
Watched the club not get turned to ash while being mauled by an ash drake.
:cl:
tweak: Gives the Hierophant Club the resistance flags LAVA_PROOF and …

Hierophant Club can no longer become ashes

---

code/modules/mob/living/brain/robotic_brain.dm

This PR fixes the oversight that makes it so robotic/positronic brains don't tell the examiner if the speaker is toggled on or off.
Bugs are bad, being a conscious brain with a disabled speaker is painful so making it easier for other people to tell if you're silenced is nice.
Gibbed a robit and Looked at the brain
:cl:
fix: Examining a robotic or positronic brain will tell you if the speaker is on or off.
/:cl:

Fixes robotics brains not showing status of speaker on examine.

---

code/game/machinery/clonepod.dm

Adds an alert whether you want to change the access restrictions or emergency eject a clone from the cloning pod
Grrr removed functionality that was very useful
See above, ejected a clone
:cl:
fix: Added the option back to emergency eject people from the cloning pod
/:cl:

Gives you the option to emergency eject clones

---

code/game/objects/items/robot/robot_upgrades.dm
code/modules/research/designs/janitorial_designs.dm
code/modules/research/designs/mechfabricator_designs.dm
code/modules/vehicle/janivehicle.dm

The janicart floor buffer upgrade has been removed. The janicart is now upgraded using the janiborg floor buffer.
The cost of the janiborg buffer has been adjusted to be the average of the old costs of the janiborg and janicart buffers.
Having two seemingly identical floor buffer upgrades that are mutually incompatible with each other is dumb. The janicart is made out of a dead janiborg, so it makes sense that a borg upgrade would work on it (as is the case with VTEC).
Spawned in.
Saw there was no janicart buffer.
Added a janiborg buffer to the janicart. It worked.
:cl:
del: Removed the Janicart floor buffer item.
tweak: Janicarts now get their floor buffer from the janiborg buffer upgrade, available in robotics. Changed the cost of the janiborg upgrade.
/:cl:

Merges the Janicart Floor Buffer into the Janiborg Floor Buffer

---

code/modules/supply/supply_console.dm
code/modules/tgui/tgui_input/alert_input.dm
code/modules/tgui/tgui_input/list_input.dm
code/modules/tgui/tgui_input/number_input.dm
code/modules/tgui/tgui_input/text_input.dm

fixes a tgui input gc issue. Timers hold a ref to objects that call em so you need to make sure they're deleted with the object
fixes the one use of timeout being way longer than intended
bugfixes
Checked GC logs after letting that text do it's thing
:cl:
fix: the timeout on the supply console order is no longer insanely long
/:cl:

fixes a tgui input gc issue

---

code/modules/mob/living/carbon/human/species/unathi.dm

Gives plasma golems their self ignite ability back by removing the duplicate definition
The unathi breathing fire PR was a stealth removal by accident
Had ignite as an unathi, which worked properly
:cl:
fix: Fixed plasma golems not being able to ignite themselves
/:cl:

Gives plasma golems their suicide ignite back

---

code/modules/mob/mob.dm

#24876 accidentally broke newlines in IC notes. This fixes them.
Putting newlines in your own memory is useful.\
It compiled.
:cl:
fix: Newlines work in IC notes again.
/:cl:

Allow new lines in IC notes again

---

code/modules/projectiles/guns/syringe_gun.dm

Fixes #25175 
Changes blowgun's trigger_guard to TRIGGER_GUARD_ALLOW_ALL. 
You do not need fingers to blow on something!
:cl: Chuga
tweak: Bamboo blowgun is now usable by ashwalkers and hulks
/:cl:

Fixes #25175: Mobs with chunky fingers can now use blowguns

---

code/modules/events/blob/theblob.dm

Makes PKAs halve their damage if they hit blob tiles
Currently, a single miner can be a **very** big nuiscance to a blob, either by Crusher to easily deal with blobbernauts (Which is decently okay with me, due to the risk of having to be in melee range) or using their infinite ammo PKA which will, by default, twoshot a normal blob tile, if in space/atmosless areas, which is true 90% of the time because the blob passively destroys the outer station walls.
This way, to 2-shot blob tiles, you'll need 2 damage mods at least, which heavily reduces the amount of recharge mods you can fit in it.
I killed a blob tile in 4 hits
Used an edited variant with 2x the damage, killed it in 2 hits as it is on live
:cl:
tweak: PKAs now deal half damage to blob tiles
/:cl:

Halves the damage dealt by PKAs to blobs

---

code/game/gamemodes/malfunction/Malf_Modules.dm

nerfs machine overload
now does a heavy explosion in a 3 by 3 box, instead of a 5 by 5 box, light explosion brought down from a radius of 5 to 3
the chat alert for it being used is now a danger alert instead of a shitty html insert. stop using the italics font just use ``<i>`` spans
you now get a fuse sound effect on the object when it's gonna blow. Just fits
This has been on my radar for awhile but the radius on this is just silly. 3 by 3 is still very good, but not "everything else in the general direction" good. To put this in perspective the minibomb had a radius of 2 and this had a radius of 3. 
Danger notices should be danger alerts for chat sorting reasons
Sound feedback is good 
did it in game
:cl:
tweak: Machine overload now has a heavy explosion radius of 2 from 3, and a light …

nerfs machine overload

---

code/modules/projectiles/projectile/bullets.dm

Prevents rubbershot pellets from triggering its guaranteed 8 second knockdown more than 5 tiles away. 
Requested by Qwerty.
At a range of >5 tiles, it's only possible to be hit by one or two pellets (at a high deflection angle). If the target has 59 stamina damage and is hit by this pellet, it will trigger a knockdown for 8 seconds. This behavior is a little bit silly for an ammunition that is intended to be employed at close range.
Note: this does not affect 99% of use cases for rubbershot, only the rare situations where the target has just enough stamina damage to get sent over the 60 damage threshold by a single pellet fired at extreme range. It is not possible to hit a target with more than one or two (out of ten) pellets over a distance of more than a few tiles because of its high …

Restricts rubbershot's guaranteed knockdown range

---

_maps/map_files/RandomRuins/SpaceRuins/listeningpost.dmm
_maps/map_files/RandomRuins/SpaceRuins/mechtransport.dmm
_maps/map_files/RandomRuins/SpaceRuins/moonoutpost19.dmm
_maps/map_files/RandomRuins/SpaceRuins/syndicatedruglab.dmm
_maps/map_files/RandomRuins/SpaceRuins/syndie_space_base.dmm
_maps/map_files/RandomRuins/SpaceRuins/syndiecakesfactory.dmm
_maps/map_files/RandomRuins/SpaceRuins/syndiedepot.dmm

Pretty much the title, replaces/adds the pens in the following space ruins with syndicate pens(not edaggers, the new syndi themed pen  #24756 added)
- Listening outpost
- Crashed mech transport shuttle (its cybersun not syndi but close enough)
- Moonbase 19, in the hidden syndi part
- Syndi drug lab
- Syndi research oupost
- Syndi cake factory
- Syndi supply depo
Syndi pen in syndi places, makes sense
these are different spots i swear
compiled, they're just a small path change
:cl:
add: Added the syndicate pen to the moonbase 19 space ruin, and syndi cake factory.
tweak: The new syndicate™ themed pen has been delivered to syndicate out coves and outposts. replacing the old ones, see pr for details.  
/:cl:

Swaps most of the pens in the syndicate:tm: themed space ruins for syndi pens

---

code/controllers/configuration/sections/general_configuration.dm
config/example/config.toml

Reverts configurable option that has been removed from config in #24060.
Besides the fact that this change was really unrelated, it will cause problems on our ss220 server, because this value can no longer be changed in the config without reverting this code. It would be great to keep this value configurable so that we don't have to create another conflict in the codebase. Thank you in advance.
Reverts existed code.
NPFC

Bring `respawn_enabled` back to config

---

.github/workflows/render_nanomaps.yml

Changes nanomap workflow exit behaviour to skip rather than fail when no changes are needed
This looks alarming when it is, in fact, fine.

Skip nanomap workflow when no changes needed

---

code/game/objects/structures/displaycase.dm

Adds much better feedback for interacting with and examining display cases.
Clicking on an open display case will now try to put the item into your hands if possible, or drop the item onto the ground if it can't.
I've personally been noob-trapped by these before; it's not always clear how you're supposed to interact with this item, which is especially annoying for something that frequently holds onto a high-value item.
Busted up a few cases, and checked them out.
:cl:
tweak: Display cases are now a bit more informative on examine and interaction.
tweak: Items removed from display cases will now be placed into your hand.
/:cl:

Improves interactions with display cases.

---

code/modules/power/lights.dm

When the security level is increased it no longer forces lights that don't have any power to magically turn on again.
(Note that when the security level goes to EPSILON the lights will still turn red, even if they don't have any power.)
Fixes: #24592
It's a bit silly if you put in a lot of work to disable APCs to turn off the lights, only for all lights to magically turn back on when the alert level changes
Depower all APCs.
Change the alert level.
The lights no longer turn on.
:cl:
fix: Security level changes no longer force depowered lights on.
/:cl:

[FIX] Security level changes no longer force depowered lights on.

---

code/game/gamemodes/miniantags/morph/morph.dm

This PR fixes a runtime preventing morphs from eating dead bodies.
Bugs bad
Ensured I could eat a dead body.
:cl:
fix: Morphs should no longer fail to eat dead bodies.
/:cl:

fix: null check during morph eat

---

code/modules/antagonists/cult/team_cult.dm

Any new converts do not gain halos/red eyes until ALL of the cult gains them.
Also, cults can no longer ascend while they are rising, but this should basically never happen.
Makes more sense than new converts instantly getting halos / red eyes while the rest of the cult has to wait 20 seconds. Looks wonky when one cultist has a halo and the rest don't.
3 Skrells sitting near the bridge, C-U-L-T-I-N-G
:cl:
fix: Cultists no longer instantly get red-eyes/halo when converted
tweak: Cults can no longer ascend while they are rising.
/:cl:

Cultists no longer instantly get red-eyes/halo when converted

---

_maps/map_files/shuttles/emergency_shadow.dmm

Engineering section is engineering / atmos locked, oops, sorry.
Directional firelocks replaced with directional reinforced plasmaglass, to make breaking it slightly harder, primarly for griefers.
Shuttle will be faster when admin forced, like a cargo order.
engineering in shuttle being engineering locked is good.
Extra protection from grief is good.
Admin forced shuttle being fast is good.
Attempted to open door as civilian, then engi, then atmos.
Called shuttle when admin ordered, faster.
Confirmed glass was there / anchored.
:cl:
fix: NTSS shadow engineering section is engineering access locked.
tweak: NTSS shadow direcitonal firelocks removed, replaced with directional plasmaglass windows.
fix: Admin ordered NTSS shadow is faster as it should be.
/:cl:

day 1 shadow tweaks

---

code/game/gamemodes/nuclear/nuclearbomb.dm

Informs the Deathsquad over the radio that the nuke has been armed, since the station no longer goes into Delta when the station is on Epsilon. This probably should have been added with the other PR but I didnt think of it until my other PR was approved!
The deathsquad should know the bomb is armed so they can leave if they so want to.
Set security level to Epsilon and armed the nuke and saw the new message.
:cl:
tweak: Deathsquad members are now informed over the Special Ops channel that the nuke has been armed.
/:cl:

Informs Deathsquad that the bomb has been armed during Epsilon Alert.

---

code/modules/mob/living/simple_animal/hostile/terror_spiders/terror_ghost_interaction.dm

This adjusts the logic in `humanize_spider` proc. It fixes an oversight with the order of conditional checks. 
It prevents ghosts from being able to control terror spiders that have been set to non-controllable by admins. 
It also ensures that some other checks are made first that would prevent a player from taking control of the terror spider.
Tried to take control of a terror spider that has `ai_playercontrol_allowtype`  set to `0` as a ghost
Tried to take control of the terror spider that was dead as a ghost
Tested to make sure that Job Ban was still working properly
NPFC

Fixes a small oversight with terror spiders and ghosts

---

code/game/objects/structures.dm
code/modules/events/spacevine.dm
code/modules/mob/living/carbon/carbon_procs.dm

Gives kudzu a chance to buckle you to it based on how well-grown it is. Unbuckling from kudzu takes five seconds per plant.
Currently, it really only buckles on spreading, which is a little rough. This should provide a disincentive for bumrushing kudzu
Ran into vines, got stuck.
:cl:
tweak: Kudzu now has a chance to buckle you when crossing it, and takes a bit of time to unbuckle yourself from.
/:cl:

Makes kudzu much more likely to entangle you

---

tgui/bin/tgui
tgui/bin/tgui_.ps1

Changes the behaviour of the merge conflict resolution for TGUI bundles, allowing the rebuilt bundles to be committed using a separate commit.
The current merge driver fails to actually use the right files when rebuilding, leading to the bundle being behind. This PR makes the TGUI build task async so it sorts itself out following the conflict resolution step.
I can't test this locally using the workflow, so lets do it live!
(it works fine with local conflict resolutions, I just don't know how the workflow for !merge_upstream will work)

Update the TGUI conflict merge resolution to properly commit rebuilt bundles

---

.github/workflows/merge_upstream_master.yml

Removes a rogue # that I'm 99% sure about isn't a loadbearing # 
Cleaner response
Before:
[There is no after because I have no idea how to test this]
None yet
NPFC

Removes a rogue # from the merge upstream bot response

---

code/modules/hydroponics/seeds.dm

Reduce the chance of getting no changes to a stat when mutating plants.
It was supposed to be 50%, but ended up as more like 75% in some situations.
Did a round of mutation selections, got less non-changes.
:cl:
fix: Corrected an oversight that made the chance of some plant stats mutating lower than intended.
/:cl:

Reduce the chance of getting no changes to a stat when mutating plants.

---

code/game/mecha/combat/marauder.dm
code/game/mecha/mecha.dm
code/game/mecha/working/ripley.dm

Set Ripley and firefighter timer to get in to 3 second instead of base 4.
Also return Mauler his heavy missile launcher, make it worth to buy. Who stole it earlier?
This changed time to get in allow miners when shuttle in-route get in their mecha without any risk to fall of landing and waste entire eternity to get up and get in mecha. Also economes 4 second after every landing because you need to get in mecha only after landing.
there is not, perhaps..
change a bit, test for work, be happy
:cl:
tweak: Return Mauler his heavy missile launcher
tweak: Ripley and Firefighter now faster to get in from 4 to 3 seconds.
/:cl:

Qol + fix for mecha

---

code/modules/mod/mod_clothes.dm

modsuits have the same virus protection as biosuits / space suits, as they are sealed suits.
Consistancy, they should have been, sorry for forgetting about this / not getting to it for so long.
"A third-generation, modular civilian class suit by Cybersun Industries, 
this suit is a staple across the galaxy for civilian applications. These suits are oxygenated, 
spaceworthy, resistant to fire and chemical threats, and are immunized against everything between 
a sneeze and a bioweapon. However, their combat applications are incredibly minimal due to the amount of 
armor plating being installed by default, and their actuators only lead to slightly greater speed than industrial suits."
Also makes it lore accurate again 😃 
it compiled and each suit had the variable 
:cl:
fix: Modsuits have the …

modsuits have the same virus protection as space suits / biosuits

---

code/game/mecha/equipment/weapons/weapons.dm
code/modules/projectiles/ammunition/ammo_casings.dm

ion scatter gets 2 more pellets and 5 degrees more spread.
Over the years, I have inderectly nerfed ion scatter through fixes / tweaks, such as:
https://github.com/ParadiseSS13/Paradise/pull/23864 , mainly for the HOS gun, a weak ion should be a weak emp effect on the tile, not 50/50 for a heavy, and:
https://github.com/ParadiseSS13/Paradise/pull/18713, which fixed weak ion shots being stronger than normal ion shots.
These changes were good,but weak ion has certainly been left behind from them in power, especially when you have to manually craft the ammunition.
This should give the ion scatter a bit more strength against borgs / mechs, and keep up as a good AOE emp weapon.
Also applied to the mech ion scatter now
I shot the funny ammo
:cl:
tweak: Ion scatter shotgun shells gets 2 more …

ion scatter gets 2 more pellets and 5 degrees more spread

---

code/modules/antagonists/vampire/vamp_thrall.dm
code/modules/reagents/chemistry/reagents/water.dm

Adds logging for vampire thrall deconversions into player logs.
Helps admins keep track of in-game events. 
Converted a mob to a thrall, fed holy water, checked logs to confirm. 
NPFC

Adds logging for thrall deconversions

---

code/game/machinery/clonepod.dm

- Grants `TRAIT_NOFIRE` to clones during the cloning process and removes it upon ejection
Tried to clone a plasmaman, when cloning was done they had max burn damage and were husked. Fun.
It just works
:cl:
fix: Plasmamen will no longer catch fire during cloning
/:cl:

Grant TRAIT_NOFIRE while cloning

---

code/modules/food_and_drinks/kitchen_machinery/gibber.dm

Buffs the gibber to produce 6 meat slabs instead of 3.
Monkeys and monkey substitutes are a staple meat source for enterprising chefs. However, currently you need to butcher them with a knife in order to get all the meat you want out of them (5 slabs). This also leaves a mess of body parts and organs everywhere, most of which cannot be used for cooking.
Using the gibber avoids the mess of body parts and organs, but you lose 2 meat and all the cookable organs when doing so.
This PR makes it so you don't have to make a mess of body parts and organs unless you're specifically **trying** to get at those organs. You get an extra slab of meat to compensate for the lost organs, which themselves can be cooked into some powerful food items.
Gib.
:cl:
tweak: Gibber now drops an extra 3 meat slabs …

The Gibber Now Drops 6 Meat Instead of 3 When Gibbing.

---

code/datums/keybindings/admin_keybinds.dm

Fixes a bug that seems to have been around for a while, but has only really surfaced while working with https://github.com/ParadiseSS13/Paradise/pull/24855. Without it, you can sometimes get stuck without your F7 or F3 keybinds. Since it's kind of a wider-ranging bug, I figured I'd pull it out into its own issue.
`check_rights()` with no mob passed defaults to `usr`, which can sometimes not be what we expect it to be, particularly when hopping between bodies and ghosts.
Thanks to Tourte for poking me about this bug until I got around to fixing it.
While it should be easy enough to get yourself out of this kinda broken state (pressing F12), admins shouldn't have to fumble to check player panels when observing.
Loaded in, was able to open player panel while observing and did not observe the …

Fixes a bug with admin keybinds occasionally not working

---

code/modules/mob/mob_movement.dm

When you move a pulled object by clicking on a tile without a module selected as a borg, you can no longer move an objects two tiles away from you. Also fixes a similar issue with telekinesis.
Fixes: #25112
You should not be able to push things beyond your reach.
Be a human, try to move and pull stuff around, works just fine
Be a cyborg, try to move something beyond my reach, I can't, everything else works just fine.
:cl:
fix: Cyborgs can no longer move pulled objects two tiles away from them.
/:cl:

Moving pulled objects as a borg checks if the turf is adjacent to you.

---

code/modules/crafting/tailoring.dm

Tweaks recipes of glasses to fix some issues. Uses defines for time values.
1. We better forbid using subtypes of a HUD to disable crafting some HUD from another crafted HUD because it consumes resources irrevocably (ok for cables).
2. We better forbid using subtypes of sunglasses because:
a. Removal recipes return simple sunglasses.
b. Different sunglasses have different features that HUD sunglasses do not have.
UPD. Came to the conclusion that these are ok:
```dm
/obj/item/clothing/glasses/sunglasses
/obj/item/clothing/glasses/sunglasses/noir
/obj/item/clothing/glasses/sunglasses/yeah
/obj/item/clothing/glasses/sunglasses/big
```
Local server ok.
:cl: Maxiemar
tweak: Different HUD sunglasses and HUD goggles recipes allow simple HUDs and only some sunglasses now.
/:cl:

Tweak recipes of glasses

---

code/game/machinery/requests_console.dm

Secondary goals will now refuse to generate if messaging is offline.
If you generate one without messaging available, you have no idea what to send.
Tried to generate a goal without messaging server. Got error message.
:cl:
tweak: Secondary goals will now refuse to generate if messaging is offline.
/:cl:

Secondary goals will now refuse to generate if messaging is offline.

---

code/modules/mob/living/simple_animal/hostile/megafauna/ancient_robot.dm

Now when you examine Vetus, you can see a postscript telling you the type of its core.
Sometimes Vetus' appearance is not obvious, especially to people with color blindness, so being able to understand the core type by inspection can be a lifesaver, as each core type should ideally have different equipment, such as magboots vs cryo, fire protection for fire type, and so on.
Cryo core example. Now air cold around him 
do code, try again, do correct
:cl:
tweak: Examination of Vetus now tells us its core type
/:cl:

Vetus Speculator now tell you what type he is

---

code/modules/mob/mob_movement.dm

Fixes an unintended side effect from #25253 which made it impossible to move an object out of your way if you get blocked in by it.
Unintended change that makes it very easy to trap yourself on accident.
Before:
https://github.com/ParadiseSS13/Paradise/assets/19361017/ac0d10c2-be8a-48b4-be3a-342bde9f0ec1
After:
https://github.com/ParadiseSS13/Paradise/assets/19361017/be9c2823-6f6f-46c2-92e6-fdc97530fd4d
Get stuck between a bunch of lockers.
Move the locker out of the way
:cl:
fix: You can now move a dragged object out of the way again if it is trapping you.
/:cl:

Fixes being unable to move objects out of your way when stuck.

---

code/modules/admin/topic.dm

This PR adds additional logging to game log and an admin message for the 'Crew Traitor' player smite. 
Additionally, this PR cleans up the name of a variable used in this smite.
The message lets admins know who was made a traitor to hunt the target of the smite.
The logging keeps track of the results of the admin action.
Started an instance with two clients.
Used one client to smite the the player on the other.
Observed admin message and checked the game log for proper behavior.
NPFC

Adds an admin message and logging for 'Crew Traitor' smite

---

code/game/objects/items/weapons/RCD.dm

The change that GDN *actually* asked for on #25062: initializing the RCD action types only once.
It doesn't runtime this time.
Built and deconstructed wall, airlock, window, and plating. LGTM
NPFC, for real this time.

Made RCD code more efficient.

---

code/modules/station_goals/secondary/secondary_goal.dm
code/modules/station_goals/secondary/secondary_goal_tracker.dm

Admin secondary goal modifications will now unregister when deleting/completing.
Leftover tracking is bad, and leads to weird things.
Deleted a goal, tracking went away.
:cl:
fix: Secondary goals will no longer half-exist when forcibly completed or deleted by an admin.
/:cl:

Admin secondary goal modifications will now unregister when deleting/completing.

---

code/game/objects/items/weapons/caution.dm
code/modules/mob/living/silicon/robot/robot_modules.dm

This PR fixes the type path of the malf janiborg mines, so they are functional.
Bugs are bad, not having funny landmines when you should is sad
Placed mines, made sure they properly blew people up.
:cl:
fix: Janitor borgs with the malf combat upgrade can place their landmines properly now.
/:cl:

Fixes malf janiborg mines

---

code/modules/shuttle/supply.dm
code/modules/station_goals/secondary/random_bulk_reagent.dm
code/modules/station_goals/secondary/science/random_ripley.dm
code/modules/station_goals/secondary/secondary_goal_tracker.dm
code/modules/station_goals/secondary/variety_reagent.dm

Update Secondary Goals to accept reagents in anything that contains reagents, notably fermenting barrels.
Ran into a bartender who thought this already worked.
Sent reagents in fermenting barrels, got paid.
:cl:
tweak: Secondary Goals will now accept reagents in anything that contains reagents, notably fermenting barrels.
/:cl:

Update Secondary Goals to accept reagents in fermenting barrels, etc..

---

code/game/gamemodes/cult/runes.dm

Clear holywater from new body during converting process
some CLEVER AS F..REAKING ENSTEIN players fill their stomach with holy water and go fight to the cult, KNOWING they are not be converted. And then accidentaly "forgot" about 300 liters of cursed liquid into their bodyes after converting.
i need to fix that
copypasta from cult dagger
:cl:
tweak: Converting into cult also purge all holy water from body
/:cl:

Tweak: Converting into cult also purge all holy water from body

---

code/modules/events/event_container.dm
code/modules/events/event_procs.dm

Removes "ASSIGNMENT_GARDENER" and fixes Chemists not affecting the weight of the Fungal Growth event.
It was meant to work this way.
Spawned as a Chemist and saw that the Fungal Growth event weight raised in the Event Manager Panel.
:cl:
fix: Fixed the amount of Chemists on station not mattering when Fungal Growth is supposed to roll.
/:cl:

Botanists are no longer Gardeners and made Chemist matter in the Fungal Growth event.

---

code/datums/spell_handler/vampire.dm
code/modules/antagonists/vampire/vamp_datum.dm
code/modules/antagonists/vampire/vampire_powers/dantalion_powers.dm
code/modules/antagonists/vampire/vampire_powers/hemomancer_powers.dm
code/modules/antagonists/vampire/vampire_powers/umbrae_powers.dm

Adds proc to handle subtracting from usable blood pool that clamps between 0 and blood total and replaces all manual subtractions from bloodusable with it. This proc should be used to safely spend blood when not handing it off to spend_spell_cost. 
This bug breaks using zero cost abilities and is not supposed to happen.
Before
After
:cl: Chuga
fix: Vampires can longer get stuck with negative blood after being fed holy water.
/:cl:

Fixes vampires ending up with negative blood

---

code/game/gamemodes/nuclear/pinpointer.dm
code/game/gamemodes/wizard/spellbook.dm
code/modules/events/blob/overmind.dm

fixes some locate checks being in world. if locate has no second arg it just defaults to in world
performance
refunded a spell and used a pinpointer
🆑
tweak: blob camera controls no longer lock you to a 3 by 3 box, instead checking if a blob tile is in a radius of 3 tiles from the camera
/:cl:

fixes some locate checks being in world

---

code/datums/uplink_items/uplink_general.dm
code/game/objects/items/weapons/explosives.dm

c4 can now be used on all mobs when unconscious or dead. can no longer be used on living noncarbon mobs.
This adds a solid way to get rid of your targets without defaulting to the other option, the chainsaw. Prevents a lot of niche cheese strats like sticking c4 to a rev and stuff while still making it generally useful.
also a very funny way to wake up from surgery
stuck a bomb on a skrell
:cl:
tweak: c4 can now be used on all mobs when unconscious or dead, can no longer be used on non carbons when they're alive
/:cl:

c4 can now be used on all mobs when unconscious or dead

---

code/game/mecha/combat/marauder.dm

Gives the marauder, and their subtypes bluespace cells. So they dont runout of charge as often.
This includes the following exo suits
- The Marauder
- The Ares
- The Seraph
- And the Mauler
CC level(and syndicate) mechs shouldn't be running out of charge as quick as they do, i believe currently they have a super capacity cell, meaning they hardly have five minutes of fight in them before they go kaput and run outa charge.
Checked if the mechs had bluespace cells. they did.
:cl:
tweak: Central command has increased the budget for their exosuit program, and have given their standard issue exosuits higher capacity cells. As with the mauler, since the syndicate didn't want to be left out.
/:cl:

Gives all the marauder mechs a bluespace cell, since they're CC mechs and all.

---

code/modules/hydroponics/grown.dm
code/modules/hydroponics/hydroponics_tray.dm

Allows the ability to extinguish light of weak strength to extinguish vegetables with the light gene, and strong level to extinguish hydroponics with light sources
Considering what spam potential the hydroponics department has, the lack of a way to put out their lights makes the shadow demon very dependent on one particular nerd rather than the efforts of the entire station, which doesn't fit the concept of a major antagonist.
Now vegetables with the light gene can be extinguished with a touch, like xenobiology cores or flashlights.
The hydroponic trays can now be extinguished. Before this was the only entity in the game that could not be extinguished at all.
do code, do smooth
:cl:
fix: Botany Gaia trays can now be turned off like other sourse of lights.
tweak: Shadow demon can now turn …

Botany light sourses can now be turned off

---

_maps/map_files/generic/centcomm.dmm

Trader shuttle gets shuttle windows instead of reinforced windows on the inside
It looks nicer, and is twice as strong as reinforced windows.
see above
:cl:
tweak: Trader shuttle gets shuttle windows inside
/:cl:

trader shuttle gets shuttle windows inside

---

code/modules/ruins/ghost_bar.dm

ghost bar members are now cleared more hastily. You'll now have your previous mob cleared if you rejoin the bar
bugfix
did it in game
:cl:
fix: Ghost bar members are now cleared when rejoining the bar with a character already in the bar
/:cl:

ghost bar members are now cleared more hastily

---

code/__HELPERS/iconprocs.dm
code/controllers/subsystem/SSstatpanel.dm
code/modules/client/client_procs.dm
html/statbrowser.css
html/statbrowser.js

The turf contents listing (AKA listedturf, client obj view, alt-click view) has been replaced with a high-performance version, easily able to handle tiles with thousands of items on them.
Fixed #24549
Fixes images not loading and causing lag.
Performance and bug fixes are good.
https://github.com/ParadiseSS13/Paradise/assets/98381/6c4e6b47-8d63-422e-b478-c8cd04fceb26
See above.
:cl:
tweak: The alt-click view of tile contents has been rewritten to have better performance, especially with large numbers of items on a tile.
fix: The same view should no longer steal your tab, frequently fail to load images, or cause lag when images fail to load.
/:cl:

Made turf contents listing more performant.

---

_maps/map_files/stations/boxstation.dmm
_maps/map_files/stations/cerestation.dmm
_maps/map_files/stations/metastation.dmm

Allows atmospheric engineers into the emitter rooms
Allows atmospheric engineers to close the radiation shutters
They can set up the engine, and are honestly the job that should have been given the SM, except for the last part of actually turning it on without help. This way you don't need to beg for extra access/the AI/the CE to do a good part of your job
Entered as: Engineer, Atmospheric engineer
Couldn't enter as assistant
:cl:
tweak: Atmospheric engineers can now enter the emitter rooms
tweak: Atmospheric engineers can now close and open the radiation shutters
/:cl:

Allows atmosians into the emitter room

---

code/game/gamemodes/wizard/magic_tarot.dm
code/game/objects/structures/crates_lockers/closets/statue.dm

Reverse Wheel of Fortune tarot card now no longer spawns disallowed vendor types.
Once #25461 is merged, fixes #25450.
Magical artifacts working as intended is good.
There are 6 disallowed subtypes of vendors: Liberation Station, Syndicate Donksoft Toy Vendor, secured Syndicate Donksoft Toy Vendor, Emergency Nanomed, Syndicate Emergency Nanomed, and finally Survival Pod Emergency Nanomed.
I put in a breakpoint during testing to tell me the length of the blacklist `message_admin(bad_vendors)` and this is the result, which concurs with the amount of vendors we want to blacklist.
Then spawned 142 vendors with Reverse Wheel of Fortune, which should be significant enough despite the RNG. Not a single disallowed vendors in the test.
:cl:
fix: Reverse Wheel of Fortune tarot card now no longer …

Reverse Wheel of Fortune tarot card now no longer spawns wallmeds or Donksoft vendors

---

code/modules/mob/language.dm

This change adds the HIVEMIND_RUNECHAT flag to the grey language datum, displaying runechat above the receiver for all psionic messages that are heard, as with the abductor hivemind language.
Runechat is integral to the game at this point, and it's better for speech to be heard than ignored.
https://github.com/ParadiseSS13/Paradise/assets/81930475/e5983cf5-c0f4-421d-8f80-0c2e7ca2c6d3
:cl: Ascio
tweak: Enable runechat for grey psionic speech
/:cl:

Enable runechat for grey psionic speech

---

code/datums/components/fullauto.dm

Any gun with full auto, now respects click cooldown modifiers, like the rest of the guns in the game.
This is consistant with TG and the double tap trait reducing full auto cooldown there as well.
Consistency is good. The QOL of full auto, should not make mechanics that increase your click speed (or decrease it), not affect the weapon. TG does the same thing with the double tap trait. Yes, it is not the most realistic thing in the world, but in real life taking drugs doesn't make you make after images, and in real life bluespace doesn't slow you down.
Fired a full auto gun set to 0.5 seconds.
Halfed my click speed.
Fired at 0.25 seconds
:cl:
tweak: Click cooldown modifiers affect full auto component the same as every other gun
/:cl:

Click cooldown modifiers affect full auto component the same as every other gun

---

code/datums/uplink_items/uplink_general.dm

Adds some additional player logs when an Uplink purchase is made.
Helps admins keep track of player uplink purchases made throughout a round. 
Spawned in an Uplink and purchased multiple items.
Checked to see if entries were in player logs.
NPFC

Adds additional logging for Uplink purchases

---

code/game/turfs/simulated/walls_mineral.dm

Removes a structural flaw introduced by capitalist spies into the walls of the USSP's structures, which allowed certain capitalist mining tools to penetrate these otherwise completely impenetrable structures.
Puny diamond drills and sonic jackhammers of capitalist origin can no longer penetrate these bastions of socialism!
Explorers shouldn't be able to casually skip the entire ruin and just rush to where the desirable loot is.
I tried to use my capitalist tools on the wall, but my efforts were effortlessly repelled!
:cl:
fix: Russian walls are now immune to diamond mining equipment.
/:cl:

[FIX] Glorious Communist Walls of USSP Station Now Fully Repel Capitalist Pigs!

---

code/modules/mob/living/living.dm

admins can see inside modsuit storage again
we should be able to see this
used the verb, could see inside
:cl:
fix: Lets admins see inside mod storage again
/:cl:

lets admins see inside mod storage again

---

code/game/atoms_movable.dm
code/modules/assembly/infrared.dm

Fixes #25317.
Also makes atoms_movable.dm slightly more readable.
Bug bad.
Pointed a laser out a window
:cl:
fix: Fixed infrared emitter lasers floating off into space.
/:cl:

Infrared emitter lasers no longer float off into space. Fixes #25317

---

code/modules/antagonists/changeling/evolution_menu.dm
code/modules/antagonists/changeling/powers/mutations.dm
code/modules/antagonists/changeling/powers/shriek.dm

Purchasing an ability through the evolution menu is now tracked in a blackbox feedback nested tally.
Also added:
* Tracks every time a weapon sting_action triggers in the changeling_powers category. This seems like it will work but please double check me.
* Adds tracking for dissonant shriek
We are currently lacking a way to track changeling ability purchases, which would be nice for design and balance.
Not sure how to test this locally, but it compiles!

Adds blackbox tracking for purchasing Changeling abilities

---

code/modules/admin/topic.dm
code/modules/events/immovable_rod.dm

Adds a portable rod smite that spawns a rod from 10-20 tiles away from your target, swooping in and hitting them specifically, and then promptly disappearing before causing catastrophic harm.
This will still mess up the people standing around them, but it won't be full station destruction.
More smites fun. I was inspired.
https://github.com/ParadiseSS13/Paradise/assets/89928798/c9b42837-1764-42e0-9930-07afea8b98ca
See images
NPFC :smirk:

Adds a rod smite

---

code/modules/power/engines/singularity/singularity.dm
code/modules/power/engines/tesla/energy_ball.dm

Gives the singularity engine a 20% chance to move towards the station instead of in a random direction.
Singularity engines are currently significantly less deadly than the tesla engines, despite not appearing roundstart on any map. 
In the rare circumstance that engineering specifically orders one from cargo and the even rarer circumstance that it gets loose (and then doesn't get GOATed), it tends to float away into deep space half the time, or eat a part of engineering at worst, which is a little anti-climactic for something that immediately gets the shuttle called.
This will make it slowly drift towards a random part of the station, to make it roughly on par in danger to the tesla engine. Mass is attracted to mass, after all, and the station is the heaviest thing around. 
Watched the …

Gives singularity engines a slight nudge towards the station

---

_maps/map_files/stations/boxstation.dmm
_maps/map_files/stations/deltastation.dmm
_maps/map_files/stations/metastation.dmm
code/game/objects/structures/transit_tubes/station.dm
code/game/objects/structures/transit_tubes/transit_tube.dm

This PR allows transit tube pod riders to skip stations altogether by holding down the directional key of the direction they're traveling. It also finally removes the tube endcaps that exist on maps, since they already can't be built by the RPD and would have made this logic more confusing.
It was already possible to cut short the delay of sitting at a station, or go in the reverse direction, by pressing a directional key while stopped at a station. This makes the delay even faster by eliminating it.
https://github.com/ParadiseSS13/Paradise/assets/59303604/363dbbc2-e5aa-4282-b788-24c2c3b9f8fa
See above.
:cl:
tweak: Transit tube stations may now be skipped by holding down the key in the direction of travel.
del: Transit tube end caps have been removed from remaining maps.
/:cl:

tube stations can be skipped by holding direction key

---

code/game/gamemodes/nuclear/nuclear_challenge.dm

This PR replaces nuclear war check for connected people with check for actual crew, used the same as the one for sharing telecrystals
Being able to start the war with less players than required is not good. When the gamemode shares telecrystals, it checks for living crew, why shouldnt it check for living crew when declaring war?
Compiled
:cl:
tweak: Declaring a war now requires actual amount of 50(currently) crew instead of just connected people.
/:cl:

Nuclear war check now checks for living crew instead of connected people

---

code/__DEFINES/dcs/signals.dm
code/datums/mind.dm
code/datums/outfits/outfit.dm
code/datums/outfits/outfit_admin.dm
code/game/dna/mutations/monkey_mutation.dm
code/game/jobs/job/central.dm
code/game/jobs/job/job.dm
code/game/jobs/job/support.dm
code/game/jobs/job/support_chaplain.dm
code/game/jobs/job/syndicate_jobs.dm
code/modules/mob/living/carbon/human/human_mob.dm
code/modules/ruins/syndicate_space_base.dm

Refactors outfits to work with mind initialization, this means admin spawned chefs/bartenders will start with cqc and their table leap even if their mind is dragged into the body instead of reincarnated.
Consistency good
Joined game as chef, had CQC and tableleap
Reincarnated as bartender, was able to leap over tables quick
Spawned a chef, dressed them up as a chef, then put my client in them and was given cqc
Reincarnated a mime and had all the expected mime spells
NNOs and Deathsquad (and all other admin outfits) still had their offstation role flag applied on their mind
NPFC

Refactors outfits to work with mind initialization

---

code/__DEFINES/food_defines.dm
code/__DEFINES/reagents_defines.dm
code/controllers/subsystem/SSeconomy.dm
code/modules/food_and_drinks/food/foods/baked_goods.dm
code/modules/food_and_drinks/food/foods/bread.dm
code/modules/food_and_drinks/food/foods/candy.dm
code/modules/food_and_drinks/food/foods/frozen.dm
code/modules/food_and_drinks/food/foods/meat.dm
code/modules/food_and_drinks/food/foods/misc_food.dm
code/modules/food_and_drinks/food/foods/pizza.dm
code/modules/food_and_drinks/food/foods/sandwiches.dm
code/modules/food_and_drinks/food/foods/seafood.dm
code/modules/food_and_drinks/food/foods/soups.dm
code/modules/food_and_drinks/food_base.dm
code/modules/reagents/chemistry/reagents/alcohol.dm
code/modules/reagents/chemistry/reagents/drugs.dm
code/modules/shuttle/supply.dm
code/modules/station_goals/secondary/botany/kudzu_goal.dm
code/modules/station_goals/secondary/kitchen/random_bulk_food.dm
code/modules/station_goals/secondary/kitchen/variety_food.dm
code/modules/station_goals/secondary/random_bulk_reagent.dm
code/modules/station_goals/secondary/science/random_ripley.dm
code/modules/station_goals/secondary/secondary_goal_tracker.dm
code/modules/station_goals/secondary/variety_reagent.dm
paradise.dme

Adds a new secondary goal: Variety of Food, for the Kitchen.
More foods are now labelled with new difficulty categories that exempt them from specific food goals, but allow them in Variety of Food if the chef wants to send them..
A few reagent difficulties have been tweaked, including using a similar exemption mechanism.
Request console messages from the supply shuttle are now batched together, and duplicates are compressed.
More secondary goal variety is nice.
Better food/reagent labelling makes for better goals.
Less request console spam is good.
Completed variety of food, saw less request console spam.
:cl:
add: New secondary goal for Kitchen: Variety of Food.
tweak: A few reagents have been tweaked to more fitting secondary goal difficulties.
tweak: Secondary Goals will no longer spam …

Add Variety of Food secondary goal, small tweaks.

---

code/modules/projectiles/guns/energy/stun.dm
code/modules/projectiles/guns/projectile/automatic.dm
code/modules/projectiles/guns/projectile/saw.dm

Makes IK-60 (RED ERT), Disabler SMG and L6-SAW full auto
Time to use new component
Rate of fire values were taken from TG
Full-Auto
Record is laggy a little, potato PC
UPD. WT full-auto removed, but it still on video, ignore it
https://github.com/ParadiseSS13/Paradise/assets/69762909/58c327ce-dc99-464c-a488-a44817bcc650
Above
:cl:
tweak: IK-60 (ERT), Disabler SMG and L6-SAW now real automatic guns (Have full-auto)
/:cl:

Make some guns REAL auto

---

code/__DEFINES/atmospherics_defines.dm
code/game/turfs/simulated/floor/asteroid_floors.dm
code/game/turfs/simulated/floor/chasm.dm
code/game/turfs/simulated/floor/fancy_floor.dm
code/game/turfs/simulated/floor/indestructible.dm
code/game/turfs/simulated/floor/lava.dm
code/game/turfs/simulated/floor/mineral_floors.dm
code/game/turfs/simulated/floor/misc_floor.dm
code/game/turfs/simulated/floor/plating.dm
code/game/turfs/simulated/minerals.dm
code/modules/atmospherics/environmental/LINDA_turf_tile.dm
code/modules/awaymissions/mission_code/beach.dm

When `planetary_atmos` is `TRUE`, it will take turf's initial temperature value instead of hardcoded lavaland's temperature
Use defines
planetary_atmos can be used not only in Lavaland
Accidentaly start a plasmafire on lavaland with toxin canister, atmos normalized

Fix planetary_atmos working correctly only for lavaland + use defines for lavaland atmos

---

code/modules/client/preference/character.dm
code/modules/client/preference/link_processing.dm

Body Randomize button now changes physique and height.
Adds safety to physique and height inputs.
Bags are also properly randomized instead of just being changed to "2"
Randomize button randomizes.
I clicked the buttons
:cl:
tweak: Body Randomize button now changes physique and height
/:cl:

Body Randomize button now changes physique and height

---

code/modules/surgery/organs/organ_extractor.dm

Requested by Qwertytoforty
When implanting a harvested heart in somebody (or yourself) who either has a) a sensory enhancer implant or b) has accumulated any mephedrone addiction threshold (which decays with time), the extractor will now deal 40 damage to the stored heart before it is implanted into the target. 
Mephedrone OD heart damage is intended to be controlled with mitocholide, nanocalcium, or other means. Using the organ extractor on morgue bodies or similarly accessible corpses allows the mephedrone user to instantly replenish their heart damage. 
Verified that it works with addiction threshold and a sensory computer installed.
:cl:
tweak: Prevents using organ extractor to circumvent mephedrone heart damage
/:cl:

Prevents using organ extractor to circumvent mephedrone heart damage

---

code/__DEFINES/misc_defines.dm
code/game/objects/items/devices/radio/intercom.dm
code/game/objects/items/devices/radio/radio_objects.dm

Adds the radio transmit noise when a Radio hotmic is toggled on.
Allows you to toggle a radio's hotmic via Alt Click
Adds logging to prevent mass enabling of hotmics because people are stupid.
QoL upgrade for Handheld Radios mostly.
Also gives a heads up if someone activates a hotmic nearby.
Logging is due to people being stupid a lot of the time.
Testing a buncha radios on local, seems to work.
:cl:
tweak: Radio hotmics can now be enabled via Alt Click + make a transmit noise on activation.
add: Added logging for hotkey hotmic enabling to prevent spam.
/:cl:

Radio Hotmic Noise + Alt Click Toggle

---

code/game/dna/mutations/mutation_powers.dm

Fixes Leap leaving you bugged when you crash into something.
Flying is cool. Flying due to a bug, less cool.
Crashed into a person. Fell to the ground.
Crashed into a window. Fell to the ground.
:cl:
fix: Leap will no longer leave you in a weird floating state if you crash into something.
/:cl:

Crashing into stuff while leaping will actually work now.

---

code/modules/reagents/chemistry/reagents/medicine.dm

Makes Chemistry goals work again.
Bugs are bad.
Successfully received both Chemistry goal types.
:cl:
fix: Chemistry goals can generate correctly again.
/:cl:

Fix Chemistry goals

---

code/modules/reagents/chemistry/reagents/medicine.dm

Removes an unused var.
Unused vars bad.
Compiled.
NPFC

refactor: remove unused var in medicine.dm

---

code/game/turfs/turf.dm

This PR removes the unused `/turf/proc/reachableAdjacentTurfs`. It was last used before the initial JPS port, so it's been completely superseded by the new pathfinding features. 
Dead code bad.
Compiled.
NPFC

refactor: remove unused /turf/proc/reachableAdjacentTurfs

---

code/game/objects/structures/flora.dm

Fixed initialzie for ppflowers as they don't have a fourth icon, resulting in missing texture
Who knows
flwrs
It's ok
:cl:
fix: Fix the lack of texture of some flora species
/:cl:

Fix ppflowers (flora) generate missing icon

---

code/game/mecha/equipment/tools/work_tools.dm

Changes mech RCD ability to build a floor instead of a wall on chasm tiles. 
Makes it easier to try and deal with chasms that turn lavaland into a real torture that is no fun to play. Also a little tightens the logic, because the wall should be placed on the floor, and the base of this "floor" is a giant hole in the middle of nowhere.
copypasta spaceturf, change into chasm, all work perfectly
:cl:
tweak: Mecha RCD now build floor on chasms instead of walls.
/:cl:

RCD now build floor on chasms instead of wall

---

code/modules/atmospherics/machinery/datum_pipeline.dm

This PR adds a missing bit of logic to how pipelines work, making them connect more consistently to each other. If an atmos player has ever described a pump as "bluespaced" this should hopefully fix this issue. Fixes #25215
Credit mostly goes to FunnyMan for actually finding the cause of this issue.
Bugs are bad, this is a notoriously sporadic and annoying bug for atmos mains to deal with.
Made sure the way I knew to consistently reproduce the bug got fixed, then set up (and correctly delammed) a normal CO2 engine to make sure nothing else changed.
:cl:
fix: Atmospheric devices will no longer stop working for no reason.
/:cl:

Makes atmospheric devices connect more consistently.

---

code/datums/status_effects/buffs.dm
code/modules/mob/living/living.dm

Riot shields (dswords, mirror shields, spellblades, anything with parry really) now, rather than blocking movement on any intent bar help, block movement on all intents, but allow people to push past on help walk intent.
You may have noticed, riot shields block movement well, as they are supposed to, when the officer is beating you to death.
However, sometimes it fails? What happens?
What happens is we let people swap on help intent. This sucks for when officers are not trying to kill people, as it doesn't make sense that "I'm going to non lethally arrest this person, but I have to let me push me around when doing so"
This means that shields are no longer weaker on help intent, and are more useful even if you are not parrying.
Disarms / knockdowns still work as usual! (perhaps they should …

You can no longer push people with riot shields (and other parry objects) on help intent

---

code/datums/uplink_items/uplink_general.dm

Reduces the price of the Advanced Pinpointer to `10TC`
Removes its ability to be discounted at this price.
Inter-antag conflict over mirrored objectives is a good thing.
This is also a REALLY good item for new players.
One concern that arose was Security getting their hands on these items more often. If people start using Evidence as Security theyll quickly find themselves demoted, jbanned, or banned just like any other large break in Space Law.
Compiles and price is changed.
:cl:
tweak: Advanced Pinpointer is now 10TC, down from 20TC.
/:cl:

Advanced Pinpointer - 10TC

---

code/game/machinery/tcomms/tcomms_base.dm
code/modules/client/preference/preferences.dm
code/modules/client/preference/preferences_toggles.dm

- Makes dchat radios work again
- Removes the mention of `nearby speakers only` for ghost radios, this wasn't a thing and is slightly confusing
- Fixes an issue where the game told you the wrong thing if you toggled the preference
These things should work
Loaded in with two clients, checked that the ghost could hear radio with the preference toggled on, and not hear radio with the preference toggled off
:cl:
fix: Fixed dchat not hearing radios
fix: Removed mentions of `Ghost radio: Nearby speakers only` - This was not a thing
/:cl:

Fixes various radio issues

---

code/game/gamemodes/miniantags/revenant/revenant.dm
code/game/turfs/simulated/floor/misc_floor.dm
code/game/turfs/simulated/floor/plating.dm

[This PR ](https://github.com/ParadiseSS13/Paradise/pull/24209) added a delayed effect to walking over clockwork and clock turfs, which used sleep for the delay. This turns the sleep into an addtimer callback because sleeping on Entered makes the linter go haywire and has the potential to break signals. 
Also converts revenant death animation to use animate() instead of decrementing alpha in a for loop in between sleeps. Fantastic.
It is making my code not compile and I would like it to compile.
Made sure it does the same thing and doesn't scream bloody murder.

Removes sleep() call from clockwork and floor turfs

---

code/__HELPERS/game.dm

After any ghost that was listening to radios is fully deleted, all radios will break, permanently.
This fixes that.
; help maints
Triggered the bug. Didn't happen.
:cl:
fix: Radios will no longer perma-break.
/:cl:

Fixes radios permanently breaking

---

code/game/objects/items/weapons/cards_ids.dm

Fixes #25214 by giving them xenobio access
Free golems should be able to use science equipment they can obtain.
Spawned golem w/ ID. Used xenobio machine.
:cl:
fix: Gave Golems xenobiology access
/:cl:

Gives Free Golems access to Xenobiology, fixes #25214 

---

code/controllers/subsystem/tickets/SStickets.dm

Reverses the names used in the ticket typing indicator, since they were backwards.
Fixed #25593
Bugs bad.
Got someone to help test this time, names were right.
NPFC

Corrected admin/user names in ticket typing indicator.

---

code/_onclick/observer_onclick.dm

Revenants no longer runtime because someone added something to attack ghost without typechecking again
runtimes bad typecase pls
clicked shit
:cl:
fix: makes revenants not runtime clicking nearly anything
/:cl:

makes revenants not runtime clicking nearly anything

---

code/modules/world_topic/adminmsg.dm

Fixes the adminPM from out of game showing as just the text `adminpm`.
None.
fix: Fixed out of game admin PMs not displaying properly
/:cl:

Fix admin PMs not working from discord

---

code/datums/datumvars.dm

This PR fixes VV incorrectly displaying lists when the lists contain values that are zero.
Inscrutable variable inspection bad.
Before:
After:
Created some lists, cached them in GLOB.string_assoc_lists, inspected them.
NPFC

fix: VV list display with values that are zero

---

_maps/map_files/stations/boxstation.dmm

title
its been frustrating me for ages, and is wrong
compiled 
:cl:
fix: Fixed a random tile in cargo being the wrong texture on box
/:cl:

Fixes a tile on box that is the wrong texture

---

_maps/map_files/RandomRuins/SpaceRuins/syndie_space_base.dmm
code/game/objects/items/weapons/cards_ids.dm

Fixes the AI from being able to jump to the cameras around the syndicate research base by means of tracking the skeleton that spawns in the cave, or from tracking researchers. This is done by changing the skeleton to a pile of remains, and making Syndicate Researcher ID's untrackable similar to Agent IDs.
AI should not be spying on the syndicate.
Spawned as researcher, walked to cave, spawned as AI, could not track researcher.
:cl:
tweak: Syndicate Researcher ID's are now untrackable to AI cameras.
tweak: Skeleton in Syndicate Research Lab Cave replaced with Remains decal.
/:cl:

No more AI tracking Syndicate Researchers

---

code/modules/mob/dead/observer/observer_base.dm

Maint drones no longer can renter the drone when ghosting from it and get the 10 minute mob spawner respawn timer
We let maint drones ghost easier, as we wanted it as a chiller low impact role you could leave whenever. We did not however want them able to ghost, look around the station for potential damages or other issues, and re-enter body
Ghosted as a maint drone, kept respawnability, but could not instantly re-enter my body or respawn from the drone factory.
:cl:
fix: maint drones no longer can endlessly ghost and respawn
/:cl:

[s] maint drones no longer can endlessly ghost and respawn

---

code/datums/uplink_items/uplink_general.dm
code/game/objects/items/weapons/bio_chips/bio_chip_adrenalin.dm
code/game/objects/items/weapons/bio_chips/bio_chip_fluff.dm

Normal Proto adrenalin price change to 10 TC
Changed the position of the adrenalin to be based on cost
Made a one-use adrenalin, that can't be discounted, with 3/4 the stim agent, synaptinzine, and weak omnizine instead of normal omnizine for the price of 20TC
Adrenaline has always been in a very weird spot regarding price. The original idea for the proto-adrenaline was to ensure that vampires and changelings were not instantly meta'ed to death since it did not have any speed to the stims. 
However, with the price of proto-adrenaline and its basic use, it was hard to justify it against the proto-freedom implant, which cost the same.
Instead, a new item called basic adrenaline, priced at 20TC will replace proto-adrenalin in the price range. It does not have much healing, so if you get …

Proto adrenalin price changes and one use adrenalin

---

code/game/objects/items/stacks/sheets/leather.dm

Fixes https://github.com/ParadiseSS13/Paradise/pull/25231 armor value, because i though there is human armor here. Now i fully understand and do proper armor this time. Dragon hide gain 79%, goliath 70%, metal plate is 51%. Like somewhat intended at first.
Invinsible mech is fun but salty to up against
Tested, damage is takes good.
:cl:
fix: Fix armor value on attachable armor for Ripleys, make them destructible now
tweak: Now dragon hide need 9 sheets to make dragon ripley, as intended before.
/:cl:

Fix undestrictible armor from attachable armor

---

code/game/objects/items/devices/radio/radio_objects.dm
code/game/objects/items/devices/uplinks.dm

Re-opens [PR](https://github.com/ParadiseSS13/Paradise/pull/25554) 
We've been testing this change on our downstream for a while now before the Alt+Click update came out, and we found an issue where someone (accidentally or on purpose) presses Alt+Click on Uplinks and speaks into a public channel and no one realizes how it happens and complains about it. This PR fixes this issue and also adds Ctrl+Shift+Click for broadcasting, which has already been tested on our downstream and this update went well.
More functions, less bugs.
Tested in-game
:cl:
add: Added Ctrl+Shift+Click to broadcast for radio
/:cl:

Adds Ctrl Shift Click to radio, fixes issue with uplink

---

code/modules/antagonists/changeling/datum_changeling.dm
code/modules/antagonists/changeling/powers/tiny_prick.dm

If you happen to have any changeling sting prepared, such as extract DNA sting, and you get de-changeling'd, you will no longer have that sting "stuck" in your middle click spot. You will be able to use middle click normally again.
1. Spawn in
2. Changeling myself
3. Prepare the Extract DNA sting
4. De-changeling myself
5. I can use middle click for pointing again
:cl:
Fix: Having a sting prepared when you lose your changeling status no longer makes you unable to use middle click
/:cl:

Having a sting prepared when you lose your changeling status no longer makes you unable to use middle click

---

code/modules/mob/living/living.dm

Fixes mobs on stretchers and chairs getting caught on wall corners.
I tested a lot, and I don't think these lines of code are needed anymore, especially since we've had diagonal movement refactored twice.
Bug bad
https://github.com/ParadiseSS13/Paradise/assets/91113370/7b5a0ed4-822c-4960-95cb-7f599d8ea389
See above.
:cl:
fix: Mobs buckled to chairs and stretchers no longer get stuck on corner walls
/:cl:

Fixes stretchers getting caught on wall corners

---

code/game/objects/items/crayons.dm

Fixes https://github.com/ParadiseSS13/Paradise/issues/20221 - an oversight that allows players to store spray paint cans behind their ears.
It's silly, but a little too silly.
Tried to put a spray can in the ear slots, was not able to.
:cl:
fix: Fixed an oversight where spray cans could be equipped in ear slots
/:cl:

Fixes an Oversight with Spray Paint Cans

---

_maps/map_files/shuttles/emergency_narnar.dmm

Replaces some windows on narsie shuttle with walls, and add some new ones
Also replaces o2 wall locker closer to the shuttle entrance
A strange arrangement of windows, one of which had space underneath it
Plus those who really need an emergency locker will get to it in time.
| Before | After |
| - | - |
| ![StrongDMM-2024-05-20 01 28 47](https://github.com/ParadiseSS13/Paradise/assets/69762909/18272a68-e0f5-4f15-bdc5-f2b64252ecb3) | ![StrongDMM-2024-05-20 01 36 19](https://github.com/ParadiseSS13/Paradise/assets/69762909/def1755f-723d-4207-81aa-a1bd0d11fe0c) |
I'm sure it's fine
NPFC?

Remove some windows from Narsie shuttle

---

code/modules/mining/satchel_ore_boxdm.dm

Fixes https://github.com/ParadiseSS13/Paradise/issues/25544 - a bug within `crowbar_act` for ore boxes. 
Bug bad
Spawned an ore box and used a crowbar on it.
Observed deconstruction of ore box.
:cl:
fix: Fixed an issue that would not allow for the deconstruction of the ore box with a crowbar
/:cl:

Fixes a Bug with Ore Box Deconstruction

---

code/modules/mob/living/simple_animal/bot/secbot.dm

Fixes #25663
The screwdriver check doesn't ever get to this point anymore because of screwdriver_act
bug bad
used my ID on beepsky, unscrewed their cover, screwed it back on, re-locked beepsky. Unlocked beepsky them used harm intent on both a synthesizer and a screwdriver (which attacks beepsky) and got attacked by them.
:cl:
fix: Beepsky will retaliate more reliably when attacked
/:cl:

Fixes beepsky

---

code/modules/mob/living/living.dm
code/modules/mob/living/living_defense.dm
code/modules/mob/living/living_defines.dm
code/modules/mob/living/simple_animal/hostile/retaliate/combat_drone.dm

Adds advanced_bullet_dodge_chance, for admin / mob use
This variable is used for a percent chance signal on mobs, for them to attempt to dodge and step out of a way of a bullet. Ideally to make up for simple mobs not dodging much when running up to someone unlike an actual person, but also for use by admins to make a mob tankier.
Used with a subtype of the proc for malfunctioning combat drones, with an updated text / effect for flavour, as well to show it off.
A system to help mobs dodge bullets could be useful. This system is easy to apply, and can be overiden to function in many ways. Could have them leap farther. Could have them phase out of reality if it is a bluespace thing. Could make them dodge and return fire! Many options, signal based.
Applicable by admins, if they want to make …

Adds advanced_bullet_dodge_chance, for admin / mob use. Applies it to space combat drones

---

code/game/machinery/merch_vendor.dm

Edits an if statement in the Merch Vendor to check for cash inserted for a current transaction instead of the cash stored inside the vendor.
Fixes #25581
Merch Vendor shouldn't disallow card purchases because of a bug
Ran & Compiled Code
Spawned in as QM, purchased an item with my card, inserted cash and bought an item with cash, once all cash was removed from the machine I purchased an item again with my card. I was unable to replicate the bug with the current fix.
:cl:
fix: Cash Purchases no longer break the Merch Vendor
/:cl:

Fixes Cash Purchases Breaking the Merch Vendor

---

code/modules/projectiles/guns/energy/special_eguns.dm

Makes the vox spikethrower less of a hassle to use, with 2 changes.
It no longer fires in a 2 shot burst, making it less likely that you waste a bullet each time you shoot it.
It can now be charged in a charger, so if you find a charger you can reload it, rather than waiting **20 seconds to reload 1 bullet**
The spikethrower is an interesting weapon, which suffers from a classic case of blowing away 20% of it's ammo each time you click with a bonus of a 20 second recharge per shot. If you miss, it will take you 40 seconds to get your ammo back. 
A 357 or ebow are both much more forgiving and generally work better, with the gimic of the vox spikethrower not working well if you don't have ammo for it.
This should keep ebow better for knocking down and recharging, and the 357 still better …

the vox spikethrower no longer 2 shot bursts, and can be charged in a charger

---

code/game/objects/buckling.dm

This PR implements logging for Buckling. It includes the integration of logging features into both the in-game player logs and the game log. 
Logging is important to the administrative process. It helps to provide a better picture of events that have taken place during a round.
Buckled a mob into a chair, then unbuckled it. 
Took control of a mob, buckled and then unbuckled it. 
Reviewed the logs for the intended updates.
NPFC

Adds Logging for Buckling

---

code/game/gamemodes/miniantags/revenant/revenant.dm

Makes revenant code use `TRUE`/`FALSE` instead of 1 and 0
Uses guard clauses a bit more
Moves some variables around
Code standardization
Used my abilities - note, are they supposed to show 0 info that you first have to click them once to unlock them?
Saw that the iconstates of the revenant were working fine
NPFC

Cleans up revenant code

---

code/modules/instruments/objs/items/instrument_items.dm
code/modules/instruments/objs/structures/piano.dm

Re-opens PR #15632
Adds more sound presets to the instruments ingame.
* **Piano:**
_Piano | FluidR3 Grand Piano | Crisis Grand Piano One | Crisis Bright Piano One_
* **Guitar:**
_Guitar | Crisis Steel String Guitar | Crisis Nylon String Guitar | Crisis Clean Guitar | Crisis Muted Guitar_
* **Glockenspiel**
_Glockenspiel | Crisis Vibraphone_
* **Accordion**
_Accordion | Crisis Accordion | Crisis Tango Accordion_
* **Trumpet:**
_Trumpet_ (Changed from Trombone)
* **Trombone:**
_Trombone | Crisis Trombone_
* **Xylophone:**
_Xylophone | Crisis Vibraphone_
* **Gilded Bike Horn:**
_Bikehorn | !!HONK!!_
<details>
<summary>Old sounds</summary>
* **Piano:**
_Piano_
* **Guitar:**
_Guitar_
* **Glockenspiel**
_Glockenspiel_
* **Accordion**
_Accordion_
* **Trumpet:**
_Trombone_
* **Trombone:** …

Adds the alternate soundsfonts to appropriate instruments outside of the synthesizer.

---

code/modules/reagents/chemistry/reagents/drugs.dm

All drugs (bar meth) have had their scaling drug downside chance halfed. This means downsides happen at half the probability now, requiring twice the drugs to reach the same downside level.
Consumption decay rate remains the same, so fully recovering from the really heavy downsides by extention if you now reach it, takes twice as long.
Meth is adjusted to 70% rather than 50%. This with luck will have people try some other drugs, while also still making meth less harsh.
Arsnep had it's toxin damage lowered since it really has to be combined with another drug to work well.
Mephedrone no longer does enough brain damage to ipcs to make them fall asleep in combat.
Instead, it does scaling brute damage when overdosing. It's power use has been tweaked to not drain an IPC out of power in the …

Halfs the probability for scaling drug downsides. Makes mephedrone less harsh on ipcs

---

code/game/sound.dm

Fixes an old bug imported from TG by #15608, where we try to calculate sound falloff at or below the minimum falloff distance.
Bugs bad.
It compiles.
:cl:
fix: Fixed a bug that could cause sounds to not play or play too loudly at close range.
/:cl:

Don't try to calculate sound falloff at or below the minimum distance.

---

code/game/objects/items.dm

fixes vortex parry arm unable to perfect parry, as I added an uneccicary check to the signals for hit reaction
We do not need to check if something is true when it is greater than one, as it will already be true.
Bugs bad, parry arm shoudl work
Parried and perfect parried with vortex.
Parried with shield.
Blocked with shielded suit
Blocked with teslawall module
:cl:
fix: fixes vortex parry arm unable to perfect parry
/:cl:

fixes vortex parry arm unable to perfect parry

---

code/game/machinery/cell_charger.dm
code/game/machinery/recharger.dm
code/modules/power/apc/apc.dm
code/modules/power/lights.dm
code/modules/power/powernets/local_powernet.dm

This PR sets powernets' APC when the APC is initialized. This wasn't getting set _anywhere_, even for station areas, but that wasn't noticeable because changes in power availability would cause power_change() calls for the affected powernet's machines. This means that machines installed in an unpowered area will be reliably powered when an APC is installed and charged.
This allows us to make it so that powernets without APCs qualify as having no power. This is meant to be the case but the proc in question skipped over ensuring the presence of an APC and went straight to checking whether the channels were enabled, which they are by default.
It also switches lights and chargers to using this proc so they can't avoid the check either. Again, this wasn't noticeable because when the APC runs …

fix: fix APC behavior in unpowered areas

---

code/modules/admin/reagents_editor.dm

This provides logging and alerts other admins when an admin uses VV to edit reagents in a target.
Provides accountability and improves administrative capabilities. 
Added, removed, edited, reagents inside of a reagent container.
Forced a reaction inside of a reagent container.
Checked that the new message and logs were working properly.
NPFC

Adds Admin Logging and Messages to Edit Reagents in VV

---

code/game/objects/items/weapons/storage/boxes.dm

Removes Synthflesh Patch and Epinepherine Autoinjector from ERT Survival Box.
Gives ERT Survival Box the survival medipen (same one as mining gets, and crew on deluxe box shift).
Now that the ERT Box no longer starts with 8 items, makes it only store 7 items, like god intended.
The synthflesh patch is pretty shit ever since we made patches slowly put reagents inside of you instead of doing an on-touch reaction. Also, if Nanotrasen gives these to all their employees on deluxe emergency box shifts, then by god they can at least give it to their well equipped response teams.
This means that while response team members won't all be equipped like medics (except the medics), they at least won't spawn with practically zero healing and might have a chance to survive an ambush before they can raid …

Replaces ERT Synthflesh with Survival Medipen

---

code/modules/reagents/chemistry/reagents/medicine.dm

Makes synthflesh heal 1 brute and 1 burn per cycle. This mostly affects patches but will cause automenders to heal slightly more
Styptic powder and silver sulfadiazene are great in patches because they heal 2 of their respective damagetype while in the system, even with the small amounts that patches inject
Synthflesh didn't have this so it was heavily outgunned in terms of healing in patchform, making the synthflesh patches that ERT and other Centcomm jobs get a pure meme
This was after dealing 75 brute and 75 burn damage to myself
See above
:cl:
tweak: Synthflesh now heals 1 brute and 1 burn for each cycle that it is inside of you. Mostly affects patches which will now heal a lot more
/:cl:

Makes synthflesh patches heal more 

---

code/modules/clothing/head/misc_hats.dm
code/modules/clothing/suits/misc_suits.dm

Makes it so that the replica black and red space suit actually uses the proper species sprite sheets for grey, vulp, taj and vox.
Seeing a Vox with a beak sticking out of a helmet sprite is annoying.
Spawn in a bunch of species
Put a replica suit on
Looks alright.
:cl:
fix: Replica syndicate space suit uses species sprite sheets.
/:cl:

Replica syndicate space suit uses species sprite sheets.

---

code/__HELPERS/trait_helpers.dm
code/controllers/subsystem/SSspacedrift.dm
code/game/turfs/space/space_turf.dm

Fixes #13574.
You can now drag people/objects across z-levels again.
Objects/people undergoing spacedrift will now have a smooth animation, instead of a janky one.
Also fucking finally removes the sleep(0) from /turf/space/entered because its fuckin useless. No need to wait. One step closer to `forceMove` being able to be a non-sleeping proc
Removes scuffedness, adds smoothness
https://github.com/ParadiseSS13/Paradise/assets/91113370/b3d74089-0923-4ef5-909a-3cf66c7a14c5
See above
:cl:
fix: You can now drag things across z-level boundaries again
tweak: Space drifting is now smoother
/:cl:

Fixes z-level dragging and smoothes space drift

---

code/game/objects/items/weapons/storage/belt.dm

This PR adds the handheld defibrillator (yellow one used to restart hearts) to the list of exception of the bluespace belt, allowing it to fit inside.
the bluespace belt is research-locked between fairly high levels and is supposed to be an upgrade to *most* belts, but it cannot hold the handheld defibrillator like the medical one can, which is a big downgrade from the medical one, since most medical doctors will have atleast one (if not two) handheld defibs on their belt.
Threw a bunch of handheld defibrillators in a bluespace belts, worked
Tried to throw a bunch of other normal-sized objects, like stunbatons, didn't work
:cl:
tweak: The bluespace belt has been upgraded to be able to hold handheld defibrillators now
/:cl:

bluespace belt fits handheld defibs now

---

code/datums/status_effects/debuffs.dm
code/game/gamemodes/miniantags/guardian/types/healer.dm
code/modules/reagents/chemistry/reagents/medicine.dm

- Sleeping in coffin as Vampire now heal your clone loss and allow to heal from crit, curing oxy damage and heart failure, making coffin a canonically good thing to use as vampire. I never believed that fool, who told me after few seconds on sun you will be permanently injured for the rest of your eternal life.
- Holoparasite healer now heal you from ALL possible damage in the game, adding heal 1 clone per tap. This is slow, but clone damage is intended to be hard damage to heal.
- Nanocalcium injector now heal you 60 clone damage. Cheap one-use version of holopara. For 10 TC being possible not goes into medbay seems fair.
Right now decloner is impossibly powerful weapon, deals permanent damage which can be healed once you give up and go to medbay, where always patrolling one or two sec, …

Add few ways to heal clone damage as Traitor and Vampire

---

code/__DEFINES/_click.dm
code/modules/mob/living/simple_animal/hostile/megafauna/megafauna.dm

Making megafauna mouse opacity stick to its icon than its size. That means that you will click megafauna only if you actually click its icon, not the 3x3 tile box which its icon size is.
I wonder why it even was used for such massive objects with big sprites as megafauna.
If you ever played as megafauna on some events, you might have find that your icon is weird, its much bigger than it looks like, you nearly always attack yourself in melee. This setting was making it, your icon was basically 3x3 box, forget about visual. And also all mobs are hidden behind that 3x3 box because your layer is above them.
If there is an item or a mob behind the megafauna and you want to interact with it, you will fail because megafauna 3x3 box covers most in game objects.
This fix makes megafauna icon …

Lowering megafauna mouse_opacity

---

code/datums/diseases/zombie_virus.dm
code/game/gamemodes/game_mode.dm
code/game/objects/items/weapons/manuals.dm
code/modules/admin/player_panel.dm
code/modules/antagonists/zombie/datum_zombie.dm

Adds wikipage to zombies now that they have a page. Fixes some bad spacing in the zombie manual too.
Fixes zombies being incurable because of an oversight... oops.
Wiki good
:cl:
fix: Zombies' now get their wikipage linked to when you become a zombie
fix: Zombies can be fully cured now. Oops.
/:cl:

Adds wikipage to zombie antag datum + minor fix

---

code/modules/power/apc/apc_construction.dm

This PR fixes the wording of the description for removing malf boards from APCs.
Bad grammar bad
Proofread message.
:cl:
spellcheck: Fixed the description for removing malf boards from APCs.
/:cl:

grammar: fix malf apc board removal message
