ParadiseSS13/Paradise

code/__HELPERS/icon_smoothing.dm, code/controllers/master.dm, code/game/dna/dna_modifier.dm, code/game/gamemodes/miniantags/guardian/types/healer.dm, code/game/machinery/cryopod.dm, code/game/machinery/machinery.dm, code/game/mecha/mecha_topic.dm, code/game/objects/items/devices/radio/radio_objects.dm, code/game/objects/items/weapons/flamethrower.dm, code/game/objects/items/weapons/tape.dm, code/game/objects/objs.dm, code/game/objects/structures/noticeboard.dm, code/game/turfs/simulated/floor/lava.dm, code/game/turfs/space/space_turf.dm, code/game/verbs/ooc.dm, code/modules/antagonists/changeling/powers/apex_predator.dm, code/modules/clothing/gloves/misc_gloves.dm, code/modules/mob/living/carbon/human/human_update_icons.dm, code/modules/mob/living/silicon/ai/ai_mob.dm, code/modules/mob/living/simple_animal/bot/ed209bot.dm, code/modules/mob/living/simple_animal/hostile/syndicate_mobs.dm, code/modules/mob/living/simple_animal/slime/slime_mob.dm, code/modules/paperwork/faxmachine.dm, code/modules/paperwork/paper_bundle.dm, code/modules/surgery/organs/organ_datums/lung_datum.dm, tools/ci/check_grep2.py
Conditionals with unnecessary outer parenthesis are now banned, I've also updated the failures for the other conditionals to be more explanatory.
Code review is easier
Catches shit like this
Compiles, check the commits for the testing of the CI
NPFC
=> More CI for conditionals

code/modules/surgery/dental_implant.dm
dental implant runtime fix
Fixes #23732 
Runtime bad
Spawned in, inserted pill, no runtime, functions as intended
:cl:
fix: Fixed dental implant runtime
/:cl:
=> Dental Implant fix

_maps/map_files/RandomRuins/SpaceRuins/listeningpost.dmm
Pretty much what the title says
fixes #23141 
so you can use the message monitoring console and stalk people's PDA messages
spawned as a explore and checked if the monitorkey was there at the listening outpost
:cl:
Add: Adds a monitorkey to listening outpost since it was forgot about
/:cl:
=> Adds a monitorkey to listening outpost that was forgotten about 

code/__HELPERS/type2type.dm
Changes the degrees a circle has from 365 to 360, major balance change
Idk the math guy said it worked or smt
I counted all degrees
tweak: Major balance change: 5 degrees have been removed from all circles
=> Makes circles have a correct 360 degrees again

.github/CONTRIBUTING.md
Adds Henri215 to the review team
Its not.
- Only used one of my eyes to verify the changes.
NPFC (Noteworthy Patch From Contributor)
=> Adds Henri215 to the review team

code/modules/surgery/organs/augments_internal.dm
Fixes hackerdeck shenanigans
We have fun here sir.
Hacked out, hacked in.
:cl:
fix: Fixed a hackerdeck exploit
/:cl:
=> [s] no unfun allowed

.github/CONTRIBUTING.md, code/__HELPERS/unsorted.dm, code/_onclick/hud/parallax.dm, code/datums/station_traits/negative_traits.dm, code/game/gamemodes/miniantags/guardian/guardian.dm, code/game/gamemodes/nuclear/nuclearbomb.dm, code/game/gamemodes/wizard/spellbook.dm, code/game/objects/items/devices/traitordevices.dm, code/game/objects/items/weapons/rpd.dm, code/modules/admin/verbs/randomverbs.dm, code/modules/atmospherics/machinery/airalarm.dm, code/modules/library/library_computer.dm, code/modules/lighting/lighting_atom.dm, code/modules/mining/equipment/survival_pod.dm, code/modules/mob/dead/observer/spells.dm, code/modules/mob/living/carbon/human/species/_species.dm, code/modules/mob/living/silicon/robot/drone/drone_manufacturer.dm, code/modules/power/engines/supermatter/supermatter.dm, code/modules/power/gravitygenerator.dm, code/modules/reagents/chemistry/reagents/medicine.dm, code/modules/reagents/reagent_containers/glass_containers.dm, code/modules/recycling/disposal.dm, code/modules/surgery/organs/augments_internal.dm, code/modules/surgery/organs/brain.dm
Removes comparisons to true and false, updates the contributing document to disallow for comparing to true/false unless you are using an external program (such as js or sql)
Also removes a mention of goonchat in the contributing guide
Code quality good. There should never be a situation where you actually need to compare to true/false rather than looking for value or novalue
Compiled and ran this
=> Removes comparisons to true and false

code/modules/tgui/tgui_panel/tgui_panel.dm
Restricts the visibility of some variables in the TGUI panel to admin only
This information should only be admin accessible
VVed the panel in game
=> Restricts the visibility of some variables in the TGUI panel

code/__DEFINES/martial_arts.dm, code/modules/martial_arts/martial.dm, code/modules/mob/living/carbon/human/species/_species.dm
Fixes an issue with limited martial arts like chef's CQC, where they would block all hand actions outside of the kitchen. This was broken by #24083
Bug bad, really bad.
Hugged a skrell outside of the kitchen as a chef
:cl:
fix: Chefs and bartenders should be able to use their hands outside of the kitchen and bar again.
/:cl:
=> Fixes an issue with limited martial arts

code/game/machinery/teleporter.dm
Having a min time of zero is bad when it can loop
Server Stability good
Compiles, not able to instantly teleport
Player facing changes, but they really shouldnt know about them.
=> [s] Prevents some weird stuff

code/datums/spell_targeting/clicked_atom.dm, code/datums/spells/wizard_spells.dm
Fireball no longer will be casted if you click something that is not turf or not being on the turf
It still spams "No suitable target found." but since most spell procs has `SHOULD_NOT_OVERRIDE(TRUE)` im not changing that.
You will need to disable spell and then open the backpack, but at least it wont explode you
Wizard exploding himself because he opened his backpack is not something we really need
This is unexpected behaviour that just ruining Qwerty's wizard runs
Compiled, tried fireballing objects, tried opening backpack and clicking items with active fireball spell
:cl:
fix: Fireball no longer explodes you when you click backpack or other items on you
/:cl:
=> fireball fix

code/game/area/ss13_areas/medical_areas.dm
Removes the "/area/station/medical/patients_rooms2", not being utilized on any maps.
Introduced by https://github.com/ParadiseSS13/Paradise/pull/24026, which got merged before the author could remove it.
Compiled
NPFC
=> Removes one map area that is not being utilized

code/modules/clothing/suits/misc_suits.dm, code/modules/customitems/item_defines.dm
Fixes a couple of suits that would be invisible on some species (Military jackets and military jackets on Grey, Kidan and Drask.)
Fixes: #23768
Fixes: #24062
Fixes: #23751
Invisible clothing is bad.
Spawn in all the jacket subtypes and put them on all the species.
They are no longer invisible.
:cl:
fix: Leather jackets are no longer invisible on Grey, Kidan and Drask
fix: Military jackets are no longer invisible on Grey, Kidan and Drask
/:cl:
=> Fixes invisible suits on Grey, Kidan and Drask

code/modules/customitems/item_defines.dm, code/modules/mob/language.dm, code/modules/mob/living/silicon/robot/robot_mob.dm, code/modules/mob/living/simple_animal/bot/secbot.dm, code/modules/mob/mob.dm, code/modules/mob/new_player/new_player.dm, code/modules/paperwork/carbonpaper.dm, code/modules/paperwork/silicon_photography.dm, code/modules/pda/ai_pda.dm
Removes set src in usr and set src = user
Implied by the compiler
Took an AI photo in game, checked my known languages6
NPFC
=> Removes unneeded verb settings

code/modules/mob/living/carbon/alien/alien_base.dm, code/modules/mob/living/carbon/human/human_mob.dm, code/modules/mob/living/simple_animal/bot/cleanbot.dm, code/modules/mob/living/simple_animal/bot/floorbot.dm
fixes https://github.com/ParadiseSS13/Paradise/issues/24059 caused by https://github.com/ParadiseSS13/Paradise/pull/23162 (oops, again)
Seperated from https://github.com/ParadiseSS13/Paradise/pull/23900
Meant for easier / faster merge
Emagged secbots should actually do something ya know
Local Server
Spawn jobs like cap, hos, engineer
Emag beepsky
:cl:
fix: emagged secbots not working
/:cl:
=> Fixed emagged secbots being broken

code/modules/mob/living/simple_animal/bot/floorbot.dm
Seperated from https://github.com/ParadiseSS13/Paradise/pull/23900
Meant for easier / faster merge
Fixes floorbots not consuming floor tiles and just keep making them
This is caused by any other setting with process_type existing.
Seperate PR from the refactor PR in hopes of this getting merged / fixed faster
BUG FIX
Local server
Feed it tiles
:cl:
fix: Floorbot not consuming floor tiles
/:cl:
=> Floorbot Eat_tile bug fix

code/game/objects/items/devices/scanners.dm
Fixes a logic error preventing normal organs from ever being seen by a cyborg analyzer
Bugs are bad
Checked to make sure IPCs do in fact have brains
:cl:
fix: Cyborg analyzers display organs correctly
/:cl:
=> Cyborg analyzers can see organs again

code/datums/diseases/_MobProcs.dm, code/datums/diseases/_disease.dm, code/datums/diseases/advance/advance.dm, code/modules/reagents/chemistry/reagents/food_reagents.dm, code/modules/surgery/organs/heart.dm
Fixes "????" making you vomit too much
Stop vomiting over the kitchen is good
Only vomited once when repeatedly eating my perfectly fine dishes
:cl:
fix: Fixes an issue where you could vomit too much when eating something that had "????"
/:cl:
=> Fixes "????" making you  vomit more than normal

code/controllers/subsystem/SSjobs.dm
Fixes a runtime that happens when an ERT gets called in
'ate runtimes, 'ate bugs
Joined an ERT, got a bank account
:cl:
fix: ERT members now have bank accounts again
/:cl:
=> Fixes an ERT runtime

code/game/objects/effects/decals/Cleanable/misc_cleanables.dm, code/game/objects/effects/effect_system/effects_foam.dm, code/game/objects/effects/effect_system/effects_smoke.dm, code/game/objects/items/weapons/extinguisher.dm, code/game/objects/items/weapons/tanks/watertank.dm, code/modules/mob/inventory_procs.dm
Refactors the atmos firefighting backpack to be a bit more sane, and some other slightly related code to use the `TRUE/FALSE` defines
Code following guidelines good
Tested if the metal foam still worked correctly, the nanofrost still moved and welded vents, water still did water things and if it could refill in every mode
NPFC
=> Refactors the atmos watertank backpack

code/_onclick/hud/alert.dm, tools/ci/check_grep2.py
Check_grep2.py errors now use github actions errors syntax when running on github
You get cool in-file errors, showing anyone viewing the code where the errors without having to dive into the CI.
In-line errors! Pretty cool.
See above.
NPFC
=> Check_grep2 errors now use github actions errors syntax

code/game/dna/dna_modifier.dm, code/game/gamemodes/miniantags/abduction/machinery/experiment.dm, code/game/machinery/Sleeper.dm, code/game/machinery/adv_med.dm, code/game/machinery/cryopod.dm, code/game/machinery/rechargestation.dm, code/game/machinery/suit_storage_unit.dm, code/modules/atmospherics/machinery/components/unary_devices/cryo.dm, code/modules/food_and_drinks/kitchen_machinery/gibber.dm, code/modules/recycling/disposal.dm
There is a problem with the fact that when putting someone in a machinery, grab does not disappear instantly, which can lead to some ***tricky*** things. This really needs to be fixed.
Tricks no more.
Burned and gibbed several tajarans while testing most of the fixed machinery. Well, I couldn't repeat the tricks.
:cl: Maxiemar
fix: Fix putting someone into a machinery with active grab
/:cl:
=> [MAJOR] Fix putting someone into a machinery with active grab

code/game/objects/items/weapons/cigs.dm
Makes cigars not being lit by everything
Resolves #24219
Cigars can only be lit by civilized means.
Couldn't light a cigar with a cheap ligher, could with a zippo
:cl:
fix: Fixed cigars being lightable by everything that emitted heat
/:cl:
=> Fixes cigars being lightable by everything

.github/CONTRIBUTING.md
updates the contributing guide to disallow for direct var access from function returns
we already have a CI for this!
=> updates the contributing guide to disallow for direct var access from function returns

code/modules/mob/living/silicon/ai/ai_mob.dm
Just provide existing icon and apply some formatting.
Now we see AI's carp, bugs are bad.
:cl: Maxiemar
fix: Fixed invisible carp hologram for AI
/:cl:
=> Fix invisible carp hologram for AI

code/modules/reagents/chemistry/reagents/alcohol.dm
Ahdomai's Eclipse lowers tajaran body temperature, but now they don't even consume it. Let's fix it.
... bug bad
I'm cold and drunk.
:cl: Maxiemar
fix: Fixed non-consumable Ahdomai's Eclipse
/:cl:
=> Fix non-consumable Ahdomai's Eclipse

code/modules/mob/living/simple_animal/hostile/headslug.dm, code/modules/surgery/organs/organ_external.dm
=> [S] fixes a headslug exploit

code/modules/projectiles/projectile/magic_projectiles.dm
fireballs have immolate set to 6, so they grant 6 firestacks and light on fire on a direct hit.
This means one must stop drop and roll twice to put it out, making up for when it used to hard stun.
If you are hit by a fireball, you should catch fire.
Makes fireballs 27.8% less disapointing.
fireballed many skrell
:cl:
tweak: Fireballs now always light people on fire on a direct hit, and will require stop, dropping, and rolling twice to put out
/:cl:
=> Fireballs now always light people on fire on a direct hit

code/modules/surgery/organs/augments_arms.dm
Allows you to retract arm implants if you are cuffed
1. This breaks things
2. Really it breaks things, this is not good
3. Allows you to panic retract an implant if you are somehow cuffed
Installed shell launcher, extended it, cuffed myself, retracted it
:cl:
tweak: You can now retract (arm) implants while you are cuffed
/:cl:
=> Allows the retraction of arm implants while cuffed

code/modules/mob/living/simple_animal/bot/floorbot.dm
Seperated from https://github.com/ParadiseSS13/Paradise/pull/23900
Meant for easier / faster merge
Fixes floorbots building in space when they should not
**LMAO**
This wasnt supposed to happen
Tested in aformention pr
:cl:
fix: Floorbot building in space
/:cl:
=> Fixes Floorbots building in space

code/modules/surgery/organs/heart.dm, code/modules/surgery/organs/lungs.dm
Switches some organ datum stuff to defines
Code improvement
compiled, the defines are the exact same
NPFC
=> Switches some organ datum stuff to defines

code/modules/martial_arts/judo.dm
Fixes judo not having an explanation footer
fix good
compiles
:cl:
fix: Judo's explanation verb now has a proper footer.
/:cl:
=> Fixes judo not having an explanation footer

code/modules/mob/living/simple_animal/friendly/cat.dm
Fixes #24222
Kittens shouldn't scoot around on their butts al the time.
Spawned a kitten.  Sat.  Stood.  Lay down.  Stood again.  Sprites all worked as expected.
:cl:
fix: Kittens no longer get permanently stuck on their "sitting" sprite the first time they sit down.
/:cl:
=> Set the kitten's resting sprite properly

code/modules/tgui/modules/law_manager.dm
Fixes a bug where you would be unable to edit the text of laws in the law manager as a borg/AI/admin.
Fixes: #24314
Fixes: #24292
Runtime bad.
Be an emagged borg.
Edit a law and add it, it works.
:cl:
fix: Law manager can once again edit and add laws properly.
/:cl:
=> Fixes runtime adding/editing laws in law manager

code/modules/reagents/chemistry/machinery/chem_master.dm
Adds the following reagents to ChemMaster's safe list, allowing patches made with them(or along with other safe reagents) to be applied instantly.
- Diphenhydramine - Antihistamine. No overdose limit or overdose effects. Causes tiny amounts of drowsiness but overall pretty safe
- Ephedrine - Similar to Epinephrine but has a higher overdose limit(35u).
- Iron - No overdose limit or overdose effects. Completely safe
- Sanguine Reagent - Restores blood but has an overdose limit of 15u. Somewhat safe. Can be retracted from the PR if requested
All of the aforementioned reagents(apart from Ephedrine, which is 0.3u/cycle) have a metabolism rate of 0.4u/cycle. Putting them in patches has the benefit of making them last longer, as well as benefiting from instant application
Created a patch from …
=> Add New Reagents to ChemMaster's Safe List

code/game/mecha/equipment/weapons/weapons.dm, code/modules/mining/machine_vending.dm, code/modules/mod/modules/modules_supply.dm
Adds a new item to the game for miner mechs, the "Little Boy" Mining Grenade Launcher. This grenade launcher is a slightly enhanced version of the grenade launcher from the Miner's MODsuit. A little more radius, a little more damage, but most importantly it's a module that allows mechs to fire Lavaland's coolest weapon. It is purchased in the miner's store for 3000 points in the "Digging Tools" section and costs a HUGE amount of energy per shot, so you need a powerful battery, or better yet, a generator to spam it.
"Mechs are people too" And have every right to have similar armament on their vehicle. Especially when it comes to really cool weapons. 
Sadly not sprite yet, but it will be later when spriter draw it
Like main version, you cant fire it in good pressure 
You can shoot it twice …
=> ADD: New weapon - Mining Grenade Launcher

code/game/objects/items/weapons/storage/firstaid.dm
Healing people is good with working patch packs,
Fixes #24070 
You can now heal your fellow crew with working patch pads
Harmed a skrell and healed them with patch packs
:cl:
fix: Patch packs can now apply patches again
/:cl:
=> Fixes patch packs dont work

code/_compile_options.dm, code/modules/unit_tests/test_runner.dm
Adds a new LOCAL_UNIT_TESTS define to run unit tests locally, which will be output to a file automatically, with 100 map errors instead of 20.
Makes it easier for people to run their unit tests locally
I want to see if dreamchecker checks if UNIT_TESTS is redefined
NPFC
=> Adds a helper for running unit tests locally

code/game/objects/items/weapons/stunbaton.dm
Makes attack aniumation if baton is toggled off
red little message in chat with no animation is weird as you actualy prod the target
Compiled
:cl:
tweak: Prodding someone with turned off baton will now do animation
/:cl:
=> Makes attack animation if baton is toggled off

code/game/objects/structures/false_walls.dm, tools/ci/check_grep2.py
Makes Check Grep output line numbers again
Fixes this oversight
NPFC
=> Makes Check Grep output line numbers again

code/modules/reagents/chemistry/machinery/chem_master.dm
Fixes attacking chemmasters when unwrenching them. Fixes #24337
bug
wrenched a chemmaster, also hit it with some other stuff
:cl:
fix: Chemmasters will no longer be hit when unwrenching them.
/:cl:
=> Fixes attacking chemmasters when unwrenching them

code/modules/hydroponics/hydroponics_tray.dm
Makes tray irrigation work again, alongside a heavily needed code cleanup
Resolves #24340
It's an intended mechanic, I broke it so I fix it again in this PR
To the left I added 40 units of robust harvest, and to the right only 10 units of robust harvest
See above
:cl:
fix: Fixed hydroponic tray irrigation not working
/:cl:
=> Fixes hydroponics tray irrigation

.github/workflows/ci.yml, _build_dependencies.sh, code/modules/surgery/organs/heart.dm, tools/ci/annotate_dm.py, tools/ci/annotate_dm.sh
Upgrades out SpacemanDMM suite to 1.8 ([515 support](https://github.com/SpaceManiac/SpacemanDMM/releases/tag/suite-1.8))
Somewhat of a revert of #24200 since it kinda replaces the entire thing.
And replaces this CI
It pipes the errors into standard out, which is then piped into the python script. Read more from where it was [ported](https://github.com/tgstation/tgstation/pull/78225).
See the "testing commit" commit.
NPFC
=> Upgrades SpacemanDMM + Dreamchecker CI

code/modules/mob/living/brain/brain_emote.dm
Fixes my favorite exploit
I didn't know this was an exploit, my bad yall
Robobrains and MMIs both worked as expected
=> Fixes an exploit with robobrains

code/modules/admin/holder2.dm
Deletes some unused vars
code maintenance  
compiled
NPFC
=> Deletes some unused vars

.github/workflows/ci.yml
Turns CI on for testing purposes here
=> Enables CI on merge queue test branch

code/modules/antagonists/changeling/datum_changeling.dm
=> Stinky clings

code/modules/antagonists/changeling/datum_changeling.dm
=> adds z's to clings

_maps/map_files/cyberiad/cyberiad.dmm
=> lava medbay cyberiad

code/modules/antagonists/changeling/powers/become_headslug.dm
=> adds more uses of the cling headslugged var

code/modules/antagonists/changeling/datum_changeling.dm, code/modules/antagonists/changeling/powers/absorb.dm, code/modules/antagonists/changeling/powers/become_headslug.dm
=> removed headslugged var

code/modules/antagonists/changeling/datum_changeling.dm, code/modules/antagonists/changeling/powers/absorb.dm, code/modules/antagonists/changeling/powers/become_headslug.dm
Merge queue test PR, please ignore.
=> [s] Merge queue test - Remove headslugged var

code/game/objects/items/tools/wrench.dm
```
//PR
/obj/item/pr
name = "PR"
gbp_adjust = 0 //done for balance reasons, making the PR high value for GBP, but complex to code
comments_removed = 3 //might or might not be too high, subject to change
```
Useless comments take up mental attention without providing any real value.
It compiled.
NPFC
=> Removed a few not-useful wrench comments.

code/game/gamemodes/miniantags/pulsedemon/pulsedemon.dm
fixes a bogus runtime
this is OK to override
Compiled
=> fixes a bogus runtime

_maps/map_files/RandomRuins/SpaceRuins/moonoutpost19.dmm
Removes the codes of this safe from captain's "safe codes" paper.
Fixes #24298.
Less confusing, cool.
Locally, yes.
:cl: Maxiemar
fix: Removed the codes of Moon Base 19 safe from captain's "safe codes" paper.
/:cl:
=> Make the safe at Moon Outpost 19 be unknown to captain

code/modules/hydroponics/hydroponics_tray.dm
Fixed #24338
Grass shouldn't take an arbitrarily-long time to grow
Var-edited a tray to have lastproduce 25.  Grew default grass (maturation 2, production 5).  Was harvestable at ages 7 and 12.
Used a new tray.  Grew grass with production 1.  Was harvestable at ages 3 and 4.
:cl:
fix: Grass grown in previously-used trays will no longer take an arbitrarily-long time to produce its first harvest.
/:cl:
=> Fixed lastproduce initialization for grass.

code/modules/food_and_drinks/food/foods/meat.dm
Removes exploit
Ported from [here](https://github.com/ss220-space/Paradise/pull/4008/files), disscused in Paradise Discord
NPFC
=> [S] Bad cubemonkeys

_build_dependencies.sh
Bumps CI to run on 515.1633, the first 515 stable build.
Make sure our code works on stable BYOND.
=> Bump CI to 515.1633 (515 stable)

code/modules/mob/mob_emote.dm
Prevents bad things from flipping.
No bad things from flipping
Bad things no longer occur
NPFC
=> [s] Prevents bad events from flippin'

code/game/objects/items/robot/items/inflatable_tool.dm, code/game/objects/structures/inflatable.dm, code/modules/mob/living/silicon/robot/robot_modules.dm, paradise.dme
Port of the refactor and new tools from "SS220 WyccStation".
We played with these changes for 2 years and don’t touch them anymore, since we fully tested them for balance, usability and user response. We hope you will like them too and improve the gameplay of robots.
- The engineering module was able to install inflatable walls by generating its own charge. Now this module is more desirable during quarantines and large outbreaks.
Engineering units can now isolate main corridors, explosions from SMA, explosions from meteorites and other holes in the plating. True, this is an expensive pleasure, since it requires a lot of energy, but they will be able to work better on depressurization.
Tested for 2 years on the SS220 WyccStation on live servers.
:cl:
add: Added cyborg engineer inflatable …
=> [BORG UPDATE] Cyborg engineer inflatable walls tool

code/datums/uplink_items/uplink_general.dm
Ups the razorwire price to 20
It's performing better than expected, could be worth the same as a stech.
:cl:
tweak: Ups the razorwire price to 20
/:cl:
=> Ups the razorwire price to 20

code/modules/reagents/reagent_containers/syringes.dm
Syringe should be stopped being sharp.
No more tomato slices and goat butchering.
Syringe seems to be still functional but can no longer cut things.
:cl: Maxiemar
tweak: Syringe can no longer be used as a knife
/:cl:
=> Fix syringe being sharp

code/modules/projectiles/guns/projectile/automatic.dm, code/modules/projectiles/guns/projectile/launchers.dm, code/modules/projectiles/guns/projectile/pistol.dm, code/modules/projectiles/guns/projectile/revolver.dm, code/modules/projectiles/guns/projectile/shotgun.dm, code/modules/projectiles/guns/projectile/sniper.dm, code/modules/research/designs/weapon_designs.dm, code/modules/supply/supply_packs/pack_security.dm
title
It's lorein' time.
Our firearms will no longer be Great Value brand, and will now have some descriptions that tell you what they are and what they're chambered in.
Also done in preparation for Ballistics Extended Descriptions, coming soon(tm) to a codebase near you.
- Loaded in
- Spawned guns
- Names and descriptions are updated
:cl:
tweak: Changed some ballistic weapon names and descs
/:cl:
=> Updates names and descriptions of common ballistics

_maps/map_files/RandomRuins/SpaceRuins/syndie_space_base.dmm, code/modules/library/library_computer.dm
Adds syndie version of library computer with syndie access, which allows syndie boys to print books. The computer at Syndicate Space Base was the only "syndie" one I found and it was the computer the issue was detected with. I think it could be used somewhere else in the future, so I provide subtype.
Syndie boys can print some books.
Works.
:cl: Maxiemar
tweak: Syndicate researchers can print books with library computer at Space Base now
/:cl:
=> Allow book printing in Syndicate

code/modules/reagents/chemistry/machinery/chem_heater.dm
Adds a description to chemical heaters
Did you know they can cool chemicals, too? I didn't, but now that will be more obvious.
See image.
:cl:
add: Added a description to the chemical heater, pointing out that it can cool, too.
/:cl:
=> Added a chem heater description to point out that it can cool, too.

code/game/objects/items/weapons/storage/garment.dm
Adds the CMO's jumpskirt to the CMO's garment bag.
Skirts are cool! No reason not to include it in the garment bag.
Acquired skirt.
:cl:
add: The CMO's garment bag now has a jumpskirt.
/:cl:
=> Adds a skirt to the CMO's garment bag

code/game/objects/structures/stool_bed_chair_nest/alien_nests.dm
Rejuv pods will no longer have their revival fail if used multiple times
The rejuv pod overlay works again
The rejuv pod and alien bed respects the nearby buckle changes
Bugfixes
Buckled a couple aliens
:cl:
fix: Rejuv pods will no longer have their revival fail if used multiple times
fix: The rejuv pod overlay works again
fix: The rejuv pod and alien bed respects the nearby buckle changes
/:cl:
=> fixes some weird stuff with rejuv pods

code/datums/diseases/cold.dm
So, you know how colds say they're fixed by rest, so docs will buckle you to a bed and tell you to sleep? Yeah, sleeping wasn't doing anything to the cold. It was only checking if you were horizontal.
Fixed that.
Sleeping to cure a cold makes sense.
On old code, got cold, buckled self to a chair, slept 5 times. Still sick.
On new code, got cold, buckled self to a chair, slept once. Cured in the first 10s or so.
:cl:
fix: Colds will now be cured if you sleep while buckled to a chair.
/:cl:
=> Re-enable sleeping affecting colds after 8 years.

_maps/map_files/test_tiny/mergequeue_testmap.dmm
merge directly without the queue
=> [s] mergequeue mapmerge test base

_maps/map_files/test_tiny/mergequeue_testmap.dmm
merge directly in so it's master
=> [s] merge queue PR1 as master, merge directly

_maps/map_files/test_tiny/mergequeue_testmap.dmm
=> [s] merge queue PR2 as queue lead

_maps/map_files/RandomRuins/LavaRuins/lavaland_surface_althland_facility.dmm
Fixes some very annoying bugs that are breaking CI.
It turns out that CI running is a good thing! #wow #whoa 
See CI
NPFC
=> Fixes some mapping types which are wrecking CI

.github/workflows/ci.yml
Allows CI to run on creation of a merge group, letting us use the merge queue. More to come down the line once we've wrangled mapmerge!
=> Base merge queue CI stuff

tools/mapmerge2/merge_queue_check.py
Should in theory perform the right merge with the right commits no matter what actually gets passed into the github action but I couldn't get it working locally so idk
Should be run with `.\tools\bootstrap\python -m mapmerge2.merge_queue_check`
=> [s] merge queue check script

code/datums/station_traits/postive_traits.dm
title,
wasn't aware the base cyber lungs were done in a snowflake way my bad
it compiled
:cl:
tweak: Atmos techs get breathing tubes during cybernetic revolution rounds 
/:cl:
=> reverts atmos techs getting cyber lungs during cybernetic revolution rounds

code/game/objects/items/weapons/storage/storage_base.dm
We have broken loadout after #24404, let's make such a silly fix.
Loadout works.
I got a cup.
:cl: Maxiemar
fix: Stuff from loadout can be obtained in the game again.
/:cl:
=> Don't check on adjacency until player is spawned

code/__HELPERS/mob_helpers.dm
Changes "Gener" to "Gender"
gener
NPFC
=> Fixes comment typo

code/modules/mob/living/brain/MMI.dm
The descriptions of the MMI and Syndicate MMI now clearly describe exactly what they are for and what they can do.
Extended descriptions have been added to both items to impart  **D E E P  L O R E**  on those that enjoy that stuff.
Descriptions being descriptive is good. Lore is good.
Spawned MMI and SMMI. Examined them closely. I was told what they did, and some interesting history.
:cl:
add: Added extended descriptions to the MMI and Syndicate MMI.
tweak: Changed descriptions of the MMI and Syndicate MMI.
/:cl:
=> Edits the descriptions of the MMI and SMMI, adds extended description to both

code/modules/antagonists/traitor/contractor/datums/objective_contract.dm
Overrides the contract explanation text with an empty override to stop the stack trace from happening
Less runtimes is better and more readable
I need two clients to test this, I cannot do that when I'm in a round, but this should theoretically work - To clarify, I will test this soon
NPFC
=> Overrides the contract explanation text

.github/workflows/merge_upstream_master.yml
Adds a workflow triggerable by commenting `!merge_upstream` on a PR that merges upstream master into the PR, running hooks and all. Inspired and proven as working over at goonstation.
Easy fix for TGUI conflicts, hopefully also runs mapmerge in a sane way.
=> New user-triggerable workflow for updating a PR from upstream master

code/modules/hydroponics/grown/herbals.dm
Capitalizes Comfrey.
Consistency good.
Examined Comfrey in a hydroponics tray and the seed extractor.
:cl:
spellcheck: The plant comfrey went on a self-confidence retreat and is now Comfrey, just as important as all the other plants. Way to go, Comfrey!
/:cl:
=> Capitalized Comfrey.

code/game/objects/structures/inflatable.dm
Fixes the examine text so that users know to ALT CLICK instead of ALT SHIFT CLICK to deflate inflatable structures.
Descriptions should be correct.
A skrell played with some inflatables, and then deflated them without issue.
:cl:
fix: Fixed wrong description for inflatable structures.
/:cl:
=> Inflatable walls and airlocks now tell you the correct way to deflate them

code/modules/shuttle/shuttle_manipulator.dm
fixes admin shuttles breaking the escape shuttle / not working
We want to send the medship / armory shuttle without breaking the escape shuttle
loaded admin shuttles. Loaded escape shuttles. Ordered shuttles from cargo
:cl:
fix: Fixes admin shuttles breaking the escape shuttle / not working
/:cl:
=> fixes admin shuttles breaking the escape shuttle / not working

code/modules/projectiles/gun.dm
Knife overlay stays after knife removing in some situations, fix it.
Bug bad.
Yes.
:cl: Maxiemar
fix: Gun icons update properly after knife removing.
/:cl:
=> Update gun icon on knife removing

code/modules/tgui/modules/atmos_control.dm
Fixes the bug in the title
Bugs are bad, especially when AIs have a dedicated subsystem for this that they can not longer use.
Yeah
:cl:
fix: Silicons can use the central atmospherics computer again.
/:cl:
=> Fixes silicons being unable to use central atmospherics computer.

code/game/gamemodes/cult/cult_mode.dm
Fixes this
We don't want tracking of the gamemode broken
Compiles, this is a simple logic change.
:cl:
fix: After a cult team wins, it will now show the proper win message instead of "The staff managed to stop the cult!"
/:cl:
=> okay one last time

code/modules/projectiles/gun.dm
Fixes #19651.
Bugs bad.
| Before| After |
|--------|--------|
| <video src="https://github.com/ParadiseSS13/Paradise/assets/39908528/9a76ddcc-27d3-4e16-b7f5-db27ecf161fd" /> | <video src="https://github.com/ParadiseSS13/Paradise/assets/39908528/ac97dbe0-ae3c-4016-bddc-a6aa9569c50f" /> |
:cl: Maxiemar
fix: Fixed flying bayonet/seclight overlays on gun throwing.
/:cl:
=> Fix flying bayonet/seclight overlay

code/game/atoms_movable.dm, code/game/objects/items/devices/radio/electropack.dm
This PR removes some faulty logic in the electropack code, making the shocks always happen instantly. It also removes an unneeded variable from atom/movable
Currently electropack has some weird interactions where you can still get shocked even after putting it down. This fixes those, while also removing it's ability to make you walk forward when signaled (?).
I shocked myself, it happened instantly
:cl:
tweak: Eletropack now always instantly shocks when receiving a signal
/:cl:
=> Electropack works more consistently, and is more responsive.

code/modules/mob/living/simple_animal/friendly/farm_animals.dm
Collar on a chick stay when it grow into a chicken. Fixes #24412
Oversight fix gud
:cl:
fix: Collar on a chick stay when it grow into a chicken.
/:cl:
=> Collar on a chick stay when it grow into a chicken.

code/modules/surgery/organs/augments_internal.dm
fixes syndicate sensory being emp weak
the syndicate version should be emp proof
emp'd syndicate version, emp proof.
emp'd rnd version, stun + 40 units of suffering
:cl:
fix: The sensory cybernetic from uplink is emp proof again
/:cl:
=> fixes syndicate sensory being emp weak

.github/CONTRIBUTING.md
Adds Contrabang to Commit Access
Updating documents good
=> [s] Adds Contrabang to Commit Access

code/modules/projectiles/guns/energy/laser.dm
Gives the proto emitter its own name and description.
Knowing that it's a different item without figuring it out or code-diving is good.
Looked at gun.
:cl:
tweak: Proto emitter has its own name and description.
/:cl:
=> Proto Emitter Gun now has its own name and description

code/modules/paperwork/paper.dm
Increases paper's window from `400x400` to `600x750` (which is pretty close proportionally to 8.5x11)
You can actually format and make paperwork thats readable without being tiny/needing to scroll as much.
Looked at some paper.
:cl:
tweak: increased the size of the paper window.
/:cl:
=> Increases Paper's Window Size

code/game/machinery/rechargestation.dm
[s] Fixes an issue with movement
issue bad
Yes
:cl:
fix: Fixed an issue with movement and charging stations
/:cl:
=> [s] Fixes an issue with movement

code/modules/mob/living/silicon/robot/robot_modules.dm
Fixes an issue I should've noticed
I kinda didn't push the fix for this I guess, that's on me
It didn't work anymore :D
=> [s] Fixes a recharger issue

code/game/gamemodes/wizard/spellbook.dm
Fixes an exploit.
Exploits are bad.
I tried the exploit, it didn't work anymore.
:cl:
fix: Fixed an exploit with wizard loadouts.
/:cl:
=> [s] Fixed an issue with wizard loadouts.

tgui/bin/tgui
It seems I am extremely incompetent, bash and powershell handle directories differently so I should not have blindly applied one to the other.
Stops 
```
./tgui/tgui/bin/tgui --merge=bundle 'tgui/public/tgui.bundle.js' .merge_file_it7pvZ .merge_file_tx5K0t .merge_file_xwn2Qk 7
./tgui/tgui/bin/tgui: not found
```
https://github.com/ParadiseSS13/Paradise/actions/runs/8379140591/job/22945345571
=> Another PR to "fix" !merge_upstream

code/modules/virology/virology_goals.dm
Fixes the first virology goal sometimes being impossible, also i swear everytime my PRs get merged there is a bug found immediatelly
Bugs bad
didnt test, this PR just changes values used in a rand proc
:cl:
fix: Fixes the first virology goal sometimes being impossible
/:cl:
=> Fixes the first virology goal sometimes being impossible

code/game/machinery/clonescanner.dm
Fixes a bug
Resolves #24740 
This shouldn't be a thing
NPFC
=> [s] Fixes a cloning bug

code/game/machinery/clonescanner.dm
Performance!
Game should go vrrooooom
add: Performance!
=> [s] Makes GC slightly faster in one very specific cleanup

_maps/map_files/cyberiad/cyberiad.dmm
why is there 3 of them
why
they're gone
:cl:
fix: Deletes the 2nd and 3rd pun puns. There is only one now.
/:cl:
=> Removes the duplicate pun puns

code/game/objects/items.dm, code/game/objects/items/hand_item.dm, code/game/objects/items/toys.dm, code/modules/mob/living/living.dm
Pointing to a slapper in your hand now states:
`**John Doe** raises their hand!`
It still shows the slapper in the little point blurb that goes above your head, for added attention grabbing.
Little fluff things are nice.
Pointed at my hand.
:cl:
add: Added the ability to raise your hand.
/:cl:
=> Adds Hand Raising

_maps/map_files/RandomRuins/LavaRuins/lavaland_surface_seed_vault.dmm, code/modules/paperwork/paper.dm
Rewrites the terraforming papers to not tell people to anchor down grass patches
Spellchecks the other 2 papers in the spawner ruin
I have answered 2 mhelps about people asking how to anchor down grass, it's not much, but it's still weird that it happened twice
Compiled
:cl:
spellcheck: Fixed the seed vault intro papers' grammar and content
/:cl:
=> Rewrites + spellchecks the seed vault papers

code/modules/clothing/suits/suit_storage.dm
Adds null safety to the pockets of suit storage.
This runtimed when anyone with a labcoat got stuffed into an emagged recycler.
Spawned as scientist for that snazzy labcoat.
"Acquired" an emag.
Emagged the recycler.
Recycled myself.
Didn't runtime.
NPFC
=> Null-safe pockets.

code/modules/mod/mod_construction.dm
Title.
The basic components for building a MOD suit have unique examine text now.
LOOOOOORRRRREEEEEEE.
- Loaded in
- Spawned MOD parts
- Read words
:cl:
tweak: Gave MOD parts actual examine text
/:cl:
=> Gives MOD parts descriptions

code/modules/projectiles/guns/projectile/sniper.dm
title
i forgor this one in the first pr
- loaded in
- rifle
- words
:cl:
tweak: updated syndiesniper's desc
/:cl:
=> Updates the Syndicate sniper's description

code/modules/mob/living/simple_animal/bot/bot.dm
fixes bot menu jumpscares, users are cleared when the window is closed
bugfix
VVed the bot in game
:cl:
fix: Opening a bot menu will no longer have that menu open up randomly throughout the round after it's closed
/:cl:
=> fixes bot menu jumpscares

code/modules/virology/virology_goals.dm
Fixes virology goals adding the amount delivered for every symptom it has until its completed (basically multiplying the amount delivered by the number of symptoms)
bugs bad
in 2 seperate deliveries, delivered a goal with less than 15u and then a goal with more than 15u to make sure i didnt break anything else
:cl:
fix: Fixed virology goals completing even when less than 15u was delivered
/:cl:
=> Fixes virology goals completing even if you delivered less than 15u

_maps/map_files/MetaStation/MetaStation.dmm
Pretty much what the title says
Fixes #24777 
To be able to find a patch pack boxes next to the pill bottles' one like every other station
Spawned as a medical doctor and checked if patch packs and pill bottles were in medical and they were there
:cl:
fix: Fixed a missing patch packs and pill bottles boxes in medical on cerebron station
/:cl:
=> Fixed missing patch pack boxes and pill bottle box In medbay on Cerebron

code/controllers/subsystem/SSjobs.dm, code/game/gamemodes/revolution/revolution.dm
Fixes a weird edge case where headrevs could fail to spawn in
Also adds a bit more of logging if this happens
Prevents weird shit
Compiled, started the game
:cl:
fix: Fixes an issue where headrevs would be assigned, but remain in the lobby
/:cl:
=> Fixes a weird edge case where headrevs could fail to spawn in

.github/workflows/merge_upstream_master.yml, .github/workflows/render_nanomaps.yml
Swaps github's default token for an app token when running certain steps of the `!merge_upstream` workflow.
Currently, running the `!merge_upstream` workflow does not trigger a CI run, which is very annoying, this is due to the following GH policy:
```
When you use the repository's GITHUB_TOKEN to perform tasks, events triggered by the GITHUB_TOKEN,
with the exception of workflow_dispatch and repository_dispatch, will not create a new workflow run.
This prevents you from accidentally creating recursive workflow runs.
For example, if a workflow run pushes code using the repository's GITHUB_TOKEN,
a new workflow will not run even when the repository contains a workflow configured to run when push events occur.
```
This bypasses that on the repository by using an app that (hopefully) has the …
=> Use a github app token, not the default token, to run !merge_upstream workflow actions

.github/workflows/merge_upstream_master.yml, .github/workflows/render_nanomaps.yml
Follow up to https://github.com/ParadiseSS13/Paradise/pull/24822, as it seems setting 
```
env:
GH_TOKEN:
``` 
in one step does not apply it to all steps, which leads to many fails.
=> Another workflow actions PR, I want this hell to end.

.github/workflows/merge_upstream_master.yml, .github/workflows/render_nanomaps.yml
ANOTHER follow up to https://github.com/ParadiseSS13/Paradise/pull/24831, our issues were caused by an action not having a properly configured token. Shout out to https://github.com/orgs/community/discussions/27072#discussioncomment-3254515 for the heads-up
=> (Last one now) Another workflow actions PR

code/game/objects/items/weapons/soap.dm, code/modules/clothing/head/collectable.dm
Removes comdoms. Also the deluxe soap is not made by Waffle Co. anymore because the lore team said so.
Comdom scent is weird. Waffle co are criminals and have been for a while, so it's weird that NT would buy soap from them.
Couldn't smell comdom.
:cl:
tweak: Removed comdom references from deluxe soap and collectable captain hat.
/:cl:
=> Soap is no longer comdom scented. Collectable captain hat doesn't look like a comdom hat.

code/modules/antagonists/changeling/powers/fakedeath.dm
fixes a ling gc issue. we don't want to give them this ability if they're already deleted
GC go vroom
Deleted myself after attempting to rejuv
=> fixes a ling gc issue

code/datums/diseases/_disease.dm
Viruses cured by ethanol now accept any form of booze.
It's much more entertaining to tell the crew "Go get drunk at the bar, doctor's orders!" than "There are ethanol pills in the fridge."
Gave myself severe anxiety.  Drank coffee.  It didn't help.  Drank wine.  Cured.
Gave myself the flu.  Injected spaceacillin.  Cured.
Gave myself GBS.  Drank sulfur alone.  Didn't help.  Drank diphenhydramine + sulfur.  Cured
New character.  Gave myself severe anxiety.  Drank pure ethanol.  Cured.
:cl:
tweak: Diseases cured by ethanol now accept any form of booze, not just pure ethanol.
/:cl:
=> Booze cures anxiety (and other ethanol diseases)

code/game/objects/items/weapons/powerfist.dm
Gives extra feedback to powerfists
Idk otherwise you're slapping them with the powerfist like a glove which is also pretty funny I guess
Didn't work :(
NPFC
=> [s] Fixes a powerfist issue

.github/workflows/merge_upstream_master.yml
There was a lack of null checks in https://github.com/ParadiseSS13/Paradise/pull/24839 leading to errors when the API returned no results.
This caused double comments where there should have been none.
Also stopped execution of the workflow early if these error comments are made.
=> Follow-up patch for "tidies other workflows and adds better logging"

.github/workflows/label_stale.yml
I used `only-issue-labels` instead of `any-of-issue-labels` meaning no labels got matched. I also used v4 of the action not v9, the latest.
🙃
=> Changes all to any when matching labels for stale issues

.github/workflows/ci.yml, code/modules/client/client_procs.dm, code/modules/zoom/engagement.dm, interface/skin.dmf, paradise.dme
As we are all aware, the game can become more un-engaging as time goes by, you grow older, you get burnt out, all sorts of issues surrounding it. You start to lose interest and the game can become boring to play for long periods of time.
Thankfully, I have a solution to rectify this.
**It was this or adding more title music https://youtu.be/sWTA8xUo8uU?si=oZmxTV-FMHYUbfPa**
Engagement good
See above
See above
add: Made the game more engaging
/:cl:
=> [AFD] Increases game engagement

code/game/mecha/equipment/weapons/weapons.dm, code/modules/projectiles/ammunition/energy_lens.dm, code/modules/projectiles/projectile/beams.dm
Do you miss the satisfying sound of a taser? Do you want to relive the days of pre-stun rework without the hassle of losing every fight instantly?
Well, its time for a throwback and for everyone to rejoice in the sound of `taser.ogg`
Funny innit?
Shot a buncha things.
:cl:
tweak: Disablers are now properly scary.
/:cl:
=> [AFD] Upgrades All Disablers to Electrodes

code/modules/admin/admin_verbs.dm
Adds mghost
I think we can trust mentors at this point, this helps them complete tickets properly
https://github.com/ParadiseSS13/Paradise/assets/108773801/a3ac0c1a-4978-4ea5-bd37-209b9f5659ad
See above
:cl:
add: [MENTOR] Adds Mghost
/:cl:
=> [AFD] Adds Mghost

code/modules/mob/living/carbon/human/species/_species.dm, code/modules/mob/living/carbon/human/species/grey.dm
Rebalances most species. You will now feel the pain of the greys every time you draw a fire extinguisher in their direction.
Too long have we had to suffer under the tyranny of the constant extinguisher threats...
:cl:
tweak: Water is now acid to most species. Greys are now the supreme species, as they should be.
/:cl:
=> [AFD] Rebalances Greys.

code/game/jobs/job/supervisor.dm, code/game/objects/items/devices/button.dm, paradise.dme
Adds an alternative way for the station to earn money!
Currently the only ways to earn money are by either waiting or selling the same static items, with this new way you can keep it all fresh!
It worked!
:cl:
add: Adds an alternative cash income source
/:cl:
=> [AFD] Adds an alternative cash source

code/_onclick/hud/fullscreen.dm
Fixes a runtime with screens
Lmao this creates a fuckton of runtimes
Didn't runtime anymore
NPFC
=> Fixes a runtime with screens

code/modules/mob/living/carbon/human/human_login.dm, code/modules/mob/living/carbon/human/human_mob.dm
Nerfs Rurik
hes too strong
Nerfs Rurik
Nerfs Rurik
:cl:
fix: Nerfs Rurik
/:cl:
=> [AFD] Nerfs Rurik

code/game/verbs/ooc.dm, code/modules/client/client_procs.dm, interface/skin.dmf
Reverts ParadiseSS13/Paradise#24929
the people requested it
=> Revert "[AFD] Improves the gameplay quality"

code/controllers/subsystem/non_firing/SStitlescreen.dm, code/game/area/areas.dm, code/modules/mob/living/living_defines.dm
adds loading screens
all the real games have them, why not this one?
my screen loaded
:cl:
fix: Client optimization by preloading areas. it's society's fault the way this change is
/:cl:
=> [AFD] adds loading screens

_maps/map_files/stations/boxstation.dmm, _maps/map_files/stations/cerestation.dmm, _maps/map_files/stations/deltastation.dmm, _maps/map_files/stations/metastation.dmm, code/_globalvars/lists/objects.dm, code/_onclick/hud/fullscreen.dm, code/game/objects/effects/landmarks.dm, code/modules/ruins/ghost_bar.dm
Fixes an issue where the skeleton would be left behind after respawning, keeping the sould on the station
We were only getting flesh husks in the bar :(
My entire body properly respawned!
:cl:
add: Added proper skeleton teleportation
del: Removed improper skeleton teleportation
/:cl:
=> [s] Fixes a respawn bug

code/game/jobs/job/job.dm
Faron is never seen wearing his canon uniform. This is fixed.
Non-canon uniforms break immersion.
Spawned in a maid dress.
:cl:
tweak: Faron now starts in a maid outfit.
/:cl:
=> [AFD] Restores Faron to canon uniform

code/controllers/subsystem/non_firing/SStitlescreen.dm, code/game/area/areas.dm, code/modules/mob/living/living_defines.dm
Reverts ParadiseSS13/Paradise#24930
It's more broke than AA at spoons on sunday
=> Revert "[AFD] adds loading screens"

code/modules/admin/verbs/SDQL2/SDQL_2.dm
why
fixes something
there ain't no way
=> [S]HAHAHAHAHAHAHAHAHA

_maps/map_files/stations/cerestation.dmm
title
shouldn't need to break into your own safe
not visual
works
:cl:
fix: Fixed captain not knowing the safe codes in the vault
/:cl:
=> [s] Fixes captain not knowing safe codes on cerestation

code/modules/mob/living/simple_animal/friendly/farm_animals.dm, code/modules/mob/mob_holder.dm
Adds the scoop up action to chicks
Fixes #24889
Consistency is good.
Was able to collect and place down a chick.
:cl:
add: You can now pick up chicks. Stop laughing.
/:cl:
=> Adds scoop up action to chicks

.vscode/settings.json, tgui/.eslintrc.yml, tgui/bin/tgui, tgui/bin/tgui-prettier.bat, tgui/bin/tgui_.ps1, tgui/packages/tgui/interfaces/PrizeCounter.tsx
Improvements to the TGUI tooling as follows
1. Remove prettier from production bundle build.
2. Enable prettier on save.
3. Apply editor rules to TSX and JSX (Which we don't support, by the way...)
4. Create a separate tgui-prettier.bat that only runs prettier
Faster production bundle build.
Quickly make code readable without running tgui.bat
https://github.com/ParadiseSS13/Paradise/assets/69762909/1908cb3c-c719-4cc3-89e1-8c268544164d
Yeah
NPFC
=> Improves TGUI tooling

code/controllers/configuration/sections/general_configuration.dm, code/controllers/subsystem/SSticker.dm, config/example/config.toml
Title says for itself.
Better configurability.
Set `restart_timeout` to 75 in config, world rebooted after 75 seconds.
Set `restart_timeout` to 15 in config, world rebooted after 15 seconds.
Set `restart_timeout` to -10 in config, world rebooted after 0 seconds.
Removed `restart_timeout` from config, world rebooted after 75 seconds.
NPFC
=> Move default restart timeout to config

code/modules/tgui/tgui_panel/telemetry.dm
Fixed something that keeps annoying me
Annoyance bad
Literally none
NPFC
=> [s] Fix something that keeps annoying me

code/modules/reagents/chemistry/machinery/reagentgrinder.dm
Allows cigarettes and cigars to be ground up.
Pills and patches are also grindable, cigarettes are the odd one out. People ask occasionally about being able to do it.
Got some cigarettes. Ground them up, got nicotine.
Injected chemicals into cigarettes, ground them up, got the chemicals back too.
:cl:
tweak: Cigarettes can now be ground up.
/:cl:
=> Cigarettes and cigars can now be ground up in the All-In-One-Grinder

code/game/world.dm
Ports tgstation/tgstation/pull/81993, see it for details.
time moves again
:cl:
fix: Time on servers hosted outside of the UK should now properly have their timezone offset.
/:cl:
=> Fixes timezone offset

code/game/objects/items/devices/radio/beacon.dm, code/game/objects/items/weapons/storage/uplink_kits.dm
Remade this PR because commits got messed up, see previous comments here https://github.com/ParadiseSS13/Paradise/pull/24285
-----
Adds the Ocelot bundle as an option for syndicate bundles. Contains two syndi revolver, two speedloaders, combat knife, encryption key, a holster, and appropriate outfit. Also fixed the TC cost comments on payday bundle.
Would be a cool reference and addition to syndi bundles, dual wield is fun. You could also trade with a fellow traitor to arm yourselves both. The Holo-cigar item was intentionally *not* part of this bundle for the sake of 1. balance 2. keeping human specific item to humans
Spawned a buncha bundle beacons till I found the new ocelot bundle, spawned it, checked that everything was there.
:cl:
add: Added the Ocelot bundle to syndicate bundle …
=> Adds the Ocelot traitor bundle

code/datums/spells/wizard_spells.dm
In PR #23036 the description said the minimum cooldown would be 15 seconds, but the code was accidentally changed to have a minimum cooldown of 10 seconds.
This probably didn't affect too many rounds luckily, but that's still 5 seconds less, which matters a lot of you have to choose between 10 and 15 seconds of cooldown
It Compiled
:cl:
fix: The minimum cooldown of the blind spell is now 15 seconds as it should've been
/:cl:
=> Makes the minimum cooldown of the blind spell 15 seconds, as it should have been 

code/modules/tgui_input/say_modal/tgui_say_speech.dm
Counts message chars instead of bytes.
No more kicks for a long non-ascii message.
I believe.
:cl:
fix: TGUI-say no longer kicks you for a long non-ASCII message.
/:cl:
=> Use length_char in TGUI-say

code/datums/emote.dm, code/modules/mob/living/brain/brain_emote.dm
Actually fixes the exploit
They bad
Yuh huh
=> [S] Fixes an oversight for a different exploit fix

code/__DEFINES/misc_defines.dm
No reason not to nullcheck this anymore as macros actually do support the ?. operator. Fixes a couple of niche get area runtimes and an issue with scoreboard not always being generated
fixes #25061 
Bugs bad
Trigged it in game via a verb with and without the changed code
:cl:
fix: Fixed field generators not working in rare situations
fix: Fixed the EOR scoreboard not always showing
/:cl:
=> fixes some more get area runtimes

.github/CONTRIBUTING.md, code/__HELPERS/unsorted.dm, code/datums/diseases/kingstons.dm, code/datums/diseases/pierrot_throat.dm, code/game/gamemodes/miniantags/abduction/abductee_objectives.dm, code/game/machinery/suit_storage_unit.dm, code/game/objects/effects/decals/Cleanable/humans.dm, code/game/objects/items/crayons.dm, code/game/objects/structures.dm, code/game/turfs/simulated/minerals.dm, code/modules/antagonists/traitor/contractor/datums/contractor_hub.dm, code/modules/events/ion_storm.dm, code/modules/food_and_drinks/food/customizables.dm, code/modules/holiday/holiday.dm, code/modules/mob/language.dm, code/modules/mob/living/brain/robotic_brain.dm, code/modules/mob/living/simple_animal/hostile/mining/hivelord.dm, code/modules/projectiles/projectile_base.dm
Changes all instances of `pick(list(....))` to `pick(....)`, as it is ever so slightly faster and an example of a bad coding practice.
There's currently only one place where it is actually needed.
This is a standard we should follow, as it looks better and makes more sense to write it like this.
Compiled, checked some of the random name functions for different species
NPFC
=> Changes all instances of `pick(list(....))` to `pick(....)`

code/modules/mob/living/silicon/pai/pai.dm
Removes a duplicate definition on pAIs, cleans up the proc itself
Duplicate definitions can have unintended consequences.
As a pAI, requested to be picked up
NPFC, due to the init order favouring the duplicate definition over the original one
=> Removes a duplicate definition on pAIs

code/__DEFINES/is_helpers.dm, code/game/gamemodes/cult/blood_magic.dm, code/game/gamemodes/cult/cult_items.dm, code/game/gamemodes/cult/ritual.dm, code/game/gamemodes/cult/runes.dm, code/game/objects/items/mountable_frames/frames.dm, code/modules/mob/living/simple_animal/bot/floorbot.dm, code/modules/shuttle/navigation_computer.dm
defines isspacearea, there were few space area checks, and should be easier in the future
Simplifies some istype checks
Unable to, I trust CI
NPFC
=> defines isspacearea

code/modules/admin/verbs/adminpm.dm, code/modules/client/client_defines.dm, code/modules/client/client_procs.dm
Fixes some issues with mhelps/ahelps.
Bugs bad.
Some.
NPFC
=> [s] mhelp/ahelp fixes

code/game/machinery/doors/airlock.dm, code/game/machinery/doors/airlock_electronics.dm, code/game/objects/structures/displaycase.dm, code/game/objects/structures/door_assembly.dm, code/game/objects/structures/windoor_assembly.dm
fixes the world's shittiest exploit
exploits bad
=> [s] fixes the world's shittiest exploit

code/game/machinery/computer/cloning.dm
fixes cloning sporadically not working
cleans? up some of the code. I don't love this nondefine string approach but I'm not refactoring this entire system
#25119 
Bugfixes
Actually fully testing this is kind of hell but it doesn't explode on impact anymore
:cl:
fix: Cloning will no longer stop working rarely
/:cl:
=> fixes cloning sporadically not working

code/game/objects/items/devices/radio/headset.dm
Fixes #17498.
Less tricks fair.
Trick unavailable on local server.
:cl: Maxiemar
fix: Encryption keys cannot be inserted into headsets when anti-drop is active.
/:cl:
=> [s] Encryption key trick no more

code/game/gamemodes/miniantags/morph/morph.dm
Resolves  #25201
Lmao this is not good
Didn't work anymore :(
NPFC
=> [s] Fixes the morph issue

code/datums/spells/lichdom.dm, code/game/gamemodes/wizard/wizard.dm, code/modules/antagonists/wizard/datum_wizard.dm
Refactors liches to not touch the fucking config. Been a long time coming
Closes #20864
Maybe will also fix #25102, but I need more user input from them
Shitcode gone
:cl:
tweak: Liches now only extend the wizard gamemode, instead of all gamemodes
/:cl:
=> Refactors liches a bit

code/modules/mob/living/brain/robotic_brain.dm, code/modules/research/designs/medical_designs.dm
Removes further uses of "non-sentient", updates the MMI's description in medical designs to its current one.
lore
also consistency 
N/A, text only changes
:cl:
tweak: Updated MMI & robobrain text
/:cl:
=> MMI and robobrain text updates

code/controllers/subsystem/SSgarbage.dm, code/modules/admin/verbs/debug.dm
adds refcount to the gc log
better information for debugging
Checked the GC log in game.
NPFC
=> adds refcount to the gc log

code/game/gamemodes/changeling/changeling.dm, code/game/gamemodes/cult/cult_mode.dm, code/game/gamemodes/game_mode.dm, code/game/gamemodes/miniantags/abduction/abduction.dm, code/game/gamemodes/nuclear/nuclear.dm, code/game/gamemodes/revolution/revolution.dm, code/game/gamemodes/traitor/traitor.dm, code/game/gamemodes/vampire/vampire_gamemode.dm, code/game/gamemodes/wizard/wizard.dm, code/modules/mob/living/carbon/superheroes.dm, code/modules/response_team/ert.dm
Makes all gamemode variables centralized in `game_mode.dm`
Helps the changes made in #25218 
I do not want to hunt for where some of these variables are hidden for 20 minutes, it's incredibly confusing and we did this before for pretty much every non-datum a while back
It compiled
NPFC
=> Removes duplicate definitions of `/datum/gamemode` on almost every gamemode file

.github/CONTRIBUTING.md
Move me up a few lines of code
I wanna get over my fear of heights this way
The higher up in the dev chain you go, the less testing you (have) to do
add: 🍇
=> Adds me to `CONTRIBUTING.md`

.github/CONTRIBUTING.md
Adds Burzah to the purple list.
More merges
I get good grades.
Purple
@Burzah
=> Adds Burza to Commit Access in CONTRIBUTING.md

.github/CONTRIBUTING.md
A wild FunnyMan appears!
Less reviews needed for other PRs, so mine can get reviewed and merged sooner.
I ran a simulation of the universe, and it didn't end for at least 10 minutes after this PR was merged. LGTM.
add: Yet another role to FunnyMan.
=> Add myself to review team in CONTRIBUTING.md

code/datums/action.dm, code/datums/spells/alien_spells/basetype_alien_spell.dm, code/game/gamemodes/miniantags/morph/spells/morph_spell.dm, code/game/gamemodes/miniantags/pulsedemon/pulsedemon_abilities.dm, code/game/gamemodes/miniantags/revenant/revenant_abilities.dm
Fixed revenant, morph, and alien actions not being updated with costs
Fixed pulse demon actions not telling you that they can be alt-clicked
Fixed people not getting error messages on their spells sometimes
Fixed not getting a notice that you can keybind actions in the action description
bugfixes
Did rev and pulsedemon things
:cl:
fix: revenant, morph, and alien  actions are updated with costs
fix: pulse demon actions once again tell you they can be alt-clicked
fix: you get a notice you can keybind actions in the action button description again
fix: if you cast a spell and it fails you are once again informed
/:cl:
=> fixes some action button issues

code/game/gamemodes/malfunction/Malf_Modules.dm
fixes repair borg not working in some cases
Love me some undocumented behavior, turns out this also calls a view check
bugfix 
Used in in game
:cl:
fix: Repair borg consistently targets again
/:cl:
=> fixes repair borg not working in some cases

code/controllers/subsystem/SSticker.dm, code/game/gamemodes/nuclear/nuclear_challenge.dm, code/modules/admin/misc_admin_procs.dm, code/modules/shuttle/syndicate_shuttles.dm
Slightly refactors `pregame_timeleft` calculations and some time defines.
Less ifs cool
It counts down.
NPFC
=> Refactor ticking of pre-game time left

code/datums/helper_datums/teleport.dm, code/game/gamemodes/miniantags/abduction/machinery/experiment.dm, code/game/machinery/clonescanner.dm, code/game/machinery/cryopod.dm, code/game/mecha/equipment/tools/medical_tools.dm, code/modules/food_and_drinks/kitchen_machinery/gibber.dm
Fixes #12809.
Less exploits cool
It compiled. Tried with some machinery - the trick unavailable.
:cl: Maxiemar
fix: Player doesn't stay in machinery after teleportation.
/:cl:
=> [s] Bluespace crystal go wzhzhzh

code/modules/antagonists/vampire/vampire_powers/gargantua_powers.dm, code/modules/mob/living/simple_animal/hostile/mining/elites/elite.dm
These walls were put in a list and not removed from it when they dissipated, which cased 16 Harddels every 5 seconds for 30 seconds
Performance go brrrr
NPFC
=> Makes the walls from Desecrated Duel GC properly

code/_onclick/hud/radial.dm
fixes a radial menu gc false positive, this cleared under a microsecond but filled up the log hard. 
false positives bad
compiled, ran, deleted the thing
NPFC
=> fixes a radial menu gc false positive

code/modules/ruins/ghost_bar.dm
It adds a zero to the amount of money that a ghost bar person get
Currently, a ghost bar person does not have enough money to do a bit of dress-up, or buy a single pack of smoke.
Spawned myself in, and saw that I could buy myself some bling with my monopoly money
:cl:
tweak: Added more money to the ghost cafe
/:cl:
=> Ghost bar cash increase

.github/CODEOWNERS
Makes me codeowner of tgui executable files (HC vote was had beforehand to agree this)
These shouldn't be changed without thorough review, so we're adding some more protection to them.
=> Tweaks codeowners

code/datums/status_effects/magic_disguise.dm, code/game/gamemodes/miniantags/abduction/abduction_gear.dm
Fixes exploit.
Less exploits cool
Fine for wizard, YOLO for abductors.
:cl: Maxiemar
fix: Plant-disguise trick is unavailable now.
/:cl:
=> [s] Disguise with plant trick

code/datums/uplink_items/uplink_traitor.dm
fixes the capitalization of tarot card name in uplink, everything else is capitalized.
See above, consistent
if adding capitals to a text string stops the game from compiling we have bigger issues
:cl:
fix: Fixes tarot card capitalization in uplink
/:cl:
=> fixes tarot card capitalization in uplink

code/__HELPERS/type2type.dm
This proc isn't used at all, and is just not necessary because it returns the defines, which at runtime is replaced by a number **So this proc does nothing, and will also not work with diagonals**
This proc is just useless
It compiled
NPFC
=> Removes num2dir

code/game/machinery/portable_turret.dm
Fixes #25289
Fixes #25289
I put a mech with an occupant and one without an occupant in front of turreets, no runtimes
NPFC
=> Fixes a runtime with mechs and turrets

code/modules/crafting/recipes.dm
Add alternative Spear recipe in Primal category with sinew restraints instead of cable restraints
Spear are almost useless in hunting and throwing compare to bone spear, but common spears are ideal tool for funny head lamps. So i added alternatire recipe for this purpose.
add new recipe with 1 change. Best coder based PR.
:cl:
add: Add alternative Spear recipe with sinew restraints instead cable coils in Primal section
/:cl:
=> Add alternative Spear recipe for Ash walkers

code/modules/surgery/encased.dm, code/modules/surgery/generic.dm, code/modules/surgery/organs_internal.dm, code/modules/surgery/other.dm
Complete missing part about Ash Walker`s ghetto surgery, if they want to roleplay as local shaman and help with their skill, not the legion cores. 
Ash walkers allowed to do ghetto surgery, but cant do that physically. Make ash walkers great again!
Add new things, do test, all worked well
:cl:
add: Add watcher sinew as retractor + FixOVein(90%) and wirecutters as saw(35%), so ash walkers now can do ghetto surgery
/:cl:
=> Ash Walkers now Ash Doctors

code/modules/station_goals/secondary/secondary_goal.dm
Added tracking of when a secondary goal is handed out.
Better data for figuring out if goals are too hard.
It compiles.
NPFC
=> Added tracking of when a secondary goal is handed out.

code/modules/clothing/under/costumes.dm, code/modules/customitems/item_defines.dm
See title
Organisation
None
NPFC
=> Moves a custom item to the right file

code/__HELPERS/tool_helpers.dm, code/datums/spells/alien_spells/build_resin_structure.dm, code/game/atoms.dm, code/game/machinery/constructable_frame.dm, code/game/machinery/mass_driver.dm, code/game/machinery/portable_turret.dm, code/game/machinery/suit_storage_unit.dm, code/game/objects/items/devices/geiger_counter.dm, code/game/objects/items/tools/tool_behaviour.dm, code/game/objects/structures/crates_lockers/largecrate.dm, code/game/objects/structures/janicart.dm, code/game/objects/structures/kitchen_spike.dm, code/game/objects/structures/railings.dm, code/modules/admin/verbs/SDQL2/SDQL_2.dm, code/modules/arcade/prize_counter.dm, code/modules/mining/machine_vending.dm, code/modules/mining/satchel_ore_boxdm.dm, code/modules/mob/living/silicon/robot/drone/maint_drone.dm, code/modules/mob/living/simple_animal/bot/mulebot.dm, code/modules/power/engines/singularity/collector.dm, code/modules/power/generators/portable generators/pacman.dm, code/modules/power/generators/solar.dm, code/modules/research/circuitprinter.dm, code/modules/research/protolathe.dm, code/modules/research/server.dm
Converts some istype crowbars into crowbar acts
Left tool_behaviour check in some cases (such as multistep crafting)
~~I felt like it~~
Sounds for tool usage and more standartization for tool usage
I clicked crowbar at things
=> More Crowbar Acts

code/game/atoms.dm, code/modules/awaymissions/maploader/writer.dm, code/modules/mob/mob_vars.dm
Removes a practically unused variable
Rewrites some comments in `atoms.dm` because one was just wrong, and others were formatted weirdly or just plainly incorrect
(Looking at you, speech bubble)
Less variables on atoms mean less variables on a lot of things
It compiled
NPFC
=> Removes a variable that is only set once

code/game/machinery/shieldgen.dm
Shields no longer stick around after the generator moves, move with shuttle
Shields floating in space / not moving with shuttle bad
Moved raven with shields active.
:cl:
fix: Fix shield generators on zlvl change
/:cl:
=> fix shield generators on zlvl change

code/__DEFINES/mob_defines.dm, code/game/gamemodes/miniantags/guardian/types/ranged.dm, code/game/gamemodes/miniantags/revenant/revenant.dm, code/modules/mob/living/living_defines.dm, code/modules/mob/mob_movement.dm
Makes `incorporeal_move` use defines
Defines are a lot more readable than magic numbers
It did compile, I triple checked the diff
NPFC
=> Changes incorporeal_move to defines

code/modules/mining/lavaland/ash_flora.dm
gives lavaland plants 50 potency, making them having no size scaling
Could be nice for ashwalkers, getting a bit more out of these lavaland plants. Or miners, however miners already have *easy warm donk pockets*, so this doesn't help miners much in that regard for healing from cactuses, in my view. The more cactus they eat, the less donk they can, which heals better.
And of course the real reason: the plants look so stupid small coming off the larger lavaland plants. It doesn't really hurt anyone, so give em the bigger plants back.
see above
:cl:
tweak: Lavaland plants adjusted from 15 potency to 50
/:cl:
=> gives lavaland plants 50 potency

code/modules/antagonists/traitor/contractor/datums/syndicate_contract.dm
Gives contractees a single unit of mutadone 
Turns out, genetic powers are just very unbalanced and unpredictable
Sadly, not many other than it compiling
:cl:
tweak: Contractees now get 1u of mutadone upon being contracted
/:cl:
=> [s] Gives contractees 1u of mutadone upon entering the prison

code/modules/projectiles/gun.dm
Fixes #25107.
Oversight bad.
Spawned all the gunborgs.
Executed some skrell.
:cl:
fix: Fixed cyborgs not being able to perform executions with guns.
/:cl:
=> [FIX] Cyborgs With Guns Can Now Perform Executions (With Guns!).

code/modules/atmospherics/machinery/components/trinary_devices/filter.dm, code/modules/atmospherics/machinery/datum_pipeline.dm
Tweaks atmospheric filter so that when it filters nothing, it acts like a pump.
It shouldn't check side pressure if it isn't filtering.
Seems ok locally.
:cl: Maxiemar
tweak: Atmospheric filter truly acts like a pump when it filters nothing.
/:cl:
=> Filter not filtering

code/modules/reagents/chemistry/reagents/drugs.dm
Disables space drugs effect of user going from side to side in 0G.
Hyperrealism game™
Tested with disabled gravity generator, ok.
:cl: Maxiemar
fix: Space drugs don't make you walk in 0G now.
/:cl:
=> Don't walk without gravity while being space drugged

.tgs.yml, tools/tgs_scripts/PreCompile.sh
Makes the TGS PreCompile script actually build RUSTG.
Scripts should work. They currently dont.
N/A
Ran the script, it did what I asked.
NPFC
=> Upgrades TGS build script to actually build RUSTG

code/modules/mob/living/silicon/robot/robot_life.dm, code/modules/mob/living/silicon/robot/robot_mob.dm
Autodocs `robot_mob.dm`.
Removes an unused proc from `robot_life.dm`.
Documentation good.
Removing unused code good.
It compiled.
=> Autodocs robot_mob.dm. Removes an unused proc.

code/controllers/subsystem/SStimer.dm
Timer log now includes the function called
logging readability
viewed in game
NPFC
=> Timer log now includes the function called

code/__DEFINES/clothing_defines.dm, code/_onclick/hud/screen_objects.dm, code/datums/keybindings/mob_keybinds.dm, code/modules/mob/living/carbon/carbon_procs.dm, code/modules/mob/mob.dm, code/modules/mob/mob_vars.dm
Adds 2 hand keybinds for right and left hands
Hitting one of these will attempt to swap to that hand, and but if you already have that hand active, it activates the item in your hand.
They have no default bind.
Also does a bit of refactoring.
More customizability for players == good
Set them to I and P respectively, and messed around with them.
:cl:
add: Adds 2 new keybinds for changing hands, Swap to/Activate (Right/Left) Hand
/:cl:
=> Adds 2 hand keybinds for right and left hands

code/modules/admin/verbs/adminpm.dm
Fixes mentor PMs showing up in admin PMs
My admin PM section is getting spammed with mentors :(
Barely any except for compiling
:cl:
fix: [MENTOR] Mentor PMs now properly show up in the mentor PM tab again
/:cl:
=> Makes mentor PMs show up as mentor PMs again

code/modules/power/engines/singularity/singularity.dm
Resolves #14848
Resolves #21751
Makes the singularity move 2 steps at size 2.
That old comment was not correct.
Thanks to https://github.com/tgstation/tgstation/pull/83005 for finding this
THIS SHOULD NOT GO THROUGH CONTAINMENT
It compiled!
:cl:
fix: The singularity has been nerfed to not go on random walks every once in a while now
/:cl:
=> Fixes a very old singularity bug

code/game/gamemodes/autotraitor/autotraitor.dm
Cleans up autotraitor.dm including:
- snake casing of variables and a function name
- removing old comments
- updating style of a for loop
- removing and replacing the use of `spawn`
Its good for contributors, so it _may_ be good for the game in the long run.
Ran a build after changes, it compiled.
NPFC
=> File cleanup for autotraitor.dm

code/datums/uplink_items/uplink_general.dm, code/datums/uplink_items/uplink_nuclear.dm, code/datums/uplink_items/uplink_special.dm, code/datums/uplink_items/uplink_traitor.dm
Turns cant_discount into can_discount, and flips the relevant values. 
Double negatives in bool names make me confused and scared.
Compiled and got discounts on local.
=> Un-doubles double negative var in uplink_item

code/modules/food_and_drinks/drinks/bottler/bottler.dm
Fixes a spelling mistake which makes the bottler try to produce a reagent that does not exist.
Bugs bad, questionably mutagenic slurry... good?
I confirmed the spelling was correct
:cl:
fix: Fixes bottler trying to produce a reagent that does not exist
/:cl:
=> fixes bottler trying to produce a reagent that does not exist

code/game/objects/items/weapons/RCD.dm
Title
```dm
[2024-05-05T04:20:51] Runtime in code/game/objects/items/weapons/RCD.dm:576: new() called with an object of type /datum/rcd_act/place_floor instead of the type path itself
proc name: afterattack (/obj/item/rcd/afterattack)
usr: Colm Keane (lewc) (/mob/living/carbon/human)
usr.loc: The floor (190,126,1) (/turf/simulated/floor/plasteel)
src: the combat RCD (/obj/item/rcd/combat)
src.loc: Colm Keane (/mob/living/carbon/human)
call stack:
the combat RCD (/obj/item/rcd/combat): afterattack
the combat RCD (/obj/item/rcd/combat): melee_attack_chain
Colm Keane (/mob/living/carbon/human): ClickOn
the floor (190,125,1) (/turf/simulated/floor/plasteel): Click
Lewc (/client): Click
```
RCDs currently do anything now, that's not great
Constructed things, rapidly
:cl:
fix: RCDs can now …
=> Fixes a bug that prevented RCDs from rapidly constructing or deconstructing anything

.github/workflows/merge_upstream_master.yml
The workflow can't cope with the async TGUI rebuild in the hook (this is usually fine for local machines).
So, we explicitly tell it to do so.
This really should just work at this stage.
=> Makes !merge_upstream rebuild TGUI properly if needed

.github/workflows/build_milla.yml
Adds a Github workflow for building MILLA, similar to !merge_upstream.  The command is !build_milla
Securely-built binaries are a Good Thing.
NPFC
=> Github workflow for building MILLA

code/modules/mob/living/living_update_status.dm, code/modules/mob/living/stat_states.dm
fixes sleepblind not being cleared if you are blind from othermeans
this should clear. Sorry for not testing this while being hit with with tear gas then sleeping
blindingmyself, waking up, still blind but bed gone
fix: Fixes sleepblind not being cleared if you are blind from othermeans
/:cl:
=> fixes sleepblind not being cleared if you are blind from othermeans

.github/CODEOWNERS
Adjust CODEOWNERS per AA's request
More pings about useful stuff, less pings about useless stuff.
YOLO
NPFC
=> Replace librust_g.so with milla.dll in CODEOWNERS

code/modules/mob/living/simple_animal/bot/ed209bot.dm, code/modules/mob/living/simple_animal/bot/secbot.dm
This PR fixes bots detaining mode which i broke in https://github.com/ParadiseSS13/Paradise/pull/23550
bugs bad
compiled, detained
:cl:
fix: Bots detaining mode works as intended once again
/:cl:
=> Fixing bots detaining mode

code/modules/mining/equipment/explorer_gear.dm
Fixes hecksuit no longer being spaceproof / being able to be mendered through, broken by #22643 
spacehelmets should be spaceproof.
Returned to parent values, which are spaceproof, these were the values changed in the above pr
:cl:
fix: Fixes hecksuit not being spaceproof
/:cl:
=> fixes hecksuit

code/__HELPERS/_logging.dm
Corrects my fuckup.
There are supposed to be HTML links here.
Nah.
NPFC
=> Turns out we DO want HTML here.

.github/workflows/build_milla.yml, .github/workflows/merge_upstream_master.yml
Fixes this as requested in https://github.com/ParadiseSS13/Paradise/pull/25328: 
Tidies some other stuff.
Less maintainer stress
=> Tidy workflow oversights

code/datums/components/debris.dm
As intended, disablers now only spawn smoke particles instead of making full debris
This was intended. Physical ammunition spawns debris and smoke, laser weaponry only spawns smoke.
Shot a disabler at a wall, only smoke
Shot a laser gun at a wall, only smoke
Shot a WT at a wall, only smoke
:cl:
fix: Disablers now spawn only smoke debris when hitting a wall
/:cl:
=> Makes bullet debris not come from disablers

code/game/objects/effects/effects.dm
fixes particle holders not naturally gcing
This is still a reference despite it being cleared quickly
shot at some walls
NPFC
=> fixes particle holders not naturally gcing

code/game/gamemodes/wizard/spellbook.dm
Removes EMP spellbook from random pool.
This spellbook is completely synthetic - it doesn't have its own sprite, the spell it suggests requires wizard clothes. I actually don't find this pool used anywhere except our downstream lavaland.
Testing is a myth. I just believe it works.
Required for this? idk
=> Remove EMP spellbook from random pool

code/modules/admin/admin_verbs.dm, code/modules/client/client_procs.dm, interface/skin.dmf
makes the profiler more accessible. Now a verb and shown in the files option
I use it a lot and it should be way more obvious
Compiled, ran 
NPFC
=> makes the profiler more accessible

code/game/objects/explosion.dm
makes flash range on explosives actually do something. flashes your eyes if you're in flash range. If you're dead set in the bomb it goes through light flash protection as well.
we live in the future mechanics can do things
compiled, ran, oppenheimer rp
:cl:
tweak: The flash range on explosives does things. if you're in the flash range your eyes get flashed.
/:cl:
=> makes flash range on explosives actually do something

code/__DEFINES/combat_defines.dm
Removes two unused damage defines
I'm 99% sure we aren't gonna use these in the near future, at the moment we are more than fine with 4 main damagetypes and some other wacky/niche damages like clone or brain
It compiled
NPFC
=> Removes two unused damage defines

code/modules/surgery/tools.dm
Title.
1. LORE
2. name = "retractor"
desc = "Retracts stuff."
I rest my case.
- loaded in
- observed surgical tools
- descriptions updated
:cl:
tweak: Updated surgical tool descriptions
/:cl:
=> Updates surgical tool descriptions

code/game/dna/mutations/mutation_powers.dm
Fixes an exploit
Bad
I loaded in and made sure it worked
=> [S] Fixes a matter eater exploit

strings/sillytips.txt, strings/tips.txt
Clarifies some tips. Adds some brand new tips. Removes an old tip that is not true anymore.
Tips good.
It compiled.
:cl:
add: Adds some new tips.
del: Removes an incorrect tip.
tweak: Tweaks some tips.
/:cl:
=> Updates tips.

tools/tgs_scripts/PreCompile.sh
Corrects a typo in the file name
Run compilation in TGS with edited PreCompile.sh
NPFC
=> PreCompile.sh typo fix

tools/ci/run_od.sh, tools/ci/setup_od.sh
Downloads precompiled OD releases, as opposed to building it ourselves.
Fixes the latest error, and speeds up the OD lint CI by **2 whole minutes.**
=> Speed up OD lint CI significantly, fixes errors

code/modules/mob/living/simple_animal/bot/bot.dm
Cleans a proc for bot with returns
Less nesting and MY EYES, Easier to read
Literally none
Unable to
NPFC
=> Cleans up a nested proc with returns

code/modules/food_and_drinks/food/foods/meat.dm, code/modules/mob/living/carbon/alien/larva/larva.dm, code/modules/mob/living/simple_animal/hostile/retaliate/kangaroo.dm
Kangaroo and larva now can be butchering. Larva does not provide many meat, but xeno meat is meat as well.
Roo meat are most recomended for peoples with bloodloss and and it tastes a lot like poultry(slight wiki searching), so i added a few iron in that.
Sinse larva now can be revived, nessecary for gibbing like the older ones are high.
For kangaroo case, i want burgers from Darwin, who killed assistant and got killed with mass injuries. Such a jerk does not deserve peaceful death.
Add line, test knife, almost get killed by kangaroo
:cl:
tweak: Kangaroo and alien larva can now be butchering. Larva provide 1 meat, Roo has 6 new type meat with iron inside.
/:cl:
=> Kangaroo and larva now can be butchering

SQL/paradise_schema.sql, SQL/updates/55-56.sql, code/__DEFINES/misc_defines.dm, code/modules/admin/sql_notes.dm, config/example/config.toml
Improves note deletions by just marking it as deleted instead of wiping the note out entirely.
Trails of paper as far as the eye can see
Deleted a note, it didnt show up ingame but still existed in the DB
NPFC
=> Improves note deletions

code/datums/uplink_items/uplink_general.dm, code/modules/reagents/chemistry/reagents/medicine.dm
The nanite injector now heals ipcs, robotic limbs, and cybernetic organs, meaning you can use nanocalcium as an emp'd ipc, or a person with cybernetics that needs a fix.
With agents getting access to more cybernetics, a way to repair would be nice, so why not include that in nanite injector traitors can buy for 10 tc?
emp'd self twice as ipc, used injector.
Organs and implants were fixed and repaired.
:cl:
tweak: Prototype nanite injector now heals ipcs / robotic limbs / cybernetic organs
/:cl:
=> prototype nanite injector now heals ipcs / robotic limbs / cybernetic organs

code/game/gamemodes/game_mode.dm
fixes #25508
nuke code requests work good
:cl:
fix: fixes  nuke code requests
/:cl:
=> fixes  nuke code requests

.github/workflows/merge_upstream_master.yml
I forgot a `; then`, so it doesn't work right
=> Another !merge_upstream PR

code/modules/events/immovable_rod.dm
Removes an unused variable that got merged in with the rod smite.
The codebase should not compile with warnings
This is a webedit. I am so so sorry
=> Remove unused variable in rod code

code/datums/mind.dm
Makes TP actually work for 516 clients. The code was old and hacky so it's a wonder it worked in the first place.
Before:
After:
Loaded TP
=> Fixes Traitor Panel for 516

code/modules/supply/supply_console.dm, code/modules/supply/supply_pack.dm, code/modules/supply/supply_packs/pack_shuttle.dm
Cargo crates can now have a tgui warning to it.
The lance shuttle gets it.
Let's have this set in stone.
```This shuttle destroys EVERYTHING in its path when docking. You should only order this shuttle if: 1. The station has a clear need for it, 2. You are a hijacker, or 3. You have ahelped and received permission. Failure to meet this will lead to punishment.```
ordered normal crate.
ordered lance, got mesage
:cl:
tweak: The lance now has a very clear confirmation message on it.
/:cl:
=> The lance now has a very clear confirmation message on it.

code/game/objects/items/devices/scanners.dm
health scanners no longer say slime people have no heart
telling the truth is good
gave slime heart attack
told to use electric shock
:cl:
fix: Health scanners no longer say slime people have no heart when having a heart attack
/:cl:
=> health scanners no longer say slime people have no heart

code/modules/mod/modules/module_kinesis.dm
blocks kinesis if user is buckled to the target or inside it.
it's a little too goofy kinesising yourself around on a chair. Kinisising other chairs that other people are on is fine, just not yourself.
that and we got 3 reports for this of late.
kinisisisisisised locker and chair
could not kaikwondo them when inside or on
:cl:
tweak: You can no longer kinesis the chair you are buckled to
/:cl:
=> You can no longer kinesis the chair you are buckled to

code/__HELPERS/game.dm, code/game/objects/items/devices/radio/radio_objects.dm, code/modules/client/preference/link_processing.dm, code/modules/client/preference/preferences_toggles.dm, code/modules/mob/dead/observer/observer_base.dm, code/modules/mob/dead/observer/observer_login.dm
refactors radios to use proximity
Overtime reduction, easier to understand code, WAY faster
Compiled and ran, worked fine in game
NPFC
=> refactors radios to use proximity

code/modules/surgery/encased.dm, code/modules/surgery/generic.dm, code/modules/surgery/organs_internal.dm, code/modules/surgery/other.dm
Fixes shivs not being distinct surgical tools from knives in some surgeries.
Fixes alien incision and sawing steps not having all the tools of their non-alien versions.
Regular chainsaws can now be used as a substitute for the syndicate chainsaw in surgery.
Claymores and energy swords can now be used in amputation with a 75% success chance.
Chainsaws can now be used to saw bone with a 90% success chance, and in amputation with a 100% success chance.
Wirecutters can now be used as a scalpel substitute in all non-debridement surgeries with a 35% success chance (they still cannot perform debridement surgery).
NPF - redefined wirecutters as `TOOL_WIRECUTTER` in the 'saw bone' surgery step.
Flamethrowers can now be used as a cautery with a 1% success chance. Have fun! 😄
Removing …
=> Tweaks Ghetto Surgery

code/modules/projectiles/ammunition/energy_lens.dm, code/modules/projectiles/guns/energy/stun.dm, code/modules/projectiles/guns/projectile/automatic.dm, code/modules/projectiles/guns/projectile/saw.dm
Fixes these guns by setting fire_delay to zero (this variable is used for burst fire which none of these guns use anymore)
bugs bad
shot em all with double speed
:cl:
fix: fix full auto on certain guns with double click speed
/:cl:
=> fix full auto on certain guns with double click speed

code/datums/particles.dm
Heavily reduces the amount of smoke that appears from explosions
Also makes sparks disappear faster
I think that one wizard round with a fireball showed that these were very overtuned
https://github.com/ParadiseSS13/Paradise/assets/108773801/29cfe553-2fdc-465b-9c75-203cee493b5b
:cl:
tweak: Explosions now release a lot less smoke
/:cl:
=> Heavily reduces explosion smoke amounts

code/game/objects/items.dm, code/modules/mob/living/living.dm
Adds punctuation to the ends of messages when pointing at stuff.
Message not having punctuation bad.
None whatsoever
:cl:
fix: Added punctuation to pointing.
/:cl:
=> Adds punctuation to pointing

code/modules/events/anomaly_bluespace.dm, code/modules/events/anomaly_cryo.dm, code/modules/events/anomaly_flux.dm, code/modules/events/anomaly_grav.dm, code/modules/events/anomaly_pyro.dm, code/modules/events/anomaly_vortex.dm
Fix https://github.com/ParadiseSS13/Paradise/issues/25552 , renaming events into "Anomaly event"
Fixes good
Rename anomaly events into "Anomaly event", so example bluespace anomaly will not have object of interest as himself. Not seeing any case who can make this broke into somewhere else.
:cl:
fix: Fix funny pronounce, caused by anomaly events.
/:cl:
=> Fixes anomaly shows anomaly

code/modules/mob/dead/observer/observer_base.dm
Fixes #25690
bug bad
See above
:cl:
fix: Drones now keep their respawnability when ghosting
/:cl:
=> Fixes drones becoming un-respawnable

code/modules/food_and_drinks/food/foods/misc_food.dm
Adds 15u of mannitol to syndicate donk pockets (the ones with meth).
Meth deals crippling-to-lethal amounts of brain damage in addition to addicting you. Syndicate donk pockets are an item that costs TC and have been relegated to a noob trap since the scaling changes. 15u of mannitol per donk pocket means that you should not end up with any brain damage unless you eat several in quick succession.
Ate a pocket and didn't end up with any brain damage.
:cl: Chuga
add: Syndicate donk pockets now heal brain damage
/:cl:
=> Syndicate Donk Pockets now have mannitol

code/modules/crafting/craft.dm, code/modules/crafting/recipes.dm
fixes https://github.com/ParadiseSS13/Paradise/issues/25676
If you craft spear with craft menu and use plasma shard, it will create plasma shard spear instead of basic one.
bugs bad
compiled, created couple spears
:cl:
fix: Crafting spear with plasma shard in crafting menu will create plasma shard spear now.
/:cl:
=> make the spear purple again

code/__HELPERS/trait_helpers.dm, code/modules/clothing/spacesuits/ert_hardsuits.dm, code/modules/clothing/spacesuits/hardsuit.dm, code/modules/clothing/spacesuits/misc_spacesuits.dm, code/modules/mob/living/carbon/human/human_mob.dm, code/modules/mod/mod_types.dm
Adds the RSG immune trait to Dsquad/Security/Medical MODsuits
Also fixes the trait behaviour because apparently I couldn't fix this in 2 PRs
Renames the RSG immune trait to be more descriptive
The trait should work
MODsuits that are supposed to work against RSGs should be RSG immune
Shot a naked skrell: hit
Shot a Skrell in Dsquad MODs: deflect
Shot a Skrell in the SST Hardsuit: deflect
:cl:
fix: DSquad/Security ERT/Medical ERT MODsuits are now RSG immune again
/:cl:
=> Adds RSG immune back to MODsuits that lost it

code/modules/admin/topic.dm, code/modules/mob/transform_procs.dm
This PR converts the Animalize command to use TGUI inputs.
Improves user experience when using the animalize command (you can read the choices you are making now).
Spawned a mob and took control of it.
Used the Animalize proc on the mob and observed changes.
NPFC
=> Converts Animalize to use TGUI

code/__HELPERS/_logging.dm, code/game/verbs/who.dm, code/modules/admin/admin_verbs.dm, code/modules/admin/misc_admin_procs.dm, code/modules/admin/player_panel.dm, code/modules/admin/verbs/adminpm.dm
=> [s]fix slight error

code/modules/mob/living/simple_animal/parrot.dm
Prevents parrots from picking up or carrying an item while being grabbed. This makes it so there is no way to consume a parrot via vulp/taj aggro grab while it has a held item.
This is really funny but it's really not good.
Made sure picking stuff up doesn't break when not grabbed.
:cl: Chuga
fix: Parrots can no longer be used as a makeshift storage implant by Vulpkanins and Tajarans.
/:cl:
=> [s] Nerfs eating

code/modules/vehicle/vehicle.dm
Fixes an 8 year old bug with vehicles.
HAHAHAHAHAHHAHA yeah this is bad
shot vehicles.
:cl:
fix: Vehicles are now affected by bullets.
/:cl:
=> [s]Fixes an 8 year old bug. As a treat.

code/game/objects/items/robot/cyborg_gripper.dm
Fixes https://github.com/ParadiseSS13/Paradise/issues/25648 
Fixes https://github.com/ParadiseSS13/Paradise/issues/25510
Engi borg now can install power cell into APC with his gripper
bugs bad
compiled, removed cell, installed it
:cl:
fix: Installing a cell into APC with engineer cyborg gripper no longer causes double action.
/:cl:
=> Engi gripper can install APC cell again

code/game/machinery/computer/communications.dm
Fixes trialmins having access to the comms console
R_EVENT flag should be checked correctly
Local server
have R_ADMIN and R_EVENT, can access the CC comms console as NNO and aghost
have R_ADMIN, can't access the CC comms console as NNO nor aghost
NPFC
=> Fixes trialmins having access to the comms console

code/game/objects/effects/effect_system/effects_smoke.dm
Makes cult smoke work again.
Sleeping gas should work
Made sure the before and after behavior was consistent.
:cl:
fix: Cult smoke works again
/:cl:
=> Fixes a cult smoke runtime

code/game/objects/items/weapons/manuals.dm, code/modules/reagents/chemistry/recipes/others.dm
Removes fungus from zombie cure recipe
Blood + Fungus already makes carpet. We shouldn't be including reactions that make something else in the zombie virus
Compiles
:cl:
fix: Fungus is no longer required for the zombie cure, because it would accidently make carpet instead
/:cl:
=> Removes fungus from zombie cure recipe

code/modules/economy/economy_machinery/atm.dm
You can no longer keep going once you're past your 3 login attempts on a bank account.
Changes the (previously unused) lockout time from 10 seconds to 10 minutes.
Fixes #24765 
Bug bad, and having -34 attempts remaining and still being able to try again is silly. 
Logged in normally, failed to log in 3 times, couldn't log in more. Waited, could try again.
:cl:
fix: Updated nanobank security to not allow unlimited attempts at password protected accounts.
/:cl:
=> Updates nanobank security to not allow unlimited attempts at password protected accounts.

code/modules/projectiles/guns/projectile/toy.dm
Changes `origin_tech` of DonkSoft LMG from `combat=6;engineering=3;syndicate=6` to `combat=5;engineering=3;syndicate=3`.
Traders probably shouldn't be selling gear that can easily get crew illegals 7, unlocking some of the most powerful RnD items out there.
It was also an oversight, as DonkSoft LMG is a subtype of genuine L6 SAW and was inheriting its `origin_tech`.
Spawned in.
Spawned a DonkSoft LMG.
Spawned science goggles.
Confirmed the origin tech is correct.
:cl:
tweak: Lowered DonkSoft LMG technology values.
/:cl:
=> DonkSoft LMG Nerf

code/modules/events/event.dm
Makes event not sleep
Requires #25541 and #25523
CI will fail until these PRs are merged
Code reliablility
Compiles.
NPFC
=> Makes event not sleep (for real this time)

code/modules/mob/living/simple_animal/bot/ed209bot.dm, code/modules/mob/living/simple_animal/bot/secbot.dm
Updating bots logic, pushing further https://github.com/ParadiseSS13/Paradise/pull/25675
Bots now will attack you if you fail to fix them or attack with damage
Bot should fight back if he gets beaten. BEEPSKY SHOULD NOT SUFFER!
Compiled, gently touched ED-209, attacked it, got fucked.
:cl:
fix: Beepsky and ED209 now react to welder attacks, same as any other attacks that deal damage to them.
/:cl:
=> Bots now react to welder attacks, fixing ED209 logic

code/game/objects/effects/effect_system/effects_foam.dm, code/game/objects/objs.dm, code/modules/mob/living/simple_animal/bot/mulebot.dm, code/modules/mob/mob_vars.dm, code/modules/projectiles/projectile_base.dm
Changes animate_movement to defines
We can use internal Byond defines for this, which makes it more readable
It compiled
NPFC
=> Changes animate_movement to defines

code/modules/reagents/reagent_containers/hypospray.dm
Makes hyposprays work on people without suits again
Bugs are bad
Used breakpoints to make sure that each step of the hypo process went as planned.
:cl:
fix: Hyposprays work on naked people again.
/:cl:
=> Fixes hyposprays

code/__HELPERS/mob_helpers.dm
`random_skin_tone()` was not updated to include the new Nian skin tone values and returned null. This caused issues when saving character preferences after randomizing.
Errors are bad. 
Did not randomize to a null skin tone when creating a moth.
=> Fixes Nian null skin_tone SQL error

code/modules/projectiles/projectile/special_projectiles.dm
fixes telegun
CALL PARENT PLEASE anyway fixed
shot skrells, teleported.
Shot a locker. Locker did not teleport.
> check code
oh it only teleports mobs, really? Should work on anything not anchored + mechs.
Anyway, another pr, doesnt leave ghost projectiles, works.
:cl:
fix: Fixes telegun
/:cl:
=> fixes telegun

code/modules/projectiles/projectile/special_projectiles.dm
Nerfs this unnoticed buff
Worked like it used to
:cl:
tweak: Somatorays now deal no damage again
/:cl:
=> [s] Nerfs floral somatorays

code/modules/mob/living/carbon/human/species/slimepeople.dm
Title. 
Rewrites the blurb to more accurately reflect their new WIP lore.
Old slime lore was godawful. Their new lore should hopefully be less terrible.
- Loaded in
- Observed blurb
- Blurb updated
:cl:
tweak: Rewrote slime blurb
/:cl:
=> Rewrites the Slime People intro blurb

code/game/objects/items.dm
Improves admin deletion logs for certain tracked objects.
It's good for admins to know where important things are getting deleted, rather than nullspace.
Loaded in, deleted some gloves, things worked as expected.
NPFC
=> Improves some admin delete logs

code/modules/mob/dead/observer/observer_base.dm
Allows you to ghost out as a robo-brain
This seems like something that it's about time to fix.
Committed airtank as an IPC, was able to ghost out easily
:cl:
tweak: Robo-brains can now ghost out.
/:cl:
=> Allows for brainmobs (particularly, robo-brains) to ghost

code/datums/status_effects/neutral.dm
checks invisibility to see invisible
get eyes of the gods instead nerds
shot stealth armor user.
tracking lost when went invisible.
restored when recovered.
:cl:
fix: lwap no longer points out invisible admins, revenants, or fully stealed clings
/:cl:
=> [s]removes ghosts from the lwap

code/game/objects/items/weapons/storage/fancy.dm
Gives Syndicate cigarette packets the Syndicate cig packet sprite and syndicate cigarettes.
It shouldn't be using a Nanotrasen packaging.
It should be using Syndicate brand omnizene cigarettes.
It compiled.
Dense smoke, flavoured with omnizene.
:cl:
tweak: Evil cigarette packets are more evil.
/:cl:
=> Enhances the Syndicate Cigarette Smoking Experience.

code/modules/admin/admin_verbs.dm, code/modules/admin/player_panel.dm, code/modules/admin/topic.dm, code/modules/admin/verbs/adminsay.dm, code/modules/admin/verbs/asays.dm, code/modules/admin/verbs/ping_all_admins.dm
Title.
Adds a verb to show a window that lists out the history of msay messages.
It's just a useful tool, and is great at catching up on the in-round discussions. It feels like something that'd be useful for mentors alike.
Said some things as a mentor I don't regret (like "Hi" and "Hello")
:cl:
add: Adds a new verb for admins and mentors to see the history of msay in-game.
/:cl:
=> Adds a verb to show mentor say history, similar to admin say history

code/modules/hydroponics/grown/misc_seeds.dm
Updates the description of gatfruit seeds. Fixes #25745
I usually love spreading misinformation but this will just disappoint anyone who doesn't already know what they do.
Used both my eyeballs to look at the description
:cl:
fix: Gatfruit seeds no longer say they grow into .357s
/:cl:
=> Fixes gatfruit seed's description

code/game/objects/items/weapons/manuals.dm
Updates the zombie manual
Updates the zombie manual
its updated
:cl:
fix: Updates the zombie manual
/:cl:
=> Updates the zombie manual

code/modules/mob/living/simple_animal/hostile/megafauna/blood_drunk_miner.dm
the blood drunk miner now navigates over lava and chasms like every other megafauna.
This means the one blood drunk map, where he literally gets surrounded by 5 tiles of lava, will no longer stand still.
lol.
Megafauna should actually do something vs stand still.
resolve #25194
had blood drunk chase me across lava, across liquid plasma, and across chasm tiles.
:cl:
fix: Blood drunk miner is no longer comically afraid of lava
/:cl:
=>  Blood drunk miner is no longer comically afraid of lava

code/modules/mob/mob_misc_procs.dm
I figured out how to reproduce the runtime on a local server and only then realized that oldname gets passed as null when golems are created, which means that `null == null` passes the check. Whoops.
Fixes runtime that was supposed to be fixed.
Verified with debugger that it works now
=> Actually fixes account_name runtime in rename_character

code/game/gamemodes/wizard/magic_tarot.dm
Fixes some people being able to play more cards than they have mana for.
You need more lands to play that many cards
Spammed the use on tarot cards.
Only got 1 use.
:cl:
fix: Fixes some tarot cards being able to be multi activated
/:cl:
=> [s] fixes the heart of the cards

code/modules/surgery/organs/autosurgeon.dm
Fixes uses on autosurgeon
no, god no
Used, attempted to insert organ, could not
:cl:
fix: Fixed an autosurgeon having too many uses
/:cl:
=> [s] fix autosurgeon

code/modules/mob/living/carbon/human/species/golem.dm
Checks for armor penetration
Put some effort in.
100% armor peirce got hitting.
Other projectiles got reflected. Apperently this has been a thing for a while. Sure, whatever.
:cl:
fix: Fixes sand golems being able to deflect projectiles with 100% armor pen
/:cl:
=> [s] Fixes something being too easy.

code/modules/mod/modules/modules_antag.dm
Title.
Antags being able to get GAMMA level armor and toys and just. removing the tracking, isn't good, you cant remove the camera from the red hardsuit, so why should you be able to remove it from the objectively better gamma modsuit.
Tried to remove it, couldn't
:cl:
tweak: NT has super glued GAMMA erts camera modules into their suits, preventing removal from bad actors.
/:cl:
=> The camera module the GAMMA ert modsuits get is no longer removeable

code/modules/clothing/under/jobs/engineering_jumpsuits.dm
Ghhhh nobody tested this when it was added
Dear god no
NPFC
=> [s] Fixes a stupid exploit

code/modules/surgery/robotics.dm
Fixed an edge case where ipc only implants could go in non ipcs
Bugs bad
Attempted to insert the organ into an augmented human chest. Failed.
Attempted to insert the organ into an IPC chest. Succeeded.
:cl:
fix: Fixed some ipc only implants being implantable in augmented humans.
/:cl:
=> [s] fix issues with robotic organs

code/_onclick/click_override.dm
Title, the error messages weren't updated when the gloves were turned into a biochip
also updated a comment that mentioned the gloves
Errrhm what da heck this is not gloves?
It compiled
:cl:
fix: Fixed the power biochip mentioning gloves in some error messages.
/:cl:
=> Fixes the power biochip mentioning power gloves

code/datums/uplink_items/uplink_general.dm
Lowers the universal gunkit to 20 tc, from 25
Almost none of the weapons are better than a stechkin, if anything this is more of a gimic build item. A price lowering is fine.
Kid tested, balance (matt) approved.
I spawned in, and checked the uplink, where it was priced for 20 TC
:cl:
tweak: Universal gun kit from the uplink is now 20 TC from 25 TC
/:cl:
=> Lowers the universal gun kit to stechkin pricing (20 TC)

code/datums/spells/wizard_spells.dm, code/game/gamemodes/wizard/spellbook.dm
Makes it not a genetic spell because it was the source of the issue and it shouldn't have been one anyways. Blindness now lasts 30 seconds and the blurry effect now lasts 40 seconds. 30 seconds seems to have been the intended value(?) originally.
This is Very Bad
Casted blindness on somebody and watched it tick down and go away.
:cl: Chuga
fix: The blindness spell is no longer permanent and now lasts 30 seconds.
/:cl:
=> Fixes wizard blind spell lasting forever

code/__DEFINES/misc_defines.dm, code/modules/mob/living/carbon/human/human_update_icons.dm
Fixes the right ear onmob sprite from overriding the left ear onmob sprite
Fixes #7514 
:cl:
fix: Fixed right ear onmob sprite overriding left ear onmob sprite
/:cl:
=> Fixes Headset Sprites

code/modules/paperwork/pen.dm, code/modules/ruins/syndicate_space_base.dm
Add undisguised variant of sleepy pens to the syndicate researchers' chem vendors.
Sleepy pens are a unique method of chem delivery due to injecting 50u at once. This lets researchers practice mixes with them.
Checked the vendor, tested the pen.
:cl:
add: Added sleepy pens to the syndicate researchers' chem vendors.
/:cl:
=> Add sleepy pens to syndicate research base

code/game/objects/items.dm
Adds heaps of auto doced(???) comments to items.dm. as well as standardizes and cleansup the comments
code readability is good
It compiles, its all comments so nothing should be effected gameplay wise, i looked through some of the auto docs and it seemed to have worked
NPFC
=> Standardises the comments in items.dm

code/datums/components/defibrillator.dm
Title. 
Sometimes, when dead, a defib would fix your heart attack instead of reviving you. While dead.
Having to defib twice, especially if you're close to the timer, is not a good thing at all.
Defibrillation still works. 
:cl:
fix: Large defibs will no longer try to fix your heart attack if you're dead.
/:cl:
=> Fixes defibs sometimes treating heart attacks instead of death

_maps/map_files/shuttles/emergency_raven.dmm
Fixes #25881
Misspellings bad.
Spawned, bought raven, checked door
:cl:
fix: Fixed a typo on the Raven Shuttle Engineering Airlocks
/:cl:
=> Fixes typo on Raven Emergency Shuttle Engineering Airlock

code/modules/admin/topic.dm
Improves the handling of FLW links to check if a user 
It's annoying to click follow links and get the message that `this can only be used on atoms of type /mob`, especially when they're coming from someone who isn't.
I was not able to easily test this, however I believe there's no reason why this should not work.
NPFC
=> Improves follow handling for admins

code/modules/mining/machine_vending.dm
fixes hoverboards from mining giving the wrong item
it was a big pr, but yeah, my fuckup. I didn't even remeber putting it in the mining vendor
Confirmed the mining vendor give it out
:cl:
fix: Fixes hoverboards from mining giving the wrong item
/:cl:
=> Fixes hoverboards from mining giving the wrong item

code/game/objects/structures/inflatable.dm
Title
It bothered me
Looked at the wall with my eyes
:cl:
spellcheck: The description for inflatable walls is fixed.
/:cl:
=> Fixes a typo in the inflatable wall's description

code/game/machinery/doors/poddoor.dm
Makes something return false on bump
WHAT DO YOU MEEEEEEEAN
face planted into shutters and the blast doors
:cl:
fix: Fixed blast doors opening when they should not
/:cl:
=> [s] fixes pod doors

code/datums/uplink_items/uplink_general.dm, code/datums/uplink_items/uplink_traitor.dm, code/game/objects/effects/spawners/random_spawners.dm, code/game/objects/items/weapons/storage/uplink_kits.dm, code/modules/surgery/organs/autosurgeon.dm
Adds the oneuse syndicate autosurgeon as a subtype to use
This way there's a lot less confusion about what typepath to use for uplink autosurgeons.
Nukie autosurgeons are still infinitely usable
Razorwire - not usable again
Thermal eyes - usable
NPFC
=> Adds the oneuse syndicate autosurgeon as a code subtype

code/__HELPERS/mob_helpers.dm, code/game/machinery/doors/airlock.dm
Removes `spawn_atom_to_turf`
The proc is quite meh and we have the technology to do all of this but better. The only useplace was for spawning some sheets which have an arg in `Initialize()` to set the amount with
It compiled
NPFC
=> Removes `spawn_atom_to_turf`

code/__HELPERS/pronouns.dm
Atomised from #25571.
Adds documentation to pronoun helpers. No player-facing changes.
Clearly explaining what these do with examples is good. I've had to stop and think if I'm using the right one a fair few times. This makes it easier.
It still compiles.
=> Documents Pronoun Helpers

code/modules/mob/dead/observer/observer_base.dm
Fixes a bug in the logic for brains ghosting, it works as intended now.
Bugs are bad.
Spawned in as a borg, gibbed myself, was able to ghost in and out after looking at warning messages
:cl:
fix: Brains can ghost
/:cl:
=> Fixes a bug preventing brains from freely ghosting

code/modules/surgery/organs/organ_external.dm
Fixes some species when augmented being invisible, fixes a nulled species sprite sheet.
Invisible IPC buff real... kidding!
Loaded offline, compiled, saw an IPC naked, cried.
:cl:
fix: Fixed invisible IPCs
/:cl:
=> [FIX] Fixes IPCs being invisible!

code/datums/uplink_items/uplink_general.dm, code/datums/uplink_items/uplink_traitor.dm, code/game/gamemodes/miniantags/guardian/guardian.dm, code/game/objects/items/devices/uplinks.dm
Makes holoparasites discountable
Holoparasites were mainly not discountable because they were refundable. Refund code has been adjusted to refund the paid amount so you can't gain a lot of TC instantly with this
Bought a holopara on discount, refunded, got my 30 TC back
Bought a normal holopara, got 60 TC back
:cl:
tweak: Holoparasites can now be discounted!
/:cl:
=> Holoparasites are now discountable

code/game/objects/items/weapons/grenades/grenade.dm
Lowers the grenade throwspeed from 4 to 3
Throwspeeds over 4 can do wacky things with boomerangs, this is really just a bandaid fix for #25920 , I can try debugging where the hell this happens in throwingcode later
Grenades are now a bit slower to throw
:cl:
tweak: Grenades are now thrown a little bit slower
/:cl:
=> Lowers grenade throwspeed

code/_onclick/item_attack.dm, code/game/gamemodes/cult/blood_magic.dm, code/game/gamemodes/cult/cult_items.dm, code/game/gamemodes/cult/ritual.dm, code/modules/mob/living/carbon/human/human_defense.dm
This PRs adds checks for shields for cult spell attacks and exploding stun mark
Blocking cult hands with shield sounds good. Blocking cultists attacking you with cult mark set is good.
Compiled, attacked with various cult weapons, tried throwing spear.
:cl:
fix: Cult weapons and attacks with stun mark on you now can be blocked with shields.
/:cl:
=> Cult magic attacks and attacks on stun mark can now be blocked by shields

code/__HELPERS/time.dm
See title
It's slightly faster and doesn't have some weird byond:tm: moments
It compiled
NPFC
=> Makes our time defines use strict numbers instead of nested defines

code/game/objects/items/weapons/storage/boxes.dm, code/modules/supply/supply_packs/pack_science.dm
Adds a new crate that contains all the components needed to construct an R&D console, protolathe, circuit imprinter, and destructive analyser. Leftover metal and glass can be used as feedstock for the machines.
The crate costs 1000 Cr.
If all the RnD consoles or circuit imprinters on the station are destroyed along with the spares in tech storage, that's it. Science is dead. No way to recover.
This crate means that if some terrible disaster happens that destroys RnD (malf AI, pulse demon, etc.) before being defeated, science will be able to resume rather than being gone for the rest of the round.
Spawned.
Ordered the crate.
Opened the crate.
Built an RnD setup using only the contents of the crate and a screwdriver.
:cl:
add: Adds the research and development crate.
/:cl:
=> Adds the Research & Development Crate - For Continuing Science After the End of the World

code/datums/uplink_items/uplink_general.dm, code/modules/clothing/spacesuits/syndi.dm
The descriptions of the syndicate space suits and the uplink have been altered to alert the user to the fact that the space suits do in fact provide protection from damage.
So people know it protects you without code-diving. I only found out about this today despite playing the game for years and years.
It compiled.
Saw the descriptions were changed.
:cl:
tweak: Syndicate space suits and uplink explainer tell you that they are armoured.
/:cl:
=> The Game Now Tells You That the Syndicate Space Suits Have Armour.

code/game/objects/effects/effect_system/effects_foam.dm
Fixes issues introduced in https://github.com/ParadiseSS13/Paradise/pull/25436.
This fixes chemfoam causing runtimes when trying to transfer reagents from foam to ghosts, and not transferring reagents to carbons/living mobs at all.
Foam should work, and it shouldn't explode with runtimes. Sorry!
:cl:
fix: Chemfoam will now properly transfer reagents to carbon mobs.
/:cl:
=> Fixes chemfoam reactions

code/game/objects/effects/mines.dm
An uppercase letter is now lowercase
Grammar good, mistakes bad.
It's just a single letter change.
:cl:
fix: Fixed a typo in description of mines.
/:cl:
=> Fix wrong capitalization in mine's description

code/modules/reagents/reagent_containers/hypospray.dm
Nanocalcium pens inject 10u of epinephrine alongside the nanocalcium now
This makes it slightly more robust in case you wanted to use this for quickly getting out of crit, which is one of it's intended uses
Injected pen
Saw epinephrine and nanocalc
:cl:
tweak: Nanocalciuminjectors now inject 10u of epinephrine aswell
/:cl:
=> Nanocalcium pens now inject 10u of epinephrine

code/datums/emote.dm
Fixes https://github.com/ParadiseSS13/Paradise/issues/26087
Oversight from the zombie PR. Fixed <3
N/A
*snap
*clap
*snap *snap *snap
:cl:
fix: Fixed emotes, they now have random frequencies when they're not age based.
/:cl:
=> fix: Emotes now vary in frequency when they are not age based.

code/game/objects/items/weapons/bio_chips/bio_chip_supercharge.dm
Removes a single letter.
Grammar.
It compiled.
:cl:
fix: Fixes a grammar error.
/:cl:
=> Removes a typo in the IPC adrenals chip.

code/modules/food_and_drinks/kitchen_machinery/icecream_vat.dm
Refactors the Cream-Master UI handling code and makes it a bit saner.
Bad code is bad.
Moved a bunch of liquids around in the Cream-Master. Worked as expected.
NPFC
=> [s] Refactor Cream-Master UI handling.

code/modules/food_and_drinks/kitchen_machinery/icecream_vat.dm
Makes it's reagent capacity 500 again
This was only relevant for big beakers and bluespace beakers
No tweaks in the feature freeze
It compiled
:cl:
fix: The icecream machine can hold more reagents again
/:cl:
=> Reverts a tweak of the icecream machine

code/datums/mind.dm
Capitalises "Syndicate", AN abductor, capitalise whatever comes after an ellipsis.
Warm fuzzy thoughts, good grammar.
It compiled.
:cl:
fix: Fixed some grammar errors.
/:cl:
=> Fixes Some Minor Grammar Errors That Most People Will Never See

code/modules/research/designs/biogenerator_designs.dm
Adds the nian worme to the biogenerator
Fixes #26178
On the original PR its shown that they'd added it to the biogenerator, and i cant see any reason/when it was removed, seemed to have been forgotten
Compiled
spawned biogenerator
spawned plant
melted plant
ejected a nian cube
vender crushed nian worme
:cl:
fix: Fixed nian worme cubes not being in the biogenerator, all is restored.
/:cl:
=> Adds the nian worme cube to the biogenerator

code/game/mecha/mecha.dm, code/modules/shuttle/shuttle.dm
Fixes mechs allowing their pilots to survive being shuttlegibbed.
Prevents the use of mechs for hijack cheese. Also it just doesn't make sense.
Stood under shuttle.
Died.
:cl:
fix: The shuttle actually kills you if you're a mech pilot, now.
/:cl:
=> [s] Fixes Mechs Protecting Their Pilots From the Crushing Force of a 2 000 Metric Ton Shuttlecraft.

code/game/machinery/rechargestation.dm
Fixes some logic to reenable the message telling someone if they can't enter a recharger
Bugs are bad, feedback is good, and this will help diagnose another bug I'm currently hunting.
Tried to get into a recharger without a modsuit and failed while getting a chat message. Tried to get into a recharger with a modsuit, as an IPC, and as a cyborg. They all worked properly.
:cl:
fix: Not being able to enter a recharger will give you a message again
/:cl:
=> Fixes not getting feedback on failing to enter a recharger

code/game/machinery/clonepod.dm
Title
Trust me
Properly ejected organs from the cloner
=> [S] Fixes a cloning exploit

code/game/objects/structures/noticeboard.dm
=> [S] Unfucks it please oh god

code/game/objects/items/stacks/sheets/glass.dm, code/game/objects/items/stacks/sheets/mineral.dm, code/modules/telesci/bscrystal.dm
Corrects some minor typos in extended descriptions of several mineral and glass items.
Good spelling is nice.
It still compiles.
:cl:
fix: Fixes some lore typos.
/:cl:
=> Fixes Some Minor Typos in Mineral & Glass Lore

code/game/gamemodes/miniantags/pulsedemon/pulsedemon_event.dm
- Makes sure that pulse demons can only spawn in powernets with 1000 or more watts, allowing them to not spawn in a dying powernet
- Properly checks the list of possible spawn locations
Pulse demons shouldn't instantly die
Resolves #26277
Spawned in as a pulse demon and didn't die instantly
:cl:
fix: Pulse demons should now die a lot less on spawn
/:cl:
=> Adds some Pulse demon failsaves

code/modules/antagonists/changeling/powers/mutations.dm, code/modules/projectiles/gun.dm
This PR slightly refactors tentacle on_hit code and makes it not runtime when shot point blank, also makes it work when shooting point blank
bugs bad, runtimes bad
compiled, shot tentacle point blank, from distance, all works as intended
:cl:
fix: Shooting tentacle point blank now works.
/:cl:
=> Tentacle works pointblank and not runtimes

code/game/objects/structures/kitchen_spike.dm
Makes meat spikes deconstructable 
Resolves #26300
You should be able to deconstruct these
Deconstructed meat spikes
:cl:
fix: Fixed meat spikes being indeconstructable 
/:cl:
=> Fixes indeconstructable meat spikes

code/game/gamemodes/objective.dm, code/game/gamemodes/objective_holder.dm
Fixes `replace_objective` not working properly
- Syndicate orgs can go on TM again
- This proc should work
Technically NPFC with a huge thanks to AA for making the TM revert so quickly
=> Fixes `replace_objective`

code/game/objects/items/stacks/stack.dm
Fixes #26273
Adds sublist identifier to the crafting buttons of items in sublists so they don't craft things from the main list.
It Fixes it
Made 20 tatami mats of each colour.
:cl:
fix: Fixes crafting multiples of recipes in a sublist
/:cl:
=> Fixes crafting multiples of recipes in a sublist

code/game/objects/structures/guillotine.dm
Fixes an issue where destroying a guillotine would nullspace whatever mob was buckled to it.
Bugs are bad.
Re-enacted the French Revolution and said the cake is a lie and decapitated a tajaran that looked like the cake kitty.
:cl:
fix: Fixed guillotines nullspacing upon being destroyed.
/:cl:
=> Guillotine no longer nullspaces people upon being destroyed.

tgui/packages/tgui-dev-server/util.js
Fixes TGUI Dev server after updating glob from 7.2.0 to 11.0.0
NPFC
=> Fix TGUI Dev Server

code/game/objects/items/weapons/storage/uplink_kits.dm
Pretty much the title, corrects alot of the prices for the syndicate bundles, as alot of them were outdated
correct prices for referencing is good
compiles, just comment changes
NPFC
=> Corrects the price comments for alot of the syndicate bundles

code/game/mecha/equipment/tools/other_tools.dm
Refactors `load_fuel` which was:
1. Atrocious
2. Barely worked
It wouldn't really like to grab bits from a stack, instead it was only the entire stack or nothing.
Ores are untouched. They will fill the generator to the max and then the entire ore stack will be deleted.
Resolves #26201
Filled a generator to the max, took a bit of fuel out, refilled until full.
:cl:
fix: Mech generators now can take fuel out of stacks instead of only taking the entire stack
/:cl:
=> Refactors `load_fuel`

code/_onclick/item_attack.dm, code/game/gamemodes/cult/blood_magic.dm, code/game/gamemodes/cult/cult_items.dm, code/game/gamemodes/cult/ritual.dm, code/game/objects/items/weapons/stunbaton.dm, code/modules/mob/living/carbon/human/human_defense.dm
Reverts attacked_by PRs which caused some issues
Compiled, tried cult spear, cult blade, cult dagger on exploding the mark, tried cult stun hand through the shield and without it, tried healing simplemob with a bruise pack, tried activating fulton pack
:cl:
tweak: Cult magic hands and cult mark exploding cant now be blocked by the shield
/:cl:
=> Revert attacked_by changes

code/modules/admin/misc_admin_procs.dm, code/modules/antagonists/zombie/zombie_spells.dm
Adds a missing `|` to the player panel after "make super hero" 
Currently at first glance it says "super hero animalalize" as its not split up with a vertical bar, this fixes that.
Compiled, checked the player panel
NPFC
=> Adds a missing `|` to the player panel after "make super hero" 

code/modules/mob/living/silicon/ai/ai_mob.dm
Resolves #26354
Makes AI cores not weirdly wrenched
This is very counterintuitive lmao
See above
:cl:
fix: AI cores are now normally wrenchable again
/:cl:
=> Fixes AI cores being weirdly wrenchable

code/_globalvars/lists/reagents_lists.dm
Corrects the comment of the general chem blacklist
That blacklist doesn't affect smoke, it affects bees and odysseus
Made sure the blacklist didn't affect smoke
NPFC
=> updates the general chem blacklist comment

code/modules/power/cell.dm
Fixes a bug from #25922 
Never trusting EOD with autodoc'ing code again
Bugs bad
:cl:
fix: Fixed a new issue with powercells
/:cl:
=> Fixes a new powercell bug

code/game/objects/items/weapons/bio_chips/bio_chip_supercharge.dm, code/modules/reagents/chemistry/reagents/drugs.dm, code/modules/reagents/chemistry/reagents/medicine.dm
Removes Combat Lube, and the addiction that came with it for some reason.
Makes Surge Plus function almost identically to a Stimulative Agent (minus some very slight OD differences, you'll probably never see them given you'd have to buy two implants and inject all the doses in at once).
Adds Smart Metal. It's omnizine but for IPCs. It replaces Combat Lube in the implant.
Adds Recal. It's synaptizine but for IPCs, and replaces Liquid Solder in the implant.
The IPC adrenals will function essentially identically to the regular adrenals instead of being objectively worse for no reason.
Became IPC. Injected self with biochip. Used it, got all the effects.
Punched and set self on fire. IPC-flavoured omnizine healed me after a while.
:cl:
tweak: IPC adrenals buffed to be like normal adrenals. …
=> Adjusts IPC Adrenals to be Like Regular Adrenals - Robotic Equality Update!

code/modules/surgery/organs/organ_external.dm
fixes: #26270
Fixes from grammar mistakes in the infection code.
example:
"the head feels like its burning!"
to
"your head feels like its burning!"
bugfix good
infected my everything
:cl:
fix: Fixed some grammar on infections
/:cl:
=> Fixes some grammar on infections

code/datums/uplink_items/uplink_general.dm, code/datums/uplink_items/uplink_traitor.dm, code/game/objects/structures/crates_lockers/crates.dm
Fixes surpluses runtiming when trying to spawn
:cl:
fix: Surpluses work again
/:cl:
=> Makes surpluses spawn items again

code/game/gamemodes/trifecta/trifecta.dm
Fixes trifecta not handing out proper delayed objectives
Trifecta should work without admin fixing
It compiled
I copied the code directly from traitors
:cl:
fix: Trifecta works again
/:cl:
=> Fixes trifecta not handing out objectives properly

tgui/package.json, tgui/yarn.lock
eslint-plugin-react finally supports eslint v9, so we change to it to resolve deps issues.
Bundle built without deps errors
=> Resolve TGUI eslint deps issue

code/game/objects/items/weapons/storage/fancy.dm
Fixes #26418
Strange question
Trust me
:cl:
fix: Rolling paper pack no longer disappearing when you take off 1 paper
/:cl:
=> Fix invisible rolling paper pack

tgui/.gitattributes
Explicitly declares that `.mjs` and `.cjs` files should be checked out with LF line endings
> [!NOTE]
> This PR does not affect existing clones. Line endings may be fixed in existing clones with the commands below. **<ins>PLEASE ENSURE NO UNCOMMITED CHANGES HAVE BEEN MADE BEFORE RUNNING</ins>**
> - Windows PowerShell or Command Prompt
>   `cmd /c "git diff-files --quiet && git checkout-index --force --all || echo Working tree dirty. Please ensure a clean repository before running."`
> - Bash
>   `git diff-files --quiet && git checkout-index --force --all || echo Working tree dirty. Please ensure a clean repository before running.`
Partial remedy to troubles faced in #26457
No notable changes available to test.
<hr>
<hr>
=> Update .cjs and .mjs files to use LF on checkout

code/__DEFINES/atmospherics_defines.dm
Adds comments to atmos defines that were referencing the wrong file
This way you don't have to move to a rust file to see what all the atmos modes do
More clarity and less painfully finding things
It compiled. It adds comments
<hr>
<hr>
NPFC
=> Adds comments to atmos defines

code/modules/mob/living/simple_animal/hostile/mining/elites/herald.dm
Makes cloak of the prophet work.
Makes cloak of the prophet work.
1. Spawn the cloak, spawn 2 mirrors.
2. Equip the cloak.
3. You can use mirror walk near a mirror.
4. Break 1 mirror.
5. You still can use mirror walk near a working mirror. 👍🏻
<hr>
<hr>
:cl: Maxiemar
fix: Cloak of the prophet is usable now.
/:cl:
=> Fix cloak of the prophet not working if a broken mirror exists

.vscode/settings.json
- Adds `tgui/public/**/*` to the list of excluded folders for VSCode find and search
Reduces search time and discards often unintended search hits
Searched for `Aleksej Komarov` in the codebase and verified that no hits were found in /tg/ui bundle files
<hr>
<hr>
=> Exclude /tg/ui bundle files from VSCode find and search

.github/ISSUE_TEMPLATE/issue_report.yml
Fixes a typo within the issue template, changing `occured` to `occurred`, the correct spelling.
Good spelling is infact good.
N/A
<hr>
<hr>
=> Fixes typo in issue_report.yml

code/game/objects/structures/kitchen_spike.dm
Fixes an exploit by correcting a faulty target check
Bluespace meatspikes are bad
Tried to push away a skrell while meatspiking them, worked properly
<hr>
<hr>
=> [S] Fixes a meat spike exploit

code/game/objects/items/devices/flash.dm
Fixes an oversight with a missed variable on cyborg flashes
They shouldn't be able to do that
Tried to open the flash as borg, couldn't
<hr>
<hr>
=> [S] Fixes a cyborg exploit

_maps/map_files/RandomRuins/SpaceRuins/syndiecakesfactory.dmm, code/game/area/areas/ruins/space_areas.dm, code/modules/mob/living/simple_animal/friendly/bunny.dm
Slightly tweaks the syndicake factory to have power again as it was incredibly cheeseable before hand.
Also adds a bunny subtype stopping the commando in the ruin from killing the bunny
Ruin cheese bad, practically two free bloodreds.
Also the poor bunny was getting killed on roundstart.
compiled, checked ruin was powered, and if the commando killed the bunny
<hr>
<hr>
:cl:
tweak: The syndicake factory has power again, as well as modifies the place slightly to give it power
tweak: the commando in the syndicake factory wont murder its own pet anymore.
/:cl:
=> Syndicake factory has power again. And the commando wont go crazy on its pet bunny.

code/game/objects/items/weapons/dna_injector.dm, code/modules/station_goals/bluespace_tap.dm
Renames the prebuilt small gene injector internally from midgit to small_size. Does the same with the antimidgit injector to anti_small_size.
Midgit is a bit derogatory, and it isn't even spelled right.
Opened game panel, spawned small size injector, used small size injector, shrunk. Spawned anti-small-size, used, grew.
<hr>
<hr>
=> Internally renames the small size to be more inclusive

code/modules/mod/modules/modules_supply.dm
Fixes a fauna aggro by properly passing in its arguments
Exploit bad
Tried to cheese hostile mobs, couldn't
<hr>
<hr>
=> [S] Fixes a fauna exploit

code/game/gamemodes/revolution/revolution.dm
Stops QM from becoming a head rev
MFW my head revolutionary is the person who we have to kill
[Insert surprised pikachu here]
It compiled
<hr>
<hr>
:cl:
fix: Fixed QM having the possibility of becoming a head rev
/:cl:
=> Fixes QM having the possibility of becoming a head rev

code/game/objects/items/dyeing.dm
Fixes #26559
`dye_item()` no longer tries to pull `var/list/sprite_sheet` off of the type itself. Instead, a new object is created from the type and the relevant variables are pulled from it before being deallocated at the end of the proc. I don't know if there's any other way to do this.
Bugfix.
Stuck a pair of black gloves in a washing machine with an orange crayon. Orange gloves popped out. Put the orange gloves on and observed orange gloves on my character.
<hr>
<hr>
:cl: Chuga
fix: Dyed items are no longer invisible when worn
/:cl:
=> Fixes #26559: "Dyed gloves do not appear on in-world sprite"

code/game/objects/items/toys.dm
You can now appreciate your pet rock!
The pet rock has long been unappreciated, and as a pet it deserves love. Now you can give it love and help your character mental stability doing so 
I went into the game and I pressed the use button while holding the pet rock in my hand!
<hr>
<hr>
:cl:
add: Appreciation for the pet rock when you press the use button
/:cl:
=> Added attack_self to the petrock so you can appreciate it

code/_onclick/hud/hud_datum.dm
`/datum/hud/Destroy()` now nulls the mob's `staminas` ref like it should have.
This causes GC failures in humans and is not good.
Before:
After:
there isn't a log because it deleted properly
<hr>
<hr>
NPFC
=> Makes human huds not harddel

code/game/gamemodes/cult/blood_magic.dm, code/game/objects/structures/aliens.dm, code/game/objects/structures/inflatable.dm, code/modules/awaymissions/mission_code/ruins/oldstation.dm, code/modules/clothing/glasses/tajblind.dm, code/modules/clothing/spacesuits/ert_hardsuits.dm, code/modules/mining/lavaland/loot/colossus_loot.dm, code/modules/power/apc/apc.dm, code/modules/power/engines/singularity/narsie.dm, code/modules/power/lights.dm
Found a few things not returning qdel hints while porting a more up to date ref tracking system. Also tries and somewhat fails to fix lightgeist harddels - at least its hud isn't hanging on anymore...
Not returning qdel hints is like not paying your taxes. In some cultures, this is considered bad. Morally, at least.
Game didn't blow up on initialization. 
<hr>
<hr>
NPFC
=> Makes various things return qdel hints on initialization

code/modules/paperwork/faxmachine.dm
This PR improves the logging of faxes within the game log.
Provides a clearer picture to administrators about what is being sent via fax.
Sent multiple faxes to different departments.
NPFC
=> Improves Fax Logging

code/datums/datumvars.dm
Adds VV open logs
Logs good
N/A
Not at all
<hr>
<hr>
NPFC
=> VV open logs

code/__HELPERS/unique_ids.dm, code/controllers/subsystem/SSstatpanel.dm, code/datums/datum.dm, code/datums/datumvars.dm, code/modules/client/client_defines.dm, code/modules/client/client_procs.dm, html/statbrowser.js
Fixes something bad while vauging the hell about it.
Also fixes my most recent PR.
Exploits bad.
Revealed to dev team
<hr>
<hr>
NPFC
=> [s] Fixes a pretty bad exploit in the most roundabout way

code/__DEFINES/_math.dm, code/__HELPERS/type2type.dm
See title. Functionality should not change except for the fact that the macro does not return `null` instead of `0` when given a string of 0's.
`hex2num()` is a very hot proc that is worth optimization due to its use in DNA code, lighting color calculations, and chat message color handling. This is what its profile results look like ~45 minutes into a live round:
| proc | Self CPU | Total CPU | Real Time | Overtime | Calls |
|---|---|---|---|---|---|
| /proc/hex2num | 0.594 | 0.604 | 0.595 | 0.062 | 332849 |
Over an entire round, the number of calls increases to nearly a million.
Macro vs proc benchmarks:
This is a _substantial_ speed gain for no cost.
Walked around in game, didn't find any runtimes, lighting issues, DNA issues, or chat message issues. 
<hr>
<hr>
=> Replaces hex2num proc with macro define

code/game/objects/items/weapons/storage/garment.dm, code/modules/client/preference/loadout/loadout_accessories.dm, code/modules/client/preference/loadout/loadout_hat.dm, code/modules/client/preference/loadout/loadout_suit.dm, code/modules/clothing/head/beret.dm, code/modules/supply/supply_packs/pack_security.dm
Adds Warden and Hos Berets to loadout
Tweaks Job Restricted Loadouts to have more Jobs available for it
| Job | Beret | Winter Coat | Bomber Jacket  | Armband |
|:---:|:---:|:---:|:---:|:---:|
| Captain | | | | Procedure |
| Head of Security | Head of Security |
| Warden | Wardens' |
| Detective | Security |
| Chief Medical Officer  | | | |  EMT |
| Virologist  | | | |  Medical |
| Paramedic | Medical |
| Geneticist | Medical, Research | Medical, Research | Medical, Research | Medical, Research |
| Shaft Miner | Cargo |
| Explorer | Cargo | | | Cargo |
also changes wardens' beret path to `/obj/item/clothing/head/beret/warden` 
instead of `/obj/item/clothing/head/beret/sec/warden`
Some people forgot to add loadout to some jobs or items when they first added it, this PR should cleanup some …
=> Adds and Adjusts Loadout Items

code/game/gamemodes/wizard/magic_tarot.dm
Tarot cards log now, who activated it and who was activated on.
Tower card specifically added to bomb log investigate
Better logging good
Threw cards and used cards to see the logs of them being activated.
Checked bomb log for the tower card.
<hr>
<hr>
:cl:
add: Improves tarot card logging
/:cl:
=> improves tarot card logging

code/modules/mining/equipment/mining_charges.dm
Removing syndicate technology in mining charges. Yeah, it also avaliable on Xray gunkit, but this one is literally free and can do roundstart.
I`m not sure if having free syndy tech with printing in protolathe is right idea, even if its a mere 1. 
1 line PR lets gooo
1 line PR lets gooo
<hr>
- [x ] I confirm that I either do not require [pre-approval](https://github.com/ParadiseSS13/Paradise/blob/master/CODE_OF_CONDUCT.md#types-of-changes-that-need-approval) for this PR, or I have obtained such approval and have included a screenshot to demonstrate this below.
<hr>
:cl:
fix: Free syndicate tech on mining charges have been removed.
/:cl:
=> Fixing syndicate tech on mining charges

_maps/map_files/stations/deltastation.dmm
Wall flashers on Kerberos/Deltastation now have the ID associated with the cell they are in, so the console actually activates the right flash when the flash button is pressed.
Fixes: #26499
Press "Flash" on a bunch of consoles.
They flash the correct flashers.
<hr>
<hr>
:cl:
fix: Kerberos wall flashers now linked to right cell console.
/:cl:
=> [DELTASTATION/FIX] Wall flashers now linked to right cell console

.github/workflows/devdocs.yml
Makes docs auto deploy to https://devdocs.paradisestation.org/
Final version of this wont have the PR events - I need them for testing
Deployments good
N/A 
We boutta find out
<hr>
N/A
=> Dev docs build rev 1

.github/workflows/devdocs.yml
This PR updates devdocs CI to watch for changes to the mkdocs.yml configuration as well as the docs directory itself.
Changes to how the docs site is built should rebuild the site.
<hr>
<hr>
NPFC
=> ci: watch mkdocs.yml for changes to publish

code/game/objects/items/salvage.dm
Title. Updates some lore, makes it more accurate and flow better.
lore accuracy good. description flow good.
- loaded
- spawned salvage
- observed salvage
- success
<hr>
<hr>
:cl:
tweak: changed some salvage lore
/:cl:
=> Updates some salvage lore

code/__HELPERS/unsorted.dm, code/modules/surgery/organs/augments_internal.dm
Adds some description text to cyberimplants to indicate where they go.
I always end up starting the wrong internal surgery for implants, it'd be really nice if you didn't have to go to the wiki for this every time.
See images.
<hr>
<hr>
:cl:
add: Cybernetic implants will now show the organ they belong inside of on examine.
/:cl:
=> Adds a message on examine of cyberimplants to indicate where they should be installed

code/game/objects/items/weapons/grenades/syndieminibomb.dm
Fix clown minibomb having 3 syndy tech. considering this item cost 5 TC, this is NOT normal tech per cost.
No clown you dont get 4 tech for 5 TC this is not the joke we want to see from you
1 line PR lets goooo
<hr>
:cl:
fix: Fix a clown minibomb having exact the same tech level as original one. 
/:cl:
=> Nerf Clown minibomb

code/game/objects/items/weapons/caution.dm
Fixes a thing.
Things should be fixed.
Tested the thing.
<hr>
<hr>
=> [s] Fixes a thing.

code/modules/mob/mob_misc_procs.dm
Fixes a runtime caused by offering a mindless body to ghosts
Runtimes bad
Offer a skrell
I am now a skrell
Also no runtimes
<hr>
<hr>
NPFC
=> [FIX/RUNTIME] Offering a body with no mind to ghosts no longer runtimes

code/game/mecha/mech_fabricator.dm, code/modules/research/rdconsole.dm
When a machine is (un)linked from an RND network it will now properly get removed/added to RND network controller.
Fixes: #26812
Linked machines should show up in the interface (And unlinked machines should properly be removed)
Unlink an RND console, it gets removed from the RNC console
Unlink an exosuit fabricator, it gets removed from the RNC console
Unlink an RND server, it gets removed from the RNC console
Link an RND console, it gets added to the RNC console
Link an exosuit fabricator, it gets added to the RNC console
Link an RND server, it gets added to the RNC console
<hr>
<hr>
:cl:
fix: Machines are now properly remove/added to the RNC console when (un)linked
/:cl:
=> [FIX] Now properly remove/add machines to the RNC console when (un)linked

code/game/objects/items/weapons/twohanded.dm
makes it check for magpulse over magboots specifically
modsuit magboots should work
used hammer with a skrell, as skrell with active magboots, and a skrell with active modsuit magboots
only the skrell was stunned and pulled
<hr>
<hr>
:cl:
fix: modsuit magboots save you from singulo hammer, rather than only normal magboots
/:cl:
=> modsuit magboots save you from singulo hammer

code/modules/awaymissions/mission_code/ruins/telecomns.dm
removes the energy shield module from dvorak as promised
replaces with portal gun to keep the pool at 4 items to not be too samey
it was too strong, and others were going to remove it but freeze / limit, I'll take the hit for the needed change
It is in the list and compiled, admittedly did not spawn the spawner till the gun showed up but should be fine
<hr>
<hr>
:cl:
tweak: Removes the energy shield module from dvorak ruin as promised, gives a portal gun instead
/:cl:
=> removes the energy shield module from dvorak as promised, gives a portal gun instead

code/modules/power/smes.dm
Unsets the broken flag on an SMES once a terminal is successfully built for it.
fixes it
- Made an SMES. It was considered broken, since it didn't have a terminal 
- Made a terminal and it was no longer broken
<hr>
<hr>
:cl:
fix: Successfully making a terminal for a SMES no longer leaves it broken
/:cl:
=> Successfully making a terminal for a SMES no longer leaves it broken

code/modules/station_goals/bsa.dm
Fixes a thing
Some things are not meant to be
Do the thing
The thing works
<hr>
<hr>
=> [s] [FIX] Exploit fix

code/datums/components/riding/riding_vehicle.dm, code/datums/status_effects/buffs.dm, code/game/machinery/clonepod.dm, code/modules/antagonists/vampire/vamp_datum.dm, code/modules/martial_arts/martial.dm, code/modules/mob/living/carbon/human/species/_species.dm, code/modules/mob/living/living_defines.dm
Protects living damage variables with SpacemanDMM. Makes a few small changes to fix where they were not properly protected.
Prevents contributors from accidently setting these variables directly
I joined, hit myself with a stunbaton. Seems to work fine.
<hr>
<hr>
NPFC
=> Protects living damage variables

code/game/objects/items/stacks/stack_recipe.dm
You can no longer stack structures on top of each other
You can no longer stack structures that you shouldn't be able to stack
Try to build the same thing a couple of times on the same tile, doesn't work.
<hr>
<hr>
:cl:
fix: You can no longer stack certain structures on itself
/:cl:
=> [s] [FIX] Structure stacking fix

code/modules/surgery/organs_internal.dm
fixes surgery
please help
removed lungs and it worked
<hr>
<hr>
:cl:
fix: Fixes surgery again
/:cl:
=> fixes surgery again please fuck

docs/CONTRIBUTING.md
Puts my name in the codebase
Gives me more power
Whats that
<hr>
<hr>
=> Adds me to CONTRIBUTING.md review team

code/__DEFINES/atmospherics_defines.dm, code/modules/atmospherics/gasmixtures/gas_mixture.dm
What the title says
fixes a bug
- filled a can with N2O
- set temp to 1401K and to 200000K
- Decomposition happened at the expected rate for each temperature
<hr>
<hr>
:cl:
fix: N2O now decomposes over 100000 Kelvin
/:cl:
=> Fixes N2O not decomposing above 100000 Kelvin

code/game/gamemodes/miniantags/guardian/guardian.dm
. = ..() instead of ..() to fix charger guardians
bugs are bad
I hate move code
I charged
it worked
yay
<hr>
<hr>
:cl:
fix: Fixes charger guardians
/:cl:
=> Fixes charger guardians

code/modules/mob/living/carbon/human/species/machine.dm, code/modules/surgery/robotics.dm
Repairing a robobrain in an IPC now properly revives it. You no longer need to kick a dead IPC that is no longer brain damaged to revive it.
Seems like an oversight, and is not well communicated enough to the player that they need to punch someone (they just repaired) for it to be good enough of a joke.
set brain damage on an ipc to 200
fixed their brain
they were alive again, wow
<hr>
<hr>
:cl:
fix: Repairing a robobrain in an IPC now properly revives the IPC
/:cl:
=> Repairing a robobrain in an IPC now properly revives the IPC

code/modules/surgery/organs/organ_extractor.dm
Swaps a target check, to user check.
Is is, trust. you could do some wonky things when it was checking for the target moving, rather than the user.
all functionality is retained, just fixes a nasty runtime.
tried multiple things as the user, and target. all worked as expected
<hr>
<hr>
:cl:
fix: Fixed a issue with the organ extractors implant function acting strange.
/:cl:
=> Fixes the organ extractor implant mechanic working in unintended ways.

code/_globalvars/lists/reagents_lists.dm, code/game/objects/items/weapons/grenades/chem_grenade.dm, code/game/objects/items/weapons/grenades/clusterbuster.dm, code/modules/reagents/chemistry/reagents/misc_reagents.dm
Adds some admin-focused reagents for efficient foam cleaning.
This adds three new reagents:
- One that cleans up (deletes) all items it comes into contact to,
- One that cleans up all mobs (by dusting, alive or dead) and body parts it comes into contact with, and
- One that cleans up *any* mob and obj it comes into contact with. Be careful with this!
This also adds grenades and clusterbusters that disperse these reagents.
These reagents and grenades are, naturally, only obtainable by adminbus.
The ways we have to clean up adminbus are a little unusual, there isn't really a great way to deal with large amounts of things like bodyparts without doing it surprisingly manually. While this is pretty cool, having better tools to deal with cleaning things up easily would be nice.
Threw some …
=> Adds some more admin-focused cleaning reagents

code/modules/research/designs/mecha_designs.dm
Fixes #27050 by ensuring the right module is printed from a circuit printer
Bugs bad.
Printed circuitboards at an imprinter. Got the right ones.
<hr>
<hr>
:cl:
fix: Janimech circuit boards print the right one
/:cl:
=> Nkarrdem CircuitBoard Fix

code/game/objects/items/blueprints.dm, code/modules/lighting/lighting_turf.dm
Registers machines in an area to its powernet during its creation
Less bugs more good
Made a room in space, placed machines there, created a new area via blueprint and powered it.
<hr>
<hr>
:cl:
fix: Fixes machines not registering on new area powernet 
/:cl:
=> Fixes machines not registering on new area's powernet when it is created

code/modules/mob/living/living.dm
Ports fix for floating animation from [here](https://github.com/ss220-space/Paradise/pull/2300)
Less bugs
Before fix
After fix
Tested on my local
<hr>
<hr>
:cl:
fix: Fix floating animation playing once.
/:cl:
=> Fix floating animation

code/modules/clothing/shoes/magboots.dm, code/modules/clothing/shoes/misc_shoes.dm
Fixes a thing
Exploit bad
Do the thing
No longer does the thing
<hr>
<hr>
=> [s] [FIX] Fixes a thing

_maps/map_files/shuttles/emergency_dept.dmm
Gives the correct access to the departmental shuttle cargo airlock.
Fixes https://github.com/ParadiseSS13/Paradise/issues/26868
Tried to open the airlock as miner, explorer, qm, cargo tech and as civilian
<hr>
<hr>
:cl:
fix: Departmental shuttle now has proper cargo access
/:cl:
=> Departmental shuttle now has proper cargo access

_maps/map_files/shuttles/emergency_bar.dmm, _maps/map_files/shuttles/emergency_clown.dmm, _maps/map_files/shuttles/emergency_old.dmm
Adds no diagonal smooth to some locations, where diagonal smooth would disconect lights or look ugly, or make black empty spaces
Better smoothing / no floating lights good.
some fixed areas:
forcing shuttles, inspecting visually.
Struggling with the top right corner tile on the clown shuttle till we put a window there to fix it suffering
<hr>
<hr>
:cl:
fix: Improves smoothing of small shuttles to prevent floating lights or black space
/:cl:
=> Fixes smoothing of small shuttles to prevent floating lights or black space

code/modules/projectiles/gun.dm
Fixes guns playing screwdriver sounds when they shouldn't. 
As well as makes attaching bayonets/seclights to guns play a sound
Bugs bad. fixes #26873
The sounds f0r adding are just neat, more audio feedback is nice.
[2024-09-30 21-32-30.webm](https://github.com/user-attachments/assets/6867b85e-b30b-45c1-bbeb-68762f157215)
checked if screwdrivers played sounds at correct times, as well as putting stuff on the guns
<hr>
<hr>
:cl:
tweak: Putting lights/bayonets on guns plays a click sound
fix: Fixed guns making screwdriver sounds when they shouldn't have.
/:cl:
=> Fixes guns playing scredriver sounds when they shouldn't be. as well as adds sounds to attaching stuff

code/game/gamemodes/wizard/artefact.dm, code/game/gamemodes/wizard/spellbook.dm, code/modules/mob/mob_misc_procs.dm
- Gives the scrying orb an extra 10 throwforce, up to 25
- Gives the scrying orb the boomerang component
- Hitting someone with the scrying orb will fracture the limb you are aiming at
It gives some extra functionality to the scrying orb, if you're crazy enough to potentially lose your xray
Threw the orb at a skrell, it did not like having the orb thrown at it
<hr>
<hr>
:cl:
tweak: the scrying orb deals more damage on throw, returns to your hand and fractures the limbs it hits
/:cl:
=> Improves the throwing capabilities of the Scrying orb

code/game/gamemodes/objective.dm
Hands out the extraction kits 5 seconds after the objective was handed out, because it is being created without having an `owner` passed
Also adds an option for admins to give a random steal objective because it's 2 lines of code
This should work.
Also some admin niceties for random steal objectives
Gave myself a random objective, gave myself both steal objectives that give out an extraction kit. No runtimes
<hr>
<hr>
:cl:
fix: [ADMIN] When giving someone the SM sliver / plutonium core objective, they now get their extraction kit properly
/:cl:
=> Fixes admin give objectives for supermatter sliver/plutonium core

code/modules/research/designs/weapon_designs.dm
Strong arm has a print time like other cybernetic implants.
Added to the mechfabricator like all other cybernetic implants (v1_arm is not as it requires blood)
Consistency, not confusing people
Was in protolathe in weapons and medical.
Was in exofabricator under medical
<hr>
<hr>
:cl:
fix: Adds strong arm to protolathe like all other cybernetic implants
/:cl:
=> adds strong arm to exosuit fabricator like all other cybernetic implants

code/game/mecha/equipment/weapons/weapons.dm
Fixes #27058 
Bugs bad. People should be able to use their equipment.
Put cleaner grenade launcher onto mech. Did not get error.
<hr>
<hr>
:cl:
fix: Fixed N23 Rotary Janitation Launcher unable to be mounted to the janitor mech
/:cl:
=> Janimech Cleaning grenade launcher mount fix

code/game/objects/structures/displaycase.dm, code/modules/mining/equipment/survival_pod.dm
Gives fake artefacts the inhands of the item they're copying
Also makes their weight class the same
Also moves the item from `/New()` to `Initialize()`
This is a fake and should be more fake
See above
<hr>
<hr>
:cl:
fix: Fixed fake artefacts not copying inhands correctly
/:cl:
=> Fixes inhands for fake artefacts

_maps/map_files/RandomRuins/SpaceRuins/ussp.dmm
Removes a random cable near the USSP station
Resolves #27031 
Having a random cable just out in space looks off-putting and doesn't fit
Loaded up a server, found the USSP station, no space cable to be found
<hr>
<hr>
:cl:
del: removed a stray cable near the USSP station 
/:cl:
=> Removes a stray cable at the USSP station

code/modules/paperwork/silicon_photography.dm
Re-adds the verb that allows silicons to change the size of their photo camera
Fixes: #24948 
This feature was removed unintentionally at one point, and never re-added
Be an AI.
Change my photo size.
Take a photo.
Look at the photo, it's 7x7.
<hr>
<hr>
:cl:
fix: Silicons can change the size of their photo camera again
/:cl:
=> [FIX] Silicons can change the size of their photo camera again

code/game/objects/items/his_grace.dm
Logs when/if his grace ascends to the black box
also how many mobs/victims they've eaten when the box is broken. 
Data is good, i'm going to attempt to balance this in the future, and knowing if they've ascended is a must for this
removed the mind check for his grace, ate 25 bodies two separate times, checked the blackbox controller, seemed to have worked. however i lack a DB to make 100% sure.
<hr>
<hr>
=> Black boxes his grace ascentions.

_maps/map_files/generic/centcomm.dmm
Removes a rogue stairway from the syndiebase
It should not have stairs in the middle of a window
None at all, it's a single-line SDMM change. I'm looking at MDB
<hr>
<hr>
:cl:
fix: The syndiebase doesn't have a rogue staircase anymore
/:cl:
=> Removes the stairway to heaven from the syndiebase

code/game/machinery/requests_console.dm
Should not be able to do that thing
Bad thing is bad.
Do the thing
Can't do the thing
<hr>
<hr>
NPFC
=> [s] Fixes a thing

code/controllers/subsystem/SSevents.dm, code/controllers/subsystem/tickets/SStickets.dm, code/game/mecha/combat/combat.dm, code/game/mecha/combat/honker.dm, code/game/mecha/equipment/mecha_equipment.dm, code/game/mecha/equipment/tools/janitor_tools.dm, code/game/mecha/equipment/tools/medical_tools.dm, code/game/mecha/equipment/tools/other_tools.dm, code/game/mecha/equipment/tools/work_tools.dm, code/game/mecha/equipment/weapons/weapons.dm, code/game/mecha/mecha_topic.dm, code/game/mecha/working/ripley.dm, code/modules/admin/topic.dm, code/modules/mob/language.dm, code/modules/mob/living/carbon/human/human_mob.dm, code/modules/mob/living/default_language.dm, code/modules/mob/living/simple_animal/bot/bot.dm, code/modules/mob/living/simple_animal/hostile/terror_spiders/terror_ghost_interaction.dm, code/modules/mob/mob.dm, code/modules/mob/new_player/new_player.dm
Fixes quite a few things
Oversights bad
Plenty of testing
<hr>
<hr>
NPFC
=> [s] Fixes a lot of stuff

code/modules/supply/supply_console.dm, code/modules/supply/supply_order.dm
Supply orders that have not yet been approved and that were ordered on a personal account get removed from the cargo console if the owner of the account cryos.
Fixes: #26864
Having orders that are permanently stuck in the request console is annoying.
Make an order that needs to be approved via personal account.
Cryo.
The order is no longer in the console.
<hr>
<hr>
:cl:
fix: Cargo request no longer are permanently stuck in the request console if the requester cryos.
/:cl:
=> [FIX] Cargo requests get deleted when requester cryos

code/game/gamemodes/autotraitor/autotraitor.dm
fixes autotraitors considering:
traders
mindslaves
temporary mindslaves
xenos
terrors
pulse demons
ert
fucking ghost bar
every antagonist ever
probably a fuck load of other stuff
as traitors, reducing the chance to actually make more traitors to a very small chance.
haha, so true bestie, that ghost bar occupant is a traitor, you totally should never spawn any antagonists.
<hr>
:cl:
fix: Autotraitor should spawn antagonists midround again more often than almost never
/:cl:
=> [s] autotraitor code moment number 82

_maps/map_files/generic/centcomm.dmm
Fixes assault pod missing chair and floating lights, couldnt track which PR caused this, but its been like that for a while.
Lights/pod control shouldnt be floating.
BEFORE
AFTER
See images above
<hr>
<hr>
:cl:
fix: Assault pod no longer has floating lights, and a missing chair was added
/:cl:
=> Fixes assault pod missing chair and floating lights

code/datums/uplink_items/uplink_traitor.dm
Changes the description of pda bombs in uplink to say it knocks the target down, not knock them out.
Explosions don't knockout anymore, and the pda bomb doesn't even hit hard enough to stun, so we update it to say it just knocks down.
It compiled, and passed spellcheck
<hr>
<hr>
:cl:
fix: PDA bomb uplink description says that it knocks down the target, rather than knock them out.
/:cl:
=> makes pda bombs not lie to you

_maps/map_files/RandomRuins/SpaceRuins/dj.dmm, code/datums/ruins/space_ruins.dm, code/game/area/areas/ruins/space_areas.dm, code/modules/paperwork/paper.dm
The fake solar arrays have been replaced with REAL solar arrays. The magic infinite power SMES has been replaced with a normal engineering SMES.
Replaces one of the solar arrays on the USSP listening post with a faux communications relay dish of impressive size.
Resizes the remaining solar arrays to compensate.
The solar arrays now actually track the real sun.
The APC now starts enabled, as the listening post is actually inhabited and the guy was just sitting in the dark before.
The custom airlock has been replaced with an airlock helper.
A second airlock has been added to the engineering section.
The external windows are electrified.
All light switches have been removed.
Includes a full set of status screens in the main room for better snooping on NT activities.
Storage has been improved …
=> Polishes the USSP Listening Post

code/datums/ores.dm
This PR fixes a runtime with datumized gibtonite calling ChangeTurf on its origin turf twice, causing a runtime. It also fixes gibtonite exploding twice.
Bugfixes.
<hr>
<hr>
:cl:
fix: Gibtonite will no longer explode twice.
/:cl:
=> fix: runtime when detonating gibtonite ores

code/modules/food_and_drinks/food/foods/baked_goods.dm
Fixes a runtime with Spaceman's Cake.
Runtimes bad.
Spawned a cake. Cooked a cake. Sliced a cake. No runtimes
=> Fixes a runtime with Spaceman's Cake

code/_onclick/hud/hud_datum.dm, code/game/objects/effects/decals/Cleanable/humans.dm, code/game/objects/effects/decals/cleanable.dm, code/modules/atmospherics/gasmixtures/gas_mixture.dm, code/modules/mob/living/simple_animal/hostile/hostile.dm, code/modules/mob/mob.dm
Fixes 4 runtimes and "fixes" a fifth by making it throw an error so that the issue can be further debugged.
Fixes #27132
Fuck runtimes
Bubblegum no longer shits out 10000s of runtimes
<hr>
NPFC (hopefully)
=> Fixes a bunch of runtimes

code/datums/spells/projectile_spell.dm
fix magic missile hitting the user if they move while casting it by making the user the firerer
it shouldnt hit the user
cast the spell and ran through the projectile without hitting myself
<hr>
<hr>
:cl:
fix: fix magic missile hitting the user if they move while casting it
/:cl:
=> fix magic missile hitting the user if they move while casting it

code/modules/mob/living/simple_animal/bot/bot_construction.dm
Fixes overlay for medibot construction.
Previously the overlays weren't being updated in the bots assembly state.
It's a bug fix.
Spawned in and built some medibots
<hr>
<hr>
:cl:
fix: Medibot construction overlays fixed.
/:cl:
=> Fixes medibot construction overlay

code/datums/mind.dm, code/game/gamemodes/objective_holder.dm, code/modules/antagonists/_common/antag_datum.dm, code/modules/antagonists/traitor/datum_traitor.dm
Tidies up some objective code
bad code bad
Compiles, the procs changed are equivalent
<hr>
<hr>
NPFC
=> Makes some code tidy

code/modules/projectiles/guns/projectile/toy.dm
fixes illegals levels added accidently in  #26984 , to reduce illegals levels, as this toy never had illegals in the first place, and it is in  the arcade machine
please no illegals 3 for 300 credits or 175 arcade tickets
Attempted deconstruction
No tech origin.
<hr>
<hr>
:cl:
fix: Fixes arcade illegals
/:cl:
=> [s] fixes arcade illegals

code/datums/ruins/bridges/bridges.dm
Adds a safeguard for bridge generation  to stop near the map borders
This can cause CI to fail sometimes
NPFC
=> Fixes bridges breaking CI sometimes

code/modules/awaymissions/mission_code/ruins/oldstation.dm
Fixes first aid kit on Theta station being called "generic first-aid kit".
It shouldn't be called this way. I forgot to change that name in the previous PR.
Compiled, checked out the name, all good.
<hr>
<hr>
:cl:
fix: First aid kit on Theta is no more called generic.
/:cl:
=> Theta first aid fix

code/game/machinery/vendors/wardrobe_vendors.dm, code/game/objects/items/weapons/storage/garment.dm, code/modules/mining/mine_items.dm
Adds the respective departmental envirosuits to the departmental clothes vendors, garment bags and lockers. From the vendors, helmets and uniforms both cost 60 credits. Justification being a sealed suit and a helmet that has built in welding protection and flashlight would be quite costly.
The lack of envirosuits makes departmental changes unpleasant, as you'll forever look like a tider, your old job or an underling. This also allows plasmamen to have more drip.
Mapped in the departmental clothes vendors, garment bags and lockers. Checked them and refilled a vendor.
<hr>
<hr>
:cl:
add: departmental envirosuits to departmental vendors, garment bags and lockers.
/:cl:
=> Adds plasmaman envirosuits to departments

code/modules/surgery/surgery.dm
Fixes surgery delays when there is lots of blood or many people nearby
https://github.com/user-attachments/assets/c64f286a-aa7b-4bf1-8605-6d7a369754e1
oversight bad, lag bad, delay bad
https://github.com/user-attachments/assets/f1462279-da81-48bc-8425-49049e68d02e
<hr>
<hr>
:cl:
fix: Surgery no longer lags when surrounded by a lot of blood or people
/:cl:
=> Fixes surgery delays

code/modules/mapping/station_datums.dm, tools/pr_sql/27431/script.sql
Unreverts #27429. Should only be merged after an SQL script is run on the DB.
```
UPDATE round 
SET map_name = 'DeltaStation' 
WHERE map_name = 'Delta';
UPDATE round 
SET map_name = 'BoxStation' 
WHERE map_name = 'Cyberiad';
```
This shouldn't break things so long as the script is run.
As before.
<hr>
<hr>
=> Unreverts Updates the technical names of BoxStation and DeltaStation

code/modules/projectiles/guns/projectile/sniper.dm
Lowers syndicate sniper rifle execution speed to 4 seconds
With limited ammo, long CD between shots and stun in one shot, you really expect to kill the target and disappear but you cant because its 8 seconds to execute. With its time being lowered to 4 seconds, sniper rifle becomes really fast one person kill weapon
Compiled
<hr>
<hr>
:cl:
tweak: Syndicate sniper rifle aka SR-31C sniper rifle execution time(when you aim at mouth point blank) is reduced to 4 seconds.
/:cl:
=> Lowers syndicate sniper rifle execution speed to 4 seconds

.github/workflows/render_nanomaps.yml
Fix syntax error in `render_nanomaps.yml`, scan stderr and pass the action with code 0 instead of code 78.
Works on my fork.
<hr>
<hr>
NPFC
=> Fix nanomaps render failures

code/game/objects/items/weapons/twohanded.dm
Reduces the stamina reduction to 75%
Makes it so it can only parry melee attacks
Reduces the cooldown to 2.1 seconds
Its a roundstart broom, this statstick was a bad copypaste probably
<hr>
<hr>
:cl:
tweak: The normal pushbroom is now a bit worse at parrying
/:cl:
=> [s] Nerfs the normal push broom

code/modules/projectiles/guns/energy/special_eguns.dm
Plasma pistols can no longer be charged, have their hand switched, so you can charge a second, switch to the first, fire, switch to second, fire. That was not intended, sorry downstream.
This is not supposed to be a 2 hand spamed weapon, alas.
Charged plasma pistols normally, fine.
dropped em, fine. 
Swapped hands charging, failed to charge.
Charged, swaped hands, discharged.
<hr>
<hr>
:cl:
fix: Fixes a plasmapistol exploit.
/:cl:
=> [s] fix plasmapistol exploit

code/datums/diseases/_MobProcs.dm
Fixes #27273 
Changes it from the jumpsuit slot flag to H.w_uniform
Disease good. Disease no work bad.
It compiled. Take it or leave it.
<hr>
<hr>
:cl:
Fix: jumpsuits properly contribute to virus resistance
/:cl:
=> Fix: jumpsuits properly contribute to virus resistance

_maps/map_files/stations/emeraldstation.dmm
Removes a steel table and food processor seemingly placed by mistake in Mr. Chang's at some point in the past.
Misplaced map objects aren't very good.
Before and after: 
Spun up a test server, mosied on over to Mr. Chang's. Found myself sad that I could no longer make my own meatballs in a family restaurant. 
<hr>
<hr>
:cl:
del: Removed two stray objects in Mr. Chang's
/:cl:
=> Removes a pair of stray objects in Emeraldstation's Mr. Chang's

code/datums/ai_laws_datums.dm, code/modules/admin/misc_admin_procs.dm
Fixes Stacking with the Check AI Laws verb. Also gives it a chat box around it.
Also makes the verb ignore clientless decoy silicons.
Makes using the verb a lot easier!
See above
<hr>
<hr>
NPFC
=> Fixes Stacking with the Check AI Laws verb

code/modules/admin/verbs/randomverbs.dm
Adds better logging for the "Show Custom Tip" verb
Lets fellow admins see what the custom tip will be
See above
<hr>
<hr>
NPFC
=> Better logging for Custom Tips

code/game/turfs/simulated/floor/asteroid_floors.dm
Fixes #27503 
Prevents you from unscrewing asteroid  turfs.
Doesn't really make sense why you can unscrew dirt.
Mapped in lavaland basalt turf, tried screwing it. It didn't do anything.
Placed grass, tiles. Worked like before.
<hr>
<hr>
:cl:
fix: Can't unscrew natural turfs anymore.
/:cl:
=> Fix: cant screw dirt anymore

docs/CONTRIBUTING.md
it says it on the tin
good?
i sure didnt
<hr>
<hr>
=> Add chuga to review team in CONTRIBUTING.md 

code/modules/food_and_drinks/drinks/drinks/drinkingglass.dm
Just uses init values instead of hardcode
future proof
=> use initial values for drinking glass name

code/modules/research/xenobiology/xenobio_camera.dm
Fixes #27575 
Replaces the new procs with legacy procs until the console is migrated
Feeding slimes potions is fairly integral to xenobio
Fed a slime potion to a slime by hand, with the machine keybind and with with the machine UI button.
<hr>
<hr>
:cl:
fix: Slime management console can feed slime potions again
/:cl:
=> Fix: The slime console can feed potions to slimes again

code/game/objects/items/his_grace.dm
Migrates his grace to the new attack chain
new attack chain good. needs to be done for a future pr
Killed a heap of things, broke a heap of things, all on various intents, all seemed right
<hr>
<hr>
NPFC
=> his grace attack chain migration

code/modules/power/engines/supermatter/supermatter.dm
The SM is supposed to only output heat up to a certain temperature, however when going beyond it it would cool things down instead. This is an oversight
This PR makes it only stop outputting heat when going beyond the temp(which itself depends on the gas mix).
Shouldn't work as it did
- Dumped hot gas into the SM and also set it alight and observed it not cooling down when it shouldn't
<hr>
<hr>
:cl:
tweak: SM now only stops outputting heat, rather than cooling gas down.
/:cl:
=> SM no longer cools down gas

_maps/map_files/stations/deltastation.dmm
=> [s] Fixes some stuff

code/__DEFINES/gamemode.dm, code/__HELPERS/trait_helpers.dm, code/game/gamemodes/objective.dm, code/game/machinery/cryopod.dm
Makes it so you can't reroll targets that are being despawned in cryo, usually your own target.
Fixes #27629. Fixes #19433.
Bug bad.
Spawned myself in as an assistant. Made another human with a mind, and then made them a traitor until I was their assassinate target. I then cryod. The objective did not reroll to the cryo'd person.
<hr>
<hr>
:cl:
fix: You can no longer re-roll objectives onto people that just cryo'd.
/:cl:
=> Prevent re-selection of targets on cryo

_maps/map_files/stations/emeraldstation.dmm
Fixes the disposals in science hallway of emerald station by robotics as it was broken
(the bin in the hall, and in the mechbay would both lead to the mechbay disposals
Fix
(pipes and cable removed for visual clarity)
compiled. checked if both bins were correct
<hr>
<hr>
:cl:
fix: [Emerald station] Fixes the disposals going from mechbay to sci hallway, and sci hallway to disposals being piped incorrectly
/:cl:
=> Fixes disposals in emerald stations science hallway

code/game/objects/effects/snowcloud.dm
Fixes snow being on the wrong plane, fixing majorly the ambient occlusion.
Looks less shit™️
Current:
New:
<hr>
see above
<hr>
:cl:
fix: Snow on the ground no longer hides shadows
/:cl:
=> Fixes snow being on the wrong plane

code/modules/hallucinations/hallucination_manager.dm
I don't know how I haven't run into this one yet but god this is such a silly thing
Saves everyone a lot of frustration
In another branch I rewrote the xeno pounce to a manager, it worked after I included this line
NPFC
=> Fixes hallucination managers ... again

code/game/atoms.dm, code/game/machinery/doors/airlock.dm, code/game/machinery/doors/door.dm, code/game/machinery/doors/windowdoor.dm, code/game/objects/items/devices/megaphone.dm, code/game/objects/items/weapons/AI_modules.dm, code/game/objects/items/weapons/agent_id.dm, code/game/objects/items/weapons/cards_ids.dm, code/game/objects/items/weapons/clown_items.dm, code/game/objects/items/weapons/grenades/grenade.dm, code/modules/economy/economy_machinery/atm.dm, code/modules/food_and_drinks/food/foods/pizza.dm, code/modules/hydroponics/gene_modder.dm, code/modules/mining/machine_vending.dm, code/modules/mob/living/simple_animal/bot/honkbot.dm, code/modules/supply/supply_console.dm
Converts:
/obj/item/card/cmag
/obj/item/card/emag
/obj/item/card/emag/magic_key
/obj/item/card/id
/obj/item/card/id/golem
/obj/item/card/id/syndi_scan_only
/obj/item/card/id/syndicate
/obj/item/card/mining_point_card
to the new attack chain.
Makes cmag act return true when successful, false otherwise.
Converts further.
Needed for heretic.
Good practice.
emagged so much shit (doors airlocks apcs things that can't be emaged organs)
emagged cyborgs
emagged IPC (robolimbs)
tried to emag normal human, failed, no animation
put emag on a table
Copied access from ids
flashed ID's
unlocked apcs with proper access, could not unlock otherwise.
edited agent id
registered golem card.
<hr>
<hr>
NPFC
=> Attack Chain Migration: /obj/item/card

code/__DEFINES/__proc_refs.dm
Improves comments
Don't confuse people when the autodoc lies
None, just comment adding
NPFC
=> Makes the autodoc comments slightly better on `PROC_REF` and related defines

code/game/objects/items.dm, code/game/objects/items/weapons/storage/storage_base.dm, code/modules/mob/inventory_procs.dm, code/modules/mob/living/carbon/alien/larva/larva_inventory.dm, code/modules/mob/living/carbon/carbon_procs.dm, code/modules/mob/living/carbon/human/human_inventory.dm, code/modules/mob/living/silicon/robot/robot_inventory.dm, code/modules/mob/living/simple_animal/simple_animal.dm, code/modules/mob/living/simple_animal/slime/slime_mob.dm
Reverts ParadiseSS13/Paradise#27694
=> Revert "Fixes for inserting/removing storage items/swapping items between hands."

code/modules/client/preference/preferences.dm
Read the title.
Knowing there's a save button is good, actually
:cl:
fix: The preferences window is slightly larger.
/:cl:
=> Expands the size of the preferences window to fit the height of the default content

code/modules/mob/inventory_procs.dm, config/example/config.toml
Fix for https://github.com/ParadiseSS13/Paradise/issues/27712
Bags are bad! We kill thouse!
Tested on local host
<hr>
<hr>
:cl:
fix: Now can't equip cards and belts throw active anti drop implant
/:cl:
=> [Fix] for anti drop being able to equip some items

.github/workflows/ci.yml, _build_dependencies.sh
Re-enabled CI for beta BYOND builds
Its that time again
N/A
We boutta find out
<hr>
<hr>
NPFC
=> Re enables beta CI

code/modules/mob/living/simple_animal/hostile/retaliate/combat_drone.dm
Refactors malf drone loot to use subtypes instead of some halfbaked bit picking
Oh my god why would  you ever do it like this
Tech levels were also all good
<hr>
NPFC
=> Rewrites some very very bad malf drone code

code/modules/antagonists/cult/team_cult.dm
Moves the recount timer start to `create_team()`
This is more sane than in `New()`
It compiled
<hr>
NPFC
=> Moving around the recount timer for the cult datum

code/datums/spell.dm
Removes some more unused variables
Less variables on a very crowded datum
Compiled
<hr>
NPFC
=> More spell var removals

code/_globalvars/lists/reagents_lists.dm
exploit fix
aaguh
tried todo it, couldn't
<hr>
<hr>
=> [S] Fixes a bad oversight

code/modules/events/traders.dm
Fixes a typo in the Cybersun trader
I notice this every time and it hurts my eyes, brain, and soul
I didn't test this lol
<hr>
<hr>
:cl:
fix: cybersun trader typo
/:cl:
=> Fix a small typo in the Cybersun trader event

code/game/gamemodes/changeling/changeling.dm, code/game/gamemodes/cult/cult_mode.dm, code/game/gamemodes/trifecta/trifecta.dm, code/game/gamemodes/vampire/traitor_vamp.dm, code/game/gamemodes/vampire/vampire_chan.dm, code/game/gamemodes/vampire/vampire_gamemode.dm
See title.
Fixes mistake.
I couldn't locally.
<hr>
<hr>
=> [s] Blacklists Nanotrasen Career Trainer from antag roles

code/modules/vehicle/janivehicle.dm, code/modules/vehicle/vehicle.dm
Fixes a bug
Tested, didn't happen
<hr>
:cl:
fix: Vtec is a bit more sane now
/:cl:
=> [s] Vtec fix

code/modules/research/strange_objects.dm
Fixes an exploit regarding research levels and strange objects.
Exploits bad.
Spawned strange object. Discovered it. Tried to research duplicates made from it. Got response that they had no tech levels.
<hr>
<hr>
:cl:
fix: Fixed an exploit with research levels and strange objects.
/:cl:
=> [s] Strange Object Research Level Fix

code/modules/reagents/chemistry/reagents/food_reagents.dm
Adds nutrients to cheese from pouring cheese on the ground
Mfw cheese hollow, mice ate it all?
Literally none
<hr>
:cl:
fix: cheese gained from pouring cheese on the ground now has nutrients again
/:cl:
=> Cheese reagent cheese has nutrients!

code/game/gamemodes/autotraitor/autotraitor.dm
This adds some additional logging and admin messages into the game log.
Helps administrators track what is going on in the round.
TBD
<hr>
<hr>
NPFC
=> Adds Additional Logging for AutoTraitor Game mode

docs/CONTRIBUTING.md
Replaces Steelslayer with Contrabang in the list of headcoders.
I accidently pushed a bunch of commits to my master and had to undo them, and then forcepush to my master branch. I will be an excellent headcoder.
NPFC
=> Adds Contrabang to Headcoders in CONTRIBUTING.md

code/datums/status_effects/buffs.dm
Makes His Grace buff heal IPCs (and robo limbs by extension).
IPCs my beloved. This was probably an oversight and it's not like IPCs don't deserve to have the full benefit of Gracing it up.
Smacked myself with His Grace in the chest, healed back up to full normally as you'd expect.
<hr>
<hr>
:cl:
fix: IPCs heal while using His Grace
/:cl:
=> make his grace heal IPCs

code/modules/mob/living/silicon/robot/robot_mob.dm
Changes one FALSE to a TRUE
Fixing an oversight. Additionally gives Rovers their own line to remain hat restricted.
It just works
<hr>
<hr>
:cl: ATP Engineer
fix: Fixed cyborg skins that used to have hats, not being able to wear hats after they got removed.
/:cl:
=> Fixes old Humanoid cyborg sprites, to actually be able to wear hats. Now that they don't already have some.

code/controllers/subsystem/SSair.dm, code/modules/shuttle/shuttle.dm
Shuttles have air again.
Air good.
Ran a loop of the supply shuttle, had air the whole way.
<hr>
<hr>
:cl:
fix: Patched the massive hole in all shuttles. They'll hold air again.
/:cl:
=> Shuttles have air again.

.github/workflows/ci.yml
Reverts ParadiseSS13/Paradise#27891
OD Lint fixed. 
Bypass required.
=> Revert "Disable OpenDream CI as it's busted"

code/modules/client/preference/preferences.dm
The randomize button now clearly says so
No more errant and accidental randomizations
<hr>
:cl:
tweak: The body randomize button is now a bit more clear in what it does
/:cl:
=> Makes the randomize body button more obvious

tools/pr_sql/27474/neckconvert.py
An updated version of the Python script found in #27474 written by Affected.
This one should actually work.
This is just an updated tool.
I can't myself but Affected ran this script on the server when #27474 was merged.
<hr>
<hr>
=> Neck convert script update

.github/workflows/ci.yml
Proper implementation of #27914
=> NET9 SDK for OD Lint

code/__DEFINES/icon_smoothing_defines.dm
Didn't notice a bug in my grimey flooring PR, this fixes that quickly.  Hopefully we can get this in before next round, lol
people saw it and was scared by it
loaded it up ingame, was fixed, thats all really
<hr>
<hr>
:cl:
fix: Fixed Grimey Flooring
/:cl:
=> Quick Bandaid Fix, Reorders Smoothing to fix Grimey Flooring

code/modules/mob/language.dm
Reworks Bubblish to be a more expressive language.
Bubblish is a very lackluster language with few syllables, falling behind compared to other languages' dozens, each with their own unique say, ask, and exclaim. Every sentence ends up boiling down to "Bloopy Fizz bubbles and pops, 'Blopplopbop. Bopblopboop.'" I have added sloshy, squishy syllables and a more expressive say, ask, and exclaim that will hopefully make the language less of an eyesore.
Ran a paracode server, used the forcesay verb on a slime whilst posessing a character that does not speak Bubblish. Results in the above image.
<hr>
<hr>
:cl:
tweak: Alters Bubblish to be more expressive.
/:cl:
=> Bubblish Changes

code/__HELPERS/unsorted.dm, code/controllers/subsystem/SSticker.dm, code/game/gamemodes/cult/runes.dm, code/game/objects/items/devices/enginepicker.dm, code/modules/events/communications_blackout.dm, code/modules/events/money_spam.dm, code/modules/mob/living/silicon/ai/ai_mob.dm, code/modules/mob/new_player/new_player.dm
Veeery small perf improvements because we're searching through a smaller list
It's a better practice
Visual inspection, it compiled
<hr>
<hr>
NPFC
=> Makes some loops use `GLOB.ai_list` instead of other various lists

code/game/mecha/equipment/tools/work_tools.dm, code/game/objects/items/weapons/RCD.dm, code/modules/mob/living/silicon/robot/robot_mob.dm
Nerfs the borg RCD. It now uses normal cartridges. The Syndicate version for borgs is untouched.
Also migrates the attackchains for RCDs
As a borg it's incredibly easy c urrently to just fill the AI sat with doors or other various things. This way you need to actually go back and get more cartridges instead of just getting a yellow core or sitting in a recharger for 10 seconds.
It also works when you click on a cartridge with an RCD
See above
<hr>
<hr>
:cl:
tweak: Borg RCDs now take cartridges. Syndicate borg RCDs are unaffected
/:cl:
=> Borg RCD nerf + migration to new attack chain

code/game/objects/structures/safe.dm
Fixes #27821 . . . at least the part of it that is actually a bug.
You'll now hear safe cracking sounds when wearing a stethoscope.
It's a bug fix.
Loaded into game and hacked a safe while wearing a stethoscope on my neck.
<hr>
<hr>
:cl:
fix: Fixed safe cracking sounds while wearing a stethoscope on neck.
/:cl:
=> Stethoscope Cracking Sounds Fix

code/datums/datumvars.dm, code/game/atoms.dm, code/game/atoms_movable.dm, code/game/objects/objs.dm, code/modules/mob/mob.dm
Fixes some hrefs
Possibly fixes VV dropdowns when using 516
We'll do it live!
<hr>
<hr>
NPFC
=> [TM FIRST] 516 Prep/Fixes regarding hrefs

code/modules/admin/verbs/randomverbs.dm
Updates "Check New Players" verb to have less shitcode and have an option for playtime also
Good admin tooling and less shitcode
Compiles, lets me input numbers. The rest needs to be tested on something with a database
<hr>
<hr>
NPFC
=> Updates "Check New Players" verb

code/modules/client/preference/loadout/loadout_glasses.dm, code/modules/client/preference/loadout/loadout_hat.dm, code/modules/client/preference/loadout/loadout_uniform.dm
Makes all sec clothing in the loadout menu available to the detective.
Easier drip customisation for the det.
Spawned in as det with a sec cap, classic sec HUD and a corporate uniform.
<hr>
<hr>
:cl:
tweak: All security clothing/glasses are now available to the detective in the loadout menu.
/:cl:
=> Makes all sec clothing in the loadout menu available to the detective

code/modules/clothing/head/helmet.dm, code/modules/clothing/suits/armor_suits.dm, code/modules/clothing/suits/misc_suits.dm
Adds or updates the descriptions and names of most common sets of armor in the game.
Lore good. Descriptions that tell you what an item does are also good.
- Loaded in
- Spawned armor
- Observed armor
- Descriptions are updated
<hr>
<hr>
:cl:
tweak: Updated a lot of armor lore
/:cl:
=> [LORE] Decently Sized Armor Lore Drop

code/game/objects/structures/mirror.dm
Adds slime people to the magic mirror. Primarily done so there can be Slime People wizards.
I tried this with Machine as well and noticed some issues that would take more effort to fix, generally other races' customization options spilled over into the machine's appearance.
More player options is good.
Joined the round as a wizard, became a slime person, became all the other races, became a slime person again, didn't notice any oddities.
<hr>
<hr>
:cl:
tweak: Add slime people as an option to magic mirrors
/:cl:
=> Add slime people to the magic mirror

strings/sillytips.txt
Removes an extra space
No double space
Absolutely none
NPFC
=> Removes an erroneous space in sillytips

code/modules/clothing/clothing.dm
While fixing #26520, the check for that wasn't compatible for mobs messing with other mobs, so the old check had to be put back side by side with the other.
Fixes #28112 and keeps the ability to change your own sensors while in stuff.
Changed a mob's sensors while in a closet, then let another mob change them. Also checked for distance changes.
<hr>
<hr>
:cl:
fix: Suit sensors can be toggled on other people again
/:cl:
=> Fix suit sensor toggling done by other mobs

code/game/objects/items/granters/action_granters/summon_cheese.dm, code/modules/antagonists/traitor/contractor/datums/syndicate_contract.dm, code/modules/food_and_drinks/food/foods/frozen.dm, code/modules/food_and_drinks/food/foods/ingredients.dm, code/modules/food_and_drinks/food/foods/pizza.dm, code/modules/food_and_drinks/food/foods/seafood.dm, code/modules/food_and_drinks/food_base.dm, code/modules/food_and_drinks/recipes/recipes_grill.dm, code/modules/food_and_drinks/recipes/tablecraft/recipes_table.dm, code/modules/reagents/chemistry/reagents/food_reagents.dm, code/modules/reagents/chemistry/recipes/slime_extracts.dm, tools/UpdatePaths/Scripts/28146_sliced_REPATH.txt
Addresses some issues that was not addressed in PR https://github.com/ParadiseSS13/Paradise/pull/27807
I need to fix what i broke.
Spawned all `/obj/item/food/sliceable` objects, insured there is no errors.
<hr>
:cl:
tweak: The syndicate's prison bread now has the same nutritional values as the regular one, which is slightly less than what it used to be.
/:cl:
=> [FIX] Follow up PR on "Better slices"

code/__DEFINES/dcs/movable_signals.dm, code/datums/components/drift.dm, code/game/atoms_movable.dm, code/modules/mob/mob_grab.dm
Prevents a source of MC failures
MC should not fail.
MC didn't fail.
<hr>
<hr>
NPFC
=> [s] Prevent a source of MC failures

code/game/objects/items/devices/scanners.dm
non-detailed gas reports sum the pressure instead of calculating with the total volume and temp.
Fixes a bug
- Scanned small and large pipenets and compared the received value to one manually calculated using the detailed report
<hr>
<hr>
:cl:
fix: Corrects the pressure shown on non-detailed gas scan reports.
/:cl:
=> Corrects the pressure readouts on non-detailed gas reports

_maps/map_files/stations/deltastation.dmm
Title.
All rooms should have fire alarms, especially as low pressure atmos alerts now trigger fire alarms, which cannot be turned off if there's no fire alarm.
<hr>
<hr>
:cl:
Fix: Adds Missing Fire Alarms to Delta Courtroom, Courtroom Gallery, Magi Office, and IAA Office
/:cl:
=> Adds Missing Fire Alarms to Delta Courtroom, Courtroom Gallery, Magi Office, and IAA Office

code/modules/power/engines/supermatter/engineering_event.dm
Fixes infinite / unending SM events.
FIxes SM events not being announced.
Bugs are bad.
Forced a few events, let them run through their duration, ensured they ended and announced as such.
<hr>
<hr>
:cl:
fix: Fixed infinite duration SM events.
fix: Fixed unannounced SM events.
/:cl:
=> Fixes SM events

code/modules/power/engines/singularity/collector.dm
Returns ITEM_INTERACT_COMPLETE once a tank is inserted into a rad collector so you don't hit it with the tank you've just inserted
Fixes bug
- Inserted a plasma tank into a collector without bonking it, and bonked it with some other stuff
<hr>
<hr>
:cl:
fix: Stops collectors from being hit by tanks inserted into them
/:cl:
=> Stops collectors from being hit by tanks inserted into them

README.md
Draft for TM sake.
This is just so I can compile the rustlibs for the right damn CPU because the action wouldnt detect on the other PR because it was in the diff not the master branch.
Ugh
Prod is my test
<hr>
<hr>
npfc
=> Actually build the rust libs for the right CPU

docs/CONTRIBUTING.md
Adds some weirdo to the maintainer list
More nerds for the nerd pile.
No, thanks. I'm allergic.
<hr>
<hr>
As my mother told me:
Never Poke Feral Cats
=> Add FunnyMan3595 to maintainer list

code/game/objects/items.dm
Makes item action buttons call the right new attackchain proc
Things working is nice
<hr>
:cl:
fix: Item action buttons, like the flayer radio jammer, work again
/:cl:
=> Makes ui buttons call the right proc for the new attack chain

code/modules/antagonists/mind_flayer/powers/flayer_passives.dm
Changes the background of the radio jammer Flayer ability to the flayer specific background.
Edit: Does the same for the telescopic eyes flayer ability.
Squashes a visual bug
Before:
The jammer icon is the flayer ability.
After:
The first jammer is the flayer ability, the second is an actual jammer traitor item.
Made myself a flayer, gave myself the ability. Checked to make sure the normal jammer still has the normal background.
Gave myself the telescopic eyes ability. Made sure the background was right.
<hr>
<hr>
:cl:
fix: Flayers' radio jammer and telescopic eyes abilities have the right background
/:cl:
=> Fixes the flayer radio jammer action button background

code/__DEFINES/gamemode.dm, code/game/gamemodes/dynamic/antag_rulesets.dm, code/game/gamemodes/dynamic/dynamic.dm, code/modules/admin/topic.dm, config/example/config.toml
Cult gamemode is now part of dynamic. Rulesets can also not roll if there is not enough minimum budget for them (7 players per traitor and theres only 6 players online? No traitors can roll.)
Ruleset cost = 1
Ruleset weight = 3
antag_cost/minimum players = 30
Cult cannot roll with traitors, vampires, changelings, or mindsflayers.
Removes the cult gamemode from rotation.
It helps improve code. Will also help in heretic addition.
Compiles, I was able to force myself roundstart onto the cult team. A TM is likely needed.
<hr>
<hr>
NPFC
=> Cult is now part of dynamic

code/modules/admin/verbs/debug.dm
Big red text and more debug info is now included in the "god help you" message. It used to be "adminotice" but that got removed so I changed them all to "userdanger"
Big red text helps read better. Also info lets you know what you fucked up.
See above
<hr>
<hr>
NPFC
=> Improves runtime info during admin proc calls

code/game/gamemodes/dynamic/antag_rulesets.dm
Its supposed to cost 30 not 120
oversight bad
<hr>
<hr>
NPFC
=> Fix cult dynamic cost

docs/references/autodoc.md
The DM reference docs use the terms "type", "object", and "datum" interchangeably, but "type" seems more correct to me, here.
- All occurrences of "class" have been replaced with "type".
- All occurrences of "function" have been replaced with "proc".
- Two typos have been fixed.
<hr>
<hr>
=> Standardizes vocabulary in autodoc reference docs

code/modules/client/preference/link_processing.dm
Hotfix for https://github.com/ParadiseSS13/Paradise/issues/28307 caused by https://github.com/ParadiseSS13/Paradise/pull/27359
Oversight on how datums work.
Changed to slime species, changed the sub type, changed species. Worked
<hr>
<hr>
:cl:
fix: Fixed subspecies causing other character slots to be changed
/:cl:
=> Fixes subspecies corrupting other character save slots

_maps/map_files/stations/deltastation.dmm, tools/maplint/lints/multiple_kirby_plants.yml
Removes a plant that on the same tile as another in engineering.
Adds a maplint to prevent this in the future
Having things stacked on top of each other is tacky and breaks immersion
Server booted, plant is there
<hr>
<hr>
:cl:
fix: Removed duplicate large plants on deltastation
/:cl:
=> Removes a Plant Sitting on top of another and adds a Maplint for It

code/__HELPERS/iconprocs.dm, code/modules/client/preference/character.dm, code/modules/client/preference/link_processing.dm, code/modules/client/preference/preferences.dm, code/modules/mob/living/carbon/human/human_update_icons.dm, code/modules/mob/living/carbon/human/species/_species.dm, code/modules/mob/living/carbon/human/species/machine.dm, code/modules/mob/living/carbon/human/species/slimepeople.dm
Fixes alot of issues with the slime / IPC imitation PR. Also puts a small clamp on the body color for slime people so that they are less likely to become the literal sun.
Fixes: https://github.com/ParadiseSS13/Paradise/issues/28333
Fixes: https://github.com/ParadiseSS13/Paradise/issues/28325
Fixes: https://github.com/ParadiseSS13/Paradise/issues/28307
Fixes are good.
Reloaded the game multiple times with a database active, changed character species, subtypes, and whatnot in the character creator. Changed species in game without an issue.
Machine (Unathi) 
Skintone:
<hr>
<hr>
:cl:
tweak: Tweaked max luminance on slimes imitating another species, hopefully resulting in less eye sores.
fix: Fixed skin tones
fix: Fixed subtypes causing character saves to break
fix: Fixed funky character mash …
=> Large patch to Slime/IPC PR - Character Creator + General Imitation Fixes

_maps/map_files/stations/emeraldstation.dmm
Removes a charger that i put under a door by mistake 
Fixes #28257
see above 
<hr>
<hr>
:cl:
fix: Removed a stray charger in the armory on the Diagoras
/:cl:
=> Removes a stray charger on the Diagoras armory

code/modules/hydroponics/grown/flowers.dm
Fixes reagents_add list() part of the spaceman's trumpet code, cuz it was a datum reference instead of reagent id
It's just a minor fix, at least there won't be an "UNKNOWN production 10%" in the DNA manipulator.
Before:
After:
Changed code, spawned trumpet seed and flower, checked gene in DNA manipulator
<hr>
<hr>
:cl:
fix: Spaceman's trumpet reagent
/:cl:
=> Fix spaceman's trumpet reagents_add list

_maps/map_files/stations/cerestation.dmm
Removes an extra floating intercom from the Farragus HOP office.
Mapping oversight removal.
<hr>
<hr>
:cl:
del: Removed a redundant, floating intercom from the HOP office on Farragus.
/:cl:
=> Removes a Floating Intercom From Farragus HOP Office

code/modules/mob/living/simple_animal/hostile/carp.dm
gives carp the swarming component
Carps can now stack up, if you try to bait fight them one at a time.
I crave violence.
spawned fishe
they swarmed
<hr>
<hr>
insert voice clip of rufus / silver saying yes here
:cl:
tweak: Space carp can swarm
/:cl:
=> carps can swarm now

code/game/machinery/clonescanner.dm
Fixes an exploit
Exploit bad
<hr>
<hr>
=> [S] Exploit fix

_maps/map_files/stations/metastation.dmm
This fixes a non-reinforced wall on Metastation, that would allow easy access to the bridge through the small maint room next to the NCT office.
People shouldn't have unintended easy access to a restricted area.
Before: 
After: 
Booted up a server, saw the wall was reinforced. All according to keikaku
<hr>
<hr>
:cl:
Tweak: Replaces a normal wall with a reinforced wall
/:cl:
=> Fixes a non-reinforced wall on Meta

code/modules/mob/living/simple_animal/hostile/carp.dm
Carp are not dense, required to make swarming work well
Carp block non carp that are dense from moving through them (so same as before)
Carp will always get hit by a laser despite being non dense
Swarming working right is actually good. I forgot that since all the carp spawned on a tile it worked fine, just not naturally after
look in coding chat enjoy my examples (durand was before making projectiles always hit)
see discord
<hr>
<hr>
:cl:
fix: Carp swarm. For real this time.
/:cl:
=> Fix carp not swarming right

code/__DEFINES/is_helpers.dm, code/datums/spells/bloodcrawl.dm, code/game/gamemodes/miniantags/demons/shadow_demon/shadow_demon.dm
This PR prevents shadow demon from using shadow crawl while shooting shadow grapple
If you shoot shadow grapple, face the consequences, dont hide in shadows.
Compiled, tested as shadow demon, tested as a human with shadow heart.
<hr>
<hr>
This change was approved by Silverplate
:cl:
tweak: You can no longer use shadow crawl while shooting shadow grapple.
/:cl:
=> [s] Shadow demon Shadow Crawl abuse fix

code/modules/mob/living/simple_animal/hostile/terror_spiders/terror_spiders.dm
Makes it so you cant grab terrors, a pr 4 years ago made it so you couldn't /pull/ terrors, but forgot that you could grab them to get the same effect.
Grabbing and throwing something thats larger and heavier than you is quite silly. 
The issue that this poses was attempted to be fixed in #16325 but grabs were forgotten about.
Fixes #18876
Tried to grab terror spiders, couldn't
<hr>
<hr>
:cl:
tweak: You can no longer grab terror spiders
/:cl:
=> You can no longer grab terrors

code/_onclick/hud/action_button.dm, code/datums/ai/ai_controller.dm, code/datums/components/scope.dm, code/game/objects/items/weapons/melee/melee_misc.dm, code/modules/clothing/suits/wiz_robe.dm, code/modules/mod/mod_actions.dm, code/modules/mod/mod_types.dm, code/modules/mod/mod_ui.dm, code/modules/mod/modules/_modules.dm, code/modules/mod/modules/modules_antag.dm, code/modules/projectiles/guns/energy/special_eguns.dm, tools/ci/check_grep2.py
Fixes misuses of `/datum/proc/UID()`, which does not take arguments, and adds a CI lint for non-empty `UID()` calls. 
Prevents bugs and unintended behavior. It looks like a macro, so it doesn't surprise me that people get confused.
Confirmed pinned modsuit modules and mouse dropping works fine.
<hr>
- [x I confirm that I either do not require [pre-approval](https://github.com/ParadiseSS13/Paradise/blob/master/docs/CODE_OF_CONDUCT.md#types-of-changes-that-need-approval) for this PR, or I have obtained such approval and have included a screenshot to demonstrate this below.
<hr>
=> CI lint for UID() misuse

code/datums/spells/charge_up_bounce.dm
Adds functionality to bouncy spells to have a delayed bounce
Extra functionality neat + Heretic
Modified the lightning spell to have a 5 seconds delay between bounces
https://github.com/user-attachments/assets/88f30100-795c-435d-b772-b67477a4d931
See above
<hr>
<hr>
NPFC
=> Adds more functionality to bouncy charging spells

_maps/map_files/stations/metastation.dmm
Title. The airlock is already the same shape as the helper, so no player-facing changes.
Standardization and maintainability of airlocks.
Inspected and used the airlock.
<hr>
<hr>
=> Replaces Meta Station AI Sat Handcrafted Airlock With Airlock Helper

code/modules/hydroponics/biogenerator.dm
Fixes small mistake in biogenerator message when it's attacked with an item it cannot accept
It's a fix
<hr>
<hr>
:cl:
fix: Fixes improper biogenerator message
/:cl:
=> Fixing improper message for biogenerator interaction from PR #26257

docs/CONTRIBUTING.md
Grants me dictatorial powers over lesser beings.
Those who pay the tithe will be rewarded with swift merges.
Testing is for sick people, and I am healthy and strong.
<hr>
<hr>
=> Adds Chuga to maintainer list

tools/ci/lints.dm
Updates Opendream CI
Catch bugs better
See commits
<hr>
<hr>
NPFC
=> Updates Opendream CI

code/modules/buildmode/submodes/advanced.dm, code/modules/buildmode/submodes/area_edit.dm, code/modules/buildmode/submodes/atmos.dm, code/modules/buildmode/submodes/boom.dm, code/modules/buildmode/submodes/fill.dm, code/modules/buildmode/submodes/mapgen.dm, code/modules/buildmode/submodes/offer.dm, code/modules/buildmode/submodes/save.dm, code/modules/buildmode/submodes/say.dm, code/modules/buildmode/submodes/tilt.dm, code/modules/buildmode/submodes/variable_edit.dm
This is a small refactor of buildmode which mainly focuses on using tgui input elements.
Improved performance and usability.
Used various buildmode tools and checked for proper function.
<hr>
<hr>
NPFC
=> Touches up buildmode code

.github/workflows/ci.yml
Speeds up CI
Fast is good
N/A
We boutta find out
<hr>
<hr>
NPFC
=> Removes dotnet from non OD CI runs

code/datums/keybindings/emote_keybinds.dm, code/modules/mob/living/carbon/human/human_emote.dm
Adds the nymph emote *chirp to diona too.
It's a tiny bit of RP content that lets diona show off their composite nature.
If they're made of things that can chirp, they ought to be able to chirp.
*chirp is a pretty short and quiet emote, so I don't expect people to find it irritating.
Used the emote, checked that the emote was in the *help menu, tested the keybind settings to make sure the emote showed up there and the keybind worked.
Listened to the emote at minimum and maximum age to make sure it still sounded alright.
<hr>
<hr>
:cl:
soundadd: Diona can now chirp
/:cl:
=> Adds the *chirp emote from nymphs to Diona

_maps/map_files/stations/deltastation.dmm
Title
Allows the HOS to do their paperwork in many exciting colours and stamp it, as they can in other stations.
Inspected the papers.
<hr>
<hr>
:cl:
add: Adds a paper bin, HOS stamp, and multi-coloured pen to the Kerberos HOS office.
/:cl:
=> Adds a Paper Bin, HOS Stamp, and Multi-Colour Pen to the HOS Office of Kerberos.

_build_dependencies.sh, code/__DEFINES/_versions.dm, code/__DEFINES/rust_g.dm
Reverts ParadiseSS13/Paradise#28591
redis issues
=> Revert "[READY] RUSTG Update"

_maps/map_files/stations/metastation.dmm
Adds a turret controller to the Meta AI upload.
Fixing a mapping oversight.
Checked it was there, it was.
<hr>
<hr>
:cl:
fix: Fixed the AI upload on Meta not having a turret controller.
/:cl:
=> Fixes an Oopsie (re-adds missing upload turret controller on meta)

_maps/map_files/shuttles/emergency_lance.dmm, docs/mapping/requirements.md
Lance shuttle brig has the proper floor tiles, adds a shuttle area to mapping docs, mentioning that if you have a brig on a shuttle to use the proper floor tiles so it counts as containing.
Shuttles should work right
confirmed that it was the correct tiles
<hr>
<hr>
:cl:
fix: Lance shuttle brig now works properly
/:cl:
=> Lance shuttle brig / mapping documents

code/game/objects/items/tools/crowbar.dm, code/game/objects/items/tools/multitool.dm, code/game/objects/items/tools/screwdriver.dm, code/game/objects/items/tools/welder.dm, code/game/objects/items/tools/wirecutters.dm, code/game/objects/items/tools/wrench.dm, code/modules/clothing/gloves/colored_gloves.dm
Title. Updates a bunch of tool descriptions to better say what they do.
Description standardization, more detail, and descriptions which actually tell you what an object does.
- observed tools
- appreciated the knowledge
<hr>
<hr>
:cl:
tweak: Updates a bunch of tool lore
/:cl:
=> [LORE] Updates a bunch of tool lore

code/game/objects/effects/spawners/random/traders/trader_department_spawners.dm, code/game/objects/effects/spawners/random/traders/trader_organization_spawners.dm, code/game/objects/items/robot/ai_upgrades.dm, code/game/objects/items/weapons/storage/lockbox.dm, code/modules/awaymissions/mission_code/ruins/telecomns.dm
Fixes #28666 by moving to new attack chain
Makes them under a common parent as that makes sense / better for the future
Bugs bad
Comment parent good for future
new attack chain good
Smacked them on the AI
it worked
<hr>
<hr>
:cl:
fix: Fixed AI upgrades not working
/:cl:
=> moves ai upgrades to new attack chain, fixes bugs

code/modules/surgery/tending.dm
- Tending gets a surgery sound
Tending was missing a sound so I gave it one. It was one of the only surgery steps missing actual audio feedback. It does actually have sounds on TG and I don't think it's too egregious for it to have sounds here since it is a sound preference that can be adjusted and toggled. I've uploaded a video of me healing 50~ brute on a dummy so you can give it a listen.
https://github.com/user-attachments/assets/7a992619-f7c4-4549-b3a3-7adf1a284a0a
See video.
<hr>
<hr>
:cl:
soundadd: Tending now has surgery sounds.
/:cl:
=> Adds surgery sound for tending

code/_onclick/cyborg.dm
Fixes #28480 
Added missing ranged click handling
Fixes broken ranged interactions for borgs
I used a fire extinguisher from range.
<hr>
<hr>
:cl:
fix: Ranged cyborg clicks are now properly handled with the new attack chain
/:cl:
=> [Fix] Cyborg ranged clicks now work with the new attack chain

_maps/map_files/RandomRuins/LavaRuins/lavaland_surface_golem_ship.dmm
Adds no-lava markers to the area around the Free Golem ship.
Fixes: #28488
Being unable to leave your ship due to lava sucks and this helps give golems some breathing room
Booted up test server, spawned as golem, flew to the reserved space in space, and flew back to lavaland
<hr>
<hr>
:cl:
add: Add no-lava markers around the Free Golem ship
/:cl:
=> Adds No-Lava Mapper Helpers to the Free Golem Ship

code/game/gamemodes/miniantags/demons/shadow_demon/shadow_demon.dm
Fixes an oversight.
In-game verification.
=> [S] do a thing differently

code/game/turfs/simulated/floor/indestructible.dm
fixes something
tried to do the thing, couldn't
<hr>
=> [S] fixy evil

code/_globalvars/lists/maint_loot_tables.dm
Adds Nuke Core/Supermatter Sliver steal kits as a rare maint item.
Makes carrying/finding them in maint have plausible deniability. Makes it at least somewhat easier for newer players with this objective.
Spawned in, walked around maint to make sure they're not too common. Used SQDL to find thm all.
<hr>
<hr>
:cl:
tweak: Adds Nuke Core/Supermatter Sliver steal kits as a rare maint item
/:cl:
=> Adds Nuke Core/Supermatter Sliver steal kits as a rare maint item

.gitattributes
Reverts an unintended change with merge hook drivers for tgui
Reverts unintended change on repo.
<hr>
NPFC
=> Reverts an unintended change with merge hook drivers for tgui

docs/CONTRIBUTING.md
This PR adds me to the maintainers section of CONTRIBUTING.md.
People will know who to blame
<hr>
<hr>
NPFC
=> add warriorstar to maintainers

SQL/paradise_schema.sql, SQL/updates/64-65.sql, code/__DEFINES/misc_defines.dm, code/game/verbs/ooc.dm, code/modules/admin/sql_notes.dm, code/modules/admin/topic.dm, config/example/config.toml
Adds public notes. Old notes are grandfathered in as private notes. Upon creation of a new note, admins will be able to choose if its public or private. Admins can toggle notes created by ONLY THEM between private and public. Only you can see your own public notes.
Admins want it as an option. Its also helpful and healthy for the playerbase.
A lot of testing. Including setting up a DB. (ignore that I'm a headcoder and haven't done it yet.)
Player view.
Admin view.
Edit: The player-side is darkmode now!
<hr>
<hr>
:cl:
add: Public player notes. View these with the "Show My Notes" OOC verb.
=> Adds public notes

code/modules/power/apc/apc.dm
APC's now acknowledge you for breaking them
Yeah there we go
APC destroyed
<hr>
<hr>
:cl:
mission: accomplished
/:cl:
=> [AFD] APC's acknowledge you for breaking them

code/modules/food_and_drinks/food_base.dm
Fixes #28833
Food never sent the afterattack signal
it's art.
Applied tape to banana, stuck it to the wall.
<hr>
<hr>
:cl:
fix: Food can be taped to walls again.
/:cl:
=> [Fix] You can tape food to walls again

code/game/objects/items/weapons/melee/melee_misc.dm
Migrates spellblade to the new attack chain.
Fixes #28639, still have no idea how i broke everything up but it works just fine on new attack chain! So must be not my issue..... probably.
Attack chain migrations and fixes can't be bad.
Used spellblades to slash people, then booted up my local server and did the same. No issues except the fact they scream a lot.
<hr>
<hr>
:cl:
fix: Spellblade's enchantments now work properly.
/:cl:
=> Attack chain migration: spellblade; fixes spellblade enchantments

code/game/machinery/clonepod.dm
Fixes #28166
Adds a for loop that adds each robot limb to the organ list
theyre still there, just not accounted for.
Added limbs in cloner, looked at the list.
<hr>
<hr>
:cl:
fix: Clone pods will now list robot limbs.
/:cl:
=> Clonepod will now show robot limbs in storage

code/game/objects/items/weapons/melee/energy_melee_weapons.dm
Makes sure energy cutlass isn't getting random light color. The only light color cutlass might have is red. Other colors are for e/dswords.
Fix.
Before
After
<hr>
<hr>
:cl:
fix: Energy cutlass now always has a red light color.
/:cl:
=> Fixes energy cutlass randomising its color

_maps/map_files/stations/emeraldstation.dmm
Title.
Airlocks should be able to cycle.
Cycled the relevant airlocks.
<hr>
<hr>
:cl:
fix: Diagoras AI sat fore airlock now fully powered. Rear airlock now has enough air to cycle.
/:cl:
=> Fixes the rear diagoras AI sat airlock having no air and a basically empty air canister for cycling. Fixes front airlock being unpowered.

docs/CONTRIBUTING.md
This PR updates the headcoders listing in the devdocs.
Accurate information is important.
NPFC
=> update headcoders in CONTRIBUTING.md

code/datums/ruins/lavaland.dm
Fixes some grammar and finished an incomplete sentence
grammar good
compiles and places
<hr>
<hr>
:cl:
tweak: fixed some grammar
/:cl:
=> Eden ruin grammar fix

code/game/machinery/ai_resource.dm
Fixes AI nodes operating at vacuume.
Spacing a room should not get around the heating mechanics of AI nodes.
Spawned in, spaced a room, turned a node in that room on. It stopped running after a few seconds, as expected.
<hr>
<hr>
:cl:
fix: Fixed a pressure-related exploit with AI nodes
/:cl:
=> [s] AI Node Pressure Fix

code/modules/mob/living/silicon/ai/ai_programs.dm
Blackboxes a tally when a program is installed or upgraded
Stats.
Compiled. Didn't crash when I installed and upgraded a program.
<hr>
<hr>
:cl:
add: Added blackboxing for AI programs
/:cl:
=> Blackboxes AI Programs

code/modules/martial_arts/combos/krav_maga/leg_sweep.dm, code/modules/martial_arts/combos/krav_maga/lung_punch.dm, code/modules/martial_arts/combos/krav_maga/neck_chop.dm
Fixes cases when you could bypass parries or shields using krav-maga on help intent.
It also results in fact that you will not anymore perform these combos while on help intent, you must be on any other.
Fix. You shouldn't be able to leg sweep target that has a shield around it or is currently parrying.
Local server testing. Tried to perform all 3 combos against shielded person - failed to. Tried the same against a person that is currently performing a parry - failed to.
<hr>
<hr>
:cl:
tweak: You can't perform Krav maga combos on help intent anymore.
fix: Krav maga won't perform combos through parry/suit shielding anymore.
/:cl:
=> Fix krav maga gloves penetrate parry/shieldings

code/modules/hydroponics/beekeeping/beebox.dm
fixes #28929
The line moving the queen bee mob from the queen bee item to the apiary was removed. I added it back.
bugfix
- put queen bee in an apiary and took it out
<hr>
<hr>
:cl:
fix: Fixes not being able to remove queen bees from apiaries
/:cl:
=> Fixes not being able to remove queen bees from apiaries

_maps/map_files/stations/deltastation.dmm
Moves a singular light on DeltaStation Hydroponics. Fixes #28983
Lights don't go on airlocks, silly!
Load map, light moved
<hr>
<hr>
:cl:
tweak: Moves a singular light on DeltaStation Hydroponics
/:cl:
=> Moves a light on DeltaStation Hydroponics

_maps/map_files/stations/cerestation.dmm
Anchors the Farragus Cargo Desk bell.
Anchors the Farragus Gym bell.
Should be anchored.
Smashed that bell icon, liked and subscribed.
<hr>
<hr>
:cl:
fix: Farragus gym and cargo bells have been anchored.
/:cl:
=> Anchors a Pair of Bells

code/modules/power/gravitygenerator.dm
Fixes #29002 by always including the holodeck in the gravity generator's affected areas(those are still limited to the same Z level)
bugfix
- Turned grav gen on and off and the holodeck grav changed accordingly
<hr>
<hr>
:cl:
fix: Fixed holodeck not being affected by the gravity generator
/:cl:
=> Fix holodeck gravity

code/modules/mob/living/silicon/ai/ai_programs.dm
Fixes an exploit that gives 2 for 1 upgrades
Exploit bad
Compiled.
<hr>
<hr>
:cl:
fix: Fixed upgrade duplication bug
/:cl:
=> [s] Fixes Duplicating Upgrades on Multimarket Analyzer

code/game/machinery/tcomms/nttc.dm
Changes the Head of Personnel's radio color to lime, for service.
While the Head of Personnel is a second-in-command, I believe that they are more associated with the crew than the command department. They don't have any high value items, and they mostly tend to their line to assist the crew and check on the service department. Changing the radio color to lime will reflect this.
See above image
<hr>
<hr>
:cl:
tweak: Head of Personnel's radio color is now lime for service.
/:cl:
=> Makes the HoP's Job Color Lime

code/modules/admin/verbs/adminpm.dm
Adds message length limits to PMs from non-admins. The maximum length for non-admins (mentors, players, devs) is now 2048 characters.
Prevents this. 
Admin PM length
Non-Admin PM length
PMed a player as an admin and an admin as a player.
<hr>
<hr>
:cl:
fix: PMs no longer have unlimited length.
/:cl:
=> [s] Adds message length limits.

_maps/map_files/test_tiny/test_tiny.dmm, code/game/objects/items/weapons/cigs.dm
Migrates cigarettes, cigars, pipes, the holo cigar, and rolling paper to the new attack chain.
No player-facing changes.
Attack chain migration good.
Spawned in test_tiny.
lit cigarettes, cigars, and pipes with various lighting tools.
Stamped out lit cigarettes and cigars, extinguished pipes.
Slipped cigarettes into a skrell's mouth. Slipped one into my mouth. Lit the cig in my mouth and used it to light the skrell's cig.
Stuffed dry tobacco into a pipe. Made the pipe full, couldn't stuff more.
Dipped cigarettes and cigars and pipes in beakers of liquids.
Activated holo cigar in my hand, turned it off again.
<hr>
<hr>
=> Migrates Smokables to the New Attack Chain

code/datums/uplink_items/uplink_general.dm
Syndicate chainsaws are now no-discount items. They will always be worth their full price.
Discount chainsaw is bwoink bait. It's too powerful to be worth 30 TC. Pay the premium if you want to meat people.
Looked at some uplinks. Didn't see a discount chainsaw.
<hr>
<hr>
:cl:
tweak: The syndicate chainsaw cannot roll discounts.
/:cl:
=> The Syndicate Chainsaw Cannot be Discounted

code/modules/atmospherics/machinery/components/trinary_devices/filter.dm, code/modules/atmospherics/machinery/components/trinary_devices/mixer.dm
Filters and mixers now stop working when they have no power or are otherwise broken
fix
- Made a loop with filters and mixers, shut down the power and they stopped working
<hr>
<hr>
:cl:
fix: Filters and mixers now stop working when they have no power or are otherwise broken
/:cl:
=> Fixes filters and mixers operating with no power

code/modules/mob/living/silicon/ai/ai_programs.dm
Fixes a bug where you can't upgrade the enhanced tracking program.
Bugs bad.
Loaded. Was able to upgrade it.
<hr>
<hr>
:cl:
fix: Fixes being unable to upgrade the enhanced tracker program
/:cl:
=> AI Programs Polish: Fixes Enhanced Tracker Upgrading

_maps/map_files/RandomRuins/SpaceRuins/oldstation.dmm, _maps/map_files/RandomRuins/SpaceRuins/syndie_space_base.dmm, _maps/map_files/stations/boxstation.dmm, _maps/map_files/stations/cerestation.dmm, _maps/map_files/stations/deltastation.dmm, _maps/map_files/stations/emeraldstation.dmm, _maps/map_files/stations/metastation.dmm, code/_globalvars/lists/objects.dm, code/game/machinery/computer/atmos_controllers.dm, code/modules/atmospherics/machinery/components/unary_devices/vent_scrubber.dm
Replaces the outputs of atmos tanks with scrubbers
Also turns them off when you connect them so they don't scrub or inject things that they shouldn't/when they shouldn't
The atmos tanks are too slow to make good use of, and scrubbers will do a much better job of draining them.
- Went to all maps and tested that the consoles there control the correct injectors/scrubbers
<hr>
<hr>
:cl:
tweak: Replace atmos tank outputs with scrubbers
tweak: Turns off devices when connected to controller console
/:cl:
=> Replace atmos tank vents with scrubbers

code/modules/ruins/lavalandruin_code/sin_ruins.dm
Migrates and fixes the envy knife.
Item should function as expected.
Attacked a human with the envy knife and I took it's identity.
Attacked a chair, didn't become a chair.
<hr>
<hr>
:cl:
fix: Envy knife can imitate people.
/:cl:
=> migrates and fixes envy knife

code/modules/mob/living/silicon/ai/ai_programs.dm
Can no longer overheal mechs with repair nanites.
Balance good. Bugs bad.
Spawned mech. Used repair nanites. Did not overheal it.
<hr>
<hr>
:cl:
fix: Fixed repair nanites overhealing mechs
/:cl:
=> [s] AI Program Polish: Fixes mecha overheal

code/modules/clothing/suits/bio.dm
Halves the slowdown of Bio-suits (1 > 0.45)
With the virology rework coming, viral outbreaks will have containment of their spread be harder. Making the Bio-suits in medical storage less hindering will help medical staff stay safe when treating patients while remaining mobile. In it's current state bio-suits are slower than radiation suits despite the later having lead in them making them unappealing. 
Opened branch in locally hosted session, spawned in, tested speed of bio-suits
<hr>
<hr>
:cl:
Tweak: Slowdown value of bio-suit changed from 1 to 0.45.
/:cl:
=> Bio-suit slowdown reduction

code/game/objects/items/weapons/storage/firstaid.dm
Tweaks tactical first aid kit:
It's no more a reskin of smuggler's satchel (can't hold normal-sized items [since](https://github.com/ParadiseSS13/Paradise/pull/20379) there is no combat defib inside)
It now has an advanced health analyzer so you can check your teammates' (or your own) health and help 'em when they are in trouble!
First aid kit being able to hold normal-sized items is obviously an oversight since combat defib got removed
Even a regular first aid kit has a health analyzer inside, so should this one - makes it much easier to understand what's the issue with your mates
Compiled, bought one from uplink - it had an analyzer and couldn't hold my egun
<hr>
<hr>
:cl:
tweak: Tactical first aid kit can't anymore hold normal-sized items.
tweak: Tactical first aid kit now comes …
=> Tweak tactical first aid kit

SQL/paradise_schema.sql, SQL/updates/66-67.sql, code/__DEFINES/misc_defines.dm, config/example/config.toml
Adds the quirk column to the character data and updates the sql version to make the testing of #28388 simpler.
It lets us TM quirks.
Visual confirmation and it compiled since this is copy pasted from quirks
<hr>
<hr>
=> SQL changes for quirks

code/_globalvars/lists/reagents_lists.dm
Replaces non-existent `"irishcarbomb"` with actual `"dublindrop"` in reagent_lists.dm, dealing with the error below
Idk, just one less error on server booting
No error - no image
Booted local server up with my changes, the error didn't appear again
<hr>
<hr>
:cl:
fix: Replaced non-existent "irishcarbomb" with actual "dublindrop" in reagents lists, dealing with error on server bootup.
/:cl:
=> Reagent Lists Fix

code/modules/projectiles/projectile/reusable.dm
~fixes #28895~
Changes the damage type of riot darts and disables nodamage so it does the damage calculations
riot darts dont stand a chance vs the Omnissiah
Magdumped a borg with a c20r and riot darts, it did not take stamina damage.
Shot a human, it took stamina damage.
<hr>
<hr>
:cl:
tweak: Borgs no longer take stamina damage from riot darts
/:cl:
=> [Tweak] borgs won't take stamina damage from riot darts

code/modules/reagents/reagent_containers/borghydro.dm
Refactors its code a bit:
Deletes unused vars
Deletes unused `/basic` subtype
Fixed issue that hypo was never able to subtract cell charge on refill proc
Hypo now may transfer from 1 to 30 units per use instead of static 5
Syndie hypo now actually refills each tick (i feel like "no time to recharge" comment says that it should has no delay to recharge it. point me out if i'm wrong)
Each reagent is now synthesized separately - you may inject 50 salbu, 50 salglu, 50 mani etc. before going onto refill.
Using a hypo now applies a click cooldown
Added hypo sound when used (only for on-station medical borgs that aren't emagged)
Moves code around so it's easier to read - subtypes of the parent type are at the bottom now
Working code is good
Making cyborg's hypo more like a regular one is good as …
=> Update borg hypospray

code/modules/mob/living/carbon/human/human_mob.dm
fixes malf hud working on the main server, whereas local testing it would work.
fixes good, the feature should work now
set someone's status. not that local testing mattered.
:cl:
fix: Fixed MALF hud not working on main
/:cl:
=> Fixes malf hud on PROD

code/__HELPERS/unsorted.dm
This PR removes eight unused procs from from unsorted.dm.
Less unused code good. Will help when trying to refactor this 2,000 line file of random crap into smaller pieces.
Compiled.
NPFC
=> delete several unused misc procs

code/modules/cooking/autochef/autochef.dm
Autochef will no longer acknowledge abstract items as something you can cook. Fixes #29256
Cooking a slap isn't possible.
Made an autochef, clicked on it with a slapper. It beat the machine. Clicked on it with other abstract items, they hit the machine too.
:cl:
fix: Autochef no longer acknowledges abstract items.
/:cl:
=> Make autochef ignore abstract items

_maps/map_files/stations/emeraldstation.dmm
Title. The rest of the equipment needed to make a singularity can be found there already.
If the Diagoras engineering crew decide to break out the singularity that comes with their station, they ought to be able to tell how much energy is inside it so they don't accidentally destroy the station/let the singularity fizzle out.
:cl:
add: Added a singularity monitor to the Diagoras secure storage.
=> Adds a Singularity Monitor Circuit to Diagoras Secure Storage

_maps/map_files/stations/deltastation.dmm
Title.
Now that a singularity spawns in secure tech storage, it's probably a good idea to give the engineers the tools they need to actually manage the state of the singularity correctly instead of running off vibes.
:cl:
add: Added a singularity monitor to Delta engineering.
/:cl:
=> Installs a Singularity Monitor to Delta Engineering

code/modules/mob/living/carbon/carbon_update_status.dm
awake to dead
trust me
Things worked properly
:cl:
fix: Stamina should be more consistant
/:cl:
=> [s] fixes something

code/game/machinery/teleporter.dm
Fixes effects being teleported by permanent teleporters.
resolve #29367 
They should not be. Bad things happen when they can be.
Blood crawled through a tile with a permanent teleporter.
Did not teleport.
:cl:
fix: Permanent teleporters no longer can teleport effects.
/:cl:
=> fix permament teleporters with effects

_maps/map_files/stations/metastation.dmm
adds cameras everywhere around cerebron arrivals and library
AI having zero sight there is bad
loaded in as AI to check new coverage
:cl:
add: Added missing cameras to cerebron arrivals
/:cl:
=> Adds missing cameras to cerebron arrivals

code/datums/diseases/_disease.dm, code/modules/awaymissions/mob_spawn.dm
Non infectious zombies / viruses made non infectious can no longer be transmited by bloodNon infectious zombies / viruses made non infectious can no longer be transmited by blood
You know why after last round
killed zombie (non infectious)
stabbed self with needle
did not get infected.
:cl:
fix: Non infectious zombies / viruses made non infectious can no longer be transmited by blood
/:cl:
=> [s] Non infectious zombies / viruses made non infectious can no longer be transmited by blood

code/modules/clothing/masks/gasmask.dm
Looks good
Before
After
:cl:
tweak: Swat masks now block your hair.
/:cl:
=> Swat mask now blocks hair

docs/CODE_OF_CONDUCT.md
Updates the repo code of conduct to clarify our position on genAI.
We're not having slop litter the PR and issue lists.
N/A - Its a markdown file
Pre approved by HCs
Nothing changed ingame.
=> Code of Conduct update - the anti slop directive

code/modules/telesci/bscrystal.dm
Fixes spelling and Britishisms 
It's not bluespece, init
Reading
:cl:
spellcheck: Fixed typos and Britishisms 
/:cl:
=> Minor spell fixings/removal of Britishism in bscrystal.dm

code/modules/clothing/spacesuits/plasmamen.dm, code/modules/clothing/under/jobs/plasmamen/antags.dm
Fixes a typo I made
oops
Removes a typo
:cl:
spellcheck: Fixes a typo with the CC envirosuit
/:cl:
=> Fixes a typo in the CC envirosuit

code/modules/reagents/chemistry/reagents/drugs.dm
Minor spelling fixes and removes a Britishism in drugs.dm
I can't get high if my immersion is broken
Read it
:cl:
spellcheck: Fixed typos and Britishisms in drugs.dm
/:cl:
=> Spelling fixes/Britishims removed in drugs.dm

code/modules/hydroponics/grown/ambrosia.dm
Fixes #28978 by standardizing the ambrosiagaia species name
Brings ambrosia gaia in-line with other species names, ensuring it doesn't stick out to layers
:cl: AmityBlamity
fix: Changed ambrosia_gaia to ambrosiagaia to standardize with other plant names
/:cl:
=> Standardized plant names

code/modules/economy/economy_admin.dm
Allows for negative payroll modification
bugfix
it compiles
NPFC
=> Allows for negative payroll modification

code/modules/reagents/chemistry/recipes/drinks_reactions.dm
Changes the recipe for Dublin Drop from 
`1 part ale, 1 part irish cream` to `1 part stout, 1 part irish cream, 1 part whiskey`.
Increased resulting quantity to 3 because of the extra input.
Any civilized bartender would rightfully beat you with a hammer if you made a dublin drop using the old recipe.
Spawned as a bartender.
Made Dublin Drop.
:cl:
fix: Dublin Drop now uses 1 part stout, 1 part irish cream, 1 part whiskey.
/:cl:
=> Fixes Incorrect Dublin Drop Recipe

code/game/objects/items/weapons/cash.dm
Sets force and throwforce for cash to 0, cuz it shouldn't have any, it's just a pile of papers lol
No accidental ATM vandalization
nah...
Works fine
:cl:
tweak: Throwing cash deals no damage to target.
/:cl:
=> Harmful Cash No More

code/modules/mob/living/simple_animal/hostile/angel_statue.dm
Fixes #27883.
Being viewed by an AI does not stop statues due to their ability to see literally everything.
The previous behaviour was kind of BS, not going to lie.
Spawned an angel statue.
Spawned and possessed a skrell. No movement.
Spawned and possessed a borg. No movement.
Spawned and possessed an AI core. Angel moved.
:cl:
fix: borg vision can freeze angel statues.
/:cl:
=> Angel Statues Cannot Move When Borgs View Them

code/modules/mob/mob_holder.dm
Changes `/obj/item/holder/mouse` to have a weight class of `WEIGHT_CLASS_SMALL`. This allows picked up mice to fit in containers that can hold small items, like pockets and boxes. Since mice are probably smaller than the average wrench, and a wrench can fit in a box, it's only logical that mice should be able to fit in a box as well. 
Mouse -> box -> mouse in a box.
It works
:cl: chuga
tweak: Mice can now fit in containers that hold small-sized items.
/:cl:
=> Shrinks mice

code/modules/clothing/shoes/magboots.dm
Fixes a couple of typos in magboots.dm
The magboot's payload is exposed. I can use the spelling winch to trigger a controlled explosion
With my eyes
:cl:
spellcheck: Fixed a couple of typos in magboots.dm
/:cl:
=> Typo fixes to magboots.dm

code/datums/spells/alien_spells/corrosive_acid_spit.dm, code/datums/spells/alien_spells/lay_alien_eggs.dm, code/datums/spells/alien_spells/neurotoxin_spit.dm, code/datums/spells/alien_spells/plasma_weeds.dm, code/datums/spells/alien_spells/queen_evolve.dm, code/datums/spells/alien_spells/transfer_plasma.dm
Fixes several typos and grammatical errors in alien spells
Facehugging never felt so good
I wrote this
:cl:
spellcheck: Fixed several typos and grammar fixes
/:cl:
=> Typo and grammar fixes for alien spells

code/datums/uplink_items/uplink_general.dm
More spelling/grammar fixes - I'm so sorry about all the PRs
Gimme an I
Gimme an M
Gimme an M
Gimme an E
Gimme an RSION
Spelling
:cl:
spellcheck: Fixed spelling/grammar typos in uplink_general.dm
/:cl:
=> A round of spelling/grammar fixes for uplink_general.dm

code/datums/uplink_items/uplink_traitor.dm
Fixes a minor spelling mistake
IMMERSION
I double checked the spelling
:cl: 
spellcheck: Fixed typo in uplink_traitor.dm
/:cl:
=> Minor spelling mistake fix in uplink_traitor.dm (Sydnicate to Syndicate)

code/game/gamemodes/wizard/spellbook.dm
Adds logging when wizards cast summon ghost and silence ghosts in their spellbooks
Spells being logged is good for administration purposes
Ignore the first Deadchat is disabled message
Tested on test server
NPFC
=> Add logging to Summon Ghosts and Silence Ghosts

code/datums/uplink_items/uplink_nuclear.dm, code/datums/uplink_items/uplink_traitor.dm
Fixes a variety of minor spelling and grammar mistakes present in Syndicate item descriptions. Also removes the Britishisms.
The British cannot be permitted to exist
Also, IMMERSION
Spelling? Checked
:cl:
spellcheck: Fixed typos, grammar, and Britishisms in uplink_traitor.dm
/:cl:
=> Spelling and grammar fixes for Syndicate item descriptions

code/modules/mod/mod_types.dm
Modsuits now use proper icon state when placed in SDMM
Modsuits set new icon state on initialize, so these icon states won't affect anything that is going to initialize
removes 2 repeated lines for vendor mining mod - it's already decalred on parent type
`empty` subtype isn't used by anything.. so i keep it as an error, i think it's something Qwerty didn't finish to port?
qol for mappers
Compiles
NPFC
=> No more ERROR modsuits in SDMM

code/game/objects/items/devices/scanners.dm
Removes throw damage from:
- Health Analyzer
- Machine Analyzer
- Gas Analyzer (already 0, the setting was redundant)
- Reagent Scanner
- Slime Scanner (already 0, the setting was redundant)
- Handheld Body Scanner
These are small items that sometimes get thrown to pass around. They're too small to really do any damage and it's just annoying.
Threw all of these items at a skrell. No skrell were harmed in the making of this PR.
:cl:
tweak: The Health Analyzer, Machine Analyzer, Reagent Scanner, Advanced Reagent Scanner, and Handheld Body Scanner do no throw damage.
/:cl:
=> Handheld Scanners Do No Throw Damage

code/__DEFINES/misc_defines.dm, code/game/objects/items/robot/robot_upgrades.dm, code/modules/cooking/machines/deep_fryer.dm, code/modules/cooking/machines/grill.dm, code/modules/cooking/machines/ice_cream_mixer.dm, code/modules/cooking/machines/oven.dm, code/modules/cooking/machines/stovetop.dm, code/modules/research/research.dm, code/modules/surgery/organs/organ_extractor.dm
- Changed some `TECH_*` defines to be consistent with `/datum/tech/` IDs, and redefined `/datum/tech` IDs to be based on `TECH_*` defines. These changes shouldn't affect current consumers (xenobiology) to the best of my knowledge
- Fixed references to non-existent technologies
- For `/obj/item`s that use a list instead of a semicolon-delimited string for `origin_tech`, converted the former to the latter
Less bugs
- Spawned a science goggle, toggled research analyzer, and examined a deep fryer circuit board and an executive service upgrade to confirm technology levels were correct
:cl: cdui
fix: "Executive service upgrade" now correctly registers with level 2 in biological technology
fix: "Alien organ extractor" now correctly registers with level 4 in alien technologies
fix: the circuit …
=> Fix technology levels of some items

code/game/objects/items/robot/cyborg_gripper.dm
Using item in a gripper now applies a click CD
Prevents players from being able to create multiple things with 1 item that requires do_after by clicking something really fast (like creating multiple light fixture frame structures by spamming LMB with only one in a gripper)
cooldowns should be respected + mini exploit fix
Crafted light fixture frame, picked it up with a gripper, tried to spam LMB onto a wall while light fixture was in my gripper, was only able to place it once. Click cooldown is also applied every time i click something with a gripper
:cl:
tweak: Using item in cyborg's gripper now applies click cooldown.
fix: Fixed exploit when you could duplicate items by spamming LMB with some item being located in cyborg's gripper.
/:cl:
=> [s] Grippers don't duplicate items

code/controllers/subsystem/non_firing/SSpathfinder.dm
Same as #29712 
https://github.com/OpenDreamProject/OpenDream/pull/2307
another one was added :agony:
=> Another `SoftReservedKeyword`

code/modules/clothing/head/helmet.dm, code/modules/clothing/suits/armor_suits.dm
title
export-grade armor is not fully fireproof 
gamma-grade armor should be spaceproof and fireproof
donned the armor and walked in space
:cl:
tweak: Spaceproofed and Fireproofed Federation combat armor
/:cl:
=> Spaceproofs and Fireproofs Federation Combat Armor

tgui/packages/tgui/interfaces/AgentCard.tsx
Formats AgentCard.tsx
Failing CI is not good
tgui still builds fine and the bundle is the same
=> Fix tgui CI checks

code/game/jobs/job/supervisor.dm
fixes some grammar
good grammar is good
compiled
:cl:
fix: Fixed  some grammar with captaincy job skill
/:cl:
=> Captaincy job skill grammar fix

code/game/objects/items/devices/painter/painter.dm
Fixes tracking for the modular painter.
Admin investigations good.
Yes.
NPFC
=> [s]Modular painter fix.

code/game/gamemodes/vampire/vampire_chan.dm
Fixes vampire changling announce by making sure it is pointed to the correct subtype.
Accuracy... probably.
Compiles appropriately.
NPFC
=> Fixes vamp_chan.dm announce()

code/modules/admin/admin_verbs.dm
The proc already uses tgui, might as well streamline it and make it easier to use. It no longer has a "Use default prompt?" screen, it sends you directly to the text screen with the default text as the default. If you submit the default it will use the color red, otherwise you get to pick the color.
Less awkward tooling is better.
NPFC
=> tguifies SEND_ALERT

code/modules/mob/living/basic/hostile/hellhound.dm, paradise.dme
Stops certain types of hellhounds spawning when they shouldn't.
Bugs bad.
Compiled
:cl:
fix: Fixed an oversight that allowed some hellhound types to spawn that shouldn't from gold cores.
/:cl:
=> [s] Fixes certain types of hellhounds spawning from gold cores

code/game/objects/structures/grille.dm
Changes the description of the grille from "flimsy" to "robust".
Also adds mentions of its uses in windows and space debris protection.
#29797 buffed the health of grilles, but didn't update the description to reflect this.
The game should not lie to you.
:cl:
tweak: Changed the description of the grille.
/:cl:
=> Updates the Description of the Grille

code/game/objects/items/weapons/chemical_flamethrower/fire_effect.dm, code/modules/mob/living/carbon/alien/alien_base.dm, code/modules/mob/living/carbon/alien/alien_death.dm, code/modules/mob/living/simple_animal/friendly/diona_nymph.dm, code/modules/mob/living/simple_animal/friendly/farm_animals.dm, code/modules/mob/living/simple_animal/friendly/mouse.dm, code/modules/projectiles/guns/projectile/pistol.dm, code/modules/surgery/tools.dm
Fixes for #29996
Bad code ugly, good ci good
Compiles
NPFC
=> Fixes for duplicate procs

code/modules/tgui/modules/colour_matrix_tester.dm
Color matrix tester doesn't override previous color, aka remembers the previous color.
Better admin tooling
Changed some colors around on a mob, closed the panel, re-opened the panel and the colors were still the same.
NPFC
=> Color matrix tester doesn't override previous color

code/modules/mining/equipment/kinetic_crusher.dm
Fixes the KC's light not being extinguished
bug fix #29969
correctly extinguished when hit by a shadow hand 
:cl:
fix: Fixed the KC's light not being extinguished by umbral vampires/shadow demons
/:cl:
=> Fixes shadow hand not putting some lights out

code/modules/virology/virology_goals.dm
Fixes #30038
Less bug more good
- Sold virus samples for the specific viral sample request and for other requests and it only completed when it should have
:cl:
fix: Fixes the specific viral sample request getting completed erroneously 
/:cl:
=> Fixes virology goal completion check false positive

code/modules/surgery/organs/organ_internal.dm
Fixes organs being inedible on the first bite.
broken code bad
For some reason, github CI passed, but local CI failed, thats how i spotted this.
:cl:
fix: Fixes organs being inedible on the first bite
/:cl:
=> Fixes organs being inedible on the first bite

code/game/mecha/equipment/weapons/weapons.dm, code/modules/research/designs/mechfabricator_designs.dm
Adds a new module for combat mechs, the DWDL-04 Dropwall Launcher. It is a grenade launcher type weapon that carries a magazine of 4 dropwall deployers. The dropwalls deploy immediately once they reach the targeted turf, and function exactly like standard dropwall generators in that they will block projectiles from one direction while allowing projectiles from another to pass through. The dropwall is automatically aligned to have the mech be behind the wall when it launches, so the mech can deploy it then switch weapons to shoot through their new defensive position.
Diverse mech equipment is good. Mechs lack support tools, and this adds to their ability to function as a force multiplier if equipped and properly used.
Mounted dropwall launcher on mech. Fired dropwalls around me. Built a …
=> Adds DWDL-04 Dropwall Launcher for Mechs

code/modules/hydroponics/grown/mushrooms.dm
Changes the description of a mushroom. 
The last description needs to be destroyed, immediately.
It just works.™
:cl:
tweak: Tweaked a description for a mushroom.
/:cl:
=> Changes a description of a mushroom

code/datums/vv_core_topics.dm
This actually does what it needs to do, there was a check missed...
Makes the thing work correctly...
Yes.
NPFC
=> Fixes trialmins being able to change names... Part 2

code/game/jobs/job/job.dm
Cyborgs don't have an initial account in their mind so there should be a check to prevent this line from runtiming
No runtime
Joined round as a borg - no runtime
=> Fix runtime for cyborgs

code/modules/library/library_catalog.dm
Prevents imaginary books that IAA's/Secoffs can generate from showing up in the library catalogue
Fixes: #29863
Should not be able to create abstract objects in the real world at will.
Go into the library computer catalogue.
No imaginary books available.
:cl:
fix: Library computer can no longer print imaginary books
/:cl:
=> [FIX] Library computer can no longer print imaginary books

_maps/map_files/stations/metastation.dmm, code/game/objects/effects/spawners/random/misc_spawners.dm, code/game/objects/items/devices/scanners.dm, code/modules/mob/living/simple_animal/bot/mulebot.dm, code/modules/power/apc/apc.dm, code/modules/power/cell.dm, code/modules/projectiles/guns/energy/energy.dm, code/modules/projectiles/guns/energy/pulse.dm, code/modules/projectiles/guns/energy/special_eguns.dm, code/modules/projectiles/guns/energy_guns.dm
Removes the crap, upgraded, and upgraded+ cells.
Increases the charge of basic cells from 1000 to 2500 (the value of the old upgraded cell), and adds them to APCs in lieu of upgraded cells.
Replaces the cell of the mulebot and portable body scanner with a high cap cell, and the advanced portable body scanner with a super cell.
Gives the generic energy gun its own special gun cell so that energy weapons do not get buffed by the basic cell's higher capacity.
Adds descriptions to all the cells.
Removes internal gun cells from the stock parts spawner.
The crap cell is literally not used anywhere except a display on Meta. It's a leftover of laptops probably.
The upgraded cell is used exclusively for APCs.
Upgraded plus is used exclusively for body analyzers and the MULEbot.
The basic cell is …
=> Removes crap, upgraded, and upgaded+ cells. Buffs the capacity of basic cells.

code/modules/buildmode/submodes/say.dm
Tweaks buildmode say logging to have a jmp button and be easily readable
Logging good
NPFC
=> Better buildmode say logging

code/game/machinery/hologram.dm
When cyborgs click on holopad it runtimes, PR prevents it from runtiming
Less runtimes
Clicked holopad as a borg - no runtime
=> Fix runtime on holopad

code/__DEFINES/dye_keys.dm, code/_globalvars/lists/dye_registry.dm, code/modules/clothing/suits/misc_suits.dm
Bombers can now be dyed in washing machines:
Red: Security
Orange: Chem
Yellow: Engineering
Green: Botany
Blue: Atmos
Purple: Sci
Black: Coroner
White: Med
Syndicate stamp: Syndicate Bomber
More creativity for dying stuff (read: I want to wear the coroner jacket when not the coroner)
Bomber go in washing machine with black crayon, comes out looking like the coroner bomber
:cl:
add: Bombers can now be dyed in washing machines
/:cl:
=> Bombers can now be dyed in washing machines

.github/ISSUE_TEMPLATE/issue_report.yml
Fixes issue template for github
It needs to work. 
Tested on my fork
=> Actually fixes the issue template this time... probably

_maps/map_files/stations/deltastation.dmm
Removes the carp spawner outside the kerberos cargo shuttle
It's a pain in the ass to have carp spawn there, and it regularly causes problems. This fixes that pain point.
Compiled
:cl:
del: Removed carp spawner outside kerberos cargo shuttle
/:cl:
=> Purges carp spawner outside kerberos cargo shuttle

code/modules/client/preference/loadout/loadout_general.dm, code/modules/client/preference/loadout/loadout_hat.dm, code/modules/client/preference/loadout/loadout_suit.dm
Adds the fake wizard clothes and staff from the AutoDrobe to the loadout menu.
Drip accessibility.
Loaded in, took the loadout, loaded into the game, crumpled under the load of magical greatness.
:cl:
tweak: Added wizard hat, robes, and staff to loadout menu.
/:cl:
=> Add fake wizard outfit to loadout

code/game/objects/items/weapons/storage/belt.dm, code/modules/mob/language.dm
Title. Almost every language in the game has had its description reworded.
Many language descriptions do not convey enough information or read poorly. Adding more information and wording things nicely is good.
Spawned. Read descriptions.
:cl:
tweak: Most languages have had their descriptions reworded.
/:cl:
=> Reworks (almost) every language description

code/modules/hydroponics/grown/tobacco.dm
Increases basic tobacco nicotine content from 6% to 60%.
Increases space tobacco nicotine content from 16% to 80%
Increases plant matter content of both tobaccos from 5% to 10%
Tobacco is really bad at its singlular job of being a leaf you grow to smoke. At 100 potency a single tobacco leaf will contain 3 units. If you roll a cigarette with this leaf you will smoke it for just a few seconds. This PR will fix this.
Grew some tobacco. Dried it. Rolled it into a cig. It lasted for more than 3 seconds.
:cl:
tweak: Tobacco contains 60% nicotine and 10% plant matter.
tweak: Space Tobacco contains 80% nicotine and 10% plant matter.
/:cl:
=> Buffs Tobacco

code/modules/antagonists/changeling/powers/swap_form.dm
Fixes some mishaps.
Why not?
None required.
Used ability.
:cl:
fix: Fixed an exploit.
/:cl:
=> [s] Fixes an exploit.

code/modules/client/preference/preferences.dm
Fixes #29597 
Being able to keybind shift(0-9) is good
Opened preferences menu, bound a key to shift+1, showed as Shift1, used it, worked
Did the same for ctrl+shift+1, alt+shift+1, ctrl+alt+shift+1
:cl:
fix: Preferences keybind now works with shift + number
/:cl:
=>  Fixes Preferences key binding problem Issue #29597

_maps/map_files/generic/centcomm.dmm
Fixes the shuttle area on the CC hardbaked shuttle to encompass the nose of the ship.
Re-adds the missing docking port that was obliterated after being pasted over (I hate how the pre-spawned shuttle works).
It broke the pre-spawned shuttle.
Started a game, force called the shuttle, rode it between CC and the station and back. It actially arrived, the windshield didn't detach at any point.
:cl:
fix: Reattaches the shuttle's windshield to the rest of the shuttle.
/:cl:
=> Fixes Broken Shuttle
