ParadiseSS13/Paradise

code/modules/telesci/rcs.dm

fixes https://github.com/ParadiseSS13/Paradise/issues/25647
selecting unknown on RCS no longer selected centcom turfs and no longer fails to teleport
bugs bad
compiled, teleported
:cl:
fix: Emagged RCS no longer fails to teleport crates when selecting Unknown option.
/:cl:

Fixing emagged RCS not teleporting crates

---

code/game/machinery/tcomms/relay.dm

This PR fixes the Lavaland tcomms relay to be properly registered to the core at roundstart. An APC's Initialize, as of #25642, is what links it to its powernet, and since the effective roundstart behavior for relays is to tell the core to refresh its z-levels after a power change, if that powernet doesn't exist, the core will think the relay doesn't have power. Since relays have a LateInitialize anyway, we do another power_change there to reflect if a powernet became available between Initialize and LateInitialize. Fixes #25722.
Bug fix good.
Stepped through debugger at round initialize, confirmed with VV that core's available z-levels included Lavaland.
:cl:
fix: Lavaland's telecomms relay will now properly be linked to the station core at roundstart.
/:cl:

fix: ensure Lavaland tcomms is linked roundstart

---

code/__DEFINES/dcs/signals.dm
code/modules/assembly/assembly.dm
code/modules/assembly/signaler.dm
code/modules/assembly/voice.dm
code/modules/paperwork/desk_bell.dm

Allows you to attach signalers to desk bells. With a bell in hand, use a signaler on it.
If a signaler attached to a desk bell is on receive mode and is activated by a radio pulse, it'll ring the bell.
If a desk bell with a signaler attached is rung, it'll act like you just hit transmit on the radio.
Have fun!
This gives a fun way to add a little button for triggering signals. Maybe you could set something like this up with toxins, or give someone a big red button to push?
Either way, I think it'll make for some fun interactions.
https://github.com/ParadiseSS13/Paradise/assets/89928798/30c611bb-1b9e-4a72-b36b-632139136478
https://github.com/ParadiseSS13/Paradise/assets/89928798/6f761c8d-cdab-4a0b-a946-e07e6ee34686
Tried ringing bells and signaling bells
:cl:
add: Desk bells can now have …

Lets you attach signalers to desk bells

---

code/modules/crafting/tailoring.dm

Fixes #25514 
No reason for skills hud sunglasses to not be craftable unlike every other subtype.
Spawned in as a Captain, took apart my skill huds, put them back together, did the same with noir sunglasses.
:cl:
add: Added recipes for crafting and uncrafting skills hud sunglasses
/:cl:

Add recipes for crafting and uncrafting skills hud sunglasses

---

code/modules/events/event.dm
code/modules/events/tear.dm
code/modules/power/engines/singularity/singularity.dm

Makes the ss13 window no longer flash yellow to ghosts for the following events: anomaly, dimensional tear. 
Makes the ss13 window flash yellow to ghosts for singoloose.
These events already have loud voice announcements, which should cause you to alt tab if you're interested in them. No need for the window to also flash yellow. 
Singolooses are something ghosts are usually pretty interested in, so it can flash the window. 
It compiled.
:cl:
tweak: Reduced events highlighting the game window for ghosts. 
/:cl:

Reduce ghost window highlight spam, part 2

---

code/game/objects/items/salvage.dm

Fixes #25768. Gives the correct tech type for tech origin on lost nanotrasen research documents
Null research bad
Compiled. Threw a bunch of notes in the analyser. No more nulls.
:cl:
tweak: Tweaked a few things
/:cl:

Fixes Null origin tech on Lost Nanotrasen Research Documents

---

code/modules/ruins/ghost_bar.dm

Adds a null check during a loop that sometimes runtimes when a reference in `loadout_gear` doesn't exist in `GLOB.gear_datums`. This is due to the fact that character save loadouts are never purged of items that have been removed, which explains why no valid reference for these items exists in `GLOB.gear_datums` when this occurs.
Special shout out to the fact that indexing a list by `null` is a valid operation, which returns null. 
I was unable to use the ghost bar because of this bug.
I can't test this locally but hoo boy this baby compiles like you wouldn't believe.
:cl: Chuga
fix: Fixes a rare bug that caused you to be unable to spawn in the ghost bar.
/:cl:

Fixes a runtime in the ghost bar that causes your character to spawn without you

---

code/modules/hydroponics/grown/kudzu.dm

`mutations` contains typepaths. `for(var/datum/spacevine_mutation/SM in mutations)` won't actually iterate through anything, because DM is stupid. Adding `as anything` makes it work as expected.
Bugs bad. Except nians. Nians good.
Ehhhh... it's probably fine.
:cl:
fix: Kudzu mutations were not showing up in analyzer or being removed with chemicals
/:cl:

Fix kudzu mutations not showing up in analyzer or being removed with chemicals

---

code/modules/surgery/organs/augments_arms.dm

De-capitalize the abductor surgery and toolset implant
Abductor Toolset implant --> abductor toolset implant
Abductor Surgery Toolset implant --> abductor surgery toolset implant
Fits in with the rest of the implants, so it's not an eyesore if you print multiple at once
Also makes it so pointing at the implant looks like "points to the abductor toolset implant" instead of "points to Abductor Toolset implant"
launched a server, spawned both implant, no capital letters
NPFC

de-capitalize the abductor surgery and toolset implant

---

code/modules/mob/living/simple_animal/constructs.dm

Hrd-mde bubblegums constructs no longer passively die from the new heat of lavaland, or of ashstorms
Constructs should be a challenging part of a certain fight, and not automatically die
:cl:
fix: Hardmode constructs no longer die to lavalands heat or ash storms
/:cl:

Hardmode constructs no longer die to lavalands heat or ash storms

---

code/game/objects/effects/effect_system/effects_smoke.dm
code/game/objects/items/weapons/tanks/watertank.dm

#24993 expanded the arguments of `/datum/effect_system/smoke_spread/set_up()` to include `datum/reagents/chemicals`, but did not adjust the arguments of the subtype's override. This caused `blasting = TRUE` to get passed into the position where `chemicals` now sits and runtime when `chemicals.copy_to()` was invoked on the number `1` instead of a `datum/reagents`.
I have just added the new argument so that things don't get passed in the wrong order.
Bugs are the source of all evil. Especially moths.
Made sure it didn't runtime or do wacky things when an unnamed argument was passed to `..()`. 
:cl: Chuga
fix: Fixed atmos nanofrost extinguishers not frosting things properly.
/:cl:

Fixes a runtime with atmos nanofrost tanks and smoke_spread

---

code/datums/uplink_items/uplink_general.dm
code/datums/uplink_items/uplink_nuclear.dm

Makes ammunition in the uplink not able to be discounted.
Makes the syndicate knuckleduster able to be a discounted - this seems like a leftover from when it was 5TC.
Also does a major cleanup of the uplink code.
Getting a 3TC, single use discount on a pistol magazine is not a great use of one (or more) of your 3 discount slots, and is very unlikely to make you change your plans. Even if you're planning on buying the gun anyways, you would probably still prefer a more meaningful discount on a stronger item. 
Purchased a surplus crate to make sure I didn't mess up the code during my cleanup.
:cl:
tweak: Ammunition can no longer be discounted in the uplink.
tweak: Syndicate knuckleduster can now be discounted in the uplink.
/:cl:

Ammunition can no longer be discounted in the uplink

---

code/modules/mob/living/living_defense.dm
code/modules/mob/living/simple_animal/hostile/retaliate/combat_drone.dm

Makes the mobs not step when dodging, this seems to cause issues when they step and die, leaving a ghost undeletable projectile.
Ghost projectiles are bad.
Shot at mobs with this variable a whole bunch, no ghost projectiles were created.
:cl:
fix: Fixes advanced_bullet_dodge mobs sometimes leaving ghost projectiles on death
/:cl:

Fixes advanced_bullet_dodge mobs sometimes leaving ghost projectiles on death

---

code/game/machinery/syndicatebomb.dm

Raises the size of Syndie Bomb to maxcap, going from 3, 9, 17 size to 5, 10, 20.
Also removes the /large/ subtype of bomb, as it doesn't seem to be used anywhere, and the blast sizes would now be identical. I kept the subtypes of /large/ as a subtype of the regular bomb core now.
Hijack only and expensive to boot, there's not too much reason to use Syndicate Bombs when toxin bombs or even a little bit of effort with chemistry can yield maxcaps that are bigger and instantaneous (no loud beeping). Obviously there's the style factor, but that alone can't carry the beep-boom.
Sure, this will buff nukies with their ability to rapidly detonate the bomb, but it'll also probably result in them blowing themselves up more, so it balances out right?
It builds.
It launches.
It beeps.
It blows up. …

Buffs Syndicate Bomb Size

---

code/modules/mob/living/carbon/human/human_defense.dm
code/modules/power/cables/cable_coil.dm

If you try to welder missing limb on help intent on IPC, you will no longer attack them, same with cable coils
Attacking IPC unintentionally while trying to fix is not good.
Compiled, weldered an IPC, tried to fix missing limb.
:cl:
fix: You no longer attack an IPC on help intent with welder or cable coils in hands if they are missing your targeted limb.
/:cl:

You no longer hit IPC on help intent if they are missing a limb

---

code/modules/clothing/clothing.dm

I didn't think about borg hats when splitting the dmis
When equipping the beret, the icon_override value was set to the beret (or softcap) file
When equipping an item that used the basic hat item, the icon_override was never reset so it would continue attempting to look for the icons in the beret/softcap file.
This PR adds a line of code to set the icon_override value back to the OG file when equipping any hat that uses the basic item.
Fixes https://github.com/ParadiseSS13/Paradise/issues/25718
Bugs bad
Put beret on borg, swap it for other hats
Put beret/other hats on myself, swap species with magic mirror to ensure all items still work
:cl:
fix: Borg hats no longer go invisible after equipping a beret
/:cl:

Berets no longer make other hats invisible on borgs

---

code/_onclick/ai_onclick.dm
code/game/machinery/camera/tracking.dm

Speeds up the time it takes to track a target by clicking their name in chat or using the search verb by up to 1.5 seconds for AIs. This was done ~~trough a massive performance refactor~~ by greatly reducing a sleep() in the proc. Tracking someone now always takes 1.5 seconds.
Tracking someone this way has always felt slow and clunky, especially when someone calls you to open a door and you have to sit there for literal seconds, waiting for the camera to finally jump to them. 
You could also theoretically exploit the delay between clicking on someone's name in chat and the time it takes to get the error message to locate a person even when the target is off cameras.
Tracked a monkey.
:cl:
tweak: Changed AI tracking speed from a dynamic time to a static 1.5 seconds.
/:cl:

Changes AI tracking speed.

---

code/modules/mod/modules/modules_supply.dm

When crates are loaded, the clamp module's `on_select_use` will attempt to drop a crate from the `stored_crates` list at a target turf after a `do_after()` timer. This works great until the user has attempted to drop more crates than they have remaining. This leads to the situation where there is a single entry left in `stored_crates` and more than one `on_select_use()` calls awaiting the completion of the `do_after()`. After the most recent drop completes, `stored_crates` is now empty, and the remaining `on_select_use()` calls will attempt to `pop()` from the empty list, which leads to a runtime.
This adds a callback check to the `extra_check` parameter of the `do_after()` that will cancel the timer if `stored_crates` empties before it completes.
This doesn't really affect gameplay much …

Fixes a runtime with loader modsuits dropping crates

---

code/controllers/subsystem/SSthrowing.dm
code/game/objects/items.dm

Caps the number of thrown object impact sounds at 20/tick (400/second).
With the uncapped singularity pull that Qwerty is looking at, singularities end up throwing a lot of items around, and causing a ton of overtime in playsound as a result. This cuts that overtime by about 75%, and I, at least, can't hear a difference.
Spawned a singularity on the supermatter and gave it enough energy to start growing. Much clanging was heard as it wandered the station.
:cl:
sounddel: Thrown object impact sounds are now capped at 20/tick (400/second) for performance reasons. You are quite unlikely to notice this, but it's technically possible.
/:cl:

Caps the number of thrown object impact sounds at 20/tick (400/second).

---

_maps/map_files/generic/centcomm.dmm

Swaps the "asset protection shutters" access requirement to "109" (specops access) that only ert+ get.
Ert being able to goto the bar after a "hard" day at the job ~~mainly eorg~~ shouldn't be restricted, the worst ert can do by going out here is killing Alice, but they'll likely be vaporized by admins for doing so
See above
:cl:
tweak: ERT can go back to the bar in central command again.
/:cl:

Partually reverts "Increases security of CC armory" by giving ert back the ability to goto the bar.

---

code/__DEFINES/misc_defines.dm
code/modules/power/engines/singularity/singularity.dm

Adds performance to the singularity by using `block()` instead. Also slightly cleans up the code
This also implements #25643 , because:
1. The issue the comment describes is fixed
2. There are less performance issues to worry about now
It's literally free performance
https://github.com/ParadiseSS13/Paradise/assets/108773801/5bf0d596-fcad-4b5b-808d-bd168ac4a9dc
See above
:cl:
fix: The singularity should move a bit more smoothly now
fix: The singularity shouldn't sometimes randomly stop eating the station
/:cl:

Adds performance to the singularity

---

code/game/objects/effects/effect_system/effects_chem_smoke.dm
code/modules/hydroponics/plant_genes.dm

Nerfs gaseous decomposition to spread out it's chemicals over people, instead of fully duplicating chemicals
Gaseous decompositions has been the target of removal attempts, this should give it something that doesn't make it the most OP trait in combat.
Expected amount is somewhere around 1u of capsaicin and other things, which will most likely get metabolized out
See above
:cl:
tweak: Gaseous decomposition now spreads it's chemicals out instead of fully copying it to all mobs
/:cl:

Nerfs gaseous decomposition

---

code/modules/surgery/organs/organ_external.dm

Now to droplimb the game checks if limb got maximum damage instead of checking a type. It lead to bugs, such as:
* Using a lighter on your head gave immunity to de-heading
* Spacing yourself for a second made you un-delimbable
Delimbing should be possible with different limb damage. Crusted to almost dust limb with burn damage should be delimable with brute knife.
Got a knife with 500 force, it delimbs after exposing the target to vaccum of space
:cl:
fix: Now delimb should work if a limb has different damages
/:cl:

Droplimb fix

---

code/__HELPERS/lists.dm
code/controllers/subsystem/SSchat.dm
code/datums/chatmessage.dm
code/game/objects/effects/spawners/grouped_spawner.dm

Adds quite a few LAZYLIST macros. The primary change renames LAZYADDASSOC to LAZYADDASSOCLIST, which appends the value to the key-list. LAZYADDASSOC has been redefined to add the value directly to the key. Also copies over the extremely helpful documentation from the TG defines.
All previous uses of LAZYADDASSOC have been regex replaced to LAZYADDASSOCLIST. There is no change in functionality.
More LAZYLIST functionality is nice, and more importantly, the new documentation is more helpful than comments such as `// LAZYING PT 2: THE LAZENING` and the critically acclaimed `// Lazying Episode 3` .
Compiled, launched, walked around, spoke in chat. Nothing should change functionally, anyways.

Adds a few LAZYLIST macros and documentation

---

_maps/map_files/RandomRuins/SpaceRuins/abandoned_engi_sat.dmm
_maps/map_files/RandomRuins/SpaceRuins/abandonedzoo.dmm
_maps/map_files/RandomRuins/SpaceRuins/debris1.dmm
_maps/map_files/RandomRuins/SpaceRuins/deepstorage.dmm
_maps/map_files/RandomRuins/SpaceRuins/listeningpost.dmm
_maps/map_files/RandomRuins/SpaceRuins/meatpackers.dmm
_maps/map_files/RandomRuins/SpaceRuins/oldstation.dmm
_maps/map_files/RandomRuins/SpaceRuins/onehalf.dmm
_maps/map_files/RandomRuins/SpaceRuins/ussp.dmm

This PR removes any varedits of `pixel_x/y` or `tag` from any `/obj/structure/cable` across all maps.
The `pixel_x/y` variables were all a single pixel, which is weird and I can't think of, or find in the source history, a reason why you would do this. Many `tag` varedits were the empty string, but a handful were `90Curve`, which I assume is an artifact from some ancient way of dealing with power. Again, I can't find any use of this in code in the source history. It may predate 2010.
See MDB.
In progress.
:cl:
fix: A handful of cables across all maps have had 1-pixel visual offsets removed.
/:cl:

refactor: remove cable varedits and tags

---

code/modules/mob/living/brain/living_brain.dm

Fixes https://github.com/ParadiseSS13/Paradise/issues/25641
Brain can now understand itself, how cool.
Speaking with asterisks while everyone else can hear what you're saying is silly.
Compiled, became robotic brain, talked
:cl:
fix: Robobrain can now understand itself speech yay
/:cl:

brain can understand itself yay

---

code/game/gamemodes/miniantags/demons/shadow_demon/shadow_demon.dm
code/game/objects/structures/crates_lockers/closets.dm
code/modules/atmospherics/machinery/atmospherics.dm

- All atmos machinery, expecially cryo pods, can now be turned off by shadow demon/shadowling vampire
- Lockers with flashlights inside now can be turned off
- Shadow demon now have full screen night vision, without black corners.
Few bugfixes for shadow boi, who struggle from another bug abuse. Also black corners for lord of shadow are bad.
black corners i mentioned earlier
cryo pods now can be turned off
Locker interaction
write code, tested with presicion
:cl:
tweak: Shadow demon now have see_in_dark = 10, having night vision for entire screen.
fix: Cryo pods and flashlights in lockers now can be extinquished by shadow demon
/:cl:

Few bugfixes for Shadow Demon

---

code/datums/spells/construct_spells.dm
code/game/gamemodes/wizard/magic_tarot.dm
code/game/gamemodes/wizard/soulstone.dm

Tarot cards show which card was used / over someones head for 1.5 seconds, activating after half a second. You can't stop the effect, but better telegraphs it / gives perhaps a moment to disarm them before they teleport away!
Anyuse soulstone constructs produce anyuse soulstones.
the reverse fool card no longer removes biochips due to a bug
A better tell what happened with a tarot card is good.
Anyuse soulstone armies working again is good.
The reverse fool card not demindshielding officers or deleting traitor adrenals is good
Used cards, used reverse fool, etc
:cl:
tweak: Anyuse soulstone constructs can make anyuse soulstones (again?)
tweak: Tarot cards now show over the affected persons head when used for 1.5 seconds, activating after a 0.5 second delay.
fix: Reverse fool no longer …

tarot card improvements / fixes

---

code/modules/clothing/suits/armor_suits.dm

Fixes vox armor sprites so they actually use their sprite sheets.
Vox do not belong in regular armor, they look like denizens of an alternate dimension when you shove them into a human shaped set of knight armor.
BEFORE:
AFTER:
Loaded a local server after compiling, gave a vox breathless and played barbie for like 30 minutes.
:cl:
fix: Vox armor sprites.
/:cl:

[FIX] Fixes Vox Armor Sprites

---

code/modules/reagents/reagent_containers/iv_bag.dm

#25805 added a status trait removal on `iv_bag/proc/end_processing()` that causes each IV bag in a blood crate to runtime when `Destroy()` is called in the instance that they do not have an `injection_target`. This most commonly happens when ordered through the cargo shuttle
Runtime log spam bad.
Ordered a crate. Sent it back. Didn't runtime.

Fix blood pack crate runtimes when ordering through cargo shuttle

---

code/modules/mob/mob_misc_procs.dm

See title. The author of this line of code did not realize that `initial_account` might be null. Specifically, this triggers when an observer spawns in as a mob - usually golems. 
Runtime bad
It compiles

Fixes runtime during rename_character when initial_account is null

---

code/datums/components/sticky.dm

If an item with the sticky component was deleted without being attached to something, it would attempt to call `pick_up()` in the component `Destroy()` and runtime. This makes it not do that.
Runtime bad
Didn't runtime when qdel'd without an `attached_to` (lying on the ground)

Fixes runtime in sticky component Destroy()

---

code/modules/admin/verbs/deadsay.dm

Adds emoji support to admin dsay. Seems this was missed in #25012 
:cl:
add: Admins can now use emoji through the dsay verb.
/:cl:

Adds emoji to admin dsay

---

code/__DEFINES/sight.dm
code/game/atoms_movable.dm
code/game/gamemodes/cult/runes.dm
code/game/objects/effects/temporary_visuals/cult_visuals.dm
code/modules/mob/mob.dm

Invisible objects now have added safeguards to prevent tooltips and examine from people who can't see them. In theory, these shouldn't be necessary, but in practice...
The teleport portal effect is now invisible to the AI. They can, however, still see the red glow that it comes with.
AI shouldn't see what AI can't see.
I tested what I could, but since I can't reproduce the original behavior of being able to hover over a rune or examine it, I can't confirm that the fix worked.
:cl:
fix: Cult runes are better hidden from the AI now.
/:cl:

Hide runes from the AI better

---

_maps/map_files/RandomRuins/LavaRuins/lavaland_surface_seed_vault.dmm
_maps/map_files/RandomRuins/SpaceRuins/syndie_space_base.dmm

Replaces the plant bags given to syndie researchers and diona botanist ghost roles with portable seed extractors and also gives them hydroponic HUDs.
There is no reason for them not to get those items, which have become very important after the botany rework.
The items show up where they should
:cl:
add: Added hydroponics HUDs to the preserved terrarium and syndie research base hydroponics crates.
add: Added portable seed extractors to the preserved terrarium and syndie research base hydroponics crates.
del: Removed Plant bags from the preserved terrarium and syndie research base hydroponics crates.
/:cl:

Update syndie research base and preserved terrarium ghost roles hydroponic equipment

---

code/modules/antagonists/changeling/datum_changeling.dm

can_absorb_dna() now only outputs a warning if the changeling already has the target DNA, instead of returning False, allowing absorption (and as a side effect, the DNA sting) to be performed on targets they already have DNA of.
Changelings are highly incentivized to get their objective's DNA as soon as possible - you never know when they might decide to hug the SM or eat xenomicrobes, or do anything else that permanently removes their DNA from the round. Absorption does much more than just give you DNA, so it makes no sense to block the entire ability over it.
All relevant code already has safeties against getting duplicates of the same DNA, so it seems that the only thing the check in can_absorb_dna() did was prevent wasting chemicals on repeated DNA stings.
Spawned in a Skrell, stung …

Changelings can now absorb people they already have DNA of

---

code/game/objects/effects/effect_system/effects_chem_smoke.dm

Fixes a runtime that would happen if no mob was hit with plant chem smoke
Mostly affected mass spreading of acid and stuff
This should work
It compiled
:cl:
fix: Smoke now properly spreads when it doesn't hit a mob
/:cl:

Fixes empty gaseous decomposition plant procs runtiming

---

code/__DEFINES/hud_locations.dm
code/_onclick/hud/alert.dm
code/_onclick/hud/hud_datum.dm
code/_onclick/hud/human_hud.dm
code/_onclick/hud/screen_objects.dm
code/modules/antagonists/vampire/vamp_datum.dm
code/modules/mob/living/carbon/human/human_life.dm
code/modules/mob/living/carbon/human/species/_species.dm
code/modules/mob/living/carbon/human/species/machine.dm
code/modules/mob/mob_vars.dm

Original: https://github.com/ParadiseSS13/Paradise/pull/25555
Moves nutrition alert to HUD element near a healthdoll. That's basically it.
"Animation" of the alert will be discarded, but it's a minor inconvenience.
Since it's always an alert, why not make it just a hud element?
Also it's required for downstream to not mess up with ui order.
Tested with:
- Human
- Machine
- Vampire
- Abductor
:cl:
tweak: Moved Nutrition alert to Nutrition hud element near a healthdoll. It won't run around, when you have multiple alerts.
/:cl:

Converts Nutrition alert to hud element

---

code/modules/surgery/organs/vocal_cords.dm

AI eyes (and other camera eyes) no longer runtime when VOG is used near them, breaking VOG
Instead, if it is a normal camera eye, nothing happens.
If it is a ai camera eye that has the "hear from it's camera" function, it instead will be affected as well by the VOG! Fun for the whole family!
Runtimes bad.
Funny niche interactions good!
Used vog, no runtime, ai unaffected.
Used VOG with relay speach, AI affected.
:cl:
tweak: AI eyes with relay speech effects the AI with voice of god if the ai eye has relay speech
/:cl:

AI eyes with relay speech effects the AI with voice of god if the ai eye has relay speech

---

_maps/map_files/stations/cerestation.dmm

This PR removes all the carp spawners from the inner ring of Cere space, as well as the space bats spawner inside engineering secure storage.
While massive carp migrations destroying every space bridge is very funny, fixing them exhaustively is time-consuming and hinders traversing the station in a way that other maps aren't affected by. The space bats inside secure storage are a little mean and keeping them out of departments, confining them to maints, makes more sense.
See MDB.
:cl:
tweak: Farragus: Space carp will no longer spawn in the space between asteroids.
tweak: Farragus: Space bats will no longer spawn in Engineering Secure Storage.
/:cl:

cere: remove inner carp spawns and secure storage bats

---

code/modules/hydroponics/grown/towercap.dm
code/modules/hydroponics/plant_genes.dm

Doubles all visible percentages for botany plants
This way, if you reach 100% reagent capacity, you will still get all types of reagents added to your plant, in their ratios.
This has no balance changes.
On live, the percentages stop counting at 50%, and densified chemicals "unlocks" the full 100% of plant power. 
This is a dumb system.
This way we can have 100% plant power at roundstart, with a potential 200% total plant power with densified chems.
It compiled
:cl:
tweak: All visible plant reagent percentages have been doubled. Their reagent production stays the same
tweak: That reagent production is now 0.5u per % of reagents
/:cl:

Doubles all percentages for botany genes

---

code/game/objects/items/control_wand.dm

For janitors, using the janitor's keyring on the same airlock you last opened will open it in 5 seconds guaranteed
Get in room, clean room, get out. Also makes sense you can recognise the airlock you just opened and get the key back quickly.
Tested the feature on both airlocks and windoors.
:cl:
tweak: Opening an airlock with the janitor's keyring will be faster if it's the same airlock you last opened.
/:cl:

Increase opening speed of jani keyring on repeated airlock use

---

_maps/map_files/stations/boxstation.dmm
_maps/map_files/stations/cerestation.dmm
_maps/map_files/stations/deltastation.dmm
_maps/map_files/stations/metastation.dmm

Every station kitchen has enough points of sale to equip all serving counters.
Every station kitchen is now equipped with a wrench.
Removes a superfluous knife from Farragus' kitchen.
Removes a seemingly useless clipboard from Delta's kitchen.
Adds a table to Box's kitchen to hold the second point of sale.
Minor repositioning of some items.
Currently, 2 of the 4 maps don't have enough points of sale to equip both serving counters. This requires capitalist chefs to direct people to whichever serving counter is being used rather than being able to use both, improving the customer service experience for the rest of the crew.
The wrench allows chefs to unanchor and reanchor the points of sale immediately at round start, either to set them up, or to allow communist chefs to throw them into …

Buffs Capitalist Chef

---

code/modules/antagonists/zombie/zombie_spells.dm

As the title says. Makes augmented or robotic limbs immune to zombie claw infections. Leaves the bite as is.
WYCI moment, talked with @Contrabang about it. They said it'd make sense for augmented limbs to be immune to zombie claw infections.
You have to go through a process even to get your chest and/or head augmented. Chance of infection from malpractice. It isn't without its' own costs to get augmented. With that being said it doesn't make you immune to infection. You can still get infected via direct bites.
Compiled. Augmented a nian, slashed them a few times. 🧟 🛑 
Slashed a vox (derogatory)... 🧟 
Bit the augmented nian. 🧟 , yummy.
:cl:
tweak: Made augmented / robotic limbs immune to zombie claw infections.
/:cl:

[TWEAK] Makes robotic limbs immune to zombie claw infections.

---

code/game/objects/items/tools/multitool.dm

Multitools can now be used to find APCs.
Press Z (aka attack_self) in hand to use it.
Makes it easier for newbie and veteran engi players help find where that freakin broken APC is in the room without looking at the .dmm files
See above
:cl:
add: Multitools can now be used in-hand to find a room's APC
/:cl:

Multitools can now be used to find APCs

---

_maps/map_files/stations/cerestation.dmm

Puts the Chapel Requests Console on Cerestation back on the wall.
Requests consoles need walls. Bad mapping is bad.
Booted up. Map fix.
:cl:
fix: Put Farragus chapel request console back on the wall
/:cl:

Fixes Chapel Requests Console on Farragus

---

code/game/objects/items/stacks/rods.dm
code/game/objects/items/weapons/handcuffs.dm

Fixes #22238.
Tiny cleanup of code.
Fix good.
Code nicer.
Compiled.
Cannot make wired rods as borg.
:cl:
fix: Borg zipties cannot be used to make wired rods.
/:cl:

[FIX] Cyborg Zipties Will Not be Consumed When Making Wired Rods

---

_maps/map_files/stations/cerestation.dmm

The Galactic Tobacco Federation has lobbied for YOUR interests as an enjoyer of our many products. Whether it's the smooth flavour of an Uplift, the dominant sensation of a Robust Gold, or the complex sophistication of an Embellished Enigma, we know you wish to be able to access your favourite brand without hassle.
And so, Nanotrasen has bowed to our demands and installed TEN brand new ShadyCigs Deluxe vendors to the NSS Farragus. These have been spaced out across the asteroids to ensure you don't have to run too far to reach them, because we know that for some reason (completely unrelated to the consumption of tobacco products) you just seem to run out of breath a lot faster than you used to.
And remember, don't listen to the reports, smoke today!
There are only 6 cigarette machines …

Enhances the Farragus Smoking Experience

---

code/datums/outfits/outfit_admin.dm
code/game/objects/items/weapons/storage/boxes.dm

This PR aims to improve the life and logic of Deathsquad existence.
1. I added sechuds with nightvision so they can recognise friends & foes better, especially when [this PR](https://github.com/ParadiseSS13/Paradise/pull/25743) will be merged.
2. I replaced flashbangs with smoke grenades, because Deathsquad don't really need non-lethal force. Smoke grenades will better outplay with thermal vision.
3. I replaced X4 with barrier grenade, and put X4 into "emergency" box, because why you ever want to use X4 when you had pulse rifle.
4. I added cybernetic implants to them, because Gamma ERT have it, so why they don't?
5. I added one extended-capacity oxygen tank to their emergency box, because you could litterally just lose yours, and that's it.
Deathsquad has some of the strongest weapons and …

Buffs Deathsquad - inventory revision and implants

---

code/modules/mob/living/carbon/human/species/drask.dm
code/modules/mob/living/carbon/human/species/grey.dm
code/modules/mob/living/carbon/human/species/kidan.dm
code/modules/mob/living/carbon/human/species/moth.dm

When these species are ghostized, get_runechat_color() throws a runtime because their internal organs no longer exist. Returns flesh_color as a default.
Bug
compiled

Fixes eye_color runtimes for Drask, Kidan, and Nian

---

_maps/map_files/stations/boxstation.dmm

Swaps the positions of the Cyberiad robotics disposals chute and table.
I HATE IT I HATE IT I HATE IT!
Protolathe that you build in the place of that table should not be separated from the RnD console by a disposals bin.
It compiled.
Stuff is where it should be.
:cl:
tweak: Swapped a table and disposals unit in Cyberiad robotics.
/:cl:

Buffs Cyberiad Robotics' Feng Shui

---

code/game/objects/items.dm

Fixes some runtimes that occur when an admin-reporting item is deleted in nullspace.
Fewer runtimes good.
The root cause of this is so unbelievably bad I don't even want to think about it.
Compiled.
NPFC

Adds a check on messaging admins if an item is in nullspace.

---

code/__DEFINES/misc_defines.dm
code/modules/surgery/organs/organ_external.dm

Makes higher levels of infection, particularly in the context of burn wounds, a bit less deadly. Germs will now not outright kill your vital limbs at level three, and will instead start to deal heavy toxin damage. Once they reach a new level four, they will still kill your vital limbs, but you should have a bit more of an idea of what's coming down the pipeline rather than just dropping dead.
Also adds a little bit of feedback as you start to creep up in infection levels.
Dropping dead because your chest suddenly died sucks. At least if you quickly decline, it feels a bit less random.
VVed my chest to have large amounts of germs, and then waited until I saw the eepy disk.
:cl:
tweak: High levels of germs in vital external organs will now deal heavy toxic damage first, which should be much …

Makes high levels of infection less likely to kill you instantly

---

code/modules/mob/living/carbon/carbon_update_status.dm

People now instantly fall asleep the moment they hit -100 HP, rather than an up 2 second delay.
357 / melee biohazards / other high alpha weapons without stamina damage suffer from 2 issues: limb damage cap, and the 2 second before knockout period.
This PR addresses the second issue, where a person rapidly dropped into crit would get 2-3 more shots off, even if they were 50 damage past the sleep point, making stamina crit weapons prefered as they could not shoot back / instantly went down from stamina.
Outside of these weapons, the only major change is if you are not stamina crit, as if you are in crit normally for a while, you'll randomly be knockdowned or stunned or slept from crit, likely leading to no diffrence felt there. This just makes the bigger hitting things, or pure melee …

Humans now instantly fall asleep at -100 HP, rather than after an (up to) 2 second delay

---

code/datums/spells/mind_transfer.dm

Makes mindswap happen instantly, unleashing a loud sound and silencing everyone in a range around both the target. Who can themselves be up to 3 tiles away. This also removes the hardstun, so you can start running instantly.
In a gamemode where many people will be running at each other at once, we need to keep the meta info on things as low as possible. After the wizard loudly yells I AM USING THE MINDSWAP SPELL and two people are stuck jittering on the floor, the wizard is pretty much dead if they aren't careful about it, or if there is at least one other person who can take that 10 second stun to beat the shit out of you.
Let's make it faster :trollface:
swapped minds with myself once or twice. effects worked as intended.
:cl:
tweak: Mindswap is now instant at range 3. It now doesn't …

Makes mind swapping instant

---

code/modules/events/blob/theblob.dm

Fixes diagonal expansion sometimes breaking when the blob tile does not have an assigned overmind. I don't know why blob tiles sometimes don't get assigned an overmind when `Pulse()` is called. They just do. This antag needs serious help.
It was broken (sometimes) and now it's not
Didn't runtime. I can't check how the overmind assignment works with a second overmind and there is a small chance something wonky will happen.
:cl: Chuga
fix: Made blob diagonal expansion less buggy
/:cl:

Fixes blob diagonal expansion

---

code/game/objects/items/weapons/storage/bags.dm

Fixes #25639.
Refactors the serving tray code a bit because ghhhhhhhhdsjkvksqdbv-
Renames "tray" to "serving tray"
Hitting someone with the tray with items in it makes the items spill around the target instead of you.
Tray now does knockdown instead of hardstun.
Bug bad.
Nice code good.
Nice name also good.
Hardstun bad.
Nice spill physics also also good.
It compiled.
Be service borg.
Use tray to scoop item.
Spill items on floor, they didn't teleport across the station.
Hit someone with full tray, it scattered around them.
:cl:
tweak: rename tray to service tray.
tweak: a full tray scatters items around the target when hitting them.
tweak: tray does knockdown instead of hardstun.
fix: fixed the borg service tray teleporting items across the station.
/:cl:

Serving Tray Tweakery

---

code/__DEFINES/dcs/signals.dm
code/_onclick/hud/alert.dm
code/datums/components/defibrillator.dm
code/modules/antagonists/changeling/changeling_power.dm
code/modules/antagonists/changeling/datum_changeling.dm
code/modules/antagonists/changeling/powers/fakedeath.dm
code/modules/antagonists/changeling/powers/revive.dm

When a changeling is faking death, and they get defibrillated, they can now be revived like any normal dead person.
If the changeling accepts, it will appear like a normal defib happened, and the changeling loses all aheal/revive powers
If the changeling denies (doesn't click on the status) it will appear like the ghost isn't in the body
If its a non-changeling form of fake death, like capulettium, it will appear like it used to.
A white-box will appear around the status effect to indicate it has been accepted. It can be toggled for the 5-seconds while being defibbed, by default it is off.
Also adds more safeties to the cling Revive power to prevent it from being stacked or from being used while alive.
Its very awkward when a changeling is forced to revive or be cloned or just left in …

Changelings now get an option to be revived by defibrillator when faking death

---

code/game/machinery/computer/ai_core.dm

Fixes #23696
The root cause here is that the laws were qdeleted by the AI core after being transferred to the AI mob, causing them to get hard-deleted at some time in the future, which would reset them to NT-Default once something triggered a sanity check.
Random law changes with zero notice suck.
Constructed AIs before:
And after:
:cl:
fix: Fixed a bug that made all constructed AIs randomly reset to NT Default after an indeterminate amount of time, without informing them.
/:cl:

Prevent constructed AI laws from randomly becoming null.

---

code/game/turfs/simulated/floor/misc_floor.dm

Catwalks now become space rather than turning into catwalk when exposed to a singularity or explosion
Recursion bad, catwalks being bomable / not infinite singulo food good.
Resolve #25838
:cl:
fix: Catwalk turfs can now be bombed properly / ate by singulos
/:cl:

fixes catwalk recursion

---

_maps/map_files/RandomRuins/LavaRuins/lavaland_surface_hermit.dmm
_maps/map_files/RandomRuins/LavaRuins/lavaland_surface_shuttlecrash.dmm

Fixes active atmos on shuttle crush and hermit ruin
No active turfs on roundstart
None
Tested in-game
:cl:
fix: Fix active atmos on some Lavaland ruins
/:cl:

Fix active atmos on shuttle crush and hermit ruin

---

code/datums/uplink_items/uplink_traitor.dm

Title.
While the spikethrower is an interesting and powerful weapon, it is unfortunately a bit overpriced compared to contemporaries such as the Power Fist and Chainsaw. This should make it picked a bit more.
N/A, one number change
:cl:
tweak: Spikethrower now costs 50TC
/:cl:

Decreases Spikethrower's cost to 50TC

---

code/modules/atmospherics/machinery/atmospherics.dm

Tweaks unsafe pressurized pipe unwrenching so that standing ontop of the pipe, instead of making you do a flip, will instead fling you in a random direction.
Magboots are required to work with atmos pipes to prevent being tossed, unless you stand directly ontop of the pipe as it is currently. This makes it so that you need magboots even while standing on the unsafe pipe.
https://github.com/ParadiseSS13/Paradise/assets/144391971/391249ff-a1b2-469d-a259-81dd6a49f5e3
See above. Spawned as CE, made a pressure problem, did not follow OSHA.
:cl:
tweak: Pressurized pipes now fling you in a random direction when stood on and wrenched unsafely.
/:cl:

Unwrenching a pressurized pipe you're standing on now flings you in a random direction

---

code/datums/components/parry.dm
code/game/gamemodes/cult/cult_items.dm
code/game/objects/items/hand_item.dm
code/game/objects/items/weapons/holy_weapons.dm
code/game/objects/items/weapons/shields.dm
code/game/objects/items/weapons/twohanded.dm
code/modules/mining/equipment/kinetic_crusher.dm
code/modules/surgery/organs/augments_arms.dm

Anything with default parry stats has a 50% uptime again, instead of a 33% uptime.
Everything else with less cooldown should be the same, along with more.
Removes the unneeded check added to parry code inflating *all* block checks by 1 second, instead just makes dsword and v1_arm have the intended 1.33 cooldown instead of .33 cooldown
This is probably part of why parrying doesn't feel great right now, because it has the wrong values and is only 33% active instead of 50% active right now
Blocked and confirmed values with debugger
:cl:
fix: Most blocking items have 50% uptime instead of 33% uptime again.
/:cl:

fixes block uptime being 33% instead of 50%

---

_maps/map_files/RandomRuins/SpaceRuins/syndie_space_base.dmm

Fixes #25841
Syndie researchers should be able to test multiple bombs without having to space walk.
Blew up the syndicate research bomb site. Plating was still there for bombs to land on.
:cl:
fix: Added an indestructable plating to syndie test site
/:cl:

Adds single indestructible plating to syndie researcher bomb site

---

code/game/area/areas/mining_areas.dm

Fixes an area's name used in winter biodome and clown ruin. These aren't where labor camp is.
People in these areas shouldn't be shown as if they were inside labor camp in gps.
Yes
:cl:
fix: fixed a lavaland area name.
/:cl:

Fixes a misleading lavaland area name

---

_maps/map_files/stations/boxstation.dmm

Gives the keycard authenticators back to the NTR and BS on cyberiad, as well as moves the request console out of the wall, so you cant see it from maints
Was missed in the explorer PR
Compiles, checked in game if the request console was good
:cl:
add: Added keycard authentication tappers back to the NTR and BS office on cyberiad
tweak: Bluesheilds request console is no longer accessible via maintenance on cyberiad
/:cl:

Gives the bluesheild and NTR back their keycard authenticators on boxstation

---

_maps/map_files/RandomRuins/LavaRuins/lavaland_surface_althland_facility.dmm
code/modules/mining/machine_processing.dm

Processing_unit is no longer dense!
Fixes #25966 
You can now access a blocked off part of the ruin.
Spawned in and walked into the blocked off area after fixing density.
:cl:
fix: A console no longer blocks the way when exploring a certain lavaland ruin.
/:cl:

Processing_unit is no longer dense - Fixes #25966

---

code/__DEFINES/misc_defines.dm
code/_onclick/click.dm

Removes move cooldown was that applied on any click while handcuffed. It prevented you from resisting via clicking the handcuffed alert. I think it's safe to remove because you shouldn't get a move cooldown from an UI click. Just a relic from the past
Makes clicking the handcuffed alert work again
Using references to `next_move`, checked if things behaved fine by clicking while being handcuffed
:cl:
fix: Handcuffed alert clicking to resist now works again
/:cl:

Removes cuffed click CD to fix handcuffed alert not working

---

code/game/objects/items/weapons/melee/melee_misc.dm
code/modules/mod/modules/modules_science.dm

Bluespace spellblade can now work with thermals or xray vision, allowing a wizard who spent points on say, smoke, or the scrying orb, to not get ripped off. It's magic, it works.
The teleporter module for modsuits that requires a bluespace core, now works with mesons or xray. You spent a core on this instead of a phason, it should work through walls.
A magic spellblade a wizard can buy should work through walls with xray or thermals.
A teleportation module that you took over a phason should bloody work through walls. I intended this, but uh, checks to prevent camera teleporting to AI core made it a pain.
Smacking skrells through walls with xray and thermals.
Teleporting through walls with mesons and xray.
:cl:
tweak: Bluespace spellblade works with thermals or xray now.
tweak: The modsuit …

bluespace spellblade and modsuit teleporter module work better

---

_maps/map_files/stations/boxstation.dmm

This PR removes floating disposals pipes on Box bridge and reconnect's Blueshield's disposal chute to the pipe network.
Disposals should work, pipes shouldn't just vibe.
Spawned in, threw thing in BS's disposal, ensured it arrived in Disposals.
:cl:
fix: Cyberiad: Blueshield's disposals chute is properly connected to the pipe network.
fix: Cyberiad: Disconnected disposals pipes on bridge have been removed.
/:cl:

box: handful of disposals fixes

---

code/modules/surgery/generic.dm

Makes cauteries remove up to 50 germs from the target limb when finishing a surgery, instead of sterilizing it
This makes it quite hard for germs to spread, unless the surgery took so long that adjacent bodyparts got infected aswell
Ongoing
:cl:
tweak: Cauteries now remove a small part of germs instead of fully sterilizing bodyparts when finishing a surgery
/:cl:

Cauteries now don't sterilize the limb they're cautering

---

code/game/turfs/simulated/walls_misc.dm

makes the boss walls  that can be broken baseturf mapping lava like the rest of lavaland instead of space
fixes this silly part of lavaland from spacing when someone fights vetus or sets off gibtonite near it.
airstriked and bombed these walls in lavaland.
It became the lava of the generation, as expected, when the plating below the walls was destroyed.
:cl:
fix: The boss arena at the north end of lavaland should no longer space itself
/:cl:

lavaland spaces itself 5% less

---

code/modules/shuttle/supply.dm

Fixes a bug that caused the supply shuttle to sometimes not bring items.
The root cause here is that shuttle docking is partially asynchronous due to MILLA, so we need to check the target port's z level, rather than the shuttle's.
Bugs bad. Getting crates good.
Ordered stuff 10 times, on 10 separate shipments, got stuff all 10 tomes.
:cl:
fix: Fixed a bug where the cargo shuttle would sometimes forget to bring your stuff.
/:cl:

Fix supply shuttle forgetting to bring stuff.

---

code/game/atoms.dm
code/game/objects/items.dm
code/game/objects/items/weapons/soap.dm
code/modules/detective_work/detective_work.dm
code/modules/mob/living/carbon/human/appearance.dm
code/modules/mob/living/carbon/human/human_defense.dm
code/modules/projectiles/projectile_base.dm
code/modules/surgery/other.dm
code/modules/surgery/surgery.dm

Objects without blood overlay(such as airlock) not make your hands/gloves bloody
Touching something bloody with bare hands now makes only hands bloody
Cleaning bare hands cleans overlay too
Replaces null blood color with red blood
Soap cant be covered in blood
Blood spread PR caused some bugs and unexpected behaviour, this PR fixes that.
Compiled, touched various bloody things with gloves and without, cleaned that all
:cl:
tweak: Only bloody items now make your hands/gloves bloody. Airlocks and other objects in game no longer spreads blood on your hands.
tweak: Soap cant be covered in blood.
fix: Cleaning bloody bare hands now removes blood overlay too.
fix: Touching bloody object with bare hands now only spreads blood on your hands.
fix: White blood(null color) shouldnt be a thing …

Blood spread fixes and tweaks

---

code/controllers/subsystem/SSthrowing.dm
code/datums/components/boomerang.dm
code/game/atoms.dm
code/game/atoms_movable.dm
code/game/objects/items/sport.dm
code/game/objects/items/theft_items.dm
code/game/objects/structures/window.dm
code/modules/mob/mob_movement.dm
code/modules/recycling/disposal.dm

Fixes #20077
Fixes #22009
Port of https://github.com/tgstation/tgstation/pull/60604 and later bugfixes.
Our old version of SSthrowing had a lot of crust and lacked proper GC handling. #25921 was made in response to a case where catching the thrown grenade would cause it to both deposit into your hand and land one tile behind you. The rough sequence of events I narrowed the cause down to is as follows:
1. The boomerang component calls `throw_at()` on the rebound, likely choosing a turf directly behind the mob.
2. The next `tick()` happens and the grenade is moved one turf in the direction of the mob.
3. Moving onto this turf triggers `Bump` against the mob, which in turn calls `throwing.hit_atom(atom)`, which then calls `finalize()`. `finalize()` triggers the mob's `hit_by`, which …

Refactors throwing

---

code/game/atoms.dm
code/game/objects/items.dm
code/modules/detective_work/detective_work.dm

This PR fixes full gloves being able to infinitely spread blood from a single bloody item
This PR reverts infinite spreading blood on items if your hands/gloves are bloodied
Blood PRs went too far with blood spreading, combined with some bugs, obvious and hidden, it should be just gone.
In total, this PR with other two do this:
Hitting someone who is bleeding makes your hands/gloves bloodied
Touching bloodied item will make your hands/gloves bloodied
You can no longer make an object bloody(such as a door, a vendor) since some of these objects just cant basically be cleaned
These three also fixes some weird mechanics from the past with blood spreading as it was, like making your whole body bloody instead of just hands and such
I hope i didnt forget anything
Compiled, touched bloody items …

Last bloody blood tweaks and fixes

---

.github/CONTRIBUTING.md

Removes this line
```
- Pull requests should be atomic; Make one commit for each distinct change, so if a part of a pull request needs to be removed/changed, you may simply modify that single commit. Due to limitations of the engine, this may not always be possible; but do try your best.
```
- I've never seen anyone actually make only commits for changes for specific parts of a PR, it's usually either all bundled up or in 15 commits that are all labelled variations "No time to finish this now, will fix later"
- In my opinion (and as far as I'm aware also from other dev team members), a better description of what an atomic PR is, is the line below it 
The line is pretty much the same except for changing the word `small` into `atomic`
```
- Keep your pull requests atomic and reviewable …
```

Updates CONTRIBUTING.md to better describe what an atomic PR is

---

code/game/objects/items/weapons/cigs.dm

Fixes #25857
Adding reagents to pipes and cigs should add additional time to how long they can be smoked for.
Spawned a pipe, smoked a bit, added reagents, was able to continue smoking the pipe.
:cl:
fix: Dipping a pipe or cig in a beaker now adds smoke time with the reagents added
/:cl:

Added smoketime calc to adding reagents

---

code/game/objects/items/weapons/cigs.dm

Changes rollies from having nicotine to having a mixture of THC and CBD, like the medical marijuana cigs.
I'm pretty sure these are supposed to be weed and not nicotine, especially since they're scattered all over the weed den along with actual cannabis leafs.
It like, totally compiled, man!
And there was this crazy cat that scanned my joints, and they said they had some dank weed inside, dude!
So we just took some and vibed.
:cl:
tweak: Rollies now have CBD and THC instead of nicotine.
/:cl:

Replaces the Nicotine in Rollies With Weed

---

code/game/objects/items/weapons/cigs.dm

Flips medical marijuana's THC/CBD ratio - it now contains 20u THC and 40u CBD.
Medical cannabis is not bred to optimise THC yield, it's bred to optimise CBD yield. This is explicitly a medical product.
It compiled.
A medical marijuana cig was scanned, contained the correct ratio.
I smoked it, it was very relaxing, didn't zoink me out quite like how they used to.
:cl:
tweak: Medical marijuana's THC/CBD ratio has been flipped.
/:cl:

Medical Marijuana is Now CBD-Optimized

---

code/game/objects/items/devices/lightreplacer.dm
code/game/objects/items/stacks/sheets/glass.dm
code/game/objects/items/weapons/manuals.dm
code/game/objects/items/weapons/shards.dm
code/modules/power/lights.dm

The Light Replacer now eats glass sheets and lightbulbs when the user clicks on them rather than having to pick up the bulb/sheet and then insert it. This is how shards currently behave and brings them in line.
It now tells you how many fragments you have when you insert any kind of compatible item.
Shards now refill 1 full light rather than 0.75 of a light (it's literally the same amount of material, a welding tool can turn it into a sheet).
It's more convenient for human janitors.
Janiborgs are now able to actually use lightbulbs and sheets.
Conservation of mass has been achieved.
I used my light replacer on shards and glass and lights and they worked.
:cl:
tweak:  Light replacers can now eat glass and lightbulbs directly to refill.
tweak:  Shards will restore an entire lightbulb when …

Tweaks the Light Replacer

---

_maps/map_files/generic/centcomm.dmm
code/game/machinery/vendors/generic_vendors.dm

Adds Dromedary Co. and Shady Jim's cigarettes to the ShadyCigs vendor. Cigpacks are now sorted alphabetically.
Replaced Premium Havana Cigars with basic Premium Cigars. Only the best of the best are supposed to have 'em! (also the price has been increased to 100 Cr).
Syndicate vendors are now better stocked, but do not carry Robust brand anymore, as the markings on the packets suggest it's an NT brand (which they wouldn't want for obvious reasons).
The ShadyCigs Ultra now carries all the cig and cigar types except for Syndicate cigarettes, and it carries a lot of them.
CentComm is now equipped with a ShadyCigs Ultra.
Dromedary Co. is another nicotine flavour, for the smoker's roleplay.
Shady Jims' is the smoking version of the weight loss shake and provides another way to not be fat on …

Expands the Cigarette Vendor Inventory

---

code/game/gamemodes/cult/runes.dm
code/game/gamemodes/miniantags/abduction/machinery/experiment.dm
code/game/objects/items/weapons/bio_chips/bio_chip_freedom.dm
code/modules/antagonists/vampire/vampire_powers/gargantua_powers.dm
code/modules/mob/living/carbon/carbon_procs.dm

- Slightly refactors `/mob/living/carbon/proc/uncuff()`
- Renames the proc to `clear_restraints()`
- Splits clearing handcuffs and legcuffs into separate procs.
- These procs now have a return value of either `TRUE` or `FALSE` depending on whether or not the respective item existed and was removed.
- All three procs now have the argument `show_message` (defaults to`FALSE`), which when `TRUE` will display a `visible_message` about the restraint being removed.
Gameplay changes:
- Blood Rush cannot be activated when the vampire is stamcritted, stunned, or buckled. This means that you will not waste blood when you can't benefit from the speed.
- Blood Rush now clears knockdowns, instantly stands the vampire up, and removes any legcuffs (bolas, beartraps).
The removal of Shadowstep left …

Gargantua Blood Rush now removes bolas

---

code/modules/research/designs/medical_designs.dm
code/modules/surgery/organs/augments_eyes.dm

Created a hydroponic HUD implant to match the medical, security, diagnostic, and janitorial implants.
Adds a hydroponic HUD implant option in order to mirror the medical, security, janitorial, and diagnostic HUD implants. 
Allows farmers to keep up with janitors in unnecessary cybernetic augmentation arms races.
Leveled up required technologies at R&D desk, printed hydroponic HUD implant. Implanted in humanized monkey, possessed humanized monkey, verified that monkey could see hydroponic HUD meters. Removed implant from humanized monkey, verified that monkey could no longer see hydroponic HUD meters. Verified that hydroponic HUD implant and worn medical HUD stacked successfully. Verified that hydroponic HUD implant and worn hydroponic HUD did not interfere with each other.
:cl:
add: Added …

Adds hydroponic HUD implant

---

code/modules/awaymissions/mob_spawn.dm
code/modules/ruins/ghost_bar.dm

Allows antagbanned players to use the ghastly rejuvinator in the ghost bar. Fixes #25868
Antagbanned players are supposed to not be able to be ghostroles so they can't mess with other players, but ghost bar players have no way to interact with the main station.
Used breakpoints to make sure the spawner logic didn't change how it currently works, but unfortunately without a database set up I cannot actually test if you can use the rejuvinator while jobbanned.
:cl:
fix: People with antagbans can join the ghost bar
/:cl:

Antagbanned people can join the ghost bar

---

code/__HELPERS/unsorted.dm
code/_onclick/click.dm
code/datums/spells/alien_spells/neurotoxin_spit.dm
code/datums/spells/wizard_spells.dm
code/game/mecha/equipment/weapons/weapons.dm
code/modules/mining/equipment/kinetic_crusher.dm
code/modules/mob/living/simple_animal/hostile/hostile.dm
code/modules/mob/living/simple_animal/hostile/megafauna/colossus.dm
code/modules/mob/living/simple_animal/hostile/mining/elites/herald.dm
code/modules/mod/modules/modules_engineering.dm
code/modules/mod/modules/modules_supply.dm
code/modules/projectiles/firing.dm
code/modules/projectiles/guns/misc/blastcannon.dm
code/modules/projectiles/projectile_base.dm

preparePixelProjectile currently has the parameters, which have been turned into
```
(atom/target, turf/targloc, mob/living/user, params, spread) 
-> (atom/target, atom/source, list/modifiers = null, deviation = 0)
```
Where modifiers is is now a list (use params2list before passing it in).
Moves the actual math into a separate helper proc, calculate_projectile_angle_and_pixel_offsets(). Most of this code has been directly ported from TG because our versions were ~95% the same. 
This is a required step towards the pellet_cloud component in #25527, which needs a version of preparePixelProjectile that does not get source turf location from a mob/living/user. 
Tested every single changed item and made sure that they didn't runtime or do weird things.

Refactors preparePixelProjectile

---

_maps/map_files/stations/deltastation.dmm

Replaces a couple of incorrect tiles in Delta's departure lounge with the correct colors. I accidentally changed these during my Chapel PR and missed them :( 
Mistakes bad. Wrong colors bad. Fixing my mistakes good.
Spun up a test server, saw that they were the right color. Wondered how my life brought me to this point.
:cl:
tweak: replaces miscolored tiles in departures with correct ones (my mistake)
/:cl:

Replaces a couple rogue tiles on Delta (Kerberos)

---

code/game/objects/items/weapons/storage/bags.dm

Gives treasure satchels their icon back
These shouldn't bei nvisible
Spawned in a treasure satchel, saw the treasure satchel
:cl:
fix: Treasure satchels have icons again
/:cl:

Fixes treasure satches not having an icon

---

code/game/machinery/recharger.dm

You can no longer unwrench a wall-mounted recharger to drag it around.
Dragging these things around is all kinds of cursed.
You can still disassemble them.
I couldn't wrench the wall chargers.
:cl:
tweak: You cannot wrench a wall recharger.
/:cl:

Wall Rechargers Cannot be Unwrenched.

---

.github/workflows/label_stale.yml

- Removed quotes around labels in the stale bot config
I am certain that quotes aren't supported, as no one mentioned them in the issue https://github.com/actions/stale/issues/98. They are not handled in code, either
https://github.com/actions/stale/blob/3f3b0175e8c66fb49b9a6d5a0cd1f8436d4c3ab6/src/functions/words-to-list.ts#L17
Furthermore, stale bot closing #25071 despite being stale exempt is further proof of this
Stop closing stale-exempt PRs like #25071
Unable to

Fix stale bot closing stale-exempt issues and PRs

---

code/modules/mob/living/carbon/human/human_mob.dm
code/modules/power/engines/singularity/narsie.dm

When narsie is spawned in, cultists will no longer be turned into harvesters by them.
They also won't be targetted by them when narsie is active but thats been broken for years
Cultists are more powerful than harvesters and it doesn't actually feel like a *reward* to be turned into one. Every time narsie is summoned, all of the cultists struggle and run to get off the rune so they don't get gibbed.
Compiles. Spawned Narsie on top of myself as a cultist. Didn't get gibbed and transformed into a harvester
:cl:
tweak: Cultists will no longer be turned into harvesters by Nar'Sie
/:cl:

Narsie no longer sacrifices their own cultists

---

code/game/objects/items/stacks/sheets/sheet_types.dm
code/game/objects/items/weapons/storage/firstaid.dm
code/modules/crafting/recipes.dm

This adds the aquatic starter kit and the machine repair kit to the list of craftable medkit from plastic.
It also adds a special craft, similar to the fake syndi toolbox, to make empty tactical medkits using blue paint and black paint.
Less impossible to get/remake items
More medibot customization :D
Made sure all medkits could be made through their correct means
~~Made sure the tactical medkit was the EMPTY one... Totally didn't forget this the first time I added it~~
Made sure the tactical medkit was the new fake variant.
Also made sure the medibot made from the fake variant used the right chems and healed crewmembers.
:cl:
add: Added a recipe for tactical medkit using blue and black paint and a first aid kit
add: Added recipes for the aquatic starter kit and the machine repair kit …

More medkits ! With the correct branch this time!

---

code/game/objects/items/weapons/storage/garment.dm
code/game/objects/structures/crates_lockers/closets/secure/security_lockers.dm

Adds both the security and medical sunglasses to the Captain's garment.
Adds a handheld monitor inside the Blueshield's closet.
Usually Captains have to ask security/medical to get one or even craft one if they desire, doesn't make sense for them to not have both available. Same situation applies for the Blueshield, which usually has to grab a crew monitor from medical.
Joined in the test server and grabbed said items.
:cl:Pedroca
add: Captain's garment now has both the medical/security sunglasses.
add: Blueshield's locker now starts with a handheld crew monitor
/:cl:

Gives more HUD options for the Captain and gives the Blueshield a crew monitor.

---

code/controllers/subsystem/processing/SSdcs.dm

Updates `GetIdFromArguments()` with its most recent TG iteration to make it work properly. This proc is used for generating IDs for elements with ELEMENT_BESPOKE (see dcs_flags.dm for what this does). 
I noticed ELEMENT_BESPOKE elements not generating properly while working on #25527. There aren't many things that use bespoke elements right now, but having it working is required for said PR.
It launches and runs. I can't test this much on a fresh master branch because there aren't many things to test. This did, however, fix the issues I was experiencing with element generation in #25527 and was tested pretty thoroughly with a new element type then.

Fixes SSdcs element ID hashing

---

code/modules/surgery/organs/subtypes/diona_organs.dm

Changes the names of most internal Diona organs.
The brain (**gas bladder**) is now the **neural strata**.
The heart (**neural strata**) is now the **circulatory siphonostele**.
The lungs (**respiratory vacuoles**) is now the **respiratory nodules**.
The kidneys (**polyp segment**) is now the **sieve-tube bundles**.
The appendix (**anchoring ligament**) is now the **auxiliary bud**.
The liver (**"nutrient vessel**) is now the **nutrient sac**.
Neural tissue is now the brain.
Most of the rest of the organs are now named after real plant structures, and they mostly do roughly the same thing as the organs or something related.
Looked inside a diona.
:cl:
tweak: Renamed diona organs.
/:cl:

Renames Diona Organs

---

code/__HELPERS/time.dm
code/modules/mob/living/carbon/human/human_update_icons.dm

Fixes #7596
Updates our icon overlays for humans to check if that little mans got leggies first.
A person shouldn't have socks on if they don't have legs. 🤔 
Spawned a skrell, put on thigh-highs (rainbow) nugget.... smite. No socks!
Rejuv'd to see if socks would appear again, they do.
:cl:
fix: Fixed a sock overlaying issue.
/:cl:

[FIX] Humans no longer have socks when they're missing either leg: My socks got knocked off!

---

code/modules/reagents/chemistry/machinery/chem_dispenser.dm

Prevent maintenance drones from using chem dispensers.
It's only a vector to break their laws and/or the rules.
Spawned as drone. Couldn't use.
Reincarnated as chemist. Could use.
Transformed to robot. Could use.
Emagged a drone. Could use.
:cl:
del: Maintenance drones can no longer use chem dispensers.
/:cl:

Prevent maintenance drones from using chem dispensers.

---

code/game/gamemodes/nuclear/nuclear_challenge.dm

Currently with the requirement of 50 people to go to war, we've seen an uptick in what people call "Blitz ops" where crew has no fore warning of 5 individuals with hijack perms and nukie gear rushing after a single objective. And its not even that the nukies WANT to do this, its cause they CANT war at all. 
So this lowers the minimum crew pop requirement from 50 to 30.
The element of surprise is extremely strong. Catching crew with their pants down prevents them from mobilizing fast enough to counter the nukies before they push the captain and nuke the station. Its not fun for the crew when you just die/lose without much of a fight.
Compiled!
:cl:
tweak: Lowered the minimum required players for nukies to declare war to 30
/:cl:

Lowers the minimum crew amount needed to War

---

code/game/objects/structures/tables_racks.dm
code/modules/supply/supply_packs/pack_miscellaneous.dm
code/modules/vehicle/tg_vehicles/scooter.dm

Glass tables break again.
Scooters are craftable.
Crashing into someone with a skateboard still knocks them down, but only hardstuns if you are grinding.
Hoverboard now costs 999 credits, so it is not grand theft if a tider steals one.
fix #26059
fixes #23975
Bugs are bad.
Bugs are bad.
Hardstuns are bad unless the situations that create them are hard to pull off or sufficiently funny.
A tider being arrested for grand theft from a hoverboard is bad.
I'll likely have to make scateboards disembark you if you get hit by enough lethals or stamina in a short period, but not touching  that in this PR.
Crafted skateboard. Screwdrivered. Applied metal. Applied rods.
Threw people on glass tables. Disarmed on glass tables. Climbed on glass tables. Hoverboarded across glass  tables.
Bonked into a …

Fix glass tables. Fix crafting. lower price  / stun

---

code/game/objects/items.dm

Changes eyestabs from dealing a flat 7 damage to dealing damage based on the force of the object you're stabbing with. Fixes #25161
Damage should be consistent
Used health scanner to check how much damage each item was dealing
:cl:
fix: Stabbing someone in the eye now deals the correct amount of damage
/:cl:

Fixes eyestabbing not dealing a correct amount of damage

---

code/datums/uplink_items/uplink_general.dm

Title. Dsword can now be bought directly in the uplink at a 20TC bulk discount.
The dsword is really damn overpriced for a weapon that is debatably worse than the chainsaw, as you are forced to pay 80TC for the privilege of wielding it.
Hopefully this makes it used a bit more often.
- loaded in
- checked uplink
- dsword
:cl:
tweak: Dsword can be bought in the uplink for 60TC
/:cl:

Dsword can now be purchased directly

---

code/game/objects/items/crayons.dm

Changes the spray can knockdown check to be looking for if eyes are covered, rather than eye protection being less than 0
As well as cleans up the proc because whoa. it was bad
AND adds a message if theres not enough uses to effect someone
The spraypaint checking for eye protection makes sense, until you notice one pesky thing. You can get less eye protection from multiple means, Mainly nian eyes, as well as cling augmented eyes in xray mode, xray eyes, and thermal eyes. theres some others, but those are the major ones
This is an issue, because spraypaint isnt a flash, its.. paint, pretty much pepper spray lite. so it effecting people that're vulnerable to flashes is a little silly.
Cleaning up the proc is self explanatory, the proc was.. really bad, it was checking multiple things …

Spray paint no longer checks for eye protection, and rather if the eyes are covered or not.

---

code/modules/recycling/sortingmachinery.dm

This PR allows small items to be immediately flushed through airless disposals chutes.
Disposals and thrown objects are weird. When thrown atoms reach a delivery chute, CanPass is called on them, which has a 75% chance of forceMoving the atom into the disposal:
https://github.com/ParadiseSS13/Paradise/blob/f6b8d87e7850de83b2de149fbb9e7b204164fadc/code/modules/recycling/disposal.dm#L525-L540
However, even if it intakes the item, the disposal still counts as an obstacle, and so the thrown object Bumps against it, and disposal chutes have behavior in Bumped to attempt to flush the thrown object (this is also why objects that "bounce off" a disposal chute still always make it in):
https://github.com/ParadiseSS13/Paradise/blob/f6b8d87e7850de83b2de149fbb9e7b204164fadc/code/modules/recycling/sort …

fix: allow airless chute flushing of small items

---

code/modules/vehicle/tg_vehicles/tg_vehicle_actions.dm

Fixes #26103
Updates pixel y on ollie, for the cases when someone does not move, causing the game to animate their pixel y through the skateboard
Misaligned pixel y bad
Did ollies, looked normal.
Did walk intent ollies into a wall, looked normal
:cl:
fix: Fixes phasing through the skateboard
/:cl:

Fixes phasing through the skateboard

---

_maps/map_files/RandomRuins/SpaceRuins/voyager.dmm
code/modules/ruins/spaceruin_code/voyager.dm

Makes the voyagers satellite components storage a wall subtype so it can be deconstructed and the safe under it can be reached.
Also fixed the spelling on the wall.
Fixes #26023 
No visual changes to the dmm
Tested on localhost, wall was deconstructible and the floor safe could be reached
:cl:
fix: The Voyager space ruin's reward is accessible
spellcheck: Fixed the spelling on Voyager's wall
/:cl:

Makes the Voyager space ruins reward accessable

---

code/game/objects/effects/effect_system/effects_water.dm
code/game/objects/items/weapons/grenades/chem_grenade.dm
code/game/objects/items/weapons/tanks/watertank.dm
code/game/objects/structures/stool_bed_chair_nest/chairs.dm
code/modules/assembly/proximity.dm

Fixes a bug where you cannot throw certain items (Chemical grenades, proximity sensor, office chair)
Fixes: #26098
Being unable to throw stuff far, ESPECIALLY an armed grenade is an issue for obvious reasons.
Throw a cleaning grenade.
It actually flies more than 1 tile.
:cl:
fix: Chemical grenades, and a couple of other items can be thrown further than 1 tile again.
/:cl:

[FIX] You can now throw chem grenades (And some other things) further than 1 tile again

---

code/datums/shuttles.dm

Standardizes the naming schemes of most purchasable shuttles. Shuttle prefixes now use N followed by letters designating their function. I.e NTV Charon, or Nanotrasen Transport Vessel Charon.
Renames some shuttles which lacked a name.
Rewrote and grammar checked shuttle lore.
Consistency in naming schemes is good. Names for shuttles are neat. Lore is good.
- Loaded in
- Checked shuttle section
- Names and desc are updated
:cl:
tweak: Rewrote shuttle lore
/:cl:

Shuttle Lore Tweaks

---

code/game/objects/items/devices/scanners.dm

Cleans up health analyser code a bit and documents it.
Tweaks the text of the attack_self.
DNR is now surrounded by (parentheses) instead of [braces].
The analyser will now explicitly tell you that you cannot defibrillate someone that has been dead for more than 5 minutes.
Health analyser upgrades now check if you have nodrop enabled when trying to upgrade with them.
Fixes #23964.
Also the T-ray scanner's name is now correctly shown as an improper noun.
Code nicer.
Buffs grammar.
Gentle reminder to medical that after the defib timer is up, they should do something other than defibing.
Toggled my scanner, punched myself, gave a skrell cybernetic organs, did some scans.
Scanned an IPC.
Scanned Ian.
:cl:
add: The health analyzer now explicitly informs you that a patient cannot be …

Cleans up and Slightly Tweaks Health Analyser Code, Makes T-Ray \improper

---

code/modules/buildmode/submodes/fill.dm

When in buildmode's fill module, you can alt-click to copy something as the fill target.
Makes working with fill mode a bit easier.
NPFC

Adds a copy button to fill build mode

---

code/game/machinery/adv_med.dm

Body scanner now shows limbs as broken in the bodies of cloned people.
Fixes: #26065
Broken bones should not be hidden.
Break every bone in my body.
Clone myself.
Look in the scanner, all my bones are still broken.
:cl:
fix: Body scanner can now show broken bones in cloned people.
/:cl:

[FIX] Body scanner now show broken bones in cloned people.

---

code/modules/client/preference/preferences_toggles.dm

Removes second toggle for TGUI input.
Currently, there are 2 ways to disable TGUI Input:
1. In Game Preferences along with other TGUI Input settings.
2. Using toogle in Genereal Preferences. This is not the most convenient way, which also does not reflect the reality, because in the enabled state it disables TGUI Input, even though it says, "You will now use TGUI Input." and vice versa.
I think it is better to leave only 1 way, which was intended originally, the more obvious and convenient one
There is only 1
Run local and watch settings
:cl:
del: Removed Toggle TGUI Input preference into General Preferences tab. A duplicate option to disable TGUI Input
/:cl:

Remove a duplicate TGUI input toggle

---

code/__DEFINES/vehicle_defines.dm
code/datums/components/riding/riding_vehicle.dm
code/datums/elements/ridable.dm
code/game/objects/buckling.dm

Sorry for doing a balance during the freeze already, but I'm not letting this be a complaint for a month. Balance pre approved.
Simple mob animals that are normal or larger sized, can not ride skateboards.
The only hostile mob that can ride a skateboard that is a simple mob, is viscerators, and headslugs.
Cyborgs, humans, monkeys, and xenomorphs can still ride them. AI sadly can not.
You can now knock people off skateboards, unbuckling them and knocking them down for 2 seconds, by hitting them with a projectile when they have 60 or more stamina damage, or 60 or more damage. If the user is stun immune (his grace, hulk, stimulants), this will not work
This means skateboards while still effective and high risk, don't let you endlessly evade. Eventually projectiles will catch up to you and …

Only small and tiny simplemobs can go on skateboards, shoot people off them [BALANCE PRE APPROVED]

---

code/game/gamemodes/objective.dm
code/game/gamemodes/steal_items.dm

Theft objectives that accept a photo of an item (currently only being the blueprints) now state that outright
As far as I know, the only place mentioning this is the "High-Risk Items" page on the wiki. It's good to explain a mechanic in-game.
Turned myself into a traitor until I rolled blueprints theft. Saw the new message. Did not see the message on any other objective.
:cl:
tweak: Blueprints theft objective now explains that a photo of the blueprints also counts.
/:cl:

Lets the players know that they can steal just the photo of the blueprints instead of the entire thing.

---

code/datums/components/riding/riding_vehicle.dm

Fixes the bullet act proc being inside can slow down. All skateboards can slow down, but should be outside.
Forgot to press push to https://github.com/ParadiseSS13/Paradise/pull/26091
Future bugs bad
:cl:
fix: Fixed var edited skateboards not having people be able to be shot off of them
/:cl:

moves the bullet act outside on skateboards

---

code/datums/elements/ridable.dm
code/datums/elements/shatters_when_thrown.dm
code/modules/unit_tests/_unit_tests.dm
code/modules/unit_tests/element_tests.dm

See title. 
If `id_arg_index` is not overridden on elements with the `ELEMENT_BESPOKE` flag, the id generation proc will attempt to index its argument list at `INFINITY`. This is not good!
Added the unit test, watched `ridable` and `shatters_when_thrown` fail the test. Fixed them, saw both elements pass the unit test.

Fixes runtime with ridable element and adds unit test for bespoke elements

---

code/__DEFINES/misc_defines.dm

Fixes https://github.com/ParadiseSS13/Paradise/issues/26118
Fixes an oversight that I forgot to update the full indexing of 48 layers.... I was tired, it's on me, sorry.
My shoes are not made of glue and generally don't have tar in them.
I'm not sending you a picture of a man with no shoes on.
Loaded it in game, took off a pair of shoes, put on a pair of shoes. Tested the blood layering stuff again. All good.
:cl:
fix: Fixed an issue where shoe overlays would not update.
/:cl:

fix: Shoes not updating when removed. 

---

code/modules/mob/living/simple_animal/friendly/diona_nymph.dm
code/modules/mob/living/simple_animal/friendly/nian_caterpillar.dm
code/modules/surgery/robotics.dm

Nian caterpillars are no longer loyal to a sentience potioner on evolving.
Diona nymphs are no longer loyal to a sentience potioiner on evolving.
MMIs, and robobrains, can no longer be stuck inside organic mobs. They can still be stuck inside IRCs and IPCS. And cyborgs.
Fixes #25914
Fixes #17333
You should not be able to mass produce loyal humanoid non golems, by sentience potioning diona nymphs or nian caterpillers, and evolving them.
Doubly so since this gets you usable blood, or gets you workable cultists.
You are no longer able to put mmis, syndicate mmis, or posibrains in the chest.
This was a buggy mess that created a whole host of issues. This also let people abuse syndicate MMIS as comically cheap mindslaves, to take over entire departments. They  still work in IRCS and IPCS just …

Fixes easy slaved non golems. Fixes syndicate MMI abuse

---

code/datums/uplink_items/uplink_traitor.dm
code/game/objects/items/weapons/twohanded.dm

Removes projectile deflection from the titanium push broom
Adds a parry with a 75% uptime
Values directly stolen from #26043 
It's been a very overloaded item for a while, being just an OP mix of carp, CQC and a desword but better as it reflects all projectiles
This way it's strength scales with how good you can parry (or just mash the parry button). The parry can parry all attacks so you can still fight against ranged weapons
Compiled
Tested that I could parry
:cl:
tweak: The titanium push broom now doesn't reflect ranged weapons when wielded
tweak: The titanium push broom's parry is now better
/:cl:

Replaces the projectile deflect from the titanium push broom with a good parry

---

_maps/map_files/RandomRuins/LavaRuins/lavaland_surface_envy.dmm
_maps/map_files/RandomRuins/LavaRuins/lavaland_surface_fountain_hall.dmm
_maps/map_files/RandomRuins/LavaRuins/lavaland_surface_pizzaparty.dmm
_maps/map_files/RandomRuins/LavaRuins/lavaland_surface_sloth.dmm
_maps/map_files/RandomRuins/SpaceRuins/meatpackers.dmm
_maps/map_files/RandomRuins/SpaceRuins/syndicatedruglab.dmm
_maps/map_files/RandomRuins/SpaceRuins/wizardcrash.dmm
code/game/area/areas/ruins/lavaland_areas.dm
code/modules/awaymissions/mission_code/ruins/oldstation.dm

This PR migrates many Lavaland ruins to powered areas, as well as the wizard crash space ruin, and sets the Meatpackers APCs to be active. Fixes #26068.
All of these ruins should be powered, and acted as such, even though they weren't, until #25642. Meatpackers already had a powernet but for some reason its APCs were unlocked and off, which doesn't make any sense considering they should be on for the ship defenses to operate.
Spawned in, visited relevant ruins to ensure they were powered.
:cl:
fix: Several ruins on Lavaland are properly powered again.
fix: The Wizard shuttle crash and Meatpackers space ruins are properly powered.
/:cl:

fix: set area poweredness for many ruins.

---

code/game/machinery/vendors/vending.dm

Fixes #26072
Shoving someone into a vendor now informs people around them who shoved the poor sucker.
Fixes an oversight.
On late arrival station traits, shove spamming is an issue, you can tell who shoves who into a wall but... not into a vendor meaning that the crime is often let go. People scrambling out of the shuttle like that and shoving one another sporadically like maniacs is... not good.
N/A
There was a lot of moth-on-moth violence. I shoved a moth into a vendor! And another! And another!
:cl:
fix: Fixed vendors not announcing who shoved who into them.
/:cl:

Shoving someone into a vendor now informs people around them.

---

code/game/machinery/deployable.dm
code/game/objects/items/sport.dm
code/game/objects/structures/holosigns.dm
code/game/objects/structures/morgue.dm
code/game/objects/structures/railings.dm
code/game/objects/structures/tables_racks.dm
code/modules/fish/fishtank.dm

It is once again possible to throw stuff over tables (And a couple of other things, like fishbowls, railings and sandbags.)
Fixes: #26092
PS: As a more general statement, we should probably take a look at the pass_flags_self, and pass_flags variables. Currently *everything* uses pass_flags, rather than pass_flags_self, even though the latter may be more appropriate in certain circumstances. However, tables and such are the most immediately affected by this, and pose a rather significan issue in-game.
You should be able to throw stuff over tables. And railings. And fishbowls.
C'mon man, your throws can't be THAT weak, can they?
I threw something over a table. And a fishbowl.
But not a fish tank.
:cl:
fix: Things can be thrown over tables again!
/:cl:

[FIX] You can throw stuff over tables again.

---

code/game/objects/items/weapons/lighters.dm

Fixes https://github.com/ParadiseSS13/Paradise/issues/23111
Bugs bad.
Flicked a randomly colored lighter on and off, it stayed the same color.
:cl:
fix: Fixed lighters becoming green if they were not green before.
/:cl:

fix: Cleans up lighter code a tiny bit and fixes colored lighters becoming green

---

code/datums/uplink_items/uplink_general.dm

This PR lowers scope eyes (as "Hardened Kaleido Optics Eyes Autoimplanter") cost in uplink to 10 TC
While the item sounds good, you would actually use it just to check areas for people with thermals or look down the hallway for secuirity. You cant really use it in fight since accuracy at this distance would be really fucked. So, with all that, cost of 20 TC makes it just not worth the cost
Compiled. There is just one number changed.
:cl:
tweak: Hardened Kaleido Optics Eyes Autoimplanter aka scope eyes now cost 10 TC(was 20 TC)
/:cl:

Lowers scope eyes cost

---

_maps/map_files/stations/deltastation.dmm

This PR assigns the correct /area types to Delta solar arrays.
Areas should be correct.
<details><summary>Before</summary>
</details>
<details><summary>After</summary>
</details>
Spawned in, ensured solar array turfs had the proper areas.
NPFC

fix: Correct areas for delta solars.

---

code/modules/mob/living/carbon/human/human_update_icons.dm

Fixes an oversight.
Hands != Feet
N/A
Loaded it, stuck my ungloved hands into a skrell's chest cavity and inserted a nian plushie vv'd to be tiny.
:cl:
fix: Fixed an issue with ungloved hands being the wrong blood color.
/:cl:

fix: Hands should now rely on hand_blood_color instead of feet_blood_color

---

code/modules/research/designs/medical_designs.dm

Corrects the designs name from "Neural Jumperstarter Implant" to the implants name of "Neural Jumpstarter Implant"
Typos bad
The name correctly updated
:cl: EOD501
spellcheck: Corrected the recipe name of Neural Jumpstarter Implants
/:cl:

Fixes a Neural Jumpstarter typo

---

code/modules/mob/living/carbon/human/human_defense.dm

This PR reverses reaction on hitting someone with item with no damage. It was automatically "blocked" which caused afterattack to not work, which made fulton pack useless.
If you hit someone with item and they have say, shielded robe or you would parry in that moment, it will be blocked even if the item has no force. 
Bugs bad. Fixing item_attack logic futher. 
Compiled, tried using fulton pack, tried using other items with /afterattack and not modified /attack proc
I also checked pretty much all the objects in game that have 0 damage and afterattack proc to make sure it works
:cl:
fix: Fulton pack now works again
/:cl:

Fixing fulton pack not working

---

code/game/objects/items/weapons/grenades/flashbang.dm

You can no longer set the fuse timer on flashbangs to one second
This is with 2(?) balance team members pre approval. (im unsure what the second member meant, but they seem fine with it?)
Flashbangs have started to become a quite cheesy method of closing the distance with people who lack one of the two forms of bang(ear) protection, and theres been a rather sharp increase of players treating others like a blob, and throwing upwards of 6 flashbangs on 1s timers, leading to no reaction time on the victim, removing the one second option should hopefully add a little skill requirement to 'insta flashing' as accurately timing 5/3 seconds with adrenaline in your system isn't the easiest thing todo.
not to mention if you lack eye protection the flashbang spam will likely blind you very quickly …

Removes the 1s option from flashbangs

---

code/modules/assembly/mousetrap.dm

Adds item_state, cause icon_state can be changed and inhand icon disapear
Also removed a small ladder into the code
That's a very important fix
Fixes #26175 
https://github.com/ParadiseSS13/Paradise/assets/69762909/9e888a1c-8b7f-4da2-8cd6-93f822b8acdb
:cl:
fix: Mousetrap no longer disappears from your hands if you activate it
/:cl:

Fix: Active mousetrap inhand sprite

---

code/game/machinery/firealarm.dm

Checks for emagged on fire alarms to properly disable them from activating unless pulled manually.
Fixes https://github.com/ParadiseSS13/Paradise/issues/25954
Oversights are bad.
N/A
Loaded it offline, emagged a fire alarm, set off a plasma fire. ooooh ahhh!
:cl:
tweak: Firealarms check if they're emagged to properly disable them from activating through damage or temperature unless pulled manually.
/:cl:

oversight fix: Firealarms will no longer activate via temperature or damage if emagged.

---

code/game/objects/items/weapons/melee/energy_melee_weapons.dm
code/game/objects/items/weapons/whetstone.dm

Makes energy sword sharpening use signals instead of an `istype()` hijack on the whetstone proc
Cleaner code and allows for things like sharpening cutlasses while they're active, and immediate updating of the force
See above
:cl:
fix: Energy weapons can now be sharpened while they are active
fix: Energy weapons now immediately update their force when you sharpen them
/:cl:

Changes energy sword sharpening to use signals

---

code/__DEFINES/cloning_defines.dm
code/game/machinery/clonescanner.dm
code/game/machinery/computer/cloning.dm

Fixes https://github.com/ParadiseSS13/Paradise/issues/25823
This was an oversight from the cloning rework, bugs are bad. Inconsistent cloning isn't intended.
The above image doesn't show the up to date feedback message. It is currently:
"The selected pod is currently cloning someone."
Shot a unathi with a death wand, shoved their writhing corpse into the scanner, the pod itself was already scanning. (VV'd to be such because I am lazy)
> currently_cloning set to 1
:cl:
fix: Fixed a cloning issue where the wrong mind would be transferred into a cloned patient
/:cl:

fix: Cloner Pod should no longer shove the wrong mind into a cloned patient

---

code/modules/mob/living/simple_animal/hostile/syndicate_mobs.dm

Syndicate Backup mobs no longer raise alert
>Syndicate Backup 173 has reported contact with hostile entity - Space Carp. Depot considered lost to hostiles, initiating self-destruct!
Ever since Explorer Redux, space is just full of various mobs, all of which will terrify Syndicate into committing suicide, taking with them any Explorer who didn't paranoidly bolt open a path outside. This behavior doesn't make much sense even against actual players (who on red alert would typically be retreating from the already looted depot), but is outright absurd when space fauna is involved.
Got beat up by Syndicate Operatives and Officers until they raised alert.
Got beat up by Syndicate Backups for a longer time and they did not raise alert.
:cl:
tweak: Depot's Syndicate Backups no longer raise alert. …

Stops Syndicate Backups from making depot Delta

---

code/game/objects/items/weapons/stunbaton.dm

Stunbatons no longer check shields when they successfully harm someone, preventing stunbatons from draining 2 shields, or harmbatoning being blocked by the reactive armor but still stunning half the time anyway.
Should behave like other items, shouldn't bypass reactive armors and stun when being blocked
Stuned and harmbatoned a lot of people, doing the same with reactive armors and shielded modsuit modules, only took 1 layer off, never stuned when blocked by armor, always stunned (off cooldown) when not blocked
:cl:
fix: Stunbaton no longer hits through reactives or hits shields twice.
/:cl:

[s] Stunbaton no longer triggers shields twice

---

code/modules/supply/supply_console.dm

Fixes #25757
- Makes it so that the supply console only updates its static data when emagged, cmagged, or approving a shuttle abstract crate purchase
- Supply console no longer reloads itself when spam approving standard crates
- UI bug, now people can approve crates at their own pace
N/A
- Reproduced bug
Compiled
- Loaded Server
- Ordered 10 regular crates, spam approved through all 10 of them and confirmed no loading issue
- Ordered a shuttle crates and confirmed it still worked
:cl:
fix: Supply Console no longer has Loading Issues when Approving Crates
/:cl:

Fixes Supply Console Loading Issues with Approving Crates

---

code/datums/uplink_items/uplink_general.dm
code/modules/clothing/chameleon.dm

This PR adds nightvision chameleon glasses, similar to nightvision googles but chameleon, to traitor uplink for 5 TC
While we have nightvision module with cost of 5 TC for a modsuit, we have nothing for people who dont wear modsuit. You can buy thermals for 15 TC but like, sometimes you dont have 15 TC and thermal doesnt provide as good nightvision as actual nightvision googles.
Compiled, checked traitor uplink, bought glasses.
:cl:
add: Nightvision Chameleon Glasses is now available in all uplinks with cost of 5 TC. Its same as nightvision googles, but chameleon. Watch your eye damage, agents.
/:cl:

Adds Nightvision Chameleon Glasses

---

code/game/objects/items/weapons/cigs.dm

Makes custom rollies have reagents
These should work
Spawned ambrosius gaia, varedited it to be dry, rolled it and smoked it. Got high.
:cl:
fix: Custom rollies have reagents again
/:cl:

Makes custom rollies have reagents

---

.github/workflows/wiki_label.yml

This creates a new workflow that allows people designated to label a PR with `Requires Wiki Update` without needing to be a member of the repository. This can be done by an authorized user by using `!wiki_label`.
~~Additionally this PR adds @SynthTwo to the list of authorized users for this command.~~
This now uses a repository variable and will need to be setup accordingly.
What is good for the code base is good for the game.
Created a separate fork of our repository.
Created a dummy PR to test the function of the workflow.
Tested new changes made during the course of this PR.
Additional thanks to @SynthTwo for helping to test this.
NPFC

Creates a New Workflow for Adding Wiki Labels  

---

code/modules/hydroponics/gene_modder.dm

The plant DNA manipulator now drops all contents when destroyed/deconstructed rather than deleting them
Fixes #25370
This feature of the disk compartmentalizer was forgotten when it was integrated into the plant DNA manipulator in #25370
Destroyed/deconstructed a plant DNA manipulator and observed that all contents were dropped.
:cl:
fix: Plant DNA manipulator now drops its contents upon destruction like the disk compartmentalizer used to
/:cl:

[FIX]Plant DNA manipulator now drops seed and disks on destruction

---

code/modules/clothing/chameleon.dm

Fixes: #26214
:cl:
fix: Chameleon cap no more invisible
/:cl:

Fix: Invisible chameleon cap

---

code/modules/unit_tests/test_runner.dm

This PR adds a `CHECK_TICK` check between tiles while looping over per-tile map checks in the unit tests. This (seems to) prevent BYOND's infinite loop detector from triggering, which backgrounds the unit tests and may cause them to fail to run before the world shuts down.
Fixes #24893.
Unit tests should run to completion.
Created a pull request on my fork and ran unit tests before and after the change. CI logs seemed to confirm the tests were no longer backgrounded. Compare [before]() and [after]() by searching for "infinite loop".
[before]: https://gist.github.com/warriorstar-orion/68375fb9e28df34da07c5b4cc6037d6c
[after]: https://gist.github.com/warriorstar-orion/806d89866b46f5fbdf456f7891406065
NPFC

fix: Prevent backgrounding of unit tests.

---

code/game/machinery/computer/camera_console.dm

Removes an unneeded qdel call that causes a bunch of runtimes. Fixes #26219
When bloom was added, the way cameras handle overlays was changed too. It used to be that cam_plane_master was a list of the overlay objects. Now, it's just a list of the paths that are used further down the proc. Regular variables runtime when they try to get qdel'd, and since there's nothing special about them anymore we can safely let them get deleted with the camera console.
oh right, runtimes bad
Loaded in, made sure that camera consoles still worked and that the bloom/overlay effects were still visible. Deconstructed the console and made sure there were no runtimes or GC issues

Fixes cameras runtiming on deconstruction

---

code/modules/library/library_computer.dm

- Patches a potential library exploit
- Adds a confirmation prompt before uploading to make sure people know what they're uploading and the consequences of that action
Built and ran locally without errors:
- Wrote a book, binded it, and uploaded it locally
- Checked to ensure it posted to the database correctly
:cl:
tweak: adds a confirmation prompt to book uploading
/:cl:

[s] Adds a TGUI confirmation prompt to book uploader + other security fixes

---

code/modules/crafting/recipes.dm
code/modules/economy/merch_items.dm
code/modules/vehicle/tg_vehicles/scooter.dm

**Pre-Approved: MattTheFicus, Komrad, Dudley**
- Skateboards and Pro Skateboards no longer fit in Bags. Hoverboard can still fit in a bag since its expensive. They can now fit on your back slot.
- Craftable Skateboard completely removed from crafting.
Skateboards are oppressive and frankly needed a Balance pass in hindsight. Security should not be rolling around at mach six arresting people. Speed is, after all, king in SS13.
TBA
Logged in, couldnt equip boards in my bag anymore.
:cl:
tweak: skateboards no longer fit in bags, fit in back slot. Hoverboard unchanged.
del: you can no longer craft the improvised skateboard.
/:cl:

Skateboard Nerfs - The Bigger One

---

code/modules/recycling/sortingmachinery.dm

Fixes #26189. You can now merge wrapping paper instead of wrapping it up.
If you are evil and want to wrap up some wrapping paper for the funnies, you can still do it on harm intent.
Merging the stacks together instead of accidentally wrapping them up is good.
Played with wrapping paper.
Only made packages when I did harm intent.
:cl:
fix: You no longer wrap wrapping paper in wrapping paper unless you want to wrap wrapping paper in wrapping paper.
/:cl:

Wrapping Paper now Requires Harm Intent to Wrap Wrapping Paper

---

code/modules/mod/mod_control.dm

Title 
Doubled toolsounds are used like.. nowhere else that leads me to think its unintended and with stuff like the alien tools, the sound can get very loud and jarring 
screwed and wrenched a modsuit with abductor and power tools, only heard the first click sound.
:cl:
fix: Fixed modsuits playing screwdriver/wrench sounds twice
/:cl:

Fixes the doubled up toolsound on modsuits cover opening/closing and core removal

---

_maps/map_files/RandomRuins/LavaRuins/lavaland_surface_dead_ratvar.dmm

This PR adds no_lava mapping helpers to the clockwork floor turfs and turfs with clockwork cult items (except the tiny replicant alloy shards), and removes all `/obj/structure/lattice/clockwork` and `/obj/structure/lattice/catwalk/clockwork` objects.
Without the no_lava helpers, chasms can rip right through the ruin, going so far as to drop the Ratvar corpse into the chasm. The clockwork lattices and catwalks not only don't instantiate correctly (presumably because they only spawn in space and not on floor turfs) but don't have the proper smoothing sprites even if they were able to spawn.
Spawned hundreds of dead gods with lots of chasms.
Before:
After:
:cl:
fix: Ratvar will no longer fall into chasms.
/:cl:

fix: ratvar ruin fixes

---

code/game/objects/items/weapons/stunbaton.dm
code/modules/power/cell.dm

Fixes a runtime from batons with rigged cells trying to check the charge of the now exploded cell
Also fixes syringes always saying "you inject the solution" even if the syringe is empty, As well as cleaned the code up slightly. i similar enough, lemme know if i should split the fixes though
Runtime bad, cant see any issues with it not checking the charge since cell is being deleted anyway.
Also it saying you injected something when you didn't is bad. also the code was hard to read
Rigged a cell, hit myself. no runtime
tried to inject a cell with an empty syringe, no message
:cl:
fix: Fixed a runtime with batons trying to check charge of a exploded cell
fix: Fixed syringes saying they injected something into a cell when empty
/:cl:

Fixes a baton runtime. And fixes a related bug todo with the runtime

---

code/modules/power/smes.dm

The display charge is now rounded upwards so that all overlays are used correctly.
100-81 -> 80-61 -> 60-41 -> 40-21 -> 20-0 and no overlay
More info from sprite, and less misunderstandings, when UI show you have 40% charge, but overlay is blinking like it low charge
| 100-81 | 80-61 | 60-41 | 40-21 | 20-0 |
| - | - | - | - | - |
| ![image](https://github.com/user-attachments/assets/1b751837-8025-4eb0-b5de-02796c700ebd) | ![image](https://github.com/user-attachments/assets/d997309f-c216-4053-8dd4-efb297a1528a) | ![image](https://github.com/user-attachments/assets/beed34f4-11ff-4612-934f-6030fa0a5adf) | ![image](https://github.com/user-attachments/assets/1589f2c7-2d42-4557-971e-20f7c923114a) | ![dreamseeker_e8JKKgK7qs](https://github.com/user-attachments/assets/7caf1f46-5794-43f7-ac66-4d0e4 …

Tweak: SMES charge overlay is now more accurate

---

_maps/map_files/stations/metastation.dmm

Fixes #26193. This PR removes an errant camera from Expedition on Metastation, moving the actual Expedition camera in its place. This particular prefab seems to have come from Cere; there's no "Research Test Lab North" on Meta.
RDs shouldn't be able to snoop on explorers.
Spawned in, confirmed visibility via AI, confirmed Expedition camera isn't part of RD network.
:cl:
fix: Cerebron: There is no longer a camera in Expedition connected to the Research network.
/:cl:

fix: remove 'research' camera from meta expedition

---

code/game/gamemodes/wizard/artefact.dm
code/modules/antagonists/traitor/datum_mindslave.dm
code/modules/antagonists/traitor/misc_mindslave.dm
code/modules/antagonists/vampire/vamp_thrall.dm

Updates necromantic stone code to fix #11205 
Buffs necromantic stones to let the wizard revive more skeletons past the cap, but with a cooldown
Updated mindslave to support different master hudicons for the wizard
Bugs bad
It was already easy to bypass the necromantic stones skeleton cap, I asked about changing it, and was told it was fine to replace it with this instead.
Tested the code with multiple clients, it worked
:cl: EOD501
fix: Necromantic stones properly mindslave the thrall
tweak: The necromantic stone can thrall more mobs past its cap, but with a cooldown between use
tweak: Mindslaves can support unique maser hud icons
/:cl:

Necromantic Stone Refactor / Buff

---

code/game/objects/items/weapons/mop.dm
code/game/objects/structures/mop_bucket.dm

Makes NODROP mops not get put into mop buckets
Also cleans up the entire proc a bit
Also refactors a proc that went
`mopbucket calls proc on mop which calls proc on mopbucket`
Into something sensible
Resolves #26205
Put a janitorial implant in me
Tried to put the mop in the bucket, did not work
Checked with a normal mop that it could be inserted
Checked that a cyborg couldn't put their mop in a bucket
:cl:
fix: NODROP mops now won't get put in mop buckets
/:cl:

Makes NODROP mops not get stuck in mop buckets

---

_maps/map_files/stations/metastation.dmm

Swaps the short-range fax machine in Meta's HoP office with a long-range fax machine.
Mapping oversight, all other stations have a long-range fax machine in the office.
The mapping icons are the same so there's no point showing a picture.
Spawned in.
Looked at the fax machine, it long range.
Faxed my ass to Central Command.
Got fax.
It contained an ass picture. Fired the BSA at the HOP.
:cl:
tweak: Increases the range of the HoP fax machine.
/:cl:

Meta Station HoP Fax Machine is now Long-Range

---

code/game/objects/effects/spawners/lootdrop.dm

Converts Cybersun trading shuttle Storage bio-chip into it's injector type which is what it was intended originally to be.
Fixes #26271
Players should actually be able to inject the bio-chips they purchase
Compiled, ran on local
- Spawned cybersun loot spawns, succesfully got injectors for minor and major spawns
:cl:
fix: Cybersun trading shuttle Storage bio-chip spawn in their injectors properly now
/:cl:

Fixes Cybersun trading shuttle Storage bio-chip

---

code/_onclick/hud/screen_objects.dm
code/game/objects/items.dm
code/game/objects/items/weapons/storage/storage_base.dm

This PR contains fix/qol improvements to hands that i ported from here:
https://github.com/ss220-space/Paradise/pull/2642
https://github.com/ss220-space/Paradise/pull/2659
1. Currently items in inventory slots for Alt+click and Ctrl+click combinations have the clickable area matching the item sprite. This is inconvenient, because for example, to change the transferrable amount of a beaker in your hand you have to Alt+click directly on the beaker. This PR makes the clickable area of items in the inventory a 32x32 area (mouse_opacity = MOUSE_OPACITY_OPAQUE), making it much easier to click. In the code, this is hovered over when equipping an item (including hands) and removed when dropping an item. Nothing should break.
2. Now, if you have an item in your active hand and hover over an empty …

Fix inventory hands clickable areas & confusing overlay

---

code/datums/components/_component.dm
code/datums/datumvars.dm
code/game/objects/items/weapons/AI_modules.dm

Makes our codebase 1641 ready, which means removing datum accessing like:
```js
var/datum/example
example[name] // Bad
example.name // Good
```
These are stupid to do and I want to try out 1641 because it will most likely fix the radiation overlay bugs
The Cyberiad statue looked fine
See above
NPFC

Makes our codebase 1641 ready

---

code/modules/admin/topic.dm

Adds log messages to rod smites
Resolves #25521
Also makes sure that every smite will very visibly say that it does not have a set log message - if it indeed doesn't have one
You can still set `logmsg = null` if you want your smite to not log for some reason
Logging is good
Rodded a skrell, got the admin logs
NPFC

Adds log messages to rod smites

---

.vscode/launch.json

Adds the ability to run with DreamDaemon instead of DreamSeeker
Allows the localhost to start initializing before the client joins, and keep the localhost open even after closing the client.
I kept accidentally closing the server
Launched with DreamDaemon and it worked

Adds starting localhost with DreamDaemon to VSCode's Run and Debug

---

code/modules/projectiles/firing.dm

Fixes #25043 by assigning projectile starting location on point blank hits, the lack of which would cause a runtime by projectiles like beanbag
Bug fixing good
| Before | After |
| - | - |
| <img src=https://github.com/user-attachments/assets/cd77f508-eca8-42fe-bbf7-f9be61020e04 > | <img src=https://github.com/user-attachments/assets/747fe281-afca-4e38-8db0-ac1e1fcc75de>
:cl:
fix: Beanbag point blank hits not throwing targets backwards has been fixed
/:cl:

Fixes beanbag point blanks not throwing mobs

---

code/game/gamemodes/miniantags/guardian/types/ranged.dm

Ranged Holoparasites in scout form no longer take `blob_act()` damage when flying over blob tiles. This prevents ranged holoparas from instantly dying if they accidently fly over a large amount of blob tiles!
This does not preclude ranged holoparas from damage from the blob, however.
This really is not a fair way for the player to go out, since there is no cooldown on how many times you can be `blob_act()`'d in 1 second, players can lose their entire round by a near unavoidable mistake.
Compiled, ran on local test server.
Spawned Holopara with host, toggled to scout mode, flew over the blob, did not take damage.
Toggled back into regular mode and stood next to blob tile, took regular `blob_act()` damage like normal!
:cl:
fix: Ranged holoparasites no longer die when flying over 1+ blob …

Ranged Holoparasites in Scout Form no longer instantly die when flying over the blob

---

code/game/objects/items/weapons/tanks/watertank.dm
code/modules/mod/modules/modules_engineering.dm

Firefighting tanks on metal foam synthesizer mode now once again generate metal foam, instead of just regular foam.
Fixes: #26161
Metal foam should, well, generate metal.
Use the firefighting tank module in a MODsuit
It generates metal foam
Use the firefighting tank
It generates metal foam
:cl:
fix: (MODsuit) firefighting tank metal foam synthesizer mode now generates metal instead of just foam.
/:cl:

[FIX] Firefighting tank can once again generate metal foam

---

code/modules/mob/living/simple_animal/hostile/syndicate_mobs.dm

Fixes #25947 
Cleans up how syndicate simplemobs handle dropping their corpses
Killing a dangerous mob should give the correct rewards, not sometime give a completely different and random corpse.
Killed a bunch of space syndicate mobs
Killed a bunch of syndicate quartermasters
Killed a bunch of regular syndicate mobs
:cl:
fix: Fixed syndicate mobs not always dropping the correct corpse
/:cl:

Fixes syndicate mobs not always dropping the correct corpse

---

code/game/objects/structures/tables_racks.dm

Stops tableflipping from flipping ghosts
Also changes a `spawn(0)` to an `INVOKE_ASYNC`
Resolves #11945
Tables should not transcend the deadspace-deadtime continuum and flip ghosts
As manually spawning a ghost currently runtimes, I only checked if it still flipped things normally
NPFC

Fixes tableflips flipping ghosts

---

code/game/machinery/doors/door.dm

Doors and windoors now properly block most superconductivity when closed.
I'm guessing the extra (original) copy of this method got accidentally re-introduced in a merge at some point, because I know I'd tested this.
Science no longer develops icicles due to the server coldroom.
Checked superconductivity was correct, saw cold having a hard time escaping the coldroom.
:cl:
fix: Doors and windoors now properly block most heat transfer when closed. The server coldroom will no longer freeze all of Science.
/:cl:

Fix (win)door superconductivity.

---

_maps/map_files/stations/cerestation.dmm
code/modules/mob/living/simple_animal/bot/mulebot.dm

This PR extends the pathfinding range of MULEbots from 250 to 350. This allows them to find all departments on Cerestation. The performance change is indistinguishable. SSpathfinder is very fast.
It also removes a grille and wall that got in the way of proper delivery to Cere science.
MULEbots should be able to reach all expected destinations.
https://github.com/user-attachments/assets/f2354113-4b82-4019-bf08-5fd010a49007
:cl:
fix: Mulebots can now reach all departments on Farragus.
/:cl:

Extend mule pathfinding range for cere and remove some obstacles.

---

code/game/objects/items/devices/transfer_valve.dm

If there isnt an icon state for the tank, itll default to "oxygen"
I would add sprites but I hate sprites and I cant do sprites on my phone, i might get to it eventually
Fixes #12802 
Put a tank in the defines list in the TTV, overlay updated to tanks icon state, put a tank not in the defines list in the TTV, overlay updated to "oxygen" icon state
:cl: EOD501
fix: Fixes invisible TTV tank overlays
/:cl:

Fixes invisible TTV tanks

---

code/game/objects/items/devices/scanners.dm
code/modules/reagents/chemistry/reagents/water.dm

fixes #25493
Adds the blood species data to the output of the scanner and removes the word "blood" from all blood species names where it was present.
It fixes it.
Mixed blood in a bunch of bags and scanned them.
:cl:
fix: Blood species is now presented in the reagent scanner's output.
/:cl:

Shows blood species in reagent scanner

---

code/modules/mob/living/carbon/human/human_update_icons.dm

Re adds the ssd overlay after `regenerate_icon()` if the player is logged out
Fixes #11306 
Rejuvenated an ssd mob and the overlay stayed
:cl: EOD501
fix: SSD overlay persists through rejuvenate
/:cl:

SSD overlay gets re applied to rejuvenated SSD players

---

code/modules/client/client_procs.dm

Fixes https://github.com/ParadiseSS13/Paradise/issues/26328 by adding returns after both reload chat and reload stat panel commands.
Without the return the href proc continues to the next link which would usually be a TM'd PR. Ooops.
Loaded chat and pressed the button.
Didn't explode.
:cl:
fix: Stopped reload chat button from opening TM'd PRs in your browser
/:cl:

Fixes client chat href issue

---

code/modules/mob/living/carbon/human/species/_species.dm
code/modules/mob/living/carbon/human/species/golem.dm
code/modules/mob/living/simple_animal/hostile/mining/hivelord.dm

Cloth Golems can no longer be infested by legions but can still be killed by them like before. 
Due to the way that cloth golems operate, they will reanimated anyways before except now a new legion won't be spawned. This prevents cloth golems from creating legions out of thin air (i.g. no host).
Compiled, Tested on local server
- Standard infesting still works for golems & other carbons
- Cloth golem was killed but not infested
:cl:
fix: New legions are no longer spawned when a cloth golem is killed by legions
/:cl:

Cloth Golems can no longer be infested by Legions

---

code/game/machinery/computer/ai_core.dm

Makes AI Cores update their icon state during all construction steps
Fixes #26221
Players need to visually see progress during deconstruction steps, this fixes that
Compiled, ran on local test server
- Build AI Core from frame
- Deconstructed that Frame completely
- All icon states showed correctly
:cl:
fix: AI Cores now properly update their icon state during all construction steps
/:cl:

AI Cores now properly update their icon state during all construction steps

---

code/game/atoms.dm
code/game/dna/dna_modifier.dm
code/game/machinery/Sleeper.dm
code/game/machinery/adv_med.dm
code/game/machinery/computer/camera_advanced.dm
code/game/machinery/guestpass.dm
code/game/machinery/machinery.dm
code/game/machinery/rechargestation.dm
code/game/objects/objs.dm
code/modules/atmospherics/machinery/components/unary_devices/cryo.dm
code/modules/mob/living/living_life.dm
code/modules/mob/living/silicon/ai/ai_life.dm
code/modules/mob/living/silicon/ai/ai_mob.dm
code/modules/mob/mob_misc_procs.dm
code/modules/paperwork/paper.dm
code/modules/reagents/chemistry/machinery/pandemic.dm

Removes a bunch of useless `set_machine` calls and `updateUsrDialogue` calls, as well as some references that dont need to exist.
Next up is TGUIing the stuff that uses this (abductor consoles among other old things).
This shit needs to fucking BURN IN THE FIRES OF HELL I WILL FORGE WITH MY OWN BARE HANDS.
- Holopads still work as intended
- Advanced camera consoles still work as intended
N/A

The Cooking Continuation

---

code/game/objects/items/weapons/storage/briefcase.dm
code/modules/projectiles/firing.dm

Fixes https://github.com/ParadiseSS13/Paradise/issues/26308
Allows guns inside the falsebottom briefcase to be fired, as intended.
TO NOTE:
Having a gun inside the falsebottom affects the click melee CD, allowing for some sick combinations. Only while it has ammo though. Once the gun inside is empty... it goes back to regular melee CD. I think this is neat.
Falsebottom is 10TC and besides hiding a high-risk item or contraband.... it's useless. It is also intended to shoot the weapon inside
> A modified briefcase capable of **storing and firing a gun** under a false bottom. Use a screwdriver to pry away the false bottom and make modifications. Distinguishable upon close examination due to the added weight.
Local server.
Autotot'd, bought a briefcase, a stetty, and a suppressor. Shot …

Falsebottom Briefcase now shoots the weapon within the false bottom of the briefcase

---

code/game/objects/structures/crates_lockers/crates.dm

Makes it so that crates cannot suck in items that a mob is currently buckled to
If you somehow manage to be sitting on a non-anchored item on the same tile as a crate, you can close the chair into the crate without unbuckling yourself. It's really hard to actually exploit this in some meaningful way but it does a weird teleportation thing over 1-2 tiles (you're still attached to the chair) if you move stuff around in a certain fashion.
Compiled, ran on local test server
- Closed chair into crate normally, works
- Buckled myself to chair and attempted to close it in, did nothing
- ???
- Profit
Not really any actual player facing changes, not ones they'd even care about anyway.

You can no longer put items in crates when a mob is buckled to them

---

_maps/map_files/stations/cerestation.dmm

Adds a T-manifold pipe to the medbay so it's connected to the distro.
Disconnected vents are not good and air needs to be easily accessible anywhere. This was probably just overlooked when the map was created.
Loaded up Farragus and saw that the pipe manifold was where it should be.
:cl:
add: T-manifold pipe to Farrgus' medbay.
/:cl:

Connects a vent in Medbay to the distro on Farragus

---

code/game/machinery/doors/door.dm

#26322 accidentally removed the only remaining definition of this proc, causing ALL doors to not block heat. This re-adds the proc and fixes that.
Fixes #26350
Doors should mostly block heat transfer. Heatproof doors should fully block it.
Checked that a closed door had lowered superconductivity again.
:cl:
fix: Fixed a merge error that made ALL doors and windoors not block heat, even the heatproof ones on the SM.
/:cl:

Fix door/windoor superconductivity, again.

---

code/modules/antagonists/zombie/zombie_spells.dm

Changes the description of the zombie claws to not use "brain_holder". As well as makes it flow a little better as replacing it with just skull or head made it look a little weird.
i assume when this was ported or added, brain_holder was originally meant to be closed in square brackets to be easily mass changed.
Compiled, spawned zombie claws, checked the description
:cl:
tweak: Tweaked the description of zombie claws to flow a little better as it used to say "brain_holders"
/:cl:

Fixes zombie claws description mentioning "brain_holders"

---

_maps/map_files/stations/cerestation.dmm

This PR fixes the access helpers on the security room of Cere departures to match other stations. It also replaces a plating tile with a floor tile under one of the airlocks.
This allows all people with the right access (i.e. all of Command) to access the security room as expected.
Spawned in, changed job outfit to each Command member in turn, tested airlocks.
:cl:
fix: Farragus: Command should now be able to access the departures security room.
fix: Farragus: A plating tile under the departures security room airlock is now a proper floor.
/:cl:

fix: cere departures sec room access/floor plating

---

_maps/map_files/stations/cerestation.dmm

Fixes some decals being miss aligned on farragus below bridge, as they were aligned to a door that was moved at some point
closes #26253
decals were misaligned, making faragus completely unplayable.
this'll hopefully make it a liked map
compiled into faragus, looked at tiles
:cl:
fix: Fixed a few misaligned tile decals on faragus
/:cl:

Fixes a few tiles that were misaligned decal wise on farragus

---

code/game/objects/items/weapons/stunbaton.dm

Stunbatons no longer check shields when they successfully harm someone, preventing stunbatons from draining 2 shields, or harmbatoning being blocked by the reactive armor but still stunning half the time anyway. This is a remake of #26197 , with the old attack chain back, now using !isnull(.)
Should behave like other items, shouldn't bypass reactive armors and stun when being blocked
Stuned and harmbatoned a lot of people, doing the same with reactive armors and shielded modsuit modules, only took 1 layer off, never stuned when blocked by armor, always stunned (off cooldown) when not blocked
:cl:
fix: Stunbaton no longer hits through reactives or hits shields twice.
/:cl:

[s] fixes that one baton bug again

---

code/game/atoms_movable.dm
code/game/machinery/vendors/vending.dm

See title
Resolves #26301
Mobs that are supposed to go through walls shouldn't be able to be tipped onto
Got crushed as a human, did not get crushed as a revenant in ghostmode.
Went out of ghostmode, got tipped and instantly killed
:cl:
fix: Blood/Shadow/Ghostcrawling mobs now don't get tipped onto by vendors
/:cl:

Makes incorporeal moving mobs immune to tipping

---

code/game/gamemodes/miniantags/tourist/tourist_arrivals.dm

Fixes a few issues related to the tourist midround, such as:
- Tourists not being added to the manifest;
- Antag roll didn't account for players preferences;
- Players without the hour requirement were able to roll traitor.
Small fixes overall, ensuring that the player preference is taken into consideration. Should be enough to avoid future issues related to the midround.
Logged in to testing, joined as tourist, checked if I was added to the manifest, turned on traitor preference, set the chance of rolling tot to 100, and tried rolling again, got traitor tourist
:cl:
tweak: Tourist event now takes preferences into consideration when selecting traitors
fix: Tourists are now properly added to the manifest
fix: Player hours are now properly taken into consideration by the tourist event
/:cl:

[FIX] Tourist Midround fixes

---

code/game/gamemodes/miniantags/abduction/abduction_gear.dm
code/game/objects/structures/table_frames.dm

Makes table construction more generic
Removes the ability to build multiple tables on a single tile
Fixes #12957 
Tested many combinations of material and table frames, and tried to build multiple tables on one tile
:cl: EOD501
fix: Fixes being able to stack multiple tables on one tile
/:cl:

Minor changes to table frames

---

code/game/objects/effects/effect_system/effects_chem_smoke.dm

Adjusts the tweaks made in #25801 to chemical smoke, moving it from process to fastprocess, and fixing it's visuals.
Smoke should actually show up, compared to currently as this:  https://imgur.com/a/ufYbCFy
Fixed: https://imgur.com/a/OhXuMAP
Through tear gas, looked right.
Got gassed by it.
Timed it to ensure it lasted the right time.
walked through smoke after 10 seconds, not hit.
Walked through smoke after 8 seconds, hit.
:cl:
fix: Chemical smoke should look normal again, and produce over 1600+ particles again.
/:cl:

Updates chem smoke to work visually again

---

code/modules/mod/mod_core.dm
code/modules/power/cell.dm

Fixes #26341
makes power cells set charge to zero after exploding to prevent repeat explosions in the event of qdel failure.
Makes modsuit power cells null out of the modsuit when exploding.
bugs are bad, infinite explosions are bad
Insert rigged cell.
Exploded once, cell was removed from modsuit properly.
:cl:
fix: Rigged power cells should perform better in modsuits.
/:cl:

fix rigged powercell for modsuits

---

code/modules/power/engines/singularity/emitter.dm

Makes emitters lockable again.
It has been accidentally broken a week ago with #26257, probably a typo.
I believe.
:cl: Maxiemar
fix: Emitters can be locked with ID again.
/:cl:

Bring emitter locking back

---

code/modules/mob/living/simple_animal/hostile/syndicate_mobs.dm

When making #26134 I did not consider the depot mob agents who had a guaranteed salvage spawn. This made it so one mob dropping two salvage was possible.
Mobs shouldn't drop two salvage
Killed every single syndicate simplemobs. Multiple time. Made sure they only dropped 1 salvage at most.
:cl:
fix: Depot Agents no longer have a chance of dropping 2 syndicate intel salvages
/:cl:

Prevents depot mob from dropping two salvage

---

code/datums/status_effects/debuffs.dm

…aling.
Fixes #26324
Uses human scoped damage adjust procs when healing a vampire via sleeping in a coffin.
Vampires heal properly now
-Got robotic leg, became vampire, damaged myself in various ways, went to sleep. 
-Damage was updates and the robotic limb did not heal
:cl:
fix: Coffing healing updates vampire health
/:cl:

Coffin healing now updates vampire's overall health

---

_maps/map_files/stations/deltastation.dmm

This PR replaces a wall that was occupying the same tile as a vendor with a floor on Delta.
Mapping error.
Before:
After:
:cl:
fix: Kerberos: A wall underneath a vendor in the primary hall has been fixed.
/:cl:

fix: Remove wall under vendor on Delta.

---

_maps/map_files/stations/boxstation.dmm
_maps/map_files/stations/cerestation.dmm
_maps/map_files/stations/deltastation.dmm
_maps/map_files/stations/metastation.dmm
code/modules/recycling/disposal.dm
tools/maplint/lints/sort_junction_names.yml

This PR updates disposals junctions to update their names on Initialize, which uses the `TAGGERLOCATIONS` list to include the correct direction in the name. This would normally happen if their destinations were changed with a tagger (did you know you could do that?) but not on Initialize.
It then removes these varedits from the station maps, and adds a maplint to prohibit their inclusion.
Less varedits are good, this ensures appropriate naming consistency.
Samples of junctions autonamed on Initialize and their `sort_type_txt`:
:cl:
fix: Disposal sort junction names are now standardized and correctly refer to destinations as displayed on the tagger.
/:cl:

fix: Autoapply disposal sort junction names.

---

code/datums/uplink_items/uplink_general.dm
code/datums/uplink_items/uplink_nuclear.dm
code/datums/uplink_items/uplink_traitor.dm

Makes sure hijack items are seen again by normal traitors. These uplink items are still unable to be bought.
Hijack only items are now undiscountable by default. This does not change any hijack only items as those were already setting `can_discount` to `FALSE`
Regression from #25915 
See above
:cl:
fix: Normal traitors can see hijack only items in the uplink again. They still can't buy them.
/:cl:

Adds hijack items back to the uplink for normal traitors

---

code/game/objects/items/weapons/stock_parts.dm

https://github.com/ParadiseSS13/Paradise/pull/26257 had a indentation error that caused the brped to play its beam effect on all `obj/machinery/...` sub types rather than just ones with stock parts, mainly vents. this pr fixes this.
Bug fix, while harmless it was a little strange
compiled, tried to "upgrade" various atmos devices, couldn't. tried to upgrade a machine with stock parts, worked
:cl:
fix: Fixed B-RPED playing its beam effect on all machinery 
/:cl:

Fixes the B-RPED trying to upgrade machinery that dont have stock parts

---

code/__HELPERS/paths/jps.dm

Caller is a protected/reserved var in 516, but we use it in JPS! This fixes that.
```
- caller and callee vars
- The current proc has caller and callee vars that return a reference to
the running caller and to the running proc itself, respectively. The
returned var is of internal type /callee.
- /callee has vars src, usr, args, file, line, caller, and all vars that
apply to proc prototypes (name, type, desc, category, invisibility).	 
```
516 should compile.
Watched the mulebot take a (non optional) path to a department

516 compat: Replace `caller` with `requester`

---

_maps/map_files/stations/deltastation.dmm

This PR moves a pixel-pushed windoor to its actual tile and ensures its access and name mapping helpers are properly applied.
I was going to make a linter for this but windoors are pixel pushed around in some places for appearance's sake e.g. to line up with the fences in the wrestling ring on Cere.
Security checkpoint should not be all-access.
Spawned in, attempted to open door as assistant and security officer.
:cl:
fix: Kerberos: Security Arrivals Checkpoint's windoor now has the correct access.
/:cl:

Delta: Fix arrivals checkpoint access.

---

code/modules/mining/lavaland/loot/colossus_loot.dm

Converts \ref[src] to UID() in the enter link.
Makes it not runtime
Clicked it and it didn't runtime.

Fixes runtime in anomalous crystal ghost notification

---

_maps/map_files/RandomRuins/LavaRuins/chasm_bridges/lavaland_bridge_horizontal_5.dmm
_maps/map_files/RandomRuins/LavaRuins/chasm_bridges/lavaland_bridge_vertical_5.dmm
_maps/map_files/RandomRuins/SpaceRuins/listeningpost.dmm
_maps/map_files/RandomRuins/SpaceRuins/rocky_motel.dmm
_maps/map_files/RandomRuins/SpaceRuins/ussp.dmm
_maps/map_files/RandomRuins/SpaceRuins/wizardcrash.dmm
_maps/map_files/generic/centcomm.dmm
_maps/map_files/stations/boxstation.dmm
_maps/map_files/stations/cerestation.dmm
_maps/map_files/stations/deltastation.dmm
_maps/map_files/stations/metastation.dmm
code/game/turfs/simulated/floor/fancy_floor.dm
tools/UpdatePaths/Scripts/26395_broken_floor_converter.txt

Removes all broken states for wooden floors on maps, replace it with damageturf landmark
Less unnecessary code on maps
Every round, random looking broken floors (No one will notice :c)
Possibility to make grayscale wood floors in the future
Look's fine
NPFC

Remove icon_stated broken wood floors

---

code/game/machinery/clonescanner.dm

fixes:  #26364
makes cloning scanner deconstructable
bugfix good
decon'd some scanners
:cl:
fix: now able to decon clone scanner
/:cl:

makes cloning scanner deconstructable

---

code/__HELPERS/trait_helpers.dm
code/game/objects/items/robot/cyborg_gripper.dm
code/modules/surgery/abstract_steps.dm
code/modules/surgery/surgery.dm

fixes  #24594
Adds a missing check for grippers when attempting surgery steps with more than one option.
fixes stuff
Spawned human, dragged it over a bunch of shrapnel and removed them via surgery as a medborg.
Implanted an IV bag in the human. Then and pulled it out as a borg.
:cl:
fix: Medical grabber now works in surgery
/:cl:

Fixes medical grippers not being usable in surgery

---

code/modules/power/engines/singularity/emitter.dm
code/modules/power/engines/supermatter/supermatter.dm

Makes emitter beams from stationary emitters not add an investigate log.
Dear fucking lord the investigate log gets spammed you genuinely can't get any useful data out of it at a glance
This is after running the SM with 3 emitters for 5 minutes
See above
:cl:
fix: [ADMIN] The supermatter investigate log is no longer spammed by emitter beams
/:cl:

Makes emitter hits that didn't turn on the SM not get logged by investigate

---

code/game/objects/items/weapons/mop.dm

Fixes dry/halfdry mops not inserting properly into the janicart
Resolves #26426
I compiled it, the issue was really that the janicart didn't properly get the inserted mop set
:cl:
fix: Dry mops can be put in janicarts again
/:cl:

Makes dry mops insert properly into the janicart

---

code/modules/mob/living/carbon/carbon_procs.dm

See title. Moves the if condition around so it will short circuit if eyes are null.
Runtime bad.
Flashed myself. Blinded myself. Stabbed my eyes with a screwdriver and then flashed and blinded myself.

Fixes flash check runtime when flashee does not have eyes

---

code/__DEFINES/misc_defines.dm
code/controllers/subsystem/SSticker.dm
code/game/gamemodes/nuclear/nuclearbomb.dm
code/modules/admin/misc_admin_procs.dm

This PR changes how biohazard victorys and defeats are tallied in SSblackbox.
The previous system suffered from some problems:
- Key names were truncated and nonconformant: with very few exceptions, the key name for feedback is a short, lowercase_underscore value. These key names were short phrases that didn't even fit within the key_name's column length, so "Xeno survives to normal round end" would be missing a "d", "Biohazard survives to normal round end" would be "Biohazard survives to normal rou", etc.
- They were redundant: They described the round end type ("Blob survives to normal round end", "Xeno nuclear victories") even though how the round ended is already available in the Round model, under `end_state`. As well, the row e.g. "Xeno nuclear victories" would include a nested …

refactor: Streamline biohazard blackbox recording.

---

code/modules/buildmode/submodes/advanced.dm
code/modules/buildmode/submodes/basic.dm

Fixes a to_chat runtime when clicking on the buildmode help button
Having less runtimes is better than having more runtimes
Clicked the button in both advanced and basic build mode, no runtime
<hr>
<hr>
NPFC

Fixes a runtime with buildmode

---

code/modules/clothing/masks/gasmask.dm

Remove armor value 0-0-0-0-0-0 in plague doctor mask because gas mask already have 0 protection from any source. Code cleaning
yes
1 line PR lets goo
<hr>
<hr>

FIX: Remove armor value 0-0-0-0-0-0 in plague doctor mask

---

code/game/dna/dna_modifier.dm

Fixes update_icon_state() proc of the DNA modifier.
Bugfix is always good
Before:
After:
Spawned DNA modifier.
Used screwdriver on it.
Put human inside.
Saw the right sprite.
:cl:
fix: DNA modifier now uses right sprites.
/:cl:

Fix DNA modifier update_icon_state() proc

---

code/game/gamemodes/objective.dm

Fixes a bad pass of arguments causing traitor-chan (and trifecta) to runtime whenever escape with identity was rolled. Might also fix escape with identity not rerolling properly.
Painful runtimes for every roundtype with traitors
See above
<hr>
<hr>
NPFC - I'm not sure if this fixes the objective reroll so we'll see

Fixes traitor-chan runtiming on roundstart

---

code/game/turfs/simulated/river.dm

This PR makes a tiny change to the RNG probabilities of the Lavaland river procgen. This shuffles about the RNG during unit tests to prevent a runtime, while having effectively no perceptible effect on in-game results.
Me not getting around to fixing the procgen runtime means it's blocking a PR that is otherwise fine but failing CI because of this (https://github.com/ParadiseSS13/Paradise/pull/26067).
Ran CI on top of failing PR.
<hr>
<hr>
I am dying to write something here like "tweak: the probability of the Lavaland lava river generator continuing to make detours while generating tiles towards its destination has been reduced from 80 to 79 percent" but there is no way anyone will notice or care.

Fix CI failures by shuffling RNG in Lavaland procgen

---

code/game/gamemodes/miniantags/pulsedemon/pulsedemon_abilities.dm

Fixes a pulse demon bug by adding a safety limit of 15 tiles
lol
used the ability normaly and through machines, worked fine, worked fine very short distances through camera consoles, attempting to travel greater than 15 tiles is blocked.
<hr>
<hr>
:cl:
fix: Pulse demons have a safety limit on their cable hop ability
/:cl:

Fixes a pulse demon bug

---

code/modules/projectiles/projectile/beams.dm

This changes proto pulse slugs to call `ex_act(3)` (damaging them) on rwalls instead of `ex_act(2)` that can delete them immediately with 50% chance.
Here it is in action and here is the parent (the dsquad pulse) not affected by it:
https://github.com/user-attachments/assets/992bbdf8-9362-4692-afc5-f792acc1897a
This is no longer possible:
https://github.com/user-attachments/assets/83255766-f1f6-4035-8744-6d6aaab86310
It was/is being discussed in this [Discord thread](https://discord.com/channels/145533722026967040/1271439593161621598/1271439593161621598).
See video above.
~~It compiled~~ I made the video above.
<hr>
:cl:
tweak: Proto pulse slugs can no longer destroy reinforced walls with a 50% chance. Instead, they deal damage to them. The deathsquad pulse slugs are not affected by this …

Proto pulse slugs no longer immediately destroy reinforced walls

---

code/game/objects/items/stacks/stack.dm

Fixes a runtime when any stack is being `attackby`'d, most notably ores
I love 500+ runtimes whenever two types of jobs are played
<hr>
<hr>
NPFC

Fixes ores runtiming when being picked up

---

code/game/objects/items/stacks/stack.dm
code/game/objects/items/stacks/stack_recipe.dm

A few things have been done:
1. Returned code that I foolishly deleted and didn't notice
2. Stacks now merge properly (Also stupid mistake, sorry)
3. Fixed windows that were crafted without overlay, just added `update_icon(UPDATE_OVERLAYS)` for crafted items.
4. Renamed 1 letter variables into stack_recipe datum
Fixing my mistakes and little improves code readability
Fixes #26482
Nothing
https://github.com/user-attachments/assets/728d1817-65b3-4470-8e16-58790e9d2c58
<hr>
<hr>
:cl:
fix: Stacks now merge like they're supposed to
fix: Crafted items are trying to fit in your hands again
fix: Handmake windows now have overlays
/:cl:

Fix stack merge & return lost code

---

code/game/machinery/machinery.dm
code/modules/power/lights.dm
code/modules/power/powernets/README.md
code/modules/power/powernets/local_powernet.dm
code/modules/recycling/disposal.dm

Fixes several issues with negative power & incorrect power readouts on APCs
Namely Fixes #20980
This PR implements much safer procs & variables for the local powernet static/passive power systems. Lights were a flagrant example of unsafe implementation of this system which was resulting in wild numbers that should not be possible and even negative readout. 
Furthermore, passive power tracking in local powernet is removed, instead we just manually readout from each power channel and aggregate the consumption. This is a lot safer and no longer prone to bad tracking.
Finally, machines now have a `power_initialized` variable tacked on to them which tracks whether or not we've initialized power on this machine yet. This locks out consuming power on a machine until we properly set the static …

Makes Passive Power Consumption Safer and Fixes Negative Power Issues on APCs

---

code/game/gamemodes/cult/runes.dm

See title. This will shortcircuit and continue before the HAS_TRAIT check can runtime as well. Observers having valid clients but a null mind is really funky and should probably be investigated further.
Fixes edge case runtime.
I can't test this locally (or reproduce the original issue), but it compiles. 
<hr>
<hr>

Stops runtime in cult spirit realm rune when observer doesn't have a mind

---

code/game/machinery/airlock_control/airlock_button.dm

Makes it so that airlock access buttons have a properly set power use state and power channel.
Airlock access buttons are machines and should consume power properly like everything else. This fixes that.
Even though they're not set to consume power atm, later they likely will be and this patches that issue before it ever becomes a problem.
cleaning up code in preparation to revive #21250
<details>
Before
After
</details>
Checked Airlock Access Button power state vars before and after, fixed state confirmed in above screenshots
<hr>
<hr>
:cl:
fix: Airlock Access Buttons consume power properly again
/:cl:

Airlock Access Buttons will now correctly consume power on powernets

---

code/game/objects/items/stacks/stack.dm

Another stack fix thanks to my stupidity.
I don't see what the point of this is anymore if it's the third time in a row I've missed a bug, but yeah
Pick's up some stack's, try merge unmergable stacks, picked up some ore with ore bag, dig some ore and pick it up without clicking and trying to merge steel with ore
<hr>
<hr>
:cl:
fix: You can pick up ore with ore bag again
/:cl:

Fix ore picking with bag

---

code/game/objects/items/weapons/storage/boxes.dm
code/modules/supply/supply_packs/pack_emergency.dm

Adds three new crates full of temporary lights for all your aesthetic and emergency needs.
Emergency Glowstick Crate: 75 cheap, shitty glowsticks, the same as what you find in a normal emergency box. Useful for equipping a horde of tiders. 100 credits.
Premium Glowstick Crate: 20 military glowsticks that last a whole lot longer than the emergency ones, and come in a nice green color. 200 credits.
Emergency Flare Crate: 15 magnesium signal flares, they don't last as long as the premium glowsticks but produce a very aesthetic red light. 150 credits.
Having other sources of light beyond just flashlights is neat. The glowsticks and signal flares are also incredibly atmospheric, and barely used at all as of now. Plus, large boxes.
- Loaded in.
- Bought crates.
- Opened crates.
- Opened boxes …

Adds 3 new light crates

---

code/modules/paperwork/desk_bell.dm

Fixes a bug where a desk bell with a receiving signaler and another receiving signaler ended up in an infinite loop.
Fixes door bells not unregistering (code) signal handlers for removed (item) signalers.
Probably fixes #25844
Less bugs are good
Attached receiving signaler to bell. Pinged with receiving signaler. Only dinged once and did not runtime. (It did runtime previously because recursion limit was reached.) Tried also with only one of the signalers on receive.
Removed the signaler and attached the other one. No runtime. (Previously caused runtime for attaching a duplicate signal handler without override=TRUE because old one wasn't removed.)
:cl:
fix: Door bells with signalers no longer cause infinite dinging loops.
fix: Door bells no longer have a bluespace connection to removed …

Fix Desk Bell Bugs

---

code/game/gamemodes/objective.dm

Due to an oversight, escape with identity objectives did not properly update their target mind when their linked assassinate objective rerolled. This PR makes the escape with identity objective reassign their target mind and then update its explanation text when it receives `COMSIG_OBJECTIVE_TARGET_FOUND` from the assassinate objective.
This bug caused a lot of annoying work for admins.
Tested with three clients on the same local server.
Changeling is assigned to client 1 and receives an assassinate and escape with identity against client 2. Client 2's character then cryo's and both the assassinate and escape with identity properly reroll to client 3 (Chip Griffith). I VV inspected both the assassinate and escape objectives to make sure everything was set correctly.
Client 3, the last …

Fixes Changeling escape with identity objective not rerolling after target cryos

---

code/controllers/subsystem/processing/SSstation.dm

This PR adds station traits rolled each round to feedback.
If and when station traits have effects on other things in the feedback DB, it's important to know when that happens.
Added several traits to `data/next_traits.txt`, started and ended round, verified results in DB.
<hr>
<hr>
NPFC

blackbox: Add station traits.

---

code/modules/mob/living/carbon/alien/special/facehugger.dm
code/modules/mob/living/carbon/carbon_procs.dm

Fixes a bug introduced by a previous PR which added the blind trait to `update_tint()`
https://github.com/ParadiseSS13/Paradise/pull/26338
Being permanently blind / being forced to relog after tint updates is not fun nor good.
Threw a face hugger at a nian, took over said nian and removed the face hugger, was able to see.
Blindfolded a nian as a different nian, took over the blinded nian and removed the blindfold, was able to see.
Blindfolded a nian as a different nian, removed the blindfold from the nian, took over the previously blinded nian, was able to see.
<hr>
- [X ] I confirm that I either do not require [pre-approval](https://github.com/ParadiseSS13/Paradise/blob/feature_freeze/CODE_OF_CONDUCT.md#currently-changes-to-the-following-types-of-content-reuires-pre-approval) for this …

General fix to update tint applying/removing blindness, tweak to facehuggers.

---

code/game/area/areas/ruins/blackmarketpackers.dm
code/game/area/areas/ruins/space_areas.dm
code/game/area/ss13_areas/engineering_areas.dm

This PR:
- Prefixes every casino ruin `/area` name with "Dorian Casino"
- Prefixes every onehalf ruin `/area` name with "DK Excavator 453"
- Prefixes every meatpackers ruin `/area` name with "BMP"
- Prefixes one of the ussp derelict ruin `/areas` with "Derelict"
- Fixes a capitalization error with the "AI Minisat Transit Tube" area
By giving these areas consistent names prefixed with their ruin name, the "Jump to Area" UI is much more useful when trying to quickly jump to station areas. The AI Minisat name is now properly displayed.
Spawned many ruins with increased budget over multiple rounds and inspected Jump to Area UI.
<hr>
<hr>
:cl:
fix: The names of ruin areas in the Jump To Area menu are more consistent and less difficult to confuse with station areas.
/:cl:

fix: Make ruin area names more consistent.

---

.github/PULL_REQUEST_TEMPLATE.md
CODE_OF_CONDUCT.md

- Add an invisible anchor serving as a fixed link for the types of changes that need pre-approval link.
- Updates the PR template to point at the anchor, and remove comment containing a duplicate link.
- Updates the link to point to the Code of Conduct of the repository where the PR was created, rather than ParadiseSS13's repository
The link in the current PR template is broken, and can easily be broken because it relies on automatically generated links.
clicked on link and it worked
<hr>
<hr>

Fix PR template approval link

---

code/controllers/subsystem/SSticker.dm
code/game/objects/explosion.dm
code/game/objects/items/weapons/storage/backpack.dm
code/modules/admin/misc_admin_procs.dm
code/modules/admin/topic.dm

Using explosives at end round grief now gibs the user.
If there is no user it just backfires and does nothing. Admins are immune to this if they need to bomb CC for whatever reason.
Gibbing the entire shuttle at EORG is boring.
Threw a grenade at round end
<hr>
<hr>
This is intentionally vague just to see who gets caught out.
tweak: Tweaked explosive behaviour during end of round grief.
/:cl:

Using explosives at end round now gibs you

---

code/modules/mob/living/simple_animal/friendly/mouse.dm
code/modules/mob/living/simple_animal/simple_animal.dm

Stops mice from eating cables during unit tests
Resolves #25588
It's hilariously funny but also quite annoying 
It compiled, latest commit should force mice to eat cables on Meta
Meta:
<hr>
<hr>
NPFC

Stops mice from eating cables during CI

---

code/game/objects/items/weapons/storage/belt.dm

Changed icon_state for bandolier to show the sprite in Stack Craft
All items have image in UI
Made sure there were no missing sprites.
<hr>
<hr>
:cl:
fix: Bandolier now have sprite in stack craft ui
/:cl:

Fix missing icon for Stack Craft

---

code/modules/recycling/disposal.dm

Updates Disposals power changes to only change it's power state when absolutely neccesary. Instead of changing every `process()` cycle, the disposal chute only changes power states when it is flushed or broken.
Currently, disposal chutes update their power state to `NO_POWER_USE` at the beginning of `process()` and then assigns it to `IDLE_POWER_USE` or `ACTIVE_POWER_USE` later in the proc. This doesn't seem like a big deal until you do the math.
65+ Disposals Chutes on Box and each time the state is changed, 4 separate procs are called in the chain. Since the state is currently changed twice every process() cycle and the disposal chute processes 30 times a minute each, it adds up over a 2 hour round
**Before Change:** 65 chutes * 8 Proc Calls a Process() * 30 Proceses a Minute * 120 …

Cleans up disposal chute power state changes to reduce the number of proc calls it makes throughout the round

---

code/game/machinery/doors/airlock_types.dm

The arguments for throw_at were adjusted and this use case was missed. Airlocks no longer pass themselves in as mob/user.
Oversight.
<hr>
<hr>
:cl: Chuga
fix: Cult airlocks properly throw people again
/:cl:

Fixes cult airlock runtime when throwing a mob

---

.github/PULL_REQUEST_TEMPLATE.md
CODE_OF_CONDUCT.md

Fixes the link to the pre-approval requirements.
Makes the requirement list stand out more with an important dialog.
Our links need to work, they were broken in https://github.com/ParadiseSS13/Paradise/pull/26516
Clicked the below link, looked at the text
<hr>
<hr>

Fix the fix to the PR template, emphasise the pre-approval list

---

code/modules/paperwork/paperbin.dm

1. Fixes bug 
2. Replaces old alert with a modern looking one
Fixes #26450
Replaces old alert() with tgui_alert()
Nothing
https://github.com/user-attachments/assets/da8d6a2a-3c3c-4583-81f2-c7638267dc94
<hr>
<hr>
:cl:
fix: Nanotrasen Paperbin now does not let you take paper from it if you are too far away
/:cl:

Fixes Nanotrasen paper bin + now its tgui_alert instead of alert

---

code/game/gamemodes/miniantags/guardian/host_actions.dm

Changes a single word of code so that the holoparasite communicate, recall and reset icons show correctly for the host.
Fixes: https://github.com/ParadiseSS13/Paradise/issues/26198
Actions buttons should be more obvious in what they do
Testing performed by Burza under identical code changes, above image as proof.
I could not test it myself as I have not set up a database to allow me to roll for antag/holoparasite as a ghost in private instances.
<hr>
<hr>
:cl:
fix: Holoparasite hosts can now visually tell the difference between action buttons
/:cl:

Holoparasite host action icon fix

---

_maps/map_files/stations/boxstation.dmm
_maps/map_files/stations/deltastation.dmm
_maps/map_files/stations/metastation.dmm
tools/maplint/lints/disposal_varedits.yml

This PR runs the pre-existing UpdatePaths from #24249 on all station maps, and adds a maplint preventing further varedits to disposals pipes icon states.
I have no idea why these weren't caught as part of #24249; maybe they were reverted accidentally, but the scripts itself seems exhaustive as maplint doesn't complain after running it again.
These were meant to have been fixed in March.
<details>
<summary>Big Station Images</summary>
</details>
Ran maplint, visual inspection, filtered views of SDMM to ensure that changes didn't cause any disconnected pipes or networks.
<hr>
<hr>
NPFC

fix: correct iconstate varedited disposals and forbid their use.

---

code/game/objects/items/weapons/storage/surgical_tray.dm

@lewcc made the surgical drape useful in #25686 (bless) but the surgical tray cannot hold this item. This PR adds the surgical drape to the accepted types of the surgical tray.
Surgical drapes are a part of surgery, they should be able to be inserted into their dedicated container.
https://github.com/user-attachments/assets/2b38a6b7-2a28-40ee-b470-0bc2af73aa28
Video above
<hr>
<hr>
:cl:
tweak: Surgical trays can now hold surgical drapes.
/:cl:

Makes surgical trays able to hold surgical drapes

---

code/game/objects/items/flag.dm

Updates existing lore for department and national flags. Doesn't touch species flags yet.
Old national flag lore was often poorly written or outright incorrect.
Old department flag lore didn't exist.
Remedying both of these issues is good, in my opinion.
- loaded in
- spawned flags
- observed flags
- lore has changed
<hr>
<hr>
:cl:
tweak: Changed flag descriptions
/:cl:

Updates some flag lore

---

code/modules/projectiles/guns/medbeam.dm

Allows you to feel how hot the damaged medbeam is so you can better control how hot its getting, as well as makes it directly deal fire damage to you if it over heats as a tradeoff.
As well as makes it loudly snap on overheat.
Also slightly changes the description to better explain how it works. 
Currently the damaged medbeam only sets you on fire, but if you're.. in space, like a explorer usually would be, that doesn't do much to them, so it doing direct damage on overheat should alleviate that a little.
The description is somewhat self explanatory. its not very explanatory on when/if it needs to be repaired when not overheated
And the snap is just fun feedback
Tested the repair steps, the heat prompts, sounds, and damage. all worked as expected
<hr>
<hr>
:cl:
tweak: You can tell how hot …

You can now feel how hot the damage medbeam is. and slightly changes the description

---

code/modules/mob/living/living.dm

Changes a temp variable name so it isn't the same as the one on the mob
Removes unnecessary var-unsetting
Adds a clearing of the mob's last words just in case, before the tgui input
This code gives me less of a headache thinking about it
Also no confusion wether `last_words` refers to the local variable or the mob-level variable
Stabbed myself, uttered some last words. No runtimes and it seemed to be working normally
<hr>
<hr>
NPFC

Cleans up last words

---

code/game/gamemodes/wizard/magic_tarot.dm

Adds what tarot cards do to their extended descriptions, so its easier to tell what they do without the wiki open.
I've tried my best to keep it "ic" and somewhat magical with the wordings, and whatnot. please do give feedback on the wordings though.
<details open>
<summary>Added descriptions</summary>
- The fool - "returns the affected user to the arrival point of this forsaken journey."
- the magician - "makes the user feel extraordinarily badass for a couple of minutes."
- The high priestess - "alerts bubblegum to the user, allowing him to strike them down, dealing heavy damage and immobilizing them."
- The empress - "gives the user a temporary boost of speed. This includes attack speed."
- The emperor - "warps the user to where command commonly resides. Be ready for a fight."
- The …

Adds extended descriptions to tarot cards.

---

_maps/map_files/stations/cerestation.dmm

This PR adds a sink to Cere genetics.
All genetics departments should have sinks so they don't need to wander around finding a water source for expanding cubes or wasting a fire extinguisher on it. The lack of one here is an oversight.
Spawned in, confirmed sink properly worked with a monkey cube.
<hr>
<hr>
:cl:
add: Farragus: Genetics finally has a sink.
/:cl:

cere: Add a sink to genetics.

---

code/modules/mob/living/simple_animal/hostile/retaliate/undead.dm

Fixes a massive oversight.
Balance would kill me if I didn't, also spawning boss monsters en mass is not good for the experience go figure.
It runs.
<hr>
<hr>
:cl:
fix: Removes Warden Skeletons from the gold slime core pool
/:cl:

Fixes a oversight with xenobiology

---

.github/PULL_REQUEST_TEMPLATE.md

This PR fixes the link used in the Pull Request Template by switching it to use an absolute link over a relative one. 
Allows contributors to successfully navigate to the page that gives information about Pull Requests that require approval before making a change.
Clicked the link to make sure it went to the right page.
<hr>
<hr>
NPFC

Fixes the Fix of the Fix for the PR Template Pre-approval Link

---

code/game/atoms_movable.dm

Fixes #26571
Folding a duplicate definition of `/atom/movable/Destroy()` in #26186 caused the opacity of an atom to never get re-adjusted after being occluded by another atom with opacity. This caused turfs be permanently made unlightable. 
This is a really bad bug.
I verified that smoke grenades no longer create a tear in the fabric of reality itself, but I'm not sure how else to test this. Considering how puzzling the effects of #26571 were, this could turn a user's computer into a thermonuclear bomb for all I know. 
<hr>
<hr>
:cl: Chuga
fix: Smoke grenades no longer create black holes at the site of detonation.
/:cl:

Fixes smoke grenades making turfs permanently dark

---

code/modules/paperwork/paperbin.dm

Regular paper bins do not have a defined letterhead_type, so selecting the "letterhead" option in the popup will attempt to create a null type and runtime. Instead, we just default to the blank paper if there is no letterhead_type.
Annoying bug.
Picked up some paper and then put it back in the bin.
<hr>
<hr>
:cl: Chuga
fix: Regular paper bins no longer have a broken "Letterhead" option.
/:cl:

Fixes runtime with paper bins

---

code/game/gamemodes/nuclear/nuclearbomb.dm

Instead of making and then improperly deleting a plutonium core, training nuclear bombs now don't make a core in the first place.
When you don't take the garbage out it starts to smell bad.
Launched the game and it didn't appear in the GC failure list
<hr>
<hr>

Makes training nuclear bomb not cause GC failure on Initialize()

---

code/game/objects/structures/crates_lockers/closets.dm
code/game/objects/structures/crates_lockers/closets/secure/secure_closets.dm
code/modules/mob/living/carbon/carbon_procs.dm

Moving while buckled and cuffed (or while in a locked locker / welded locker) will no longer reset your unbuckle timer. This leaves the resist timer for breaking out of cuffs untouched.
Buckle-Cuffing in a moving object like a chair, roller-bed, or locker seemed a little broken and unintended especially when it was abusable. Just walking into the person in the object would reset them.
Buckled a human to an office chair, moved them around. They were able to unbuckle themselves.
**Moved around a cuffed human, their timer was reset without fail.**
Moved around a locker that was welded, a person was inside, they were able to break out.
Moved around a secure locker, a person was inside, they were able to break out.
<hr>
<hr>
:cl:
tweak: Moving while resisting in a movable object (or in a …

Moving while buckled or while in a locker that is locked / welded will no longer reset resist timer.

---

code/modules/mod/modules/modules_general.dm

Fixes https://github.com/ParadiseSS13/Paradise/issues/26368
Makes modsuit storage unable to be bloodied
Not the storage module, storage itself which contains items
Since modsuit itself is not designed as a storage, it has its own "ghost" storage that contains items. If you just hit someone, got your hands covered in blood, then put something in the modsuit, this storage will get bloody and you would not be able to clean it since that thing does not exist for the player
Bugs bad!
Compiled, put bloody items in modsuit, took them out, made sure you can clean it all
<hr>
<hr>
:cl:
fix: Modsuits no longer create infinite bloody hands
/:cl:

Fixing modsuit causing infinitely bloody hands

---

code/modules/food_and_drinks/kitchen_machinery/kitchen_machine.dm

Fixes oversight that allowed one to altclick a kitchen machine at any distance.
If you want your donk pockets, you're going to have to work for it.
Wasn't able to telepathically project my will onto a microwave across the room.
<hr>
<hr>
:cl: Chuga
fix: You can no longer alt click kitchen machines across the room.
/:cl:

You can no longer activate kitchen machines at range

---

code/modules/reagents/reagent_containers/spray.dm

Stops sprays from spraying when clicking on a MODsuit.
Less bugs - cool (pest spray sends its regards).
1. Equip MODsuit.
2. Find any spray.
3. Try put it into the MODsuit by clicking (spray not spraying).
4. Try put it into the filled MODsuit by clicking (spray not spraying).
<hr>
<hr>
:cl: Maxiemar
fix: Sprays no longer spray after being put into MODsuits.
/:cl:

Do not use sprays after putting them into a MODsuit

---

code/game/objects/items/weapons/AI_modules.dm

Prevents Protect Station and Safeguard AI modules from overlapping with existing laws. This *does* make it an inherent law, meaning that it would need to be removed with a purge module or overwritten with another AI module (Eg. Crewsimov)
Fixes: #26574
Laws with overlapping priorities are confusing and bad.
Upload Hippocratic oath to the AI
Upload Protect station to the AI
No overlapping laws
<hr>
<hr>
:cl:
fix: Certain AI modules no longer causes overlapping priorities.
/:cl:

[FIX] Certain AI modules no longer causes overlapping priorities.

---

code/modules/awaymissions/mission_code/ruins/deepstorage.dm
code/modules/mod/mod_actions.dm
code/modules/vehicle/tg_vehicles/tg_vehicles.dm

See title.
code cleanup
It compiles
<hr>
<hr>
my sanity

Cleans up a few more duplicate var definitions

---

code/game/machinery/camera/camera.dm

Cameras can fail to del if a chunk is hanging on to a reference. This makes it not happen.
Makes cameras slightly less broken
Deleted a camera.
<hr>
<hr>

Fixes a source of camera harddels

---

code/game/objects/effects/decals/Cleanable/humans.dm

See title. Images need to be cleaned up or they will cause hard dels and misery.
Blood is fuel.
It deleted.
<hr>
<hr>

Makes blood decals clean up their weightless image

---

code/modules/mob/mob.dm

See title
Yep
Examined a maints drone and it didn't runtime. Examined a human with flavor text and it didn't runtime. DNA stung said human and examined my flavortext and saw the other guy's flavortext transferred over like intended.
<hr>
<hr>
i don't even know if this affected anything in game

print_flavor_text no longer runtimes when dna is null

---

code/game/objects/items/stacks/stack.dm

Ports https://github.com/tgstation/tgstation/pull/60835 in an attempt to stop the scourge of locally non-reproducible /obj/item/stack harddels. This is kind of a shot in the dark, but I can't think of any other reason for such a consistently high occurrence of failure.
Hopefully stops major and consistent harddels.
Stack stuff seems fine in game, but please check me on this.
<hr>
<hr>
NPFC

Fix item stacks qdeling themselves in Init and some item stack self-merge scenarios (port)

---

code/game/gamemodes/miniantags/abduction/abduction_gear.dm
code/game/objects/items/robot/robot_upgrades.dm
code/modules/surgery/organs/augments_arms.dm

Lowers the origin tech of the abductor janitor equipment from 3, to 2. 
Getting abductor engineering tools from a single alien alloy is absurd. 
There are no other alien, or really any other items in rnd (above level 5) that gives more levels than whats needed. So it was inconsistent and frankly overpowered 
compiled, deconstructed tools, only got level three, the tools need level 4.
<hr>
<hr>
:cl:
tweak: You can no longer get abductor engineering tools without organs, or other tools.
/:cl:

You can no longer get abductor rnd level 4+ from level 1

---

code/game/objects/effects/anomalies.dm

Makes the vortex anomaly more dangerous by:
- Increasing it's max range by a single tile, this will cause it to hit at most 4 tiles more, and hitting 4 more tiles a bit more heavily
- It now does it's floor ripping move + the mob pulling once every second instead of two. This will make it a lot more dangerous.
- It keeps the 25% chance to do nothing per tick.
Also rewrites a loop because it was genuinely illegible
Anomalies should be dangerous, and the vortex has for a while now been a slightly worse gravitational anomaly. The Vortex anomaly is also the only anomaly that is announced **in advance**. This PR will make it live up to it's reputation as an anomaly that will have to be dealt with ASAP - and worthy of a pre-spawn-announcement.
Arrivals after an anomaly has done it's thing
See …

Makes the vortex anomaly more dangerous

---

code/game/objects/structures/reflector.dm

Reflectors, all kinds. need to be anchored to actually reflect, and lowers the hp to 50, from 300, also ups the weld time to 5 seconds, from 2.
Before this, DORVAK was comically easy to cheese with a single reflector box, the combo of lowering the hp, and making the anchor be a requirement should aid in making the ruin a threat todo. 
It'll take three standard laser shots to break the reflectors, and 3 volleys from the malf space drones(the hitscan fire ones)
see above
<hr>
<hr>
:cl:
tweak: All reflector types now need to be anchored to reflect
tweak: Lowered the HP of all reflectors to 50, from 300
tweak: Anchoring reflectors takes 5 seconds now, from 2
/:cl:

Reflectors now need to be anchored to reflect, as well as lowered the hp of them

---

html/browser/common.css

Added image-rendering: pixelated to common.css for 516 support
And removed white border on `<hr>`
UI's still cursed, but without blurry char preview on 516
<hr>
<hr>
NPFC

Little adjustments for 516

---

code/game/machinery/computer/HolodeckControl.dm

This PR removes the ability to duplicate carpet tiles & grass tiles from the holodeck, as it makes absolutely no sense why it should duplicate it.
You can't duplicate infinite amounts of carpet tiles & grass tiles anymore.
- Spawned in, visited the holodeck.
- Selected the Theatre & Picnic area
- Used a crowbar on carpet tiles & grass tiles.
- Carpet tiles & grass tiles drops. (Flabbergasted)
- Removed 2 lines of code responsible for spawning the item if removed via a crowbar.
- Visited the holodeck again, to see the tiles disappear into thin air.
- Profit.
<hr>
<hr>
:cl:
fix: Fixed being able to duplicate "grass & carpet tiles" in the Holodeck.
/:cl:

[s] Update HolodeckControl.dm 

---

_maps/map_files/RandomRuins/SpaceRuins/telecomns_returns.dmm
code/game/machinery/constructable_frame.dm
code/modules/awaymissions/mission_code/ruins/telecomns.dm

Tweaks the sat in a few ways to reinforce it.
<details>
<summary>Details hidden for those who want the specifics hidden</summary>
<br>
Turns some walls reinforced, to prevent an easier getaway or avoiding a large majority of turrets.
Blast doors have been added, to ensure the middle room is not skipped to avoid turets and bot traps. This closes the blast door behind you, forcing you to engage the turrets and go through the window to get back around. Everyone always opened the windows anyway, now you really will have to.
You may now build the trapped autolathe! Prank security, prank your friends, piss off your fellow explorers!
Adjusts the layout of the core room, so a security bot does not get trapped stuck, and so there is not empty spaces when AA's rnd rework removes the servers. …

Tweaks to Dvoraks telecomns sat ruin

---

code/modules/mob/living/simple_animal/slime/slime_death.dm
code/modules/mob/living/simple_animal/slime/slime_mob.dm

- Dead slimes previously stored their Target ref to a monkey forever, which caused those monkeys to hard del. Now they clear it on death.
- Makes absolutely 100% sure that slimes stop walking on destroy because of byond reasons.
- Deletes innate actions in addition to removing them.
After these changes, I have been unable to reproduce any failures for either mob.
This is what currently happens in a round:
This is NOT good.
To make monkeys fail to GC:
1. Let a slime suck on a monkey and then kill it somehow. Verify with VV that Target is not null.
2. Delete the monkey and watch it fail to GC.
After changes:
2. doesn't happen anymore.
To make slimes fail to GC (probably not the only way, but it's the first method I found to work multiple times in a row):
1. Let slimes suck on some monkeys …

Makes xenobiology slimes and monkeys GC better

---

code/modules/clothing/chameleon.dm

This PR fixes the Beanies utilized in the Chameleon Hat selection to have color again.
Fixes #26442
Colorful Chameleon Hat Beanies.
- Suffer for several hours.
- Find core issue and experience with syntax.
- Added `I.color = initial(picked_item.color)` in line `160`.
- Spawned in.
- Spawned in Chameleon Hat.
- Selected Beanie of different colors.
- Beanies change color with no sprite errors.
- Profit.
<hr>
:cl:
fix: Fixed Chameleon Hat's Beanies not appearing with their corresponding color.
/:cl:

Fixes Chameleon beanies appearing white while a different color is selected.

---

code/game/objects/effects/spawners/mess_spawners.dm
code/modules/events/event_procs.dm
code/modules/events/tear.dm

Fixes runtimes that occur when events cannot find valid event areas. This usually only occurs when debugging on tiny_test, since it has no valid areas.
Getting smacked with unrelated runtimes on startup when debugging is really annoying. This fixes that.
Compiled and started up the game, saw no runtimes.
<hr>
<hr>
NPFC

Fix runtimes when events cannot find a valid event area

---

code/modules/reagents/chemistry/reagents/medicine.dm
code/modules/reagents/chemistry/reagents/toxins.dm

This targets a very specific chem mix that has seen use in recent weeks as precisely as possible so that the remaining majority of use cases aren't affected. That is, this mix can no longer heal faster than almost anything in the game, which granted the user near god-mode in combat.
As this mix demonstrates, heal_on_apply reagents (styptic powder, silver sulfadiazine, and synthflesh) can be fed via a 1u transfer rate IV drip together at volumes as low as 0.1u per cycle to provide constant, passive, patch-equivalent brute and burn healing. This is just an unfortunate fact of the reagent system. Additionally, the toxin damage that is done on ingestion is proportional to half of the volume. In this specific mix's case, each reagent's volume is 0.1u... so the toxin damage received as a …

Prevents pseudo-exploit with heal_on_apply reagents and IV bags

---

code/modules/atmospherics/machinery/components/unary_devices/thermomachine.dm

Fixes thermo machines runtiming not connecting to pipes when you wrenched the port to their direction.
This happened because build_network was called instead of initialize_atmos_network which caused it to try to build a new pipenet and add the adjacent pipe to it, instead of connecting to the existing one.
Fixes it a bit
-Made a sacrifice to the atmos gods
-Wrenched a thermomachine to nothing, to an empty pipe which I then filled and to a filled pipe.
-Wrenched a pipe to the thermomachine
<hr>
<hr>
:cl:
fix: Wrenching thermomachines connects them to pipes now and doesn't runtime.
/:cl:

Fixes thermomachines runtiming and not connecting when wrenching them to a pipe

---

code/game/objects/effects/decals/Cleanable/humans.dm
code/game/objects/effects/decals/Cleanable/misc_cleanables.dm
code/game/objects/effects/decals/cleanable.dm

#26611 made cleanable decals destroy properly, revealing a host of issues to do with Bump() getting called multiple times on a deleting decal.
- Bump() getting called multiple times caused the decal to try to splat() when it was already qdel'd. This suddenly started causing a runtime because it never properly destroyed before.
- Tries to make cleanable decals not qdel in initialize via try_merging_decal() (which was called in initialize), instead returning a qdel hint
- removes /obj/effect/decal/cleanable/blood/ex_act() because for some reason it was calling update_icon() after the parent call made it qdel and it caused runtimes out the ass.
Bug and runtime fix
Threw a shit ton of blood drips at windows and observed they didn't runtime or do other funny business.
Dropped a bomb on a bunch …

Cleans up /obj/effect/decal/cleanable 

---

_maps/map_files/RandomRuins/SpaceRuins/abandoned_engi_sat.dmm
code/modules/awaymissions/mission_code/ruins/abandoned_engi_sat.dm
paradise.dme

This PR fixes the varedited lockers on the abandoned Engi sat to be proper, empty subtypes of their department lockers. It also replaces the empty emergency lockers with filled ones. Explorers can have a few emergency supplies, as a treat.
These lockers were varedited and terribly broken.
The O2 from the emergency closet may actually come in handy for explorers.
Spawned in, confirmed empty lockers started unlocked and open, opened emergency lockers, confirmed they had contents.
<hr>
<hr>
:cl:
fix: The lockers on the Abandoned Engi Sat now function properly, and the emergency lockers now have proper contents in them.
/:cl:

fix: Standardize abandoned engi sat lockers.

---

code/modules/admin/verbs/freeze.dm

This PR resets an afrozen mob's health if they are set to delete their bodies on death, just before they are unfrozen. This prevents them from dying during the unfreeze, which will kick the player out of their bodies. Fixes #26102.
An afrozen mob's health is never actually reset back to admin_prev_health anywhere, but it doesn't matter because their health is set to the mob's maxHealth on rejuvenate.
Not going to even ask why or think too hard about why their health is set to 0 in the first place.
Losing one's body can be disruptive to their round.
Spawned a wraith, entered it, afroze self, unfroze self.
<hr>
<hr>
:cl:
fix: Afrozen mobs whose bodies are destroyed on death will no longer have that happen when unfrozen.
/:cl:

fix: Unfrozen mobs keep their bodies.

---

code/game/machinery/computer/card.dm

Makes it so that the ID computer also updates the `rank` variable on IDs when someone gets demoted/terminated so their HUD icon updates to the proper HUD icon. Also makes it update the rank on the ID when examined.
Fixes: #26456
HUD should be accurate, as should the ID card.
Demote myself.
I now have the assistant HUD icon, and the "Rank:" section on my ID says "Demoted"
<hr>
<hr>
:cl:
fix: Demotion/termination now properly updates HUD icon
/:cl:

[FIX] Demotion/termination now properly updates HUD icon

---

code/modules/mob/living/silicon/robot/robot_defense.dm
code/modules/mob/living/silicon/robot/robot_mob.dm

Fixes the logic introduced in #26280 to work as intended.
Flashing borgs should flash them
Successfully shined a flash into myself as a normal borg, and could not flash myself as a deathsquad borg.
<hr>
<hr>
:cl:
fix: Cyborgs get blinded by flashes again
/:cl:

Fixes cyborgs not getting blinded by flashes

---

code/game/verbs/who.dm

Fixes how ckeys show up in adminwho for anyone with an admin holder. Fixes an issue that arose in https://github.com/ParadiseSS13/Paradise/pull/26669.
Adminwho is currently a bit unreadable if you're an admin, so this fixes it.
See images
<hr>
<hr>
:cl:
fix: Anyone with admin rights will now get a clearer view of adminwho.
/:cl:

Fix stealthmin handling in adminwho

---

docs/hooks/contributing_path.py
docs/index.md

Makes sure mkdocs rewrites URLs pointing to uppercase filenames, not just the filenames themselves.
<hr>
<hr>
NPFC

fix all occurrences of uppercase links in markdown

---

mkdocs.yml

This PR enables the search plugin for devdocs.
This should have been enabled originally.
Rebuilt site, ensured search index was sent, ensured UI worked, ensured clicking on search results worked.
<hr>
<hr>
NPFC

docs: enable site search

---

code/modules/crafting/recipes.dm

Adds extended throwers to a proper category
It should be craftable
It actually shows up in my crafting menu
<hr>
<hr>
:cl:
fix: Fixed extended chem flamethrowers being uncraftable
/:cl:

Fixes extended thrower recipes

---

mkdocs.yml

Fixes the "None" text that shows up on social preview cards.
"None" looks bad.
See above
<hr>
<hr>
NPFC

docs: add generic site description for social cards

---

code/game/mecha/mech_fabricator.dm
code/modules/research/backup_console.dm

This PR fixes the tgui_alert calls in the R&D rework refactor to the correct arguments.
Runtimes bad.
Visual inspection and prayer.
<hr>
<hr>
:cl:
fix: GUIs for the mech fabricator and backup console now correctly handle unlinking and data disk uploads.
/:cl:

fix: R&D rework: convert rest of tgui_alert choices to lists

---

code/game/gamemodes/game_mode.dm
code/game/gamemodes/vampire/vampire_chan.dm
code/game/gamemodes/vampire/vampire_gamemode.dm
config/example/config.toml
paradise.dme

Title + Adds extra logic to gamemodes that prevents someone from being picked for multiple antagonist roles.
<details>
<summary>
I've gotten on my soapbox on the Discord a few times already, so I'll copy+paste my thoughts from there.
</summary>
I think the changeling gamemode is very flawed, and here are the main reasons why.
- A roundtype of exclusively KOS antags means escalation will only ever increase.
- Changelings don't have enough varied playstyles to make 5-7 in a single round interesting.
- Having such relatively few antags in a round that perma-die when dealt with means that good security officers can quickly run out of things to do, and will cryo with the meta-knowledge that the round has like 2 interesting clings left.
- Once one changeling goes loud, every other changeling is …

Replaces the changeling gamemode with a vampires + changelings gamemode.

---

code/modules/hydroponics/grown/towercap.dm

Changes required minimum oxygen mole value to ignite a bonfire from `14` to `8` (each lavaland tile has 8 moles of oxygen) and adds a notification message when there's not enough oxygen. Fixes #26642.
This is likely an oversight. Players should be able to ignite bonfires in lavaland again.
Tried to ignite it in both station and lavaland wastes, it burned. Tried again in space vacuum, it didn't burn.
<hr>
<hr>
:cl:
fix: Fixed being unable to ignite bonfires in lavaland.
/:cl:

Fixes being unable to ignite bonfire in lavaland

---

_maps/map_files/stations/cerestation.dmm

Removes unnecessary request console.
No flying console.
I believe it won't appear.
<hr>
<hr>
:cl: Maxiemar
fix: Removed flying request console from Farragus.
/:cl:

Remove flying request console from Farragus

---

code/modules/events/spacevine.dm

Forbids spacevine to access arrival shuttle area.
New arrivals won't be entangled upon arrival and will have a chance to survive.
1. Get kudzu seeds.
2. Create spacevine near the arrival shuttle.
3. Wait.
4. The arrival shuttle is safe and sound (still vulnerable to explosions).
<hr>
<hr>
:cl: Maxiemar
tweak: Spacevine no longer destroys the arrival shuttle.
/:cl:

Protect arrival shuttle from spacevine

---

code/game/objects/items/stacks/stack.dm
code/game/objects/items/weapons/shards.dm
code/game/objects/structures/bedsheet_bin.dm
code/modules/hydroponics/grown/towercap.dm

- Cleans up old code in towercap logs and glass shards that didn't let stacks handle merging on their own. This caused runtimes when logs and shards were spam clicked. Now, they just make a new object at the user's loc and let stacks take it from there. An unfortunate side effect of letting stacks handle merging and deletion is that you can no longer see the resulting amount of items in the new stack. This is because there is no guarantee that the stack you have just created will be the final stack and not merged/deleted to form a new one.
- Implements can_merge() (ported from TG stacks) to generalize merge checks. 
- Makes Crossed() call merge() via INVOKE_ASYNC().
After banging my head against the wall for several hours, I can no longer reproduce the spam click stack creation runtimes …

Fixes stacks, attempt 2

---

code/game/gamemodes/game_mode.dm
code/modules/admin/topic.dm
code/modules/station_goals/secondary/bar/random_bulk_drink.dm
code/modules/station_goals/secondary/bar/variety_drinks.dm
code/modules/station_goals/secondary/botany/kudzu_goal.dm
code/modules/station_goals/secondary/kitchen/random_bulk_condiment.dm
code/modules/station_goals/secondary/kitchen/random_bulk_food.dm
code/modules/station_goals/secondary/kitchen/variety_food.dm
code/modules/station_goals/secondary/medical/random_bulk_medicine.dm
code/modules/station_goals/secondary/medical/variety_medicine.dm
code/modules/station_goals/secondary/science/random_bulk_chemical.dm
code/modules/station_goals/secondary/science/random_ripley.dm
code/modules/station_goals/secondary/science/variety_chemicals.dm
code/modules/station_goals/secondary/secondary_goal.dm

Before this PR, requesting a secondary goal got you an un-weighted random type of goal.
With this PR, there is instead a grab bag of goal types, with the number of each defined by the goal type's weight. Requesting a goal pulls from the grab bag, and when the bag is empty, it gets refilled.
Getting variety tasks 1/2 or 1/3 of the time means that, ironically, you have less variety in your secondary goals. By adding the grab bag system and increasing the weight of other goal types, you will get a much more interesting mix of goals.
Spawned as chef, requested 11 goals in the kitchen. First ten contained exactly the expected mix, 11th began a new bag as expected.
Requested a goal in robotics, got one there, too.
Requested a goal in the chapel, got the list of valid departments.
<hr>
<hr>
:cl: …

Re-weight secondary goals.

---

code/controllers/subsystem/SSticker.dm

This PR prevents a night-shift check from being run during SSticker setup if it was disabled in `config.toml`. This was two different attempts at refactoring SSnightshift but it made me want to die so it's just the simplest thing that could possibly work.
The configuration should work.
- Set game time offset to 0. Set `enable_night_shifts = true`. Ensured night shift was enabled immediately, with IC message.
- Raised alert level to red, ensured night shift disabled. Lowered to green, ensured night shift enabled.
- Used admin secrets to change nightshift mode, confirmed correct behavior.
- Set `enable_night_shifts = false` in `config.toml`. Ensure night shift didn't get enabled on roundstart.
<hr>
<hr>
NPFC because night shift is enabled on prod.

fix: Unintentional night-shift despite disabled in configuration.

---

code/modules/mining/lavaland/loot/hierophant_loot.dm

This PR changes the description when deploying the Hierophant beacon.
Fixes #26215
It stops people from accidentally teleporting Mega Fauna / Fauna onto the station.
- Thought of a more precise description when deploying the beacon.
- Changed the description of the `user.visible_message()` in line 156 of `hierophant_loot.dm`.
- Checked Grammar.
- Spawned in.
- Spawned in the Hierophant Club.
- Used its beacon detach ability.
- Description was functional.
- Profit.
<hr>
<hr>
:cl:
tweak: Rewrote item description of the Hierophant Club Vortex Recall to be more precise.
/:cl:

A more precise message for when you detach your Hierophant beacon.

---

code/game/gamemodes/cult/blood_magic.dm
code/modules/mob/living/carbon/human/human_mob.dm
code/modules/surgery/organs/organ_helpers.dm

Gives the Shadow Shackle cult spell the ability to cuff people who are missing an arm.
Fixes #26706
Removes procs that were only used for this one check.
Normal cuffs can do this, so cult cuffs should be able to as well.
Cuffed an IPC with both 2 and 1 arm. Failed to cuff an unarmed (heh) IPC.
<hr>
<hr>
:cl:
fix: Cult Shadow Shackles can now cuff people who are missing an arm.
/:cl:

[FIX] Cult Shadow Shackles can now cuff people who are missing an arm.

---

code/game/objects/items/weapons/shards.dm
code/modules/hydroponics/grown/towercap.dm

This PR removes two unused vardecls introduced in #26633.
Compiler warnings bad. Surprised CI didn't yell about this.
Compiled project.
<hr>
<hr>
NPFC

fix: remove two unused vardecls

---

code/modules/research/designs/medical_designs.dm

Fixes #26718
Makes the RnD console call holo stretcher for holo stretcher and not holo strecher
Spelling mistake bad
I did RnD, then searched for "holo". I saw "holo stretcher" as an option and not "holo strecher"
<hr>
<hr>
:cl:
spellcheck: Fixed a typo in holo stretcher name
/:cl:

Fixes holo stretcher misspelling

---

code/modules/client/preference/preferences_toggles.dm

Re-adds a toggle for admins to hear the notification sound whenever a prayer is made. Was removed (by accident?) in #24060
Admins should be able to hear/not hear prayer sounds
Compiles
Prayed with toggle off, didn't hear a sound
Prayed with toggle on, heard the sound
<hr>
<hr>
:cl:
fix: Re-added the prayer sound toggle for admins
/:cl:

Re-add removed toggle for prayer sounds

---

_maps/map_files/stations/boxstation.dmm
_maps/map_files/stations/cerestation.dmm
_maps/map_files/stations/deltastation.dmm
_maps/map_files/stations/metastation.dmm

Adds a board for the R&D Network Controller and R&D Backup Console to secure tech storage on all maps
Having R&D bricked isn't fun.
See MDB.
None.
<hr>
<hr>
add: Added RND backup console and RND network controller boards to secure tech storage.
/:cl:

Adds the new R&D boards to secure tech storage on all maps

---

code/modules/power/smes.dm

Fixes SMES not outputting if it has been recharged.
The current check makes SMES not working. The `charge` should not be compared to `output_level`, because these values have different sense (the first one is *kinda* charge, the second one is power). Low charge will just lead to low output.
1. Discharge a SMES.
2. Set output to something > 0. Provide some power to it. 
3. Start recharging.
4. SMES provides power.
<hr>
<hr>
:cl: Maxiemar
fix: SMES now recharges correctly providing power.
/:cl:

Fix SMES not working after recharge

---

code/controllers/subsystem/non_firing/SSmapping.dm
code/datums/weather/weather_types/radiation_storm.dm
code/modules/security_levels/keycard_authentication.dm

Moves some global procs to the mapping subsystem.
Global procs cannot be overriden, these procs should belong to some type.
All features work.
<hr>
<hr>
NPFC

Move global access procs to the mapping subsystem

---

code/game/machinery/doppler_array.dm
code/game/objects/explosion.dm
code/modules/mod/modules/modules_science.dm

This PR replaces the list of global explosion sensors with a signal that doppler arrays and advanced reagent MOD modules subscribe to.
We have this signal, might as well use it; one less GLOB list; less typecasting and null checks in /proc/explosion.
Blew up toxins test range, used Event panel to drop bombs, checked that doppler arrays and advanced reagent scanners reacted to explosions.
<hr>
<hr>
NPFC

refactor: use DCS signal for explosion sensors.

---

code/game/objects/items/weapons/chemical_flamethrower/chemical_flamethrower.dm
code/game/objects/items/weapons/chemical_flamethrower/fire_effect.dm
code/modules/crafting/recipes.dm

- Canisters will now show their ammo
- Canisters will now show what reagent they have
- Canisters will clear out their reagents after fully being filled
- You don't get the message from being burned by a fire if you are immune to fire
- Gives a new name and description to the syndicate canister
- Shortens the audible message for adding reagents to canisters
These are nice QOL tweaks
It compiled, filled some canisters and examined them
<hr>
<hr>
:cl:
tweak: Chemthrower canisters now show their ammo properly
tweak: Fires no longer say you are burnt when you are fire immune
tweak: Syndicate chemthrower canisters now have a proper name
/:cl:

Various chemthrower fixes

---

code/modules/clothing/chameleon.dm

Changes the in_game name of the chameleon optical mason scanner from `Optical Meson Scanner` to `optical meson scanner`.
Fixes #26678
You can't meta the hell out of it if you EVER encounter it.
- Spawned in.
- Spawned in `chameleon optical meson scanner`.
- Chameleon X-ray's, Mesons, Thermals have the correct grammar.
- Description fitted changes.
- Profit.
<hr>
<hr>
:cl:
spellcheck: Changed the item's in_game name to chameleon optical meson scanner.
/:cl:

Changes the in_game name of chameleon mason scanners

---

code/game/objects/effects/anomalies.dm

- Gives the cryo anomaly some more attempts to shoot mobs in a 7 turf radius
- Quadruples the amount of CO2 and N2O that it spreads normally. This sounds like a lot but it barely spawned anything
- Triples the amount of gas it spawns on detonate
- Increases the amount of random projectiles from 1-3 to 3-5
Cryo anomalies are quite the joke. They're a non-factor to defuse, as the ambient temperature in a decently sized room will reach barely below 0, which a human's natural heating will easily fix.
With this change, a room can quickly reach -100 C, and people will be hit by more shots generally. You'll be wanting to wear some insulating clothing going in here.
Spawned a cryo anomaly, no runtimes.
Went in the room and got slowed quite fast, and hit by 6 shots before I managed to defuse it. …

Makes the cryo anomaly more dangerous

---

code/modules/recycling/conveyor2.dm
code/modules/recycling/disposal.dm

This PR fixes behaviour of coveyer belts and disposal units, making you place an item on/in it only on help intent so you dont randomly loose your baton
Fixes are good, Something that stores items acting like everything else storing items is good.
Compiled, put items on belt, in disposals unit, made sure you're not doing this on disarm
<hr>
<hr>
:cl:
fix: Conveyer belts and Disposals units will only place your item in on help intent
/:cl:

Conveyer belts and Disposals units no longer steal items on nonhelp intents

---

code/game/machinery/clonepod.dm

The cloner once again mulches people on emag, or a prob (100 / (severity of emp * average level of stock parts)). Upgrading the cloner if emps are about would be a good idea.
People mulched by the cloner are grabbed into the cloned body, before being ripped apart, spreading gibs all over.
Unlike before, this does not turn the cloner into the mess, as the mess function was not brought over with the rework.
This prevents the person from being cloned again, as their current body is now the mulched one, like before.
The cloner running out of power, or being early ejected, acts the same. This only will come into play if an antagonist is trying to make sure you stay dead, or an emp related accident happens.
As for it being too easy to remove someone, one still has to kill them in the first …

The cloner once again mulches people on emag or emp

---

_maps/map_files/stations/boxstation.dmm
_maps/map_files/stations/cerestation.dmm
_maps/map_files/stations/deltastation.dmm
_maps/map_files/stations/metastation.dmm
code/game/objects/structures/reflector.dm

Makes the maps consistent by having the reflectors by supermatter welded down, so engineers don't get surprised half the time as the emitters just break
See above, you shouldn't be gaslighted half the time as engineering
forced map, turned on emitters
reflected without breaking
<hr>
<hr>
:cl:
fix: Reflectors now anchor on mapload, to avoid sm setups breaking rounstart
/:cl:

reflectors anchor on mapload

---

code/game/jobs/job/central.dm

Removes hoverboard from SOO starting inventory
Not needed? Random bloat to inventory of this role, silly to have. If an admin specifically wants it they can spawn it.
Despite being a one-line change, I did test it. And then I noticed that I forgot to remove the comma.
So yeah testing PR's is important.
<hr>
I literally cannot imagine this needing pre-approval.
<hr>
:cl:
tweak: SOO's will no longer spawn with a hoverboard. They're not cool enough.
/:cl:

Removes hoverboard from SOO starting inventory

---

code/game/objects/items/weapons/chemical_flamethrower/chemical_flamethrower.dm

Chemical flamethrowers now use 2 ammo per tile of fire, instead of 3. This increases the effective ammo of a flamethrower by about 50%. Sounds like a lot, but the basic canister goes from 34 tiles to 50. Extended canisters go from 60-ish to 100.
While the flamethrower feels good, it definitely has some ammo issues. You'll eat through extended canisters like candy - also partially because there isn't anything to show if you use a flamethrower again on already burning tiles.
Shot a flamethrower, I could shoot more tiles than before
<hr>
<hr>
:cl:
tweak: Chemical flamethrowers now use slightly less ammo
/:cl:

Makes chemical flamethrowers more efficient

---

code/datums/components/squeak.dm

Continuation of #26461 because you can't reopen PRs with force-pushed branches, apparently.
fixes #10334 "Blood crawling slaughter demons make rubber duckies squeak"
fixes squeak component being confused about what is the crossed and what is the crossing atom
prevents some potential runtimes in play_squeak_crossed
Less bugs, less runtimes and it is more intuitive if blood crawling demons don't cause things in the normal plane to squeak.
- Walked normally and
- - Walked over ducky as human. It  squeaked.
- - Walked over a resting jestosterone'd human as human. They squeaked.
- - Walked over ducky as slaughter demon. It  squeaked.
- - Blood crawled below the ducky. It didn't squeak.
- - Threw ducky. (just to be safe.) It  squeaked.
- Mounted a broom as wizard and
- - Flew over ducky as …

fix squeak component

---

_maps/map_files/stations/cerestation.dmm

This PR adds a missing disposals junction in Cere janitor's closet.
Without this trash just shoots right back out via a hole in the floor.
Put trash in trash.
<hr>
<hr>
:cl:
fix: Farragus: Disposals unit in Janitor Closet now functions properly.
/:cl:

fix: cere jani closet disposal pipe

---

code/game/machinery/portable_turret.dm

You can no longer disasemble something when active or sealed again
lol, lmao, fight the turrets goobers
crowbared active turret, failed, broke it, then could crowbar.
Attempted syndicate turret active, failed, broke it, was informed it was sealed
<hr>
<hr>
:cl:
fix: Fixes active / syndicate  turrets being crowbarable
/:cl:

[s] fix incorrect crowbar check

---

code/game/objects/items/weapons/storage/storage_base.dm

Fixes inventory code that didn't check right
I don't need to know what rnd is up to from the admin testing area
boxed stuff and used bigger items, could see when adjacent for small, or from farhter away for larger items.
moved to another zlvl at the same cordients, couldn't see it
<hr>
<hr>
:cl:
fix: Fixess being able to see someone put an item in their bag or box from another zlvl.
/:cl:

[s]makes you unable to to see inventory from another zlvl

---

code/game/objects/items/stacks/stack.dm

Fixes a runtime where a stack that has merge_without_del returns a qdeling stack of 0 items tries to merge with another stack item.
A lot less runtimes
Tried to reproduce the bug with a reliable method of crafting floor tiles as a cyborg, it didn't runtime.
Used breakpoints to make sure the guard clause was working
Tried to merge a bunch of other stack items to see if it broke something else.
Made sure cyborgs could still stack items.
<hr>
<hr>
:cl:
NPFC
/:cl:

Fixes a runtime caused by stacks accidentally merging twice

---

code/modules/mob/living/simple_animal/hostile/megafauna/megafauna.dm
code/modules/vehicle/tg_vehicles/scooter.dm

Hoverboards get cursed if used to fight megafauna.
After 5 seconds, the hoverboard will kick the user off. You can not buckle to a cursed board or pick it up. After 30 seconds the board will be uncursed and can be picked up.
Normal skateboards will cause stamina damage when ridden on basalt, due to the rocky terrain.
I am off vacation, though I should have fixed this ages ago.
It lets you cheese megafauna far too easily, I intended for the boards to be used for chasm or lava crossing, not fauna fighting.
Fought ash drake, it kicked me off the board, could not pick up, or ride it, wore off later.
Rode hoverboard on lavaland, no stamina.
Rode pro skateboard, took stamina and got message
<hr>
<hr>
:cl:
tweak: Necropolis will curse your hoverboard if used against megafauna.
tweak: Non …

Hoverboards will now get cursed if used during megafauna

---

_maps/map_files/stations/metastation.dmm

Adds a single indestructable tile to the cerebron toxins test site.
Toxins test sites should have a single indestructable tile where the bomb lands, so that the bomb doesn't bounce off and return to the toxins launch room and blow up part of the station.
No visible changes.
Loaded cerebron. Blew up toxins. Plating remained.
<hr>
<hr>
:cl:
fix: Added indestructable plate to cerebron toxins
/:cl:

Cerebon - Toxins Test Site Fix

---

code/game/objects/items/weapons/defib.dm
code/game/objects/items/weapons/knuckledusters.dm
code/game/objects/items/weapons/melee/melee_misc.dm
code/game/objects/items/weapons/teleportation.dm

This PR removes the tech origins, and by extension the ability to destroyed at RnD, from the hand teleporter, captain's rapier, QM knuckledusters, and CMO defib.
Destroying these items via RND in most cases is a rule break. There is no reason for these items to have a tech origin. No other high risk items have tech origins.
Ensured all four items could no longer be deconstructed at RnD
<hr>
<details>
<summary> Approval screenie </summary>
</details>
<hr>
:cl:
tweak: removed tech origin from hand teleporter, Captain's rapier, QM knuckledusters, and CMO defib
/:cl:

Removes tech levels from four high risk items

---

code/game/objects/items/weapons/holy_weapons.dm

You can no longer use the full power of god to husk anyone on your screen at range anymore. Sorry.
It was not balanced. (and a bug)
Clicked people from range, failed to do burn damage.
Melee'd, did burn damage.
Used prayer beads, did no burn damage
<hr>
<hr>
:cl:
fix: You can no longer use the full power of god to husk anyone on your screen at range anymore as an ERT inquisitor. Sorry
/:cl:

[s] you no longer can instantly husk people as an ERT inquisitor

---

code/datums/components/defibrillator.dm
code/datums/mind.dm
code/game/data_huds.dm
code/game/objects/items/robot/robot_parts.dm
code/modules/mob/living/carbon/examine.dm
code/modules/mob/mob_misc_procs.dm
code/modules/surgery/organs/brain.dm

Changes the `get_ghost()` proc so that it now checks if the mind also has the right `key`. This should prevent an issue where if a mob that was offered up to ghosts get killed, and then when revived (through cloning, defib, revive rune, etc.) have the original owner of the body take the body back instead of the new owner. 
Also gets rid of some superfluous loops that look for ghosts in favour of the `get_ghost()` proc.
fixes: #24691
fixes: #19323
fixes: #20480
fixes: #17669
fixes: #10266
It's very annoying getting kicked out of a body you thought you were in charge of.
Be a cultist, offer body to ghosts.
Ghost maintains respawnibility.
Body is taken over, now ascend to dark spirit. The original owner of the body cannot enter my currently uninhabited body.
Try and put a brain in an MMI in …

[FIX] Mobs that were offered up to ghosts no longer get taken over by their old owners

---

code/game/objects/items/weapons/cigs.dm

Pipes now allow you to click on them directly to light them again. Their `attackby()` for adding dried plants overrode the lighting behaviour.
I can smoke a pipe!
Used a pipe and corncob pipe, lit them.
<hr>
<hr>
:cl:
fix: Can light pipes directly again.
/:cl:

[FIX] Pipes can be lit by direct clicking again

---

code/modules/client/preference/link_processing.dm

Not all IPC head models have head markings.
This PR fixes a runtime when trying to select head markings on an IPC head model that does not have head markings.
fix: #26693
Runtimes bad.
Try to change my head markings on a head that has none.
I get a pop-up.
Try to change head markings on a head that does have them.
I can change my head markings.
<hr>
<hr>
:cl:
fix: When trying to open the head marking menu for certain IPC heads you now get a pop-up instead of a runtime.
/:cl:

[RUNTIME] Fixes trying to open the head marking menu for certain IPC heads.

---

code/game/jobs/job/supervisor.dm

Title.
Removes the one (1) singular reference to the NT Supreme Court existing in the game.
Makes the Magi now answer to Nanotrasen Asset Protection, the place where their legal team is.
NT has no reason to have a supreme court. It is a company.
It makes much more sense for the legal rep on station to answer to the legal team in Asset Protection.
- Joined game as Magi
- I answer to NAP now
<hr>
<hr>
:cl:
tweak: Magistrate now answers to NAP as the station arbiter of Space Law
/:cl:

Vaporizes NT Supreme Court

---

code/game/machinery/doors/door.dm

Makes heat-proof doors actually heat-proof again.
Bugs bad
Successfully contained very hot air with heat-proof doors.
Unleashed heat by opening a heat-proof door despite air flowing the other way.
Melted a non-heat-proof door by putting very hot air on one side.
:cl:
fix: Heat-proof doors will no longer leak heat and melt.
/:cl:

Fix heat-proof doors

---

code/game/objects/items/weapons/melee/energy_melee_weapons.dm

fixes eswords reflecting bullets rather than just energy projectiles on parry.
should only be lasers as intended in https://github.com/ParadiseSS13/Paradise/pull/21463
Parried lasers from an energy turret, reflected back.
Parried bullets from  a syndicate turret, blocked.
Parried a terror spider, blocked.
<hr>
<hr>
:cl:
fix: Fixes eswords reflecting bullets rather than just energy projectiles on parry.
/:cl:

[s] Fixes eswords reflecting bullets rather than just energy projectiles on parry.

---

code/modules/projectiles/firing.dm

Fixes shell launch system not backfiring properly on emp, after changes in https://github.com/ParadiseSS13/Paradise/pull/25567
Bugs are bad
shot the shotgun.
Emped myself with rubbershot and gun deployed, gun retracted and hit my arm.
emped myself with dragonsbreath and gun retracted, gun fired and hit my arm
Emped myself with frag12, hit then arm gibbed
<hr>
<hr>
:cl:
fix: Fixes shell launch sytem not backfiring right
/:cl:

[s] Fixes shell launch sytem not backfiring right

---

code/game/gamemodes/miniantags/revenant/revenant_abilities.dm
code/game/objects/structures/tables_racks.dm

Allows revenants to flip tables. This is a fix as this used to be the case beforehand (and I meant to include it in https://github.com/ParadiseSS13/Paradise/pull/26452 but forgor :skull:).
Funny upsidedown table.
Also on the code side this should provide access to other types of interactions that were inadvertently removed.
Spawned in and flipped some tables
<hr>
<hr>
:cl:
fix: Revenants can once again flip tables.
/:cl:

Revenants can once again flip tables

---

code/game/objects/items/weapons/grenades/atmosgrenade.dm

ever so slightly refactors atmosgrenades.dm to have the qdel on the prime proc, rather than the now removed release_air proc.
The grenades not going away was unintended.
and the `release_air` proc was never called so i removed it
fixes #26769
ensured the grenades worked, as far as i can tell, they do
<hr>
<hr>
:cl:
fix: Fixed gas grenades not correctly deleting themselves
/:cl:

Fixes gas grenades not going away after detonation

---

code/game/jobs/job/engineering_jobs.dm
code/game/jobs/job/medical_jobs.dm
code/game/jobs/job/science_jobs.dm
code/game/jobs/job/security_jobs.dm
code/game/jobs/job/supervisor.dm
code/game/jobs/job/support.dm
code/game/jobs/job/support_chaplain.dm

This PR sorts and newlines all station job access lists.
I am probably going to do a sanity pass through these soon and would rather the formatting be done separately so any refactorings are clearer and easier to read.
<hr>
<hr>
NPFC

cleanup: access lists.

---

code/game/mecha/mech_fabricator.dm

Prevents things made in Mech Fabricator from going straight into the wall
Also sets the output_dir depending on the dir of the machine itself during init, which fix issue on Emerald Station on screenshot bellow
Mech Fabricator doesn't print thing into the wall, which funny but bad
Started local with Emerald Station, print some MOD storage and see it doesn't stuck into the wall.
Turned output dir via multitool and make sure it doesn't print into the wall.
<hr>
<hr>
:cl:
fix: Mech Fabricator no longer prints things into the wall
/:cl:

Fix: Prevent Mech Fabricator output into the wall

---

code/game/objects/structures/tables_racks.dm
code/modules/mob/living/silicon/ai/freelook/eye.dm

This PR:
- Fixes a check in /obj/structure/table/CanPass which checks for ismob but then casts to /mob/living, accessing variables that don't exist on `/mob` and runtiming
- Overrides `Process_Spacemove` on `/mob/camera/aiEye` to always return `TRUE`, since it cannot be blocked by anything it passes over in the first place
These runtimes were exposed by #26700 though I can't fathom how.
Less runtimes good, correct logic good.
Spawned in as AI, observed runtime while passing over a table constructed in space. Made change, observed no runtimes while doing the same.
<hr>
<hr>
NPFC

fix: AI Eye movement runtimes

---

code/modules/surgery/organs/vocal_cords.dm

VOG wizard version can only be implanted once. This prevents using it's toggle organ button, which calls attack() from trying to drop and reimplant it
Wizards should be able to use VOG without worrying about their item dropping
spawned in
implanted wizard vog by using it in hand
used toggle
did not drop items in hand
<hr>
<hr>
:cl:
fix: Using wizard vog no longer drops your active item
/:cl:

the wizard voice of god no longer makes you drop your own items

---

code/datums/components/squeak.dm

fixes #26805 that was introduced in PR #26709. It caused squeaky things to squeak even when something was simply moved within the turf (e.g. into a storage container). It now checks whether the movement was onto the turf itself, which should be a necessary condition for squeaking. (Unless we want to change it and also cause  squeaking when something is put into the same container. That's different from the bugged state, in which it squeaks when anything is moved on the same turf, since  that sends the CROSSED signal in every or most cases, for some god forsaken reason.)
Less bug
Put ducky on ground and walked over it. Squeaked. Walked over it as slaughter demon. Squeaked. Blood crawled "over" it. Didn't squeak.
Put ducky in worn backpack, put item into backpack. Didn't squeak. Put on …

fix too much squeaking

---

code/modules/research/rdconsole.dm

Bluespace closet no longer has a random pixel offset when printed on protolathe
Fixes: #24672
Structures probably should not have weird offsets for no reason, especially since the offset can't be changed.
Print a bunch of bluespace closets, they're all centered
Print anything else: Random offset.
<hr>
<hr>
:cl:
fix: Bluespace closet no longer has a random offset when printed on protolathe
/:cl:

[FIX] Bluespace closet no longer has a random offset when printed on protolathe

---

_maps/map_files/stations/cerestation.dmm

Add missing railing corner to the green patch in Cerestation security.
Fixes: #26784
It was previously missing.
Join the game.
Railing is no longer missing
<hr>
<hr>
:cl:
fix: Missing railing corner has been added to the green patch in Cerestation security.
/:cl:

[FIX/CERESTATION] Adds missing railing to Cerestation security

---

_maps/map_files/stations/cerestation.dmm

This PR fixes the direction of a disposal outlet in the farragus west waste belt loop.
Shit getting stuck
<hr>
<hr>
:cl:
fix: Farragus: A disposal outlet on the west waste belt loop is now facing the correct direction.
/:cl:

fix: Farragus disposal outlet direction

---

code/game/gamemodes/miniantags/abduction/abduction_gear.dm

Fixes #23898. Now appears like it used to before #19748 (at least I think that what caused it)
Bug bad
Now appears like it used to. There are and were never any unique sprites for these on the toolbelt.
See above
<hr>
<hr>
:cl:
fix: Abductor belts no longer shows the incorrect item overlays
/:cl:

Fixes the abductor belt having incorrect overlays

---

code/modules/research/designs/weapon_designs.dm

Fixes extended chemthrower parts not being available
They should be available
They showed up in the protolathe
<hr>
<hr>
:cl:
fix: Extended chemthrower parts are now available in the protolathe again
/:cl:

Makes extended chemthrower kits available in the protolathe

---

code/modules/mob/living/simple_animal/friendly/cat.dm
code/modules/mob/living/simple_animal/simple_animal.dm

Dead cats no longer try to chase mice. Cats also stop chasing the mouse after the mouse is dead
Fixes: #25610
Dead cats chase no mice.
Spawn in a mouse, cat starts chasing it, I kill the cat before they reach the mouse, they stop moving.
<hr>
<hr>
:cl:
fix: Dead cats no longer chase mice
/:cl:

[FIX] Dead cats no longer chase mice

---

_maps/map_files/stations/boxstation.dmm

This PR changes the name of the camera in the NT Rep's office from "Blueshield" to "Nanotrasen Representative's Office" on Cyberiad. This also allows both cameras to be accessed from the camera console again.
Fixes #26768
It makes it possible to spy on your Blueshield on Cyberiad once more.
- Accessed both the Blueshield and NT Rep's cameras from various camera consoles
<hr>
<hr>
- Changed NT Rep's camera name

Fixed NT Rep's camera name

---

code/game/machinery/computer/cloning.dm

Makes it so that scanning people doesn't brick after you scan two people
Turns out you should test something at least three times before you make a PR.
Scan someone three times
Cloning scanner doesn't shit itself
<hr>
<hr>
:cl:
fix: Cloning doesn't break again
/:cl:

[FIX] Unbricks cloning

---

_maps/map_files/RandomRuins/SpaceRuins/ussp.dmm
_maps/map_files/RandomRuins/SpaceRuins/wizardcrash.dmm
code/game/turfs/simulated/walls_indestructible.dm
code/game/turfs/simulated/walls_mineral.dm

Makes indestructible titanium walls into a subtype of indestructible walls rather than being their own thing, with all the additional strengthening to their indestructibility this brings.
The Wizard and USSP ruins have been remapped with the new walls.
This prevents two entire ruins from being completely bypassed by using the RCD to deconstruct a single wall. This is clearly not intentional given the effort that was put into making the walls resist other methods of destruction.
Visited the wizard shuttle and USSP ruin.
Verified that I couldn't deconstruct them with the RCD.
Made sure that there were no weird smoothing issues with the walls at either location.
<hr>
<hr>
:cl:
fix: You cannot deconstruct indestructible titanium walls with an RCD anymore.
/:cl:

Makes Indestructible Titanium Walls Into an Indestructible Wall Subtype

---

code/game/machinery/doors/airlock_types.dm

Adds a signal type to RegisterSignal() of pair_airlock proc
No more GC issue from filler objects
Tried to assemble / disassemble multi-tile airlock on localhost. Checked GC queue from debug menu
<hr>
<hr>
:cl:
fix: filler_objects doesn't get stuck in GC queue anymore
/:cl:

[Fix] GC issue of multi-tile airlocks

---

code/game/gamemodes/miniantags/tourist/tourist_arrivals.dm

Fixes a check that didn't allow people to roll tot on tourist.
It's working as it should again! 
Logged into test with an improv db, tested and got tot!
<hr>
<hr>
:cl:
fix: Tourists should be able to roll traitor again.
/:cl:

[FIX] Tourist not rolling traitor

---

code/game/objects/items/robot/cyborg_gripper.dm
code/modules/mob/living/silicon/robot/robot_inventory.dm

You can no longer put your cyborg gripper in a display case
Place items you're not supposed to drop, and that become undroppable for others is less than desirable.
https://github.com/user-attachments/assets/10c0c49b-7c93-4a06-bdc8-b1e1ed88d6e4
Try to put the gripper in a display case
Grab airlock electronics
Put those in the display case
Put them in the trash
Drop them
Use them in hand
<hr>
<hr>
:cl:
fix: You can no longer put your cyborg gripper in a display case
/:cl:

[FIX] You can no longer put your cyborg gripper in a display case

---

code/modules/supply/supply_packs/pack_organic.dm

The manifests for critter crates now show their contents
Fixes: #26843
Should be able to tell what is in a crate before you order it
Look at the cargo console
View contents on a cow crate
I can order cows
<hr>
<hr>
:cl:
fix: Cargo console entry for critter crates now show their contents
/:cl:

[FIX] Cargo console entry for critter crates now show their contents

---

code/game/machinery/tcomms/tcomms_core.dm

Disables encoding for tcomms filter input via `html_encode`. It was accidentally enabled when TGUI input was used.
The names of some characters contain special symbols such as `'` (Apostrophe 39, replaced with `&#39;`) that cannot be filtered.
The filter allows special symbols now.
<hr>
<hr>
:cl: Maxiemar
fix: Telecommunications Core filter allows special symbols in names now.
/:cl:

Disable encoding for tcomms filter input

---

code/game/objects/items/weapons/storage/boxes.dm

When a monkey cube box (Or any of their variants) is destroyed by acid/fire, the cubes inside are also destroyed.
Prevents cheesing by biohazards
Burn a monkey cube box by blowing up a weldertank next to it, monkey cubes are destroyed
Spray acid on monkey cube box as a xeno queen, monkey cubes are destroyed
<hr>
<hr>
:cl:
tweak: Destroyed monkey cube box now destroys monkey cubes inside.
/:cl:

[TWEAK/BALANCE] Destroyed monkey cube box now destroys monkey cubes inside

---

code/game/objects/effects/spawners/random/engineering_spawners.dm
code/game/objects/effects/spawners/random/food_spawners.dm
code/game/objects/effects/spawners/random/maint_loot_spawners.dm
code/game/objects/effects/spawners/random/misc_spawners.dm
code/game/objects/effects/spawners/random/random_spawner.dm
code/game/objects/effects/spawners/random/trash_spawners.dm

This PR disables blackbox recording of random spawner spawns by default for new subtypes, and explicitly enables them for spawners that are part of maintenance loot tables.
I'd prefer having the toggle var as opposed to just having the base type's `/record_item` do nothing, because the default format of the blackbox row is still worth not having to reimplement for other subtypes.
I need to start moving all the old random_spawners over to the new type, and we don't need to know every time fungus spawned somewhere in the galaxy.
Manually stepped through logic.
<hr>
<hr>
NPFC

fix: only blackbox maintloot spawners

---

code/modules/antagonists/vampire/vampire_powers/hemomancer_powers.dm

Hemomancer claws no longer runtimes on hitting a xenomorph.
Instead, they become stronger due to the acid blood _**UNTIL THE CLAWS RUN OUT OF DURABILITY!**_ Recasting the claws afterwords, will be *back to normal*
When empowered by acid, the claws do an acid act similar to dumping facid on someone, but:
Less damage because its not the chemical, it's acid act
Clothing protects you.
Aditionally, the claws heal the user twice as much so they *might* survive using them on a xenomorph, and now do 50% more damage / blood collection, and become burn for the duration.
Remember. You need a live xenomorph, you need to engage them in melee, and it only lasts 20 hits (2 handed, if you drop it you lose it) Good luck!
Sure, I could have just made it not runtime, but this is cooler. Might make a vampire …

Stops hemo claws runtiming on xenos, makes them become stronger

---

code/game/objects/structures/tables_racks.dm

Adds in the ability to map in flipped tables (And adds a subtype for the base table for mapping)
Fixes: #26145
It's useful to be able to map in flipped tables
Map in some flipped tables
Load in
They are flipped
<hr>
<hr>
NPFC

[FIX] You can now map in flipped tables

---

code/game/objects/items.dm

`cigarette_lighter_act()` will not check for intent or body part targeting if you are attacking the smokable directly.
This act should only be making those checks when trying to light by clicking someone's sprite instead of directly clicking the smokable.
Gathered a collection of cigarettes and cigars. Cycled through my intents and body parts whilst trying direct clicking and sprite clicking.
The smokables lit when directly clicked regardless of body part target or intent, as intended.
The smokables only lit during sprite lighting when intent was Help and body part targeted was mouth, as intended.
<hr>
<hr>
:cl:
fix: Lighting cigarettes by clicking on them no longer requires specific intent or body part targeting.
/:cl:

Fixes Cigarette Act `attackby()` handling.

---

code/modules/food_and_drinks/food/foods/frozen.dm

Changes the trash that is dropped when tating an Ant Popsicle from a Metal Rod to a Used Popsicle Stick.
Fixes #26841
Puts the trash in line with what the recipe calls for. 
Spawned in Ant Popsicle
Consumed
:cl:
tweak: Changed the trash that drops when consuming Ant Popsicles from Rod to Popsicle Stick.
/:cl:

Ant Popsicle Now Drops Proper Trash when Eaten

---

code/datums/status_effects/blob_burst.dm
code/datums/status_effects/buffs.dm
code/datums/status_effects/debuffs.dm
code/datums/status_effects/neutral.dm
code/datums/status_effects/status_effect.dm
code/modules/projectiles/guns/chaos_bolt.dm
code/modules/unit_tests/_unit_tests.dm
code/modules/unit_tests/status_effect_ids.dm

Adds some sanity to see if status effects have an ID
Adds missing IDs to status effects
`transient` and `incapacitating` technically didn't require an ID but they got one anyways
This makes it easier to see if someone forgot to set an ID for a status effect which could cause some unintended behaviour (looking at you cling)
Gave myself all status effects without any runtimes
<hr>
<hr>
NPFC

Gives all status effects an ID

---

code/game/objects/effects/decals/Cleanable/humans.dm
code/modules/reagents/chemistry/reagents/water.dm

Blood no longer layers on non fulltile windows. This helps, as it's sprite doesn't line up correctly, and it only visually makes sense on fulltile ones.
Footprints no longer layer above windows or grills. You are stepping on the floor, not on the windows. This shouldn't be an issue anymore anyway with the above window check, but safety first is good
Spacecleaner foam now cleans windows or grills of blood, much like the floor
Buggy blood that doesnt visually look sense or is nearly impossible to clean isn't good. This fixes this.
Spacecleaner foam covering a window with space cleaner should clean it, much like it cleans every other object in the game
Attempted to bleed on non fulltile windows, blood layered the floor.
Attempted to splatter blood on fulltile windows, layered properly. …

Non fulltile windows don't get blood on them, spacecleaner cleans blood more reliably

---

code/game/objects/structures/shelves.dm

Fixes something with shelves 
it is, trust
compiled, checked the issue was still an issue
<hr>
<hr>
:cl:
fix: Gunracks now drop metal on deconstruct
/:cl:

[s] Fixes a issue with shelves 

---

docs/CODE_OF_CONDUCT.md
docs/CONTRIBUTING.md
docs/contributing/reviewer.md

Changes references in our documents to reflect the new policy change of updating the `Commit Access` team to the name `Maintainer`.
It brings the team name in-line to what the job entails. 
Reviewed documents with markdown preview
<hr>
<hr>
NPFC

Updates Documents for Renaming Commit Access to Maintainers

---

code/__DEFINES/misc_defines.dm
code/datums/components/multitile.dm
code/modules/power/gravitygenerator.dm
code/modules/station_goals/bluespace_tap.dm
code/modules/station_goals/dna_vault.dm

The multitile component now works with any length of lists and creates all of the fillers relative to MACH_CENTER, rather than the center of the table.
This makes it easier and more intuitive to create big machines of various shapes while also dramatically reducing the size of the table needed to create shapes of high aspect ratios.
I tested the following shapes by changing the filler's sprite to that of a wooden table:
Hourglass:
list(1, 1, 1, 1, 1)
list(	1, 1, 1)
list(  MACH_CENTER)
list(	1, 1, 1)
list(1, 1, 1, 1, 1)
Hollow Diamond:
list(		 	1)
list(	 	1,	0, 	1)
list(	   1, 0,	0, 	0, 1)
list(   1, 0,  0,	0, 	0, 0, 1)
list(        1, 0,	0, 	0, 1)
list( 		1, 	0, 	1, )
list(		   MACH_CENTER)
Snake:
list(	          1, 0, 0, 0, 1, 0, 0),
list(MACH_CENTER, 0, 1, 0, 1, 0, 1, 0, 1),
list( …

Allows multitile to work with arbitrary list lengths

---

code/modules/mob/dead/observer/orbit.dm

Event characters can now be easily seen in the orbit menu when ahudded.
QOL change for antag hudded observers. event characters are normally interesting and should be separated.
Changes compile properly, tested on local with multiple clients. ahud and orbit menu work properly when role is added and then removed.
<hr>
<hr>
:cl:
tweak: Ahud now shows event roles in a separate line in the orbit menu
/:cl:

Event characters now have their own section in the orbit menu when ahudded

---

code/datums/status_effects/buffs.dm

Makes it so the drill can actually heal the brute and burn of IPCs too.
Fixing oversights is good, it's an antag item healing.
Spawned as a Drask tot Assistant, spawned Payday bundle, opened Vault with C4, aghosted and went back to lobby to then spawn as a Drask HoS, moved HoS just out of sight of the Vault interior, aghosted then controlled Assistant, used drill on safe, walked out enough to spot HoS, got payback effect, dealt brute burn and stamina damage, saw damage got healed, removed drill from safe.
Aghosted and went back to lobby to then spawn as an IPC tot Assistant, spawned Payday bundle, used drill on safe in Vault, walked out enough to spot HoS, got payback effect, dealt brute burn and stamina damage, saw damage got healed.
<hr>
<hr>
:cl:
fix: Fixed the drill payback buff to …

The amplified drill actually heals IPCs for more than just stamina damage

---

code/modules/martial_arts/combos/judo/judothrow.dm
code/modules/martial_arts/judo.dm

Fixes #26053. You can now perform wheelthrow and armbar being prone. Not judothrow.
Fixes are good
Tried to perform an `armbar` and a `wheelthrow` being prone - was able to
Tried to perform a `judothrow` being prone - was unable to
<hr>
<hr>
:cl:
fix: Judo combos are now working as it was intended long ago
/:cl:

Judo combos fix

---

code/game/objects/items/weapons/melee/melee_misc.dm

Simple (almost 1 to 1) copy paste from eswords (because  oop sucks).
Adds the same suicide as eswords to the captain saber, with the only difference being that it only deals brute and no burn damage.
Captain can now die in style.
Suicided with saber. 250 brute was applied. One of the two messages was selected at random (both work).
<hr>
No balance or wide reaching gameplay implications. Simply some flavour that already exists in another place.
<hr>
:cl:
add: Added seppuku suicide to the captain saber.
/:cl:

Add Seppuku to the Captain Saber

---

_maps/map_files/RandomRuins/SpaceRuins/syndiedepot.dmm
code/game/objects/effects/spawners/depot_spawners.dm
code/game/objects/effects/spawners/random/random_spawner.dm

Fixes #26975
Adds new var, `spawn_inside` for random spawners' code (I just stole it from old one).
Fix. Hope i'm not breaking something with this.
On a local. Checked out depot, no issues.
<hr>
<hr>
:cl:
fix: Depot now properly spawns lockers.
/:cl:

Fix: Syndie depot locker is only spawned when there is a loot

---

code/modules/mob/living/living_defense.dm

Removes an unused proc
We don't use it anymore and it's kinda crappy
Compiled
<hr>
<hr>
NPFC

Removes a random proc that we don't use

---

code/controllers/subsystem/processing/SSstation.dm
code/datums/station_traits/admin_panel.dm

Makes station traits saving for next round work again
resolve #26983
Bugs are bad, admin tools should work
<hr>
Forced the traits. (Cybernetic, rave, carp.)
Loaded cybernetic, rave, carp next round, verified with breakpoints t hat they were loaded and not random generated
<hr>
:cl:
fix: Fixed admins being unable to force station traits for next round
/:cl:

Fixes some unknown tgui change breaking station trait saving

---

code/__HELPERS/unsorted.dm
code/game/objects/items/mountable_frames/frames.dm
code/game/objects/items/mountable_frames/light_frames.dm
code/game/objects/items/mountable_frames/mountables.dm

Makes sure that you can't put anythin on a wall that already has a wall object
This is for consistency and the view of the mapping team that every wall should have only a single wall object (excluding switches)
Tried putting a lot of frames on walls, they only could when there wasn't anything on the wall
<hr>
<hr>
:cl:
tweak: Lights now respect wall objects
tweak: Switches now can be placed on a wall regardless of any other wall objects
/:cl:

[s] Blocks any doubled wall mount placement

---

code/modules/reagents/chemistry/reagents/misc_reagents.dm

Makes it so IPCs are affected by Jestosterone relative to their job variable. Mime IPCs are burned instead as IPCs are unaffected by Toxin damage and burns feel somewhat similar to poison with numbness and burning sensations.
Funny Clown chemical should do funny Clown things to all. Also because IPC Clowns and Mimes should be affected as it is part of the chemical's gimmick.
Spawned in as a Drask Clown, dealt brute to myself, drank Jestosterone, watched myself get healed.
Spawned in as an IPC Clown, dealt brute to myself, drank Jestosterone, watched myself get healed.
Spawned in as a Drask Assistant, drank Jestosterone, felt and saw the funny effects.
Spawned in as an IPC Assistant, drank Jestosterone, felt and saw the funny effects.
Spawned in as a Drask Mime, drank Jestosterone, felt …

IPCs are affected by Jestosterone now

---

code/game/turfs/simulated/floor/plating.dm

No longer calls parent in the singularity_pull proc of reinforced floors, and forces conversion to plating. This allows the reinforced floor to properly disassemble.
Fixes it
Created singulos in various stages and observed reinforced floors being affected as they should be
<hr>
<hr>
:cl:
fix: Reinforced floors now properly disassemble when pulled by a singularity
/:cl:

Fixes singulo pull on reinforced floor

---

code/modules/mod/mod_core.dm

Rebinds pulling cells out of modsuits from click to ctrl-click.
It was being overridden by storage modules meaning you could not actually remove a cell with a normal click.
Changed the examine text to reference ctrl-click and bolded both hints. The other hints given for wrench, crowbar and so on were bolded so this is just to match that style.
Bug fix.
Spawned myself in and tested ctrl-clicking cells out of modsuits with and without storage.
<hr>
<hr>
:cl: Bmon
fix: Fixed removing cells from modsuits. To remove a cell from a modsuit ctrl-click it while the panel is open.
/:cl:

Fixes Powercell Removal On Modsuits

---

code/game/objects/items/robot/robot_upgrades.dm

Unfucks cyborg upgrades.
Runtime bad
Install a vtec upgrade.
Nothing breaks
<hr>
<hr>
:cl:
fix: Unbrick cyborg upgrades
/:cl:

[FIX] Unbrick cyborg upgrades

---

code/game/objects/effects/spawners/depot_spawners.dm
code/modules/food_and_drinks/food/foods/pizza.dm

This PR randomizes the pizza variety on pizza bombs so it's not always "pepperoni". It also refactors the relevant code.
No more predicting if the pizza is a bomb just by its toppings.
Ensured boxes spawned with varied labels, ensured stacking them worked, ensured getting blown up worked.
<hr>
<hr>
:cl:
tweak: Pizza bombs now can be labelled as any pizza topping.
/:cl:

feat: Pizza bombs now disguise as any flavor.

---

code/game/objects/items/weapons/storage/fancy.dm

Fixes the eternal candle box appearing empty on spawn, also changes how the normal candle box handles it slightly.
The boxes looked empty, the whole point of fancy storage is you can /see/ how full/empty it is
(trust me)
Spawned every candle box type, all appeared correctly. swapped candles around the boxes, no issues seen
<hr>
<hr>
fix: Fixed eternal candle boxes appearing empty when they spawn
/:cl:

Fixes eternal candle boxes appearing empty on spawn

---

code/game/objects/items/weapons/storage/belt.dm
code/modules/martial_arts/judo.dm

Reworks an assault belt to make it usable for on-station security. You can now store WT/IK magazines, stunbatons in it, alongside with the default tools. 2 of these are in SWAT crate for 900 credits.
Gives judo belt `combined_w_class = 7` instead of `6` since there is a normal sized item (detective scanner) possible (3+2+2=7).
Gives webbing `15` instead of `14` so its able to store 1 extra normal sized item compared to standard belt.
Belts are better to use. 
Tried to put an item with `w_class` more than `3` inside assault belt - failed.
Tried to put regular security's staff inside - succeed.
Also was able to store a radio in any of these belts.
<hr>
<hr>
:cl:
tweak: Assault belt is now able to hold security items. Security belts are able to store radio, and security webbing with judo …

Security belts tweak

---

code/datums/components/zombie_regen.dm
code/datums/helper_datums/teleport.dm
code/datums/spells/area_teleport.dm
code/game/machinery/slotmachine.dm
code/game/objects/buckling.dm
code/game/objects/items/tools/wirecutters.dm
code/game/objects/items/weapons/scrolls.dm
code/modules/mob/living/carbon/carbon_procs.dm
code/modules/mob/living/carbon/human/species/_species.dm
code/modules/mob/living/carbon/human/species/golem.dm
code/modules/mob/living/living.dm
code/modules/mob/living/living_defines.dm
code/modules/mob/living/simple_animal/hostile/floorcluwne.dm
code/modules/mob/living/simple_animal/slime/slime_powers.dm
code/modules/mob/mob.dm
code/modules/mob/mob_vars.dm
code/modules/research/experimentor.dm
code/modules/shuttle/shuttle.dm
code/modules/surgery/organs/vocal_cords.dm

Adds a helper proc `unbuckle` to `mob` that handles unbuckling and replaces all instances of `buckled.unbuckle_mob()` with the helper proc instead.
A single proc for this is simpler and more readable
Buckle myself to a chair
Unbuckle myself from a chair
<hr>
<hr>
NPFC

[REFACTOR] Helper proc for unbuckling a mob

---

code/modules/power/engines/supermatter/supermatter.dm

Fixes #27029. Anomalies now generate on turf within rage.
Anomalies spawning inside pipes, APCs, and another anomalies is cursed and bad.
Abused several SMs to ensure anomaly generation behavior looked right. no runtimes thrown. 
<hr>
<hr>
:cl:
fix: supermatter anomalies no longer generate inside structures
/:cl:

Fixes Sm anomaly generation to not spawn them inside machines/structures

---

code/game/objects/items/weapons/storage/backpack.dm

Fixes stimulating steak from being a possible target for the kitchen secondary goal.
Fixes: #27035
Unobtainable item should not have to be obtained for a secondary goal
Single line change, did not test.
<hr>
<hr>
:cl:
fix: Stimulating steak no longer possible kitchen secondary goal
/:cl:

[FIX] Stimulating steak no longer possible kitchen secondary goal

---

code/game/mecha/mecha_construction_paths.dm

Fixes #27054 by fixing a bad path in the construction result, which caused a runtime and no appearance.
Bugs bad. Oops.
Constructed a nkarrdem, did not runtime, had a mech that was actually a mech and not an invisible chassis.
<hr>
<hr>
:cl:
fix: Fixes runtime caused by bad construction path
/:cl:

Fixes Null Runtime in Janimech Construction

---

code/modules/hydroponics/grown/cocoa_vanilla.dm

Allows you to now mutate Bungo Fruit seeds from Cocoa, as was intended.
Actually being able to create things with Bungo Juice is a good thing.
It mutated.
<hr>
<hr>
:cl:
fix: Bungo Fruit can now be mutated from Cocoa
/:cl:

Bungo Fruit is now growable.

---

code/__HELPERS/trait_helpers.dm

UID is a proc you call on a datum, not one you pass the datum as an argument
This should work as intended ~~there is a chance it does work properly but in any case now it also looks correct~~
Ate a pulse demon heart, was shock immune, deleted it, wasn't shock immune anymore
<hr>
<hr>
NPFC

Fixes `UNIQUE_TRAIT_SOURCE`

---

code/__HELPERS/trait_helpers.dm
code/modules/clothing/shoes/magboots.dm

Fixes magboot fuckery. Specifically fixes #26740 as an alternate PR to #26788 with permission of the author.
Also renames the internal magpulse trait from "magnetificent" to "magpulse" (its funny but without codediving its harder to tell what it is)
Fixes a bug
Picked up the boots, turned them on (magpulse not active)
Put the boots on my feet (magpulse active)
took the boots off my feet (magpulse not active)
turned the magboots off (magpulse not active)
put the boots on my feet (magpulse not active)
turned the magboots on (magpulse active)
took the magboots off (magpulse not active)
<hr>
<hr>
:cl:
fix: Magboots only work when equipped
/:cl:

Fixes magboot fuckery

---

code/modules/antagonists/traitor/datum_traitor.dm

Malf AIs will no longer be given a traitor organization. No gameplay changes as objectives for malf AI didn't care about the player's org.
Unintentional change when I added traitor orgs. Kinda goofy for AIs to be assigned lore orgs meant for crew.
Became traitor as human, and traitor as AI, check works as expected.
<hr>
<hr>
:cl:
fix: Malf AIs no longer get assigned a traitor organization. No gameplay change.
/:cl:

Fix malf AI getting assigned a traitor organization

---

_maps/map_files/RandomRuins/SpaceRuins/telecomns_returns.dmm

Removes some reinforced walls, makes them indestructable
No you can not skip the dangerous half of the ruin
<hr>
:cl:
fix: Fixs being able to skip the left side of the dvorak ruin
/:cl:

[s] fixes some walls I missed

---

code/modules/customitems/item_defines.dm

Fixes #27071
Invisible sprites bad.
This may be a really hacky fix, but the item /never/ had a icon state to begin with, so this is better than both, nothing. Or using a place holder
see above
<hr>
<hr>
:cl:
fix: Fixed a donator fluff item not having a icon state.
/:cl:

Fixes combat pants not having a icon state

---

_maps/map_files/generic/Lavaland.dmm
_maps/map_files/stations/deltastation.dmm
tools/maplint/lints/stacked_matching_extinguisher_cabinets.yml

This PR removes two instances on maps where multiple fire extinguishers were stacked in the same direction, and adds a maplint prohibiting it in the future.
Easy mapping oversight, let's fix it forever.
<hr>
<hr>
:cl:
fix: The mining shuttle no longer has two fire extinguishers stacked on the same wall.
fix: Kerberos: the SMES room no longer has three fire extinguishers stacked on the same wall.
/:cl:

fix: duplicate mapped fire-extinguishers

---

code/game/objects/structures/crates_lockers/closets.dm
code/game/objects/structures/crates_lockers/closets/secure/personal.dm

Fixes some issues with animated closets:
1. Personal closets no longer go invisible when you swipe an ID over them.
2. Bluespace lockers once again go transparent when something moves through them.
Bugs are bad
Move a bluespace locker through myself, and a table, and open and close it a bunch. It handles transparency fine.
Swipe my ID card over a personal locker. It does not go invisible.
<hr>
<hr>
:cl:
fix: Personal lockers no longer go invisible if you swipe your ID over them.
fix: Bluespace lockers can once again go transparent.
/:cl:

[FIX] Animated closet fixes

---

code/game/objects/structures/crates_lockers/closets/secure/guncabinet.dm

Fixes a bug introduced by animated closets where the gun overlays were drawn before the door overlay on gun cabinets
Bugs bad
Look at a gun cabinet, open a gun cabinet, close a gun cabinet.
<hr>
<hr>
:cl:
fix: Guncabinets no longer show the gun overlays above their doors.
/:cl:

[FIX] Guncabinet overlay fix

---

code/__DEFINES/misc_defines.dm
code/modules/mob/living/carbon/human/human_inventory.dm
code/modules/mob/living/carbon/human/human_mob.dm

Fixes an issue where cybernetic eyes, xray eyes, and a few other misc eye traits would ignore the overlays and appear over items they shouldn't. (Like a hood or gasmask etc.)
Fixes https://github.com/ParadiseSS13/Paradise/issues/25725
Bugs are bad.
Loaded offline, made a nian with cybernetic eyes. Walked into a dark room. Put on a gas mask, took off the gasmask. Smiled!
<hr>
<hr>
:cl:
fix: Eye_shine no longer goes over masks and other clothing.
/:cl:

Fixes a glowing eye issue and eye overlay issue

---

_maps/map_files/stations/cerestation.dmm

This PR corrects some areas on Cere's service asteroid. Fixes #27110.
Mapping oversight.
###Before
<hr>
<hr>
:cl:
fix: Farragus: some area designations on Service asteroid have been fixed.
/:cl:

cere: fix some area desginations on service asteroid

---

code/modules/projectiles/gun_attachments.dm

Keeps suppressors consistent by calling them universal suppressors, as they are called in RND, uplink, their description, and in space law
See above
I changed it's name and confirmed it was spelled right
<hr>
<hr>
:cl:
tweak: Renames the suppressor to universal suppressor, as it is called everywhere else.
/:cl:

Renames the suppressor to "universal suppressor", as it is called everywhere else

---

code/modules/food_and_drinks/kitchen_machinery/cooker.dm

makes /food transfer reagents
It is good for the deep frier to not eat all the nutriments / poison in your food, was broken in #23379
VV'd the deep fried food / cereal to make sure it had the reagents of the original food.
Conducted a taste test!
<hr>
<hr>
:cl:
fix: Fixes deepfrier / cereal maker not transfering reagents to the food you make with it
/:cl:

Fixes deepfrier / cereal maker not transfering reagents

---

code/game/objects/structures/crates_lockers/closets/secure/secure_closets.dm

Makes the sparks from emagging a closet disappear again after a second
Unintended change, these sparks are not intended to be permanent.
https://github.com/user-attachments/assets/ddb796f9-7577-4e8a-8725-640cf206f178
Emag a locker
The sparks disappear
<hr>
<hr>
:cl:
fix: Emagging a closet no longer causes it to have permanent sparks.
/:cl:

[FIX] [IDB Ignore] Closet emag sparks disappear again

---

code/__DEFINES/mob_defines.dm
code/game/gamemodes/miniantags/abduction/gland.dm
code/game/gamemodes/miniantags/demons/slaughter_demon/slaughter.dm
code/game/machinery/rechargestation.dm
code/modules/mob/living/carbon/carbon_update_status.dm
code/modules/mob/living/carbon/human/human_update_status.dm
code/modules/surgery/organs/augments_arms.dm
code/modules/surgery/organs/heart.dm
code/modules/surgery/organs/organ_datums/battery_datum.dm
code/modules/surgery/organs/organ_helpers.dm
code/modules/surgery/organs/subtypes/machine_organs.dm
paradise.dme

Fixes #26665 by creating a datum for an organ that powers an IPC. Currently given to cyberhearts, cursed hearts, demon hearts, and abductor glands. Makes it so IPCs can always enter rechargers even if they don't have a standard microbattery. It also adds extra feedback for when an IPC is able to be revived.
Not being able to charge when you should be able to is bad, and datumizing organs also makes them generally easier to work with. The extra feedback when being revived is just a really needed change, and since it works when you get a microbattery replaced now that was enough justification to add it in this PR.
Spawned in without instantly dying as IPC, replaced my battery with various demon hearts and was still able to live/charge. 
Used an organ extractor to replace my demon heart with …

Datumizes microbatteries

---

code/game/objects/items/weapons/legcuffs.dm

Makes beartraps actually trigger when people walk over them rather than flying over them.
Bug bad.
Walk over a beartrap.
That hurts.
<hr>
<hr>
:cl:
fix: Beartrap is once again triggered by people on the ground rather than those flying.
/:cl:

[FIX] Beartraps work again

---

code/game/machinery/suit_storage_unit.dm

Adds backpacks to the list of items suit storage units can store.
You take your modsuit, you put it on, and your old backpack you.. drop on the ground? Cmon, put it in the storage unit like a civilized person. 
Put a modsuit into suit storage
Put a backpack into suit storage
<hr>
<hr>
:cl:
tweak: Suit storage units can now hold backpacks.
/:cl:

Suit storage units can now hold backpacks

---

code/modules/admin/admin_ranks.dm

This PR fixes two procs guarded by the `TESTING` compiler define to use the new functions introduced in https://github.com/ParadiseSS13/Paradise/pull/24065.
It's pretty clear no one has used this define at *all* since at least March, and who knows how useful they are, and I'm half tempted to remove it completely and migrate some of its other guards to other defines and better logs, but this works for now.
Code should compile with expected compiler flags.
Built server with `TESTING`, spawned in, ensured I could Advanced Proccall the two procs that were previously guarded.
<hr>
<hr>
NPFC

fix: TESTING-enabled admin rank helper procs

---

code/__HELPERS/bitflag_lists.dm
code/datums/mixed.dm
code/game/machinery/constructable_frame.dm
code/game/objects/effects/misc_effects.dm
code/game/objects/items/devices/taperecorder.dm
code/game/objects/items/weapons/cards_ids.dm
code/game/objects/items/weapons/teleportation.dm
code/modules/atmospherics/machinery/portable/canister.dm
code/modules/client/preference/link_processing.dm
code/modules/client/preference/preferences.dm
code/modules/clothing/suits/armor_suits.dm
code/modules/clothing/suits/suit_storage.dm
code/modules/clothing/under/accessories/storage_accessories.dm
code/modules/clothing/under/costumes.dm
code/modules/crafting/craft.dm
code/modules/library/library_catalog.dm
code/modules/mob/living/carbon/human/species/_species.dm
code/modules/mob/living/carbon/human/species/human_species.dm
code/modules/mob/living/carbon/human/species/unathi.dm
code/modules/mob/living/simple_animal/friendly/farm_animals.dm
code/modules/mob/mob.dm
code/modules/mob/mob_vars.dm
code/modules/mod/mod_types.dm
code/modules/recycling/disposal.dm
tools/ci/check_grep2.py

This PR fixes cases where empty list declarations had whitespace in their parentheses, and adds a check_grep lint to forbid it.
Shit's dumb
Visual inspection
<hr>
<hr>
NPFC

lint: forbid whitespace in empty list decls

---

code/game/machinery/autolathe.dm
code/game/mecha/mech_fabricator.dm
code/modules/research/rdconsole.dm

This PR removes the "RND Production List" feedback key, and replaces it with "station_protolathe_production", only recording production on the station level. It also adds commensurate "station_autolathe_production" and "station_mechfab_production" keys that record their respective machine output.
The original "RND Production List" key was poorly named, incorrectly nested (usually ending up in a key called, literally, `/list`), and wasn't restricted to station level. The lack of similar feedback for other production machines seemed like an oversight. Recording names of output instead of using their types is bad because it makes reverse lookups extremely painful (e.g. trying to find the amount of materials used for "C-Foam cartridge" instead of `/datum/design/c_foam_ammo`).
See above. Also …

blackbox: improve lathe production feedback

---

code/modules/mob/living/brain/robotic_brain.dm

Robobrains removed from cyborgs no longer look inactive because of them being borged in under 60 seconds from being activated.
Posibrains can no longer be offered to ghosts, they are actual players and far too often get stolen from the actual player because someone tried to turn on their microphone.
Robobrains no longer send the person inside them to the void at times
These bugs were bad. Brains looking inactive, or kicking you out of the game, is bad.
Posibrains now refuse to be offered to ghosts, as 90% of the time it is accidental, and the remaining 10% of the time the brain probably wants back into their body but you offer it before it gets in.
Attempt to activate a ghosted posibrain, fail.
Attempt to join into a robobrain with a mob in it, fail.
Borg a robobrain, its icon is fine …

Fix 3 posibrain / robobrain bugs

---

code/modules/mob/living/carbon/human/human_defense.dm
code/modules/mob/living/simple_animal/bot/ed209bot.dm
code/modules/mob/living/simple_animal/bot/secbot.dm

secbots no longer try to detain dead people
humans now have canBeHandcuffed() return TRUE. This was problem A.
Switches  world.time - target.stam_regen_start_time < 4 (was giving negative numbers aka always true) to target.stam_regen_start_time - world.time <= 5 SECONDS (also makes it more consistant of batoning people in time) This was problem B
switches  && target.getStaminaLoss() <= 100 to  || target.getStaminaLoss() <= 100, so the bots will actually keep someone detained in stamina crit. This was problem C
Adjusts last target to 5 seconds from 10, so it can still go after people in stamina crit if it decides to recalculate targets for some reason, which lasts around 10 seconds
A: Secbots not endlessly beating dead people is good, while funny made them less of a problem when emaged or …

makes secbots / ed209's not stupid as a fucking rock

---

code/modules/projectiles/ammunition.dm
code/modules/projectiles/ammunition/magazines.dm

This PR adds a check to make sure the default 7 shell count is not appended to the DL-88 speedcharger, which is supposed to be energy-based and single use.
The speedcharger itself is defined in magazines.dm, with the comment `//yes this doesn't really belong here but nowhere else works`, so I've just added a check to make sure the count doesn't appear instead of touching the speedcharger.
Fixes #26874
Quality of Life, game is literally unplayable if the speedcharger says it has shells
Spawned the speedcharger, examined it, it showed no shell count. Used it to recharge the DL-88, still no shell count.
<hr>
<hr>

[FIX] Prevent Shell Count From Appearing on DL-88 Speedcharger

---

_maps/map_files/RandomRuins/SpaceRuins/ussp.dmm
code/game/objects/effects/spawners/random/trash_spawners.dm
code/game/objects/items/trash.dm

Adds a selection of casings for use in mapping:
* Buckshot, slugs, rubbershot, beanbag, dragonsbreath, stun.
* small, large, and .50 cal bullet casings.
* Spent IK casings.
The USSP station ruin has been remapped with these new spent casings, replacing the varedits it was previously using.
Trash spawners can spawn any of the new casings.
Allows mappers to place down randomly scattered casings without needing to varedit. The random offset and rotation makes them actually look like they've been shot. Good for environmental storytelling.
Spawned into USSP ruin, saw the cartridges were now randomly scattered.
Mapped in a pile of all the casing types, they all got scattered on their tiles randomly.
<hr>
<hr>
:cl:
tweak: mapped-in spent casings are now randomly scattered.
add: Trash spawners …

Adds a Collection of Spent Ballistic Casings With Random Rotation and Offsets

---

code/game/objects/items/devices/radio/headset.dm
code/game/objects/items/weapons/storage/backpack.dm
code/modules/clothing/head/helmet.dm
code/modules/clothing/spacesuits/ert_hardsuits.dm
code/modules/clothing/suits/armor_suits.dm
code/modules/clothing/under/centcom.dm
code/modules/mod/mod_theme.dm

Adds and rewrites a lot of descriptions and lore associated with ERT equipment.
lore
also changing the modsuit descriptions is good because we ripped them from tg and they suck
- entered game
- spawned gear
- observed gear
- success
<hr>
<hr>
:cl:
tweak: Rewrote a lot of ERT lore
/:cl:

[LORE] Reasonably Sized ERT Lore Drop

---

code/game/objects/items/weapons/storage/boxes.dm

Adds an R&D server circuit, R&D server controller circuit, scanning module, and cable coil to the R&D crate.
The recent R&D rework has made the server controller and server into required components of R&D. Simply destroying either along with the single spare circuit in tech storage permanently removes R&D from the round. This crate will once again allow R&D to be restarted even if science and tech storage are vaporized completely.
Spawned in, ordered the R&D crate. Built everything, linked everything, did some science. It all worked.
<hr>
<hr>
:cl:
tweak: The R&D crate from cargo now includes the components to make an R&D server and server controller.
/:cl:

Updates the Research & Development Crate to Include Components for the R&D Server and Server Controller

---

code/datums/uplink_items/uplink_traitor.dm
code/modules/paperwork/pen.dm

Replace Love in love pen with Pax, who give target full pacifism, instead of force status + reagent who just names "love" and doesnt do something to avoid you from death. Added reagent regeneration, so you can use it far more than 4 times for 20 TC.
Cheap stuffs always was the most funny or cursed ones, yet the pen only give you limited time for do something. Now with removing original author restrictions and adding regeneration, you can use it AND for easy kills without resistance AND for trolling sec who cant kill someone. Counter to this is pretty easy to obtain and dont restrict you from stunning opponents, so it will remain niche item. But now you can use it for fun, because it never deplete fully, and more fun = more joy to play. In my opinion, this pen now have all he need to be …

TWEAK: Love pen now higly peaceful

---

code/modules/power/engines/supermatter/supermatter.dm

Mole crushing the SM now generates anomalies in the same way that high EER engines do.
Mole crush engines give far too high of a reward for virtually zero risk. This brings them in line with the other high power generation option.
mole crushed an engine, confirmed all three types of anomalies generated. 
<hr>
<hr>
:cl:
tweak: Mole crush SMs now generate anomalies 
/:cl:

Mole crush SMs now generate anomalies

---

_maps/map_files/stations/emeraldstation.dmm

Adds an intercom, newscaster, and two emergency wall lockers to the arrivals shuttle.
Adds entertainment monitors to more public areas around the station, and in the engi break room.
missing items are bad
map boots up fine 
<hr>
<hr>
:cl:
add: Added some wall items around the diagoras
/:cl:

Adds some wall items to Diagoras

---

code/modules/mod/mod_types.dm

Pins firefighting tank by default in atmos and advanced modsuits
This module is rarely used and it seems to be unknown to many players. I've often seen atmos techs or CEs use a fire extinguisher while wearing their modsuit.
Pinning it should make it more obvious it exists.
- Put on an advanced and an atmos modsuit and saw the button appear
<hr>
<hr>
:cl:
tweak: Pins firefighting tank by default in atmos and advanced modsuits
/:cl:

Pins firefighting tank by default in atmos and advanced modsuits

---

code/game/objects/structures/window.dm

Title. These gain the same protection as standard shuttle windows
As these windows are used on shuttles, this makes behavior consistent.
Tested construction/deconstruction. Tested if cult constructs could break them (no), tested if green terror could break them (no), tested if purple spider could break them (yes), tested if axe could break it (yes). Panic at the horrors of buildmode.
<hr>
<hr>
:cl:
Fix: Makes Plastitanium windows resistant to large mobs one hit break abilities
/:cl:

Makes Plastitanium windows resistant to large mobs one hit break abilities

---

code/game/objects/items/weapons/storage/storage_base.dm

This PR fixes items having MOUSE_OPACITY_OPAQUE after dropped by burned out container. Now they have their mouse_opacity reset which would lead them to have normal MOUSE_OPACITY_ICON in most cases.
If you pick up an item like that and drop it, its mouse_opacity will be resetted anyway so that PR just fixes it not being resetted by the burnout.
Bugs bad.
Compiled, burned container, made sure mouse opacity gets resetted.
<hr>
<hr>
:cl:
fix: Fixed items from burned out container having too big mouse opacity.
/:cl:

Fix: Mouse Opacity of items dropped by a burned container should be Icon

---

code/game/objects/items/weapons/thurible.dm

Makes sure that a division by zero does not happen, since mobs_to_smoke length can be zero if you swing the thurible next to no one.
Fixes the following runtime.
* Ignited the thurible (full of holy water) and swung it next to a skrell for a while, then went to a place without any carbons nearby, no runtime noticed.
<hr>
<hr>
NPFC

Fixes a thurible runtime

---

code/defines/procs/announcer_datum.dm
code/game/objects/items/weapons/cards_ids.dm
code/modules/newscaster/obj/newscaster.dm

Fixes #26357 (Newscaster does not recognize IDs inside wallets)
Simplyfies newscaster/proc/get_scanned_user
Moves proc/GetNameAndAssignmentFromId from a comms console related file to the ID card file
One less bug
Makes a proc that's universally useful more discoverable
Created news channel with empty wallet in ID slot. Manage channel was available.
Put on ID directly. Manage channel was greyed out.
Put on ID in wallet. Manage channel was greyed out.
Created news channel with ID in wallet. Manage channel was available.
IIRC put on ID directly and manage channel was available. (I should have written this while I was testing.)
Removed ID. Manage channel was greyed out.
Logged into comms console with debugger ID. Made announcement. Job was shown correctly.
Same with ID in wallet.
Tried …

Fixes Newscaster Treatment of Wallets

---

code/modules/mob/living/living.dm

beam hurty rather  than healy
beam lights you on fire vs just oiling you up
ok as funny as being invicible to burn damage is this thing is supposed to kill you
beamed myself
fucking died on fire
<hr>
<hr>
:cl:
fix: Fixed the PTL laser not working right
/:cl:

[s] fixes this bloody laser

---

README.md

Updates readme links to point to the devdocs where appropriate.
Removes a section that has no equivalent anymore.
The new devdocs site is great, we should be directing users to it.
<hr>
<hr>

Update readme to use devdocs site for links to guides

---

code/game/objects/items/weapons/storage/boxes.dm
code/game/objects/items/weapons/storage/fancy.dm
code/modules/projectiles/ammunition/ammo_casings.dm

- Gives holy dart boxes their sprite back (oops)
- Renames `rubber shot` to `rubbershot shell`
- Renames the `[shell type] darts` to `[shell type] dart`
- Fixes the examine of shotgun shell boxes
These should work, and with a proper examine, the names would stand out very much (and be outright wrong sometimes)
Examined boxes with different shells, saw that the examine worked properly
<hr>
<hr>
:cl:
fix: Holy water dart boxes have a sprite again
fix: Shotgun shell boxes have a proper examine now
fix: Some shotgun shells have had their typos removed
/:cl:

Fixes some shell box issues

---

code/game/objects/structures/crates_lockers/closets.dm
code/game/objects/structures/crates_lockers/closets/secure/personal.dm

Personal lockers can be locked and unlocked again
Also fixes the closing sound playing twice when closing a closet.
Fixes: #27130
Bug bad.
Swipe my ID card on a locker, it unlockes.
Swipe it again, it's now locked.
Make sure not to use a captain's ID since it apparently can unlock all personal lockers.
<hr>
<hr>
:cl:
fix: Personal lockers can be opened and closed again.
fix: You can no longer hear a closet close twice.
/:cl:

[FIX] Personal lockers fix

---

code/modules/mob/living/silicon/ai/ai_mob.dm

Makes it so the AI can no longer toggle floorbolts while dead.
You're not supposed to be able to do stuff when you're deceased.
Try to toggle floorbolts after dying as an AI.
Floorbolts are not toggled.
<hr>
<hr>
:cl:
fix: AI can no longer toggle floorbolts while dead
/:cl:

[FIX] AI can no longer toggle floorbolts while dead

---

code/modules/supply/supply_console.dm

People with account security set to pin required can once again order through the cargo console.
Fixes: #27059
You should probably be able to put in your pincode when prompted for it.
Try to order something through cargo.
I am prompted for my pincode.
I enter my pincode.
The order goes through successfully.
<hr>
<hr>
:cl:
fix: Cargo console pincode prompt works again
/:cl:

[FIX] Cargo console pinnumber prompt works again

---

code/modules/clothing/under/color.dm

Stops assistants from randomly spawning with jumpskirts (an oversight on my behalf).
Also prevents the iconless `/obj/item/clothing/under/color/random` from spawning again.
I assume people prefer the more neutral option by default.
I spawned `/obj/item/clothing/under/color/random` a ton of times.
<hr>
<hr>
Bmon
:cl:
fix: Assistants no longer have a chance to spawn with jumpskirts.
/:cl:

Fixes assistants spawning with jumpskirts

---

code/game/objects/effects/anomalies.dm

Fixes the gravity generator not going down when a gravity anomaly detonates
Fixes https://github.com/ParadiseSS13/Paradise/issues/27160
- Spawned a gravity anomaly and waited for it to detonate, affecting the generator this time.
<hr>
<hr>
:cl:
fix: Fixes the gravity generator not going down when a gravity anomaly detonates
/:cl:

Fixes the gravity generator not going down when the gravity anomaly detonates

---

code/datums/wires/robot_wires.dm
code/modules/mob/living/silicon/robot/robot_death.dm
code/modules/mob/living/silicon/robot/robot_life.dm
code/modules/mob/living/silicon/robot/robot_mob.dm
code/modules/mob/living/silicon/robot/robot_update_status.dm

Fixes borg code to not try to toggle it's camera on every tick.
Borgs actually turn off their camera when they die, this was broken.
Borgs turn on their camera when they are revived, if the wire is not cut. This is re-added, replacing the life check.
Pulsing a borgs camera turns it off.
This fixes many problems, but yes, a dead borg should have it's camera off, and it should be done properly, not by setting camera status to false, which creates other issues.
killed borgs, revived borgs, pulsed wires, cut wires, mended wires.
<hr>
<hr>
:cl:
fix: Fixed borg cameras not turning off when they died.
fix: Fixed borg cameras not turning on or off half the time you try to toggle them.
fix: Pulsing a borg's camera turns it off properly now.
/:cl:

Fixes borg cameras

---

code/game/objects/items/devices/scanners.dm

Fixes a machine analyzer runtime that happens when you use it on a mech/structure that has less than 100% obj_integrity.
You can no longer use the machine analyzer on mechs/structures as it was unintended.
Fixes the following runtime:
- Tried to use the machine analyzer on mechs and structures, couldnt.
<hr>
<hr>
:cl:
fix: You can no longer use the machine analyzer on structures/mechs, as it was unintended
/:cl:

Fixes a machine analyzer runtime

---

code/modules/martial_arts/krav_maga.dm

Added indestructible flags to warden gloves, since they're a high-value target
The Warden's Krav Maga gloves can no longer be destroyed by explosives, lava, acid, or other methods of removing items without dusting them.
We've decided that high-value items should be difficult to destroy, only allowing them to be dusted in the Supermatter Crystal or via Supermatter Shard. This prevents someone from redtexting if the Warden is blown up via maxcap, killed via acid tomato, or otherwise falls afoul of a hijacker.
Opened up local, blew up all high-value target storage machines with C4, verified that all high-value items survived the blast except for the Krav Maga gloves, which were destroyed. Also maxcapped the CMO office and Warden office to verify that this was not a C4-specific interaction. …

Warden gloves made indestructible

---

_maps/map_files/stations/deltastation.dmm

Fixes #27213 
Good for code, and bugs bad
I went to the Kerberos science Break Room and tried opening it with scientist, roboticist, IAA, Research Director, Captain's Spare, Syndicate Researcher, and Virologist ID cards. The Syndicate Researcher and Virologist did not have access, everyone else did.
<hr>
<hr>
:cl:
fix: Fixed Kerberos science Break Room access
/:cl:

Fixes Kerberos science Break Room access

---

code/game/objects/items/weapons/powerfist.dm
code/game/objects/objs.dm
code/modules/mob/living/living.dm

- Makes the powerfist respect armor
- Makes wallbashing respect armor
The powerfist fully ignores armor. This makes it just as effective to fight it with riot armor and as if you were naked. This now works intuitively with the rest of the armor system.
The wallbashing change is included here because they go hand in hand with the powerfist changes.
<hr>
<hr>
:cl:
tweak: the Powerfist now respects armor
tweak: wallbashing now respects armor
/:cl:

Makes powerfist and wallbashing not ignore armor

---

code/modules/station_goals/bsa.dm

BSA will no longer reload if the APC powering it doesn't have enough energy, or if the APC doesn't exist.
Less bug more good
- Made a BSA in an area where the APC didn't have enough energy to reload it and the BSA did not reload
- Gave the APC cell enough energy to reload the BSA. BSA reloaded
- Demonstrated the power of flextape
<hr>
<hr>
:cl:
fix: BSA now checks if it has enough energy for a reload before reloading
/:cl:

BSA now checks if the APC has enough power to reload

---

code/game/gamemodes/miniantags/morph/morph_event.dm
code/modules/antagonists/_common/antag_spawner.dm

This PR makes morphs spawn inside vents, instead of the pre-mapped spawn points used for old xenomorphs. It uses basically the exact same code as terror spiders and blob mice.
It's how all the other ventcrawling antagonists work since #19391, and with the otherwise unused xeno spawns it uses now I've seen a morph spawn in an enclosed maintenance room with no way to safely get out. I imagine it was just a small oversight of the original PR.
Forced a morph midround, it spawned in a vent.
Used a wizard morph summoner, it spawned in a vent.
<hr>
<hr>
:cl:
fix: Morphs now properly spawn inside vents
/:cl:

Morphs now spawn in vents

---

_maps/map_files/RandomRuins/SpaceRuins/syndie_space_base.dmm
code/game/machinery/camera/camera.dm
code/game/objects/items/devices/camera_bug.dm
code/modules/mob/living/silicon/ai/freelook/chunk.dm

AI can no longer see through camera bugs.
Add a variable to cameras that prevent cameras being added to the camera chunk system. Use this on cameras you don't want the AI to see through
AI can no longer see through cameras on the syndicate space base.
Please sir let us use camera bugs without instantly outing ourselves.
tested camera bugs worked
tested could see through them
tested ai could not see
tested advanced camera console could not see
tested that normal cameras worked
tested could not track through camea bug cameras as AI
<hr>
<hr>
:cl:
fix: AI can no longer see through camera bugs or to the syndicate research base
/:cl:

[s] AI can no longer see through camera bugs or to the syndicate research base

---

code/game/objects/structures/flora.dm

This PR fixes the menu icon for randomly spawned plants.
Right-click menu icons should be as accurate as possible when BYOND will let us get away with it.
Checked plants on centcomm as above.
<hr>
<hr>
:cl:
fix: Potted plants should now show their proper icon in the right-click menu.
/:cl:

fix: update random plant menu icon

---

code/game/objects/items/weapons/explosives.dm

c-4 no longer blows up your backpack, boxes, or modsuits, instead goes into them
It's time to remove some soul, and not crush newer players hopes and dreams when they attach their c4 to their backpack / nukie modsuit instead of putting it in it, destroying all their items
tried to put c4 into a belt / backpack box by clicking on its sprite.
it didn't blow up on me.
c4 on other things worked as expected
<hr>
<hr>
:cl:
fix: c-4 no longer blows up your backpack, boxes, or modsuits
/:cl:

c-4 no longer blows up your backpack, boxes, or modsuits

---

code/modules/lavaland/caves_theme.dm

This PR reduces the probability of boulders spawning on Blocked Burrows from prob(9) per cave tile to prob(7). prob(8) did not seem to make a substantial difference, still allowing huge clumps of boulders.
This still presents a challenge for miners in terms of navigation, placing shelters, etc., but is not as ridiculous as the current spawn rate.
I'm not going to run stats for this, you're just going to have to trust me that 7 is less than 9.
<hr>
<hr>
:cl:
tweak: The rate of boulder spawns on the Blocked Burrows cave theme has been slightly reduced.
/:cl:

tweak: slightly reduce spawn rate of boulders on blocked burrows

---

.github/CODEOWNERS

Removes my ownership of the unit tests module, and `check_grep2.py`.
I shouldnt be the review bottleneck for this. I dont need to stare at these with a watchful hawk's eyes, these are fine now.
N/A
N/A
<hr>
N/A

Unhands some codeowners stuff

---

code/modules/station_goals/bluespace_tap.dm

This PR removes a typo from the bluespace tap file which was causing the creation of a distinct type. This was almost certainly some truncated text from the defines above it.
Fixing typos good.
See above.
<hr>
<hr>
NPFC

fix: typo making unintentional type

---

code/modules/mining/equipment/mining_charges.dm

This PR fixes mining charges not working on non-ore rock, a regression caused by https://github.com/ParadiseSS13/Paradise/pull/27043.
Bugfix.
https://github.com/user-attachments/assets/0fea2725-e32f-4816-a0ce-462f71c2c0b5
See above.
<hr>
<hr>
:cl:
fix: Mining charges properly detonate all rock.
/:cl:

fix: mining charges work again for non-ore rock

---

code/modules/surgery/limb_reattach.dm

When porting surgery sounds in https://github.com/ParadiseSS13/Paradise/pull/26884 I forgot to add surgery sounds for limb reattachment like an idiot.
This is now fixed.
Fixes a missing surgery sound.
Spawned in-game
Tested the surgery to make sure the sound worked.
<hr>
<hr>
:cl:Bmon
fix: Limb reattachment now has surgery sounds.
/:cl:

Fixes missing surgery sound

---

code/modules/power/engines/supermatter/supermatter_event.dm

Makes previously less impactful SM events more impactful
C/D class events now add MUCH more gas to the engine, heat penalty threshold decease doubled for C3.
B Class events now cause double their original effect
S-Laminate now causes 25x heat output, 25x waste output (not as much as you think) and causes a fairly large EMP pulse upon starting. 
Most of our events you can completely ignore, this makes them slightly more impactful.
manually test each modified SM event by commenting out all the others. Cry. regret datumizing them, repeat.
<hr>
<hr>
:cl:
tweak: Makes some SM events more dangerous
/:cl:

Buffs SM Events

---

code/game/gamemodes/wizard/spellbook.dm
code/modules/antagonists/_common/antag_spawner.dm

The pulse demon summoner advises against summoning the demon in maints, as it will literally shock you to death in 3 seconds if you are not shockproof or on a covered turf when you summon this.
See above. While generally people know "summoning a demon might be bad", there is a difference between getting stabbed in the back 2 minutes later, and being dead before you know what hit you, lmao.
I checked the spellbook, tried to summon the demon
<hr>
<hr>
:cl:
tweak: Pulse demon summoner warns the wizard better so they don't die to shocks 2.8 seconds after summoning the demon
/:cl:

pulse demon summoner warns better

---

code/game/objects/items/devices/radio/radio_objects.dm
code/game/objects/items/weapons/stunbaton.dm
code/modules/mob/living/living_defines.dm

Stops flayers from permanently disabling radios
This should not happen
<hr>
<hr>
:cl:
fix: Fixed flayers sometimes permanently stopping headsets from working
/:cl:

[s] Fixes flayers borking radios sometimes

---

code/modules/mob/living/default_language.dm
code/modules/mob/mob.dm

Fixes flavor text not being viewable. Also fixes not being able to reset the default language.
Oversights bad
Could view the flavorful text. Could reset my default language.
<hr>
<hr>
:cl:
fix: You can view other mob's flavor text again
fix: You can clear your default language
/:cl:

Fixes flavor text not being viewable

---

code/game/machinery/computer/communications.dm

Fixes #27272
Bug bad
Made a classified announcement, and then a public announcement. Both worked correctly.
<hr>
<hr>
NPFC

Fixes Admin Comms Consoles

---

code/game/objects/items/weapons/bio_chips/bio_chip_death_alarm.dm

Adds small cooldown(0.1 seconds) to the death alarm emp message to prevent spamming when ion scatter shot is used.
Having common flooded with 7 death alarm messages is really not ideal.
Compiled, shot a target with a death alarm with a regular ion rifle, no dropped messages noticed.
shot a target with ion scatter, only one message was sent per shot
<hr>
is very tweaky fix, lemme know if i should've gotten approval first.
<hr>
:cl:
fix: ion scatter no longer floods common radio with death alarm messages if the target has one
/:cl:

Death alarms have a SLIGHT cooldown on when they send another message

---

code/modules/mob/living/carbon/alien/alien_base.dm
code/modules/mob/living/living.dm

- Xenos now bleed with lime blood color, instead of red.
- Xenos now doesnt have neutral fraction, as any other biohazard(blod, spooder, demons). Now its only alien.
Red blood is not good for immersion
Neutral xenos are not exist in this world
Neutral xenos - the only biohazard you have. This is clearly an oversight
Before update:
After fix:
Spawn xeno, kill him. drag him, see the green blood as expected.
Spawn goliath, he attack xenos. Kill him, revive him with lazarus, now he is neutral but still attack xenos, as he do with spiders or blobs.
<hr>
<hr>
:cl:
fix: Xenomorph blood is green again
tweak: Neutral mobs are now hostile to xenomorphs, similar to other biohazards
/:cl:

[FIX] Fixes for xenomorphs

---

code/game/gamemodes/miniantags/abduction/machinery/experiment.dm

Fixes #27276 
Fixing this also means you have a 50% chance of not escaping the abductor experimentor machine, with the oversight you could guarantee an escape by having 10 escape attempts that all rolled at nearly the same time and electrify/sedate have a delay that did not cancel the near-instant subsequent attempts.
Oversight bad
I was inside an abductor experimental machine and held a movement button to get out. could only start one attempt and would cancel my attempt if I attempted a second attempt two seconds after the first. I did roll all three different outcomes to make sure I did not mess anything up.
<hr>
<hr>
:cl:
fix: Fixed abductor experimentor escape spam
/:cl:

You can only have one active abductor experimentor escape at a time

---

code/modules/clothing/head/job_hats.dm

Fixes item_state name for chef hat
You won't hold chef outfit while hold chef hat
Fixes #27322 
I see chef hat in hands on screenshot above
<hr>
<hr>
:cl:
fix: You will no longer see the chef outfit in your hands when you hold the chef hat
/:cl:

Fix chef hat inhands sprite

---

code/modules/games/cards.dm

Fixes the text related to turning your card in hand.
Fixes an issue.
I did not test but I believe such small change doesn't need any testing.
<hr>
<hr>
:cl:
spellcheck: Fixed a typo in card hand turning.
/:cl:

fixes small mistake in card hand turn text

---

code/modules/mob/living/carbon/carbon_procs.dm

Being in a cryogenic tube no longer shows you all the pipes connected to it, even when asleep or when the pipes are under the floor.
My immersion is restored.
Hop in a cryogenic cell.
I can't see all the pipes.
Crawl into a vent.
I can see pipes.
<hr>
<hr>
:cl:
fix: You can no longer see all pipes while in a cryocell
/:cl:

[FIX] You can no longer see all pipes while in a cryocell

---

code/modules/tgui/modules/appearance_changer.dm

Fixes missed thing
Bugs bad
Fixes #27338
Changed runechat color in the mirror, work's fine
<hr>
<hr>
:cl:
fix: You can again change runechat color in appearance changer (Mirror)
/:cl:

Fix Appearance Changer runechat color change

---

code/modules/mod/modules/modules_supply.dm

Stops mining grenades from causing goliaths to look alive when hit.
Fixes: #27306
Goliaths should no pretend to be alive when they are dead.
Shoot a dead goliath with a mining grenade
They do not come to life.
<hr>
<hr>
:cl:
fix: Goliath no longer seems to come to live from mining grenades
/:cl:

[FIX] Goliath no longer seems to come to live from mining grenades

---

code/modules/food_and_drinks/food/condiment.dm
code/modules/food_and_drinks/kitchen_machinery/kitchen_machine.dm

Prevents people from adding reagents to a kitchen machine that is currently operating, since this would cause the reagents to be wasted.
Fixes: #27270
Currently it's easy to accidentally waste reagents adding them to a running machine.
Try to add reagents to a candy maker that is currently on.
Can't add them
<hr>
<hr>
:cl:
fix: Kitchen machines no longer accept reagents while running
/:cl:

[FIX] Kitchen machines no longer accept reagents while running

---

code/modules/mob/living/carbon/carbon_update_icons.dm
code/modules/mob/living/living_status_procs.dm

Fixes resting off-set for non-carbon living mobs.
Reverts part of #19903 
I was wrong in my original PR about what was causing this issue to happen. It has nothing to do with the `pixel_y` being duplicated in `update_transform`.
While `pixel_y = pixel_y` was a completely useless part of the `update_transform` proc it red herringed me into thinking that was the cause of the issue.
Simply put, the actual issue was that on a `/mob/living/` level another `PIXEL_Y_OFFSET_LYING` was being applied to `pixel_y`. This breaks resting for non-carbons and once upon a time broke resting for carbons by applying `PIXEL_Y_OFFSET_LYING` twice to `pixel_y`.
The old fix was to completely ignore `pixel_y` and hard set the resting offset to `PIXEL_Y_OFFSET_LYING`. While this worked, it isn't ideal if you ever …

Resting offset fix 2

---

code/_onclick/hud/fullscreen.dm
code/game/objects/items/weapons/bio_chips/bio_chip_stealth.dm
code/modules/surgery/organs/augments_internal.dm

Stealth box is now a fullscreen, should no longer disjoint from the stealth box.
Bynat now will show  the beam if you are in a locker or mech or stealth box
Disjointing bad
Invisible emaging bad
Emaged in locker
emaged in stealthbox
Tried as hard as possible to disjoint the stealth box image from mob, could not
<hr>
<hr>
:cl:
fix: Stealth box image should no longer disjoint from the stealth box.
fix: Bynat will make a beam from the locker or mech or stealth box you are in if you emag something while in one
/:cl:

[s] Stealth box fix

---

code/game/objects/items/weapons/storage/bible.dm

Nerfs bible healing - Currently the bible heals 10 brute and burn damage per limb. At it's extreme, this means one hit could heal up to 110 damage of each type (Assuming the damage is equally spread over all limbs)
Change:
Bible hits now only heal 10 brute and burn overall, rather than per limb.
The bible can currently heal way too much per hit, potentially 110 points of instant healing is problematic.
Smack myself with a bible.
It hurts a little less, but I am not completely restored.
<hr>
<hr>
:cl:
tweak: Bible healing was reduced from 10 brute and burn per limb to 10 brute and burn overall.
/:cl:

[BALANCE] Nerf bible healing

---

code/game/objects/items/weapons/weaponry.dm

Baseball resets its deflectmode to FALSE when the item is dropped. Why? Because ~~I got robusted~~ picking up the item is not notifing that the user is apparently in deflect mode.
Also bigger message, that you can't attack.
More logic
<hr>
:cl:
tweak: Baseball bat resets its deflectmode when is dropped. Now after disarming your opponent and picking up their baseball bat, you will be able to hit them, even if they entered deflect mode before being disarmed.
tweak: Baseball bat now has louder message that you can't attack in deflect mode.
/:cl:

Baseball resets deflectmode on dropping

---

_maps/map_files/stations/boxstation.dmm
_maps/map_files/stations/cerestation.dmm
_maps/map_files/stations/deltastation.dmm
_maps/map_files/stations/emeraldstation.dmm
_maps/map_files/stations/metastation.dmm

Replaces all shelves labeled "adult" to "romance"
Replaces the random shelves on cerestation with the standard empty labeled ones.
Also slightly shifts the organization of bookshelves.
We do not tolerate adult content, so having a library shelf for it seems incorrect.
Also consistency is good.
Complied. 
<hr>
<hr>
:cl:
tweak: Changed "Adult" shelves in the library to "romance"
tweak: Replaced random bookshelves in cerestation library to standard empty labeled ones for consistancy.
/:cl:

Librarian bookshelf tweaks

---

code/modules/power/cables/cable.dm

Changes the multitool cable pulse (the one that shows you grid power) from 'danger' to 'notice', thus stopping it from spitting out its results in the Combat Log.
Wondering why you aint seeing the grid power coz its spitting it out in the combat log is annoying.
Compiled master, pulsed cable, went in combat log.
Changed message, compiled branch, pulsed cable, went in chat.
<hr>
<hr>
:cl:
tweak:Multitool cable pulses no longer outputs in the combat log.
/:cl:

Multitool cable pulse message is now outputs in regular chat rather than the combat log

---

code/game/machinery/machinery.dm

this is a funny fix
Following the laws of physics good
yes
<hr>
<hr>
:cl:
fix: You can no longer break the laws of thermodynamics
/:cl:

[s] yes ghmm

---

code/game/objects/items/weapons/grenades/chem_grenade.dm
code/game/objects/items/weapons/grenades/grenade.dm

Grenades now once again explode 15% of the time you are shot with them in hand, when it is not a stamina attack. This has been broken since parrying.
Fixes the formatting of it so it doesnt do the bullet (lowertext) or ... hit Ash Ketchum's the grenade casing.
Make it delete the grenade if it doesn't delete itself, so you do not get people holding grenades as endless passive shields.
I don't think it would happen, but grenades shouldn't be left over. It was just blown up after all!
Grenades should explode on hit sometimes as intended.
Weird messages are bad
Set up a turret to fire at me a lot.
Picked up grenades and grenade casings and had them explode.
Compile over and over again till I was happy with the message.
<hr>
<hr>
it's a fix
:cl:
fix: Fixes grenades not exploding 15% of the …

Fixes grenades not exploding 15% of the time you are shot

---

code/game/objects/items/tools/welder.dm

fixes #27355 
Allows the welder to set flammable people on fire when attacked and lit.
Makes the welder consistent with other fire sources and itself. Repairing a flammable mob will set it on fire (existing functionality) thus it doesnt make sense that an attack wont.
https://github.com/user-attachments/assets/6f72c229-21dd-4980-b3b0-27d5011ca8d3
<hr>
<hr>
:cl:
fix: Lit welders will now set flammable mobs on fire
/:cl:

Fix: Lit welders will now set flammable people on fire

---

code/game/gamemodes/miniantags/abduction/machinery/experiment.dm

Removes the delay in the abductor experimentor electrocution as this can cause runtimes, and changes the sedate chemical in said machine to pancuronium
Runtimes bad, the runtime in question happened when the electrification response happened and the mob was removed from the experimentor less than 1 second after the electrification started. 
The ether took 80 seconds to sedate whereas pancuronium only takes 20 seconds to paralyse, which is conveniently the same as the escape attempt timer
I went into the experimentor and tried to escape, I was electrocuted instantly when electrocuted, and I was given pancuronium when injected
<hr>
<hr>
:cl:
tweak: Replace ether with pancuronium in the sedate-response to escape attempts from the abductor experimentor
fix: Fixed a runtime caused by a 1 …

Tweaks abductor experimentor slightly and fixes a runtime

---

code/game/gamemodes/miniantags/revenant/revenant.dm
code/modules/mob/mob_misc_procs.dm

Gives revenants the ability to speak and hear deadchat.
Revenants are ghosts - why should they not be able to talk with other ghosts? It would also add some fun interactions with ghosts giving advice / chatting with the slightly more corporeal ghost.
As a revenant: 
- Spoke in deadchat
- Listened to others speak in deadchat
- Didn't get prompts to follow people speaking in deadchat
As a ghost:
- Heard the revenant
- Followed the revenant
<hr>
<hr>
:cl:
add: Revenants can now hear and speak in deadchat.
/:cl:

Revenants can hear and speak in deadchat

---

code/datums/components/label.dm
code/modules/food_and_drinks/food/condiment.dm
code/modules/food_and_drinks/food/foods/candy.dm
code/modules/hydroponics/seeds.dm

Fixes #26844, allows condiment bottles to retain their labels, adds COMSIG_ATOM_UPDATE_NAME to the label's signal list.
Bugs should be squished.
1. Get hand labeller.
2. Create new bottle with milk cream using the condimaster.
3. Label the bottle.
4. Transfer reagents in and out of the bottle. Add different reagents, empty the bottle.
5. Ensure the label is maintained throughout the process.
<hr>
<hr>
:cl:
fix: Condiment bottles now retain their labels when reagents are moved in or out of them.
/:cl:

Fixes #26844 - Labeled condiment bottle loses its label when contents change

---

code/modules/mob/living/simple_animal/friendly/butterfly.dm
code/modules/mob/living/simple_animal/friendly/cat.dm
code/modules/mob/living/simple_animal/friendly/diona_nymph.dm
code/modules/mob/living/simple_animal/friendly/farm_animals.dm
code/modules/mob/living/simple_animal/friendly/mouse.dm
code/modules/mob/living/simple_animal/parrot.dm
code/modules/mob/living/simple_animal/posessed_object.dm

This PR migrates all overrides of /New for simple animals to /Initialize.
See #27261.
<hr>
<hr>
NPFC

refactor: /New -> /Initialize §1: simple animals

---

code/game/objects/items/weapons/stunbaton.dm

Fixes #27411.
Bricking a borg's baton is bad.
Spawned a borg.
Emagged them.
Assumed direct control.
Tried to unscrew baton.
Could not.
SUCCESS!
<hr>
<hr>
:cl:
fix: Borg stun arms cannot be unscrewed to remove the cell.
/:cl:

[FIX] Makes Borg Stun Arm `screwdriver_act()` return `FALSE`.

---

code/datums/revision.dm

Fixes this
The above looks wank
See main desc
None, I aint spinning up TGS for a 3 line change
<hr>
<hr>
fix: Fixed the TGS version not showing right in Get Revision Info
/:cl:

Fixes revinfo

---

code/modules/antagonists/cult/team_cult.dm

Every 5 minutes, the rise and ascend thresholds are recalculated, to account for people leaving the round / joining late
This helps a lot when a lot of people leave the game, or a lot of people latejoin
**This image should say `-1` but I accidentally closed my instance before taking a screenshot**
See above
<hr>
:cl:
fix: Cult will now be a little more consistent when a lot of people latejoin / leave the round early
/:cl:

Recounts `rise_number` and related variables every once in a while

---

_maps/map_files/stations/metastation.dmm

Space grilles now have lattice under them. Not sure who removed them but they were definitely there on the original port of Meta from /tg/ that I did. This makes solars and other space details not look ugly and matches with Boxstation. [1]
I re-did a tiny bit of the grille work around Security so it's not hugging the wall anymore. [2]
Areas now lean towards maintenance when they can, this mainly is for radstorms but also just because maintenance doors should be in maintenance. Most maintenance areas are already set up like this on Meta, it's just that newer additions neglected this. Honestly should be standard for all maps. [3]
Floor colouring around the aft hall/science fixed. There used to be a desk and table where the coloured tiles were but that was removed and the coloured floor …

Metastation Megafix

---

code/modules/reagents/chemistry/reagents/drinks_reagents.dm

Triple citrus now ticks with `on_mob_life` instead of only on ingest
Helps set it straight with like 95% of other drinks.
The toxin healing is slightly lower than Doctor's Delight, which takes 1 more ingredient to make
Drank some triple citrus without any runtimes
<hr>
<hr>
:cl:
tweak: Triple citrus now heals with metabolism instead of only on ingestion
/:cl:

Makes triple citrus tick on life instead of ingest

---

code/datums/uplink_items/uplink_nuclear.dm
code/game/objects/items/weapons/storage/backpack.dm

Currently theres 3 bulldog "bundles":
- "Bulldog Bundle" (1 bulldog shotgun, 2 slug mags, 1 chame thermals)  = (45 TC) 
- "Bulldog Ammo Bag" (6 slug mags, 2 buckshot mags, 1 dragons breath mag)  = (60 TC) 
- "Bulldog XL Ammo Bag" (1 slug mag, 1 buckshot mag, 1 dragons breath mag)  = (60 TC) (magazines are twice the size)
The only good one is the Bulldog ammo bag. This PR changes them to be:
- "Bulldog Shotgun" (1 bulldog shotgun)  = (15 TC) 
- "Bulldog Ammo Bag" (No Changes)
- "Bulldog XL Ammo Bag" (3 slug mag, 1 buckshot mag, 1 dragons breath mag)  = (60 TC) (magazines are twice the size)
Basically replacing the bundle with just the shotgun for cheaper, and adding 2 more slug mags to the XL ammo bundle.
The descriptions of each were also altered to make it more clear what they are.
The …

Unfucks Bulldog Bundles

---

_maps/map_files/RandomRuins/SpaceRuins/ussp.dmm

This PR removes a stray cig vendor from USSP space introduced by #27017. No idea how I did this, probably an accidental click.
Fixes mapping regression.
Before:
After:
<hr>
<hr>
:cl:
fix: A stray cigarette vendor outside the USSP ruin has been removed.
/:cl:

fix: remove stray cig vendor from USSP

---

code/game/objects/items/weapons/storage/uplink_kits.dm

Replaces the 40 TC Energy Sword in the Hacker bundle with the 20 TC Razorwire Spool Arm Implant Autoimplanter.
Literally this is miles cooler than budget lightsabers
But seriously - Energy swords always felt a bit out of place in a bundle for a Hacker, and the mono/razorwire is a really cool weapon for the Cyberpunk universe, which really fits the whole Combat Hacker theme along with the Binyat.
The razorwire's negative armour penetration also solidifies the Hacker bundle's role as a covert operator - You are a hacker who finesses your way through wiliness and guile, not brute force. If heavily armoured foes come your way you aren't supposed to take them head on.
It compiles fine.
Bought bundles with TC until I got Hacker
Verified that there are no Energy Swords, and that the Razorwire …

Buffing the Hacker bundle by nerfing it

---

code/__DEFINES/misc_defines.dm
code/datums/chatmessage.dm
code/modules/mob/mob_misc_procs.dm
code/modules/mob/mob_say_base.dm

Observers will now have runechat appear above their heads.
- It will not be active if they're orbitting someone to prevent from 20 people's runechats overlapping
- Admins using Dsay verb will not have runechat above their heads
- Non-observers cannot see the runechat, unless they would normally hear them and the ghosts are visible (i.e. a ghost bar person speaking to a ghost that is revealed by a wizard's show ghosts spell.)
It was previously not done because of performance issues, but I have not seen the runechat subsystem have noticable lag in a long time, so this is worth at least a TM.
Makes it easier to talk to people in dchat without missing their messages
See above.
Need to test what ghost bar occupants runechat looks like if they speak onto the deadchat radio.
<hr>
<hr>
:cl:
add: …

Deadchat now has runechat

---

tools/pr_sql/27257/update_script.sql

This retroactively adds an update script for PR #27257
This assures that characters that had the secondary language `Neo-Russkiya` will have it changed to `Zvezhan` per the original PR.
To be handled by DBA if needed.
<hr>
<hr>
NPFC

Update Script for PR #27257 -  Language Changes & Lore Pt. 1

---

code/game/objects/structures.dm

Fixes a runtime that occurs when a table that is being climbed gets deconstructed
Runtimes are bad.
Start climbing a table.
Deconstruct the table.
No runtimes.
<hr>
<hr>
NPFC

[FIX/RUNTIME] Table climbing runtime

---

_maps/map_files/shuttles/emergency_lance.dmm
_maps/map_files/stations/emeraldstation.dmm
tools/maplint/lints/generic_access_helpers.yml

This PR fixes the use of some access helpers that didn't actually provide any access, and creates a maplint prohibiting their use in the future.
I'm not sure how/if these ever worked but if they worked before, my switch to req_access lists probably broke them. Either way, none of these should be used in maps.
Spawned in, bumped into doors and ensure I could walk into them with the correct access, and couldn't with the wrong access.
<hr>
<hr>
:cl:
fix: Diagoras: A door in the bridge and on AI sat hallway have had their command access fixed.
fix: Lance: A door in the command cockpit has had its command access fixed.
/:cl:

fix: remove access-less helpers and add a maplint

---

code/modules/mob/living/carbon/human/species/_species.dm

Makes human apply_damage return if godmode is on instead of damaging limbs and fucking up the user so they die after
godmode means godmode, one should not die when in godmode or take a bunch of limb damage
Bombed them
Batoned them
punched them
357'd them
actually worked
<hr>
<hr>
:cl:
fix: Godmode works right now
/:cl:

GODMODE actually prevents humans from taking organ damage and limb damage and such aka works now

---

code/modules/mob/living/carbon/human/human_mob.dm

Fixes an issue introduced by the switch to ITEM_SLOT_FLAGs where character serialization/deserialization would be broken. Old JSONs probably won't work entirely as expected anymore but should still get partially equipped, with the rest of their items spawning on the ground.
Fixes: #27432
Admins should be able to serialize and deserialize characters where needed.
Serialize a character with all slots filled
Deserialize that same character, all items equip as expected with no runtimes.
<hr>
<hr>
NPFC

[FIX] Json serialization/deserialization for characters

---

code/game/objects/items/weapons/storage/storage_base.dm

Fixes an oopsie that did not exclude user from seeing a message intended for those in adjacent tiles. (orange excludes the center object and all of its contents)
Also removes a comment that no longer has meaning. 
Bug
<hr>
<hr>
:cl: Chuga
fix: Stops double messages when putting things into storage items
/:cl:

Putting things into your bag no longer shows a double message

---

code/game/objects/items/weapons/storage/garment.dm

Fixes #27489 
Removes cloaks from `cant_hold`
They start in the bags, they return in the bags.
Took out a cloak, put it back in.
<hr>
<hr>
:cl:
fix: Cloaks can now be put back into garment bags.
/:cl:

Fix: Cloaks can now be put back into garment bags

---

_maps/map_files/stations/cerestation.dmm

Fixes #27439 by adding two tables to the south and placing the registers on them, separated, on Cerestation.
Having two cash registers stacked directly on top of one another is confusing and jarring. They should be separated.
Spun up a test server, and fiddled with the cash registers. Alas, they no longer seem to duplicate!
<hr>
<hr>
:cl:
tweak: Moves two cash registers and places new tables for them
/:cl:

Moves the two cash registers in Cerestation's kitchen

---

code/datums/components/proximity_monitor.dm

This removes a Stack Trace introduced in  #26585 that causes map unit testing to fail during CI and Merge operations.
Fixes the issue with CI failing on unit testing only. As of now this has not appeared to affect live in any way.
To be conducted
<hr>
<hr>
NPFC

Removes a Stack Trace that causes intermittent failing during Unit Testing

---

_maps/map_files/stations/metastation.dmm

Fixes a disconnected disposals line in the Toxins Launch room (Not the one that leads into the mass driver) by adding a new disposals for it to hook up to.
Disposals networks should be completed and not be left with tubes that go nowhere
Before and after:
Spun up a test server, flushed half a TTV to test that it worked. Scared the nonexistent cargo techs out of their shoes.
<hr>
<hr>
:cl:
fix: Fixed the unfinished disposals loop in Toxins
/:cl:

Fixes Meta's Toxins disposals not starting anywhere

---

code/modules/mob/living/silicon/robot/robot_mob.dm

Medical rovers can no longer wear hats, as the system doesn't allow hat offsets per-direction.
Stops medical rovers from wearing hats.
It's not designed with hat-wearing in mind, and the hat is floating when facing sideways. Besides, they already have a light-up nurse hat.
This happened because I tried to join my two branches together and left out a bit. I'm annoyed that this happened, because I tested this stuff for hours before joining the branches, but you live and learn.
Tried to put a hat on a medical rover, couldn't.
<hr>
<hr>
:cl:
tweak: Medical rovers can no longer wear hats.
/:cl:

Medical Rover hatfix

---

code/game/objects/items/weapons/cards_ids.dm

Admin Jsons now have proper assignments and ranks. This will not break old jsons.
More JSON creativity for admins
Spawned myself in as a custom json that had pre-assigned rank and assignment
<hr>
<hr>
NPFC

Admin Jsons now have proper assignments and ranks

---

code/modules/food_and_drinks/recipes/recipes_microwave.dm

Replaces invalid reagent id with a valid one. Frostoil is a display name, not an id.
Working recipes.
99% sure it works.
<hr>
<hr>
:cl: Maxiemar
fix: Bungo donuts can be cooked now.
/:cl:

Fix bungo donut recipes

---

code/game/machinery/computer/camera_console.dm

Prohibits `multitool_act` for `/obj/machinery/computer/security/telescreen/entertainment/television` that causes invalid sprite offset like it's wall-mounted but it's actually not.
No more invisible wall tricks.
No act allowed.
<hr>
<hr>
:cl: Maxiemar
fix: The direction of wooden entertainment tv can no longer be changed.
/:cl:

Prohibit multitool act for television

---

code/modules/mod/modules/_modules.dm

Fixes modsuit modules with a device (Eg. Firefighting module nozzle) dropping their device on the ground when it cannot be deployed to hand, for example if you are handcuffed
Fixes: #27433 
Unintended behaviour that causes nodrop items to drop on the floor.
Equip the advanced engineering MODsuit.
Activate and deactivate the firefighting module, deploys as expected.
Handcuff myself with the firefighting module active, the module does not drop on the ground (Though it does stay in hand, but this is out of scope to fix within this PR)
Handcuff myself and activate the firefighting module, it does not deploy and does not fall on the ground.
<hr>
<hr>
:cl:
fix: Modsuit module devices no longer drop on the ground when you try to deploy them when you can't.
/:cl:

[FIX] Modsuit module device dropping

---

code/modules/mob/dead/observer/observer_base.dm

This PR adds back the chat messages displayed when ghosts jump to a ruin. I originally removed these in #22953 because the descriptions were pretty bad, but they've been improved since then, and the ones that still need improvement will at least show up in-game and possibly motivate people to clean them up.
More interesting in-game info.
Jumping to some space ruins:
Jumping to some lava ruins:
See above.
<hr>
<hr>
:cl:
add: Jumping to ruins as a ghost will now display the ruin's name and some flavor text.
/:cl:

Add ruin jump description messages back.

---

code/game/machinery/vendors/wardrobe_vendors.dm

This changes a typo in the virodrobe's description
It also purges the last of the "IAAs are lawyers" legend by changing the IAA's vendor description.
Typos bad, IAAs are not lawyers.
Loaded the game, stared at the vendor. Correct descriptions
<hr>
<hr>
:cl:
fix: IAAs are no longer referred to as lawyers by the Lawdrobe
spellcheck: Fixed a typo in the virodrobe's description.
/:cl:

fixes vendor's descriptions.

---

code/modules/hallucinations/hallucination_manager.dm
code/modules/hallucinations/hallucinations.dm
paradise.dme

Adds a framework to use hallucinations with, `hallucination managers`!
These will automatically spawn hallucinations and do special behaviour at certain points, alongside allowing for special spawning placement.
They are made to work alongside normal hallucination effects, so these can easily be put in the global `hallucinations` list.
Our hallucinations are very old and bad, adding this framework will make it easier to add better hallucinations. I'm not sure if moving every (visual) hallucination as they currently are over to this is worth it, and it is probably better to improve what they do first.
The first and most important step is to decide what you want your hallucination to do.
After you've done that, you should start with making your `/obj/effect/hallucination/no_delete`. This is …

Adds hallucination managers

---

docs/mapping/quickstart.md

This PR removes a hyperlink to a non-existent doc in devdocs.
Links that go nowhere are bad.
<hr>
<hr>
NPFC

Remove non-existant mapmerge doc link

---

code/game/objects/items/devices/powersink.dm

Adds an 'object of interest' notification when powersinks are turned on. 
and when its at 95% capacity
Letting ghosts know whats happening in a round is nice, a powersink is a VERY impactful event for the round, so letting ghosts quickly be able to watch people walk past it is nice.
same with it exploding
Im sure some people will be quick to point out 'wouldn't this lead to dead crewmember metagaming?' and well, yeah. probably. but ghosts can already find the powersink much easier than crew can, and from there its not too hard for that information to make its way to a dead crewmember that could use the information to disable it.
So i dont think it'll be that big of a problem
(`a the powersink` has since been fixed, forgot to take a new screenshot :p)
see above, did some multi instance …

People activating a powersink now pokes ghosts with a follow prompt

---

code/datums/datumvars.dm

VV now supports references as keys in associated lists. Half of the line is now for the ref, while the other is a ref to the list.
Requested feature for debugging
See above, clicking on "the deck of cards" leads to the ref of the cards and not the list.
<hr>
<hr>
NPFC

VV now supports references as keys in associated lists

---

docs/references/attack_chain.md

This PR updates the attack chain migration docs to tell people which Python to use.
Bad docs bad.
On a brand new machine with no pre-existing Python environment, ran commands from cmd.exe and powershell.
<hr>
<hr>
NPFC

docs: update attack chain docs to use correct python

---

docs/references/attack_chain.md

Fixes an admonition in the new attack chain documentation.
Style of the devdoc site is important to us, especially when it comes to information on attack chain migration.
Checked the markdown viewer in VS code for proper format.
(See image above)
<hr>
<hr>
NPFC

Fixes an admonition in Attack Chain Documentation

---

code/__HELPERS/unsorted.dm
code/_onclick/item_attack.dm
code/game/machinery/doors/airlock_electronics.dm
docs/references/attack_chain.md

This PR fixes the attack chain migration for airlock electronics, properly handling their destroyed subtype. It also updates the documentation to explain how to do this in the future, using the incorrect migration as an example (the code doc links won't work until the day after this PR gets merged).
Bugfix, better docs.
<hr>
<hr>
:cl:
fix: Destroyed airlock electronics should now properly prevent players from setting their access.
/:cl:

Attack Chain Migration: /obj/item/airlock_electronics/destroyed

---

code/game/machinery/autolathe.dm

This PR fixes two issues with autolathe signals. `COMSIG_TOOL_ATTACK` is deprecated for new usage but is still required for autolathe/screwdriver interactions. It also prevents signal registration overrides with trapped autolathes. Fixes #27555.
Bugfix, less runtimes.
<hr>
<hr>
:cl:
fix: Screwdrivers are properly recycled in autolathes on harm intent.
fix: A runtime related to the DVORAK ruin has been fixed.
/:cl:

Fix some autolathe signal issues.

---

code/_onclick/item_attack.dm
code/_onclick/item_attack_legacy.dm

This PR fixes an error in #26834 where attacked_by was being called when it shouldn't be, such as when an item couldn't bludgeon.
Bugfix.
<hr>
<hr>
:cl:
fix: Several unexpected attack side-effects, including borgs bludgeoning themselves with goliath hide plates, have been fixed.
/:cl:

Fix attacked_by being called after handled attacks

---

_maps/map_files/stations/boxstation.dmm
_maps/map_files/stations/cerestation.dmm
_maps/map_files/stations/metastation.dmm

Fixes a typo in the holodeck disclaimer, from Brusies to Bruises
Typos bad. Also voxxies speaksies bad.
Loaded maps. Checked disclaimer. Was not assaulted by yayaspeak.
<hr>
<hr>
:cl:
fix: Fixed a typo in the holodeck disclaimer
/:cl:

Unvoxies the holodecksies

---

code/game/objects/structures/bedsheet_bin.dm

Fixes not being able to dye bedsheets using the washing machine.
Oversight bad
Washed a bedsheet with a purple crayon in washing machine
<hr>
<hr>
:cl:
fix: Fixed the ability to dye bedsheets.
/:cl:

Restores the Ability to Dye Bedsheets

---

code/game/machinery/computer/computer.dm

This PR bumps the brightness of computer's ambient light, and uses the computer's screen state to suss out an appropriate color for the light.
Better atmosphere. The start of an attempt to improve environmental ambience.
With no lights:
With emergency lights:
Testing broken screens don't use it:
See above
<hr>
<hr>
:cl:
tweak: Computer screens now glow slightly brighter and in an appropriate color.
/:cl:

Make computer screens glow brighter and match screen color.

---

code/modules/mob/living/carbon/alien/special/alien_embryo.dm
code/modules/surgery/organs/body_egg.dm
code/modules/surgery/organs/parasites.dm

Forces body eggs to call parent `on_life()` and `dead_process()` cause `egg_process()` is called there.
This one fixes an alien egg not evolving inside a body. Can lead to some other bug fixes I am not aware of.
Became an alien's young mom after wearing facehugger for a while.
<hr>
<hr>
:cl: Maxiemar
fix: Alien eggs evolve correctly now.
/:cl:

Fix alien egg not being able to can

---

code/modules/hallucinations/hallucination_manager.dm

Fixes a runtime when a `null` is trying to be deleted
Runtimes bad
None. The timer has `TIMER_DELETE_ME` as a flag, which makes it automatically delete when the datum is deleted. This line is not needed
<hr>
NPFC

Fixes managers runtiming on delete

---

code/game/machinery/vendors/wardrobe_vendors.dm

What the titles says. Adds the CMO's action figure to the contraband list of the medical clothing vendor
makes the CMO's figurine finally consistent with all other head's figurine and how to obtain them (except Cap/HoP)
Loaded in, hacked medical clothe vendor, bought CMO figurine, threw it in the SM.
<hr>
<hr>
:cl:
tweak: added CMO's figurine to the medical clothing vendor if it is hacked.
/:cl:

Adds the CMO's action figure to the medical clothing vendor

---

code/modules/mob/living/carbon/human/human_mob.dm

Makes a proc called `invoke_hallucination` that will spawn in the hallucination on the mob you're calling it. Accepts a typepath, either string or normal
Easier to spawn in hallucinations + to debug anything with hallucinations
Spawned in as ah uman
Gave myself the tesla ball hallucination
<hr>
<hr>
NPFC

Proc to easy spawn in hallucinations

---

code/modules/admin/topic.dm

Fixes admin faxes by making sure a fax datum is sent instead of the paper itself.
Admins can now do funny faxes again.
Sent a fax to centcom, used an autoreply via the template option.
Fax arrived back to sender.
Sent a fax to centcom, replying with a custom message.
Fax arrived back to sender.
<hr>
<hr>
NPFC

Fixes admin faxes... Again.

---

code/datums/datumvars.dm
code/modules/mob/living/carbon/human/human_mob.dm

Heavily improves the VV option for hallucinations by:
- Not actually making the person hallucinate
- Adding managers to the list of options
You can't make carbons hallucinate anymore, but I don't think admins were making many xenos hallucinate to begin with
1. This should work with managers aswell
2. I'm clairvoyant, we have the technology now 
<hr>
<hr>
:cl:
add: [ADMIN] VV hallucination option has been improved a lot
/:cl:

Makes VV hallucination not shit

---

code/modules/clothing/suits/utility.dm

Slightly lowers the slowdown the radiation suit gives you.
from 1.5 down to 0.75
Currently, the only way to get full radiation immunity (as normal crew) is be ce, or have a radsuit. 
Not the worst thing, but due to how high the slowdown of the radsuit is, it makes doing anything just incredibly tedious, as you're basically dragging yourself all over the place.
Hopefully this aids in that, without making it too powerful. I was originally going to go with .5 but it felt a bit *too* good.
compiled, checked a handful of speeds, settled on 0.75
<hr>
<hr>
:cl:
tweak: The radiation suit has gotten better shielding, allowing it to be lighter, without sacrificing protection
/:cl:

Lowers the slowdown the radiation suit has.

---

code/datums/status_effects/magic_disguise.dm

Using disguise self/flesh facsimile now updates your security HUD so you no longer appear wanted when disguised as someone else.
Fixes: #27504
Disguising yourself should also disguise your security status, otherwise this ability is kind of moot.
Set myself to wanted.
Use disguise self.
I am no longer wanted.
<hr>
<hr>
:cl:
fix: Disguise self now hides your security HUD.
/:cl:

[FIX] Disguise self now updates security HUD

---

code/game/turfs/simulated/floor/light_floor.dm

This PR removes some behavior in the light floors related to bulb replacement. As can be seen, `light_broken` is never modified anywhere, and the logic here is in reverse, replacing a bulb if `!light_broken`, causing floor lights to accept infinite light bulbs.
Mostly dead code, unused behavior, no more bizarre in-game behavior.
Spawned light floor in-game, ensured that bulbs could not be used on it.
<hr>
<hr>
:cl:
fix: Behavior where light bulbs could be inserted an infinite number of times into light floors has been fixed.
/:cl:

Remove unused 'broken light' light floor state

---

code/datums/datumvars.dm

This switches input for add/remove organs from the old list to use the newer tgui version.
Provides a cleaner interface for organ selection.
Allows the user to traverse larger lists using built-in search.
Spawned in mob.
Used vv to add an organ.
Used vv to remove an organ.
<hr>
<hr>
NPFC

Changes add/remove organs in the VV panel to use tgui input lists

---

code/controllers/subsystem/SSghost_spawns.dm
code/modules/admin/misc_admin_procs.dm
code/modules/admin/verbs/pray.dm
code/modules/mob/mob_misc_procs.dm
code/modules/paperwork/faxmachine.dm

Fixes some messages showing up in the Unsorted Chat Tab.
- Fax messages, centcomm messages, syndicate requests, ert requests, and nuke code requests all show up in the ADMIN PM section now
- Notify_ghosts sends the message to the deadchat tab now
- Now looking for candidates message shows up in deadchat too
QOL good
Asked for nuke codes, it was in the right tab. Did some notify_ghost stuff with golems, showed up in the right tab
<hr>
<hr>
:cl:
fix: Fax messages, centcomm messages, syndicate requests, ert requests, and nuke code requests all show up in the ADMIN PM section now
fix: Notifying ghosts and polling ghosts now shows in the deadchat tab now
/:cl:

Fixes some messages showing up in the Unsorted Chat Tab

---

_maps/map_files/stations/emeraldstation.dmm

Fixes the clown office on Emerald not having a stamp
Its supposed to have a stamp
Stamp is there
<hr>
<hr>
:cl:
fix: Clown's Office on Emerald Station has a stamp again
/:cl:

Fixes the clown office on Emerald not having a stamp

---

code/modules/unit_tests/map_tests.dm
tools/maplint/lints/invalid_space_neighbors.yml
tools/maplint/lints/unary_vents.yml

This PR moves some per-tile tests into maplints. Per-tile tests are almost certainly slower on measure, and I prefer the way @Contrabang is using them, for verifying tile state after map load. Maplints should be used for map pre-load checks; anything that doesn't need atoms being initialized.
Some details:
- there were two checks involving checking for duplicate cables on tiles, one just for nodes and one that compared each cable's d1 and d2. These are both already handled by `stacked_matching_cables.yml`.
- that there was a check for structures on centcomm areas that never ran because centcomm was never passed as a z-level, and it fails because the windows surrounding the holodeck scenes are on space areas, and I'm not touching that part of the map.
Almost certainly faster, even if only …

Move some per-tile tests to maplints.

---

code/game/objects/items/weapons/cards_ids.dm

This PR fixes a regression where clicking on an ID card with a wallet would not put the card in the wallet.
Bugfix.
https://github.com/user-attachments/assets/490f5eca-b32b-405e-8618-0747f063d742
<hr>
<hr>
:cl:
fix: Wallets now correctly insert ID cards by using the wallet on the card.
/:cl:

Fix wallets not ingesting cards on click.

---

code/modules/mod/modules/_modules.dm

Fixes #27250
Pegs modsuit modules to + 0.1 of the `HEAD_LAYER`. The `HEAD_LAYER` should be the highest layer any modsuit part uses which is why I chose it instead of the suit layer. This also means that modules will layer above cloaks which is a good thing.
Fixes a bug. In-hands now layer above modsuit modules.
This also means modules will no longer layer above HUDs (yes they were doing this before that is how stupidly high the effects layer is)
Modsuit module overlays should never have been on the `EFFECTS_LAYER`. Even the DM reference warns that `EFFECTS_LAYER` is mostly no longer needed.
Spawned in.
Checked modsuit module layering on suits (with the mirage module) and helmets (with the welding protection module)
<hr>
<hr>
:cl:
fix: Modsuit modules now layer below in-hands.
/:cl:

Fixes modsuit overlay issue

---

code/game/objects/items/devices/traitordevices.dm

converts traitordevices.dm to activate_self
We should be killing off legacy stuff, and this is simple practice for me.
Used Radio jammer in hand. Saw chat messages, tried  to use radio, jammed, turned it off.
Teleported self with syndicate teleporter.
Tried to use fireproofing injector as a human, failed. Injected self as plasmaman. Tried to inject self again, failed.
Tried using cryoregenerative injector as a plasmaman, failed. Injected self as a drask, worked. Attempted again, failed.
Used mindbatterer, worked. Threw it, still worked.
Used the handheld mirror, worked.
Confirmed all converted items had new_attack_chain = TRUE
<hr>
<hr>
NPFC

 Attack Chain Migration: traitordevices.dm to activate_self

---

.github/workflows/build_rust.yml

Fixes !build_rust
Building our dependencies is good.
https://github.com/FunnyMan3595/Paradise/actions/runs/12433940999/job/34716569047
Build worked, it just didn't have access to push to the PR (issue with my own repo setup)
<hr>
<hr>
NPFC

Fix !build_rust by updating lib32gcc

---

code/modules/client/preference/link_processing.dm

Read the title.
Self explanatory.
:cl:
tweak: Changing your viewport size in preferences now automatically updates your viewport size.
/:cl:

Run `fit_viewport()` upon changing view size.

---

_maps/map_files/RandomRuins/SpaceRuins/meatpackers.dmm
code/game/machinery/portable_turret.dm

Fixes #27421.
Removes custom installation on ship turrets so they don't anymore give you `/gun/energy/gun` but `/gun/energy/gun/turret`
Fixes an issue. You shouldn't be able to get 1500 worth of credits (6 eguns) for destroying 6 dummy turrets
Compiled, destroyed a turret, deconstructed it using a crowbar, ensured there is a turret-egun instead of a normal one.
<hr>
<hr>
:cl:
fix: Turrets on meatpackers ruin no more drop energy guns on deconstruction.
/:cl:

Tweak for meatpackers ruin turrets

---

code/game/objects/items/toys.dm

skrell plushes no longer runtime if destroyed with no headpocket item
runtimes bad
resolve #27729
plushified a bunch of mobs
deleted them
skrell runtimed, rest worked
fixed runtime
now works no issues after testing
<hr>
<hr>
:cl:
fix: Fix skrell plushes runtiming
/:cl:

Fix skrell plushes runtiming

---

code/modules/mob/living/simple_animal/parrot.dm

Tweaks parrot's desired perches.
Fixes levitating sitting parrot.
Fixes parrot not able to pick stuff from most objects.
Makes parrot forget it's current perch at some point and find another one.
Current parrot logic makes it collect all the stuff near a telescreen in the CE office, 'cause it's the only object which location parrot can achieve. Tweaking path logic to allow adjacent tiles makes parrot able to select different perches messing everything between them.
I tweak allowed perch objects removing some large or unreasonable structures, pixel offset computers and adding some new objects which seem fine to me.
Stealing frequency is increased for demonstration.
<details>
<summary>Video</summary>
https://github.com/user-attachments/assets/9015c5d0-b146-4fb0-b309-ca7460116e1c
</details> …

Parrot behavior changes

---

_maps/map_files/RandomRuins/SpaceRuins/spacebar.dmm
_maps/map_files/RandomRuins/SpaceRuins/ussp.dmm
_maps/map_files/stations/boxstation.dmm
tools/maplint/lints/stack_tile.yml
tools/maplint/lints/tile_mineral.yml

Swaps the floortiles on the space bar, ussp, and box from a non existing `/mineral` or the base tile type type to the actual plasteel type thats meant to be used.
Also adds lints to prohibit this in the future
the floortiles were broken, the name was quite literally "broken floor tile"
Fixes #27672
not visual, heres what it was like before though
Compiled, checked if i could use the floor tiles
<hr>
<hr>
:cl:
fix: Fixes some of the flooritles on cyberiad, USSP space ruin, and the space bar being broken.
/:cl:

Fixes some tiles on the space bar, USSP, and box being broken

---

code/modules/food_and_drinks/food/foods/baked_goods.dm

`/obj/item/food/sliceable/plaincake` is currently called `vanilla cake`
`/obj/item/food/sliceable/vanilla_cake` is also called `vanilla cake`
This PR renames `/obj/item/food/sliceable/plaincake` to `plain cake`
I'm handling the wiki edit as well
People don't get confused about the recipe, pound cake needs plain cakes, not vanilla cakes
none, it is a name change
1. Spawned in, spawned a `/obj/item/food/sliceable/plaincake`
2. Spawned a knife
3. Sliced it
<hr>
<hr>
:cl:
fix: Plain cakes are now called plain cakes instead of vanilla cakes (as we also have vanilla cakes, this removes a duplication).
/:cl:

Fixes duplicate vanilla cake by renaming it to its real type

---

code/game/atoms_movable.dm

This PR checks the `TRAIT_CURRENTLY_Z_MOVING` for pulled objects being forcemoved, ensuring that pulls aren't broken in those cases. Fixes #27700.
Bugfix.
Drifted across zlevel while pulling locker, used jetpack to pull locker across zlevel.
<hr>
<hr>
:cl:
fix: Mobs should no longer let go of objects while attempting to pull them across space levels.
/:cl:

Do not break pulls on zlevel transitions during forceMoves.

---

docs/mapping/design.md
docs/mapping/requirements.md

This PR adds the proposed mapping requirements and design guidelines for submaps to devdocs.
Gets these out of HackMD and into the official docs.
Proofreading.
<hr>
<hr>
NPFC

Add submap requirements and guidelines to devdocs.

---

tools/ci/check_legacy_attack_chain.py

This PR improves the CI script for attack chain migrations to include filename and line number for aberrant proc declarations. This script is getting a little goofy and complicated but it only needs to last long enough to get across the finish line for the migration.
Having filenames and line numbers here is much more easier to work with when checking the CI run.
<hr>
<hr>
NPFC

Improve CI output for legacy attack chain check

---

code/modules/mob/living/carbon/human/species/_species.dm

makes it so if dont have the ability to breath, but *do* have a screen alert relating to no oxygen, the alert will clear
The alert(s) would stick, even when ghosting.
Fixes #27715
Compiled, checked vox, plasmen, and humans and their related alerts
<hr>
<hr>
:cl:
fix: If you loose the need to breath with a breathing related alert on screen, it will no longer be stuck there
/:cl:

Fixes oxygen related alerts sticking in your hud if you loose the need to breath

---

code/modules/mob/living/carbon/human/species/_species.dm

fixes ipcs thinking they need to beath by making the check separate, didn't tthink to test it on ipcs because the original fix was related to breathing.
bug :<
compiled, checked all the species. Atleast humans, vox, plas, and machine people
<hr>
<hr>
:cl:
fix: IPCs no longer panic thinking they need to breath, when they cant.
/:cl:

Fixes IPCs thinking they need to breath. Woops.

---

code/datums/ai_law_sets.dm

Tweaks Pranksimov to have a better defined definition of "funny". `unless doing so would be funny.` is now `unless doing so would be funny to the crew.`
Too often AI players don't know what the word "funny" means, and often just use it as approval to grief. Despite its law header being "Comedy Routine", rarely does anything funny actually happen for the crew. This change specifies that it must be funny for the crew, which means the AI can't just turn off telecomms, or do a bunch of random shit to annoy people. They'll actually have to put in effort to make good jokes.
Compiles
<hr>
<hr>
:cl:
tweak: Pranksimov's ending clause has been tweaked from "unless doing so would be funny." to "unless doing so would be funny to the crew."
/:cl:

Tweaks Pranksimov to have a better defined definition of "funny"

---

_maps/map_files/stations/metastation.dmm

Replaces the standard air alarm in the Meta server room with a server room air alarm.
Oh, right. The air alarm. The air alarm for the server room, the air alarm chosen especially to control the server room's air, the server room's air alarm.
Stops the air alarm from triggering an alert and shutting the hazard door at roundstart.
Loaded Meta.
Looked at the server room.
All systems green.
<hr>
<hr>
:cl:
fix: Fixed the meta server room not using the server room air alarm subtype.
/:cl:

Fixes Meta Server Room Air Alarm

---

code/modules/events/event_container.dm

This PR moves the Pulse Demon in the event container from Moderate to Major. It now has the same chance to roll as a Shadow or Slaughter Demon.
Pulse in its current stage is very strong. Mixed with major event rolls and possibly other moderate rolls it can become too much for the crew to handle with the amount of chaos it can potentially cause.
Compiled.
Checked that the Pulse Demon was now a Major in the Event Manager.
Checked that Pulse Demon would be triggered by Major event rolls.
<hr>
<hr>
:cl:
tweak: Pulse Demon is now a Major Event instead of a Moderate Event
/:cl:

Moves Pulse Demon from a Moderate Event to a Major Event

---

code/modules/admin/verbs/randomverbs.dm

This replaces the old Modify Traits input with the tgui equivalent in the vv menu dropdown.
Allows administrators to modify traits faster.
Used VV dropdown to add a trait to a mob.
Used VV dropdown to remove that trait for the same mob.
<hr>
<hr>
NPFC

Updates Modify Traits to use TGUI Input in VV

---

code/__DEFINES/antag_defines.dm
code/modules/antagonists/_common/antag_datum.dm

This reduces the chance that the hijack objective will roll on a traitor by half, moving from 10% to 5%.
This PR also changes the average organization role percentage from 60% to 65% to match the change in reduction of one organization by 5%.
Overall, hijack is an objective that ends rounds early, prevents ERT from being sent in most cases, and is brutal when it comes to lower population shifts. Normally the first two would be fine, but the amount of times it happens becomes too chaotic, when you account for things like midround rolls, higher amounts of antag, and current security on board. This PR aims to level those issues out, while we plan the move over to dynamic. In that essence it is temporary.
On a personal note. I believe that hijack should be rare. This gives it a more …

Reduces the chance of hijack to roll per traitor from 10% to 5%

---

code/modules/admin/verbs/randomverbs.dm

This provides additional logging for subtle, direct narrate, and headset messages, making them available in the log viewer of the player that has been messaged. 
Improves administrative tools.
Used a client to send the three message types to another client.
<hr>
<hr>
NPFC

Adds Logging in Log Viewer for  Subtle, Direct Narrate, and Heatset Messages

---

code/modules/clothing/spacesuits/ert_hardsuits.dm

This removes the slowdown from ERT hardsuits, bringing them in line with the other ERT levels which do not experience any slowdown. 
ERT is often called to a station in times of need, having the slowdown compared to the other groups is counterproductive of that. 
Currently even the security modsuits have more bullet and bomb protection and less slowdown than the ERT hardsuits.
Spawned in an RT Red suit and tested the speed.
<hr>
<hr>
:cl:
tweak: Removed slowdown for ERT hardsuit
/:cl:

Removes Slowdown from ERT Hardsuits

---

code/game/gamemodes/miniantags/pulsedemon/pulsedemon.dm

- Lasers deal 50% their damage to pulse demons. They also stop healing for 1 cycle
- Pulse demons now can only heal to 50% of their hp when outside of machinery.
Pulse has been a long time PITA to deal with, due to it only being vulnerable to ion shots and having exceptional healing while on the fly. This forces them to retreat and heal up after a fight instead of being able to fully heal when still moving about. It also gives security an extra weapon to fight them with, albeit overall worse than an ion rifle
Did a bunch of testing, for example this is when a pulse has 24 out of 50 hp, it only healed 1 hp
<hr>
<hr>
:cl:
tweak: Pulse demons now take half damage from lasers
tweak: Pulse demons now can only heal to half hp while outside of machinery
/:cl:

Nerfs the pulse demon

---

code/__DEFINES/atmospherics_defines.dm
code/modules/atmospherics/machinery/airalarm.dm
code/modules/atmospherics/machinery/components/unary_devices/vent_pump.dm

- Makes a variable use defines instead of pretending to be flags
- Removes some unused variables
- Improves autodocs
More clean code
It compiled
<hr>
<hr>
NPCF (I hope)

Change a variable to use defines, also some autodoc improvements

---

code/game/objects/items/robot/cyborg_gripper.dm

This PR adds a shim to the borg gripper for attack-self/self-activating held items.
Ensures new attack chain-migrated items work with borg gripper.
Spawned in as borg, selected engineering module, spawned in airlock electronics, grabbed electronics with gripper, clicked on gripper and used keyboard shortcut to ensure I could modify airlock electronics.
<hr>
:cl:
fix: An issue where borgs could not modify airlock electronics via their gripper has been fixed.
/:cl:

Fix borg gripper held item self-activation.

---

_maps/map_files/stations/cerestation.dmm

Replaces the reinforced window spawners at the Farragus vox box with grilled reinforced window spawners, as space-facing windows are supposed to be grilled.
Replaces the rock on either side of the windows with metal walls so that the windows actually tile-blend with the window frame.
Replaces a single asteroid rock with cold asteroid rock.
Space-facing windows are supposed to be grilled.
The windows look bad when they don't tile-blend into the walls adjacent to them.
Asteroid rock diagonally adjacent to space is cold everywhere else on Farragus, this should be consistent.
Went to the area, windows were grilled and flanked by metal walls. The one bit of asteroid rock was now cold.
<hr>
<hr>
:cl:
fix: Fixes missing window grilles at the farragus vox box.
/:cl:

Fixes missing window grilles and singular missing cold rock at the Farragus vox box

---

code/modules/mob/living/simple_animal/constructs.dm

Changes the Harvester hit sound from Prod to bladeslice (similar to the wraith).
Changes the harvester attack text to "Rends"
The sound seems so wimpy, considering they do more damage that a lot of other things on station, and nearly as much as a wraith. They frequently are very successful killers and with the current sound it feels like you're just poking someone. Having some proper feedback you're actually doing damage is good for gamefeel
Rended a buncha skrells
<hr>
<hr>
:cl:
tweak: Tweaked harvester hit sound and text
/:cl:

Tweaks cult harvester  attack sound

---

code/datums/spells/alien_spells/build_resin_structure.dm
code/datums/spells/alien_spells/corrosive_acid_spit.dm
code/datums/spells/banana_touch.dm
code/datums/spells/mime_malaise.dm
code/datums/spells/sentient_sword_lunge.dm
code/game/gamemodes/wizard/godhand.dm
code/game/objects/items/toys.dm

Magic touch spells no longer trigger and kill themselfs on floors or walls or lockers or holopads, etc.
Fixes spelling in plasmaman plush.
Allows sword / bread / plush spirits to break out of storage objects with a 50% chance. Makes it less harsh for crew.
Losing your spell charge because you missclicked is bad.
Spelling right good.
Allowing plushes to break out of bags 50% of the time their throw spell is good to make it less shitty for the victim.
clicked on everything with touch spells
Confirmed only activated on valid targets (basically everything for xeno acid, mobs for other things)
Confirmed could break out of backpacks and also fail to break out.
<hr>
<hr>
:cl:
fix: Touch spells no longer false triggers on floors or lockers or other things.
fix: Fix plasmaman plush spelling. …

fix magic touch spells false deleting, fix spelling, allow escape

---

code/game/objects/items/weapons/cards_ids.dm

It stops the NCT chip from deleting Heads access
Fixes something that shouldn't happen
Hopped in and saw that the QM didn't lose access anymore.
<hr>
<hr>
:cl:
fix: Fixed NCTs deleting access from Heads of Staff
/:cl:

[FIX] NCT removing access from Heads of Staff

---

_maps/map_files/stations/boxstation.dmm
_maps/map_files/stations/cerestation.dmm
_maps/map_files/stations/deltastation.dmm
_maps/map_files/stations/emeraldstation.dmm
_maps/map_files/stations/metastation.dmm

Fixes the tags on the cameras in the PTL room on all stations so they show up properly
bug fix
- Found the camera on the console and looked through it
<hr>
<hr>
:cl:
fix: Changes the wrong names of cameras in the PTL room in all stations
/:cl:

PTL Camera name fix

---

code/modules/client/preference/loadout/loadout_donor.dm

Adds customized welding helmets to the loadout.
I was surprised to notice these helmets. They don't seem to be found anywhere, so adding to the loadout seems appropriate.
Started with a nice helmet in a backpack.
<hr>
<hr>
:cl: Maxiemar
tweak: Customized welding helmets are available in the loadout now.
/:cl:

Add customized welding helmets to the loadout

---

_maps/map_files/stations/emeraldstation.dmm

Makes Emerald Stations solars be built by default, to where you would only need to wire them.
Labels all solar array's correctly
Fixed mislabled door in Aft-Port Solars
This stations solars almost never get set-up due to the time it takes to do it, and makes it next to impossible to quickly setup in an emergency. Solars should be easy power and them taking upwards of an hour to setup is not needed
loaded server and wired solars, worked as expected and all solars are properly labled
<hr>
<hr>
:cl:
add: Emerald Station solars are now built by default, only needing to be wired
del: Removed solar crates from Emerald Station
fix: Fixed a mislabeled door on Emerald Station
fix: All solar arrays are now properly labeled on Emerald Station 
/:cl:

Emerald Station solars are now built by default [NOT WIRED] and properly labled 

---

code/modules/surgery/organs/augments_internal.dm

nuggeted ipcs have their implant go on cooldown for a minute before healing begins so they can be dealt with by traitors or sec.
Especially if they are a ventcrawling ipc.
Normal ipcs / humans impacted.
see above
confirmed ipcs healed fine normally.
Confirmed minute cooldown before healing for nuggeted ipcs.
<hr>
<hr>
:cl:
tweak: Nuggeted IPCS no longer instantly start reviving from reviver, which has been very problematic on mindflayers. There is now a minute cooldown before healing begins specifically for nuggeted ones. Normal ipcs are not impacted.
/:cl:

fixes some ipc mindflayer shenanigan

---

tools/ci/check_grep2.py

This PR fixes a CI check which was returning the wrong kind of return value, so its error messages weren't getting collected properly.
Fixes CI failure failure.
Ran against https://github.com/ParadiseSS13/Paradise/pull/27788/commits/dd04dcfabafe5f9003afc06213cced946175f87b:
<hr>
<hr>
NPFC

fix return value of check_datum_loop CI check

---

_maps/map_files/stations/emeraldstation.dmm

This PR fixes an error where the airlocks from the southwest to west primary hallways on Emerald were designated as northwest hallway.
Mapping error.
<hr>
<hr>
NPFC

emerald: fix bad hallway area designation

---

code/__HELPERS/_logging.dm
code/datums/log_record.dm
code/datums/log_viewer.dm
code/datums/logging.dm
code/modules/admin/verbs/debug.dm

Fixes some logging issues.
Issues bad.
Issues gone.
<hr>
<hr>
NPFC

[s] Better logging.

---

code/__HELPERS/_logging.dm
code/__HELPERS/mob_helpers.dm
code/controllers/subsystem/SSjobs.dm
code/datums/log_record.dm
code/modules/mob/mob.dm

Clean up some errant logging warnings.
Not warning about normal things is good.
Tried stuff that warned spuriously before. It didn't.
<hr>
<hr>
NPFC

Clean up some errant logging warnings.

---

code/__HELPERS/_logging.dm

Fix a couple logging runtimes
Runtimes bad.
Tried shooting a watcher with a KA. No runtime.
Tried hallucinating. No runtime.
<hr>
<hr>
NPFC

Fix a couple logging runtimes

---

code/modules/hydroponics/grown/towercap.dm

Removes the Carbon chemical from Towercaps and replaces it with Plant-matter.
This stops botany being able to easily produce synthflesh tomatos/plants within >15m of the round, this does not prevent them from making it all as carbon is still present in gatfruit, however encourages them to cooperate with xenobiology in order to achieve this if they really want to. As suggested by Stoniest, it is now replaced with 45% Plantmatter giving it a niche of being the plant with the most plantmatter (great for the biogen!)
Furthermore we wont be seeing people frequently give 100 potency synthflesh tomatos out to regular crew which nullifies the need to ever visit medbay besides for surgeries since with a few tomatos crushed in your hand you'll be good as new. This will also stop security needing to …

Removes Carbon from Towercaps and replaces them with Plantmatter

---

code/modules/station_goals/bluespace_tap.dm

Fixes cleaning bug in recent BSH Changes. Reduces the chance of events.
Events have a way too high probability at high energy states. This adds a cap to the chance of an event and reduces the odds of an event overall.
Dirty is bugged. Bugs are bad. Cleans up a cleaning bug.
Spawned BSH. Made it dirty. Cleaned the BSH.
<hr>
<hr>
:cl:
fix: Lowered probabilty of BSH events to more expected levels
fix: Cleaning a BSH actually cleans it
/:cl:

BSH Improvement Fix: Cleaning and Event Prob

---

code/controllers/subsystem/SSshuttles.dm
code/modules/shuttle/shuttle.dm

Makes the mining and gulag shuttles report the current state of the shuttle with more detail.
"Departing" when the shuttle is about to take off, "En-route" when the shuttle is in flight, and "Refuelling" when the shuttle is at one of the docks, but still on cooldown.
The cooldown was introduced in #20083.
I had always thought there was some sort of bug with the mining shuttle when it'd say it was "processing a movement request" even if it was docked, but on cooldown.
This doesn't change the cooldown behaviour, just makes it clear that a cooldown exists and is active.
https://github.com/user-attachments/assets/27b5f747-f86f-4674-9825-0b8ea85cbb8a
Spammed the call button on the mining shuttle console and recorded the messages it played back.
Made sure the shuttle still flew.
Checked through …

Makes mining/gulag shuttle request message clearer

---

docs/CONTRIBUTING.md

Adds Burza to the list of headcoders.
It's not.
What's that?
<hr>
<hr>
Probably some player facing changes.

Adds Burza to Headcoders in CONTRIBUTING.md

---

code/game/objects/effects/effect_system/effects_smoke.dm

Sets `/obj/effect/particle_effect/smoke/bad` to last for 16 cycles (32 seconds) instead of 60 (120 seconds).
Also makes the direction the smoke spreads random and the amount it will spread less.
These changes come from #26762 . Warrior said this change was done by accident and was only intended for testing purposes.
It was an accidental change that needs to be reverted.
Smoke grenades are way too strong and last way too long right now.
Loaded into the admin testing area and spawned in `/obj/effect/particle_effect/smoke/bad` and timed it.
Tested smoke spread to ensure it spreads out in random directions.
<hr>
<hr>
:cl:
fix: Sets smoke from smoke grenades to last 32 seconds instead of 120. This change was done by accident.
fix: Smoke from smoke grenades spread around in random directions …

Removes accidental smoke greande buff

---

code/modules/mob/living/carbon/carbon_life.dm
code/modules/mob/living/carbon/carbon_procs.dm

Carbon mobs breathing in nullspace was causing runtimes.
It doesn't anymore.
Fixes #27746 
Not breaking CI is good.
Put a skrell inside a machine's circuit board without the PR. Runtimes.
Put a skrell inside a machine's circuit board with the PR. No runtimes.
<hr>
NPFC

Fixes nullspace breathing runtime.

---

code/modules/clothing/clothing.dm

Adds a custom `strip_delay` and `put_on_delay` to underclothes, a.k.a. jumpsuits and uniforms.
It should probably take more time to strip a jumpsuit off of someone than it should take to take off their shoes.
Took off and put on a jumpsuit on a mob.
<hr>
<hr>
:cl:
tweak: Increased strip and put on delays for the strip menu
/:cl:

Increases the time to Strip and Put on clothing via the Strip Menu

---

code/modules/hydroponics/grown/misc_seeds.dm
code/modules/hydroponics/grown/replicapod.dm
code/modules/hydroponics/hydroponics_tray.dm
code/modules/hydroponics/seeds.dm

Makes plant bag harvesting more logical:
* Non-food produce (e.g. logs) now goes into the plant bag.
* Stuff on the ground no longer goes into the plant bag.
It's good when things behave the way you'd expect them to.
Harvested berries, tower caps, replica pods, and starthistle, all both without the bag and with the bag while standing on other produce.
<hr>
:cl:
fix: When harvesting a hydroponics tray with a plant bag, non-food produce (e.g. logs) now goes into the plant bag.
fix: When harvesting a hydroponics tray with a plant bag, you no longer pick up other produce off the floor.
/:cl:

Improved plant bag harvesting

---

code/modules/food_and_drinks/kitchen_machinery/kitchen_machine.dm

Lets chefs dump entire bags/trays into kitchen appliances. Only works with things that can be quick-emptied onto the floor.
Fixes a minor grammar error when trying to put incorrect reagents into kitchen appliances
Moving things one-by-one is annoying. Now you can drop all the ingredients you need out of the fridge, and move them together.
Tried dumping a backpack into a microwave.
Tried putting a kitchen knife into a microwave.
Tried emptying an empty serving tray into a microwave.
Tried emptying a serving tray containing a cream carton into a microwave.
Put one olive into a microwave with a serving tray.
Put one olive into a microwave by hand.
Put several olives into a microwave with a serving tray.
Tried to add enough olives with a serving tray that the microwave would be overfilled. …

Let chefs dump entire bags into kitchen appliances

---

code/modules/client/preference/loadout/loadout_uniform.dm

This adds the 3 business suits to the loadout menu that appear in the ClothesMate vending machine. 
It gives players more options to choose how they customize the look of their characters.
Started a test instance.
Opened Loadout to see if suits appeared in the Uniform tab.
<hr>
<hr>
:cl:
add: Added business suits to the loadout menu
/:cl:

Adds Business Suits to the Loadout Menu

---

code/_onclick/item_attack.dm
code/tests/attack_chain/test_attack_chain_cult_dagger.dm

This PR fixes the attack chain so that legacy return values from attack are taken into account for legacy attacked_by calls.
Unblocks issues with https://github.com/ParadiseSS13/Paradise/pull/27563.
Made accompanying change to unit test, ensured test failed, made implementation change, ensured test passed.
<hr>
<hr>
NPFC

Respect return values of legacy attack in chain negotiation

---

code/modules/mob/mob_misc_procs.dm

Adds additional logging to the game logs for when an admin offers ghosts control of characters.
Provides additional oversight.
Offered a mob to ghosts.
Checked the game log to make sure it displayed properly.
<hr>
<hr>
NPFC

Adds Additional Game Logs when Offering Ghosts

---

code/modules/ruins/lavalandruin_code/dead_ratvar.dm

Fixes a mistakenly included underscore in the name of the vanguard cogwheel, replacing it with a space.
We use spaces in this house.
<hr>
<hr>
:cl:
spellcheck: Replaced an underscore with a space in the vanguard cogwheel's name.
/:cl:

Fixes underscore in vanguard cogwheel's name

---

code/modules/client/preference/character.dm
code/modules/mob/living/carbon/carbon_life.dm
code/modules/mob/living/carbon/carbon_procs.dm
code/modules/mob/living/carbon/human/human_defines.dm

Make character previews not stack trace
Stack traces should happen for unusual things, not every player editing their character.
Could see and edit my character without stack traces.
Ghost image was correct and didn't generate a stack trace.
Spawning in worked normally.
Was able to process chems after spawning in.
<hr>
<hr>
NPFC

Make character previews not stack trace

---

code/datums/mind.dm

Removes an unused variable on mind
We don't use it
~~None~~, linters will test
<hr>
NPFC

Removes an unused var

---

_maps/map_files/stations/deltastation.dmm

Places Brig Locker 1, 2, 3, etc. in the corresponding cell. Previously, all the cells had Cell 5's locker in it.
Currently, the door timers don't close/lock the lockers when you start a sentence or open when the sentence is over. This fixes it so officers don't need to lock or unlock the lockers manually.
The lockers look the exact same.
Booted up test server and brigged Urist McAntag, McVampire, McChangeling, McTide, and McNNO. All the lockers locked and unlocked properly. 
<hr>
<hr>
:cl:
fix: Fixes Deltastation's brig lockers.
/:cl:

Fixes the Deltastation Brig Lockers to Be Linked to the Door Timers

---

.github/workflows/ci.yml

Disable OpenDream CI as it's busted
CI working is good.
Can't.
<hr>
<hr>
NPFC

Disable OpenDream CI as it's busted

---

_maps/map_files/stations/deltastation.dmm

adds a magistrate and IAA spawn landmark to kerberos
having a proper start is good
Spawned in as magistrate/IAA on kerberos
<hr>
<hr>
:cl:
fix: Fixes magistrate and IAA spawn on kerberos
/:cl:

Adds Magistrate/IAA start to Kerberos

---

code/datums/mind.dm

Adding a new custom objective (rather than editing an existing objective) from the traitor panel would make its explanation text "Free objective", no matter what you tried to say the objective was.
It now keeps the text you gave it.
Please do not frustrate the admins.
Gave myself a new custom objective. Text was correct.
<hr>
<hr>
:cl:
fix: Admin-added custom objectives will no longer accidentally end up as "Free objective" sometimes.
/:cl:

Make adding custom objectives work right

---

code/controllers/subsystem/SSchat.dm
code/tests/_game_test.dm
code/tests/_game_test_puppeteer.dm
code/tests/attack_chain/test_attack_chain_vehicles.dm

This PR adds a small shim to SSchat to redirect chatlog messages sent in tests to a list in order to query that list for test assertions.
Improves fidelity for puppeteer testing by being able to actually check the contents of the chatlog to see the outcome of events, rather than inspecting the internal state of objects, since puppeteer tests are meant to be a player-imitating abstraction.
See modification of existing test as an example usage.
<hr>
<hr>
NPFC

Add ability to check chatlog for test assertions.

---

.github/PULL_REQUEST_TEMPLATE.md

Removes spaces in front of an `<hr>` tag on the pull request template. 
It will stop driving me insane every time I make a PR.
Made the changes based on fixing it before submitting other Pull Requests.
<hr>
<hr>
NPFC

Fixes <hr> tag spacing on the Pull Request Template

---

code/datums/uplink_items/uplink_general.dm
code/modules/mod/modules/modules_maint.dm

Updates spring lock description, so people will not ger confused.  FIX https://github.com/ParadiseSS13/Paradise/issues/27820
Linker says, it's fine!
<hr>
<hr>
:cl:
tweak: Clarified the spring lock module description to better specify its activation method (smoke).
/:cl:

Updates spring lock description to better indicate activation method

---

_maps/map_files/stations/deltastation.dmm

Makes the Head of Security's airlocks the command variant of airlocks.
Adds a keycard swiper to the office.
Head of Security is command, therefore they should get a command door. They should also have the ability to swipe for red, enable EA, and call for an ERT.
Loaded a test server, checked the airlock names, tried to go red but I can't because it's just me.
<hr>
<hr>
:cl:
fix: Fixed HoS' door color and lack of key card authenticator
/:cl:

Makes the HoS's Door Blue on Delta and Adds a Keycard Authenticator

---

code/modules/research/designs/smelting_designs.dm

Half the price of "Alien Alloy" sheets from the protolathe and ORM so they only cost 1 metal and 1 plasma instead of 2 metal and 2 plasma per sheets.
Alien Alloy is a "decorative" items much like plastitanium glass and plasma glass, except unlike those it has no real benefits to regular walls and tables AND cost twice as much, leading to anyone wanting to make a fancy alien area to drain all of the plasma from the ORM.
Now instead we can cover twice as much of the station in abductor coating for the same price.
Checked the material pricing on the protolathe.
Printed an alien alloy sheet from the protolathe. Checked it only used one metal and plasma and not two of each, it did.
Printed an alien alloy sheet from the ORM. Checked it only used one metal and plasma and not two of each, it did. …

Half printing price of alien alloy sheets

---

code/modules/clothing/suits/bio.dm

Reduces slowdown for Security Biosuits from 1 to 0.45, same as Security MODsuits.
Other biosuits are not affected by this PR.
Everyone is familiar with the dreaded Botany gaming with their fluorosulphuric acid + deathmix tomatos, which melts away most protection that you would have - While you can get breathing tubes to counter breathing in the toxic fumes, most injectproof clothing are not acidproof and will still melt from the acid.
Biosuits on the other hand are currently extremely underused due to their crippling slowdown, and the Security biosuit is usually left forgotten in the Armoury even when a Botany war criminal is out and about - While I'm hesistant in making all the biosuits move faster, I feel like the Security variant could use a little boost, especially since it is one of …

Reduces slowdown on Security Biosuits

---

.github/workflows/ci.yml

From pull request: 
https://github.com/tgstation/tgstation/pull/88988
`OpenDream was recently bumped to .NET 9, which is not on our runner image. I added an action which installs the required .NET version for DMCompiler to function.`
`Adding this action is not only good as a quick hack fix, but also for posterity.
I also considered the impact this has on our runner execution time, but my hope is that it should not matter if we have .NET installed already.`
<hr>
-  [x] I confirm that I either do not require [pre-approval](https://github.com/ParadiseSS13/Paradise/blob/master/docs/CODE_OF_CONDUCT.md#types-of-changes-that-need-approval) for this PR, or I have obtained such approval and have included a screenshot to demonstrate this below.
<hr>
NPFC

.NET 9 SDK setup action for CI

---

code/datums/beam.dm

This PR moves beam segments to their visual location in order to ensure that connect_loc signals attached to each beam segment fire when passed through at their perceived location. Fixes #27872.
Fixes legion beams causing 50x damage when walking under the legion.
Commented out godmode-ignoring targeting in hostile.dm, set legion boss attack probabilities to always fire a beam.
Spawned in player and made godmode, spawned in legion, and attacked. Walked through and crawled under beam to ensure that only one disintegration beam proc was fired.
<hr>
<hr>
:cl:
fix: Legion disintegration beams should no longer cause 50x their expected damage.
/:cl:

Fix legion beam damage output.

---

code/modules/power/engines/supermatter/supermatter_event.dm

Your honor, I plea oopsie daisy. Removes a double negative from event C-3.
Makes the event do what it says on the tin!
Code complied. 
<hr>
<hr>
:cl:
fix: Fixed SM event C-3
/:cl:

Fixes event C-3

---

code/modules/mob/living/brain/brain_say.dm
code/modules/mob/mob_misc_procs.dm

Fixes #27344
Fixes EMP'd brain speaking by making a new proc, brain_gibberish. First, it checks if the first letter is * and returns the message to allow emoting. Else, it checks the first letter of a Gibberish message and if the first letter is * or #, replaces it with one of the replacement characters. 
Trying to speak as an EMP'd robobrain would often result in an extremely annoying experience where your message fails to go through due to starting with * which attempts to emote.
Made myself a robobrain and EMP'd myself. Spammed chat and watched if I tried to emote.
<hr>
<hr>
:cl:
fix: EMP'd brains will no longer try to emote
/:cl:

Fixes brain gibberish from attempting to emote

---

code/modules/martial_arts/judo.dm

This PR makes `/obj/item/storage/belt/judobelt/equipped()` call its parent, ensuring that all the related bookkeeping and effects proc.
Judo belt can get in an inconsistent state when unequipped into a hand slot because its `in_inventory` is never set properly. This fixes that.
Equipped judo belt, and then pulled into empty hand slot. Ensured 'in_inventory' was set to 1, and that hovering over the belt in the hand slot properly outlined it.
<hr>
<hr>
:cl:
fix: Judo belts make the proper sounds when unequipped and are properly highlighted when hovering over them in hands after being unequipped from the belt slot.
/:cl:

fix bad judo belt unequip state

---

_maps/map_files/stations/emeraldstation.dmm

Fixes #27664
Fixes #27814
An assortment of small fixes including: A weird access choice on the armory outward door, the broken lockers in the abandoned security area (cargo maint), and added a fire alarm to xenobiology
bugfix good
booted up a test server and verified changes
<hr>
<hr>
:cl:
fix: Fixed emeraldstation abandoned sec lockers
fix: Fixed armory windoor access
fix: Gave xenobiology a proper fire alarm
/:cl:

EmeraldStation misc fixes

---

_maps/map_files/stations/cerestation.dmm
code/modules/mod/mod_theme.dm

Fixes a spot in the brig where a disposal pipe would sometimes route disposals coming from the warden's office into processing.
Makes sure that things thrown down the disposal chute from the warden's officer are properly routed.
Spawned a mob and used disposals in the warden's office.
Spawned a mob and used disposals in processing. 
Tracked routing of each mob.
<hr>
<hr>
:cl:
fix: Fixed a disposal junction leading from processing in the brig.
/:cl:

Fixes a Disposal Pipe in the Farragus Brig

---

code/game/machinery/doors/windowdoor.dm

Fixes #27565
Bugs bad.
Removed and reinstalled windoor electronics.
<hr>
<hr>
:cl:
fix: Airlock electronics no longer brick when removed from a windoor.
/:cl:

Fixes uninstalled windoor electronics.

---

code/game/objects/items/weapons/storage/uplink_kits.dm
code/modules/clothing/chameleon.dm

Adds a chameleon tie to the chameleon kit (standard and nukie).
Implementation of this is based on all other chameleon items.
It's the only slot missing a chameleon item.
This will help anyone using a chameleon kit disguise themself as another job.
Note: The default icon is now a black tie not a red tie.
- Compiled the code
- Spawned the chameleon tie in game
- Tested the UI to make sure it still worked
- Selected various neck items to disguise as
- Tested the EMP act on the tie
- Spawned in the complete chameleon kit to confirm that the tie is included
<hr>
<hr>
:cl:
add: The Syndicate now include a tie in their chameleon kit!
/:cl:

Adds Chameleon Tie

---

code/modules/hallucinations/hallucination_manager.dm

Hopefully fixes the runtime with xeno pouncers
Less runtimes
It compiled, I still don't have a consistent way of triggering this
<hr>
<hr>
NPFC

Hopefully fixes a runtime with the xeno pouncer

---

code/game/objects/effects/spawners/random/plushie_spawners.dm
code/game/objects/items/toys.dm

Adds Diona, Drask, Human, Kidan, Plasmaman, Skrell, and Borg plushies to the plushie spawner.
Removes Nian plushie from the list that says it doesn't contain Nan plushies so Nians aren't twice as likely to appear as any other species.
Borg plushie modules can be selected if no module has been selected using **Alt-Click**. If a module has already been selected, a cyborg module reset board can be used to turn it back into a basic borg plushie.
Borg plushies obtained from the loadout menu always start as standard module plushies. Borg plushies generated by the plushie spawner are randomized.
Prize balls and mapped-in plush spawners can now pick all the species plushies instead of arbitrarily lacking some and including others.
Borg plushies now include an extra gimmick based on stuff actual …

Borg Plushies Have Selectable Modules, Adds Missing Species Plushies to Plush Spawner

---

code/modules/atmospherics/machinery/portable/canister.dm
code/modules/atmospherics/machinery/portable/portable_atmospherics.dm

This PR makes it so that portable atmos machines, notably canisters, spend less time in SSair updating their icons and checking to see whether they should update their icons. Despite all the bookkeeping and flag updating here, update_icon was still getting called and executing countless times, to the tune of 3.5 million times a round:
This removes all that and just calls update_icon when it needs to be called, when we know the appearance needs changing:
- When the portable is connected to a port
- When a tank has been inserted
- When the total pressure in the portable has changed
- When the can is repainted
Performance.
Attached canisters to ports, unattached, added tank to canister, removed tank, opened valve, watched light as pressure changed, modified canister paint job.
<hr>
<hr>
NPFC

Stop portable machines updating their icon every atmos tick

---

code/modules/power/lights.dm

So, remember this line from the nightshift message?
Yeah, turns out that never worked. But what if it did?
[Closed my instance by accident but the nightshift power usage was 40 W]
Finally, the text isn't lying and the bug has been fixed
Dim lights = power saving
See above
See above
<hr>
:cl:
fix: night shift lighting actually saves power now
/:cl:

Makes night shift actually save power like it should

---

code/modules/response_team/ert_outfits.dm

Removes NAD Pinpointer from Amber/Red ERT, gives it to Gamma. Amber/Red now get a Crew Pinpointer.
NADJack is kinda a thing. Making so that you have to prep for all of Security, the Captain, the Blueshield, AND any future ERT is kinda rough. Unless we want to change NADJack to be something where you do have hijack-esque perms, this should make it so you dont have to go so big to have a chance at winning.
Loaded in and checked the loadouts.
<hr>
<hr>
:cl:
tweak: Amber/Red ERT gets Crew Pinpointer, Gamma gets NAD Pinpointer
/:cl:

Amber/Red ERT Now Get Crew Pinpointer, Gamma Gets NAD Pinpointer

---

_maps/map_files/stations/cerestation.dmm

Swaps the area of the Farragus Service Asteroid bathroom from Dormitory Toilets to Unisex Restroom
The toilets are not in dorms. The labelling will direct engineers and atmos techs to the incorrect part of the station if an alarm goes off there. This is bad and should be fixed.
Loaded in.
Saw it was unisex and not dorm.
<hr>
<hr>
:cl:
fix: Fixed Farragus' service toilets being incorrectly labelled as "Dormitory Toilets".
/:cl:

Fixes Farragus Service Bathroom Area Being "Dormitory Toilets"

---

code/controllers/subsystem/SSjobs.dm
code/game/jobs/job_objectives/science.dm

When you spawn in, you get notified about your job objectives (currently: RD, scientist, roboticist, virologist). These are the same objectives you can already find in IC > Notes.
Job objectives, that are meant for new players to get started in their department, will be actually displayed for said new players, not just get tucked away in an obscure IC verb.
I intend to add more job objectives, figured I'd split this into two separate PRs.
Roboticist:
Scientist:
Research Director:
Virologist:
1. Spawn in as a Scientist, Roboticist, Research Director, or Virologist
2. Take screenshots as above
<hr>
<hr>
:cl:
add: Job objectives are now displayed when you spawn in (currently, this is for the Research Director, Roboticists, Scientists, and the Virologist).
/:cl:

Adds announcement of job objectives upon spawning in

---

code/game/objects/items/weapons/twohanded.dm

This PR fixes fusion gauntlets failing to deploy with empty hands. Fixes #27945.
Bugfix.
Spawned fusion gauntlets and pyro core, inserted core into gauntlets, wore gauntlets and confirmed I could activate them with the UI button. Waited for cooldown, put a toolbox in my hand, flagged it NODROP, ensured I could not activate gauntlets.
<hr>
<hr>
:cl:
fix: Fusion gauntlets will now properly activate.
/:cl:

fix fusion gauntlets failing to deploy

---

code/game/objects/items/his_grace.dm

Forcefully gives ascended grace nodrop
If you drop grace while ascended you get instantly eaten lmao
It compiled
<hr>
<hr>
:cl:
fix: His Grace now permanently has nodrop when ascended again
/:cl:

Fixes his grace nodrop

---

code/game/objects/items/stacks/sheets/mineral.dm
code/game/objects/structures/tables_racks.dm

1. Adds `surgical tray` (the one that holds surgical tools) to titanium recipes, costing 1 sheet
2. Renames `surgical tray` (the wheeled one) to `surgical instrument table`
3. Increases the cost of `surgical instrument table` to 3 sheets
1. Cargo can print / order surgical tools, but we have no way to store them properly should the originally spawned 2 trays get destroyed
2. We had two identically named items
3. It made no sense for an entire structure to only cost that few sheets
https://github.com/user-attachments/assets/c62a564c-0d1c-4c56-9ea3-62626384d80c
See above, the video has the old costs
<hr>
<hr>
:cl:
add: Added surgical trays (the green box holding surgical tools) to the titanium recipes, they cost 1 titanium sheet to be crafted.
tweak: Surgical trays (the draggable, green …

Adds surgical tray crafting recipe, renames and increases cost for the wheeled one

---

code/modules/mob/living/carbon/examine.dm

Fixes abstract items showing on mob examine by moving the trait_skip_examine up so the else doesnt falsely trigger
Abstract items should not show on examine
skip examine items should still not show on examine
Equipped abstract nullrod.
Did not show on examine, did show the fleshy arm message
Made a non abstract item have TRAIT_SKIP_EXAMINE
Did not show on examine still
<hr>
<hr>
:cl:
fix: Fixes abstract items showing on mob examine
/:cl:

Fixes abstract items showing on mob examine

---

code/game/objects/effects/spawners/depot_spawners.dm

Replaces autosurgeons with standalone implants.
Removes, adds, replaces items from next pools:
- Armory:
- Qani-Laaca (40TC) replaces gloves of North Star (40TC).
- Added proto-adrenal biochip (10TC), toy SR (priceless).
- Officer:
- Added toy c20r (25TC), snakesfang (25TC), tactical first aid kit.
- Removed **self-repair** module for borgs (I **didn't** mention it to get the pre-approval), 10 uranium (we have 20 uranium in rare loot).
- Rare:
- Chameleon kit (10TC) replaces chameleon jumpsuit.
- Added chameleon voice change mask (5TC), plate compression module (10TC), hyper medipen (10TC), syndie eva.
- Removed chameleon stamp, zippo, tactical first aid kit, syndie and black jacket.
- Common:
- Added combat and sniper uniforms (from bundles, same as tactical turtlenecks), zippo, …

Adjust depot loot a little and remove some irrelevant items.

---

code/modules/mob/living/carbon/carbon_procs.dm

Fixes a runtime in carbon/Destory
These two lists are both lazy, so they should be using QDEL_LAZYLIST. Normally, this isn't a big deal, because QDEL_LIST_CONTENTS checks if(the_list). In the case of processing_patches, however, this has caused a runtime because we LAZYREMOVE a patch when it's deleted, and qdel will immediately trigger that.
Runtimes bad.
Nope. It's replacing one define with a slightly more paranoid one. If it compiles, it's fine.
<hr>
<hr>
NPFC

Fix carbon/Destory runtime

---

code/game/atoms_movable.dm

Simplifies this `if`-statement a bit
- `has_buckled_mobs()` is useless here, it doesn't nullproof it in any way shape or form
It compiled
<hr>
<hr>
NPFC

Refactors a small bit of `forceMove()` code

---

code/modules/mob/living/silicon/robot/robot_mob.dm

Makes borgs not runtime if they try to use an empty module slot
Runtimes bad
It compiled
<hr>
<hr>
NPFC

Fixes a minor borg runtime

---

code/modules/admin/verbs/infiltratorteam_syndicate.dm

The SIT spawn prompt was 9 years old. It didn't account for the TC inflation, and falsely claimed that they wouldn't be able to trade TC.
Honest messaging.
I changed a string. If this somehow breaks something, I'm going to need to step away from the computer for a while.
<hr>
<hr>
:cl:
fix: The prompt admins get when spawning an SIT has been updated to account for the TC inflation in 2023. We should be less likely to give far too little TC now. Oops.
/:cl:

Update SIT spawn prompt

---

code/_onclick/item_attack_legacy.dm

Adds missing parentheses to `/obj/attackby__legacy__attackchain`. You can no longer hit objects with `can_be_hit = FALSE`
Beating a holoray and fire isnt immersive.
Spawned /obj/effect/holoray and a door.  Tried  beating the holoray and tried beating the door. The door was attacked, the holoray wasnt.
Cleaned blood with soap.
<hr>
<hr>
:cl:
fix: Can't beat fire and holorays anymore
/:cl:

Fix: legacy attackby respects can_be_hit again

---

code/modules/client/preference/preferences.dm
code/modules/mob/living/carbon/human/species/diona_species.dm

This removes the weird human eyes that are layered on top of diona characters' heads. A diona's actual eyes are the small lime green spots on their face and body, and most of the time to make your character look right you'd have to deliberately change the color of the human eye overlay to the diona skintone to make it harder to see.
This also removes the menu item in preferences to customize the color of eyes for diona, because it doesn't work on the diona's actual eyes, only the human eye overlay. 
It also removes the menu item to customize the color of slimepeople eyes, because (as far as I could tell in my testing) the NO_EYES flag on slimepeople prevents their eyes from being a custom color, and the customization menu has no effect.
I think having the human eyes overlay on dionea …

Diona eye adjustment

---

code/datums/status_effects/debuffs.dm
code/modules/mob/living/carbon/carbon_emote.dm

This PR replaces sleep with paralyze on faint
It is abusable.
Compiled, fainted, all good
<hr>
<hr>
NPFC

[s] Replacing Sleep with Paralyze on faint

---

code/game/objects/items/devices/scanners.dm

Fixes a small oversight where a conditional check returned true no matter if the user of a scanner was hallucinating or not.
Stops wacky death times on the scanner even if the user is not hallucinating
Used a health scanner on a dead mob without hallucination to check for normal behavior.
Used a health scanner with the hallucination trait to check for proper hallucination behavior.
Checked that the hallucination was working properly by using a ghost to scan the same mob with ghost health scanner.
<hr>
<hr>
:cl:
fix: Fixed an oversight with health scanners always showing random death times.
/:cl:

Fixes an oversight with med scanner hallucinations

---

code/game/machinery/computer/sm_monitor.dm
code/modules/power/engines/supermatter/supermatter.dm

Stops the SM monitoring console from pulling data from crystals that aren't on sim_floors.
It just doesn't add them to its list(array?)
Also adds a default value to the sm's gas coeff var. _(I believe trying to get and display a null was causing this in the first place)_
Fixes #27885 
TGUI crashes are bad, and annoying.
Tested and works, monitoring console behaved as normal, shards in crates no longer appear until they are opened.
Video below is proof of new behaviour and NO crashing.
https://github.com/user-attachments/assets/90b708fb-6d57-408e-8a6a-5d591979d2de
<hr>

[FIX] SM monitoring console crash

---

code/game/machinery/hologram.dm

Holopads now only activate on help intent for humans. You can no longer try to disarm, grab, or harm intent click on them. Security and antagonists alike rejoice.
You ever try clicking someone until they're sideways and you get jumpscared by a holopad menu? It sucks.
Help intent with empty hand: Menu opens
Disarm, Grab, and Harm intent with empty hand: Menu doesn't open
<hr>
<hr>
:cl:
tweak: Holopads now only open their menu on help intent with an empty hand to prevent accidental clicks on them during combat.
/:cl:

Holopads now only activate on help intent

---

code/game/machinery/vendors/departmental_vendors.dm

Adds 20 papersacks to the Plasteel Chef's Dinnerware Vendor.
Papersacks are a great gimmick for chef's to package food and encourages some wholesome interactions, having some to start up your packaged food business is handy and might inspire newer chef players to also try the same. *(additionally, they would also discover the crafting feature when they need to make more and i feel like the crafting feature isn't so obvious right now to newcomers)*
There's 20, so there's plenty to begin with but when business begins to boom one might have to steal and empty a bin of papers.
>join
>check vendor
>paper sack
> :D
<hr>
<hr>
:cl:
add: The Chef's Dinnerware vendor now has some papersacks to jumpstart your packaged food business.
/:cl:

Adds papersacks to the Plasteel Chef vendor

---

_maps/map_files/RandomRuins/SpaceRuins/rocky_motel.dmm
_maps/map_files/RandomRuins/SpaceRuins/submaps/rocky_motel_submap.dmm

Removes a fluff jacket spawner from rocky motel.
~~It messes with the space loot pool.~~ Not a valid object, shouldn't have been originally.
Server booted and no issues occured.
<hr>
<hr>
:cl:
del: Removed fluff jacket spawner from Rocky Motel
/:cl:

Removes a Fluff Spawner in the Rocky Motel and its Submaps

---

code/modules/events/immovable_rod.dm

Immovable rods cause more holes in the floor, back to their original ~24% chance.
Immovable rods now cause light damage to more floors that they don't break.
Immovable rods are more likely to break objects and deal more damage to mobs.
Wizard rods deal more wall damage.
With #27894, engineering ERTs can more effectively deal with large-scale breaches, So even if a rod breaks a lot of floors, it's still feasible to recover the station. They've also moved up to a major event since the initial nerf, so it's fair to make them more deadly.
Wizard rods shouldn't have gotten nerfed, but I forgot to fix that before MILLA 2 went in.
Threw an event rod at the station. Many floors and objects were broken.
CLONGed my way through the station as a wizard. Many walls were broken.
CLONGed my way through …

Re-buff immovable rods

---

code/modules/mob/living/silicon/robot/robot_mob.dm

Moves the setting of the emagged state on borgs before sleep, so borgs can't be emagged multiple times within a 0.6 seconds interval.
Fixes #28007
Poor borgs
Emagged a cyborg and clicked quickly, but it was only emagged once.
<hr>
<hr>
:cl:
fix: Borgs cannot be emag spammed
/:cl:

[FIX] Cyborgs cannot be emag spammed

---

code/game/objects/items/weapons/storage/belt.dm

Fixes the wrong icon state on the sword sheaths when clicked with telekinesis.
Fixes the unsheath sound playing when clicked with telekinesis.
Fixes #27782 
An invisible items is bad
Gave myself telekinesis, clicked on the sabre sheath, it didn't become invisible and didn't play the unsheath sound
<hr>
<hr>
:cl:
fix: Fixed the sword sheaths disappearing when clicked with telekinesis
/:cl:

Fix sword sheaths disappearing when clicked with telekinesis
