ParadiseSS13/Paradise

code/datums/status_effects/buffs.dm
Ensures that you don't lose the medical HUD from the Rod of Asclepius if you equip and then unequip any medical HUD.
Fixes #27991 
Bugs are bad.
Used the Rod of Asclepius, equipped the medical HUD, then unequipped the medical HUD. The HUD remained.
<hr>
<hr>
:cl:
fix: Fixed an issue where the medical HUD from the Rod of Asclepius would be lost when equipping and unequipping other medical HUDs.
/:cl:
=> Fixes the loss of the medical HUD from the Rod of Asclepius

code/modules/mob/mob.dm
Examining atoms with double-examine lore blurbs now tells you you can examine again to find out more.
Edit: Double examining atoms with no lore blurb now gives you the normal examine message, rather than a message telling you there's no blurb.
There are a bunch of lore blurbs in the game that most players will miss because there's no way to know which atoms have them.
This makes the lore blurbs more visible and stops the writers' work from going unread.
Edit: This also lets you examine atoms like pipe pressure meters as fast as you like without getting a "There's nothing more to see" message.
Examined a bunch of atoms with lore blurbs once and twice.
Examined a bunch of atoms without lore blurbs once and twice.
<hr>
<hr>
:cl:
tweak: Double-examine lore blurbs are more visible.
tweak: …
=> Advertises double-examine lore blurbs on a single examine

code/controllers/subsystem/SSair.dm
Restores a missing conditional from SSair's "am I good to start running?" check.
Code correctness, fixes CI failures.
The condition was there before, and got dropped by accident. It compiles. If it passes CI, it's fine.
<hr>
<hr>
NPFC
=> Stop SSair ignoring sleepers

code/game/gamemodes/dynamic/antag_rulesets.dm, code/game/gamemodes/dynamic/dynamic.dm, code/game/gamemodes/game_mode.dm
Fixes an issue with dynamic late spawning
Bug bad
Security cant roll antag :)
<hr>
<hr>
NPFC
=> [s] Fixes an issue with dynamic late spawning

code/__DEFINES/text_defines.dm, code/modules/mob/mob.dm
This ups the flavor text length before being cut off to 400, from 40
40 characters is really not enough to describe anything meaningful about a character.
400 characters sounds like a _lot_, but it's about this much:
For reference, you're currently only allowed this much before cutoff:
That's not enough to write something even as simple as "An average-looking skrell with blue skin."
It'd be nice to be able to read a bit more of characters' flavor text without having to open up a clunky popup. 400 characters isn't a huge amount, but it's enough to write at least a decent amount about your character. It's not such a large amount that it'll crowd out your chat window and interfere with mechanical uses for examining people.
Being able to write/read flavor text more easily might add to the RP …
=> Ups flavortext length before cutoff to 400

code/datums/uplink_items/uplink_general.dm, code/modules/surgery/organs/augments_arms.dm
Provides much needed nerfs to the Mantis Blades.
Raises the prices on Mantis Blades 60 -> 75
Reduces the force on Mantis blades from 20 -> 15 (Syndicate) and 18 -> 12 (Nanotrasen)
Removes Mantis blades from the Nuclear Uplink
Removes Mantis blades from Surplus
Removes Mantis blades from discount item list
Mantis blades were a bit over tuned when introduced to the game. This levels them out after being tested in different conditions with multiple Balance Team members. This puts them more in line with higher damaged weapons while considering other items they can be paired with.
Spawned in Uplink and checked Force on Mantis Blades (Syndicate) and checked their price.
Spawned in Mantis Blades (Nanotrasen) and checked the force.
Spawned in a Nuclear Uplink and checked to see if Mantis Blades …
=> Nerfs Mantis Blades

code/game/turfs/simulated.dm
Ensures that simulated turfs clean up their wind effect before going away.
Probably fixes #28048 
Bugs bad.
I can't reproduce the original issue, but even if this doesn't fix it, it's harmless to do.
<hr>
<hr>
:cl:
fix: Added some extra cleanup to hopefully prevent wind effects from getting orphaned and remaining forever.
/:cl:
=> Don't orphan wind

code/game/machinery/doors/airlock.dm, code/game/objects/items/control_wand.dm
Fixes #27816
Migrates door remotes to the new attack chain
Removes an unused var from airlocks and unused procs from door remotes
new attack chain + bug bad
None of the remotes tapped objects pre-migration and none of them tap objects after.
Janitor Keyring
Door Remote
Access Tuner
<hr>
<hr>
NPFC
=> Migrates door remotes to the new attack chain + fixes janikeyring

code/game/objects/items/crayons.dm
Fixes #27772
Registers a signal on the spray cans New(), preventing it from opening the crayon menu.
Double menu is confusing
Checked crayon menu
Checked spraycan menu
Freshly spawned crayons do random letters, runes and grafitti
Freshly spawned random crayons are in random colors
<hr>
<hr>
:cl:
Fix: Spray can no longer opens 2 menus
/:cl:
=> Fixes spray can double menu

code/datums/uplink_items/uplink_traitor.dm, code/game/gamemodes/cult/cult_items.dm, code/game/gamemodes/vampire/traitor_vamp.dm, code/game/gamemodes/vampire/vampire_gamemode.dm, code/game/gamemodes/wizard/soulstone.dm, code/game/machinery/dance_machine.dm, code/game/machinery/tcomms/tcomms_base.dm, code/game/mecha/equipment/tools/janitor_tools.dm, code/game/objects/items/salvage.dm, code/game/objects/items/weapons/bio_chips/bio_chip_fluff.dm, code/game/objects/items/weapons/storage/backpack.dm, code/game/objects/items/weapons/storage/bags.dm, code/game/objects/items/weapons/storage/belt.dm, code/game/objects/structures/crates_lockers/closets.dm, code/game/objects/structures/crates_lockers/crates.dm, code/modules/antagonists/vampire/vampire_powers/hemomancer_powers.dm, code/modules/awaymissions/mission_code/ruins/oldstation.dm, code/modules/awaymissions/mission_code/ruins/telecomns.dm, code/modules/mining/equipment/wormhole_jaunter.dm, code/modules/mob/living/simple_animal/hostile/hellhound.dm, code/modules/projectiles/ammunition/magazines.dm, code/modules/projectiles/guns/energy/telegun.dm, code/modules/projectiles/projectile/special_projectiles.dm, code/modules/reagents/chemistry/reagents/alcohol.dm, code/modules/reagents/reagent_containers/glass_containers.dm, code/modules/recycling/belt-placer.dm, code/modules/research/designs/bluespace_designs.dm, code/modules/research/designs/janitorial_designs.dm, code/modules/research/designs/stock_parts_designs.dm
Goes through a bunch of random things that reference bluespace and ensures they comply with Lore Team's vision for it. Also updates some descriptions and removes dead memes while I'm there.
Ensuring bluespace is handled the same way everywhere it's referenced helps us keep the setting in line.
Functional descriptions are also good.
Loaded in, spawned the items in question, you know the drill. 
<hr>
<hr>
:cl:
tweak: Updated a bunch of names and descriptions referencing bluespace
/:cl:
=> [LORE] Bluespace Lore Pass Pt. 1

code/game/objects/structures/window.dm
Gives plasma reinforced windows and plastitanium windows heavy rad protection.
Unreinforced full tile plasma windows have been given the default very light rad protection (like the basic full tile windows currently are).
Other smaller dir-based windows have been given no rad protection.
Mainly because I want the plasma full tile r-windows around the SM to have radiation protection but this makes things more consistent overall. Right now only the normal R-windows have heavy rad protection.
Big window = some radiation protection.
Big window + reinforced = heavy radiation protection.
Small tiny dir window = no protection.
I think this is easier to understand for the players compared to the current system where plasma windows (all types) have no radiation protection.
This also means that the …
=> Gives full tile R-Windows and Plasma R-Windows and Plastitanium heavy rad protection, nerfs smaller dir based windows.

code/modules/mob/living/carbon/carbon_procs.dm, code/modules/reagents/chemistry/reagents/medicine.dm
This changes Lazarus Reagent to behave more like a chemical version of defibrillators; it will give the ghost a notification that their body has Lazarus reagent in it, and if they return to their body, they will be revived. It also gives feedback in cases where this would fail or can't succeed.
It was once implemented this way here #18910 and was reverted here #19089 due to bugs.
I would like to prefix everything here with the fact that these are my most extensive changes to date, and with a history of how changes like this have not worked well on live before, a TM will likely be needed.
This would also resolve #27822 which is what first sent me down the rabbit hole.
Not being "SUDDENLY ALIVE" is good, and _should_ stop rare edge cases where LR revives someone and they are catatonic.
I …
=> Lazarus Reagent no longer forces you Alive

code/datums/datumvars.dm
Update VV to work better in 516 by stopping it from editing the DOM like crazy
Gives me profound sympathy for anyone else who's had to do anything moderately complex with this godawful browser
516 compatibility
VV'd something.
Searched.
Used down and up both while searching and not.
Used enter to edit a value.
<hr>
<hr>
NPFC
=> Update VV to work better in 516

code/__DEFINES/tools_defines.dm, code/modules/surgery/surgery.dm
- Improves spacing when only two items are specified
- Fixes a runtime that would occur when non-surgical tools (such as screwdrivers) were the primary tool for a surgery
- Ensures regular tools (or anything else unconventional) will display properly on the computer.
- Regular tools will only appear on the surgical computer if they have a 100% success chance (or are the first item in the tool list)
The computer being broken for robotic surgeries isn't great. This ensures better parity.
Sliced open some robots and a vulp, ensured everything worked as intended.
<hr>
<hr>
:cl:
fix: The surgical computer now properly displays the names of work tools for the next steps in surgeries.
fix: Spacing on the surgical computer's tool display has been improved.
/:cl:
=> Fixes some display issues with the next step on the surgical computer

code/modules/clothing/clothing.dm
Switches the adjacent check for toggling sensors. Mobs and objects have different `Adjacent` procs, and it is objects that will recurse to check if they're in storage or on the mob.
Fixes #26520
Toggled sensors in and out of disposals or closets, also stuffed jumpsuits in storage to try too.
<hr>
<hr>
:cl:
fix: Suit sensors can be toggled while in disposal or other large containers.
/:cl:
=> Fix toggling suit sensors while inside other objects

code/datums/spell_targeting/cone.dm, code/datums/spells/cones/cone_spell.dm
Fixes cone spells sometimes trying to go diagonal
Diagonals no worky
Tried to cast diagonal, went into a cardinal direction instead
<hr>
<hr>
NPFC
=> Fixes cone spells accidentally going diagonal

_maps/map_files/stations/deltastation.dmm
Adds a fire alarm to the Kerberos medbay hall.
Stops the firelocks from being eternally engaged once triggered.
Fixes #28060 
(I hope I did this correctly)
In game:
StrongDMM:
Flooded medbay with plasma, was able to toggle the fire alarm on and off.
Breached medbay, and allowed it to space, was able toggle the fire alarm on and off.
<hr>
<hr>
:cl:
add: added missing fire alarm
/:cl:
=> Adds a missing fire alarm to Kerberos medbay

code/modules/shuttle/shuttle_manipulator.dm
Removes `/obj/machinery/shuttle_manipulator/proc/action_load`, replaces it with `/obj/machinery/shuttle_manipulator/proc/action_load_old` which was, somewhat ironically, more recently updated.
Dead code is bad.
Compiled, confirmed it wasn't used.
<hr>
<hr>
NPFC
=> Remove an old proc

code/modules/mod/modules/modules_medical.dm, code/modules/mod/modules/modules_supply.dm, code/modules/telesci/gps.dm, code/modules/tgui/modules/crew_monitor.dm
Makes UI based modsuit modules act like on TG.
Allows to use crew monitor module, gps module with modsuit state off.
Doesn't anymore spawns a crew monitor/gps in your hand with nodrop flag, instead just opens a UI on module use.
Turns off mod's GPS by default, so you are not going to see "Syndiecake" or "DK Excavator" on your GPS roundstart because of the mods that are spawned in the ruins.
There was no point of using them. Most of the time you use GPS or a crew monitor - you have them in pockets, belt or chest slot, so their UI stands open and you can track the data to get the most recent info. Having them in your hands was ridiculous.
With this PR they become useful - you trade 1 pocket or similar slot for 1 modsuit complexity. 
Blueshield doesn't have to turn on his modsuit in order to …
=> Change behavior when using 2 UI dependent modsuit modules.

code/modules/admin/verbs/one_click_antag.dm
Lets admins know who just rolled antag with one-click-antag, and removes the guessing game.
Hopefully helps with handling situations where people in space are made vampires.
Feedback is also good, no more having to guess who was just made antag.
Tested on a local server, sends feedback. Seems to work just fine. 👍
All true and false changes seem to work just fine too.
<hr>
<hr>
=> Makes One-Click-Antag report who was made antag

code/modules/clothing/head/helmet.dm, code/modules/clothing/suits/armor_suits.dm
Title. Corrects the descriptions of the generic armor vest and helmet.
Descriptions which lie to people are bad.
spawned the items and observed them.
<hr>
<hr>
:cl:
fix: Fixes two armor descriptions
/:cl:
=> [FIX] Fixes descriptions of two armor pieces

code/modules/mob/living/simple_animal/hostile/hostile.dm
This PR does a null check before this runtime failure in tests:
```
[2025-01-25T19:06:28] Runtime in code/modules/mob/living/simple_animal/hostile/hostile.dm:470: Cannot read null.loc
proc name: EscapeConfinement (/mob/living/simple_animal/hostile/proc/EscapeConfinement)
src: the leg (/mob/living/simple_animal/hostile/ancient_robot_leg)
src.loc: null
call stack:
the leg (/mob/living/simple_animal/hostile/ancient_robot_leg): EscapeConfinement
the leg (/mob/living/simple_animal/hostile/ancient_robot_leg): DestroySurroundings
the leg (/mob/living/simple_animal/hostile/ancient_robot_leg): leg_movement
the Vetus Speculator (/mob/living/simple_animal/hostile/megafauna/ancient_robot): leg_control_system
the Vetus Speculator (/mob/living/simple_animal/hostile/megafauna/ancient_robot): …
```
=> fix flaky vetus test failures in the dumbest way possible

code/__HELPERS/game.dm
Refactors `/proc/get_mobs_in_view` and its child `/proc/recursive_mob_check`, saving ~28% total CPU.
Performance goes brr
Before:
1.22e-3 per call
After:
8.80e-04 per call
~28% savings
This proc uses ~25s of total CPU time over a 2 hour round, meaning we save ~7s of total CPU time per round.
Heard Poly while standing in the room.
Heard Poly while in a locker.
Heard Poly while in a backpack in the locker.
<hr>
<hr>
NPFC
=> Refactor /proc/get_mobs_in_view for speed

code/game/turfs/space/space_turf.dm, code/game/turfs/turf.dm
This PR fixes being unable to lay cable on catwalks in space by clicking on the space itself. Fixes #28069.
Bugfix.
Wired solars, using alt-click to specifically select the space, and not the catwalk on the space. Confirmed it worked as an engiborg.
<hr>
<hr>
:cl:
fix: Cables can properly be placed on space catwalks by clicking on space.
/:cl:
=> fix catwalk cabling placement when clicking on space

code/game/objects/effects/effect_system/effects_other.dm
Removes fadetype, fade, and the flick call in /datum/effect_system/trail_follow, as large ammount of flick calls seems to lead to effect removal corruption per  https://github.com/ParadiseSS13/Paradise/pull/25777, https://github.com/ParadiseSS13/Paradise/pull/25898, and this issue port showing up after flick was reintroduced: https://github.com/ParadiseSS13/Paradise/issues/28103
Fix: #28103
Random jetpack effects when cleaning decals is bad
https://cdn.discordapp.com/attachments/984761070159818753/1332891795960631377/Paradise_Station_13_2025-01-25_20-55-47.mp4?ex=6796e7b8&is=67959638&hm=1129906d6701c3307271ee1dbe85c3adf83558aaeb07120f29c56a36ce5003e8&
https://cdn.discordapp.com/attachments/984761070159818753/1332892069307617290/Paradise_Station_13_2025-01-25_20-56-51.mp4?ex=6796e7f9&is=679 …
=> kills flick from jetpacks again

code/modules/hydroponics/hydroponics_tray.dm
Fixes #28113.
Also removes 2 empty lines in the code that I saw.
Bugs are bad.
Used a cultivator on a hydroponics tray, with and without weeds. It didn't go bang.
<hr>
<hr>
:cl:
fix: Cultivator no longer attacks hydroponics trays.
/:cl:
=> Fixes cultivators attacking hydroponics trays

code/modules/mob/living/simple_animal/slime/slime_powers.dm
Prevents TGUI crash when slime tries to feed with 0 valid targets, by not allowing to call a a TGUI input with 0 options.
Bugs are bad! I hate them!
After
<hr>
<hr>
=> Prevents TGUI crash when slime tries to feed with 0 valid targets

code/__HELPERS/game.dm
Removes a redundant block that results in duplicate messages
Bugs bad
Probably should.
<hr>
<hr>
:cl:
del: Doubled messages.
del: Doubled messages.
/:cl:
=> Remove redundant block that results in duplicate messages

_maps/map_files/stations/deltastation.dmm
Gives science access to the mecha bay, as robotics had access to sci via it, so why should science not get that privilege?
Moves a sign, that was covering up the guest pass machine
Adds a tiny fan to the toxins launch room
And fixes a tile that was the wrong colour in break room.
Also adds some fire alarms scattered about the main hall for sci, as it lacked them before hand. 
As stated above, robotics can just run into rnd via the mecha bay, and the door is just kinda.. in rnd, it's a strange design choice, but RND not having access to the door that leads into/out of their room was something thats bugged me for a  while.
The sign is self explanatory, it was covering the guestpass machine
The fan makes toxins 100% less annoying todo
And there was a stray floor tile that i think i did ages …
=> Touches up deltas science a little

code/modules/admin/db_ban/functions.dm, code/modules/admin/topic.dm, code/modules/mob/mob_login_base.dm, code/modules/mob/new_player/new_player_login.dm
Changes the ban process from Player Panel to rely on `last_known_ckey` instead of `ckey`, so that banning (including jobbanning) a disconnected player doesn't rely on manual bans.
Better admin tooling is good.
Jobbanned myself from one of each category of ban.
Jobbanned myself from each ban category entire.
Banned myself. (It bailed out at the last second, but still kicked me.)
Banned a volunteer (thank you, Ratcliffe!) both while they were online and after they'd been kicked for the first ban.
Jobbanned the same volunteer after they were gone.
<hr>
<hr>
NPFC
=> Easier banning of DC'd players.

code/modules/mob/living/simple_animal/hostile/megafauna/hierophant.dm
This PR fixes an issue where the hierophant blast would trigger BYOND's recursion limit due to simple mobs dropping mob spawners, which in the process of generating their organs, would trigger the hierophant blast on the same tile. Note that this wasn't actually an infinite loop, but a deeply nested call stack which caused BYOND to barf.
Better logic.
Yeah
<hr>
<hr>
NPFC
=> fix recursion limit triggering in hiero blasts

code/modules/mob/living/simple_animal/slime/slime_mob.dm, code/modules/mob/living/simple_animal/slime/slime_powers.dm
Stops the feeding process if slimes resist()
Either with the keybind or by clicking the "Buckled!" icon.
Fixes #27903 
Opening a tgui menu full of targets to then having to try and select your current one to stop feeding is bad.
Tested on a local server, could use resist to stop feeding. ✔
Video of testing post changes;
https://github.com/user-attachments/assets/f4fa9a94-8676-4879-8d55-01c973e0d089
<hr>
<hr>
:cl:
fix: Slimes can resist to stop feeding.
/:cl:
=> [FIX] Slimes can now resist to stop feeding

code/_onclick/ai_onclick.dm, code/game/machinery/hologram.dm, code/game/mecha/mecha.dm, code/modules/mob/camera/eye/hologram_eye.dm
PR fixes https://github.com/ParadiseSS13/Paradise/issues/28022
PR fixes https://github.com/ParadiseSS13/Paradise/issues/28056
PR #25078 introduced a few bugs related to AI eyes, mechs, and holograms, which are referenced in #28022. This change fixes those bugs.
* Entering a mech with an active hologram eye will now release that eye before granting control of the mech.
* Double clicking on a turf as an AI while in a mech will no longer unstick the camera from the mech.
* When exiting a mech, the AI will now properly refocus on its core instead of on the spot that it first entered the mech.
* AI will no longer receive duplicate original audio from holopads, and now will receive only relayed speech.
* AIs will no longer be able to activate a holopad while occupying a mech.
Bugs are bad. …
=> Fixes #28022: mecha/AI/hologram bugs from #25078

code/game/machinery/vendors/vending.dm
Fix a vending migration bug. ITEM_INTERACT_COMPLETE is definitely not a canister.
Bugs bad.
If it passes CI, it can't be any more broken than what's currently there.
<hr>
<hr>
:cl:
fix: Refill canisters should work on vending machines again.
/:cl:
=> Fix a vending migration bug

code/game/objects/items/weapons/stock_parts.dm
This PR fixes the logic check for distance for BRPEDs which I mistakenly inverted in #27784. Fixes #28127.
Bugfix.
Spawned with debug outfit, went into kitchen, used tier 4 BRPED to click on machines from a distance, ensured upgrades occurred.
<hr>
<hr>
:cl:
fix: Bluespace RPEDs will properly upgrade machines from a distance again.
/:cl:
=> fix brped distance check

code/controllers/subsystem/SSthrowing.dm
This PR resets the glide size of thrown objects once the throw ends.
Throwing things increases their glide size and without a reset, their movement becomes keyed to the new glide size and is jumpy and weird.
Threw a monkey, VV'd to ensure glide size reset.
<hr>
:cl:
fix: Thrown simple mobs should no longer have jumpy/glitchy movement after being thrown.
/:cl:
=> reset glide size for thrown objects once throw ends

code/game/machinery/clonepod.dm
This PR fixes cloning pods not accepting reagent transfers from open containers.
Bugfix.
First attempted with closed container, then open container.
https://github.com/user-attachments/assets/94213dfb-41fb-4893-8f58-6a9373cf98ff
<hr>
<hr>
:cl:
fix: Cloning pods properly accept reagents from containers.
/:cl:
=> fix cloning pods not accepting beaker transfers

code/game/mecha/mecha.dm, code/modules/mob/living/carbon/human/human_defense.dm
Makes it so mechas cant "melee" the floor, eating attack cooldown timers. I believe one of the attack chain prs messed with it.
Also, i found that phazons on the burn mode dealt brute still, and have for over 5 years. so, thats something. well, was.
Bug fixes bug fixes bug fixes #28040
beat up a lot of things, machines, doors, walls. in the durand, gygax, and phazon. and on the phazon, tested on all the modes.
<hr>
<hr>
:cl:
fix: Fixed mechas having melee attack cooldowns taken up by clicking the floor.
fix: Phazons finally actually deal burn on the burn mode. 
/:cl:
=> Mechas no longer get their attack cooldowns taken up by clicking the floor. And phazons finally deal burn on the burn mode

code/modules/atmospherics/environmental/LINDA_turf_tile.dm
Marks wind as always-initialized so that it doesn't randomly break CI
CI failures bad.
Server started fine, wind flowed fine.
<hr>
<hr>
NPFC
=> Make wind not unpredictably break CI due to bad init.

code/modules/surgery/organs/subtypes/xenos.dm
Fixes stacking ability buttons when removing hijacked xeno organs
Fixes #27337 
Bugs are bad
Implanted and removed xeno plasma vessels multiple times; at each step, there was the correct number of ability buttons: 0 or 1.
<hr>
<hr>
:cl:
fix: Fixed stacking ability buttons when removing hijacked xeno organs
/:cl:
=> Fix stacking ability buttons when removing hijacked xeno organs

code/game/machinery/spaceheater.dm, code/modules/hydroponics/gene_modder.dm
Adds some missing checks on put_in_hands to ensure that AI and silicons don’t teleport items to themselves
Fixes #27335
Bugs are bad
Loaded plant DNA manipulator with disks, tried to eject disk as AI; disk spawned on DNA manipulator
Uncrewed space heater, tried to remove power cell as AI, cell spawned on space heater
<hr>
<hr>
:cl:
fix: AI don’t teleport disks and seeds from plant DNA manipulator to the core on eject
/:cl:
=> Fix some cases of silicons teleporting items on put_in_hands

code/_globalvars/genetics.dm, code/datums/components/zombie_regen.dm, code/game/dna/mutations/disabilities.dm, code/game/gamemodes/setupgame.dm, code/game/objects/items/weapons/dna_injector.dm, code/modules/mob/living/living.dm, code/modules/mob/living/living_status_procs.dm, code/modules/reagents/chemistry/reagents/admin_reagents.dm
Removes tourettes
- It's in poor taste
- It's a caricature of what it actually is
Opened player panel, saw no tourettes
<hr>
<hr>
:cl:
tweak: Removed Tourettes
/:cl:
=> Removes tourettes

code/game/objects/items/control_wand.dm
Fixes #28137
Door remotes can go in backpack again when clicked
covering up my fuck ups
Put all remotes in the backpack by clicking on it. Also opened the doors and bolted and checked what they do when activated again
<hr>
<hr>
:cl:
fix: door remotes can go in backpack again
/:cl:
=> Fixes door remotes

code/game/machinery/vendors/vending.dm
Fix a vending bug
Bugs bad.
Bug went away.
<hr>
<hr>
NPFC
=> [s] Fix a vending bug

code/__DEFINES/vv.dm, code/modules/admin/verbs/debug.dm, code/modules/admin/verbs/modifyvariables.dm
VV and proc calls now use the same value-picking method (vv_get_value), which has been upgraded to allow you to pick an atom by clicking on it, pick something inside that atom, or pick an atom's turf.
Less clunky admin interfaces. Proc calls in particular had some options (e.g. typepath) that were completely unusable, because they'd freeze your client.
https://github.com/user-attachments/assets/0cf2665d-5aa2-46ce-8880-ee8c839c8765
Made stuff in view float.
Made stuff nested in inventory glow.
Made myself jump to a turf.
Set a var to a visible object.
Entered buildmode while picking an atom. Got buildmode clicks.
Reconnected while picking an atom. Got normal clicks.
<hr>
<hr>
:cl:
tweak: Admin UIs for editing variables and calling procs now share the same value picker, which can now pick …
=> Upgraded VV and proc call arguments

code/modules/mob/new_player/new_player.dm
Fixes #28143
Adds a `stat` check lost in an earlier migration from `GLOB.alive_mob_list` to `GLOB.ai_list`, to ensure dead AIs aren't added to the list of announcers.
"Newly arrivals should be announced, and dead AIs should not be forced to speak" - #28143 
Logged in as AI, smited self with fire death, logged in with another client as a mime, observed that the mime was announced by Arrivals Announcement Computer instead of the dead AI.
```
[Common] Arrivals Announcement Computer says, "Pantomime, Mime, has arrived on the station."
```
<hr>
<hr>
:cl: Ascio
fix: Fixed dead AIs being forced to announce new arrivals
/:cl:
=> Fix dead AIs being forced to announce new arrivals

code/game/gamemodes/dynamic/antag_rulesets.dm, strings/tips.txt
This removes two outdated Traitor tips of the round that have become obsolete.
Accurate round tips good.
¯\\_(ツ)_/¯
<hr>
<hr>
:cl:
del: Removed two outdated traitor tips from tips of the round.
/:cl:
=> Removes outdated traitor round tips

code/modules/vehicle/speedbike.dm
This PR allows speedbike riders to pull mobs, and removes the arm requirement for riding, allowing them to have things in their hands.
Regression caused by #27698. Fixes #28091.
https://github.com/user-attachments/assets/9b1edc26-3591-41b4-9cea-3c1f970a105f
<hr>
:cl:
fix: Speedbike riders can properly pull things while riding.
fix: Speedbike riders can properly use items in their hands while buckled to the bike.
/:cl:
=> Allow speedbikers to pull mobs and use their hands.

code/modules/food_and_drinks/kitchen_machinery/kitchen_machine.dm
Reagent containers and storages no longer bonk when used on kitchen machinery.
I don't want to break my oven, thanks.
Dumped a tray into the candy maker.
Poured cream into a microwave.
<hr>
<hr>
:cl:
fix: Storage items and reagent containers no longer bonk on kitchen machinery.
/:cl:
=> Fix more chef bonks

_maps/map_files/stations/emeraldstation.dmm
Adds three new chargers to the brig on emerald station. As it was sorely lacking in chargers
Emerald station's brig has 4 chargers available to standard sec, making charging somewhat frustrating to charge.
see above
<hr>
i cant imagine this'd fall under anything that would count as needing it? correct me if im wrong though.
<hr>
:cl:
tweak: Added three more chargers in brig on emerald station
/:cl:
=> Adds three more chargers to emerald station brig.

code/modules/mob/living/simple_animal/friendly/mouse.dm
Due to a quirk of catwalks, they are technically valid for mice eating cables. This adds another check to prevent that, and at the same time rework the proc into early returns.
IC justification? They're chunky mice.
Fixes #27943
Boxed in a mouse over catwalks and cables, then removed a catwalk. No animals were harmed.
<hr>
<hr>
:cl:
fix: Mice won't eat cables through catwalks anymore
/:cl:
=> Make mice not chew cables through catwalks

code/game/objects/items/weapons/flamethrower.dm, code/game/objects/items/weapons/lighters.dm, code/modules/surgery/generic.dm, code/modules/surgery/tools.dm
Adds a burn check for the cauterize surgery step, and tweaks lighters, flamethrowers and cautery so they have logical damage types. Lighters would permanently set their damage to burn if lit once in their lifetime, flamethrowers were always brute which is weird, and same for cautery even though they use "burnt" as an attack verb.
I didn't want to rescope `lit` down to an item level var otherwise.
Fixes #25359. Opens up some other possibilities, either with lighters/flamethrowers, or for the cauterize step.
Did a little surgery with a zippo.
<hr>
<hr>
:cl:
tweak: Lit flamethrowers and cautery deal burn damage on physical hits
fix: Cauterize needs lit flamethrowers or lighters
/:cl:
=> Cauterize surgery checks for lit implements, tweak lighter/flamethrowers/cautery so they deal burn when appropriate

code/modules/food_and_drinks/kitchen_machinery/kitchen_machine.dm
Re-bonk reagent containers on kitchen appliances
Without the bonk, the reagents don't go in.
The bonk happens when the reagent container's legacy attack chain fires, and that's what's handling the reagent transfer.
Used a cream carton on a microwave. Bonk. Got reagents in microwave.
<hr>
<hr>
:cl:
fix: Reagents go into kitchen appliances again. This does make reagent containers bonk on them again, for now.
/:cl:
=> Reagents go into kitchen appliances again

code/modules/paperwork/paper.dm
Gives shoving paper in someone's face a prompt for the target in their chat to click to view the paper.
Being able to force a pop up in combat, or in general, without a cooldown... was deemed bad gameplay design.
https://github.com/user-attachments/assets/d6156308-68f1-4669-8205-ca818a6d99c8
<hr>
<hr>
:cl:
fix: Aiming eyes with a piece of paper will no longer instantly open up a pop up browser that would cause the game to become unfocused. Gives the target a link in which they can click to read the paper.
/:cl:
=> Begone combat paper stun!

code/game/machinery/firealarm.dm, code/game/objects/items/robot/cyborg_gripper.dm, code/modules/research/scientific_analyzer.dm
- Migrates `/obj/item/gripper` to the new attack chain.
- Fixes #28124.
- Fixes #28104.
- Fixes an issue where animals would be petted x2 any time they were clicked on by the gripper (missing `return`).
- Fixes grippers bapping machines when inserting held items into them.
- Adds a check for the gripper into `/obj/machinery/r_n_d/scientific_analyzer/item_interaction()` so it returns `..()` if being attacked by the gripper.
Attack chain migration good.
Makes the gripper compatible with new attack chain.
Bug fixes good.
Became engiborg.
Assembled fire alarm*, air alarm, APC, extinguisher cabinet, defib mount, charger, and computer from components to completion.
Attacked scientific analyser with and without items held, behaviour remains the same as before migration.
Removed cell and added …
=> Migrates Borg Gripper to New Attack Chain, Fixes Some Bugs

_maps/map_files/stations/deltastation.dmm
Fixes cell flashers on delta
Bug bad
Seems to work
<hr>
<hr>
:cl:
fix: Kerberos' cell flashers work again.
/:cl:
=> Fixes cell flashers on delta

code/modules/mining/lavaland/necropolis_chests.dm
Fixes a code loop in the try_attach_to_owner() function of the Rod of Asclepius by adding a check to see if the owner is equal to the thief. Previously, it was called on dropped(), which forced the thief to drop the rod and then it returns to the owner's hand, causing an infinite loop.
Additionally, refactors try_attach_to_owner() to utilize guard clauses.
Fixes #28035
Code loops are bad
Used the rod of asclepius, gave myself advanced kingston disease, changed the disease's stage probability to 50, transformed into Unathi, spawned a human, and set his brute damage to 50. The code did not loop, and the rod still healed the human.
<hr>
<hr>
:cl:
fix: Fixed code loop when you change your species with rod of asclepius in hand
/:cl:
=> [FIX] Fix Code Loop in rod of asclepius try_attach_to_owner()

code/modules/power/engines/supermatter/supermatter.dm
Limits gas_coefficent to 10.
For context, with the _entire_ stations plasma tank in  the chamber, none in the cooling loop or secondary loop, you hit almost 11.
The reasoning for this PR is we have been having radiation from supermatters being significantly higher than it should be when undergoing a delamination for the past month or so
See examples like 
I suspect this is part of the gas_coefficent getting spiked by an anomaly, or when situations like
happen.
This leads to an insane gas coefficent, leading to the above insane rad values.
By capping it to 10, which **should not be reached under almost any supermatter setup**, we should hopefully have this happen less.
This will need an eye on.
See above
dropped the supermatter in the plasma tank, hit exactly 10
<hr>
<hr>
Yes I did 10 …
=> Places a limit on gas_coefficient to limit rad issues

code/modules/hallucinations/effects/xeno_pounce.dm
Makes it so even if the xeno hallucination misses its target after the leap, it will still qdel itself.
Fixes #28156 
Bug are bad, temporary hallucinations should not linger.
Tested on a local server, hit or miss it will qdel itself after 2 seconds.
<hr>
<hr>
:cl:
fix: Xeno Hallucination no longer lingers
/:cl:
=> [FIX] Xeno hallucination hanging

code/game/objects/structures/kitchen_spike.dm
Fixes lying_angle set on post_unbuckle_mob on kitchen spike, so unbuckled mob will be displayed horizontally. The value was 0, so the body was lying in the north (up) direction. The default value is pick(90, 270), so this does not need to be explicitly specified
Fixes #28018
Bugs are bad
Spawned kitchen spike, killed human and buckled him to spike, unbuckled him, his corpse was displayed horizontally
Buckled alive human, unbuckled him, his body was displayed horizontally
<hr>
<hr>
:cl:
fix: Fixed standing corpse when unbuckling it from a meat spike
/:cl:
=> Fix standing corpse when unbuckling it from a meat spike

code/game/gamemodes/dynamic/antag_rulesets.dm
Increases the cost of traitors when selecting from the budget from 5 -> 7.
This will decrease the amount of traitors in a round during traitor rounds.
This needs to be adjusted to keep rounds fair within the antag/sec loop.
Can't be tested properly without being ran on live.
<hr>
<hr>
:cl:
tweak: Increased the cost of traitors when drawing from the budget.
/:cl:
=> Dynamic Traitor Cost Adjustment

code/game/gamemodes/miniantags/morph/morph.dm
Exploit bad
Exploit bad
Exploit bad
Yes
<hr>
<hr>
NPFC
=> [s] Fixes an exploit

code/datums/components/scope.dm
Stops the runtime in process() by checking if the tracker is valid before trying to get the owner.
Fixes #28165 
Runtimes are bad, validity checks are good.
Tested on a local server, shoot myself which applied the knockdown. Did NOT runtime.
https://github.com/user-attachments/assets/7fb4149f-a3fb-4b10-aae1-132a167a2f50
<hr>
<hr>
=> [FIX] Scope runtime if user loses the tracker

code/__DEFINES/time_defines.dm, code/__HELPERS/time.dm, paradise.dme
Moves time defines to the defines folder
Time defines are loaded earlier than __HELPERS, so they can be used in it
It's just moving the code
<hr>
<hr>
NPFC
=> Move time defines to the defines folder

code/game/objects/items/weapons/cards_ids.dm
changes one of the returns to `NONE` thus letting the key resume the attack chain and go in backpacks
annoying bug
loaded in
used key on backpack
tried beating stuff with key
opened a door and key got kaputed
<hr>
<hr>
:cl:
fix: magic key go in backpack again
/:cl:
=> magic key go in backpack again

code/game/machinery/vendors/custom_vendors.dm
You can now dump the contents of a bag (or serving tray) into a custom vendor by dragging it from your hand onto the vendor.
It's nice to have a better way to load custom vendors when you have a bunch of matching items, e.g. freshly-cooked food.
Clicked an unlocked custom vendor with a serving tray. Was prompted for a price for the tray.
Dragged the tray onto the vendor. Was prompted for a price for its contents.
Did a bunch of permutations of stuff in the bag already being in the vendor or not and doing all the things that should prevent it from succeeding or continuing.
<hr>
<hr>
:cl:
add: You can now dump the contents of a bag (or serving tray) into a custom vendor by dragging it from your hand onto the vendor.
/:cl:
=> Custom vendor bag drag&drop

code/modules/power/engines/supermatter/supermatter.dm
Prevents the SM from runtiming if the total air in the chamber becomes negative.
How can this happen when MILLA zeroes out negatives every tick? Well, what happens with turf air is:
1. MILLA runs a tick.
2. Something wants to look at the air in a turf, so it loads that from MILLA.
3. Any further accesses use the already-loaded air.
4. MILLA-safe code can edit the loaded air.
5. Later code will use the edited air.
6. The final value gets written back to MILLA just before the next MILLA tick.
The SM is also set to run last, so any other code that edits the turf's air will run first, and could potentially make the total air negative. It'll get fixed by MILLA next tick, but the SM will run before that, and runtime.
Runtimes bad.
If CI passes, it's fine.
<hr>
<hr>
NPFC
=> Negative pressure sucks

code/__HELPERS/unsorted.dm, code/modules/events/infestation.dm
This PR fixes two issues with the vermin infestation event. The first is that locating an area always returns a result, even if that area has no turfs, meaning a station without the chosen area (like Meta using Turbine instead of Incinerator) will silently fail. The second is that the `turf_clear` method it was using for checking for available spawn points was awful, essentially excluding any floor with any contents whatsoever: lights, underfloor cables, etc. This meant that for example, Metastation tech storage was seen as having no eligible turfs for spawning:
Despite having tons of floor space.
More reliable event.
Used event manager to run Vermin Infestation event, ensured results were still random and all expected locations worked.
<hr>
<hr>
:cl:
fix: Vermin infestation events will …
=> fix two vermin infestation issues

code/game/objects/items/weapons/dice.dm
Species without a lesser form just get gibbed when rolling a 5 on the die of fate, so it makes sense for it to happen for IPCs too.
Oh, and they toast bread when that happens.
Fixes #25542
https://github.com/user-attachments/assets/f21f17cc-2cbb-4b81-8241-228c012cd1ea
Threw a rigged die of fate and made breakfast.
<hr>
<hr>
:cl:
fix: Machine people get gibbed when rolling a 5 on the Die of Fate
/:cl:
=> IPCs get gibbed when rolling a 5 on the Die of Fate

code/tests/_game_test.dm, code/tests/_game_test_puppeteer.dm
Adds an activate_self wrapper and a negative check for any_chatlog for game tests,
Taking suggestions for their naming cause I suck at it!
Could wind up useful for game tests
Negative any_chatlog check
failed activate_self check
checked that they run and that they fail.
<hr>
<hr>
NPFC
=> Puppet test activate_self wrapper and negative any_chatlog check

code/modules/projectiles/guns/energy/special_eguns.dm
Fixes the check that would try to make a blue portal on the wormspace projector. It was still expecting it to be bluespace rather than wormhole.
Fixes #28212
Spawned a wormhole projector and fired two times.
<hr>
<hr>
:cl:
fix: Wormhole projector can fire both types of portals
/:cl:
=> Fix wormhole projector not creating both types of portals

code/modules/power/engines/supermatter/supermatter.dm
Adjust the SM gas production method to avoid producing a ridiculous output when active and at very low pressure.
SM should not go supernova because it was low pressure.
Procedure:
1. Disable engine bypass.
2. Enable and maximize the engine input/output pipes.
3. Configure the air alarm normally. This will create a vacuum in the chamber.
4. Fire one emitter shot at the SM.
5. Set the output speed on one N2 tank's pump to 9 kPa.
6. Turn on that pump.
Results without this change:
and worsening. It will quickly reach a state that's effectively unsalvageable.
Results with this change:
and stable.
<hr>
<hr>
:cl:
fix: Fixed a bug that would cause the SM to go haywire if it was ever active and exposed to an extremely low (but nonzero) amount of gas.
/:cl:
=> SM sanity at low pressure

code/modules/antagonists/changeling/powers/mutations.dm
…lee shots
Remember https://github.com/ParadiseSS13/Paradise/pull/26245 ?
Apparently it didnt fix all the issues and we have runtime right now if you hit someone point blank
Well, not after that PR. It adds couple variables to track when the tentacle can be deleted instead of qdeling it in the middle of the shot causing runtime
I also switched `Crossed` to `on_atom_entered` on the beartrap so it works now
Bugs bad, runtimes bad
Compiled, shot tentacle point blank and from far away, shot it down the hallway(not hitting anything), made sure all works as intended
<hr>
<hr>
:cl:
fix: Changeling tentacle activates beartrap if shot point blank at the target.
/:cl:
=> Tentacle fix 2, no runtime on adjacent hit, cling beartrap activates now

code/datums/status_effects/neutral.dm, code/modules/mob/living/carbon/human/human_defense.dm, code/modules/mob/mob_movement.dm, config/example/config.toml
Made it so the LWAP doesn't mark SSD mobs.
Also made it so you don't hit SSD mobs with snipers/lwaps by shooting over them, as you could unintentionally hit them with a perpetrator round for example
Closes #28130
SSD protection is good.
Multi instance testing, shot over/at ssd mobs, and as shown above, ssd mobs aren't marked
<hr>
<hr>
:cl:
tweak: The LWAP no longer marks SSD mobs
tweak: Sniper rifles/LWAPs no longer hit SSD mobs if you shoot over them. 
/:cl:
=> Adds some more protection to SSD mobs with lwaps and snipers

code/modules/paperwork/photography.dm, code/modules/paperwork/silicon_photography.dm
Makes it so cameras can take pictures of unconsealed runes and cult portals unless they're the AI subtype. The change to rune interaction with AI also affected cameras since they check for _any_ form of invisibility.
Fixes #25203
Placed runes, and took a picture with both a normal camera, and from the AI.
<hr>
<hr>
:cl:
fix: Cameras can take photos of unconsealed runes and cult portals. AIs are unaffected.
/:cl:
=> Non-AI cameras can take pictures of unconcealed runes and cult portals

code/modules/research/circuitprinter.dm, code/modules/research/protolathe.dm, code/tests/attack_chain/test_attack_chain_machinery.dm
This PR fixes reagent containers not transferring reagents into protolathes or circuit imprinters.
Bugfix.
New tests added to suite.
<hr>
<hr>
:cl:
fix: Beakers and other containers properly transfer reagents to protolathes and circuit imprinters.
/:cl:
=> fix reagent containers not transferring into protolathes or circuit imprinters

code/game/area/areas.dm, code/game/machinery/doors/firedoor.dm
While this was intended as a fix, I ended up cleaning up the code at the same time since the behavior was really weird if taken at face value.
So to sum up the behavior now:
- Firedoors do not close automatically unless an alarm is active
- The alarm/area itself will close the doors every 10 seconds, while opening it manually will close it in 5, whichever comes first baring obstructions.
- Emagging turns it into a manual-only door, on top of opening up right then.
The first two are technically the current behavior, minus the extra quirks.
Fixes #25952
A lot of the inconsistent behavior was probably borne out of the odd code.
https://github.com/user-attachments/assets/30c9fd16-5c66-4556-add1-7151c42dd70f
Messed with firealarms and firedoors, noting the new behaviors with cleaned up code. …
=> Clean up firedoors and add proper emag behavior

code/modules/supply/supply_packs/pack_shuttle.dm
Makes the pencil shuttle only able to be bought when the supply console has been cmagged.
Ultimately this is an exercise for the reader.
Every pencil shuttle is chaotic LRP hell. Regardless of whether you think it's funny or not, the shuttle ruins the potential for RP, kills the natural resolution of antag/sec rivalries, and now with MILLA it takes one person leaving the door open on exit to kill everyone inside that wasn't prepared.
There is no good reason for buying the shuttle besides "trolololol".
Checked supply console shuttle options, no pencil, cmagged the console, bought it, waited 10 minutes because it was green alert and I didn't know how to set the shuttle time, got on the shuttle, rode it to CC, hated my life every second of the ride
<hr>
<hr>
:cl:
tweak: Secure Transport …
=> make pencil shuttle cmag only

code/modules/clothing/suits/hood.dm, code/modules/clothing/suits/misc_suits.dm, code/modules/customitems/item_defines.dm
Increases `w_class` of `/obj/item/clothing/suit/hooded` from `2` to `3`.
Keeps `w_class` of `2` for hoodies and fluff hooded suits, but not for fluff wintercoats (there is only 1 fluff wintercoat atm)
<details>
<summary>Notable changes with w_class increased from 2 to 3</summary>
Explorer, goliath, drake and berserker armors<br>
Flagellant and cult robes<br>
Missonary robe (chaplain uplink)<br>
Carp costume (doubtful) (including space dragon's)<br>
Fluff winter coats<br>
</details>
<details>
<summary>Suits that are left untouched</summary>
Fluff hooded suits<br>
All hoodies (/obj/item/clothing/suit/hooded/hoodie), since they are really small and none of them has any armor stats
</details>
You shouldn't be able to fold a bone armor into your pocket, or any other, especially when they are …
=> Increase w_class of most hooded suits by 1

code/game/dna/dna2.dm, code/game/dna/dna2_helpers.dm, code/game/objects/structures/mirror.dm, code/modules/tgui/modules/appearance_changer.dm
Adds eyes and head DNA synchronization with mob DNA in the `ResetUIFrom` proc. Removes the `APPEARANCE_UPDATE_DNA` flag check on the appearance changer mirror `update_dna` proc, so changes from any mirror is saved. If you just add `APPEARANCE_UPDATE_DNA` to the mirror, then it will be possible to change race.
It turns out that `head_traits_to_dna` is writing UI changes to the mob DNA, but `write_head_attributes` (bad name, it applies attributes, in fact) is taking DNA from the head DNA.
These changes will ensure that character DNA is consistent, preventing hair and other changes from resetting on any `UpdateAppearance` call.
Fixes #25892 
Fixes #27923 
Getting your appearance changed in moments when you don't expect it is bad
Spawned the mirror, changed my hairstyle, and called …
=> Fix appearance changes from the mirror resetting on any UpdateAppearance() call

code/modules/admin/verbs/modifyvariables.dm
Fixes a runtime when using VV/proccall's new "click an atom" feature.
Runtimes bad.
Made a die rainbow glow. No runtime.
<hr>
<hr>
NPFC
=> No VV/proccall click runtime

code/game/objects/items/scratch_card.dm
Title.
Fixes #28176.
ACM is good.
Bug fix is good, restoring cash money.
Scratched a ton of cards till I got a winning one.
Verified only winning cards let you get cash money.
<hr>
<hr>
:cl:
fix: Winning scratch cards are now redeemable at ATMs again.
/:cl:
=> Migrates `/obj/item/scratch` to the new attack chain

code/game/objects/effects/spiders.dm
Moves spiderlings from walk_to to move_manager.home_onto
Likely fixes #28223
Bugs bad
(Well, except the spiderlings themselves)
Spawned a bunch of spiderlings in the garden, watched them scurry about.
It looks pretty funky without #28242, but it does work.
<hr>
<hr>
:cl:
fix: Hopefully fixes spiderlings twitching like mad sometimes.
/:cl:
=> Spiderlings on move_manager

code/controllers/subsystem/movement/movement_types.dm
Corrects a bug in `/datum/move_loop/has_target/move_towards` that made it go slightly off-track and fail to update its target after a diagonal move.
Fixes #28229 
The issue here is that the code is trying to avoid recalculating on the first part of a diagonal move, but got the check backwards, so it *only* recalculates on the first part of a diagonal move.
Accurate movement is good. Stuck meteors are bad.
Sent a meteor flying 5 tiles southeast without the PR. Missed by a tile and never corrected.
Sent a meteor flying 5 tiles southeast with the PR. Hit the target and despawned.
<hr>
<hr>
:cl:
fix: Meteors no longer get stuck after missing the station.
/:cl:
=> move_towards the right spot

code/game/machinery/vendors/vending.dm
Vended items land on the vendor again, rather than falling to the floor under the user.
No hiding items under me, please.
Vended three items with left hand active. First in left hand, second in right hand, third on the vendor.
Vended three items with right hand active. First in right hand, second in left hand, third on the vendor.
<hr>
<hr>
:cl:
fix: Vending an item with your hands full will leave it on the vendor, rather than the floor under you.
/:cl:
=> Vended items land on the vendor again

code/modules/surgery/other.dm, code/modules/surgery/surgery.dm, code/modules/surgery/tending.dm, paradise.dme
Ports tend wounds/tend burns surgeries from /tg/. The first part in what's hopefully a substantial difference in healing on Paradise.
The two surgeries are fundamentally the same, they just differ in name. 
scalpel -> hemo -> retractor -> heal (or treat bones/IB) -> cautery,
where healing makes use of a hemostat (or a pen/pair of wirecutters in a pinch), and will repeat automatically until the patient is healed.
While performing the healing, you'll get a little indicator in chat that'll tell you how the healing is going, and if you have a health analyzer in your off-hand, it'll tell you the exact number of brute/burn remaining.
It'll heal a *teensy* bit faster when a patient has more brute damage, and will be less effective if the patient is wearing a jumpsuit/shirt. There has to be some …
=> Adds Tend Wounds/Tend Burns surgeries

code/__DEFINES/is_helpers.dm, code/__DEFINES/mob_defines.dm, code/datums/outfits/outfit_admin.dm, code/game/dna/mutations/mutation_powers.dm, code/game/objects/items.dm, code/modules/clothing/clothing.dm, code/modules/mob/living/carbon/carbon_procs.dm, code/modules/mob/living/carbon/human/species/unathi.dm, code/modules/mob/mob_vars.dm
Fixes a runtime when you're talking with a cig butt in your mouth
Also makes the code more compliant with non-mask items in your mask slot so you don't have to make your item into a mask if you want to put it there
Also also removes some old `/mob/spirit` defines
Less runtimes is good
Talked with a cig butt in my mouth, no runtimes
<hr>
<hr>
NPFC
=> Fixes runtimes when you talk with a cig butt in your mouth

code/modules/surgery/tending.dm
Fixes a bug with tend wounds surgeries that I didn't notice until it went in. You can now properly perform tend wounds.
Mechanics should work, sorry!
they did surgery on a vulp
<hr>
<hr>
:cl:
fix: tend wounds surgery should now work properly.
/:cl:
=> Fixes a bug with tend wounds

code/modules/security_levels/keycard_authentication.dm
ERT reminder is a little popup that says "ERT request ignored for 5 minutes" basically.
It's on a 15 minute timer to appear.
This just makes it a 5 minute timer so the game stops **lying** to our faces.
I'unno maybe we won't miss your ERT request "The Clown has lube".
It's a single number change on the timer, and it built properly. I don't think I can actually send an ERT request as a single person on the server, so I'm just going to assume this won't somehow unravel the fabric of reality by changing 15 to 5.
<hr>
<hr>
NPFC.
=> Stops ERT reminder from lying to us

code/modules/atmospherics/environmental/LINDA_turf_tile.dm, code/modules/atmospherics/machinery/airalarm.dm
Removes an unnecessary `blind_set_air` on turf init.
Makes air alarms not fire until a MILLA tick has passed.
Makes roundstart N2O/plasma visible.
Correctness good, unnecessary work bad.
Started game. Saw stuff in atmos tanks. Air alarms didn't panic about lack of air.
<hr>
<hr>
:cl:
fix: The Shadow should no longer randomly have its fire alarms triggered.
fix: Roundstart N2O/plasma is now visible.
/:cl:
=> Better atmos init

code/__DEFINES/dna.dm, code/game/dna/dna2.dm, code/game/dna/dna_modifier.dm
Turns the proc EncodeDNABlock into a define. It is a one liner that improves readability but otherwise eats up performance, especially during startup.
Less startup lag.
Spawned in as geneticist. Followed the guide on the wiki to make a humanized monkey. Changed the humanized monkey's gender via setting UI block 37. Irradiated SE block 1 until above DAC. Made single block injector and injected myself. Got morphing power. Morphing power worked.
Spawned in as clown. Shot a laser gun and clumsily shot myself in the foot on first shot. Removed clumsy gene via player panel. Shot rest of laser gun charge. Did not shoot myself in the foot.
<hr>
<hr>
NPFC
=> turn EncodeDNABlock proc into a define

docs/CODE_OF_CONDUCT.md
This removes the two pull request limit imposed on the code base.
As headcoders, we believe we are in a place where we currently do not need to have a limit on the number of pull requests open. It was implemented when a lot of changes were backlogged. The development team needed  time to rest and formulate a better strategy. 
At this time the same pre-approval limits still apply!
Examined through Markdown viewer.
<hr>
<hr>
NPFC
=> Removes the Two Pull Request Limit

code/game/objects/items/weapons/rpd.dm, code/game/objects/items/weapons/stock_parts.dm
fixes exploit
exploit icky bad
tested the exploit, couldn't do it
<hr>
<hr>
ya'll dont get to know the expoit
=> [s] exploit fix

code/modules/client/preference/link_processing.dm, code/modules/surgery/robotics.dm
Fixes corrupted save slots and machine surgery for imitation.
Again, this is my fault. Fixes are good.
This is after changing character slots, changing species from one to another, changing the subtype, then swapping over. Repeating this in random orders to truly test it all.
Proof of IPC machine configuration fixes. This broke after I changed how the proc took in parameters. fixed now.
<hr>
<hr>
:cl:
fix: Fixed IPC imitation surgery (Still done by targeting head -> Identity Reconfiguration)
fix: Fixed corrupted save slots caused by swapping slots or subtypes of species.
/:cl:
=> Imitation fix 2

code/datums/spells/banana_touch.dm, code/game/machinery/recycler.dm
Adds a cmag effect to the recycler, which utilizes a variant of the `banantouched()` proc called `bananatouched_harmless()`
Made a new proc, alternative to `bananatouched()` called `bananatouched_harmless()`. It's identical in idea, but omits some of the more round crippling effects that the original proc has.
Added dropdel variants of the clown clothes, which will be used to equip the recycled clown.
Recycler emag and cmag are now mutually exclusive. You cannot cmag an emagged recycler and vice versa.
Process goes, cmag recycler, someone falls in, they get stripped off their uniform, shoes, mask and if plasmaman, helmet. Their original belongings drop under the recycler (where they won't be deleted). They get equipped with enough dropdel clown clothing that they won't burn up or look …
=> Feature: Clown recycler, a new Cmag effect

code/modules/antagonists/revolutionary/datum_headrev.dm, code/modules/surgery/organs/augments_eyes.dm
Headrev sechud is now an implant instead of chameleon security sunglasses. They lose their flash protection. The implant cannot be seen on bodyscanners (unless they're tier 4, or they use surgery).
Getting your glasses checked is unfun, mindshielding should be the way to tell if theyre a headrev.
made myself a headrev, got the implant
<hr>
<hr>
:cl:
tweak: Headrev sechud is now a hidden implant instead of chameleon security sunglasses. 
/:cl:
=> Headrev sechud is now an implant

_maps/map_files/stations/boxstation.dmm, _maps/map_files/stations/cerestation.dmm, _maps/map_files/stations/deltastation.dmm, _maps/map_files/stations/emeraldstation.dmm, _maps/map_files/stations/metastation.dmm, code/controllers/subsystem/non_firing/SSlate_mapping.dm
This creates a step in the late mapping process where mice are spawned in maintenance randomly, with a random ratio range. Instead of just placing them manually, let the game do it for you unless you have _really_ specific spots in mind.
Current ratios are 125 to 200 valid maintenance turfs per mice, making it range from 20 to 30 on Boxstation.
Maps are edited to remove all mice except for Tom, as the current fixed spawns would be excessive on top of the random ones (Except for Delta, which has a notable lack of mice). Let me know if there's some that should remain, or if the ratio should be tweaked.
Mice being hard placed essentially means they'll have the same outcome most of the time (i.e. chew on the same cable every round). This changes things up, and is not reliant on dropping …
=> Dynamic Mice: Let's populate maintenance randomly

code/game/objects/items/weapons/RCD.dm
Due to how RCDs try to interact with atoms by looping through their actions, they'd wind up showing the suicide message if trying to deconstruct something invalid.
This adds a proper check, and also tweaks what gets passed in certain proc calls to retain functionality.
Fixes #25891
https://github.com/user-attachments/assets/faf374fa-9cb1-49a6-a92b-57e4003c0d74
Used the RCD on an indestructible wall, built and deconstructed things. Let the thing meet my maker.
<hr>
<hr>
:cl:
fix: Fixed bogus message/interact when trying to do an invalid deconstruct with the RCD
/:cl:
=> Fix RCD interactions with invalid types

code/controllers/subsystem/SStimer.dm, code/modules/hallucinations/effects/blind_rush_hallucination.dm
Fixes #28054
The Blind Rusher timer failed to delete itself and would run indefinitely. This PR adds 2 QDELETED checks (from https://github.com/tgstation/tgstation/pull/69879) in the timer fire proc. If the timer has been deleted inside it's callback, it wont reinsert itself.
Blind Rusher now has the TIMER_DELETE_ME flag instead of TIMER_STOPPABLE, as  that seemed to always fail to delete.
runtime spam not good
Invoked the hallucination on myself, didn't runtime, didn't run infinitely.  Tried another TIMER_LOOP hallucination, deadchat control on a mob, the timers seem to run and delete. Aside of that, I have very surface level clue of what this actually does. Issues seemed related, so I gave it a shot.
<hr>
<hr>
NPFC
=> fixes blind rushers hallucination runtimes

code/game/machinery/firealarm.dm
Refactors `/obj/machinery/firealarm/item_interaction()` for readability.
Also fixes the following bugs:
- The sprite doesn't change to its unwired state when wires are cut.
- Borg grippers cannot add circuitry to the alarm.
Better more readable code. Enabling more better code down the line.
Assembled a fire alarm from 0 to completion.
<hr>
<hr>
:cl:
fix: Fire alarm now changes to unwired sprite when wires are removed.
fix: Borg grippers can add fire alarm electronics to fire alarms.
/:cl:
=> Refactor Fire Alarm `item_interaction()`

code/modules/shuttle/on_move.dm
This PR fixes multi-tile airlocks not moving with shuttles they're installed on.
Fixes regression introduced by #26762.
Travelled in whiteship, ensured that airlock moved with ship.
<hr>
<hr>
:cl:
fix: Multi-tile airlocks will not be left behind from shuttles when moving.
/:cl:
=> fix multi-tile airlocks not travelling with shuttles

code/datums/uplink_items/uplink_traitor.dm, code/game/gamemodes/changeling/changeling.dm, code/game/gamemodes/cult/cult_mode.dm, code/game/gamemodes/dynamic/antag_rulesets.dm, code/game/gamemodes/traitor/traitor.dm, code/game/gamemodes/trifecta/trifecta.dm, code/game/gamemodes/vampire/traitor_vamp.dm, code/game/gamemodes/vampire/vampire_chan.dm, code/game/gamemodes/vampire/vampire_gamemode.dm
This removes the following roles from being able to role as a round start antagonist. This does not mean they will be mindshielded, only that they will now not be able to be traitors, vampires, or changelings. They can still be converted, thralled, mindslaved or even hired into the command position.
In addition this also moves the Telegun to a hijack only item strictly for scientists.
This is good for the game for a few reasons:
Heads should be trustworthy and vetted even more so than security officers. This aligns more to what is considered acceptable behavior when even considering the hiring of command staff.
Heads should be the teachers of the departments, as well as the ones to make sure their departments are secure. They have an overall responsibility to be commanders.
Reduces antag …
=> Removes command from being eligible for round start antagonist

code/modules/martial_arts/cqc.dm
Fixes invalid input on cqc chokehold.
Fix.
Local. Performed chokehold on carbons with stamcrit and without. More oxy damage when in stamcrit, less when not.
<hr>
<hr>
:cl: Navvok
fix: CQC chokehold is now dealing up to 2.2 times more oxygen damage, depending on your target's stamina damage.
/:cl:
=> Fix CQC chokehold

code/modules/admin/admin_verbs.dm, code/modules/admin/verbs/playsound.dm, code/modules/client/client_procs.dm
Ports two verbs from TG:
`Stop Sounds` Special verbs verb that anyone can use. Stops all sounds when used.
`Stop Sounds Global` Debug verb for those holding sound flags(GA+). Stops sounds for every player when used.
Original PRs/commits from TG:
https://github.com/tgstation/tgstation/pull/1310 (original global verb)
https://github.com/tgstation/tgstation/commit/df189498ce42127575c30a3175406e742e2bd2db (client verb)
https://github.com/tgstation/tgstation/pull/29611 (updated version)
I think I got most of the PRs but dear god this verb was subject to several non-atomic refactors. The code is all from TG with a few edits that I made for paracode/removal of blackbox logging which isn't necessary.
Having the ability to stop sounds is useful for when someone does something annoying and you want …
=> Ports stop sounds verb from TG

code/game/objects/items/hand_item.dm
Fixes slapper getting qdel() on drop held item hotkey even when it's not in your active hand.
Bug fix. You can now again perform combos like 3q3 without losing your ability to parry.
Local. Performed some combos, slapper never got deleted. Tried to drop slapper while in active hand by pressing Q, succeeded.
<hr>
<hr>
:cl:
fix: CQC slapper won't anymore get deleted while performing combos like 3q3, 3q4 or dropping item from your other hand.
/:cl:
=> Fix CQC slapper

code/game/atoms_movable.dm, code/modules/mob/camera/eye.dm
Fixes #28326
With #27698, a default-TRUE `momentum_change` parameter was added to each call to `/atom/movable/proc/Moved()`. With #25078, a callback to `Moved()` was kept in the `set_loc` proc, which is exclusively used in camera eye movement, but its call signature was not updated to match the new function signature. This caused camera eyes to undergo a newtonian move every movement, which is the reason for the sluggishness seen in #28326. The missing parameters have been added to the `Moved` call in `/atom/movable/proc/set_loc`, which removed said sluggishness.
Sluggish movement is uncomfortable.
I logged in as an AI and moved around with low and high acceleration, and noted the sluggishness in camera eye movement was gone.
<hr>
<hr>
:cl: Ascio
fix: Fixed sluggish AI/camera eye movement …
=> Fix sluggish AI/camera eye movement

_maps/map_files/stations/emeraldstation.dmm
Adds a missing fire alarm to the Emeraldstation AI satellite hallway and moves a camera to make room.
Adds a missing fire alarm to the Emeraldstation AI satellite hallway and moves a camera to make room.
Adds a missing fire alarm to the Emeraldstation AI satellite hallway and moves a camera to make room.
Loaded up paracode, joined as AI, fire alarm works and camera-visible area has not been affected.
<hr>
<hr>
:cl:
fix: Adds a missing fire alarm to Emeraldstation AI Satellite Hallway
/:cl:
=> Adds a missing fire alarm to Emeraldstation

code/modules/surgery/organs/subtypes/tajaran_organs.dm, code/modules/surgery/organs/subtypes/vulpkanin_organs.dm
Lowers taj/vulp darksight to 3 tiles again. 
Taj/vulp darksight was originally lowered to 3 in #20035 but was raised up to 4 in #20275 with the addition of a malus. 
This malus was removed in #23642 but darksight remained at 4.
Taj/vulps have very minor maluses, they should not be getting 4 darksight for what they currently have.
#20035 Has pictures of what 3 darksight looks like. This is one extra tile over human eyes.
It compiles.
<hr>
<hr>
:cl:
tweak: Taj/vulp darksight lowered to 3 again.
/:cl:
=> Reduces taj/vulp darksight to 3 tiles again

code/modules/shuttle/on_move.dm
This PR fixes the "lighting object was qdeleted with a different loc then it is suppose to have" runtimes caused by making sure that lighting objects, which are always attached to a specific turf, are not considered for the purposes of shuttle moves.
Bugfix.
Called mining shuttle, ensured no runtimes.
<hr>
<hr>
NPFC
=> fix lighting objects being moved from their turfs on shuttle move

code/modules/clothing/gloves/boxing_gloves.dm
Boxing gloves will now give you the chunky fingers trait when equipping the gloves. The trait will be removed when the user takes off the gloves.
Because boxing gloves shouldn't have the dexterity to do things like shoot guns. 
Equipped boxing gloves. Checked to see if the Trait was applied.
Removed boxing gloves. Checked to see if the Trait was removed.
<hr>
<hr>
:cl:
tweak: Added chunky fingers trait to boxing gloves.
/:cl:
=> Adds the Chunky Fingers Trait to Boxing Gloves

code/modules/mob/living/carbon/carbon_update_icons.dm
Adjusts Y_Pixel translate to properly sit the carbon on the tile they're standing on
Extremely large resized carbons would still be centered on their tile but wouldn't look like they were standing on it but rather originated from it like an object in 3D space.
Testing shown in Images of changes
<hr>
<hr>
:cl:
fix: Fixed Y-offset for resized mobs.
/:cl:
=> Resizing Carbon Y Pixel Offset Fix

code/game/objects/items/weapons/grenades/frag.dm, code/game/objects/items/weapons/misc_items.dm, code/modules/projectiles/ammunition.dm
- Allows the matter decompiler (of engineering cyborgs and maintenance drones) to decompile shrapnel and empty cardboard tubes
Less trash on station
1. created trash
2. decompiled trash
3. floor clean
<hr>
<hr>
:cl: cdui
tweak: Engineering Cyborgs' and Maintenance Drones' Matter Decompiler to allow decompilation of shrapnel and empty cardboard boxes
/:cl:
=> Allow decompilation of shrapnel and cardboard tubes

code/modules/projectiles/ammunition/ammo_casings.dm
Partially reverts https://github.com/ParadiseSS13/Paradise/pull/21501 by reducing the shot spread on both rubber shot and laser shot.
With the direction antagonists have taken over the time since the original PR, security needs some buffs to compete.
Spawned in a riot shotgun with rubber shot.
Observed the spread of the pellets.
<hr>
<hr>
:cl:
tweak: Tweaked the shot spread of Rubber shot and Laser shot
/:cl:
=> Buff for Rubber Shot and Laser Shot Shells

code/modules/mob/living/simple_animal/constructs.dm
Reduces the laser resistance of juggernauts from 0.6 x damage to 0.8 x damage. 
Shots to kill moved from 21 to 16.
Juggernauts are in a funny place. Melee is incredibly impractical with them and they're very very resistant to lasers, so their mere existence practically requires autorifles. But those autorifles are also very effective against the rest of cult, meaning that if sec orders autorifles early, cult can generally be stomped pretty easily.
Here's the range of problems I see:
**Sec orders Autorifles early to handle Juggs:**
Cult can be stomped very easy due to how powerful autorifles are, especially at countering Flag Robes (instant bone-breaks go brrt) and Mirror Shields.
**Sec doesn't immediately order Autorifles to handle Juggs:**
Juggs can pretty easily stomp sec by just …
=> Reduces Juggernaut laser resistance

code/modules/hydroponics/grown/cannabis.dm
Fixes the description for normal cannabis leaves to properly reflect its legal status.
Descriptions which lie to you are bad.
it changes a single description sentence so I didn't bother
<hr>
<hr>
:cl:
tweak: changed the description of weed leaves
/:cl:
=> [LORE] Fixes the cannabis leaf's description

code/modules/power/lights.dm
This PR fixes issues with engiborgs attempting to use grippers to remove/insert lights from sockets.
Bugfix.
Removed and reinserted bulb from socket as engiborg. Switched to medborg. Ensured I could not remove/insert light bulbs.
<hr>
<hr>
:cl:
fix: Engineering borgs can now properly insert and remove light bulbs from sockets.
/:cl:
=> fix engiborgs not being able to insert/remove lights from sockets

code/datums/status_effects/buffs.dm
Removes stamina healing from legion cores while off Lavaland z-level
Players should not have an infinite source of full stamina heals (outside of chemgaming)
Ran paracode, spawned legion cores and a disabler beam turret. Took stamina damage, used core, no stamina healing but still applied brute and burn healing. All effects are applied properly on Lavaland.
<hr>
<hr>
:cl:
tweak: Legion cores no longer clear stamina damage while on station
/:cl:
=> Nerfs legion cores on-station

.vscode/settings.json
Makes TOML files not format on save.
Otherwise, people change the indentation in the file a lot.
Shit doesnt fuck up anymore.
<hr>
<hr>
NPFC
=> Makes TOML files not format on save

code/modules/mob/living/simple_animal/friendly/mouse.dm
This PR fixes map tests to not allow mice to chew through cables.
AGHGHGHGGHGHGHG
<hr>
<hr>
NPFC
=> don't let mice chew through cables in map tests

code/datums/outfits/outfit_debug.dm, code/game/objects/items/tools/multitool.dm
Removes the "admin detector" variant of the AI detector
It's a pointless item whose only possible use is for griefing. You'd need some kind of exploit to get one, but once you got it, you'd be able to make sure you were only breaking the rules while admins weren't watching.
Compiled, spawned in with debug outfit, didn't have it.
<hr>
<hr>
NPFC
=> Remove admin detector

code/game/objects/items/robot/robot_items.dm
Title.
No player-facing changes.
Attack chain migration good.
Stunned some skrell with the stun arm, it functioned as before.
<hr>
<hr>
=> Migrates `/obj/item/borg/stun` to the new attack chain.

code/game/objects/items/weapons/flamethrower.dm
Fixes an issue with flamethrowers producing way more heat than they should
Was kinda exploity.
Used flamethrower. Got reasonable results.
<hr>
<hr>
:cl:
fix: Flamethrowers will no longer produce way too much heat under some circumstances.
/:cl:
=> [s] Less magical flamethrowers

code/game/gamemodes/dynamic/dynamic.dm, code/tests/game_tests.dm, code/tests/test_dynamic_budget.dm
Makes dynamic usable below 10 players.
Scales back dynamic budget below 30 players. Previously, it was always 1 per player. Now:
* Flat budget of 7
* +0 budget each for players 1-4
* +0.5 budget each for players 5-20 (cumulative total 15)
* +1.5 budget each for players 21-30 (cumulative total 30)
* +1 budget each for players 31+
**Breakpoints:**
* 7 always: 1 tot
* 10 @ 10 players: 1 tot/cling/vamp/flayer
* 14 @ 18 players: 2 tots
* 17 @ 22 players: 1 tot, 1 cling/vamp/flayer
* 21 @ 24 players: 2 clings/vamps/flayers OR 3 tots
* 24 @ 26 players: 2 tots, 1 cling/vamp/flayer OR 2 clings/vamps/flayers OR 3 tots
* 27 @ 28 players: 1 tot, 2 clings/vamps/flayers OR 3 tots
* 28 @ 29 players: 1 tot, 2 clings/vamps/flayers OR 4 tots 
* 30+ players: as before
Lowpop antagonists are pretty brutal. …
=> Reduced dynamic budget at low player count

docs/mapping/submaps.md
This PR updates the docs to include design guidelines for submaps. This doc was already reviewed and approved by mapping team, except for the point regarding entire maints replacements, which I just came up with because it came up in Discord.
Guidance for contributors.
<hr>
<hr>
NPFC
=> docs: submap design guide

code/datums/ores.dm
Makes the visible message for defusing gibtonite use the turf name instead of the datum.
Fixes #28421
Rigged a turf to always have gibtonite, hit it then defused it.
<hr>
<hr>
:cl:
fix: Defusing gibtonite shows the proper messaging
/:cl:
=> Defusing gibtonite does not show datum paths

code/datums/spells/summonitem.dm, code/game/gamemodes/nuclear/nuclearbomb.dm, code/game/objects/items/devices/radio/headset.dm, code/modules/clothing/suits/armor_suits.dm, code/modules/hydroponics/beekeeping/beebox.dm, code/modules/hydroponics/biogenerator.dm, code/modules/hydroponics/compost_bin.dm, code/modules/newscaster/obj/newscaster.dm, code/modules/research/backup_console.dm, code/modules/research/scientific_analyzer.dm
The recent TG move manager results in funky behavior when items are dropped in zero-g. Putting an item in a machine using `drop_item_to_ground()` without gravity ends up attaching a `drift` component to the item. This will continue to fire even after the item is moved into the atom that is being transferred into. After it is moved, the item will be forced onto the turf of the target atom by a move loop fire without removing the target atom's references to the item. This causes duplication-like issues and weirdness. We need to go through `transfer_item_to()` instead.
Bugs are bad!
I have only tested the science analyzer in zero-g. I have not tested the rest of these. Please do not merge this until they are tested.
<hr>
<hr>
=> Makes putting things in some things less likely to result in more things than anticipated

code/game/gamemodes/miniantags/guardian/guardian.dm
Gives holoparas/guardians the same level of lowlight as humans, so they can see a tile around them in the dark
They have no lowlight at all currently, and its incredibly frustrating when your summoner /does/, so if they're in the dark, with NVGs or something, you're stuck looking at basically nothing as you using your light would also reveal your summonee. 
before:
after:
human vision to compare:
While the holopara can technically see more better, they can only see tiles the human can too, i believe theres an issue with how the darkness hud is applied to non carbons, im not sure.
see above
<hr>
<hr>
:cl:
tweak: Holoparasites/guardians now have very minor lowlight vision, comparable to standard humans. 
/:cl:
=> Gives guardians/holoparas lowlight vision

code/game/gamemodes/miniantags/abduction/abduction_gear.dm
Adds a message to the combat vest for when its been triggered, as it previously didn't, updates the failure prompt to include how much longer it has, and updates the vest to use TG cooldowns
Actual feedback is good
better timers are also good
Used the vests combat mode action button to check the success, and failure messages
<hr>
<hr>
:cl:
tweak: Tweaked the text feedback for the combat mode abductor vests adrenal ability, to better reflect what it's doing.
/:cl:
=> Improves the abductor vest combat mode stim injector feedback

code/modules/research/designs/weapon_designs.dm
This is a revert of https://github.com/ParadiseSS13/Paradise/pull/25490, that added illegals to making the WT-550 Toxin Tips. 
Security needs some buffs overall and reverting this change is one of them.
Checked to see if Toxin Tip rounds could be printed without illegals 3.
<hr>
<hr>
:cl:
tweak: Removed the requirements for printing WT-550 TTX rounds.
/:cl:
=> Removes Requirements for Printing WT-550 TTX

_maps/map_files/stations/cerestation.dmm
This PR runs the updatepaths from #28046 again, catching missed paths from #27936.
No quantum plants.
<hr>
<hr>
:cl:
fix: Farragus: plants in medbay now spawn properly.
/:cl:
=> rerun plant updatepaths post cere-medbay remap

code/game/gamemodes/objective.dm
See title. `replace_objective` was being passed a typepath instead of an object, which caused a runtime and caused the replacement to fail.
bug
Tested locally with multiclient. Didn't runtime and the objective was replaced.
<hr>
<hr>
:cl: Chuga
fix: AI destroy objectives are now properly re-rolled when the AI wipes core.
/:cl:
=> Fixes destroy AI objective not reassigning when AI cryos

code/modules/admin/menus/antagonist_menu.dm
See title 
See title
I saw it work with my own eyes.
<hr>
<hr>
=> Fixes null spaced high value item runtime in TGUI antagonist menu

code/game/objects/items.dm, code/modules/martial_arts/martial.dm, code/modules/mob/living/carbon/human/human_defense.dm, code/modules/mob/living/carbon/human/species/_species.dm
Removes references to `/mob/living/carbon/human/proc/check_block()` and `var/block_chance` on `/datum/martial_art`. Since no martial art makes use of `block_chance` anymore, this code is no longer needed.
We're wasting precious CPU cycles on soul from a bygone era.
It compiled. None of this code did even did anything.
<hr>
<hr>
=> Removes unused proc check_block() 

code/game/objects/items/weapons/storage/belt.dm
Adds `/obj/item/grenade/barrier` type to the whitelist of security belt.
These nades are small-sized, belt is the best place for them.
No belt_sprites, unfortunately.
Spawned security belt, barrier grenade, dropwall shield. Grenades went inside a belt perfectly.
<hr>
<hr>
:cl:
tweak: Security belts and webbings are now able to store barrier grenades and dropwall shield generators.
/:cl:
=> Adds barrier grenades to the security belt can_hold

.gitignore, docs/mapping/submaps.md, tools/rustlibs_tools/mapmanip.ps1
This PR makes a fix to the powershell script used to generate mapmanip output from outside of the game, adds documentation referring to it, and adds a pattern to gitignore to ignore the generated map output.
Tooling cleanup, helps mappers.
Ran powershell script to ensure that map generation outside of the game worked, ensured that new map files were not marked as new to git.
<hr>
<hr>
NPFC
=> fix mapmanip script and add docs/gitignore for generated maps

code/game/machinery/hologram.dm, code/game/objects/effects/portals.dm
Adds a `HOLOGRAM_2` flag check for hand tele portals, and adds the flag to the holocall hologram.
Fixes #27527
Took a call, and then used a hand tele and had the caller go through the portal
<hr>
<hr>
:cl:
fix: Holograms do not destabilize hand tele portals anymore
/:cl:
=> Add a hologram flag check for hand tele portals

code/game/gamemodes/dynamic/antag_rulesets.dm
Changeling ruleset can no longer roll by itself
Bugfix
Yeah it works
<hr>
<hr>
:cl:
fix: Changeling ruleset can no longer roll by itself
/:cl:
=> Fixes it so changelings cant roll solo ruleset

code/datums/components/swarming.dm, code/modules/mob/living/simple_animal/hostile/carp.dm
Dead carp can be passed through on harm intent / don't swap positions on help intent.
Dead carp no longer block lasers
Dead non dense mobs should not block lasers. We don't need people dragging dead carp to use as an indestructible shield.
shot carp walked through dead carp etc etc why has carp been a pain auugh
<hr>
<hr>
:cl:
fix: Dead carp act normally and don't block projectiles
/:cl:
=> Dead carp no longer block lasers / interact weirdly

code/game/atoms_movable.dm
Recalls blood drails again from accidental removal in #28224
fixes mobs not bleeding when dragged heavily injured.
see above, also did it with a corgi
<hr>
<hr>
:cl:
fix: Mobs bleed again when dragged heavily injured
/:cl:
=> mobs make trails of blood again when dragged

code/modules/antagonists/mind_flayer/powers/flayer_weapon_powers.dm
Title
This is a pretty egregious bug, whoops
Fired a level 1, level 2, and level 3 grappling hooks. They all had the correct cooldowns
<hr>
<hr>
=> [S] Fixes mindflayer grapple having a lower cooldown than it should

code/game/machinery/hologram.dm
Makes the hologram transfer on holopads for AI more flexible by changing where the area check is done for it specifically, while other mobs are still constrained to the area they're calling to. This prevents cases where the hologram gets cancelled when changing areas even though you're still within range of the old one.
The way transfering holograms for AI was too rigid, and didn't make sense for it. Old comment made it sound like it was a perf save, but the distance check was done all the time regardless _and_ looped through all holopads.
https://github.com/user-attachments/assets/a1dd161a-63d7-4825-b4cd-113ce041c1da
Used holopads as an AI and moved around.
<hr>
<hr>
:cl:
tweak: Range check for holopad projections is more flexible for AI
/:cl:
=> AI holograms can switch between holopads more seamlessly

code/modules/research/protolathe.dm
Makes the chemical capacity of protolathes scale with the beakers. Other machinery do it already, the proto just was missing the code for it and was defaulting to 100.
Fixes #28477. Protolathes also have two beakers, so turns out they're supposed to have 200 capacity on roundstart, not 100.
Started an instance and checked the research computer.
<hr>
<hr>
:cl:
fix: Fix protolate chemical capacity not scaling with beakers. Roundstart machines now have 200 capacity.
/:cl:
=> Protolathe chemical capacity is now based on their installed beakers

code/datums/datum.dm, code/modules/mob/living/simple_animal/hostile/megafauna/legion.dm
Fixes a case when you could throw 2+ hardmode grenades at Legion and he would enrage for more than one time, which resulted in 4+ half-sized Legions and 2+ staffs of storms.
Also moved code around for the constistency.
Bug fix. I doubt that you should be able to get 10 staffs of storms as well as fighting 20 half-sized Legions.
Local server, tried to enrage him with 3 different hardmode nades - he only enraged one time and i had to deal with just 2 half-sized Legions instead of 6.
<hr>
<hr>
:cl:
fix: Legion megafauna can't be enraged for more than one time now, which prevents getting 2+ staffs of storms.
/:cl:
=> Fix Legion megafauna being able to `enrage()` for more than 1 time and remove `/datum/nothing`

code/game/atoms_movable.dm, code/game/machinery/vendors/vending.dm
Makes vendors take 4 seconds to stand back up after falling, down from 14.
14 seconds is a massively long time, to the point that people tend to leave vendors on the floor to avoid the hassle. It's disruptive to normal gameplay and the opportunity cost of avoiding an single strategy that has other safeguards isn't worth the trouble to the rest of the crew.
Even with a 4 second righting time, it can't reasonably be exploited for combat.  For one, you can't vendorcrush somebody until they unflatten from the first crush, making combo-crushing the same person impossible, and 4 seconds is a _long_ time to be standing still undisturbed in combat. If you have 4 seconds to spare to right a vendor in the situation that two people are fighting you, the second person gets 4 seconds of free hits on …
=> Vendors can be righted much faster

code/__HELPERS/game.dm, code/controllers/subsystem/SSghost_spawns.dm, code/game/gamemodes/game_mode.dm
This PR removes `/proc/get_roletext(role)`, a proc that does nothing but return its argument. It used to do something back when special roles were bitflags (#3025) but is no longer necessary.
Code cleanup.
Ran CI.
<hr>
<hr>
NPFC
=> remove unnecessary proc get_roletext

code/modules/station_goals/bluespace_tap.dm
Stabilizers would draw enough energy to stabilize the desired mining power even when there wasn't enough power to reach it, leading to less power being available for mining. This would happen specifically when the actual mining power was under 30MW and the desired was both higher than it and higher than 15MW.
bug fix
- Input varying amounts of power into the BSH and input different mining power with stabilizer priority both on and off
<hr>
<hr>
:cl:
fix: BSH stabilizers no longer draw more power than they should when desired mining power is set too high
/:cl:
=> Fixes BSH stabilizers drawing more power than they should when requesting more mining power than can be stabilized

code/modules/projectiles/projectile/bullets.dm
Recolors WT-550 TTX rounds
There is now a visual que to you being shot with TTX rounds.
https://github.com/user-attachments/assets/1fada639-51d2-46ce-b1c3-ebcd66ab9791
Complied, shot WT round as above
<hr>
<hr>
:cl:
tweak: WT-550 TTX rounds are now green
/:cl:
=> Re-Colors WT-550 TTX rounds

code/game/objects/items/devices/scanners.dm
Fixes a null value runtime in PDA atmos scanner code
Runtime bad
Compiles, now gives a readout when scanning empty pipes
<hr>
<hr>
:cl:
fix: PDA atmos scanners no longer runtime when scanning empty devices.
/:cl:
=> Fixes a runtime in PDA gas scanner code

code/game/gamemodes/wizard/magic_tarot.dm
Makes The Moon's teleporting code into a separate proc, and changes the order of calls done (Make the floor _first_, then teleport the poor sap).
Fixes #28409
Limited the pool of ruins, and made one out of only chasms, then used a Moon card.
<hr>
<hr>
:cl:
fix: The Moon will always place a floor at the intended location first before teleporting them
/:cl:
=> The Moon card makes flooring first before teleporting

code/modules/reagents/chemistry/reagents/medicine.dm
Adds Pump Up to the list of stimulants that Haloperidol purges and the list of stimulants that nanocalcium checks for.
Fixing oversights is a good thing.
Put 50u of Pump Up in a human, shot at the human with a tranquiliser dart shell, saw Pump Up being removed as Haloperidol normally does for stimulants.
Put 40u of Pump Up in a Drask, used a nanocalcium injector, once the generous purging phase ended toxin damage as expected for stimulants began to occur, this caused the death of the Drask.
<hr>
<hr>
:cl:
fix: Fixed the oversight of Pump Up not being purged by Haloperidol.
fix: Fixed the oversight of Pump Up not being among the stimulants that Nanocalcium checks for.
/:cl:
=> Add Pump Up to the list of stims in Haloperidol and Nanocalcium

_maps/map_files/stations/emeraldstation.dmm
Removes the dead corpse from the Diagoras storefront butchery maint area and replaces it with skeletal remains and gibs.
Was supposedly causing too many false murder callouts for security and medbay. This should lessen that without jeapordizing the environmental storytelling.
Map compiled and ran
<hr>
<hr>
:cl:
tweak: Replaced Emeraldstation storefront maint corpse with remains
/:cl:
=> Changes Diagoras storefront maints corpse into remains and gibs

code/modules/recycling/disposal.dm
Cyborg grippers can drop stuff into disposals again.
Removes some now-redundant code.
Bug fix good.
Removing duplicated code bad (thank you new attack chain).
Dropped stuff into disposals with gripper.
Tried to drop empty gripper.
<hr>
<hr>
:cl:
fix: Cyborg gripper can drop stuff into disposals again.
/:cl:
=> Fixes Cyborg Gripper Disposal Bin Interaction

code/modules/research/xenobiology/xenobiology.dm
This PR migrates slime potions to the new attack chain.
Trying to migrate mobs before this is painful and awkward so I'm getting these out of the way first.
Existing tests for docility and consciousness transfer potion, manual testing of remaining potions.
<hr>
<hr>
NPFC
=> Attack chain migration: slime potions.

_maps/map_files/stations/emeraldstation.dmm
Fixes: #27592 
Adds access to Firing Range on the Diagoras
Having access restrictions on department only areas is good
map compiled and ran. Access added
<hr>
<hr>
:cl:
fix: Added access to Diagoras firing Range
/:cl:
=> Adds access to Firing Range on the Diagoras

_maps/map_files/stations/boxstation.dmm
Replaces the hand-made airlock on the Cyberiad AI satellite with a 2x2 airlock helper.
Moves a vent to avoid intersection with the airlock air tank pipe.
Replacing handcrafted airlocks with map helpers improves maintainability and standardizes airlocks in general.
The airlock is easier to use than the old one.
SDMM
In-game
Visited airlock, inspected it, used it.
<hr>
<hr>
:cl:
tweak: The Cyberiad AI satellite airlock is now 2x2.
/:cl:
=> Replaces Cyberiad AI Sat Airlock With 2x2 Airlock

_maps/map_files/stations/emeraldstation.dmm
Replaces the upper handmade Emerald AI sat external airlock with a 2x2, and the lower airlock with a 3x2.
Replacing handcrafted airlocks with map helpers improves maintainability and standardizes airlocks in general.
Larger airlocks are easier to use than 1x1s.
Inspected and used both airlocks.
<hr>
<hr>
:cl:
tweak: The fore external airlock on the emerald AI sat is now 2x2.
tweak: The aft external airlock on the emerald AI sat is now 3x2.
/:cl:
=> Enlarges Emerald AI Sat's External Airlocks

code/modules/projectiles/projectile_base.dm
Fixes cursed penetrator projectiles code.
This will fix an issue, when you receive a damage multiple times from a single projectile.
This will fix an issue of when you walk on the projectile trajectory, projectile teleports next to you and continues its way in a random direction, penetrating other things.
It makes people's life a bit better. Seen explorers suffer from this, was awful. Not even talking about crew vs nukies.
How it is on live (he is shooting 1 projectile each ~5 seconds, however i receive damage for more than one time)
https://github.com/user-attachments/assets/36acb0f9-1325-43c8-afcf-90ecab6de324
How it is with the fix
https://github.com/user-attachments/assets/2e02b509-9277-491a-ac54-b47d2d634416
It's in a section above. Despite second video is being only 3 seconds long, …
=> Fix penetrator projectiles

code/modules/power/apc/apc.dm
This makes emergency lighting turn off after 2 minutes, which they were intended to but don't because of a bug.
Apart from the infinite emergency power being a bug, I think it's good for losing power to lights to (eventually) mean no lights.
The total lack of darkness on the station even in blackouts is a bit of a detriment to the atmosphere of the game, I think, and more or less relegates torches, flares and light sources to situations where antags intentionally created darkness.
Between this and #28518, hopefully we can get an eerily quiet, dark environment when the station is falling apart.
VV'd an APC to see the timer. 
Waited 2 minutes to see if the lights turned off.
Restored power to make sure the timer reset.
Turned APC power off while unpowered to make sure emergency power didn't …
=> Emergency lights turn off after 2 minutes again

code/modules/mining/equipment/lazarus_injector.dm
This PR migrates laz injectors to the new attack chain.
Easier to fix this before mob migration than the other way around.
Existing tests in mob attack chain suite.
<hr>
<hr>
NPFC
=> Attack chain migration: laz injector.

code/modules/clothing/head/misc_special.dm
Welding helmets no longer hide ears when the helmet is up. While the helmet is down, it still protects your ears.
Change requested by a balance member, ear protection should be harder to come by than any welding helmet.
See above
<hr>
<hr>
:cl:
tweak: Welding helmets no longer hide ears when the helmet is up.
/:cl:
=> Welding helmets no longer hide ears when the helmet is up.

code/datums/tgs_event_handler.dm
Currently, if you do many TGS deployments quickly, TGS doesnt send the heartbeat event to not overload DD.
Unfortunately, our health check SS doesnt care.
This PR makes it so any TGS event counts as communication, since, well, it is, and uses that to track.
False warnings that make me get out of bed are bad.
N/A
I didnt even bother compiling this, but I am upfront about that.
<hr>
<hr>
NPFC
=> Fixes heartbeat warnings when stacking deployments

code/__DEFINES/mob_defines.dm, code/__DEFINES/sight.dm, code/__HELPERS/game.dm, code/datums/emote.dm, code/game/atoms.dm, code/game/gamemodes/miniantags/pulsedemon/pulsedemon.dm, code/game/objects/items/devices/megaphone.dm, code/game/objects/items/devices/radio/radio_objects.dm, code/modules/mob/mob.dm
Adds AI eye support for emote, visible_message, and audible_message. audible_message is only  relayed if the camera relays speech.
Note: emotes that are tagged as audible are still always relayed. This is because our "audible" emotes are almost all things that would have an obvious visual tell as well, e.g. sneezing, and the audible tag is used for handling muzzles and miming instead.
The AI should be able to see things that a camera should see, and hear things that a mic'd up camera can hear.
Triggered emotes, visible_message, and audible_message both near the core and well beyond the core's sight/hear range.
<hr>
<hr>
:cl:
add: AI eyes can now see emotes and other visible actions.
add: AI eyes can now hear audible actions if they can hear speech.
/:cl:
=> AI eye support for emote, visible_message, and audible_message

code/modules/mob/living/simple_animal/hostile/hostile.dm, code/modules/mob/living/simple_animal/hostile/syndicate_mobs.dm
Adds a check for ranged mobs, so they will attack closets with `OpenFire()`, instead of trying to perform a melee attack.
Syndie mobs now properly kill their opponents, despite them being asleep.
Ranged mobs will not just stay nearby the object you are hiding at, since it was only possible to attack this object in melee, but most of the ranged mobs have a `minimum_distance` > 1, which didn't allow them to get close enough to perform a melee attack.
Ranged syndie mob will now kill you even if you press "Sleep" button being in stamcrit from C-20r bullets. No cheesing, also properly dealing with the mobs that are getting sleep proc from being in critical condition, which made them non target and allowed to quickly escape after they wake up. Syndie mobs don't handcuff their opponents, so they …
=> Tweak for ranged and syndie mobs

.github/workflows/ci.yml
Remove redundant MariaDB Container Startup
Applies https://github.com/DaedalusDock/daedalusdock/pull/1220
Since the original TG Travis -> Actions migration, most SS13 servers start a completely pointless and misconfigured MariaDB/MySQL container as a service. But then proceed to start the runner OS's preinstalled MySQL server anyway.
This saves on average ~18-26 seconds per affected test job. This is more of a problem on TG than Paradise, though.
Github Actions-Related. This PR is the test.
<hr>
<hr>
NUFC
=> Removes unused/Misconfigured MariaDB container from SQL Tests

code/game/objects/items/robot/robot_upgrades.dm, code/game/objects/items/weapons/storage/bags.dm
Fixes #28512
It's an oversight from when I refactored cyborg inventories, whoops.
Tried to auto-pickup ores with a regular mining bag and a mining satchel of holding, both worked as intended.
<hr>
<hr>
:cl:
fix: Cyborg ore bags of holding can auto-pickup again
/:cl:
=> Fixes cyborg satchels of holding not properly picking up ores.

_maps/map_files/stations/boxstation.dmm, _maps/map_files/stations/cerestation.dmm, _maps/map_files/stations/emeraldstation.dmm, _maps/map_files/stations/metastation.dmm, code/game/objects/structures/crates_lockers/closets/secure/security_lockers.dm
This PR removes all the arbitrary contents added on top of the hardcoded items added to detective closets across all stations and adds them to the hardcoded list.
Mapping consistency.
<hr>
<hr>
:cl:
fix: Detective closets across all stations, if they didn't have them already, will now have a flash, an extra flask, a pair of handcuffs, a and a pair of latex gloves.
/:cl:
=> make detective closet contents consistent across stations

code/game/objects/items/weapons/storage/belt.dm
Stops belts from disappearing on mouse drop when the wearer is being grabbed  be their neck.
I believe `/obj/item/storage/MouseDrop()` completely overlaps `/obj/item/storage/belt/MouseDrop()` functionality, so the latter can be removed.
Fixes a bug.
<hr>
<hr>
:cl: Maxiemar
fix: Belts no longer disappear when being mouse dragged to a hand while the wearer is being grabbed by their neck.
/:cl:
=> Fix belt disappearing on mouse drop

_maps/map_files/RandomRuins/LavaRuins/lavaland_surface_seed_vault.dmm
Fixes: #26542
Removed the redundant trash chute and replaces it with two fire suit lockers in the lavaland seed vault. Each locker has an extra set of equipment in it for the possible 4 diona that can spawn there. This will allow a means for the diona to leave the seed vault without burning up
should be possible to complete diona objectives, which require you to go out into lavaland
code compiled, simple map change
<hr>
<hr>
:cl:
tweak: Added firesuits to seed vault
/:cl:
=> Added fire suits to seed vault

code/modules/mod/modules/modules_supply.dm
It's in the title. Adds 2 lavaland-exclusive turfs to the list of allowed turfs, so mining suit will not lose its ash while running on them.
Have you ever tried to solve a puzzle ruin while wearing mining modsuit? It's really annoying when each step you hear that recharge sound. Also puzzle area doesn't defend you from ash, so you should be able to keep the charge.
Also adds Legion's turfs from Necropolis. Yeah, there is not much of space, but.. it's more for the SS220, where we have a little bit more expanded Necropolis to explore. And its area isn't ashproof, so you should be able to keep the charge, otherwise you will suffer.
Spawned in, spawned these turfs, walked on them and didn't lose any charges of stored ash.
<hr>
<hr>
NPFC
=> Adds 2 lavaland turfs to `keep_turfs` of ash accretion module

code/datums/mind.dm, code/game/machinery/doors/windowdoor.dm, code/game/sound.dm, code/game/turfs/turf.dm, code/game/verbs/suicide.dm, code/modules/admin/misc_admin_procs.dm, code/modules/admin/topic.dm, code/modules/admin/verbs/cinematic.dm, code/modules/admin/verbs/debug.dm, code/modules/admin/verbs/gimmick_team.dm, code/modules/admin/verbs/infiltratorteam_syndicate.dm, code/modules/admin/verbs/onlyone.dm, code/modules/admin/verbs/randomverbs.dm, code/modules/admin/verbs/striketeam_syndicate.dm, code/modules/antagonists/_common/antag_team.dm, code/modules/mob/camera/cameranet.dm, code/modules/mob/living/living.dm, code/modules/mob/living/living_defense.dm, code/modules/mob/living/silicon/ai/ai_defense.dm, code/modules/mob/living/silicon/robot/drone/drone_manufacturer.dm, code/modules/mob/mob.dm, code/modules/mob/new_player/new_player.dm, code/modules/response_team/ert.dm
This PR cleans up SSTicker checks to use game stages, as opposed to checking if the ticker was running at all.
Fixes #18159 
Code consistency is good. Code being more specific is also good.
Complied, observed pre-start, spawned as drone, got in a skrell, opened a windoor, walked round, started round, committed suicide.
<hr>
<hr>
NPFC
=> Refactors SSTicker checks

_maps/map_files/generic/centcomm.dmm, code/datums/uplink_items/uplink_nuclear.dm, code/game/objects/structures/crates_lockers/closets/syndicate_lockers.dm, code/modules/admin/verbs/striketeam_syndicate.dm, code/modules/projectiles/guns/projectile/saw.dm
Title. Also changes a few names and descriptions for readability.
Does not change any stats of the weapon or its ammunition.
The L6 being chambered in 5.56 didn't make much sense given its higher damage and relatively low magazine capacity. Also, the icon for the bullet it fires is literally called a 7.62 round already.
- loaded in
- observed weapon and ammo
- fired weapon
- success
<hr>
<hr>
:cl:
tweak: Changed L6 to 7.62, changed a few descriptions and names.
/:cl:
=> [LORE...sorta] Switches the L6's caliber to 7.62x51mm

code/game/machinery/doors/airlock.dm
Fixes #28438
Changes `used` to `user` in the airlock `interact_with_panel`. `interact_with_panel` expects a mob, meanwhile the airlocks `item_interaction` passed it an item.
Runtime bad. Bugs bad too.
Opened a door without anything, opened a door with a signaler, installed a signaler inside a door with an open panel.
<hr>
<hr>
:cl:
fix: signalers wont runtime when opening doors
/:cl:
=> [Fix] Signalers wont runtime when opening airlocks

code/game/machinery/vendors/vending.dm, code/modules/mob/living/silicon/silicon_mob.dm
Fixes #28546
Fixes #28381
overrides silicon put_in_hand_ procs.
bug
vended 12 items
<hr>
<hr>
:cl:
fix: Items vended by borgs no longer go in their hands
/:cl:
=> Fixes items being vended into cyborg hands

code/game/gamemodes/miniantags/revenant/revenant.dm
Refactors the spawning of revenants, so they dont wait 15 seconds to give spells and abilities when you spawn
Mostly copied from how pulse demon spawns
It waiting how it did was seemingly for if admins manually spawned a revenant? which is a decent idea in theory, but im unsure as to why an admin would be manually spawning a revenant to give to ghosts, over using the event manager. 
it waiting an entire 15 seconds has confused me personally multiple times when i've rolled it, so i can imagine it'd confuse others too
Forced a revenant event, got the spells and objectives.
Manually spawned a revenant, got spells, didn't get objectives, however this is consistent with all the other midrounds(excluding humanoids) that have objectives so im counting it as working as intended:tm:
<hr>
<hr>
:cl: …
=> Refactors how revenants spawn

code/game/objects/items/weapons/manuals.dm
Title. A bunch of manuals have summaries that are no longer copy-pasted. Also removes a mention of the literal, actual Weyland-Yutani corporation, which does not exist in lore.
Copy-pasted escriptions are bad. Word for word references to other media franchises are bad.
- spawned books
- absorbed knowledge
<hr>
<hr>
:cl:
tweak: Added some proper manual summaries.
/:cl:
=> [LORE] Updates a bunch of manual summaries

code/modules/admin/reagents_editor.dm, code/modules/mob/living/carbon/carbon_procs.dm, code/modules/mob/living/carbon/human/human_life.dm, code/modules/mob/living/carbon/human/species/_species.dm, code/modules/reagents/chemistry/reagents_holder.dm
Painkiller reagents no longer affect non-human mobs and species that cannot metabolize them. 
Technical changes:
- `can_metabolize()` is now a `/mob/living/carbon/human` level proc.
- All shock reduction calculations now go through `/mob/living/carbon/proc/shock_reduction()`. Only the human level version performs any calculations. This is a hack to get around HUD procs being at the carbon level.
- `shock_reduction()` now checks if the reagent can be metabolized by the mob.
The way shock reduction from reagents was calculated before was a little strange. Non-human carbon mobs like xenomorphs would see the damage HUD effects of painkillers, but wouldn't receive any slowdown reduction. Species that couldn't otherwise metabolize painkiller reagents nevertheless received their slowdown and HUD …
=> Refactors reagent shock reduction

tools/ci/check_grep2.py
Since check_grep2 is just iterating through a bunch of files and running some regexes on each line, most of the current slowness is due to file IO overhead. 
ProcessPoolExecutor is Python's high level API for splitting tasks across concurrent process forks. By splitting it over several processes, the program isn't stuck waiting on file operations the whole time. Instead, _several_ programs are stuck waiting on file operations the whole time. This is much more efficient.
I am a very impatient person. I do not like waiting for a several second lint to complete. This thing _zooms_ (at least a 10x speedup or more) on my laptop's 8 core Intel CPU. This makes running lints frequently during development much more tolerable.
CI examples:
Old: …
=> Makes check_grep2.py 10x faster

code/game/objects/structures/curtains.dm
Removes an unused var.
Compiler warnings annoying.
<hr>
<hr>
NPFC
=> remove unused variable

code/tests/_game_test_puppeteer.dm
Makes puppet test `use_item_in_hand` check an items attack chain
Trying to use that with an unmigrated item in a test will cause it to fail.
After adding that, the unmigrated item in a test works again
<hr>
<hr>
NPFC
=> Adds an attack chain check for puppet test's use_in_hand proc

code/controllers/subsystem/SSai_controllers.dm, code/controllers/subsystem/movement/SSai_movement.dm, code/controllers/subsystem/processing/SSai_behaviors.dm
This PR cleans up the names of some AI-related subsystems.
Consistency, looks nicer.
Visual Inspection
<hr>
<hr>
:cl:
tweak: The names of AI-related subsystems have been cleaned up.
/:cl:
=> Cleanup AI subsystem names

code/game/objects/structures/watercloset.dm
Fixes #28538
Shower fixture's `try_build` had a proximity check that was removed in a recent PR.
Rebuild showers good
Built showers on walls
<hr>
<hr>
:cl:
fix: Showers can be built again
/:cl:
=> Fixes shower building

code/datums/uplink_items/uplink_traitor.dm
Stops telegun from spawning when surplus crates are purchased.
Fixes an oversight
Compiled
<hr>
<hr>
:cl:
fix: Fixed an oversight where telegun could spawn in surplus crates.
/:cl:
=> [s] Prevents telegun from spawning inside surplus crates

_build_dependencies.sh, code/__DEFINES/_versions.dm, code/__DEFINES/rust_g.dm, code/controllers/subsystem/SSredis.dm, tools/ci/install_rustg.sh
Bumps rustg from 3.4.0-P to 3.7.0-P. Has new features for iconforge shenanigans and a soundfile length thing. No idea if we will use either but nice to have.
TM because updating this has a tendency to make redis just stop working. Im not pushing a new release to our rust repo till we know this works, so the CI library is in repo for a bit. Purists be damned.
Updates good
Started server, redis connected, SQL connected, verified that logs are the right format.
<hr>
<hr>
experiment: Updated the rust helper library that handles logging and DB stuff
/:cl:
=> [READY] RUSTG Update

code/datums/elements/strippable.dm, code/modules/mob/living/carbon/carbon_stripping.dm, code/modules/mob/living/carbon/human/human_stripping.dm
Makes thief gloves stealthy again. Fixes all cases of cogbars appearing on in_thief_mode() check.
Fixes #28598 
Fixes #28615
Oversight fix
Joined a local server with two clients, spawned thief gloves, and stripped the item from one of the clients
<hr>
<hr>
:cl:
fix: Fixed cogbars appearing with thief gloves
/:cl:
=> Fix cogbar appearing with thief gloves

code/__HELPERS/constants.dm, paradise.dme
This PR removes an unused two line file of macro defines.
Dead code bad.
Built and ran CI.
<hr>
<hr>
NPFC
=> remove unused constants define file

_maps/map_files/templates/shelter_2.dmm
This PR removes a tiny corner window in the luxury capsule which was preventing movement through the shelter, pixel shifting two nearby windows to take up the space. The windows were overlapping a nearby door anyway so the change is basically unnoticeable. This is basically the only instance of a corner window being used like this and the movement code, keyed to the dir of the atom, is all scuffed and there's no reason to spend time fixing it when this is the only time it's a problem, as evidenced by the available icon states:
Movement shouldn't be stopped by something this unnecessary.
Spawned luxury capsule, walked around.
<hr>
<hr>
:cl:
fix: Players can now properly move about the interior of luxury shelter capsules.
/:cl:
=> fix luxury capsule windows blocking movement

code/_onclick/ai_onclick.dm
Fix Cogbar Appearing Over Cyborgs When Bolting/Shocking Doors
Fixes Cogbar Appearing Over Cyborgs/AI When Bolting/Shocking Doors
Fixes #28625
Oversight fix
Tried to bolt airlock as cyborg, no cogbar on other client.
<hr>
<hr>
:cl:
fix: Fixed сogbar appearing over cyborgs/AI when bolting/shocking doors
/:cl:
=> Fix Cogbar Appearing Over Cyborgs/AI When Bolting/Shocking Doors

code/_onclick/hud/plane_master.dm
Fixes a bug for those who play without new lighting
Less bugs
https://github.com/user-attachments/assets/4dfbf744-48d2-4857-8fa7-8413c8f1a1e0
https://github.com/user-attachments/assets/65671933-baef-4d5e-b055-3a79fbc3cb93
Tested a few things in localhost as shown in the videos above
<hr>
<hr>
:cl:
fix: Fixed rendering of unblurred exposure icon on every backdrop
/:cl:
=> [Fix] Rendering of unblurred exposure icon on every backdrop

code/game/objects/structures/janicart.dm
Adds an interaction for stuffing things into the bag for the janicart. It is at the very end of the item interaction chain, so you can't end up stuffing equipment or reagent containers in it unless you remove the bag first. Everything else is handled by the bag's own procs.
Fixes #28636
Spawned as a ~~monke~~ janitor and started interacting with a trashbag, either on its own or in the cart.
<hr>
<hr>
:cl:
fix: Items can be put into a trashbag attached to a janicart
/:cl:
=> Allow putting items into a janicart's trashbag

code/__DEFINES/layers.dm
Shifts the defined planes and layers so that cogs and thought bubbles aren't overlapping. I can't just shift cogs since it's a plane and those do not support floats like layers, so everything has to be moved up.
Otherwise, the cog plane ends up taking over the bubble plane, which makes the preference runtime since it's looking for a screen element that does not exist.
Fixes #28612
https://github.com/user-attachments/assets/fdad3665-a0be-4241-87a7-5bbfbba55a5d
Looked around in general to make sure nothing was broken with general lighting and UI elements. Toggled both thought bubbles and cogs on a player separately from each other.
<hr>
<hr>
:cl:
fix: Fix cogs setting conflicting with thought bubbles
/:cl:
=> Shift planes and layers to prevent overlap with conflicting displayed elements

code/modules/mob/living/simple_animal/parrot.dm
Gives Poly some more lines and adds one line that is the 'WHO TOOK THE DAMN HARDSUITS?' but 'MODSUITS' instead of 'HARDSUITS'.
Poly seems too constrained by the limited lines. Engineering doesn't use hardsuits anymore.
Just changed and added some text lines, I feel that testing wouldn't be needed in _this_ case.
<hr>
<hr>
:cl:
add: Adds 19 lines to Poly
/:cl:
=> Gives Poly Some More Lines

code/game/objects/items/weapons/melee/melee_misc.dm
Bluespace enchantment now takes into account blade's power to adjust its cooldown time, not only weaken time. This results in lavaland's spellblade being able to dash only each 5 seconds, instead of 2.5.
The only difference between wizard's and bubblegum's bluespace spellblades is 2.5 DECIseconds of weaken(). You don't notice these 2 and a half of deciseconds at all. But we can just adjust cooldown depending on blade's power, and wow, wizard is 2x more effective at dashing! Incredible, thanks, i know.
Left one is wizard's, right one is miner's.
<hr>
<hr>
:cl:
tweak: Bluespace spellblade's ability cooldown now depends on its power.
/:cl:
=> Nerf Lavaland's bluespace spellblade

code/datums/mind.dm
Fixes a small spelling mistake in a code comment.
Tiny increase in code quality.
Not required (or I'm going to scream)
<hr>
<hr>
npfc
=> fix spelling of a code comment from "defualt" to "default"

code/modules/antagonists/changeling/powers/augmented_eyesight.dm, code/modules/antagonists/changeling/powers/transform.dm
Fixes some bugs with changeling's Augmented Eyesight, including giving you the wrong eyesight flags post-transforming.
Bugs bad
Yep, it works correctly.
<hr>
<hr>
:cl:
fix: Changeling's Augmented Eyesight stays active after a transformation.
/:cl:
=> Fixes some bugs with changeling's Augmented Eyesight

_maps/map_files/RandomRuins/SpaceRuins/oldstation.dmm, _maps/map_files/stations/cerestation.dmm, _maps/map_files/stations/deltastation.dmm, tools/maplint/lints/cable_tmpvars.yml
This PR adds a maplint prohibiting use of the `d1` and `d2` vars on cables and runs the updatepaths from #27386 for what is hopefully the last time. I could have sworn this maplint already existed, but it did not, and so these vars have snuck back into maps since that PR was merged.
Map conformance good.
CI and Maplint.
<hr>
<hr>
NPFC
=> ban d1/d2 cable vars in maps for good

.github/workflows/label_stale.yml
This increases the time from 60 -> 120 days on github-actions when marking a PR stale.
Allows for issues to stay listed longer, which helps to get bugs noticed and fixed.
It works, trust me.
<hr>
<hr>
NPFC
=> Increases the time on stale issue labeling

code/game/area/areas.dm
This makes fire alarms stop the racket after 4 minutes.
They still do all the other fire alarm stuff after that, just not the noise.
The sound is really grating and carries across half the station, and the immersive effect wears thin a bit after hearing it for ages when atmos hazards haven't been repaired. It's good for a bit, but after a while of being on it's just a nuisance to anyone in a huge radius, who has to hear it or mess with their volume until engi fixes whatever caused the alarm.
I think 4 minutes is a good amount of time to alert everyone and get engi called, without being too painfully long, but I can change it if need be.
Also, the silence is nice and thematic when things have really gone to hell on the station after a plasmaflood or huge explosion.
Between this and #28517, …
=> Fire alarms now eventually stop blaring

code/datums/uplink_items/uplink_traitor.dm, code/modules/clothing/under/jobs/plasmamen/engineering_plasmasuits.dm, code/modules/mob/living/carbon/carbon_procs.dm
Adds the contortionist's envirosuit, a plasmaman-friendly, plasmaman-exclusive alternative to the contortionist's jumpsuit that can only be worn by plasmamen and allows you to wear a helmet while ventcrawling.
All species should have the joy of contortionist's jumpsuit. Lots of plasmamen atmos techs are denied this.
Ran paracode, plasmamen can buy contortionist's envirosuit as an alternative, other species cannot.
<hr>
<hr>
:cl:
add: Contortionist's envirosuit, a Plasmaman-friendly alternative to the contortionist's jumpsuit.
/:cl:
=> Adds contortionist's envirosuit (Plasmaman contortionist's)

code/game/turfs/simulated/floor/light_floor.dm
Allows AI and borgs to toggle light tiles on/off.
Light tiles should be controllable like other lighting systems. This avoids requiring the jank workaround of crowbaring up a tile and putting it back down to turn it on as a borg and having to turn off the APC to turn the tiles off.
Spawned an AI and a borg in test tiny along with a normal and disco variant of the light tile.
I was able to turn the light tile on/off at will.
The disco light tile could be turned on if depowered, but not turned off.
<hr>
<hr>
:cl:
tweak: AI and borgs can now toggle light tiles.
/:cl:
=> AI and Borgs can Toggle Light Tiles

code/modules/recycling/disposal.dm
This PR fixes disposal pipes rendering above other underfloor atoms like pipes. I changed this in #28544, probably for debugging purposes, but forgot to change it back. Fixes #28701.
Regression fix.
<hr>
<hr>
:cl:
fix: Disposals pipes will properly render under atmos pipes under flooring.
/:cl:
=> fix disposal pipe draw layer

code/game/objects/items/devices/painter/floor_painter.dm
Fixes #28702 
oversight fix
above
<hr>
<hr>
:cl:
fix: The floor painter can paint cargo brand full brown tiles
/:cl:
=> Adds the full brown tile to the floor painter options

code/game/atoms.dm, code/modules/awaymissions/mission_code/ruins/telecomns.dm, code/modules/projectiles/projectile_base.dm
Adds new var for all atoms (if i could make it less massive, let me know), that will allow projectiles to hit things like cables, pipes, floor tiles, literally anything. Only if we want them to.
Fixes inability to hit rigged plasma tank in dvorak's ruin.
Rigged plasma tank has `bullet_act`, so you should be able to hit it.
Loaded ruin, removed catwalk upon plasma tank, shot it with a laser. Boom!
Tried the same with pipes, cables that were on the plating - they ignored a projectile, just as always.
<hr>
<hr>
:cl:
fix: You can finally explode rigged plasma tank with a shot, not only by stepping on it.
/:cl:
=> Fixes inability to explode hidden rigged plasma tank

code/game/gamemodes/miniantags/revenant/revenant_abilities.dm
Makes it so the haunted items ability can attack things that aren't humanoid(as well as humanoids)
example some of what they can now attack;
Borgs/ai
Ian the corgi
Terror spiders
blob naughts/spores
Basically if they're a simple mob, or carbon they'll be attacked. The only things that they wont attack, are revenants, and other possessed items.
Theres little reason why the haunted items ability only targets humanoid mobs, If lets say, the revenant had the objective "Help the crew in critical situations, but take your payments in souls." and terror spiders rolled. All the rev could do, is spam light shock, But if the terrors break the apc, now the rev is unable to help the crew in any meaningful way, outside of report where terrors are. 
Ontop of that, stuff like cyborgs that dont get …
=> Revenants haunted items ability can now hit stuff that aren't humanoid mobs

code/modules/reagents/reagent_containers/glass_containers.dm, code/modules/reagents/reagent_containers/syringes.dm, code/tests/attack_chain/test_attack_chain_reagent_containers.dm
This PR fixes two issues found with the reagent containers attack chain migration: not being able to place beakers on tables, and various interaction problems with syringes.
Bugfixes.
See newly added tests.
<hr>
<hr>
:cl:
fix: Beakers and other such containers can properly be placed on tables and in backpacks.
fix: Syringes can now properly draw from beakers and inject into other items like slime extracts.
/:cl:
=> reagent container interaction fixes

code/_onclick/item_attack.dm, code/_onclick/item_attack_legacy.dm, code/modules/reagents/reagent_containers/iv_bag.dm, code/modules/reagents/reagent_containers/patch.dm, code/modules/reagents/reagent_containers/spray.dm, code/tests/attack_chain/test_attack_chain_reagent_containers.dm
This PR fixes and adds tests for:
- Chemistry bags not picking up all reagent containers with one click on a tile
- Chemistry bags not emptying into chem fridges
- Chemistry bag not accepting items placed directly inside them
- IV bags not being filled from other containers
- Syringes not emptying into containers on inject
- Fixes spray cleaners adjusting their nozzle flow twice on use
- Fixes spray cleaners not being able to spray a distant tile
Chem bags were a new code path for the attack chain and needed a few call sites added in negotiating between chains. The issue is still that /obj/item/attackby is still the only place where the main behavior of using storage on other items sits, and up until now, to the best of my knowledge, nothing else has been migrated that is auto-picked up …
=> interaction fixes for IV bags, chem bags, and syringes

code/modules/reagents/reagent_containers/patch.dm, code/modules/reagents/reagent_containers/pill.dm, code/tests/attack_chain/test_attack_chain_reagent_containers.dm
This PR fixes not being able to activate pills and patches in hand to ingest or apply them.
Bugfix.
Manual and test suite addition.
<hr>
<hr>
:cl:
fix: Patches and pills are properly applied and ingested when used in-hand.
/:cl:
=> fix pill and patch activate in-hand

code/game/machinery/clonepod.dm, code/modules/reagents/reagent_containers/glass_containers.dm, code/tests/attack_chain/test_attack_chain_reagent_containers.dm
Fixes #28772 
Clonepods dont skip to the afterattack in their item interaction anymore, adds a missing return to glass container interactions so it doesnt bap.
fixes bugs.
Tested it ingame, added it to the puppet tests.
<hr>
<hr>
:cl:
fix: clonepod accepts reagents again
/:cl:
=> [Fix] clone pod accepts reagents again

code/modules/food_and_drinks/food/condiment.dm, code/modules/reagents/reagent_containers.dm, code/modules/reagents/reagent_containers/dropper.dm, code/modules/reagents/reagent_containers/glass_containers.dm, code/modules/reagents/reagent_containers/patch.dm, code/modules/reagents/reagent_containers/pill.dm, code/tests/attack_chain/test_attack_chain_reagent_containers.dm
This PR fixes:
- Incorrect messages appearing in chat when using a dropper on mobs
- Attack animations occurring when drinking from or feeding a mob from glass bottles
- Being unable to insert pills into a bottle by hand
- Lack of click cooldown in certain situations (not mentioned in changelog for reasons)
Bugfixes.
Manual testing, especially for attack animation stuff since we don't have a good test harness for that yet, and test suites for everything else.
<hr>
<hr>
:cl:
fix: Messages about drawing reagents from people will no longer appear when using an eye dropper on them.
fix: Attack animations will no longer occur when drinking from or feeding a mob from glass bottles.
fix: Pills can properly be inserted into and picked up by pill bottles.
/:cl:
=> dropper, patch and pill fixes

code/game/objects/items/control_wand.dm
Makes access tuner's `do_after` hidden
Fixes #28753
Oversight fix
Local tests
<hr>
<hr>
:cl:
fix: Fixed cogbars appearing with access tuner
/:cl:
=> Fix access tuner causes cogbar

code/modules/power/engines/supermatter/supermatter_event.dm
Fixes wrong proc call at one of the Supermatter's event, caused to nothing to happen on the event.
Fix
Started SM by throwing a skrell at him, forced event, ensured it actually turned off scrubbers and vents.
<hr>
<hr>
:cl:
fix: Supermatter's A-2 class anomaly is now working.
/:cl:
=> Fixes one of the SM events

code/modules/mob/mob.dm
1) Prevents glance messages for AI when in camera mod
( fix for https://github.com/ParadiseSS13/Paradise/issues/28453)
2) Prevents appearance for users in case no one else can see the interaction
AI should be able to spy undetected. GLORY TO MY IMMORTAL OVERLORD!!!
localhost, all good.
<hr>
<hr>
:cl:
tweak: You will not get a message in chat when ai examine something close to you.
/:cl:
=> Edge cases broadcast examine

code/modules/mining/equipment/resonator.dm, code/tests/attack_chain/test_attack_chain_turf.dm
Fixes #28533
Adds an ancient rock check in the resonators burst code.
Changes the turf attack chain test to use a regular mineral rock.
you can break ancient rock with unintended tools
Tried to mine ancient rock
<hr>
<hr>
:cl:
fix: It's no longer possible to mine ancient rock with a resonator.
/:cl:
=> [Fix] resonator no longer destroys ancient rock

code/modules/power/lights.dm
This PR changes how lights lookup their managing APC when being set to emergency lights. Previously, on every power change which required emergency lighting, every light would receive a signal and perform a `/area/proc/get_apc()` call on its area, which iterates over every APC in the world before returning the relevant one, instead of just checking the APC in the light's powernet, which has to be the same one, because every area can only have one APC.
Tiny tiny performance improvement.
Turned off light channel on APCs on station, ensured emergency lights still worked. Added a light to the druglab ruin, spawned multiple drug lab ruins, and ensured that turning the power off on one of them did not effect the lights on the other one.
<hr>
<hr>
NPFC
=> refactor: speed up emergency light change

.github/ISSUE_TEMPLATE/issue_report.yml
Updates the issue form template, hopefully to attract more attention to if someone may be reporting a exploit in the public by having two check boxes with text detailing the two major factors to an exploit
Mistakes happen or sometimes some people define exploits differently to how we do, hopefully making it so you need to check two boxes with text next to them detailing what we define as an exploit will help.
Im going to be completely honest, im not totally sure how to test this outside of looking at the file preview on github, not without doing some merge stuff with my local branch that i don't feel overly confidant in being able to undo after the fact.  However as far as i can tell it works
<hr>
<hr>
NPFC
=> Updates the issue report template to hopefully better draw attention to what may be an exploit

code/datums/uplink_items/uplink_traitor.dm, code/modules/projectiles/ammunition.dm, code/modules/projectiles/ammunition/magazines.dm, code/modules/projectiles/guns/projectile/automatic.dm
Adds a bulldog shotgun to the traitor uplink for 50 TC, loaded with rubbershot. Additional magazines of rubbershot can be bought for 10 TC each and can be reloaded with all shotgun rounds that are not buckshot or Frag12.
Traitors deserve to use the shotgun too.
Spawned as tot. Opened uplink. Bought Bulldog and Extra Mag. Confirmed was all rubbershot. Reloaded with lasershot. Failed to reload with Frag12.
<hr>
<hr>
:cl:
add: Added bulldog to traitor uplink
/:cl:
=> Bulldog for Traitors

code/game/machinery/vendors/generic_vendors.dm
Adds two (2) splints to the emergency first aid wall vendors, allowing patients to be splinted in the field before they come to medical.
Splints are primarily there to allow patients to be transported to medical so they can have their bones fixed by surgery. Once you're actually in medical, there's not really a reason to use them, because surgery is right there, and yet they are only available from medical.
This gives splints a reasonable use case outside and might actually make people use them more.
Spawned in and went to a vendor, noticed there were splints, vended them, turned myself into a cast mummy.
<hr>
<hr>
:cl:
add: Added 2 splints to first aid wall vendors.
/:cl:
=> Adds Splints to First Aid Wall Vendors

code/game/objects/items/weapons/bio_chips/bio_chip_stealth.dm, code/game/objects/structures/crates_lockers/closets/cardboardbox.dm
Adds `return ..()` for the large cardboard box's `attackby`, so you can perform an attack in melee. 
Feels strange not being able to hit an object. Looks like an oversight, tho.
Destroyed some boxes on local with a welding tool.
<hr>
<hr>
:cl:
tweak: You can now attack large cardboard boxes in melee.
/:cl:
=> Allows to attack large cardboard box in melee.

code/modules/reagents/reagent_containers/spray.dm, code/tests/attack_chain/test_attack_chain_reagent_containers.dm
This PR fixes spray containers not being interactable with certain objects like tables. Fixes #28787.
Bugfix.
Manual testing and added game test.
<hr>
<hr>
:cl:
fix: Spray bottles can properly be placed on tables, racks, and other structures.
/:cl:
=> fix spray container interactions with tables

code/__DEFINES/dcs/atom_signals.dm, code/game/machinery/smith_machines.dm
Fixes an issue with the smart hopper.
Issues are bad.
Spawned in, did things, issue ceased to be.
<hr>
<hr>
:cl:
fix: Fixed an issue with the Smart Hopper
/:cl:
=> [s] Fixes an issue with the smart hopper

_maps/map_files/stations/emeraldstation.dmm
Adds a missing Security Shutter in Warden's Office on Diagoras when Prison Wing Lockdown is initiated.
It looks weird, and evildoers can just break the window and console and go inside.
Booted up Diagoras, triggered Prison Wing Lockdown, saw the shutter activate.
<hr>
<hr>
:cl:
fix: Added a missing Security shutter in Warden's Office on Diagoras
/:cl:
=> Adds a missing Security Shutter on Diagoras

code/datums/spells/bloodcrawl.dm
This PR simplifies the description of the shadow crawl power. Rather than just change the spelling of "terrane" to "terrain", I just used smaller words. I'm not even sure if "incomprehensible" is also the intended word usage here. Like, they probably just mean invisible right? It could literally mean "unable to be comprehended (with the senses)" but that feels kind of overwrought when they could just say "invisible". Whatever.
Easier to read.
<hr>
<hr>
:cl:
tweak: Reworded the description of the shadow crawl ability to be clearer.
/:cl:
=> reword shadow crawl ability description

code/modules/surgery/organs/organ_icon.dm
Fixes #27847
Fixes #25421
Changes `GetUITriState` to `GetUIState`. I assume it was getting jumbled with TriState since there's only 2 body types and TriState expects 3, but I haven't delved deep into DNA code. That caused it to randomly revert the body types of every species upon being created.
Reports came from slime players cause their body types are the most noticeable, due to their eyes.
Getting your body type and visuals inverted for an entire round sucks
Row 1
Gender - Female
Body Type - Feminine
Row 2
Gender - Male
Body Type - Feminine
Row 3
Gender - Female
Body Type - Masculine
Row 4
Gender - Male
Body Type - Masculine
On image, spawned 36 slimes with various combinations of settings. Also tested humans and IPCs. All get the correct body type to the setting.
<hr>
<hr>
:cl:
fix: …
=> [Fix] Body type isn't random anymore.

.github/workflows/ci.yml, tools/ci/check_map_sizes.py
This PR refactors the map size check CI. The current check looked up map size by running nanomap-renderer with special args to print out map metadata, requiring looking up the system platform to run the right windows/linux executable, parsing STDOUT, etc. I don't know if this is necessarily faster but it's much less complicated and much more in line with the expected style and output of the rest of our CI checks.
Less complicated Python scripts.
sample run:
<hr>
<hr>
NPFC
=> refactor map size CI

tools/ci/lints.dm
Some dweeb (https://github.com/ParadiseSS13/Paradise/pull/26729) didn't bother to read the documentation when they went and changed a bunch of pragmas willy-nilly. So Paradise hasn't compiled in OD for months unless you pass `--suppress-unimplemented` which is why CI still works.
=> Fixes OpenDream not compiling outside of CI

config/example/config.toml
This PR sets `enable_ruins` to true in the example config.
Ruins are good
Visual inspection
<hr>
<hr>
:cl:
fix: Ruins should properly spawn in production
/:cl:
=> fix default value of enable_ruins in example config

_maps/map_files/stations/deltastation.dmm
Adds a missing mining access helper to the airlock below the Delta cargo ORM.
Miners should have access to the mining bay without going through maintenance.
Spawned as miner. Used the door.
<hr>
<hr>
:cl:
fix: Miners can access the door under the Delta cargo ORM.
/:cl:
=> Adds a Missing Mining Access Helper to an Airlock on Delta Station

_maps/map_files/stations/emeraldstation.dmm
Makes it so the shutters will close when you push the respective button
Shutters working are good
"NO I DON'T HAVE NIGHT VISION MESONS, BRING ME THE JETPACK"
Booted server, pushed button, shutters closed, pushed button, shutters opened
<hr>
<hr>
:cl:
fix: Fixed the RnD shutter button on Diagoras
/:cl:
=> Syncs the Button and RnD Shutters on Emeraldstation

_maps/map_files/stations/boxstation.dmm, _maps/map_files/stations/emeraldstation.dmm, _maps/map_files/stations/metastation.dmm
This PR removes the mining station camera console from where it remained in all station HOP offices. It also removes a flash from the Metastation HOP office since the HOP's flash spawns in the locker already.
These are remnants from before command QM, HOP doesn't need these anymore.
See MDB.
<hr>
:cl:
del: The mining station camera console has been removed from the HOP Office on Cyberiad, Diagoras, and Cerebron..
/:cl:
=> Remove mining station camera console from HOP offices

code/controllers/subsystem/non_firing/SSmapping.dm
This PR fixes it so that leaving a space sector doesn't accidentally transit you to Lavaland.
Twisting the fabric of reality bad.
Thinkin bout the code real hard.
<hr>
<hr>
:cl:
fix: Space levels are properly isolated from Lavaland and cannot teleport you there.
/:cl:
=> fix space sectors leading to lavaland

code/game/objects/items/weapons/storage/firstaid.dm, code/game/objects/items/weapons/storage/storage_base.dm
After numerous complaints about irresponsible crewmembers getting access to medication, it is time to make the medbay's inventory safer. Adds child-proof caps to pill bottles and lids to patch packs.
THINK OF THE ~~CLOWNS~~ CHILDREN! 
Spawned a pill bottle, and tried to get the candies inside. Also tried other storage. 10/10, would curse those safety advocates.
<hr>
<hr>
:cl:
fix: Pill bottles now are child-friendly
/:cl:
=> [AFD] Child-proofed pill bottles and patch packs

code/game/gamemodes/changeling/changeling.dm, code/game/gamemodes/dynamic/antag_rulesets.dm, code/game/gamemodes/traitor/traitor.dm, code/game/gamemodes/trifecta/trifecta.dm, code/game/gamemodes/vampire/traitor_vamp.dm, code/game/gamemodes/vampire/vampire_chan.dm, code/game/gamemodes/vampire/vampire_gamemode.dm
This PR removes all command, procedure, dignitary, and mindshielded roles from the default antag restriction lists. I know there's a config option to do this for dynamic but a non-config PR is easier to deal with for the purposes of AFD.
If this game's about paranoia it's time to stop being such little bitches about it
<hr>
<hr>
:cl:
tweak: All standard on-station roles may now roll antag.
/:cl:
=> [AFD] remove mindshield restriction from antags

code/controllers/subsystem/non_firing/SSlate_mapping.dm, code/modules/mob/living/carbon/human/human_mob.dm
Makes it so monkeys have a chance to turn into gorillas. Mapload gorillas can't be rampaging, and their step is separate from the monkey init just so pets don't wind up runtiming. We might be returning to monke, but that doesn't mean I'm banging rocks together here, gotta keep it clean.
Started an instance and looked around for gorillas, then started spawning monkeys.
<hr>
<hr>
:cl:
fix: It's time for the apes to reclaim the station
/:cl:
=> [AFD] Planet of the Apes

code/game/machinery/doors/airlock.dm
Airlocks will now sound more unique.
Good? I am not sure about that. It is mildly funny though.
Walked through some airlocks.
<hr>
<hr>
:cl:
tweak: Tweaked airlock sounds to use a pool of sounds at random.
/:cl:
=> [AFD] What's that sound?

code/datums/browser.dm
Fixes some runtimes that can sometimes occur when trying to open certain UIs.
Bugs are bad, and this one's bugging the usage of some useful verbs.
Ran one of the verbs that didn't show a browser window before (msays), it works now
<hr>
<hr>
:cl:
fix: Some verbs that displayed browser UIs (the old grey-with-blue-buttons) should now work more consistently.
/:cl:
=> hopefully fix users-as-clients runtiming browser UIs

code/game/objects/items/weapons/grenades/ghettobomb.dm
Adds an admin message to the improvised firebomb.
Provides better visibility to admins on events during a round.
Threw multiple firebombs
Checked for proper message to be displayed.
<hr>
<hr>
NPFC
=> Adds admin message for improvised firebomb

code/game/objects/structures/crates_lockers/crates.dm
Says to the code that crates have no animated doors and forces it to use `update_icon` in a different way.
Bug fix.
Before
After
Above, loaded up 1 ruin with opened crate inside, changes applied properly.
<hr>
<hr>
:cl:
fix: Opened on roundstart crates now have a proper icon.
/:cl:
=> Fixes wrong `icon_state` of opened crates on initialize

code/modules/clothing/clothing.dm, code/modules/crafting/smithed_items.dm
Fixes an issue with mobility inserts.
Bugs bad.
Tested fix repeatedly. Issue did not reoccur.
<hr>
<hr>
:cl:
fix: Fixed a bug with mobility meshes
/:cl:
=> [s] Fixes Mobility Mesh Bug

code/game/machinery/pipe/pipe_construction.dm
fixes #28740 
fixes #28206
less bug more good
- unwrenched pumps that are on by default and flipped filters
<hr>
<hr>
:cl:
fix: Certain pipe types no longer look wrong when unwrenched
/:cl:
=> Fixes certain atmos devices appearing wrong when unwrenched

code/game/objects/items.dm, code/game/objects/items/weapons/batons.dm, code/game/objects/items/weapons/storage/bible.dm, code/modules/antagonists/vampire/vamp_datum.dm, code/modules/mob/living/carbon/human/species/_species.dm, code/modules/mob/living/living.dm, code/modules/mob/living/living_defense.dm, code/modules/mob/mob.dm, code/modules/mob/mob_grab.dm, code/modules/mob/mob_vars.dm, code/modules/recycling/disposal.dm, code/modules/research/xenobiology/xenobio_camera.dm
This PR removes the variable `/mob/var/LAssailant`, which, since #22790, is only set and never read anywhere.
Dead code bad.
Compiled.
<hr>
<hr>
NPFC
=> refactor: remove unused var /mob/var/LAssailant

code/_globalvars/lists/maint_loot_tables.dm, code/game/objects/effects/spawners/random/engineering_spawners.dm
This PR adds common engineering electronics to the maintenance loot tables, specifically
- airlock electronics
- firelock electronics
- firealarm electronics
- apc electronics
- air alarm electronics
- and camera assemblies.
They have a 1% chance in the 66% chance loot tier of the tier 0 table, so reasonably rare. They won't start flooding maints.
More variety in maint loot table, more emergent scenarios if one of these is needed in a pinch. It honestly feels like an oversight these weren't included because of the amount of other shit like stock parts, tools, and materials.
<hr>
<hr>
:cl:
add: Common engineering electronics may now be found in maintenance loot spawners.
/:cl:
=> add miscellanous engineering boards to maint loots table

code/modules/cooking/recipes/oven_recipes.dm, code/modules/cooking/steps/recipe_step_add_produce.dm
This PR fixes a recipe collision between pumpkin and blumpkin pies by specifying exact types for the input ingredients. Also fixes a bug in the add_produce recipe step for exact paths. Fixes #28864.
We don't want recipes with the same inputs resulting in two different possible outputs.
Confirmed both recipes worked with expected ingredients and no debug errors.
<hr>
<hr>
:cl:
fix: Pumpkin and blumpkin pie recipes work properly.
/:cl:
=> fix pumpkin/blumpkin pie recipe collision

code/modules/mob/living/simple_animal/bot/mulebot.dm
Removes a useless `CanPass` check that would never pass (heh) from MULE's `unload` proc, and replaces it with a proper `Move` check. Now MULEbots will follow the nav beacon's `dir` variable to know where to correctly unload their crates.
Returns functionality that may have been broken with one of the "recent" movement refactors. Crates being dropped under flaps makes them near-invisible unless you know it happens. Not only that, but a crate right on top of a navigational beacon would become a pathing obstacle for any subsecuent MULE deliveries until removed.
- Loaded a MULEbot with a crate, sent it on its merry way
- Observed how the crate would be unloaded at the correct destination point, as determined by the nav beacon
- Tried again with the destination point blocked by a crate and a …
=> Fixes MULEbots not unloading crates according nav beacon's `dir`

code/modules/research/xenobiology/xenobio_camera.dm
Fixes #28627 
de-legacyfies the action procs
can apply potions again
Tested ingame, action and keybind.
<hr>
<hr>
:cl:
fix: Xenobio camera can apply potions again.
/:cl:
=> Fixes xenobio camera actions

code/__HELPERS/atom_helpers.dm, code/game/atoms.dm, code/modules/atmospherics/machinery/portable/canister.dm
This PR adds an investigate log for broken canisters, including the last attacker and weapon if known.
Improve admin powers.
<hr>
NPFC
=> Add investigate log for broken canisters

code/__DEFINES/lighting_defines.dm, code/game/objects/items/devices/flashlight.dm, code/modules/mob/living/simple_animal/hostile/mining/elites/legionnaire.dm
Tweaks define for a `LIGHT_COLOR_RED` making it a bit more saturated with red color.
Changes red glowstick's color back to `LIGHT_COLOR_RED` as `PURE_RED` is too dark actually.
Changes legionnaire bonfire's lighting color from `LIGHT_COLOR_RED` to `LIGHT_COLOR_FLARE`.
Current red color is just nowhere as saturated as any other, like green, blue, pink, yellow, orange and so on. This PR makes it a bit more noticable that your lighting has a red color.
https://discord.com/channels/145533722026967040/1355900526683750636
<hr>
<hr>
:cl:
tweak: Red color used by some lighting devices (cult pylon, esword, glowcap, glowstick etc.) is now a bit more saturated.
tweak: Legionnaire's bonfire now has more saturated lighting color.
/:cl:
=> Makes red lighting color more red

_maps/map_files/stations/boxstation.dmm, _maps/map_files/stations/cerestation.dmm, _maps/map_files/stations/deltastation.dmm, _maps/map_files/stations/emeraldstation.dmm, _maps/map_files/stations/metastation.dmm, code/game/objects/structures/engicart.dm
- Migrates the Engineering Cart to the new attack chain.
- Cleans up the cart's code to be nice and shiny.
- Allows cyborgs to wrench/unwrench the cart.
- Makes a new pre-filled version of the cart.
- Adds the pre-filled cart to all stations.
Ancient object with code not touched since the beginning of time getting updated is good.
Showing off the surprising amount of stuff this thing can carry with its pre-equipped variant may encourage more usage, as with the pre-equipped janitorial cart.
Delta
Meta
Cere
Emerald and Delta already have a cart, it has just been filled up.
Placed items into and removed from cart and added back in.
Transferred items to different cart.
Tried to add duplicate items to cart.
Wrenched cart as human and borg.
<hr>
<hr>
:cl:
tweak: Engineering's engi cart now …
=> Migrates Engi Cart to the New Attack Chain - Cleans up Engi Cart Code - Makes Pre-Filled Engi Cart Variant and Adds it to All Stations

tools/ci/check_wallbump_collisions.py
This PR adds a Python script that checks maps for colliding wallbumps. This can't be done in a maplint because the checks need to be performed under very specific conditions, including:
- checking for wallbumps when there are airlocks but not counting airlocks and firelocks colliding as a false positive
- ensuring that two wallbumps on the same tile but facing different directions don't count as a false positive
- dumb bullshit regarding accurate positioning of cameras
- including pixel_x/pixel_y in determination of apparent wallbump location even if there isn't a varedit for them
It's not enabled as a CI check just yet because there are currently hundreds failures across our maps.
It can be run locally via `.\tools\bootstrap\python_.ps1 -m ci.check_wallbump_collisions` in a Powershell at …
=> add dormant CI check for wallbump collisions

code/game/turfs/simulated/floor/chasm.dm, code/modules/mining/equipment/wormhole_jaunter.dm
This PR adds a signal to chasm turfs letting them know when atoms are initialized on them, and calling their standard drop behavior on those atoms when that occurs. This means that e.g. in the case of legions falling into chasms, the bodies and cores they drop will also get chasmed properly. It's a little goofy visually, the legion falls, then the body spawns, then the body falls, but 99.9% of the time the legion is already dead when players stumble across it. This is a minimally invasive solution; really we should probably use something like /tg/'s chasm component, but this is a lightweight fix in comparison.
Seeing a body on the ground when it's actually a chasm is deceptive and not really fair to players if they walk into the chasm thinking it's solid ground.
Spawned althland …
=> ensure atoms spawned over chasms fall when appropriate

_maps/map_files/stations/boxstation.dmm, _maps/map_files/stations/cerestation.dmm, _maps/map_files/stations/deltastation.dmm, _maps/map_files/stations/emeraldstation.dmm, _maps/map_files/stations/metastation.dmm
In stations where it was not already the case, medbay spare power cells have been changed from basic to high capacity.
In stations where it was not already the case, there is now a screwdriver present at the charger to allow for quick cell swapping of defibrillators.
Adds an extra recharger to Delta, as it was lacking one.
Equipment consistency across stations is good.
Basic cells are awful and not what the defibrillator uses, so these cells do not get used.
Inclusion of screwdrivers makes sense and ensures the cells are actually usable for their intended purpose.
Single representative sample (Cyberiad)
New charger on Delta
<hr>
<hr>
:cl:
tweak: All medbay spare power cells are now high-capacity. A screwdriver is included at each recharger.
add: Delta Station medical …
=> Medbay Spare Power Cells Now Unified as High Capacity With Complimentary Screwdriver

code/modules/atmospherics/machinery/atmospherics.dm
This PR fixes atmos machines like pipes, vents and scrubbers not updating their appearance properly when they are rotated as a result of a shuttle move.
Visual bugfix.
Created whiteship dock facing East, called ship, ensured airlock atmos machines had the correct appearance.
:cl:
fix: Atmos machines now properly update their appearance when the shuttle they are on moves.
/:cl:
=> fix atmos machines not updating appearance on shuttle rotate

code/game/objects/items/weapons/cards_ids.dm, code/modules/mob/living/simple_animal/corpse.dm
Creates a new ID type, `/obj/item/card/id/syndicate_fake`. It has no access or any of the other abilities of an agent ID and is purely cosmetic.
This new ID replaces the generic no-access ID found on syndicate mobs.
Theming and drip. Plus, if they're going to be so psyched up about being in the Syndicate that they scream about it every 6 seconds, you can bet your ass they'll proudly display their affiliation on a membership card.
Spawned in some syndicate mobs, looted them, they had evil-looking IDs.
<hr>
<hr>
:cl:
tweak: Syndicate mobs now drop syndicate-styled IDs instead of generic IDs. They have no new access or abilities.
/:cl:
=> Syndicate Mobs With IDs Now Have Syndicate-Themed IDs.

code/modules/buildmode/submodes/atmos.dm
Adjusts buildmode tgui input for atmos
Prevents accidents and turns off rounding, allowing for floats.
TBC
<hr>
<hr>
NPFC
=> Adjusts input for atmos buildmode

code/game/gamemodes/miniantags/revenant/revenant_abilities.dm
Defile can no longer spawn heretic rust under AI cores.
Revenant having an ability that can easily kill the AI is bad.
Spawned as revenant. Could not rust the AI's plating.
<hr>
<hr>
:cl:
fix: Fixed an oversight that let revenant rust murder AI's deader.
/:cl:
=> Fixes Revenant defile and AI cores

code/__DEFINES/mod.dm, code/modules/mod/mod_control.dm, code/modules/mod/mod_paint.dm, code/modules/mod/mod_theme.dm
Moves proc that makes mod spaceproof to a different place as well as making it easier to add new modifiers that depend on a skin.
Fixes #27165
It's a fix
Spawned in mod, it had cold protection. Spawned in a regular mining mod and applied a new skin - it applied cold protection as well.
<hr>
<hr>
:cl:
fix: Mining modsuits with asteroid skin from space ruins are now actually spaceproof.
/:cl:
=> Fixes roundstart asteroid mining mods not being spaceproof

code/controllers/subsystem/non_firing/SSlate_mapping.dm, code/modules/shuttle/dock_generator.dm, code/modules/shuttle/shuttle.dm
This PR makes several changes to the whiteship signaller:
- The number of docks that can be created on a sector is increased from 1 to 3.
- The number of docks that can be created, total, is increased from 3 to 6.
- Alt-clicking on the signaller opens a shuttle console interface, allowing the holder to move the shuttle to any dock remotely.
A tiny refactor was made to move shuttle consoles checking for docking ports on late init to SSlate_mapping, because doing it on late init is pointless because SSshuttles isn't initialized until much later in the init order. This was necessary in order to allow the signaller to look up available connections from the shuttle console without having to use the shuttle console at least once, first.
As part of the discussion on #28883 I mentioned that …
=> more whiteship signaller features

code/modules/cooking/recipes/cutting_board_recipes.dm
This PR adds the slime jellied toast recipe to the cutting board. This must have gotten lost during the automated conversion of recipes from the old to the new system.
Fixes regression.
Confirmed recipe worked.
:cl:
fix: Slime jelly toast, which was accidentally removed as a recipe, can be made again.
/:cl:
=> readds slime jelly toast recipe to new system

code/modules/cooking/recipes/oven_recipes.dm, code/modules/cooking/recipes/stove_recipes.dm
This PR makes nettle soup use the correct recipe step type for nettle, because it counts as an item, not produce. Fixes #28904.
Bugfix.
Verified nettle soup could be made with recipe as described.
:cl:
fix: Nettle soup can properly be made by following its recipe.
fix: Moffins can properly be made by following their recipe.
/:cl:
=> fix broken nettle soup recipe

code/modules/cooking/cooking_container.dm
This PR fixes cooking containers causing premature reagent reactions, as in the case of the recipe for chocolate bars containing the same reagents as the chemical reaction for chocolate bars. Fixes #28903. This doesn't fix the problem of recipes transferring excess reagents to finished products, which, in the case of extra milk in the container, would cause a reaction making another chocolate bar on top of the ice cream mixer, but that's a whole other thing.
Bugfix. Was setting the noreact flag on the wrong thing.
Performed recipe, ensured reagents didn't react.
:cl:
fix: Cooking containers will properly prevent chemical reactions of ingredients when following a recipe.
/:cl:
=> fixes cooking containers causing premature reagent reaction

code/modules/mob/living/living.dm
This PR fixes AI controllers not activating when a client enters their z-level. Luckily the only thing this affected was cows.
AI controllers should run when players are present.
Spawned in round, checked Betsy's AI controller, ensured it was on. Ensured other simple mobs weren't affected.
:cl:
fix: Cows should properly wander around like other animals again.
/:cl:
=> fix ai controllers ignoring client presence on z-level

_maps/map_files/RandomRuins/SpaceRuins/whiteship.dmm, code/game/objects/effects/spawners/random/misc_spawners.dm, code/game/objects/effects/spawners/random/pool/misc_pools.dm, code/game/objects/effects/spawners/random/pool/spawn_pool.dm, paradise.dme
This PR creates a mini spawn pool for the whiteship pirates, giving them two guaranteed spawns; one melee pirate and one with a 50/50 chance of either a ranged or melee pirate, and placing spawners throughout the ship.
The existing placement of the pirates makes it easy to get rid of them. This varies things up a bit.
The spawns:
Some example results:
See above.
:cl:
tweak: The two pirates on the explorer ship may either be gunners or swordsmen, and may spawn in any of the ship's rooms.
/:cl:
=> randomizes whiteship pirate placement

_maps/map_files/stations/boxstation.dmm
Changes the name of the first camera in the Cyberiad aft primary hallway from "Virology Lobby" to "Aft Primary Hallway 1"
Incorrectly named cameras are bad.
<hr>
<hr>
:cl:
fix: Fixed a camera in the engineering hallway of Cyberiad being named "Virology Lobby"
/:cl:
=> Fixes an Incorrectly Named Camera

code/modules/cooking/recipes/midway_recipes.dm, code/modules/food_and_drinks/food_base.dm, code/modules/reagents/chemistry/recipes/slime_extracts.dm
This PR adds a custom recipe to the deep fryer, re-enabling the ability to deep-fry any food item. It removes the old unnecessary `/obj/item/food/deepfryholder` object. Note this doesn't add the emagged ability back yet.
Brings back functionality that was temporarily missing after the kitchen rework.
:cl:
fix: The ability of the deep fryer to deep fry any food item has been added.
/:cl:
=> readds deep-fryer recipe for any food

code/game/objects/effects/spawners/random/decal_spawners.dm, code/game/objects/effects/spawners/random/engineering_spawners.dm, code/game/objects/effects/spawners/random/food_spawners.dm, code/game/objects/effects/spawners/random/furniture_spawners.dm, code/game/objects/effects/spawners/random/loot_spawners.dm, code/game/objects/effects/spawners/random/misc_spawners.dm, code/game/objects/effects/spawners/random/outfit_spawners.dm, code/game/objects/effects/spawners/random/pool/misc_pools.dm, code/game/objects/effects/spawners/random/pool/pool_spawner.dm, code/game/objects/effects/spawners/random/pool/space_loot.dm, code/game/objects/effects/spawners/random/random_spawner.dm, code/game/objects/effects/spawners/random/toy_spawners.dm, code/game/objects/effects/spawners/random/traders/trader_department_spawners.dm, code/game/objects/effects/spawners/random/trash_spawners.dm
This PR removes some redundant icon declarations on random spawners.
For a while these were split between random_spawners.dmi and spawner_icons.dmi. Now everything's in the right place.
CI should say if there's any invalid icon states.
NPFC
=> remove redundant spawner icon decls

_maps/map_files/stations/boxstation.dmm
This PR adds a microwave back to Box perma. Fixes #28922. I double checked all other station permas have microwaves.
I goofed up and forgot there's donks in perma.
Check MDB.
:cl:
fix: Cyberiad perma has the expected microwave as all permas.
/:cl:
=> add microwave back to box perma

code/modules/projectiles/guns/energy/energy.dm
Makes it no longer possible to dual wield eshotguns without the badass trait.
Balance.
Tried to dual wield eshotguns. Could not.
<hr>
<hr>
:cl:
fix: Fixes eshotgun dual-wield oversight
/:cl:
=> [s] Fixes eshotgun dual-wield

code/modules/smithing/smithed_items/inserts.dm
Fixes insert slowdown values being too low to actually matter. Slowdown factors don't matter below 1, so now minor slowdown inserts have a 1 slowdown and major has a 1.5. 
Balance.
Inserted masterwork heavy insert into suit. Was slowed down.
<hr>
<hr>
:cl:
fix Fixed smith insert slowdown values being too small to actually matter.
/:cl:
=> [s] Smith insert slowdown fix

_maps/map_files/templates/shelter_1.dmm, _maps/map_files/templates/shelter_2.dmm, code/modules/mining/equipment/survival_pod.dm
changes the vender in the emergency standard shelter to include 1 stack of splints 1 stack of gauze 1 stack of ointment 1 charcoal syringe 2 and epipens.
Also changes the luxury vender to a normal station nanomed 
also adds "emergency" to the name of the standard shelters vender 
The nano med that the survival pods have currently are hilariously useless, as you rarely ever need splints, since legion cores, and it lacks anything else
This changes that so over healing 0
you can heal a maximum of 60 brute/burn with 15u of charcoal
Plus the weak donks i the shelter storage, however they heal such a low amount you're unlikely to get any good use out of them in an emergency
Point being, its an emergency shelter, that lacks proper medical supplies. It just doesn't make sense to me why a shelter …
=> Adds basic healing supplies to the nanomed in stardard shelters, and givesthe luxury shelter a standard nanomed 

code/modules/smithing/machinery/casting_basin.dm, code/modules/smithing/machinery/power_hammer.dm
Fixes how some sounds play that were being varied unintentionally.
Audio bugs bad
Ran basin and hammer. Sounds fixed.
<hr>
<hr>
:cl:
fix: Fixed smith machine sounds unintentionally varying.
/:cl:
=> Smith Polish - sound fixes

code/game/gamemodes/nuclear/pinpointer.dm
This PR fixes vetus pinpointers not correctly showing the direction of nearest tendrils. Fixes #28965.
Bugfix.
Spawned in multisector lavaland, spawned pinpointer, activated, verified we got arrows.
:cl:
fix: The vetus pinpointer will properly target tendrils in your sector.
/:cl:
=> fixes vetus pinpointer tendril targeting

code/game/mecha/equipment/tools/medical_tools.dm, code/game/mecha/equipment/tools/work_tools.dm, code/game/mecha/mecha_parts.dm
This PR refactors all mech parts to use /Initialize instead of /New.
See #27261.
NPFC
=> /New -> /Initialize Migration §3: Mech parts.

_maps/map_files/stations/cerestation.dmm
Installs windows into the external and shuttle airlocks of the Farragus docking asteroid.
Replaces lock varedits with lock helpers.
Uses autoname helpers on arrival shuttle external airlocks.
Improves the view. Using helpers over varedits is good.
<hr>
<hr>
:cl:
tweak: Farragus docking asteroid airlocks now have windows.
/:cl:
=> Installs Glass into Farragus Docking Airlocks

_maps/map_files/stations/emeraldstation.dmm
Adds windows to the Emerald departures airlocks.
Replaces lock varedits with lock helpers.
Good view. Varedit bad.
<hr>
<hr>
:cl:
tweak: Emerald departures airlocks now have windows.
/:cl:
=> Installs Glass into Emerald Departures Airlocks

_maps/map_files/stations/emeraldstation.dmm
Installs windows into Emerald external and shuttle airlocks. The pod's airlock remains opaque.
Changed lock varedits to lock helpers.
Shuttle external airlocks now use autoname helpers.
Good view. Helpers > varedits.
<hr>
<hr>
:cl:
tweak: Emerald Arrivals airlocks now have windows.
/:cl:
=> Installs Glass into Emerald Arrivals Airlocks

_maps/map_files/stations/metastation.dmm
Installs windows into Meta arrivals external and shuttle airlocks.
Changes locked varedits into lock helpers.
Arrivals airlocks now use autoname helpers.
Improved view. Using helpers instead of varedits is good.
<hr>
<hr>
:cl:
tweak: Arrivals airlocks on Meta now have windows.
/:cl:
=> Installs Glass into Meta Arrivals Airlocks

_maps/map_files/stations/boxstation.dmm
Installs windows into the external and shuttle airlocks of Cyberiad arrivals. The pods' airlocks remain opaque.
Replaces varedited locks with lock helpers.
Shuttle external airlocks now use autoname helpers.
Windows improve the view.
Replacing varedits with mapping helpers is good.
<hr>
<hr>
:cl:
tweak: Cyberiad arrivals airlocks now have windows.
/:cl:
=> Installs Glass into Cyberiad Arrivals Airlocks

_maps/map_files/stations/deltastation.dmm
Installs windows into the escape airlocks at Delta Departures.
Replaces locked door varedits with lock helpers.
Improves the view, removes varedits and replaces them with helpers that can easily be seen when mapping.
<hr>
<hr>
:cl:
tweak: Delta departures escape airlocks now have windows.
/:cl:
=> Installs Glass into Delta Departures Airlocks

_maps/map_files/stations/deltastation.dmm
Converts the external airlocks and shuttle airlocks at Delta Arrivals to glass versions. The airlock on both pods remains opaque.
Locked airlocks now use lock helpers instead of var edits.
Windows give a nice good view!
Varedits are stinky, glorious airlock lock helpers let mappers easily see at a glance what airlocks are locked.
Locked airlocks now look like this
<hr>
<hr>
:cl:
tweak: Windows have been installed on Delta arrivals airlocks.
/:cl:
=> Installs Glass Into Delta Arrivals Airlocks

rust/src/rustlibs_dmi/mod.rs
My attempt to be crafty and devious when porting the rust-g dmi fell flat when I fucked up the port and didn't test the changes properly. This is now a line for line port of the whole module like it should have been.
Makes job icons work again.
Read, wrote, and stripped some dmi files. Examined their contents with exiftool and imhex. Confirmed that they remained valid. Compiled and passed in-game unit tests.
<hr>
<hr>
=> Fixes rustlibs dmi module

code/modules/mob/living/silicon/ai/ai_programs.dm
Improves the blackboxing for AI programs.
Duplicate blackboxes are bad. We should also probably blackbox which ones are upgraded.
Compiled.
<hr>
<hr>
NPFC
=> Better AI Program Blackboxing

code/game/turfs/turf.dm
fixed #28966 by calling parent if Z level transition fails when a ghost attacks a turf
bug fix
- Atmos scanned tiles as ghost
- Transitioned between Z levels as ghost
<hr>
<hr>
:cl:
fix: Fixes ghost atmos scan on tiles
/:cl:
=> Makes ghost gas scan work again

code/_onclick/item_attack.dm
Forces item's `attack()` proc to respect target's active parry/shieldings. If target has some of them, the attack will be stopped - no further effects, only shielding/parry reaction.
No one wants to code unique checks for target's shield for every single item in game.
Tested with upcoming chainsaws, stunbaton. No issues noticed, it's working in a proper way.
<hr>
<hr>
NPFC
=> Attack chain migration slight improvement

code/modules/smithing/machinery/kinetic_assembler.dm
Lenses and Bits have durability. You also need a set of them to outfit a toolbelt's worth of tools or an armory's worth of eguns. This PR makes it so that lenses and bits are crafted as a set of 3, to provide replacements to broken ones as well as for better outfitting.
Makes Smith gameplay smoother. 
Smithed a masterwork balanced bit. Got 3 when it was completed.
<hr>
<hr>
:cl:
tweak: Lenses and Tool Bits are now crafted in batches of 3
/:cl:
=> Smith Polish: Lens and Bit Batch Crafting

code/modules/lavaland/caves_theme.dm
This PR fixes tendrils spawning in oases, accidentally caused by #28968.
Miners should be able to get to tendrils.
Ran several deeprock rounds, ensured tendrils didn't spawn in center of oases.
:cl:
fix: Lavaland tendrils should no longer spawn in the middle of deeprock lakes.
/:cl:
=> fix tendrils spawning in deeprock oases

code/__HELPERS/unsorted.dm
This PR ensures that basic mobs are visible in the Orbit menu.
Orbit menu should be exhaustive.
:cl:
fix: Mobs using the new AI controllers should probably appear in the Orbit menu.
/:cl:
=> add basic mobs to orbit menu

code/game/objects/effects/alien_acid.dm, code/modules/mob/living/carbon/carbon_procs.dm, code/modules/mob/living/carbon/human/human_defense.dm, code/modules/mob/living/living.dm, code/modules/reagents/chemistry/reagents/toxins.dm
"The acid burns you!" message and its sound now appear only when you are actually getting damage from it.
Stops your mask from getting melted if your helmet is `ACID_PROOF`.
Allows you to use breathing tube implant without a gas mask, but with a helmet that has `BLOCK_GAS_SMOKE_EFFECT` to prevent breathing in gases.
It's good when your helmet is actually acid proof. It prevents, for example, cases when a nukie is getting hit by a facid grenade, it melts his gas mask through an `ACID_PROOF` helmet and he is getting one hundred and fourty units of acid which will slowly kill him.
Also i believe that `can_breathe_gas` didn't take into account breathing tube implant which is not being a mask-slot item, but still allows to breath through internals. So you may now, for example, wear a magnate …
=> Fixes some acid procs

_maps/map_files/stations/cerestation.dmm
Adds missing air alarm.
Moves hydroponics trays around to unblock a table.
Moves some wallbumps around so there's zero conflict.
Accessible tables are good.
No wallbump conflicts are good.
Having an air alarm is good.
<hr>
<hr>
:cl:
tweak: Rearranged Farragus Hydroponics trays, newscaster, intercom, and requests console.
fix: Added missing air alarm to Farragus Hydroponics.
/:cl:
=> Adds Missing Air Alarm to Farragus Hydroponics, Minor Furniture Rearrangement.

code/game/turfs/simulated/floor/asteroid_floors.dm
This PR adds item types dug up from rock floors, such as volcanic ash, to the `ore_mined` blackbox feedback.
We should be tracking how much ash is mined alongside all the other materials found on Lavaland.
NPFC
=> add a blackbox for rock floors dug into ore_mined feedback

code/game/dna/mutations/monkey_mutation.dm, code/modules/mob/living/carbon/human/species/_species.dm
Stops items that are inside a mob's bodyparts from getting deleted when it changes species. 
- cybernetic implants drop on the floor
- cavity implanted items and other contents are transferred 
- If the analogue of the original organ is missing the relevant items will get dropped
Species change shouldn't delete random items
- Implanted stuff in and changed species on a bunch of people and monkeys. Used CMA, mutadone and changeling ability
<hr>
<hr>
:cl:
tweak: cybernetic implants now drop on species change
fix: items inside a mob no longer get deleted on species change
/:cl:
=> Implants, implanted items and other bodypart contents no longer get deleted on species change

code/__DEFINES/radiation_defines.dm, code/datums/radiation_wave.dm
Removes exponential decay of radiation waves past a certain distance.
In the utter majority of situations players won't know the difference, but for things like the singulo that can move about in a big enclosure it can make for some inconsistencies.
Extremely powerful SM setups in the millions of EER can now potentially leak a small amount of radiation into other areas.
This was intended purely as a performance feature, but the loss of performance I observed before adding it was a result of my testing rather than rad waves being too slow. upon retesting, there doesn't seem to be any TIDI even with something impossible like a 100,000,000,000 EER engine that irradiates the entire station.
- Ran the server separately through dream daemon this time
- Var edited the SM to 100,000,000,000 EER …
=> Remove exponential rad wave decay

code/game/objects/structures/mirror.dm, code/game/turfs/simulated/floor/chasm.dm, code/modules/ruins/lavalandruin_code/sin_ruins.dm
There is no more dumb z lvl check, instead, whenever you try to use mirror not being next to it - you will get cursed.
Changes span class from tiny `danger` to `colossus`, making it more visible and stylish.
Fixed unintended double `drop()`, removed unused code.
Unused code is useless. This z lvl check also caused the mirror to fuck up the whole idea on downstream, because its Lavaland is located on lvl 4, not 3. Also you are now able to put this mirror anywhere, not only Lavaland. The mirror should be only located to the north of player, tho.
Tested everything i changed. It's working properly.
<hr>
<hr>
:cl:
tweak: You can't fool pride mirror's anymore.
tweak: Message for trying to fool a pride mirror is now more noticable.
/:cl:
=> Updates pride mirror's code

code/modules/mob/living/carbon/human/human_update_icons.dm
fixes #28894
Returns an overlay insert that got missed in the slime imitation revert
bug bad
https://github.com/user-attachments/assets/60d052fe-3f0d-482e-9767-1d475cb7b5da
Looked at wagging vulps, wagging tajarans, wagging vox in multiple directions. All retained their tails.
<hr>
<hr>
:cl:
fix: Wagging tails are visible again when facing north.
/:cl:
=> Fixes missing tail wag sprites when facing north

.github/workflows/ci.yml, code/__HELPERS/debugger.dm
Adds a new global var, `debugger_enabled`, for specific behaviour when the debugger is plugged in.
This var existing is gated behind the `PARADISE_PRODUCTION_HARDWARE` define **NOT** being set. Why? Because one of the primary uses for this would be tweaking MC logic to not delay SS runs after long debugger pauses, and I don't want ANY extra overhead in the MC tick loop.
Said MC changes are not in this PR, as I am not smart enough to do them anymore.
Dev-assists are always fun
N/A
Tried building with and without the prod define, compiled just fine. If someone could test this with the debugger that would be real nice.
<hr>
<hr>
NPFC
=> Adds hooks for debugger specific behaviour

code/modules/smithing/smithed_items/lens.dm
Fixes how fire rate modifications are applied to energy weapons and automatic energy weapons to better apply their effects.
Lenses should do as advertised.
Created masterwork rapid lens. Put it in disabler smg. Observed dakka.
<hr>
<hr>
:cl:
fix: Fixes lens fire rate modifier application
/:cl:
=> Smith Polish: Fixes lens fire rate modifications

code/datums/components/two_handed.dm, code/game/objects/items/weapons/twohanded.dm
Changes the way two handed component uses its `attacksound`. Now it applies a new attack sound for when item is wielded and goes back to default when it's not. Sound's volume is also now in line with any other's item now
Usually, when item has no `hitsound`, it gets one on `New()`. But `initial(hit_sound)` returns `null` in this case, so hit sounds for two handed items should be set manually. 
Currently not a single item is using this, but with this PR dsword will become the first one. I just don't know if there is any other that needs this, tho.
Well, at this moment no one uses this var, but we can use it for dswords and upcoming refactored chainsaws. 
Tested with dswords, chainsaws - sounds applied.
<hr>
<hr>
NPFC
=> Two handed component slight audio improvement

code/modules/mob/living/simple_animal/hostile/megafauna/megafauna.dm
Changes megafauna melee attack delay from dynamic (1-8 seconds) to static (0.25 seconds). This is only used after performing an ability (Ash drake swoops, bubblegum charges etc.)
A delay of 8 seconds resulted in Ash Drake being harmless after his swoop, and you could just stand next to him for this amount of time. He couldn't do anything except of chasing you.
This will make megafauna a little bit more "active", so they won't just do nothing and receive hit by hit from miners.
This might sound like a huge change, but it's not really. You are still able to hit fauna while they perform the ability attack, so there is not much of a change in "difficulty". It's just about megafauna being not that stupid.
The only thing i was unable to fix - Ash Drake, after his swoop, stays for around 1-2 …
=> Decrease megafauna melee attack delay after ability

code/game/gamemodes/miniantags/guardian/guardian.dm, code/modules/mob/living/living.dm
Fixes #27801. The issue ended up being only the UI remaining on the summoner when the holopara is gibbed. All other behaviour is as intended
bugfix
- Went into scout mode as a ranged holopara and went across a singularity
<hr>
<hr>
:cl:
fix: Holopara actions buttons are correctly removed from summoner on holopara gibbing
/:cl:
=> Fix holopara action buttons remaining if your holopara gets gibbed

_maps/map_files/stations/boxstation.dmm, _maps/map_files/stations/cerestation.dmm, _maps/map_files/stations/deltastation.dmm, _maps/map_files/stations/emeraldstation.dmm, _maps/map_files/stations/metastation.dmm
- Adds one extra gold bar to Cere and Delta vaults, bringing them up to 3 bars (same as Box, Meta, and Emerald).
- Replaces the coins in the silver crates with 3 silver bars (all stations).
- All vaults should have the same amount of gold.
- The silver in the silver crates is not usable as there is no way to extract the silver. The crates are supposed to be emergency fallbacks to allow RnD progression if mining fails to deliver (as noted in SOP).
Visual inspection of the vault contents.
<hr>
<hr>
:cl:
tweak: Cere and Meta vaults now contain 3 gold bars, as all other stations do.
tweak: All vaults have had their silver coins replaced with 3 silver bars.
/:cl:
=> Makes the Number of Gold Bars in Vault Equal Across all Stations. Turns Vault Silver From Coins to Bars.

code/modules/mining/minebot.dm
Makes nanotrasen minebots ash-proof, similar to hostile minebots.
Consistency and buffs a pretty weak mining purchase
I think it works
<hr>
<hr>
:cl:
tweak: Nanotrasen Minebots are now ash-proof, similar to hostile minebots
/:cl:
=> Makes minebots ash-proof

code/modules/power/cables/cable.dm
implements the now abandoned #28613 with the requested changes:
Shows ghosts cable power when they examine it. Acts the same as a multitool would.
Moves the info generation to a cable proc.
- Scanned powered/unpowered cable with multitool
- Examined powered/unpowered cable as ghost
-
<hr>
<hr>
:cl:
tweak: Shows cable power info when examined by ghosts
/:cl:
=> Show cable power when ghosts examine cable

code/modules/client/client_procs.dm
This is gonna annoy a lot of people, but needs to be done.
Not only is a 516 not compatible with 515 clients, but the split between IE-Trident and Webview is causing a lot of inconsistencies within TGUI and other things, and developing perfect support is not in our appetite given one is going to be deprecated.
We need to move on
Only shows if youre on 515
Tested on 515, saw message
Tested on 516, no message
<hr>
<hr>
add: Added a warning if you are on old BYOND
/:cl:
=> Warning if clients are still on 515

code/game/objects/structures/stool_bed_chair_nest/chairs.dm, code/modules/mob/living/living.dm
fix #29001 and #27993 by making buckled mobs not reset their direction when pushed
bugfix
<hr>
<hr>
:cl:
fix: Buckled mobs now change directions with the chair when pushed
/:cl:
=> Chair rotation fix

code/datums/mind.dm, code/game/data_huds.dm, code/modules/mob/living/carbon/examine.dm
Fixes #29013
Makes examine conditions work even if player left server being inside his dead body (not as a ghost) - it's displayed properly now
Fixes case when IPC player dies, ghost decides to fly around and his body is displayed with improper icon - gray static line instead of a blue pulsating one
Fixes and improvements are good
This time tested more with 2 differents sessions on local server. Runtime is gone; hud and examine descriptions display properly when player leaves a server or joins back
<hr>
<hr>
:cl:
fix: Dead IPCs now have a proper diagnostic HUD icon.
fix: You are now properly displayed as inactive for other players when you leave a server being located in your dead body.
/:cl:
=> Fix `check_ghost_client()` runtime + improve examine/hud conditions

code/modules/smithing/smith_datums.dm
Fixes a bad value in the material datum that let some smith inserts have no movement penalties
Balance good, Exploits bad.
Made an insert out of affected material. Verified proper movement penalty
<hr>
<hr>
:cl:
fix: Fixed a bad smith material value negating movement speed modifiers.
/:cl:
=> [s] Fixes exploit in material speed modifier

code/game/objects/items/weapons/stunbaton.dm
Makes it so you can parry stunbaton again
Also converts cooldowns to TG cooldowns
You should be able to parry it. It's been broken for a while now
Local server testing. Could parry it and deflect using gamma armory modsuit's shield
<hr>
<hr>
:cl:
fix: Fixed issue when stunbaton would always stun you on melee hit, even if you parried/had an active suit shield.
/:cl:
=> [s] Fix stunbaton ignores parry/shield

code/game/atoms_movable.dm
This PR brings back updating `l_move_time` that is used to display burn wound/broken bone messages
It was removed here https://github.com/ParadiseSS13/Paradise/pull/27698
There was no reason to remove it and PR author obiously didnt mean to remove these messages
Fixes https://github.com/ParadiseSS13/Paradise/issues/29068
Bugs bad
Compiled, got burn wound, ran around, got messages
<hr>
<hr>
:cl:
fix: Burn wounds and broken bones logic when walking is working once again.
/:cl:
=> Fixing no burn wound/broken bone messages

docs/mapping/submaps.md
This PR fixes some formatting in the docs for submaps.
Proper header hierarchy and linkability is good. Raw links are bad.
See above.
NPFC
=> fix some submaps docs formatting

_maps/map_files/stations/boxstation.dmm, _maps/map_files/stations/cerestation.dmm, _maps/map_files/stations/deltastation.dmm, _maps/map_files/stations/emeraldstation.dmm, _maps/map_files/stations/metastation.dmm, code/game/objects/effects/spawners/random/tech_storage_spawners.dm, code/modules/cooking/machines/deep_fryer.dm, code/modules/cooking/machines/grill.dm, code/modules/cooking/machines/ice_cream_mixer.dm, code/modules/cooking/machines/oven.dm, code/modules/cooking/machines/stovetop.dm
This PR adds a spawner for service circuitboards for tech storage, and updates the supply board spawner to include one of each smithing machines. It makes some minor mapping tweaks on some maps to arrange things so that there's a good spot for the new rack of boards. It also removes some pointless dir/atom varedits on the racks holding the circuit boards.
These inventories haven't been updated in a while and we have nice new spawners to make it easier to do so, so might as well flesh out the available boards.
:cl:
add: Several service-related boards from hydroponics and kitchen are now kept in tech storage.
add: Circuit boards from one of each smithing machines are now kept in tech storage alongside the other supply boards.
/:cl:
=> add smith, and some service boards, to tech storage

code/modules/smithing/machinery/casting_basin.dm, code/modules/smithing/smith_machinery.dm
This PR makes it so if you try to add an item to a smithing machine that already contains that item, it swaps them. 
Quality of Life.
Tried to place a component in a power hammer that already contained a component. The components were swapped.
<hr>
<hr>
:cl:
tweak: Smithing machines (power hammer, lava furnace, casting basin) now swap casts/components when you try to insert one while another is in the machine.
/:cl:
=> Smith Polish - Item Insertion QOL

code/game/objects/items/weapons/storage/surgical_tray.dm
Adds surgical drapes to surgical trays.
We're not banging rocks together over here. We're an advanced space station. This surgical tray has instant bone-fixing juice on it! Why can't it have a sheet of fabric for preventing infections!?
Doctors shouldn't be making improvised drapes (or more likely, not using them at all) when this is basic equipment you'd expect in any modern operating room. If we want them to stop using spaceacillin to solve all their problems, we should give them the tools they need.
Spawned a tray. Looked inside.
<hr>
<hr>
:cl:
tweak: Surgical trays now have surgical drapes.
/:cl:
=> Surgical Trays Have Surgical Drapes

code/modules/projectiles/guns/energy/stun.dm
Adds nonlethal suicide for the disabler as a little treat for security players, since it's supposed to be a non-lethal weapon and it will currently just melt you face like any other energy weapon.
Just a little extra shenanigans for one of the more high-stress jobs on the station.  Also considering the disabler is the widest availability non-lethal, it might be expected that going through certain motions would also have a non-lethal result during phases where security has too much time on their hands.
I was originally considering doing a few other non-lethal weapons, and then I got into select-fire weapons, and then the changes just got too big with too much duplicated code, so I reined it back in to just a bit of extra flavor on the vanilla disabler.
A few revs just to tweak things to …
=> Added a few non-lethal SHAME suicide paths for the disabler.

code/game/gamemodes/cult/cult_items.dm, code/game/gamemodes/cult/cult_structures.dm, code/game/gamemodes/cult/ritual.dm
Title. Updates the descriptions of various Cult items to make them more atmospheric and spooky.
Descriptions are good. Spook is good.
loaded in and read words
<hr>
<hr>
:cl:
tweak: Updates descriptions of many Cult items and structures.
/:cl:
=> Enspookifies descriptions of cult items and structures

code/datums/ores.dm, code/game/objects/items.dm, code/game/turfs/simulated/floor/asteroid_floors.dm, code/game/turfs/simulated/minerals.dm, code/modules/smithing/components/tool_bits_components.dm, code/modules/smithing/smith_datums.dm, code/modules/smithing/smithed_items/tool_bits.dm
The productivity bit is a new tool bit the smith can make. When attached to a pickaxe, drill, shovel, or sonic jackhammer, this bit will increase the amount of ore mined and sand dug significantly, depending on material and quality.
It gives the smith something more to work with miners with, promoting cooperation and enhancing tools that are often unused (pickaxes).
Added bit to drill. Drilled some sand, drilled some ore. Saw larger returns on investment.
<hr>
<hr>
:cl:
add: Added productivity bit
/:cl:
=> Smith Addition: Productivity Bit

code/modules/mod/mod_control.dm, code/modules/mod/mod_link.dm
Linkage options now do what they say when copying from a modlink to a modlink, rather than being inverted. The message is also now clearer for that linkage.
The buttons for linking scryer to scryer or scryer to modsuit should not be inverted from modsuit to modsuit or modsuit to scryer
<hr>
Copied from modsuit, imprinted scryer
Copied from scryer to scyrer.
<hr>
:cl:
fix: Fixed modlink linkage being inverted at times
/:cl:
=> unfucks modlink linkage

code/modules/mob/living/basic/basic_mob.dm
This PR fixes morphs not being able to attack and kill basic mobs. Fixes #29115.
Regression.
Spawned as morph, spawned cow and pig, ensured I could kill and eat them. Changed over to goat, ensured I could attack morph and that morph took damage.
:cl:
fix: Simple mobs such as morphs can properly attack basic mobs such as cows and pigs.
/:cl:
=> fix morphs not being able to attack basic mobs

code/modules/mob/mob_vars.dm
This PR removes the dead var `/mob/var/can_strip`.
Dead code bad.
Compiled.
NPFC
=> remove dead var /mob/var/can_strip

code/modules/admin/misc_admin_procs.dm
Fixes #28571
Fixes a regression that made `Start now` fail if the game is still initializing. It now checks if the game state is anything less than `GAME_STATE_STARTUP`.
Verb didn't work as expected.
Started game and forced a start while it was still initializing
<hr>
<hr>
:cl:
fix: Start Now verb works before the game has initialized.
/:cl:
=> Fix Start now verb not working before the game has initialized

_maps/map_files/stations/metastation.dmm
- Slightly enlarges the lower portion of toxins mixing.
- Rotates the toxins mixer.
- Moves the disposals unit so it doesn't block access to the thermomachine when a canister is wrenched to it.
- Fixes missing purple floor border.
- Relocates the area air control computer outside of toxins storage.
- Relocates the RPED rack to avoid a 1 tile wide section.
- Less claustrophobic.
- Consistent floor patterning.
- Always-accessible thermomachine controls.
- I have realized that the entire point of the area control computer is that you can safely purge toxic spills without opening the door to the toxic spill. Cyberiad, Delta, and Emerald already follow this design principle.
Visual inspection of the area.
<hr>
<hr>
:cl:
tweak: Slightly enlarged meta toxins.
tweak: Meta toxins scrubber control …
=> Slight Touchup of Meta Toxins

code/modules/mob/living/carbon/carbon_procs.dm
Fixes that wearing a gas mask was not enough to stop breathing in gas
Closes #29019
Chemists won't suffocate when mixing cyanide
Didn't know i affect it this way when i fixed acid procs. At some point it has logic that if there is no internals then you breath from environment, but gas masks have some gas filters inside (not actually, but we will just pretend that they do)
Walked into a smoke without a mask; with a regular breathing mask but without internals - started coughing. Walked into a smoke with gas mask; with breathing tube implant + internals; with a modsuit that blocks gas smoke effect - didn't cough
<hr>
<hr>
:cl:
fix: Gas masks now protect from gas again
/:cl:
=> fix gas mask not protecting from.. gas

_maps/map_files/RandomRuins/LavaRuins/lavaland_surface_nt.dmm
This PR surrounds the non-building area of the mining station near the doppler radar with no lava mapping helpers.
These areas shouldn't be getting turned into lava/chasms randomly.
:cl:
fix: Parts of the mining station near the doppler radar will no longer be subject to random lava/plasma/chasm river generation.
/:cl:
=> fill in area around doppler radar with no lava helpers

code/datums/components/ducttape.dm, code/datums/components/shielded.dm, code/datums/elements/decal_element.dm, code/datums/elements/rust_element.dm, code/game/atoms.dm
This PR adds a list argument to the `COMSIG_ATOM_UPDATE_OVERLAY` signal to allow responders to put the overlays they want managed into that list.
This is how we should have been doing this and cleans up a bunch of code where elements/components had to do some of their own overlay management.
NPFC
=> allow COMSIG_ATOM_UPDATE_OVERLAY responders to add managed overlays directly

code/modules/cooking/cooking_container.dm, code/modules/cooking/recipes/midway_recipes.dm, code/modules/cooking/steps/recipe_step.dm
This PR:
- converts the "deep fried anything" recipe to actually use the "deep fried anything" add-item step, so that it is properly filtered out of valid recipe results when using an item that's part of an existing deep fryer recipe.
- sets the /check_conditions_met proc to be pure so that recipes and the autochef to restrict how much of the game state can change as a result of calling it
- ensures that deep-fried food cannot be deep-fried twice
- adds a custom message when trying to deep-fry already deep-fried food similar to the one that existed pre kitchen-rework
Gets rid of debug log spam, improves experience around deep-frying things.
Used raw potato sticks in deep fryer, ensured they turned into fries with no debug log. Deep fried fries, ensured they were converted as expected. …
=> fix deep-fried anything recipe collision

code/game/gamemodes/miniantags/guardian/types/explosive_guardian.dm
guardian bomb CanPass now returns the CanPass for the stored object
Thanks to @DGamerL for the solution, i aint ever finding this out on my own.
functions again
Planted bombs on airlock, window, directional window, ripley
Bumped all and exploded
<hr>
<hr>
:cl:
fix: Explosive guardian booby traps detonate upon bump
/:cl:
=> Fix explosive guardian not detonating upon being bumped

code/modules/mob/living/simple_animal/hostile/terror_spiders/black.dm, code/modules/mob/living/simple_animal/hostile/terror_spiders/green.dm, code/modules/mob/living/simple_animal/hostile/terror_spiders/white.dm
fixes #29049 and also takes care of other terror spiders
Fix
- Spawned green, black and white terror spiders and parried their attacks
<hr>
<hr>
:cl:
fix: Fix black, green and white terror spider attacks being improperly parried
/:cl:
=> Fix some spider attacks being improperly parried

code/modules/client/client_procs.dm
Fixes #29036
`show_hud()` clears the clients' screen and then calls `apply_clickcatcher()` to make darkness clickable again, but since the `void` atom already exists, `apply_clickcatcher()` never reaches the line that re-adds the click_catcher to the clients' screen. This PR moves said line outside of the `if` statement so it always gets re-added upon HUD changes.
It's an irritating bug that crops up in several scenarios, such as mechs, F12 HUD changes, status changes, various antagonist HUD changes.
https://github.com/user-attachments/assets/34ac98c4-1a83-4074-8918-003ae40ba89f
Interacted with dark tiles upon joining the round
Switched HUD modes and interacted with dark tiles
Ghosted in and out of my body and interacted with tiles
Observed a mob and unobserved
Fired a gun at dark tiles …
=> Fixes darkness becoming unclickable

code/game/atoms.dm
Proc "add_vomit_floor" creates vomit on the source atom. Problem is, cleanable decal vomit can be created only on floors(and name of the proc suggests it). But in the code it was used sometimes to add vomit to other atoms, such as mobs (like [here](https://github.com/ParadiseSS13/Paradise/blob/df7eea25d7d1d8055c5753292c61a0c5f979b592/code/modules/mob/mob.dm#L1135)), it was broken in PR #20993, commit: 6397499f6445c9d93bb21bde437f3dd2aafe81a5
So to make sure all such mistakes are fixed and there will be no similar errors in the future, I decided not to change every occurence of the function to be used on the floor atom, but so that the function gets the turf of the source itself
Fixes the bug, hopefuly makes the proc more robust to the errors in the future
Tested on a local server, vomit …
=> Fix vomit not dripping on the floor

code/modules/station_goals/bsa.dm
This PR adds BSA fires to the investigate log for bombs.
Currently the details of who fired a BSA are hidden in admin logs and require diving. This info should be easier to get to.
Confirmed worked with person at console, as well as AI accessing console remotely.
NPFC
=> add BSA fires to investigate log

code/game/machinery/airlock_control/airlock_controllers.dm
Adds specific handling for when the chamber pressure matches the target pressure, preventing from the airlock deadlocking itself.
Airlocks should facilitate traversal between station and space, not prevent it. Also, functions as expected and I saw an engineer nearly die due to getting stuck outside.
https://github.com/user-attachments/assets/245caae9-ef14-491a-884f-42d9fc5f1c7a
See video.
<hr>
<hr>
:cl:
fix: External airlocks won't deadlock themselves.
/:cl:
=> [Fix] prevents external airlocks from getting deadlocked

code/game/objects/items/weapons/cigs.dm
Fixes #28322.
The last thing you want in your Nanotrasen cigarette is somebody's foot fungus. But as it turns out, that may be what you get.
Lit a cigarette in my mouth. Let it burn out. It stayed in my mouth.
Lit a cigarette in my hand, let it burn out. It fell to the floor.
Lit a cigarette as a service borg, picked it up, let it burn out. It fell to the floor and there was no runtime to be seen.
<hr>
<hr>
:cl:
tweak: Cigarettes no longer teleport to your mouth when stamping them out.
/:cl:
=> Stamping out Cigarettes Doesn't Teleport Them to Your Mouth Anymore

.github/CODEOWNERS
Adds all the HCs as codeowners for reviewing/approving config changes.
Adds @Burzah as a code owner on tgui/docs
Streamlines the review process as HCs can update the server config as needed.
Trust me, bro.
<hr>
<hr>
NPFC
=> Updates CODEOWNERS adding the HC's to config. Adds Burzah to another TGUI Directory

code/modules/reagents/reagent_containers.dm, code/modules/reagents/reagent_containers/syringes.dm
fixes runtimes that would happen when trying to inject with an empty syringe.
This was caused by some checks always returning true.
bugfix
- Injected syringe, beaker and human with a syringe both empty and full
<hr>
<hr>
:cl:
fix: Fixes syringes runtiming when trying to inject with an empty one
/:cl:
=> fixes syringe runtimes

code/modules/smithing/machinery/power_hammer.dm
Adds a check for if something is inserted to stop operations.
Runtimes bad.
Interacted with power hammer. Was told there was nothing inside instead of runtiming.
<hr>
<hr>
:cl:
fix: Fixed a powerhammer runtime
/:cl:
=> Fixes Powerhammer Runtime

code/game/objects/items/weapons/cigs.dm
This PR removes a debugging message from cigarettes.
Not supposed to be there.
:cl:
fix: You'll no longer receive a warning message when a lit cigarette in your mouth goes out.
/:cl:
=> remove cigarette debugging message

code/modules/mining/lavaland/loot/ashdragon_loot.dm
Removes spectral blades' flat block chance
Adds a parry that scales with ghosts. Starts out with a `stamina_coefficient` of 1 and 30% uptime, at 20 ghosts it reaches stam_coeff of 0.5 and 70% uptime. It cannot parry projectiles.
Lowers the damage per ghost 4 -> 3.
Lowers spectral blade dmg cap 75 -> 50
With it's block and damage, it's an oppressive weapon that enables antags. Despite that, the item is interesting and I do not wish to see it completely removed.
Compiled. Number adjustment. Tested parrying by orbiting my character and VV-ing the parry values. They updated accordingly to my ghost.
:cl:
tweak: spectral blade damage caps out at 50,
tweak: spectral blade now gets 3 damage per ghost.
tweak: spectral blade now uses a parry that scales with ghosts.
/:cl:
=> Nerf Spectral Blade

code/__HELPERS/qdel.dm
Title
Runtimes shouldn't exist
Tested without these changes: applied a patch to a mob and used a staff of ressurection - got a runtime for `null.Cut()`
With changes: applied patch, used staff of ressurection - no runtime
<hr>
<hr>
NPFC i believe
=> fix `QDEL_LIST_CONTENTS()` runtime

code/modules/research/designs/bluespace_designs.dm, code/modules/telesci/rcs.dm, config/example/config.toml
Adds the Rapid Crate Sender (RCS) design to protolathes. It has a technology level of programming 5, bluespace 4, engineering 4 and plasmatech 4; just like the cargo telepad beacons.
The design only requires glass and metal (3750 glass and 5000 metal without upgrades) which means it can be printed in autolathes should a design disk be made and inserted in one.
The Rapid Crate Senders now have the same origin tech as cargo telepad beacons, which is bluespace 3.
The smith's introduction made RCSs a lot more used than they were before, but did not add ways to make new ones, this leads to many peoples wanting to use the item but not many being available per maps (~4 are mapped in in every maps I believe, counting lavaland; Cyberiad has 6).
This PR will change this by allowing more RCS to be …
=> Making the Rapid Crate Sender (RCS) printable

code/__DEFINES/rust.dm, code/controllers/subsystem/SSblackbox.dm
This PR adds the following values to blackbox:
- build compiler version (`DM_VERSION` and `DM_BUILD`)
- server runtime version (`world.byond_version` and `world.byond_build`)
- random seed
- name of rustg library file
- name of rustlibs library file
This is valuable information to keep around for a variety of reasons including bug reproduction, making sure the correct DLL files are used, etc.
NPFC
=> blackbox various technical details

code/game/objects/items/weapons/holy_weapons.dm
Adds a mind check to prayer bread
Fixes #29162
Spawned as a mime, bread, and a regular human mob. Looked for runtimes.
<hr>
<hr>
NPFC
=> Fix prayer bread runtiming on mindless mobs

code/modules/mob/living/death.dm, code/modules/mob/living/living_defines.dm, code/modules/mob/living/simple_animal/simple_animal.dm
Makes it so when a simple mob is gibbed, player that used to control him will be properly shown in a ghost form, instead of being fully transparent (having no icon to display)
There is no reason to set icon to null. For simple mobs at least, but i still don't know if it's actually used by something, so i'm not removing it globally
Terror spiders are a great example. If you are located inside the body and gib() is called, your icon will be set to null.
Before (yeah you can see the icon on RMB context menu, but not otherwise):
After:
<hr>
<hr>
:cl:
fix: Gibbed simple mobs will now always have a proper icon for a ghost form.
/:cl:
=> Fix simple mobs lose their `icon` on `gib()`

code/modules/station_goals/secondary/supply/random_smithed_item.dm
Fixes #29152
When a smith item is created, quality is a new datum while mineral is a type reference. The quality needed to be an istype instead of an equals as a result
Bugs bad
Smithed items manually instead of var edit. Items successfully turned in for secondary goals.
<hr>
<hr>
:cl:
fix: Fixes turning in secondary goals for smith
/:cl:
=> Smith Polish: Fixes secondary goal turn in

code/modules/cooking/recipes/oven_recipes.dm
This PR fixes #29179.
Recipes should work.
Completed both recipes in-game.
:cl:
fix: The bake times for strawberry chocolate cake and clown cake have been fixed to not cause a burnt mess.
/:cl:
=> fix too-long oven recipes

code/game/turfs/simulated/floor/plating.dm, code/modules/mining/lavaland/loot/colossus_loot.dm
This PR makes a fake version of asteroid floors for use with the anomalous crystal theme warp for Lavaland. This ensures the floors will still count as floors for the purposes of shuttle transit.
It also removes a comment about the lavaland theme warp "depressurizing" the area that gets transformed; even when Lavaland was first added that wouldn't have been true due to how Lavaland was ported over from /tg/.
This fixes a serious regression that is caused when used on shuttles.
:cl:
fix: Anomalous crystals which theme warp areas to "Lavaland" will generate the correct floors and work as expected on shuttles.
/:cl:
=> fix lavaland anomalous crystal shuttle floors

code/game/objects/items/weapons/cigs.dm
Checks for syringes, continues the attack chain if used is a syringe. Fixes #29135
regression fix
Injected cigarette. tried to draw from cigarette.
:cl:
fix: Syringes can inject into cigarettes.
/:cl:
=> fix cigarette syringe injections

code/datums/weather/weather_types/lavaland_weather.dm
This PR changes a check in volcano's area_act to check for a list length instead of truthiness.
Fixes a runtime.
NPFC
=> fix empty list length check in volcano

code/modules/surgery/organs/augments_arms.dm
Fixes a minor runtime involving implants not unregistering their signal on removal.
Runtimes are bad
Took off an IPC's charging arm, reattached it with the charger still inside, no runtime
<hr>
<hr>
=> Fixes a runtime error caused by reattaching limbs

_maps/map_files/stations/cerestation.dmm, _maps/map_files/stations/deltastation.dmm, _maps/map_files/stations/emeraldstation.dmm, _maps/map_files/stations/metastation.dmm
Adds cargo telepads to non-box stations.
Science should be standardized, and having cargo telepads is generally a good thing.
Compiled
<hr>
<hr>
:cl:
add: Adds cargo telepads to all non-box RND rooms.
/:cl:
=> Standardizes Cargo Telepads in Science

code/modules/response_team/ert.dm
Makes it so selecting a female gender will now also update your mob's sprite
Removes bearded women from ERT
Skin tone randomise now respects mob's species
You shouldn't have male body when you are displayed as a female
Using more advanced proc created for randomising skin tone is good
Called for an ERT, spawned 3 times as a female, had no beard and a female body. Skin tone is ok. Tested only with humans cos i don't really know how other species "should" normally look like, but it won't break anything
<hr>
<hr>
:cl:
fix: Selecting female gender as an ERT member will also update your body's sprite.
tweak: You won't spawn with a beard as an ERT member if you are a female.
tweak: Tweaked available skin tones for ERT.
/:cl:
=> Improve ERT appearance by a little

code/modules/smithing/smithed_items/tool_bits.dm, code/modules/surgery/surgery.dm
Makes tool bit failure rate affect surgery failure chance.
Bits doing what they are advertised to do is good.
Used var-editted bit on scalpel. Saw adjusted success chance in break point during surgery action.
<hr>
<hr>
:cl:
tweak: Tool bit failure rate now affects surgery failure chance.
/:cl:
=> Smith Polish: Makes tool bits affect surgery fail rate

code/datums/ores.dm, code/game/turfs/simulated/floor/asteroid_floors.dm, code/game/turfs/simulated/minerals.dm
Changes the productivity bit to add more instead of act as a multiplier.
Too many minerals makes mining dull.
Created best possible productivity bit. Mined ore. Saw increased values but not insane multiplied ones.
<hr>
<hr>
:cl:
fix: Fixed over-production from productivity bits.
/:cl:
=> Nerfs Productivity Bit

_maps/map_files/stations/metastation.dmm
Rotates and removes a duplicate smith shutter. Fixes #29057
looks better
Loaded in, observed the shutters, closed and opened the shutters.
:cl:
fix: metastation shutters aren't doubled and rotated.
/:cl:
=> Fixes Metastation's smith shutters

code/modules/surgery/organs/eyes.dm
Changes the `parent_organ` of eyes from the head to the eyes meaning that your eyes are now located within the eye slot... bit confusing yes but what this means is you don't need to do head organ manipulation to get at someone's eyes, it's under eye organ manipulation.
It makes little to no sense that the eyes are located within someone's head/skull.
You do not need to saw through the top of someone's head to remove their eyes even in real life.
Other servers have already set their code up to have the eye slot as the parent organ for eyes, this will bring us in line with them and just logically makes more sense.
In game, did a bunch of surgery to make sure the eyes still functioned.
Made sure all the eyes+hud implants still fit in the eye slot.
Made sure you still go blind when your eyes …
=> Moves eyes to the eye slot

code/__DEFINES/misc_defines.dm, code/__HELPERS/files.dm, code/modules/admin/admin_verbs.dm, code/modules/admin/verbs/getlogs.dm
This PR adds an admin command for accessing logs for rounds by entering their ID. It defaults to the current round but will look up the log directory based on the date time of the inputted round in the database. Kind of fiddly but does the job.
Admin request.
https://github.com/user-attachments/assets/33f8c0b2-59b3-4c82-803c-aa1ca916ad2c
See above
NPFC
=> add admin verb for log access by round ID

code/controllers/subsystem/SStgui.dm, tgui/public/tgui.html
So turns out the issue is chrome now cares about CORS for stylesheets and we needed to go "dont worry about this just allow it fam", hence the change to `tgui.html`.
Also removes `basehtml` from the TGUI VV list. There isnt a security risk here, it just bloats the everliving fuck out of the VV window.
RSC CDN Assets good.
Notice how the assets are infact working
See above
<hr>
<hr>
fix: Fixed CSS for RSC CDN assets
/:cl:
=> Oneliner to make RSC CDN work.

code/game/machinery/cryopod.dm
Fixes #29210
The cryopod would qdel the PDA id, resulting in the spare getting deleted. The PDA id slot is now simply set to null and ID card deletion is handled like normal items (captains spare being the sole exclusion)
Important item go kaput no good
Put spare ID in PDA, cryod. Respawned and dispensed the spare ID. Regular ID was not kept, PDA was not kept.
:cl:
fix: Captain's spare ID will no longer get eaten by the cryopod.
/:cl:
=> Fixes captains spare ID getting deleted

code/modules/events/event_container.dm
Title.
Does not affect pulse demon itself or remove any of its code.
Pulse demon is one of the most hated midround antagonists in our lineup. It's unfun to fight, can become godly powerful in a few minutes at the supermatter buffet, and the only ways to kill it are to cut power to the entire station or use ions, which themselves may kill more people than the demon. Plus, its console explosion ability can blow holes in the station, which is extremely lethal with MILLA.
While I understand that this may lead to Pulse becoming deprecated content in the future, better that than leaving a terrible antagonist in the game to steal the show from more enjoyable midrounds.
- entered game
- checked admin event panel
- no more pulse demon event
<hr>
<hr>
:cl:
tweak: Removes pulse demon from event …
=> Removes the Pulse Demon event from rotation

code/modules/projectiles/guns/energy/kinetic_accelerator.dm
MY EYES- No but less jokingly this shouldn't happen and it was my fault so I'm fixing it now
Without modkits
With modkits
Went in, stared hard at it.
:cl:
fix: Fixed the kinetic crusher description telling you you could remove modkits with a crowbar too many times.
/:cl:
=> Fix kinetic accelerator desc taking up half your chat when it has modkits inside it

code/game/turfs/simulated/walls.dm
Makes thermite create actual plating instead of a fake floor with the plating icon. Fixes #29234
The fake default floor is confusing and refuses to be interacted with.
Burned down walls with fast acting thermite C4 and with thermite from a beaker. It produced Real Genuine plating.
:cl:
fix: Thermite will no longer produce fake floor.
/:cl:
=> Thermite won't create fake plating anymore

_maps/map_files/stations/cerestation.dmm
Moves the bar double wide airlock to the correct spot
Airlock being in window looks bad
I launched a server and looked at the now moved airlock
<hr>
:cl:
fix: nudged farragus's bar double wide airlock into frame
/:cl:
=> NSS NSS Farragus, moves a double wide airlock to its correct spot

.github/PULL_REQUEST_TEMPLATE.md
Standardizes the declaration section on this template. Getting rid of the use of headers and using an H2 sizing for the decleration title instead.
Its good for me.
Trust me, bro.
(examined in markdown viewer)
NPFC
=> Standardizes Declaration Section on Pull Request Template

code/game/gamemodes/miniantags/pulsedemon/cross_shock_component.dm
Fixes #28844
Perpetual maker will now point to the parent as the attacker
immersion
Shocked a mob as a human that has eaten a pulse heart.
<hr>
<hr>
:cl:
fix: Perpetual pacemaker has a proper attack path again.
/:cl:
=> Fixes the perpetual pacemaker attack log

code/datums/elements/wears_collar.dm
This PR fixes a typo in a typecast for pet collars.
You can get in this situation when e.g. Poly drops an item they're holding, and this will runtime. Runtimes bad.
NPFC
=> fix a bad typecast with collar element

.github/actions/restore_or_install_byond/action.yml, .github/workflows/ci.yml, tools/ci/install_byond.sh, tools/tgs_scripts/PreCompile.sh
This PR attempts to integrate TG's GitHub action for installing and caching BYOND in CI.
Even though #29282 properly caches BYOND, some unknown stupidity with the install script is still refusing to see it.
Let's find out
NPFC
=> integrate tg's restore_or_install_byond github action

code/modules/mob/mob.dm
Fixes #29190
Examine broadcasts will now send the appropriate messages. If the examined atom is not visible to the user, it will not send an examine message.
Feature wasn't working as intended.
In an instance with 2 clients:
:cl:
fix: Examines will now send the appropriate message in chat.
/:cl:
=> Fix examine broadcast sending the wrong messages

code/modules/mob/living/carbon/carbon_procs.dm
Hides morphs ventcrawl cogbar. Fixes #28835
For something that can mimick anything, it doesnt make sense to blatantly announce sinking into a vent.
Loaded server with 2 clients, observed morph from 2nd client.
:cl:
fix: Hides morph ventcrawl cogbar
/:cl:
=> Hides morph ventcrawl cogbar

code/modules/mob/living/silicon/ai/ai_mob.dm
Lets the AI pick the "malfunctioning" screen display again
Was unintentionally removed as an option back in 2013
(this doesn't add any sprites, just the selection but heres what it looks like)
compiled. spawned a ai core possessed the ai core chose the "malfunctioning" option, icon properly changed
:cl:
add: Added back the "malfunctioning" as an optional screen state for the ai
/:cl:
=> Restores the "malfunctioning" screen state for the ai

code/modules/surgery/organs/organ_internal.dm
Fixes an issue where eyes (or any mouth implant) would despawn during limb reattachement surgery.
https://github.com/ParadiseSS13/Paradise/pull/29297 can hopefully be unTM'd now
Fixes a 9 year old bug
In-game I sawed the head off of a dummy and reattached it, the eyes/mouth organs didn't despawn and worked.
:cl:
fix: Fixes mouth/eye organs despawning after being reattached to a body
/:cl:
=> Fix for eyes despawning when heads are reattached

code/modules/mob/mob.dm, code/modules/surgery/organs/augments_internal.dm, code/tests/game_tests.dm, code/tests/test_anti_drop.dm
Fixes #29226
Let's #29225 be closed.
Undoes my previous fix and lets antidrop implants remove `NODROP` from its items regardless which slot theyre in.
Prevents items getting glued permanently when using anti drop implants.
Manually tested the implant and edge cases. Wrote a unit test for it.
:cl:
fix: Belts will no longer get stuck to you when using the anti drop implant.
/:cl:
=> Makes antidrop implant release its items regardless which slot theyre in

code/modules/mob/living/simple_animal/hostile/carp.dm
This PR fixes overlays for carp mouths.
Bugfix.
:cl:
fix: Space carps now properly update their mouth sprite when dead.
/:cl:
=> fix carp mouth overlays

code/modules/mob/living/simple_animal/simple_animal.dm
Makes it so dead simple mobs now have a proper icon on RMB's context menu (maybe somewhere else tho)
Fix
Before
After
:cl:
fix: Fixed simple mobs not updating their icon when they die.
/:cl:
=> Fix simple mobs not updating their icon state on `death()`

code/_globalvars/misc_globals.dm, code/modules/mob/living/living.dm
This PR adds user logs for when players start and stop pulling mobs, atmos canisters, and reagent tanks.
Improved admin logging, will help to see who is dragging around fuel tanks to welderbomb, if people are taking SSD players somewhere that isn't cryo, etc, etc.
See above
NPFC
=> add admin logging for pulls of mobs, canisters, and reagent tanks

code/game/gamemodes/objective.dm, code/game/gamemodes/objective_holder.dm
Fixes #29065
Adds a proc to `objective_holder` which will return the list of assigned targets. Changed the target validity check to use the returned list.
Bug bad. Objectives should reroll into valid targets or not at all.
As shown on the images, the round had a total of 3 crew, 2 valid targets. Upon cryoing of one target, there's now only 2 crew.  The objective tried to reroll, but due to a lack of valid targets (the sole existing one already being a target), it removed the objective.
:cl:
fix: Objectives will no longer reroll repeats.
/:cl:
=> Fix repeat kill objective rerolls

code/game/objects/items/weapons/pneumaticCannon.dm
Title
More updated attack chains is good
Put a tank on a pneumatic cannon, stuffed it with things until I couldn't anymore, fired. Tried to put cannon in bag, tried to fire cannon point-blank on both harm and help intent, properly bashed the target when on harm intent.
:cl:
tweak: Pneumatic cannon will now only fire point-blank on help intent, like other guns
/:cl:
=> Ports pneumatic cannon to new attack chain

code/datums/status_effects/buffs.dm
Quicksiver form grants TRAIT_HANDS_BLOCKED for the duration. This means the flayer cannot attack during this time, however most abilties still work.
This will cause items that cannot be stored to be dropped (unless antidrop). The ability will **attempt** to store the items you have in hand like you pressed E, starting with  the item in active hand.
We do not allow guns with carp. Qani can dodge bullets, but not deflect them, takes a moderate portion of tc, a 5 minute cooldown, and a *lot* of heart damage.
Quicksilver form lasts 10 or 20 seconds, giving it up to ***50%*** uptime (since it has a 40 second cooldown), of which the flayer can shoot you down, be reflecting your ranged attacks, and pass through windows and mobs.
As such, it reaaaally doesn't need the ability to attack at the …
=> Quicksilver form no longer allows item useage

code/game/objects/items/weapons/storage/bags.dm, code/modules/food_and_drinks/food_base.dm
This PR:
- restricts the items food trays can pick up to food and reagent condiment containers
- fixes not being able to pick up sliceable foods like pizzas by clicking on them with a food tray
Yes, technically it's just a tray, there's no reason why you couldn't put anything on it, but its practical usage in game is for storing food. Trying to use it on cluttered kitchen tables to get things into a food and drink cart or the counters is an exercise in frustration because it literally picks up everything that can fit on it, forcing you to constantly pick things off of it to fit the actual things you want. This makes it more useful for its actual job.
Used food tray on above items as well as others, ensured it behaved as expected.
:cl:
tweak: Food trays now only pick up food, reagent …
=> some food tray improvements

code/game/objects/items/weapons/storage/garment.dm
Increases the garment bag slots to 27. Fixes #29236
Captains bag has 27 items. Taking an item out results in not being able to put it back in.
Tried to put in a 28th item. Bag full.
Took an item out, put it back in.
:cl:
tweak: Garment bags now have 27 slots.
/:cl:
=> increases garment bag slots to 27

code/datums/uplink_items/uplink_general.dm, code/modules/research/designs/weapon_designs.dm
What it says on the tin. Syndicate mantis blades now cost 50 TC. They still cannot be obtained from surplus or be discounted, per balance's request.
Nanotrasen mantis blades now only require illegals 4 instead of illegals 6.
Mantis blades got nerfed into the ground, and yet are prohibitively expensive still while there are much much better things available. This makes them more than a meme choice.
It also makes nanotrasen mantis blades not require the insurmountably high illegals 6 to obtain.
Compiled.
<hr>
<hr>
:cl:
tweak: Cheapened mantis blades
tweak: Reduced research requirements for NT mantis blades
/:cl:
=> Makes Mantis Blades Cheaper

code/modules/projectiles/guns/energy_guns.dm
Fixes an issue where, if you're clicking faster than the gun can shoot, durability damage is still applied to the lens.
Bugs bad.
Spawned a lens. Shot gun. Watched durability in VV.
<hr>
<hr>
:cl:
fix: Fixed lenses taking extra damage if clicking faster than the fire rate of the gun
/:cl:
=> Smith Polish: Fast-Click Lens Durability Fix

code/modules/mod/mod_link.dm
Modsuits properly named the holograms, but I missed a statement for if the name was the same as the voice. Whoopsies.
Also H.name instead of M.name, more correct.
See above
It worked, unfortunately most of my calls in original testing were from modsuits, and the renaming was a later addition
<hr>
:cl:
fix: Fixed mod scryer calls not properly forwarding the name of who is talking
/:cl:
=> fix modlink from scryers not renaming the hologram to voice correctly

code/modules/smithing/machinery/casting_basin.dm, code/modules/smithing/smithing_cast.dm
Fixes a runtime error when examining an egun parts cast. Also gets rid of an extra var.
Bugs bad.
Examined the cast.
:cl:
fix: Fixed a runtime in examining egun parts casts
fix: Purged an extra var that was doing nothing
/:cl:
=> Fixes Egun Frame Cast Examine Runtime

code/modules/surgery/limb_reattach.dm, code/modules/surgery/organs/organ_external.dm
Title
It always seemed very arbitrary to me that the style reset like that. It bothered me so I imagine it probably bothered someone else.
Decapitated myself, recapitated myself, I looked exactly the same
:cl:
tweak: Putting an IPC's head back on no longer resets the style to default
/:cl:
=> IPC monitors no longer reset to a default after reattachment

code/modules/mob/living/simple_animal/hostile/megafauna/ancient_robot.dm
Changes (health <= health / 2) to (health <=maxHealth / 2), so it actually works
Code working is good. 20% faster vetus at low hp (not including how the fuck megafauna life process works) is good
Compiled, proper.
:cl:
fix: Vetus now properly gets 20% faster in its special moves once it is below half hp
/:cl:
=> Vetus now properly gets 20% faster in its special moves once it is below half hp

code/modules/smithing/components/trim.dm, code/modules/smithing/smith_item.dm, code/modules/smithing/smithed_items/inserts.dm, code/modules/smithing/smithed_items/lens.dm, code/modules/smithing/smithed_items/tool_bits.dm
Fixes uranium upgrade and part radioactivity.
Intended side effects should be there.
Made uranium parts. Checked radioactivity. Saw healthy glow.
<hr>
<hr>
:cl:
fix: Fixes smith upgrade and part radioactivity
/:cl:
=> Smith Polish: Fixes Radiation

code/modules/power/engines/singularity/singularity.dm, code/modules/power/engines/supermatter/supermatter.dm, code/modules/power/engines/tesla/energy_ball.dm
Touching any of the main engines (SM, Tesla, Singulo) with telekinesis will ghost you but you will retain respawnability. Fixes #29267
Regular deaths from said engines do not result in losing respawnability.
Telekinetically touched the SM, Energy Ball and Singulo. My brain got removed but I still had respawnability.
:cl:
fix: Telekinetically touching engines will no longer remove respawnability.
/:cl:
=> Makes touching engines with Telekinesis retain respawnability

code/game/objects/effects/spawners/random/pool/lavaland_pools.dm, code/game/objects/effects/spawners/random/pool/misc_pools.dm, code/game/objects/effects/spawners/random/pool/pool_spawner.dm, code/game/objects/effects/spawners/random/pool/space_loot.dm, code/game/objects/effects/spawners/random/pool/spawn_pool.dm, code/game/objects/effects/spawners/random/pool/spawn_pool_manager.dm, docs/mapping/spawn_pools.md
This PR switches spawn pools from using string IDs to just datum references. I should have done it this way in the first place.
Cleaner, less risk of typos fucking things up.
NPFC
=> switch spawn pools from using IDs to typerefs

code/modules/clothing/gloves/misc_gloves.dm
Title. Combat gloves now get a small amount of armor in most categories. Also updates the description to reflect that.
You'd think that a pair of military-standard combat gloves would be better at protecting your hands than literal pieces of bone strapped to your arms. Now they are.
Description is good.
N/A, number changes only.
<hr>
<hr>
:cl:
tweak: Armors up combat gloves.
/:cl:
=> Gives Combat Gloves light armor

code/datums/elements/strippable.dm, code/game/objects/items/weapons/knuckledusters.dm
Makes items with `TRAIT_SKIP_EXAMINE` visible on strip menu.
Removes the `ABSTRACT` flag from knuckledusters and replaces it with `TRAIT_SKIP_EXAMINE`. Knuckledusters are now always visible in strip menu. Knuckledusters are visible in examine when ungripped , invisible when gripped. Fixes #29247
I'll probably make them invisible on strip again, but that'd be after NODROP is made into a trait and non-attached NODROP items lose the flag on death. (ETA whenever I finish testing it)
An invisible and undroppable item that occasionally is a high value target is weird.
Ungripped knuckledusters
Gripped knuckledusters
Images. Local instance, strip and examine mob with ungripped dusters and with gripped dusters.
:cl:
tweak: Knuckledusters will show on strip menu when gripped.
/:cl:
=> Makes knuckledusters visible on strip menu

code/modules/mob/mob_misc_procs.dm, code/modules/surgery/organs/eyes.dm, code/modules/surgery/organs/subtypes/tajaran_organs.dm, code/modules/surgery/organs/subtypes/vulpkanin_organs.dm
Changes it so IPCs are fully affected by colorblindness instead of just with pulsing wires. Also changes a few instances of "colour" to "color".
If you choose the colorblind disability, you should be colorblind. They already have the colorblind version of door wires, so this keeps the behavior consistent. Also keeping coding standards up to date a bit more.
Spawned in as human with colorblind, and IPC with colorblind. Replaced both eyes with cybernetics and colorblindness was properly cured.
<hr>
<hr>
:cl:
tweak: IPCs are fully affected by colorblindness
/:cl:
=> IPCs can be colorblind

code/modules/mining/equipment/lazarus_injector.dm
This PR makes mob capsules respect pet collar names, both for the capsule name and the mob's name.
Pokemon
https://github.com/user-attachments/assets/5fc60178-6fb8-40fd-816c-5758e51a0e64
Captured a migo without a collar and it's name updated appropriately.
Captured a migo with a Hatsune Mi'Go collar and it's name remained Hatsune Mi'Go. Capsule was named Hatsune Mi'Go as well.
:cl:
tweak: mob capsules will respect pet collar names.
/:cl:
=> Make mob capsules respect collar names

code/__DEFINES/cooking_defines.dm, code/modules/cooking/recipes/deep_fryer_recipes.dm, code/modules/cooking/recipes/grill_recipes.dm, code/modules/cooking/recipes/oven_recipes.dm, code/modules/cooking/recipes/stove_recipes.dm, code/modules/cooking/steps/recipe_step_add_meathunk.dm, paradise.dme
This PR fixes a collision between chicken- and meat-steak recipes, and provides a custom add-item recipe step specifically for meat, because it has about a dozen subtypes which are appropriate for use as a "generic hunk of meat" in recipes (ham, synthflesh, human flesh, etc.), and about a half dozen subtypes which aren't (raw chicken, etc.). Fixes #29321, and removes some recipes that are redundant as a result of the refactor.
Fixes a broken recipe and makes recipes more consistent.
Attempted to make steak recipes with various meat subtypes, ensured things were working as expected, ensured autochef continued to work with meat steak recipe.
:cl:
fix: Chicken and meat steak recipes now work properly
tweak: Food recipes which require some kind of meat hunk will no longer accept certain …
=> fix meat/chickensteak recipe collision

_maps/map_files/RandomRuins/SpaceRuins/sieged_lab.dmm, code/modules/awaymissions/mission_code/ruins/sieged_lab.dm
This PR puts the two research papers in the sieged lab executive room on a noticeboard, and puts a safe under the floor containing two guaranteed space loot pool spawners.
The sieged lab gets depressurized often due to mines and things and the research papers were getting constantly blown off the table and lost. The syndicate loot isn't ingenious or anything but sieged lab loot is awful right now and at least people will get used to looking for a floor safe so we can add something else to it later. I got some more interesting feedback about things which may come later.
Spawned in, ensured I could get the papers off the noticeboard. Took off carpet, ensured that safe contained spawned contents.
:cl:
add: The sieged lab executive suite now contains a safe with potentially valuable Syndicate …
=> add siegedlab loot, add research paper noticeboard

_maps/map_files/RandomRuins/LavaRuins/lavaland_surface_cultaltar.dmm
Changes the 1 tile random lava to alternating plasma / lava tiles.
For a ruin for cosmetic loot (unless you are a cult I guess), the 1 tile random tiles potentially being chasms is a bit punishing. As such, we change them to be the lava / plasma tiles.
before
after
after with no darksight
see above, even missed tiles originally
<hr>
<hr>
:cl:
tweak: removes 1 tile chasm potential from summoning ritual ruin
/:cl:
=> removes 1 tile chasm potential from summoning ritual ruin

code/modules/cooking/recipes/midway_recipes.dm
This PR sets the proper outputs of the related jelly bean recipes. Fixes #29311.
Bugfix.
Created fixed recipes, ensured the product was the correct type.
:cl:
fix: Recipes for Dr Gibbs- and coffee-flavored jelly beans produce the correct output.
/:cl:
=> fix coffee/drgibb jelly bean recipes

code/modules/admin/misc_admin_procs.dm
Cancelling server restart prompt will not remind you that the server is live (if it is)
I got a heartattack because of it working this way
Jokes aside, it's working properly now. No need to send a second prompt when user already cancelled it at first
Compiled on local with `is_live_server = TRUE`, cancelled server reboot prompt and there was no further prompts
Didn't cancel it at second attempt and it restarted the server as usual
NPFC
=> No more heartattack on cancelled server restart

code/modules/antagonists/vampire/vampire_powers/hemomancer_powers.dm
Hemo claws are on the new attack chain, moved from afterattack to actual attack so parries work more expectedly with it etc.
Corrects the affectsvampires check
I like hemo claws working and granting the vampire blood when used
stabbed a skrell without a ckey, no blood
stabbed a skrell with a ckey blood.
stabbed a window, no durrability loss or blood
:cl:
fix: Fixed hemo claws not healing the vampire, unstunning them, or getting them blood
/:cl:
=> moves hemo claws to new attack chain, fixes them not working at all

code/modules/surgery/surgery.dm
Fixes a runtime that happens when you complete a step of a surgery that involves using your hand.
Runtimes bad.
Performed surgery to remove embedded objects after blowing up a skrell with a frag. No runtime.
NPFC
=> Fixes runtime in applying bit damage to unarmed steps in surgery

code/modules/mining/lavaland/necropolis_chests.dm, code/modules/mob/living/simple_animal/hostile/megafauna/bubblegum.dm
Fixes bubblegum hallucinations dropping ores
Fixes vetus sometimes blowing up it's own chest
Bugs are bad
Fought bubblegum, hallucinations didn't drop chests, exploded the chest after it dropped and nothing happened.
:cl:
fix: bubblegum hallucinations no longer drop ore
fix: Vetus can't blow up its own chest anymore
/:cl:
=> Megafauna dropping ore hotfixes

code/modules/mob/living/simple_animal/hostile/megafauna/ancient_robot.dm
Corrected spelling of KTMGMKOTM to KTMGMOTM
(ENGAGEING to ENGAGING)
Spelling is good.
Almost no one will translate it, but hey, should be correct.
:cl:
fix: Fixes spelling in vetus' self destruct
/:cl:
=> fix spelling in vetus' self destruct

code/modules/response_team/ert.dm
ERT spawning makes the mob in its spawn location vs nullspace.
It does not fix the job runtime at this time
N/A to players, just better code practice.
Spawned ERT, ERT still worked
:cl:
fix: ERT no longer initially spawns in nullspace
/:cl:
=> ERT no longer initially spawns in nullspace

code/modules/mob/living/carbon/human/human_examine.dm
Allows security HUD users to read people's security records without needing to use a console.
Allows health HUD users to read people's comment logs without having to first open their entire medical record.
Security officers should be able to read people's security records without needing an entire console, this will help open more roleplay opportunities based on people's characters' lore.
Doctors should not have to flood their chat with people's health records every time they want to check if the CMO really allowed them to obtain LSD from medical chemistry.
Before :
- Security HUD :
- Health HUD :
After :
- Security HUD : 
- Health HUD :
- Tried to see someone's security record with a security HUD, I succeeded.
- Tried to see someone's medical record's comment logs with a health HUD, I …
=> Standardise security and medical records examination (QOL)

code/modules/clothing/chameleon.dm
Fixes an issue when you could select something like holo cigar as a tajaran and there would be no sprite on your mob at all
fix
some items have `sprite_sheets` set to null, and if they do, chameleon mask doesn't take that into account and keeps its old `sprite_sheets`. so that's what causes the issue
compiled, spawned chameleon mask, equipped as tajaran, switched between ~10 different looks, `sprite_sheets` always updated correctly. Did the same with drask and human
<hr>
<hr>
:cl:
fix: Fixed an issue when chameleon clothing couldn't render on-mob sprite if you weren't a human.
/:cl:
=> Fix some chameleon items display no on-mob sprite on non-human species

_maps/map_files/stations/boxstation.dmm
Reinforces a table with plasteel
Aestetically pleasing and unreasonable for the table to not be reinforced
Loaded up the cyberiad.
Spawned as captain.
Inspected the table.
moved the pen on the table and placed a sheet of paper on the table.
:cl:
tweak: NSS Cyberiad, replaces a metal table with a reinforced table on the bridge.
/:cl:
=> NSS Cyberiad (Boxstation) reinforces a single regular table on the bridge

code/game/machinery/portable_turret.dm
Makes lenses applicable to turrets, such as AI turrets and custom built ones. Lenses can either be used on the completed turret, or it will inherit the lens from the gun used in construction.
Using eguns to make turrets would lead one to think that modifications attached to those eguns do something.
Built LWAP turrets. One had no lens, one had an admin lens. Admin lens hit harder and shot marginally faster, with a faster projectile speed, than the turret without.
<hr>
<hr>
:cl:
add: Added ability to insert lenses into energy turrets.
/:cl:
=> Smith Polish: Lenses for Turrets

_maps/map_files/RandomRuins/LavaRuins/lavaland_surface_golem_ship.dmm, _maps/map_files/RandomRuins/SpaceRuins/golemtarget.dmm, _maps/map_files/RandomRuins/SpaceRuins/ussp.dmm, code/modules/awaymissions/mission_code/ruins/freegolems.dm, code/modules/shuttle/shuttle.dm
This PR fixes the dimensions of the docking ports for the new golem ship.
Bugfix.
:cl:
fix: The new golem ship now properly docks and undocks at all its available locations.
/:cl:
=> fix new golem ship docking port dimensions

code/game/objects/structures.dm
This PR makes it possible to climb over railings from both sides again. Fixes #23529.
Bugfix.
Climbed over railing from both sides, ensured it worked.
:cl:
fix: Fixed inability to climb over railings from both sides.
/:cl:
=> fix inability to climb over railings

code/modules/mob/living/silicon/ai/ai_life.dm, code/modules/mob/living/silicon/ai/ai_mob.dm, code/modules/mob/living/silicon/ai/ai_programs.dm
Fixes three issues with the enhanced tracker:
- The enhanced tracker auto-resetting when it locks the first time
- The enhanced tracker not properly resetting the tracked mob when the menu is cancelled
- The enhanced tracker scaling the upgrades twice as fast as intended
Bugs are bad. Oversights are bad. Bad numbers are bad.
Spawned as AI. Bought enhanced tracker. Tracked pun pun. 
:cl:
fix: Fixed enhanced tracker auto-resetting
fix: Fixed enhanced tracker scaling twice as fast as it should
fix: Fixed enhanced tracker not resetting when tracking menu is canceled.
/:cl:
=> Various enhanced tracker fixes

code/modules/mob/living/silicon/ai/ai_mob.dm
Makes the amount of nanites you have for active program use display in the status tab. Also displays the rate of regeneration.
Useful information like that shouldn't be hidden. 
Spawned as AI. Saw nanites.
:cl:
fix: Fixes nanites not displaying to AI
/:cl:
=> Fixes nanite amount not displaying in status tab for AIs

code/datums/ruins/ruin_placer.dm
This PR makes ruin placement failures (for non-required ruins) a debug log statement instead of a stack trace, and adds a bit more useful info to the message.
A failure here isn't the end of the world, it just means there was an overall mismatch between available space and ruin rolls. One less noisy runtime.
NPFC
=> makes non-required ruin placement failures a log, not a runtime

code/modules/events/spacevine.dm
Buffs event kudzu mutation rate and spread rate. 
Kudzu event currently does next to nothing. This buff should make it a tiny bit challenging.
- Spawned some kudzu events and looked at their stats and spread
:cl:
tweak: Event kudzu production changed from 5 - 2  to 3 - 1 
tweak: Event kudzu mutativeness changed from 30 - 70 to 30 - 100 
:cl:
=> Buffs event kudzu mutation rate and spread rate. 

code/__DEFINES/mob_defines.dm
Updates the minimum age of a character to 20 years old.
The game corrects the minimum age of a character when loaded. This means no database edit is required.
Ensures crewmembers have the needed experience to work on a station.
Prevents further issues administratively.
Ensures everyone is old enough to drink I guess. (by non American standards)
Confirmed the game tells me a human can be 20-85 years old.
Attempt to set my age to 18 years old.
The game corrects it to 20.
:cl:
tweak: The minimum age of a character is now 20 years old.
/:cl:
=> Updates the minimum character age to 20 years.

.vscode/settings.json
This PR enables the VSC setting for adding a final newline to files on save to the default editor settings.
So people don't have to worry/care about this or set it manually
Visual inspection
NPFC
=> modify default vsc settings to insert final newlines on save

code/datums/spells/rod_form.dm
This PR fixes wizard immovable rods becoming invisible impassible barriers on tiles after turning back into wizards. Fixes #29386. Also cleans up some references on the rod for sanity's sake.
Bugfix.
Spawned in as wizard, used rod form, ensured that it was qdel'd properly and was not located in-game.
:cl:
fix: Wizard's rod form should no longer leave behind invisible impassible obstacles.
/:cl:
=> fix persistent wizard immovable rod

code/game/objects/items/stacks/stack_recipe.dm
Prevents stack recipes from force-merging the potentially qdel'd recipe result. 
Fixes runtimes and a potential source of hard deletes.
Produced the runtime by making a bunch of metal rods. Can no longer produce the runtime after making the fix.
=> Fixes stack merge runtimes when building stack recipes

code/modules/cooking/machines/cooking_machine.dm
Changes the logic to calculate the average of the machine parts rating, rather than just their sum. This is done to fix the problem with the unimproved grill producing too much stuff, because it has more parts than other machines and thus it's machine rating is higher.
Cooking machines logic is now more universal, grill doesn't make two steaks out of one slab of meat and so on.
Made a bunch of stuff with an improved grill, then changed the parts for the best ones and did it again.
<hr>
<hr>
:cl:
tweak: Tweaked cooking machines logic now doesn't allow the grill to produce matter out of thin air.
/:cl:
=> Cooking machines logic tweak

.vscode/tasks.json
Probably nobody cared, so tgui build and tgui dev server tasks used nonexistent files on linux.
=> fix: tgui tasks for linux

code/modules/mapping/dynamic_airlock_linker.dm
This PR fixes a runtime caused by dynamic airlock helpers. These loops iterate over anything on the turf, so we can't ignore the type cast.
Fewer runtimes.
Started server with drug lab ruin, ensured that no runtimes occurred.
NPFC
=> fix dynamic airlock linker runtime

_maps/map_files/stations/cerestation.dmm
This PR adds firelocks to doorways in Cere brig and perma that were missing them, using Box as a reference.
Mapping consistency.
:cl:
fix: Several doorways missing firelocks in Farragus brig have had them added.
/:cl:
=> add missing firelocks to cere brig

_maps/map_files/stations/deltastation.dmm
Fixes a missing wall 
Walls should be where they should be
Compiled
:cl:
fix: Put a missing wall into kerberos departures
/:cl:
=> Fixes a missing wall on Kerberos

code/modules/mob/living/silicon/ai/ai_mob.dm, code/modules/mob/living/silicon/ai/ai_programs.dm
When an AI is carded, it resets their programs and prevents them from purchasing new ones while they are in the card.
Carded AIs should not be able to use programs.
Spawned an AI. Bought programs. Carded AI. AI did not have programs anymore.
:cl:
fix: Made AI programs no longer function while carded
/:cl:
=> Makes AI Progams not function while carded

_maps/map_files/RandomRuins/SpaceRuins/submaps/whiteship_submaps.dmm
Plating now is under the destroyed room's door instead of wood.
Security colored flooring instead of wood to the armory room.
:cl:
fix: Fix whiteship flooring of 2 layouts
/:cl:
=> fix flooring of whiteship submaps

code/datums/status_effects/buffs.dm
Mindflayer rejuv doesn't tick when dead
People should die when they are killed
I tried but to be perfectly honest I'm not sober enough to do robust testing rn, I'm like 80% sure it works
:cl:
fix: mindflayer rejuv doesn't heal when dead
/:cl:
=> Fixes mindflayers regenning from being dead

code/game/machinery/doors/airlock.dm, code/game/machinery/doors/airlock_types.dm, code/game/machinery/doors/door.dm, code/game/objects/structures/door_assembly_types.dm
Reverts most of the #29402
Keeps the fixes
Fixes that some glass airlocks couldn't let the lasers pass through them
They are not 100% useless as i thought
Fixes are good
Tested on test tiny that they are fine
:cl:
fix: Multitile glass airlocks will let the energy projectiles pass through them once again.
/:cl:
=> Sorta revert of #29402

code/modules/cooking/machines/grill.dm
This PR fixes a runtime caused by grills running out of fuel when no cooking container is on them.
Getting rid of runtime spam.
NPFC
=> fix runtime in grill

code/controllers/subsystem/SSair.dm, code/game/turfs/turf.dm
This PR prevents pressure overlay deletion in two ways:
- makes it an abstract effect, so things like explosions won't qdel it
- stores the pressure overlay if it exists before a turfchange and adds it back after
GC was grinding deleting these but they shouldn't be getting deleted in the first place; they're meant to persist per-turf after the first time someone turns a pressure overlay on.
Spawned several tunguskas, spaced and exploded areas of the station with pressure overlay on and off, ensured they did not show up in the qdel log.
NPFC
=> prevent pressure overlay deletion

code/modules/mob/living/carbon/human/human_life.dm
Adds a missing null check in `/mob/living/carbon/human/handle_critical_condition()`. 
Rarely, mobs can enter crit with a null brain (usually happens with zombies). A missing null check in this proc would cause a runtime that triggered 20 times per second until the long overdue death of the brainless mob. 
```
[2025-05-26T22:26:55] Runtime in code/modules/mob/living/carbon/human/human_life.dm:628: Cannot read null.max_damage
proc name: handle critical condition (/mob/living/carbon/human/handle_critical_condition)
src: Unknown (/mob/living/carbon/human)
src.loc: the floor (135,95,2) (/turf/simulated/floor/plasteel)
call stack:
Unknown (/mob/living/carbon/human): handle_critical_condition
Unknown (/mob/living/carbon/human): Life
Unknown (/mob/living/carbon/human): Life
Unknown …
```
=> Fixes brainless mobs runtiming when in crit

code/modules/reagents/reagent_containers.dm
Reagent containers `can_set_transfer_amount` will return `is_valid_interaction` after it checks for possible transfer amounts. Fixes #29492
Wireless emissions are harmful and must be prevented. Also doesn't make sense why its possible.
Set transfer amounts as a human, set transfer amounts of personal beaker as a robot.
:cl:
fix: You can no longer wirelessly set reagent container transfer amounts.
/:cl:
=> Prevent reagent container transfer amounts from being set if a user is incapacitated, unconscious or not next to the container.

code/modules/antagonists/antag_org/antag_org_syndicate.dm
Adds an Oxford comma to antag_org_syndicate.dm
Oxford comma is king
I read it
:cl:
spellcheck: Added a missing oxford comma
/:cl:
=> Minor grammar fix in antag_org_syndicate.dm

code/modules/ruins/lavalandruin_code/hermit.dm
This PR fixes the name of the lavaland hermit in the admin equip menu so it doesn't say "SOMEBODY FORGOT TO SET A NAME, NOTIFY A CODER" anymore.
SOMEBODY FORGOT TO SET A REASON, NOTIFY A CODER
SOMEBODY FORGOT TO SET IMAGES OF CHANGES, NOTIFY A CODER
SOMEBODY FORGOT TO SET TESTING, NOTIFY A CODER
SOMEBODY FORGOT TO SET A CHANGELOG, NOTIFY A CODER
=> fix hermit in admin equip menu

code/modules/surgery/organs_internal.dm
Minor spelling fix in organs_internal.dm
Finally I can look at organs without being disgusted
Spelt
:cl:
spellcheck: Fixed typo in organs_internal.dm
/:cl:
=> Minor spelling fix in organs_internal.dm

code/modules/smithing/smithed_items/misc_smithed.dm
Increases cost of egun parts to 25 titanium, 25 plasma, and 2 of the space ores.
Balance bandaid.
Compiled numbers change.
:cl:
tweak: Changes mineral cost for egun parts significantly
/:cl:
=> Smith Polish - Nerfs gun parts material costs

code/modules/admin/admin_verbs.dm, code/modules/admin/verbs/SDQL2/SDQL_2.dm, code/modules/admin/verbs/SDQL2/sdql2_verbs.dm, paradise.dme
This PR adds support for running saved SDQL queries from the `data/sdql` directory. Incredibly basic and straightforward, no-frills. Once you choose a file it loads it up into the SDQL2 query prompt so you can inspect, modify, and run it.
Convenience method for developers/admins.
Loaded and ran scripts, ensured they worked as expected.
NPFC
=> support running saved sdql scripts

_maps/map_files/stations/metastation.dmm
This PR fixes a remaining office chair repath that must have slipped in after #29156 
Bugfix
Visual inspection and CI
:cl:
fix: Cerebron should properly load.
/:cl:
=> fix lingering office chair repath

code/modules/mob/living/simple_animal/hostile/gorilla/gorilla.dm
Makes it so that dead gorillas show the proper sprite when dead.
As funny as it is, gorillas probably shouldn't still be standing upright after they die
Killed a gorilla.
It slumped to the ground
:cl:
fix: Gorilla sprite updates once again when they die.
/:cl:
=> [FIX] Gorilla icon updates on death

code/modules/mob/living/living.dm
Splits up the if check in `living/can_be_flashed`. Something was going wrong with it, which caused it to not check for the flash protection trait. Fixes #29513
Traits should work.
Flashed myself without any protection, with sunglasses, when blind and with the trait. All worked as they're supposed to.
:cl:
fix: Flash protection trait will protect from flashes again.
/:cl:
=> Fix FLASH_PROTECTION trait not protecting against flashes.

code/game/gamemodes/miniantags/revenant/revenant_abilities.dm
Disables Revenant's Malfunction ability from working on emergency shuttle consoles.
Emagging the shuttle console is highly disruptive to the flow of the game. It should only ever be done by hijackers or under duress. A revenant is neither of those things.
Not tested, vibe coded. 95% chance it works.
:cl:
tweak: Revenants can no longer emag emergency shuttle consoles with malfunction
/:cl:
=> Disables Revenant's ability to emag the emergency shuttle console

_maps/map_files/RandomRuins/LavaRuins/lavaland_surface_nt.dmm, code/datums/weather/weather_types/lavaland_weather.dm, code/game/area/areas/mining_areas.dm
Provides the following fixes for volcanic activity:
- Boulders no longer target the shuttle layer **at all** and if they do, the check that sees if it breaks it now actually works again.
- Boulders will no longer hide tendrils (as was intended originally) and will now break before changeturf is called
- If lavaland is not loaded from config (for quick testing) it will no longer run a runtime every weather act.
as a side effect, a new are type has been made that acts like outside but will not be targeted by the storm:
/area/lavaland/surface/outdoors/outpost/no_boulder
boulders should be very dangerous, but should break certain things like shuttles.
threw boulders at shuttle, checked with debug mode if it skips no_boulder areas. Manually threw boulders at the shuttle. threw boulders at …
=> Volcanic Activity Fixes

code/datums/spells/bloodcrawl.dm, code/datums/spells/conjure.dm, code/datums/spells/construct_spells.dm, code/datums/spells/horsemask.dm, code/datums/spells/magnet.dm, code/datums/spells/mime_malaise.dm, code/datums/spells/wizard_spells.dm
Spelling and grammar fixes for wizard spells
I cast spel
I cast reading
:cl:
spellcheck: Fixed spelling/grammar issues in wizard spells
/:cl:
=> Wizard spells spelling/grammar fixes

code/modules/antagonists/cult/team_cult.dm
Allows cult fall to have more cultists on lowpop. When a cult would rise at 5, and fall it 1, it instead falls at 3.
Lowpop cult falling is REALLY unforgiving, because it expects there to be a higher population for the percentage.
It compiles
:cl:
tweak: Allows cult fall to have more cultists on lowpop
/:cl:
=> Allows cult fall to have more cultists on lowpop

code/__HELPERS/cmp.dm, code/datums/mapping/ruin_placer.dm
This PR modifies ruin placement to place required ruins in decreasing order by size.
Required ruins can still fail to place if no place can be found for them. Small ruins placed in the middle of large areas make it impossible for larger ruins to be placed, which is fine if we don't care if the large ruin is required, but if we're just iterating over required ruins, we should place them from largest to smallest to increase the guarantee that they all get placed as expected.
Lavaland currently has a lot of required ruins, and the largest one is the most important.
Ensured ruins placed in expected order. Before:
The list starts from the end and goes backwards, so the relay, a small ruin, would be placed, immediately followed by the legion gate, a large ruin. Given we randomize placement …
=> place required ruins in decreasing order of size

code/game/machinery/autolathe.dm, code/game/machinery/vendors/vending.dm
Attempting to deconstruct a shocked vendor or autolathe with a crowbar or crowbar-adjacent will try to shock you now instead of deconstruct the device. You can still deconstruct the shocked device with insuls.
Metal objects should be conductive.
Shocked a vendor. Tried to crowbar it apart. Got zapped again.
:cl:
Tweak: Stopped being able to deconstruct shocked devices without getting shocked.
/:cl:
=> Fixes deconstructing shocked devices without consequence

code/modules/hydroponics/beekeeping/beebox.dm
Allows sentient bees to enter hives by clicking on them (regardless of intent) and to leave them by moving. Also fixes Queen Bees not having their home set to the apiary. Fixes #29378
Shouldn't interfere with the AI pollination handling of bees, as that seems to be handled in their AI.
Sentience event can leave players stuck in an apiary. Homeless Queen Bee is sad.
https://github.com/user-attachments/assets/4c0a6296-7865-47fb-a7ff-99b627b4c991
Exited apiary, nuzzled a human, stung a human, entered the apiary.
:cl:
fix: Sentient bees can now enter and exit apiaries.
fix: Queen bee now gets its home set to the apiary it's placed in.
/:cl:
=> Allow sentient bees to enter and leave apiaries + fix queen bee home not being set

code/controllers/subsystem/SSstatpanel.dm
Closes #26363
Fixes error modsuits on statpanel (sorry for cyrillic)
`icon2asset` now receives icon state of a thing to render instead of always taking it as a `null`
this affects literally any atom btw, not only modsuits
proper icon render
no errors
also everything is kinda the same with other items? so i don't think it'll break anything
above
:cl:
fix: Modsuits on statpanel won't be rendered as "ERROR" anymore.
/:cl:
=> Statpanel properly renders modsuit control's icon

code/modules/mob/living/simple_animal/hostile/mining/hivelord.dm
`handle_automated_movement` relies on `Process_Spacemove` to check whether or not a mob is allowed to move. That's where gravity checks happen, lattice checks. With legions returning FALSE on it, they never go through these checks and will always fail movement. Fixes #29617
Functional AI good.
Loaded lavaland, observed legions moving around.
:cl:
Fix: Legions are capable of moving again.
/:cl:
=> Fix legions on lavaland not moving

code/modules/power/engines/singularity/particle_accelerator/particle.dm
OpenDream is adding `src` to the `SoftReservedKeyword` pragma: https://github.com/OpenDreamProject/OpenDream/pull/2307
This PR renames a `var/src` to `var/source`.
This pragma is currently an error on paradise, because using internal var names for declared var names is cringe.
bro it's a var rename
=> Rename a `var/src` to `var/source`

code/__HELPERS/game.dm
Removes a check which adds true observers to the mob list. Observers are already caught in a prior check (line 164) and checking a second time ends up returning a list with doubled observers.
Prevents getting doubled messages when visible_message, atom_say, or anything else that uses get_mobs_in_view.
https://github.com/user-attachments/assets/3e1efb22-00c3-4ac2-b502-3f77ca1b73e0
I tested speaking, emoting and attacking. All messages went through and reached the observer, whether the observer was orbiting or true observing. Also tested speaking and emotes from the same character the observer is true observing.
atom_say also goes through.
:cl:
fix: Ghosts won't get doubled messages when observing someone.
/:cl:
=> Fix ghosts getting double messages when true observing

code/__DEFINES/mob_defines.dm, code/datums/weather/weather_types/lavaland_weather.dm
Fixes acid rain penetrating mechas to damage players
Fixes players getting blown out of mechas
Adds define to check if mob is being inside a mecha (pilot or somehow else, like in that oddyseus' sleeper)
Fixes
Btw the fact that magboots/move resist don't protect you from wind kinda sucks and forces players to use mechas.. but they still don't since no one has reported these 2 bugs about mechas. just shows that people don't use them at all on lavaland cos they suck!!!
Was inside a mecha. No damage from acid rain. Walked out, started receiving damage. Equipped debug mod (is acid proof), no damage
Was inside a mecha. Was unaffected by wind. Walked out - it started.. blowing me, u know
:cl:
fix: Mechas now protect you from acid rain.
fix: Mechas now protect you from wind storms.
/:cl:
=> Fix mechas' immunity against lavaland's weather

code/modules/smithing/machinery/kinetic_assembler.dm
Fixes a wrong path for the scientific assemblers screwdriver interaction, adds missing closed wire panel icon states for both machines, makes both machines upgradeable by a regular RPED. Fixes #29605
Bugs bad. Lack of upgrades bad.
Unscrewed and screwed the 2 assemblers, upgraded both assemblers with a regular RPED.
:cl:
fix: Scientific and Kinetic assembler will appropriately update their icon state, whether their panel is open or closed.
fix: Scientific and Kinetic assembler are both upgradeable by a normal RPED.
/:cl:
=> Fixes Kinetic Assembler and Scientific Assembler's missing open closed states, makes RPED work on them

code/modules/antagonists/mind_flayer/powers/flayer_stealth_powers.dm
Title.
Fixes #28671.
Attack migration good.
Bug bad.
Spawned a borg.
Spawned an IPC, turned them into a mindflayer and gave them the silicon override spell.
Used it on the borg successfully.
:cl:
fix: Fixes the mindflayer Silicon Administrative Override ability not working.
/:cl:
=> Migrates the Mindflayer's Silicon Administrative Override to the new Attack Chain

code/_onclick/cyborg.dm
Fixes #28371.
Consistent behaviour with all other mobs.
Spawned in test_tiny.
Buckled myself to a chair and a janicart.
Was successfully able to use tools whilst buckled in both cases.
:cl:
tweak: Cyborgs can use tools whilst buckled (like every other mob).
/:cl:
=> Being buckled doesn't block borg tool and non-remote machine interaction

code/game/machinery/vendors/custom_vendors.dm, code/game/machinery/vendors/vending.dm
custom vendor now ignores abstract items (like slappers)
Prevents buggy, unpredictable behaviours.
Tipped vendors on myself, tried selling various things, tried selling a slapper and a grab.
:cl:
fix: Custom vendors will no longer accept abstract items for sale.
/:cl:
=> Various vending machine fixes

code/modules/mod/mod_control.dm
Now you can talk into/hear from radio that is located inside your modsuit's storage
Fix
Talked into radio with turned on broadcast. Could hear what i say
:cl:
fix: Radio inside your modsuit's bag is now working. You don't have to take the radio out of storage in order to talk/hear people.
/:cl:
=> Fix broken radio inside modsuits

_maps/map_files/RandomRuins/SpaceRuins/abandoned_engi_sat.dmm
With reference to the original engi sat map:
- Adds dead plants where there used to be potted plants.
- Adds vendors where there used to be vendors.
- Moves the carp plushie to the correct position.
- Adds a floodlight and heater.
- Adds a box of lightbulbs, a red toolbox (old).
- Adds an empty box of donk pockets.
- Adds a stack of metal, glass, and wood, and a flare.
- Adds a missing poster spawn.
- Adds a missing light.
- Rebuilds the cyborg recharger.
- Adds a missing linen bin.
- Adds a missing zippo lighter.
Also:
- Makes the solar array functional and provides a SMES for it to feed.
- Converts the upper airlock set into an airlock helper.
- Because of the above, the APC now starts with charge.
- Converts the blue toolbox into an old toolbox.
- Adds grilles to the external windows. …
=> Touches up the Abandoned Engineering Satellite

code/modules/mob/living/simple_animal/hostile/bees.dm
Prevents AI queen bees from leaving the apiary. From what I can tell, queen bees weren't intended to be able to leave their apiary and lack the code that lets them go back into one. Queen bees will not leave the apiary and their AI will remain idle, unless they've somehow been forced out of the apiary, either it being destroyed or admin shenanigans. Fixes #29608
Keeping the queen in the apiary lets you split her with royal jelly and change her reagent.
Watched bees for 30 minutes. Split a queen with royal jelly.
Sentient queen bees can leave the apiary and if they return into it, they're able to be taken out like normal.
:cl:
fix: Queen bees won't leave their apiaries on their own anymore.
/:cl:
=> Prevent AI queen bees from leaving the apiary

code/game/turfs/simulated.dm
Turf wet overlay will now have transformations reset. Fixes #29563 
It looks weird and jank.
Wetted the grass floor and a normal floor. It looked normal.
:cl:
fix: Wet overlay will now line up with grass tiles.
/:cl:
=> Add `RESET_TRANSFORM` to turf wet_overlay

code/game/machinery/vendors/generic_vendors.dm, code/game/objects/items/weapons/cigs.dm, code/game/objects/items/weapons/storage/fancy.dm
Moves rolling papers out of the contraband section of the smoking vendor.
Moves Midouri cigarettes into the contraband section of the smoking vendor.
Removes THC from medical weed, replaces with more CBD.
You can now smell the cannabis in Midouri.
Medical Weed helpfully informs the user that it is legal.
The legal weed product should not be illegal.
The illegal weed product should not just casually be on open sale. Swapping it with the thing that isn't illegal makes sense.
Inspected a vendor. Vigorously. With a screwdriver and multitool.
:cl:
tweak: Medical Weed 20 u THC 40 u CBD changed to 60 u CBD.
tweak: Medical Weed informs you it is legal.
tweak: Midouri cigarettes and packets now smell of weed.
tweak: Midouri cigarettes are now contraband.
tweak: Rolling papers are no longer …
=> Midouri Cigarettes are Contraband, Rolling Papers are not, Medical Weed is now Fully Legal Under Space Law

code/modules/antagonists/changeling/powers/mutations.dm
Automatic parrying was removed from the cling shield, this PR updates its description so it doesnt lie to players.
Lying is bad.
Viewed ingame
:cl:
fix: Cling shield description no longer says it can auto parry.
/:cl:
=> Update cling shield description so it doesn't claim it can auto-parry

code/modules/mob/living/carbon/human/human_mob.dm
Removes a check for new present flavor text. Flavor text will now always be updated when transforming, whether it's empty or full. Fixes #28135
Prevents clings from being meta'd through flavor text.
pre-transform
post-transform
Transformed from a flavorful moth into a flavorless human. My flavortext was empty. Transformed back into a flavorful moth, flavor text returned.
:cl:
fix: Flavor text will now clear itself properly when DNA is changed.
/:cl:
=> Fix flavortext not clearing itself if you transform into a flavorless person

_maps/map_files/stations/boxstation.dmm, _maps/map_files/stations/cerestation.dmm, _maps/map_files/stations/deltastation.dmm
This PR removes several cameras which were in maintenance areas.
Our [mapping design guidelines](https://devdocs.paradisestation.org/mapping/design/) are clear that AI cameras are not permitted in maintenance. Most of these cameras are in areas that are unambiguously maintenance tunnels. There are a handful of gray areas but I've gone with precedent and my own intuition with them:
1. Atmos checkpoints: are within maintenance areas, and boxstation does not include cameras for them, so I have removed them from elsewhere.
2. Cameras outside solars: The design guidelines state that the sole exception in the prohibition of cameras in maints is just outside solar maintenance. This prohibition was intended to only be for boxstation, but other maps have had cameras added in similar locations. I'd …
=> remove several cameras from maints

code/game/objects/structures/morgue.dm
Migrates the crematorium and morgue tray to the new attack chain.
Progress to the new attack chain.
Renamed and unnamed a morgue tray. Cut a tag off a morgue tray. Attacked and broke a morgue tray.
Renamed and unnamed a crematorium. Cremated a body. Attacked and broke a crematorium. Repaired a crematorium.
NPFC
=> Migrate crematorium and morgue tray to the new attack chain

SQL/paradise_schema.sql, SQL/updates/67-68.sql, code/__DEFINES/misc_defines.dm, config/example/config.toml
Optimise ip2group tables to use ints instead of varchars
Storing IPs and other info as strings is cringe, this makes joins and other updates so much faster. Theres no good reason to store them as strings when we can do the same with unsigned ints.
I'll need to update backend tooling after this is merged but that can wait.
Tried converting a copy of the prod dataset, all worked fine.
NPFC
=> Optimise ip2group tables to use ints instead of varchars

code/__HELPERS/paths/path.dm
This PR fixes a typo in /datum/can_pass_info's type declaration. This shouldn't have had any effect on pathing since the field's value gets clobbered in the constructor, but better safe than sorry.
Correct code good.
NPFC
=> fix a typo in can_pass_info decl

code/game/objects/items/tools/wirecutters.dm, code/modules/power/cables/cable_coil.dm
- Adds throwforce to wirecutters
- Removes throwforce from wires
That's it
- Wirecutters are solid, they should do some damage when thrown at your face.
- Wires are soft, they shouldn't do any damage.
G
Works fine, no runtimes noticed
:cl:
tweak: Wires now don't deal damage when thrown.
tweak: Wirecutters now deal damage when thrown.
/:cl:
=> Wires And Wirecutters Damage Tweak

code/modules/admin/topic.dm
Makes the lightning bolt smite behave better with the shock changes. It does this by shifting some of the damage from the forced burn to the electrocute act, and removes the forced weaken by relying on the stun + weaken from the electrocution.
It also plays a lightning bolt effect now.
If an admin lightning strikes someone, it should do the funny skeleton sprite. It also should be more obvious as to what happened to someone should they get bolted by god.
Smote a skrell.
:cl:
tweak: Tweaks lightning bolt smite to behave better with the new electrocute act
/:cl:
=> Updates Lightning Bolt Smite

code/modules/mob/living/carbon/carbon_update_icons.dm
Y offsets get swapped with X offsets when laying down. That results in offsets getting stacked together if you shift vertically while standing, then unshift when resting, eventually going visually off-screen.
Breaking the laws of physics isn't good. Makes fighting people impossible.
I used the Dwarf gene in a variety of ways, when standing, resting, when changing between the two. My offset updated appropriately and I didn't float away into any direction.
Tested vendor squashing, it doesn't reach that code.
:cl:
fix: Fixed a bug where offsets would stack incorrectly when switching between resting and standing.
/:cl:
=> [s] fix vertical offsets incorrectly stacking when switching between resting and standing positions

code/controllers/subsystem/SSevents.dm
This PR adds a VV button to active events in the event manager.
Lets me look at the thing at the place where I'm looking at it
Clicked button, ensured the relevant event's VV came up.
NPFC
=> add VV button to event manager

code/modules/shuttle/supply.dm
Adds an exclusion for conveyor belts in the handling of spawning supply crates.
Fixes #29646
Mapping in conveyors in the entirety of the supply shuttle, ordered crates.
:cl:
fix: Cargo crates can spawn on top of conveyor belts in the shuttle
/:cl:
=> Fixes conveyor belts blocking cargo crates from spawning

code/controllers/subsystem/non_firing/SSlate_mapping.dm
This PR ensures that old-school hardcoded controllers, such as the ones used in xenobio, are properly linked. I'm dumb and forgot about this in #29672. It's still good that this linkage isn't happening in LateInitialize (as the work for constructable chambers relies on that), but it has to happen _somewhere_. Despite hating them, varedited airlocks still need to be possible, because they permit for configurations that can't be done otherwise, such as the controller proper being outside of the airlock chamber, which isn't supported by dynamic airlock linkers.
Bugfix.
Spawned in Boxstation xeno, operated all linked machines of airlock chamber.
:cl:
fix: Airlock chambers such as xenobio's should work properly.
/:cl:
=> link varedited airlock controllers in latemapping

code/game/objects/items/weapons/storage/storage_base.dm, code/modules/mob/living/carbon/human/human_inventory.dm, code/modules/mod/mod_control.dm
Adds storage dumping inbetween storage items like bags, belts, boxes. There's a 0.3 second do after for each item, which gets canceled if the player moves.
QoL. It makes transferring items between storages easier, especially if they're not on you (eg transferring items between bags on the ground).
https://github.com/user-attachments/assets/bc4a6526-240f-4708-a36b-1f6245708756
Dumped a toolbox in my belt, my belt in a toolbox, dumped a bag into another bag on the floor, tried dumping a modsuit without a bag and into a modsuit without a bag.
Shuffled boxes inside my inventory without dumping contents into each other.
:cl:
add: Storage dumping between storage items.
fix: roundstart in backpack items will now be marked as in_storage
/:cl:
=> Adds storage dumping

code/_globalvars/_regexes.dm, code/modules/mob/mob_say_base.dm
Changes the language parsing to not allow language switches that start in the middle of a word or number.
Mostly so it won't eat anomaly codes when they happen to overlap with a language you know.
See above.
:cl:
tweak: You can no longer switch languages in the middle of a word or number; the character before the language selector has to be a space or some sort of punctuation. Notably, this means you can now say an anomaly's code is 4.1 without having to worry about whether you know sol common (and other similar language issues).
/:cl:
=> Prevent language-switching in the middle of a word or number.

code/game/jobs/job/job.dm
This PR fixes a runtime encountered when equipping ERT members.
Bugfix for noisy runtime.
Sent a single amber Commander ERT team and signed up for it. Ensured that runtime did not occur.
NPFC
=> fix runtime in ERT equip

code/__HELPERS/mob_helpers.dm
Adminghosts can now ctrl+click blob cores to open their player panel.
Admin tooling good.
Made blob.
Ctrl+clicked as adminghost.
:+1: 
:cl:
fix: Adminghosts can now ctrl+click blob cores to open their player panel.
/:cl:
=> Make it easier to get blob player panels.

code/modules/atmospherics/machinery/components/unary_devices/vent_pump.dm
The `/obj/machinery/atmospherics/unary/vent_pump/siphon` and `/obj/machinery/atmospherics/unary/vent_pump/siphon/on` vent subtypes are used in mapping to create vents that siphon by default, like the one in the xenobiology slime kill chamber. Unfortunately, siphon vents respect the external pressure bound, so if there's normal air in the room, these vents will do nothing by default. Farragus alone had the necessary override to set this to 0.
Since the intent of the mapper is clearly to make a vent that siphons, this sets the default pressure bound to 0, so that they actually siphon. 
Mapping objects should work in the way that they appear to.
Turned down the cooler in xenobiology on Cyberiad. Slime kill chamber worked as expected.
:cl:
fix: Mapped-in vents that appear to siphon will now …
=> Make all siphon vents siphon

_maps/__MAP_DEFINES.dm, code/__DEFINES/dcs/global_signals.dm, code/controllers/subsystem/non_firing/SSmapping.dm, code/game/machinery/tcomms/tcomms_core.dm, code/modules/space_management/space_level.dm, code/modules/space_management/turf_reservation.dm, code/modules/space_management/zlevel_manager.dm
This PR adds a z-level trait which is checked by tcomms relays. Z-levels with this trait will always receive radio messages, regardless of whether there's a relay on them. It refactors a bit of the surrounding code, adding the ability to specify required traits in a turf reservation and ensuring a z-level with those traits exists before creating a new one. It makes the signature for the new z-level signal more explicit, and has tcomms cores register to listen for when they get added, since that can happen whenever one is requested. Fixes #29653.
Allows transit z-levels to have tcomms as expected, but doesn't force all new space levels to have one, so admins can still have their events on levels that are out of radio range.
Got on mining shuttle, sent a radio message when in transit. …
=> ensure space transit z levels receive comms

_maps/map_files/stations/cerestation.dmm
Moved a firelock on Farragus Holodeck one tile down so it is over a door instead of a window.
Inconsistent firelock positioning probably a mapping error, and mapping errors are bad.
Booted up testserver, checked location of firelock
:cl:
fix: Moved a firelock on Farragus holodeck to the correct position
/:cl:
=> Moved Farragus Holodeck firelock to the correct position

code/datums/datumvars.dm, code/game/atom_vv.dm, code/modules/mob/mob_vv.dm
This PR puts the "admin renaming" (that properly modifies name, real_name, ID, datacore, etc) link for mobs back as the large version of their name in the VV's header. I modified these in #29673 because the header is inherited and the link is different for mobs versus other objects, and the naive real_name var editing link didn't seem useful when the admin renaming link existed. This is all back to what it should be now.
It also fixes drop down options for lists not being present.
Makes sure links work as expected for admins.
NPFC
=> vv refactor day 1 patch

code/game/objects/effects/spawners/random/pool/pool_spawner.dm
This PR fixes pool spawners deleting themselves and spawning their items in nullspace. idk why I even wrote this, I know full well they handle spawning in late mapping so they can't be qdel'd this early.
Bugfix.
:cl:
fix: Items in pool spawners, such as space loot and Lavaland mobs, should now spawn properly.
/:cl:
=> fix pool spawners deleting themselves way before they should

code/__HELPERS/unsorted.dm
This PR removes "pixloc" from the list of vars dynamically copied to objects when loading holodeck presets.
First bugfix as a result of running 516 on the server?
See above
:cl:
fix: The holodeck should load scenes properly again.
/:cl:
=> fix holodeck runtiming on load

.github/workflows/ci.yml, _build_dependencies.sh, code/__DEFINES/rust.dm, code/_compile_options.dm, rust/Cargo.lock, rust/Cargo.toml, rust/src/lib.rs, rust/src/milla/api.rs, tools/ci/build_all_rustlibs.sh, tools/ci/install_byond.sh
Does what it says on the tin. 
Should probably TM because I also bumped the rustlibs crate, though initial testing showed it is fine.
No more legacy compat. Makes `!build_rust` twice as fast.
N/A
Started the server, joined, seems to work.
add: BYOND 516 is now the minimum build version
/:cl:
=> Bins off 515

code/modules/mod/mod_types.dm, code/modules/mod/modules/modules_general.dm
Adds some nice modules to default pins
Stabilizes jetpack module by default - it's better on than off and you don't anymore have to do like 6 clicks every single time to enable stab
Removes resistance flags from magnate mod, flags are added on Initialize() by magnate's theme, no need to duplicate it
Removes empty req_access from prototype mod (did nothing)
Jetpacks should be pinned by default, they drain battery by a lot and you want to switch their states in 1 click or even bind it to some key
All modsuits now have their jetpacks pinned - was weird that it vary from mod to mod
Compiles. Selected debug mod, it had pinned jetpack module and i wasn't drifting in space
:cl:
tweak: Some modsuits now have more pinned modules by default.
tweak: Jetpack modsuit module is now stabilized by …
=> Tweak modsuit's pinned modules and stabilize jetpack by default

code/modules/mining/machine_redemption.dm
Makes ore redemption machines take in sheets from the input side. Sheets go through the material containers' `insert_stack` proc, like it would if it was manually inserted by a player. There, sheets that aren't accepted by the ORM get filtered out, meanwhile accepted sheets are inserted into it.
Invalid sheets will get spit out the output side, with a buzz and a message notifying crew that the material is invalid. Also, prevents needless processing if someone dumps 100 invalid stacks in the input.
With the Smith being responsible to bring refined materials up to station, there's a lot of tedium in inserting all the sheets in the ORM. This will permit smiths to just dump a crate of mats in the input, much like miners do with ore.
https://github.com/user-attachments/assets/932e1aa7-4aaa-4991 …
=> Tweak: Makes ore redemption machines take in sheets from the input side

code/modules/mob/living/silicon/robot/robot_defense.dm
This removes the flash_eyes call from robots when they are attacked by slimes. Currently robots receive an 80% flash, confusion, and damage every time they're attacked by a slime. This allows even a baby slime to stamcrit a borg in 3 hits.
Slimes should not inflict a 4-second confuse + 40 stamina damage + temporary blindness melee attack against a cyborg while also being healed by burn damage.
Assume control of a cyborg.
Spawn a slime (a gray baby is fine).
Attack the slime to aggro it.
Don't be blinded when attacked by the slime.
:cl:
del: Removed the flash effect when slimes attack bots
/:cl:
=> Removes flash from slime attacks against bots

code/modules/mining/equipment/mineral_scanner.dm
Fixes #29604
Brings mining productivity back up to normal levels
1. Spawned the following items: mesons, night vision mesons
1. Spawned the following objects: manual mining scanner, advanced automatic scanner, APLU Firefighter with mining scanner module
1. Tested that every combination worked and showed ores as expected
:cl: cdui
fix: mesons don't show mining scanner-highlighted ores located behind walls
/:cl:
=> Fix mesons not showing ores behind walls

code/modules/mob/living/carbon/human/human_mob.dm, code/modules/mob/living/silicon/robot/robot_mob.dm, code/modules/reagents/chemistry/reagents/drinks_reagents.dm
Gives medical examinations a message if theres no issues, Makes rapid pointing work with all coffees, and gives borgs a message when manually charged
giving some QOL to the QOL pr
examined, drank some coffee, and charged some borgs
:cl:
tweak: Tweaked some job perks in a minor way
/:cl:
=> Some Job Perk Tweaks

code/game/machinery/machinery.dm
Fixes one missing argument causing part replacers to delete replaced beakers instead of storing them
Sending parts into nullspace incurs costs
- Spawned a ChemMaster
- Spawned a tier 4 bRPED
- Upgraded the ChemMaster and checked that small beakers are stored in the bRPED
:cl: cdui
fix: part replacers (RPEDs) delete replaced beakers
/:cl:
=> Fix RPEDs delete beakers

code/modules/awaymissions/mission_code/ruins/telecomns.dm, tools/ci/check_legacy_attack_chain.py
This PR fixes #29743. It also makes the attack chain CI a tiny bit better at finding bad uses of legacy procs.
Bugfix.
Spawned in as assistant, spawned an AI, aghosted into the AI, aghosted back to the assistant, spawned a remote AI upload and "oxygen is toxic to humans" module, used the upload in hand, selected the AI, and used the module on the AI upload. Ensured I got the "Upload complete" message.
:cl:
fix: The remote AI upload loot from DVORAK should now work as expected.
/:cl:
=> fix dvorak remote ai upload not working

code/__HELPERS/unsorted.dm
Blacklists the pixloc var from being duplicated in perfect copy `DuplicateObject` proc. Pixloc also changes the `loc` var which moves items back to Z1, causing them to get deleted. Fixes #29818
Holodeck works.
image
:cl:
fix: Holodeck items will spawn again now.
/:cl:
=> Fix HoloDeck items not spawning

code/modules/mob/living/carbon/carbon_procs.dm
Fixes being null spaced at the end of the timer if the vent you're entering gets removed
Bug fixes #29711 good, null spacing bad
Started to enter a vent, unwrenched the vent before i entered the vent, didn't get nullspaced
:cl:
fix: Fixed vents null spacing you if they get removed while you're crawling into it
/:cl:
=> Fixes being null spaced when vennting into a unwrenched vent

code/modules/station_goals/dna_vault.dm
Lets "basic mobs" be DNA sampled, some examples are: All the nether world mobs, the cow and pig and deer. This list is soon to expand to most naturally spawning mobs, so best fix this now
bug fixes #29762
DNA sampled some basic mobs, and simple mobs, both worked, both counted on the vault
:cl:
fix: Fixed basic mobs not counting as compatible mobs with the dna vault
/:cl:
=> Fixes basicmobs not counting for DNA samples

code/modules/mob/living/carbon/human/human_mob.dm, code/modules/mob/living/carbon/human/species/_species.dm, code/modules/mob/living/carbon/human/species/diona_species.dm, code/modules/mob/living/carbon/human/species/drask.dm, code/modules/mob/living/carbon/human/species/machine.dm, code/modules/mob/living/carbon/human/species/vox.dm
Fixes #29778
Corrects an oversight
- Spawned humans, changed their species and lobbed them at a spinning turbine
:cl:
fix: Moves the species behaviour of compressor grinding to the species datum(oversight fix)
/:cl:
=> Moves the compressor grind  special species actions to the species datum

code/controllers/subsystem/non_firing/SStitlescreen.dm
Adds debug logging for the title screen file chosen.
Reasonable thing to log, and may help us track down #29769.
Booted server. Opened game.log. Saw log entry.
NPFC
=> Add logging for the splash screen selected.

tools/requirements.txt
Unpins most of our tools' python dependencies
Some of the versions we were requiring are old enough that they are incompatible with newer systems. By allowing the tooling to use newer versions where available, we let them keep up to date without having to micromanage their versions over time. The downside is that there's a chance a newer version will break things, but as we've already seen that *old* versions break things, too, it seems reasonable to take the risk.
Made a commit. Hooks ran. Stuff built. Commit completed.
NPFC
=> Unpin most of our tools' python dependencies

code/game/objects/items/weapons/RCL.dm
Migrates the RCL to the new attack chain. Fixes inhands not getting updated when filled/runs out.
New attack chain, no schrodingers cable layer.
Loaded a cable layer, screwdrivered a cable layer, laid cable automatically and manually, refilled a cable layer.
:cl:
fix: Cable layer will update its in-hand sprite appropriately when it's filled or runs out.
tweak: Added extra messages for what's happening to the RCL.
/:cl:
=> Migrate Rapid Cable Layer to new attack chain and fix inhands not getting updated

code/modules/admin/topic.dm, code/modules/mob/dead/observer/observer_base.dm
Admin FLW links will no longer runtime if you are an observer.
Admin FLW links will now give a nicer message if you click them while alive and unable to aghost.
Admin FLW links will successfully follow after triggering an aghost.
Admin FLW links will now work slightly faster, as there was a pointless `sleep(2)` in them.
Runtimes bad. Working things good.
Tried to FLW myself from the lobby.
Tried to use an old FLW link while de-adminned.
Used a FLW link to immediately start orbiting my body.
Tried to FLW out of my body with only mentor permissions.
The mentor one is a bit odd, since they can use OBS, but it at least demonstrated that the permissions check worked.
:cl:
fix: Admin FLW links work the first time, even if they trigger an aghost.
/:cl:
=> Saner FLW links.

code/game/objects/items/weapons/grenades/frag.dm
Returns the behavior of the frag grenade to what it should be. 
Because a frag grenade should be a frag grenade and not a stinger grenade.
I haven't done it yet, I was not at my desktop for this one.
:cl:
fix: Fixed frag grenade acting like a stinger grenade
/:cl:
=> Fixes Frag Grenade Behavior

code/modules/research/xenobiology/xenobiology_organs.dm
Fixes an xeno organ duplicate definition where shivering was called where sweating should have been.
Produces correct behavior based on conditions.
I haven't yet. I was too busy watching the qualifier.
:cl:
fix: Fixed xeno kidney behavior based on body temperature
/:cl:
=> Fixes unintended behavior for xeno kidney organs

_maps/map_files/RandomRuins/SpaceRuins/abandoned_engi_sat.dmm
Converts the airlock spawner in the Abandoned Engi Sat into a dynamic airlock.
Allows the ruin to be rotated without the airlock bugging the hell out and spawning off to the side somewhere.
Looked at the airlock in differently rotated version of the ruin. Pushed some buttons. It worked.
:cl:
fix: The abandoned engi sat secondary airlock no longer sometimes spawns off to the side from where it should.
/:cl:
=> Fixes Abandoned Engi Satellite Secondary Airlock Spawning Wrong if Ruin is Rotated

code/modules/mob/living/basic/retaliate/clown.dm
Remedies clown mob AI to not only have the targeted victim retaliate, but the whole circus as well.
Basic mob AI should contain all the behaviors of prior AI implementations.
Attacked a clown. Got honked by him and his troupe.
:cl:
fix: Fixed clown mob retaliation to affect all nearby clowns
/:cl:
=> Fixes clown mob group retaliation

code/game/jobs/job/support.dm
This PR fixes the "Shaft Miner (Equipment + MODSuit)" entry in the admin "Select Equipment" menu. This was still equipping a softsuit and backpack, which was clobbering the modsuit assignment.
Bugfix.
Used select equipment menu, selected entry, ensured modsuit spawned, and miner equipment was placed in modsuit storage.
NPFC
=> fix admin equipment for shaft miner modsuit

code/modules/mob/living/basic/retaliate/clown.dm
Gives clown mobs a language so they don't speak only gibberish.
You should understand what a mob says.
Spawned clowns. Listened.
:cl:
fix: Fixes clown mob languages
/:cl:
=> Fixes Clown Mob Language

code/datums/spells/alien_spells/basetype_alien_touch.dm, code/datums/spells/alien_spells/corrosive_acid_spit.dm
Makes the xenomorph related in hand spells not appear to be magical
So if a human/xeno is holding the corrosive acid that queens and drones can use, it'll appear on inspect as "[pronoun]'s [left/right] hand is dripping with vile corrosive goo!"
And if a human uses the hijacked organ, on inspect it'll appear as "[pronoun]'s [left/right] hand has a shimmering mirage around it!" (this one could be subject to change with how powerful the spell is, and how unassuming the warning text is)
Fixes #29736
Xenomorphs dont.. well, those things dont usually use magic.. so it shouldn't appear as if xenomorphs are "holding" magic related stuff
Same with the hijacked version, its not /meant/ to be magic, so it shouldn't appear as such
inspected the corrosive acid in hand spell inspect, and the burning …
=> Alien hand 'spells' are no longer magical

code/datums/elements/strippable.dm
This PR fixes alternate strippable actions not working.
Bugfix.
:cl:
fix: Alternate actions on the strip menu, like setting suit sensors and modifying internals, should work as expected.
/:cl:
=> fix strippable actions not working

code/modules/atmospherics/machinery/components/unary_devices/vent_scrubber.dm
This cleans up procs in vent_scrubber.dm by handling it under one definition instead of two.
What is good for the codebase is good for the game. This prepares us for new CI to detect and prevent duplicate proc definitions.
Compiles.
Deleted a few active scrubbers.
NPFC
=> Refactors destroy() in vent_scrubber.dm

code/modules/asset_cache/assets/asset_paper.dm, code/modules/asset_cache/assets/asset_safe.dm
Enables the legacy flag on a few simple assets.
Fixes asset delivery (hopefully) for a few things like stamps and the safe.
Testing via TM
EDIT: Changes have fixed the problem.
:cl:
fix: Fixed Stamps and safe dial so they appear in game again.
/:cl:
=> Fixes Stamps and Safe Dial Rendering

code/_onclick/cyborg.dm
Allows robot mobs to use alt-shift-click.
There are multiple objects with alt-shift-click mechanics that maintenance drones and engiborgs cannot use:
- Enabling detailed information reporting on gas analyzer.
- Flipping windoors to change the direction they open into.
- Controlling the light bulbs on constructable fish tanks.
- Changing the gathering method on RPEDs and ore satchels (which also applies to mining cyborgs).
- Most importantly, being able to flip pipes, atmos devices, disposal devices, and transit tubes when constructing these systems.
Spawned a collection of atmospheric devices and tubes, flipped them all.
Began construction of a windoor, successfully flipped it.
Built a fishtank, turned on the light.
Toggled advanced scanning on my gas analyzer, marvelled at the extra data …
=> Enables Robot Alt-Shift-Click

code/modules/research/xenobiology/xenobiology_dissections.dm
fixes an oversight in which xenomorphs were set as having no xenobio organs too early
you should be able to get all the organs from a xeno, as intended
removed a lot of xeno organs
:cl:
fix: Xenomorphs can now have all organs removed from them now
/:cl:
=> Xenomorphs can have all organs dissected now

code/game/gamemodes/game_mode.dm
Updates the discord messaging hook to include a round ID for the round that was just completed.
Gives a quick reference to the previous Round ID
What's that? (Can't be tested normally)
NPFC
=> Updates a message for #new_round_alert

code/modules/mob/living/brain/MMI.dm
When inserted into a silicon mob, MMIs, robobrains, and positronic brains will early-return their `emp_act()` and take no brain damage as a result.
Silicon mobs themselves are completely unaffected by brain damage, and there is also no way to repair brain damage in a silicon mob without completely deconstructing them.
There is no way to tell how much brain damage has accumulated, and the effects of accumulated damage only manifest upon deconstruction. This is very silly.
Mag dumped a cyborg with an ion rifle.
Deconstructed it.
Checked for brain damage, there was none.
:cl:
tweak: MMIs, robobrains, and positronic brains do not take damage whilst inside a silicon mob.
/:cl:
=> Gives MMI/Robobrain/Posibrain EMP Immunity Inside Silicon Mobs

code/modules/reagents/reagent_containers/dropper.dm
Adds 2 humorous messages when embalming a headless corpse. The embalming will fail, since there's no head. Fixes #29758
Dripping into non-existent eyes is immersion breaking and this is humorous.
Message shown to user
Bystander message
Images + Retested after fixing the head check.
:cl:
tweak: You can no longer embalm headless corpses with a dropper. Should be injected with formaldehyde.
add: Added fail messages for embalming headless corpses.
/:cl:
=> Tweak: Makes embalming headless corpses with a dropper no longer possible. Adds 2 fail messages for embalming a headless corpse with a dropper.

code/modules/admin/admin_verbs.dm, code/modules/mob/mob.dm
- Trying to observe someone while observing someone else will no longer require you to click the button twice, it will just switch.
- Observers can now use the face-direction hotkeys to change what direction they're looking.
Observer quality of life
Spawned in some mobs, switched between observing them. Then spun around in place :)
:cl:
fix: Trying to observe someone while observing someone else will no longer require you to click the button twice, it will just switch.
fix: Observers can now use the face-direction hotkeys to change what direction they're looking.
/:cl:
=> Observer tweaks

code/modules/atmospherics/gasmixtures/gas_mixture.dm, code/modules/atmospherics/machinery/datum_pipeline.dm
* Removes a runtime in `share_many_airs` that does not and cannot provide any useful context for tracking down what it's complaining about. The runtime would trigger continuously for minutes once fired, and had an absurdly long message, flashbanging anyone with runtimes displayed in their chat log.
* Added some `QDELETED` checks to `/datum/pipeline/proc/reconcile_air`, which is the sole caller of `share_many_airs`. This prevents the nulls that were tripping the above runtime, and ensures that deleted valves and connectors do not transmit air.
* Removed `as anything` from `share_many_airs`, since we were doing `istype` immediately after anyway. Added QDELETED checking as well, for extra safety.
Runtimes bad, correctness good.
Started an SM as AI, used buildmode to delete assorted pieces of …
=> Prevent qdeleted pipelines and machinery from sharing air.

code/game/gamemodes/miniantags/revenant/revenant_abilities.dm, code/game/objects/structures/morgue.dm
Revenant glassbreaks no longer are centered on the revenant. Instead, defile will cause crew within a nearby area to be the center of the glass breaks. The glass break range has been decreased from 4 to 3, however normal revenant defile range is unchanged. Additionally, adds a cosmetic effect around crew when defile is triggered for added feedback.
Additionally, defile can now open up bodybags and morgue trays at a 20% chance. 
Revenant's defile is far too opressive for a medium. For practically zero risk, the revenant can break every single window on station and make massive swaths of the station uninhabitable. Since this isnt targeting specific crew, all this is doing is annoying players by making many areas inaccessible, without generating bodies for the revenant. This also creates …
=> Revenant Defile Tweaks

_maps/map_files/shuttles/ferry_meat.dmm
Fixes a tiny spelling mistake in ferry_meat.dmm
Meat Ferry fans will be sobbing with joy
Eyes
:cl:
spellcheck: Fixed a tiny spelling mistake in ferry_meat.dmm
/:cl:
=> ferry_meat.dmm minor spelling fix

code/datums/chatmessage.dm
Adds a null conditional operator to prevent a runtime.
```
[2025-08-07T08:28:25] Runtime in code/datums/chatmessage.dm:170: Cannot read null.seen_messages
proc name: finish image generation (/datum/chatmessage/proc/finish_image_generation)
src: /datum/chatmessage (/datum/chatmessage)
call stack:
/datum/chatmessage (/datum/chatmessage): finish_image_generation
/datum/callback (/datum/callback): Invoke
Runechat (/datum/controller/subsystem/timer/runechat): fire
Runechat (/datum/controller/subsystem/timer/runechat): ignite
Master (/datum/controller/master): RunQueue
Master (/datum/controller/master): Loop
Master (/datum/controller/master): StartProcessing
```
Less runtime and function behavior good.
Haven't tested it yet (will end up TMing).
NPFC
=> Fixes a runtime for runechat messages

code/datums/components/action_item_overlay.dm
Fixes a bug that would cause overlays to get stuck .
Fixes: #29809 
Overlays should work properly
Spam an action button while growing some plants
Remove the plants
Overlays all get removed properly.
:cl:
fix: Overlays no longer get stuck on botany trays and beakers
/:cl:
=> [FIX] Overlays no longer get stuck on botany trays and beakers

code/modules/mob/living/basic/basic_mob.dm, code/modules/mob/living/simple_animal/simple_animal.dm
Shadow demons, slaughter demons, and any other basic or simple mob that deletes its corpse on death no longer breaks the client's rendering if they died while inside a clown car, vehicle, mech, or other object.
Fixes #29952
Bugs bad
Spawned as a shadow demon. Jumped into a clown car. Spawned lights. Burned to death. Did not have rendering break.
:cl:
fix: Fixed rendering breaking if a mob that deletes on death dies inside a TG vehicle
/:cl:
=> Fixes dead demon rendering when dying in a clown car

code/modules/mod/mod_control.dm, code/modules/mod/mod_link.dm, code/modules/mod/mod_types.dm
Constructed modsuits / printed mod scryers start linked. This makes them not require having to find someone with a modsuit to set them up, needlessly complicating the system.
The neck scryers use 1/4th the power now, going from 100 seconds to 400 seconds with the standard 10k battery.
They are very inconvient to use on rounds without the trait, leading to them rarely getting setup.
Additionally during the trait, they run out of juice far too fast. This should help.
Built modsuit / modlink, linked.
I didn't test the power drain, but the math checks out. If 50 is not 1/4th of 200, we have an issue.
:cl:
tweak: Modsuits and mod scryers that are built / printed start on the NT network.
tweak: Mod scryers had their power leak fixed, and now NT assures you they last 4 times as long as the …
=> Does the changes to the scryer system I forgot to do

.gitattributes, .github/workflows/merge_upstream_master.yml, tgui/bin/tgui, tgui/bin/tgui_.ps1
- Deprecates the tgui bundle merge driver. I dislike the merge driver for the following reasons,
- The merge driver runs once for every single conflicted bundle file. For instance, if `tgui.bundle.css` and `tgui.bundle.js` are both conflicted, then two Yarn builds will be triggered by the merge driver. Two or more Yarn builds are excessive because just one Yarn build already rewrites all of the bundle files and resolves any conflicts. Locking the bundle files such that only one Yarn build is triggered even if multiple files are conflicted involves non-trivial code which I am not willing to implement
- The merge driver runs asynchronously. Merge drivers should never run asynchronously. Merge drivers must resolve the conflicts before the merge commit is created, and running asynchronously …
=> Fix !merge_upstream

code/modules/mob/living/carbon/give.dm
Give actions click intercept will now return true, preventing the attack from happening.
Trying to give someone something currently also beats them.
Tried giving an item to a mob, it didn't beat the mob.
:cl:
fix: Giving items will no longer beat people.
/:cl:
=> fix give click intercept not cancelling attack

SQL/updates/69-70.sql
Adjusts the 69-70 SQL update script to properly remove rank and permissions from "Removed" admins.
This was an oversight in the original script: the old code would assign a "Removed" rank to admins who should not have powers anymore, and ignore any permissions set for them. The proper way to do this now is to not give them a rank or permissions at all. The updated script does that.
This has no impact on us, as we've already applied the script and corrected the issue, but will hopefully avoid some headaches for downstream servers.
[db_update_test_mk2.txt](https://github.com/user-attachments/files/21706329/db_update_test_mk2.txt)
NPFC
=> Removed admins should stay removed.

code/controllers/subsystem/SSstatpanel.dm, code/modules/mob/mob.dm, code/modules/mob/new_player/new_player.dm
Adds the pre-game status panel information to pre-game observers during pre-game.
It's pretty silly that ghosts can't see how long it is until the game starts.
Looked at stat panel as admin new player before round start.
Looked at stat panel as de-adminned new player before round start.
Looked at stat panel as admin ghost before round start.
Looked at stat panel as de-adminned ghost before round start.
Looked at stat panel as admin new player after round start.
Looked at stat panel as de-adminned new player after round start.
Looked at stat panel as admin ghost after round start.
Looked at stat panel as de-adminned ghost after round start.
All as expected, no runtimes.
:cl:
add: Ghosts can now see pre-round data until the round starts, just like people in the lobby.
/:cl:
=> Pregame info for ghosts

code/modules/research/xenobiology/xenobio_camera.dm
Increases max slimes in the xenobio console to 6 from 5
It makes it just a touch easier to manage. If you keep 2 slimes in a pen, they make 8 offspring. if you want to keep a population of 2, you need to make a trip of 5 and a trip of 1 and its just slightly annoying. Now you can do it all in one trip.
single number change. Compiled.
:cl:
tweak: Raised xenobio console max slime cap.
/:cl:
=> Xenobio Console Slime Cap tweak

code/modules/admin/admin_ranks.dm
Removes an errant debug message
The message wasn't.
CI will suffice.
NPFC
=> Remove an errant debug message

code/game/objects/items/weapons/extinguisher.dm
Lets extinguishers get stored when clicking a backpack with the safety off. Fixes #28457
Mechanical restrictions on storing unsafetied extinguishers weren't intended in the original PR.
I put an active extinguisher inside a backpack.
:cl:
fix: Unsafetied extinguishers can be clicked into storage again.
/:cl:
=> fix extinguishers not going into backpack when safety is off

code/datums/spells/bloodcrawl.dm
Exiting bloodcrawl changes you back to your old color.
Atomized from #30081
Weird edge cases annoy me.
It works.
:cl:
fix: Colored mobs stay colored after exiting bloodcrawl.
/:cl:
=> Colored mobs stay colored after exiting bloodcrawl

code/game/objects/items/storage/storage_base.dm, code/modules/mob/inventory_procs.dm
Prevents dragging items being nullspaced when they are dragged to a slot with a missing hand from inventory.
Fixes https://github.com/ParadiseSS13/Paradise/issues/30086
Missing items bad. Potential exploits also bad.
Chopped off hand, tried to drag a belt into that slot.
:cl:
fix: Fixed nullspacing inventory items with missing hand.
/:cl:
=> Fixes nullspace inventory issue

code/datums/status_effects/debuffs.dm, code/modules/mob/living/simple_animal/hostile/megafauna/bubblegum.dm
Fixes runtimes in `STATUS_EFFECT_BUBBLEGUM_CURSE` cos of executing code after `qdel()`
Fixes an issue when dead hardmode bubblegum would still teleport you to the arena pretending he is still alive (hardlock for players, no way to get out)
Fixes an issue when dead hardmode bubblegum would teleport himself back to the arena, not giving you his body
These are fixes
@Qwertytoforty NO ONE USES HARDMODE THESE DAYS!!!!!!!
Tested on local server, no runtimes, i escaped his arena once i killed him and i also received his dead body
:cl:
fix: Fixed broken hardmode Bubblegum. You can di-.. i mean, enrage him again!!
/:cl:
=> Fix bubblegum's hardmode

code/modules/admin/misc_admin_procs.dm
Changes the announce sound from adminhelp to the vote sound (server_alert.ogg)
It's less jarring.
Yes, i announced to just myself
:cl:
tweak: Changes the announce sound from adminhelp to the vote sound
/:cl:
=> Changes the announce sound from adminhelp to the vote sound

code/game/atom/atom_tool_acts.dm
Some pipes no longer runtime on installation (i.e. transit pipes). This is because they were returning `3` to the higher parts of the chain, which only expected 1 or 2. This is a side effect of allowing the RPD to detect if a piece was really installed or not with auto-anchor. No other tool_act uses this, and I suspect they won't want to. So we're switching over to this.
Kills quite a few runtimes of transit tubes taking damage after deletion
Spawned in transit pipes, screwed em down, no more runtimes/hitting them on installation.
:cl:
fix: Transit pipes no longer get hit by screwdrivers when installing them
/:cl:
=> Some pipes no longer runtime on installation

code/modules/atmospherics/machinery/airalarm.dm
Fixes #28283.
Fixes #25953.
Fixes an issue with the central atmospheric computer where any non-AI silicon that tried to open an air alarm from the interface would fail unless the air alarm was within their direct line of sight. This issue was introduced at some point during the TGUI updates of 2024 (TGUI 4 I think).
Bugs are bad.
Accessed an air alarm as a skrell. Walked away and the UI closed.
Accessed the central air computer as a skrell. Opened an air alarm remotely with it.
Accessed an air alarm as a cyborg. Walked away and the UI became inactive as soon as it was no longer in view.
Accessed the central air computer as a cyborg. Opened an air alarm remotely with it.
:cl:
fix: Cyborgs can use the central atmospherics computer to remotely control air alarms without needing to be able to …
=> Fixes central atmospheric computer not opening air alarm panels for non-AI silicons unless they have direct line of sight of the air alarm

code/modules/awaymissions/mission_code/ruins/telecomns.dm
Malf secborgs don't claw you while bashing you to death with a baton.
Bugs bad.
https://github.com/user-attachments/assets/d545abf3-ed44-4939-b0e9-127d032d1443
:cl:
fix: Fixed malf borg mobs double attacking with their stun baton
/:cl:
=> Fixes double attack on malf secborg mobs

code/game/machinery/cryopod.dm
Adds the grapple arm, intergrated laser(and advanced), and the shrapnel cannon to the cryopod item blacklist
These items are implants/not meant to exist outside of the body, so shouldn't be preserved.
fixes #30088
cryoed with the items out, saw none entered the storage
:cl:
fix: Fixed a few mindflayer related items being put into cryo storage 
/:cl:
=> Adds a few mindflayer related items to the cryopod storage blacklist

code/__HELPERS/game.dm
Makes `collect_nested_mobs` set its next layer, so it s actually recursively going through things. Fixes #29957
Proc does what it should do. Holoparas can hear and see stuff when inside host.
Tested each message type while inside the host and outside the host.
:cl:
fix: Holoparas can hear emotes, messages and actions inside hosts again.
/:cl:
=> fix next layer not getting set in collect_nested_mobs

code/modules/buildmode/submodes/advanced.dm, code/modules/buildmode/submodes/area_edit.dm, code/modules/buildmode/submodes/basic.dm, code/modules/buildmode/submodes/copy.dm, code/modules/buildmode/submodes/fill.dm, code/modules/buildmode/submodes/portal.dm
Improves buildmode logging with admin_spawned var for several buildmodes.
it clarifies that stuff created by buildmode are adminspawned
It works
NPFC
=> Improves buildmode logging

code/modules/awaymissions/mission_code/ruins/deepstorage.dm
fixes #30102
bugs bad, rare one of a kind(mostly) item, you should be able to obtain it
killed and butchered the fleshling, got the organ
:cl:
fix: Fixed fleshlings not dropping the regenerative mesh on butcher
/:cl:
=> Fixes fleshlings not dropping the regen mesh on butcher

_maps/map_files/stations/boxstation.dmm, _maps/map_files/stations/cerestation.dmm, _maps/map_files/stations/deltastation.dmm, _maps/map_files/stations/emeraldstation.dmm, _maps/map_files/stations/metastation.dmm
Adds tags to every pod external airlock that causes them to automatically seal closed when the shuttle departs. The external airlocks remain unlocked at all times before the shuttle leaves (without player invervention).
Also labels each escape pod external airlock with name of its attached pod (e.g. Escape Pod 1, Escape Pod 2, etc.)
Just as the departures airlocks seal closed to stop departures from being spaced when the shuttle leaves, it is good if the escape pod airlocks seal closed to stop other areas from being spaced.
Inspected shuttle external airlocks at roundstart, unlocked.
Called the shuttle, waited for it to arrive, still unlocked.
Opened one shuttle external airlock and left the other closed. Waited for the shuttle to leave.
The closed door immeditely locked, the open door …
=> Escape Pod External Airlocks now Close and Lock When the Shuttle Leaves

code/modules/research/designs/power_designs.dm
Power cells now appear in the protolathe's Stock Parts category.
They still appear under Power as well.
A lot of scientists forget to print cells when filling their RPEDs for upgrade runs. Several machines use cells, including chem masters, borg chargers, and SMESs.
Even for those that know to print off cells, having them available under stock parts reduces the amount of menu navigation required to print off all the supplies they need for an upgrade run.
Spawned in. Maxed out research levels.
Checked power and stock parts menus in the protolathe.
Saw cells in both menus.
:cl:
tweak: Power cells now appear under the stock parts menu of the protolathe in addition to the power menu.
/:cl:
=> Adds Power Cells to the Protolathe's Stock Parts Menu

code/datums/status_effects/debuffs.dm
Changes the C-foam launcher from a 4 second paralysis to a 5 second immobilization.
For 30 TC, the C-foam has the stunning power similar to a 60TC E-bow (made worse by the fact it sleeps instead of stuns), plus the added utility of a VERY long slowdown and the ability to block up doorways. This makes it a bit more of a niche of slowing anything its shot at without hardstunning people indefinitely. As-is, this item could (theoretically) keep a 4 man team of officers hard-stunned until you run out of ammo. 
Shot some people with c-foam, wiggles about and shot some lasers while waiting to get free. 
:cl:
tweak: converts c-foam hard stun into an immobilization
/:cl:
=> Tweaks C-Foam to immobilization from paralyze

code/game/objects/items/devices/radio/radio_objects.dm, code/modules/mob/living/carbon/human/species/plasmaman.dm, code/modules/ruins/ghost_bar.dm
Ghost bar occupants now use outfits instead of hardcoded clothing
Adds chameleon kit (without PDA and regular headset) for them
Ghost bar's radio headset is now chameleon by default
Removes setting for internal slot in plasmaman code because it's _always_ redeclared just a moment later in a different proc
Removes return false in the same code because there is no reason to, currently nothing checks for what this proc returns and there is only 1 possible return in the proc
Limiting player's capabilites of selectring drip to just a couple of clothing vendors is kinda booo. Why not just let them pick any clothing they want to
Spawned as a human char. Nothing has changed, everything is working as always. Spawned as a plasmaman, had internals set to my hand. Both times i had a chameleon kit in …
=> Adds chameleon kit for ghost bar occupants

code/game/gamemodes/miniantags/abduction/gland.dm
clears ventcrawl on ventcrawl organ removal
waiter waiter I wish to perma this man please
waited for organ to kick in.
Ventcrawled.
Replaced heart.
No longer can ventcrawl
:cl:
fix: Ventcrawl is properly removed when the abductor ventcrawl organ is removed.
/:cl:
=> [s] No more needing to weld it all

_maps/map_files/stations/emeraldstation.dmm
Changes erroneous console frame into a working solars. Also give some solars parts and a toolbox for flavor.
This was leftover from previous ideas and has been annoying ever since
:cl:
tweak: Emeraldstation northwest solars has a real console now.
/:cl:
=> Fixes emeraldstation northwest solars

code/modules/antagonists/changeling/powers/fakedeath.dm
Closing a TGUI alert prompt makes it return null, which is different from `"No"`. Regenerative Stasis prompt now checks if the result is different from `"Yes"`. If it is, it fails. Fixes #30142
Popping an ability you clicked out of is weird.
Clicked Regenerative Stasis 3 times.
First time I clicked "No". I didn't enter stasis.
Second time I clicked "X". I didn't enter stasis.
Third time I clicked "Yes". I entered stasis.
:cl:
fix: Closing the regenerative stasis prompt won't cause it to activate.
/:cl:
=> fix regenerative stasis popping when closing the alert prompt

code/modules/antagonists/changeling/changeling_power.dm
Makes cling power sting attempts return true by default. Their value doesn't appear to be checked anywhere, but it matters for interrupting the MiddleClickOverride in AltClickOn. Fixes #30144
Prevents you from attempting actions on sting targets  (like medical exam perk)
Loaded into game, ensured alt click was resolved.
:cl:
fix: Changeling power alt-clicks will no longer do unintended actions.
/:cl:
=> fix cling power alt click not interrupting the alt click chain

code/__DEFINES/_math.dm, code/__DEFINES/clothing_defines.dm, code/_globalvars/lists/mob_lists.dm, code/controllers/subsystem/SSticker.dm, code/controllers/subsystem/tickets/SStickets.dm, code/datums/mind.dm, code/game/gamemodes/autotraitor/autotraitor.dm, code/game/gamemodes/dynamic/antag_rulesets.dm, code/game/gamemodes/game_mode.dm, code/modules/admin/topic.dm, code/modules/admin/verbs/adminhelp.dm, code/modules/admin/verbs/adminpm.dm, code/modules/admin/verbs/deathsquad.dm, code/modules/admin/verbs/debug.dm, code/modules/admin/verbs/one_click_antag.dm, code/modules/client/client_defines.dm, code/modules/client/client_procs.dm, code/modules/mob/dead/observer/observer_base.dm, code/modules/mob/living/living.dm, code/modules/mob/living/silicon/robot/robot_mob.dm, code/modules/mob/living/simple_animal/friendly/mouse.dm, code/modules/mob/mob.dm, code/modules/mob/new_player/new_player.dm, code/modules/mob/new_player/new_player_login.dm, code/modules/response_team/ert.dm
Creates the `/datum/persistent_client` type for storing data that logically belongs to the client, but is important to keep if the player disconnects and returns. This gets automatically attached as the `persistent` var on all clients, and has the following vars:
```dm
/// Holds admin/mentor PM history. Inherited from /client.
var/datum/pm_tracker/pm_tracker
/// The Global Antag Candidacy setting from the new player menu. Inherited from /client.
var/skip_antag = FALSE
/// Used to prevent rapid mouse spamming. Inherited from /client.
var/time_died_as_mouse = null
/// All of the minds this client has been associated with. New in this PR.
var/list/minds = list()
/// Ckeys that sent us kudos. Inherited from /datum/mind.
var/list/kudos_received_from = list()
```
The addition of `minds` to the …
=> Persistent clients and body recovery

code/modules/hydroponics/grown.dm, code/modules/hydroponics/plant_genes.dm
Currently only the battery plant trait uses on_attackby. If valid it'll return true and finish the interaction. Otherwise it continues. Fixes #30182
I could replace this with an istype for plant bags if thats better too.
Functional botany.
Picked up plants with a plant bag.
:cl:
fix: Plant bags can pick up plants.
/:cl:
=> fix picking up plants with bags

code/game/machinery/portable_turret.dm
Fixes runtime when there is no lens in `/obj/machinery/porta_turret_construct`
Code is working
Constructed turret without runtime
:cl:
fix: Fixed weird behaviour when constructing portable turret without gun lens
/:cl:
=> Fix runtime for porta turrets

code/modules/paperwork/photography.dm
Moves cameras to the new attack chain
new attack chain
NPFC
=> Moves cameras to the new attack chain

code/modules/food_and_drinks/food_base.dm
Re-adds eating cooldown after it was lost in the food migration.
You cant guzzle down 30lbs of beef patties in 5 seconds.
Spammed eating, spammed force-feed, beated a person with a baguette.
:cl:
fix: Eating has a cooldown again.
/:cl:
=> re-adds eating cooldown

code/game/jobs/job/engineering_jobs.dm
Fixes paychecks in engineering department. CE - 250 credits (high). Others - 200 credits (medium).
The department was overlooked in https://github.com/ParadiseSS13/Paradise/pull/29682.
Got 250 credits in paycheck as CE.
:cl: Maxiemar
fix: Fixed engineering paychecks.
/:cl:
=> Fix engineering paychecks

code/modules/admin/holder2.dm
Code should've set it to enabled if a person had the required ranks, but it actually set disabled to true again. This pr fixes it! Fixes #30128
Easier access to debugging tools for devs.
With Admin
Without admin
Images. Accessed it with admin, couldnt access it without admin.
npfc
=> Reenables MC Debug and Profile Code in the topleft file menu.

code/modules/events/alien_infestation.dm
Title. Xenos will now re-roll the major if under 50 crew.
Xenos are far, far too strong for our current population levels. This also gives development somre more wiggle room in improving the antagonist.
Compile, force alien infestation, confirm it re-rolls.
:cl:
tweak: Alien infestation major midround will re-roll if under 50 people are on the manifest.
/:cl:
=> Xenos cant roll under 50 crew

code/modules/awaymissions/mission_code/ruins/gps_ruin.dm, code/modules/mining/equipment/survival_pod.dm, code/modules/telesci/gps.dm
Turning off handheld GPS devices by default, getting rid of spam in signals list.
Internal GPS (that one mostly used in lavaland bosses), cyborgs GPS, survival pods GPS and debug GPS are still on by default.
Less unused GPS signals in list, making it easier to find that one you need.
No GPS devices active by default on Lavaland, except megafauna and other shit.
GPS signals from space ruins still works well
Tested on local server. GPS that should have been turned off turned off. GPS that should have stayed on still stay on. Images from tests are above.
:cl:
tweak: Handheld GPS devices now are turned off by default.
/:cl:
=> Turning Roundstart Handheld GPS' Off

code/datums/mutable_appearance.dm
Ports a change to new appearances from tgstation/tgstation/pull/69838.
This might fix those weird issues we've been having with mutable appearance copying
Seems to be fine, known bugs with mutable appearances are spurious, so i cant reliably test them.
NPFC
=> Ports /mutable_appearance/New()

code/__HELPERS/trait_helpers.dm, code/modules/mob/living/simple_animal/slime/slime_life.dm, code/modules/mob/living/simple_animal/slime/slime_mob.dm, code/modules/research/xenobiology/xenobiology_dissections.dm, code/modules/surgery/generic.dm, code/modules/surgery/surgery.dm
This PR does a few small tweaks:
- Makes dissection managers not fail constantly when doing surgery, but quality is still tied to "failure rate" of tool used
- Due to this, dissector are no longer valid for use as a scalpel
- gives slimes a "Tamed" tag to their name when they are properly trained(for clarity)
- gives slimes some voice lines when they're tamed asking for treats
some small unintentional frustrations being removed
tamed some slimes. dissected some goliaths
:cl:
tweak: Dissection managers do not fail constantly
tweak: Dissectors can no longer be used as a scalpel
tweak: Gave slimes a name tag and some voice lines when tamed
/:cl:
=> Xenobiology QOL tweaks

code/modules/mining/lavaland/loot/tendril_loot.dm
replaces a missing icon state line
icky bad
used the talisman, worked as expected
:cl:
fix: Fixed a missing icon state for the hole in reality
/:cl:
=> [s] fixes an issue with the immortality talisman

code/modules/admin/admin_verbs.dm
Moves admin_verb.dm alert boxes to tgui.
Tgui looks cleaner, and we are working on moving more inputs to tgui.
I haven't yet.
NPFC
=> Moves alert messages to tgui in admin_verb.dm

code/game/objects/items/tools/welder.dm, code/game/objects/items/weapons/extinguisher.dm, code/modules/research/designs/autolathe_designs.dm
Makes welding tools and extinguishers printed on Autolathe empty by adding /empty subtupe to some of them.
I haven't done same thing with experimental and alien welding tools from Protolathe since i see no point emptying self-refilling welding tools. Plus it causes a weird bug: they dont self-refill at fuel level 0 until manually refilled from fueltank.
No welders and extinguishers coming out of Autolathe magically pre-filled with fuel/water.
Errrm dunno what i could put here...
Printed all awaiable welders and extinguisher on Autolathe. They appeared to be empty as intended.
:cl:
tweak: Welding tools and fire extinguishers printed on Autolathe now have no fuel/water.
/:cl:
=> Emptying Lathed Welding Tools And Extinguishers

code/__HELPERS/text.dm
Currently if not using TGUI for multiline inputs, hitting 'cancel' clears the field.
Expected behavior is that hitting cancel should leave the field unmodified.
This has been done by ensuring the null from cancelling doesn't get converted to HTML (which consequently produces an empty string).  Upstream code depends on this null being preserved to avoid clearing the field.
Also this adds a newline to the bottom of the modified file, per current .editorconfig standards.
In the past this has led to nuking some rather lengthy flavor text by hitting cancel, making me reluctant to add text to those fields at all.
While this is not an issue with the current incarnation of TGUI, it's still nice to fix this as a fall-back.
No bad behavior to be seen so far.  Editing records in the player profile …
=> Fix for non-TGUI multiline input clearing fields on cancel.

_maps/map_files/stations/boxstation.dmm
Removes some random lattices, plating, and walls from around Box station. North of Perma, by the Aft-Port Solar Array, and Toxins.
Despite just being random debris, it counts as a station hit for the purposes of the meteor shield goal, requiring valuable satellites to be positioned next to *literal junk* to achieve full coverage.
It's not attached to the station, so it should just float away. That's the canon reason that it's not there anymore.
:cl:
del: Removed the random space junk around Box Station.
/:cl:
=> Removes a bunch of random debris from around Box Station

code/modules/hydroponics/grown/potato.dm, code/modules/hydroponics/grown/pumpkin.dm, code/modules/hydroponics/grown/root.dm
Fixes #30214.
Oversight bad.
Grab potatoe
add wyre
get potatoe batree
:cl:
fix: Potatoes can now be turned into potato batteries again.
/:cl:
=> Fixes potatoes not becoming potato batteries

code/modules/buildmode/submodes/tilt.dm
Fixes a runtime in the buildmode setting for tilt. Settings for tilting should work properly again.
Things shouldn't runtime if we can help it.
Enter build mode, select tilt.
Right click
Go through the settings
No runtime
NPFC
=> [FIX] Buildmode tilt TGUI alert runtime

code/game/objects/effects/landmarks.dm, code/modules/mob/living/basic/mining/gutlunch.dm
Gives basic gutlunches a controller, and allows guthens into the spawn chance. During the intial conversion, only the subtypes got controllers.
Mobs should work as expected.
Started game, checked if gutlunch had an AI controller. It did.
:cl:
tweak: Made it so guthens could spawn instead of only gubbucks
fix: Fixed basic gutlunches having no controller
/:cl:
=> Fixes gutlunch controllers

code/modules/surgery/surgery.dm
Make surgery computers recognise the Place Item/Extract Item step and show it instead of it being blank. Also fixes a related runtime.
Fixes #30076.
Massive thanks to @1080pCat for bringing this issue to my attention.
Surgery computer not telling you what steps to take makes new doctors harder to learn.
Runtimes are also quite bad.
Before: 
After: 
Loaded up testserver with changes, tried Cavity Implanting a skrell, the surgery was successful and the steps are shown correctly on the computer.
Tried inserting the NAD, a rollerbed (A Bulky item) and an item help with antidrop implant on, all failed. Tried inserting a cautery and it ended the surgery instead.
Tried inserting a Normal size item and it worked, tried taking it back out again and it showed up back in my hand.
<hr>
<hr>
:cl:
fix: …
=> Make Cavity Surgery steps show up on Surgery Computers again

code/modules/atmospherics/machinery/pipes/simple/pipe_simple_he.dm
HE pipe colour animation is now 0.5 seconds, down from 2, and only happens at 50K thresholds, up from 10K. This is to fix the issue of HE pipes causing lag due to high network traffic from a large amount of animations
Less lag more good. Also looks a bit better
https://github.com/user-attachments/assets/8aa20693-ae82-44e7-9ac5-f8e5fd6f30c5
- Made a heat cycling contraption and connected from another PC to test network usage. It went down from 19mb/s to around 0.4 mb/s
:cl:
fix: HE pipes no longer cause lag(hopefully)
tweak: HE pipes now animate at 50K intervals and for 0.5 seconds
/:cl:
=> Increases animation temperature threshold and reduces animation time for HE pipes

code/modules/mob/living/carbon/carbon_procs.dm
When someone else tries to extinguish you by patting the fire out it no longer incorrectly states that you are trying to put yourself out.
Fixes: #30295 
You should be able to tell who's doing what.
Set someone on fire.
Try to pat them out.
They get the right message
:cl:
fix: Trying to pat fire out on someone no longer erroneously tells them they are patting themselves out.
/:cl:
=> [FIX] Extinguishing someone else gives the right message

code/datums/components/swarming.dm
Swarming mobs now update their swarm appearance on initialize. No more 20 carps all on one tile without it being visually distinct.
Looks better.
https://github.com/user-attachments/assets/fee6365b-0c95-4ae4-a338-1d815c7781b9
See above
:cl:
fix: Carps swarm when they're created.
/:cl:
=> Swarming mobs now update their swarm appearance on initialize

code/game/objects/structures/transit_tubes/transit_tube.dm
Transit tubes are now dense when they have gravity. 
This incentivizes them to not be used as giant hallway tubes, but still allows them to be used for cases for transporting people safely though space.
Spawned some inside the station, couldn't walk over any of em. Walked over the ones by ai-sat just fine. Turned off gravity on-station and was able to float over the tubes.
:cl:
tweak: Transit tubes can no longer be walked over when they have gravity.
/:cl:
=> Transit tubes are now dense when they have gravity

code/modules/mob/living/simple_animal/slime/slime_mob.dm
Fixes tamed slimes repeatedly having tamed added to their names when fed plasma. Fixes #30326
Bug
Saw slime, fed slime plasma. Slime was tamed but it didn't become Tamed Tamed Tamed repeated feedings.
:cl:
fix: You can no longer repeatedly tame tamed slimes.
/:cl:
=> fix tamed slimes being repeatedly tameable

code/__HELPERS/game.dm
Replaces the turf density check for open turf to use Millas airtight index. This lets things like Windows, airlocks, walls, anything else that might be airtight, to report as such. Fixes firelocks they shouldnt affecting areas they shouldnt. Fixes #30126
Makes firelocks less janky. They will now respect airtightness of airlocks, windows and other things that block air.
Activated firealarms in 2 problematic areas (pictured above). Previously, in both images, the airlock next to the window would end up being activated by the rooms fire alarm. Now as you can see, it doesnt.
I replaced the 2 windows in the images with 2 border windows. One was oriented in a way which would block air, the other was oriented in a way which would let air through. The firelocks reacted appropriately. The one …
=> Make get_open_turf respect the airtightness of anything in the turf.

_maps/map_files/RandomRuins/LavaRuins/lavaland_surface_ash_walker1.dmm, code/modules/hydroponics/grown/herbals.dm
Poultices are no longer 1:1 for healing : potency. Now the amount of healing a poultice kit is 1/4 the potency of the plant, making a max-potency poultice just as effective as an advanced brute/burn kit and not 4x.
Increases base potency of ashwalker aloe and comfrey to 40 to account for this, so their roundstart healing is just as effective as it was before.
Basic plants should not be 4x as effective as space-age advanced medical kits. Especially when you can harvest a large number of 100-heal 6-use kits very quickly with maxed-out plants.
Compiled.
:cl:
tweak: Poultice potency scales 1:4 healing to potency.
tweak: Ashwalker aloe/comfrey starts at potency 40.
/:cl:
=> Nerfs Poultices

code/modules/admin/holder2.dm, code/modules/client/2fa.dm, code/modules/client/client_procs.dm
Makes it so the message telling the user that they need 2FA to use some admin commands now prompts them to the correct menu using a chat link rather than just telling them to set it up
From request of funnyman, also makes the reload admin verbs when you do set it up silent so it doesn't tell every admin that their verbs were reloaded
Being told to setup something that you're not told *where* to set the thing up isn't good, i personally thought i had to setup 2fa on the byond account side of things rather than in game, so telling the person where they can setup 2fa is good.
Also every admin being told that their verbs were reloaded when someone setup 2fa isn't the best, as its a little confusing 
For the 2FA setup prompt a flipped a var to make the warning popup even if the server didn't …
=> The 2FA warning now prompts the user to the correct menu to setup 2FA

code/modules/point/point.dm
Currently code doesn't support displaying items that are at least 2 layers deep inside ur mob. It affects: items inside boxes that are inside ur backpack, paradox bag, modsuit's bag and so on. This PR allows to display items that are located deeper than just ur mob or ur mob's contents
We should be able to display items that are located somewhere inside of our mob
Clicked on a bananium (bananium is inside box, box is inside box, box is inside mod bag, mod bag is inside mod module, mod module is inside mod control, mod control is inside mob)
:cl:
tweak: You may now click with MMB on items that are located inside your modsuit's backpack/paradox bag/box that is inside your backpack in order to show them in a point bubble
/:cl:
=> Allow poiniting on items inside deep mob's storage

code/game/gamemodes/miniantags/abduction/abduction_gear.dm, code/game/objects/items/weapons/kitchen.dm, code/game/objects/items/weapons/shields.dm, code/game/objects/structures/stool_bed_chair_nest/bed.dm, code/modules/clothing/masks/gasmask.dm, code/modules/research/designs/autolathe_designs.dm, code/modules/research/designs/mining_designs.dm, code/modules/research/designs/power_designs.dm, code/modules/research/designs/weapon_designs.dm, code/modules/surgery/tools.dm, tools/ci/check_material_recycle_costs.py
This PR adds a check for exploitable recycle costs and brings a dozen or so recycle/printing costs for items to be consistent. Fixes #30212.
Better to solve all these issues in one fell swoop and have a check preventing issues in the future.
:cl:
fix: The recycle and printing costs of several items have been adjusted to prevent infinite material refund loops.
/:cl:
=> add CI check for exploitable recycle costs

code/modules/research/designs/mechfabricator_designs.dm
Fixes build_path and material cost for https://github.com/ParadiseSS13/Paradise/pull/30042
Typos are bad.
Tested it on my local server. Assured module properly prints and attaches.
:cl:
fix: Fixed Dropwall Launcher not being printable in mechfab
/:cl:
=> [FIX] DWDL-04 Dropwall Launcher build path and cost

code/modules/cooking/recipe_tracker.dm, code/modules/cooking/steps/recipe_step.dm, code/tests/_game_test_puppeteer.dm, code/tests/game_tests.dm, code/tests/test_cooking.dm
This PR fixes some behavior in the recipe tracker to handle situations with multiple valid step types. It also adds some more documentation around the cooking rework to try and help clarify some of the most finnicky code. Fixes #30297. In all honesty the existing code was more or less incomplete--situations like the bug being fixed just weren't a problem until I had to look deeper into it now.
A very small test suite is added for the soylent green recipe and a cutting board recipe, just to have a very basic sanity check.
Bugfix and lays down some expectations for recipe behavior.
Manual recipe creation, and new test suite.
:cl:
fix: The soylent green recipe should work as expected.
/:cl:
=> fix cooking step failures

.gitignore
This PR adds dmdoc.exe and dmdoc/ to gitignore.
Makes it easy to test dmdoc stuff and not get in the way of other branch shit going on.
Checked contents of git status.
NPFC
=> add dmdoc and output dir to gitignore

code/modules/mob/living/basic/friendly/nian_caterpillar.dm
Fixes an issue where nian caterpillars when fully fed will start to eat everything quickly.
Bugs bad.
Fed a nian caterpillar until it was sated. Didn't see it continue to eat.
:cl:
fix: Fixed an issue where nian caterpillars ate tons of food after being fully fed
/:cl:
=> Fixes nian caterpillars becoming ravenous when fully fed

docs/contributing/exploits.md, mkdocs.yml
This PR adds a devdocs page defining an exploit at a basic level.
Nowhere do we have a good, exhaustive definition of an exploit with examples. It's on us to have this if we expect people to file bugs and exploits in their correct places. This can be linked in the issue report template at some point.
Generated devdocs locally, proofread.
NPFC
=> adds documentation on what an exploit is

_maps/map_files/stations/deltastation.dmm
This PR adds the appropriate access helpers to delta brig.
Assistants should not be able to waltz into the brig.
:cl:
fix: Kerberos: The brig MULEbot entrance is now properly access restricted.
/:cl:
=> add access helpers to delta brig mule entrance

code/controllers/subsystem/SSradiation.dm, code/datums/radiation_wave.dm
Adds a cache so different radiation waves don't need to repeat get_rad_contents() on the same turf in the same tick.
The cache gets populated as rad waves pass over turfs and gets reset each time SSradiation fires.
more performance
- Set the SM's EER to 5,000,000 and let it rip
:cl:
tweak: Radiation waves now cache the list of items they generate from turfs they pass along
/:cl:
=> Adds a cache to radiation waves

_maps/map_files/stations/boxstation.dmm
Changes most of the external airlocks to use external airlock access helpers on BoxStation.
Also puts an airless plating tile under the external door so a gush of magic space wind doesn't happen when the airlock first cycles into space.
Also slightly expands the disposals airlock.
External airlocks not leading into engineering areas should not be using engineering access helpers, and should instead be using the external airlock access helper specifically designed for external airlocks.
Disposals airlock change:
:cl:
tweak: Non-engineering external airlocks now use external airlock access instead of engineering access on BoxStation.
tweak: Extended the disposals external airlock to a 1x2 on BoxStation.
/:cl:
=> Changes Most BoxStation External Airlock ID Access Restrictions from Engineering to External Access

code/modules/atmospherics/machinery/airalarm.dm
Previously, the `buildstage` variable in `code/modules/atmospherics/machinery/airalarm.dm` had assignments and checks that were mixed: some were clear defines (e.g. `AIR_ALARM_READY`) and some were flat numerals (e.g. `2`). This standardizes all of them so that the meaning is always clear.
Clear code is better code.
Compiled, hosted, assembled an air alarm, and broke it with a welder. I examined it at various points during the process. It seemed fine.
NPFC
=> Standardize air alarm buildstages to defines for clarity

code/modules/mob/living/carbon/human/human_defense.dm
… your welding tank to repair
ou no longer attack yourself when repairing cyber limbs with insufficient fuel
It's very annoying when you are repairing yourself, your fuel runs out and you start hitting yourself with a welder instead
Repair myself until my fuel tank reaches 0.5 units of welding fuel.
I stop repairing myself and get told that I don't have enough welding fuel to do this.
:cl:
fix: You no longer attack yourself when repairing cyber limbs with insufficient fuel
/:cl:
=> [FIX] You no longer attack yourself when repairing cyber limbs with insufficient fuel

code/modules/mob/living/brain/robotic_brain.dm
Positronic brains can speak by default.
Consistency with robotic brains, who also start unmuted, and MMIs, who start unmuted.
Makes IPCs slightly less bad.
Spawned as an IPC, gibbed myself, spoke.
:cl:
tweak: Positronic brains can speak by default.
/:cl:
=> Makes Positronic Brain Speaker Active by Default

code/modules/mob/living/basic/friendly/mouse.dm
This PR fixes mice not squeaking when stepped on. `squeak_sound` here was getting coerced into a string, probably.
Mice should squeak.
Spawned mice, squeaked em
:cl:
fix: Mice properly squeak when stepped over
/:cl:
=> fix mouse squeak

code/modules/clothing/clothing.dm
It no longer sets your worn_icon_state to `"_up" `from `null`
Also removed lines about chameleon since there is no chameleon item that has can_toggle = true
Fixes #30450
Fixes #30535
Bugfix
Local server
:cl:
fix: Fixed missing sprite for welding helmets
/:cl:
=> Fix missing sprites for welding helmets

code/modules/awaymissions/mob_spawn.dm
This PR removes a log for mob spawners when no ckey is associated with the action (e.g. corpse spawners).
This crap is useless
NPFC
=> clean up logs for mob spawns

code/game/objects/structures/lavaland/necropolis_tendril.dm
This PR ensures that attacks from melee items properly cause damage to tendrils. #30365 most likely introduced this.
Bugfix.
Spawned tendrils, ensured that melee weapons on both old and new attack chains caused damage to the tendril.
:cl:
fix: Melee attacks properly damage Lavaland tendrils again.
/:cl:
=> fix melee attacks not working with tendrils

code/modules/smithing/machinery/kinetic_assembler.dm
Fixed the message when using a kinetic assembler with your hand while there's a finished product inside it to say that that is the case instead of it lacking a component.
Messages should be clear as to why something failed.
Used hand on assembler with incomplete item inside. Got expected message.
:cl:
fix: Fixed message when using hand on assembler
/:cl:
=> Fixes hand interaction with kinetic assembler

code/modules/events/clogged_disposals.dm
Fixes #30536 
Bugs bad
Ran the event a bunch of times and didn't see a generic casing.
:cl:
fix: Fixed generic casings spawning from disposals clog events.
/:cl:
=> Fixes generic spent shells being in clogged disposals events

code/game/objects/objs.dm
Autodocs all the vars in `/obj` along with some of the procs.
Removed an unused, commented-out var.
I saw `suicidal_hands = TRUE` and I was so confused. Others shall be spared my pain.
It still compiles so it's probably fine.
NPFC
=> Makes `/obj` documentation better.

code/modules/research/xenobiology/xenobiology.dm
Fixes #30022
Bugs bad
Used a consciousness transfer motion on a basic mob.
:cl:
fix: Fixed consciousness transfer potions not working on basic mobs
/:cl:
=> Fixes Consciousness Transfer potions not working on basic mobs

code/modules/reagents/chemistry/reagents/food_reagents.dm
Removes an additional space from the end of Tinea Luxor's chemical description.
Sentences don't end with spaces after periods.
Compiled. Inspected visually.
:cl:
fix: Tinea Luxor's chemical description no longer has an extra space in it.
/:cl:
=> Removes an extra space in Tinea Luxor's description

code/game/jobs/job/support.dm
Switches the default internals box smiths get with a mining internals box.
Smiths work on lavaland, which is known for having inhospitable atmospherics. They're even expected to go out into the wastes at times. It's fitting that they are at least equipped for lavaland-related emergencies.
Compiled.
:cl:
tweak: Replaced smith internals box with mining internals
/:cl:
=> Improves smith internals boxes

code/modules/clothing/suits/bio.dm
Allows you to put large internals tanks into the suit storage slot of biosuits.
It's weird when those are in the biohazard lockers but you can't put them on. It has also become much less viable to use emergency tanks with the shrinking of those.
Put on biosuit. Put O2 internals tank in the slot. Put plasma internals tank (one that doesn't fit on belt or in pockets) in the slot. Put penlight in slot (yes, those are whitelisted). Tried putting emergency injector in slot, was unable to.
***Ultra*** approved:
:cl:
tweak: You can now put large internal tanks into the biosuit's suit storage slot.
/:cl:
=> add large internals tanks to biosuit suit slot whitelist

tools/rustlibs_tools/mapmanip.ps1
This PR fixes the locations of rustlibs in the mapmanip FFI test script (used for testing mapmanip outside of the game).
Tools should work.
Ran `.\tools\rustlibs_tools\mapmanip.ps1`, ensured that all mapmanipout.dmm files were created.
NPFC
=> fix references to rustlibs in mapmanip.ps1

_maps/map_files/stations/cerestation.dmm
Fixes a nonfunctional external airlock door on Farragus by changing the area of the outer door from nearspace to maint.
Oversight bad.
Cycled door, it worked.
:cl:
fix: Fixes a broken external airlock on Farragus.
/:cl:
=> Fixes a Farragus External Airlock

_maps/map_files/RandomRuins/SpaceRuins/moonoutpost19.dmm, code/modules/awaymissions/mission_code/ruins/moonoutpost19.dm
Turns some notes into lore consoles on MB19
also slightly changed the wording on some things, as they were a little wonky
Small papers usually go unnoticed, or get blown away, or are a little too well hidden. 
and using lore consoles is neato :)
made sure all the formatting was fine
:cl:
tweak: Tweaked a few lore tidbits in moonbase 19
tweak: Swapped the paper lore dumps for lore consoles
/:cl:
=> Moves some notes in MB19 to be lore consoles

code/modules/station_goals/secondary/secondary_goal.dm
When someone requests a secondary goal, also dispatches a message to cargo that a new crate is available to ship.
Fixes #28746
Altered a map so a requests console from medbay and cargo were right next to each other. Compiled, hosted, and requested a goal from the medbay console. Received notification of, and read message about, the new crate via the cargo requests console.
:cl:
add: Added a notification to the cargo requests console when a secondary goal crate is ready to ship.
/:cl:
=> Notify cargo of incoming secondary goal crates.

code/modules/mob/living/simple_animal/hostile/megafauna/legion.dm
Fixes #30521
#29093 broke HRD-MDE Legion because it only drops the loot when it is the only Legion in the game. That PR added megafauna corpses so the Legions stay in game, just dead. This prevented the second Legion from dropping its loot.
Clearing HRD-MDE should absolutely reward you the regular loot and the disk on top of it. Getting absolutely nothing may be what miners deserve but it still sucks.
1. I spawned a Legion and killed it. The regular loot dropped.
2. I spawned a Legion, used a HRD-MDE grenade and killed both Legions. The regular loot dropped along with a single HRD-MDE disk.
:cl:
fix: HRD-MDE Legion drops loot again
/:cl:
=> HRD-MDE Legion drops loot now

code/_globalvars/misc_globals.dm
Adds multiple new physique and height options to the character creator menu.
More customization and ways to display character traits is a good thing.
Joined. Ensured list loaded properly. Examined. Saw no errors.
:cl:
add: New physique and height options have been added to the character creation menu.
/:cl:
=> Adds new physique and height options to character creation

_maps/map_files/generic/centcomm.dmm, _maps/map_files/shuttles/emergency_cyb.dmm
Extends the bridge of the shuttle by 1 tile. Adds 2 wall lockers with emergency oxygen.
Adds a medical records and AI restorer computer so each head's station has 2 consoles.
Recolours the bridge antechamber black.
Adds <STAND CLEAR> markings outside the entrence to the secure area.
Removes most of the floor markings, adds some back sparingly.
Adds windows to the external airlocks.
Adds operating equipment and a defibrillator to the ship medbay.
Adds a machine repair kit to the service bay.
If the doctors forget or are unable to get their surgery equipment, there's not much they can do on the shuttle. Almost every purchasable shuttle has a proper operating table and surgery tools, and defibrillators are also fairly common.
This gives the doctors some more content and possibly allows some …
=> Slight Touchup of the Default Emergency Shuttle

_maps/map_files/RandomRuins/SpaceRuins/deepstorage.dmm, _maps/map_files/RandomRuins/SpaceRuins/dj.dmm, _maps/map_files/RandomRuins/SpaceRuins/telecomns_returns.dmm, _maps/map_files/RandomRuins/SpaceRuins/turretedoutpost.dmm
Replaces all the power monitors in all ruins with the `secret` subtype that hides it from the power-ON PDA app.
Fixes #30530.
The secret power monitor subtype was made for exactly this reason.
Spawned all the ruins with power monitors. Could not see them in my PDA.
:cl:
fix: Off-station power monitors can no longer be seen by engineer PDAs.
/:cl:
=> Hides off-station power monitors from the power-on app
