- code/game/objects/items/weapons/storage/storage.dm
- code/modules/mob/living/living.dm
> Fixes exchange document objective

- code/game/gamemodes/blob/overmind.dm
- code/modules/mob/dead/observer/login.dm
- code/modules/mob/dead/observer/logout.dm
- code/modules/mob/dead/observer/observer.dm
- code/modules/mob/living/silicon/ai/freelook/eye.dm
- paradise.dme
https://github.com/tgstation/-tg-station/pull/8072
This is the ghostsight everyone has been asking for.
> The Ghostsight the server deserves

- code/modules/mob/living/simple_animal/friendly/corgi.dm
- Fixes #478 but also seems to magically fix #481
> Emergency corgi runtime Fix

- code/controllers/garbage.dm
- code/datums/mind.dm
- code/game/gamemodes/blob/overmind.dm
- code/game/machinery/doors/airlock.dm
- code/modules/mob/dead/observer/observer.dm
- code/modules/mob/living/silicon/ai/ai.dm
- code/modules/mob/living/silicon/ai/freelook/eye.dm
- code/modules/nano/nanomanager.dm
Changes:
1) Fixes https://github.com/ParadiseSS13/Paradise/issues/501.
2) Re-adds the door forcing sound.
3) Removes qdel from ghost images, as it was causing warnings in Dream Daemon.
4) Clarifies the qdel debug command and actually makes it work.
5) Fixes a possible NanoUI runtime.
> Fix player panel, other fixes

- code/__HELPERS/lists.dm
- code/modules/organs/blood.dm
- God I hope this one works.
- Might as well get a quickie blood color fix in there too.
> Emergency player panel fix

- code/game/objects/items/devices/paicard.dm
- code/modules/mob/living/silicon/pai/pai.dm
- code/modules/mob/living/silicon/pai/software.dm
- code/modules/mob/living/silicon/pai/software_modules.dm
- code/modules/nano/nanointeraction.dm
- nano/templates/pai_atmosphere.tmpl
- nano/templates/pai_directives.tmpl
- nano/templates/pai_doorjack.tmpl
- nano/templates/pai_interface.tmpl
- nano/templates/pai_manifest.tmpl
- nano/templates/pai_medrecords.tmpl
- nano/templates/pai_messenger.tmpl
- nano/templates/pai_radio.tmpl
- nano/templates/pai_secrecords.tmpl
- nano/templates/pai_signaller.tmpl
- paradise.dme
Ports pAI NanoUI interface from Baystation12/Baystation12#8089, this will allow pAIs to resize their UI windows and have more than one module window open at a time. Check the Baystation PR for images. Big thanks to @GinjaNinja32 for figuring out the reason I couldn't get the manifest to work.
PR is ready to merge.
> NanoUI pAIs

- code/game/machinery/poolcontroller.dm
Updates pool controller code so that it doesn't affect ghosts, AI eyes, and silicone,
also changes the message to only display on prob(50), to cut down on the
message spam
Edit: Sanity checks is not an accurate title.
> Pool controller fixes

- code/game/vehicles/spacepods/spacepod.dm
impacts health, also makes ion rifles work correctly against pods. I believe this would be considered a balance change, or possibly a fix, not sure
> EMP_Act for spacepods, disables movement, eats cell charge, largely

- code/modules/mob/mob_grab.dm
> Let Tajaran eat mice!

- code/modules/mob/living/carbon/give.dm
> Fix giving things to non-carbons

- code/game/objects/structures/crates_lockers/closets/statue.dm
- code/modules/power/lighting.dm
Problem pointed out by tgstation/-tg-station#8313, discovered it works on our code as well, ported tgstation/-tg-station#8455 to fix it
> Add clickdelay to attacking statues & lights

- code/modules/jungle/jungle_animals.dm
- code/modules/mob/living/simple_animal/friendly/cat.dm
- code/modules/mob/living/simple_animal/friendly/crab.dm
- code/modules/mob/living/simple_animal/friendly/fox.dm
- code/modules/mob/living/simple_animal/friendly/mouse.dm
- code/modules/mob/living/simple_animal/friendly/tomato.dm
- code/modules/mob/living/simple_animal/hostile/alien.dm
- code/modules/mob/living/simple_animal/hostile/bat.dm
- code/modules/mob/living/simple_animal/hostile/bear.dm
- code/modules/mob/living/simple_animal/hostile/carp.dm
- code/modules/mob/living/simple_animal/hostile/giant_spider.dm
- code/modules/mob/living/simple_animal/parrot.dm
- code/modules/mob/living/simple_animal/tribbles.dm
Fixes https://github.com/ParadiseSS13/Paradise/issues/623
Essentially adds in meat_amount where missing.
> Fixes meat harvesting of some simple_animals

- code/game/objects/items/weapons/storage/bible.dm
On the tin, insert beaker of water into bible, `"<span class='notice'>You feel [deity_name] blessing \the [W] as you insert it into your [src].</span>"`, and you get holy water. 
Don't question the branch name, it was too difficult to change.
> Allow Chaplain to bless beakers by inserting them into his bible

- code/ZAS/Airflow.dm
- code/game/turfs/simulated/walls.dm
This received positive feedback on the forums.
Since LINDA is coming eventually and doesn't have some of the frustrating points of ZAS, a few tweaks have been made to ZAS to make it feel a bit more LINDA like so players can adjust.
- Getting hit by air will no longer stun, paralyze, or weaken you; it will still shove you around and cause you to hit walls (and take damage), but it will not keep you glued to the floor for huge periods of time
- Walls are no longer made of "chocolate" (as ADR calls them =p); fires will no longer destroy walls (floors, objects, etc are still impacted by fire).
> ZAS Tweaks

- code/game/atoms_movable.dm
- code/game/objects/items/weapons/twohanded.dm
https://www.youtube.com/watch?v=PGNiXGX2nLU&feature=player_detailpage#t=61
Sometimes simple things are the best.
> Thrown Object Spinning

- code/modules/reagents/Chemistry-Reagents.dm
- code/modules/reagents/Chemistry-Recipes.dm
this resulted in doublestacking of reagent effects
thanks byond
there's a cyanide in toxins.dm that replaces this one
> i forgot to remove old cyanide in favor of new cyanide, rippers

- code/defines/obj/weapon.dm
- code/game/objects/items/weapons/grenades/ghettobomb.dm
- code/modules/crafting/recipes.dm
- Readds old IED recipe while also keeping tablecrafting overhaul
- Allows IEDs to be attached to beartraps for leg-blowing-off !!FUN!!
> IED fix and trap

- code/game/objects/items/weapons/defib.dm
- code/modules/mob/living/silicon/robot/robot.dm
- Updates the borg's defib sounds to be consistent with regular defibs
- Borgs don't have emagged defibs by default anymore
- Can still acquire emagged defibs if the medical borg itself is emagged
> Borg Defib Fixes

- code/game/atoms_movable.dm
- code/modules/mob/living/living.dm
Fixes up the spin animation for thrown things---improvement made by Goofball
- Thrown items will stop spinning when they hit something
> You Spin Me Right Round

- code/game/atoms_movable.dm
- code/modules/mob/living/living.dm
Until we can fix it so thrown mobs don't spin forever....
> Disables Perma-Spinning (for now)

- code/game/machinery/bees_items.dm
- code/game/machinery/kitchen/microwave.dm
- code/modules/food/candy_maker.dm
- code/modules/food/grill_new.dm
- code/modules/food/oven_new.dm
- code/modules/mob/living/carbon/human/life.dm
- code/modules/reagents/Chemistry-Reagents.dm
- code/modules/reagents/Chemistry-Recipes.dm
- code/modules/reagents/newchem/food.dm
- code/modules/reagents/newchem/medicine.dm
- code/modules/reagents/newchem/other.dm
- code/modules/reagents/newchem/pyro.dm
- code/modules/reagents/newchem/toxins.dm
- code/modules/reagents/reagent_containers/food/snacks.dm
More tweaks and fixes
- Updates even more chem's descriptions, colors, and mix messages
- ???? is now in burned messes
- Fixed up neurotoxin so it behaves properly (yes, it really does behave that oddly)
- makes the honey reagent actually do something (I didn't even know we had a honey reagent)
- Adds in reaction for cola
- Fixes a whole bunch of small behaviors that are inconsistent with how the chemicals are supposed to function.
- Heart attacks paralyse you
> [Goonchem] Even More Tweaks and Fixes

- code/__HELPERS/icons.dm
Since I did it on tg anyway
fixes #596
> Avoid infinite loop in getFlatIcon

- code/modules/mob/mob.dm
Corpse smells other corpse...corpse finds this disgusting and vomits.
Other corpse finds other corpse also disgusting and vomits , too---vomit fest continues until corpses don't find other corpses disgusting.
Yeahhhhhh oops.
> Fixes Dead People Vomitting

- code/modules/reagents/newchem/medicine.dm
- code/modules/reagents/newchem/toxins.dm
Super tiny tweaks
- Updates Omnizine and Sarin
- Updates Sodium Thio's color
> [Goonchem] Tweaks

- code/game/machinery/kitchen/processor.dm
THERE WAS A `:`
LET ME REPEAT THERE WAS A FUCKING COLON OPERATOR IN THIS
AND OH GOD THE RELATIVE PATHS, THEY HURT
THEY HUURTT
So yeah, major refactor of the kitchen processor.
> Cleanup food processor code

- code/game/machinery/vending.dm
- code/game/objects/items/random_items.dm
- code/game/objects/items/weapons/grenades.dm
- code/modules/reagents/Chemistry-Reagents.dm
- code/modules/reagents/newchem/drugs.dm
- code/modules/reagents/newchem/food.dm
- code/modules/reagents/newchem/medicine.dm
- code/modules/reagents/newchem/toxins.dm
- code/modules/reagents/reagent_containers/food/drinks.dm
- code/modules/reagents/reagent_containers/food/snacks.dm
- code/modules/reagents/reagent_containers/food/snacks/candy.dm
Just more tweaks and such.
- Fixes up more descriptions/colors/behaviors of existing reagents
- Adds in a few more reagents for future use
- Fungus, which will be used for a few medicines and recipes
- Ants--deal brute and do brute on application, as well.
- Concentrated Initro--Instant heart attack if someone has over 5 units in their system; will be tator only.
- Adds in a few more reagents that will be accessible immediately
- MSG: makes everything taste good--has a low probability each cycle to cause a migraine (find it in Chinese food!)
- Chocolate: decays into sugar--can be found in a lot of current foodstuffs that are chocolate based
- Chicken Soup: provides nutrition--can purchase in vendors
> [Goonchem] More Additions and Tweaks

- code/modules/client/preferences_mysql.dm
- code/modules/mob/living/carbon/human/human_organs.dm
- code/modules/surgery/surgery.dm
Fixes:
http://i.gyazo.com/1f5828b8d5dad870cf2a5d4e453c5dc9.png 
ADMIN: TheDZD/(DOOMCRAB) (JMP): Start sawing off arm, switch area target to head. 
ADMIN: TheDZD/(DOOMCRAB) (JMP): Wait for surgery step to end, head pops off.
- Fixes #743 
- Fixes #738
> Organs/Surgery Fixes

- code/game/objects/items/weapons/signs.dm
This fixes the issue of being able to spam picket sign messages, and also makes them a bit less intrusive- blue notice text instead of red warning text. http://puu.sh/h4eWl/4bba713859.png
> Picket sign fixes

- code/modules/admin/admin.dm
- code/modules/admin/admin_verbs.dm
- code/modules/admin/verbs/alt_check.dm
- code/modules/client/client defines.dm
- code/modules/client/client procs.dm
- paradise.dme
Thanks to https://github.com/Spoffy/LLA-Station-13/pull/280
Allows admins to easily check for alt ckeys using both IPs and computerID.
> Alt Account checking

- code/modules/reagents/Chemistry-Machinery.dm
- nano/templates/chem_dispenser.tmpl
As requested: https://github.com/ParadiseSS13/Paradise/issues/758
Makes it possible to dispose chemicals directly from the chem dispenser
> Dispose chems directly from chemdispenser

- code/__HELPERS/unsorted.dm
- code/modules/reagents/reagent_containers/food/drinks.dm
- code/modules/reagents/reagent_containers/glass.dm
- code/modules/reagents/reagent_containers/glass_containers.dm
- paradise.dme
Adds in improvised heating
- Anything that is "Hot" (welders, igniters, candles, etc) will heat drinking glasses or glass containers by 15k
- Long live the ghetto chemist
I had to remake glass.dm because it was a "cursed" file that Github was incapable of tracking changes on. This commit totally effed things and is the original source of the problem: https://github.com/ParadiseSS13/Paradise/commit/c0ba021bcd440c532547d9384f1917825c4a56c4
> [Goonchem] Improvised Heating

- code/modules/organs/organ.dm
- code/modules/organs/organ_stump.dm
- code/modules/surgery/implant.dm
- Makes organ stumps amputatable. (Seriously, why the fuck were they
not? You NEED to remove them to attach new limbs, including heads.)
- Removes organ rejection (But muh reelizms! No, fuck that, test dummies
were rejecting their own organs and dying. Why did this even exist?)
- Organs removed from a body take SIGNIFICANTLY longer to take damage
and decay now. That brain you just removed will actually be
transplantable a minute later.
Fixes #775
> Fixes surgery bugs & removes organ rejection

- code/game/machinery/hydroponics.dm
- code/modules/reagents/newchem/other.dm
Hydro fix, fixes https://github.com/ParadiseSS13/Paradise/issues/683
Added corgis random color when splashed with colorful reagent.
> Hydro fix & colorful corgis

- code/modules/client/preferences.dm
- code/modules/mob/living/carbon/species.dm
> Slime people fixes

- code/game/area/areas.dm
Fixes the popping sound heared when white noise is toggled on.
> Popping sound fix

- code/game/gamemodes/vampire/vampire.dm
- code/modules/reagents/Chemistry-Reagents.dm
Sucking blood increases nutrition, nutriment does not. Also adds an immunity check for holy water contact. Fixes #593, if that was even a bug.
> Vampires get nutrition from blood, not food.

- code/modules/mob/living/simple_animal/hostile/giant_spider.dm
- code/modules/reagents/Chemistry-Reagents.dm
I wondered how many people would gib because of Venom.....apparently a lot.
- Adds in Spider Venom
- Spider venom is just a weaker toxin--it does 1.5 ToxLoss per cycle (like on TG) and nothing more.
- Spiders now inject spider toxin instead of venom
> Spider Balance--Venom

- code/modules/admin/DB ban/functions.dm
- code/modules/admin/topic.dm
Cleans up the admin unban panel stuff, makes manual bans properly pick up on a mob's IP even if it leaves, limits how many results show to unlag the system, etc.
> Admin unban panel overhaul

- code/modules/mob/living/carbon/human/human.dm
High priority, needs to be merged and patched ASAP.
Need one of the other maintainers to check to see if this won't be
particularly process-intensive for the server.
> Fixes Invisible living/carbon/human Mobs

- code/modules/mob/living/carbon/human/death.dm
- code/modules/organs/organ.dm
- code/modules/reagents/reagent_containers/food/snacks.dm
Makes Gibbing way more gorey
- Gibbing will now throw out your organs *everywhere*
- Brain, Lungs, Liver, Kidneys, Eyes, and Appendix all go flying
- Can pick up organs and eat them (be on harm intent then click on the organ itself)
> More Gore from Gibbing

- code/modules/reagents/Chemistry-Holder.dm
- code/modules/reagents/Chemistry-Recipes.dm
- code/modules/reagents/newchem/other.dm
- code/modules/reagents/newchem/pyro.dm
- code/modules/reagents/newchem/toxins.dm
Adds in support for chemical reactions not having a mix message.
Current Reactions that won't have a message:
- Ash
- Neurotoxin
- Black Powder
> [Goonchem] No Mix Messages

- code/modules/mob/living/default_language.dm
- code/modules/mob/living/simple_animal/friendly/corgi.dm
Fixes: https://github.com/ParadiseSS13/Paradise/issues/845
This now works. Simple as that.
> Language fix + Corgi health status fix

- code/game/gamemodes/vampire/vampire.dm
- code/modules/organs/blood.dm
- code/modules/reagents/Chemistry-Reagents.dm
Fixes #881, vampires should no longer get fat from drinking too much blood.
> Prevents vampires getting fat by drinking too much blood.

- code/modules/reagents/Chemistry-Machinery.dm
- code/modules/reagents/newchem/food.dm
- Fixes cheese's recipe
- Fixes cider not being available at all
> [Goonchem] Fixes

- code/modules/assembly/igniter.dm
- code/modules/reagents/Chemistry-Machinery.dm
- code/modules/reagents/reagent_containers/glass_containers.dm
- maps/cyberiad.dmm
- Fixes up a proc name so it's not overriding an actual legitimate proc (oops)
- Fixes the portable chem dispenser not having a number of reagents
- Fixes the laptop vendor in cargo NOT being a Cartridge Vendor (I dunno how this even happened).
> Various Fixes

- code/modules/paperwork/stamps.dm
Fixes and exploit involving the NT Rep's stamp.
> Exploit Fix

- code/game/shuttle_engines.dm
- code/modules/admin/admin.dm
Remove ZAS debug stuff from game panel
Add CanAtmosPass to shuttle windows - fml
> LINDA patch #2

- code/game/objects/structures/window.dm
I left out a very important define from plasma windows that prevents them
from heating the room
> Fix plasma windows (again)

- code/modules/mob/living/living.dm
This commit updates the /mob/living resist verb to -tg- standards. It is
no longer a giant mess of 1 single verb, it has been split into a central
verb with multiple sub-procs.
This is not a port of -tg-'s optimized resist code, it simply makes the
existing code a bit less terrible, and organized in sub procs like -tg-'s code.
Player notes: Nothing has changed, but coders may add more functionality to resist now that it is more modular.
Coder notes: Defining a new action on the resist verb is much easier now. Just add a new sub-proc, write the if-checks in the central verb, done. No fiddling with a ridiculously long block of code.
> Resist update to -tg- standards

- code/modules/mining/mine_turfs.dm
Now that we have LINDA, the "hot asteroid bug" shouldn't crop up
- Asteroid is now cold again (as it should be).
> Asteroid Temp Fix 2.0--LINDA Edition

- code/ATMOSPHERICS/atmospherics.dm
- code/ATMOSPHERICS/components/unary/unary_base.dm
- code/game/machinery/cryo.dm
- code/modules/mob/living/carbon/carbon.dm
- code/modules/mob/living/login.dm
d3athrow/vgstation13#4251
tgstation/-tg-station#9296
- Fixes moving between pipeline datums not updating pipe vision
- Fixes login() not updating pipe vision
- Removes hardcoded limit of entering through unary machinery-- does
nothing *now*
- Can see pipes in darkness as fullbright
- More sanity checks
TL:DR; Fixes, can see pipes in darkness, possible future things.
> Ventcrawling fixes

- code/modules/mob/living/carbon/human/update_icons.dm
- code/modules/organs/organ_external.dm
- Fixes #926
- Fixes #857
- Cut down prob of delimbing by half, seemed to happen too easily with new limb overhaul
> Limb bugfixes

- code/modules/client/client defines.dm
Hopefully this fixes the error:
runtime error: Cannot read null.ambience_playing
proc name: Entered (/area/Entered)
source file: areas.dm,388
> Runtime error fix

- code/_onclick/cyborg.dm
- code/modules/mob/living/silicon/robot/inventory.dm
- code/modules/mob/mob_movement.dm
- interface/interface.dm
This PR gives cyborgs the ability to point with Middle Click (module cycling is now on Ctrl+Middle Click), and makes the existing Drop Item and Toggle Throw hotkeys deselect or unequip, respectively, the current module.
The current lack of cyborg pointing is... odd. As far as I can tell, when middle-click-to-point was implemented [in this commit](https://github.com/ParadiseSS13/Paradise/commit/98a99ebd1a227ddffbc0fe48d573097d318c3088), the fact that cyborgs had a custom `MiddleClickOn` wasn't considered, and nobody got around to fixing it. I can think of no reason for them *not* to be able to point, so now they can do so, with the same click carbons use. Module cycling has been moved to Ctrl+Middle Click, in case anyone still wants to cycle with the mouse.
* Cyborgs can now point with …
> Cyborg Pointing and Deselect/Unequip Module Hotkeys

- code/modules/procedural mapping/mapGenerator.dm
@RemieRichards added more commits after pull-request #916 was merged.
Going to request a DNM on this until tgstation/-tg-station#9252 is merged into -tg-.
Primary fixes; 
- Spherical map generator works now
> Procedural Map Generator Improvements - Patch 1

- code/__HELPERS/lists.dm
https://github.com/tgstation/-tg-station/pull/9415
Used once in code for some camera assembly thing, can probably be insta-merged.
> uniquelist proc optimization (used once in code)

- code/modules/research/designs/medical_designs.dm
Oops...both named the same thing.
> Health Analyzer Name Fix

- code/modules/mob/living/silicon/ai/laws.dm
> Adds service radio to ai

- code/game/machinery/poolcontroller.dm
This updates the pool controller with some of the fixes that
HippieStation/Atlas added.
Things changed:
- People will now drown in the pool if they are resting.
- There are a few conditions.
- They must not be wearing internals.
- They must not be a skrell.
- They must be a species that breathes
- They must not have the NO_BREATHE power
- AI's can no longer save people from burning in the pool with their
magical field
- Yes this was a thing, it would stop looking for mobs if it found an
AI eye
> Pool Controller update: Hippie Edition

- code/game/gamemodes/blob/blobs/resource.dm
title, makes resource nodes far better. should pick up the drag that is costing resources to send blob to corpse.
> Updating Resource to /tg/ standars along with factory

- code/modules/library/lib_machines.dm
- Added rules to upload computer
- Added upload admin msg 
- DB now logs ckeys of uploaders, no more digging through logs.
Cleaned out DB of non-fluff books, still tons left to do. We were up to 500 books, making it hard to find the good ones from the copypasta of classic literature, erotic novels, dubs, wikipedia copypasta (really?), etc.
> Library Fixes

- code/game/objects/items/weapons/storage/belt.dm
- code/modules/mob/living/carbon/superheroes.dm
- Owlman belt contents now properly updates contents on reload when open
- Fixed typo in E-N class, causing him not to appear in check antagonists
> Couple of superhero fixes

- code/modules/mob/living/carbon/human/login.dm
- code/modules/mob/living/login.dm
- Ventcrawler code make a runtime that happened for every person joining server, so unable to check other runtimes.
> Mob login runtime fix

- code/modules/mob/living/living_defense.dm
- This behavior was removed from the GUI overhaul, this adds it back.
> Allows GUI buttons for accessories

- code/modules/mob/living/carbon/carbon.dm
- code/modules/recycling/sortingmachinery.dm
This commit fixes a couple bugs with ventcrawling, and makes packages work
correctly again, instead of just qdelling themselves.
Fixes #1041
> Fix ventcrawling, Fix packages qdelling things

- code/__HELPERS/game.dm
- code/modules/reagents/Chemistry-Colours.dm
Ports https://github.com/d3athrow/vgstation13/pull/4414
Properly accounts for different blood colors.
> Simpler color mixing

- code/game/turfs/turf.dm
This may be the cause of a lot of the lag. Profiler was going pretty crazy with Entered()
> Adds checks for lighting overlays to Entered()

- code/modules/lighting/light_source.dm
- code/modules/lighting/lighting_process.dm
- We were missing schecks in the overlay file.
> LIGHTING - Fixed divide by zero, optimize performance

- code/__HELPERS/mobs.dm
- code/defines/procs/statistics.dm
- code/game/gamemodes/nuclear/pinpointer.dm
- code/game/objects/explosion.dm
- code/game/objects/items/stacks/medical.dm
- code/modules/admin/verbs/adminjump.dm
- code/modules/mob/living/carbon/human/human.dm
- code/modules/mob/living/carbon/metroid/say.dm
- code/modules/mob/living/carbon/species.dm
- code/modules/mob/living/living.dm
- code/modules/mob/living/simple_animal/friendly/farm_animals.dm
- code/modules/mob/living/simple_animal/parrot.dm
- code/modules/organs/organ_external.dm
This fixes an infinite loop, and a bunch of runtimes, most of which probably won't have any noticeable impact on gameplay. Fortunately, several of them *will* have a significant impact on how quickly we hit runtime overload.
As part of the add_logs fix, admins may notice that the attack_logs in VV now include attacks from NPCs which aren't otherwise logged. Previously, these all simply runtimed and added logs to nothing.
> Runtime (and an infinite loop) Fixes

- code/__HELPERS/unsorted.dm
- code/game/mecha/mecha.dm
- Ported from https://github.com/d3athrow/vgstation13/pull/4378
- Mechas sent from Mass Drivers now break through windows, grilles, tables, and hurt people
- OH YEAAAAAAAAAAAH
https://dl.dropboxusercontent.com/u/33846352/byond/dreamseeker%202015-05-10%2005-38-31-07.webm
> Mechas breakthrough

- code/modules/lighting/lighting_overlay.dm
> Fix space cleaner 'cleaning' lighting

- code/game/machinery/biogenerator.dm
Fixes bug #1076 and displays a warning message telling the user that the
beaker is full.
> Biogenerator fix

- code/game/gamemodes/changeling/traitor_chan.dm
> Apply new antag-restricted-roles stuff to traitorchan

- code/modules/research/designs/comp_board_designs.dm
This commit fixes the designs for the GAC, the Tank Control, and the AAC.
> Fix GAC, tank control, AAC boards

- code/__DEFINES/atmospherics.dm
- code/datums/gas_mixture.dm
- code/game/gamemodes/cult/cult_items.dm
- code/game/gamemodes/shadowling/shadowling_items.dm
- code/modules/admin/verbs/diagnostics.dm
- code/modules/clothing/clothing.dm
- code/modules/clothing/gloves/color.dm
- code/modules/clothing/gloves/miscellaneous.dm
- code/modules/clothing/head/hardhat.dm
- code/modules/clothing/head/helmet.dm
- code/modules/clothing/head/misc_special.dm
- code/modules/clothing/shoes/colour.dm
- code/modules/clothing/shoes/miscellaneous.dm
- code/modules/clothing/spacesuits/alien.dm
- code/modules/clothing/spacesuits/plasmamen.dm
- code/modules/clothing/suits/armor.dm
- code/modules/clothing/suits/utility.dm
- code/modules/clothing/under/miscellaneous.dm
- code/modules/mob/living/carbon/human/life.dm
- code/modules/mob/living/carbon/human/species/golem.dm
- code/modules/mob/living/simple_animal/tribbles.dm
- code/modules/ninja/suit/gloves.dm
- code/modules/ninja/suit/shoes.dm
Ok...short end of it:
- Updates Gas Datums to TG's latest standards
- Uptdates Atmospherics defines to TG's latest standards
- This means that clothing has some different define names, but the overall effects are the same.
There's still some quirks about LINDA, even with this,but this should help eleminate some of the differences and help us pin down remaining bugs.
Needs a lot of scrutiny and look-through by @Tigercat2000
No runtimes or odd behaviors that I could see, initially.
> LINDA--Updated Gas Datums and Atmospheric Defines

- code/game/vehicles/spacepods/spacepod.dm
Fixes #1099
Refactors a couple ridiculous spacepod verbs with the universal CheckIfOccupant2 proc, Makes the toggle doors verb a bit better and shorter.
> Refactor a few spacepod verbs, Fix being unable to open 2 tile poddoors

- code/game/vehicles/spacepods/spacepod.dm
This commit makes a major refactor to spacepod code, mostly just cleaning
up the huge mess I left behind with the two-seater code.
This commit also adds a small feature: Based on their icon_state,
spacepods will have different headlight colors.
> Refactor, Light colors for Spacepods.

- code/modules/reagents/Chemistry-Recipes.dm
- code/modules/reagents/reagent_containers/food/snacks.dm
Soy sauce is definitely not made from acid, so I made the recipe more realistic, using the INTERNET!
Also, Kahlua is made from rum or vodka in addition to the ingredients already included, so I added that.
Sake is made from rice alcohol and it is by and large always diluted by water, so that was added to the recipe.
> Make Sake,Kahlua, and Soy Sauce Recipe more realistic

- code/modules/library/lib_machines.dm
This incredibly popular feature has been broken for nearly two weeks now, and nobody said anything about it until today! What's up with *that?*
Fixes #1138
> Fixes uploading books to the library database

- code/game/objects/structures/crates_lockers/closets/job_closets.dm
Gives the janitor a bar of soap.
Why he didn't have one before is beyond me; should help him clean off some unreachable/difficult to reach areas.
> Janitor--Bar of Soap

- code/datums/mind.dm
- code/game/gamemodes/objective.dm
- code/game/gamemodes/traitor/traitor.dm
After a discussion, it was quite clear the speciesist objective was going to go...soo..
- Removes Speciesist objective.
- Slightly increases the chance for hijack to show up.
> Removes Speciesist Objective

- code/modules/reagents/Chemistry-Reagents.dm
- code/modules/reagents/reagent_containers/food/snacks.dm
- code/modules/reagents/reagent_containers/glass/bottle.dm
Got merged in too soon.
Title is self-explanatory.
> Removes Nanomachines

- code/modules/mob/new_player/sprite_accessories.dm
Fixes female Vulpkanin not being able to select from facial fur styles.
> Vulpkanin Facial Fur Fix

- code/__HELPERS/unsorted.dm
> Fix getPixelDistance()

- code/__DEFINES/combat.dm
- code/modules/mining/equipment_locker.dm
- code/modules/mob/living/simple_animal/hostile/bear.dm
- code/modules/mob/living/simple_animal/hostile/hostile.dm
- code/modules/mob/living/simple_animal/hostile/mining_mobs.dm
- code/modules/mob/living/simple_animal/hostile/spaceworms.dm
- code/modules/mob/living/simple_animal/simple_animal.dm
Ports the following:
tgstation/-tg-station#1780
Part of tgstation/-tg-station#6278 (Not including faction transferring)
tgstation/-tg-station#8206
tgstation/-tg-station#8543
This should mean that we're more or less up to date with /tg/'s mobs, which would then allow me to port /tg/ mining over. This compiles, but has not yet been tested.
> simple_animal and simple_animal/hostile Refactor

- code/game/dna/genes/monkey.dm
- code/game/machinery/kitchen/monkeyrecycler.dm
- code/modules/mob/living/carbon/human/human.dm
- code/modules/mob/living/carbon/human/species/monkey.dm
- code/modules/mob/living/carbon/primitive/dionaold.dm
- Fixes #1182 
- Fixes invisble nymphs
- Fixes monkeys genetics stuff
- Fixes being able to dress up monkeys like people. Silly monkeys, you're not people!
> Monkey Fixes

- code/game/dna/genes/monkey.dm
- Fixes monkeys still dropping their organs. #1196
> Monkey Fixes #2

- code/game/gamemodes/shadowling/shadowling.dm
This was being sent once for every shadowling, oops.
> Fixes Shadowling Intercept

- code/modules/reagents/grenade_launcher.dm
- Fixes the sprite because the pie cannon starts loaded.
> Small sprite fix

- code/LINDA/LINDA_turf_tile.dm
Fixes hotspots not being removed when a turf is Del()'d
> LINDA Fix for Turfs

- code/game/gamemodes/changeling/powers/mutations.dm
- code/game/objects/items.dm
- code/game/objects/items/weapons/twohanded.dm
- code/modules/clothing/suits/armor.dm
- code/modules/mob/living/carbon/human/human.dm
- code/modules/mob/living/carbon/human/human_defense.dm
- code/modules/mob/living/living.dm
Just a number of fixes from TG:
- Simplifies+refactors the ability to reflect lasers+energy projectiles
- fixes shields not properly blocking ranged projectiles despite saying they did
- Fixes shields not shielding against simple animals and slimes
- Fixes Godmode not properly making people, well, invincible
- Fixes it so that items with NOSHIELD (chainsaw, esword) properly pierce shield based items.
> Fixes and Tweaks to Defenses

- code/datums/datumvars.dm
- code/datums/mind.dm
- code/game/machinery/constructable_frame.dm
- code/modules/clothing/clothing.dm
- code/modules/clothing/under/accessories/accessory.dm
- code/modules/computer3/lapvend.dm
- code/modules/mob/living/carbon/human/examine.dm
- code/modules/mob/mob.dm
- code/modules/reagents/reagent_containers/food/snacks.dm
* Fixes admins de-antagging a shadowling/thrall deleting the Shadowling Hivemind language entirely, and also not removing shadowling abilities from a shadowling's mind.
* Fixes player-controlled corgis being able to consume food as fast as they could click.
* Also fixes corgis being able to go slightly above their maximum health by eating.
* Fixes accessories' icons getting stuck in your hand slots when quick-equipped. (Fixes #716)
* Fixes laptop vendors asking for a PIN when your account's security level wasn't high enough to require one. (Fixes #1199)
* Also fixes some missing line breaks in the order confirmation HTML.
* Fixes dismantling machine frames causing the loss of some items. (Fixes #1194)
* Fixes limb stumps not showing up properly when you examine someone.
* Fixes a …
> Various Minor Fixes

- _maps/cyberiad.dm
- code/controllers/shuttle_controller.dm
Fixes two references to the NCS Cyberiad.
It's been the NSS Cyberiad for months now.
> Fixes NCS Cyberiad References

- code/modules/mob/mob_grab.dm
Fixes:
- Headbutting not working at all.
- Throwing people around while not next to them.
Title is because I can't remember how many other fixes I have made.
> Grab Fixes MKIIIIIIIIVIVIvXXVV. 

- code/game/gamemodes/objective.dm
Should help clarify just where you can escape with and what "free" means.
> Clarifies the Escape Objective

- code/_onclick/hud/hud.dm
- code/_onclick/hud/monkey.dm
- code/game/dna/genes/monkey.dm
- code/game/gamemodes/changeling/changeling.dm
- code/game/gamemodes/changeling/changeling_power.dm
- code/game/gamemodes/changeling/evolution_menu.dm
- code/game/gamemodes/changeling/powers/humanform.dm
- code/game/gamemodes/changeling/powers/lesserform.dm
- code/game/objects/items.dm
* Fixes monkeys bypassing equipment restrictions by quick-equipping.
* Fixes being monkeyized leaving your jumpsuit equipped.
* Fixes various mismatches between the Monkey and Human HUDs, which were resulting in visual oddities, missing HUD elements, and runtimes.
* Fixes changelings stealing DNA from monkeys.
* This should stop changelings turning people into monkeys and the various problems caused by them doing that.
* Fixes changelings' Lesser Form being various kinds of broken.
* You can now leave Lesser Form.
* You can no longer use all of your changeling powers in Lesser Form.
* Lesser form still won't preserve implants. Being monkeyized should probably just preserve them, but I'm not too worried about it for now.
* Leaving Lesser Form ~~will not~~ probably shouldn't gib you.
* …
> Fixes Monkey Issues (Changelings, HUD, thinking they're people)

- code/game/gamemodes/meteor/meteor.dm
- code/game/gamemodes/meteor/meteors.dm
- Waves now last 5-15 minutes
- You now get have 5-15 minutes to repair after each wave
> Adds waves to meteor gamemode

- code/modules/projectiles/projectile/beams.dm
This calls bullet_act if lightning from power gloves hits something. Power gloves will now correctly deal damage. Fixes #1263.
> Fixes power gloves lightning not calling bullet_act.

- code/__HELPERS/unsorted.dm
- code/game/machinery/computer/prisoner.dm
- code/game/objects/items/shooting_range.dm
- code/game/objects/structures/target_stake.dm
- code/modules/admin/player_panel.dm
- code/modules/admin/verbs/playsound.dm
- code/modules/power/apc.dm
- code/modules/reagents/Chemistry-Recipes.dm
Basically two optimization PRs in one:
https://github.com/Baystation12/Baystation12/pull/5207
- replaces get_turf_loc with get_turf to help cut down on runtimes
https://github.com/tgstation/-tg-station/pull/9838
- much faster get_turf
> Get Turf Optimizations

- .travis.yml
- code/game/objects/items/weapons/swords_axes_etc.dm
- code/modules/mob/living/carbon/carbon.dm
- code/modules/mob/mob_grab.dm
Preps for moving to 508.1287
- Throw is an actual proc in that version of BYOND, therefore we can't exactly use it in the code anymore.
- Updates Travis to be based around 508.1287.
> Makes the Code Compile for 508.1287+Travis Update

- code/modules/projectiles/guns/energy/hos.dm
Fixes HoS's gun so that the stun mode has the proper cooldown/delay on it.
> HoS Lasergun Fix

- code/game/objects/items/weapons/storage/bags.dm
- code/game/objects/items/weapons/storage/uplink_kits.dm
Fixes the bookbag, space suit kit, and syndicate rig kit not being able to hold items.
> Can Hold Fixes

- code/datums/spell.dm
- code/game/objects/effects/effect_system.dm
Fixes the recently added Harvester's paralysis smoke spell not working at all.
> Harvester Spell Fix

- code/game/objects/explosion.dm
Courtesy of VG
Re-enables explosions pausing lighting updates until the BOOM is complete.
> Optimizes Explosions

- code/datums/helper_datums/teleport.dm
Updates the teleport datum to TG's standards.
Fixes https://github.com/ParadiseSS13/Paradise/issues/1299
Big thanks to @phil235 https://github.com/tgstation/-tg-station/pull/9965 for fixing the hand tele issues.
> Updates+Fixes Teleport Datum

- code/game/gamemodes/steal_items.dm
Fixes those lazy ass syndicates giving those lazy ass engineers even more excuse to be lazy ass engineers.
(fixes engineers getting the plasma tank objective).
> Fixes Lazy Syndicates

- code/modules/clothing/suits/jobs.dm
I misspelt Blueshield for Blueshied so i am ashamed.
> Blueshied to Blueshield Fix.

- code/game/gamemodes/revolution/revolution.dm
Title. Whoops.
Note; Will break low pop rev, as the round can immediately end on starting if there are no heads.
But low-pop rev being broken is better than all rev being broken, right?
> Fix revolution. Antag-selection oopsied it.

- code/game/turfs/space/space.dm
- code/game/turfs/turf.dm
> oh god I hope this fixes spess

- code/datums/uplink_item.dm
- code/game/objects/items/weapons/grenades/chem_grenade.dm
- code/game/objects/items/weapons/storage/uplink_kits.dm
- code/modules/reagents/newchem/medicine.dm
- code/modules/reagents/newchem/toxins.dm
- code/modules/reagents/reagent_containers/glass/bottle.dm
Converts Sarin into Tabun
- Harder/more time consuming to make, but better yield
- Wiki friendly, I guess
- same effects as Sarin and same treatment
> Sarin -> Tabun

- code/game/objects/items/weapons/handcuffs.dm
And made it say that they ziptie-cuffed instead of handcuffed, if this proc has to exist.
> Fix ziptie log being backwards.

- code/datums/supplypacks.dm
Adds Brute Trauma Treatment Kits to cargo.
not to be confused with the Advanced Brute Trauma kit
> Supply crates medical

- code/game/turfs/space/space.dm
Actually I realised that ever since I started coding.
Fixes #1379 for REAL this time
> In which I realise that I am an idiot.

- code/modules/clothing/spacesuits/rig.dm
Players:
-Explains a bit further on what happens when you switch from combat mode to travel mode, and vice versa. Hopefully this will keep newer Nuke Ops players from dying less often.
http://nanotrasen.se/forum/viewtopic.php?f=12&p=34708#p33996 relevant thread.
> Syndicate Hardsuit elaborations

- code/modules/flufftext/Hallucination.dm
- code/modules/mob/living/carbon/human/life.dm
- code/modules/mob/living/living_defines.dm
tgstation/-tg-station#9791
>This commit adds a number of new hallucinations and increases the
modularness of the hallucination system. Included hallucinations:
- Alien Hunter
- Alien hunter comes out of the nearest vent, leaps and stuns you, then
crawls back into the vent.
- Plasma flood
- Singularity
- Stage 4 singularity appears and chases you.
- Fight sounds
- Series of sounds that sound like a fight.
- Clown-visions
- Delusion, which makes an image of a mob standing still.
- Fake bolted doors
- A number of doors will appear to become bolted, via overlay.
- Fake speech/radio messages.
- This makes it appear as if someone has said something, either via
speech or radio, using one language from their avalible languages.
Radio messages will only happen if there are no people in view to say …
> New hallucinations

- code/modules/reagents/Chemistry-Holder.dm
- code/modules/reagents/Chemistry-Reagents.dm
- code/modules/reagents/reagent_containers/food/condiment.dm
- code/modules/reagents/reagent_containers/food/drinks.dm
- code/modules/reagents/reagent_containers/food/snacks.dm
- code/modules/reagents/reagent_containers/pill.dm
Fixes Food and Pills so that they actually transfer their reagents properly
- Big thanks to Krausus for helping with locating and correcting the issue
Fixes IPCs being able to eat pills.
- They have a monitor for a head, where do you think you're going to put that?
Fixes IPCs being immune to the soothing effects of water
- IPCs that are on fire can be properly doused with a splashing of water.
> [High-Priority][Fix] Food/Pill Fixes

- code/ATMOSPHERICS/pipes.dm
- code/__HELPERS/unsorted.dm
- code/game/machinery/atmoalter/portable_atmospherics.dm
- code/game/objects/items/devices/PDA/PDA.dm
- code/game/objects/items/devices/scanners.dm
- code/game/objects/items/weapons/flamethrower.dm
- code/game/objects/items/weapons/tanks/tanks.dm
- code/modules/assembly/bomb.dm
- code/modules/power/singularity/collector.dm
Just a simple analyzer scan refactor.
Functionally, scanning atmospheric things is exactly the same as before--this just saves some lines of code. Quite possibly one of the most boring PRs ever!
> Analyzer Scan Refactor

- code/modules/projectiles/gun.dm
- code/modules/projectiles/projectile.dm
Fixes emitter beams not properly pooling.
> Fixes Emitter Beam Pooling

- code/modules/flufftext/Dreaming.dm
Small dreaming refactor
- Has a few more dream texts related to Paradise species and jobs
- Spanclassses
> Dreams Refactor

- code/game/turfs/turf.dm
- code/modules/lighting/lighting_overlay.dm
Fixes #1401 
Fixes #1415 
Dunno if I caused this but these 2 things are happening when placing carpet:
https://dl.dropboxusercontent.com/u/107028026/ShareX/2015/07/2015-07-04_17-31-04.webm
https://dl.dropboxusercontent.com/u/107028026/ShareX/2015/07/2015-07-04_17-31-51.webm
> Fixes fucked up lights on carpets and the alike.

- code/game/machinery/kitchen/gibber.dm
Kinda. I made it longer and more complicated, but less ridiculous in
amount of icon operations.
Also fixed an issue with people in the gibber ending up in nullspace and shortly after being deleted by the GC.
> Refactor gibber animation code.

- code/_globalvars/lists/objects.dm
- code/game/machinery/syndicatebeacon.dm
- code/modules/power/singularity/field_generator.dm
- code/modules/power/singularity/generator.dm
- code/modules/power/singularity/particle_accelerator/particle.dm
- code/modules/power/singularity/particle_accelerator/particle_accelerator.dm
- code/modules/power/singularity/particle_accelerator/particle_control.dm
- code/modules/power/singularity/particle_accelerator/particle_emitter.dm
- code/modules/power/singularity/singularity.dm
Just some singulo equipment cleanup and fixes
- Cleans out some old, unused code for R-UST regarding PA particles
- Fixes hacked overloaded PA's doing nothing
- Fixes admins not being notified when the singularity escapes
- Fixes some construction behavior when attempting to build the PA in space or while stunned
- Adds in Destroy()'s for the PA and Control Box
> Singulo Equipment Cleanup and Fixes

- code/game/atoms.dm
- code/game/atoms_movable.dm
- code/game/objects/effects/effect_system.dm
- code/game/objects/items.dm
- code/modules/events/tgevents/vent_clog.dm
- code/modules/projectiles/guns/projectile.dm
- code/modules/reagents/Chemistry-Holder.dm
- code/modules/reagents/Chemistry-Reagents.dm
- code/modules/reagents/reagent_containers.dm
Just a third pass at Destroys
Requesting review by @Krausus 
Haven't noticed any odd behavior, runtimes, or the likes, but I'm probably missing something =X
Also, I realize that the proc delete for effects is qenuinely terrible, but that's for another day.
> Destroy Pass III

- code/modules/reagents/Chemistry-Holder.dm
- code/modules/reagents/Chemistry-Recipes.dm
- code/modules/reagents/newchem/drinks.dm
- code/modules/reagents/newchem/drugs.dm
- code/modules/reagents/newchem/food.dm
- code/modules/reagents/newchem/medicine.dm
- code/modules/reagents/newchem/other.dm
- code/modules/reagents/newchem/pyro.dm
- code/modules/reagents/newchem/toxins.dm
- code/modules/reagents/reagent_containers/food/drinks/drinkingglass.dm
- code/modules/research/xenoarchaeology/chemistry.dm
Adds the code functionality to make a chemical reaction only occur when at or below a specified temperature.
- Chemical reactions have a new var named "max_temp" which defines the highest temperature that the reaction can occur at. Above this number, the reaction will not occur.
Adds new reaction for freezing water into ice
- Must be at or below 270K to turn water to ice
Adds two new reagents/drinks: Applejack and Jack Rose cocktail
- Applejack is obtained by freezing cider at or below 270K
- Applejack is slightly more potent than cider, due to it's alcohol concentration being higher
- Jack Rose is a new mixed drink that is 4 parts Applejack, 1 part Lemon Juice
Only Ice and Applejack utilize the cold reactions at this time, but the functionality is in place for future reactions.
- This …
> Cold Reactions and Applejack

- code/game/objects/items/devices/chameleonproj.dm
Updates the chameleon projector from TG.
Fixes a number of issues with it; no more invisible item exploits, colons, relative pathing or all that jazz.
> Updates Chameleon Projector

- code/controllers/master_controller.dm
- code/datums/datacore.dm
- code/datums/mind.dm
- code/game/gamemodes/gameticker.dm
- code/game/machinery/computer/medical.dm
- code/game/machinery/overview.dm
- code/game/machinery/telecomms/logbrowser.dm
- code/game/objects/effects/effect_system.dm
- code/modules/admin/verbs/one_click_antag.dm
- code/modules/hydroponics/seed_controller.dm
- code/modules/mob/living/carbon/brain/death.dm
- code/modules/mob/living/carbon/human/update_icons.dm
- code/modules/mob/living/silicon/ai/latejoin.dm
- code/modules/mob/living/silicon/pai/death.dm
- code/modules/mob/new_player/logout.dm
- code/modules/mob/new_player/new_player.dm
- code/modules/power/lighting.dm
Just a second pass of qdel()'s; these are the ones I was unsure about; some of them, though, I just plain missed.
Two qdel()'s were changed back to del's, because I'm pretttty sure no qdel()'s should be involved in with controllers.
Requesting review by @Krausus.
> qdel pass II

- code/__HELPERS/timed_alerts.dm
- code/game/gamemodes/borer/borer.dm
- code/game/objects/items/weapons/storage/bags.dm
- code/modules/admin/player_notes.dm
- code/modules/flufftext/Hallucination.dm
- code/modules/mob/living/living_defense.dm
Replaces a few del X with del(X).
Also removed some unused living defense code related to stun-beams.
please use del responsibly.
> Changes a few del to del()

- code/modules/mob/living/carbon/human/life.dm
This commit cleans up the human/life.dm file, which contains their Life() proc.
Things changed:
- Removed all colon operators
- There was only one. It belonged to cryobags.
- Removed all remaining color macros.
- Removed all relative pathing.
> Clean up human Life()

- code/controllers/verbs.dm
- code/modules/lighting/lighting_process.dm
This was something not included when the new lighting system was included--should have been, to allow coders and such to make tweaks to it and test with it, but it wasn't. Oh well. Here it is.
> Adds in Lighting Controller Debugability

- code/__DEFINES/lighting.dm
- code/game/turfs/turf.dm
- code/modules/lighting/light_source.dm
- code/modules/lighting/lighting_overlay.dm
- code/modules/lighting/lighting_system.dm
- code/modules/lighting/lighting_turf.dm
Requested by @Fox-McCloud after I showed him some numbers concerning the performance increase.
https://github.com/Baystation12/Baystation12/pull/10070
There's a performance increase on apply_lum() of about 33%
Also tears out hi res lighting since it kills any clients
> Implements the new bay lighting optimization.

- code/modules/mob/living/silicon/robot/drone/drone_console.dm
Fixes https://github.com/ParadiseSS13/Paradise/issues/1531
> Drone Console Fix

- code/game/gamemodes/blob/blobs/blob_mobs.dm
Fixes Blobbernaughts being unkillable.
Oops.
> Fixes Immortal Blobbernaughts

- code/game/gamemodes/blob/blobs/blob_mobs.dm
Uh yeah, I forgot there was "spore" and "spores" here.
Spores isn't so bad....spore, however....
> Fixes Blob Self Replication

- code/game/jobs/job/medical.dm
- code/game/jobs/job/science.dm
- code/game/jobs/job/support.dm
- code/game/jobs/job/support_chaplain.dm
Largely a continuation of a previous PR to fix up item spawning.
This should help better prevent oddities with item spawning at round-start/joining the game.
> Item Equipment Fixup

- code/game/machinery/computer/buildandrepair.dm
Some day, all the quotes for pathed things need to be killed off....so updates don't end up doing stuff like this..
Fixes it so power monitors can be constructed.
> Fixes the Power Monitor Being Unconstructible

- code/game/objects/items/weapons/grenades/clowngrenade.dm
Fixes https://github.com/ParadiseSS13/Paradise/issues/1582
invisible banana grenades
> Banana Grenade Fix

- code/modules/admin/admin_verbs.dm
See title.
Also replaced some color macros.
> Remove invisimin icon-setting. It's terrible.

- code/modules/mob/living/simple_animal/friendly/butterfly.dm
No more aquashing butterflies.
> Fixes a butterfly typo.

- code/modules/mob/living/simple_animal/hostile/mining_mobs.dm
Don't know how I forgot about this one.
> Fixes hivelord infinitely dropping cores

- code/modules/mob/living/simple_animal/revenant/revenant.dm
Fixes revenants never properly dying.
> Revenant Death Fix

- code/datums/uplink_item.dm
On recommendation of @Markolie 
Lowers the cost of clown grenades from a whopping 8 TC to 5 TC.
> Lowers Cost of Clown Grenades

- code/game/mecha/mech_bay.dm
- code/modules/admin/admin.dm
- nano/templates/mech_bay_console.tmpl
Changes:
1) Refactors the mech recharger, and makes it use NanoUI. Ported from Bay.
> Refactor mech recharger

- code/game/gamemodes/newobjective.dm
- code/game/gamemodes/steal_items.dm
- code/game/objects/structures/girders.dm
- code/game/turfs/simulated/walls.dm
- code/game/turfs/simulated/walls_reinforced.dm
- code/modules/mob/living/silicon/robot/robot_modules.dm
- code/modules/research/designs/mining_designs.dm
- Fixes mining drones having access to a plasma cutter energy weapon, replaced with a diamond drill. Functionality is almost identical to what it was with old plasma cutters.
- Pathing fixes for diamond drills.
> Diamond Drill and Drone Fixes

- code/__DEFINES/misc.dm
- code/modules/lighting/light_source.dm
Some DVIEW lighting fixes from Bay.
The previous PR of mine had some oddities about lights updating.
Tested and no oddities were noticed regarding this.
> DVIEW Lighting Fixes

- code/modules/lighting/light_source.dm
Prevents lighting from runtiming out the butt.
Requesting review by @PJB3005
> Lighting Runtime Fix

- code/modules/power/solar.dm
Changes:
1) Might fix https://github.com/ParadiseSS13/Paradise/issues/1624.
> Solar control initialization fix

- code/game/objects/items/weapons/handcuffs.dm
- code/modules/power/cable.dm
Changes:
1) Fixes https://github.com/ParadiseSS13/Paradise/issues/1627.
> Fix cable coil sprite

- code/modules/projectiles/projectile.dm
Changes:
1) Fixes https://github.com/ParadiseSS13/Paradise/issues/1629.
> Mecha turret fix

- code/game/objects/structures/mirror.dm
> Replace (TM) in mirror title with actual TM character

- code/modules/recycling/disposal.dm
Makes disposals properly GC far more reliably.
Not 100% certain, but this also seems to resolve a runtime related to disposals, as well.
> Makes Disposals GC

- code/game/machinery/camera/camera.dm
Fixes Xenos not being able to flash/kill cameras.
> Fixes Xeno Camera Slashing

- code/modules/research/circuitprinter.dm
Fixes a runtime error involving the circuit imprinter
> Imprinter Runtime Fix

- code/datums/uplink_item.dm
- code/game/objects/explosion.dm
- Fixes https://github.com/ParadiseSS13/Paradise/issues/1654 (poison traitor bottle = pizza bomb)
- Fixes lopsided reactionary explosions
> Fixes Explosion and Poison Traitor Bottles

- code/game/machinery/bots/bots.dm
- Makes bots GC better
- Bots being removed from the bot processing list now happens in Destroy() rather than a specific proc...should help cut down on bots never being removed from the bot controller.
> Bot GC+Processing Fix

- code/modules/clothing/clothing.dm
Almost every codebase has this.
Pretty much, now, when you click 'toggle suit sensors', a window will pop up with suit sensors options.
> Ports Baystation's suit sensors

- code/modules/recycling/disposal.dm
Changes:
1) This might fix the disposal non-responsiveness issue.
> Attempted disposals fix

- code/modules/research/designs/mining_designs.dm
Fixes the category for the advanced plasma cutter and the sonic jackhammer.
> Catergory Fix for Protolathe

- code/modules/admin/verbs/debug.dm
Pretty much what it says on the tin. Allows for [this](http://gfycat.com/GrimyCheapAnchovy) to easily be done without looking through a list of mobs. (Black bars on the side were because OBS was being uncooperative, odd floor tile textures are because of view ranged being edited.)
One other change is that if you try to call a proc that doesn't exist, it will tell you that and cancel out of proc cal instead of asking you for arguments and *then* telling you the proc doesn't exist after you input them all.
Port of tgstation/-tg-station#11027
> Allows use of marked objects/datums in proc call

- code/__DEFINES/mob.dm
- code/game/dna/genes/goon_powers.dm
- code/modules/mob/living/carbon/human/death.dm
- code/modules/organs/organ_external.dm
- code/modules/virus2/effect.dm
Re-uplaod of this: https://github.com/ParadiseSS13/Paradise/pull/1679
Can be merged once it passes Travis.
Github had a fit about a merge conflict and absolutely refused to do anything.
> Dismemberment Tweaks

- code/modules/research/server.dm
Changes:
1) Fixes RnD server deconstruction. Previously screwdrivering didn't work.
> Fix RnD server deconstruction

- code/game/gamemodes/gameticker.dm
- code/game/gamemodes/heist/heist.dm
- code/game/gamemodes/scoreboard.dm
- code/game/objects/items/devices/uplinks.dm
Changes:
1) Fixes https://github.com/ParadiseSS13/Paradise/issues/1655.
2) Fixes Vox Heist end of round message.
> Fix traitor end of round message

- code/game/objects/explosion.dm
This PR mainly fixes lopsided reactionary explosions, by pre-caching the explosion resistance of every turf in the explosion area. This seems to actually make explosions _faster,_ since they ex_act fewer turfs. There's also a couple other changes...
* Fixes lopsided reactionary explosions.
* Fixes explosions calling `ex_act(0)` on things that weren't actually exploded.
* Makes explosion profiling use btime, when available.
> Explosion Fixes and Profiling Improvement

- code/modules/reagents/reagent_containers/syringes.dm
Should hopefully resolve #1705
> Makes lethal injection syringes far more deadly

- code/game/objects/items/weapons/storage/toolbox.dm
- code/modules/clothing/gloves/color.dm
Changes:
1) Gives the syndi toolbox red insulated gloves, based on /tg/. It replaces the toolbox's wires.
> Give syndi toolbox insulated gloves

- interface/skin.dmf
Suggested by @melandor0
This (probably) adds an option to the dropdown menu, to set the game to forced 48x48 mode.
> Add 48x48 option to dropdown menu

- code/__HELPERS/text.dm
- code/modules/client/preferences.dm
- code/modules/mob/living/carbon/human/emote.dm
- code/modules/mob/living/silicon/silicon.dm
- code/modules/mob/mob.dm
Changes:
1) Fixes encoding issues in flavour texts (i.e. ' not showing up properly).
> Flavor text encoding fix

- code/datums/mind.dm
- code/game/gamemodes/cult/cult.dm
- code/game/gamemodes/cult/runes.dm
- code/game/machinery/computer/communications.dm
- code/modules/admin/verbs/randomverbs.dm
- code/modules/mob/living/carbon/human/human.dm
- code/modules/mob/living/silicon/ai/ai.dm
- code/modules/mob/living/silicon/pai/software_modules.dm
Changes:
1) Fixes https://github.com/ParadiseSS13/Paradise/issues/1772.
2) Fixes simple animals being able to loot pockets. Fixes https://github.com/ParadiseSS13/Paradise/issues/1770.
3) Fixes AI's getting alerts from pAI doorjacking on other z-levels. Fixes https://github.com/ParadiseSS13/Paradise/issues/1743.
4) Fixes sanitization in shuttle call reasons - apostrophes and such should now show up properly.
> Cult loyalty implant fix, other fixes

- code/modules/recycling/disposal.dm
Changes:
1) Fixes janitorborgs being unable to empty their trashbags into disposals.
> Disposal trash bag fix

- code/game/machinery/camera/camera.dm
- code/game/machinery/camera/tracking.dm
- code/game/objects/items/weapons/cards_ids.dm
- code/modules/mob/hear_say.dm
- code/modules/mob/language.dm
- code/modules/mob/living/carbon/human/say.dm
- code/modules/mob/living/silicon/ai/ai.dm
Changes:
1) Cleans up the way AI tracking works.
Fixes https://github.com/ParadiseSS13/Paradise/issues/1763.
> AI tracking update

- code/game/objects/items/toys.dm
As it says on the title.
I'm not sure why they never did this.
> Griffin/ Owl toys actually make Griffin/ Owl noises.

- code/game/machinery/computer/buildandrepair.dm
- code/modules/projectiles/guns/energy/hos.dm
Changes:
1) Renames the head of security's energy gun to "head of security's energy gun".
2) Renames "Computer-frame" to "computer frame".
> Rename the head of security's energy gun

- code/game/gamemodes/shadowling/shadowling.dm
- code/game/gamemodes/shadowling/special_shadowling_abilities.dm
Should fix thralls not getting their spells removed upon dethralling.
> Shadowling Dethrall Fix

- code/modules/mob/mob_helpers.dm
Changes:
1) Fixes another missing dsay check. Not as high priority - only determines whether or not ckeys always show up.
> Another dsay fix

- code/modules/events/mass_hallucination.dm
> Making TullyBBurnalot happy (AKA the dumbest grammar PR ever.)

- code/datums/wires/nuclearbomb.dm
- code/game/gamemodes/nuclear/nuclearbomb.dm
- nano/templates/nuclear_bomb.tmpl
- paradise.dme
Changes:
1) Makes the nuclear bomb use the wires datum.
2) Adds some admin messaging to the nuke.
3) Engaging a nuke will now set Delta alert level, unless it's a syndicate nuke (e.g. nuke ops).
4) Nuclear bombs can no longer be anchored in space.
> Nuke update

- code/game/machinery/computer/security.dm
- code/modules/computer3/computers/security.dm
Noted this when i was updating records as warden one time, looks like a copy error from medical records probably so i figured i would fix it.
> [Text Edit] Crime is not a Disability

- code/modules/mob/living/silicon/pai/recruit.dm
We can do the same with posibrains, why not pAI's?
> Adds the ability to teleport to people who activate pAI cards.

- code/modules/research/designs/machine_designs.dm
Fixes Fox being retarded
- Emitters can now properly be produced
> Emitter Fix

- _maps/map_files/cyberiad/z3.dmm
- code/datums/cache/apc.dm
- code/game/machinery/computer/power.dm
- code/game/objects/items/devices/PDA/cart.dm
- code/modules/nano/modules/power_monitor.dm
- code/modules/power/power.dm
- nano/templates/pda.tmpl
- nano/templates/power_monitor.tmpl
Changes:
1) Adds some additional information to the power monitor screen.
2) Fixes an issue where power monitors would suddenly go blank.
3) Adds a missing disposal outlet to telecomms.
> Power monitor update

- code/game/machinery/poolcontroller.dm
Added logs to the pool, both attack and visible messages.
Hopefully no more `accidental` murders.
> pool logging

- code/modules/mob/living/carbon/alien/humanoid/emote.dm
> Allows xenos to use *flip.

- code/game/verbs/ooc.dm
Changes:
1) Fixes admins not seeing LOOC (was set to R_MENTOR, who aren't supposed to have it, and admins don't have R_MENTOR).
> Fix admins not seeing LOOC

- code/game/objects/items/robot/robot_upgrades.dm
- code/modules/mob/living/silicon/robot/robot.dm
- code/modules/mob/living/silicon/robot/robot_modules.dm
- code/modules/mob/living/silicon/robot/robot_movement.dm
Changes:
1) Gives engineerings borgs a permanent magboots effect: https://github.com/tgstation/-tg-station/pull/11427.
> Give engineering borgs a permanent magboots effect

- _maps/map_files/cyberiad/cyberiad.dmm
- code/_globalvars/lists/objects.dm
- code/datums/cache/air_alarm.dm
- code/datums/cache/powermonitor.dm
- code/game/machinery/alarm.dm
- code/game/machinery/computer/power.dm
- code/modules/admin/verbs/adminjump.dm
- code/modules/computer3/computers/message.dm
- code/modules/events/money_spam.dm
- code/modules/mob/living/silicon/pai/software_modules.dm
- code/modules/mob/living/simple_animal/constructs.dm
- code/modules/power/apc.dm
Changes:
1) Removes a few useless sortAtom's (which is a very resource intensive proc).
2) Removes a redundant air alarm in the atmos control room.
3) Gets rid of laggy construct Bump code.
> sortAtom removal, performance fixes

- code/game/machinery/rechargestation.dm
- code/game/objects/items/stacks/sheets/sheet_types.dm
Changes:
1) You can now build wheelchairs with fifteen metal sheets. Fixes https://github.com/ParadiseSS13/Paradise/issues/1897.
2) Fixes https://github.com/ParadiseSS13/Paradise/issues/1904.
> Allow for the construction of wheel chairs

- code/game/verbs/ooc.dm
Changes:
1) Fixes admins not seeing all LOOC's for real (and fixes https://github.com/ParadiseSS13/Paradise/issues/1879).
> Fix admin LOOC for real

- code/ATMOSPHERICS/components/unary/vent_scrubber.dm
- code/ZAS/Plasma.dm
- code/game/objects/items/weapons/grenades/flashbang.dm
- code/game/objects/items/weapons/tools.dm
- code/modules/power/supermatter/supermatter.dm
- code/modules/virus2/effect.dm
Changes:
1) Updates some messaging around mechanical eyes, and the "watery eyes" sympton will no longer affect you when you have mechanical eyes.
2) Fixes hitting scrubbers after welding them.
> Mechanicals eyes update

- code/modules/admin/topic.dm
Changes:
1) Fixes admins being unable to view papers/photos in paper bundles.
> Fix admin viewing paper bundles

- code/modules/mob/living/silicon/robot/emote.dm
I'm sorry.
@Markolie 
Fixes https://github.com/ParadiseSS13/Paradise/issues/1933
EDIT: Actually, this is a feature, since SOMEONE thought it was a good idea to make that intentional to spam.
(Am I even allowed to downvote my own PR's? :-1:)
> Fixes *halt spam.

- code/modules/customitems/item_defines.dm
Actually, derp fox cannot be fixed, but: https://github.com/ParadiseSS13/Paradise/issues/1923 can.
> Fixes Derp Fox

- code/game/gamemodes/cult/runes.dm
- code/stylesheet.dm
Changes:
1) Adds a custom style (red color, italicized) to cult messages to make them more distinguishable.
> Add custom styling to cult messages

- code/modules/reagents/reagent_containers/borghydro.dm
- code/modules/reagents/reagent_containers/hypospray.dm
Fixes https://github.com/ParadiseSS13/Paradise/issues/1930.
> Removes clowns

- code/modules/mob/living/carbon/human/life.dm
- code/modules/mob/living/simple_animal/friendly/spiderbot.dm
Changes:
1) Fixes cryo bags not resetting properly: Fixes https://github.com/ParadiseSS13/Paradise/issues/1972.
2) Fixes invincible spiderbots (this must've been a thing for ages).
> Fix invincible spiderbots and cryo bags

- code/modules/admin/admin_verbs.dm
- code/modules/admin/verbs/cinematic.dm
This will add the cinematic verb to the Event panel, will work like anormal nuke / AI override, meaning it will kill everyone (ending theround)
> Adds cinematic verb

- _maps/map_files/cyberiad/cyberiad.dmm
Muzzles are the best clothing item.
Re-adds the ballgag to security ![ballgag](http://puu.sh/jVKD3/ce5fb0b1a7.png)
> Return gag to security

- code/modules/research/rdconsole.dm
Fixes warnings related to making items 100% reliable.
Derp.
> Fixes RD Console Var Warning

- code/modules/lighting/light_source.dm
> Another lighting fix!

- code/game/gamemodes/changeling/powers/swap_form.dm
Fixes: https://github.com/ParadiseSS13/Paradise/issues/2018
Your target will no longer be able to talk on changeling hivemind and you (the ling) will still be able to.
> Changeling Swap Forms Language Fix

- code/game/machinery/alarm.dm
Changes:
1) Fixes https://github.com/ParadiseSS13/Paradise/issues/1402.
> Air alarm temperature fix

- code/modules/nano/modules/human_appearance.dm
Changes:
1) Fixes the skin tone/skin color option not showing up properly for certain races.
> Fix skin tone/color selection in CMA

- code/datums/material_container.dm
https://github.com/tgstation/-tg-station/pull/11772
Fixes autolathes rejecting stacks.
> Fixes Autolathes and Stacks

- code/game/supplyshuttle.dm
Changes:
1) Updates the shipping manifest so it's easier to tell which is which: it now includes the same data that the supply form does (what's been ordered, by who, what rank that person has).
> Update cargo shipping manifest

- code/modules/client/preferences.dm
Fixes display notices of body accessories if you don't have admin rights.
> Tails Notification Hotfix

- code/game/objects/items/stacks/sheets/mineral.dm
- code/modules/mining/ore.dm
port of: https://github.com/tgstation/-tg-station/pull/11622
Adds materials to ore
- unrefined ore will contain actual materials now
> Adds Materials to Ore

- code/game/mecha/mech_fabricator.dm
- code/game/objects/items/weapons/storage/lockbox.dm
- code/modules/research/designs/mechfabricator_designs.dm
Makes it so mech weapons spawn in a large lockbox
Adds in large lockboxes, basically just lockboxes with 1 slot that allows w_class 4
Controversial topic go, keep all discussion civil, thread here http://nanotrasen.se/phpBB3/viewtopic.php?f=12&t=5355
List of things that are locked: the LMG, cluster flashbangs, bolas, heavy and normal lasers, the carbine, scattershot, ion rifle, flashbang, and the missile rack
> Mech weapons spawn in lockboxes framework

- code/modules/mob/living/silicon/say.dm
> I have no idea why you would ever sanitize() say, it already strips html

- code/modules/research/designs.dm
- code/modules/research/designs/weapon_designs.dm
- code/modules/research/protolathe.dm
- code/modules/research/rdconsole.dm
From TG.
Fixes not being able to produce items/objects that have a reagent requirement.
> Protolathe Fix

- code/modules/research/rdconsole.dm
Fixes is so that the protolathe's reagent cost ACTUALLY goes down with efficiency and doesn't just display a number that is lower.
> Further Protolathe Fixes

- code/modules/mob/dead/observer/observer.dm
Changes:
1) Fixes https://github.com/ParadiseSS13/Paradise/issues/2095.
> Observer forceMove fix

- code/modules/reagents/oldchem/reagents/_reagent_base.dm
Reworks skin penetration of reagents.
Right, so, as some of you know some reagents penetrate the skin--not many, but a few of them do---this reworks how that functions.
On live, this functions in a very binary and snowflake manner; if you're wearing a biohood+biosuit, then it doesn't penetrate at all---that said, if you're wearing ANYTHING else, then it does penetrate.
This has been reworked to utilize the get_permeability_coefficient() proc to modify how effective a reagent will penetrate your skin.
If you're naked, well...100% of it is still going to transfer---if you're just in normal clothes, the vast majority of it is going to transfer. If you have a few protective items here or there, it'll greatly cut it down.....anddd if you're in a full biosuit, then you'll have immunity (unless …
> Reagent Skin Penetration Rework

- code/datums/material_container.dm
- code/datums/wires/wires.dm
- code/game/machinery/recycler.dm
- code/game/objects/structures/musician.dm
- code/modules/power/powernet.dm
- code/modules/research/protolathe.dm
- GC's a few datums
- Makes powernets actually qdel()
Tested it out; couldn't manage to find any of these datums in the hard GC area; they all GC'd well.
> GC a few Datums

- code/modules/mob/say.dm
> fix me() verb

- code/modules/mob/living/carbon/brain/brain.dm
- code/modules/mob/living/carbon/brain/say.dm
> Fix posibrains being unable to speak binary

- code/game/machinery/kitchen/monkeyrecycler.dm
This fixes the monkey recycler not changing the amount of monkeys consumed based on the manipulator inside.
> Monkey Recycler Micro Manipulator Fix

- nano/templates/pai_bioscan.tmpl
This fixes typos present within the pAI's bioscan function.
> Fixes some typos in the pAI's bioscan

- code/modules/mob/living/carbon/human/human.dm
I forgot to change the droplimb() parameters for explosions clear back here: https://github.com/ParadiseSS13/Paradise/pull/1693
This fixes that.
> Explosion Dismemberment Fix

- code/modules/mob/living/silicon/pai/pai.dm
Before this change, pAI's, once damaged, could never be fixed. This feature request adds the ability to repair their systems with nanopaste.
> Allows Repair of pAIs with Nanopaste

- code/modules/admin/secrets.dm
- code/modules/admin/topic.dm
> Admins secret menu reformat

- _maps/map_files/cyberiad/cyberiad.dmm
Changes:
1) Stray pipe in security removed.
> Stray pipe

- code/game/dna/genes/goon_disabilities.dm
I noticed my IPC dropping dead after hanging out around radioactive people. This should fix that.
> Goon "Irradiated" disability now respects NO_DNA_RAD

- code/game/mecha/equipment/tools/tools.dm
- code/modules/computer3/computers/scanconsole.dm
- code/modules/media/broadcast/transmitters/broadcast.dm
- code/modules/reagents/newchem/toxins.dm
Did a search through the codebase, thought it might be good to patch up
other things that touch the radiation variable.
> Made apply_effect used more consistently in regards to radiation

- code/modules/mob/living/simple_animal/hostile/poison_bees.dm
> fix infinite loop by nuking that entire shit loop

- code/modules/reagents/newchem/toxins.dm
> Toxin Tweak

- code/datums/datumvars.dm
- code/game/gamemodes/changeling/evolution_menu.dm
Changes:
1) Adds logging to all options in the view variables menu.
2) Fixes the changeling language not being removed when a player is de-changelinged.
> Changeling language fix, additional logging

- code/defines/procs/statistics.dm
Changes:
1) Simplifies an area check in the death logging.
> Simplify area check

- code/game/objects/items/devices/laserpointer.dm
Was originally going to also contain the kitchen spike stuff, turned out too difficult to implement.
tgstation/-tg-station#11994
~~Shamelessly stolen~~ original PR gif:
The gif sums it up pretty much, laser pointers now appear where you click.
> Pixel-coords laserpointer

- code/game/objects/structures/inflatable.dm
Changes:
1) Inflatable walls will now block atmos.
> Fix inflatable walls

- config/example/space_levels.txt
Changes:
1) Adds the space levels config file.
> Space levels config

- code/game/objects/items/weapons/flamethrower.dm
Changes:
1) Fixes https://github.com/ParadiseSS13/Paradise/issues/2214.
> Fix flamethrower logs

- code/game/machinery/cloning.dm
- code/game/machinery/computer/cloning.dm
- code/game/machinery/requests_console.dm
- code/game/mecha/equipment/tools/tools.dm
- code/game/mecha/mech_bay.dm
- code/game/objects/items/weapons/mop.dm
- code/modules/projectiles/guns/energy/temperature.dm
Fixes a few destroys that weren't returning the parent call.
Also...dat mop.
> Fixes a few Destroys

- code/game/objects/items/devices/laserpointer.dm
- code/modules/mining/equipment_locker.dm
- code/modules/mob/living/carbon/alien/alien_defenses.dm
Did a search, and found 3 of these to patch up. Perhaps there's something left, perhaps not.
> Fixed a few more reversed add_logs

- code/game/objects/structures/safe.dm
- code/stylesheet.dm
Cleans up the safe a bit
- prevents uncrackable safes
- better spans,
- prevents putting items you shouldn't into the safe.
> Safe Cleanup and Fix

- code/game/dna/dna_modifier.dm
- code/game/machinery/Sleeper.dm
- code/game/machinery/constructable_frame.dm
- code/game/machinery/cryo.dm
- code/game/machinery/iv_drip.dm
- code/modules/reagents/Chemistry-Machinery.dm
The beakers that mediborgs have should now be less prone to getting caught in certain machines, or less capable of finding their way into the hands of some unfortunate doctor. I understand that the chem dispenser already checks if the character is a robot, but hopefully this should watch for other(?) NODROP cases, now, too.
> Stickier cyborg beakers

- code/modules/admin/verbs/adminpm.dm
Changes:
1) Fixes https://github.com/ParadiseSS13/Paradise/issues/2228.
> Admin PM fix

- code/modules/admin/verbs/deadsay.dm
- code/modules/mob/living/carbon/human/emote.dm
- code/modules/mob/living/simple_animal/friendly/diona.dm
- code/modules/mob/mob_helpers.dm
Changes:
1) Fixes https://github.com/ParadiseSS13/Paradise/issues/2237.
2) Fixes https://github.com/ParadiseSS13/Paradise/issues/2239.
> Add cooldown to chirp emote, dsay fix

- code/__DEFINES/mob.dm
- code/modules/mob/living/silicon/ai/ai.dm
- code/modules/mob/living/silicon/ai/say.dm
Changes:
1) Lets AI's makes text announcements.
> Add AI text announcements

- code/modules/mob/living/silicon/ai/ai.dm
- code/modules/mob/new_player/new_player.dm
Variables added:
- $species : Species name of the individual.
- $age : Character age
- $gender : Character gender
[Common] LarkensAI states, "Say hello to Gemma Larkens, the dirty Female 21-year-old Machine Civilian"
> Add a few variables to the AI announcment message

- code/game/machinery/doors/door.dm
- code/game/objects/structures/signs.dm
> And So Dies ZAS

- code/modules/projectiles/guns/energy/hos.dm
- code/modules/projectiles/guns/energy/laser.dm
- code/modules/projectiles/guns/projectile/automatic.dm
- code/modules/projectiles/guns/projectile/launchers.dm
- code/modules/projectiles/guns/projectile/pistol.dm
- code/modules/projectiles/guns/projectile/shotgun.dm
Changes:
1) Ports over https://github.com/tgstation/-tg-station/pull/12081 by KorPhaeron.
> Guns rename, take two

- code/modules/mob/living/carbon/human/human.dm
- code/modules/reagents/reagent_containers/borghydro.dm
Changes:
1) The syndicate borg hypospray now penetrates thickness protection.
> Bypass thick protection for syndicate borg hydro

- code/game/machinery/recycler.dm
Fixes the recycler not extracting plasma from objects.
> Fixes Recycler Plasma Extraction

- code/game/dna/dna_modifier.dm
- code/game/machinery/Sleeper.dm
- code/game/machinery/biogenerator.dm
- code/game/machinery/bots/medbot.dm
- code/game/machinery/cryo.dm
- code/game/machinery/kitchen/icecream_vat.dm
- code/game/machinery/kitchen/juicer.dm
- code/game/machinery/kitchen/kitchen_machine.dm
- code/game/machinery/kitchen/smartfridge.dm
- code/modules/food/icecream_vat.dm
- code/modules/reagents/Chemistry-Machinery.dm
- code/modules/reagents/dartgun.dm
- code/modules/reagents/newchem/chem_heater.dm
- code/modules/virus2/centrifuge.dm
- code/modules/virus2/curer.dm
- code/modules/virus2/dishincubator.dm
After a search through the code, I think I've expunged every obvious way to get a borg to drop a NODROP beaker. With any luck, we shouldn't have any shifts with beakers glued to our hands anymore.
> Stickier beakers ii

- code/modules/mob/living/carbon/human/human.dm
- code/modules/mob/living/carbon/human/inventory.dm
- code/modules/mob/living/simple_animal/friendly/corgi.dm
- code/modules/mob/mob.dm
Fixes #2270, #2259 
I'm not too sure how qdel behaves with things like this. Did I do it right?
> Fixes putting NODROP items onto humans

- code/datums/uplink_item.dm
Forgot to update the telegun uplink description when it was refactored on how it worked.
> Telegun Description Fix

- code/modules/admin/create_poll.dm
Changes:
1) Some create poll fixes from /tg/.
> Create poll fixes from /tg/

- code/modules/admin/create_poll.dm
Changes:
1) Some more create poll improvements from /tg/.
> More create poll improvements

- code/modules/paperwork/pen.dm
> Sudoku via pen

- code/modules/power/apc.dm
Fixes it so that APC cell's properly GC.
There's still a reference pointing to APCs themselves somewhere---that I can't locate, but this solves a problem with them; their cells not GCing.
> APC Cell GC Fix

- code/datums/wires/radio.dm
- code/game/objects/items/devices/radio/electropack.dm
- code/game/objects/items/devices/radio/radio.dm
- code/modules/nano/interaction/default.dm
- nano/templates/radio_basic.tmpl
- nano/templates/radio_electro.tmpl
Things changed:
- All radios now use nanoUI
- Syndicate mode for any radios with syndicate access!
- Electropacks also upgraded, since they are technically radios
- Fancy as a motherfucker
Glorious screenshots:
> Upgrade radios to NanoUI

- code/game/verbs/who.dm
- code/modules/paperwork/paper.dm
Changes:
1) Fixes a space in adminwho.
2) Fixes being unable to write on paper. Fixes https://github.com/ParadiseSS13/Paradise/issues/2300.
> Fix writing on paper

- code/game/objects/items/devices/aicard.dm
- nano/templates/aicard.tmpl
Ripped from #2278 
Might not finish that for a while, it's giving me trouble and I don't have much will to work on it right now, but this is a simple little improvement that shouldn't wait.
> NanoUI Intellicards

- code/LINDA/LINDA_turf_tile.dm
- code/_onclick/hud/screen_objects.dm
- code/game/smoothwall.dm
- code/game/turfs/simulated/walls.dm
- code/game/turfs/turf.dm
- code/modules/mob/dead/observer/observer.dm
- code/modules/mob/living/silicon/ai/ai.dm
- code/modules/mob/living/silicon/ai/freelook/cameranet.dm
- code/modules/mob/living/silicon/ai/freelook/eye.dm
- code/modules/mob/living/silicon/ai/freelook/read_me.dm
- code/modules/mob/living/silicon/robot/robot.dm
- code/modules/mob/living/silicon/robot/robot_modules.dm
- code/modules/mob/mob.dm
Just more Destroy fixes
- Purges all Del()'s from the codebase minus the maploader one, Client/Del(), and Datum/Del()
- removes a duplicate argument in storage clicking
- moves some duplicate Destroy()'s into a singular Destroy()
> More Destroying Tweaks

- code/LINDA/LINDA_fire.dm
Fixes duplicate Hotspot/New()'s.
> Fixes Duplicate Hotspot New()'s

- code/game/objects/items/devices/scanners.dm
Bugfix, can be merged at any time.
> Fixes reagent scanner not showing time of death correctly

- code/game/machinery/bots/bots.dm
- code/game/machinery/bots/mulebot.dm
- code/game/machinery/computer/station_alert.dm
- code/game/mecha/mech_bay.dm
- code/game/objects/items/devices/sensor_device.dm
- code/game/objects/items/weapons/flamethrower.dm
- code/game/objects/items/weapons/grenades/smokebomb.dm
- code/game/objects/objs.dm
- code/modules/assembly/igniter.dm
- code/modules/assembly/shock_kit.dm
- code/modules/assembly/signaler.dm
- code/modules/examine/descriptions/engineering.dm
- code/modules/mob/living/simple_animal/hostile/retaliate/drone.dm
- code/modules/mob/login.dm
- code/modules/mob/mob.dm
- code/modules/power/singularity/singularity.dm
- code/modules/power/supermatter/supermatter.dm
More GC fixes
Totally not suspicious or anything. *shifty eyes*
> More Dereferencing

- code/game/machinery/poolcontroller.dm
- nano/js/nano_base_helpers.js
- nano/templates/poolcontroller.tmpl
This commit does the following:
- Adds a new helper to nanoUI JS, from rigsuits
- Improves the pool controller code
- Improves the pool controller nanoUI template
No new features have actually been added, so.
Going to conflict with #2278, of course.
edit, actually probably won't, but 2278's nanoUI won't work until this is merged
> Pool controller refactor

- code/modules/reagents/reagent_containers/food/snacks.dm
Makes monkey cubes GC and utilize spans.
> Makes Monkey Cubes GC

- code/game/dna/dna_modifier.dm
- code/game/machinery/OpTable.dm
- code/game/machinery/Sleeper.dm
- code/game/machinery/adv_med.dm
- code/game/machinery/computer/HolodeckControl.dm
- code/game/machinery/cryo.dm
- code/game/machinery/cryopod.dm
- code/game/machinery/suit_storage_unit.dm
- code/modules/admin/verbs/onlyoneteam.dm
- code/modules/mob/living/carbon/brain/brain_item.dm
- code/modules/organs/organ.dm
- code/modules/organs/organ_internal.dm
- code/modules/reagents/newchem/medicine.dm
- code/modules/reagents/oldchem/chemical_reaction/chemical_reaction_med.dm
- code/modules/reagents/oldchem/reagents/reagents_med.dm
- code/modules/surgery/organs_internal.dm
Just some fixes regarding eye blurriness and damage
- Internal Organ surgery adjusted for eyes
- Internal organ surgery on the head will now remove nearsightedness and blindness, in addition to blurriness
- Internal organ surgery on the head will now also fix/repair deafness
- Oculine has been tweaked/adjusted a bit
- 80% chance each cycle to reduce both eye AND ear damage by 1
- 50% chance of curing nearsightedness
- 30% chance of curing blindness
- 30% chance to cure deafness if ear damage is less than 25
The above two should likely fix https://github.com/ParadiseSS13/Paradise/issues/2350
- Removes Audioline
- Doubles mitocholide's effectiveness
- basically for each 2 units you consume, it'll heal 2 organ damage.
- Fixes being able to heal organs into negative damage thresholds.
- Fixes …
> Eyes Fixes and Chem Tweaks

- code/modules/recycling/disposal-construction.dm
- code/modules/recycling/disposal.dm
For whatever reason, this was broken by commit https://github.com/ParadiseSS13/Paradise/commit/f7ce7e55dfc914cedbf48a310fb2aab25c7e5d1f#diff-c113cc8b190f978c4e67605c46061b1bR738
@Markolie Am I doing something horribly wrong here, or..? I don't see any problems with this, but it twas your commit that ripped it out in the first place.
Fixes #1455
> Fix disposal pipe icon issues, unify slightly, little bit of unpathing

- code/game/objects/items/weapons/cosmetics.dm
Fixes a runtime related to lipstick application and progress bars.
> Fixes a Lipstick Runtime

- code/game/gamemodes/cult/cult_items.dm
- code/modules/clothing/clothing.dm
- code/modules/clothing/head/collectable.dm
- code/modules/clothing/head/hardhat.dm
- code/modules/clothing/head/helmet.dm
- code/modules/clothing/head/jobs.dm
- code/modules/clothing/head/misc.dm
- code/modules/clothing/head/misc_special.dm
- code/modules/clothing/suits/bio.dm
- code/modules/clothing/suits/miscellaneous.dm
- code/modules/clothing/suits/utility.dm
- code/modules/clothing/suits/wiz_robe.dm
- code/modules/mob/living/carbon/human/human_attackhand.dm
- code/modules/mob/living/carbon/human/human_defense.dm
- code/modules/mob/living/living_defense.dm
- code/modules/mob/living/silicon/silicon.dm
Just some code cleanup
- Removes the unused "loose" var from clothing
- Removes the stun_effect() proc
- Used by the old stunbeams.
> Code Cleanup

- code/ATMOSPHERICS/atmospherics.dm
Fixes up a little bit of pipes.
- Removing of meters is already handled in pipe/Destroy()
- Adds sanity of locations to mobs leaving pipes
> Pipe Fixes

- code/game/machinery/adv_med.dm
- nano/templates/adv_med.tmpl
Adds NanoUI to the bodyscanner (god help me)
Also:
- Fixes misdetecting blindness as nearsightedness; one is an sdisibilities flag, one is a disibilities flag, it was checking both as sdisiibilities
- Cleans up (some) of the code
- Mostly got rid of colon abuse and cleaned up the normal UI code
- Yes, I did have to keep the normal UI code, for printing paper
> NanoUI Bodyscanner

- code/game/vehicles/spacepods/spacepod.dm
Fixes #2412 as best as I can really.
All references _should_ behave properly, but if they don't, there is a proc now which fixes shit and debug logs it.
> Fix Spacepod bullshit.

- code/game/machinery/kitchen/monkeyrecycler.dm
Not as good as frog fractions, but it'll have to do.
This adds the other half of the fix I made a while back #2134, so that upgrading the matter bin actually increases the amount of monkey cubes made.
Also adds plurals to the text, though I played it a bit safe with the \s macro. Oh, and \<span\>s, too!
> Monkey Multiplication

- code/modules/hydroponics/seed.dm
- code/modules/telesci/bscrystal.dm
> Bluespace crystal and tomato fix

- code/controllers/configuration.dm
- code/modules/mob/login.dm
- config/example/config.txt
This is seriously fucking annoying when testing local changes. Only a config option instead of being removed completely because I don't know if anyone actually gives the slightest shit about it on the live server.
> Add config option to disable same-CID popup "YOU'LL BE BANNED STOP IT"

- code/modules/admin/admin_investigate.dm
- code/modules/power/cable.dm
Adds in investigation of cable-cutting. The logs for this were already being technically generated, but weren't able to be accessed.
Anddd because I hate you cable-cutting griefers so much, I'm adding in exact X,Y,Z location logging of said cut location with a link for admins to jump straight to that tile where you committed your shittery so they can track down where you were an ass and be able to solve the problem quicker while also banning your pathetic self in the process.
Enjoy your "tee-hee, I killed off all station power to grief them, heee!" grief-shit while it lasts, assholes.
> Wire Investigation

- code/modules/research/designs/equipment_designs.dm
> fixes 2458

- code/modules/admin/admin_verbs.dm
- code/modules/nano/modules/virus2_creator.dm
- code/modules/virus2/disease2.dm
- nano/templates/virus2_creator.tmpl
- paradise.dme
Basic Nano-module virus2 creator
Not feature complete, but good enough for basic use
Current features:
- Make and delete virus datums
- Randomized symptoms/effects on creation
- Change effects for each stage
- Change multiplier and chance for each stage
- Spread to someone random or a specific chosen person (ignores bio
protection)
> Admin Virus2 Creator

- code/game/machinery/vending.dm
Fixes the vending machine aquarium kit being the empty version.
> Fixes Acquarium Kits

- code/modules/mob/living/carbon/carbon.dm
- code/modules/mob/living/carbon/life.dm
yeah whoops
APPARENTLY BAY HAD LIVING/LIFE() AND CARBON/LIFE()
damnit bay
fixes #2525
> Fix carbon/Life()

- code/modules/food/recipes_microwave.dm
- code/modules/reagents/reagent_containers/food/snacks.dm
- Fixes the second mint recipe
- Makes it so you can make frosted donuts
- Meh, close enough to a fix.
> Recipe Fix

- code/defines/procs/hud.dm
- code/modules/mob/living/life.dm
- code/modules/mob/living/silicon/ai/life.dm
- code/modules/mob/living/silicon/pai/life.dm
- code/modules/mob/living/silicon/robot/life.dm
@Fox-McCloud 
Oh god why, AI code is the worst code.
> Fixes medhud/sechud/etc shit, ai life refactor

- code/modules/mob/living/carbon/brain/life.dm
- code/modules/mob/living/carbon/human/life.dm
- code/modules/mob/living/life.dm
- code/modules/mob/living/silicon/pai/life.dm
- code/modules/mob/mob.dm
probably does what the title states
all hail copypaste
> fix stunned shit

- code/ATMOSPHERICS/components/unary_devices/passive_vent.dm
Made passive vent equalize pressure between its `air_contents` and the turf, according to the ideal gas law.
* This is presumably what everyone naturally assumes what it's supposed to do.
* If anyone's curious, it previously acted like a volume pump with a constant volume outputting to the turf, which is silly and the opposite of "passive".
Fixes #2521
> Made passive vent equalize pressure

- code/game/machinery/wishgranter.dm
No more being both Owlman AND Griffon at the same time and removing a slot from other people to find.
> [BUGFIX] Fixes bug allowing player to multiclick WG

- code/game/gamemodes/meteor/meteor.dm
- Makes the waves actually work
- Warning about gamemode happens between 1 and 3 minutes into the round
- First wave begins at the 10 minute mark
- Waves last from 2.5 minutes to 5 minutes
- Pauses between waves last from 5 to 15 minutes
- It is up to crew to decide if/when to call the shuttle
> Fixes to Meteor Gamemode

- code/game/jobs/job/engineering.dm
> Mechanic now has access to ore reclaimer

- code/game/gamemodes/meteor/meteor.dm
- code/game/gamemodes/meteor/meteors.dm
- Scales duration of meteor showers with numbers of waves survived
- Moves away from spamming process() which was retarded
- Cuts down on screen shake by 75%
> Update to meteor gamemode

- code/game/objects/items/toys.dm
- code/game/objects/items/weapons/twohanded.dm
- code/modules/mob/living/carbon/human/human_defense.dm
I was bored, and a sudden idea popped into my mind.
"Toy chainsaws"
So I just had to.
It was mostly just a fun little thing to make and test, so I don't really care if this gets merged one way or the other.
Thanks to @Crazylemon64 for assisting me.
> Adds in toy chainsaws.

- code/modules/mob/living/simple_animal/hostile/statue.dm
Fixed using a spawn() in Life(), not ideal, but w/e
fixes #2554
> Fix statues causing mob process crashes

- code/modules/mining/equipment_locker.dm
Did that uranium arrive just now, or with the last shipment? Now you
know!
> Ore Reclaimer announcements are now timestamped

- code/game/machinery/computer/cloning.dm
- code/game/objects/items/devices/paicard.dm
- code/modules/mob/living/silicon/pai/software.dm
- nano/templates/cloning_console.tmpl
- nano/templates/cryo.tmpl
Fixes sanitize() issues with cloning computers.
Fixes #2534 
Couldn't figure out #2562, it's unrelated.
fixes minor issue with cryo
Going to have to kill @TheDZD for [this shit](https://github.com/ParadiseSS13/Paradise/commit/7d600c4379e9c6939cd0604f9082a865dfdc01e1#diff-db9fc6f8418e04882dabc18dc1ba5db3R228)
> HTML5 fixes, batch 1

- code/modules/hydroponics/seed.dm
I'm sorry, but having a single plant harvest thrown at you and you win up beocoming a slime or shadow species isn't fun, fair, or balance to fight or deal with, especially for the mass levels of produce that can be generated once the reagent is found. It's just suddenly "oh, I'm this, and there's nothing I can do about it for the rest on the round".
finally fixes https://github.com/ParadiseSS13/Paradise/issues/2439
> Seed Mutation Mutation Chems Removal

- code/ATMOSPHERICS/datum_pipeline.dm
They pipeline reconciling code for T-Valves had broken logic.
* The disconnected side was connecting to both of the other sides, bridging them all into a 3-way manifold.
* Fixes #2400
> Fixed T-Valves to work.

- code/game/objects/items/weapons/tanks/tanks.dm
- code/modules/mob/living/carbon/human/life.dm
> Rigsuit oxygen fixes.

- code/modules/examine/descriptions/atmospherics.dm
- code/modules/examine/descriptions/engineering.dm
- code/modules/examine/descriptions/mobs.dm
- code/modules/examine/descriptions/structures.dm
- code/modules/examine/descriptions/weapons.dm
Corrected some spelling errors in the examine descriptions
> Corrected some spelling errors in the examine descriptions

- code/game/objects/items/weapons/dna_injector.dm
- code/modules/mob/living/carbon/human/human_movement.dm
- Fixes green overlay not showing up
- HULK slows you down by +1
> HULK fixes and balance

- code/modules/research/designs/autolathe_designs.dm
- code/modules/research/designs/medical_designs.dm
- Removes the health analyzer from the protolathe
- Adds the health analyzer to the autolathe
- Adds the bonesetter to the autolathe
> Minor Research Tweaks

- code/game/gamemodes/meteor/meteor.dm
- code/modules/admin/verbs/randomverbs.dm
- code/modules/mob/living/carbon/human/life.dm
- code/modules/mob/living/life.dm
- code/modules/mob/living/silicon/ai/life.dm
- code/modules/mob/living/silicon/robot/life.dm
- code/modules/mob/living/silicon/robot/robot.dm
- Fixes combat borg shield overlay
- Fixes Meteor gamemode never kicking off
- Fixes Enemy Communications bugging out
- Fixes all nation HUDs including AI
- Fixes AI sec/medhuds
- Fixes a small borg runtime
> Nations 2.1.3 bugfix + other bugfixes

- code/modules/mob/living/carbon/human/life.dm
- code/modules/mob/living/life.dm
- code/modules/mob/living/silicon/robot/life.dm
- Fixes race condition with clearing image huds
> Nations 2.1.4 - final bugfix edition

- code/modules/hydroponics/grown.dm
- code/modules/hydroponics/seed.dm
- code/modules/hydroponics/spreading/spreading.dm
- code/modules/hydroponics/spreading/spreading_response.dm
HEAVILY nerfs spreading plants!
- Spread chance cut down by 66%
- In general, plants will spread slower, meaning they won't outpace a goat wielding a scythe and plant-killer grenades.
- Spread distance cut down by AT LEAST 66% (this is due to spread distance being based off spread chance)
- TRAIT_SPREAD 1 plants (glowshrooms) will spread to a maximum distance of (TRAIT_POTENCY * 0.1)
- TRAIT_SPREAD 2 plants (kudzu) will spread to a maximum distance of (TRAIT_POTENCY * 0.6) if they are vines or biomass growth_type (most common types)
- TRAIT_SPREAD 2 that have the "worms" or "mold" growth_type will spread to a maximum distance of (TRAIT_POTENCY * 0.3)
Buffs spreading plants!
- Spreading plants with thorns or stinging will now properly attempt to affect anyone who walks over them!
- Wearing …
> Weaponized Botany Changes

- code/game/dna/genes/powers.dm
Re-adds the Dwarf mutation now that overlay issues have been fixed.
Dunno if this really needs to wait 24 hours or not.
> Re-Adds Dwarf Mutation

- code/modules/admin/verbs/randomverbs.dm
> Fixes custom enemy communications

- code/game/gamemodes/nations/nations.dm
- code/game/gamemodes/nations/nationsprocs.dm
- Fixed leaders not being assigned due to runtime
- Made sure all verbs worked correctly.
> Nations 2.2.1

- code/game/machinery/cryo.dm
> NODROP beakers won't summon yog-sothoth when placed in a cryo tube now

- code/modules/mining/equipment_locker.dm
poof
You know what these things from -tg- might probably be handy
:cl:
* Ore reclaimer can now make plasglass sheets much in the same way plasteel sheets are made
/:cl:
> Lets the ore reclaimer make plasma glass from plasma and glass

- code/game/gamemodes/nations/nationsdatums.dm
- code/game/gamemodes/nations/nationsprocs.dm
- code/modules/mob/living/silicon/robot/robot.dm
- Fixes Heirs not getting a custom rank
- Fixes #2716 Borg issues
- Fixes #2726
> Nations 2.2.2

- code/modules/mob/living/carbon/brain/posibrain.dm
No more cultist ghosts yelling about deconverting when borged, among other things
Fixes #2457
> Posibrains have their mind cleared, so that no badness happens

- code/game/dna/dna_modifier.dm
Alright, you should now ACTUALLY be able to walk to easily exit a DNA machine
> Fixes the dumb I made with the DNA machine

- code/game/mecha/equipment/tools/medical_tools.dm
- code/game/objects/objs.dm
- code/game/objects/structures/crates_lockers/closets.dm
- code/game/objects/structures/crates_lockers/closets/secure/secure_closets.dm
- code/game/objects/structures/morgue.dm
- code/modules/mob/holder.dm
- code/modules/mob/living/living.dm
> Resist to escape an odysseus' sleeper

- code/game/objects/items/weapons/twohanded.dm
Fixes issues with two handed weapon sprites
#2730 
#2632
> Fixes issues with two handed weapon sprites

- code/__DEFINES/flags.dm
- code/datums/datacore.dm
- code/modules/mob/living/carbon/human/species/species.dm
- code/modules/mob/living/carbon/human/species/station.dm
- code/modules/mob/new_player/preferences_setup.dm
- code/modules/organs/blood.dm
- code/modules/reagents/Chemistry-Holder.dm
- code/modules/reagents/reagent_containers/syringes.dm
- Removes vestigial bloodflags  flag stuff
- Makes slime blood (water) part of the new system
- Makes the system generic to allow for any reagent to be used as blood
- Partial port of https://github.com/tgstation/-tg-station/pull/7611
- Technically we can make dionas bleed maple syrup now or something.
> exotic blood changes

- code/modules/mob/living/carbon/human/examine.dm
- code/modules/mob/living/carbon/human/human.dm
Bugfixes: 
- Messages written in blood should now show on examine
- Oil-covered clothing no longer shows as blood when examining a human
- Bloody/oily feet are now shown when examining while not wearing shoes
Fixes issue #1032
> Blood examine fixes

- code/__HELPERS/mobs.dm
- code/modules/client/preferences.dm
- code/modules/mob/new_player/preferences_setup.dm
- code/modules/mob/new_player/sprite_accessories.dm
Don't listen to the commit, it tells lies, mostly because the TortoiseGit UI (shoot me, I like UIs instead of remembering DOS/Git Bash commands) is obtuse. Reverting #2687 for a speedmerge + patch because it broke character setup. Fixes #2768. Fixes #2761.
> Reverts #2687

- code/game/objects/structures/flora.dm
- code/modules/awaymissions/exile.dm
- code/modules/clothing/glasses/hud.dm
- code/modules/reagents/reagent_containers/food/condiment.dm
Fixes mistakes with using /improper instead of \improper
> Fixes mistakes with using /improper instead of \improper

- code/modules/mob/new_player/preferences_setup.dm
This will probably let you have your hair in character setup again.
Haven't tested it though, no time for me to do so yet
> This might fix the character setup problem

- code/__HELPERS/mobs.dm
- code/modules/client/preferences.dm
- code/modules/mob/new_player/preferences_setup.dm
- code/modules/mob/new_player/sprite_accessories.dm
Reverts ParadiseSS13/Paradise#2771
> Revert "Reverts #2687"

- code/LINDA/LINDA_turf_tile.dm
- code/_globalvars/misc.dm
- code/controllers/Processes/air.dm
- Adds ice overlays to cold pressurized turfs
> FUN ADDITION: Helado Edition

- code/game/mecha/mech_fabricator.dm
- code/game/objects/items/stacks/stack.dm
- code/game/vehicles/spacepods/pod_fabricator.dm
- code/modules/research/rdconsole.dm
* Research machinery and the fabricators now allow you to eject a custom
amount of sheets, so you don't have to spam-click
* Research machinery and the fabricators now also count how many sheets you have 
in units of 0.1 at a time, so you have some relatable idea of how much you have besides 
some exorbitant amount
* Grabbing a single item from a stack is as before, but click again and you 
will have a prompt on how much to move over from one stack to the other.
> Improved Sheet Handling; Better Sci machine resource Formatting

- code/modules/admin/IsBanned.dm
Port of: 
- https://github.com/tgstation/-tg-station/pull/13485
- https://github.com/tgstation/-tg-station/pull/13487
Hopefully resolves the mass stickybanning problem
> Sticky Ban Fix

- code/modules/admin/IsBanned.dm
> ASS DAY ALL DAY EVERY DAY TODAY IS ASS DAY

- code/modules/arcade/arcade_base.dm
- code/modules/arcade/claw_game.dm
- code/modules/arcade/crane.html
Fixes #2795
- Game will now close if you wander away from the machine
- Cannot use the game while laying down/dead
- Game can now be closed like a normal window, and will behave properly when doing so
- Dropped prizes will actually visibly fall before the game over screen appears
- Claw game will now properly use machine processing for power and such
Also some code adjustments to help make it more organized or something.
- Seriously though, it does clean some stuff up and removes a redundant variable
> Claw Game Fixes

- code/game/machinery/vending.dm
First time i do something like this, please tell me if i've done it right, and that i didn't miss anything like adding a UI for it if it even needs one.
> Adds fire alarm electronic to engi-vend

- code/modules/arcade/claw_game.dm
People like having multiple claw games, who knew?
- Fixes the issue of claw games not closing when multiple are present
> Claw Game Fix 2

- code/game/machinery/cryopod.dm
> Cryopods now only let one in at a time

- code/game/objects/items/toys.dm
> Grammar fixes.

- code/modules/client/client procs.dm
(probably) fixes #2834 
I am 99% sure this is the reason
however I can't reliably test connection delay on a local system
sooooooooooooooooooooooo
worst that happens is that NOTHING CHANGES! whoo #tigerworstcoder2015
> Emergency patch, fixes asset_cache interfering with verbs

- code/game/mecha/equipment/weapons/weapons.dm
- code/game/objects/items/devices/camera_bug.dm
- code/game/objects/items/weapons/power_cells.dm
- code/modules/clothing/shoes/magboots.dm
- Fixes the origin tech on the mech plasma cutter
- Fixes origin tech on a few cells
- Adds in some missing origin tech on the camera bug and syndi magboots
- Reduces w_class of cells from 3 to 2
> Cell Weight Class and Tech Fixup

- code/game/dna/dna_modifier.dm
Yup
Fixes a dumb I made with my previous change, so that there's not a silly message about someone putting themself in the DNA modifier
> Spans and adds good grammar to self-scanner-inserting

- code/game/objects/items/toys.dm
- Makes it so the action figures print their message to the chat rather than just the user
- More fun/consistency with the other figures
- Changed the Laywer Action figure to the IAA action figure and changed what they say to reflect that, a bit better.
> Action Figure Tweak

- code/game/machinery/cryopod.dm
this is the most likely candidate
> (Probably) Fix "Cryo Computer can't find computer!"

- code/game/machinery/cloning.dm
- code/game/machinery/computer/cloning.dm
> Added sanity checks to cloner autoprocess, scanning, and growing

- code/game/gamemodes/objective.dm
Fixes hijack so multiple tator-tots can actually work together.
ERT exclusion actually works now.
> Fixes Hijack Objective

- code/game/turfs/space/transit.dm
Fixes z-level fuckery with jumping off of shuttles in transit. Thanks for pointing out where this was @tigercat2000. 
Fixes #2518
> Fixes Shuttle Transit Z-Levels

- code/datums/mind.dm
- code/game/gamemodes/changeling/changeling.dm
- code/game/gamemodes/traitor/traitor.dm
- code/game/gamemodes/vampire/vampire.dm
- code/modules/mob/dead/observer/observer.dm
- code/modules/mob/living/silicon/robot/login.dm
fixes https://github.com/ParadiseSS13/Paradise/issues/2899 and parts therein
Changlings dechangling on borging, they apprently were not setting thier special role properly and not triggering the bit for it, put a proc in for that plus one for vampires just in case needed in future.
Added in toggle alert for antaghud on/off
need sleep for work now.
> Hud Fixups

- code/modules/surgery/robotics.dm
I mean replacing the head should work too but alright
Does this trivialize IPC face repair ya or na
What this does:
* Advanced cyborg limb repair (welding while the cover is opened) will repair disfigurement
> Advanced structural roborepair fixes disfigured bits

- code/modules/mob/living/silicon/robot/drone/drone_items.dm
- code/modules/mob/living/silicon/robot/inventory.dm
Fixes #2368
i killed it gaiz
* No more infinite tables from a gripper
> Fixes the robogripper infinite tables bug

- code/game/turfs/simulated/floor.dm
- code/game/turfs/simulated/walls.dm
- code/game/turfs/simulated/walls_reinforced.dm
When I made #2585, I forgot that you can run bent pipes through walls too.
* Fixes #2990
> fixes drilling bent pipes into walls

- code/modules/shuttle/shuttle.dm
this probably won't cause problems
probably
> Fix nukeops pipes n' nukes disapperin

- code/game/machinery/telecomms/traffic_control.dm
This will save a lot of time for anyone trying to compile a script to all channels. Keep in mind, if you're a traitor and managed to get into the room without being detected by the AI, and robusted by security, then it doesn't matter how long it takes to compile the script. And if you're a traitor with legit access, then the AI isn't gonna check on the code that you're writing usually.
> Adds the ability to compile NTSL to all telecomms servers at the same time

- code/datums/ai_law_sets.dm
#1913 changed the drone laws, staffchat is having a fit over it, so whatever
> Restore drone law order

- code/game/machinery/computer/arcade.dm
Reduces sound range from 12 to 3.
> Fixes Battle Arcade Rupturing Eardrums

- code/game/machinery/telecomms/traffic_control.dm
This allows NTSL scripts to be MUCH longer. Now we can have even more features in our telecomms scripts! Fixes #2775
> Changed TComms Traffic Control to use POST for NTSL code

- code/__DEFINES/role_preferences.dm
Fixes not being able to toggle guardian preferences.
> Fixes Guardians not being a selectable role

- code/modules/surgery/robotics.dm
Forgot to add a case for fixing heads that lacked brute damage, but were disfigured. Enjoy!
> Can actually do robot face surgery now

- code/game/gamemodes/nations/nations.dm
- code/game/mecha/mecha.dm
- code/modules/mob/living/simple_animal/bot_swarm/swarmer.dm
- code/modules/mob/living/simple_animal/guardian/guardian.dm
Fixes https://github.com/ParadiseSS13/Paradise/issues/3069
May have missed come checks
Fixes https://github.com/ParadiseSS13/Paradise/issues/3049
GWARGGHHRRIOIGHIRG
Fixes https://github.com/ParadiseSS13/Paradise/issues/3012
this is why we can't have nice things.
Added:Names for guardians based on TG PR
Attempted:Fixing ranged guardian delay...GWRAAGGHHHHHH
> bug fixes 

- code/modules/power/apc.dm
> Removes the apc from the area's APC list when destroyed

- _maps/map_files/RandomZLevels/fileList.txt
Christmas is over, time to put away the Christmas away mission.
Santa might return next year though...
> Returns Away Missions to normal cycle

- code/__DEFINES/role_preferences.dm
Fixes https://github.com/ParadiseSS13/Paradise/issues/3077
> Fixes Lack of Revenant Preferences

- code/game/objects/items/weapons/storage/backpack.dm
Will now prompt you if you're REALLY sure if you want to singularitybomb everyone, and takes a little bit of time to complete the evil deed, as well as warning people around you.
> Nerfs the bag of holding + bag of holding effect

- code/__HELPERS/icons.dm
- code/__HELPERS/unsorted.dm
- code/controllers/Processes/air.dm
- code/game/gamemodes/blob/blob.dm
- code/game/gamemodes/game_mode.dm
- code/game/gamemodes/newobjective.dm
- code/game/gamemodes/objective.dm
- code/game/machinery/bots/floorbot.dm
- code/game/machinery/magnet.dm
- code/game/machinery/telecomms/machine_interactions.dm
- code/game/turfs/turf.dm
- code/modules/fish/fishtank.dm
- code/modules/mob/living/living.dm
- code/modules/power/singularity/emitter.dm
> January Cleaning 

- code/game/objects/items/weapons/storage/belt.dm
Fixes https://github.com/ParadiseSS13/Paradise/issues/2919
> ERT Medical Belt Fix

- code/modules/research/designs/comp_board_designs.dm
- code/modules/shieldgen/circuits_and_designs.dm
Fixes https://github.com/ParadiseSS13/Paradise/issues/2908
Ok, I have to rant about this because it's Cael code...
- The circuits were text pathed
- They needed plasma despite the imprinter not taking plasma
- THEY PRODUCED THE ACTUAL FULL MACHINE INSTEAD OF THE CIRCUITBOARD
> Fixes Shield Generator Circuits

- code/modules/client/preferences_mysql.dm
> EMERGENCY PASTE REMOVAL

- code/game/gamemodes/antag_hud.dm
Fixes https://github.com/ParadiseSS13/Paradise/issues/3099
I also keep wanting to spell cloneing as clowning
> Fixes antag huds showing after cloneing for solo antags

- code/modules/client/preferences_mysql.dm
I guess we gung-ho tore out the old roles but alright, here we are
> Removes that conversion proc we didn't actually use

- code/game/machinery/constructable_frame.dm
- code/modules/reagents/Chemistry-Machinery.dm
- code/modules/research/designs/machine_designs.dm
Ports over the constructable chemmaster from TG.
Also fixes up a number of colon usage in the file....seriously, why was it done this way?
> Constructable Chem Master

- code/modules/client/preferences.dm
- code/modules/mob/living/carbon/human/body_accessories.dm
- code/modules/mob/living/carbon/human/species/station.dm
Fixes a few in-code typo's relating to the Vulpkanin.
Only one that really impacts anything for players is the plural name for Vulps.
> Fixes a Few Vulp Typo's

- code/game/objects/items/devices/guitar.dm
- code/game/objects/items/devices/violin.dm
- code/game/objects/structures/musician.dm
- html/changelogs/Tastyfish-PR-3120.yml
- nano/assets/nanoui.css
- nano/styles/_lists.less
- nano/templates/song.tmpl
Updated the instrument (piano, guitar, violin) to use nanoui.
* Functionally less fiddly now as well. (All the buttons actually work as expected in all states or are disabled).
* A couple minor bugs were also fixed.
> Instrument UI updated to modern nanoui.

- code/game/machinery/adv_med.dm
- html/changelogs/Certhic-PR-3136.yml
- nano/templates/adv_med.tmpl
Bugfix: Bodyscanner now shows robotic and assisted parts in internal organs
> Bugfix: Bodyscanner now shows robotic parts in internal organs

- code/game/gamemodes/wizard/artefact.dm
- html/changelogs/fethas.yml
Tweaked the nya-cromantic stone..it now not only revives a person..but makes them a human female...with a schoolgirl outfit and cat ears...
Need to figure out a way to not make them bald....
> Fethas Carnival of horrors:OH GOD WHY

- code/modules/mob/living/carbon/human/life.dm
- code/modules/mob/living/carbon/life.dm
- html/changelogs/crazylemon-sleepymobs.yml
> SSD humans are now sleepier

- code/modules/reagents/newchem/medicine.dm
- html/changelogs/strange-reagent-fox-mccloud.yml
Fixes strange reagent not working on simple animals.
> Strange Reagent Fix

- code/game/machinery/Sleeper.dm
- code/game/machinery/adv_med.dm
- html/changelogs/crazylemon-rotatingsleepers.yml
> Sleepers now rotate nicely

- code/modules/mob/living/carbon/human/human.dm
- code/modules/mob/living/carbon/human/species/species.dm
- code/modules/mob/living/carbon/human/species/station.dm
- html/changelogs/crazylemon-funisdumb.yml
Fixes #2429 
This needs the "Fun Removal" tag
> Makes everything terrible

- code/game/gamemodes/wizard/raginmages.dm
- code/game/gamemodes/wizard/wizard.dm
- code/modules/mob/living/carbon/human/human.dm
- html/changelogs/crazylemon-RAGINMAGES.yml
Re-implements the Ragin' Mages gamemode. I'd like to test this, though, to make sure everything's working right.
Associated with: #3155
> Fixes RAGIN' MAGES

- paradise.dme
I decided to remove organs as they were unbalanced and mostly just full of empty processes that didn't do anything anyways.
HUE
what this actually does: removes an unused file that's empty.
> Removes Organs

- code/modules/clothing/shoes/miscellaneous.dm
- html/changelogs/CrAzYPiLoT-Footsteps.yml
Fixes half of #2786, other half has already been fixed.
> Footsteps fix

- code/modules/projectiles/guns/projectile/revolver.dm
- html/changelogs/revolver-fix-mccloud.yml
Fixes a runtime related to revolver spinning.
> Fixes Revolver Spin Runtime

- code/game/turfs/simulated/floor.dm
- html/changelogs/startup-fix-mccloud.yml
Fixes server startup time taking forever.
May also fix: https://github.com/ParadiseSS13/Paradise/issues/3218 (can't be sure)
May also fix null air on some turfs
> Fixes Server Startup Times

- code/game/gamemodes/heist/heist.dm
- code/game/gamemodes/objective.dm
because of course, they have to be shit that is annoyingly difficult to actually test
> objective fixes

- code/modules/mob/living/carbon/human/human.dm
- code/modules/mob/living/carbon/human/species/station.dm
Dramatically decreases the cost of human mob creation.
Before:
http://hastebin.com/ohagasejev.mel
After:
http://hastebin.com/awavawakov.mel
35% cheaper
Also fixes https://github.com/ParadiseSS13/Paradise/issues/2409
side note: human mob icon generation is horrifyingly expensive.
> Fixes Human Creation and Cuts its Cost

- code/modules/customitems/item_defines.dm
The nanofibre suit stops cycling through its modes once it reaches the
final mode.
Fixed.
> Fixes the nanofibre suit.

- code/game/objects/structures/inflatable.dm
- html/changelogs/Jey-altclickdeflate.yml
Alt-click on an inflated one to deflate (same as the deflate option on right click)
> alt click to deflate inflatable walls / doors.

- code/game/jobs/job/supervisor.dm
fixes/remove Blueshield job datum copy-paste.
> Fixes Blueshield Copypaste

- code/datums/uplink_item.dm
- html/changelogs/elite-hardsuit-grammar-fox-mccloud.yml
Fixes the description to be more accurate.
Fixes https://github.com/ParadiseSS13/Paradise/issues/3256
> Fixes Elite Hardsuit Description

- code/modules/admin/admin.dm
Fixes #3253 
Was broken by 
https://github.com/ParadiseSS13/Paradise/commit/529205ccb281edb2f5515dd35aaf7ed4848172a8#diff-08955c4954d03922b61a042ae2e757caL54
Not a clue why, all of these work on new_player mobtypes
@Markolie
> Fix #3253, banning in lobby

- code/game/gamemodes/traitor/traitor.dm
- code/game/machinery/kitchen/gibber.dm
- html/changelogs/tiger-IGOTAGIBBERUPMYASS.yml
Monkeys can no longer be gibbed, because the feed-in-top animation was not ever designed with them in mind. 
Buncha styling changes.
I eventually want to make more modes for the gibber, as well as a nanoUI interface, but it'll probably never happen *cry*
> Gibber stuff (and fixing a compile warning *glares at Aurora*)

- _maps/map_files/cyberiad/cyberiad.dmm
- html/changelogs/Tastyfish-PR-3279.yml
Replaces the approval stamp labelled as a QM stamp with the actual QM stamp, an approved stamp, and a denied stamp. No idea why the stamp situation was what it was.
* Fixes #2781 
* Fixes #3278
> Would the real QM stamp please stamp up?

- code/datums/mind.dm
- code/game/gamemodes/autotraitor/autotraitor.dm
- code/game/gamemodes/cult/cult.dm
- code/game/gamemodes/heist/heist.dm
- code/game/jobs/job/security.dm
- code/game/jobs/job/supervisor.dm
- code/game/machinery/adv_med.dm
- code/game/objects/items/weapons/implants/implant.dm
- code/game/objects/items/weapons/implants/implant_death_alarm.dm
- code/game/objects/items/weapons/implants/implant_traitor.dm
- code/game/response_team.dm
- code/modules/admin/verbs/one_click_antag.dm
- code/modules/admin/verbs/striketeam.dm
- code/modules/admin/verbs/vox_raiders.dm
- code/modules/mob/living/carbon/human/human.dm
- code/modules/mob/living/carbon/superheroes.dm
- code/modules/surgery/implant.dm
- html/changelogs/implant-refactor-II-fox-mccloud.yml
Technically impacts balance, thus the tag.
This is part II of the implant refactor.
This refactors implants to be based purely off of mob contents rather than implanted in specific organs. Why? To avoid a lot of problems/bugs.
Currently, implants being in organs means it's easy for them to go wrong; it's easy to keep references that are dangling on limbs that get removed and account for this all of the time--likewise, if you get rejuvinated, then the implant will end up still being in you, but not not removable or detectable. Likewise, it's pretty easy to meta if someone is a tator tot by this fact; the medical scanner says they have an unknown body and yet they have a broken bone in a different location---hmm, gee I wonder.
What this PR does, more simply, as it impacts you as a player
- …
> Implant Refactor Part II

- code/controllers/Processes/shuttles/supply.dm
* Cleaned up the if statements in the supply and ordering console from #3293 
* Also, there was a rogue `usr` in the `ui_interact` of the ordering console which caused the nano controller to crash if you walk away while ordering (how did that never get caught?)
> Optimizations for supply console/#3293

- code/game/gamemodes/cult/cult.dm
- code/game/gamemodes/nuclear/nuclear.dm
- html/changelogs/bay_shuttles_still_haunt_me.yml
> Fix #3259 in an annoying way

- code/game/machinery/adv_med.dm
- nano/templates/adv_med.tmpl
> Fixes #3303, legit implants for adv_med

- config/example/config.txt
Changes example config.txt tickrate to the one the server actually runs on.
> Update example config

- config/example/config.txt
- config/example/game_options.txt
Updates the Example config to be more accurate to the live server.
> Updates Example Config

- code/modules/mob/living/carbon/human/human.dm
- code/modules/mob/living/carbon/human/species/monkey.dm
- code/modules/mob/living/carbon/human/species/species.dm
Monkeys will now change first time. Also fixes a problem where any dna
changes in species were getting overwritten with human dna afterwards -
you can now change species dna to give abilities rather than having to
hardcode the verbs in
> Fixes issue #2690

- code/game/objects/items.dm
If you try to stab someone in the eyes that doesn't have eyes, they now take 10-14 head damage
> Fixes #3354 and goes with damage suggestion in #3367

- nano/templates/adv_med.tmpl
fixes the print icon of med scanner
> fixes print icon of med scanner

- nano/templates/cloning_console.tmpl
- nano/templates/helm.tmpl
- nano/templates/song.tmpl
@tigercat2000 missed one of the icon types when switching over to Font Awesome.
> Replaced now non-existant document icon with appropriate FA icons

- code/modules/mob/mob_grab.dm
- html/changelogs/crazylemon-mateat_tweak.yml
Eating mobs with minds will also generate attack logs
> Humans with matter eater can now grab eat

- code/__DEFINES/genetics.dm
- code/game/dna/genes/disabilities.dm
- code/game/dna/genes/goon_disabilities.dm
- code/game/dna/genes/goon_powers.dm
- code/game/dna/genes/vg_disabilities.dm
Fixes mutadone not working with some genetic mutations
Fixes #3383
@Crazylemon64 
bugfix: Fixes mutadone not working with some genetic mutations
/:cl:
> Fixes Mutadone

- code/modules/events/mass_hallucination.dm
- code/modules/events/radiation_storm.dm
- code/modules/mob/living/damage_procs.dm
Fixes https://github.com/ParadiseSS13/Paradise/issues/3396
Fixes Polonium not metabolizing+runtiming
Fixes https://github.com/ParadiseSS13/Paradise/issues/2331
Fixes Mass Hallucinations and Radiation Storms causing runtimes
bugfix: Fixes polonium not metabolizing
/:cl:
> Fixes Radiation Runtimes

- code/modules/hydroponics/seed.dm
- code/modules/hydroponics/spreading/spreading_response.dm
> Fixes plants attempting to sting ghosts

- code/game/objects/items/stacks/sheets/glass.dm
- code/game/objects/items/weapons/tools.dm
- code/modules/mob/living/simple_animal/hostile/retaliate/drone.dm
They had `plasma` origin instead of `plasmatech` origin.
Fixes #3447
> Some items had typo in their origin tech

- code/modules/mob/living/carbon/human/emote.dm
:cl:
rscadd: People with slime people limbs can now *squish
/:cl:
> People with squishy limbs can now squish

- config/example/game_options.txt
Sorry about that @Markolie; didn't realize you changed this.
Fixes the example config for AI laws to be accurate, once again.
> Fixes Game Options Config

- code/game/machinery/computer/Operating.dm
- html/changelogs/pinatacolada-pr-usefulishsurgerycomputers.yml
- nano/templates/op_computer.tmpl
Adds nanoUI to it, and makes the surgery computer announce the patient's
health and beep when it degrades past certain thresholds. Also lets you
customize those tresholds and mute them individually if you want to.
This is my first PR and I did it more so I could get familiar with byond
and git, please tell if something's wrong
> Makes the surgery computer useful

- code/game/gamemodes/miniantags/bot_swarm/swarmer.dm
Swarmers become unable to eat space pods
> Fixes #3465

- code/modules/mob/living/carbon/human/species/plasmaman.dm
- code/modules/mob/living/carbon/human/species/station.dm
I had a few more messages for #3461 from the thread, but it got merged before I could add them.
> Some more species suicide messages

- code/modules/events/event_container.dm
<a href=http://nanotrasen.se/forum/viewtopic.php?f=12&t=7002>From here.</a>
:cl:
tweak: Increases the frequency of the cortical borer event.
/:cl:
> Makes borer more likely to occur

- code/game/gamemodes/miniantags/borer/borer.dm
Fixes #3460
Blahwehbluhbluh nahwehbleh
:cl:
bugfix: A mind trapped by a cortical borer can now understand things it could understand when normally in its body.
/:cl:
> Trapped minds can now understand what the host mob can

- code/modules/mob/living/simple_animal/constructs.dm
> Removes horrible sins against nature from cult code

- code/game/gamemodes/wizard/spellbook.dm
Fixes world start runtime errors involving pre-placed spellbooks.
> Fixes Roundstart runtime with Spellbooks

- code/_onclick/observer.dm
:cl:Crazylemon
rscadd: Ghosts can now follow mecha
/:cl:
> Ghosts can follow mechs

- code/modules/mob/living/carbon/carbon.dm
Helpfull intent
aim head
click person to pat
Pat pat
:cl: PPI
rscadd: Adds head patting
/:cl:
Re-make of #3534
> Adds head patting

- interface/skin.dmf
:cl: PPI
rscadd: Adds a reconnect button to the File menu in the client.
/:cl:
> Adds reconnect button

- code/game/gamemodes/vampire/vampire.dm
- code/modules/mob/living/carbon/human/species/species.dm
Fixes Vampire thermal vision
Improved regen was working, but the message was commented out due to
spam, it now shows without spamming
> Fixes Vamp Passives (#2812)

- code/datums/supplypacks.dm
:cl: ppi
rcsadd: Adds tesla engine to supplypacks
rcsadd: Adds grounding rod to supplypacks
rcsadd: Adds tesla coil to supplypacks
/:cl:
> add tesla to supplypacks

- code/game/gamemodes/vampire/vampire.dm
Fixes my <span> cockup in #3541
> Fixes span closure in vamp regen

- code/modules/mob/living/simple_animal/friendly/butterfly.dm
- code/modules/mob/living/simple_animal/friendly/lizard.dm
Butterflies don't actually give you meat
:cl:Crazylemon
rscadd: You can now gib butterflies and lizards with a knife
/:cl:
> Lets you gib butterflies and lizards for keks

- code/game/gamemodes/cult/cult.dm
- code/game/gamemodes/game_mode.dm
- code/game/gamemodes/revolution/revolution.dm
- code/game/gamemodes/shadowling/shadowling.dm
- code/modules/admin/topic.dm
- interface/stylesheet.dm
Not much to say about this, just means that shitters who get jobbanned don't fuck over the antag that tried to convert them. Should be alright to merge once it passes 24 hours, assuming I didn't miss some sort of critical SQL change that would be needed for shadowling thrall jobbans.
Port of tgstation/-tg-station#12795
:cl:
add: Adds admin attack log to players being converted to cult.
add: Adds shadowling thrall jobbans.
add: Jobbanned players who are converted to shadowling thrall, revolutionary, or cultist will have the control of their body offered up to eligible ghosts.
/:cl:
> Jobban Tweaks

- code/modules/projectiles/guns/energy/special.dm
port of: https://github.com/tgstation/-tg-station/pull/15213
Kinetic Accelerators (and by virtue of inheritance, e-bows) automatically reload instead of having to be manually clicked and reloaded.
Tweak: Kinetic Accelerators and E-bows automatically reload
/:cl:
> Kinetic Accelerators Auto-Reload

- code/modules/admin/verbs/adminhelp.dm
- code/modules/admin/verbs/adminpm.dm
- interface/stylesheet.dm
I accidentally made mentorhelps the same color as mentor OOC, whoops. Should be a slightly less vibrant blue now.
@Fox-McCloud
> Fixes DZD Being Colorblind

- code/_onclick/observer.dm
:cl:Crazylemon
tweak: Relaxes the check on what atoms you can follow to any movable atom
/:cl:
> Lets you ghost-follow any movable atom

- code/modules/admin/verbs/adminhelp.dm
- code/modules/admin/verbs/adminpm.dm
- interface/stylesheet.dm
> Makes adminhelp colors slightly less blinding

- code/game/gamemodes/nuclear/nuclear_challenge.dm
Fixes an exploit.
bugfix: Fixes an exploit with declaring war on the station
/:cl:
> [s]Fixes Nuclear Exploit

- code/controllers/configuration.dm
- code/modules/ext_scripts/irc.dm
- config/example/config.txt
Allows for send2irc to send to multiple hosts.
> send2irc Multi-Host upgrade

- code/game/objects/items/weapons/clown_items.dm
- code/modules/mob/living/carbon/carbon.dm
Removes slipping whilst walking from banana peels and soap to give a way
out of slip lock (#3490)
> walking prevents sliplock

- code/__HELPERS/game.dm
Thanks to @MrStonedOne and @LummoxJr of course
https://github.com/tgstation/-tg-station/pull/15457
our profiling results are a bit different, but, on the whole, it's definitely cheaper:
http://www.hastebin.com/opavirifek.vhdl
> Faster get_area

- code/game/turfs/simulated.dm
fixes #3589
missed a 0 in the arguments
> Fixes walking on water

- code/game/machinery/bots/ed209bot.dm
- code/game/machinery/bots/secbot.dm
- code/game/objects/items.dm
- code/game/objects/items/weapons/melee/misc.dm
- code/game/objects/items/weapons/swords_axes_etc.dm
- code/modules/projectiles/gun.dm
- code/modules/projectiles/guns/energy/laser.dm
- code/modules/projectiles/guns/energy/special.dm
From TG.
Refactor's how weapon checks are handled; it's no longer based on a list of "acceptable" weapons on a secbot/ED209, but based on a var attached to all items.
Functionally, nothing changes; just more OOP.
> Refactors Bot Weapon Identification

- code/game/objects/items/weapons/kitchen.dm
- code/modules/mob/living/carbon/carbon.dm
- code/modules/mob/living/carbon/human/human.dm
- code/modules/reagents/oldchem/reagents/reagents_food.dm
> Stops utensils from working on mouthless humanoids.

- code/game/objects/items/stacks/rods.dm
- code/game/turfs/simulated/floor/plating.dm
- Fixes #3618 
- Makes rod->metal code not be really weird, and also work correctly in some cases.
> Fixed a couple catwalk / rod things.

- code/game/machinery/vending.dm
- code/modules/economy/utils.dm
Implementing this topic http://nanotrasen.se/forum/viewtopic.php?f=12&t=7144
:cl:
rscadd: EngiVend now has 10 camera assemblies.
tweak: Borgs can now use vending machines.
/:cl:
> EngiVend has camera assemblies & be used by borgs

- code/modules/clothing/under/accessories/accessory.dm
:cl:Crazylemon
rscadd: Attacking someone with an accessory will now let you put things on them without having to strip them.
/:cl:
> Lets you put accessories on other people by attacking them with it

- _maps/map_files/cyberiad/z2.dmm
> Gives wizard correct bedsheet

- code/game/objects/items/weapons/defib.dm
Also adds a message in case the ghost is still haunting about.
:cl:Crazylemon
tweak: The defib should be more reliable on people who have ghosted
tweak: The defib will now give a message if the ghost is still haunting about
/:cl:
> Might make the defib more reliable on players who have ghosted

- code/ATMOSPHERICS/components/unary_devices/vent_pump.dm
:cl: PPI
rscadd: Adds the ability to hide papers in vents. You can now leave a romantic love letter, exchange information in secret, or hide papers infused with the power of nar'sie from sight.
/:cl:
> You can now hide papers and cards in vents

- code/_onclick/item_attack.dm
- code/modules/mob/living/simple_animal/simple_animal.dm
Fixes #3625 
<a href=https://www.youtube.com/watch?v=ifSr0XPi8pw>Related video</a>
:cl:Crazylemon
bugfix: No more superspeed attacking simplemobs
/:cl:
> No more superspeed simple mob attacking

- code/game/objects/items.dm
- code/game/objects/items/weapons/mop.dm
- code/game/objects/items/weapons/stunbaton.dm
- code/game/objects/structures/watercloset.dm
- code/modules/reagents/reagent_containers.dm
- code/modules/reagents/reagent_containers/food/snacks.dm
fixes #3570
Could have fixed with another if statement in sink/attackby, but it was
already pretty snowflakey, and had the potential to get worse
Items now have a wash proc that the sink calls, that can be overridden
when needed
> refactors washing items

- code/game/objects/items/weapons/cigs.dm
:cl:Crazylemon
tweak: You can now light cigarettes off of burning mobs.
/:cl:
> You can now light cigarettes off of burning mobs

- code/game/dna/dna_modifier.dm
- code/game/machinery/computer/cloning.dm
Applies the same fix as #3665 for loading from a disk and creating an
injector
Thanks @Crazylemon64
> Genetics disk fix pt 2

- code/game/dna/dna2_domutcheck.dm
- code/game/dna/genes/goon_disabilities.dm
- code/modules/mob/living/carbon/alien/humanoid/humanoid.dm
- code/modules/mob/living/carbon/slime/slime.dm
- code/modules/mob/mob_defines.dm
- code/modules/projectiles/projectile/special.dm
> Completely tears out all uses of the 'update_icon' var in mobs

- code/game/objects/items/weapons/storage/lockbox.dm
- code/game/objects/items/weapons/storage/secure.dm
> prevents autoequip to locked lockboxes

- code/modules/mining/mine_turfs.dm
- code/modules/mining/ore.dm
Should I make the human version of this effect require a bluespace satchel?
:cl:Crazylemon
tweak: Miners can now collect ore by walking over it with an ore satchel on.
/:cl:
> Miners can now collect ore by walking on it while having an ore satchel on

- code/game/machinery/computer/message.dm
- code/modules/pda/messenger.dm
> Fixed in-chat pda message reply link

- code/game/machinery/kitchen/icecream_vat.dm
- code/modules/food/recipes_candy.dm
- code/modules/hydroponics/grown.dm
- code/modules/hydroponics/seed_datums.dm
- code/modules/reagents/newchem/food.dm
- code/modules/reagents/oldchem/chemical_reaction/chemical_reaction_drink.dm
- code/modules/reagents/oldchem/chemical_reaction/chemical_reaction_food.dm
- code/modules/reagents/oldchem/reagents/reagents_food.dm
- code/modules/reagents/reagent_containers/food/snacks.dm
- code/modules/reagents/reagent_containers/food/snacks/candy.dm
Standardized the spelling of "Cocoa", as this was inconsistent
- One spot refers to it as cacao still, but that is because it is in the
actual Latin scientific name. Everything else is now cocoa (not coco).
Chocolate now will provide some nutrition (and make you fat if you eat a
lot)
- Cocoa Powder (the arguably main component of chocolate) provided
nutrition, but that nutrition mysteriously vanished when you combine it
with milk and sugar. Now chocolate provides the same nutrition as the
cocoa powder in it
Merged a number of cases where foods had both chocolate and cocoa to now
have just chocolate
- In the case where both were present, the volumes were combined to
maintain food sizes
Renamed cocoa pile to Pile of Chocolate, as this was wrong
- The cocoa pile claimed to be a pure cocoa …
> Cocoa Spelling and Relative Pathing Cleanup

- code/modules/pda/pdas.dm
> Fixes some of the pda's not initializing, oops

- code/modules/mob/living/carbon/life.dm
- code/modules/reagents/newchem/toxins.dm
Fixes Capulettium Plus not silencing
Also fixes stuttering, slurring, druggy, and silence ticking down at twice the normal rate
bugfix: Fixes Capulettium Plus not silencing
bugfix: Fixes slurring, stuttering, drugginess, and silences last half of what they should
/:cl:
> Fixes Capulettium Plus

- .travis.yml
- _maps/test_away_missions.dm
- Makes Travis test the away missions as well, in case a refactor changed a path and forgot about the other maps.
> Adds testing of away missions to Travis.

- _maps/map_files/RandomZLevels/beach.dmm
- code/controllers/Processes/timer.dm
- code/game/turfs/unsimulated/floor.dm
- code/modules/awaymissions/mission_code/beach.dm
- paradise.dme
- I mapped out a 7 tile buffer around the edge so that you can't see the edge of the world, and bushes to visually stop you.
- I also renamed `PStimer` to `timer_master`, by @tigercat2000's request.
- Adds soda dispenser to beach bar.
- Splashes
:cl:
rscadd: The beach now has a border and is splashier.
/:cl:
> Gives the beach an edge instead of endless blackness.

- code/__HELPERS/text.dm
- code/defines/procs/announce.dm
> Allows admin communications announcements to have newlines

- code/modules/mob/mob.dm
#3743 was merged 2 fast 4 me.
- Fixes writing multi-line IC notes, as @Fox-McCloud pointed out.
> Newlines 2 - IC Notes Boogaloo

- code/modules/hydroponics/grown_predefined.dm
- code/modules/reagents/reagent_containers/food/snacks.dm
- Fixes there not being a pre-defined potato grown
- Fixes there being an attackby for potatoes that's handled elsewhere...properly 
Fixes https://github.com/ParadiseSS13/Paradise/issues/3737
> Ensures there are Potatoes

- code/game/machinery/vending.dm
- The main issue was that `RefreshParts()` added the starting inventory on top of the existing inventory every time it ran...which is bad.
- `user` was also mishandled in `refill_inventory()`.
> Fixes vending machines borking their inventory

- code/game/machinery/cloning.dm
- code/game/machinery/cryo.dm
:cl:Crazylemon
bugfix: Putting people in an active cryotube now produces the message on insertion, rather than release.
bugfix: An EMP'd cloning pod will now display its sprites correctly.
/:cl:
> Improves behavior of Cryo tubes and Cloning pods

- code/modules/mob/living/carbon/human/emote.dm
- html/changelogs/VampyrBytes-pr-3748.yml
fixes #3727
Removes part of code that removed last character if it was an s
Hardcodes grammatical options for emotes into switch
Updated help emote with missing emotes
> fixes emotess

- code/modules/pda/cart_apps.dm
- Hopefully
- fixes #3773 
- It turns out the data core just randomly leaves dangling null records after heavy use.
> Fixes PDA records apps when records deleted

- code/datums/spells/lichdom.dm
> Fixes lich spell preventing round end when viewed in the spellbook

- code/modules/mining/mine_items.dm
Givers miners an extra edge on things
That is to say, their drills now have an edge.
tweak: Mining drills now have an edge
/:cl:
> Gives Mining Drills an Edge

- code/modules/mining/equipment_locker.dm
:cl:
rscadd: Lazarus Injector's can now be emagged to activate their special features, alongside using EMPs on them.
/:cl:
> Adds Lazarus Injector emag_act()

- code/game/machinery/recharger.dm
- code/game/objects/structures/stool_bed_chair_nest/alien_nests.dm
- code/modules/surgery/organs/subtypes/xenos.dm
:cl: Fethas
bugfix: the nest buckle now looks for the right organ path
bugfix: Fixed some sprites.
bugfix: No more putting no drops in rechargers,
/:cl:
> Organ fixes

- code/game/machinery/recharger.dm
> Refactors NODROP Check in Rechargers

- code/modules/mob/living/carbon/alien/life.dm
- code/modules/reagents/oldchem/reagents/reagents_flammable.dm
- code/modules/research/designs/medical_designs.dm
- Fixes augments not showing up in R&D unless searched for
- Fixes some augments being missing from mech fabs
- Fixes augments having no construction time
- Fixes Xenos breathing in plasma not increasing their plasma
- Fixes plasma reagent not increasing plasma every cycle
bugfix: Fixes augments not showing up in R&D unless specifically searched for
bugfix: Fixes some augments being unavailable in mech fabs
bugfix: Fixes augments having no construction time
bugfix: Fixes xenos not gaining plasma when breathing in plasma
bugfix: Fixes plasma reagent not generating plasma for a person
/:cl:
> Organ Related Fixes

- code/modules/surgery/organs/organ_internal.dm
:cl: Fethas
bugfix: Though shalt not eat robotic organs..including cybernetic implants..
/:cl:
> For the head not the food

- code/controllers/Processes/shuttles/supply.dm
- code/game/gamemodes/game_mode.dm
- code/game/jobs/job/science.dm
- code/game/jobs/job_objectives/science.dm
- code/game/mecha/mecha_construction_paths.dm
:cl:Crazylemon
rscadd: Science members now get compensated when they ship tech disks to centcomm.
rscdel: Science crew are no longer paid when they "max" research.
bugfix: Roboticists now get credit for making RIPLEYs and Firefighters
/:cl:
> Modifies science and robotics objectives

- code/modules/surgery/organs/subtypes/xenos.dm
- code/modules/surgery/other.dm
:cl: Fethas
bugfix: ITS SURGERY_STEP/DETHRALL NOT SURGERY_STEP/INTERNAL/DETHRALL
/:cl:
> EMERGENCY FIX:SHADOWLING DEHTRALLING

- code/game/objects/items/weapons/tanks/watertank.dm
- Allows water tank back item's nozzle to be removed while driving around janicart.
> Allows tank nozzle to be pulled out while on janicart

- code/game/objects/items/stacks/sheets/sheet_types.dm
- code/modules/research/designs/autolathe_designs.dm
Shitty Byond crashes for no apparent reason because of them so oh well :cry:
> Removes the ability to build picture frames

- code/game/machinery/deployable.dm
- code/game/mecha/equipment/tools/tools.dm
Thanks to @Fox-McCloud for pointing out this issue.
> Tweaks Recitence RCD

- code/game/gamemodes/nations/nations.dm
- code/game/machinery/doors/brigdoors.dm
- code/modules/shuttle/shuttle.dm
Fix for #3842 for shuttle docks.
> Derped and forgot to update shuttle dock doors

- code/game/machinery/doors/brigdoors.dm
Fixes #3888 
Amazingly, this _wasn't_ my fault and was always handled wrong, apparently.
> Fixes brig doors going insane at real world midnight

- code/game/objects/items/weapons/weaponry.dm
- code/modules/customitems/item_defines.dm
> fluff tweaks

- code/game/objects/items/devices/megaphone.dm
- Fixes #3879 
- Was an uncaught typo in #3736
> Fixes megaphone

- code/modules/admin/admin_verbs.dm
> Makes toggling debug logs actually save

- code/game/machinery/autolathe.dm
- code/modules/power/cable.dm
- code/modules/research/designs.dm
- code/modules/research/designs/autolathe_designs.dm
port of: https://github.com/tgstation/-tg-station/pull/15146
Can now make cable coils in autolathes. About damn time.
rscadd: Can now make cable coils in autolathes
/:cl:
> Can Make Cable Coils in Autolathes

- code/game/gamemodes/vampire/vampire.dm
- code/game/gamemodes/vampire/vampire_powers.dm
> Fixes vamp antag hud not showing on round start

- code/__HELPERS/text.dm
- code/modules/mob/living/carbon/human/emote.dm
- code/modules/mob/mob.dm
:cl:
fix: Fixes an instance of old code being so incredibly, unbelievably, makes-me-want-to-stab-myself-in-the-eye-edly idiotic.
/:cl:
Didn't touch the SQL that gets put into the DB tables because I'd rather not have somebody dropping tables because something fucked up, would rather @ZomgPonies take a look at what @tigercat2000 had in mind for that first.
@Fox-McCloud Merge ASAP.
> Fixes Some HTML Chucklefuckery

- code/modules/research/designs/autolathe_designs.dm
:cl:
rscadd: You can now make video cameras at the autolathe.
/:cl:
> Adds video cameras to autolathe

- code/modules/clothing/clothing.dm
:cl:
fix: Adjusted masks no longer block CPR (including bandanas).
fix: You can no longer run internals from adjusted breath masks (or airtight adjustable masks in general).
/:cl:
Fixes #3948
> Fixes #3948, Adjusted bandanas no longer block CPR + No more internals from adjusted breathmasks

- code/game/gamemodes/shadowling/shadowling.dm
> fix #3955 spacing

- code/modules/clothing/under/accessories/accessory.dm
- code/modules/mob/living/simple_animal/simple_animal.dm
> Fixes simple animal Destroy() & death alarm text

- code/modules/admin/topic.dm
> Adds notification to admin ghost incarnation

- code/datums/martial.dm
Fixes sleeping carp combo's not having an attack animation
fix: Fixes Sleeping Carp combos not having an attack animation
/:cl:
> Fixes Sleeping Carp Combos Attack Animations

- code/modules/pda/PDA.dm
- code/modules/pda/chatroom.dm
- code/modules/pda/messenger.dm
> Fixes doing the pda chat link things while sleepy/dead

- code/modules/mob/living/carbon/human/species/station.dm
:cl:
rscadd: Slime People can now wear underwear.
rscadd: Slime People can now wear undershirts.
/:cl:
Resolves #3966
> Slime People can now use Underwear and Undershirts, Fixes #3966

- code/modules/mob/living/simple_animal/parrot.dm
My only purpose in life is to add new and improve existing ways to spam players.
> Makes Poly use the say/radio prefix system correctly

- code/datums/martial.dm
Fixes [#3895](https://github.com/ParadiseSS13/Paradise/issues/3895)
*tell me this works please*
> Fixes martial arts going away after boxing and booze

- code/modules/client/preferences.dm
Refer to title.
@Necaladun
:cl:
rscadd: You can now have up to 20 characters.
/:cl:
> Change max character slots to 20

- code/datums/spells/bloodcrawl.dm
- code/game/gamemodes/miniantags/slaughter/bloodcrawl.dm
- code/game/gamemodes/miniantags/slaughter/slaughter.dm
fixes https://github.com/ParadiseSS13/Paradise/issues/4027
:cl: Fethas
bugfix: Hell has recently remapped its blood transit system and you can now once again crawl through blood. We are sorry for the-GIVE US YOUR SOUL!
/:cl:
> fixes demons

- code/modules/reagents/newchem/drinks.dm
- code/modules/reagents/oldchem/reagents/drink/reagents_alcohol.dm
Okay, so I might have totally botched this, please don't shout.
This changes the alcohol system a bit and makes booze have defined levels of ethanol. 
As it stands all the `***_start` values are roughly twice the number of units of whiskey you'd need to reach that level of intoxication, whiskey being a 40% beverage.
Generally all the exotic drinks using plasma and other weird ingredients have more ethanol than they technically should have.
tweak: Alcoholic beverages now have proper levels of ethanol in them. Good luck passing out after a beer.
/:cl:
> Alcohol percentages!

- code/game/machinery/PDApainter.dm
- code/modules/mob/living/silicon/pai/pai.dm
- code/modules/mob/living/silicon/pai/software_modules.dm
- code/modules/pda/ai.dm
- nano/templates/pai_chatroom.tmpl
Fairly self-explanatory. Gives pAI's a software module which allows them to use chatrooms.
:cl:
rscadd: pAI's can now use the PDA chatrooms.
/:cl:
> Adds chatroom to PAIs

- code/game/gamemodes/shadowling/shadowling.dm
Let'sssss not start shadowling rounds with 5 people on board, k?
> Shadowling Fix

- code/_compile_options.dm
- code/modules/paperwork/paper.dm
> [s]Fixes paper limit exploit

- code/modules/clothing/head/misc.dm
- code/modules/clothing/suits/miscellaneous.dm
:cl: Fethas
bugfix:moves the bloated human head to the right file and maybe fixes a icon issue for the inventory slot.
/:cl:
> Fixes bloated human head

- code/modules/mob/living/simple_animal/hostile/headcrab.dm
fixes: https://github.com/ParadiseSS13/Paradise/issues/3999
Apparently it is, in fact, possible.
fix: fixes spawned changeling headcrab behavior
/:cl:
> Headcrab Fix

- code/modules/reagents/reagent_containers/food/snacks.dm
Fixes #4059
Forks now don't produce trash when eaten off
Forks now do leave trash when taking the last bit of food from the
original item
> Fixes forks producing trash/not leaving trash

- code/__DEFINES/hud.dm
- code/datums/hud.dm
- code/game/gamemodes/antag_hud.dm
- code/game/gamemodes/autotraitor/autotraitor.dm
- code/game/gamemodes/changeling/changeling.dm
- code/game/gamemodes/traitor/traitor.dm
- code/game/gamemodes/vampire/vampire.dm
- code/modules/mob/dead/observer/observer.dm
Based on TG updates, makes my solo antag hud stuff neater (Again from TG)
Still some bugs with nations hud i know.
If anyone spots anything i can fix just slap me with some eyeballs..
:cl: Fethas
rscadd:Antaghud Updates
/:cl:
> Antag Hud updates

- code/modules/reagents/reagent_containers/syringes.dm
:cl:Crazylemon
bugfix: Syringes will now draw water from slime people.
/:cl:
> Using a syringe on slime people will now get water out of them

- code/modules/mob/mob.dm
i swear dm.exe didn't warn about anything :8ball:
> Fixes a compile warning

- code/modules/surgery/implant.dm
:cl: Fethas
rscadd:You can now remove loose bits of metal and bannas lodged into ipcs.
/:cl:
> Fixes IPC Embbedded object surgery

- code/game/gamemodes/meteor/meteors.dm
- code/modules/events/meaty_ops.dm
:cl: Fethas
tweak: maybe makes them last longer...maybe..and fixes the event end message
/:cl:
> MeteorOps Tweaks

- code/game/machinery/flasher.dm
- code/game/objects/items/devices/flash.dm
- code/game/objects/items/weapons/grenades/flashbang.dm
- code/modules/mob/living/carbon/carbon.dm
- code/modules/mob/mob_defines.dm
Fixes most of weak eyes not really having much of an impact....now it will
Fixes https://github.com/ParadiseSS13/Paradise/issues/4080
fix: Fixes weakeyes having a negligible impact
/:cl:
> Fixes Weakeyes

- code/game/machinery/vending.dm
Adds tape to the ArtVend
Because why the heck not.
add: Adds tape to the ArtVend
/:cl:
> Adds Tape to ArtVend

- code/game/objects/effects/decals/Cleanable/tracks.dm
> Fixes to_chat script messing up one line

- code/modules/clothing/gloves/miscellaneous.dm
> Makes fingerless gloves functionally clipped

- code/modules/mob/living/carbon/human/species/monkey.dm
- code/modules/mob/living/carbon/human/species/species.dm
:cl: Fethas
tweak:Adjusts the code for monkey butcher results
/:cl:
> Playing with Monkey Meat

- code/game/machinery/PDApainter.dm
- code/modules/mob/living/silicon/ai/ai.dm
- code/modules/mob/living/silicon/pai/pai.dm
- code/modules/mob/living/silicon/robot/robot.dm
- code/modules/pda/ai.dm
- Fixes #4135 
- But only when they have charge. :wink:
> Fixes cyborg pda messenger

- code/modules/mob/living/simple_animal/friendly/cat.dm
- code/modules/mob/living/simple_animal/friendly/corgi.dm
- code/modules/mob/living/simple_animal/friendly/fox.dm
- Resolves #4133 
- All cats now chase mice, not sure why the code was specific to Runtime before.
:cl:
tweak: All cats can kill mice now.
tweak: E-N can't suffocate.
/:cl:
> Makes synipets and borgi not need to breathe air

- code/game/machinery/kitchen/monkeyrecycler.dm
Fixes a runtime with monkey recyclers
I swear I committed this, because I did run across this in testing, but apparently...I did not.
> Fixes Monkey Recycler Runtime

- code/game/objects/structures/girders.dm
> Fixes girder animal smash messages

- code/modules/reagents/reagent_containers/food/cans.dm
Oddly, we already had the crush can item and its sprites.
- Humans can now crush cans by attacking themselves in the **head** with the can in **harm** intent.
- Janiborgs can now crush cans when they pick them up with their trashbag.
:cl:
rscadd:Humans can now crush cans by attacking themselves in the head with the can in harm intent.
rscadd:Janiborgs can now crush cans when they pick them up with their trashbag.
/:cl:
> Makes cans crushable by humans and janiborgs

- code/game/machinery/supply_display.dm
- code/game/objects/structures/crates_lockers/largecrate.dm
- Fixes MULEcrates eating the MULE when opened.
- Fixes the supply display not showing the cargo shuttle time.
> Fixes MULEs not coming out of their shell.

- code/modules/admin/verbs/SDQL2/SDQL_2.dm
- code/modules/admin/verbs/SDQL2/SDQL_2_parser.dm
Port of https://github.com/d3athrow/vgstation13/pull/9338 :heart: @PJB3005
- Allows proc calls of vars and in any expression.
```sql
CALL say(species.makeName(gender)) ON /mob/living/carbon/human WHERE !stat
UPDATE /mob/living/carbon/human SET real_name = species.makeName(gender), name = real_name
```
- Allows array indexing
```sql
CALL say(species.suicide_messages[2]) ON /mob/living/carbon/human WHERE !stat
```
- (Port of older vg addition) Allows UPDATE to set to vars of vars
- `/datum/admin` ie `holder` is blocked from being usable with this. :wink:
```sql
UPDATE /mob/living/carbon/human SET client.dir = 4
```
> More SDQL Insanity

- code/modules/surgery/organs_internal.dm
- code/modules/surgery/robotics.dm
:cl: Fethas
bugfix: You should now be able to operate on IPC eyes, SHOULD
bugfix:hopefully surgery on diona works right
/:cl:
> I HATE EYEBALLS

- code/modules/client/preferences.dm
Fixes the blind player disability preference not doing anything
fix: Fixes the blind player preference not doing anything
/:cl:
> Fixes Blind Player Preference Doing Nothing

- code/modules/library/lib_machines.dm
Fixes #4222 
<sub><sup>derp</sup></sub>
> Fixes books being blank

- code/controllers/Processes/npcai.dm
> Minor fix to npc controller

- code/modules/mob/living/say.dm
- code/modules/mob/living/silicon/pai/say.dm
- code/modules/mob/living/silicon/say.dm
Fixes #4170 
Technically a feature addition since pAI's could never whisper at all, but it's reasonable for pAI's to be able to whisper to their owner.
> Lets pAI's whisper consistently

- code/modules/pda/radio.dm
> Fixes pda signaller radio

- code/game/gamemodes/miniantags/abduction/abduction_gear.dm
Ensures abductor handcuffing calls the proper proc.
> Abductor Handcuff Fix

- code/modules/clothing/spacesuits/rig/rig.dm
- code/modules/clothing/spacesuits/rig/rig_verbs.dm
- Replaced /proc/toggle_seals with /proc/unseal and /proc/seal
- You can no longer retract anything but the helmet after you seal the
suit (what the fuck was the point of having the seal if it does nothing
but make it latch onto your back)
- Clicking on parts and popping them off shouldn't be a thing anymore
(hopefully)
- Rewrote some of the nasty toggle_piece code.
Fixes #2545
- Toggle Hardsuit now seals the suit properly
- It will no longer delete your items if it can't deploy (wtf)
- Rigsuit boots are still borked but they have their own issue report
> RIGsuit fixes

- code/datums/mind.dm
- code/game/gamemodes/vampire/hud.dm
- code/game/gamemodes/vampire/vampire.dm
Make the de-vampire option remove the abilities & the HUD, immediately.
> Fixes devamping via the traitor panel

- code/game/objects/structures/fullwindow.dm
- code/game/shuttle_engines.dm
- code/game/turfs/simulated/shuttle.dm
- code/modules/shuttle/shuttle.dm
- Fixes #4242 
- Also fixes windows, engines, etc becoming messed up if the shuttle is rotated a differently angled dock.
> Fixes shuttle smoothing

- code/modules/mob/living/simple_animal/hostile/hostile.dm
> Fixes reloading gun for player-controlled hostiles

- code/_onclick/hud/alert.dm
- code/game/objects/items/weapons/dna_injector.dm
- code/modules/admin/verbs/map_template_loadverb.dm
- code/modules/hydroponics/grown.dm
- code/modules/mob/living/carbon/carbon.dm
- code/modules/pda/ai.dm
gragle gragle :angry: @Fox-McCloud @Tigercat2000 :eyes:
> Fix multiple instances of to_chat not being used

- code/game/mecha/equipment/tools/medical_tools.dm
- code/modules/mob/living/simple_animal/hostile/bees.dm
- code/modules/projectiles/projectile/bullets.dm
Fixes several injections not properly procing INGEST when they occur.
Things impacted:
- Bees
- Mech Syringes
- Darts
fix: Fixes bees, mech syringes, and darts not properly calling INGEST for a reagent
/:cl:
> Fixes Several Injections

- SQL/paradise_schema.sql
- SQL/paradise_schema_prefixed.sql
- code/modules/client/preferences.dm
- code/modules/client/preferences_mysql.dm
- code/modules/mob/living/living.dm
SQL changes
```
ALTER TABLE `player`
ADD `show_ghostitem_attack` smallint(4) DEFAULT '1'
```
You can either merge #4243 first, then this, or merge just this, either works.
> #4243 preference option

- code/modules/research/designs/machine_designs.dm
> Makes gameboard circuits printable

- code/game/gamemodes/mutiny/mutiny_admin.dm
- code/modules/admin/player_panel.dm
Fixes #4279 
Makes it more OOPy too
> Fixes Check Antagonists Panel

- code/game/objects/items/weapons/lighters.dm
- code/modules/power/lighting.dm
tweak: cheap lighters only damage your hand if you fail to properly use such a complicated contraption, not the whole body
/:cl:
~~Yah. Pretty much everyone said it's either redundant or only there for laughing at clueless newbs.~~
~~Let us be once again at peace with our inner selves, knowing that lightulbs are back to being harmless and this is a conversation we won't have to return to ever again.~~
I tagged the lighter code onto it, might as well.
Apparently some people do have the need to commit suicide through the excessive use of lumens.
> Lightbulbs no longer burn you, lighters do a bit less.

- code/game/objects/items/weapons/cigs.dm
- code/game/objects/items/weapons/lighters.dm
Fixes cigarette and in-hand sprites for what you light cigs with not updating in some circumstances
fix: Fixes cig icons not updating under some circumstances
/:cl:
> Cig Icon FIx

- code/datums/mind.dm
> Traitor panel now properly removes special role from deculted cultists

- nano/templates/slotmachine.tmpl
Fixes the slot machine UI saying it costs 5 credits when it's 10.
fix: Fixes UI On slot machine saying it costs 5 credits when it's 10
/:cl:
> Fixes Slot Machine UI Displayed Cost

- code/game/gamemodes/miniantags/abduction/abduction.dm
Fixes abductors having tails.
Fixes https://github.com/ParadiseSS13/Paradise/issues/4350
fix: Fixes abductors having tails
/:cl:
> Fixes Abductors Having Tails

- code/game/objects/items/weapons/scissors.dm
Fixes being able to meta the traitor scissors based upon them making a different cutting sound when you start cutting someone's hair.
fix: Fixes traitor scissors having a different hair-cutting sound
/:cl:
> Fixes Safety Scissors Meta

- code/game/objects/effects/datacore-effect.dm
- code/modules/mob/living/silicon/pai/software_modules.dm
- code/modules/pda/core_apps.dm
Fixes #4359 
Forgot to strip the last of the weird old cache hack stuff from the json code, whoops :cry:
> Unbreaks the pda manifest

- code/game/machinery/vending.dm
- code/modules/hydroponics/seed_datums.dm
- code/modules/reagents/reagent_containers/food/snacks.dm
Mushrooms no longer have "fungus" reagent in them; this should make mushroom pizzas, soups, dishes, and custards not give the "YUCK!" message when you eat it.
Moves the fungus reagent to the mold plant and puts 2 of these packets in the seed vendor as contraband.
bumps up the ???? reagent from 1 to 5 for bad recipes.
tweak: removes fungus from mushrooms
tweak: adds fungus to "mold" plant
tweak: adds mold seeds to hydro vendor
tweak: bumps up ???? reagent from 1 to 5 on bad recipes
/:cl:
> Mushrooms No Longer Taste Nasty

- code/modules/surgery/implant.dm
> prevents implanting fukken disks in boxes inside of people

- code/modules/mob/living/say.dm
- code/modules/mob/mob_helpers.dm
tweak: Robots now slur and stutter robotically
/:cl:
I'm not 100% sure if people want this to happen or not, so feel free to discuss.
Stammering IPC
Slurring IPC
> Robutts slur and stammer robotically

- code/modules/power/lighting.dm
you can now remove lightbulbs regardless of intent if you are able to
remove them, if you're on disarm or grab you'll burn yourself if you
aren't able to, if you're on help or harm you'll get a message of "too hot
to touch!"
> Makes the "lightbulbs don't burn you" thing less awful

- code/modules/admin/verbs/one_click_antag.dm
> Fixes Create Antagonist panel's vampire thing

- code/modules/client/preferences.dm
Reorganized the character preference screen.
> Preference Screen Overhaul

- code/game/objects/items/weapons/RCD.dm
rscadd: Windows can now be constructed and deconstructed using RCD's.
/:cl:
> Gives the RCD the ability to construct and deconstruct windows.

- code/game/machinery/telecomms/broadcaster.dm
- code/game/objects/items/devices/radio/radio.dm
- code/modules/scripting/Implementations/Telecomms.dm
- code/modules/scripting/Implementations/_Logic.dm
This fixes the weird quirks you get when you try to use `sleep()` in telecomms.
bugfix: Fixes sleep() in telecomms
/:cl:
> Telecomms concurrency fix

- code/modules/mob/living/simple_animal/simple_animal.dm
> Makes the galaxy not be on Orion's belt

- code/modules/mob/living/silicon/pai/death.dm
- code/modules/mob/living/silicon/pai/pai.dm
> Makes pAI's die in a consistent way

- code/game/objects/items/weapons/table_rack_parts.dm
- Fixes #4442 
- Refactors table parts to not just repeat the same code 4 times.
> Fixes table stacking, refactors table parts

- code/game/gamemodes/vampire/traitor_vamp.dm
Fixes Chaplains being able to be vampires during traitor-vamp
fix: Fixes Chaplains being able to be vampires
/:cl:
> Fixes TraitorVamp Chaplains

- code/world.dm
> Recommended version update

- code/game/objects/structures/crates_lockers/closets/secure/secure_closets.dm
I was so, so bored.
Just adds a 'click' sound when you lock any lockable locker. Lock.
Signed-off-by: Razek <megamattman2234@hotmail.co.uk>
> Adds a click sound when you lock a locker

- code/ATMOSPHERICS/components/binary_devices/circulator.dm
- code/modules/power/generator.dm
:cl:Crazylemon
rscadd: You can now fasten the circulators in the TEG kit with a wrench - no adminbus needed to set it up, now
/:cl:
> You can now fasten the TEG circulators

- code/game/objects/items/weapons/legcuffs.dm
How many times has a space bear named Boris seen you, while you were trying to catch it? Well, this product fixes that problem! Adds the ability to attach signalers to bear traps to make them notify you when they catch something while you are hiding in your office. Happy hunting!
:cl: CrAzYPiLoT
rscadd: Adds the ability to attach signalers to bear traps. Stealthy hunting!
/:cl:
> Pilot's Useless Fiesta; Part 1: The hunting trip

- code/modules/vehicle/ambulance.dm
> Fixed ambulance move runtime

- code/game/machinery/rechargestation.dm
- code/game/turfs/simulated/walls.dm
- code/game/verbs/suicide.dm
- code/modules/assembly/timer.dm
- code/modules/mob/living/silicon/pai/death.dm
- code/modules/mob/living/simple_animal/hostile/bees.dm
- code/modules/mob/say.dm
- code/modules/surgery/organs_internal.dm
- interface/interface.dm
- Fixes #4492 
- Also a bunch of runtimes.
> Fixes a few runtimes & pAI suicide

- code/game/machinery/computer/robot.dm
- code/game/machinery/gameboard.dm
- code/game/machinery/guestpass.dm
No salt please
- Adds a 1 minute cooldown to the chessboard. Attempting to win within that cooldown causes the admins to get a message
- Fixes use of spaces in chessboard.
- Fixes a somewhat serious exploit with the guest pass computer that lets you give yourself any access.
- Fixes an exploit with the robotics console that lets anyone blow a borg.
> Fix some href exploits

- code/__DEFINES/misc.dm
- code/__HELPERS/AnimationLibrary.dm
- code/modules/admin/admin.dm
- code/modules/clothing/glasses/glasses.dm
- code/modules/mob/living/simple_animal/posessed_object.dm
> Clean up the horrific mess of 6bae633 through 468944f

- code/modules/power/lighting.dm
:bulb: 
:cl:
rscadd: Adds a suicide for light tubes.
/:cl:
> Adds a critically missing feature to light tubes & bulbs

- code/game/machinery/teleporter.dm
> Fixes permanent teleporters not being deconstructable

- code/modules/mob/living/carbon/human/species/abductor.dm
Fixes https://github.com/ParadiseSS13/Paradise/issues/4514
Abductors are no longer super nerds who can speak other languages
fix: Fixes abductors speaking other languages
/:cl:
> Fixes Abductor Languages

- code/game/gamemodes/changeling/changeling.dm
- code/game/gamemodes/cult/cult.dm
- code/game/gamemodes/extended/extended.dm
- code/game/gamemodes/game_mode.dm
- code/game/gamemodes/malfunction/malfunction.dm
- code/game/gamemodes/meteor/meteor.dm
- code/game/gamemodes/mutiny/mutiny.dm
- code/game/gamemodes/nuclear/nuclear.dm
- code/game/gamemodes/traitor/traitor.dm
- code/game/gamemodes/vampire/vampire.dm
- code/game/gamemodes/wizard/wizard.dm
Fixes some game modes giving traitors less than 20 TC.
Doesn't apply 99% of the time, but if adminbus is involved....
fix: Fixes traitors getting less TC on some game modes
/:cl:
> Telecrystal Fix

- code/game/gamemodes/changeling/changeling_power.dm
- code/game/gamemodes/changeling/powers/swap_form.dm
> Fixes an oldie

- code/game/machinery/Sleeper.dm
- Fixes obscure sleeper runtime
> Fixes sleeper runtime

- code/modules/reagents/oldchem/chemical_reaction/chemical_reaction_food.dm
🆑 TechDragon610
rscadd: ice regent melts
/:cl:
makes sure that the ice regent turns to water when heated.
> makes ice regent melt when heated

- code/game/objects/items/stacks/stack.dm
- code/modules/power/cable.dm
> Fixes splitting cable coils off inactive hand not having correct color

- code/game/objects/items/stacks/stack.dm
> Makes stacks even better

- code/game/gamemodes/blob/blobs/blob_mobs.dm
- _Probably_ why blob was crashing? I'm not 100% sure since there's no useful log information regarding it.
> Fixes spores recursively dying forever

- code/game/objects/items/weapons/holy_weapons.dm
Fixes not being able to equip the nullrod to the Crusader armor
Fix: Fixes not being able to sheath the claymore in the Crusader Armor
/:cl:
> Fixes Nullrod Equipping

- code/modules/mob/living/carbon/brain/life.dm
- code/modules/mob/living/carbon/life.dm
Fixes #4463. I didn't want to add anything for normal brains as it makes sense for them not to live in hostile environments.
> Posibrain fix

- code/modules/reagents/oldchem/chemical_reaction/chemical_reaction_drink.dm
- code/modules/reagents/oldchem/reagents/drink/reagents_drink.dm
- code/modules/reagents/reagent_containers/food/drinks/drinkingglass.dm
Adds in the Cafe Mocha drink
Chocolate+Cafe Latte
Add: Adds in a mocha drink
/:cl:
> Adds in Cafe Mocha

- code/game/objects/items/weapons/stock_parts.dm
I'm surprised this wasn't causing runtime errors
> Fix some origin_tech s

- code/game/objects/items/stacks/rods.dm
- code/game/objects/items/stacks/stack.dm
Finally fixes there not being progress bars for most forms of stack-based construction
fix: Fixes the lack of progress bars for more stack-based construction
/:cl:
> Fixes Construction Progress Bars

- code/game/objects/items/weapons/holy_weapons.dm
Always double-check when you change var names, kids.
> Prayer Bead Fix

- nano/templates/order_console.tmpl
- nano/templates/supply_console.tmpl
bugfix: Fix javascript error in cargo UI
/:cl:
> Fix javascript error in cargo UI

- code/modules/clothing/under/miscellaneous.dm
The tie is blue, not red. Literally unplayable.
> Fixes the charcoal suit's description

- code/modules/reagents/reagent_containers/food/condiment.dm
https://github.com/tgstation/tgstation/pull/18150/fileshttps://github.com/tgstation/tgstation/pull/18150/files port as a suicide act
...Act now with suggestion and i might add more suicide acts based on them for other items
> Makes the crew more salty

- code/game/gamemodes/newobjective.dm
- code/game/gamemodes/steal_items.dm
This one should be obvious. A boring objective for everyone involved.
> Removes Stealing a RCD as an objective

- code/game/machinery/cryopod.dm
After repeated complaints about this from some admins, I decided to send this feature to the cooler. Players that used to use this as a respawn mechanic will now have to chill in deadchat like everyone else.
:cl:
del: Cryodorms will no longer kick you to lobby if you have logged off when they despawn your body, they will now always ghost you.
/:cl:
> The Ice Age (for cryodorms at least)

- code/modules/mob/new_player/new_player.dm
> Adds selected character below Setup Character button

- code/game/objects/items/weapons/storage/artistic_toolbox.dm
His Grace now grants stamina regeneration.
Given that it reduces dizziness, drowsiness, and makes you stun immune, it doesn't make much sense for it to not grant this, as well.
tweak: His Grace grants massive stamina regeneration
/:cl:
> His Grace Tweak

- code/modules/research/designs.dm
- code/modules/research/designs/stock_parts_designs.dm
- code/modules/research/rdconsole.dm
tweak: Makes stock parts build 5x faster
/:cl:
> Makes stock parts build 5x faster

- code/game/objects/items/weapons/misc.dm
Telephone can now be activated in hand to make a ring noise.
Force on telephones reduced from 3 to 0 (now you can call people any time without threat of serious injury!)
add: Telephones will now ring when activated in-hand
tweak: Force on telephones removed
/:cl:
> Telephone is More...Ring-y

- code/game/objects/items/weapons/storage/lockbox.dm
:cl:FreeStylaLT
typo: changed its to it's in lockbox description
fix: changed \red to <span> formatting
tweak: changed stetchkin's price from 9 TC to 4 TC, suppressor's from 3 TC to 1 TC
/:cl:
> Fixes some grammar mistakes, changes the \red to <span class> formatting

- code/game/gamemodes/vampire/traitor_vamp.dm
Actually fixes vamp-chaplains
Should actually fix things.
fix: Actually fixes vamp chaplains
/:cl:
> Actually Fixes Traitor-Vamp

- .travis.yml
- code/_onclick/hud/hud.dm
BYOND 510.1346 made the FLOAT_PLANE thing native apparently.
> Fixes a Thing

- code/game/objects/items/weapons/storage/belt.dm
This is why you shouldn't copypasta. But how did I paste that right in the middle of it and not notice?
Thanks to Keroman for telling me something was up with the bandolier.
> Bandolier fix

- code/modules/detective_work/scanner.dm
Issue #4720 
Deleting records fucked the scanner's search function up, the datacore is a shit.
This should, hopefully, resolve any issues by validating that the record we're checking for does, infact, exist.
The scanner will also now report partially complete searches (So if fingerprint records were erased it will still report name and blood DNA)
:cl: DaveTheHeadcrab
fix: Fixes the scanner's search functionality.
/:cl:
> Fixed #4720

- html/changelogs/AutoChangeLog-pr-4730.yml
Manual change to outdated changelog message, that wasn't changed in time for #4730.
> Fixes changelog message for #4730

- code/modules/food/recipes_candy.dm
Changes the recipe to 15u of salglu so that it's actually possible to make. Neat.
Fixes [#4750](https://github.com/ParadiseSS13/Paradise/issues/4750)
> Taffy. Quite.

- code/modules/mining/equipment_locker.dm
Fixes the mining drone bug where you couldn't repair it in a certain AI state and even when you could, it wouldn't actually do anything.
Fixes [#4237](https://github.com/ParadiseSS13/Paradise/issues/4237)
> Mining drone fix.

- code/modules/mob/living/carbon/human/interactive/functions.dm
- code/modules/mob/living/carbon/human/interactive/interactive.dm
- Chef was making things at a comically high rate (funny but to the point of it beginning to be significant cpu-wise on average)
- Fixes SNPC initialization handling job-specific PDA's correctly
- Movement tweak so SNPC's work on away missions correctly
> Fixes snpc PDA bug, heavily reduces rate that snpc chef does their thing

- code/game/objects/items/weapons/RCD.dm
- nano/templates/rcd.tmpl
Disclaimer: I did not give the normal RCD extra ammo capacity. I tested this with a combat RCD, which is identical to a normal one except it starts with 500 ammo.
rscadd: RCD gets a UI
rscadd: RCD-built airlocks can now receive different types and accesses.
/:cl:
> Gives RCD a UI, and the ability to select airlock type and access

- code/game/machinery/vending.dm
- code/modules/clothing/head/jobs.dm
- code/modules/reagents/reagent_containers/food/snacks/candy.dm
Fixes #4754 
This took a lot longer than it should have.
> Fixes candy corn not having an icon

- code/modules/mob/living/simple_animal/friendly/corgi.dm
Now space explorer corgis can explore space. Don't question how a corgi is able to breathe without an airtank. The answer is bluespace.
Fixes #4767
:cl:
rscadd: Space explorer corgis can now safely explore space
/:cl:
> Space explorer corgis are now space worthy

- code/__DEFINES/genetics.dm
- code/datums/spells/genetic.dm
- code/datums/spells/wizard.dm
- code/game/dna/dna2_domutcheck.dm
Fixes https://github.com/ParadiseSS13/Paradise/issues/4769
Mutate should now properly grant the hulk mutation, including all of hulk's abilities and proper overlays.
> Wizard Mutate Spell Fix

- code/modules/mob/living/silicon/pai/recruit.dm
Allows pAI candidates to see who actually requested them
Add: pAI candidates can now see who requested them
/:cl:
> pAI Candidates can now see who requested them

- code/modules/mob/living/simple_animal/parrot.dm
Poly managed to slip some colour macros past @tigercat2000 and was runtiming because of it
changes all parrot colour macros to spans
> Poly grabs the colour macro!

- code/game/turfs/unsimulated/beach.dm
:bikini::tropical_fish::shell:
> Fixes beach shallow/deep edge overlay being pullable

- goon/browserassets/js/browserOutput.js
https://github.com/d3athrow/vgstation13/pull/10775
> Fix goonchat tab issue

- code/game/gamemodes/vampire/vampire.dm
- code/game/gamemodes/vampire/vampire_powers.dm
- code/modules/admin/NewBan.dm
- code/modules/mob/living/simple_animal/parrot.dm
> Fixes a bunch of to_chat runtimes

- code/datums/Emote_system/emote.dm
- code/game/jobs/access.dm
- code/game/verbs/ooc.dm
- code/modules/mob/language.dm
- code/modules/mob/living/simple_animal/parrot.dm
- goon/browserassets/css/browserOutput.css
- goon/code/datums/browserOutput.dm
> Runtime & Goonchat fixes

- code/modules/mob/new_player/new_player.dm
Properly checks for admin rights for the players ready who is/who is not ready.
> Lobby Players Ready Fix

- code/game/machinery/turrets.dm
> Fixes instances gun_turret not properly firing projectiles

- code/modules/admin/topic.dm
fixes https://github.com/ParadiseSS13/Paradise/issues/3032
maybe
And i may have missed some...
:cl: Fethas
bugfix: adds comfirmation dialogs to transforms from player panel
/:cl:
> Adds comfirms to admin player transforms

- code/game/gamemodes/vampire/vampire.dm
Few issues that I fucked up with #4832 and didn't notice.
Thanks for pointing these out @Krausus
> [s]Fixes a Few Things I Failed to Notice in #4832

- _maps/map_files/cyberiad/cyberiad.dmm
There was a single Atmospherics Scrubbers pipe missing from the Custodial Closet.
It's there now.
> Fixes the Custodial Closet's (lack) of Scrubber Pipes

- code/game/turfs/simulated.dm
Nerfs Space lube
@TheDZD and I were waiting for the other slip PR to be changed a bit, but it never happened, so we opted to make an independent PR.
- Damage Removed
- Duration reduced from 7 to 5
Tweak: Space lube damage removed and duration reduced from 7 to 5
/:cl:
> Nerfs Space Lube

- code/modules/reagents/newchem/pyro.dm
Plays a distinctive "bang" sound instead of bubbling.
tweak: Azide and CLF3+Firefighting foam now play a bang sound when mixed
/:cl:
> Changes Mix Sound for Azide and Firefighting+CLF3

- code/modules/awaymissions/mission_code/spacehotel.dm
> Removes debugging messages from hotel code

- code/modules/mob/living/carbon/human/human_damage.dm
> Makes human's healthdoll immediately update upon health being changed

- code/modules/projectiles/guns/projectile/launchers.dm
> Fixes the m90 grenade launcher.

- code/game/objects/items/robot/robot_items.dm
Fixes borg's stun attack bypassing shields.
Also cleans up the code a bit
fix: Fixes borg's stun arm bypassing shields
/:cl:
> Fixes Borg Stun Arm Bypassing Shields

- code/modules/reagents/oldchem/reagents/drink/reagents_drink_cold.dm
> Fixes the brownstar reagent's description

- code/modules/reagents/Chemistry-Machinery.dm
- nano/templates/chem_master.tmpl
rscadd: The ChemMaster now uses NanoUI! Yey!
/:cl:
> The Long-Requested Nano-UI-ification of the ChemMaster

- code/modules/martial_arts/sleeping_carp.dm
- code/modules/mob/living/carbon/human/human_attackhand.dm
There is a small chance someone who is a vampire will also get traitor, or vice versa. If they get the martial art scroll (sleeping carp), they are unable to harm intent the head to drink blood anymore. This makes it so they can if they have sleeping carp.
:cl: Twinmold
Fix: Vampires with sleeping carp (traitor+vampire rounds) can now suck people's blood like normal.
/:cl:
> The Sleeping Carp Vampires

- code/modules/admin/verbs/atmosdebug.dm
> Fixes Check Piping verb

- code/modules/paperwork/photocopier.dm
- Absolutely not a "Goddamnit, just start over" PR. Nope
:cl:
add: When emagged, Photocopiers now have a cooldown if used to copy butts
/:cl:
> Adds Emagged Photocopier Cooldown

- code/modules/customitems/item_defines.dm
Gives it a hitsound, fixes the runtiming with the attack message.
> Jay Wingler Fluff Item Fix
