code/game/response_team.dm
`src` and `usr` have some very big, very important differences. Differences that were causing ERT creation to try and create an ERT composed entirely of whatever **one** person initiated its creation. To be honest, it's probably *good* that it was simply failing instead of ripping some poor captain out of his body to shove into an ERT member.
- Fixes usage of `usr` instead of `src` in a couple procs that no longer have distinct `usr`s.
- Fixes creation getting blocked by input occurring without spawning off.
- Fixes ERT members existing on their spawn point as naked bodies while choosing their class.
- Adds "ERT" to the gender selection dialog, so players actually know what they're picking it for.
- Fixes #5053.
=> Fixes ERT Creation

code/modules/clothing/under/chameleon.dm
Fixes chameleon jumpsuits not updating the user's appearance when EMPed and not properly reverting back to the default form when the EMP effect wears off.
=> Fixes chameleon jumpsuits not updating properly when EMPd

code/game/machinery/vending.dm
If you have your ID in your PDA and you click it on a vending machine it can be used to pay for products.
add: Can scan vending machines with your PDA to pay for items (if there's an ID in your PDA)
/:cl:
=> Can Scan Vending Machines with your PDA

code/modules/mob/living/carbon/human/say.dm, code/modules/mob/living/say.dm
fixes #5117 
i have no fucking idea, please kill this with fire asap
=> Fix radios not suppressing messages or whatever

code/game/machinery/atmoalter/meter.dm, code/game/machinery/camera/camera.dm, code/game/machinery/computer/computer.dm, code/game/machinery/doors/airlock_control.dm, code/modules/recycling/disposal.dm, code/modules/research/server.dm
Fixes #5126
Fixes #5122
:cl:Crazylemon
fix: Disposal units will now process again
fix: Computers will now process again
fix: Cameras will now process again
fix: Airlock sensors will now process again
:cl:
=> Fixes Various Machine Processing Fails

_maps/map_files/cyberiad/z5.dmm
ACTUALLY FIXES MINING APC
fix: ACTUALLY FIXES MINING APC
/:cl:
=> ACTUALLY FIXES MINING APC

code/game/machinery/doors/brigdoors.dm
bugfix: Brig timer UI reopening after being closed fixed.
/:cl:
=> Fix brig timer cell ui opening multiple times after being closed.

code/modules/projectiles/ammunition/energy.dm, code/modules/projectiles/gun.dm, code/modules/projectiles/guns/energy.dm, code/modules/projectiles/guns/energy/special.dm, code/modules/projectiles/guns/energy/telegun.dm, code/modules/projectiles/projectile/special.dm
Small refactor to those three guns to move their handling from general gun code to their specific gun code.
Fixes #4762
:cl:
fix: Fixes tempgun not recharging.
fix: Fixes tempgun beams costing one tenth of what they are supposed to.
/:cl:
=> Refactors Telegun Tempgun and Mimicgun

code/modules/client/preference/loadout/loadout_uniform.dm
=> Fixes corporate security uniforms not being selectable

code/game/objects/effects/datacore-effect.dm, code/world.dm
Returns JSON data in the format
`{ department: [{ name: title }, { name: title }] }`
For CyberiadAI or any other bots.
=> Add crew manifest world/Topic

code/modules/client/preference/loadout/loadout_general.dm, code/modules/client/preference/loadout/loadout_shoes.dm, code/modules/client/preference/loadout/loadout_suit.dm, code/modules/client/preference/loadout/loadout_uniform.dm, code/modules/clothing/masks/miscellaneous.dm
tweak: IAAs can now select the classic secHUD in loadouts
rscadd: adds bananas and suit jackets to the loadout system
rscadd: adds dress shoes and fancy sandals to the loadout system
fix: Miners can now get the mining coat from loadouts
/:cl:
Also added a bunch of missing slashes to bandanas.
=> Further loadout tweaks.

code/game/objects/items/toys.dm, code/modules/mob/living/damage_procs.dm, code/modules/research/experimentor.dm, code/modules/surgery/face.dm, code/modules/surgery/other.dm
Fixes up `apply_damage`
Nothing really impacted, to be honest.
=> Fixes up apply_damage

code/modules/events/event_container.dm
Well, more like re-adds it.
:cl: FreeStylaLT
add: Added grid check into random events.
/:cl:
=> Adds electrical grid check to random events.

SQL/paradise_schema.sql, SQL/paradise_schema_prefixed.sql
Somehow I didn't see this until after merging #4739.
=> Fixes Another Error in SQL Schema

code/modules/mob/new_player/new_player.dm
=> Fixes Late-Join Window's Round Duration

code/game/jobs/job/supervisor.dm
Changed the text from: "All hands, captain" to "All hands, Captain."
The supervisors are now also proprly capitalised.
It kinda bugged me that they weren't to begin with.
=> captain to Captain

code/modules/clothing/clothing.dm, code/modules/clothing/gloves/color.dm, code/modules/clothing/gloves/miscellaneous.dm
:cl: Fethas
rscadd:Due to various complaints from tajarans having hand cramps, glove makers have changed the fabric to not include plasteel in the thread...
/:cl:
=> Readds Glove snipping

code/game/gamemodes/vampire/vampire.dm, code/modules/mob/living/carbon/human/human_attackhand.dm
Yes yes i know..snowflake species checks..
:cl: Fethas
tweak:Plasmaman can no longer be vampires
tweak:removes the mask check on both victim AND Vampire and makes the message a bit more obscure...so its up to your imagination of where you are biting them and with what..
bugfix: (Maybe?)..We actually check if the race HAS BLOOD before trying to suck them
/:cl:
=> Alternative to #5219 :super snowflake edition

code/game/gamemodes/malfunction/Malf_Modules.dm
I simply removed one of the C's in "Cconstruction" and added a space in
another description.
=> Fixing spelling issues in Malf AI ability desc.

code/game/objects/items/stacks/sheets/light.dm, code/game/objects/items/stacks/stack.dm, code/modules/admin/verbs/SDQL2/SDQL_2.dm, code/modules/admin/verbs/debug.dm
Removes some more del's
Pretty much the only del's left now are for clients (intentional), and controllers.
=> Removes More Del's

code/__DEFINES/atmospherics.dm, code/__DEFINES/misc.dm, code/game/sound.dm
I dunno why this was a constant and not a define.
*shrug*
=> Sound Defines

nano/templates/chem_master.tmpl
The Condimaster now actually makes a bottle of condiments, instead of
only making packs.
Thank you, ChopChop1416 for telling me about Git Grep, that made finding
the file a LOT easier.
Note: This is a fix for issue #5292
=> Fixes the Condimaster so it can actually make condiment bottles.

code/modules/clothing/suits/storage.dm
Fixes the C4 exploding bug when you put it in a lab coat, thanks to CrazyLemon who helped me with this. C4 exploding bug can be found here #5055 
:cl:
Fix: Fixed the C4 labcoat exploding bug
/:cl:
=> Fixes the C4 bug

code/game/machinery/computer/pod.dm, code/game/machinery/door_control.dm, code/game/machinery/doors/airlock.dm, code/modules/admin/buildmode.dm, code/modules/admin/topic.dm, code/modules/security_levels/security levels.dm
Removes a bunch of `in world` calls for airlocks/doors.
=> Removes Airlock World Calls

code/game/objects/items/weapons/twohanded.dm
Compiled it and it must have fixed the spaces and stuff too.
Fixes how other people can see your failures of trying to hide in a plant with something in your other hand.
I ended up purging my entire fork and hopefully theres not 1000 merge tracking things now
:cl:
tweak: Fixes "is too cumbersome to carry in one hand" from showing up to other players.
/:cl:
=> Fixes "is too cumbersome to carry in one hand" from showing up to other players

code/datums/spells/horsemask.dm
This is quite a simple fix for the horsemask spell bug which can be found here #5270
:cl:
Fix: fixes the bug where you couldn't put a horsemask on people
/:cl:
=> Fixes horsemask bug

code/game/gamemodes/changeling/changeling.dm, code/modules/telesci/bscrystal.dm
Fixes the bug where changelings receive objectives to absorb species #5338 that they cannot absorb. Simply fixing the check so it checks for blood and dna, similar to the check when you actually try to absorb someone.
Excuse the extra commits I have been having some issues with GitHub lately.
:cl:
Fixes changeling absorb bug
/:cl:
=> Fixes changeling bug

code/modules/mob/living/simple_animal/friendly/corgi.dm
Makes corgis (Other than Ian, Lisa, and E-N) have a randomized gender, instead of always being male.
I'm sure nothing bad like accidental corgi puppy outbreaks could come from this.
~~Also fixes a grammar thing. The message you get when shaving a corgi will now properly use 'the' when the corgi doesn't have a name and is just "corgi".~~Nevermind
=> Corgi Gender Equality

code/game/jobs/whitelist.dm
thanks to a certain salty tiger...
Fixes https://github.com/ParadiseSS13/Paradise/issues/5202
:cl: Fethas
bugfix: The whitelist will respect addons better, didn't even have to make a ban appeal..
/:cl:
=> Fixes #5202

code/game/gamemodes/changeling/changeling.dm
Just removed some un needed coding fluff which wasn't even being run.
=> Removes coding fluff

code/_globalvars/lists/objects.dm, code/controllers/Processes/fast_process.dm, code/controllers/Processes/machinery.dm, code/game/machinery/camera/presets.dm, code/game/machinery/computer/pod.dm, code/game/machinery/doors/airlock_control.dm, code/game/machinery/doors/brigdoors.dm, code/game/machinery/iv_drip.dm, code/game/machinery/machinery.dm, code/game/machinery/recycler.dm, code/game/machinery/syndicatebeacon.dm, code/modules/arcade/claw_game.dm, code/modules/mining/equipment_locker.dm, code/modules/mining/machine_stacking.dm, code/modules/mining/machine_unloading.dm, code/modules/mining/mint.dm, code/modules/recycling/conveyor2.dm, paradise.dme
Ports over TG's fast processing
Basically it's a process loop that processes things incredibly rapidly; every 0.2 seconds, as a matter of fact.
Things that use fast processing:
- Conveyors
- Ore Redemption
- Stacking Machine
related
- ports over TG's recycler updates, largely so it plays nice with super fast conveyors
tweak: Dramatically speeds up conveyor belts
/:cl:
=> Adds in Fast Processing

code/modules/clothing/suits/miscellaneous.dm
4 of these don't have sprites~~, the other is a mankini~~, none of them are mentioned anywhere else.
=> Removes unused stripper uniforms

code/game/objects/structures/crates_lockers/closets/utility_closets.dm
=> Fixes welded fireclosets not showing up properly

code/datums/datumvars.dm
I think I might've accidentally stripped this when looking at this conditional wrong, when refactoring the file a while back. Whoops!
Fixes #5347
:cl: Crazylemon
fix: Associative lists in VV now display properly again
/:cl:
=> Fixes the VV list view

code/game/jobs/job/engineering.dm
<s> Now engineers can steal all the diamonds</s>
Engineers and ATs are capable of retrieving building materials that they <s>don't</s> need for <s>non</s> engineering purposes.
:cl: Alexshreds
tweak: Engineers and Atmos Techs have access to the ORM
/:cl:
=> ORM 4 Engies 2016

code/datums/supplypacks.dm, code/game/objects/items/weapons/storage/uplink_kits.dm, code/modules/admin/verbs/debug.dm
For some reason I missed those while adding the Chaplain hoodie and others. This fixed (I believe) every issue with the old Chaplain hoodie still existing.
=> Fixes old chaplain hoodies existing

code/modules/mob/dead/observer/observer.dm, code/modules/mob/living/carbon/brain/brain.dm, code/modules/mob/living/carbon/human/human_defines.dm, code/modules/mob/mob_defines.dm
=> Removes Unused Mob Vars

code/modules/mob/living/silicon/robot/robot_modules.dm
Nothing bad could possibly come from this
:cl:
add: Engineering cyborgs now have floor painters. Absolutely nothing bad can happen because of this.
/:cl:
=> Adds floor painters to engineering cyborgs

code/game/gamemodes/changeling/powers/tiny_prick.dm
Fixes the transformation sting bug (cant find the ID for its issue page on the GitHub) and makes it check if the target has DNA or not. Which it didn't before, for some reason.
:cl:
Fix: fixes transformation sting not working.
Fix: transformation sting now checks if the target has DNA or not
/:cl:
=> Changeling update

code/modules/mob/living/carbon/human/human_organs.dm, code/modules/mob/living/carbon/human/life.dm, code/modules/surgery/organs/organ_icon.dm, code/modules/surgery/organs/subtypes/standard.dm
:cl: Crazylemon
fix: Fat people are now fat when naked.
/:cl:
=> You're Fatter.

code/game/gamemodes/changeling/powers/tiny_prick.dm
=> Fixes Styling Issue with Changeling Sting Transformation

code/modules/mob/living/silicon/robot/robot_modules.dm
Prevents the removal of cyborgs.
Don't worry, we'll all saved now.
=> Prevents Removal of Cyborgs

_maps/map_files/RandomZLevels/spacehotel.dmm, code/modules/mob/living/carbon/brain/brain_item.dm
Just a small fix for something I saw when porting devil.
Slime brains now take damage properly.
=> Slimebrains are now properly an internal organ.

code/game/dna/dna2_helpers.dm, code/modules/client/preference/preferences.dm, code/modules/mob/living/carbon/human/appearance.dm, code/modules/mob/living/carbon/human/species/species.dm, code/modules/surgery/limb_reattach.dm
Fixes eyes not being set right on round start
Fixes IPC heads not being able to be attached
Fixes debug spam of multi-brains
=> Fixes a bunch of organ-related bugs

code/modules/mob/living/carbon/human/human.dm
More things broken by Monster's blind conversion script.
fix: Fixes the attack text of simple animals attacking human mobs
/:cl:
=> Fixes Animal Attack Text

code/modules/surgery/bones.dm, code/modules/surgery/encased.dm, code/modules/surgery/implant.dm
I forgot to document this in the IPC surgery update PR, and so, I am removing it at Fox's request.
:cl: Crazylemon
tweak: You can now mend incisions after having cut open someone's ribcage.
/:cl:
=> You can now cancel surgery after cutting someone's ribcage open again

code/game/turfs/simulated.dm
Fixes a runtime when a non-human mob tries to bleed on the floor.
=> Fixes a runtime for non-human mobs bleeding on the floor

code/modules/mob/living/silicon/pai/software_modules.dm
Fixes a couple pAI messages to go to the right target.
=> Fixes a couple pAI runtimes

code/modules/surgery/organs/organ_external.dm, code/modules/surgery/organs/organ_internal.dm
=> Humans no longer spew debug messages when deleted

code/__DEFINES/qdel.dm, code/game/machinery/recycler.dm
=> Fixes a runtime when a recycler eats something containing other stuff

code/modules/hydroponics/seed.dm
=> Fixes some runtimes when throwing hydroponics fruit

code/game/gamemodes/gameticker.dm, code/game/machinery/computer/ai_core.dm, code/modules/admin/topic.dm, code/modules/admin/verbs/randomverbs.dm, code/modules/mob/living/silicon/ai/latejoin.dm, code/modules/mob/new_player/new_player.dm, code/modules/mob/transform_procs.dm
=> Moves AI movement to their own procs, and cleans up their creation

code/game/gamemodes/changeling/powers/fakedeath.dm, code/modules/mob/living/carbon/alien/death.dm, code/modules/mob/living/carbon/alien/larva/death.dm, code/modules/mob/living/carbon/brain/death.dm, code/modules/mob/living/carbon/human/death.dm, code/modules/mob/living/silicon/ai/death.dm, code/modules/mob/living/silicon/robot/component.dm, code/modules/mob/living/silicon/robot/death.dm, code/modules/pda/utilities.dm
=> timeofdeath is now set and used consistently

code/controllers/Processes/timer.dm, code/game/machinery/doors/airlock.dm, code/game/machinery/doors/door.dm, code/modules/surgery/organs/organ_external.dm
=> Fixes a runtime when an airlock set to `autoclose` is deleted

code/game/objects/items/weapons/storage/belt.dm
=> Fixes sheath??

code/modules/mob/living/silicon/robot/drone/drone.dm
Fixes https://github.com/ParadiseSS13/Paradise/issues/5559
fix: Fixes drones not being able to bump open doors
/:cl:
=> Drone Door Fix

code/modules/surgery/organs/organ_external.dm
This was breaking `Life` and causing huge problems for... anyone who had a limb injured enough to have wounds, which was then healed? Pretty bad stuff.
=> Fixes Hilariously Problematic Wound Cleanup Timer Runtime

code/modules/awaymissions/mission_code/spacehotel_npcs.dm
bugfix: Fixes hotel SNPC's getting access that they shouldn't get.
/:cl:
=> Fix hotel SNPC's getting access they shouldn't.

code/datums/mind.dm
The current one is pretty hellish.
I'm not touching the code part itself, because I'll probably break it, but I'm pretty sure it would use some work too.
BEFORE
AFTER
=> Makes TP formatting nicer

code/game/objects/items/weapons/scissors.dm
Just fixes the barber's scissors attack grammar. No more "has been beautifully cuts"!
=> Fixes the Barber's Scissors grammar

code/game/machinery/vending.dm, html/changelogs/Jughu-#5609.yml
Adds 4 epin autoinjectors to medbay machines
In trade for 2 epin bottles 
You would really think medbay would have atleast some epin autoinjectors
:cl: Improvedname
rscadd: Adds 4 epinephrine autoinjectors to nanomedplus vending machines
/:cl:
=> Adds 4 epin auto injectors to medbay vending machines

code/game/dna/genes/goon_powers.dm, code/modules/mob/living/carbon/human/emote.dm
NO ONE THOUGHT I WAS INSANE ENOUGH TO DO THIS
:cl:Fethas
rscadd: *fart now has newtonian move if you have the Superfart power
/:cl:
=> Slight Buff to Genetics

code/game/objects/items/devices/violin.dm
Adds a few funny attack messages, including 'strung' and 'fiddled'.
=> Adds new violin attack messages

code/game/objects/items/weapons/misc.dm
Cleans up the grammar of the Desk Fan and Ball Toy. Additionally, some new attack messages are added to the Red Phone and Cane.
=> Fixes misc grammar and adds new attack messages

code/modules/hydroponics/beekeeping/beekeeper_suit.dm
=> Fixes the beekeeper suit and hat descriptions

code/modules/projectiles/guns/energy/nuclear.dm
Don't call me a coder but im pretty sure this fixes #5655
=> Fixes bs missing sprite #5655

code/game/objects/items/weapons/dnascrambler.dm
=> Fixes DNA scrambler not having an icon

code/modules/projectiles/ammunition/magazines.dm
Also removes a probably unnecessary snowflake proc
Fixes #5672
=> Fixes shitty stetchkin mags disappearing when you put a bullet in them

code/game/machinery/autolathe.dm, code/game/mecha/mech_fabricator.dm, code/modules/research/rdconsole.dm, code/modules/research/research.dm, code/modules/research/server.dm, code/modules/spacepods/pod_fabricator.dm
Ports tgstation/tgstation#15394
As a result, operations that formerly looped through all research now are constant-time operations.
Also slightly refactors research datums to simplify transferring research data
=> Ports tg's associative-list research datums

code/modules/research/designs/machine_designs.dm, code/modules/research/designs/mechfabricator_designs.dm, code/modules/research/rdconsole.dm, code/modules/research/research.dm
Also fixes the admin "max tech" button
Fixes #5693
Fixes #5696
:cl:Crazylemon
fix: Borg coolers and SMES boards can be made again
/:cl:
=> SMES and Borg coolers can now be made again, R&D maxing works again

code/modules/flufftext/Hallucination.dm
fix: fixes a hallucination runtime, actually making one more aspect of being high as f*** work for the first time in ages
/:cl:
=> Fixes a hallucination runtime

code/__DEFINES/gamemode.dm, code/game/gamemodes/objective.dm
fix: SNPCs no longer get targeted by assasinate objectives
/:cl:
Fixes #5663
=> Ckeyless humans no longer get targeted by the assasinate objective

code/datums/mind.dm, code/game/objects/items/weapons/holy_weapons.dm
=> adds logs to missionary stuffs

code/datums/uplink_item.dm
This PR also signifies the moment at which my commit description quality starts to dip below acceptable levels.
Fixes #5688
=> Fixes nukie cyberimplants being free

code/game/gamemodes/miniantags/guardian/guardian.dm
This might be intentional, but...
#5729
=> Ghosts of tossed out guardians are now respawnable

code/modules/client/preference/preferences.dm
=> Character names can now have numbers

code/modules/arcade/arcade_base.dm
Arcade machines should no longer spawn additional arcade machines after
spawning additional arcade machines after spawning additional...
Fixes #5714
=> Arcade duplication fix

code/datums/uplink_item.dm
Yeah, #5750 was broken.
This unbreaks it.
=> Actually fixes the cyberimplants this time

code/game/objects/items/weapons/defib.dm
Correctly un-wields defib paddles when dropping.
=> Fix for issue #5768

code/modules/power/singularity/particle_accelerator/particle_chamber.dm, code/modules/power/singularity/particle_accelerator/particle_control.dm, code/modules/power/singularity/particle_accelerator/particle_emitter.dm, code/modules/power/singularity/particle_accelerator/particle_power.dm
Fixes https://github.com/ParadiseSS13/Paradise/issues/5850.
=> PA wording fixes

code/game/objects/structures/morgue.dm
Fixes https://github.com/ParadiseSS13/Paradise/issues/5884.
=> Grammar fix

code/game/machinery/newscaster.dm
Fixes double breaking news.
Fixes https://github.com/ParadiseSS13/Paradise/issues/5901
fix: Fixes double-breaking news newscaster
/:cl:
=> Fixes Super Breaking News

code/__DEFINES/misc.dm, code/game/verbs/ooc.dm, code/modules/admin/verbs/adminhelp.dm, code/modules/admin/verbs/adminpm.dm, code/modules/admin/verbs/pray.dm, code/modules/client/client defines.dm, code/modules/client/client procs.dm
Fixes https://github.com/ParadiseSS13/Paradise/issues/5848.
A cooldown of 0.5 seconds has been added to:
- OOC
- LOOC
- AdminHelp
- AdminPM
- Pray
Admins are not affected by this change. If spam starts happening through other channels as well we can add a similar cooldown there.
=> [s]Adds OOC throttling

code/modules/mob/living/simple_animal/tribbles.dm
P2W is bad, mmkay?
Also removes the `f_amt` var which existed on everything, yet was never used.
=> Brings the fur equipment in line with other loadout gear

code/controllers/configuration.dm, code/game/gamemodes/gameticker.dm, code/modules/admin/admin.dm, code/modules/client/client procs.dm, code/modules/mob/logout.dm, config/example/config.txt
Fixes the admin notifier to actually notify the admins if all admins leave the server.
=> Makes the admin logout tracking system actually work

code/controllers/configuration.dm, code/game/gamemodes/gameticker.dm, code/modules/admin/admin.dm, code/modules/client/client procs.dm, code/modules/mob/logout.dm, config/example/config.txt
Reverts ParadiseSS13/Paradise#5917
gahhhh I made a mistake
=> Revert "Makes the admin logout tracking system actually work"

code/game/gamemodes/nuclear/pinpointer.dm
As title says. IDK why this wasn't a thing before.
=> Lets you wear the NukeOps Pinpointer in PDA slot.

html/changelogs/AutoChangeLog-pr-5938.yml
Adds missing changelog entries for merges committed while the GitHub webhook was broken.
=> Changelog fixes

code/modules/crafting/recipes.dm
Fixes personal crafting of ED-209's being more expensive than otherwise should be.
Fixes https://github.com/ParadiseSS13/Paradise/issues/5979
unrelated: I hate these robotcs
🆑 Fox McCloud
fix: Fixes the personal crafting cost of ED-209's being too expensive
/:cl:
=> Fixes ED-209 Crafting Oversight

code/modules/surgery/organs_internal.dm
Alternative to #6013 
Fixes the issue without just giving aliens a snowflaked internal organ manipulation step
=> Fix xenomorph organ surgery (properly)

code/modules/computer3/computers/medical.dm, code/modules/computer3/computers/security.dm, code/modules/computer3/computers/station_alert.dm
Fixes a runtime with the computer3 programs for medical, security, and station alert
=> Computer3 machines no longer set the user's machine to a datum

_maps/map_files/shuttles/emergency_clown.dmm
NO NO NO NO NO NO NO NO NO NONONO
:cl: Fethas
bugfix:Removes a door i thought i did on th the clown shuttle template
/ :cl:
=> (Clown Shuttle Fix)NONO NO NO NO

code/controllers/configuration.dm, code/modules/client/client procs.dm, config/example/config.txt, interface/skin.dmf
Ports tgstation/tgstation#20058
Not 100% sure on how nicely this will play with new clients that haven't been on the server before
=> [s] MSO's CID randomizer buster

code/__HELPERS/game.dm
"Do you want to be a pet of Nerdwad McXenobiologist?"
"Do you want to be a pet of Nerdwad McXenobiologist?"
"Do you want to be a pet of Nerdwad McXenobiologist?"
"Do you want to be a pet of Nerdwad McXenobiologist?"
DAAAAAAAAAAAAAAAAAAAAAAAAAAA
:cl:Crazylemon
tweak: You can now opt out of all requests on a role for a round
/:cl:
=> You are now able to opt out of all role requests for a single round

code/game/machinery/iv_drip.dm
does what the tin says. In 1, 5 and 10 u rates
🆑 pinatacolada
tweak: IV drips now have adjustable rates
/ 🆑
=> Adjustable rate for IV Drips

code/modules/mob/living/silicon/robot/inventory.dm
:cl:Crazylemon
fix: Borg sight modules work again
/:cl:
=> Borg sight modules work again

code/_globalvars/lists/names.dm, code/modules/mob/new_player/new_player.dm, config/names/mime.txt
Mimes can now choose their own name on entry just like Clowns
:cl:
add: Mimes can now choose name on entry just like Clowns
/:cl:
=> Mimes can rename themselves

code/modules/mob/living/carbon/human/human_defense.dm
=> Fixes a silly admin logs runtime

code/__DEFINES/role_preferences.dm, code/__DEFINES/rolebans.dm, code/game/objects/effects/spiders.dm, code/modules/client/preference/preferences.dm
Giant spiders are now a separate role from Alien so a spider infestation doesn't opt you out of future xeno shenanigans in the round
🆑 Crazylemon
tweak: Giant spiders now have their own role pref
/:cl:
=> Giant Spiders no longer clog up the Alien role channel

code/game/objects/items/weapons/garrote.dm, code/modules/mining/equipment_locker.dm, code/modules/surgery/organs/subtypes/standard.dm
Garrote no longer runtimes when the mark vanishes
Limb removal no longer runtimes
Mining drones can activate their mesons again
Fixes #6070
:cl:Crazylemon
fix: Mining drones can now use meson sight again
/:cl:
=> Runtime killer

code/game/machinery/computer/medical.dm, code/game/machinery/computer/skills.dm
Hold out your tongue for the first winter snowflake! ❄️
🆑 Lady Luck
tweak: office laptops are now traversable
/🆑
=> Makes office laptops traversable

code/game/mecha/mecha.dm
Fixes https://github.com/ParadiseSS13/Paradise/issues/6122.
🆑 Markolie
fix: simple_animals now have an attack cooldown when attacking mechas.
/🆑
=> Add cooldown to simple_animal Mecha attacks

code/game/gamemodes/cult/ritual.dm
Every do a change and swore you commited it before you had gone to sleep?
yeah......that happend...
=> Bugsie 2:Do not sleep..ever..

code/game/machinery/OpTable.dm, code/game/machinery/computer/Operating.dm
Fixes it so operating tables and operating computer properly garbage collect.
Also resolves a runtime when there's no operating table for and operating computer.
=> Fixes Operating Table and Operating Computer GCing

code/game/objects/items/weapons/storage/bible.dm
:cl:Crazylemon
fix: Bibles can now reveal runes as they did before
/:cl:
=> Bibles can reveal runes now

code/game/gamemodes/cult/ritual.dm, code/game/gamemodes/cult/runes.dm
Fixes #6204
:cl:Crazylemon
fix: Joined Souls works now
fix: Scribing the end rune now no longer is impossible
/:cl:
=> Fixes a couple cult rune things

code/defines/procs/announce.dm
Fixes https://github.com/ParadiseSS13/Paradise/issues/6223.
=> Fix admin message title

_maps/map_files/cyberiad/cyberiad.dmm
Before:
http://i.imgur.com/CeRjdxI.gifv
***REEEE*** ✊ 😠 💢 
After:
http://i.imgur.com/vI8ZPNE.gifv
much better :ok_hand:😃
🆑 FreeStylaLT
tweak: AI sat transport tubes are no longer misaligned
/🆑
=> Fixes triggering AI Sat tube misalignment

code/modules/reagents/chemistry/reagents/medicine.dm
I'm not quite sure why the code is structured like that there, I'm probably in the wrong removing it, but I figured I'd just do that and wait for you people to shout at me.
The problem arises when your organs aren't organs.
That's a pill implanted into the teeth thing.
=> Fixes a weird mitocholide runtime. I think.

code/game/objects/structures/misc.dm
I was a dumb and couldn't do anything good in the last PR, so here's a real PR, with real text and commits.
=> Respawner Machine (Attempt Deux)

code/modules/surgery/dental_implant.dm
Fixes https://github.com/ParadiseSS13/Paradise/issues/6264
=> Fixes Dental Pill being an internal organ

code/game/gamemodes/cult/ritual.dm, code/game/magic/Uristrunes.dm
:cl: Fethas
bugfix: Fixes a rune runtime.
/:cl:
=> Bugsie:Stupid Rune Edition

code/__DEFINES/clothing.dm, code/modules/mob/living/simple_animal/bot/bot.dm, code/modules/mob/living/simple_animal/friendly/corgi.dm, code/modules/mob/living/simple_animal/simple_animal.dm
This is being done to remove the simple_animal/Topic() override, because that broke default languages.
Somehow also fixes using the language prefixes. Not sure what I did, but hey!
=> Add slot_collar, remove simple_animal add_inv/remove_inv

code/modules/reagents/chemistry/reagents/water.dm
Fixes ParadiseSS13#6324
:cl: Fethas
tweak: Brings unholy water in line with its description.
/:cl:
=> Unholy water fix

code/game/machinery/computer/buildandrepair.dm, code/modules/research/designs/comp_board_designs.dm, code/modules/research/xenobiology/xenobio_camera.dm
Xenobiology Console is now constructible, board has been added to Circuit Imprinter. It will work in the area it was built in and any with the same name.
:cl:
add: Xenobiology Console is now constructible, board has been added to the Circuit Imprinter.
/:cl:
=> Constructible Xenobiology Console

code/modules/mob/living/simple_animal/hostile/terror_spiders/terror_spiders.dm, code/modules/mob/mob_helpers.dm
```action = NOTIFY_ATTACK``` has replaced it
=> removes attack_not_jump from notify_ghosts

code/game/objects/items/weapons/grenades/clowngrenade.dm
Ooops
fix: Fixes traitor banana peels having no sprite
/:cl:
=> Fixes Iconless Banana Peels

code/datums/mind.dm, code/game/gamemodes/changeling/changeling.dm, code/game/gamemodes/changeling/powers/linglink.dm, code/modules/mob/language.dm, paradise.dme
https://github.com/tgstation/tgstation/pull/17618
Adds a new ability for Changelings, Hivemind Link. Get someone in a neck grab or higher and activate Hivemind Link to give them Hivemind Communication for 3 minutes (you can let go after using the ability). If you decide to choke the victim for extra paranoia, the victim will be stabilized (countering suffocation damage). All lings are alerted to the presence of the victim. You can talk to victims and perhaps persuade them to help you, give you intel, threaten them along with the other lings, or even ask for their uplink code.
:cl:
add: Changelings have a new default ability: Hivemind Link. This lets you bring a neck-grabbed victim into the hivemind for a few minutes. You can talk to your victims and perhaps persuade them to help you, give …
=> Hivemind Link

code/game/objects/effects/aliens.dm
Fixes https://github.com/ParadiseSS13/Paradise/issues/6353 Reeeeee
TG's object damage system when?
fix: fixes xeno eggs taking damgae from disablers
/:cl:
=> Fixes Xeno Eggs and Projectiles

code/modules/mob/camera/camera.dm, code/modules/mob/living/living.dm, code/modules/mob/mob.dm
Mobs just don't GC well under the vast vast majority of circumstances; they have so many references, it's ridiculous. I see them crop up in the "failed to GC" log way too much; we're just going to hard delete every single one.
=> Makes all Mobs Hard Delete

code/modules/hydroponics/grown/mushrooms.dm
Had listed amantin twice in the reagents_add function for destroying angel. Combined to 0.3
=> Cleaned up reagents in destroying angels

code/game/gamemodes/wizard/godhand.dm
If spells somehow get dropped they will now delete
fixes #6292
continues #6306
=> Fixes #6292

code/modules/client/client defines.dm, code/modules/client/client procs.dm
=> Fixes client varedit

code/controllers/configuration.dm
Doesn't change anything, player wise, except maybe ensure lighting ticks at the proper rate.
=> Tweaks Ticklag default config

code/controllers/Processes/lighting.dm
=> Readd lighting DI info

code/controllers/Processes/lighting.dm, code/modules/lighting/lighting_source.dm
=> Add debug light source/corner/overlay instance count

code/game/jobs/job/silicon.dm, code/game/jobs/job/supervisor.dm
Changes:
- IAA now requires 5 hours
- Captain and AI now require 20 hours
🆑
tweak: Playtime requirements for IAAs have been set at 5 hours (similar to Sec Officer). Playtime requirements for Captains and AI have been increased from 10 hours to 20 hours.
/🆑
=> Tweaks some playtime requirements

code/modules/events/spacevine.dm
:cl:Crazylemon
fix: Achieving higher growth rates on kudzu will result in a faster-growing vine when planted
/:cl:
=> Kudzu growth now scales the correct way for quicker growth speed

code/game/response_team.dm
Makes ERT members show up correctly in Player Panel New.
IE: "Major Tom (ERT Security)" instead of "Major Tom ()".
No CL as this is is only visible to admins.
=> ERT PPN Fix

code/modules/client/client procs.dm, code/modules/client/preference/preferences_mysql.dm
Title, pretty much. This should help us track down a few bugs.
=> Fix window flashing not saving to SQL & Add error logging to log_client_to_db

code/modules/reagents/chemistry/reagents/misc.dm
1(normal) >1.1 > 1.2> 1.25 > 1.3 > 1.5 (new cap)
Numbers can be changed...espically the mob metabolize cycle numbers as thats alway been voodoo to me.
:cl: Fethas
tweak: Cap growth serum at 1.5
/:cl:
=> Stunts Growth Serum

code/modules/lighting/lighting_overlay.dm
https://www.youtube.com/watch?v=8L1CDFvHTr4
STAND BACK WE IS DEBUGGING SHIT
NO CL
CRASHING THIS PR WITH NO SURVIVORS LOL!!!!111
=> Lighting DeBugging test

code/datums/datacore.dm, code/modules/mob/living/carbon/human/human.dm, code/modules/mob/living/carbon/human/human_defines.dm, code/modules/mob/living/carbon/human/species/station.dm, code/modules/mob/living/carbon/human/update_icons.dm, code/modules/mob/new_player/preferences_setup.dm, code/modules/surgery/organs/organ_external.dm, code/modules/surgery/organs/organ_icon.dm
Resolves #4960 at long last
When a new Vox spawns in, your tail won't suddenly break (become a different colour).
Abstracts icobase/deform/tail from the species definitions so individual mobs can have a different icobase/deform/tail than other mobs of the same species.
:cl:
fix: Vox tails won't change colour when other Vox spawn in anymore.
/:cl:
This also means you could go (potentially) tailless in the future (should a no-tail option or tail removal surgery be added) and makes icobase/deform icon changes possible. @HugoLuman this might prove crucial to your Yin PR as otherwise all Yin transformed guys will only have one of the 'skins' (pertaining to species) at once
_Still rendering just fine in the character creator. Humans and other species show up fine too._
_More than one Vox in …
=> Fixes Vox-tail Bug

code/modules/events/meaty_ops.dm
Fixes MeatorOps to actually end correctly...
Its like a one letter fix..do i need a CL for this?
=> Its one letter

code/modules/mob/living/carbon/human/species/station.dm
:cl:Crazylemon
tweak: Slime people and Dionae now make sounds when coughing
/:cl:
=> Slime people and Diona now make sounds when coughing

code/game/gamemodes/miniantags/borer/borer.dm
Initializing a bunch of datums and leaving them for the GC to clean up just feels *wrong*.
=> Adds a few patches to borer to not fling datums to the GC

code/modules/events/spacevine.dm
This makes it spread monstrously fast; none shall be spared.
This might be better as a specific mutation, instead of standard, extremely deadly behavior - this removes one of the primary inhibitors on kudzu growth.
:cl:Crazylemon
experiment: Space vines now have a mutation that lets them grow in a more intelligent manner
/:cl:
=> Kudzu is now more intelligent about where it tries to grow

code/modules/station_goals/bsa.dm
:cl:Crazylemon
fix: Centcomm is no longer obnoxiously pedantic, regarding BSA deployment
/:cl:
=> The BSA goal will no longer choke on the z2 BSA

code/modules/mob/living/carbon/human/say.dm
No cl, nothing visible to players
=> Fixes a speech_span runtime

code/modules/mob/living/living.dm
Fixes #6458 
:cl:Crazylemon
fix: Mind transfer abilities work again
/:cl:
=> Mind transfer works again

code/modules/recycling/disposal.dm
Fixes https://github.com/ParadiseSS13/Paradise/issues/6477
🆑 Markolie
fix: Slicing disposal pipes now shows a progress bar.
/🆑
=> Fix slicing disposal pipes not showing a progress bar

code/game/machinery/newscaster.dm, code/game/machinery/vending.dm
Turns out I'm a major idiot! Sorry everyone!
=> Fix secure vending machine and newscaster interaction

code/modules/shuttle/shuttle.dm, nano/templates/shuttle_console.tmpl
rscadd: Shuttle Console now uses Nano-UI.
/:cl:
=> Shuttle Console Nano-UI-ification

code/modules/reagents/chemistry/reagents/paradise_pop.dm
IT PASSED THE TURING TEST! ABORT! ABORT!
=> Nerfs sentient AI in our code

code/game/machinery/autolathe.dm, nano/templates/autolathe.tmpl
rscadd: Autolathe now uses Nano-UI.
/:cl:
<details> 
</details>
<details> 
<summary>Search screen</summary>
</details>
<details> 
<summary>Category screen + processing queue</summary>
</details>
=> Autolathe Nano-UI-ification

code/datums/wires/autolathe.dm, code/game/machinery/autolathe.dm
:cl:Crazylemon
fix: Autolathes can be hacked again
/:cl:
=> Makes autolathe hacking work again

code/game/dna/dna2_helpers.dm
No CL, no player-facing change
=> Fixes runtime when non-dna'd mobs step on a rad mine

code/modules/economy/EFTPOS.dm, nano/templates/eftpos.tmpl
rscadd: EFTPOS now uses Nano-UI.
/:cl:
<details> 
<summary>Unlocked screen</summary>
</details>
<details> 
<summary>Locked screen</summary>
</details>
=> EFTPOS Nano-UI-ification

code/game/machinery/computer/medical.dm, code/modules/mob/living/carbon/human/human.dm, code/modules/paperwork/filingcabinet.dm, nano/templates/med_data.tmpl
rscadd: Medical Records now uses Nano-UI.
/:cl:
Medical Records comments now uses the `fields["comments"]` list instead of using `fields["com_1"]`, `fields["com_2"]`...
I increased the size of the photo from 64x64 to 96x96
<details> 
</details>
<details> 
<summary>Record list</summary>
</details>
<details> 
<summary>Records maintenance</summary>
</details>
<details> 
<summary>Record</summary>
</details>
<details> 
<summary>Virus database</summary>
</details>
<details> 
<summary>Medbot monitor</summary>
</details>
<details> 
<summary>Temp message example</summary>
</details>
=> Medical Records Nano-UI-ification

code/game/machinery/computer/skills.dm, nano/templates/skills_data.tmpl
rscadd: Employment Records now uses Nano-UI.
/:cl:
I increased the size of the photo from 64x64 to 96x96
<details> 
<h4>Search on action</h4>
</details>
<details> 
<summary>Records maintenance</summary>
</details>
<details> 
<summary>Record</summary>
</details>
<details> 
<summary>Temp message example</summary>
</details>
=> Employment Records Nano-UI-ification

code/__DEFINES/mob.dm, code/controllers/communications.dm, code/game/dna/dna2.dm, code/game/machinery/telecomms/logbrowser.dm, code/game/machinery/telecomms/telecomunications.dm, code/game/objects/items/devices/radio/radio.dm, code/modules/mob/living/carbon/brain/brain.dm, code/modules/scripting/Implementations/Telecomms.dm
Full speed ahead
:cl:Crazylemon
fix: Telecomms monitor is now infused with fastitude
/:cl:
=> Telecomms monitor is speedier now

code/game/machinery/computer/security.dm, code/modules/mob/living/carbon/human/human.dm, code/modules/paperwork/filingcabinet.dm, nano/templates/secure_data.tmpl
rscadd: Security Records now uses Nano-UI.
/:cl:
Security Records comments now uses the `fields["comments"]` list instead of using `fields["com_1"]`, `fields["com_2"]`...
I increased the size of the photo from 64x64 to 96x96
<details> 
<h4>Search on action</h4>
</details>
<details> 
<summary>Records maintenance</summary>
</details>
<details> 
<summary>Record</summary>
</details>
<details> 
<summary>Temp message example</summary>
</details>
=> Security Records Nano-UI-ification

code/game/jobs/job/job.dm
🆑 Kyep
fix: players will no longer spawn with loadout items their job has no access to. 
/🆑
=> Loadout system bugfix

code/modules/economy/ATM.dm, nano/templates/atm.tmpl
rscadd: ATM now uses Nano-UI.
/:cl:
<details> 
<summary>Unauthenticated screen</summary>
</details>
<details> 
</details>
<details> 
<summary>Security level screen</summary>
</details>
<details> 
<summary>Transfer funds screen</summary>
</details>
<details> 
<summary>Transaction log screen</summary>
</details>
=> ATM Nano-UI-ification

code/game/jobs/job/job.dm, code/game/jobs/job/supervisor.dm, code/game/jobs/job/support.dm
Fixes #6617 
Fixes #6611 
:cl:Crazylemon
fix: Barbers and captains get the right stuff now
/:cl:
=> Fixes barber and captain equipment

code/game/machinery/doors/door.dm, code/game/machinery/doors/firedoor.dm
:cl:Crazylemon
fix: Firelocks can now be operated by AIs again
/:cl:
=> Robots can now work with firelocks again

code/__HELPERS/unsorted.dm, code/game/machinery/computer/law.dm, code/modules/computer3/computers/law.dm
AI upload, and borg upload, consoles now only work on the station zlevel.
🆑
tweak: AI & Borg upload consoles now have to be on the station zlevel to work.
/🆑
=> Stops AI & Borg upload consoles working on other zlevels

code/game/machinery/doors/airlock.dm, code/game/objects/effects/spawners/random_barrier.dm, paradise.dme
:cl:Crazylemon
rscadd: It's now possible to have random floors or walls when mapping
/:cl:
=> Adds a random barrier for use in mapping

code/game/jobs/job/support_chaplain.dm
=> Fixes Religious Choices Blocking Round Startup

code/__HELPERS/mobs.dm
=> [s]Disables the .click macro

code/modules/events/spacevine.dm
Also refactors space vines slightly to allow admins to delete spacevine events cleanly without blowing up half the station, if one of them mutates to "explosive"
:cl:Crazylemon
rscadd: Kudzu vines now can yield materials if carefully tended to
/:cl:
=> Encourages crew to foster highly dangerous biothreats

code/modules/clothing/spacesuits/miscellaneous.dm
=> Fixes the Mime's EVA Suit description

code/modules/mob/living/carbon/carbon.dm, code/modules/mob/living/carbon/human/human_damage.dm
:cl:Crazylemon
fix:Electrocution is now tracked in autopsy
/:cl:
Tell me what else needs autopsy tracking
=> Adds stuff to autopsy

code/__HELPERS/mobs.dm
.clicks click silently /
validhunters die in pain /
nobody misses
=> [s]Actually suppresses .click macros

code/game/jobs/whitelist.dm, code/modules/admin/sql_notes.dm, code/modules/karma/karma.dm
**Important:** If this gets ported to any downstreams using the karma or notes systems, they **must** use the Python script, below, to update their database.
~~First off, this is DNM until @Allfd is ready with the script that will clean up the tables; merging this without also cleaning up the tables will basically wipe out karma and some notes for an unpredictable number of people.~~
This makes the karma logging (`karma`), storing (`karmatotals`), and unlocking (`whitelist`) tables use ckeys (which are always the same for a given player) instead of keys (which are occasionally not the same for a given player). This should prevent the occasional karma issues caused by key inconsistencies (fixes #6595). The change from keys to ckeys requires these tables to be updated in any existing …
=> Makes Karma and Notes Tables Always Use CKeys

code/ATMOSPHERICS/components/binary_devices/passive_gate.dm, code/ATMOSPHERICS/components/binary_devices/pump.dm, code/ATMOSPHERICS/components/binary_devices/volume_pump.dm, code/ATMOSPHERICS/components/trinary_devices/filter.dm, code/ATMOSPHERICS/components/trinary_devices/mixer.dm, code/game/objects/structures/tank_dispenser.dm, nano/templates/atmos_filter.tmpl, nano/templates/atmos_mixer.tmpl, nano/templates/atmos_pump.tmpl, nano/templates/tank_dispenser.tmpl
rscadd: Tank dispenser now uses Nano-UI.
rscadd: Passive gate, pump and volume pump now uses Nano-UI.
rscadd: Atmospherics filter and mixer now uses Nano-UI.
/:cl:
<details> 
<summary>Tank dispenser</summary>
</details>
<details> 
<summary>Passive gate/pump/volume pump</summary>
</details>
<details> 
<summary>Filter/mixer</summary>
</details>
=> Atmos Nano-UI-ification

code/game/machinery/newscaster.dm, nano/templates/newscaster.tmpl
rscadd: Newscaster now uses Nano-UI.
/:cl:
Newscaster's photos now uses base64.
Refreshing the feed channel page will not add more views.
<details> 
<summary>Main menu</summary>
</details>
<details> 
<summary>Feed channel/feed story creation</summary>
</details>
<details> 
<summary>Feed channels</summary>
</details>
<details> 
<summary>Wanted issue</summary>
</details>
=> Newscaster Nano-UI-ification

code/datums/wires/airlock.dm, code/datums/wires/alarm.dm, code/datums/wires/apc.dm, code/datums/wires/autolathe.dm, code/datums/wires/camera.dm, code/datums/wires/explosive.dm, code/datums/wires/mulebot.dm, code/datums/wires/nuclearbomb.dm, code/datums/wires/particle_accelerator.dm, code/datums/wires/radio.dm, code/datums/wires/robot.dm, code/datums/wires/smartfridge.dm, code/datums/wires/syndicatebomb.dm, code/datums/wires/vending.dm, code/datums/wires/wires.dm, code/game/objects/items/devices/radio/radio.dm, code/modules/mob/living/simple_animal/bot/mulebot.dm, nano/templates/wires.tmpl
rscadd: Wires now uses Nano-UI.
/:cl:
=> Wires Nano-UI-ification

README.md
We don't use IRC anymore, not officially anyways.
=> Updates the Readme to have discord instead of IRC

code/modules/mob/living/carbon/human/emote.dm
Due to the controversy surrounding removing bible farting I would propose this alternative.
Who can say what will happen if you anger the gods?
🆑 Alffd
rscadd: Farting on a bible now puts you at the mercy of the gods.
rscdel: Removed automatic biblefarting gibbing.
/🆑
=> Makes bible farting less predictable

code/game/jobs/job/supervisor.dm
:cl: FlaaaaaattestGuitar
tweak: Magistrate now starts their shift with a pair of white gloves as well as Bridge and Meeting Room access.  
/:cl:
As per [this](https://nanotrasen.se/phpBB3/viewtopic.php?f=12&t=9999) thread.
Discuss below, I will adjust the PR.
=> Buffs Magistrate 👌

code/modules/projectiles/projectile/bullets.dm
Port of: https://github.com/tgstation/tgstation/pull/23088
Yeah, buckshot is insanely strong, no matter how you slice it; the fact that it's a two-shot kill at point blank is a bit much, not to mention the argument made in the PR above.
tweak: Buckshot now does a max of 70 damage, down from 90
/:cl:
=> Nerfs Buckshot

code/game/objects/items/devices/flashlight.dm
:cl: FlattyPatty
tweak: Improved Nanotrasen click manufacturing procedures now allow the flashlights to make that classic clicking sound you know and love.
/:cl:
=> Adds clicks to flashlights 🔦 

code/__DEFINES/construction.dm, code/datums/supplypacks.dm, code/game/objects/items/stacks/sheets/mineral.dm, code/game/objects/items/stacks/sheets/sheet_types.dm, code/modules/clothing/spacesuits/breaches.dm, code/modules/crafting/recipes.dm, code/modules/events/spacevine.dm, code/modules/food_and_drinks/drinks/bottler/bottler.dm, code/modules/mob/living/silicon/robot/drone/drone.dm, code/modules/mob/living/silicon/robot/drone/drone_items.dm, code/modules/reagents/chemistry/recipes/others.dm, code/modules/shuttle/supply.dm, paradise.dme
Plastic is not /sheet/mineral but /sheet now, plastic flaps can be deconstructed with a screwdriver and welder (takes roughly 2x wall decon time) and made with 5 sheets of plastic.
Added a new file for construction defines
:cl:
add: Plastic flaps can be deconstructed with tools and constructed using 5 sheets of plastic.
/:cl:
=> Plastic is not a mineral anymore, plastic flaps can be constructed/deconstructed

goon/browserassets/css/browserOutput.css, nano/templates/radio_basic.tmpl
A picture is worth a thousand words, so http://puu.sh/uQKUl/36b5ff094f.png
Inspired by the fact that Medical and Common are nearly indistinguishable in the chatbox, and extended to make some other channels fit the scheme as well.
=> Modify radio channel colors for better contrast. Medical channel especially affected.

code/game/gamemodes/gameticker.dm, code/game/objects/structures/crates_lockers/closets/secure/freezer.dm
Even IPCs.
Tested by arming and blowing the nuke as an IPC.
:cl:
tweak: No-one escapes nuclear hellfire.
rscadd: Secure fridges/freezers are now lead-lined and have thus become nuke resistant.
/:cl:
=> Nuke kills everybody (On the station Z-level).

code/game/objects/items/weapons/tools.dm, code/modules/research/designs/medical_designs.dm, code/modules/surgery/encased.dm, code/modules/surgery/face.dm, code/modules/surgery/generic.dm, code/modules/surgery/implant.dm, code/modules/surgery/organs_internal.dm, code/modules/surgery/tools.dm
- Fixes a couple of power tools having titanium on them
- Refactors laser scalpels so they're all the child of a parent type
-  This has the side effect of the incision management system being able to cauterize now
- Removes deprecated use of success rates being higher than 100 on surgery steps
tweak: Incision management system can now cauterize
/:cl:
=> Fixes Power Tools Materials and Recators Laser Scalpels

code/modules/admin/admin_verbs.dm
why is there no option to cancel out right now
=> Adds a cancel button to the drop bomb command.

code/modules/mob/new_player/sprite_accessories.dm
I thought I'd fixed this some time ago. Hmm!
:cl:
fix: Slime People can wear underwear, undershirts and socks.
/:cl:
=> Slime people can wear undergarments.

tools/icon_merge_tool/Run Icon Conflict Fixer.bat, tools/icon_merge_tool/icon_merge_tool.py
=> Kill all icon conflicts tbh

code/game/jobs/job/engineering.dm
The CE doesn't spawn with one, Yet even the mechanic does. This PR fixes that.
=> Gives the CE a T-ray scanner

code/game/machinery/doors/airlock.dm
=> Mime's door no longer breaks the mime code.

code/datums/uplink_item.dm
=> Fixes #6965

code/modules/mob/new_player/sprite_accessories.dm
Fixes #6980 
:cl:
fix: Skrell can now choose undergarments (undershirts, underpants, socks) at character creation and dressers.
/:cl:
Though this shouldn't stop anyone from going commando.
=> Skrell can now choose undergarments.

code/modules/mining/machine_processing.dm, code/modules/mining/mint.dm
Shoulda done a kickstarter
Rest in pieece urist mc memer you never implemented adamitine/mythrill it took u 5 years and you still dindu nuffin!!!
=> Goodbye old friend

code/modules/projectiles/ammunition/magazines.dm
The typo is actually "Incindiary" not "Incinidary". :3
Should this be done in a bigger Fixes PR? I just thought that I had free time and saw this sooo...
=> Fixes #6993

code/modules/food_and_drinks/drinks/drinks.dm, code/modules/mob/living/carbon/carbon.dm
:cl:
rscadd: You can now slam drinks/bottles/flasks by click-dragging them onto yourself while it's in your active hand.
/:cl:
Chugging is interrupted by dropping the glass/whatever, being incapacitated, moving, etc.
Unless you put the drink/bottle down or any of the above happens, you'll knock back the entire thing in one go. Unless you can't/won't, know how to stop or you'll... drop. Seriously, a bottle chug FUCKS you up.
Party animals only.
=> Enhances Alcoholism

code/game/gamemodes/miniantags/abduction/abduction.dm, code/game/gamemodes/nuclear/nuclear.dm, code/game/response_team.dm
:cl:
fix: Nuclear Operatives/ERT Members/Abductors will no longer spawn in with genetic quirks.
/:cl:
=> No more Extremely Round Teams

code/game/gamemodes/cult/cult_objectives.dm, code/game/machinery/cryopod.dm
🆑 Kyep
fix: Cultists now get a new sacrifice target when the current one cryos.
/🆑
Needs review by @Aurorablade, and I'd appreciate all the hard looks I can get on it generally, as I can't test this locally.
=> Fixes cults not getting new sac target when target cryos

code/__HELPERS/qdel.dm, code/game/machinery/camera/camera.dm, code/game/machinery/camera/camera_assembly.dm, code/game/machinery/cloning.dm, code/game/machinery/doors/brigdoors.dm, code/game/objects/effects/anomalies.dm, code/game/objects/effects/decals/cleanable.dm, code/game/objects/effects/spiders.dm, code/game/objects/items/devices/radio/headset.dm, code/game/objects/items/devices/radio/radio.dm, code/game/objects/items/weapons/dna_injector.dm, code/modules/food_and_drinks/food/snacks.dm, code/modules/mob/living/simple_animal/simple_animal.dm, code/modules/recycling/disposal.dm, code/modules/research/xenobiology/xenobio_camera.dm
Just some more qdel fixes.
Also ensures fake announcers properly `return ..()`
=> More qdel and Destroy Fixes

code/game/objects/items/weapons/cigs.dm
:cl: Purpose2
add: You can now light cigarettes with Wands of Fireball, at the cost of your eyebrows.
/ :cl:
=> Enables lighting cigarettes with Wands of Fireball

code/modules/research/designs/autolathe_designs.dm, code/modules/research/designs/equipment_designs.dm
rscadd: Rapid Cable Layer now have an autolathe design.
/:cl:
Fixes #7028
=> Gives RCL an autolathe design

code/modules/mob/emote.dm, code/modules/mob/living/carbon/human/emote.dm, code/modules/mob/living/silicon/emote.dm, code/modules/mob/living/simple_animal/bot/emote.dm
You can wink, buzz2, scream, smile, shake head, wave, nod and snap fingers at people now.
Someone mentioned something on the Discord and I just decided to go for it. 🤷‍
=> Adds Targeting to Some Emotes, Cleans up Emotes Backend

code/datums/spells/lightning.dm, code/datums/spells/magnet.dm, code/modules/clothing/head/misc.dm, code/modules/clothing/shoes/miscellaneous.dm, code/modules/clothing/suits/miscellaneous.dm, code/modules/clothing/under/miscellaneous.dm, code/modules/mob/living/carbon/superheroes.dm
:cl:
fix: Fixes Superhero ID cards
fix: Fixes Griffin missing his Freedom Implant
fix: Fixes ElectroNegmatic's Ability not working at all.
tweak: Changes LightnIan's ability into a non-damaging stun lasting 2 ticks, with the amount of people affected depending on how long you hold the power in for.
/:cl:
- New PR due to lead merges
- Cleans up useless items only used for superheros
=> Superheroes update

code/modules/reagents/chemistry/reagents/pyrotechnic.dm
🆑 Kyep
rscdel: Plasma dust no longer creates plasma gas on objects or turfs during reactions.
/🆑
Stops plasmadust grenade grief.
=> Removes Obj & Turf reactions from Plasma Dust

code/game/jobs/job/support_chaplain.dm
Fixes #7076
:cl: IK3I
fix: Chaplain now spawns with his bible
/:cl:
=> Adds Equip call for Chaplain's Bible

code/modules/clothing/suits/miscellaneous.dm
It was bothering me, ok?
🆑
rscadd: Permits hoodies to carry flashlights. 
/🆑
=> Permits hoodies to carry flashlights

code/game/turfs/simulated/floor/misc_floor.dm, code/game/turfs/unsimulated/beach.dm
:cl: alexkar598
fix: you can now click on things underwater
/:cl:
fixes #7021 
first pr on paradise
=> underwater fix

code/game/mecha/mecha_parts.dm, code/modules/admin/buildmode.dm
Fixes a few build mode related `Destroy`s not returning a qdel hint.
Also fixes mech chassis's failing to GC.
=> Fixes a few more Destroys

code/datums/progressbar.dm
Ported from Hippie, I *think* originally made by **tortellinitony**, but I'm not 100% on that.
Either way, thanks!
:cl: Flattest
rscadd: Animated progress bars!
/:cl:
=> Animated progress bars!

code/defines/procs/announce.dm, code/game/gamemodes/blob/blob_report.dm, code/modules/admin/verbs/randomverbs.dm
My last PR missed a bit of code, so I figured I might as well change this whole bit here.
Admins have access to the different types of announcements way faster now, and the whole thing is a bit cleaner, though the end result is still pretty much the same.
No CL because it's backstage.
=> More announcement tweaks 🔈

code/modules/spacepods/spacepod.dm
Simple QOL change that makes inserting an energy cell consistent with inserting into the other spacepod slots. I'm thinking no changelog necessary because this is super trivial and only affects pilots, but let me know if I should make one.
=> Notify user when cell inserted into spacepod

code/game/machinery/doors/airlock.dm, code/game/objects/items.dm
Just fixes a few things failing to GC.
=> Fixes More Destroys

code/_onclick/hud/alert.dm
Makes a few screen alerts properly GC.
=> Screen GC Issues

code/datums/mind.dm, code/datums/outfits/outfit_admin.dm, code/game/gamemodes/heist/heist.dm, code/game/jobs/job/job.dm, code/game/machinery/computer/cloning.dm, code/game/objects/items/weapons/implants/implant.dm, code/modules/admin/verbs/one_click_antag.dm, code/modules/admin/verbs/striketeam.dm, code/modules/mob/living/carbon/superheroes.dm, code/modules/surgery/implant.dm
=> Makes All Instances of Implanting Use Proper Procs

code/game/jobs/job/supervisor.dm
:cl:  Fethas
tweak: Magistrate, IAA, and BS will now spawn with the correct color dpet satchal and duffel
/ :cl:
=> Correct massive oversight on some outfit datums

code/game/objects/items/candle.dm, code/game/objects/items/robot/robot_parts.dm, code/game/objects/items/weapons/bee_briefcase.dm, code/modules/hydroponics/beekeeping/beebox.dm, code/modules/hydroponics/hydroponics.dm, code/modules/hydroponics/seed_extractor.dm, code/modules/hydroponics/seeds.dm, code/modules/mob/living/silicon/robot/robot.dm, code/modules/mob/living/simple_animal/hostile/bees.dm, code/modules/mob/living/simple_animal/hostile/hostile.dm
=> Hydro and Bees GC fixes

code/game/machinery/alarm.dm, code/game/machinery/firealarm.dm, code/modules/security_levels/security levels.dm
just more GC stuff.
And using proper list searches instead of `in world`
Also kills off unused vars on fire alarms.
=> More GC and Performance Fixes

code/modules/mob/living/carbon/human/examine.dm
Fixes #7277 
This was hard work.
=> Fixes #7277

code/game/jobs/job/medical.dm
:cl: Fethas
tweak: Removes sec access from the paramedic
/ :cl:
=> Decreases the Brig Physician job slot back to one

code/game/objects/effects/decals/Cleanable/humans.dm, code/game/objects/effects/spiders.dm, code/modules/clothing/clothing.dm, code/modules/clothing/under/accessories/accessory.dm, code/modules/clothing/under/accessories/holster.dm, code/modules/clothing/under/accessories/storage.dm
See the title
and spiderlings, apparently.
=> Makes Clothing Accessories, Clothing with Accessories, Blood, and Spiderlings GC

code/modules/reagents/reagent_containers/dropper.dm
There's not a single implementation of droppers I like (TG, Bay, or even Goon), so, I just refactored it how I thought was best.
Droppers function the same as before, with a minor change:
- Droppers now incur a 3 second delay on dripping, like syringes do
Fixes: https://github.com/ParadiseSS13/Paradise/issues/7241
fix: can no longer make lethal medical patches with droppers
tweak: dripping reagents on someone with a dropper now incurs a 3 second delay like syringes
/:cl:
=> Droppers Refactor

code/modules/clothing/glasses/hud.dm
fixes https://github.com/ParadiseSS13/Paradise/issues/7286
:cl: Fethas
bugfix: fixes hudsunglass goof with vox.
/ :cl:
=> Don't Let Coders Make Sprite PRs

code/modules/mob/living/carbon/human/examine.dm
fixes https://github.com/ParadiseSS13/Paradise/issues/7279
:cl: Fethas
bugfix: Makes thrall examine use MASKCOVERMOUTH and HIDEFACE flags
/ :cl:
=> thrall check

code/modules/mob/living/carbon/human/examine.dm
Jeez, Fethas.
https://github.com/ParadiseSS13/Paradise/pull/7281 broke examines; this fixes that.
=> fixes faec

README.md
Updates the github readme file to bring us into the github tradition of having build badges!
=> We need badges!

code/modules/clothing/head/misc.dm, code/modules/clothing/under/accessories/accessory.dm
Fixes #7307
- Fixes minor typos with Cowboy items
:cl:
fix: Fixes typos with cowboy items
/:cl:
=> Fixe typos with cowboy items

code/modules/admin/admin_verbs.dm
This follows a staff discussion on the matter.
Not visible to players, so no CL.
👌
=> Makes msay be enabled by default 💬

code/modules/food_and_drinks/kitchen_machinery/gibber.dm
=> Fixes #7324

code/game/objects/effects/decals/contraband.dm
:cl: Purpose2
fix: Makes the new posters actually spawnable.
fix: Fixes far more spelling errors than there ever should have been on the posters.
/ :cl:
=> Fixes poster issues

code/game/objects/items/devices/taperecorder.dm
Fixes #7332
- Deaf people can no longer hear tape recordings
:cl:
bugfix: Deaf people cannot hear tape recordings anymore
/:cl:
=> Fixes Deaf Listening

code/game/dna/genes/goon_powers.dm
:cl:
fix: Empath stops telling you how much it hurts to not be human
/:cl:
=> Fixes #7316

code/game/jobs/job/job.dm
So I can stop seeing this every single round start.
=> Fixes a superfluous bracket

code/game/objects/structures/morgue.dm
=> Fix morgue trays flying away

code/modules/admin/banjob.dm
I can't get XAMPP to work over here because of my illiteracy, so this is completely untested.
I'd appreciate if someone took the code and tested it themselves if they have a mySQL set up on their local server.
rscadd: Adds a jobban-checking verb to the OOC tab.
/:cl:
=> Adds a jobban checking verb. 🔨

code/modules/admin/verbs/adminpm.dm
=> Fix admin PM logs including emoji_enabled span

code/modules/clothing/spacesuits/plasmamen.dm
:cl: Fethas
tweak: PLASMAMAN ATMOS SUITS ARE NOW THE SAME AS REGULAR ATMOS SUITS FLAG WISE! AND SO IS THE CE SUIT
/ :cl:
=> Here, now stop being on fire..

code/modules/mob/living/carbon/slime/slime.dm, code/modules/mob/living/silicon/robot/robot_movement.dm, config/example/game_options.txt
Quick movement patch on behest of tigercat, whose internet is acting up
=> Adds a patch to movement delay

code/game/machinery/vending.dm, code/game/objects/items/weapons/RCD.dm, code/game/objects/items/weapons/grenades/smokebomb.dm
Couldn't see a reason they weren't already using it.
=> Makes a few more things use QDEL_NULL

code/__HELPERS/lists.dm, code/game/gamemodes/miniantags/abduction/abduction_gear.dm, code/game/machinery/OpTable.dm, code/game/machinery/cloning.dm, code/game/machinery/computer/cloning.dm, code/game/objects/items/devices/scanners.dm, code/game/objects/items/weapons/defib.dm, code/modules/mob/living/carbon/carbon_defines.dm, code/modules/mob/living/carbon/human/death.dm, code/modules/mob/living/carbon/human/human.dm, code/modules/mob/living/carbon/human/human_organs.dm, code/modules/mob/living/carbon/human/life.dm, code/modules/mob/living/living.dm, code/modules/reagents/chemistry/reagents/disease.dm, code/modules/reagents/chemistry/reagents/food.dm, code/modules/reagents/chemistry/reagents/medicine.dm, code/modules/reagents/chemistry/reagents/toxins.dm, code/modules/reagents/chemistry/recipes/medicine.dm, code/modules/research/xenoarchaeology/genetics/reconstitutor.dm, code/modules/surgery/organs/augments_internal.dm, code/modules/surgery/organs/organ.dm, code/modules/surgery/organs/organ_internal.dm
Here I ported it anyways
https://github.com/tgstation/tgstation/pull/24106
:cl:Crazylemon
rscadd: Cloning now can be halted at any point, but ejecting too early may result in clones with missing body parts.
/:cl:
=> Cloning now puts you together bit by bit

code/modules/mob/living/carbon/human/life.dm
:cl:Crazylemon
fix: Slime people now no longer spontaneously die
/:cl:
=> Slime people don't die of heart attacks now

code/modules/admin/verbs/one_click_antag.dm
Because you guys can't be trusted.
Fixes #7408
=> Adds logs to the use of One-Click-Antag admin buttons

code/game/objects/items/devices/megaphone.dm
:cl: Purpose2
tweak: Increases the size of Megaphones.
/ :cl:
=> <span class='reallybig'>WHY ARE MEGAPHONES TINY ITEMS</span>

code/modules/pda/PDA.dm
In the past you could retrieve your ID by ALT clicking on PDAs. Today you can retrieve your pen by CTRL clicking on your PDA... Hopefully
🆑Fruerlund
add: You can now take out pens by CTRL Clicking PDAs
/🆑
=> CTRL Click on PDA's will now pull pens

README.md
=> Fixed website link

code/game/mecha/equipment/weapons/weapons.dm, code/modules/research/designs/mechfabricator_designs.dm
Tweaked the origin/required techs of the mech tesla, immolator, and disabler.
These managed to escape the R&D tech level refactor; just addressing/fixing these.
tweak: adjust the mech tesla, immolator, and disabler techs to bring it in line with the tech refactor
/:cl:
=> Fixes/Tweaks Old Origin Techs

code/datums/diseases/advance/symptoms/vision.dm, paradise.dme
Fix - #7454
Hyphema and ocular restoration were missing.
This PR comes with less git boogaloo.
🆑 Alexshreds
bugfix: Hyphema and Ocular Restoration are now possible to evolve from viruses
/ 🆑
=> Adds Missing Disease Symptoms Take 2

code/game/machinery/holosign.dm
fixes #7488
🆑 alexkar598
fix: Surgury holosign switch has correct icon at roundstart
/🆑
=> Fixes holo sign switchs

code/modules/power/lighting.dm
Fixes an exploit where glass can be infinitely made. simples.
Also changed a list var and deleted three just because it stuck out for me.
=> Fix infinite glass exploit

code/game/objects/structures/crates_lockers/closets.dm, code/game/objects/structures/crates_lockers/crates.dm, code/modules/shuttle/supply.dm
Fixes #7242 
Fixes #7243 
:cl:
fix: Adds some sanity checking to the RCS.
fix: The cargo shuttle no longer permits RCS telepads.
/:cl:
See commit descriptions
=> Fixes Some RCS Issues

code/modules/mob/living/simple_animal/tribbles.dm
=> Fixes siemens_coefficient oversight

code/modules/mob/language.dm
=> Fix languages with apostrophes being unable to be made default

code/modules/mob/living/carbon/human/body_accessories.dm
On request from jay, makes jays old fluff of a tail open for public use by Tanagerines.
he just kept forgetting to ask someone to do it when he got his new one
:cl: Fethas
tweak: Public Wiggler Tail
/ :cl:
=> Makes Jays old fluff tail public

code/game/objects/structures/windoor_assembly.dm
=> Stops multi-windoor creation

code/modules/hydroponics/hydroponics.dm
Fixes #7564 
:cl: Purpose2
fix: Fixes Fluorine's non-functionality in plants.
/ :cl:
=> Fixes 7564

code/game/jobs/job/job.dm
=> Makes a loadout message public-friendly

config/example/admins.txt
So many people mess this up because the example is wrong, figure might as well just resolve it once and for all.
=> Fixes the 'standard' admins file

code/modules/admin/admin.dm, code/modules/admin/topic.dm
🆑 Kyep
fix: Smite/Bless commands are now restricted to Game Admins. (admins with R_EVENT)
/🆑
=> Changes Smite/Bless to require R_EVENT permissions

code/modules/mob/living/carbon/human/emote.dm
Because @Allfd forgot to in merge #7110.
=> Add Vulpkanin emotes to *help

code/modules/admin/admin.dm
🆑 Kyep
fix: Trial admins no longer see a permissions error when opening player panel.
/ 🆑
=> Fixes #7635

code/_onclick/hud/alert.dm, code/game/gamemodes/wizard/soulstone.dm
tweak: Chaplain's soul stone is now opt-in.
/:cl:
Alternative to that other PR I made a while back and broke by accident. I think this is a good option for leaving this in and not having to rip out the feature in its entirety.
Discuss!
=> Makes Chaplain soulstones opt-in 👻

code/modules/events/event_container.dm, code/modules/events/sentience.dm, paradise.dme
orginally in https://github.com/ParadiseSS13/Paradise/pull/7453
Simple mobs that have the SENTIENCE_ORGANIC flag will be elible for a sentience event. allowing them to talk and understand people.
:cl: Purpose2 and Re-Opened by Fethas
rscadd: Rare Sentience event, the mice now want coffee!
/:cl:
=> Re-Open sentience event

code/world.dm
This allows for direct kicking of clients through remote tools.
No changelog as backend/administrative only.
=> [s] Topic Kick

code/modules/surgery/limb_augmentation.dm
Fixes https://github.com/ParadiseSS13/Paradise/issues/7662
Fixes robotic augmentation surgery leaving the limb as an open wound
fix: Fixes limbs being an open wound after augmentation
/:cl:
=> Fixes Limb Augmentation Open Wound

code/modules/mob/language.dm, code/modules/reagents/chemistry/reagents/toxins.dm
Fixes a few of the things myself and others found post-testing. Whoops!
Edit: Day zero is over! Merge-ready.
Fixes #7685
:cl:fludd12
fix: Greys are now PROPERLY immune to sulfuric acid.
fix: Greys don't pretend to touch their heads when they don't manage to anymore.
/:cl:
=> [Ready!] Grey Rework Day-Zero Fixes

code/game/objects/items/weapons/teleportation.dm
:cl: Fethas
bugfix: fixes issue with hand teleporter not working in active hands
/:cl:
=> Hand Tele bug fix

code/game/objects/effects/mines.dm, code/game/objects/items/weapons/powerfist.dm, code/modules/recycling/conveyor2.dm
Just some minor \icon -> bicon() fixes
Also cleaned up power first's code a bit, as it had some errors in it.
=> Icon Fixes

code/game/objects/effects/anomalies.dm
Seems it was being garbage collected in error in #7038
Fixes #7714
:cl: Purpose2
fix: Anomalies will once again drop cores.
/ :cl:
=> Anomalys drop cores again

code/modules/mob/living/carbon/alien/humanoid/life.dm, code/modules/mob/living/carbon/alien/larva/life.dm, code/modules/mob/living/carbon/carbon.dm, code/modules/mob/living/carbon/human/death.dm, code/modules/mob/living/carbon/human/life.dm, code/modules/mob/living/carbon/human/species/plasmaman.dm, code/modules/mob/living/carbon/human/species/species.dm, code/modules/mob/living/carbon/life.dm, code/modules/mob/living/carbon/slime/slime.dm
Removes a whole bunch of (seemingly) unnecessary spawns in `Life`
=> Removes a bunch fo Spawns in Life

code/game/objects/items/crayons.dm
Fixes #7676
:cl:
fix: Rainbow and mime crayons will now change colour as intended.
/:cl:
=> Praise Honkmother! 📯 🤡 (Fixes mime and clown crayons not changing colour) 

code/game/objects/effects/anomalies.dm
=> Wherein I Grump at Bad Code

code/__DEFINES/combat.dm, code/game/machinery/adv_med.dm, code/game/machinery/iv_drip.dm, code/game/objects/items/devices/scanners.dm, code/game/objects/items/stacks/medical.dm, code/modules/mob/living/carbon/carbon.dm, code/modules/mob/living/carbon/human/examine.dm, code/modules/mob/living/carbon/human/human_defense.dm, code/modules/mob/living/carbon/human/species/species.dm, code/modules/mob/living/carbon/human/species/station.dm, code/modules/mob/living/damage_procs.dm, code/modules/reagents/chemistry/holder.dm, code/modules/reagents/chemistry/reagents/toxins.dm, code/modules/reagents/chemistry/reagents/water.dm, code/modules/reagents/chemistry/recipes/toxins.dm, code/modules/surgery/organs/blood.dm, nano/templates/adv_med.tmpl
This is mostly a fix and refactor PR, but it does have a new feature with it, as well.
Credit to TG for a number of these fixes
The blood system transitioned us from the old system to the new, but not everything was transitioned though so you could have some oddities with healing/fixing/stopping bleeding
Fixes:
- Fixes blood type and volume only showing up if a mob was low on blood
- Fixes exotic blood names
- Fixes examining and checking yourself not showing if you're bleeding or not
- Makes everything use the new bleeding system for bandaging
- Fixes species exotic blood being injected into them not increasing their blood volume
- Fixes faked deaths still causing bleeding, thus revealing that it is, in fact, faked.
- Fixes IV drips not transferring the proper amount of blood
Refactor:
- …
=> Blood Refactor Fixes

code/modules/reagents/chemistry/reagents/water.dm
Fixes a runtime with blood and mindless mobs.
Also prevents meta'ing a vampire (full power or not).
=> Fixes Blood Runtime

code/game/machinery/iv_drip.dm
Fixes a runtime involving attaching IV drips to non-carbons.
also fixes https://github.com/ParadiseSS13/Paradise/issues/7489
=> Fixes IV Drip Runtime

code/game/gamemodes/vampire/vampire_powers.dm, code/game/objects/items/weapons/dnascrambler.dm, code/modules/mob/new_player/preferences_setup.dm
:cl:
fix: Fixes a bug with Vampire Shapeshift where you didn't get a name appropriate to your species and clarifies the ability description.
fix: Fixes a bug with DNA scramblers whereby you wouldn't get a name appropriate to your species.
/:cl:
Ensures you won't be taking on another species using this vampire shapeshift by circumventing an exploit.
Desnowflakes preferences_setup.dm like I had done with preferences.dm in #7019.
=> Vamp Shapeshift/DNAScrambler Fixes & Desnowflakes Preferences Setup

code/modules/power/cable.dm
Makes @Bram961 very happy
:cl:Crazylemon
fix: Cable laying by clicking the cable you want to join to works now
/:cl:
=> Fixes easy cable laying

code/modules/mob/living/simple_animal/friendly/diona.dm
This PR lets diona nymphs live in space like their gestalt form, instead of dying to cold and missing oxygen.
Fixes #7807 
Fixes #6028
I don't know what I did wrong on my last contribution but the changelog entry didn't show up in the actual changelog. Please confirm that I did it right this time. 
:cl: Ataman
fix: Fixed diona nymphs needing oxygen and getting cold.
/:cl:
=> Make diona nymphs space worthy

code/modules/mob/living/carbon/human/species/species.dm, code/modules/reagents/chemistry/reagents/water.dm, code/modules/surgery/organs/blood.dm, code/modules/surgery/organs/organ_internal.dm
Fixes blood volume being able to exceed the maximum of 560.
TG allows you to go up to 2000 units of blood, but I suspect this is in error; I'm pretty sure you' die if you had that much blood in you.
fix: Fixes blood volume being able to exceed 560
/:cl:
=> Limits BLood Volume to 560

code/modules/admin/permissionverbs/permissionedit.dm
=> [s] Closes a rank modification hole

code/__HELPERS/text.dm, code/_globalvars/configuration.dm, code/controllers/configuration.dm, code/modules/admin/verbs/SDQL2/SDQL_2.dm, code/modules/admin/verbs/modifyvariables.dm, code/modules/ext_scripts/irc.dm, code/modules/ext_scripts/python.dm
=> [s] Oh my gooooooooo-

code/__HELPERS/text.dm
=> Adds#spaces#to#recognized#characters#for#paranoid#sanitize

code/modules/client/preference/preferences.dm
🆑 Kyep
fix: Loading a different character while in the lobby will now update the character name listed on the lobby screen. Same when you rename an existing character.
/🆑
=> Fixes #4721 - char name not updating on new player screen when different character loaded

code/modules/surgery/organs/organ.dm
Fixes cloners causing organs to be infected.
Fixes https://github.com/ParadiseSS13/Paradise/issues/7857
fix: Fixes cloners causing infections in clonees
/:cl:
=> Fixes Infections in Organs from Cloning

code/game/machinery/adv_med.dm, code/game/machinery/cloning.dm, code/game/objects/items/weapons/implants/health.dm, paradise.dme
Fixes a number of oddities about health implants
- Health implants won't grant an action button anymore
- Health implants will now properly display health
- Health implants now properly show up on advanced scanners
=> Fixes Health Implants

code/game/gamemodes/objective.dm
Oops, my bad. Should have noticed this in @FlattestGuitar's PR.
=> Fixes Getting Weird/Undefined Objective

code/modules/research/designs/stock_parts_designs.dm
Adjusted `lathe_time_factor` for all stock parts tier 1 through 4 to fix them to the correct value of 0.2.
🆑 Birdtalon
Fix: Protolathe stock part printing no longer takes a lifetime.
/ 🆑
=> R&D Stock Parts Print Time Fix

code/modules/admin/topic.dm, code/modules/admin/verbs/infiltratorteam_syndicate.dm
🆑 Kyep
fix: Playing as a smite/bless hunter, or syndie infiltration team member, now requires that you be traitor-eligible. IE: have enough playtime, and the preference enabled.
/🆑
Fixes #7925 
Would appreciate the maints verifying that this is indeed the correct way to do it.
=> Fixes #7925 for smite/bless and SIT

code/modules/surgery/cavity_implant.dm, code/modules/surgery/implant_removal.dm, code/modules/surgery/other.dm, code/modules/surgery/remove_embedded_object.dm
fixes https://github.com/ParadiseSS13/Paradise/issues/7974
:cl: Fethas
bugfix: Dethaws some IPC surgery issues.
/:cl:
=> IPC Surgery Fix

code/modules/surgery/organs/organ_external.dm
Fixes Diona and other races from having internal bleeding.
Fixes: https://github.com/ParadiseSS13/Paradise/issues/7959
fix: Fixes Diona, Plasmamen, and other races having internal bleeding
/:cl:
=> Fixes Bloodless Internal Bleeding

code/game/objects/items/weapons/paint.dm
Fixes #8042 
🆑 Birdtalon
fix: Paint bucket now respects its lid.
/🆑
=> Paint Bucket Fix

code/game/gamemodes/changeling/powers/fakedeath.dm, code/modules/mob/living/carbon/human/emote.dm
:cl: Fethas
bugfix: There is a time and place for emotes, fakedeath is not one of them.
/:cl:
=> [FIX]Prevents emotes from happening under certain conditions

code/game/gamemodes/miniantags/bot_swarm/swarmer.dm
👀 
Fixes #8105 
Swarmers now respect antagonist ban.
🆑 Birdtalon
fix: Swarmers respect antagonist bans.
/🆑
=> Swarmers respect antag ban

code/game/objects/items/devices/scanners.dm
Spectrometers will now scan and the results will now be properly saved. You can also use the print function now.
🆑Fruerlund
fix: Spectrometers, print and scan.
/🆑
=> Fixes spectrometers

code/datums/datumvars.dm
HAWT MROWL!
((Fixes an issue with editing someting with VV returning a message that the object rejected the action. VV-Senpai will now notice you. No CL needed))
=> GIVES TIGERS VV REFACTOR A HAWT FIXIN

code/modules/mob/mob.dm
Currently the description conflicts with our rules. This amends that.
=> FlavorText Description Fix

code/modules/clothing/shoes/miscellaneous.dm, code/modules/reagents/chemistry/reagents/alcohol.dm
Fixes #8080 
A single word doesn't deserve a changelog.
Additional grammar fix regarding taping one's shoes... Shoes don't make footsteps, people do. This makes a bit more sense in my mind.
=> Spelling Mistake

code/datums/datumvars.dm
VV is no longer color blind friendly.
We have color on our attack logs now.
thank tiger for providing code cause fuck that i would've ever fixed
this lol
fixes #8115
=> VV Attack Log Fix

code/game/objects/items/weapons/rpd.dm, code/modules/mob/living/silicon/robot/robot_modules.dm, code/modules/research/designs/autolathe_designs.dm
Works fine. The autolathe price is pretty expensive, adjusted the RPD's materials to match.
:cl:
add: Engineering Cyborgs now have an RPD!
add: Maintenance Drones now have an RPD!
add: Hacked Autolathes can now print RPDs!
/:cl:
=> Adds the RPD to hacked Autolathes, Drones and Engineering Cyborgs

code/modules/reagents/reagent_containers/borghydro.dm
Adds hydrocodone to the cyborg hypospray (medical)
🆑  
Add: Adds hydrocodone to the Cyborg Hypospray
/ 🆑
=> Adds hydrocodone to medical borg hypospray

code/modules/food_and_drinks/drinks/bottler/bottler.dm
Fixes #7686 
List was being complete deleted and not reset to expected length.
🆑 Birdtalon
fix: Bottler doesn't break after one use.
/🆑
=> Fixes the Bottler

code/modules/mob/living/silicon/robot/robot.dm
No longer able to see/gossip with syndie/commando borgs over PDA messenger.
#7948
:cl:
Fix:No longer able to see/gossip with syndie/commando borgs over PDA messenger.
/:cl:
=> Syndie Borg fix

code/modules/hydroponics/beekeeping/beebox.dm
I didn't take into account people using bees with no reagent. I mean... who does that.
Fixes #8202 
🆑 Birdtalon
fix: Bees with no reagent will now work.
/🆑
=> Follow up bee fix.

code/game/gamemodes/cult/talisman.dm
Remake of #8109 seeing it is stale
Thank Mr.Foxman and turkeytoe for code.
:cl:
fix: Cult must use teleport tailsman in active hands.
/:cl:
=> Cult Teleport Fix

code/game/objects/structures/crates_lockers/crates.dm
Fixes #8159
:cl:
fix: Can now place garbage in garbage cans without standing on top of them.
/:cl:
=> Garbage Cans are now functional

code/game/objects/items/weapons/implants/implant_traitor.dm
🆑 Kyep
fix: mindslaving an antagbanned player now offers control of their mob to ghosts.
/🆑
=> handles antagbanned players who get mindslaved

code/modules/mob/living/simple_animal/hostile/terror_spiders/ghost.dm
Terror spiders now respect antagHUD.
🆑 Birdtalon
fix: Terror spiders now respect antagHUD respawn restrictions.
/🆑
=> Terror spiders respect antag HUD

code/datums/datumvars.dm
....just changes another number to try to keep the VV attack log to stop capping at 50.
Hopefully this works. otherwise i blame tiger.
=> Try to fix VV Log numbers

tools/mapmerge/instructions.txt
=> Update map merge instructions

code/modules/surgery/helpers.dm
:cl: Fethas
bugfix: Many things use sleeping. Surgry pain fail fix.
/:cl:
=> Hotfix for Surgery Pain

code/ATMOSPHERICS/atmospherics.dm, code/game/machinery/doors/airlock.dm, code/game/machinery/doors/firedoor.dm, code/game/objects/effects/mines.dm, code/game/objects/structures/fullwindow.dm, code/modules/mob/living/carbon/alien/special/facehugger.dm, code/modules/mob/living/simple_animal/friendly/corgi.dm, code/modules/shuttle/on_move.dm
Not much to say really; This PR is a bunch of fixes to try and reduce the number of issues...
Fixes #2704 - Full-sized plasma windows are fire-resistant, and reinforced ones are fully fireproof;
Fixes #2802 - You can now remove facehuggers from corgis. Multiple facehuggers hugging the same corgi will now drop off the corgi instead of disappearing inside it to hug it forever;
Fixes #5912 - Fixed an atmospheric runtime;
Fixes #7023 - Firedoors and other doors will no longer automatically close when a shuttle docks;
Fixes #7205 - Radiation mines now do not affect species with the NO_DNA flags (they will still take the damage);
Fixes #7654 - Airlocks no longer spark when you throw something metallic through them. Instead of checking for if the item contains metal, it just checks if it's …
=> In which I fix a bunch of issues and tweak some other things

code/datums/mind.dm, code/game/machinery/cloning.dm, code/game/machinery/computer/cloning.dm, code/modules/mob/living/death.dm
Suiciders are no longer able to be cloned in any fashion.
:cl:Crazylemon
tweak: Suiciding crewmembers are no longer capable of being cloned.
/:cl:
=> No more cloning suiciders

code/modules/admin/tickets/adminticketsverbs.dm
Day one fix.
Disables "My tickets" for non-admins while I fix a bug.
No CL due to backend changes.
=> Admin Ticket Fix

code/modules/reagents/chemistry/machinery/chem_dispenser.dm
🆑 
Add: Adds Sake to a hacked booze dispenser's menu.
/ 🆑
=> Adds sake to hacked booze dispenser

code/game/gamemodes/cult/cult_items.dm, code/game/gamemodes/cult/cult_structures.dm, code/game/objects/items/stacks/sheets/sheet_types.dm
split of https://github.com/ParadiseSS13/Paradise/pull/7345
Adding:
🆑 Fethas
tweak:pylon heal is now 3 secs (from 2.5s).
tweak:hulks cannot use cult blades or build structures.
tweak:Cult structures now drain blood(10) on build.
/ 🆑
=> Cult Pass split: Balance shit

code/game/machinery/hologram.dm
Fixes #8130, tested with a wiped AI, when only the stat was checked, and aghost, with the full check, i was unable to test more alone.
:cl:
Fix: Stops holograms from attempting to appear when they just disappeared because the AI became unable to keep it up.
/:cl:
=> Makes holograms end when they should

code/game/dna/genes/vg_powers.dm
fixes: https://github.com/ParadiseSS13/Paradise/issues/8340
=> Fixes Remote Talk Metagaming

code/game/gamemodes/miniantags/guardian/guardian.dm
:cl: Fethas
bugfix:Guardian health display fix.
/:cl:
=> Fix for Guardian Health display runtime

code/modules/admin/admin_verbs.dm, code/modules/admin/tickets/adminticketsverbs.dm
🆑 Fethas
bugfix: changes the my tickets from a verb..to a prock. To quote lemons: F.
/🆑
=> Fixes a teensy issue with a ticket command

code/game/objects/items/devices/flash.dm, code/game/objects/items/weapons/cosmetics.dm, code/game/objects/items/weapons/garrote.dm, code/modules/mob/living/carbon/human/examine.dm, code/modules/mob/living/carbon/superheroes.dm
Fix #8281
Stop some cases of assuming gender in the code.
🆑 
fix: Some genders are no longer assumed.
🆑
=> Stop assuming gender.

code/__DEFINES/clothing.dm, code/game/gamemodes/vampire/vampire.dm, code/game/machinery/vending.dm, code/modules/clothing/masks/miscellaneous.dm, code/modules/mob/living/carbon/alien/special/facehugger.dm, code/modules/mob/living/carbon/carbon.dm, code/modules/mob/living/carbon/human/human.dm, code/modules/mob/living/say.dm, code/modules/reagents/chemistry/reagents/water.dm
This PR provides for non-lethal vampire handling options, the purpose is to enable low-powered vampires to be able to be inserted into prison populations without posing a constant threat.
This will enable more IC options and RP possibilities for this class of antags as prisoners under the existing execution rules.
🆑Alffd
add: A new Anti-Bite muzzle has been added to the SecVendor. This muzzle can be locked through the strip panel and will prevent a vampire from feeding.
add: Holy water now causes vampires to vomit blood, before vomiting the water. After this holywater behaves as normal.
/🆑
=> Makes vampires more containable

code/datums/wires/airlock.dm
Ths bug is quite shocking and i don't want alot of people catching wind of it.
=> [s] Fixes an issue with airlocks.

code/game/machinery/doors/airlock.dm, code/game/objects/items/stacks/sheets/mineral.dm, code/game/objects/structures/false_walls.dm, code/game/objects/structures/mineral_doors.dm, code/game/objects/structures/statues.dm, code/game/turfs/simulated/floor/mineral.dm, code/game/turfs/simulated/walls_mineral.dm
=> Adds plasma ignitions to the atmos investigate logs

code/__HELPERS/logging.dm, code/modules/mob/language.dm
=> Logs Robot Talk

code/game/objects/items/weapons/RSF.dm
🆑 Kyep
fix: It is no longer possible for Service borgs using the Rapid Service Fabricator to end up with negative energy.
/ 🆑
=> RSF negative energy fix

code/modules/mob/living/carbon/slime/life.dm
I forgot that slimes were carbons...andd of course they don't have lungs
Fixes slimes just dying by themselves
fix: Fixes slimes dying by themselves
/:cl:
=> Fixes Slimes Dying on their Own

_maps/map_files/RandomZLevels/evil_santa.dmm
:cl:
rscadd: Adds fans under the doors at the North Pole.
/:cl:
=> Polar Vortex

code/game/gamemodes/game_mode.dm, code/game/jobs/jobs.dm
Kinda a back end change by by request from Tully.
Adds NT Rep to command roles and Magistrate to sec roles, This means they will be affected by approtiate job bans.
Assumeing i did this right...
=> Expands Banhammer

code/game/machinery/dye_generator.dm, code/game/machinery/poolcontroller.dm, code/game/objects/effects/spiders.dm, code/modules/economy/ATM.dm
Fixes https://github.com/ParadiseSS13/Paradise/issues/8371
Fixes https://github.com/ParadiseSS13/Paradise/issues/8330
Fixes https://github.com/ParadiseSS13/Paradise/issues/8339
:cl: Fethas
bugfix:Dye bottles were fed mutadone, lost telekensis.
bugfix:Grey should not go swim in the pool or the ocean.
bugfix:Depowered ATMS might not eat cards anymore.Maybe.
/:cl:
Do you hate bugs? We all do..If you like squishing bugs grab one from the issue list and have at it! Only you can help prevent bug...fires...things..
(The authort of this PR does not condone the Harm or Squishing of Kidan or other sentient insects)
=> Wherenin Fethas is actually useful and not making stupid features

code/modules/client/preference/loadout/loadout_donor.dm
=> Remove items from donor preferences with wrong license

code/modules/mining/equipment_locker.dm
Actually I'm surprised this was left so long. Miners rejoice!
:cl:
fix: Jaunters work again.
/:cl:
=> Fixes jaunters

code/game/objects/items/toys.dm
Adds some messages for playing with the syndicate balloon. Some suggestions for more messages / handling how others see the messages (currently it only displays one message) would be nice.
:cl:
tweak: Using a syndicate balloon while it's in your hand allows you to play with it.
/:cl:
=> You can now play with the syndicate balloon

code/world.dm
Allows for external scripts to rotate server logs without the overhead of a an additional controller.
=> Adds log rotate command to World/Topic()

code/modules/hydroponics/hydroponics.dm
Fixes #8584 
Missed underscore in original file.
=> Fixes 8584

.travis.yml
Changes Travis build test from unstable to stable branch to reflect current server version.
=> Change TravisCI tests to stable branch

SQL/paradise_schema.sql, SQL/paradise_schema_prefixed.sql, code/modules/client/client procs.dm, code/modules/client/preference/preferences.dm, code/modules/client/preference/preferences_mysql.dm
Note: you need Byond 511+ for this to work
:cl:
add: You can now change your client FPS in Game Preferences
/:cl:
=> Makes Paradise 60 FPS

code/game/verbs/ooc.dm, code/modules/admin/verbs/adminsay.dm
=> Prevents mentors from seeing stealthed admins

code/modules/projectiles/projectile/beams.dm
=> Oops. Emitter beams should have a green glow

SQL/updates/1-2.sql, code/__DEFINES/misc.dm, code/modules/client/preference/preferences_mysql.dm, config/example/dbconfig.txt
Fixes https://github.com/ParadiseSS13/Paradise/issues/8608
also adds an SQL update
:cl:
fix: Client FPS setting should save properly now
/:cl:
=> Fixes FPS Setting

code/modules/reagents/chemistry/reagents/pyrotechnic.dm
This code was commented out in pr #1438
Its been 2 years and it havent been touched.
=> Removes some old unused code

code/modules/mob/living/silicon/robot/drone/drone.dm
:cl: Tayyyyyyy
fix: Players job banned from syndicate can no longer play emagged drones
/:cl:
=> Players job banned from syndicate can no longer play emagged drones

code/game/data_huds.dm
I was passing the wrong thing
Consider it a test of the medical teams skill.
=> Fixes Med huds

code/game/data_huds.dm, code/game/gamemodes/miniantags/borer/borer.dm, code/game/gamemodes/miniantags/revenant/revenant.dm, code/game/gamemodes/miniantags/slaughter/slaughter.dm, code/modules/mob/living/simple_animal/simple_animal.dm
fixes https://github.com/ParadiseSS13/Paradise/issues/8645
=> medhud fixes

code/modules/food_and_drinks/drinks/drinks.dm
Fixes #8638
🆑 Birdtalon
fix; Prevents chugging of unopened drinks.
/🆑
=> Prevents chugging unopened drinks.

code/modules/mob/living/carbon/human/species/species.dm, code/modules/mob/living/carbon/human/species/station.dm, code/modules/reagents/chemistry/reagents/toxins.dm
:cl: MarcellusPye
fix: Grays can now drink sulphuric acid without being burnt
/:cl:
fixes #8349
=> Lets grays drink sulphuric acid

code/__HELPERS/text.dm, code/modules/paperwork/paper.dm
[time] tag replaced with current station time. One way conversion from pencode to text.
🆑 Birdtalon
add: adds [time] tag for paperwork
/🆑
=> Time tag for paperwork

code/game/objects/structures/crates_lockers/closets/secure/medical.dm, code/modules/reagents/reagent_containers/pill.dm
A request from Piccione🕊on discord.
A few more things for the Psyche locker.
- 1 Extra Haloperidol pill, 1 extra Methamphetamine pill, 2 Hydrocodone pills
- 1 Random plushie.
- 3 Random chocolate candies.
🆑 
tweak: A few more items in the Psyche locker.
/🆑
=> A few more things for the Psyche locker.

code/ATMOSPHERICS/components/unary_devices/vent_pump.dm, code/__DEFINES/process_scheduler.dm, code/game/area/areas.dm, code/game/machinery/doors/firedoor.dm, code/game/turfs/simulated/walls.dm, code/modules/clothing/spacesuits/rig/suits/light.dm, code/modules/mob/language.dm, code/modules/paperwork/carbonpaper.dm, code/modules/power/singularity/collector.dm
In case you ever get in the mood to start using [MapDiffBot](https://github.com/MapDiffBot/MapDiffBot), a GitHub bot for rendering changed areas of maps on PRs. It's optimized for tg so it might render oddly in some cases but these changes will make it baseline functional.
Precedent:
https://github.com/yogstation13/yogstation/pull/3137
https://github.com/tgstation/tgstation/pull/32284
=> Fix various syntactic problems

code/modules/reagents/chemistry/reagents/food.dm
What says on the tin. I deleted the taste descript of nutriments (since most foods contains nutriments, it made all food taste bland), changed "plant matter" to "vegetables" and changed the taste descript of soy sauce to  "soy".
🆑 Piccione
rscadd: Changed the taste message of a few food items
/:cl:
=> I changed the taste description of a few food items

code/game/objects/structures/crates_lockers/closets/secure/security.dm
Pretty self explanatory. The Tape Recorder is an useful tool for the detective, so i thought "why not".
🆑 Piccione
rscadd:Added Tape Recorder to Detective's Closet
/:cl:
=> Added a Tape Recorder and a box of tapes to the Detective's Locker

code/modules/admin/IsBanned.dm, code/modules/admin/topic.dm
I am keeping the typo tiger...
=> Obscure Admin Related fixes

code/datums/uplink_item.dm
Reverts ParadiseSS13/Paradise#8737
i pressed the wrong button
=> Revert ".357 nukie price fix"

code/_globalvars/lists/names.dm, code/game/objects/structures/bedsheet_bin.dm, code/game/objects/structures/stool_bed_chair_nest/alien_nests.dm, code/game/objects/structures/stool_bed_chair_nest/bed.dm, code/game/objects/structures/stool_bed_chair_nest/chairs.dm, code/modules/flufftext/Dreaming.dm, code/modules/mob/living/carbon/carbon_defines.dm, code/modules/mob/living/carbon/life.dm, config/names/dreams.txt, config/names/nightmares.txt
ports https://github.com/tgstation/tgstation/pull/29104
Dreams are slightly longer though given the diffrence in code bases i may need to adjust timeing.
bedsheets now contribute to what you can dream.
Adds nightmare texts and migrates the dream/nightmare streams to a txt file rather then a large string list.
Nightmares cuase shakeing and jittering, and can sometimes cuase hallucinations.
I am open to more dream texts or someone to tell me how/if i need to tweak timings or chances and to what.
:cl: Fethas
rscadd: Bedsheets can contribute to dream messages.
rscadd: sometimes dreams will be nightmares.
tweak: Moves dream/nightmare strings to txt files.
rscadd:sleeping has a small change to heal brute/fire. but you need a bed..and a bed sheet to be effective.
/:cl:
=> Byond the wall of sleep

code/game/machinery/computer/HolodeckControl.dm
fixes #8786 
or well should,tested in game on local did not hang
🆑 alexkar598
fix:examining holo plating will no longer hang the game
/🆑
=> Examining holo floors will no longer hang the game(or should no longer)

code/datums/action.dm
if you set use_itemicon to false it will insteed use the icon you supplied it with in its subtype
also removed a useless file i found
=> Allows item_action to not use the item icon by adding a var to let it not do so

code/modules/examine/examine.dm
Stat throttling doesn't actually accomplish anything.
https://github.com/tgstation/tgstation/pull/36357
=> Removes Stat Throttle

code/modules/mob/living/silicon/robot/emote.dm, code/modules/mob/living/silicon/robot/robot.dm
Quality of death: Power warning is on a 2 second cooldown.
:cl: Tayyyyyyy
tweak: Borg power warning is on a 2 second cooldown
/:cl:
=> Borg QOD improvements

code/hub.dm, code/world.dm
Inspired by a post from MSO.
Allows for control of byond listed status via world topic.
=> Migrate listing controls to byond

code/modules/events/spacevine.dm
Fixes: https://github.com/ParadiseSS13/Paradise/issues/8839
=> Fixes Unkillable Spacevines

code/modules/food_and_drinks/food/snacks.dm
=> Fixes cheese wheel typo

code/_globalvars/lists/reagents.dm, code/game/objects/items/weapons/defib.dm, code/modules/mob/living/silicon/silicon.dm, code/modules/reagents/chemistry/reagents/medicine.dm, code/modules/reagents/chemistry/recipes/pyrotechnics.dm
A couple of tweak requests and a fix:
- Nanocalcium added to blacklisted reagents, can no longer be synthesised by bees/Odysseus
- Silicon diagnostic HUD now gets correctly removed. Fixes #8785 
- Defibrillators not longer yield endless paddles
🆑 Birdtalon
tweak: Nanocalcium can no longer be synthesised by bees or Odysseus
fix: Silicons now have their diagnostic HUD removed correctly.
fix: Defibs no longer give endless paddles.
/🆑
=> Fixes and tweaks

_maps/map_files/cyberiad/cyberiad.dmm
🆑 Streaky's Pestering
add:A couple of timers were added to Brig.
/🆑
=> Adds Timers to Brig per request

code/controllers/subsystem/nightshift.dm, code/modules/security_levels/security levels.dm
=> Make sec levels avoid overwriting an admin-forced nightshift

code/ATMOSPHERICS/components/binary_devices/dp_vent_pump.dm, code/ATMOSPHERICS/components/binary_devices/passive_gate.dm, code/ATMOSPHERICS/components/binary_devices/pump.dm, code/ATMOSPHERICS/components/binary_devices/valve.dm, code/ATMOSPHERICS/components/binary_devices/volume_pump.dm, code/ATMOSPHERICS/components/trinary_devices/filter.dm, code/ATMOSPHERICS/components/trinary_devices/tvalve.dm, code/ATMOSPHERICS/components/unary_devices/outlet_injector.dm, code/ATMOSPHERICS/components/unary_devices/vent_pump.dm, code/ATMOSPHERICS/components/unary_devices/vent_scrubber.dm, code/__DEFINES/qdel.dm, code/controllers/subsystem/garbage.dm, code/game/machinery/adv_med.dm, code/game/machinery/alarm.dm, code/game/machinery/atmo_control.dm, code/game/machinery/buttons.dm, code/game/machinery/doors/airlock.dm, code/game/machinery/doors/airlock_control.dm, code/game/machinery/embedded_controller/embedded_controller_base.dm, code/game/machinery/lightswitch.dm, code/game/machinery/magnet.dm, code/game/objects/items/devices/radio/radio.dm, code/modules/assembly/signaler.dm, code/modules/logic/logic_base.dm, code/modules/pda/radio.dm, code/modules/power/singularity/emitter.dm
ports over: https://github.com/tgstation/tgstation/pull/36872
Also, in my testing, found out that body scanners weren't GC'ing. Made them do so.
Should also help pipes GC better.
=> Adds more GC Debugging

code/modules/mob/new_player/new_player.dm
Fixes a typo that is the first thing you see when you connect to the server. 
Originally introduced in #8754
=> Spelling is hard

code/defines/procs/admin.dm, code/modules/admin/verbs/adminhelp.dm
Fixes PM responses to players runtiming.
Before:
After:
=> Fix PM type being wrong

code/modules/client/preference/loadout/loadout_hat.dm
As per title.
🆑 
add: Kitty ears to loadout option under hat for 1 point
/🆑
=> Add kitty ears to load out

code/modules/reagents/chemistry/recipes/others.dm
Fixes plastic not being makeable 
fix: Fixes not being able to make plastic with reagents
/:cl:
=> Fixes Plastic Recipe

code/game/objects/items/weapons/storage/storage.dm, code/modules/mining/satchel_ore_boxdm.dm
No guarantees this will completely stop the problem, but it should help, as a stop-gap measure.
=> Emptying Stop-gap

code/game/response_team.dm
A small fix to prevent runtimes when admins dispatch an ERT.
=> Fixes ERT runtimes

code/game/mecha/mecha_topic.dm
This log down renaming of a Mech into game log so that inappropriate names can be caught. No CL as it is a backend change.
=> Log mech renaming

code/modules/mob/living/carbon/human/npcs.dm
:cl: Tayyyyyyy
fix: Pun pun is back!
/:cl:
=> Restore Pun Pun

code/__DEFINES/qdel.dm
I meant to remove this in the Timer SS PR.
Forgot to.
Oops.
=> Removes a Proc I Forgot To

code/modules/admin/IsBanned.dm
Self explanatory "The is a" changed to "This is a"
=> Fixes annoying typo in IsBanned.dm

code/datums/mind.dm, code/modules/mob/living/carbon/human/emote.dm, code/modules/modular_computers/file_system/programs/command/card.dm
Removes the last of the color macros.
Also there was an issue with being able to utilize the space movement of superfart if you had both toxic farts and superfarts. That's fixed.
fix: Fixes not being able to propel yourself through space by farting if you possessed both superfart and toxic farts
/:cl:
=> Removes the last of the color macros

code/game/machinery/doors/poddoor.dm
Continuation to #8669.
Fixes #8519.
:cl: Kyep and Bxil
fix: Prevents everyone and their mother from seeing through closed poddoors.
/:cl:
=> Poddoors, now with 14 times less commits

code/modules/admin/tickets/admintickets.dm, code/modules/admin/verbs/adminpm.dm
Fixes:
- PMs getting added to all stale tickets
- Mentorhelp PMs getting added to a user's adminhelp ticket
=> Fix ticket bleed

SQL/paradise_schema.sql, SQL/paradise_schema_prefixed.sql, SQL/updates/2-3.sql, code/__DEFINES/misc.dm, code/_globalvars/configuration.dm, code/game/world.dm, code/modules/mob/new_player/new_player.dm, config/example/tos.txt
Adds terms of service / privacy policy feature.
Mostly administrative.
=> Terms of service

code/datums/uplink_item.dm, code/modules/clothing/gloves/miscellaneous.dm
Fixes the description of the gloves of the north star.
It doesn't work with hulk anymore.
=> Fixes Gloves of the North Star's Description

code/modules/power/singularity/narsie.dm
Time to settle this debate once and for all.
=> Ports TG's Nar'Sie

code/datums/weather/weather_types/snow_storm.dm
Oops, I forgot to comment out the probability, so any z-level that has space...it snows on now.
fix: It no longer snows on away missions
/:cl:
=> Fixes Away Mission Weather

code/game/objects/items/weapons/weaponry.dm
Should now actually be able to see the status of how much it's charged up.
=> Fixes Home-Run Bat Charge

code/modules/mining/coins.dm
A quick fix, small but it fixes immersion ( from #9106  )
Removes: Old directory for coin string
Change: Changes directory for coin string to economy
=> coin string fix

code/game/objects/items/weapons/storage/boxes.dm, code/game/objects/structures/crates_lockers/closets/cardboardbox.dm
Fixes #9118
:cl:
fixes: Cardboard drop counts
/:cl:
=> Fix cardboard drop count

config/example/config.txt
Logging admin chat and mentor chat is an option in the code, but it wasn't anywhere in the configurations.
Oops.
=> Adds Admin Say Log Configuration

code/datums/spell.dm
This was merged in. Somehow it got reverted without so much as a trace.
=> Ragin' Mages Spell Cast Fix

.github/CONTRIBUTING.md, .github/SETTING_UP_GIT.md
This updates the CONTRIBUTING guidelines and adds a guide to using Git. 
Most of the CONTRIBUTING file has been stolen from /tg/'s and mildly adjusted for some of our extra rules. The git guide, I wrote myself!
=> Contributing guidelines update

code/modules/mob/living/silicon/ai/ai.dm, code/modules/mob/living/simple_animal/simple_animal.dm
=> Ais can no longer be on fire

code/game/objects/structures/signs.dm
Fixes #9096 
:cl:alexkar598
bugfix:You can no longer duplicate signs by doing input spam
/:cl:
=> Prevents sign duplication

code/game/objects/items/weapons/cards_ids.dm
RIP custom jon title
:cl:
fix: Spelling error in agent IDs
/:cl:
=> Fixes spelling error

code/modules/mob/living/carbon/brain/brain_item.dm, code/modules/surgery/organs/organ.dm, code/modules/surgery/organs/organ_internal.dm, code/modules/surgery/organs/subtypes/machine.dm, code/modules/surgery/organs/subtypes/standard.dm, code/modules/surgery/organs/subtypes/vox.dm
Heads are no longer vital, that said, brains most definitely still are.
Remove someone's head, with a brain inside, and they're still going to die though.
tweak: Heads are no longer vital organs, but brains still are
/:cl:
=> Heads No Longer Vital (Brains Still Are)

_maps/map_files/cyberiad/cyberiad.dmm
You know it was meant to be.
🆑 FreeStylaLT
add: Added a Harmonica to Perma Brig
/🆑
=> Adds a Harmonica to Perma Brig

code/modules/spacepods/equipment.dm
So this used to wait 2 seconds to apply in the cooldown,in that period you could fire the verb again i think,~~not sure~~YAY IM SMART IT WORKS
:cl:alexkar598
bugfix:Pods can no longer fire lasers at the speed of light.Pun intended.
/:cl:
Fixes #8934
=> Pods are no longer miniguns

code/datums/pipe_datums.dm
Whoops, not much to say here
:cl:
fix: volume pumps can be dispensed by the RPD again
/:cl:
=> adds volume pumps back to the RPD

code/datums/datumvars.dm, code/game/machinery/machinery.dm, code/game/objects/objs.dm
For evil bus purposes
It's in the VV menu
No CL since this is an admin-only change
=> Adds an admin VV button to make any object speed process

code/game/gamemodes/miniantags/bot_swarm/swarmer.dm
Redid the swarmers eating active clone pods things that was stale. Partly because I think it makes sense but MAINLY because I wanted to use the web editor. :^) Fite me
🆑alexkar598 and taukausanake
tweak: Swarmers can no longer destroy active clone pods.
/🆑
=> Reopen of #9162

code/modules/surgery/organs/mmi_holder.dm, code/modules/surgery/organs/subtypes/machine.dm
Fixes posibrains having incorrect names
fix: Extract posibrains should have the correct names now
/:cl:
=> Fixes Posibrains Having Incorrect Names

code/modules/surgery/robotics.dm
Fixes cybernetic customization surgery reprogram step not ending the surgery.
=> Fix Cybernetic Limb Custom Appearance Surgery

code/datums/supplypacks.dm
this really opened the lid for cargo's inflation
=> [s] Fixes the plastic crate exploit

code/modules/reagents/chemistry/reagents/pyrotechnic.dm
Fixes #9256
Corrects pyrosium description to say that it heats reagents, not cool them
=> Fixes pyrosium description

code/game/objects/items/random_items.dm
Why was this a while loop?
Seriously if someone has an answer, please.
:cl:
fix: Changed wannabe for loop to a real for loop.
/:cl:
=> Changes While Loop To For Loop

code/modules/arcade/arcade_prize.dm
Prize Balls weren't dropping more than one ticket at a time.
(also added another switch)
:cl:
fix: Claw Game Prize Ball now drops more than one ticket like it should.
/:cl:
=> Fixes Prize Ball Dropping Single Ticket

code/__HELPERS/text.dm, code/_onclick/hud/fullscreen.dm, code/datums/components/_component.dm, code/defines/procs/announce.dm, code/game/machinery/computer/communications.dm, code/modules/library/lib_items.dm, code/modules/modular_computers/file_system/programs/command/comms.dm, code/modules/paperwork/paper.dm, code/modules/power/supermatter/supermatter.dm, code/modules/research/rdmachines.dm
Refactor with minor-to-no code effects.
=> Cleans up useless syntax and macro redefinitions

code/modules/admin/admin.dm, code/modules/admin/admin_verbs.dm, code/modules/admin/topic.dm, code/modules/admin/verbs/randomverbs.dm
So..We already had reply via headset for like..faxes..this kinda make is a verb. And adds an option to speak from syndicate.
My brain is not smart enough right now to make it add other options to it. Its an admin verb. Open to suggestions and improvement.
...Fethas go sleep now yes?
=> Slight TG Headset Communication port

code/game/objects/items/toys.dm
Fixed issue #5167 
Added icon update function to cards.
Changed for loop to right format.
Removed katana class duplicate. (I didn't remove katana)
:cl:
fix: Fixed Therapy Dolls not working.
/:cl:
=> Fixed Therapy Doll Issue

code/modules/projectiles/guns/projectile/shotgun.dm
So due to a small error when I was taking code from Tiger, I forgot to add in the `/shotgun/riot` to make it only apply to the riot gun. 
This fixes #9335
=> Fixes sawing off

code/modules/reagents/chemistry/machinery/chem_master.dm
A check to see if the reagents datum actually contains any reagents before creating a pill.
🆑 Birdtalon
fix: Prevents creation of 0u pills with Chem Master
/🆑
=> Sanity check for pill creation (0u pills)

code/controllers/subsystem/air.dm
This is the most extensive code port i have ever done....
:cl:
tweak: Changes to air Subsystem to make it load faster taken from TG by SpaceManiac.
/:cl:
=> Ports TG Atmos SS tweak

_maps/map_files/RandomZLevels/centcomAway.dmm
This fixes a runtime caused by a non-existent path in the map.
No CL.
=> Fixes bad path runtime

code/datums/diseases/lycancoughy.dm
:cl:
tweak: Attemps to cap dogs you can cough up to 10..then you cough up a plush fox. Totally normal.
/:cl:
=> Limits Dogs from Lycancoughy virus

code/modules/admin/verbs/pray.dm
As per title. Fixes #9356 
🆑:
add: Logging for prayer.
/🆑
=> Add logging to prayer

code/modules/admin/topic.dm
=> fixes admin prison

code/game/objects/items/weapons/storage/storage.dm
fixes #9403 
It possibly fixes more issues, since this for sure happened on more than one occasion to me.
=> you can remove items from storage with forceMove() properly

code/modules/clothing/masks/gasmask.dm
I think the shitcode has been improved from a grade 6 level to a grade 7 level
Big thanks to everyone who helped
No actual changes in game, just code wise
🆑 
tweak: Decreases sechailer shitcode
/ 🆑
=> Makes sechailer have less of my shitcode

code/modules/mob/living/silicon/robot/robot.dm
This PR fixes the xeno borg so it both is able to be made, if you have a xeno brain, and so the icon works. 
This does not make xeno borgs useful though.
🆑 Shazbot
fix: Now you can actually make xeno borgs.
/🆑
=> Fixes xeno borg

code/modules/flufftext/Dreaming.dm
Fixes: #9498 
🆑 
fix: Nightmare writhing now properly works
/ 🆑
=> Fixes #9498

code/modules/arcade/arcade_base.dm
Fixes an error I made in the economy refactor in the claw game (removed the return value by accident).It should work properly now.
🆑:
fix: Claw game should give you token for payment by card properly again.
/🆑
=> Fixes claw game

code/modules/mob/new_player/new_player.dm
First thing people see when they connect is a typo. Ick.
=> Fixes minor mistake

code/datums/datumvars.dm, code/modules/mob/living/carbon/human/human_damage.dm
AdjustBruteLoss() & AdjustBurnLoss() now have the "robotic" parameter, allowing them to repair robotic limbs.
When called from the VV panel they will also heal robotic limbs.
Fixes #9517 
:cl:uc_guy
fix: It is now possible to heal robotic limbs and IPCs through View Variables
/:cl:
=> VV can now also fix robotic limbs.

code/game/gamemodes/malfunction/Malf_Modules.dm, code/modules/mob/living/silicon/ai/ai.dm
A quick bit of performance optimisation.
:cl: Purpose
tweak: CPU Performance tweaks in Malf AI
/ :cl:
=> Removes Sleeps/Spawns from Malf AI modules

code/modules/mob/living/carbon/alien/humanoid/caste/hunter.dm
minor performance improvements
:cl: Purpose
tweak: CPU Performance tweaks in the Xeno Hunter tackles
/:cl:
=> Refactors Xeno Hunter tackle spawn

code/game/turfs/simulated/floor/mineral.dm
minor performance improvements
:cl: Purpose
tweak: CPU Performance tweaks in the Bananaium floor honks & squeaks
/:cl:
=> Refactors the Bananium floors cooldown

code/game/objects/items/devices/autopsy.dm
Fixes #8903
:cl:uc_guy
fix: Autopsy scanner now prints all times in human readable format.
/:cl:
=> Autopsy scanner now prints all times in human readable format.

code/game/gamemodes/wizard/spellbook.dm
Laughter demon currently refunds 2 spell points, when it costs 1 point, this fixes that.
🆑 
Fix: Fixed an exploit letting wizards farm spellpoints.
\ 🆑
=> Fixes wizard refund glitch

code/game/machinery/pipe/pipe_dispenser.dm
minor performance improvements
:cl: Purpose
tweak: CPU Performance tweaks in the Pipe Dispenser
/:cl:
=> Refactors Pipe Dispenser's cooldown

code/game/gamemodes/miniantags/guardian/types/healer.dm
Depends on #9519. Do not merge before it!
Fixes #3814
EDIT: Alright, was able to test it. Works for me.
:cl:uc_guy
Support holoparas can now also heal IPCs and robotic limbs.
/:cl:
=> Support holoparas can now also heal IPCs and robotic limbs.

code/game/machinery/camera/camera_assembly.dm
Just refactoring - no change log required.
=> Tidies up camera_assembly.dm

code/modules/recycling/disposal.dm
Fixes #5923
Floortile thrown with you is now the tile that was on the floor. Not some random ass broken tile.
You're able to place the tile back again no problem.
Code I removed made the tile unusable and made the plating act weird.
🆑 Farie82
fix: No more broken tile due to getting shot out of disposals.
/🆑
=> Fixes #5923

code/modules/vehicle/ambulance.dm
Big thanks to everyone who helped me with this
It uses the same sound as the justice helmet
Top left to toggle on/off along with the red emergency light
🆑 
add: Ambulances now have sirens!
/ 🆑
=> Adds a siren to the Ambulance

.github/PULL_REQUEST_TEMPLATE.md
A template is now provided for PRs, which includes what the PR is, why it should be merged, a section for images (If applicable), and an example changelog for those who dont know how to format it. The template itself is below.
_________________________________________________
**What does this PR tweak:**
Include a small description of what your PR changes
**Why is this better:**
This is your reasoning for why the PR should be merged
**Images of sprite/map changes (IF APPLICABLE):**
If you did not make a map or sprite edit, you may leave this section blank. You may include a gif of your feature if you want
**Changelog:**
// THIS HAS BEEN REMOVED FROM THE PR DESCRIPTION TO AVOID THE IN GAME CHANGELOG GOING NUTS //
_________________________________________________
=> Adds a PR template

code/game/gamemodes/gameticker.dm, code/modules/admin/verbs/randomverbs.dm
I can't believe I forgot about this.
🆑:
fix: Not spawning in with your memory of bank account at roundstart...
/🆑
=> Stop you from losing your memory and money at roundstart

code/modules/client/client procs.dm, code/modules/karma/karma.dm
As title says.
Added new procs to reduce repeated code, replaced booleans with TRUE/FALSE.
If anything seems wrong, please tell me, I'm still learning these things!
:cl:
refactor: Reduced repeated code in karma system.
/:cl:
=> Karma Cleanup

code/controllers/configuration.dm, config/example/config.txt, interface/interface.dm, interface/skin.dmf
Adds the discord button in discord colors
Makes the karma shop in bold
Makes the donate button green, and bold
It's easier to read with them bolded, I think at least.
=> Adds a Discord button & stylizes the Karma Shop and Donate buttons

TGS3.json
This PR adds the configuration JSON for use with the /TG/Station Server Suite
https://github.com/tgstation/tgstation-server/releases
**Images of sprite/map changes (IF APPLICABLE):**
N/A
**Changelog:**
No CL as this has no impact on the game at all
=> Adds support for TGS3

code/__HELPERS/game.dm
:cl: Purpose
tweak: CPU Performance in get_area proc
/:cl:
=> Speeds up get_area

_maps/map_files/RandomZLevels/academy.dmm
:cl: Purpose
tweak: Wizard Academy now uses decals
fix: Wizard Academy misplaced wires fixed
/:cl:
=> Fixes mapping inconsistencies & updates Academy.dmm to using decals

code/modules/arcade/claw_game.dm, code/modules/arcade/crane.html, code/modules/arcade/page.css
Makes the claw game open in the correct size, auto-close on win, makes the close button actually close, and changes so when the claw has firm hold of prize, it counts as a win in case your game is interrupted it will still drop the prize. Also _"centered"_ buttons.
:cl:
fix: Claw Game is now a bit easier to use. Slower speeds, still receive prize when interrupted, and auto-close.
fix: Claw Game has correct window size, centered buttons, general code cleanup.
/:cl:
=> Claw Game Refactor

code/game/gamemodes/wizard/soulstone.dm
Fixes a small oversight in formatting in soulstone.dm.
Fixes #9666
🆑 Birdtalon
fix: Small formatting fix in soulstone.dm
/🆑
=> Small formatting oversight fix.

goon/browserassets/js/browserOutput.js
This fixes 2399401 - More commonly known as the flavor text examine bug.
https://secure.byond.com/forum/?post=2399401
Closes #9533 
There's no need to sanitize that with this in place.
^ This would have previously displayed nothing after triggering both messages, because the entire message would be deemed "corrupted".
:cl:
fix: Chat no longer horribly breaks at the first high-ascii character.
/:cl:
=> Fix BYOND Bug 2399401

code/game/machinery/OpTable.dm
fixes #9237 
Just closes the inventory. Should work. 
:cl: Farie82
fix: Your hands won't become the surgeons hands anymore in surgery
/:cl:
=> Fixed the inventory bug

code/game/turfs/simulated/floor/plating.dm
Fixes #9688
:cl: Purpose
fix: Damaged plating when fixed, now loses the aesthetic damage too.
/:cl:
=> Fixes damaged plating not being visually fixed after welding

code/modules/projectiles/guns/medbeam.dm
Another personal request from the admin team...
=> [s] Nukie exploit fixed

code/game/objects/effects/decals/Cleanable/aliens.dm, code/game/objects/effects/decals/Cleanable/fuel.dm, code/game/objects/effects/decals/Cleanable/humans.dm, code/game/objects/effects/decals/Cleanable/misc.dm, code/game/objects/effects/decals/Cleanable/robots.dm, code/game/objects/effects/decals/Cleanable/tracks.dm, code/game/objects/effects/decals/cleanable.dm, code/game/objects/effects/decals/crayon.dm, code/game/objects/effects/decals/misc.dm, code/game/objects/effects/decals/remains.dm, code/game/objects/effects/decals/warning_stripes.dm
Mostly just tidying up, and code improvements... but have moved the decals into Initialize as well.
:cl: Purpose
tweak: Decals now Initialize()
/:cl:
=> Refactors decals

code/modules/food_and_drinks/food/snacks.dm
Fixes #8842 
You can cut sliceable with any sharp item. Only scalpel and kitchen knife will do it accurately like before.
Alt-click is now used to put items inside sliceable. This means hiding small sharp object is now possible. Some refactoring has been done on the code too.
🆑:
add: All sharp items can cut sliceables like cheesewheel now.
tweak: Putting items inside sliceables is done by alt-click now.
/🆑
=> Allow you to slice sliceables with any sharp item & alt-click to hide item

_maps/map_files/RandomRuins/SpaceRuins/asteroid4.dmm
:cl: Purpose
fix: Fixes improper turf in the shuttle crashed into one of the space ruins.
/:cl:
=> Fixes Asteroid 4 Turf

_maps/map_files/RandomRuins/SpaceRuins/gasthelizards.dmm
:cl: Purpose
tweak: GasTheLizard Space Ruin now uses Decals properly.
/:cl:
=> Updates Decals on Gas The Lizards Space Ruin

_maps/map_files/RandomRuins/SpaceRuins/onehalf.dmm
:cl: Purpose
tweak: OneHalf Space Ruin now uses Decals properly.
/:cl:
=> Updates Decals on OneHalf Space Ruin

_maps/map_files/RandomRuins/SpaceRuins/spacebar.dmm
This could really do with a proper re-map, as this is a properly poorly done ruin....
But, I've fixed missing turfs under the shuttle, I've updated it to using decals.... and also fixed the pod door button to not appear on both sides of the wall....
:cl: Purpose
fix: Fixing improper decals & missing turfs in the Space Bar space ruin, and some tiny fixes.
/:cl:
=> Updates Spacebar.dmm Space Ruin

_maps/map_files/RandomZLevels/evil_santa.dmm
:cl: Purpose
tweak: Evil Santa Away Mission now uses Decals properly.
/:cl:
=> Updates Decals on Evil Santa Away Mission

interface/skin.dmf
As requested in Discord... your wish is my command....
First one is the old one, second is the new.
:cl: Purpose
tweak: Prettier Donate/Karma buttons!
/:cl:
=> Improved buttons

code/game/world.dm
Fixes: #9762
🆑 
fix: Fixes runtime in world.dm;127
/ 🆑
=> Fixes #9762

_maps/test_all_maps.dm
This was missing like 3-4 things.... so I've also put it alphabetically to be more obvious if it happens again.
When this merges, if we haven't fixed the Battle problems.... this'll error all Travis Checks.
:cl: Purpose
fix: TravisCI now checks all space ruins & away missions for integration.
/:cl:
=> Updates Travis to check ALL the Space Ruins & Away Missions

code/game/objects/items/weapons/stunbaton.dm
For @KasparoVy 
:cl: Purpose
add: Thrown stunbatons & improvised batons have a low chance to stun.
/:cl:
=> Thrown Stunbatons have a low chance to stun

code/modules/mob/dead/observer/observer.dm, code/modules/mob/living/carbon/alien/alien_defense.dm, code/modules/mob/living/carbon/carbon.dm, code/modules/mob/living/simple_animal/posessed_object.dm, code/modules/surgery/other.dm
Updates resting vars to use StopResting(), StartResting() as per Ansari
Fixes #9769 
🆑 Ansari, Birdtalon
fix: Updates resting procs, fixes getting people up from help intent.
/🆑
=> Help intent resting bugfix

code/modules/mob/living/silicon/pai/recruit.dm
Fixes: #9784 
🆑 
fix: Fixes PAIs
/ 🆑
=> Fixes PAIs

code/modules/scripting/Implementations/Telecomms.dm
As per title.
No CL, purely backend.
=> [s] Fixes a way to circumvent banned HTML tag check

code/modules/martial_arts/brawling.dm
Moves boxing logs to the `attack log all` preference
🆑 
tweak: Boxing logs moved to the ALL preference 
/ 🆑
=> Moves Boxing logs to the ALL preference

code/modules/mob/living/carbon/human/death.dm
Fixes #7783
:cl: Purpose
fix: Fixes a gibbing runtime
/:cl:
=> Fixes gib runtime

code/game/objects/items/weapons/stunbaton.dm
Fixes stunbaton runtime
https://i.imgur.com/oGnmcWd.png
🆑 
fix: Fixes stunbaton runtime (Stun() being called on a turf)
/ 🆑
=> Fixes stunbaton runtime

nano/templates/autolathe.tmpl
Fix for issue #9865
:cl: Certhic
fix for small display bug when queuing a stack in the autolathe
/:cl:
=> autolathe queue display fix

code/modules/mob/living/silicon/pai/recruit.dm
Prevents people from downloading pAI's while dead.
**Changelog:**
:cl: craftxbox
fix: added check to make sure person downloading pAI isnt dead.
/:cl:
first commit, first pr and first foray into DM. please let me know how i did.
Fixes #9855
=> add check to make sure person downloading pAI isnt dead.

nano/templates/safe.tmpl
The last PR missed the final UI update.
**Changelog:**
:cl: Warior4356
fix: Final UI update was missed in Safe Refactor PR
/:cl:
=> UI was missed in commit

code/game/gamemodes/miniantags/revenant/revenant.dm
This refactor the revenant code a little bit so that the proc for giving them objectives and text is separate from New(). It also make admin-bused revenant have a better chance of getting proper objectives and goal.
**Changelog:**
🆑:
tweak: Minor refactor of revenant code.
/:cl:
=> Improve revenant code a bit

.travis.yml
512 512 512 512 512 512
👏 👏 🎆 🔥 🍾 🌳 
:cl:
add: We're going 512 boisssssssssssssss
/:cl:
=> Making the jump to 512 time bois

code/game/gamemodes/revolution/revolution.dm
Code improvement
:cl: Purpose
tweak: Code improvement with timers in Revolution gamemode.
/:cl:
=> Removes a revolution spawn

code/game/objects/items/weapons/tools.dm
:cl:
fix: welders will now fix external IPC leaking. My Bad.
/:cl:
=> IPC HOTFIX:Welders fix external bleeding

code/game/mecha/mecha.dm, code/game/objects/obj_defense.dm, code/modules/mob/living/living_defense.dm, code/modules/mob/living/silicon/pai/pai.dm, code/modules/spacepods/spacepod.dm
Fixes simple animals attacking while they were on help intent. Also fixes punctuation. 
**Changelog:**
:cl: Certhic
fix: Fixes simple animals attacking while they were on help intent.
/:cl:
=> fixes animals attacking while on help intent

README.md
Nothing aside from a CL, since the catgirl revert PR didnt have one
**Changelog:**
del: Removed catgirls, be gone foul beasts
/:cl:
=> CL for the catgirl removal

code/modules/mob/living/silicon/robot/examine.dm
Fixes #8028 
**Changelog:**
:cl: uc_guy
add: You can now tell if a borg has suicided by examining them
/:cl:
=> Added borg suicide examine message.

code/modules/mob/pulling.dm
Fixes: https://github.com/ParadiseSS13/Paradise/issues/9848
Fixes being able to pull when incapacitated.
**Changelog:**
:cl: Dovydas12345
fix: Fixed being able to pull when incapacitated
/:cl:
=> Fixes being able to pull when incapacitated

code/modules/mob/living/carbon/carbon_defense.dm
Fixes https://github.com/ParadiseSS13/Paradise/issues/7606 (Probably others too)
Makes it impossible to catch two handed items with one hand.
**Changelog:**
:cl: Dovydas12345
fix: Fixes catching two handed items with one hand.
/:cl:
=> Fixes catching two handed items with one hand

code/modules/mob/pulling.dm
Fixes reversed logic in #10018
🆑 
fix: Pulling fixed
/ 🆑
=> Fixes pulling

code/modules/mob/living/simple_animal/hostile/hostile.dm
Fixes hostile mobs "nuzzling" people instead of attacking from #10007 
🆑 
fix: Hostile mobs attack again instead of nuzzle
/ 🆑
=> Hostile mob fix

code/game/mecha/mecha.dm, code/game/objects/obj_defense.dm, code/modules/mob/living/living_defense.dm, code/modules/mob/living/silicon/pai/pai.dm, code/modules/mob/living/simple_animal/hostile/hostile.dm, code/modules/spacepods/spacepod.dm
As requested by @variableundefined and @tigercat2000 
Fixes hostile mobs in a better way than #10026
Reverts: #10026 
🆑 
tweak: Better way of fixing hostile mobs not attacking
/ 🆑
=> Hostile mob fix V2

code/datums/supplypacks.dm
Cargo can now buy ~~IPC blood~~ an oil tank with a oil can.
**Changelog:**
:cl: Farie82
add: Cargo can now buy oil tanks.
/:cl:
=> Gives cargo the ability to buy an Oil tank.

code/game/objects/structures.dm, code/game/objects/structures/tables_racks.dm
Fixes #8084
**Changelog:**
:cl: uc_guy
fix: You can no longer table people through walls/doors/shutters.
/:cl:
=> Fixed tabling through solid objects.

code/modules/recycling/disposal.dm
On the tin. I thought I got all of these but it turns out there is another slightly convoluted way to achieve this. Tested in-game, seems to work fine / nothing appears to have been broken by this.
Also rewrites a little bit of the disposals code to be a little nicer to read.
No CL as I doubt many players have come across this bug.
🆑:
fix: A disposal nullspace bug.
/🆑
=> Kills another disposals nullspace bug

code/modules/clothing/gloves/miscellaneous.dm
Fixes #10081 by adding attack log to stun gloves
**Changelog:**
:cl: 
add: Attack log to stun gloves
/:cl:
=> Add attack log to stun gloves

code/__HELPERS/mobs.dm, code/datums/datacore.dm, code/game/machinery/computer/security.dm, code/modules/mob/living/carbon/human/human.dm
Initializes the security comments when creating the records. 
Also made a helper to set the arrest. Since fuck I hate double code.
fixes: #10080
**Changelog:**
:cl: Farie82
fix: Security comments now work again. Sec hud arrests will now function as intended.
/:cl:
=> Initializes the security comments on creation of the records + made a set criminal status helper

.github/CONTRIBUTING.md
As per title
**Changelog:**
:cl:
add: Tigercat2000 & variableundefined (Ansari) to the maintainer list.
/:cl:
=> Add Tigercat and Ansari (variableundefined) to maintainer list

code/game/gamemodes/changeling/powers/mutations.dm
Add attack logs to everything that the changeling tentacle does.
Fixes #10068
**Changelog:**
:cl: Regen
fix: The tentacle changeling power now generates admin logs.
/:cl:
=> Adds admin logs to changeling tentacle arm

code/modules/surgery/organs/blood.dm
fixes #10020
**Changelog:**
:cl: uc_guy
fix: IPCs and slimes now have an effect on the floor when bleeding.
/:cl:
=> Fixes exotic blood not working.

code/modules/pda/cart.dm
This fixes #6915
**Changelog:**
:cl: 
fix: added mulebot control to captain's PDA again.
/:cl:
=> Added mulebot control to captain's pda again

code/game/jobs/job/job.dm
This is really, really stupid.
:cl:
tweak: Captain and HoS can be nearsighted again.
/:cl:
=> Remove nearsighted restriction from HoS and Captain

goon/browserassets/js/browserOutput.js
=> [s]fix goonchat cookies

code/modules/hydroponics/grown.dm
Fixes: https://github.com/ParadiseSS13/Paradise/issues/10150
Allows to slice certain food grown by hydroponics (pineapple, watermelon etc.)
**Changelog:**
:cl: Dovydas12345
fix: Fixes being unable to slice certain food grown by hydroponics (pineapple, watermelon etc.)
/:cl:
=> Allows grown food to be sliced

code/game/jobs/job_exp.dm
A verb to check one's own playtime on the server. If it requires fix tokens I can quote them.
🆑 Birdtalon
add: Verb to check your own playtime.
/🆑
=> Adds a verb to check one's own playtime.

code/game/jobs/job_exp.dm
Fixes a couple of silly mistakes with #10201 
- Missing ' in span declaration causing it not to display correctly..
- Checking against wrong config flag.
🆑 Birdtalon
fix: Fixes playtime self checker.
/🆑
=> Fixes a couple of silly mistakes in #10201

code/game/objects/items/weapons/cigs.dm
Fixes #10140
**Changelog:**
:cl: Certhic
fix: fixed a cigs runtime error
/:cl:
=> cig runtime fix

code/game/objects/items/weapons/holy_weapons.dm
Fixes #10099
Vampires are now also affected by the passive effect of the prayer beads.
**Changelog:**
:cl: uc_guy
fix: Fixed the passive effects of prayer beads and prayer bread.
/:cl:
=> Fixes the passive effects of prayer beads and prayer bread.

code/ATMOSPHERICS/components/binary_devices/dp_vent_pump.dm, code/ATMOSPHERICS/components/binary_devices/valve.dm, code/ATMOSPHERICS/components/unary_devices/outlet_injector.dm, code/ATMOSPHERICS/components/unary_devices/vent_pump.dm, code/ATMOSPHERICS/components/unary_devices/vent_scrubber.dm, code/controllers/communications.dm, code/game/machinery/alarm.dm, code/game/machinery/atmo_control.dm, code/game/machinery/computer/communications.dm, code/game/machinery/doors/airlock_control.dm, code/game/machinery/doors/alarmlock.dm, code/game/machinery/magnet.dm, code/game/machinery/status_display.dm, code/game/objects/items/devices/radio/electropack.dm, code/game/objects/items/devices/radio/intercom.dm, code/modules/assembly/signaler.dm, code/modules/atmos_automation/console.dm, code/modules/modular_computers/file_system/programs/command/comms.dm, code/modules/pda/cart_apps.dm, code/modules/pda/radio.dm, code/modules/power/singularity/emitter.dm, code/modules/shuttle/supply.dm
Replaces radio freq magic numbers with constants
:cl:
tweak: Replaces radio freq magic numbers with constants
/:cl:
=> refactor radio magic numbers

code/modules/mob/living/carbon/human/human.dm
fixes being able to set sec/medhud statuses, add sec/medhud comments, view sec/medhud comments or add sec/medhud records
:cl: craftxbox
fix: add observer/incapacitated check for all sec/medhud actions
/:cl:
Fixes #10250
=> make sure they arent dead when trying to use hud stuff

code/game/objects/items/devices/radio/encryptionkey.dm
Fixes #10285 
**Changelog:**
:cl: name here
fix: Fixed a runtime in a syndieteam radio.
/:cl:
=> Fixed a runtime in syndieteam radio.

_maps/map_files/cyberiad/cyberiad.dmm
What it says on the tin (can...)
Fixes #10348 
:cl:
add: Adds the rubbish bin in front of the kitchen again
/:cl:
=> Adds the rubbish bin to the kitchen again

code/modules/research/designs/mechfabricator_designs.dm
Dunno how but the way to create it never had a build path....
Now it does
**Changelog:**
:cl: Farie82
fix: You can now actually make the rescue jaws
/:cl:
=> fixed the rescue jaw not spawning... whomstve really?

code/modules/food_and_drinks/kitchen_machinery/gibber.dm
fixes #10372 (and cleaned up some minor things while I was there)
**Changelog:**
:cl: 
fix: No more making infinite meat and crashing the server with gibbers
/:cl:
=> Fixes gamebreaking gibber bug

code/game/dna/genes/powers.dm
Fixes an exploit where you become 1 pixel sized.
**Changelog:**
:cl: Farie82
fix: Can't become 1 pixel big anymore due to genetics
/:cl:
=> You're made smaller/bigger now upon activation/deactivation

code/game/machinery/dance_machine.dm
Fixes #10388
:cl:
fix: Fixes a runtime caused by AIs watching dance machines
/:cl:
=> Fixes runtime in dance machines caused by AIs

code/modules/mob/living/silicon/ai/ai.dm, code/modules/mob/living/silicon/pai/recruit.dm, code/modules/nano/modules/law_manager.dm
:cl: Kyep
fix: Fixed a few things that should not be possible with pAIs and AIs.
/:cl:
=> [s] pAI and AI fixes

code/_globalvars/misc.dm, code/modules/paperwork/photocopier.dm
🆑
fix: Added a global cap on printing papers.
/🆑
=> Add global cap on printing papers

code/__DEFINES/gamemode.dm, code/game/machinery/wishgranter.dm, code/modules/mob/living/carbon/superheroes.dm
Re-adds superheroes to wishgranters in a subtype
🆑 
add:Re-adds superhero wishgranters
/ 🆑
=> Re-adds superheroes

code/game/gamemodes/miniantags/guardian/guardian.dm
Movemen
:cl:
fix: fixed a typo
/:cl:
=> Fixes litteraly my immersion

code/datums/spell.dm
fixes #10499
🆑 
fix: Fixes "makes frantic gestures" invalid emote with mute people using spells
/ 🆑
=> Fixes frantic gesture emote

code/game/objects/items/weapons/storage/toolbox.dm, code/modules/crafting/recipes.dm
Adds a recipe, that allows you to paint  a toolbox and turn it into a syndiecate toolbox, known as well "suspicous toolbox"  its not contrabrand i know, its just a cool toolboxx honestly and i hate they are super rare n stuff, and you easily be tell the difference by examining it
:cl:
add: Adds a recipe for the toolbox to make it a suspicous toolbox
/:cl:
=> Adds a recipe, that allows making syndicate toolboxes

code/modules/mob/living/simple_animal/friendly/mouse.dm
Allows mice to *squeak using squeak sound.
:cl:
add: Mice can *squeak now.
/:cl:
=> Gives Mice *squeak Emote

code/game/gamemodes/miniantags/slaughter/slaughter.dm, code/modules/events/tear_honk.dm
:cl:
bugfix: Fixes Slaughter demons not releaseing corpses on death.
bugfix: Fixes tears in spacetime just kinda sitting there.
/:cl:
=> Fixes Tears and Demons

code/modules/clothing/spacesuits/chronosuit.dm
Title
**Changelog:**
:cl:
del: Removed a useless comment in chronosuit code.
/:cl:
=> Removes a random multi-line comment from the chronosuit

code/controllers/subsystem/tickets.dm
fixes: #10329 
**Changelog:**
:cl:
fix: Fixes the runtime in admin tickets
/:cl:
=> Fixes the runtime in admin tickets handling when the client left

code/modules/mining/equipment_locker.dm, code/modules/mob/living/simple_animal/hostile/mining_mobs.dm
:cl:
add: Now lazarus injector displays a message when emaggin
:cl:
=> Lazarus injector now display message when emagged

code/modules/mining/equipment_locker.dm, code/modules/mob/living/simple_animal/hostile/mining_mobs.dm
Same with RIPLEY APLU, being able to upgrade it to improve its armor
FIXED: Useless lines of codes removed
:cl:
Add: Firefighters can now be reinforced with goliath plates
:cl:
=> Added to upgrade FireFighters with goliath plates

code/__HELPERS/global_lists.dm, code/game/objects/effects/snowcloud.dm, code/game/objects/structures/statues.dm, code/modules/crafting/recipes.dm, code/modules/holiday/christmas.dm
This PR adds a crafting recipe for snowmen. This recipe only appears during Christmas and is as follows: 10 snowballs, 1 carrot, and 2 logs. It takes 10 seconds to build one snowman.
Built snowmen have 50 health, they melt if exposed to fire, and can be repaired using a snowball. When destroyed they drop the carrot and logs used.
Also removes some commented-out code from `statues.dm`
:cl:
add: You can now build snowmen out of 10 snowballs, 2 logs, and a carrot.
/:cl:
=> Do you wanna build a snowmaaaaaaaan~

code/game/gamemodes/game_mode.dm, code/game/gamemodes/traitor/traitor.dm
~~REMOVE COLLAB remove collab you are the worst mechanic you are the self-antag smell to our server you may not go~~
Remove syndicate collaborators, as requested by PurpleGenie.
🆑
Delete: Removed syndicate collaborators.
/🆑
=> Remove collaborators

code/modules/surgery/organs/lungs.dm
While working on upping the oxygen damage to Vox I have discovered that toxic gases do a laughable amount of damage. For example you could stay in 25% plasma atmosphere indefinitely and survive by vomiting alone.
This PR increases the toxicity of the gases by a factor of 10.
It also ups the damage Vox take from oxygen, bringing the oxygen toxicity in line with the toxicity of plasma.
A vox will fall into hard crit in about 2 minutes and 20 seconds in the normal atmosphere.
**Changelog:**
:cl: uc_guy
balance: Toxic gases now do more damage.
balance: Vox take higher damage from oxygen.
/:cl:
=> Increases gas toxicity across the board.

code/modules/mob/living/carbon/human/say.dm
^^^ 
🆑
Fix: Fixed grey translator translating the entire server.
/🆑
=> Fix grey translator translating the entire server

code/modules/assembly/voice.dm
That does nothing else but fix this specific obscure typo.
=> a completely inconspicuous PR

code/game/area/Space Station 13 areas.dm, code/game/machinery/computer/arcade.dm, code/game/machinery/constructable_frame.dm, code/game/machinery/doors/poddoor.dm, code/game/machinery/recharger.dm, code/game/objects/items/devices/flashlight.dm, code/game/objects/items/shooting_range.dm, code/game/objects/items/weapons/weaponry.dm, code/modules/power/singularity/generator.dm
Normalizes a few paths in nine different source files.
**Changelog:**
:cl:
fix: Normalized some paths in the code tree
/:cl:
=> Some path normalization

code/modules/customitems/item_defines.dm
Description was cut halfway
🆑
fix: Fixed bluespace bunny ears fluff item description
/🆑
=> Fix bluespace bunny ears fluff desc

code/modules/mob/living/carbon/human/species/abductor.dm, code/modules/surgery/organs/subtypes/abductor.dm
No balance change, just make it look like grey brains.
🆑
tweak:Abductor brains now look alien.
/🆑
=> Changes abductor brains to use the alien brain sprite

goon/browserassets/js/browserOutput.js
Added a notification about the chat reconnecting after dark chat mode has been toggled. 
**Changelog:**
:cl:
add: Added a notification about the chat reconnecting on toggling of the dark chat mode. 
/:cl:
=> Dark Mode Chat - Notification added. 

SQL/paradise_schema.sql, SQL/paradise_schema_prefixed.sql, SQL/updates/4-5.sql, code/__DEFINES/misc.dm, code/modules/discord/accountlink.dm, code/modules/discord/notify.dm, code/modules/ext_scripts/irc.dm, config/example/dbconfig.txt, paradise.dme
Since the loss of CyberiadAI, we have not had a round notify system. This PR fixes that and also adds discord account linking to the game
Linking Discord Account:
*The bitly link links to a page on the Discord help centre of how to get IDs.*
https://bit.ly/2AfUu40
*Ignore the error line, thats because I cancelled it*
If you press the link button when you already have an account linked, you will get this popup:
Pressing unlink does this:
It also removes the row from the DB
Pressing update simply re-runs the store code, but with `UPDATE` instead of `INSERT`
The notify verb will toggle between the two states when click
At roundstart, the code that notifies the webhook of server starting will ping everyone who has requested notify on the server. It will also set …
=> Discord linking and roundstart notifications!

code/controllers/configuration.dm, code/controllers/master.dm, config/example/config.txt
Reverts ParadiseSS13/Paradise#10781
AAAAAAAAAAAAA
Anyways, breaks server, no subsystems start, not sure why, but will need some testing.
=> Revert "Added a configuration option for disabling subsystems by name"

code/_globalvars/lists/reagents.dm
Title. I think this should be done to be consistent?
:cl:
tweak: Adds jestosterone to the list of standard reagents, not sure if this has any in-game effect.
/:cl:
=> Adds jestosterone to standard reagents list

code/game/jobs/job/support_chaplain.dm
Removes the special case for homosexuality and some shitty ones.
Choosing this will get you bwoinked anyway so why encourage it with a special name?
**Changelog:**
:cl:
del: Removes some of the chaplain special religion names
/:cl:
=> Removes some special cases for the chaplains religion

code/modules/discord/accountlink.dm
Trying to prevent misunderstanding on what exactly the "ID" is, in this case.
**Changelog:**
:cl: Alonefromhell & AffectedArc07
tweak: Tweaked the discord link alert text slightly.
/:cl:
=> Update to discord link alert text

code/modules/reagents/chemistry/reagents/toxins.dm
I forgot to commit this to the mutgen PR. OOps
fix: Fixes edge case mutagen behavior
/:cl:
=> Mutagen Fix

code/modules/mob/living/simple_animal/bot/secbot.dm
Beepsky now can't insta cuff you when you run away and get back close to him.
fixes: #10906 
**Changelog:**
:cl:
fix: Beepsky now can't insta cuff you when you run away and get back close to him.
/:cl:
=> Beepsky now uses do after

code/game/objects/items/weapons/dna_injector.dm
Genetics has been broken for quite a while now.
Diona have been able to acquire mutations they shouldn't (speed increase and the self radiation block, for instance).
Additionally, DNA injectors would, guaranteed, activate powers on their user. 
This most definitely isn't intended; it was caused by a fix here: https://github.com/ParadiseSS13/Paradise/pull/5896
pre-spawned injectors now have a `forcedmutation` var that guarantees they will always activate the powers they have; that said, injectors made on station will retain their probability to activate.
fix: Fixes genetic powers always activating when injected
fix: Fixes Diona being able to be speedy and irradiate themselves with genetic powers
/:cl:
=> Fixes Genetic Powers Activation

code/game/objects/items/stacks/stack.dm
Friggin' darn crappy stack code. DIE.
fixes: https://github.com/ParadiseSS13/Paradise/issues/10979
fixes: https://github.com/ParadiseSS13/Paradise/issues/10984
fix: Hopefully fixes weird stack issues. Maybe. Who knows. The World can burn.
/:cl:
=> The World Can Burn For All I Care

.github/CONTRIBUTING.md
He's gone, boys. Gone forever.
=> Dethrones Tigercat

appveyor.yml, tools/appveyor/build.ps1, tools/appveyor/deploy.sh
This PR adds compatibility for Appveyor CI. Now I know what youre saying, and yes I know we already have Travis. But Appveyor has something useful. Artefacts. Appveyor will build the current PR, and provide a zipped download to the compiled code to allow for testing. I havnt *fully* cut down on what files we dont need yet, but that will come soon (Its 00:20 AM).
No CL because this doesnt even change the game code
=> Appveyor CI

code/__HELPERS/_logging.dm, code/_globalvars/logging.dm, code/game/world.dm, code/modules/client/asset_cache.dm
this is a port of https://github.com/tgstation/tgstation/pull/43089 its not even merged over there. I am just so stuck on my crusade on our own RSC file issues i think i am just screaming DEUS VULT! now.
Anyway logging of assets to check for user incompatibility. Plus we get to see if any of our own assets kinda get stuck in a pattern.
=> Asset logging

code/game/objects/items/weapons/defib.dm
Adds a line informing newer players that you can ctrl click to remove the paddles from a defibrillator
Requested by ansari in #coder-chat of discord
**Changelog:**
:cl:
add: Added a new line to the defib examine text
/:cl:
=> Defibrillator QoL

code/modules/admin/admin.dm
Adds a confirmation alert to the "start now" verb.
**Changelog:**
:cl:
tweak: Adds a confirmation to the start now verb. Make it ansari proof
/:cl:
=> Add a confirmation to start the round

code/LINDA/LINDA_turf_tile.dm
Fucked up the logic. Here's the fix
**Changelog:**
:cl:
fix: Fixes the atmos bug
/:cl:
=> Fixes my mistake in the dview pr

code/modules/mob/living/carbon/human/human_organs.dm
**Changelog:**
:cl:
fix: no more organ: spam sorry admins
/:cl:
=> Removes the debug line

code/modules/events/sentience.dm, code/modules/research/xenobiology/xenobiology.dm
This makes it so that upon becoming sentient, either by the xenobiology sentience/transference potion or by the random sentience event, it becomes possible to put a collar on you.
**Changelog:**
:cl: EmanTheAlmighty
tweak: It is now possible to put a collar on any animal that has gained sentience.
/:cl:
=> Can now put a collar any animal that has gained sentience.

code/datums/diseases/gbs.dm, code/modules/mob/living/death.dm, code/modules/mob/living/living.dm, code/modules/reagents/chemistry/reagents/medicine.dm, code/modules/reagents/chemistry/reagents/toxins.dm
When you OD on Venom, you fall over, are weakened, and convulse violent until you eventually gib.
This is a specialized bit of code that is only here, but I went ahead and made the code more general where it can be utilized in other spots. 
This new proc will be utilized for Venom, Strange Reagent, and GBS.
Also refactored the `do_jitter_animation` so you could make it loop as many times you want.
add: Mobs that are gibbed with strange reagent and GBS have a bit more of a dramatic flare to them with violent convulsions before exploding into tiny bits
/:cl:
=> Makes Delayed Gibbing a Proc

code/modules/mob/living/silicon/ai/ai.dm
Fixes the toggle floor bolts option, which allows the AI to anchor and unachor itself properly, which allows the AI core to be pulled again.
**Changelog:**
:cl:
fix: Fixes AI's toggle floor bolts ability
/:cl:
=> Fixes AI's ability to toggle floor bolts

code/__HELPERS/icons.dm, code/__HELPERS/unsorted.dm, code/controllers/configuration.dm, code/game/area/areas.dm, code/game/machinery/computer/depot.dm, code/game/mecha/working/ripley.dm, code/game/objects/empulse.dm, code/game/objects/explosion.dm, code/game/objects/structures/safe.dm, code/modules/admin/admin.dm, code/modules/buildmode/submodes/link.dm, code/modules/examine/examine.dm, code/modules/flufftext/TextFilters.dm, code/modules/mob/living/carbon/brain/robotic_brain.dm, code/modules/mob/living/simple_animal/hostile/mining_mobs.dm, code/modules/mob/mob.dm, code/modules/paperwork/paper_bundle.dm, code/modules/shuttle/shuttle.dm, config/example/config.txt
This pull request resolves some issues in our code that the compiler doesn't spot, but the [IntelliSense for DreamMaker](https://www.reddit.com/r/SS13/comments/b2204j/announcing_intellisense_for_dreammaker_with_vs/) does.
I've also fixed two config setting names in the example file and added two missing configuration options that were in the file but weren't applied to the game. Also fixes a shuttle warning on start up.
Fixes https://github.com/ParadiseSS13/Paradise/issues/10336.
🆑 Markolie
fix: Fixed some issues the compiler doesn't spot and some start up issues.
/🆑
=> Resolve some issues that the compiler doesn't spot

code/modules/reagents/chemistry/recipes/toxins.dm
Now the plasma won't explode when you make it!
Eventually, this is getting replaced with voltagen.
fix: Fixes Teslium recipe
/:cl:
=> Fixes Teslium Being Unmakeable

code/game/objects/items/weapons/storage/firstaid.dm
I indented too far, thus now allowing you to click drag to open the inventory of the pill bottle. Oops.
fix: Fixes being unable to view pill bottle inventory in some circumstances
/:cl:
=> Fixess Being Unable to Open Pill Bottles

code/datums/helper_datums/hotkey_modes.dm, code/modules/mob/living/silicon/robot/login.dm, interface/interface.dm, interface/skin.dmf
Fixes the toggle hotkey button not working properly. After making the AZERTY change I hadn't tested this properly.
**Changelog:**
:cl: Markolie
fix: An issue where the Hotkey Toggle button wasn't working has been fixed.
/:cl:
=> Fix Hotkey Toggle button

code/game/objects/items/weapons/grenades/flashbang.dm
Flashbangs currently do not stun people, even if they're not wearing any protection (or so I've been told). This pull request fixes that.
**Changelog:**
:cl: Markolie
fix: Fixes flashbangs not working properly.
/:cl:
=> Fixes flashbangs not flashing or banging

code/modules/mob/living/simple_animal/friendly/farm_animals.dm
Fixes goats so they actually retaliate against you and attack you.
Also updates a few things from TG.
- Goats will now eat glowshrooms
- Goats attacking Diona nom their bodyparts
fix: Fixes goats not attacking people
tweak: Goats will eat glowshrooms
add: Goats will eat full grown diona
/:cl:
=> Fixes and Updates Goats

code/game/gamemodes/vampire/vampire_powers.dm
Fixes: #11321
**Changelog:**
:cl:
fix: Vampiric glaring is logged now
/:cl:
=> Vampire glare is logged now

code/game/gamemodes/cult/cult_comms.dm
Fixes #11346
**Changelog:**
:cl: uc_guy
fix: Players in the lobby no longer see cult speak.
/:cl:
=> Players in the lobby no longer see cult speak.

code/modules/reagents/chemistry/reagents/drinks.dm
Fixes the typos in the path
**Changelog:**
:cl:
fix: Doctor delight and orange juice now heal again
/:cl:
=> fixed orange juice and doctordelight not working on ingestion

code/__HELPERS/mobs.dm, code/modules/admin/admin.dm, code/modules/admin/player_panel.dm, code/modules/client/client procs.dm, code/modules/mob/login.dm
Fixes old admin PM's where it would still use the mob instead of the client.
**Changelog:**
:cl:
fix: Fixes admin PM's. Bwoinks are back on the menu!
/:cl:
=> PM's work again

code/modules/clothing/under/miscellaneous.dm
:cl: Fethas
bugfix: Cluwne suits should no longer fall off cluwnes from being fat.
/:cl:
=> Fixes Cluwnes being nudists

code/modules/mob/living/carbon/alien/humanoid/alien_powers.dm, code/modules/mob/mob_grab.dm
Fixes: #11352 
**Changelog:**
:cl:
fix: Devour and regurgitate use forcemove now. So no being buckled inside an alien
/:cl:
=> Force move for regurgitate and devour now

code/game/machinery/telecomms/ntsl2.dm
Fixes a security issue within NTTC. This is why you use sensitisation kids
**Changelog:**
fix: Fixes a minor NTTC issue
/:cl:
=> [S] URGENT

code/controllers/subsystem/jobs.dm, code/game/jobs/job_exp.dm
This PR removes a `while(TRUE)` that didnt have any breaks in it. Kyet is being fired dont worry.
**Changelog:**
tweak: Removes an infinite loop in the code
/:cl:
=> while(TRUE) removes a while(TRUE) loop

code/modules/client/client procs.dm, code/modules/client/preference/preferences.dm
:cl: Kyep
fix: fixed $5+ donors not getting extra loadout points.
/:cl:
=> Fixes $5+ donors not getting extra loadout points

code/modules/reagents/chemistry/recipes/toxins.dm
Fixes https://github.com/ParadiseSS13/Paradise/issues/11532.
**Changelog:**
:cl: Markolie
fix: Rotatium can now be created properly.
/:cl:
=> Rotatium fix

code/modules/paperwork/paper.dm
Fixes an issue that occurs with paper.
**Changelog:**
:cl:
fix: Fixes a paper exploit.
/:cl:
=> Fixes paper.dm issue

code/modules/client/preference/preferences.dm
Some prefs got unalphabetised, this PR fixed that
**Changelog:**
:cl:
tweak: Tweaks some preference orders
/:cl:
=> Re-alphabetises prefs

code/game/objects/items/stacks/stack.dm
See the changelog.
**Changelog:**
:cl: Markolie
fix: An exploit with the sheet multiplier has been fixed.
/:cl:
=> Fixes an exploit with the sheet multiplier

code/game/objects/effects/portals.dm, code/modules/events/wormholes.dm, code/modules/mob/living/simple_animal/bot/construction.dm, code/modules/mob/living/simple_animal/bot/honkbot.dm, code/modules/mob/living/simple_animal/hostile/mining/gutlunch.dm
See the changelog.
Fixes https://github.com/ParadiseSS13/Paradise/issues/11689.
**Changelog:**
:cl: Markolie
fix: Gutlunches will now eat properly.
fix: The tesla can no longer travel through wormholes.
fix: Fixed an issue with honkbot construction.
/:cl:
=> Fix gutlunches not eating and tesla wormhole fix

code/game/mecha/mech_fabricator.dm, code/modules/research/designs/medical_designs.dm
Creates a new medical category to the exosuit fabricator!
Tested locally with no issue.
(This category could also be renamed to cybernetics)
**Changelog:**
:cl:
add: Medical category to exosuit fabricator with implants and cybernetics
/:cl:
=> Fix cybernetics not appearing in mech fabricator

code/modules/research/designs/equipment_designs.dm
fix the Portable Seed Extractor design on the protolathe.
**Changelog:**
:cl:Evankhell
fix: Portable Seed Extractor designon the protolathe.
/:cl:
=> Portable Seed Extractor design

code/modules/admin/topic.dm
Adds auto noting for manual bans because it has angered me long enough.
🆑 
fix: Manual bans now auto-note
/ 🆑
=> Adds Auto-Note for Manual Bans

code/modules/hydroponics/biogenerator.dm
:cl: Kyep
fix: fixed a bug with biogenerator.
/:cl:
Based on: https://github.com/tgstation/tgstation/commit/223e5429ef768fd65ff4402acdc77610e87acfca#diff-cb1200c7109c577cbc379d64d2df58fc
=> Fixes bug with biogenerator

code/__HELPERS/lists.dm, code/datums/helper_datums/input.dm, code/modules/mob/dead/observer/observer.dm, html/browser/autocomplete.js
Adds an autocomplete input. I've only added it to ghost buttons for now, but can expand it to karma awarding, admin things, and other stuff if this seems better.
Fixes #11720
**Images:**
**Changelog:**
:cl: Tayyyyyyy
add: Autocomplete for ghost buttons
/:cl:
=> Autocomplete input

code/modules/food_and_drinks/kitchen_machinery/smartfridge.dm
Smartfridge joins his other vendor comrades and will now try to put an item in your hands after vending, if able and if you chose to vend only 1x item at a time. Also contains minor refactors.
Ported from /tg/station13.
Tested locally without any issue.
**Changelog:**
:cl: Arkatos
tweak: Smartfridge will now try to put an item in your hands after vending, if able
/:cl:
=> Smartfridge gets smarter Mk.3

code/modules/reagents/chemistry/reagents/food.dm
fixes a typo in msg
**Changelog:**
:cl:
fix: typo in msg
/:cl:
=> fix typo in msg reagent

code/game/gamemodes/vampire/vampire.dm
Allows vampires to suck stuff again
Tested and ready
**Changelog:**
:cl:
add: adds a line to alert people as to why they're not getting blood from the monkeys
fix: The vampires are finally off their monkey diet, theycan now suck blood from players and humanized monkeys 
/:cl:
=> Vampire hotfix

code/modules/events/disease_outbreak.dm
Small fix to symptoms not correctly being generated
**Changelog:**
:cl:
fix: Symptoms are now correctly generated for level 7 biohazards
/:cl:
=> Disease rework patch

code/modules/surgery/organs/organ_external.dm
Alright, so here's the deal with bones. Prior to this PR if a limbs damaged exceeded the brute threshold that bone would break. This meant that if you received large amounts of brute damage over multiple limbs you would likely break multiple bones. Which is fine, until you look at the thresholds.
Hands and feet took 15 brute damage to break. If they are broken you are immediately slowed to a crawl or forced to drop what you are holding.
Arms and legs took 30 brute damage to break.
Torso, Head, and groin took 35 brute damage to break.
Someone could toolbox both your hands to essentially pacify you with no counter.
**So what did I change?**
Bones no longer break at the threshold. They start rolling for breakage after the bone has passed the threshold(This is …
=> Bones nerf

code/modules/client/preference/preferences_mysql.dm
fixes #11854 Credit to Fox and Crazy for originally figuring this issue out
**Changelog:**
:cl:
fix: Preferences not saving properly
/:cl:
=> Fix preferences not saving

code/modules/mob/living/simple_animal/hostile/jungle_animals.dm
Changes panthers to be able to see in the dark.  This is likely an oversight as they are rarely used.
:cl:
tweak: Panthers can now see in the dark.
/:cl:
=> Big hostile cats, should be able to see in the dark.

code/modules/mob/mob.dm
🆑Ty-Omaha and DominikPanic
fix: Limits IC notes
/ 🆑
=> [s] Memory is fickle

code/game/atoms.dm
look at the code
🆑
tweak: Gave plastic surgery to line 364 of atoms.dm
/ 🆑
=> Refactors disgusting if statement

code/modules/mob/living/simple_animal/hostile/bees.dm
Fixes #11751 
Basically copied the fix from #11724 
**Changelog:**
:cl:
fix: Bees no longer inject venom when nuzzling
/:cl:
=> Makes bees not inject venom when nuzzling

code/_globalvars/misc.dm, code/modules/admin/admin_verbs.dm, code/modules/client/client procs.dm
:wave:
This PR adds the panic bunker as an admin toggle. Why? Because we have a 200k tubetide coming in about 5 hours.
**Changelog:**
add: Panic Bunker
/:cl:
=> Panic Bunker

_maps/map_files/cyberiad/z2.dmm
Adds a ERT shuttle console which is accessible to ERT members
**Images of sprite/map changes (IF APPLICABLE):**
**Changelog:**
:cl:
add: Adds a ERT shuttle console which is accessible to ERT members
/:cl:
=> Adds a ERT shuttle console which is accessible to ERT members

code/game/turfs/simulated/floor/asteroid.dm
Lavaland might be metal, but not that kind of metal.
fix: Fixes walking on lavaland sounding like walking on metal plating
/:cl:
=> Fixes Lavaland Sounding Like Metal

code/modules/surgery/organs/organ_internal.dm
Honktumors:
Now force you to waddle
Adds the squeak component so you bike horn on move.
Honkbladder:
Silly organ (admin add) that makes you do the clown step noise.
:cl: Fethas
tweak:Upgrades honktumor for more suffering.
/:cl:
=> Upgrades Honktumor, Adds Honkbladder

code/game/turfs/simulated/floor/plating.dm
Title.
**Changelog:**
:cl:
fix: You no longer have to unscrew a plating to repair it.
/:cl:
=> Fixes having to unscrew plating to repair it

code/datums/diseases/advance/symptoms/shivering.dm
Fixes: #12058
Switched a < to a >.
Untested mobile webedit.
**Changelog:**
:cl:
fix: The shivering symptom in virology now properly chills people.
/:cl:
Sent from my iPhone.
=> Shivering should now cool you down properly

code/modules/events/grid_check.dm, code/modules/power/power.dm
Fixes a bug where hotwiring solar panels would allow for power to remain even when the grid check power failure event is active.
**Changelog:**
:cl:
fix: Fixed a bug where hotwiring solar panels would allow for the station to remain powered in the Grid Check power failure event.
/ 🆑
=> Fixes Grid Check

code/modules/projectiles/guns/projectile/saw.dm
I don't even know why or how this  become broken but okay.
Fixes #12069
**Changelog:**
:cl:
fix: You can insert magazines into L6 SAWs again
/:cl:
=> Fixes a bug that prevented you from inserting L6 SAW magazines into the gun

code/game/objects/effects/decals/Cleanable/humans.dm, code/game/objects/effects/decals/Cleanable/misc.dm, code/game/objects/effects/decals/crayon.dm
Fixes blood, graffiti, and fungus from not showing up when on walls
fix: Fixes fungus, blood, and graffiti not showing up on a wall
/:cl:
=> Fixes Blood, Graffiti, and Fungus not Showing Up

code/game/objects/structures/crates_lockers/closets/cardboardbox.dm
Not really that urgent but may as well fix it anyway. credit to TG for the code here
Fixes: #12048 
**Changelog:**
:cl:
fix: cardboard boxes are no longer sonic speed
/:cl:
=> Fix cardboard box walldash

code/game/objects/items/weapons/weaponry.dm
Fixes baseball bats throwing anchored things.
Fixes: https://github.com/ParadiseSS13/Paradise/issues/11907
fix: Fixes baseball bats throwing anchored things
/:cl:
=> Fixes Baseball Bats Throwing Anchored Things

.github/ISSUE_TEMPLATE/bug_report.md
Title. 🤔 
~~AI, deactivate space!~~
=> Adds spacing to the bug_report template

code/game/turfs/simulated/floor/chasm.dm, code/game/turfs/simulated/floor/fancy_floor.dm, code/game/turfs/simulated/floor/indestructible.dm, code/game/turfs/simulated/floor/lava.dm, code/modules/events/spacevine.dm
Fixes `/turf/open` existing/being defined at all. Yikes.
Also fixes some underlays not working
fix: Fixes some turf underlays not working
/:cl:
=> NO THE OPEN TURFS

code/game/atoms.dm, code/game/objects/items/weapons/storage/bible.dm, code/modules/mob/living/carbon/human/emote.dm
Quite possibly, the most important refactor to ever grace Paradise.
Cuts down on snowflake code: ✔️ 
More Object Oriented: ✔️ 
Allows for Expansion of future features: ✔️
Potentially usable for a future needs system: ✔️ 
Makes you question your own existence: ✔️ 
This PR is a total gas, and it would be shame if it would fall flat on its face when such a refactor has the potential to be a total blowout.
Biblefart gibbing is now a form of suicide; should cut down on admin annoyance and properly set the `suiciding` var to `TRUE`
@KasparoVy @FreeStylaLT 
tweak: Refactors the very core and soul of SS13 and enhances the code that powers it
tweak: Bible fartgibbing is now a form of suicide
/:cl:
=> The Most Important Refactor Ever

code/modules/food_and_drinks/food/snacks.dm, code/modules/hydroponics/grown.dm, code/modules/hydroponics/seeds.dm, code/modules/reagents/chemistry/reagents.dm, code/modules/reagents/chemistry/reagents/drink_cold.dm, code/modules/reagents/chemistry/reagents/food.dm, code/modules/reagents/chemistry/reagents/misc.dm, code/modules/reagents/chemistry/reagents/pyrotechnic.dm, code/modules/reagents/chemistry/reagents/toxins.dm, code/modules/reagents/chemistry/reagents/water.dm
Big thanks to @Crazylemon64 for helping me pin down the problem; I was starting to suspect reagents were involved, but I wasn't completely sure, and I doubted myself enough that I ruled it out. 
Either case, this fixes fruit wine causing runtimes and not actually fermenting.
This should also fix some instances of "you taste sweetness, ,and ". For a few null taste reagents. If we want something to not have a taste, it shouldn't be `null`, it should just have a `taste_multiplier` of `0`.
Other:
Implemented some of TG's code for taste (not really functionally different).
fixes: https://github.com/ParadiseSS13/Paradise/issues/12175
fixes: https://github.com/ParadiseSS13/Paradise/issues/12176
fix: Fixes some blank tastes
fix: Fixes not being able to brew fruit wine
/:cl:
=> Fixes Some Null Tastes and Fruit Wine

code/game/objects/structures/tables_racks.dm
GOSH DAMN IT SANITY CHECK YOUR CODE AND DON'T JUST COPY PASTA FROM TG WITHOUT ANY CONTEXT OR IT WILL BITE YOU IN THE BUTT OK.
@Couls 
fix: Fixes poor TG copy pasta code that caused hundreds of runtimes
/:cl:
=> Fixes Who Knows How Many Runtimes

code/modules/economy/ATM.dm
when trying to withdraw any amount, it doubled that amount
fixes #12172
**Changelog:**
:cl:
fix: Fixed ATM withdrawals doubling.
/:cl:
thanks @Citinited
=> Fixes ATM withdrawals

code/modules/clothing/gloves/miscellaneous.dm
Changes a m to a b.
**Changelog:**
:cl:
spellcheck: Fixed a typo in admin gloves of rapidness.
/:cl:
=> Fixes a word

code/modules/reagents/chemistry/reagents/toxins.dm, code/modules/zombie/organs.dm
Fox be silly
no CL as this isn't important for notification on live.
=> Fixes Romerol Reagent Pathing

code/game/turfs/simulated/floor/plating.dm
Welding a tile now gives a more clear message to the user
**Changelog:**
:cl:
tweak: Welding a tile away now gives a more useful message when doing so.
/:cl:
=> Welding a tile away now gives a new message

code/game/machinery/slotmachine.dm
`// .02%`
So you don't have to do it yourself.
(Correct me if I'm wrong, please.)
=> Adds comments with the chance of winning at slots

code/game/machinery/vending.dm, code/modules/arcade/prize_datums.dm
Adds the headpat gloves to the arcade machine prizes as requested in #12189 
:cl:
tweak: Headpat gloves added to arcade machine prizes
/ 🆑
=> Adds headpat gloves to arcade prizes

code/game/gamemodes/miniantags/guardian/guardian.dm
Fixes https://github.com/ParadiseSS13/Paradise/issues/12231.
Yep, I used the web editor for this. I don't have access to my desktop while I'm in the United States.
**Changelog:**
:cl: Markolie
fix: Guardian communciation now longer shows up to players in the lobby.
/:cl:
=> Fix Guardian Communication showing up to players in the lobby

code/modules/customitems/item_defines.dm
Recursive detecting of detective corgis has been detected by the other detecting detective corgi.
Wait, what?
fix: Fixes too much detecting corgis
/:cl:
=> Detect the Detecting Corgi Detective

code/game/mecha/equipment/tools/other_tools.dm
See title & CL
**Changelog:**
:cl:
fix: The gravitational catapult no longer pushes ghosts when used
/:cl:
=> The gravitational catapult no longer pushes ghosts when used

goon/code/datums/browserOutput.dm
adds an autoban for evasion
:cl:
tweak: Minor ban evasion update
/ 🆑
=> Ban evasion autoban 

code/modules/admin/verbs/adminpm.dm, code/modules/admin/verbs/pray.dm
I missed changing CA to TP on files adminpm.dm and pray.dm. I missed those two files, this fixes that.
I was not able to test Syndicate, Honk, or ERT Request but the syntax is easy.
**Changelog:**
:cl: xProlithium
tweak: Altered CA to TP for prayers and adminpms.
/:cl:
=> CA to TP on adminpm and prayers

code/modules/projectiles/guns/energy/special.dm
adds a check
**Changelog:**
:cl:
fix: Plasma cutters will no longer eat plasma if you try recharging a full gun.
/:cl:
=> Fixes plasma cutter being able to eat an infinite amount of plasma

code/__DEFINES/admin.dm, code/modules/client/client defines.dm, code/modules/keybindings/bindings_client.dm, code/modules/keybindings/setup.dm
:cl: Kyep
fix: fixed an issue with keyboard input
/:cl:
https://github.com/tgstation/tgstation/pull/46425
=> Mirrors TG PR 46425

interface/skin.dmf
Fixes #12234 
Fixes good
:cl:
fix: hotkey menu option in the dropdown works correctly now
/:cl:
=> fix hotkey help button

code/__HELPERS/mobs.dm
Moves attacks from mobs targetting themselves to the almost_all level of logging.
Because I don't care about the greytide in brig slowly punching himself to death
:cl:
tweak: lowered attack log level of self-harm
/:cl:
=> Reduces attack log level of self-harm

code/game/gamemodes/blob/blob.dm
makes being a blob give you an audible alert (like traitor)
please, for the love of fuck, suggest better sounds
**Changelog:**
:cl:
tweak: Blobs now get a audio notification roundstart (like traitors do.)
/:cl:
=> Being a blob now gives you a sound notification

code/modules/awaymissions/zlevel.dm
Ports my own PR from TG.
Fixes tendrils spawning inside ruins.
Fixes: https://github.com/ParadiseSS13/Paradise/issues/12257
fix: Fixes tendrils spawning inside ruins
/:cl:
=> Fixes Tendrils Inside Ruins

code/game/objects/items/devices/lightreplacer.dm, code/modules/power/lighting.dm
Fixes light replacers breaking lights/hitting lights twice
fixes: https://github.com/ParadiseSS13/Paradise/issues/12305
fix: Fixes light replacers breaking/hitting lights
/:cl:
=> Fixes Double-Bonking Light Replacer

strings/tips.txt
fixes tip
cause reasons
:cl:
fix: the most grave of wrong tips
/:cl:
=> Fixes wrong tip

code/controllers/subsystem/tickets/tickets.dm
Adds man up to autoreply
🆑 
add: Adds "Man Up" to autoreply
/ 🆑
=> Adds man up to autoreply

code/controllers/subsystem/throwing.dm, code/modules/mob/mob_movement.dm
From TG
See title
Hitting yourself with things you throw isn't really fun for you and it also makes no sense
:cl:
fix: you no longer hit yourself with things you throw
/:cl:
=> thrown objects now phase through the thrower instead of hitting them

code/__DEFINES/math.dm
=> Second Most Important PR
